### ISSUE TITLE
Condition for killing players? (With certain reputation)

### ISSUE THREAD

**Issue by joostdemem** [SmartlyDressedGames/Unturned-3.x-Community#100]
This could be used on rp servers where there are bandit npcs that want you to kill certain player with positive reputation or police officer that wants people with negative reputation dead. The use of a certain weapon could be a condition to, for example: Weapon_Type Explosive or Weapon_ID 133

**Comment by Vulby** [comment]
It may look something like this if added in game

Condition_#_Type Kills_Player
Condition_#_Skillset Type of skillset required by dead player "Fire", "Police", "Army", "Farm", "Fish", "Camp", "Work", "Chef", "Thief" or "Medic".. (Optional Condition)
Condition_#_Rep: 0 to 65535
Condition_#_ID: Short flag to track stat.
Condition_#_Value: Target kills.
