### ISSUE TITLE
[Feature] Ability to get the limb of a mannequin when hit.

### ISSUE THREAD

**Issue by megoesrawr** [SmartlyDressedGames/Unturned-3.x-Community#1001]
The ability to get what a mannequin is wearing when hit by something would be cool. If it's possible, I or other devs could use it for test dummies or combat dummies to test guns damage and stuff.

Or make a new item that does this would be cool too.

**Comment by SDGNelson** [comment]
Perhaps I'm misunderstanding, but can you use the InteractableMannequin shirt/pants/etc variables to get those values?

**Comment by megoesrawr** [comment]
Yea. Sorry. Is there a onhitbarricade event yet?

**Comment by SDGNelson** [comment]
Ah I see, checked the related code and I don't think there's any nice way to do that at the moment, but one option might be:

1. Custom "destructible" object with sections for each damage region
2. listen for damage events on your object type and prevent actually destroying them
3. broadcast the damage info using chat or custom UI

**Comment by megoesrawr** [comment]
Ok. Thanks.

**Comment by SDGNelson** [comment]
Does that always happen? Provider.kick should be showing a message to the client, whereas Provider.dismiss should just let them timeout.

**Comment by megoesrawr** [comment]
Not always. But it seems like every other time.

**Comment by SDGNelson** [comment]
Did some investigation into the kick timeout today, and while I wasn't able to replicate it while, testing I do have a hunch. When kicking, banning, or shutting down the server waits a short period before closing the connection, and those final packets might not have been getting sent in that window because they were in the normal queue. In the next update (on preview this Friday) they should be the final packet sent, and should flush the send queue to the receiving player.

**Comment by SDGNelson** [comment]
Did you notice any difference on this after the 3.19.15.0 update?

**Comment by Johnanater** [comment]
I haven't noticed anymore of those timeouts when kicking myself since the update.

**Comment by SDGNelson** [comment]
@Johnanater Awesome! Thank you for the confirmation. 🎉 

Will close the issue now. Getting this bug fixed likely helped resolve other miscellaneous disconnection issues. Thanks for bringing it up megoesrawr!

**Comment by megoesrawr** [comment]
Did you make an update lately for Unturned? For some reason, when you /kick or /exit from the server, it crashes the server. Here are the error logs: https://pastebin.com/dZmkbYie

**Comment by SDGNelson** [comment]
For the public version not since the Dango update on Sept 20th, but there was an update to the Unity 2018.4 beta last week. It looks like the crash is in mono which should be more stable in the 2018.4 version. Does it happen if you test in vanilla mode?

**Comment by megoesrawr** [comment]
Its fine in vanilla mode, even with mods and no rocketmod. I think its just a plugin issue. Thanks for the help though.

**Comment by SDGNelson** [comment]
Glad that it's working in vanilla, but good luck with the plugin! Another player reported a similar crash so I'm linking them here. Do you have any idea which plugin it is?

**Comment by megoesrawr** [comment]
Im sure its one of Imperials.

**Comment by Trojaner** [comment]
If you know which plugin from ImperialPlugins causes it, feel free to contact me on our discord server
