### ISSUE TITLE
One more byte array with metadata for items

### ISSUE THREAD

**Issue by Jerico97** [SmartlyDressedGames/Unturned-3.x-Community#1004]
I think it's nice feature to add and save item information like gun owner or amount of repairs

**Comment by Adamv21** [comment]
I think something like NBT tags would be more useful? Only a Dictionary<string, object>. It would possibly corrupt files tho, dont quote me on that.

**Comment by Charterino** [comment]
How can you know who's the owner? Who firsly picked it up?

**Comment by SDGNelson** [comment]
This would be a great feature to have, but is unlikely to happen: looking through the amount of code that deals with items not to mention breaking plugin code is huge.
