### ISSUE TITLE
Some [Parameter Suggestions]

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1007]
**Hi**

- Parameter for Ignore Errors . This parameter can Apply for anything helps out to remove the list of errors that the game recommande you example Ballistic range 3

![small thing](https://user-images.githubusercontent.com/40163506/62983830-28481b80-be31-11e9-93a2-f87b2789cee5.JPG)

Parameter
_Ignore_Errors_ true & false

- Parameter To Endless Ammo magazine. By auto re charge the ammo with out having another one , to help not having alot of magazines that will help  my work alot

Paramter
 _Auto_Ammo_ true & flase

**Comment by SDGNelson** [comment]
Why not fix the ballistic mismatch issue? The problem is that those items have two ranges defined.

**Comment by BREEZEXPVP** [comment]
it's been fixed i didnt now what problem came from , thanks
