### ISSUE TITLE
Maplestrike Bug

### ISSUE THREAD

**Issue by nausofficial** [SmartlyDressedGames/Unturned-3.x-Community#1010]
Maplestrike is not reloadable.
This bug is available in version 3.30.6.0

**Comment by PandahutMiku** [comment]
It appears Nelson was testing one of the new flags he added this update and accidentally left

"Allow_Magazine_Change False" inside of the Maplestrike.dat

**Comment by nausofficial** [comment]
You are right, it definitely works.

**Comment by SDGNelson** [comment]
Gosh I'm not sure how this snuck in. Typically I make these one-liner edits and revert the change prior to committing, but I messed up. Will upload a tiny patch to revert that...
