### ISSUE TITLE
i use CommandInputHandler cant print game output,just has Console.writ;

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1015]
CommandWindow   commandWindow = new CommandWindow();
ThreadedWindowsConsoleInputOutput windowsConsoleInputOutput = new ThreadedWindowsConsoleInputOutput();
commandWindow.setIOHandler(windowsConsoleInputOutput);

i cant put any key in this Console.

**Comment by HanaForward** [comment]
just can print rocket log

**Comment by RoyIL** [comment]
This is not a plug-in development support page for kids, do you know how to actually Google stuff?

**Comment by SDGNelson** [comment]
For custom IO handlers the intention is to access the command window instance from Dedicator.commandWindow. Are you just trying to enable the threaded console though? It's now enabled by default.

**Comment by HanaForward** [comment]
> For custom IO handlers the intention is to access the command window instance from Dedicator.commandWindow. Are you just trying to enable the threaded console though? It's now enabled by default.

no , i I want to use my own console so he can support utf8 encoding.

**Comment by SDGNelson** [comment]
Ah, okay. In that case you can create your IO instance and then call Dedicator.commandWindow.setIOHandler. Currently the vanilla game uses the default Console.InputEncoding and Console.OutputEncoding which is probably wchar_t on Windows.

**Comment by HanaForward** [comment]
> 啊好吧。在这种情况下，您可以创建IO实例，然后调用Dedicator.commandWindow.setIOHandler。目前，vanilla游戏使用默认的Console.InputEncoding和Console.OutputEncoding，它可能是Windows上的wchar_t。



> Ah, okay. In that case you can create your IO instance and then call Dedicator.commandWindow.setIOHandler. Currently the vanilla game uses the default Console.InputEncoding and Console.OutputEncoding which is probably wchar_t on Windows.

Think you very much
