### ISSUE TITLE
Russian localization of Windows breaks the crash window

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#1017]
Sent to me by a player.
![image](https://user-images.githubusercontent.com/1404955/63281690-e9451a80-c2b5-11e9-90a4-4823ae1a4c27.png)
Pressing 'Yes' causes this to happen:
![image](https://user-images.githubusercontent.com/1404955/63281706-f2ce8280-c2b5-11e9-9e39-c63b29adcc11.png)
Gibberish/wrong encoding when the User is in Cyrillic instead of Latin.

**Comment by Trojaner** [comment]
This is a Unity problem, I don't think Nelson can do anything about it

**Comment by SDGNelson** [comment]
Sorry for the issue, but Trojaner is correct that this is the Unity built-in crash reporter.
