### ISSUE TITLE
[FEATURE REQUEST] Stat Modifier Volume

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1019]
A volume that affects a specific stat when inside. Can be set to either Additive or Subtractive. Can affect Health, Energy, Immunity, Food, Water and Oxygen. Tick-rate can be set per volume.

Possible use cases: 
- A location devoid of breathable air, forcing players to move quickly or invest in additional breathing equipment. Perhaps could also be combined with a Deadzone, creating an even more dangerous environment. 
- A vent underwater providing oxygen, allowing for prolonged underwater trips.
- Volumes in out-of-map locations (Like Kuwait's Outlands or Elver's Final quest) that provides Food and Water, so players don't starve if they come ill-equipped for a long visit.
- Zones in arena maps that provide passive health regeneration, perhaps creating more conflict in certain areas, as players try to secure this resource

**Comment by Spebby** [comment]
I was thinking about this suggestion the other day when considering how Oxygen Volumes could be used on maps to create more deadly deadzones with a hard time limit that can't be circumvented with bringing extra filters. While thinking about that, I also remembered the time I died in Kuwait's Outlands due to not having enough water. The more I thought about it, the more it seemed like a better idea to have a generic stat affecting volume, rather than the inflexible oxygen addition/reduction volume. Map makers have also been requesting "Hurt Volumes" for awhile now, this would likely fit that criteria?

**Comment by Spebby** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1184

**Comment by Spebby** [comment]
partly added with the addition of Oxygen volumes.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
