### ISSUE TITLE
Nelson , my effectUI cant display,I do not know why

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1021]
unity version : 2019.2.1f1
i create 2D project . and add GameObject-Image.
modify Canvas to Effect 
bundle tool  -  Grab  - Effect

in plug
 EffectManager.sendUIEffect(45010, 5, player.CSteamID, false);

but not display

**Comment by HanaForward** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1842010997

MODID 1842010997

**Comment by HanaForward** [comment]
Effect.dat ：
GUID 214c4d1589f24dd9a9972434ad9025ec

Type Effect
ID 45010
Lifetime 60

**Comment by Alex-Well** [comment]
You are using the wrong version of Unity, and you may also have done something wrong.

**Comment by educatalan02** [comment]
If It's made with  BundleTool you need to include "Exclude_From_Master_Bundle" or something like this.

**Comment by HanaForward** [comment]
> You are using the wrong version of Unity, and you may also have done something wrong.
I used the example of others as well.
I will try to use the old unity version
