### ISSUE TITLE
Can't take maplestrike

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1022]
On my server after last update players can't pick maplestrake in hands.

**Comment by PandahutMiku** [comment]
Make sure your server is updated, Nelson released a patch for the maplestrike to fix an issue where it was accidentally made unreloadable without requiring the update for the server/client. If both your client and the server are fully updated, you should have zero issues taking it out. 

You should also be able to see if the server is updated by seeing if the server's Maplestrike.dat (Unturned\Bundles\Items\Guns\Maplestrike) has the line `Allow_Magazine_Change False` in it. If it does, the server needs to be updated.

**Comment by Greenorine** [comment]
Thanks so much =)
