### ISSUE TITLE
Suggestion for an update of gun pickup

### ISSUE THREAD

**Issue by shadegn** [SmartlyDressedGames/Unturned-3.x-Community#1023]
Hey! I've got reports from my arena server players, it is annoying to fast run & pickup a gun, but it gets to the (left) first hand.
It becomes annoying when it's a small gun, then you find a big gun like maplestrike, and it gets to your inventory, instead of your hand because of this "feature".
So my suggestion in the name of my players.. to make small guns like scalar to get picked up(if empty) to the other "hand", which doesnt allow bigger guns to use.

It is not neccessary, not a "must", just a simple suggestion which would make the playtime more enjoyable for some ppl.

**Comment by SDGNelson** [comment]
I'm not sure if this was how it was before some of the slot changes, but it makes sense to prioritize the secondary slot for secondaries. Will fix for the next update.
