### ISSUE TITLE
Glitch under map in vanilla

### ISSUE THREAD

**Issue by shadegn** [SmartlyDressedGames/Unturned-3.x-Community#1024]
https://www.youtube.com/watch?v=Qyiv4ZgnV4A

One of my players asked me to report this vanilla glitch, a way to get under map, way too easy.
Not sure if you can fix it, but i feel like it's always better to report things like that.

**Comment by SDGNelson** [comment]
This issue's been frustratingly back-and-forth across versions for years, and though the game tries to prevent situations like that e.g. prevent opening the doors the best solution was a new flag for character movement added last year. Here's the comment I have in the code right now:

	// Overlap recovery tries to force character's capsule out of
	// rigidbodies that it overlaps which might be fine in singleplayer,
	// but is inevitable in multiplayer. Often players abused overlaps
	// to teleport through walls and the like, so it's important to disable.
	//
	// Edit: Sadly there are issues when walking toward slopes that bend inward,
	// so we have to re-enable this for now. To test if it works in the future,
	// walk toward the inside of a barracks building in PEI base.
	controller.enableOverlapRecovery = true;

My current hope is to test disabling overlap recovery again when/if we update to 2018.4 LTS in Sept/Oct.
