### ISSUE TITLE
Map Error | Map Editor [ Please help ] 

### ISSUE THREAD

**Issue by karatelg** [SmartlyDressedGames/Unturned-3.x-Community#1025]
Sorry for my English, I use a translator.
I recently edited a map and saved it. Later I went out and tried to go back to the editor. But could not. Download freezes in one place. In a single player game, in the editor, int the the devkit, you can’t enter everywhere.
I found the trouble - this is because of the object.dat file. I deleted it and went into the game and I managed to go into the editor. But there were no objects, respectively. When I returned the file, I could not enter the game. Please, Nelson, you are a good guy. If you read this, please help me. I do not want to lose what I built for a very long time. Screenshots attached below and object.dat also attached below

![image](https://user-images.githubusercontent.com/52929598/63637192-6c81ba00-c682-11e9-9058-4a977d0f66fa.png)
[Objects.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3537166/Objects.zip)
![image](https://user-images.githubusercontent.com/52929598/63637207-bb2f5400-c682-11e9-81b1-ef2c253d6098.png)
![image](https://user-images.githubusercontent.com/52929598/63637212-bff40800-c682-11e9-94dc-c40562f16852.png)

**Comment by karatelg** [comment]
[Objects.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3537171/Objects.zip)

**Comment by Trojaner** [comment]
Can you post your log?

**Comment by karatelg** [comment]
[UnityDebug_Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3537207/UnityDebug_Client.log)

This?

**Comment by karatelg** [comment]
> Can you post your log?
I run the game without mods

**Comment by SDGNelson** [comment]
That looks incredible! Sorry for the bug. It looks like what happened is some objects are far outside the level, and cause index out of bounds when loading. I've fixed this and some other related code for the next update, but in the meantime here's a re-saved copy of the file which should load. There are some objects clamped at max +X min -Y so I'd suggest flying over there to delete them.
[FixedObjects.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3537356/FixedObjects.zip)

**Comment by HanaForward** [comment]
@SDGNelson  
Objects.dat
What is in it?
I hope you can answer it.

**Comment by SDGNelson** [comment]
@HanaForward The Objects.dat file in the Level folder, which is what karatelg send over, contains a list of all the models placed into the map with their positions, rotations, scale, etc. The server Objects.dat is saved by ObjectManager and tracks their per-instance state e.g. how much water in a water tower.

**Comment by HanaForward** [comment]
> @HanaForward The Objects.dat file in the Level folder, which is what karatelg send over, contains a list of all the models placed into the map with their positions, rotations, scale, etc. The server Objects.dat is saved by ObjectManager and tracks their per-instance state e.g. how much water in a water tower.

think you , SDGNelson

**Comment by karatelg** [comment]
@SDGNelson 

Hello, Nelson. Thank you. Your Fix helped me go to the editor. But the following problem happened. I put your file and decided to go into a single player game. And still I can not do it. Download stops. Sorry to ask you to help, but the Russian community could not help me. The fate of the project depends on your help.
To be sure, I deleted all the mods and also tried to go to the map. But in logs it was spammed:
BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.

I attach a screenshot and, if necessary, my favorite, but so problematic map. Maybe this will help.
https://dropmefiles.com/9NXcu - MAP
![image](https://user-images.githubusercontent.com/52929598/63654389-4d6a5180-c782-11e9-9473-95e33e993ed8.png)

**Comment by karatelg** [comment]
@SDGNelson 
I think the error is again in the object.dat file
I deleted it and was able to go into a single player game. I don’t understand what happened now :(((((

**Comment by SDGNelson** [comment]
It should be safe to continue editing the map in the level editor, but until the next patch there is a similar out-of-bounds error while playing the map. I just double-checked with the fixed objects file and it loads properly in the next version.

**Comment by SDGNelson** [comment]
Sorry for the long period, but there is some good news: it's looking like the next version with these fixes should be up on the preview branch on the 6th.
