### ISSUE TITLE
Advanced modding, Part Two (Synchronization between clients)

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1026]
Part One #992 

(Sorry for my English)
Hello, here I would like to reason and get answers to questions that no one likely asked before me.
As we know, for the collision and physics to work correctly, most standard objects have a Clip prefab which contains components related to physics. However, the principle of operation and purpose are not completely clear to me. I also had a question: can I add other components that are not related to physics and how can I use them?
Moving a bit away from this question, I thought: Can physics even affect GameObject in the same way for different clients if the prefab Clip does not bind it? (Probably not clearly expressed)
Experimenting, I created a Constant Force component in Vehicle prefab which, when activated, pushed my car up. This component was included ONLY on the client side using the UI button. At the same time, this component was not in the prefab Clip.
When testing on the server, I recorded a parasitic result! When I tested before with object appearances and animations, they worked ONLY for the player who activated them. However, Constant Force, as usual, was activated for only one player, however, it influenced the machine and both players saw it on the server! It was noteworthy that if the player who activated the Constant Force left the car, then the car stopped moving.
From this experiment it follows that some functions in the game that are activated only on the client side of one player can indirectly affect other functions, which in turn are activated for all players on the server!
Actually, this was the basis of my plan for implementing physical input which, through a common function, CollisionEventHook, could transmit events such as OnClick to all players on the server. This would allow a standard way to expand the modding capabilities in Unturned 3.0. However, as I wrote earlier, I ran into a problem and very much please pay attention to #984 there I even recorded a video demonstration with the CollisionEventHook working incorrectly and for this I really look forward to correcting its work!

**Comment by SDGNelson** [comment]
The reason that your clientside Constant Force component worked correctly in multiplayer is that most vehicles use client authoritative physics aside from a few checks serverside. For example if the force were strongly pushing the vehicle upward the server would rubberband the vehicle downward, but as long as it's considered "reasonable" for the vehicle's speed value it will work.

**Comment by Alex-Well** [comment]
Sorry, I also wanted to know how Clip works. Can it somehow be used not only to track collisions with the collider of an object?

**Comment by SDGNelson** [comment]
For vehicles and objects the Clip prefab is only loaded and spawned on the server. It doesn't have any particular special purpose, and is usually identical to the client version but with audio/visuals components removed.

I think I initially chose the name "Clip" from past experience making maps in the Source engine where you manually refine many props collision with clipping brushes. Nowadays I would probably do away with it entirely, and instead have the game find/destroy certain components... Maybe a future update!

**Comment by LeoBlanchette** [comment]
Has_Clip_Prefab False is now an option. Is this a replacement for creating a clip prefab?
