### ISSUE TITLE
How to make ambient sound for unturned?

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1029]
I can't make ambient audio sound effect. I making just sound with 3D radius and it sounds at all map when should be in effect node.

**Comment by baranmod** [comment]
set spatial blend to 3d

**Comment by Greenorine** [comment]
Thanks, will test =)

**Comment by Greenorine** [comment]
> 
> 
> set spatial blend to 3d

Made spatial blend to 3e and it haven't any sounds ingame.

**Comment by baranmod** [comment]
can you drop a screenshot on how it looks in unity editor?

**Comment by Greenorine** [comment]
![изображение](https://user-images.githubusercontent.com/41028671/63685629-4b070680-c819-11e9-8c49-4f8cb4c17f55.png)

**Comment by baranmod** [comment]
set spatial blend to 1, increase distance and volume (probably thats why you don't hear)

**Comment by Greenorine** [comment]
If I will test with spatial blend 1 it hasn't sound

**Comment by Greenorine** [comment]
if I'll make spatial blend 0 it will audible at all map.

**Comment by Greenorine** [comment]
If spatial blend is 3D and volume is 1 is audible but sooo quietly

**Comment by baranmod** [comment]
if you making ambient sound for map - its done in a different way (you need ambient bundle with all ambient sounds in it (day,night etc). If you want to use it on some specific zone - you create effect and configure audio source something like that: 
![image](https://user-images.githubusercontent.com/14231707/63686438-89e19000-c80a-11e9-99d0-57015aaba6a3.png)

**Comment by Greenorine** [comment]
Ok, will try one more time.

**Comment by SDGNelson** [comment]
Thanks baranmod!
