### ISSUE TITLE
Problem: the player can make the server slow.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#103]
**The player can load the server using a macro.** He does a lot of clicks in 1 second and presses on the pumping skills, and at this stage the server starts to lag far behind.
Well for example, to put a macro on a click
And pumping skills, for example, at 5000 clicks per second.

**Comment by SDGNelson** [comment]
What do you mean by pumping skills - upgrading/leveling up a skill?

**Comment by VitaxaRusModding** [comment]
I already wrote a plugin for this garbage that kicks players.
We have tried many times to help you, but you do not multithread, look for the problem yourself.
Or roll 3.0 and make 4.0
Will server of 3.0 ever use more than 1 processor core?
================================================
I write from all the guys who understand the code.

**Comment by Trojaner25** [comment]
Unity API's are only accessible from main thread

**Comment by VitaxaRusModding** [comment]
https://www.assetstore.unity3d.com/en/#!/content/66960

**Comment by Trojaner25** [comment]
`All of these complex tasks will spend a lot of time on processing, and not possible to be done at runtime since Unity does not have support for Multi-Threaded programming. `

What I have written still applies...

**Comment by yegac1337** [comment]
Speaking of server lag, Maybe you could fix server crashing if you want to put the time into fixing 3.0's hacker problem.

**Comment by SDGNelson** [comment]
Trojaner's correct. I suspect that plugin just facilitates spreading game thread requests across multiple frames from a separate thread, e.g. game logic thread requests spawning 1,000 gameobjects which the plugin spawns on the main thread 200 per frame.

**Comment by SDGNelson** [comment]
In the next update I've added a method tryToPerformRateLimitedAction to the Player class which should be checked before client->server requests:

https://i.imgur.com/5k9mVMh.png
