### ISSUE TITLE
Add "quest conditions updated" event

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1031]

**Comment by SDGNelson** [comment]
What use do you have in mind? Depending what conditions you need this event would be getting called quite a bit, so I'm curious what you need it for.

**Comment by Sl4vP0weR** [comment]
Send UI effect on "quest conditions updated"

**Comment by SDGNelson** [comment]
Like send a UI effect when the tracked quest makes progress towards completion? e.g. 1/5 zombies killed, 2/5 zombies killed

**Comment by Sl4vP0weR** [comment]
This is what I meant

**Comment by SDGNelson** [comment]
Added the onAnyFlagChanged event to the quests class which is the main thing required. All NPC progress is tracked using those, so it's triggered when kills are acquired, quests are completed, objects are activated, etc.
