### ISSUE TITLE
[FEATURE REQUEST] Config Overrides being Prioritized over Server Settings.

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1034]
Currently, Config Overrides aren't prioritised over Server Settings when it comes to Item, Vehicle, Resource, Zombie & Animal Spawn/Despawn times. Server instead uses it's own Respawn times, this could break some maps that require specific Config Overrides to function as intended.

**Comment by PandahutMiku** [comment]
This could prevent Servers from changing options of maps to their will, I would recommend doing what Unturnov plans to do about this, just including an example/default config.json inside of the Workshop Item itself for Servers to use.

**Comment by SDGNelson** [comment]
Right now there aren't any restrictions in place on which values can be overridden by maps, if you check the UnityDebug_Client.log file do you see any warnings about the level config overrides? (e.g. failed to find config)

**Comment by Spebby** [comment]
The config works in single-player, but once I tamper with Single-Player "Advanced" settings or a Server Config the config overrides get ignored.

**Comment by SDGNelson** [comment]
Double-checked and it looks like it applies in the correct order on a server, did it work when you tested it yesterday?

**Comment by Spebby** [comment]
Yeah, it did, it appears that it doesn't always work on singleplayer?
