### ISSUE TITLE
Debug logs errors

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1035]
![image](https://user-images.githubusercontent.com/13141042/64069602-19dd6a80-cc4d-11e9-87e9-cac092d3f523.png)
and then my server it close

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/64070789-8e72d200-cc6a-11e9-90df-062a7a562b6c.png)

**Comment by Trojaner** [comment]
None of these are errors

**Comment by TH3AL3X** [comment]
> None of these are errors

And why my server it close

**Comment by SDGNelson** [comment]
If you can share the UnityDebug_Server_XYZ.log file from the Logs folder it may become apparent, but Trojaner is right that the messages in the images are general verbose output.

**Comment by TH3AL3X** [comment]
Now it works without using the docker, but it seems weird because before I had a problem where people disconnected en masse but I saw a post where you said you had fixed it, then reinstall the unturned and now the server does not appear and nobody can connect , I have the ports open

**Comment by TH3AL3X** [comment]
[UnityDebug_Server_servidor.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3580210/UnityDebug_Server_servidor.log)

**Comment by SDGNelson** [comment]
Only error reported in that log is some plugin using OnPlayerConnected, but that shouldn't be an issue since it's related to Unity's built-in networking unused by Unturned. Advertising on the server list can be finicky sometimes, but as long as 27015, 27016, 27017 are open it should eventually show up.

**Comment by TH3AL3X** [comment]
For some reasons, port 27015 does not work, but with others it does ...
