### ISSUE TITLE
Voice Sending Event

### ISSUE THREAD

**Issue by Pigeon-cmd** [SmartlyDressedGames/Unturned-3.x-Community#1036]
It would be nice if we had more control over the voice system, starting with a simple event for OnServerSendVoice with parameters like a modifiable list of the players receiving, ref bool to cancel.

**Comment by SDGNelson** [comment]
Makes sense, will add. For the meantime the PlayerVoice.allowVoiceChat field is intended for plugin muting.

**Comment by Pigeon-cmd** [comment]
Sorry, I don't mean to be impatient, but any update on this or idea when these suggestions would be implemented? 

Thanks for your time

**Comment by SDGNelson** [comment]
For 3.0 the most recent updates time was focused on changes for Dango, and then on the next 4.0 update for the 27th.

My next focus for 3.0 will be seeing about updating to Unity 2018.4, but several smaller feature requests like this should make it into that update.

**Comment by SDGNelson** [comment]
This has been added for the next update:

1. Bind onRelayVoice to your handler. This determines whether the speaker is allowed to talk, whether the packet should use "radio mode", and to set a culling handler.

2. If culling handler is set it will be invoked for each eligible listener. If not it will fallback to handleRelayVoiceCulling_RadioFrequency or handleRelayVoiceCulling_Proximity.
