### ISSUE TITLE
Nelson/gameObject information

### ISSUE THREAD

**Issue by Ziiyqol-coder** [SmartlyDressedGames/Unturned-3.x-Community#1040]
@SDGNelson how can we solve a problem with items ? Server have only information about items but dont have a gameObject of those items

**Comment by SDGNelson** [comment]
For performance reasons the server doesn't spawn any game objects for items, instead tracking a few details with the ItemData class. If you only need to associate some info while the item is on the ground you could use a dictionary using the instance ID as a key, but once the items are in players inventories there's unfortunately no per-instance storage. One workaround may be to use harmony to patch in an extra field, but that's outside my know-how.

(Also answered 1008)
