### ISSUE TITLE
Server Crashing. Better logs?

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1042]
Hey,

Recently my server has been crashing every 24-48h with this error log
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3575992/error.log)

Is there anyone someone could tell me what was causing the crash? I heard it was quite difficult to track crashes with unturned's current logging and I was told to ask if there is a possibility that a better logging system could be implemented onto servers so we can see what causes the crashes

Thanks!

**Comment by Trojaner** [comment]
Whoever told you that it needs better logging doesn't know how to analyze crash dumps. Any useful information is saved in these.

If you send the .dmp file we can figure out what crashed it.

**Comment by Bradler26** [comment]
Heres the crash file. I'm not saying it can be fixed by nelson I just need an easy way to find what causes it so I can fix it. 
[crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3576327/crash.zip)

**Comment by Trojaner** [comment]
> >	UnityPlayer.dll!physx::PxsBroadPhaseContextSap::batchUpdateFewUpdates(unsigned int,struct physx::PxcBroadPhasePair * &,unsigned int &,unsigned int &)	Unbekannt
 	UnityPlayer.dll!physx::BroadPhaseBatchUpdateWorkTask::runInternal(void)	Unbekannt
 	UnityPlayer.dll!physx::PxsBroadPhaseContextSap::updatePPU(class physx::PxBaseTask *)	Unbekannt
 	UnityPlayer.dll!physx::Cm::BaseTask::run(void)	Unbekannt
 	UnityPlayer.dll!PhysxJobFunc()	Unbekannt
 	UnityPlayer.dll!JobQueue::Exec(struct JobInfo *,__int64,int)	Unbekannt
 	UnityPlayer.dll!JobQueue::ExecuteOneJob(void)	Unbekannt
 	UnityPlayer.dll!CompletionTask::ProcessAllPhysicsTasks(void)	Unbekannt
 	UnityPlayer.dll!PhysicsManager::Simulate(float)	Unbekannt
 	UnityPlayer.dll!PlayerLoop(void)	Unbekannt
 	UnityPlayer.dll!PerformMainLoop()	Unbekannt
 	UnityPlayer.dll!MainMessageLoop()	Unbekannt
 	UnityPlayer.dll!UnityMainImpl(struct HINSTANCE__ *,struct HINSTANCE__ *,wchar_t *,int)	Unbekannt
 	UnityPlayer.dll!UnityMain()	Unbekannt
 	[Möglicherweise fehlen Frames, keine Binärdatei für "Unturned.exe" geladen]	
 	[Externer Code]	

It is the same crash as you have [reported earlier](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/764#issuecomment-508436115)

**Comment by Bradler26** [comment]
So for now my best bet is to wait for unity 2018?

**Comment by Trojaner** [comment]
Yes

**Comment by Trojaner** [comment]
The crash might be related to AABB code, so bad colliders might cause it.
I pretty sure a workshop mod is reponsible for this.

**Comment by SDGNelson** [comment]
Thanks for grabbing the stack trace from the dump Trojaner!
Only useful info I have here is to ask if that's 24-48 hours of running without restart? Server program (not OS) should probably be restarted every 24 hours or so to avoid floating point time precision loss - even Unreal engine is still working on phasing away from bugs related to that.

**Comment by Bradler26** [comment]
It includes a restart about every 12h
