### ISSUE TITLE
Set limit of vehicle speed

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1048]

**Comment by SDGNelson** [comment]
As in change the max speed of the vehicle from the server side dynamically? What do you have in mind?

**Comment by educatalan02** [comment]
It would be good if you can change serverside vehicle speed for each vehicle for eg. Making a plugin which you can make speed upgrade for black sedan. And the same for other vehicles.

**Comment by Sl4vP0weR** [comment]
@SDGNelson
