### ISSUE TITLE
Nelson, please tell us about the future of modding in Unturned 3.0.

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1049]
Over the course of several months, I asked very unusual questions and suggested ideas that would help the development of Unturned 3.0. Many thanks to Nelson for following this and expressing his ideas. However, the further fate of some very interesting ideas remained unclear. Here I would like to summarize and clearly understand what awaits us in the future, and what remains in our fantasies.

1. The fate of CollisionEventHook, as Nelson recently wrote, in a couple of months he plans to clean up the game code, which in theory will correct the principle of its operation. However, this topic did not receive a note: Planned for a future update. Is there a risk that everything will remain the same and we will never receive the long-awaited correction?

2. New ModHooks, as Nelson wrote, the ModHooks I offer go beyond modding in Unturned 3.0, but does this really mean that our favorite game has finished developing in this direction and there will be only three ModHooks in it? !!!
(If this is not so, then I advise you to take a closer look at my Varants, they would really become very useful, and most importantly, they are made almost like standard scripts in the game, it remains only to adapt them to MoodHook.)

3. In this comment https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/992#issuecomment-519678547, Nelson suggested a slightly obscure, but amazing system that I would allow to improve the content for Unturned 3.0 many times. However, we still did not receive an answer that would make it clear: Will it be in the game and how quickly will it appear?

4. Are there any other innovations planned related to modding that we do not yet know about?

**Comment by Pigeon-cmd** [comment]
Nelson is focusing more on Unturned II and not 3.0. Why put tons of work into a game which will be completely obsolete in ~1-2 years when Unturned II launches? 

A lot of things you have repeatedly suggested can simply be done with Plugins and Harmony, use them to spawn effects for all players or specific clients.

**Comment by Sl4vP0weR** [comment]
> Nelson is focusing more on Unturned II and not 3.0. Why put tons of work into a game which will be completely obsolete in ~1-2 years when Unturned II launches?
> 
> A lot of things you have repeatedly suggested can simply be done with Plugins and Harmony, use them to spawn effects for all players or specific clients. Look into Rocket Plugins.
> 
> Ultimately, I think it's kind of hard for Nelson to justify putting time away from II to work on a feature for 3.0 which can already be done with Plugins and would only be very minorly used.

Yes, you're right, but 1-2 years is not a short time, maybe 50% of the community will not want to go to Unturned II

**Comment by Pigeon-cmd** [comment]
> > Nelson is focusing more on Unturned II and not 3.0. Why put tons of work into a game which will be completely obsolete in ~1-2 years when Unturned II launches?
> > A lot of things you have repeatedly suggested can simply be done with Plugins and Harmony, use them to spawn effects for all players or specific clients. Look into Rocket Plugins.
> > Ultimately, I think it's kind of hard for Nelson to justify putting time away from II to work on a feature for 3.0 which can already be done with Plugins and would only be very minorly used.
> 
> Yes, you're right, but 1-2 years is not a short time, maybe 50% of the community will not want to go to Unturned II

I heavily disagree with the idea that "maybe 50% of the community will not to go Unturned II", it's panning out to support all of the things 3.0 does, better performance, better networking, and trying to go back to the roots of unturned.

Regardless, the point was just that you can do what you are suggesting with plugins in most cases. for example you can use Advanced Zones (https://harbor.rocketmod.net/plugins/advancedzones/), make a zone for it, then in your own plugin just hook onto "AdvancedZones.AdvancedZones.onZoneEnter" and send an effect to the player himself or all players.

**Comment by Sl4vP0weR** [comment]
![image](https://user-images.githubusercontent.com/42337892/64483524-a2ec3700-d235-11e9-9c35-fed26f6180c4.png)

**Comment by Alex-Well** [comment]
> > > Nelson is focusing more on Unturned II and not 3.0. Why put tons of work into a game which will be completely obsolete in ~1-2 years when Unturned II launches?
> > > A lot of things you have repeatedly suggested can simply be done with Plugins and Harmony, use them to spawn effects for all players or specific clients. Look into Rocket Plugins.
> > > Ultimately, I think it's kind of hard for Nelson to justify putting time away from II to work on a feature for 3.0 which can already be done with Plugins and would only be very minorly used.
> > 
> > 
> > Yes, you're right, but 1-2 years is not a short time, maybe 50% of the community will not want to go to Unturned II
> 
> I heavily disagree with the idea that "maybe 50% of the community will not to go Unturned II", it's panning out to support all of the things 3.0 does, better performance, better networking, and trying to go back to the roots of unturned.
> 
> Regardless, the point was just that you can do what you are suggesting with plugins in most cases. for example you can use Advanced Zones (https://harbor.rocketmod.net/plugins/advancedzones/), make a zone for it, then in your own plugin just hook onto "AdvancedZones.AdvancedZones.onZoneEnter" and send an effect to the player himself or all players.
> 
> I just don't think it's realistic to keep asking for these things for workshop items to use that would only be slightly used and distract from II. Of course, this is just my opinion.

Well, then can I use the plugin to disable the GameObject I need in the object hierarchy? If not, then my suggestions are really important and relevant.

**Comment by SDGNelson** [comment]
Right now there are a couple higher priority updates to tackle like looking into updating to Unity 2018 LTS, but after that doing some netcode rewrites is on my radar. Improving network features will help modding in a couple major ways, two of them being significantly more control for custom UIs and more possibilities for "modhooks".

Currently points 1, 2 and 3 in the OP are limited for network-related reasons (e.g. proposed modhooks depend on replication), so I think provided that network changes are made reasonable expectations for modhook improvements in the future are warranted.

**Comment by Alex-Well** [comment]
Then I will look forward to the transition of the game to the new version of Unity and the subsequent code change that will add / fix these items. However, even now I have another idea and I will continue to look for a way out of the situation) Maybe soon I will make a test version to show the Unturned community what can be implemented in the game right now. (Although on the client side)

**Comment by SDGNelson** [comment]
Everything mostly pends on #1233, but I do expect the chat message request will be implemented at some point. Curious to see what your test turns out to be! Closing, but feel free to comment and I'll re-open.
