### ISSUE TITLE
Light speed, ridiculous speed, ludicrous speed. Give 'em all

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#105]
First of all, thanks for the gravity steam call and bugged `sendPluginGravityMultiplier` (tellRecov huh?)

Back to the topic: would be awesome to be able to set **the speed** in a similar way (modifier). That would allow to apply cripple effects or temporary speed boosts (actually, you could make Adrenaline apply speed boost)

**Comment by baranmod** [comment]
Sounds cool. Also, curious if its possible to add ability to set similar multipliers on workshop items? Like setting 1.0 gravity on light weight items and 1.5 gravity for heavier items for example. Same for speed, etc.

**Comment by SDGNelson** [comment]
Added an RPC to set the speed multiplier similar to gravity. Per-item speed multipliers will be in 4, but probably not 3.
