### ISSUE TITLE
[FEATURE REQUEST] Off-Season Objects/Resources

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1051]
Add the ability to create objects that disappear on the start of certain seasons. Would be useful on a map where certain cover gets replaced with Spooky Coffins or Jolly Snowmen. 

In terms of Off-Season Resources, a snowy part of the map could lose most or all of its snow during non-winter months. Certain trees could also shed leaves during fall/winter months. However, this would require the game to recognize certain months as "Holidays"

**Comment by SDGNelson** [comment]
Like the opposite version of the Holiday objects - visible when holiday is NOT active?

**Comment by Spebby** [comment]
Yep.

**Comment by SDGNelson** [comment]
Makes sense, will see about doing it before the Halloween update.

**Comment by Spebby** [comment]
Please extend this to Resources.

**Comment by SDGNelson** [comment]
For this year's winter event I added a feature with a similar purpose: object, tree, foliage, etc timed redirectors. On PEI they are used to swap out a winter theme throughout the event.
