### ISSUE TITLE
[ITEM REQUEST] Kosovo Jersey

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1052]
Please, Nelson, 1.8 Million people are going unrecognized. 

The most important request.

**Comment by Daniil1288** [comment]
yeah and next up are the LPR and the DPR then?
I don't think it's ever a good idea getting political in a video game about literal squareheads fighting zombies... if you're not trolling

**Comment by Spebby** [comment]
LPR isn't as good as an idea as it is completely unrecognized, Kosovo, on the other hand, is recognized by 100 UN nations. DPR is in the same boat as LPR, it's not recognized by any UN state.

**Comment by SDGNelson** [comment]
This seems to have become a bit of a meme in the last few days, so I had to give it some thought. There are 30 jersey items for countries based on playerbase size, and it's not feasible to add an item for every single country. While Canada does recognize Kosovo as a country, I think the fair choice is to take the same stance as with other requests for items for smaller countries.
