### ISSUE TITLE
Modules Feature Request

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#1053]
Hello Nelson, it would be nice if you can add something to download automatically client modules which are in a server into the user client. 

With that we can do very interesting things, like a GPS. Synchronized and players do not need to download external things to be able to enter the server.

**Comment by Sl4vP0weR** [comment]
Maybe this good idea,but i know,some servers will use this for own purposes(bad things)

**Comment by Trojaner** [comment]
This is not a good idea at all. 
Modules are .NET based without *any* sandboxing or restrictions at all.

This would open gates for any kind of malware.

**Comment by Sl4vP0weR** [comment]
> This is not a good idea at all.
> Modules are .NET based without _any_ sandboxing or restrictions at all.
> 
> This would open gates for any kind of malware.

what i meant

**Comment by SDGNelson** [comment]
If modules were sandboxed or everyone could be trusted this would be a great feature, but unfortunately as Sl4vP0weR and Trojaner mention this would easily be abused. If you do build a module with client functionality that's exciting however, there are not many out there at the moment!

**Comment by educatalan02** [comment]
Yes, it's exciting, but it's really not useful. Because nobody is going to download and place the module and every time you enter another server remove the module. I just wanted to give the modules a bit of utility, because if you're not famous or don't have someone to promote you, you can't do things with a clientside module.

**Comment by Trojaner** [comment]
*Friendly reminder that client side modules don't work anymore*

**Comment by Johnanater** [comment]
_Very exciting client side "modules"_
