### ISSUE TITLE
i9 9900k Cant handle servers?

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1056]
Hey Nelson,

I recently upgraded my dedi to a i9 9900k with 64gb of ram and ever since then I have been struggling with my whole dedi crashing. 

When it crashes according to windows event viewer it BSOD's
here is the XML of the event
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331C3B3A-2005-44C2-AC5E-77220C37D6B4}" /> 
  <EventID>41</EventID> 
  <Version>4</Version> 
  <Level>1</Level> 
  <Task>63</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000400000000002</Keywords> 
  <TimeCreated SystemTime="2019-09-14T16:18:13.046020000Z" /> 
  <EventRecordID>4899</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="8" /> 
  <Channel>System</Channel> 
  <Computer>WIN-E3QE5KR7OKQ</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="BugcheckCode">0</Data> 
  <Data Name="BugcheckParameter1">0x0</Data> 
  <Data Name="BugcheckParameter2">0x0</Data> 
  <Data Name="BugcheckParameter3">0x0</Data> 
  <Data Name="BugcheckParameter4">0x0</Data> 
  <Data Name="SleepInProgress">0</Data> 
  <Data Name="PowerButtonTimestamp">0</Data> 
  <Data Name="BootAppStatus">0</Data> 
  <Data Name="Checkpoint">0</Data> 
  <Data Name="ConnectedStandbyInProgress">false</Data> 
  <Data Name="SystemSleepTransitionsToOn">0</Data> 
  <Data Name="CsEntryScenarioInstanceId">0</Data> 
  </EventData>
  </Event>
```

I have reinstalled my dedi
Changed OS from win server 2019 to 2016
Reinstalled unturned server app
replaced all hardware

After still getting the crashes I decided today that I would run a hardware stress-test to see if the  system PSU or Motherboard could be causing an issue. I ran the stresstest for hours at 100% load on the CPU and the dedi has not crashed. Yet whenever I boot the unturned servers the dedi lasts about 10min-1hour before it BSOD's.

Any help from anyone would be appreciated.

**Comment by Trojaner** [comment]
Brad before reporting anything ensure this happens without any mods and without any plugins.
Even then, there is likely nothing Nelson could do about this.

**Comment by joeymisfit** [comment]
Hello @Trojaner,
Unfortunately we've already tested multiple instances without any plugins and workshops on the dedicated server and sadly it still has caused the bsod after certain periods of time.

**Comment by Bradler26** [comment]
No, Joe is slightly wrong there. I have run a vanilla server for a couple hours now with no issues. Does anyone have any suggestions as to what it could be?

**Comment by Johnanater** [comment]
What plugins / mods do you use?

**Comment by Bradler26** [comment]
Plugins
![image](https://user-images.githubusercontent.com/47075751/64918725-b1d96900-d7a2-11e9-96f1-cd6c4899da08.png)
List of mods
https://www.bradsnetwork.com/forum/m/47358202/viewthread/32313429-modpack-info

**Comment by Bradler26** [comment]
Turns out it was a bios setting and some drivers that were outdated even though my hoster says they were not. Anyways issue fixed. Hope that helps with anyone that has it aswell ;)
