### ISSUE TITLE
Glitching Through Doors

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#106]
**The glitch is as follows:**

![unnamed](https://user-images.githubusercontent.com/7349712/33236419-d75f381e-d220-11e7-911f-2f88cfb56d89.jpg)
![unnamed 1](https://user-images.githubusercontent.com/7349712/33236420-d8daaf0c-d220-11e7-8df1-c3b8be48421a.jpg)

Most cases it will teleport you into the door, but you may have to tap "S". Please let me know if you need any more information! Thanks.

**Comment by SDGNelson** [comment]
This was fixed several patches ago. I'll investigate why it would still be possible.

**Comment by SDGNelson** [comment]
Are you sure this is still possible in the current public version of the game?

**Comment by N1GHTPATROL** [comment]
Looks like it's been fixed, however I didn't remember seeing a patch note about it. Sorry!

**Comment by SDGNelson** [comment]
Ok thanks for confirming!
