### ISSUE TITLE
Packet Spam Kills The Server

### ISSUE THREAD

**Issue by Kr4ken-9** [SmartlyDressedGames/Unturned-3.x-Community#107]
Works with pretty much any packet, askChat packets are most commonly used for this purpose.

**Comment by yegac1337** [comment]
This fix was basically applied to the skills. It can basically be used with any packet as stated by kr4ken-9, I would love to see this fixed as it is a major problem towards streamers.

**Comment by SDGNelson** [comment]
I'll incorporate the rate limiting for more types of packets e.g. chat, and investigate automatically banning for configurable influx of traffic from an IP.

**Comment by aviadmini** [comment]
@SDGNelson maybe take a look at Rust. They have these ` server.maxrpcspersecond   (200)` and similar. This exact one might be not what you need but gives an idea to limit packets by sender

**Comment by Trojaner25** [comment]
Limiting RPC per seconds is a good idea. Maybe throttle connection to client if it exceeds some value
