### ISSUE TITLE
Error when equipping gun only on multiplayer servers

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#1073]
[9/26/2019 7:13:05 AM] [Error] ArgumentException: The Object you want to instantiate is null. - UnityEngine.Object.Instantiate[T] (T original) (at <2686255ceb974cc2967520f770810585>:0)
SDG.Unturned.Attachments.updateAttachments (System.Byte[] state, System.Boolean viewmodel) (at <369968f2cd05451081133d15a60b74ca>:0)
SDG.Unturned.ItemTool.getItem (System.UInt16 id, System.UInt16 skin, System.Byte quality, System.Byte[] state, System.Boolean viewmodel, SDG.Unturned.ItemAsset itemAsset, SDG.Unturned.SkinAsset skinAsset, System.Collections.Generic.List`1[T] outTempMeshes, UnityEngine.Material& tempMaterial, SDG.Unturned.GetStatTrackerValueHandler statTrackerCallback) (at <369968f2cd05451081133d15a60b74ca>:0)
SDG.Unturned.ItemTool.getItem (System.UInt16 id, System.UInt16 skin, System.Byte quality, System.Byte[] state, System.Boolean viewmodel, SDG.Unturned.ItemAsset itemAsset, System.Collections.Generic.List`1[T] outTempMeshes, UnityEngine.Material& tempMaterial, SDG.Unturned.GetStatTrackerValueHandler statTrackerCallback) (at <369968f2cd05451081133d15a60b74ca>:0)
(wrapper dynamic-method) SDG.Unturned.PlayerEquipment:tellEquip_Patch1 (object,Steamworks.CSteamID,byte,byte,byte,uint16,byte,byte[])
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
(wrapper dynamic-method) SDG.Unturned.SteamChannel:receive_Patch2 (object,Steamworks.CSteamID,byte[],int,int)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive_Patch2(Object, CSteamID, Byte[], Int32, Int32)
SDG.Unturned.SteamChannel:send(ESteamCall, ESteamPacket, Int32, Byte[])
SDG.Unturned.SteamChannel:send_Patch2(Object, String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.PlayerEquipment:tryEquip(Byte, Byte, Byte, Byte[])
SDG.Unturned.PlayerEquipment:askEquip(CSteamID, Byte, Byte, Byte, Byte[])
System.Reflection.MethodBase:Invoke(Object, Object[])
SDG.Unturned.SteamChannel:receive_Patch2(Object, CSteamID, Byte[], Int32, Int32)
SDG.Unturned.Provider:receiveServer_Patch1(CSteamID, Byte[], Int32, Int32, Int32)
SDG.Unturned.Provider:listenServer(Int32)
SDG.Unturned.Provider:listen()
SDG.Unturned.Provider:Update()

I cannot figure out what is wrong with the prefab, I remember it working fine and suddenly not working anymore without me changing anything :/

**Comment by erik7302** [comment]
PlayerEquipment:tellEquip_Patch1, SteamChannel:receive_Patch2, Provider:receiveServer_Patch1. as far as I know, "patch" is thing of patching with harmony, i think is a plugin causing it, try without plugins

**Comment by SDGNelson** [comment]
Since the exception is in updateAttachments and related to instantiating a prefab, the most likely problem is one of the attachments missing a Sight/Grip/Tactical/Magazine/Barrel prefab. For the next update I'll fix that to not throw an exception, and log which prefab is missing during asset loading.

**Comment by tankirules** [comment]
> Since the exception is in updateAttachments and related to instantiating a prefab, the most likely problem is one of the attachments missing a Sight/Grip/Tactical/Magazine/Barrel prefab. For the next update I'll fix that to not throw an exception, and log which prefab is missing during asset loading.

![image](https://user-images.githubusercontent.com/35437320/65824931-fe00cf00-e2b3-11e9-97a0-3b2ea3d8cf53.png)
I don't see anything wrong with my prefab?

**Comment by SDGNelson** [comment]
I mean that the attachment itself seems to be missing the prefab that gets instantiated and attached to the gun prefab. Does your gun have custom attachments?

**Comment by tankirules** [comment]
> I mean that the attachment itself seems to be missing the prefab that gets instantiated and attached to the gun prefab. Does your gun have custom attachments?

It turns out that the invalid magazine error (which was originally a typo, then i left it because i did not want the gun loaded with ammo when spawned) caused the error in console - the ID was 130012, do you think the big number caused it or just the fact a gun spawned with invalid magazine?
Thanks for your help regardless.

**Comment by TheCubicNoobik** [comment]
> the ID was 130012, do you think the big number caused it or just the fact a gun spawned with invalid magazine?

65535 is max
