### ISSUE TITLE
Allow Client Modules to get Players Health

### ISSUE THREAD

**Issue by bruris** [SmartlyDressedGames/Unturned-3.x-Community#1074]
allow clients to receive health from players. admins and myself, on my server, use a client module administration tool to help rid the server of other glitchers and cheaters. being able to see players health would be very helpful. Thanks.

**Comment by Gringoniceguy** [comment]
I agree this will be a nice feture pls add

**Comment by Trojaner** [comment]
Sounds like a great feature for cheaters.
As far as I know, client modules do not load anymore?

If you are making a client module anyway, you could easily add this yourself by adding relevant functionality to the server module.

**Comment by bruris** [comment]
its a battleye disabled servers, so the module does load
there is much worse that cheats could get then reading health values anyway. not sure what there is to be of concern there

**Comment by SDGNelson** [comment]
While Trojaner is probably right in his suspicions, it's worth noting that yes this could be achieved by adding an RPC to a module shared by the client and server, and it should become a bit easier once I get around to cleaning up some of the netcode.

**Comment by Gringoniceguy** [comment]
ok do it then
