### ISSUE TITLE
RPC client->server index mismatch?

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1076]
Got an interesting description:

Also, there is a bug in which a few things seem to happen at once: at certain times, I will go to reload and am unable to do so, but I have also noticed that if I am trying to build and something will no longer place (it will show up as green and make the placing sound/motion but not place) I also can no longer reload.  Other times, I will be shooting someone and almost none of my hits will register (besides the normal server lag/server-side shot detection bugs); when I ask what’s up in the chat, the people will reply that I was not shooting at all on their screen (this has happened several times to me and also to many of my friends).  After this, I usually can no longer reload once again.  Finally, sometimes when I try to reload but cannot, the barrel on my gun will pop off, and when I press the reload button, the gun only makes the noise but does not reload.

**Comment by SDGNelson** [comment]
Edit: similar report of not being able to reload more than once after getting killed by an explosion?

**Comment by Trojaner** [comment]
This desync issue might be caused by plugins (e.g. if using stuff like async chat or if sending RPCs with invalid data)

**Comment by SDGNelson** [comment]
Definitely, it could be that too. I'm planning to rewrite some of the packet code soon and will put some checks in place to prevent invalid usage.

**Comment by SDGNelson** [comment]
There was no obvious problem, but I have tidied up a few aspects of how useable items are destroyed and how the RPC list is rebuilt.
