### ISSUE TITLE
Add fade delay for Chat Messages with rich formatting

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1077]

**Comment by Trojaner** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/485
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/396

![grafik](https://user-images.githubusercontent.com/1809172/65831861-6f497d80-e2c6-11e9-9416-f8cede3c82c1.png)
