### ISSUE TITLE
Performance-Related Settings

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1088]
See if there are any new engine optimizations we can take advantage of.

**Comment by Trojaner** [comment]
You could take advantage of the new jobs feature
E.g you could implement the A* Pathfinding using it

**Comment by SDGNelson** [comment]
@Trojaner Agreed that the jobs feature looks promising. Right now all the pathfinding queries run on worker threads, but if implementing a new pathfinding system it would be interesting to experiment with the jobs system.
