### ISSUE TITLE
Explosive Chewing Gum

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#11]

**Comment by snowball7275** [comment]
Definitely need this instead of nice additions for developers.

**Comment by SDGNelson** [comment]
It will act as a cyanide tablet and hostage taking / threatening. Will be very useful for roleplay.

**Comment by redmoogle** [comment]
Nelson what have you been smoking

**Comment by redmoogle** [comment]
Last time I checked you can't forcefully put gum in someone mouth

**Comment by redmoogle** [comment]
Also very unrealistic to to do that.

**Comment by SnowEdwin** [comment]
http://www.independent.co.uk/news/world/europe/exploding-bubble-gum-kills-student-1837673.html
🤔
