### ISSUE TITLE
Submarine possibility?

### ISSUE THREAD

**Issue by Surefire58** [SmartlyDressedGames/Unturned-3.x-Community#110]
With the introduction of the new blimp mechanic, would it be possible to make submarines possible? The blimp can ascend and descend in water, allowing it to not get stuck in the water(like basic vehicles). Adding this to certain boats could turn them into submersibles, and even maybe a config option to allow oxygen to the player so its actually a full sub. This could be used for other things like the jet to on maps where the oxygen ceiling is low. Just wanted to see if this could be a possibility, thanks in advance for your comments.

**Comment by Savagethepanda** [comment]
I think he may do this some day. Just not today because he has to code to not have water in the vehicle which would be hard in my opinion.

**Comment by aviadmini** [comment]
Actually eazzy, it's achievable by simply checking whether player is in submarine.

**Comment by SDGNelson** [comment]
Submarines likely won't be added due to the complexity of masking out the water visuals inside the vehicle, and none of the maps have deep enough water to facilitate subs.
