### ISSUE TITLE
Control voice-chat radius

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1102]
if voice volume is high - its a scream - distance increase
if voice volume is low - its a whisper - distance decrease

**Comment by SDGNelson** [comment]
Neat idea. It could perhaps be done by looking at the average amplitude of the voice data. In 4.0 I've been using the scroll wheel for more inputs like this, and perhaps it would work nicely to use (voice key + scrollwheel) to adjust volume range.

**Comment by Sl4vP0weR** [comment]
> (voice key + scrollwheel) to adjust volume range.

Hmm, need always to change your voice volume
