### ISSUE TITLE
How Make a Mod to Show progress bar

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1105]
I want to make a UI plug，but i dot how to use untiy to create progress bar。
if use animation ， hot to   pause animation? or start animation from the specified location
Nelson  can you release guide ?

**Comment by erik7302** [comment]
To create a ProgressBar you only need to create an image component and change image type to "Fill"
If Nelson implements my code from #1002, you could use "sendUIEffectFillImage" to change the progress of the ProgressBar.

**Comment by SDGNelson** [comment]
Interesting case, I'll mark it as "UI-related" for the upcoming plugin UI networking improvements. erik7302 is right that typically it would be done by modifying the transformation of the progress bar image.

**Comment by HanaForward** [comment]
@erik7302  image type to Fill How to control it of progress rate?

**Comment by SDGNelson** [comment]
Sorry, I worded my response poorly: it's not currently possible with the existing UI RPCs, but I'd like to make it possible in a future update.

**Comment by HanaForward** [comment]
enen  thinks , Nelson  and erik7302
