### ISSUE TITLE
More gun audio/animation options

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1110]

**Comment by Sl4vP0weR** [comment]
Add ability to create mods with animations for player,
Calling the player animations on the server-side

**Comment by erik7302** [comment]
Also "Charge" audio and animation for guns witth firing delay

**Comment by OneManOperative** [comment]
Perhaps I would like to add more options. Other than reloads depending on ammo capacity, you could also consider adding safety animations that are separated from sprint animations, hammers playing first before the reload, sounds that play before & after a minigun spin & maybe alternate animations depending on what ammo is used. Although I think that should be more on the magazine side than the gun but it's up to you on how it would be done.
