### ISSUE TITLE
Ammo text component in Gun prefab

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1118]

**Comment by Sl4vP0weR** [comment]
I dont understood...
For what ? Changing of ammo count ?
Guns have a metadata value with ammo...

**Comment by SurvivorRISC** [comment]
> I dont understood...
> For what ? Changing of ammo count ?
> Guns have a metadata value with ammo...

For mods
![Screenshot_2019-10-04 weapon with display gameplay 11 тыс изображений найдено в Яндекс Картинках](https://user-images.githubusercontent.com/17459138/66203885-80c1c980-e6ba-11e9-9b2a-a0ddc38c0983.png)
