### ISSUE TITLE
Unity 2018.4 LTS Beta Branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1119]
A beta version running on 2018.4 is now available to opt-in. The previous upgrade to 2017.4 broke asset bundle compatibility due to shader changes, but this upgrade should be fully backwards compatible. The game currently fixes up asset bundles loading from past versions.

Some of the nice improvements include:

- Stabilized .NET 4.5
- Improved Headless Performance
- Terrain Rendering Optimizations
- Reworked Logging
- Nested Prefabs

For more information: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Unity2018.md

**Comment by Johnanater** [comment]
Yay! Looks like the Unity update fixed the following on the Linux client:
Ambient Occlusion doesn't give you wallhacks anymore
New trees don't crash the client anymore
Grass/Rocks actually work up now 

Haven't tested any server stuff, but it looks great so far! :D

**Comment by Kenzim** [comment]
how long until this is main release?
also, thanks for this, hopefully linux server hosting will cease to be a
meme.

**Comment by SDGNelson** [comment]
Today I tested out the latest Linux dedicated server build and the terminal seems to be working nicely! I think we can make -ThreadedConsole the default again.

**Comment by SDGNelson** [comment]
Currently considering releasing this as part of the Halloween update on the 25th. To my knowledge everything is stable now, so if you run into any issues please let me know!
