### ISSUE TITLE
Plugin Ability To Mark Locations On Map

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#113]
As far as i know this is not possible right now, how i was thinking this could be added is through the marker (waypoint?) players can place, but be able to place as many of them as you want and show them to certain players, this would allow plugins to have objective that you have to get to and lots of other things

**Comment by yegac1337** [comment]
This should be possible if time is put to it. I'd also like to see the waypoint appear on the compass!

**Comment by xdlewisdx** [comment]
They do appear on compass...

**Comment by SDGNelson** [comment]
Until this is implemented it's possible to adjust the player's waypoint from your plugin by manually sending tellSetMarker in PlayerQuests.

**Comment by aviadmini** [comment]
That's exactly what we were doing. Although non player waypoints would be great

**Comment by xdlewisdx** [comment]
@SDGNelson Indeed this is what I did in the first place but the problem with it is you can't rename the marker and you can't place more then 1, so i'll wait until its added, thanks
