### ISSUE TITLE
The plugin I made : PlayerLibrary

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1131]
Clean up the player database residue
Related plugins please use foreign key association
Uconomy plugin will be released later
https://github.com/HanaForward/PlayerLibrary

**Comment by Trojaner** [comment]
This repository is for suggestions and bug reports to the Unturned game, not to promote your own plugins or do other kind of advertisments.

**Comment by Tortellio** [comment]
sad

**Comment by HanaForward** [comment]
> This repository is for suggestions and bug reports to the Unturned game, not to promote your own plugins or do other kind of advertisments.

How can I get my plugin on RocketMod?
