### ISSUE TITLE
2560x1440 Resolution Bug

### ISSUE THREAD

**Issue by Yasamashi** [SmartlyDressedGames/Unturned-3.x-Community#1135]
Hi, I've occurred into a problem when I downloaded Unturned on my new PC. Its specs are:
- Mobo: ASRock B450M Pro4
- GPU: AMD Radeon RX 5700 XT 8GB
- CPU: AMD Ryzen 5 3600X
- RAM: G.Skill Ripjaw V 8GB x2 Dual Channel
- Monitor: AOC Q3279VWFD8 31.5" 2560x1440 @75Hz

The problem occurred when I tried to select the resolution (2560x1440 @75Hz) but instead it just set it to 1280x1440 @75Hz. It happens with every resolution over 1280 pixels of width, the ones below work as they should I think. It doesn't change in any way, tried to modify registry files, the Graphics.json file. It just reverts to 1280x1440 for some reason. Hope this problem can be solved, I'll try to reply as well as I can if you need more info. Thanks in advance!

**Comment by SDGNelson** [comment]
Apologies for the insane delay here! I hope it sorted itself out.

In the (belated) meantime a workaround may be to set the ```Override_Resolution_Width``` and ```Override_Resolution_Height``` values in the Preferences.json file.

For the next update I will also adjust the game to look for Unity's default ```-screen-width``` and ```-screen-height``` command-line options, and if present, will disable in-game resolution in-case Unity set values. I'll also add some common aliases for those in-case anyone is trying to set values that way.

**Comment by Yasamashi** [comment]
Actually thanks for the reply. I found a workaround in Steam's discussion
threads and basically I had to set to 0 the value for the supported monitor
only (can't remember the exact name of the parameter). Now it's fine
although I still have to set the display resolution to 2k every time I log
into the game. Hope it helps in the resolution of this problem. Also, maybe
you get that a lot but thanks for creating this awesome game!

Il mar 19 nov 2019, 04:55 Nelson Sexton <notifications@github.com> ha
scritto:

**Comment by SDGNelson** [comment]
That's nice of you to say considering these bugs!
If setting that value to zero worked, then it may be worth trying the resolution overrides as well - they should allow you to set it to 2k by default.

For the next update I've made those changes mentioned in my previous comment, and added -w, -h, -width and -height command-line options just in case.
