### ISSUE TITLE
House #13 missing door slot

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#1139]
Door between interior and back porch is missing a door slot (doors cannot snap to frame).
![image](https://user-images.githubusercontent.com/7608445/66721883-fae60280-edcc-11e9-812a-47d2234ad6ca.png)

**Comment by PndaPT** [comment]
I have noticed that too

**Comment by SDGNelson** [comment]
Thanks for the report! Will be fixed in the next update.
