### ISSUE TITLE
More Key Presses For Plugins

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#114]
it would be great to be able to check when ANY key is press, this would allow plugins to have custom keybinds to do things, right now you can check for only the things below
```
this.keys[0] = this.player.movement.jump;
this.keys[1] = this.player.equipment.primary;
this.keys[2] = this.player.equipment.secondary;
this.keys[3] = this.player.stance.crouch;
this.keys[4] = this.player.stance.prone;
this.keys[5] = this.player.stance.sprint;
this.keys[6] = this.player.animator.leanLeft;
this.keys[7] = this.player.animator.leanRight;
```

Clearly this would have to be limited so it only sends key presses if they are tabbed into the game and don't have steam overlay open, otherwise you could keylog

**Comment by Trojaner25** [comment]
I had something like that in my own test game and it caused performance issues

**Comment by xdlewisdx** [comment]
Or maybe some kinda of action menu for example, the gesture menu, but put customs items on it for plugins to use, just some kinda of easy way for a plugin to interact with a plugin without typing commands.

yes i would reuse the gesture menu but then people wouldn't be able to use gestures

**Comment by Trojaner25** [comment]
I suggest that plugins can register a callback on a key and that they get notified once said key has been pressed. But this needs to be made in a way that plugins can not listen to "all keys", only specific ones maybe
