### ISSUE TITLE
How to control Image fill Amount in Plug.

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1140]
![1P{56AOTV58YECKEU N~$5C](https://user-images.githubusercontent.com/30208197/66800535-19bcd400-ef48-11e9-96d3-53d906780d75.png)

look like it cant use {0} to control amount.
who can tell me, how to ues it?

**Comment by HanaForward** [comment]
Can i use Script?

**Comment by notyourbusiness9484** [comment]
This is not a place for support this is a place for issues

**Comment by SDGNelson** [comment]
Not currently supported, but it may be added during the UI upgrades.

**Comment by HanaForward** [comment]
@SDGNelson  thanks you , Nelson

**Comment by hksz** [comment]
Have you solved the problem

**Comment by HanaForward** [comment]
close it

**Comment by wrdkj** [comment]
请问您解决了吗
