### ISSUE TITLE
Cannot join server using Steam browser protocol link - shows "Server not responding"

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#115]
Links like `steam://connect/server_ip:server_port`

**Comment by yegac1337** [comment]
Copy the IP and port and just use it ingame.

**Comment by aviadmini** [comment]
The whole damn point of it is to join game without doing IP copying bullshit

**Comment by Trojaner25** [comment]
I can confirm this and it is really annoying, especially when including links to servers from browser.

Example scenarios: Server lists, homepage of server etc...

**Comment by yegac1337** [comment]
I can confirm this also is a problem with other games.

**Comment by yegac1337** [comment]
This is more of an issue with Steam. Has been around forever with multiple games.

**Comment by MoltonMontro** [comment]
@yegac1337 is correct. Steam browser protocols have been broken for a long time, and I doubt there's too much Nelson can really do to fix that.

**Comment by aviadmini** [comment]
Rust works just fine

**Comment by Trojaner25** [comment]
Developers can talk to Steam Staff to get such issues fixed @MoltonMontro

**Comment by MoltonMontro** [comment]
> It works for Rust just fine
Apologies if it came off like it, but I wasn't trying to imply it's broken for every game and every protocol.

> Developers can talk to Steam Staff to get such issues fixed @MoltonMontro
They can, but considering it has affected numerous games, including Valve titles at some points, you'd think that it would have been fixed again already.

There's also the issue of Valve sometimes opting to not pursue on developer feedback unless it is from a "major title." iirc, Steam Economy item border colors weren't made publicly available until after Overkill also sent in a request. Many features (developmental or not?) are restricted to Valve-exclusives for a while.

**Comment by SDGNelson** [comment]
It does work, but iirc you need to specify the Steam query port not the game port which is (game port +1) or +2. This has been reported many times and every time I've looked into it and managed to get it working by fixing the port number used.

**Comment by aviadmini** [comment]
@SDGNelson if the game is open it doesn't work (tried just now)

**Comment by aviadmini** [comment]
It's possible to make query port same as game port, right? At least Rust seems to do so
