### ISSUE TITLE
Add GUID to Barricades/Sturctures

### ISSUE THREAD

**Issue by Pigeon-cmd** [SmartlyDressedGames/Unturned-3.x-Community#1153]
It would be nice if each Barricade/Structure had a unique GUID or ID assigned to it that was persistence between restarts. This would make a lot of stuff easier for Plugin Devs and would be simple enough. I'm aware that some Plugin Frameworks do this right now like AviRocket, but doing it yourself has a lot of implications and AviRocket has big issues every single time a barricade region comes out of sync.

**Comment by SDGNelson** [comment]
It would make sense to do so, and unlike item guids should be easier to do. If there's spare time in these next couple weeks I'll see about slipping it in.

**Comment by SDGNelson** [comment]
In the next update these instance IDs are persisted between restarts, and are kept in the Data structs as well.
