### ISSUE TITLE
text shadows changed. Hardly readable on some backgrounds.

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1159]
I guess text had blurred shadow on all sides of text, now its angled. Its really hard to read light text on light background.

For example: 
![image](https://user-images.githubusercontent.com/14231707/67596008-7605cc00-f770-11e9-834d-415fa1f0530a.png)

**Comment by SDGNelson** [comment]
When experimenting I felt this could go either way, but for the patch I will enable full shadows for all in-world text like that. It wasn't just change for change's sake - there is a performance benefit to not blurring in all directions - but for these labels it's probably worth having full shadows.

**Comment by Kenzim** [comment]
please make this a graphics option @SDGNelson !! personally, i love this new one way blur, it looks soo much cleaner. thanks

**Comment by SDGNelson** [comment]
I agree it does feel crisp and new somehow. In the interest of breaking as little as possible I won't include an option for it in this patch, but I have opened a separate issue to add an option in the future.
