### ISSUE TITLE
Facility Glass #3 is no longer transparent

### ISSUE THREAD

**Issue by LukaszWypych** [SmartlyDressedGames/Unturned-3.x-Community#1169]
![Unturned_MViEgdGyNh](https://user-images.githubusercontent.com/52205132/67624434-ccd2da80-f830-11e9-9466-e91c512f5728.jpg)
Facility Glass #3 is no longer transparent
Hawaii assets

**Comment by PndaPT** [comment]
oh ok

**Comment by PndaPT** [comment]
both Facility glass 3 and 6 all-glass are not transparent

**Comment by SDGNelson** [comment]
Thanks for the report! It should be fixed in the .2 patch now. Those windows were missed by the auto-updater because they were setup in an unexpected way, but any other windows are hopefully covered by the fix as well.
