### ISSUE TITLE
Replace *.foliage files

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1170]
Probably one of the most egregious asset mistakes in the history of the game. Makes updating and validation slow having so many *.foliage files for each map.

Replacing has been on the backburner for a while, but hopefully we can get to it within the new few months. Ideally some sort of header with offsets into a single foliage blob.

**Comment by Daniil1288** [comment]
Speaking from personal experience, I have, in fact, manually removed the foilage folder for every custom map I've had on my server since it reduces the size by so much.

**Comment by Spebby** [comment]
Since this is happening "Next Update" how will existing devkit foliage be impacted? How will custom Devkit foliage be changed?

**Comment by SDGNelson** [comment]
It's backwards compatible, so there shouldn't be any negative side effects. I'll have this rewrite up on the preview branch by early next week for comparison.
