### ISSUE TITLE
Maple stump visibility with SpeedTree wind on/off?

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1173]

**Comment by Spebby** [comment]
More and issue with stumps in general. Seems to be an issue caused by speedtree materials being set from "Best" to "None", and the game not handeling lower wind settings well.

**Comment by SDGNelson** [comment]
I wasn't able to personally replicate the stump issue, but made a few precautionary changes that may have fixed it.
