### ISSUE TITLE
Hawaii Asset Bug

### ISSUE THREAD

**Issue by PndaPT** [SmartlyDressedGames/Unturned-3.x-Community#1174]
So I have making my RP MAP when I noticed that all the "Facility Glass" were not even considered Glass any longer, due to the fact that now the "Glass" its Mate blue... Please fix it nelson we need Hawaii objects in unturned in order for us Map makers keep their jobs :)
![unknown](https://user-images.githubusercontent.com/57059929/67632307-a8f7af00-f899-11e9-9d8d-cdbbccdccf42.png)

**Comment by DiFFoZ** [comment]
#1169

**Comment by SDGNelson** [comment]
Thanks for the report! It should be fixed in the .2 patch now. Those windows were missed by the auto-updater because they were setup in an unexpected way, but any other windows are hopefully covered by the fix as well.
