### ISSUE TITLE
Slow speed of vehicle on server

### ISSUE THREAD

**Issue by karatelg** [SmartlyDressedGames/Unturned-3.x-Community#1176]
Hello, Nelson. I have some car that was made on 2017 Unity. After your update on server they all have 10 km/h speed. How can i fix them. This models are very expensive for me.

![image](https://user-images.githubusercontent.com/52929598/67640878-2230e980-f90e-11e9-87b1-dafab7e57583.png)

**Comment by SDGNelson** [comment]
Wow, I'm curious to check out those cars in-game!

Do they have their center of mass manually set? Either from an older "cog" transform or in the .dat file? The .1 patch adjusted how that's calculated by default.

Another property that might help is raising the mass of the wheel colliders. I found that helped with the vanilla racecar.

**Comment by khakers** [comment]
Changing wheel collider mass caused all my vehicles with speed issues to behave normally again. It doesn't make them jitter when turning either now which is a massive improvement.

**Comment by karatelg** [comment]
@SDGNelson, I do not have the source code for these machines. Only. unity3d and .dat file. Do you manage to help me in any way? I do not want to lose these cars. I can send the .unity3d and .dat file if necessary.
Also there is no connection with a model maker since he left unturned

**Comment by SDGNelson** [comment]
One option would be to set this line in the .dat files to give it a try:

    Wheel_Collider_Mass_Override 5

It was added to quickly test with the racecars, but might be moved into the wheel physics profile in the future.

**Comment by karatelg** [comment]
@SDGNelson 
Wheel_Collider_Mass_Override 5 dont help me. I wrote it in .dat file like this.

What i should do? Wait update from you?
![image](https://user-images.githubusercontent.com/52929598/67701587-40a3ed00-f9c1-11e9-8be8-fff98338594c.png)

**Comment by SDGNelson** [comment]
Perhaps your car has a more realistic mass? All of the legacy vehicles have a mass of 1, but I've seen modded cars with more realistic masses (in the thousands). It might be worth trying a value of 5,000 or 50,000 just to see if it affects anything.

**Comment by karatelg** [comment]
@SDGNelson, you are breathtaking!!!
It works!!!!!!!
![image](https://user-images.githubusercontent.com/52929598/67716242-802c0280-f9dc-11e9-889e-3fe7f9f1e403.png)

**Comment by SDGNelson** [comment]
Haha! Glad we were able to sort it out. In the future (no ETA yet) I plan to introduce an asset which will help with tuning these wheeled vehicle physics to be a little more reliable. #1172
