### ISSUE TITLE
Spirit Zombie Type

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#118]
For an upcoming map. ;)

**Comment by SnowEdwin** [comment]
no but literally what

**Comment by Savagethepanda** [comment]
So I guess the new map will be somewhere in Europe.

**Comment by walz77** [comment]
I hope it’s a remastered version of Canada

**Comment by DieselsiselMedia** [comment]
Yoga zombie?
