### ISSUE TITLE
Problem with starting the game

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1181]
My friend fully deleted the game and after installing he has this problem with BattleEye. How to resolve it?

```
21:12:30: Starting BattlEye Service...
21:12:30: Failed to start BattlEye Service (1053).
21:12:30: Installing BattlEye Service...
21:12:32: Failed to install BattlEye Service (4, 41d).
```

**Comment by karatelg** [comment]
Try to reinstalling Battle Eye

**Comment by Greenorine** [comment]
No way. Same errors.

**Comment by SDGNelson** [comment]
BattlEye support and FAQ can help out with these sorts of issues: https://www.battleye.com/support/

Apologies, I thought I'd replied before. Hopefully it sorted itself out or was resolved. Feel free to comment and I'll re-open.
