### ISSUE TITLE
Effect Prefab

### ISSUE THREAD

**Issue by Radless0** [SmartlyDressedGames/Unturned-3.x-Community#1190]
How can i find effect prefab for unity?

**Comment by SDGNelson** [comment]
Can you provide more details? There are several examples in the AllExamples.unitypackage file.

**Comment by Radless0** [comment]
@SDGNelson I want make custom effect with image for upload to workshop.

**Comment by SDGNelson** [comment]
Sorry, but that falls outside the scope of the issue tracker. What you'll want to do is create a custom effect in Unity, export it for use with a custom effect .dat file, and then upload it to the workshop from the in-game tool.
