### ISSUE TITLE
Lots of mods became white after recent update.

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1193]
![image](https://user-images.githubusercontent.com/14231707/68049905-b0c9b000-fcec-11e9-9049-86b572605a6f.png)

**Comment by SDGNelson** [comment]
I believe the relevant change is that previously the emission upgrade was run only on "Fade" render mode materials, but now it is run on all standard materials. Here's the relevant snippet:

	/// <summary>
	/// Based on fixup routine in StandardShaderGUI SetMaterialKeywords.
	/// </summary>
	public static void fixupEmission(Material material)
	{
		Color emissionColor = material.GetColor("_EmissionColor");
		if(emissionColor.maxColorComponent < 0.01f)
		{
			material.globalIlluminationFlags = MaterialGlobalIlluminationFlags.EmissiveIsBlack;
		}
		else
		{
			material.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
		}

		bool shouldEmissionBeEnabled = (material.globalIlluminationFlags & MaterialGlobalIlluminationFlags.EmissiveIsBlack) == 0;
		if(shouldEmissionBeEnabled)
		{
			material.EnableKeyword("_EMISSION");
		}
		else
		{
			material.DisableKeyword("_EMISSION");
		}
	}

Perhaps the material emission color is set to white? Worst case I can change it to only do the upgrade for older fade/transparent materials if the material source is no longer available.

**Comment by baranmod** [comment]
Not really, checked two items which went white after update. Both had emissions disabled on materials

**Comment by SDGNelson** [comment]
Even if emission was disabled, their emissive color or texture might have been set. While preparing for 2018.4 I found that a lot of materials had emission enabled as black, or emission disabled but with a color set - the standard shader tool is supposed to fixup those keywords when selected as well.

I'll change the emission fixup to only apply to fade and transparent mode materials in the next patch.

**Comment by baranmod** [comment]
Yeah, saw that. But one of those white items had emission color set to white and another one - to black. Will try to enable emissions with black color and see if that helps. Thanks for help :)

One more thing (I guess related to this) - modded scopes which have emission enabled are not transparent (seems like alpha cutoff would be set to 0, yet it isn't). I mean, it looks as supposed to look in unity, but not in game. Tried Asset_Bundle_version 3 on single player, it did a job. Yet after I uploaded it to server today after unturned update - it doesn't work again

**Comment by SDGNelson** [comment]
If they have black color it should be okay to disable emission, and I will change it to only apply to fade and transparent.

Scope with render texture using unlit texture material? Or the black reticule using a cutout material?

**Comment by baranmod** [comment]
Unlit material for Scope, and cutout material for reticule. Sadly, those scopes supposed to have emissions for reticles.

**Comment by SDGNelson** [comment]
Double-checked and it looks like all the sights are included in the examples package now, so it might be worth comparing the material settings with a vanilla one. If Asset_Bundle_Version is set to 3 none of these upgrade steps will be run on it. Also if you like, send over a broken sight to my email and I'll download it and see what might be the issue.

**Comment by strongunturned** [comment]
Less effort to fix all the errors associated with the update. Above provided screenshots of some popular mods....

![Screenshot_1](https://user-images.githubusercontent.com/48184311/68073664-77a04700-fda3-11e9-97b3-db646443c5f4.png)
![Screenshot_2](https://user-images.githubusercontent.com/48184311/68073665-77a04700-fda3-11e9-98e4-4c8a3b4eee9c.png)
![Screenshot_3](https://user-images.githubusercontent.com/48184311/68073666-77a04700-fda3-11e9-8220-f024d83c388e.png)
![Screenshot_4](https://user-images.githubusercontent.com/48184311/68073667-7838dd80-fda3-11e9-9e5c-0fc6b442b735.png)
![Screenshot_5](https://user-images.githubusercontent.com/48184311/68073668-7838dd80-fda3-11e9-8a78-0792b63a3d75.png)
![Screenshot_6](https://user-images.githubusercontent.com/48184311/68073669-7838dd80-fda3-11e9-8297-d5c3fa4038e6.png)
![Screenshot_7](https://user-images.githubusercontent.com/48184311/68073670-7838dd80-fda3-11e9-84ad-af2a3e651e42.png)
![Screenshot_8](https://user-images.githubusercontent.com/48184311/68073671-7838dd80-fda3-11e9-8fc4-45f613cb60e9.png)
![BTgfD4qiCZw](https://user-images.githubusercontent.com/48184311/68073673-7e2ebe80-fda3-11e9-84a7-6b0ca5858b6c.jpg)
![yOo8hP0hvto](https://user-images.githubusercontent.com/48184311/68073674-7e2ebe80-fda3-11e9-81d4-725d9bde4d84.jpg)
![wNsfDnxhrxc](https://user-images.githubusercontent.com/48184311/68073675-7e2ebe80-fda3-11e9-9e67-e0bd66a6f8ad.jpg)
![W2f3aJO5Ip8](https://user-images.githubusercontent.com/48184311/68073676-7e2ebe80-fda3-11e9-9c4a-4c815e69e259.jpg)

**Comment by SDGNelson** [comment]
@strongunturned Do you have links to some of these workshop items? These screenshots are cursed. All of the vanilla and curated content had similar problems, but the game tries to update shaders to restore them to usual - curated maps are still using the automatic update as a test case.

**Comment by strongunturned** [comment]
@SDGNelson 


Also experiencing problems with all transport. Links to some mods: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1755044692
https://steamcommunity.com/sharedfiles/filedetails/?id=1738130955

These are mostly our fashions, but many popular fashions as well as curated objects are broken as well. Before the update everything worked fine, now we do not know what to do.

**Comment by SDGNelson** [comment]
@strongunturned I installed those mods, and there is a large quantity of content. Spawning in a few of the contained items they appeared okay, so do you have any specific IDs with older shaders that are having problems?

Mostly they appear to contain re-uploads of other workshop items, so a better option is probably to create a collection of workshop items. That way when the creator updates them everyone will receive the update, and players can visit the original item's page. WorkshopDownloadIDs auto-download also works properly with collection IDs, so the collection can be setup to auto-download.

**Comment by SDGNelson** [comment]
@baranmod In tomorrow's patch I've changed emission fixup to only run for fade and transparent materials, and even if the emission color is set it will only enable if a texture is also set - it looks like the vast majority of emissive materials have emissive maps, though this is now the StandardShaderGUI behavior I think it will be helpful.

**Comment by baranmod** [comment]
Its fixed now, thanks! BTW, scopes thing is fixed too (by asset bundle version 3), it was something in cache I believe as it got back to normal after couple restarts

**Comment by SDGNelson** [comment]
Thanks for the confirmation! There've been some bumps in the road, but at least 2017 -> 2018 has been smoother than 5.5 -> 2017.
