### ISSUE TITLE
Is it useless protector or joke?

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#1194]
3 methods use method <PrivateImplementationDetails>.ComputeStringHash(name);
And these methods have useless code
![sdg1](https://user-images.githubusercontent.com/43498426/68051586-d9f03d80-fcf8-11e9-830c-ca367b4fbc6f.PNG)
![sdg2](https://user-images.githubusercontent.com/43498426/68051587-da88d400-fcf8-11e9-9b7b-d358c63fb454.PNG)
![sdg3](https://user-images.githubusercontent.com/43498426/68051588-da88d400-fcf8-11e9-99d4-fa37a9743c1d.PNG)

**Comment by Trojaner** [comment]
The code you are viewing is the optimized compiler generated code and does not represent the real source code. 

What exactly is useless here? I can see that it checks if num meets to specific criterias and if that is true it will compare it to text like "Snow". This is basic AND logic.

**Comment by SDGNelson** [comment]
In the source code that method is implemented as a switch statement, but it looks like the compiler found that was more optimal. Implementing is nowadays I definitely wouldn't do it as a hardcoded string comparison, but this function probably dates back to pre-3.0.

All the comparisons are to string literals. If this were C I'd guess that it's comparing offsets to the string definition, but judging from the hash it might be the C# string pool.

**Comment by GazziFX** [comment]
In your opinion, adding extra lines that do not make useful work in the end is an optimization?
Optimization for C# or CIL never adds a Call instruction

**Comment by Trojaner** [comment]
> In your opinion, adding extra lines that do not make useful work in the end is an optimization?

There is no extra line, there is a switch which got optimized to branching instructions. 
It looks longer when converter to C# code but that has no meaning in regards to performance.

> Optimization for C# or CIL never adds a Call instruction

There is no additional call code.

**Comment by GazziFX** [comment]
Just compare with older version
There is a new call instruction
![image](https://user-images.githubusercontent.com/43498426/68053244-87b11b80-fcfc-11e9-8c10-4f80278a2be7.png)
![image](https://user-images.githubusercontent.com/43498426/68053302-a2839000-fcfc-11e9-8b63-4a9dfaa727ac.png)

**Comment by Trojaner** [comment]
ComputeStringHash is not part of the optimization I was talking about, it was converting switch to if's

**Comment by Coopyy** [comment]
this one made me laugh gazzi, thank you

**Comment by GazziFX** [comment]
> There is no extra line, there is a switch which got optimized to branching instructions.
> It looks longer when converter to C# code but that has no meaning in regards of performance.

Maybe Im wrong but CLR compares reference of pooled strings faster than computing hash
