### ISSUE TITLE
PEI Zombie-mesh issues

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#1197]
It seems something is up with zombie navigation on PEI lately, people have complained about zombies falling from the sky and related things.
I don't know much about unturned map navigation meshes, but it looks like at Holman the mesh there is messed up and causing zombies to get stuck.
![image](https://user-images.githubusercontent.com/17209937/68079675-90205980-fdc3-11e9-89c3-97683eef44da.png)
![image](https://user-images.githubusercontent.com/17209937/68079680-9adaee80-fdc3-11e9-8c54-bff231b54ca6.png)
People have been spooked out by the zombie noises, fitting of Halloween, just a few days late.

**Comment by SDGNelson** [comment]
Sorry for missing this! I'll take a look into it... Zombies shouldn't be spawning under there in the first place, but I wonder if they are spawned before collision is enabled. Another thing I should do is teleport zombies to a random spawnpoint if they fall outside the map.

**Comment by SDGNelson** [comment]
For the next update:

1. If a zombie is outside the map it will be teleported to a valid spawnpoint within its original area. There was a similar test before to move it back up to the top of the map, but there may have been some issues with that.

2. Death barriers inside objects (like the ones at Holman) now kill zombies as well, so hopefully if they do find their way in there they will get killed and respawn.

3. Zombies spawn with more clearance above the ground in case they were somehow falling through on the frame they spawned.

I double-checked and level objects and the ground are loaded before zombies are spawned, and there are no misplaced spawns down there, so it's unclear how those zombies got there in the screenshot.

For the sake of tracking what needs doing I'll close this for now, but feel free to comment and I'll re-open, or post another issue if more arise.
