### ISSUE TITLE
Vanilla Ambulance issue?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1200]
Hello Nelson,

I just recently noticed a bug in-game while dealing with a few players; basically the tires on the vehicle were there for me and one of the players, but yet the other player not being able see 2/4 tires, I spawned him in tires and oddly enough he was able to place them even though 2 out of 3 people saw tires on the vehicle?

Another weird thing to add is I could drive the vehicle perfectly fine turning right and left but the kid having the issue couldn't turn right in-game.

2 pictures are attached, 1 is showing me looking above the vehicle down at it where the tires are, and the other shows the vehicle having tires, yet the animation shows it's missing a tire or tires. (Left back tire and right front tire.)

Hope this report helps!

![ambu1](https://user-images.githubusercontent.com/20868143/68113558-ec10de00-fea8-11e9-9b90-386bacecd22e.png)
![ambu2](https://user-images.githubusercontent.com/20868143/68113559-ec10de00-fea8-11e9-9efc-85eae837224b.png)

**Comment by SDGNelson** [comment]
Since the ambulance is tilted in the last screenshot the tires must be missing on the server, so the clients who do see the tires must be the ones not displaying properly. Will investigate. 🤔

**Comment by SDGNelson** [comment]
Testing in multiplayer (in particular with the ambulance) it all seems to be working properly in vanilla, e.g. destroying a tire and then rejoining it is still missing as expected.

One potential problem that comes to mind when looking at the code however is do you have any plugins affecting the wheels? For example, if a plugin is setting tireAliveMask directly without calling sendTireAliveMaskUpdate there will be problems. The preferable way to handle that is askDamageTire or askRepairTire.

**Comment by SDGNelson** [comment]
Assuming that was the problem I'll close this now, but feel free to comment and I'll re-open.
