### ISSUE TITLE
admin editor broken

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#1201]
click and drag to select multiple items once is broken after the last patch.

**Comment by megoesrawr** [comment]
Also, getting if the person is in admin editor mode isn't working either. It always says the player isn't in the mode even though they are.

**Comment by SDGNelson** [comment]
I'll double-check before the next update.

@megoesrawr Whether the player is currently using it has never been available to the server, the only server-controllable property is allowWorkzoneWithoutAdmin.

**Comment by megoesrawr** [comment]
@SDGNelson Ok, Thanks. Is it possible to add an event for when people use admin editor or the shift + F# things? Sadly, its hard to check who used admin edit without asking all the staff.

**Comment by SDGNelson** [comment]
Ah interesting, so the idea is to keep an audit log of admin edits? I like it! Opened a separate issue #1202 that will allow overriding the new placement, as well as just tracking who/when.

**Comment by SDGNelson** [comment]
@aman7 Thanks for the report! The underlying bug was pretty stupid, and is resolved for tomorrow's patch.
