### ISSUE TITLE
[FEATURE REQUEST] More train options

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1203]
"Spawn_At_Ends" to force vehicles to spawn only at ends of a track.
"Can_Use_Items_Driver" Would allow the driver to pull out items/weapons.

**Comment by SDGNelson** [comment]
In the next update Min_Spawn_Placement and Max_Spawn_Placement have been added for individual train associations.

Allowing the driver to use weapons is not possible however, as none of the code was designed with driving and weapons at the same time.
