### ISSUE TITLE
Voice Range Changer

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#121]
Would be great to have a way of changing how far you're voice travels, for example. Whisper, Talk, Yell

You would change it by press Page Up / Page Down or + / - or some other keybind you think is better

**Comment by yegac1337** [comment]
This, It would allow for a lot.

**Comment by RichardCastilloUnturned** [comment]
Yes! I have had many issues with people who talk too loud or too soft. This would be a great improvement.

**Comment by MoltonMontro** [comment]
>I have had many issues with people who talk too loud or too soft.

I don't think it would fix that issue. This is a suggestion for voice chat range, not voice chat volume. Voice chat volume should already have a slider in the options menus.
