### ISSUE TITLE
Getting off vehicle 

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1211]
Sometimes when I get off a vehicle, I get teleported to a random spawnpoint. However, I still have all my stuff on me and I have no idea why this is happening. It's also possible to get teleported to a place with a lot of water (Maybe under the map?). Anyone else has this issue?

**Comment by SDGNelson** [comment]
Is this happening with a specific vehicle? If a safe nearby exit point cannot be found (e.g. vehicle is stuck inside a cliff) it falls back to teleporting you to a spawnpoint, but it sounds like this is happening incorrectly in your case.

**Comment by AwesomeGOAT** [comment]
This has only happened to me twice during my 1.6k hours of Unturned. Both times are because of jets. I believe the second time, I hit the prison wall on PEI with the bottom of the jet and got off to avoid death.

**Comment by AwesomeGOAT** [comment]
Another player, Pablo, who's on the offical Discord server, said that this happened to his friend as well couple days ago. Except that they were riding a bike.
