### ISSUE TITLE
Linux problem 

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1215]
The problem with Linux servers after the upgrade

Connecting: PlayerID: 76561198335880138 Name: FireRain4 Character: Hartmut11
../run.sh: line 70: 11829 Segmentation fault LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib64 ./Unturned_Headless.x86_64 -nographics -batchmode +secureserver/Rocket > output.log
CRASH: Sun Nov 10 15:11:03 MSK 2019

**Comment by Trojaner** [comment]
You should share logs at least..

**Comment by SvyatoslavOrlov** [comment]
[output.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3828749/output.log)

**Comment by Trojaner** [comment]
These logs do not contain the crash log / stacktrace

**Comment by SvyatoslavOrlov** [comment]
The error was displayed in the console, but I don’t know where to find it in the logs
