### ISSUE TITLE
New Unity

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1219]
1. DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
2. After update of Unity - Linux servers with my plugins always crashing. What can i do ?
3. I'm thinking - event onPluginKeyTick crash server.

**Comment by erik7302** [comment]
2 & 3 You can send the errors.

**Comment by Sl4vP0weR** [comment]
> 2 & 3 You can send the errors.

Automatic crashes

**Comment by SDGNelson** [comment]
1. Which object are you trying to do this with? Off the top of my head I think DontDestroyOnLoad only makes sense for root objects.

2. That depends on the crash call stack. Where is the crash occurring?

3. Likely related to point 2.

**Comment by Sl4vP0weR** [comment]
> 1. Which object are you trying to do this with? Off the top of my head I think DontDestroyOnLoad only makes sense for root objects.

Module, "when creating new GameObject" or "when adding component to gameObject of module(as MonoBehaviour)"

**Comment by Sl4vP0weR** [comment]
> 1. Which object are you trying to do this with? Off the top of my head I think DontDestroyOnLoad only makes sense for root objects.
> 2. That depends on the crash call stack. Where is the crash occurring?
> 3. Likely related to point 2.

I'm guess this happens, when I calling method "EffectManager.sendUIEffect" with key (short)-id

**Comment by Sl4vP0weR** [comment]
Coroutine couldn't be started because the the game object 'Plugin' is inactive!
-----------------------
The script 'MK_Mask_Effects.Start' could not be instantiated!
_______
Cuz @SDGNelson updated Unity, many of troubles with plugins on linux.

**Comment by educatalan02** [comment]
Just plugingameObject.SetActive = true
Then DontDestroyOnLoad

**Comment by SDGNelson** [comment]
I believe educatalan02 is right that activating the component is the issue there. The base game uses DontDestroyOnLoad for some singleton objects like the "managers". For DontDestroyOnLoad I'd double check that it's in the root, and that DDOL is called on the gameobject itself. There might also be some related HideFlags.
