### ISSUE TITLE
Modify devkit tools

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1220]
Nelson, please make for Kill Volume a custom value for the amount of damage the player will receive. This will create areas in which players will receive once-only damage and will be useful for many maps.

**Comment by WolfCaesar** [comment]
Nice !!!! I will be use it at the next day start!

**Comment by SDGNelson** [comment]
Are there any other parameters that would be useful for kill triggers? I'm planning to add an alternative script to the mod hooks package which will expose more options.

**Comment by Alex-Well** [comment]
Yes, it would be useful to be able to adjust the duration of the interval through which the damage is done and the ability to turn on this cycle. This would allow the creation of zones with periodic damage, similar to the Acid of a spitting zombie.

**Comment by Alex-Well** [comment]
(OFF-TOPIC)
A few months ago, I also invented and implemented my system thanks to which I can use the plug-in to activate the Unity Event I need and thereby change the prefab structure in fashion. The most interesting thing that I did this in an extremely unusual way and I plan to tell more about it soon.

**Comment by WolfCaesar** [comment]
My team of script progmans puzzled for 2 months how we can make it for our project. So, 
thanks for hearing us.
And one small request : I had trouble with "killvolume". I can*t delete, or even 
highlight or select "killvolume", my Inspector does not see this, but I can choose effects and other Asset Browser functions. This happened after saving the map. By the way, why in the proposed options where you can save the map so many folders where you can done it?? Is this a bug or a feature?)

**Comment by SDGNelson** [comment]
Update re #1316 

For the past major update I prioritized the chat and interactable mod hooks because those opened a lot of new possibilities. This kill volume request might be added in January or February, but the complications are mostly due to damage-over-time and properly working with all entity types e.g. players, animals, zombies, vehicles.

**Comment by WolfCaesar** [comment]
In this case, I have only one delicate request for you: can you make permanent custom damage only for players by the New Year?
Let me explain: I am making one of the best servers by S.T.A.L.K.E.R in Unturned in the entire history. But in order for my server to be almost perfect, I need anomalies that not only kill the players, but cause damage to the player. I can do in without custom damage? but it will be realy badly.

**Comment by WolfCaesar** [comment]
... And thank you for listening and helping us.

**Comment by SDGNelson** [comment]
Permanent custom damage? If only players are required then there are the existing Barrier and KillVolumes which both kill players on touch. When this is added it will be primarily to make that easy to do, and provide more options like damaging other entity types and damage over time.

**Comment by WolfCaesar** [comment]
Ok,Thank you for helping us)
