### ISSUE TITLE
Getting off Vehicles

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1222]
I investigated a bit further, this is what's happening. In Unturned, your able to flip other vehicles with plates. When you use a vehicle that is armored and able to flip others (Plates, etc) and you bump into another vehicle that's armored with layers all around it, it doesn't flip. However, it gets stuck and stays there. Now, when you keep pressing W, and then get off the vehicle, you will be teleported to a random spawn.

**Comment by SDGNelson** [comment]
With armor the exit check should be ignoring attached items. I'll double-check if there's some case involving hitting another vehicle and its attachments...

Linking to: #1211

**Comment by SDGNelson** [comment]
From your comments in these two posts I've made several changes to the exit behavior in the next update. Tilted / rolled vehicles should exit more consistently now, exiting near walls will use proper padding, and upward/downward exits are considered too.
