### ISSUE TITLE
Update Vehicle Rigidbody Mass

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1224]
Was messing around with vehicles recently, decided to give a vehicle's Rigidbody mass 2 instead of 1, the vehicle controls so much better than any vanilla vehicle. Most standard vehicles (Offroaders, Roadsters, Sudans, Trucks, Vans, etc) should have a mass of 2, something like the dump truck should have a mass of 8 or so. 

EDIT: Messing with Wheel Suspension also yields good results if done properly.

**Comment by SDGNelson** [comment]
Will be part of #1172
