### ISSUE TITLE
In-game server hosting information

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1226]

**Comment by joeymisfit** [comment]
My only concern with the in-game server hosting info is if people are using CloudFlare and a domain to mask the server IP that leaves it a bit vulnerable if it lists the server ip, no?

**Comment by khakers** [comment]
Using a domain name is not an effective way to hide the ip address from anyone who can be bothered to get it.

**Comment by joeymisfit** [comment]
That is true, it's basically as easy as going to a website to unmask the servers ip. However, I've known several dedicated server owners from past experience that keep their firewalls disabled which isn't really a smart approach when you have a full server or a player count above 24.

**Comment by SDGNelson** [comment]
To clarify: this is about having a menu describing _how_ to host servers with links to documentation and 3rd-party services.

**Comment by SDGNelson** [comment]
In the next update I've included a link to: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md

One consideration is having an explanation, as well as links to 3rd-party hosting services in-game. Mixed feelings on that one.
