### ISSUE TITLE
Zombie clothing system improvement

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#1228]
Currently not all clothes function works on zombies like emission, metallic, 3d shirt(mesh replacement). If all clothes function works on zombies, it will be really fun. Glowing zombie, better zombie(lost one arm, half of head gone etc), complete invisible zombie etc.

**Comment by SDGNelson** [comment]
Agreed that it would be good to have. Right now zombie clothes work completely separately from human clothes. If there's time at some point it would make sense to combine them and apply the zombie optimizations to players as well.
