### ISSUE TITLE
Translations requests

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1231]
I've been trying to mess with translations a bit but apparently I can't do much yet, what I found in the workshop were translations that had to be installed manually.

I uploaded a song to the workshop but apparently unturned is not recognizing the translation, I also tried to change the namespace on song and translation but it stop working at all.

I ask you to take a look at how the translations work and improve it, for example, to check if there are other files with the same language and namespace carrying only keys that unturned do not yet contain or override the old ones. (the game currently only checks for language and namespace)

**Comment by SDGNelson** [comment]
A few months ago I made changes to the localization loading so that it's easier to detect workshop ones. It was never supposed to be manual, but some were configured in ways that the game wasn't detecting them. 

My original intent was to load the older .dat localization files and reinterpret them as the newer format, but progress on that halted a while ago. Only a few systems actually use the "translations" by default, whereas all game features use the "localizations". Which piece of content were you working on?

**Comment by rube200** [comment]
I was working with songs.

```

> Song1.asset

"Metadata"
{
	"GUID" "(can't se me)"
	"Type" "SDG.Unturned.StereoSongAsset, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
}
"Asset"
{
	"ID" "1"
	"Title"
	{
		"Namespace" "SDG"
		"Token" "Stereo_Songs.Song1.Title"
	}
	"Song"
	{
		"Name" "somemusic.content"
		"Path" "Assets/Music/Song1.mp3"
	}
}
```

```

>English songs.translation

"Metadata"
{
	"Language" "english"
	"Namespace" "SDG"
}
"Translation"
{
	"Stereo_Songs"
	{
		"Song1"
		{
			"Title"
			{
				"Text" "Nice Song"
				"Version" "1"
			}
		}
	}
}
```

If I change the namespace in both files, the game will not detect the song, if I leave them as they are, the game will not load the song text and an empty box will be left in the stereo.

**Comment by SDGNelson** [comment]
Where is your .translation file saved? The game might not be detecting it. In the Client.log file it will log which translations were loaded. As a test I created a translation file and song asset using the "rube200" namespace and they loaded properly.

**Comment by rube200** [comment]
![Captura de Ecrã (66)](https://user-images.githubusercontent.com/20555316/69251089-c1ad6900-0ba8-11ea-8088-ece25efcc2e1.png)


These are the folders, I patched the server and saw the translation loading when I changed the name espace but the song didn't load.

**Comment by SDGNelson** [comment]
What I'm thinking to do for this in the next update is a "sandbox" folder in the game folder which loads identically to workshop content, and that way it is easier to work on these and know they'll function properly on the workshop.

**Comment by SDGNelson** [comment]
The sandbox directory has been added for the next update, and loads any assets, translations and content its subfolders contain the same way workshop ones are loaded. I tested setting up a song with a translation in there and it worked. I'll leave this open to see how things go after the update.

**Comment by rube200** [comment]
Ok I think it's working.
If I use the "SDG" namespace it doesn't work but if I use "my" own namespace "Rube200" in translations and assets it already works correctly.


Could you do anything about the workshop translations? they all seem to require additional changes (creating a folder, being moved, etc ...) to be read by the game.

And thanks

**Comment by SDGNelson** [comment]
Which workshop translation is that? Even if the description says they need to be moved they should work properly. I'll download it and check though.

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I'll re-open. In 3.20.1 there are several improvements to the localization systems as well.
