### ISSUE TITLE
Future Netcode Rewrite

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1233]
Collection of requests for the potential future rewrites of Unturned's network layer.

Options to switch between platform sockets, old Steam API and new Steam API.
#1013 

Referencing GameObjects, in particular UI effects, over the network.
#804
#984 
#992
#996
#1002
#1045
#1140

#1289

- Thunk between calling RPC and executing? Rather than referencing by name.
- Reduce memory (especially array) allocations.
- Protect against corruption by plugin threads.
- RPC attribute for rate limiting.

**Comment by Ankumo** [comment]
That'd be such a pleasant update! Especially after Rust plugin development (oxide) with the similar netcode

**Comment by educatalan02** [comment]
Is there any ETA on this?

**Comment by Greenorine** [comment]
When it will possible to move UI objects?

**Comment by CatzMR** [comment]
I hope to solve the impact of the VSE Flood attack on the server. When being attacked, the server usually receives a large amount of FF: FF: FF: FF: 54: 53: 6F: 75: 72: 63: 65: 20: 45: 6E : 67: 69: 6E: 65: 20: 51: 75: 65: 72: 79: 00, then the server will not be able to search, it is recommended to increase the carrying capacity of the number of game data packets

**Comment by CatzMR** [comment]
TIPS: What are a2s_info and a2s_connect?
a2s_info: used for querying the information of the A2S server. Hexadecimal data segment of the message (fixed to 25 bytes): FF: FF: FF: FF: 54: 53: 6F: 75: 72: 63: 65: 20: 45: 6E: 67: 69: 6E: 65: 20: 51: 75: 65: 72: 79: 00

a2s_connect: Application layer handshake when connecting to the A2S server. Message hexadecimal data segment (fixed to 23 bytes, mask segment random) FF: FF: FF: FF: 71: 63: 6F: 6E: 6E: 65: 63: 74: 30: 78: ?? : ??: ??: ??: ??: ??: ??: ??: 00

**Comment by CatzMR** [comment]
"TSource Engine Query” DDoS attack
The server will be subject to a large number of TSource Engine Query packages

**Comment by SDGNelson** [comment]
"Transport Layer" rewrite is now on a beta branch, see #1971
