### ISSUE TITLE
Normal map not working in game.

### ISSUE THREAD

**Issue by alsgur1638** [SmartlyDressedGames/Unturned-3.x-Community#1235]
I am using normal maps within Unity. This time, the Unity version has been upgraded and not working in game. I want to know why the normal map doesn't work.

**Comment by SDGNelson** [comment]
Have you set the Asset_Bundle_Version to 3? If not, the game might not have normal map shader variants but is trying to replace your standard shaders.

**Comment by SDGNelson** [comment]
Feel free to comment and I'll re-open.
