### ISSUE TITLE
Groupname on main player HUD

### ISSUE THREAD

**Issue by jackthefrag** [SmartlyDressedGames/Unturned-3.x-Community#124]
Would be helpful, as the 'Group' screen searchbar conflicts with 'wasd' when trying to exit.

**Comment by SDGNelson** [comment]
Are you suggesting displaying it as part of the main game HUD e.g. ammo, compass?

**Comment by jackthefrag** [comment]
Yup, or maybe you could disable the textbox when buttons are pressed if it's much of a hassle.
Same happens when crafting. Esc button is too far when you need a quick exit.

**Comment by SDGNelson** [comment]
How would the text field know a key meant to leave the menu v.s. actually searching? Will look into adding tab/dashboard key as an escape key.

**Comment by jackthefrag** [comment]
You're right. How about setting a key eg; 'Enter' or '/' to activate the text field?
