### ISSUE TITLE
[FEATURE REQUEST] Ability to rotate server logs

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#1240]
Sometime log files becomes too big (over 1gb and more). Truncating not working, as the file still in use. It will be great to autoclean file without restarting the server when size exceeded given limit

**Comment by Trojaner** [comment]
Sounds like something a plugin should do

**Comment by D-AIRY** [comment]
Not sure how to access to a private variable, `private static LogFile debugLog;`

**Comment by rube200** [comment]
I think this is something that you are looking for.
`var LogFile = (LogFile)typeof(Logs).GetField("debugLog", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null);`

**Comment by SDGNelson** [comment]
For the next update I've added a few functions to the Logs class which should allow you control:
```
string getLogFilePath()
void setLogFilePath(string logFilePath)
void closeLogFile()
```

When I've seen huge log files in the past (GB+) it's usually exceptions being thrown every frame, either from plugins or unexpected asset setups. What's being spammed to your log file?

**Comment by D-AIRY** [comment]
You're right, it's plugin's exceptions. Clients often complaints about missing drive space. I cannot fix every hosted server. Thank you for that new functions

**Comment by SDGNelson** [comment]
Ah, sorry about that. I've also added a command-line option -NoDefaultLog which disables log setup unless a plugin calls setLogFilePath.

Have you had any luck with the newer mono binaries I sent over the other day?

**Comment by D-AIRY** [comment]
Didn't test yet. I'll do until the end of the week
