### ISSUE TITLE
Players can walk on Precision Charges

### ISSUE THREAD

**Issue by awedy01** [SmartlyDressedGames/Unturned-3.x-Community#1241]
https://youtu.be/2SGvHWVKJVg
We just noticed, players can walk on Precision Charges. I reported the same thing about Demolition Charges earlier, you fixed it with demos but not with prec charges, so i guess it's a "bug" aswell.

**Comment by SDGNelson** [comment]
Thanks for the report! Sneaky charge usage. This should be fixed for the coming update.
