### ISSUE TITLE
Allow plugins to close PlayerLifeUI

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#1242]
It would be great if plugins could close the PlayerLifeUI (bottom left as well as chat) on players for custom UIs.

Thanks :)

**Comment by Coopyy** [comment]
custom ui from the server would be disgusting and slow

**Comment by educatalan02** [comment]
No, It's really good for Roleplay Servers

**Comment by SDGNelson** [comment]
I'll plan to make the rest of the life HUD controllable from EPluginWidgetFlags in the next main update in January. This past update the death screen finally became optional.

**Comment by SDGNelson** [comment]
Obviously a long time since this issue was posted, but at some point in 2020 flags for hiding all of the life stats and status effects was added. Not chat though.
