### ISSUE TITLE
Randomly pushing out players from server

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1245]
Basically, this message spam log for a bit and all players are pushed out from server (no errors in logs except this one message so its probably related to mass kick?)

[2019-11-19 19:51:08] Discarding old unacknowledged input packets (25/24)

Doesn't happen very often but still annoying a bit

**Comment by SDGNelson** [comment]
Disabling "Enable_Kick_Input_Spam" in Config.json will prevent that kick, and maybe it should be disabled by default until the netcode rewrite.

**Comment by baranmod** [comment]
I've disabled this couple weeks ago (since I opened this issue), yet today, after update, this started happening again and each couple minutes now. Any ideas?

**Comment by baranmod** [comment]
Nevermind, its just some new plugin bug after latest update
