### ISSUE TITLE
Collision detection problem

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1247]
Curious if there is any way to make fast-moving projectile not go through colliders? Tried all collision detection types, all works the same as discrete. Basically the only way now to make it detect colliders correctly is by increasing projectile's mass or decreasing ballistic force.

**Comment by SDGNelson** [comment]
I would think the sweep-based CCD would do the trick, but perhaps not. This doc explains the tradeoffs: https://docs.unity3d.com/Manual/ContinuousCollisionDetection.html

If it's going that fast I wonder if it would make more sense as a normal bullet? Is there a projectile-only setting needed?

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I'll re-open.
