### ISSUE TITLE
Barricade and structure problem

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#1249]
This is a very old problem, but since it still exists, I decided to write about it. In general, due to the fact that all cycles in barricade managers and structures are used **ushort**, problems occur. For example, you take a barricade, and you get another. Some barricades become invisible, etc.

We have a method for taking a barricade where the index is **ushort**, but what if there are more than **65535** barricades in the region?

This is where the problem arises!

I’m not sure that I will be able to explain what’s the matter, I’ll try to explain clearly through the code :D
```CSharp
tellTakeBarricade(CSteamID steamID, byte x, byte y, ushort plant, ushort index)
```

```CSharp
private static void loadRegion(byte version, River river, BarricadeRegion region)
{
      ushort num1 = river.readUInt16();
      for (ushort index = 0; (int) index < (int) num1; ++index)
      {

      }
}
```

**Comment by Trojaner** [comment]
I don't think there is a problem with how unturned processed barricades.
You very like do something wrong in how you process barricades...

**Comment by surv0013** [comment]
> You very like do something wrong

Yes, but this time it’s not the problem

I just want to say that 65,535 barricades on the region are not enough

**Comment by SDGNelson** [comment]
Is your server actually hitting that limit? Each region is 128m x 128m, so that area would be incredibly dense if so.

**Comment by surv0013** [comment]
> Is your server actually hitting that limit - are you logging entity counts? Each region is 128m x 128m, so that area would be incredibly dense if so.

The number of elements does not reach the limit, but the problem described above occurs. I don’t know why these problems arise, but it is somehow related to filling the region with barricades.

**Comment by SDGNelson** [comment]
If it's not at the limit where is it overflowing the ushort?

The regions serve as spacial partitioning, and are used to (somewhat) improve the size of the active object set and spatial queries. e.g. when looking up barricades within a radius it only needs to check the regions overlapped by that radius, and network data is only sent for entities within a certain number of regions.

**Comment by SDGNelson** [comment]
Sorry, I wasn't trying to say there isn't an issue, I'm wondering if there's an exception or something that is leading to issues. Or perhaps there is a plugin where the overflow is occurring?

**Comment by PandahutMiku** [comment]
From what @surv0013 has described of the issue `For example, you take a barricade, and you get another. Some barricades become invisible, etc.`
Pretty sure he's just talking about the lists of BarricadeDrops and BarricadeData within a single BarricadeRegion coming out of sync. 
I have seen this issue happen a decent amount simply when a barricade region has a ton of barricades in it (~10k or so, nowhere near ushort max though) or when there is a lot of changes in that region.
I don't know the exact cause or more information about the issue besides that the issue happens to a single barricade region and that it has been around for a long time. Wreckingball as early as 2016 would report[ these sync issues](https://github.com/cartman-2000/Rocket-Plugin-Wrecking-Ball/blob/e5416cfa4408c345f3d1426f230f8a0586cf0194/DestructionProcessing.cs#L152). 


If I had to guess, this is just happening because too many barricades are being placed/destroyed and the index hits ushort max. It's fixed by restart simply because of the index being reset. 

You can/I have accidentally caused this issue before by simply creating and destroying a large number of barricades in a single region. I wouldn't call this an important issue though, as having daily restarts is pretty much necessary for unturned and if you have that many barricades in one region to begin with, #936 will be a bigger issue for your players.

**Comment by SDGNelson** [comment]
@PandahutMiku Thanks for this in-depth description! I had no idea that those lists were getting out of sync. I'll introduce vanilla warnings for those, and tidy up any code that is modifying the lists separately. Hopefully we can track this down and put an end to it!

**Comment by joeymisfit** [comment]
It's happened a few times for current servers I manage and previous servers I was admin on, entities tend to get up to 10k due to RP server aspect, and like Miku stated you salvage one thing and you get something completely different that you don't own in the area.

**Comment by PandahutMiku** [comment]
@joeymisfit  Yea, a full list of possible "Effects" from it is something like:
Invisible Barricades (If Server is enforcing movement, you can't see them but you'll get lagged back if you try to walk through them)
Unable to open storages/doors (but most of the time if the server is enforcing movement you can just walk right through)
Salvaging/wrecking one thing and destroying a completely unrelated thing

I've only ever seen this effect on Barricades, which would make according to the list desync theory.

**Comment by joeymisfit** [comment]
That makes sense, but I've also noticed that when workshops get removed from servers, and you have those items on a premade level backup, those items don't show but they still lag when walking on top of the area for the workshop item. So in all desync would cause both issues, perhaps?

**Comment by PandahutMiku** [comment]
> That makes sense, but I've also noticed that when workshops get removed from servers, and you have those items on a premade level backup, those items don't show but they still lag when walking on top of the area for the workshop item. So in all desync would cause both issues, perhaps?

From my experience, if you remove workshop from the server and load a map backup with those workshop items on it, the server would just remove them.

If you have structures/barricades in that the server has loaded but your client doesn't, as well as having the server enforce movement, then you would "lag" on top of the workshop item as the server is enforcing your position. 

A lot of players had this issue on Unturnov, where they wouldn't download Greece for whatever reason automatically and they would not see the main bunker at all but just float/desync around. This isn't the lists coming out of sync though, this is just the server enforcing the clients position.

**Comment by SDGNelson** [comment]
I've made several changes related to this for the next update:

1. During loading and saving the game will log the number of regions which were out of sync (if any), and a message to bug me about it. 

2. From reviewing all the code that touches these arrays I think the most probable issue is if spawning the buildable prefab failed. This can happen if the model was missing, bad asset, exception, etc. That case should be fixed now.

3. Scoped tests for catching this were added, e.g. this logs if tellTransformBarricade desynchronizes the arrays:

using(var test = new BarricadeRegionSyncTest(region, "tellTransformBarricade oldRegion"))

I'd recommend plugins manipulating the arrays to add those, but most likely it's either fixed now or we'll find a problem in vanilla.

**Comment by SDGNelson** [comment]
Note that in the next update barricade/structure IDs are persisted between restarts, so be careful with any code that is being injected into those load and save functions.

**Comment by surv0013** [comment]
Yes, the problem is that the synchronization between `BarricadeDate` and `BarricadeDrop` is broken. This only happens when there are many barricades on a server in one region.

I understand that now the barricade identifier will be stored on the hard drive? Well, that is, it will remain after the restart?

And you can add ready-made methods to remove the barricade, for example: `SendRemoveBarricade (Transform transform)` or `SendRemoveBarricade(uint instanceID)`?

I just think the plugins that remove the barricades are partly to blame. And if there is a ready-made method, there will be less problems, because now you need to collect a method to remove from shit and sticks...

**Comment by PandahutMiku** [comment]
> Yes, the problem is that the synchronization between `BarricadeDate` and `BarricadeDrop` is broken. This only happens when there are many barricades on a server in one region.
> 
> I understand that now the barricade identifier will be stored on the hard drive? Well, that is, it will remain after the restart?
> 
> And you can add ready-made methods to remove the barricade, for example: `SendRemoveBarricade (Transform transform)` or `SendRemoveBarricade(uint instanceID)`?
> 
> I just think the plugins that remove the barricades are partly to blame. And if there is a ready-made method, there will be less problems, because now you need to collect a method to remove from shit and sticks...

There is
`BarricadeManager.damage(Transform barricade, float damage, float times, bool armor, CSteamID instigatorSteamID = default (CSteamID), EDamageOrigin damageOrigin = EDamageOrigin.Unknown;`

`StructureManager.damage(Transform structure,Vector3 direction,float damage,float times, bool armor, CSteamID instigatorSteamID = default (CSteamID), EDamageOrigin damageOrigin = EDamageOrigin.Unknown)`
You can just pass in a very high value for damage, as wreckingball itself does.
As for the instance ID one, you could just loop through every single barricade/structure yourself until you find the one you want, then use the damage method to destroy it.

**Comment by surv0013** [comment]
> You can just pass in a very high value for damage, as wreckingball itself does.

Yes, I use this method and also saw it in WreckingBall , but it's a crutch

**Comment by SDGNelson** [comment]
Re how it's stored: each system maintains an unsigned int for an instanceID, and both the next available instanceID and each item's instanceID are kept in the savedata now.

Vanilla code doesn't keep an instanceID to instance lookup table, so that might be better left to how other code decides to use it. Ideally all of the functions would operate on instanceIDs or by component, but that rewrite's unlikely to happen anytime soon.

It looks like there are a few places which invoke tellTakeBarricade, so I will actually add a helper function for removing properly too.

**Comment by SDGNelson** [comment]
Have you guys seen any of the new warnings after the Friday update, or does it seem to be fixed now?

**Comment by PandahutMiku** [comment]
Happened once on our RP server, nothing of particular interest though happened in logs before or after this though:
[2019-12-08 14:19:14] 1 structure regions were out of sync while saving. Bug Nelson about this!
[2019-12-08 14:19:15] 1 structure regions were out of sync while saving. Bug Nelson about this!
Errored every save till Restart, it would be nice if in the future it said which specifically was out of sync.

I also realized Wreckingball logs specifically which regions are out of sync, and it is not just barricade regions at all.


RP Wise:
12/09/2019: Structures array out of sync
10/31/2019: Structure array out of sync
10/13/2019: Structure arrays out of sync
07/29/2019: Structure arrays out of sync
06/25/2019: Barricade Arrays out of sync
05/31/2019: Barricade Arrays out of sync
05/11/2019: Barricade Arrays out of sync

That being said, on a server which pretty much only builds inside of seattle, it's still pretty rare.

**Comment by SDGNelson** [comment]
Thanks Miku! Sure, I'll adjust it to log which region was out of sync while saving.
Is there anything in the log along the lines of:
Structure region out of sync! # # Context: ''

**Comment by PandahutMiku** [comment]
@SDGNelson Thanks for adjusting it, I found this
	Line 12265: [2019-12-08 14:11:32] Structure region out of sync! 63 62 Context: 'destroyStructure'
	Line 12266: [2019-12-08 14:11:32] Structure region out of sync! 63 62 Context: 'damage'


At the same time in Structure Logs
`[12/08/2019 02:11:32 PM] [12/08/2019 02:11:32 PM] [Info] John Harvey[76561198384094128] damaged [-20HP] 76561198969485958] structure (Pine Doorway), At: 566.925 37.691 -59.11652 (UseableGun - Dragonfang is equipped.)`
`[12/08/2019 02:11:32 PM] [12/08/2019 02:11:32 PM] [Info] John Harvey[76561198384094128] damaged [-20HP] 76561198969485958] structure (Pine Rampart), At: 566.925 37.691 -59.11652 (UseableGun - Dragonfang is equipped.)`


Might have been that, but there's nothing special about those structures

**Comment by SDGNelson** [comment]
Thanks for the details! This tells us a lot:
1. They came out of sync during destroyStructure while taking damage
2. The structure data was removed, but the model was not removed

Beyond that it's unfortunately not clear why destroyStructure failed, unless there was an exception while sending the RPC. I don't suppose there's any errors nearby in the log? 😕

**Comment by PandahutMiku** [comment]
The closest one (and only one I can see) around it is this
`[2019-12-08 14:10:36] Exception raised when RPC invoked askInput:
[2019-12-08 14:10:36] Exception has been thrown by the target of an invocation.
[2019-12-08 14:10:36]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at (wrapper dynamic-method) SDG.Unturned.SteamChannel.receive_Patch2(object,Steamworks.CSteamID,byte[],int,int)
[2019-12-08 14:10:36] Value cannot be null.
Parameter name: value
[2019-12-08 14:10:36]   at System.ThrowHelper.ThrowArgumentNullException (System.ExceptionArgument argument) [0x00006] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.BitConverter.ToInt32 (System.Byte[] value, System.Int32 startIndex) [0x00003] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at SDG.Unturned.Block.readInt32 () [0x00021] in <039feb9e1f4b46359cba1795872003e0>:0 
  at SDG.Unturned.Block.read (System.Type type) [0x000c1] in <039feb9e1f4b46359cba1795872003e0>:0 
  at SDG.Unturned.SteamPacker.read (System.Type type) [0x00000] in <039feb9e1f4b46359cba1795872003e0>:0 
  at SDG.Unturned.SteamChannel.read (System.Type type) [0x00000] in <039feb9e1f4b46359cba1795872003e0>:0 
  at SDG.Unturned.PlayerInputPacket.read (SDG.Unturned.SteamChannel channel) [0x00000] in <039feb9e1f4b46359cba1795872003e0>:0 
  at SDG.Unturned.WalkingPlayerInputPacket.read (SDG.Unturned.SteamChannel channel) [0x00000] in <039feb9e1f4b46359cba1795872003e0>:0 
  at SDG.Unturned.PlayerInput.askInput (Steamworks.CSteamID steamID) [0x001d2] in <039feb9e1f4b46359cba1795872003e0>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7ba07f088431485bb722f3b3373e87ee>:0 `

To make this a little less back and forth, I've sent you the log to your email (miku@pandahut.net)

**Comment by SDGNelson** [comment]
Thanks for sharing the log! Inside it looks like that askInput exception was one-off, but if it happened more frequently it might be a cause of disconnects because the input acknowledgement would not get sent.

For the patch I've made a few minor changes to the barricade and structure removal to error if something unexpected is happening e.g. bad region serverside.

**Comment by SDGNelson** [comment]
Have you still been running into this? Hopefully we can track down and fix the remaining case(s) shortly. I'm positive that the ones we fixed earlier would have been potential causes, so it should be rarer already.

**Comment by SDGNelson** [comment]
Update on this as mentioned when referring from issue #1448:

Based on the logs shared and the checks I put in place I think the remaining cause(s) are _probably_ due to plugins making unsafe calls from other threads. In the 3.20.2.0 update I put exceptions in a few places to ensure they were being called from the game tread, and already plugins have been hitting them and being fixed, so it bears seeing if there is a good place to put a similar check for barricades.

**Comment by Greenorine** [comment]
[2020-02-16 12:07:44] Structure region out of sync! 18 17 Context: 'destroyStructure'
[2020-02-16 12:07:44] Structure region out of sync! 18 17 Context: 'damage'
[2020-02-16 12:07:45] Structure region out of sync while saving: (27, 37)
Maybe problem after using plugin WreckingBall.

**Comment by charter0** [comment]
I think it is really related to Avi plugins somehow

**Comment by Bradler26** [comment]
Im getting this issue every few hours and it does seem to be related to Avi but the dev doesn't support any option to disable his plugins touching the level files and making their own. If anyone knows a bypass or a fix it would be greatly appreciated as I get this issue right after a map wipe and it happens every few hours. Although it could be something with destroying and placing many barricades as my server does do that quite often. Any help would be appreciated

**Comment by m0r3d** [comment]
i have it and i use avi plugins
