### ISSUE TITLE
askVehicle Spam Crashes The Server

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#125]
Various hacked clients have a crash server feature which still works after this update.

**Comment by Kr4ken-9** [comment]
Can confirm, as I said in #107 , any spammed packet will kill the server.

**Comment by aviadmini** [comment]
Current implementation of max packets it useless

Instead, one should limit RPCs from client by amount of calls defined per RPC. E.g. askVehicles should be called only once so more calls most likely mean that client is "hacked" (note the quotes)

These "hacked" clients are not even hacked. Unfortunately, more and more people get to know the easy way to "hack" the client

**Comment by SDGNelson** [comment]
The current max packets implementation is more to prevent spamming in general. These RPCs will have to be reviewed on a case by case basis. For the next patch I'll limit askVehicles to once per connection.

**Comment by aviadmini** [comment]
Limiting total packets it nonsense.

Exactly, case by case basis BUT with a general rule. I'm pretty sure none of the RPCs should be received 50 times per second.

Of course adding a nuclear exposive chewing gum spitter boss is much more important than working on game stability and hack and so-called-hack prevention

**Comment by SDGNelson** [comment]
It's not total packets, it's max packets per second per player. I think what you're asking for is what was implemented.

You sound a bit frustrated, but a balance between content, features and stability is important to maintain interest. For example when my focus was entirely on the editor and performance for several months last year player numbers dropped significantly.

**Comment by aviadmini** [comment]
I guess my "total packets" is ambiguous, so thanks for clarification. I did mean what you said and jumped to wrong conclusion based on the last update behavior (didn't look in the code because it's quite uncomfortable to decompile each version). 

Not sure how features/content can maintain interest when stability is messed up. But you probably know better than me ¯\_(ツ)_/¯

**Comment by SDGNelson** [comment]
> Not sure how features/content can maintain interest when stability is messed up. But you probably know better than me ¯_(ツ)_/¯

Do you have any particular stability suggestions in mind?

**Comment by aviadmini** [comment]
Alright, 
* Client crashes on startup on Windows 10 unless set compatibility mode to Windows 8 (reported by a lot of people)
* Client getting stuck on map loading screen when it doesn't get some specific packets from server or gets kick request before those packets
* FileNotFoundException on server if `Unturned/Bundles/Workshop/Content` and `Unturned/Bundles/Workshop/Maps` folders not exist. I know you can create them manually. However, running steamcmd verify seems to break it
* Netcode usage. I'm like 99.99% sure it won't be ever upgraded but worth a try. We all know the way it's done in Unturned is *khem* not the best *khem* 
* Most of servers lag at 48 players. Not officially supported here means it's not scalable. Rust can do 8-10x on same CPU. 

There's more, might check /r/unturned https://vgy.me/3Sojcf.png - although it needs time to browse through

Hugs <3

**Comment by SDGNelson** [comment]
- It seems to be related to a Windows 10 update, I'm going to be re-investigating updating Unity to a newer version which will hopefully be more compatible.

- I've added investigating getting kicked before loading in to my to-do, though that packet shouldn't get sent at that time. Do you know which specific packets they are?

- Unturned should automatically be creating those folders, but it might be that Steam thinks they don't exist because they're empty so it's removing them. Will investigate.

- Unfortunately you're right: Unturned 3's network architecture isn't going to significantly change at this point and doesn't scale very well.

**Comment by N1GHTPATROL** [comment]
Hello Nelson,

Regarding the game not loading on multiplayer (Stuck on Queue Pos 1) there are many issues that can be the cause, including map corruption or more commonly an issue with workshop content. It's also weird because commonly people can hear their surroundings but get to gaze at the queue pos 1 screen.

Involving 4.x servers, I would suggest that you invest a good amount of time to allow servers with 100+ people to function with no problem. This in my opinion would give players more confidence, seeing a server with for example 60/100 rather than 4/24 spread among 15 different servers. As a server owner, I dream of a day in which Unturned servers support hundreds of people, and honestly large servers would spark a whole lot more interest in Unturned, considering it is heavily multiplayer. Those are just my thoughts- please feel free to remark <3

**Comment by aviadmini** [comment]
No, I don't know which packet(-s) exactly causes it. And I'm not willing to figure it out

As for kick packets - you can ignore that, it was sent by a plugin. However would be nice if it worked

**Comment by Kr4ken-9** [comment]
[Example of packet spamming in use](https://www.youtube.com/watch?v=IiGNdnZYUGI)
