### ISSUE TITLE
Modded Vehicles have no passengers / Players

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#1250]
I am trying to get passengers of a mod vehicle like this:

```cs
InteractableVehicle vehicle = ...;
var passengers = vehicle.passengers
               .Select(d => d.player?.player)
               .Where(d =>d != null)
               .ToList();
```

However this seems to return empty for some reason (it works with vanilla vehicles).

I tried an alternative approach to get players based on the child components:
```cs
 var passengers = vehicle.gameObject.GetComponentsInChildren<Player>()
                .Select(d => d.channel.owner)
                .ToList();
```

However this yields the same result. It works for vanilla vehicles but not for the mod ones.

I don't know how the mod vehicle is made, as someone else made it. 
Any ideas what might cause this weird behaviour?

**Comment by SDGNelson** [comment]
If you spawn the vehicle into a vanilla map on your server and enter + exit it are there any errors in the log file? (vanilla to reduce noise from errors in other assets) It might also be worth checking vehicle.passengers.Length is what you expect.

**Comment by Trojaner** [comment]
There are no errors. 
I know for sure that the vehicle has passengers when running the code I posted.  
`vehicle.passengers.Length` returns 0 for mod vehicles while it returns 1 for vanilla vehicles.

It was not tested on a vanilla map tho.

**Comment by Trojaner** [comment]
Affected Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1630180602
Affected Vehicle ID: 43152

**Comment by SDGNelson** [comment]
I'm surprised there aren't any errors in that case. There is a passenger for each seat in the vehicle:

    _passengers = new Passenger[seatsTransform.childCount];

So it sounds like the vehicle has no seats. Asset validation does check that a seats transform exists, but not that there are >0 seats. I'll add a test for that in this coming update!

**Comment by Trojaner** [comment]
There was a mistake on my side, passengers count is 11. The previous count I have mentioned were passengers whose players are not null.

**Comment by SDGNelson** [comment]
The flow of updating a player in that array is:
1. askEnterVehicle
2. tellEnterVehicle
3. InteractableVehicle.addPlayer

If anything is interfering with those that might be a cause. It could also be worth binding onPassengersUpdated to see if that's called. I'll download the mod pack and see if anything jumps out at me.

**Comment by SDGNelson** [comment]
In singleplayer it seems fine, but the test server can't download due to IP restriction. I'll add a bypass for that to check out in the next build.

**Comment by K-Raptor** [comment]
I have removed the IP restriction for you. Hopefully, that helps.

**Comment by SDGNelson** [comment]
Thanks K-Raptor. I also added a private bypass so it won't be an issue in the future, feel free to re-enable the restriction.

Loading up on my vanilla test server, spawning in 43152 and entering the vehicle works okay. I added some logging and indeed the player is assigned to seat 0.

When is your code running?

**Comment by Trojaner** [comment]
It is running when the vehicle enters a specific area, so while it is driven.

**Comment by SDGNelson** [comment]
Perhaps the vehicle being queried is not the one being driven?
You could try removing all of the vehicles from the level (askVehicleDestroyAll) except for the one you are testing, and then log the passengers array each frame to see what's going on there.

**Comment by Trojaner** [comment]
We found a workaround for this issue.
I don't know why its like that, but after @K-Raptor made some changes to the models by following the official guide, it started to work again.

However it was the vehicle being queried and its really strange how it behaved.

**Comment by SDGNelson** [comment]
Glad that it's sorted out! Sorry not to have tracked it down.

What changes did you make @K-Raptor? If it was causing a big issue then I should probably add some warnings and checks for it.

**Comment by K-Raptor** [comment]
Thanks for taking the time to read this about this issue, Nelson. To clear things up, it was not the model at all. The issue was that I tend to use "Clips" like your tank example does in my vehicle objects yet I removed the original colliders located in the "Vehicle" object since the "Clips" were my colliders. Silly mistake on my behalf but seemed to work with Trojaners old plugin so it never mattered till now. But at least it wasn't a game bug.

**Comment by SDGNelson** [comment]
Ah, thanks for the followup. I wonder if in that case the lack of colliders was not overlapping with a trigger in Trojaner's plugin. I could add a warning if there are no colliders on the root gameobject, but I suspect there are plenty of workshop vehicles that purely use child colliders and work fine.

**Comment by K-Raptor** [comment]
No problem, I'd say you don't have to do anything. I don't think that there are many mods doing the method I chose to do which is good because I see now that it was a mistake. Anyways thanks for your time and have a good one!
