### ISSUE TITLE
[REQUEST] Reward_ID in items that uses "(use) animation"

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1251]
add option reward_id to items that does not use "Fisher" example

my idea was if animation called use is played then the item.dat check if there is reward_id then rewards the player. if true , if there no reward_id then gives other things  "water, food  ..."

My item is a chest and it have "Items called Devil fruits , Belly$ , other stuff ".  i did a spawn_table for the reward_Id . and i want my player if it uses the chest can give him random stuff. 
![dddd](https://user-images.githubusercontent.com/40163506/69636699-7509d800-1057-11ea-94de-6e6ffcc0c66d.JPG)

also if there is other way to do this help me :)

thanks

**Comment by SDGNelson** [comment]
If I understand correctly: you want an item that can be equipped in the player's hands, and when used is deleted but grants a random reward item to the player?

Which item type is it setup as? i.e. consumeable

**Comment by BREEZEXPVP** [comment]
yup "consumeable"

**Comment by SDGNelson** [comment]
There are several consumeable changes for the next update, so this makes sense to include as well. Thinking about whether there's a more generic structure for rewards like this i.e. trees also drop several items from spawn tables.
