### ISSUE TITLE
Ranger Sniper Ekho Alternative?

### ISSUE THREAD

**Issue by birdboy23** [SmartlyDressedGames/Unturned-3.x-Community#1254]
I say there should a ranger sniper rifle alternative to the ekho like how the timberwolf has the grizzly I say the matamorez should take up this role since it has 300m ranger already and not a good assault rifle. It would be better as a sniper rifle compared to an assault rifle.

**Comment by Mithallas** [comment]
https://steamcommunity.com/app/304930/discussions/2/

**Comment by SDGNelson** [comment]
Originally the Matamorez was considered a sniper rifle, but it was voted too powerful. In the older versions the Timberwolf and Grizzly were not available on the same maps, but nowadays they are thanks to airdrops and beacons. I'm open to making balance adjustments like this, but I think your best bet would be opening a discussion on the [forums](https://forum.smartlydressedgames.com/) and gaining community support for the proposal.
