### ISSUE TITLE
California Crash Log

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#1260]
My california map has been crashing a lot
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3903547/error.log)

**Comment by SDGNelson** [comment]
It looks like the crash is within Unity's physics, related to a missing DLL - perhaps PhysX. It might be worth validating the install?

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I'll re-open.

**Comment by Mithallas** [comment]
i have tried validating the install, no dice. it only happens with california and I have a couple other maps running off the same install

**Comment by SDGNelson** [comment]
Looks like a similar physics crash. There was an LTS update on the 11th that has some physics fixes, so I'll update to that soon and hopefully it will be fixed.

**Comment by SDGNelson** [comment]
Have you run into it after the 3.19 update? That one updated to 2018.4.14f1.

**Comment by Mithallas** [comment]
california has stopped crashing consistently, although all servers have been occasionally crashing.
i'll attach a couple crash logs
[error-jan7.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4049776/error-jan7.log)
[error-jan-11.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4049777/error-jan-11.log)

**Comment by SDGNelson** [comment]
Thanks for the log. That's reassuring that at least the map-specific crashes are better. I'll keep an eye out for future LTS releases, and using the 2019.x mono has helped too.
