### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by AlexBread17** [SmartlyDressedGames/Unturned-3.x-Community#1266]
So a few months ago me and one of my friends discovered a bug you can do and disconect other players from a server, in order to make the bug you have to switch clothes really fast (t-shirts), you wear one an you put the other one in the left top corner of your inventory and you switch them really fast, this will sure make lag on the server but using a macro will make your  pc go to 1 fps and other players will experience extreme lag and some will lose conection.This was discovered by mistake on a RP server. I hope this gets resolved :)
AIex#3226

**Comment by joeymisfit** [comment]
I think I remember that bug, isn't it where you craft several cloths, etc in your inventory real fast?

**Comment by SDGNelson** [comment]
Thanks for the report! Fortunately this will be fixed in this week's update: swapping clothes was not rate-limited prior to the update.

**Comment by AlexBread17** [comment]
I'm prud i did something ;)
