### ISSUE TITLE
Is there a option to enable particules with mesh character replacement?

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1269]

**Comment by SDGNelson** [comment]
Like attach a particle system to the character mesh? One indirect way to do this would be including particle systems in the other clothing items.

**Comment by BREEZEXPVP** [comment]
i attached the Particle System with in the bones 
example : 
if i want to attach PS in Right_Arm & Left_Arm. i don't think that will happen with item clothing
