### ISSUE TITLE
Kicking from steam group doesn't go on effect until relog to server

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1270]
Not sure if anyone reported this earlier, but if possible to fix it, that would be great because players abusing this to salvage their ex-teammates bases

**Comment by SDGNelson** [comment]
If frequent add/removal from groups is a concern then the dynamic groups feature is probably a better option. The gameserver doesn't get a callback when Steam group membership changes (would be a lot for groups with hundreds of thousands of members), so it would have to be periodically checking each player's membership.
