### ISSUE TITLE
Help please. Valve in Unturned! Urgent to read!

### ISSUE THREAD

**Issue by Lordev-Steam** [SmartlyDressedGames/Unturned-3.x-Community#1271]
Dear game creators Unturned, my account was hacked while I was recovering it, I got a VAC lock, I have 1.800+ hours in the game, Untunred 2 is also available, I don’t know how to prove that my account was hacked, my name is Dima, I'm 14 years, I am from Russia, really love your game, and for this I ask you to remove the VAC game lock. I am attaching to my letter: 1) A link to the Steam profile https://steamcommunity.com/id/7656119808556804/
2) Steam ID 64 76561198085568097
I really love your game, and this problem prevents me from playing, help !! The support service is not responding, I don’t know where to write!

**Comment by Spebby** [comment]
Not the place for ban appeals. Go to Valve about VAC bans, though they're unlikely to repeal them.

**Comment by SDGNelson** [comment]
If your case is legitimate, then I'm sorry they cheated on your account. :(

Unfortunately all bans are final. Otherwise cheaters would always contact Steam support after they got banned claiming their account was hijacked / stolen.

**Comment by Coopyy** [comment]
im impressed if thats actually a vac ban
only way i know how to do that is cheatengine
