### ISSUE TITLE
Render Issue 2

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#1273]
For a while I have noticed there are always large frames drops when rendering large bases (maybe 500+ barricades+structures?), even with higher end gfx cards. Large groupings of small bases can also cause this. Large maps with many buildables all over dont drop frames, just has lower consistent frames which is probably to be expected. I did search issues history and found another who described something similar, although it was backlogged and closed a few months later without explanation. If spreading the rendering over a few frames doesn't work, perhaps the server can carry some of the load somehow?

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/164

**Comment by PandahutMiku** [comment]
I think you're talking about #936. Nelson *eventually* plans to fix it, but it is a high order.

**Comment by SDGNelson** [comment]
Thanks Miku, that's the one I was going to link as well. 
The main related to-do has an issue open here, but there's no ETA yet: #1233 
Closing for now, but I do agree it is a problem.
