### ISSUE TITLE
Error in server logs

### ISSUE THREAD

**Issue by Stralix** [SmartlyDressedGames/Unturned-3.x-Community#1279]
[2019-12-07 11:50:23] DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.

After this error, the server crashed.

**Comment by SDGNelson** [comment]
There were some plugin developers asking about how to use DontDestroyOnLoad here recently. I would suggest trying to disable a few plugins at a time to figure which one is causing the crash.

**Comment by surv0013** [comment]
> There were some plugin developers asking about how to use DontDestroyOnLoad here recently. I would suggest trying to disable a few plugins at a time to figure which one is causing the crash.

It's UnturnedPlayerComponent from RocketMod on Linux servers

**Comment by SDGNelson** [comment]
Checking back through older issues: the DontDestroyOnLoad warning mentioned here has been removed in the next update of the officially maintained RocketMod version.
