### ISSUE TITLE
Barricade state update

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#1280]
When using BarricadeManager.updateReplicatedState on doors (possibly on some other barricades/structures) after 3.19.19.0 update they're becoming not interactable to salvage or open/close even when you've not made any changes to barricade state

**Comment by SDGNelson** [comment]
In the previous update doors were changed to disable their collision while someone is overlapping the colliders. Is a vehicle / player overlapping them?

**Comment by Ankumo** [comment]
Nope, there was nothing that might be blocking the door. Sometimes it's causes player recov to happen if you move close to this bugged door, but i can't remember how I've managed to get that and I've experienced this before 3.19.19.1 patch. Although you've not did anything to barricade colliders in that patch AFAIK?

**Comment by Ankumo** [comment]
I've tested raycasting to the doors (freshly spawned and the bugged one) and it showed that it's losing navmesh and hinge components after updating its state. Maybe it happens because the door is reopening, idk

**Comment by SDGNelson** [comment]
Ah, you're completely right. Thanks for the report and description! It should be fixed in today's patch.
