### ISSUE TITLE
BoxColliders issue.

### ISSUE THREAD

**Issue by megoesrawr** [SmartlyDressedGames/Unturned-3.x-Community#1282]
![image](https://user-images.githubusercontent.com/7830406/70380034-14a25280-1903-11ea-8440-954163775e13.png)

**Comment by SDGNelson** [comment]
It's an annoying warning due to the left-handed character hitboxes. It should not have any negative side effects, but there is no way to turn it off sadly. Unity added it a few years back and I even asked them about disabling it. 😢

**Comment by megoesrawr** [comment]
Ah. Thank you for explaining.
