### ISSUE TITLE
Queue Pos is bugged

### ISSUE THREAD

**Issue by bjorn29922** [SmartlyDressedGames/Unturned-3.x-Community#1285]
Everytime there is 24 players online on the server and you go on to try to join then you have a queue position but the problem is that when somebody leaves the server you are then still stuck in the queue position and cant join if you cancel it and try to join again

**Comment by SDGNelson** [comment]
I double-checked by running a full server and joining with some bots in the queue. After the bots joined it put me in. Do you have any queue-related plugins?

**Comment by bjorn29922** [comment]
I dont think so

**Comment by bjorn29922** [comment]
AviAdminTools

**Comment by bjorn29922** [comment]
Can that be it

**Comment by SDGNelson** [comment]
It could be, but that one is commonly used I think. The next time it happens could you send me the Server_X.log file from the Logs folder please? It might have some useful errors. I reviewed the queue functions and don't see any obvious bugs, but I'll keep an eye out.

**Comment by bjorn29922** [comment]
Oke

**Comment by SDGNelson** [comment]
Each log is reset during server startup, so if it the server has not been restarted yet that log is perfect. If you can attach it and send it to nelson@smartlydressedgames.com that works well.

**Comment by bjorn29922** [comment]
I use a server host lyhme So i think i can find it in the logs there

**Comment by bjorn29922** [comment]
[Rocket.1575759825.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3952445/Rocket.1575759825.log)

**Comment by SDGNelson** [comment]
Apologies that the "next update" label has been left on this for a while. If I recall correctly this issue lead in part to several changes in the past few updates which prevent plugins from screwing up the main thread networking. Has this been less prevalent recently?

**Comment by bjorn29922** [comment]
The queue pos is fixed for me

Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________

**Comment by SDGNelson** [comment]
I'm glad to hear that! Sorry again for the long process. Thanks for the confirmation, and feel free to comment if needed and I'll re-open.
