### ISSUE TITLE
Speedtree Billboards ignore Fog on Forwards Rendering

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1286]
May just be an issue with modded speedtrees, but none the less an issue.

**Comment by SDGNelson** [comment]
Double-checked and they work in vanilla, so is it one of the following two?
1. Exponential fog shaders should not be stripped in Unity Graphics settings. This should be setup by importing Project.unitypackage.
2. Billboards should be using the Framework/SpeedTree Billboard shader.

**Comment by Spebby** [comment]
After testing more this seems to have been an isolated case. I no longer have access to the Trees that were having this issue, but I can assume a few things based off of circumstance.

1. Map sizes may affect billboards differently, as fog may un render before a billboard does, this case took place on an Insane sized map, so that might factor into it.
2. The trees were Unity 3ds, so perhaps that may be the culprit?
3. Asset_Bundle_Version 2/3 may have been missing from the .dats.

whenever I have the chance I'll double-check and depending on what I find I'll either continue the investigation or close the thread.
