### ISSUE TITLE
destroyed vehicles not despawning after recent updates?

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1287]
not sure if this only happening for me due to some plugin. Same happening on two servers. Worth to mention that only plugin which was interacting with vehicles was already disabled yesterday due some crashing issue.

**Comment by SDGNelson** [comment]
There were some changes to the behavior a couple months ago, but nothing recently.

Is it that the vehicles are being destroyed, but no replacements are getting respawned? Or are they not being destroyed?

**Comment by baranmod** [comment]
I mean, destroyed vehicles not despawning (stay burning until I remove them manually). But it might be vehicles.dat corrupted for some reason. I removed it and will see if its still happening

**Comment by baranmod** [comment]
Just checked again, still happening (found a lot of flaming, destroyed vehicles)

**Comment by SDGNelson** [comment]
Respawn_Time is the duration in seconds before a flaming vehicle is destroyed. Is it set to a high number?

 I'll double-check in vanilla.

**Comment by baranmod** [comment]
its set to 300 seconds

**Comment by SDGNelson** [comment]
On a vanilla test server with respawn timer set to 5 seconds the burning vehicles seem to get destroyed properly. Perhaps the game mode is different from the config (easy vs normal), or a plugin is adjusting something? Also, if the level type is arena then vehicles don't respawn.

**Comment by baranmod** [comment]
its set to easy and double-checked config, timer on easy is set to 300. Also, not arena. But if it works as supposed on vanilla, I think it might be some plugin after all. Will take a deeper look later. Thanks anyways :)

**Comment by SDGNelson** [comment]
Alright. Good luck! I'll leave this open until we know.

**Comment by baranmod** [comment]
That was because of no vehicle spawns were on the map. I guess when there are no spawns server doesn't need to remove destroyed vehicles to spawn new ones?

**Comment by SDGNelson** [comment]
Ah, okay I will adjust that to despawn vehicles on maps with no spawnpoints.
