### ISSUE TITLE
Zombie Manager add new zombie network replication

### ISSUE THREAD

**Issue by Pigeon-cmd** [SmartlyDressedGames/Unturned-3.x-Community#1289]
If my analysis is correct, it seems currently new zombies cannot be created and sent to players. The system was seemingly not intended to do this, but it would be very nice plugin-wise if we could create new zombies and notify all clients about them.

`public void createReplicatedZombie(byte newType, byte newSpeciality, byte newShirt, byte newPants, byte newHat, byte newGear, Vector3 newPosition, byte newAngle)`

or if you don't want to go through the trouble of finding the region for us based on position, just make us input the region num.

And of course, because I am asking to be able to create a replicated one, it would be nice if we had a simple method to delete a zombie completely and replicate such.

Thanks for your time!

**Comment by SDGNelson** [comment]
You're right that spawning and deleting extra zombies isn't supported yet. All vanilla code currently respawns a dead zombie from the pool and adjusts properties as needed. It might be supported depending the extent to which other systems are rewritten for the netcode update in 2020, but for the meantime this is unlikely.
