### ISSUE TITLE
Interactable object to open dialogue

### ISSUE THREAD

**Issue by Vulby** [SmartlyDressedGames/Unturned-3.x-Community#129]
Quest only on certain difficulties can be useful for hard quest you make and actually want to be a challenge and that the dialogue option only shows when on the said difficulty

A devkit box which when interacted or walked in to a dialogue pops up eg can be used if you want a radio with a npc on the other side which gives you quest

Option to set weapon: “Safety” “Ready”

**Comment by MoltonMontro** [comment]
> A devkit box which when interacted with dialogue pops up eg can be used if you want a radio with a npc on the other side which gives you quest

I feel like this is already possible.

**Comment by Vulby** [comment]
The devkit box would use a dialogue id not a condition/effect id

**Comment by SDGNelson** [comment]
I've definitely had my share of frustrating data entry experiences. Unfortunately some user errors are hard to detect e.g. conditions is 0 when it should be > 0, but I'll double-check what other things could be logged.

**Comment by Vulby** [comment]
I don't know if its possible but if you can make it show which line there was an error would be enough to help people out

**Comment by SDGNelson** [comment]
Renamed issue to the remaining feature
