### ISSUE TITLE
Allow disabling icons of freezing, etc PlayerLifeUI

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#1290]
![image](https://user-images.githubusercontent.com/48765566/70390137-fa4ba000-19fa-11ea-8027-94f1e1077c4d.png)

Can you add an option to remove the icon of starving, dehydrated or freezing?
...

**Comment by Greenorine** [comment]
Hello, can you say please how you made progress bar?

**Comment by SDGNelson** [comment]
Interesting custom UI!
I'll plan to make those adjustable similar to the rest of the HUD in the next main update (probably January), as well as controllable from the server.

**Comment by Paradox304** [comment]
@SDGNelson do you have plans to implement this?

**Comment by joeymisfit** [comment]
+1 This would be amazing for roleplay servers!

**Comment by SDGNelson** [comment]
Sorry - I must have missed the issue when preparing that update. Since I said I would do it, I will mark this Next Update so that it gets addressed.

**Comment by Paradox304** [comment]
Thanks!

**Comment by DiFFoZ** [comment]
Also, can you implement #1411 ?

**Comment by Paradox304** [comment]
Will the possiblity to disable health UI and gun UI that we can already do through map config.json be available to do through plugins when this is implemented?

**Comment by SDGNelson** [comment]
Some parts of the UI got minor reworks for this in the next update. The following widget flags were added:

	/// <summary>
	/// Enable health meter in the HUD.
	/// </summary>
	ShowHealth = 1 << 5,

	/// <summary>
	/// Enable food meter in the HUD.
	/// </summary>
	ShowFood = 1 << 6,

	/// <summary>
	/// Enable water meter in the HUD.
	/// </summary>
	ShowWater = 1 << 7,

	/// <summary>
	/// Enable virus/radiation/infection meter in the HUD.
	/// </summary>
	ShowVirus = 1 << 8,

	/// <summary>
	/// Enable stamina meter in the HUD.
	/// </summary>
	ShowStamina = 1 << 9,
		
	/// <summary>
	/// Enable oxygen meter in the HUD.
	/// </summary>
	ShowOxygen = 1 << 10,

	/// <summary>
	/// Enable icons for bleeding, broken bones, temperature, starving, dehydrating, infected, drowning, full moon,
	/// safezone, and arrested status.
	/// </summary>
	ShowStatusIcons = 1 << 11,

	ShowLifeMeters = ShowHealth | ShowFood | ShowWater | ShowVirus | ShowStamina | ShowOxygen,

**Comment by educatalan02** [comment]
Vehicle related HUDs should be done too please 👍

**Comment by XanderCodes** [comment]
I believe that the game chat is the only thing we can't hide with widget flags for custom UI's... that would also be really nice!
