### ISSUE TITLE
Some problem with images from URL

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1291]
I used SendUIEffectImageURL and got some white lines near images. What is that? Images haven't it. 
![2-O8to3bmVY](https://user-images.githubusercontent.com/41028671/70394008-4e15b380-1a12-11ea-8a47-790d28bfcff9.png)

**Comment by erik7302** [comment]
If u are using .PNG try using other image format or try changing the image component settings
