### ISSUE TITLE
Some items became impossible to pick-up

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1294]
Have no idea why, but got multiple reports from multiple players that they can't take loot from the ground sometimes. There is nothing specific to those items (happening for various items) and they are visible on ground. But isn't visible even in "nearby" window.

**Comment by rube200** [comment]
I can confirm this and for example if a player dies too close to a wall with many items some get stuck inside it, even making it impossible to pick up.

**Comment by SDGNelson** [comment]
Has that still been happening today? In the other patch I disabled the LoS test for pickups because I realized it had been disabled before because the server doesn't know where the client thinks it fell to.

**Comment by baranmod** [comment]
Didn't get any reports since last patch, will let you know if it happens again
