### ISSUE TITLE
Skycrane broken?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1295]
I'm not sure if it was the latest update but for me and a few others that had tested both in single player and in multiplayer; skycranes aren't able to pickup vehicles anymore and I've noticed the same about modded towtrucks they are failing to grab a hold of vehicles.

**Comment by SDGNelson** [comment]
I just gave it a quick go in singleplayer using the Skycrane and it seemed to work okay. It's bound to the "Other" key which does a lot of stuff so maybe that got rebound? Though if it's happening for a few people if you can send me the Client.log file from the Logs folder after it happens again I'll take a look!

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I'll re-open.

**Comment by SDGNelson** [comment]
Sorry for my negligence on this one. It should be fixed in the next update! Sigh.
