### ISSUE TITLE
Troubleshooting, 4+ months crashing on large maps

### ISSUE THREAD

**Issue by jackthefrag** [SmartlyDressedGames/Unturned-3.x-Community#130]
I apologize if this is the wrong place for my issue, if so i'd gladly take it down.

My issue is crashing on large maps and highly modded servers. My PC specs are Pentium Dual Core, E5500 2.8Ghz, 4GB Ram, 32x Win10, graphics card 1Gb Asus (GDDR5 7750). I desperately need help on what i should upgrade/change, in order of importance.

Thanks in advance! I really do appreciate any sort of help.
[Attached is a crash folder for Hawaii on SP]
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1548524/error.log)
[output_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1548525/output_log.txt)

**Comment by Trojaner25** [comment]
This is a unity issues.
Related: https://forum.unity.com/threads/u5-3-error-symgetsymfromaddr64-getlasterror-attempt-to-access-invalid-address.413565/

Apparently this issue seems to happen when you do not have enough free RAM which explains why it only happens on large maps with lots of workshop.

**Comment by jackthefrag** [comment]
You're beautiful. I had a 64x but sent my PC to some shifty lad when i got a BSOD, so he downgraded me to 32x which i realised later on lol. Anyhow, I really appreciate your long ass detailed reply fam, I highly support your work and use it on a daily bases :)

**Comment by jackthefrag** [comment]
Just noticed your 20 edits, thank you for your dedication!
