### ISSUE TITLE
Allow_Per_Character_Saves duping items

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1303]
When I connect with different character - some of the items are on top of each other in inventory and when I drop them, it doesn't drop from inventory, when I relog again, I can drop those items again (Allow_Per_Character_Saves is set to false)
![image](https://user-images.githubusercontent.com/14231707/70664113-70a60780-1c72-11ea-84e5-606d7d76fb24.png)

**Comment by SDGNelson** [comment]
Sorry I can't believe I missed your post this morning! 🤦‍♂ 

Are there any plugins intercepting the ESteamPacket.CONNECT message, or interfering with the character ID? Allow_Per_Character_Saves simply sets the player's character ID to zero when they join the server.

**Comment by SDGNelson** [comment]
Did you end up finding the cause?

**Comment by baranmod** [comment]
I wiped player data on test server and seems it fixed this issue. Can't tell if its related to some plugin or not tho, but most probably it is as I don't see any more reports related to it.

**Comment by SDGNelson** [comment]
Glad that it worked itself out then, it must have been a plugin.
