### ISSUE TITLE
InteractableSentry power

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1306]
I was looking through the sentrys code and found this:

```
		public bool isPowered
		{
			get
			{
				return !(this.power == null) && (!this.sentryAsset.requiresPower || this.power.isWired);
			}
		}
```

Shouldn't it be:
```
		public bool isPowered
		{
			get
			{
				return !this.sentryAsset.requiresPower || (!(this.power == null) && this.power.isWired);
			}
		}
```

**Comment by SDGNelson** [comment]
At first I thought you must be right, but it turns out "power" is a separate component that should always be present (even if requiresPower is false). It also looks like the compiler has optimized that auto-property, as here's how it appears in the source:

	public bool isPowered
	{
		get
		{
			if(power == null)
				return false;

			if(sentryAsset.requiresPower)
			{
				return power.isWired;
			}
			else
			{
				return true;
			}
		}
	}
