### ISSUE TITLE
Sentry bug

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1307]
So I found this a couple month ago and I'm not sure if it's fixed. When you build a hostile sentry in game and then create an in-game group, when you invite someone, the sentry will still shoot the person even though they are in the same group as you. Is this issue fixed?

**Comment by joeymisfit** [comment]
From what I know, I believe the in-game group has to be created before sentries are placed.

**Comment by AwesomeGOAT** [comment]
Yea, and newly joined group members will be shot

**Comment by SDGNelson** [comment]
joeymisfit is right that the sentry is associated with your group at the time it was placed. This has pros and cons, but a workaround is to pick it up and put it back down if the group needs updating. One reason for not updating the group is if a member is helping build the base, but is then kicked from the group, it would be unfortunate to have the sentries begin attacking the original members.
