### ISSUE TITLE
Rich Text Problem

### ISSUE THREAD

**Issue by Dolphinchik** [SmartlyDressedGames/Unturned-3.x-Community#1309]
When using rich text in chat, it does not disappear after a while, why is it done and can it be controlled???

I just need to use rich text in my plugin to simplify the chat on the RP server, but I can not use color text, because messages simply "hang" in the chat. If there is opportunity, tell me please ♥

**Comment by PandahutMiku** [comment]
#396

**Comment by Dolphinchik** [comment]
But we moved to a new version of unity, I'm not sure that the problem remains. Thanks for the answer

**Comment by Dolphinchik** [comment]
It may be better to abandon the attenuation and just remove posts than to leave them

**Comment by PandahutMiku** [comment]
I don't think much has changed there nor has nelson probably updated the UI from unity 4 Imgui. I hope it can be fixed though.

**Comment by Trojaner** [comment]
This is at least the 3. or 4. issue regarding that. Nelson said it is not fixable because he is using Imgui. However in DMs he told me that he might move to the Unity UI system which would make fading text possible for rich messages.

**Comment by Dolphinchik** [comment]
Thank you for the answer, sorry for the duplicate question
