### ISSUE TITLE
Load assets on demand

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#131]
As far as I know Unturned loads all assets at start (for built-in assets?) / joining server (for workshop stuff).

My suggestion is to load assets dynamically at runtime / ingame. For example do not load a car's model until that car is near to you. I do not know if you can unload models / assets in Unity, but that could also be used to unload assets which are not in near render distance anymore. A placeholder (e.g. car model with really basic details) asset can be used for assets which are far to the player.

This should drastically reduce RAM usage but would probably increase CPU usage.

Pros:
- Faster joining to servers as workshop assets do not have to load (download still applies)
- Drastically less RAM usage and fixes issues like #130 
- Reduces minimum RAM a lot

Cons:
- Higher CPU / IO usage when new assets load
- Could cause lag when suddenly a lot of new assets begin to load (e.g going to RP cities which have a lot of different cars) [does not apply if loading is async]

Plugins should not be affected by this as servers should still load all assets on startup, not dynamically like described here.

**Comment by SDGNelson** [comment]
Some of the newer features e.g. Landscape support runtime load/unload, but it's unlikely the rest of the game will be overhauled for dynamic loading. Objects however somewhat support it, but ran into a few issues with texture corruption on different hardware.
