### ISSUE TITLE
Barricade region out of sync

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1312]
![изображение](https://user-images.githubusercontent.com/41028671/70851920-50b65400-1ebd-11ea-8e70-7db3577eba5c.png)

**Comment by TheCubicNoobik** [comment]
Related to #1249

**Comment by SDGNelson** [comment]
Thanks for the update! Cubic is right that it's #1249. Unfortunate that it's still happening then...
