### ISSUE TITLE
Steamcalls

### ISSUE THREAD

**Issue by Edsparr** [SmartlyDressedGames/Unturned-3.x-Community#132]
I assume there is No easy way of cancerkongressen steamcall. I'm aware it might not even be possible with how steamcalls are setup. But a way of canceling steamcalls would b amazing. OnTriggerSend(normal parameters, ref bool cancel)

**Comment by Trojaner25** [comment]
how to break RocketMod 101

**Comment by Edsparr** [comment]
As i thought

**Comment by SDGNelson** [comment]
Which rpc are you hoping to cancel?

**Comment by wandereri** [comment]
for example for tellTakeStructure to cancel the destruction of the structure

**Comment by SDGNelson** [comment]
The next update now has salvage requested events that allow you to prevent salvaging
