### ISSUE TITLE
See Region Lines

### ISSUE THREAD

**Issue by Pigeon-cmd** [SmartlyDressedGames/Unturned-3.x-Community#1320]
This is an odd request, Please let us work around barricade/structure region and have a special camera mode (f8) to see the actual lines of these regions, minecraft-style.

It would be nice if they showed up on the map too, but completely unnecessary.

Thank you for your time!

**Comment by Pigeon-cmd** [comment]
> > if you cannot fix Unturned's fundamental flaws like the Barricade/Structure region system
> 
> People really became rude here and lost all sense of respect. This isn't how you request features for a free game.
Sure, I edited it. I didn't mean to be rude, was just too blunt. I do not mean to blame Nelson in anyway, he made this game while he was still learning. The barricade/structure region issues are just too deep and late to fix, and it would be nice if we had a way to better work around them.

**Comment by SDGNelson** [comment]
Reworking these systems is going to be my main goal in 2021: https://blog.smartlydressedgames.com/unturned-in-2021/
