### ISSUE TITLE
AutoSave error

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#1326]
The server will auto save and this error will appear. The server stops accepting players. Has happened handful of times in the past few weeks. Its not consistent so i didnt know if this was a rocketmod issue or not...  autosave interval set to 15 minutes. 
![Screenshot_2](https://user-images.githubusercontent.com/35383961/71040797-72018500-20f5-11ea-9878-93245c4cd4c6.png)

**Comment by Johnanater** [comment]
I had weird issues with the server doing this. It's inconsistent and restarting "fixes" the issue. I made a simple plugin that will simply shutdown the server (which in my case gets automatically restarted) if it fails to save.
https://github.com/Johnanater/SaveCrash/releases

**Comment by SDGNelson** [comment]
Sorry for my delay over the holidays. It doesn't look like the exception is in patched code so it's likely vanilla, but the code in save() isn't too suspicious. I will bulletproof it though just in case.
