### ISSUE TITLE
Renaming childs of UI

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1327]
Ability to rename childs of UI(renaming button or a text)

**Comment by SDGNelson** [comment]
Why? I don't see how it would be useful. If you mean changing the text in a Text Component then there is an RPC for that at the moment.

**Comment by Trojaner** [comment]
I am not too much into UI development but maybe he wants to prevent others from using his UI this way?

**Comment by Sl4vP0weR** [comment]
If u add this function - I be able to create one UI for many of my tasks.

**Comment by Sl4vP0weR** [comment]
@SDGNelson please check

**Comment by SDGNelson** [comment]
From your "reuse for many tasks" I wonder if you have something like a modal "yes" "no" box in mind that would rename the buttons to "deleteItem_Yes"? For the moment I wonder if it would work to just track per-player which of your menus they have open, and deal with the button callbacks based on that?

**Comment by Sl4vP0weR** [comment]
Yeah, as I think - u understood me, I'm just need rename "deleteItem_Yes" to "addItem_Yes"

**Comment by SDGNelson** [comment]
From the sounds of things what you could do then is have a unique ID for your buttons like Sl4vP0weR_Yes and Sl4vP0weR_No, and then on the server you can keep track of the context. For example a dictionary matching Players to a Context. Like SDGNelson -> AddItemContext.

**Comment by Sl4vP0weR** [comment]
No, @SDGNelson, u dont understand me, I want to call UI for player and change the name of button.
For example: Player go to the point and recieve an UI with 2 buttons "JOB_Yes", "JOB_No", I have many points like this & I dont want to create many of UIs for every point. If I will be possible to change "JOB_Yes" to "JOB2_Yes" its will be perfect.

**Comment by SDGNelson** [comment]
You don't need to rename the buttons to achieve that. You only need to know server-side that you sent them the generic menu with JOB1 or JOB2 context. When you get the Yes or No callback then you check which context they were in.

**Comment by Sl4vP0weR** [comment]
> You don't need to rename the buttons to achieve that. You only need to know server-side that you sent them the generic menu with JOB1 or JOB2 context. When you get the Yes or No callback then you check which context they were in.

@SDGNelson , I understand this, but I dont think what is will be more easily than just renaming when sending ui.
