### ISSUE TITLE
Event for unlocking vehicle using carlockpick item

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#133]
It's sorta painful to make that event ourselves

Would be awesome for RP to have it, e.g.:

Ready to use implementation:

Add to `VehicleManager`
```csharp
    public delegate void VehicleCarlockpicked(InteractableVehicle vehicle, Player player);

    public static event VehicleCarlockpicked OnVehicleCarlockpicked;

    internal static void triggerCarlockpick(InteractableVehicle vehicle, Player player) {
        if (OnVehicleCarlockpicked != null) {
            OnVehicleCarlockpicked(player, vehicle);
        }
    }
```

In `UseableCarlockpick::simulate` method either right after unlocking vehicle or after `useStepA` call add the following:
```csharp
        VehicleManager.triggerCarlockpick(this.vehicle, this.player);
```

**Comment by SDGNelson** [comment]
I went to go implement this and realized InteractableVehicle onLockUpdated already exists - it should be getting called on the server. What did you have in mind to use this event for/how does it behave differently than the current one?

**Comment by aviadmini** [comment]
I couldn't find a way to figure out whether vehicle was unlocked using stealy wheely and know who exactly unlocked it. That's why I believe it can make *some* difference ;)

**Comment by SDGNelson** [comment]
In the next update I've added VehicleManager.onVehicleLockpicked which notifies you of lockpicking and optionally allows you to cancel the lockpicking.
