### ISSUE TITLE
Something that is not fully implemented in code

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1330]
I have problems on the server with NPC quests

I found these errors in the logs:
![image](https://user-images.githubusercontent.com/46658857/71313158-96cf6280-243d-11ea-862a-8e5c4bb3dfec.png)

look like something that is not full implemented in the code, its come from NPCQuestCondition.applyCondition()

**Comment by SDGNelson** [comment]
This depends on the specific quest asset. Something is trying to modify quest state in an unexpected way. In the next update I'll adjust that log message to include which specific instigator is causing the problem

**Comment by MrGoBi** [comment]
SDGNelson, Thank you

**Comment by MrGoBi** [comment]
SDGNelson, I do not want to open a new topic, so I’ll ask here. I made a car with a hook component. In single player, everything works well, but not on the server. I added a clip to the prefab, but that didn’t help either.

**Comment by Trojaner** [comment]
You should open a new issue so they can be categorized and closed separetely
