### ISSUE TITLE
Mac crashes on joining server

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1333]
Couple players reached out to me with some problem (both on OSX). Basically, their game crashes when joining server. Got log file from one of those (attached). I can't tell if this only mac related issue, but pretty sure there are more players using mac who are playing without much of issues
[Client (4).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3993317/Client.4.log)

Update: apparently something in player data gets corrupted (removed it and player can now join without problems)

Update 2: Removing data was a temporary fix, player crashed again while playing and now crashing while trying to join a server

**Comment by baranmod** [comment]
did some digging and apparently thats because of some bundles which weren't re-exported on unity 2018

**Comment by SDGNelson** [comment]
Re-bundling them in 2018 resolved the crash? Somewhat related: this past Friday I updated the Hawaii and Greece asset bundles to 2018.4

**Comment by baranmod** [comment]
Didn't try yet, but I assume it should as from what I learned this line is related with unity clients crash (on mac) if mac bundles aren't rebundled on new unity version (2017>2018). Will update my bundles later and update this issue if fixed or not.

**Comment by SDGNelson** [comment]
Did updating those bundles fix the problem?

**Comment by baranmod** [comment]
Yeah, I believe it did. At least, Im not getting any reports related to that anymore

**Comment by SDGNelson** [comment]
Thanks for the confirmation!
