### ISSUE TITLE
Starting server causes #MASTER_BUNDLE_PROGRESS error even though only one unturned process runnning?

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#1338]
<img width="312" alt="mstsc_lZP40IQnIe" src="https://user-images.githubusercontent.com/35437320/71356687-16dd0000-25d7-11ea-8ba0-c0de36ca295a.png">

**Comment by tankirules** [comment]
I do believe that this normally happens when you try to start the same exe twice

**Comment by SDGNelson** [comment]
It looks like the localization files are not loaded, so it's falling back to the key. Was a different language specified, and/or are the English files present?

**Comment by tankirules** [comment]
> It looks like the localization files are not loaded, so it's falling back to the key. Was a different language specified, and/or are the English files present?

I do not know of any changes to the language, it was always english, and there seems to be english localization in the folder.

**Comment by SDGNelson** [comment]
Hmm the game might be doing something dumb thinking one of the command-line arguments is a language switch. I'll add some error messages related to this for the next update to protect against not loading a language

**Comment by TheCubicNoobik** [comment]
This happened when I make a typo in a .module file.
