### ISSUE TITLE
The transport hook does not mount cars on the server

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1339]
I made a car with a hook component. In single player, everything works well, but not on the server. I added a clip to the prefab, but that didn’t help either.

**Comment by SDGNelson** [comment]
Uh oh! @joeymisfit raised a similar concern in #1295, but I only double-checked it in singleplayer. I'll take a look in multiplayer to see if I broke something there in one of the recent updates.

**Comment by SDGNelson** [comment]
Yikes this is a huge mistake on my part. I should have checked into this over the holiday break, but it will be patched for the next update. There was a change that fixed loading client objects on the server, and a side effect was that the server is thinking those vehicles have police sirens... so the skycrane hooks and blimps are not triggerable. 🤕

**Comment by SDGNelson** [comment]
Should be fixed in the next update!
