### ISSUE TITLE
Stuck Queue Position #1

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#134]
This seems to be happening to a lot of servers but only when it goes over 8 - 9 players, once it's over that number anyone who tries to join gets stuck in queue position #1 with their mouse stuck in the middle of the screen like if they joined, they can punch, you can hear the sound but the loading screen is still there.

This is most likely because of Max_Packets_Per_Second at its default is very low, but it shouldn't matter if its low or not.

This will need to be fixed and ready to launch with next update, if not a patch as soon as possible

**Comment by N1GHTPATROL** [comment]
This has to do with Nelson's `Max_Packets_Per_Second` config option. He will probably have to bump up the default number. If it's happening on a server tell them to bump it up to 300-500 for a full server with no problems.
