### ISSUE TITLE
Big bug with quests NPCs

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1342]
Imagine, an NPC should give out a reward of 7 items, you get them and run to the bank to exchange for an exp, look, yes, you can really sell 7 pieces and as soon as you click only 1 item is sold, the rest become “invisible” to the NPC, although in the inventory they there is.. This bug works both in single player and on the server.
Players reported this issue to me about 11 months ago.
Watch the video to make sure: https://www.youtube.com/watch?v=uEgxt9mgaWI

**Comment by dzonyloker** [comment]
Just create 2 rewards with amount 1
or change amount to value

**Comment by MrGoBi** [comment]
The fact is that I use Avi plugins, and they do not synchronize the received exp to the balance.

**Comment by SDGNelson** [comment]
Thanks for the report video! I'll investigate to find why that item is being ignored.

**Comment by SDGNelson** [comment]
This should be fixed in the next update!
