### ISSUE TITLE
VERY URGENTLY! Ladders bug !!!!!!!!!!!

### ISSUE THREAD

**Issue by karatelg** [SmartlyDressedGames/Unturned-3.x-Community#1343]
All vanilla / mod ladder have stopped working. What to do? I attach video from the server
https://youtu.be/PtIb1OZN-BI

**Comment by HanaForward** [comment]
I find it very interesting。。。。。

**Comment by HanaForward** [comment]
Are all players like this?Still just a case？

**Comment by SDGNelson** [comment]
I meant to reply when I checked this out day-of. Apologies for my delay over the holidays. It works fine in vanilla singleplayer and multiplayer, so chances are it's a plugin which restricts "stance" changes. I'd suggest enabling and disabling a few to see what's going on if it's still happening.

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I'll re-open.
