### ISSUE TITLE
Unturned Workshop Upload don't work [Issue: "K_EResultFail"]

### ISSUE THREAD

**Issue by PuschiYT** [SmartlyDressedGames/Unturned-3.x-Community#1346]
Pics:
1
https://images-ext-2.discordapp.net/external/OPwzvuvi7V7whw3fXatX-YeIOd26fzScYG8Fm1T4xto/%3Fwidth%3D1202%26height%3D676/https/media.discordapp.net/attachments/527924306924142592/659148157887709204/unknown.png
2
https://images-ext-2.discordapp.net/external/w3ff4JBWZv_uBgDQ8czo-vZIh5gWMGrEssPGkdQ4HUI/%3Fwidth%3D1203%26height%3D676/https/media.discordapp.net/attachments/527924306924142592/659148446246240276/unknown.png
3
https://media.discordapp.net/attachments/527924306924142592/660482028919324677/unknown.png?width=1202&height=676

**Comment by SDGNelson** [comment]
Apologies for my delay over the holidays. There may be further details in the Client.log file, but generally these sort of errors are temporary maintenance. Did it work for you later?

**Comment by PuschiYT** [comment]
It isnt a Maintaince Problem because i tried to upload a Map like 1 year
ago and it still didn't work, Like there was the same Problem than here.
And now it's not working too i think. If iam arriving home ill test it.

Nelson Sexton <notifications@github.com> schrieb am Di., 7. Jan. 2020,
02:02:

**Comment by SDGNelson** [comment]
I waited a couple days so that I could test it with the Hawaii map and bundles workshop updates, but they were able to upload successfully.

Could you upload the Client.log file from the Unturned/Logs directory the next time it fails please?

**Comment by PuschiYT** [comment]
Hello,
There is the File:
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4048154/Client.log)
----------------------------------
Can we actually talk about Discord because I can answer Discord at any time and it would be better for me if it doesn't bother

Discord: 😈_Puschi_😈#6896

**Comment by SDGNelson** [comment]
According to the Steam docs this is a generic failure, whereas the game responds to other failures like needing to accept the legal agreement or IO failure.

There might be more details in the Steam internal log file typically located here:
C:\Program Files (x86)\Steam\logs\workshop_log.txt

**Comment by PuschiYT** [comment]
Should i send the data?

Nelson Sexton <notifications@github.com> schrieb am Fr., 10. Jan. 2020,
23:42:

**Comment by SDGNelson** [comment]
Yes please! Either as an attachment here, or by email to nelson@smartlydressedgames.com

**Comment by PuschiYT** [comment]
Here is the data:
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4059923/workshop_log.txt)

**Comment by SDGNelson** [comment]
Thanks for the log. It appears to be this same workshop internal error repeated:

    [AppID 304930] Upload starting for workshop item 1803249713 by AppID 304930
    [AppID 304930] Upload workshop item failed, failed build workshop depot 304930

Unfortunately there are no further details, and looking online there are occasional reports from other players in other games. It might be worth opting into or out of the Steam client beta to see if it works properly, but otherwise I don't think there's anything we can do on the game's end.

**Comment by PuschiYT** [comment]
Ok thx for helping me but is there any way for me to upload this map?

Nelson Sexton <notifications@github.com> schrieb am Di., 14. Jan. 2020,
23:31:

**Comment by PuschiYT** [comment]
it still dont work sry i had to do lot of stuff in the last weeks



Am Mi., 15. Jan. 2020 um 00:03 Uhr schrieb _Puschi_ <
puschmann.tino@gmail.com>:

**Comment by PuschiYT** [comment]
i think i found the issue all my maps are back in unturned 3.0


Am Sa., 8. Feb. 2020 um 08:48 Uhr schrieb _Puschi_ <puschmann.tino@gmail.com
