### ISSUE TITLE
[Request]Disable logging of"Unable to resolve dependency Include it in one of your module assembly lists." 

### ISSUE THREAD

**Issue by erik7302** [SmartlyDressedGames/Unturned-3.x-Community#1347]
A commandline or a option to disable the logging of "Unable to resolve dependency Include it in one of your module assembly lists."

**Comment by SDGNelson** [comment]
I guess it's a dependency of RocketMod plugin that uses a custom  AppDomain.CurrentDomain.AssemblyResolve?

I could add an option, or another option would be for the game to provide a fallback resolve assembly event that plugins can use.

**Comment by erik7302** [comment]
> 
> 
> I guess it's a dependency of RocketMod plugin that uses a custom AppDomain.CurrentDomain.AssemblyResolve?
> 
> I could add an option, or another option would be for the game to provide a fallback resolve assembly event that plugins can use.

RocketMod has a custom AssemblyResolve, both unturned and rocketmod AssemblyResolve are called to "Resolve" but rocket does resolve the assembly and unturned doesnt and thows "Unable to resolve dependency Include it in one of your module assembly lists." and that confuses most players thinking that the dependecy is missing but it dont.

Both options are good until the event get implemented on rocketmod or no we can disable the logging with option.

**Comment by SDGNelson** [comment]
Ah I see, took a look at the Rocket IModuleNexus. I'll make that warning opt-in for the next update.

**Comment by Johnanater** [comment]
Yay, my logs won't be 30KB+ anymore :D
