### ISSUE TITLE
Localization Requests

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1352]
1. Translate location names shown on the in-game map
2. Translate debug text / camera modes
3. Improve economy translation
4. Update to work with sandbox
5. Is curated timestamp formatting using local settings?

**Comment by TheTioSweet** [comment]
Thank you for the update! I've already translated the camera debug modes, but I don't understand how to translate the map locations. Could you elaborate?

**Comment by SDGNelson** [comment]
For example to translate PEI:

1. Copy PEI's English.dat file
2. Create a Maps directory at the same level as Editor, Menu, Player, etc
3. Paste the English.dat file into the new directory
4. Rename it to PEI.dat
5. Localize name and description if desired
6. Add keys for location names, with underscores replacing spaces. e.g. "Oulton's_Isle"

**Comment by TheTioSweet** [comment]
> 5. Localize name and description if desired
What if I already localized the name and description on the map itself?

**Comment by SDGNelson** [comment]
That's fine too, however the game will default to the Spanish.dat because it assumes it was translated by the map's creator in that case. Either file can contain the localized names for locations. In my opinion moving that translation to the Maps folder is preferable because it makes it easier to install.

**Comment by TheTioSweet** [comment]
> That's fine too, however the game will default to the Spanish.dat because it assumes it was translated by the map's creator in that case. Either file can contain the localized names for locations. In my opinion moving that translation to the Maps folder is preferable because it makes it easier to install.

Oh, alrifght

**Comment by sagnoir** [comment]
So, should I just paste the file into the Spanish/Maps (Spanish/Maps/PEI.dat) folder? Or should I make a subfolder for that (Spanish/Maps/PEI/PEI.dat)? I got this to work by loading the Spanish.dat file in Unturned\Maps\PEI. I added the location keys and then I just loaded the map and... it worked!

However, does the PEI.dat file need to have exactly the same keys as the English.dat file? I mean, I didn't want to include these values:
Name Blah blah blah (placeholder)
Description Blah blah blah (placeholder)

Secure Blah blah (placeholder)
Insecure Blah blah (placeholder)

Loading_Server Blah blah (placeholder)
Loading_Editor Blah blah (placeholder)

**Comment by SDGNelson** [comment]
Spanish/Maps/PEI.dat is right yes.

The "Name" key is optional. If it's not present then the map's folder name is used instead.

The "Secure", "Insecure", "Loading_Server" and "Loading_Editor" keys were from back when there were only two or three maps, but nowadays are used from the shared loading screen's file instead.

**Comment by TheTioSweet** [comment]
> Spanish/Maps/PEI.dat is right yes.
> 
> The "Name" key is optional. If it's not present then the map's folder name is used instead.
> 
> The "Secure", "Insecure", "Loading_Server" and "Loading_Editor" keys were from back when there were only two or three maps, but nowadays are used from the shared loading screen's file instead.

I see. However, I tried to do this and didn't work. That's why I had to stick to the Spanish.dat file on the Unturned/Maps folder.
![22](https://user-images.githubusercontent.com/33989469/72655798-ba6ec580-3975-11ea-9903-9e6f6300e201.PNG)

Thanks for your time, Nelson.

**Comment by SDGNelson** [comment]
Did you remove the Spanish.dat file from the PEI folder while the PEI.dat file was in the Spanish/Maps folder?

**Comment by TheTioSweet** [comment]
> Did you remove the Spanish.dat file from the PEI folder while the PEI.dat file was in the Spanish/Maps folder?

No, I didn't maybe that was the issue?

**Comment by SDGNelson** [comment]
The "next update" label was accidentally left on this, but I will close it now. Feel free to comment if needed and I'll re-open.

**Comment by sagnoir** [comment]
From what I gather, the default value format is "Rarity + Type". Would changing the order in "PlayerDashboardInventory.dat" cause any issues? To elaborate: lines 1 through 6 currently contain the rarity values. What would happen if I removed those lines, so that the block starts with "Type_0" instead—essentially changing it to "Type + Rarity"?. **Update: I tried changing it and it didn't work.**

(There was an image here. It's gone now).

**Comment by TheTioSweet** [comment]
This is what I mean.
![image](https://user-images.githubusercontent.com/33989469/79804230-a8644080-8331-11ea-89f4-47a60290bdbc.png). 
![image](https://user-images.githubusercontent.com/33989469/79804257-b619c600-8331-11ea-9722-6179bffd7c96.png)

**Comment by SDGNelson** [comment]
Hi TioSweet! That should be a straightforward change. I will take care of it for the next update.

**Comment by TheTioSweet** [comment]
> Hi TioSweet! That should be a straightforward change. I will take care of it for the next update.

Hi Nelson, thanks! This is something that I've been wanting to modify for a long time.

**Comment by TheTioSweet** [comment]
I'm writing this to know we are on the same page. What I meant, is that I need a feature that let's us change the grammatical order of the inventory dashboard, i.e., Item Rarity + Item Type (Epic Melee Weapon). On Spanish, this would be Item Type + Item Rarity (Melee Weapon Epic).

**Comment by SDGNelson** [comment]
Yep exactly, it will be a straightforward change.

**Comment by TheTioSweet** [comment]
> Yep exactly, it will be a straightforward change.

Alright. I was thinking I messed up since my English is rusty as hell.

**Comment by SDGNelson** [comment]
This has been added in the next update with a `Rarity_Type_Label` key in `PlayerDashboardInventory.dat`

**Comment by sagnoir** [comment]
I've been trying to figure this out for a long time: what real-world gear are the Unturned military uniforms based on? Take the Forest and Desert uniforms, for instance—I assume the desert one is American, but is the forest one Canadian? I can't tell whether the tops are jackets or jerseys. I've been calling them "jerseys" or "sweaters" in my Spanish translation (most of the time), but I'm not really sure if those tops are actually jerseys or sweaters. Could anyone give me some context? Have I been using the right terms?

One more thing: are the Coalition tops jackets or jerseys, and is the Desert Military Top modeled after an M-1965 field jacket?

**Comment by SDGNelson** [comment]
They were not based on any particular real-world outfit. The Forest ones have Canadian flag patches, and the Desert have US flag patches. I would be inclined towards Jersey or Jacket, or maybe Uniform.

You raise a good point: I will keep in mind some actual outfits in Unturned II. :)

**Comment by sagnoir** [comment]
Oh, thanks for answering! Guess I'll just use 'shirt' then. I don't know... pockets would look pretty weird on a jersey, haha.

**Comment by sagnoir** [comment]
Hello again. I was wondering if the quest name "The Squeaky Motor Gets the Grease" was a reference to the "the squeaky wheel gets the grease" idiom (is it a pun?) or if it was a coincidence. Also, are there more references that I should be aware of? I've been translating a lot of things without context, so I don't know if I've translated them properly.

**Comment by SDGNelson** [comment]
Hi! Yes, it was named after "the squeaky wheel gets the grease" pun/idiom. It has been so long that there aren't other references coming to mind, but if you have any questions feel free to ask.

**Comment by TioSweet** [comment]
Thank you.

**Comment by sagnoir** [comment]
Hi again, Nelson! Is it possible to use the bold or italic markdown in item descriptions?

**Comment by SDGNelson** [comment]
It should be - you can use `<b>bold text</b>` and `<i>italic text</i>`

**Comment by TioSweet** [comment]
Thanks, I'll try to do that.

**Comment by SDGNelson** [comment]
Sorry, but the item titles/names do not support rich text

**Comment by TioSweet** [comment]
> Sorry, but the item titles/names do not support rich text

Oh, okay. Thanks.

**Comment by Sagnoir** [comment]
Hello again, Nelson! Is "Bran Cereal"'s name and description a nod to the user "Bran_Salad" (according to the wiki) or it's just bran cereal?

**Comment by SDGNelson** [comment]
Very old! That item was a nod to the user Bran_Salad, but is also literally bran cereal.

**Comment by Sagnoir** [comment]
Oh, ok. Thanks!

**Comment by sagnoir** [comment]
Hello again, Nelson! What is the character limit for strings in PlayerLife.dat? I found out that my translation overflows the gesture dialog box. 

(There was an image here. It's gone now).

**Comment by SDGNelson** [comment]
That depends on the font and language used, so it is impossible to give an exact answer sorry. Do they need more space for the text you need?

**Comment by sagnoir** [comment]
> That depends on the font and language used, so it is impossible to give an exact answer sorry. Do they need more space for the text you need?

I can try using shorter words, but Spanish usually needs more space. We don't have single-word verbs for everything, so we have to use phrasal verbs instead. For example, 'Salute' translates to 'Hacer el saludo militar,' which literally means 'To do the military greeting.'

Also, I can't actually run Unturned on my laptop anymore. It's too low-spec and crashes as soon as it tries to load the main menu. Because of that, I have to rely on gameplay videos or ask other players to test the translation in-game and send me screenshots.

**Comment by SDGNelson** [comment]
Sorry to hear that the game is crashing. If you can attach these files after trying to load into the menu it might be something I can help work around:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file to your reply
5. Return to the Unturned folder
6. Open the Unity AppData folder
7. Attach the Player.log file to your reply

Thanks for the "Hacer el saludo militar" example text. I have made a note to revisit the gesture menu to make space for that for one of the next updates.

**Comment by sagnoir** [comment]
> Sorry to hear that the game is crashing. If you can attach these files after trying to load into the menu it might be something I can help work around:
> 
> 1. Right-click Unturned in your Steam Library
> 2. Select Properties... > Local Files > Browse...
> 3. Open the Logs folder
> 4. Attach the Client.log file to your reply
> 5. Return to the Unturned folder
> 6. Open the Unity AppData folder
> 7. Attach the Player.log file to your reply
> 
> Thanks for the "Hacer el saludo militar" example text. I have made a note to revisit the gesture menu to make space for that for one of the next updates.

"Facepalm" would also require more space.

Don't worry about the crash, though—I'm pretty sure my laptop is just too underpowered to run the latest version of the game. I used to be able to play it, but only with really low FPS. However, Unturned 2.2.5 runs just fine on my system. For context, my specs are pretty modest: an Intel Celeron 1.7 GHz processor, 128 MB of dedicated video memory, Windows 7 32-bit, and Intel HD integrated graphics.

**Comment by SDGNelson** [comment]
Those are underpowered specs, but I am still hopeful - there are several known Unity crashes with workarounds. Please? :D

**Comment by sagnoir** [comment]
Oh no, it’s not because of the GUI update. This has actually been happening for months—since around mid-2019, I think. You’ve released a ton of updates (which isn’t a bad thing!),but my laptop just can’t handle the game anymore. I’ll try launching it again and check out the log file.

Cheers!

**Comment by Sagnoir** [comment]
Well, I tried to run Unturned and... it stopped responding. Here are the logs.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5740768/Client.log) 
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5740769/Player.log)

**Comment by SDGNelson** [comment]
Thanks for the logs! Looking up the errors it seems like other games have had some luck with a few workarounds, so I will put that on my to-do list as well.

**Comment by SDGNelson** [comment]
If you would like to check out the preview (public test) branch there are two relevant changes:
1. Gesture buttons have more space, tested with your example text.
2. If you run the game with the "-AggressiveGC" then _hopefully_ (fingers crossed) you might be able to load in.

**Comment by sagnoir** [comment]
I'll give it a try and reply if the game crashes again, haha.

**Comment by sagnoir** [comment]
I tested the preview branch, but it crashed. I tried playing at the lowest settings and resolution, but still nothing. I'm pretty sure it's because the game needs more RAM than I have.

Update: When the game tries to load assets, it uses nearly 1.1 GB of memory. That pushes my physical memory usage up to 99%—and that’s with things like Steam and explorer.exe running in the background. Told you. :/

**Comment by SDGNelson** [comment]
Thanks for giving it a try. Sorry that we could not get it to work. You were right. :/

**Comment by sagnoir** [comment]
No worries! Your game is great, so I'll just keep relying on beta testers to check everything for me until I can buy a decent computer.

**Comment by SDGNelson** [comment]
Do you have a paypal account or something? I will chip in a bit towards a new PC. :)

**Comment by Sagnoir** [comment]
> Do you have a paypal account or something? I will chip in a bit towards a new PC. :)

I don't. My Paypal accounts were constantly hacked so I decided to delete the ones I still could log in to.

**Comment by SDGNelson** [comment]
Do you have any other preferred online method? You have done so much for the Spanish players!

**Comment by sagnoir** [comment]
Sadly I don't, so we'd have to talk about it elsewhere. I don't really feel comfortable discussing that here. Happy New Year!

**Comment by Sagnoir** [comment]
> Do you have any other preferred online method? You have done so much for the Spanish players!

![ffg](https://user-images.githubusercontent.com/33989469/103430674-38d37000-4ba5-11eb-8b4d-e728171b018b.jpg)
![axxx](https://user-images.githubusercontent.com/33989469/103430681-41c44180-4ba5-11eb-95fa-a34589b2ecf5.jpg)

**Comment by SDGNelson** [comment]
Hehe, I see you sent an email and will follow up there.

**Comment by sagnoir** [comment]
Hey, Nelson, is PEI's "Pirate Cove" a cave, a https://en.wikipedia.org/wiki/Rock_shelter or a cove ("(now uncommon) A hollow in a rock; a cave or cavern. [from 9th c.]") or "A small coastal inlet, especially one having high cliffs protecting vessels from prevailing winds"? I'm having a rough time trying to figure out why you changed "cave" to "cove" and now I'm confused. I don't know how I should translate it. Is it like a "creek"?

**Comment by SDGNelson** [comment]
Sorry, that must have been a misunderstanding of "cave" vs "cove" on my part. You really did your research! It should probably be "cave" then.

**Comment by Sagnoir** [comment]
> Sorry, that must have been a misunderstanding of "cave" vs "cove" on my part. You really did your research! It should probably be "cave" then.

Okay! Thanks for replying.

**Comment by sagnoir** [comment]
Hi Nelson, are Unturned's berries based on real-life ones? For instance, is the Indigo Berry a blueberry, and is the Amber Berry a cloudberry? Are these [berries](https://en.wikipedia.org/wiki/Berry) or just [berries (botany)](https://en.wikipedia.org/wiki/Berry_(botany))? I’m worried I might have been translating them wrong.

On a technical note, would it be possible to increase the character limit for item text, or implement a text-scaling system similar to the gesture menu? Right now, translated names and descriptions overflow the inventory slot boxes and the pickup notifications. If that's not feasible, I'll just look into abbreviating the names instead.

**Comment by SDGNelson** [comment]
They are not 1:1 with real-life berries, instead generic colorful fruits. In that case is the extra space needed?

**Comment by sagnoir** [comment]
Yeah, I'd definitely need extra space if they're just generic colorful fruits. In Spanish, we usually call them 'frutas del bosque' (forest fruits) or 'bayas silvestres' (wild berries) when they grow on bushes or small trees. Up until now, I’ve been translating them simply as 'bayas,' but technically, that’s not entirely accurate.

Update: I think I’m gonna ask my beta tester to try out the translation and send me screenshots of both the bush interaction text and the inventory slot. I want to see how much of the text actually fits before it starts overflowing the UI.

**Comment by sagnoir** [comment]
Okay, so this is the only instance where the string doesn't fit the UI. It's the refined berry seed (35 characters). I assume it's going to look different on every resolution, especially when you factor in UI scaling options, right? I think I'll just abbreviate the words in this case.

Update: Nevermind, I'll just name them "bayas".

(There was an image here. It's gone now).

**Comment by SDGNelson** [comment]
> Nevermind, I'll just name them "bayas".

Is that shortening okay? Hmm I'm not sure which way to extend that UI if more than 35 is needed.

**Comment by Sagnoir** [comment]
> > Nevermind, I'll just name them "bayas".
> 
> Is that shortening okay? Hmm I'm not sure which way to extend that UI if more than 35 is needed.

It's not entirely okay but it will do.

**Comment by sagnoir** [comment]
I realize this might not be the best place to ask about the Classic version (2.2.5), but while I was translating the game (specifically digging into Assembly-CSharp.dll), I came across some lines that I haven’t seen anywhere in the menus. Are these unused server filter strings, or were they just placeholders?I'm trying to figure out if it's even worth translating them, since I can't find them in-game and I'm not even sure if there's an active server browser for them. The strings look like: 'Not Passworded, Passworded, Any Mode, Any Space, Any Ping, Empty, Any Syncing, Any Style, Any Hosts, Map, Search' and so on. Should I bother translating these, or can I just skip them if they don’t actually show up?

**Comment by SDGNelson** [comment]
Translating a 7.5 year old game by reverse-engineering the binaries, hardcore.

They are probably from the old Unity master server which as far as I know has been offline for years, or _maybe_ from some work on a Steam server browser for 2, but I do not think either is available in-game in that version.

**Comment by sagnoir** [comment]
Thanks for the reply! Sorry for the delay. In that case, I'll just leave those server strings as they are. I’ve also come across some other strings that seem to be related to debug mode—should I bother translating those at all?

Regarding the 'reverse-engineering' part, I’m just using a tool (a fork of a .NET decompiler) to edit any hardcoded strings that aren't tied to scripts. As far as I know, this is currently the only way to translate older Unity games like Unturned 2.2.5 or Antique Unturned.

I've also been using asset extraction tools to export, modify, and re-import assets, making sure to rename the files so the game recognizes them. Thanks to that, I’ve already successfully imported the translated PEI map locations and the tutorial wall text!

**Comment by SDGNelson** [comment]
Impressive!
