### ISSUE TITLE
Pines #3 (Maybe #4?) Speedtree Skybox are tinted red

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1353]
Most likely caused by the reddish bark texture meshing with the snowy leaves during Speedtree's exporting process.

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like that tree was using a different asset for the billboard than for the LOD[0, 2] models. I'll correct the billboards to use the same tree for the next update.
