### ISSUE TITLE
Spawn effect that will follow player.

### ISSUE THREAD

**Issue by TheCubicNoobik** [SmartlyDressedGames/Unturned-3.x-Community#1355]
Like `EffectManager.sendEffect`, but the effect will be spawned in the player's game object.

**Comment by HanaForward** [comment]
EffectManager.sendEffect  has point parameter
you just try invoke it follow player.point.

**Comment by erik7302** [comment]
> 
> 
> EffectManager.sendEffect has point parameter
> you just try invoke it follow player.point.

Not enough or useless if u use a trail for example, the trail will just dont work, also a particle will alway be reseted and not have a smooth movement.
also destroying and resending the effect will not look good

**Comment by SDGNelson** [comment]
Without a way to address all objects over the network it would be a very niche use case of only players. Could be added only with: #1233
