### ISSUE TITLE
Vehicles are instantly removed by getting into the water on the server!

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1356]
I know that if you submerge a vehicle in water, then after restarting the server it will disappear. However, all my vehicles, when they fall into the water, are instantly removed. Be it mod or vanilla transport.
Although, if you just drive into the water with wheels, everything works as it should.

I learned about this from the players. The first complaint came a month ago.

**Comment by Spebby** [comment]
I know this is something you might have already tried, but worth suggesting none the less.

Check the server config and make sure the values involving vehicle spawning/despawning are as intended.

**Comment by MrGoBi** [comment]
I did not touch this config. Vehicle instantly disappears as soon as it falls into the water.

**Comment by SDGNelson** [comment]
Spebby is correct that the reason for this happening would be from setting the Vehicle_Respawn_Timer to zero so that underwater vehicles instantly respawn.
