### ISSUE TITLE
Possible to get MAC adress and adress of subnet mask of player

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1357]
Hello, Nellson! You added HWID, it's good, but really easy to bypass with cheats. Can you add possible to get MAC adress of player and adress of subnet mask for improve bans? HWID and IP are good, but not enough and have some problems(like banning innocents). What if use HWID + IPmask and MAC + IPmask bans?

**Comment by TheCubicNoobik** [comment]
It will be easy to bypass too.

**Comment by Greenorine** [comment]
Harder then now

**Comment by TheCubicNoobik** [comment]
No, same as HWID.

**Comment by HanaForward** [comment]
Bypassing IP and MAC is quite easy

**Comment by HanaForward** [comment]
When running the game for the first time, bind to a Steam account to generate a verifiable ID, and verify the validity of the ID every time in the future, and obfuscate related modules，Also updated with every game update。
How is this approach？

**Comment by Greenorine** [comment]
@HanaForward good I think

**Comment by HanaForward** [comment]
It's easy for players to switch accounts，
Switching clients requires re-downloading。

**Comment by Trojaner** [comment]
None of this will work because its the client who sends the HWID / MAC etc.
It can be always spoofed and this will not change anything.

**Comment by Greenorine** [comment]
So there are noways to block people without bypassing.

**Comment by HanaForward** [comment]
yes , Can only try to increase their cost

**Comment by Greenorine** [comment]
Btw I need IPmask for better protection from dynamic IPs, I don't want to block IPmask, I want to block IPmask+HWID together in one union

**Comment by SDGNelson** [comment]
Comments are correct that "HWID" is the closest option and adding extra parameters to it is a waste of time.

**Comment by Greenorine** [comment]
Yes I god that Mac is closest to HWID, but can you add possible to get IP of mask of subnet for improving IP bans. I'm using HWID+IP Ban(I mean that I'm banning players with token that contains HWID and IP). With IPmask I can make token HWID+IPmask, so if player has dynamic IP and can change it with restart of router he will get banned with new IP. It will be very good if you can add it.

**Comment by SDGNelson** [comment]
For custom HWID + subnet mask banning I'd suggest binding `onCheckBanStatusWithHWID` and returning a banned status if the HWID and IP match your record. Changing HWID or IP is easy however, so requiring both to match will make it easier to bypass bans.
