### ISSUE TITLE
Bullet ballistic calculation on the client side

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1358]
Set ballistic calculation only from the server side

**Comment by HanaForward** [comment]
Ballistic calculations should only be performed by the client, and the server only verifies

**Comment by HanaForward** [comment]
The trigger mechanism of the zombie should only be calculated by the client, and the server only judges whether the distance before the trigger is normal.

**Comment by Sl4vP0weR** [comment]
If ballistic calculation will be only on server side - It solve problem with "NoRecoil", "NoSpread" and other hacks functions...

**Comment by rube200** [comment]
This shouldn't happen `The trigger mechanism of the zombie should only be calculated by the client`

This allows cheats to prevent triggering zombies.

**Comment by SDGNelson** [comment]
In an ideal world everything would be server-side deterministic and only predicted by the client. At one point in 3.0 early development there was a prototype with hit detection rollback, but Unity physics APIs had issues with updating the colliders multiple times during the frame. There's also the problem of synchronizing animations between client and server, which gets even more complicated for all the layered blends in 4.0 like turning hips/feet.
