### ISSUE TITLE
Pie & Bush Example

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1359]
Were to be included in #1198, but for whatever reason weren't included. Pies would have most likely just included an Indigo pie, while as bushes would have hopefully included all Berry Bushes (To allow for the bushes colours being changed for used on maps with unique materials, without guessing what the correct hex code for the berries are)

**Comment by SDGNelson** [comment]
It looks like they were included, but the package was not rebuilt before the update. Will do
