### ISSUE TITLE
Multiple player colors or appearances

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1361]
The same players, can not distinguish camp

**Comment by SDGNelson** [comment]
Distinguish camp?

**Comment by HanaForward** [comment]
yes,Just like fat players and thin players

**Comment by HanaForward** [comment]
Tall or short

**Comment by Johnanater** [comment]
Probably not going to happen in 3.0. Ark Survival Evolved has this and players just pick hilarious looking people that have broken hitboxes and appearance. Sounds like a lot of work for people being "meatballs".

**Comment by SDGNelson** [comment]
Sorry, but that sort of customization is not going to be added.
