### ISSUE TITLE
Vanilla Nightvision and Time of day change discoloration or lag?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1363]
Hey Nelson, I'm not sure if a previous issue was reported on this but I've noticed that when you are turning off nightvision it literally fades the nightvision color before returning to normal scenery, it's the same when you switch from dusk/nighttime to daytime via command or plugin it fades to another color variation before switching it to daytime. Both me and a few others have tested it on a couple different servers while experiencing the same issue.

**Comment by SDGNelson** [comment]
I believe it's the same issue as this: #1349 
Should be addressed during the next update!
