### ISSUE TITLE
Ability to be above sky limit?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1365]
Hey Nelson, I heard from several vanilla servers, and a few modded servers that people are now able to go above the sky limit? Apparently there isn't a limit anymore, as before when we'd ascend via admin commands or build a stairway to the limit you were only able to go about 500ft or so into the sky and now people build double and triple that.

**Comment by SDGNelson** [comment]
You're right: however there is still a limit. Previously the "devkit" limit was twice the "legacy" limit, but they are equal now at ~1000 meters.
