### ISSUE TITLE
Document RocketMod Setup

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1366]
Many servers use RocketMod, so we should document it.

- Explain shutdown and link to announcement
- Link to official subreddit
- Link to popular plugins

**Comment by TeemoCell** [comment]
Well, the Site is gone. We have to Build the plugins on our own. Here Nelson, you should read this. https://github.com/RocketMod/Rocket/blob/master/Farewell.md
