### ISSUE TITLE
Map doesn't update

### ISSUE THREAD

**Issue by Skogen787** [SmartlyDressedGames/Unturned-3.x-Community#1367]
So, when i try to update my map, it says its successful, but when i check if everything was done right in singleplayer or on a server it reveals that the files have not been updated even though they should have, i have no idea what this issue might be caused by, help would be very much apprechiated

**Comment by SDGNelson** [comment]
If you're subscribed to the map from the workshop at the same time as using a local copy, the chances are that you're editing the workshop version but uploading the local version. Is that the case?

**Comment by Skogen787** [comment]
That is definetly not the issue, i have checked, and its always the workshop file which is unchanged (when i try to update or edit it i make sure im not subscribed to it)

**Comment by SDGNelson** [comment]
I waited a couple days so that I could test it with the Hawaii map and bundles workshop updates, but they were able to upload successfully.

Could you upload the Client.log file from the Unturned/Logs directory the next time it fails please?

**Comment by Skogen787** [comment]
You mean this 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4050035/Client.log)
? Cause it failed again now

**Comment by SDGNelson** [comment]
According to the Steam docs this is a generic failure, whereas the game responds to other failures like needing to accept the legal agreement or IO failure.

There might be more details in the Steam internal log file typically located here:
C:\Program Files (x86)\Steam\logs\workshop_log.txt

**Comment by Skogen787** [comment]
This one?
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4061218/workshop_log.txt)

**Comment by SDGNelson** [comment]
Thanks for the log. It appears to be picking up a change to upload judging by:

    [AppID 304930] Uploaded new content ( ManifestID 2501118985796123435 ) for item 1965065824.

It looks like afterwards that item is subscribed to and unsubscribed from twice. First it downloaded the new manifest, then reverted to the old manifest. It might be worth opting out of the Steam client beta if that's installed. Otherwise I do still think the most likely cause is having multiple versions of the map conflicting.

**Comment by Skogen787** [comment]
You mean conflicting files with the same name? I doubt that is the issue, because i have checked over and over again to make sure all the files containing the exact same map files are nsmed slightly differently

**Comment by SDGNelson** [comment]
Was this sorted out? Unsure what happened here. Closing, but feel free to comment and I will re-open.
