### ISSUE TITLE
Insane RAM allocations at runtime

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#137]
After latest update, had a server crashed twice due to lacking RAM which never happened before. I don't claim it to be related but it's worth looking into anyway:

End of `Unturned/Logs/Server_XXX.log` here:
```Could not allocate memory: System out of memory!
Trying to allocate: 536870912B with 16 alignment. MemoryLabel: Physics
Allocation happend at: Line:168 in 
Memory overview

[ ALLOC_DEFAULT ] used: 654354732B | peak: 0B | reserved: 737227708B 
[ ALLOC_TEMP_JOB ] used: 0B | peak: 0B | reserved: 1048576B 
[ ALLOC_GFX ] used: 77152888B | peak: 0B | reserved: 79691784B 
[ ALLOC_CACHEOBJECTS ] used: 2282908B | peak: 0B | reserved: 10485760B 
[ ALLOC_TYPETREE ] used: 91840B | peak: 0B | reserved: 4194304B 
[ ALLOC_PROFILER ] used: 0B | peak: 0B | reserved: 0B 
[ ALLOC_TEMP_THREAD ] used: 32768B | peak: 0B | reserved: 2293760B 

User allocator returned NULL.
```

The problem here is that it looks to me that game wants to allocate another 530+ Mb at unknown point of time (I couldn't find any pattern)

I am running the server on a 2Gb RAM VPS because it has always been enough unless having loads and loads of Workshop. Not this time :0

I'm gonna test drive it for more times just in case and report if I find anything new

**Comment by aviadmini** [comment]
`Trying to allocate: 2147483648B with 16 alignment. MemoryLabel: Physics`
That's a bit too much... 2 Gb memory allocation :(

**Comment by N1GHTPATROL** [comment]
Same issue here, I've had my servers crash 4 times now, and it looks like my servers went from using <1.2GB to over 3GB in some cases.

![image](https://user-images.githubusercontent.com/7349712/34065650-fe192076-e1d1-11e7-9b67-2d2483140c6c.png)

**Comment by aviadmini** [comment]
I had 6Gb of RAM for a single server (used swap) and still crashed
Linux here :9

**Comment by Trojaner25** [comment]
![sda](https://cdn.discordapp.com/attachments/284399832385191936/391376541348790272/unknown.png)

Not my server tho

**Comment by aviadmini** [comment]
Okay, reverting to Unity 5.5.3 seems to have solved that

**Comment by aviadmini** [comment]
Didn't happen since, considering closed

**Comment by SDGNelson** [comment]
Yeah, pretty annoying though that only this one patch of Unity works properly with Unturned. :P
