### ISSUE TITLE
(Request) Train spawn position

### ISSUE THREAD

**Issue by TinyGiraffes** [SmartlyDressedGames/Unturned-3.x-Community#1376]
Hello, I have a tunnel map the uses the train to travel but currently, the train can spawn anywhere on that track, I was hoping that you could add the ability to mark a node for a train spawn location. Love both the versions!

**Comment by SDGNelson** [comment]
Nice timing, this was actually added recently! Each track in the level config has a Min_Spawn_Placement and Max_Spawn_Placement which vary from 0 to 1 and control the spawn location. https://github.com/SmartlyDressedGames/U3-Docs/blob/master/LevelConfig.md
