### ISSUE TITLE
binding to ChatManager.onServerSendingMessage cause chat bug

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#1378]
Hello,
if I bind function to ChatManager.onServerSendingMessage then when player type in chat it won't show his names, instead it will show "%SPEAKER%".

I think the bug in the following code in ChatManager.serverSendMessage function:
```
if (ChatManager.onServerSendingMessage != null) {
  ......
}
else if (fromPlayer != null && toPlayer != null) {
  ....
  text = text.Replace("%SPEAKER%", newValue);
}
```

I guess the "else" word is extra and should be removed, because I think this condition not related to the previous if.
thank you
![UT_bug](https://user-images.githubusercontent.com/59157332/72320081-98d9b980-36a9-11ea-8007-2e4f28357a37.jpg)

**Comment by nanashi88** [comment]
to make it more clear, it doesn't matter what you bind to onServerSendingMessage, the bug will exist as soon as you bind anything. cuz the next condition block won't work because it is "else if", and I think it should be "if" without else.

**Comment by SDGNelson** [comment]
The reason for this is so that the callback can control how %SPEAKER% is formatted, but I will change it as proposed in case the callback does not format it. Here's the docs from those two events:

		/// <summary>
		/// Called on the server when preparing a message to be sent to a player.
		/// Allows controlling how %SPEAKER% is formatted for the receiving player.
		/// </summary>
		public static ServerSendingChatMessageHandler onServerSendingMessage;

		/// <summary>
		/// Called on the server when formatting a player's message before sending to anyone.
		/// Allows structuring the message and where the player's name is, for example: '[CustomPluginRoleThing] %SPEAKER% - OriginalMessageText'
		/// </summary>
		public static ServerFormattingChatMessageHandler onServerFormattingMessage;

**Comment by nanashi88** [comment]
ok, now I understand. thank you.
