### ISSUE TITLE
Disconnectings with Battleye error

### ISSUE THREAD

**Issue by Projoker** [SmartlyDressedGames/Unturned-3.x-Community#1382]
All my servers disconnect players in one or two minutes after connection with msg: 

> you were kicked from this server because: Battleye: Client not responding

I see this problem several days.

Tested without modules and plugins

![image](https://user-images.githubusercontent.com/34097519/72385886-37195e00-3742-11ea-90ce-6f0bdc5bf6dc.png)

**Comment by Sl4vP0weR** [comment]
MB You cant connect to BE services

**Comment by Sl4vP0weR** [comment]
U can try to reinstall server

**Comment by Projoker** [comment]
> U can try to reinstall server

I'd tried to reinstall steam and unturned. No result.
