### ISSUE TITLE
Rocket in Modules folder in new update

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#1384]
Hello, it seems in the lastest update you pushed rocket to everyone (Everyone has it in their modules folder). Which is causing people to get kicked for "Battleye: Unsupported modules"

**Comment by Johnanater** [comment]
F

**Comment by Arechii** [comment]
F

**Comment by X-Doctor-X** [comment]
F

**Comment by SDGNelson** [comment]
Idiotic mistake on my part. Patch that removes it is pending. In the next major update I'll sign it officially so that BattlEye doesn't kick for it.

**Comment by PandahutMiku** [comment]
Not sure if you can fix it, but it is seemingly also removing Rocket for people updating the Unturned Dedicated Server package, which could probably be an issue for some people with auto restarts/managed hosting

**Comment by Johnanater** [comment]
Didn't happen on my servers. 🤔

**Comment by joeymisfit** [comment]
Big oofie!
