### ISSUE TITLE
Discarding old unacknowledged input packets - pushing out players

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1388]
Enable_Kick_Input_Spam is set to false (did it after the last time I reported this issue), but apparently didn't help. Any ideas what else might cause it?

Here is a client log:
https://pastebin.com/9VMx4kUw

And this is a part of server log (of pushing-out moment)
https://pastebin.com/HpVBBCFq

Doesn't seem to be pushing out players often, but happened on two server today (on one of them 2 times). And probably worth to mention it started today

**Comment by SDGNelson** [comment]
There are quite a few exceptions in that client log from an invalid index for equipment tellSlot -> updateSlot. I'll investigate what might be causing it and add some bounds checking.

It looks like the client thinks the server isn't acknowledging its inputs, and the server thinks the client isn't sending inputs. It might be that whatever's causing the slot exception is corrupting the packets, however on the client side the read index is safe regardless of exception. This makes me think that whatever's on the server causing the bad tellSlot call could be writing garbage.

Plugin-wise this would be related to equipment, or maybe multi-threaded network bogus. Is there anything like that? In this past update I added some thread exceptions, so if it is the multithreaded one then I'll add a check to whatever it is.

**Comment by baranmod** [comment]
It could be an issue with some plugin. Definitely got some related equipments. Sadly, it would be pretty hard to track down which one exactly tho. I've seen same exception in the past too, but it was more like a random one (no spam in logs).

Another thing (I believe could be related to this, was some strange acting of items when players couldn't de-equip them. Have seen several other server owners speaking about it. But again, its happening randomly and I couldn't replicate it myself.

Anyways, I will try to speak with some devs

**Comment by SDGNelson** [comment]
I held off on the patch over the weekend in case bigger bugs were reported that should be patched immediately. This morning the .2 patch will go up which fixes the client side of this exception, the lighting refresh, and an editor saving issue.

**Comment by baranmod** [comment]
I think this update fixed the issue. At least, exception (tellSlot) didn't appear on logs so far. Thanks!
