### ISSUE TITLE
AntiMapGlitch

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#139]
So because of all the ways someone can glitch through the map I thought I'd start a little project called AntiMapGlitch (https://github.com/Torubloo/AntiMapGlitch) which is a RocketMod plugin, It is very basic and seems to work fairly well, sadly this doesn't stop all glitching because all it really does is check if there is ground below you and if not then do a action (none/kick/ban) and there are cases where the map has a extra bit of ground below that ground, or if they glitch into a building, for example the castle in Germany because there is still a ground below the castle it can't detech

Was wondering if something like this could be added to the game?

**Comment by jackthefrag** [comment]
What if they're airborne? xD

**Comment by Torubloo** [comment]
If they are airborne it knows there is a ground below them, https://github.com/Torubloo/AntiMapGlitch/blob/master/AntiMapGlitch.cs#L47 if you go VERY VERY high it can detect but that is impossible without tping, you need to be WAY above the map border for it to not find the ground

**Comment by SDGNelson** [comment]
Unturned used to check if you were underneath the terrain, but you're right that with the addition of landscape holes this check doesn't make sense anymore. Unfortunately there isn't an easy way to determine if the player is somewhere they shouldn't be without explicitly marking areas off limits.
