### ISSUE TITLE
Why does the "home" button hide only the GUI, and the UI remains?

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1391]
Why does the "home" button hide only the GUI, and the UI remains?

![image](https://user-images.githubusercontent.com/46658857/72680594-4131b880-3ac4-11ea-8808-7dd25572f578.png)

**Comment by Trojaner** [comment]
Because those are plugin UIs

**Comment by MrGoBi** [comment]
It would be correct if the button "home" will hide the GUI and UI together.

**Comment by educatalan02** [comment]
No, that's destroying the interesting thing.

>

**Comment by SDGNelson** [comment]
Currently the game doesn't track which canvases it would need to turn off, but it would make sense to. Will do in a future update.

**Comment by SDGNelson** [comment]
Rather than tracking plugin components the long-term plan for this will be to allow server-side plugins to create glazier UI elements that respect the built-in UI settings.
