### ISSUE TITLE
Issue with sentries

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1392]
Its an older issue (not related to recent update). If, for example, shirt have 0.1 (or more) damage reduction and vest have 0.1 (or more) damage reduction (which equals to 90% per part) - sentries doesn't do any damage for player. But if I set damage reduction to 0.15 for vest and 0.2 for shirt - all works good, even though it also equals to more than 100% per both parts.  It worked well long time ago, yet issue appeared after some older update (can't really recall which one exactly).

Maybe it would be possible to add an option to make sentries shoot into head instead of body?

**Comment by SDGNelson** [comment]
With the shirt and vest that would be multiplying damage by 0.01, rounding down to 0 damage. That damage is consistent between player guns and sentry guns, so I wonder if those armor values are intended?
