### ISSUE TITLE
Scrollbar UI problem

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1393]
I made UI with scrollbar, but when I'm trying to move scrollbar down, it's getting start position itself.
![ksflrj5rYS](https://user-images.githubusercontent.com/41028671/72684169-09486680-3b00-11ea-9549-91c755a56500.gif)
Content of Scrollview isn't empty, it's just many empty texts.

**Comment by Greenorine** [comment]
This problem doesn't exist in Unity.

**Comment by hksz** [comment]
Excuse me, have you tried the Health Point Scrollview ui?

**Comment by Greenorine** [comment]
I don't know what you're talking about, but this problem has been solved.
