### ISSUE TITLE
Linux can't command save

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#1395]
What happens when I attempt command save from console on ubuntu 18.04

[save error.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4087632/save.error.txt)

**Comment by SDGNelson** [comment]
In the 3.20.1 update I added current thread checks to a few functions, this being one of them. It appears the RocketMod command executor is on a different thread. I just double-checked and the multi-threaded vanilla console saves properly.

I think our best insight will be if our friendly neighborhood RocketMod expert Trojaner is willing to shine some light on this? If you have a moment Trojaner do you have

**Comment by Trojaner** [comment]
RocketMod should call the commands from the Unity thread and as it seems the same command works on Windows without issues. Maybe checking threads doesn't work correctly on Linux?

**Comment by SDGNelson** [comment]
Thanks Trojaner! That does appear the most likely considering that older code is calling directly into the command system from a separate thread. Are you using an older version of RocketMod, Mithallas?

**Comment by TheCubicNoobik** [comment]
Before the 3.20.1/.2 update sending messages from a separate thread worked fine, but now I getting a lot of similar errors. Are you sure this check is necessary?

**Comment by Mithallas** [comment]
I'm using RM v4.9.3.0

**Comment by SDGNelson** [comment]
@TheCubicNoobik even if it seemed like they were working fine, it was **definitely** not working fine. Plugins calling functions that aren't thread-safe is currently a huge source of problems, and despite warnings devs are still doing it, so I'm going to add similar checks to other functions.

**Comment by aman7** [comment]
i am having same error as mithallas
i have tried few commands: broadcast, save, heal
and i have tried it by three different methods:
1. command window by which we start the server using ServerHelper.sh : NOT WORKING
2. connecting the server using telnet(putty): WORKING
3. using server management plugin by one of the developers from imperial: NOT WORKING

I am using ubuntu 18.04 with latest RM version and this is how start my server
./ServerHelper.sh -logfile 2>&1 -LegacyConsole +secureserver/instance
Hope it will help to find out the problem.

**Comment by SDGNelson** [comment]
@aman7 Off the top of my head using the logfile redirect and -LegacyConsole would prevent any input on Linux unless you are using an older version of RocketMod which still had console input built-in. Nowadays if you specify -ThreadedConsole the logfile redirect is no longer needed.

**Comment by aman7** [comment]
well now i am using -ThreadedConsole and i can use commands like broadcast, heal but still cant use save, the only way to use save is by opening new telnet connection using putty. Also my RM is latest.

**Comment by SDGNelson** [comment]
@aman7 Could you post the exception stack trace when running the save command please? 

The game thread check seems to be working fine because it runs in a few other key places like when enqueueing a network update.

**Comment by aman7** [comment]
where i can get stack trace? also i found something, i restarted the server and ran this command "broadcast hello" it worked fine.
then i joined the server and ran the same command "broadcast hello" and i got error. 
[error.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4130480/error.txt)
same happened with the heal.

**Comment by SDGNelson** [comment]
To test I loaded up the vanilla server on Ubuntu and it is able to run commands properly, but when using the final RocketMod release on Ubuntu it runs into this problem. It might be that the final release was not built with the latest version of the code and is missing the commit Trojaner linked. I'll see about re-building the final version.

**Comment by Raxul257** [comment]
Related to #1400 

I had the same error with latest rocket release

**Comment by SDGNelson** [comment]
Attached is the re-built copy of the final release of RocketMod. It will be included in the Extras directory going forward from the next update. I tested on Ubuntu and it seemed to work properly.

[Rocket.Unturned.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4131358/Rocket.Unturned.zip)

**Comment by Mithallas** [comment]
what start script are we supposed to use with the rocketmod you just attached? when using ServerHelper I am unable to input any commands into console

**Comment by SDGNelson** [comment]
The next update will warn about older versions of RocketMod, and the next update after that will finally make -ThreadedConsole the default.
