### ISSUE TITLE
Profanity Censor inconsistencies (Signs)

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#1396]
Hello

![image](https://user-images.githubusercontent.com/7608445/72758010-2f6d1580-3b97-11ea-9d18-ce1a83d3c939.png)

In chat, the profanity censors words only if the blacklisted word matches 1:1 (placement and spelling). On signs, the blacklisted word is censored regardless of where it appears (e.g., as a part of another word).

E.g.; "Hello" doesn't get censored in chat, but appears as "####o" on signs.

**Comment by SDGNelson** [comment]
I'll follow up in private messages.
