### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by Keyword65d** [SmartlyDressedGames/Unturned-3.x-Community#1410]
I can't seem to figure this one out on my own and now seeks help.
I am working on a map and for some reasons I get errors in Console on my server then I boot it up,
and if anyone joins around 30 seconds later the server crashes.
The map works just fine in singleplayer.
I have been going around and trying to find the so-called "posters" but without luck, I, therefore, went to the files to see if there was a better way to do it.
![errorsserver](https://user-images.githubusercontent.com/48893234/73129661-36f24b80-3fe9-11ea-8ed4-5630445f6cd9.PNG)
![objectdat](https://user-images.githubusercontent.com/48893234/73129662-3a85d280-3fe9-11ea-8f6e-9671fb0587a8.PNG)

**Comment by SDGNelson** [comment]
If you really want to get rid of the missing assets you can use the "-NoPreserveMissingObjects" command-line option and then resave the map, which will delete them all during save.

That said, I suspect it's a different issue causing the crash. After it crashes can you post the error log please?
