### ISSUE TITLE
Vehicle UI hide

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#1411]
Please add into map config a line to hide the vehicle UI

**Comment by surv0013** [comment]
And plugin flag too

**Comment by SDGNelson** [comment]
Makes sense, will do at some point.

**Comment by NoThreat** [comment]
Awww, common, #1380

**Comment by DiFFoZ** [comment]
@SDGNelson Can you implement this?
