### ISSUE TITLE
Workshop: Download whitelisted IP addresses from custom remote server

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#1412]
This is an extension to #179

#179 has been adopted great so far. It is used for 2 primary reasons:
* Custom workshop mods only for your own servers
* Selling workshop mods and only allowing your customers to use it

This request is for the latter one.

You might be a great workshop modder, you might have lots of customers. But maintaining the IP whitelist of your mods will take ages and you would have to update your mod everytime someone purchases your mod or every time you want to do changes to your whitelist. This is de facto preventing selling mods in a bigger capacity.

The solution for this would be to download the workshop IP whitelist dynamically from the internet. 

GET `https://example.com/SomeMod/Whitelist`

It could just return a simple .txt file like this:
```txt
12.124.127.23
62.48.117.45
22.214.146.28
```

or JSON
```json
{ 
    "hasWhitelist": true,
    "serverWhitelist": [
        "12.124.127.23",
        "62.48.117.45",
        "22.214.146.28"
    ]
}
```

ALTERNATIVE WAY  (preferred):
GET `https://example.com/SomeMod/Whitelist?ServerIP=32.4.212.4&Port=22025`
```json
{
    "isWhitelisted": true
}
```

The alternative way will prevent exposing which servers have access to the workshop item, also with more servers allowed to use it the list might grow very huge and make downloading even slower.

The workshop mod author would just add this URL to the workshops data file, e.g.
`IP_Whitelist_Url https://example.com/SomeMod/Whitelist`

or for the alternative way:
`IP_Whitelist_Url https://example.com/SomeMod/Whitelist?Server=%SERVER_IP%&Port=%SERVER_PORT%`

I suggest adding the following macros which are then replaced:
`%SERVER_NAME%`, `%SERVER_IP%` and `%SERVER_PORT%`

Of course the way how the data is generated and returned, setting up or writing the required software for this would be up to the workshop author.

There are some cases to consider:
* Server might not be reachable, might return in wrong format, might return 4xx or 5xx errors -> prevent mod from working?
* Server could be very slow -> Set download timeout to like e.g. 5 seconds?

If you are going to use Unity's http client, download will be asynchronous which means the asset might load *after* the server and map was loaded.
You should consider using a synchronous approach instead.

**Comment by SDGNelson** [comment]
This makes sense for the selling per-server access case, but would be low priority to add. Originally adding this feature my main intent was to help mod creators who felt their work was being stolen.

In the meantime a plausible workaround would be to use the Steam UGC API to automatically add and remove IPs from the whitelist, and then automate Steam CMD to log in and out as-needed.

**Comment by Trojaner** [comment]
Sadly the UGC API would likely require me to get the private Steam credentials for each workshop creator, so I think a feasible workaround doesn't exist

**Comment by SDGNelson** [comment]
Ah, I figured they were all your items hosted on your account. You're right that there isn't a workaround now then. ☹️

**Comment by erik7302** [comment]
if i reading this correctly u want a better/easy way to update the IP Whitelist/Blackslist.
 if so why not put it on the end of the workshop description of mod like:
```
WhitelistIPs:xxx.xxx.xx.xx, xxx.xxx.xxx.xx
BlacklistIPs:xxx.xxx.xx.xx, xxx.xxx.xxx.xx
```
or put it on a service like www.pastebin.com also like above ^^^^^
and have unturned download that info and check if the mod can be downloaded.

**Comment by Trojaner** [comment]
I prefer calling a service which just returns true/false instead of the whole IP address list

**Comment by Trojaner** [comment]
Is there any hope that this could be added soon?

**Comment by SDGNelson** [comment]
If implemented the most likely approach would be as described by `https://example.com/SomeMod/Whitelist?Server=%SERVER_IP%&Port=%SERVER_PORT%`

There are a lot of feature requests and to-dos at the moment, so this is not a priority sorry. Even then this is kind of a hacked-together way to handle paid workshop item licensing. Out of curiosity I wonder what sort of workshop content you are trying to sell access to - UIs?

**Comment by Trojaner** [comment]
It could be any kind of workshop content, I just noticed that people do this manually and struggle a lot

**Comment by SDGNelson** [comment]
Ah, I figured it was for a shop, not to help out existing items. Will prioritize higher then

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
