### ISSUE TITLE
 Request to add event:OnStatUpdate(byte newStat) in SDG.Unturned.Player.sendStat(EPlayerStat)

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1414]
Although the rocket has this method,but it was use TriggerSend .
The efficiency is too low. I want to subscribe directly.Reset rocket 4.0.
Thanks

**Comment by HanaForward** [comment]
My dear Nelson?

**Comment by SDGNelson** [comment]
Okay, in the next update there is an `onPlayerStatIncremented` event
