### ISSUE TITLE
France assets

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1415]
The map I've been working on has many France assets--maelstroms, churches, and guns/vehicles/items-- and today they've disappeared as a part of the France asset migration to the workshop. 
So I must ask, in a haze of fear, are the assets going to return when the full migration is done? I worry the assets previously placed will be gone forever, and it would indeed waste a huge amount of time to replace and re-add France item tables.

**Comment by SDGNelson** [comment]
Did you unsubscribe from the France workshop item? It's been setup for auto-subscription from this past Friday to February 7th, so it should be safe to assume most players have it and all of the associated assets.

**Comment by INeedHelp225** [comment]
No, I had not unsubscribed.

**Comment by SDGNelson** [comment]
Perhaps the France assets are disabled under the Workshop > Manage menu in-game?

**Comment by aman7** [comment]
assets are not going to be available for us same as hawaii and greece?

**Comment by SDGNelson** [comment]
To double-check I just loaded up the vanilla editor and was able to place the Eiffel Tower in PEI.

All curated map assets are available for use. 
Greece assets are bundled with the map here: https://steamcommunity.com/sharedfiles/filedetails/?id=1702240229
Hawaii assets are available separately here: https://steamcommunity.com/sharedfiles/filedetails/?id=1753131903

**Comment by INeedHelp225** [comment]
![image](https://user-images.githubusercontent.com/59327136/73228545-c56ee600-412b-11ea-8fb6-5a880c4a5942.png)
![image](https://user-images.githubusercontent.com/59327136/73228591-e59ea500-412b-11ea-8e99-dcbfd7a5143f.png)

Nothing appears? I had restarted the game multiple times and have been subscribed to the France assets.

**Comment by aman7** [comment]
> 
> 
> To double-check I just loaded up the vanilla editor and was able to place the Eiffel Tower in PEI.
> 
> All curated map assets are available for use.
> Greece assets are bundled with the map here: https://steamcommunity.com/sharedfiles/filedetails/?id=1702240229
> Hawaii assets are available separately here: https://steamcommunity.com/sharedfiles/filedetails/?id=1753131903

i know these and using it, i was talking about france's assets just like these maps

**Comment by SDGNelson** [comment]
Could you send over the Client.log file from the Unturned/Logs directory please @INeedHelp225? The only thing that comes to mind is that the items might not be registered in offline mode, but it appears you are online. We'll see if the log has other explanations.

 Are the France assets missing for you as well @aman7?

**Comment by aman7** [comment]
no its working fine with france server, but i want to use those assets in russia, washington, yukon and so on. which is missing

**Comment by INeedHelp225** [comment]
This is the file, yes?
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4125579/Client.log)

**Comment by SDGNelson** [comment]
It looks like it thinks the old version of France is still installed in Maps/France. One reason that comes to mind for this is if the map was locally edited, which I should improve the check for. In the meantime if you delete the local Maps/France folder it will load the workshop version.

**Comment by INeedHelp225** [comment]
Ah! That must be it! I used an unlocker script to see if there were any special constructions I could use in my own map. Thanks!
