### ISSUE TITLE
UI overlapping

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#1416]
Please add a form to set the ui in the top of the normal UIs

**Comment by SDGNelson** [comment]
By normal UIs are you referring to the built-in inventory, HUD, etc? The reason that they draw on top is because they use the Unity 4 IMGUI system. Reworking them to use the more recent systems in on the longer-term to-do list.

**Comment by Greenorine** [comment]
Is it possible to change order of layers for custom UI for overlapping?

**Comment by educatalan02** [comment]
Doctor means to set Workshop UI's up to Game HUDS

**Comment by X-Doctor-X** [comment]
> Doctor means to set Workshop UI's up to Game HUDS

Yes, i want to set a UI over the normal UIs of the game

**Comment by SDGNelson** [comment]
Nowadays this is possible because the game uses uGUI, and in the future plugins will be able to use the built-in UI functions.
