### ISSUE TITLE
/admin command is broken

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#1417]
I've got an issue where /admin isn't working at all 

I tried using steamid64 and all nickname combinations in game and from the console

/admins say there are no admins

**Comment by SDGNelson** [comment]
What does the output from running the admin command say? e.g. "Player not found"

**Comment by TickleMeEdwa** [comment]
Check your commands.dat and check if “admin” was set to false. If it was, set it “true”, save the xml and restart your server.

**Comment by SDGNelson** [comment]
Did it turn out to be the issue TickleMeEdwa mentioned?

**Comment by gegtor** [comment]
Sorry for not replying i forgot about it

It turned out to be an issue with rocket and unturned command conflict 

I swapped it in rocket.commands config file
