### ISSUE TITLE
Why Unable to use multithreading on Server？

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1418]
In the latest version I found that methods in MonoBehaviour cannot be called through threads

**Comment by megoesrawr** [comment]
Hopefully nelson can fix this. I really need this for one of my plugins.

**Comment by HanaForward** [comment]
This broke the asynchronous processing of my rocket

**Comment by SDGNelson** [comment]
Even if it seemed like your multithreaded code calling into the game thread was working, it was _**definitely**_ causing issues. You can run your own logic on other threads, however calls into the game thread should be made from the game thread.

What sort of logic were you running that was calling into these methods?

**Comment by HanaForward** [comment]
i was ues PETimer interval execution

**Comment by HanaForward** [comment]
the code : https://github.com/HanaForward/Rocket/blob/master/Rocket.Core/TimeTask/TimerTask.cs
No longer need coroutines
No need to call update * n (number of plugins)
Asyn calls will enable them to request network resources

**Comment by HanaForward** [comment]
@SDGNelson

**Comment by megoesrawr** [comment]
I had a delay timer for running other bits of code. I calling the movement plugin multipliers.

**Comment by HanaForward** [comment]
@SDGNelson plz add a even!! 
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1414

**Comment by SDGNelson** [comment]
Async calls to network resources outside the game code (e.g. database server) are perfectly fine. You will need to hand them over to the game thread for safe usage however. I suggest reading more about multithreaded programming before proceeding.

One way to handle timers for large numbers of objects would be to keep a list sorted by their expiry time, and then only update them as-needed from an Update call.

**Comment by HanaForward** [comment]
So will we not be allowed to use multithreading in the future?

**Comment by SDGNelson** [comment]
Multi-threading is allowed. You just need to understand how to write multi-threaded code properly.

Most Unity functions are **_NOT_** thread-safe. Some components of the game like the ThreadedConsoleInputOutput class are designed for multi-threading. Corrupting the network buffers from other threads is **_NOT_** thread-safe.

**Comment by HanaForward** [comment]
OK, thanks, can you add events?
