### ISSUE TITLE
Broken floors

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1420]
On the map Washington, in the brown building of Seattle, if you manage to get a zombie on the black stairs, it can move around the stairs normally and chase you. However, the zombie will glitch through the floors if you try to get the zombie on to any floor(except the first floor ofc).

**Comment by SDGNelson** [comment]
By the black stairs are you referring to the fire escape? https://cdn.britannica.com/64/123464-050-19FE04A3/Fire-escapes-balconies-exterior-building.jpg

The multistory buildings without stairs don't have multifloor navmeshes because the zombies aren't ordinarily able to get up there.

**Comment by AwesomeGOAT** [comment]
Yes, the stairs are the fire escape. S

**Comment by SDGNelson** [comment]
That's impressive you managed to get a zombie onto the next floor on Washington. If I recall correctly I put some "nav blocking volumes" on some of the zombie-accessible rooftops of Berlin to allow them to pathfind properly up there. Otherwise the zombies aren't normally able to get up there.
