### ISSUE TITLE
Level files not generating which ends up in frozen server after launch

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1421]
Have no idea what this might be related to. Happened twice  on two servers after wipe. Basically, I launch a server after wipe, it loads up fine but only vehicles.dat file is generated.  Players can't join as server doesn't fully launch.  Happily, in both cases one of the servers loaded up fine so I just used levels folder from that one.

After first fail to load, tried to remove all plugins and changed map to PEI - didn't help (didn't load up even on PEI map). Also, tried to verify files - didn't help either

Any ideas what might be the problem?

**Comment by SDGNelson** [comment]
To try this out I launched a few servers like "./ServerHelper.bat +InternetServer/GenFiles3", however they all generated their level files properly. If this happens again can you attach the server error log please?

**Comment by baranmod** [comment]
Alright, I will try to replicate it again. Sadly launched server with imported level files couple times and didn't think about server log file :D

Will update this issue once (if) I replicate it
