### ISSUE TITLE
Question-- how would you get the small boulders that are on the sides of the rivers on Washington?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1422]
![image](https://user-images.githubusercontent.com/59327136/73588115-ee6bdf80-4479-11ea-8a31-5a3ec03f8191.png)
My map's beaches are quite bare, and I want them to look like the rocky Washington beaches
![image](https://user-images.githubusercontent.com/59327136/73588127-05123680-447a-11ea-8613-d966a28c5209.png)
I have tried, with the little editor file knowledge I do have, to copy over files like the details/materials files to get the pretty stones to no avail.
So how would I get them? 
Thanks!

**Comment by SDGNelson** [comment]
I'm happy to hear you like the river-side stones! I think that was one of the biggest visual improvements when the foliage was reworked a couple years back.

They use a technically "newer" feature in the devkit, but are less user-friendly than the original ones. There isn't any documentation for it, but basically you place a "FoliageVolume" around the level and then click bake in the devkit foliage tool.

**Comment by INeedHelp225** [comment]
Ah, okay. Thanks!
