### ISSUE TITLE
Ammo counter drops fps by 20~

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1425]
Not sure if I am doing something wrong, yet it works as supposed to work but drops fps drastically (reminds me a bit of cameras usage on mods)

**Comment by SDGNelson** [comment]
Using a UI text component for ammo on the gun? One thing that comes to mind is if the resolution for the canvas render target is high. The performance should be similar to the signs.

**Comment by baranmod** [comment]
Did some testing today. Tried to take canvas out of sign example - same problem. Made two identical weapons (one with counter, one without). The one with counter always drops fps by 20-25. Also tried on lower-end laptop, drop was pretty much same even though idle is much lower
