### ISSUE TITLE
"Custom" Assets not appearing in editor.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1429]
[Durham_Commander.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4162510/Durham_Commander.zip)
To make non-conflicting propaganda posters for my NPC's quest I've copied the offical coalition posters and given them new names and new IDs.
I then went back into the editor to place the posters to see if the quest would work with them. The "custom" posters are not in the item list.

![image](https://user-images.githubusercontent.com/59327136/73796120-3e3ff480-4761-11ea-8a22-1c6c97a3d279.png)

[Propaganda_Coalition_Durham.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4156635/Propaganda_Coalition_Durham.zip)

**Comment by SDGNelson** [comment]
In the Menu > Workshop > Error Logs menu there may be an explanation. I think it should work fine to use the official posters on your map however, unless you need more in which case you can do what you've done and also set bundle override paths.

**Comment by INeedHelp225** [comment]
Thank you! Issue solved!
