### ISSUE TITLE
Question: ItemTool.getIcon from server

### ISSUE THREAD

**Issue by RestoreMonarchy** [SmartlyDressedGames/Unturned-3.x-Community#1430]
Hello,
I'm trying to use ItemTool.getIcon in RocketMod plugin to get item's icon Texture2D and then using `EncodeToPNG` get byte array to upload it to my web api.

When I'm using the code below it works weird, because callback is only called for **guns** and **melees**, but for any other item it's not called and I find in `/Logs` error message for each item
`[2020-02-03 16:57:33] (ItemShirtAsset) Parka_Red [166]: missing 'Icon' Transform`

Even though callback is called for guns and melees, the picture after .EncodeToPNG and saved as file  looks like [this](https://user-images.githubusercontent.com/35507241/73865560-bda5f480-4843-11ea-8428-a03e24bcca95.png) and only size is sometimes different, depends on size_x and size_y I believe.

```cs
ItemAsset itemAsset = (ItemAsset)Assets.find(EAssetType.ITEM, 363);
var ready = new ItemIconReady((icon) =>
{
    UploadItem(new UnturnedItem(itemAsset.id, itemAsset.itemName, (Marketplace.Shared.EItemType)itemAsset.type,
                                itemAsset.itemDescription, itemAsset.amount, icon.EncodeToPNG()));
});
ItemTool.getIcon(itemAsset.id, itemAsset.quality, itemAsset.getState(), ready);
```

I also tried executing `captureIcon` directly to get Texture2D without callback, some IconUtils methods, but always end up with the same result as above.

I know IconUtils is working for generating icons in Workshop menu in Unturned client, but is there any chance to get icons pictures on the server too?

Thank You

**Comment by surv0013** [comment]
@SDGNelson add method `EffectManager.sendUIEffectImageRaw(short effectKey, CSteamID steamID, bool reliable, string childName, byte[] raw)` so we can send images from the server

**Comment by educatalan02** [comment]
EffectManager.sendUIEffectImageURL
@surv0013

**Comment by RestoreMonarchy** [comment]
Hey @surv0013 how is that even related to my question?

**Comment by DiFFoZ** [comment]
You can't get Icon (Texture) from a server because Item Gameobject didn't load. Only from client


`if (!Dedicator.isDedicated || this.type == EItemType.GUN || this.type == EItemType.MELEE) // <--- !Dedicator.isDedicated
			{
				this._item = bundle.load<GameObject>("Item");
				if (this.item == null)
				{
					throw new NotSupportedException("missing 'Item' GameObject");
				}
				if (this.item.transform.Find("Icon") != null && this.item.transform.Find("Icon").GetComponent<Camera>() != null)
				{
					throw new NotSupportedException("'Icon' has a camera attached!");
				}
				if (id < 2000 && (this.type == EItemType.GUN || this.type == EItemType.MELEE) && this.item.transform.Find("Stat_Tracker") == null)
				{
					Assets.reportError(this, "missing 'Stat_Tracker' Transform");
				}
				AssetValidation.searchGameObjectForErrors(this, this.item);
			}`

**Comment by DiFFoZ** [comment]
Maybe try to load a bundle then capture and unload?

**Comment by RestoreMonarchy** [comment]
Hey, thanks for the reply  

Loading a bundle would probably solve `missing 'Icon' Transform` error and would execute callback for `ItemTool.getIcon()`, however it still won't fix an issue with capturing an icon, because though callback is executed for guns and melees it returns an empty picture like this one below.

I feel like it could be cause of necessary unity modules not being loaded for server?

![](https://user-images.githubusercontent.com/35507241/73865560-bda5f480-4843-11ea-8428-a03e24bcca95.png)

**Comment by RestoreMonarchy** [comment]
Ok, so I found the way to make `captureIcon` work for server, I had to remove `-nographics` from startup parameters and now I get pretty icon of an item.

However this works only for melees and guns, because when `captureIcon` is called for other items, it logs error `missing 'Icon' Transform`, so I tried the way you told me to load bundle for them although I'm not sure how can I do that, but I tried the way below `bundle.load<GameObject>("Item")` but yet it returns null.

```cs
ItemAsset itemAsset = (ItemAsset)Assets.find(EAssetType.ITEM, ushort.Parse(args[0]));
var ready = new ItemIconReady((icon) =>
{				
	Console.WriteLine("Icon is ready!");
	File.WriteAllBytes(this.Directory + $"/{args[1]}.png", icon.EncodeToPNG());
});

if (itemAsset.type != EItemType.GUN && itemAsset.type != EItemType.MELEE)
{
	var bundle = Bundles.getBundle(itemAsset.getFilePath());
	Console.WriteLine($"Is null: {bundle.load<GameObject>("Item") == null}");
	typeof(ItemAsset).GetField("_item", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(itemAsset, bundle.load<GameObject>("Item"));
}

ItemTool.getIcon(itemAsset.id, 0, itemAsset.quality, itemAsset.getState(), itemAsset, null, string.Empty, string.Empty, itemAsset.size_x * 50, itemAsset.size_y * 50, false, true, ready);
```

@DiFFoZ Can you show me the proper way to get bundle? 
Thanks in advance!

**Comment by SDGNelson** [comment]
It looks like you've made a lot of progress on this. I'm impressed!

There is some overhead to disabling -nographics, and going forward there is some risk that this will break because the dedicated server uses the "headless" Unity player.

For tomorrow's update I've added a command-line option `-AlwaysLoadItemPrefab` as a workaround.

**Comment by RestoreMonarchy** [comment]
I got it working now, many thanks!
