### ISSUE TITLE
France Attack Heli(Hind) still spawnable

### ISSUE THREAD

**Issue by awedy01** [SmartlyDressedGames/Unturned-3.x-Community#1432]
After the retire of map, files which were found in Bundles instead of Maps/France folder, are still PROBABLY available to download and use in the game, surely know it about the "Hind_France"(ID174).
I just downloaded Unturned in a different folder to check. (Unturned server edition(1110390)

**Comment by SDGNelson** [comment]
Good catch! The reason for this is that I added several objects and vehicles for France a while before the map's release so that they could be used. In order to keep things simple they will probably stay in the core game files.
