### ISSUE TITLE
Linux mono error

### ISSUE THREAD

**Issue by QnAisbest** [SmartlyDressedGames/Unturned-3.x-Community#1433]
After the last update linux server (debian 10) has been crashing because of mono error.
The error comes when the server is starting.

**Comment by Sl4vP0weR** [comment]
Can u send error info ?

**Comment by aman7** [comment]
you should include the error logs

**Comment by Mithallas** [comment]
Prob not be an unturned issue. I am having trouble loading mysqlkits plugin through trojaner's IPloader and its was also causing crashing. I just disabled that plugin and it works fine again. without a posted error people can only speculate.
