### ISSUE TITLE
New game currency

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#1435]
Of course, it’s great that now we can collect money (items) from the ground and exchange with NPCs, but I would like to have some kind of currency that would not occupy a place in the inventory. Yes, this can be implemented using the plugin, but then we will have to make purchases through the plugin, because the objects in the game are made for the economy of the game. Of course, we can use experience, but it is also used to improve skills. Nelson, please add a currency that does not take up space in the inventory and can be exchanged.
![image](https://user-images.githubusercontent.com/17459138/74090604-ae82a900-4ac6-11ea-8c8c-d91886428712.png)

**Comment by TickleMeEdwa** [comment]
Such ‘thing’ already exists with rocket plugins

**Comment by SDGNelson** [comment]
It's unlikely that something like this will be added to vanilla anytime soon - the currency feature was added for a few curated maps and mods that will hopefully take advantage of it. My intention for reducing space was that larger denominations can be used, and theoretically the currency items could be stacked though 3's item stacking support is not great.

@TickleMeEdwa is right that the best option for now would be a plugin. For example a plugin could track each player's global balance and provide a UI for depositing items into their balance and withdrawing from their balance as currency items. The currency-related classes have a few helper functions for converting between items and quantity, and converting between denominations.
