### ISSUE TITLE
Errors on Linux Servers because a screen is expected

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#144]
On headless linux servers, the following exception occurs:
```
IndexOutOfRangeException: Array index is out of range. - SDG.Unturned.GraphicsSettingsResolution..ctor ()
    SDG.Unturned.GraphicsSettingsData..ctor ()
    SDG.Unturned.GraphicsSettings..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for             
    SDG.Unturned.GraphicsSettings
    SDG.Framework.Landscapes.Landscape.Awake ()
    UnityEngine.GameObject:AddComponent(Type)
    SDG.Framework.Devkit.LevelHierarchy:read(IFormattedFileReader)
    SDG.Framework.Devkit.LevelHierarchy:load()
    SDG.Framework.Devkit.LevelHierarchy:handleLoadingStep() 
   SDG.Unturned.<init>c__Iterator0:MoveNext()
   UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

This happens because in `GraphicsSettingsResolution` the following line: 
`public GraphicsSettingsResolution() : this(Screen.resolutions[Screen.resolutions.Length - 1])`
is expecting at least one screen, but on headless linux servers there are no screens, hence `Screen.resolutions.Length` is 0 and its trying to access `Screen.resolutions[-1]`, which causes this exception.

There is no known workaround, except maybe by creating a virtual screen on a X11 server ([Xvfb](http://www.wikizero.org/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvWHZmYg)).

Fix:
``public GraphicsSettingsResolution() : this(Screen.resolutions.Length > 0 ?
 Screen.resolutions[Screen.resolutions.Length - 1] :  new Resolution()) ``

**Comment by SDGNelson** [comment]
Thanks for the very comprehensive report! Fixed in this Friday's patch.
