### ISSUE TITLE
Changes on mods doesn't go on effect even after first game restart

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1440]
When mod is updated and server launches - players won't see changes when they connect, even if they restart game before joining. Basically, player would have to restart game couple times for changes to go on effect.

**Comment by SDGNelson** [comment]
If the player is in-game when the server is restarted and subscribed to it then they won't get the changes until Steam downloads the update and they restart the game. It can take some time before the Steam client detects a change and the download scheduler queues it.

One option to force an update check is to run "Validate Game Files" on the client which will find workshop updates and download them.

If they aren't subscribed to the item then they might get the update when they reconnect to the server, but it depends whether they get a cached response from the UGC query.
