### ISSUE TITLE
Lin_Ain's Feature Requests

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1442]
All suggestions are taken from this thread. These are quoted exactly.
https://forum.smartlydressedgames.com/t/unturned-3-0-suggestions-which-are-useful-and-not-difficult-to-archive/13502

1. Add Armor_Piercing_Multiplier(APM in short) to magazines. It doesn’t need to have complex mechanism like Escape from Tarkov. When the target is hit, the damage should be like Damage = Basic Damage x Armor x APM, and if Basic Damage x Armor x APM > Basic Damage, then the Damage = Basic Damage. (Most important function. This fuction can totally make different weapons have different use. Like for smg, they have high rpm and normal damage, but low APM, so they are suitable to damage those enemies without armor. And for bolt-action rifle, they share the same damage with dmr, but have higher APM, so they are suitable to damage enemies with heavy armor. This function can solve the awkward situation that the only way to make a weapon useful is increasing its damage and decreasing its recoil.)

2. Add Ballistic_Drop from Barrels to Magazines. So we can make different magazines have different use. (I tried to make a rifle with underbarrel launcher before. When using ‘normal’ magazine, it shot bullets. When using ‘grenade’ magazine, it shot grenade. The only problem is that grenade will be launched too far. If magazines have Ballistic_Drop, I just need to add this to ‘grenade’ magazine.)

3. Add durability to Medicals. When using the medical, it will lost a part of durability and when durability reaches 0, the medical will disappear.

4. Add long time buff to medicals. Such as Adrenaline, it only recover Energy in one second now. If we have a buff like recovering energy per second in 1 minute, the Adrenaline will be more useful. Health buff will also be a good idea.

5. Movement_Multiplier to clothes (or at least vest and helmet).

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
