### ISSUE TITLE
[EDITOR QUESTION] How would I go about creating a teleporter similar to that of Germany?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1453]

**Comment by SDGNelson** [comment]
Sorry for missing this earlier. Did you figure it out? Basically the teleporters are interactable objects with a teleport "reward" type that specifies the destination.

**Comment by INeedHelp225** [comment]
Oh, no problem. I fixed the issue with an NPC quest. Sorry for the awfully broad question.
