### ISSUE TITLE
Costume loading screen

### ISSUE THREAD

**Issue by DerSpace** [SmartlyDressedGames/Unturned-3.x-Community#146]
**What do i mean?**

I was hopping Nelson could add a custom loading screen where we can make some sort of Animation for the loading and maybe the owner of the servers can put some background music while it loads in, This just add more feature's for unturned and i think its a great idea.

**Thankyou for your time.**

**Comment by yourmumlovedick** [comment]
I think its a good idea but please change the song every month and can u do a vote for chose the music.

**Comment by SDGNelson** [comment]
Unturned loads the map/server on the main thread so it would stutter a lot. The loading screen customization is mostly limited to the map loading image at the moment.

**Comment by viktnnchik** [comment]
Is there somewhere I can change the loading screen when logging into my server?
