### ISSUE TITLE
[Request] Event "onServerLoading" with CSteamID of player

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1463]

**Comment by rube200** [comment]
when should this happen?

**Comment by Sl4vP0weR** [comment]
Level.loading();

**Comment by SDGNelson** [comment]
Server-side event for when the player has begun trying to connect? What do you have in mind usage-wise?

**Comment by Sl4vP0weR** [comment]
> Server-side event for when the player has begun trying to connect? What do you have in mind usage-wise?

I want to change server info while player is loading for bypass WORKSHOP_ADVERTISMENT_MISMATCH, that are will give me ability to set NoWorkshop with workshop mods loading

**Comment by surv0013** [comment]
> > Server-side event for when the player has begun trying to connect? What do you have in mind usage-wise?
> 
> I want to change server info while player is loading for bypass WORKSHOP_ADVERTISMENT_MISMATCH, that are will give me ability to set NoWorkshop with workshop mods loading

So Nelson, on the contrary, is fighting this 😄

**Comment by Sl4vP0weR** [comment]
> So Nelson, on the contrary, is fighting this 😄

My friend lose online cuz server have UI mods and he can't change workshop on No

**Comment by SDGNelson** [comment]
This is intentionally enforced by the game. If players have switched the workshop filter from Yes to No then they should not be finding servers with workshop items.
