### ISSUE TITLE
(Request) More than one light source for Night Light Script

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1464]
Add_Night_Light_Script works only if object has only one Light in Unity. Is this possible to make more than one light source for this script?

**Comment by SDGNelson** [comment]
Fair point. Recently I saw a project which was added them directly in Unity, so I should set it up with the other "event hook" scripts. One option in the meantime is you could actually use the WeatherEventHook script and wire up multiple lights to the day and night events.
