### ISSUE TITLE
Offensive animals running away

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1465]
Can't tell if its a bug or been done on purpose but when you shoot to offensive animal from higher distance than its aggression range they simply run away like passive animals. 

Maybe it would be possible to add some option to config so animal would always attack player?

**Comment by iBowie** [comment]
It's a feature

**Comment by SDGNelson** [comment]
Odd, I'll check it out.

**Comment by SDGNelson** [comment]
Thanks! Will be fixed in the next update.
