### ISSUE TITLE
BattlEye disabled Warning

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#147]
![](https://vgy.me/oITg3d.png)

Apparently everyone starts getting this warning now...

**Comment by N1GHTPATROL** [comment]
+1

**Comment by Trojaner25** [comment]
This seems to be on purpose, workaround for #145 probably?

**Comment by FredMods** [comment]
License run out?

**Comment by SDGNelson** [comment]
In the Greece update the -BattlEye command line argument was accidentally removed so the game didn't know if BattlEye was running, which was quickly fixed.
