### ISSUE TITLE
Game bans

### ISSUE THREAD

**Issue by Summerboy2020** [SmartlyDressedGames/Unturned-3.x-Community#1471]
Hi Nelson, please pay attention to what I will tell. Half a year ago I downloaded cheats to take revenge, later deleted it and never started it. Yesterday afternoon I was banned by BattlEye. I completely uninstalled the game (and reinstalled later) and created a new account. However, I was also banned. No cheats have been obtained for a long time already in the game and on the computer, but there are still bans.

**Comment by educatalan02** [comment]
The point is that you used cheats.

**Comment by Summerboy2020** [comment]
> The point is that you used cheats.

Hey, half year ago

**Comment by educatalan02** [comment]
You have also used them.

**Comment by Summerboy2020** [comment]
> You have also used them.


This is not logical

**Comment by MoltonMontro** [comment]
Bans are not distributed nor removed by SDG. All bans are handled automatically by VAC and BattlEye, and are non-appealable if you cheated.
