### ISSUE TITLE
(Assistance Needed) False Ban

### ISSUE THREAD

**Issue by TacoExtreme0** [SmartlyDressedGames/Unturned-3.x-Community#1472]
Hello Nelson. Please read this.
I was using a plugin created for a Roleplay server when I was logged out and banned by BattleEye. I have never used a modded client for Unturned nor installed one. 
Reach out for more information.
Thank you.
-Taco

**Comment by TacoExtreme0** [comment]
A bit more descripitve:
I was in the Plugins HUD checking out how it worked. Both me and the Developer are confused of why this happened. I clicked a button on the HUD and it logged me out, banning me. 
I have contacted BattlEye support but chances of them reaching out are low.

**Comment by SDGNelson** [comment]
For anyone reading this: yesterday there was a BattlEye upgrade causing a lot of bans, so of course there is a surge of disingenuous "please unban" posts.

Contacting BattlEye support as you mentioned is the right course of action.
