### ISSUE TITLE
Issue with shirt bounds

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1476]
Ok. I downloaded Unity 2018.4.0f1 (Not Linux Standalone). I used Items guide from Steam. And... Shirt has bounds like on picture below. 
![image](https://user-images.githubusercontent.com/59829274/75030698-b9b9d980-54b5-11ea-99a4-19338f8e8056.png)

After this I watched some YouTube guides, and everything ok there. The new Unity project was created. I just imported there only Project and ExampleAssets. Used Chef_Top example shirt, exported it as .unity3d (and then even .masterbundle), and now we have same thing. 

.dat and English files were the same as in Chef_Top in-game folder besides GUID and ID. Is everything ok? What should I do to make bounds work properly?

**Comment by SDGNelson** [comment]
Is the material set to Cutout render mode? I suggest importing the ExampleAssets.unitypackage and comparing your material to one of the built-in materials.

**Comment by NoThreat** [comment]
It was set to Cutout. As I said, I fully used your ready example, with all already tuned settings. And that's what I have. Any ideas why?

**Comment by CyberAndrii** [comment]
Change the color space to linear if you didn't.

**Comment by NoThreat** [comment]
> Change the color space to linear if you didn't.

I don't know exactly where to find "Color Space", but think it is already done because it is example, what can go wrong?

**Comment by CyberAndrii** [comment]
I had this issue when I used `Asset_Bundle_Version 2` (3 works fine), so you probably spelled this line wrong. But then you will get another problem: your shirt will be brighter than vanilla one, so you need to change color space. https://prnt.sc/r65bcl

**Comment by NoThreat** [comment]
It's works now, thank you, but Nelson should write about this in Workshop guide to prevent beginners do this mistake.

**Comment by SDGNelson** [comment]
Was it the color space, or asset bundle version that sorted it out? Importing the unity packages should set the project to Linear color space because the settings files are included. 🤔 

Thanks @CyberAndrii for helping!

**Comment by CyberAndrii** [comment]
The package should include the `ProjectSettings.asset` file to do this. Currently, it doesn't.

![Screenshot_4](https://user-images.githubusercontent.com/37713088/75112532-709c8d80-564d-11ea-989f-7bdfc134937c.png)

**Comment by SDGNelson** [comment]
Thanks again! The reason I didn't originally include ProjectSettings.asset is because it also includes a lot of other settings like preprocessor defines, but I will start including it in the next update.
