### ISSUE TITLE
Rubberbanding on Roads

### ISSUE THREAD

**Issue by WarpKat** [SmartlyDressedGames/Unturned-3.x-Community#148]
3.23.0.0 update left us with some rubberbanding on the roads, particularly in Washington - have not tested Greece, PEI or Russia (yet).

**Comment by Hiddens1337** [comment]
I have same problem. Ubuntu 16.04. Without plugins, without mods. just clear server.

**Comment by SDGNelson** [comment]
Unable to replicate on my server the other day. Has this still been happening?

**Comment by Hiddens1337** [comment]
Hi, this problem was fixed after 3.23.1.0 i think. thanks.

**Comment by WarpKat** [comment]
Hey Nelson - I think this was fixed in the last update.  None of my players (nor I) have been experiencing the issue since then.

**Comment by SDGNelson** [comment]
Glad to hear! Will close the issue then.
