### ISSUE TITLE
[Suggestion] Objects that link together

### ISSUE THREAD

**Issue by TinyGiraffes** [SmartlyDressedGames/Unturned-3.x-Community#1480]
Hello, it would be cool to see objects that link together, for instance, I have a 3.0 Metro map I've been making but the tunnels have gaps or don't line up correctly because it's hard to line them up exactly and they need to be exact. I could make them all the same object but then I would be rendering things that don't need to be rendered and it would mess up render distances. If there was a linking system where I could pick objects to link when they get close to each other that would let me link these tunnels more neat and tidy. Maybe there's a trick for this I don't know but other than making the tunnels a road, I'm not sure. Love the additions to 2!

**Comment by SDGNelson** [comment]
The built-in way to do this is pressing Ctrl+B to copy an object's transform, and then press Ctrl+N with another object(s) selected to paste the transform. This is useful for props designed to fit together like roads, or in your case it sounds like custom tunnels. Hopefully that does the trick! Curious to see the metro map.
