### ISSUE TITLE
Single Request for mass UI changes (Suggestion)

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#1481]
As you may've already seen some servers decided to put a huge amount of dynamic UI on information billboards with whatever information to show that requires to send (and update instantly if some button was pushed or time has come) a large amount of requests with tellUIEffectText method for keeping everything correctly displayed and which may be causing perfomance impact on servers and clients. And also it's causing delays on text that is being changed (imagine that'd be happening every second with 10 or even more text objects on UI effect for player with 100ms ping or higher).
It'd be more flexible synced and better with a small addition to EffectManager class with a new method like tellUIEffectMassTextReplace accepting 2 string arrays (keys and values) where keys => UI Effect child names, and values => list of texts that needs to be changed on the same indexes as in the first (keys) array.

Code example based on your tellUIEffectText method:
```
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void tellUIEffectMassTextReplace(CSteamID steamID, short key, string[] childNames, string[] texts)
{
    if (!indexedUIEffects.TryGetValue(key, out var value))
    {
        UnturnedLog.info("tellUIEffectMassTextReplace: key {0} not found (childNames: {1}, texts: {2})", key, string.Join(", ", childNames), string.Join(", ", texts));
        return;
    }

    if (value == null)
    {
        UnturnedLog.info("tellUIEffectMassTextReplace: key {0} was destroyed (childNames: {1}, texts: {2})", key, string.Join(", ", childNames), string.Join(", ", texts));
        return;
    }

    for(int i = 0; i < childNames.Length; i++)
    {
        if(i >= texts.Length)
        {
            return;
        }

        var child = value.transform.FindChildRecursive(childNames[i]);

        if(child != null)
        {
            var textComponent = child.GetComponent<Text>();
            if(textComponent != null)
            {
                textComponent.text = texts[i];
            }
            else
            {
                UnturnedLog.info("tellUIEffectMassTextReplace: '{0}' does not have a text component (key {1} text {2})", childNames[i], key, texts[i]);
            }
        }
    }
}
```

Obviously you can place here some limitations and provide a new extension method as well for finding all childs recursively with given names without returning after first match.

This problem applies to tellUIEffectVisibility method too cause it's causing flickering effects on massive requests when you want to display some lists or change a color/font of some blocks for example.

tellUIEffectMassToggle:
```
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void tellUIEffectMassToggle(CSteamID steamID, short key, string[] childNames)
{
    if (!indexedUIEffects.TryGetValue(key, out var value))
    {
        UnturnedLog.info("tellUIEffectMassToggle: key {0} not found (childNames: {1})", key, string.Join(", ", childNames));
        return;
    }

    if (value == null)
    {
        UnturnedLog.info("tellUIEffectMassToggle: key {0} was destroyed (childNames: {1})", key, string.Join(", ", childNames));
        return;
    }

    for(int i = 0; i < childNames.Length; i++)
    {
        var child = value.transform.FindChildRecursive(childNames[i]);

        if(child != null)
        {
            child.gameObject.SetActive(!child.gameObject.activeSelf);
        }
        else
        {
            UnturnedLog.info("tellUIEffectMassToggle: childName '{0}' not found (key {1})", childNames[i], key);
        }
    }
}
```

**Comment by Raxul257** [comment]
I am creating UI system that often has to change different text cells. It would help a lot. @SDGNelson would it be possible to include it in the next update?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
