### ISSUE TITLE
Hawaii roads not placing

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1483]
Navigation too. On other map (PEI, Russia, Washington) editors you can place new roads/navigation. On Hawaii you can only change and edit already placed roads and navigations, but can't create new. What's wrong with Hawaii?

**Comment by SDGNelson** [comment]
It looks like the misc editor handles underneath the ground and in the background are taking priority (e.g. there are lots of dark areas). If you disable them in the visibility tab it lets you place roads and navmeshes.
