### ISSUE TITLE
Low button tracking functionality 

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#1485]
For plugins, the functionality of tracking a player's button click is very small. I ask you to increase the number of available keys or give full access to the player's keyboard. This is necessary for plugins that trigger certain events when a button is clicked. Without this functionality, many plugins have to be done in a different, stupid way, or not at all.

**Comment by rube200** [comment]
Check this #395

**Comment by Greenorine** [comment]
> Check this #395

Yes, I know about this discussion, but even after it, the functionality was not great.

**Comment by rube200** [comment]
as you disagree instead of partitions in the discussion you opened the new one. Nice

**Comment by Sl4vP0weR** [comment]
I think all buttons tracking = more abilities.
Abilities = community creativity.
@SDGNelson
