### ISSUE TITLE
Mass DC caused by server receiving extra input packets?

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#1489]
![image](https://user-images.githubusercontent.com/35437320/75625178-b807b880-5c0f-11ea-994a-d668ced4b565.png)
Randomly happens, everything is fine then mass DC

**Comment by bjorn29922** [comment]
I got the same thing

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time! Looking back at this my guess is the server hitched for long enough that a whole bunch of inputs came in at once. Hitching was somewhat improved with rewrites to time-slice instantiation of certain networked objects, but there is still work to do especially on the server side. If you still happen to be hosting servers and  running into this please feel free to comment and I will re-open.
