### ISSUE TITLE
"Missing Object GameObject Highly Recommended to fix"?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1491]
![image](https://user-images.githubusercontent.com/59327136/75821218-b7c40600-5d52-11ea-864e-4014dbad2108.png)

I'm finishing off a custom map. So people don't need to install extras, I've bundled NPCs and their Dialogues/Quests/Vendors, they work perfectly fine. I then bundled my lore notes in a similar manner.
![image](https://user-images.githubusercontent.com/59327136/75821407-0f627180-5d53-11ea-839f-258556776982.png)
![image](https://user-images.githubusercontent.com/59327136/75821417-14bfbc00-5d53-11ea-899f-f08f88cede6a.png)
I then finish bundling the notes in their respective folder, and get back into the game and check the workshop editor problems thing, finding "Missing Object GameObject Highly Recommended to fix"

I am confused, but perhaps it has to do with how the code for the notes work? I noticed a difference between the code I used (Copy and pasted, then changed, from the official game) and the France Notes.
![image](https://user-images.githubusercontent.com/59327136/75821654-8435ab80-5d53-11ea-91d4-3630a83281c7.png)

**Comment by INeedHelp225** [comment]
Nevermind, lol, I used the France code as a reference and now the notes work.

**Comment by Spebby** [comment]
Can you close the issue then?

**Comment by INeedHelp225** [comment]
Oops, thought i did
