### ISSUE TITLE
Harmony for Unturned 

### ISSUE THREAD

**Issue by Trankvil** [SmartlyDressedGames/Unturned-3.x-Community#1496]
good afternoon. I'm trying to set up harmony for my project in Unturned. I want to configure it to view data in the method when there is for example a call to the sendEffect method, so that I can get data from it that it received such a ushort id and Vector3 point. Tell me an example of the code, how it can be implemented, I do not get it, unfortunately.

**Comment by archie426** [comment]
@Trojaner guess what

Use CS detour if you're a beginner it's a single static class. Harmony is overcomplicated and its features are redundant for something like this.
If there are multiple sendEffect methods (which I believe there may be), make sure you are getting a list of them and then selecting them by parameters.

**Comment by Trojaner** [comment]
Do not use CS detour. It will override other plugins patches and cause conflicts, hence is not suitable for plugins. It is mostly used only by cheating software.

Regardless of that, this is not the place to ask for Harmony issues. Ask them on the Harmony repository.

**Comment by Trojaner** [comment]
You can define parameters for patches like this:

![image](https://user-images.githubusercontent.com/1809172/86914436-06cadf00-c129-11ea-98b2-a79af01ac050.png)

**Comment by archie426** [comment]
Can you close this before you make me and trojaner argue about why harmony is overcomplicated for newbies which I will win @Trankvil
