### ISSUE TITLE
Include inactive UI elements

### ISSUE THREAD

**Issue by Raxul257** [SmartlyDressedGames/Unturned-3.x-Community#1499]
Right now UI elements (Button, Text, InputField) must be set to active to work with for example `EffectManager.onEffectButtonClicked`. If I don't want player to see some of these elements I can use `EffectManager.sendUIEffectVisibility` right after sending UI but setting `includeInactive` parameter of `GetComponentsInChildren` function to `true` seems like be a better way to do handle it - less packets sent and UI will get smoother.

**Comment by SDGNelson** [comment]
That makes sense. Will change that.
