### ISSUE TITLE
Anti-Water Volumes

### ISSUE THREAD

**Issue by Hexadec1ma1** [SmartlyDressedGames/Unturned-3.x-Community#150]
I don't think it'd work too well with water volumes, so how about a volume that removes water from the legacy water (the water level thingy in the legacy editor)? This would be pretty great for underwater bases in large oceans that don't use the devkit's water volumes.

**Comment by SDGNelson** [comment]
Unfortunately it would only be able to remove the physics effects. The visual effects like bubbles, fog and blur would be non-trivial to mask out.
