### ISSUE TITLE
[Request]Add LiteNetLibs to the network rework

### ISSUE THREAD

**Issue by erik7302** [SmartlyDressedGames/Unturned-3.x-Community#1503]
For what i see in other game like 7 days to die it work better most of the time(Better ping). if gets implemented the server owner has to select between steamnetwork or LiteNetLib, being steam the default one, maybe also a third option "client selection" where the client select which use and cant be change while connected to the server.

**Comment by SDGNelson** [comment]
Most likely there will be two official implementations (old Steam P2P vs new Steam sockets) and a debug non-Steam implementation. Ideally this library could be implemented externally. I would not be inclined to introduce another 3rd-party dependency to the base game however.
