### ISSUE TITLE
Static PlayerEquipRequestHandler

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#1504]
It would be better to have a static PlayerEquipRequestHandler like onCraftBlueprintRequested in PlayerCrafting

**Comment by Charterino** [comment]
Coders these days lmao

**Comment by GazziFX** [comment]
If you think that the current solution is more suitable, then why a similar event in crafting is marked with Obsolete attribute?

**Comment by SDGNelson** [comment]
It is unfortunately inconsistent compared to some of the other static events. 

While the static objects are easy, they are severely overused in Unturned's codebase. Ideally it would be cleaned up, but it would be pointless vs other development tasks. Will ponder what to do about some of these inconsistent cases.
