### ISSUE TITLE
Trying to get console input working with management panel

### ISSUE THREAD

**Issue by Greelan** [SmartlyDressedGames/Unturned-3.x-Community#1505]
This is a long shot, but thought I'd ask anyway.

I use an application management panel ([AMP](https://cubecoders.com/AMP)) to manage several game servers. The panel comes with pre-built modules tailored to a number of different games so that it can seamlessly act as the frontend. The panel works by running each game server instance in a tmux session, so it can run multiple games, and multiple instances of the same game, at the same time.

There is no specific module for Unturned but the panel does have a ["generic" module](https://github.com/CubeCoders/AMP/wiki/Configuring-the-'Generic'-AMP-module) that allows for basic configuration to work with a range of different applications. To build it, you specify a number of different parameters in a template configuration file - type of OS the application runs on, where the application software is obtained from, what executable is to be run to start it, ports, startup arguments, etc.

The panel is supposed to able to interact with the application to provide a console, using one of a range of methods specified, including stdio and various forms of RCON.

I've written a generic module template to use with Unturned Dedicated Server (steam app id 1110390). It functions just fine for almost everything - it is able to download the server files from steam and install them, start the server with the correct arguments, and show console output (and even parse that output so that the panel knows when the application has started up and when users connect to and disconnect from the game).

However, I cannot get console input to work through the panel. I've tried both the stdio method and telnet RCON using RocketMod. I've also tried various flags on the command line, in different combinations with the communication method - `-ThreadedConsole`, `-NoDefaultConsole -logfile 2>&1`, and `-LegacyConsole`.

I also tried changing `export TERM=xterm` in `ServerHelper.sh` to `export TERM=screen`, given the panel starts game applications in tmux.

Nothing works to allow me to pass commands to the server through the panel's console.

I realise this is probably more an issue for the panel's developers to help figure out how the panel is trying to interact with Unturned (I have raised the issue with them too), but I thought I'd ask here in case there were any obvious pointers where a management panel that uses tmux is being used as the frontend to an Unturned Dedicated Server.

Using Ubuntu 18.04.4, Unturned Dedicated Server v3.20.3.1 and the bundled RocketMod v4.9.3.0.

Thanks!

**Comment by GazziFX** [comment]
You can code your plugin/module that creates thread for recieve and enqueue commands. And process this queue with CommandWindow.input.onInputText(string) in void Update() (Because some methods can be called only in main thread)

**Comment by SDGNelson** [comment]
Unfortunate that it is not working with that input passing method.

Depending how far you would like to go with customization, this would be a great use case for implementing the `CommandInputOutput` interface. Your c# class could read and write from the web service however you like.

It sounds like you have experimented thoroughly with the existing options. I do not have anything to suggest beyond those, so hopefully the panel devs have an idea.

**Comment by Greelan** [comment]
Appreciate the responses. I’m now working with the panel devs to try to understand how the panel communicates via RCON, to see if something can’t be worked out there. The other pointers may be useful to the panel devs in developing a dedicated module for Unturned, if they are inclined. Thanks
