### ISSUE TITLE
Vanilla Rich text messages

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#1506]
There should be an option to force vanilla Unturned to use rich text message instead of normal messages (or to send all messages as rich text message).

This will make chat messages consistent when using rich text plugins (whose messages do not fade away)

**Comment by UncleLYHME** [comment]
I can second this of someone who uses a lot of rich text based plugins.

**Comment by SDGNelson** [comment]
Makes sense, will do. Ideally the UI will be moved off IMGUI in order to support rich text transparency in the future.
