### ISSUE TITLE
Suggestion for startup arguments for Unturned Servers.

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1507]
Hey @SDGNelson,
I was wondering if at some point you and/or Tyler "MoltonMontro" planned to add to the dedicated server guide all of the different startup arguments that server owners can use to fix certain issues or to modify the server performance e.g. -NoDeferAssets, -LogAssemblyResolve, and so on, just so that newer server owners and older server owners have an idea of what each argument does.
Thanks!

**Comment by SDGNelson** [comment]
It's a good idea. Most of the options should are not too important though, e.g. -LogAssemblyResolve is only useful when working with non-RocketMod plugins. I should setup automation for this because most of the newer CL args register themselves automatically.

**Comment by joeymisfit** [comment]
Fair enough, I was just thinking it would be useful so that we can prolong the life of our Game Servers without as many consistent issues.

**Comment by CatzMR** [comment]
It is recommended to list the values, parameters and the like that can be used to open the server, and make the server documentation. @SDGNelson
