### ISSUE TITLE
GUID Issues

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#151]
Hello,

Currently workshop items with the same ID will brick themselves when used on the same client. It would be amazing if Unturned could distinguish between the two IDs so if another mod uses the IDs then Unturned will not be confused. This would be helpful so people don't have to re-upload content to get it to work together. Thanks!

**Comment by SDGNelson** [comment]
Unfortunately it's too late in the development of 3 to make such a far-reaching change as this, but I'm making sure to avoid similar issues in 4.
