### ISSUE TITLE
Text Chat event Hook doesn't work on server

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#1510]
The Unturned script Text Chat Event Hook work in singleplayer but not in server.

For example the door in the metro of Russia (night and anastasia in area chat) works solo but not online. Go check please

**Comment by SDGNelson** [comment]
IIRC this was also reported by email, but I was unable to reproduce it (worked fine in singleplayer and multiplayer).
