### ISSUE TITLE
New Map Size

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#152]
Hello, I think it would be a good idea to set a new map size in between Small and Medium, considering medium is 4x the size of small. This would be helpful for servers owners to make/choose maps which are not way too big, but not too small because medium is way too big and small is too small. Thanks!

**Comment by FredMods** [comment]
Devkit.

**Comment by Torubloo** [comment]
Devkit can have custom max sizes afaik, also can change the size of an existing map

**Comment by N1GHTPATROL** [comment]
No documentation available on that, please let me know otherwise.

**Comment by MoltonMontro** [comment]
Just open up the Devkit and add more tiles, or remove tiles. You can't be using legacy terrain, however.

**Comment by SDGNelson** [comment]
The best option for this at the moment would be to use a medium map and restrict the play area with clip volumes/cliffs/etc. You could decorate the area outside them similar to other areas outside the map.
