### ISSUE TITLE
Expand ItemConsumeableAsset by adding Thirst, Tire and Starve

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#1522]
We have counter-part for `Virus` that is called `Disinfectant`. It would be great to have counter-parts for `Food`, `Water` and `Energy` - `Starve`, `Thirst` and `Tire` respectively

**Comment by SDGNelson** [comment]
IIRC this was eventually added by allowing negative values! :)
