### ISSUE TITLE
Cars stuck in the sky

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1523]
I use a hook on the server. When I hook the car and let it go, there is a chance that it will fly high into the sky, from where it will never return. At first I thought that they disappear there, but as it turned out later, the cars got stuck. For what reason, I do not know.
Also on the server I use the / jump command. If I look into the sky and enter this command, I will also be stuck in the sky.

![image](https://user-images.githubusercontent.com/46658857/76881698-34420300-6882-11ea-9272-faeecae2cdb2.png)
![image](https://user-images.githubusercontent.com/46658857/76881703-386e2080-6882-11ea-8319-5d1af68df6cf.png)

**Comment by SDGNelson** [comment]
During loading cars should be clamped back into the playable space unless there is an invisible wall at the top of the sky. I will check it out.

**Comment by SDGNelson** [comment]
I was mistaken: they were only clamped back if their position was "not finite" i.e. NaN or infinity. In the patch tomorrow they should get moved down back into the playable space.
