### ISSUE TITLE
In-game build mode copy/paste

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1525]

**Comment by JackSONGaO** [comment]
How about implement this function by adding a shortcut of give command？
I propose to add a give command in In-game build mode，like in this photo.
![图片1](https://user-images.githubusercontent.com/39083648/76911433-f5489780-68eb-11ea-9e91-04b1d871e660.png)

**Comment by SDGNelson** [comment]
Closing because it is a copy of #1490, my bad
