### ISSUE TITLE
[FEATURE REQUEST] Chart Size, Position & Shape Customisability

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1526]
- Allow for specification of Chart aspect ratio
- Offset Chart's Camera position (Useful when the center of a map isn't 0,0,0)

**Comment by SDGNelson** [comment]
Can you clarify the "grid based" aspect of this?

**Comment by educatalan02** [comment]
With Grid he probabbly means with Coords like that: 

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fplayrust%2Fcomments%2F7q80v4%2Fplease_explain_why_the_fuck_this_is_a_spawn%2F&psig=AOvVaw3cXvYKU0wS-yVL6NhBldnC&ust=1585004461933000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIDunvGXr-gCFQAAAAAdAAAAABAM

**Comment by Spebby** [comment]
The Chart/GPS baking position would move based on tiles, not based on the origin point of a map. I suppose a better name would have been "Tile Based Chart System"

**Comment by Spebby** [comment]
added in 3.22.15.0
