### ISSUE TITLE
being able to place lockers in apc

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1529]
http://prntscr.com/rijyji
http://prntscr.com/rijzk0

also this
http://prntscr.com/rijwcw

**Comment by SDGNelson** [comment]
It looks odd but placing lockers inside the APC is fine I think.

What's the third image?

**Comment by surv0013** [comment]
> What's the third image?

I think, this is sentry in APC

**Comment by Erkan53** [comment]
> It looks odd but placing lockers inside the APC is fine I think.
> 
> What's the third image?

sentry in metal wall
