### ISSUE TITLE
glitching under the map with 1 seater makeshift vehicle

### ISSUE THREAD

**Issue by Erkan53** [SmartlyDressedGames/Unturned-3.x-Community#1532]
https://www.youtube.com/watch?v=5jxQZRqGLyQ
i saw this video on youtube nelson please fix

**Comment by SDGNelson** [comment]
Hmm thanks for the link - the exit points for the 1 seater might need some fixing up.

**Comment by SDGNelson** [comment]
Should be fixed in tomorrow's patch! Vehicle exit points will properly test whether they intersect the terrain.
