### ISSUE TITLE
Car speed wont go over 20 mph

### ISSUE THREAD

**Issue by BoneCrusher03** [SmartlyDressedGames/Unturned-3.x-Community#1534]
I found a  car mod recently but the cars dont go over 20 mph, they slingshot to 30-40 mph and then slowly go down to about 22 mph. I have access to the .dat and .unity3d files
![Unturned1](https://user-images.githubusercontent.com/62486993/77237882-47c7d380-6bcc-11ea-9ac9-883caa537de8.png)

**Comment by SDGNelson** [comment]
Usually this depends on physics properties in Unity like the wheel collider mass. Are you going to edit this mod? If so I recommend checking out the vehicle physics profile feature to fixup / standardize those properties.

**Comment by BoneCrusher03** [comment]
> Usually this depends on physics properties in Unity like the wheel collider mass. Are you going to edit this mod? If so I recommend checking out the vehicle physics profile feature to fixup / standardize those properties.

Where can I find those?

**Comment by SDGNelson** [comment]
Sorry, here's the info about them: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/VehiclePhysicsProfile.md

**Comment by BoneCrusher03** [comment]
> Sorry, here's the info about them: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/VehiclePhysicsProfile.md

Thanks. Ill look through that and try to understand it and fix it. I just havent found a way to open .unity3d files

**Comment by danaby2** [comment]
Me and my family were also affected by this issue many times. I have found that 90% of the time you can just add Wheel_Collider_Mass_Override 5 to the .dat file and all your problems will be forever solved.
