### ISSUE TITLE
Player_Damage_Virus not working

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1536]
Might be I just tested it in a wrong way but tried:
Player_Damage_Virus 50
Player_Damage_Virus true
Player_Damage_Virus always
+ some other variations with/without default player damage line. None worked. Didn't test food/water damages, but all others (bone breaking, bleeding, hallucination) worked fine

**Comment by SDGNelson** [comment]
I think the catch here is that it should be: `Player_Damage_Virus -50`
That is confusing considering it is called damage. Those values are all added to the player's stats, so for example `Player_Damage_Food +50` feeds them.

**Comment by baranmod** [comment]
ohh, thanks for clarifying :)
