### ISSUE TITLE
[HELP] Change Salvage Time

### ISSUE THREAD

**Issue by Maxim-Yarovoi** [SmartlyDressedGames/Unturned-3.x-Community#1538]
Hello, I wrote a plugin that uses the "sendSalvageTimeOverride" method, but I encountered a problem that everything works on my local server, but when I reset the client it doesn’t work for him, he tried on a hosting that uses the Linux operating system and he also tried on my local server with the Windows 10 operating system and nothing works for him, while I run the plug-in on my local server with the Windows 7 operating system everything works for me. And what’s most interesting, the zakashchik doesn’t give any errors.

What could be the problem?

P.S.I apologize for my bad English, I use a translator)

**Comment by SDGNelson** [comment]
I suggest logging related events to make sure it is doing what you expect. Several plugins already use this feature so I am relatively confident that it works.
