### ISSUE TITLE
Inactive Player Mass Disconnect

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#154]
In the current version of the game, when a player gets kicked for inactivity in some circumstances it will DC the entire server. Have had this verified by me and two other people.

**Comment by Torubloo** [comment]
Ummm what? players can't get kicked for inactivity.

**Comment by Torubloo** [comment]
Unless you are using a afk plugin or something, and in that case the plugin is badly made

**Comment by N1GHTPATROL** [comment]
I was told by two people that it crashed them, and it happened to me too. I didn't add any plugins, and they didn't either.

**Comment by SDGNelson** [comment]
Found the problem, will fix!
