### ISSUE TITLE
Master Bundle Tool can bundle .content asset labels

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1545]
Please prevent the Master Bundle Tool from bundling anything but a .masterbundle asset label, there have been to many cases where I accidentally bundle .content instead of an .masterbundle

**Comment by SDGNelson** [comment]
The .masterbundle file type is arbitrary - they could be bundled as .content and then set the file name in the MasterBundle.dat file. This is why the tool lets you mark which asset bundles are candidates for export.
