### ISSUE TITLE
Unturned doesn't show anything on startup and closes itself.

### ISSUE THREAD

**Issue by TheBoxxd** [SmartlyDressedGames/Unturned-3.x-Community#1546]
I played Unturned a lot. But now,I just started up Unturned and it hides my cursor,shows up in the task bar and then just randomly closes.
I tried : Deleting and installing unturned,deleting all workshop mods and unsubscribing,trying to launch the game raw from the files and rebooting my pc.

**Comment by SDGNelson** [comment]
Sorry about the crash! After this happens could you attach the `Client.log` file from the `Unturned/Logs` directory please?

**Comment by TheBoxxd** [comment]
Okay. Here you go: https://drive.google.com/open?id=1-DZbcS-qzxmKnmvWfFhDMKUfMLAXhrbH

**Comment by TheBoxxd** [comment]
Hello? Anyone?

**Comment by SDGNelson** [comment]
Hi! Sorry I missed your comment. Will follow up in your new thread (#1558).
