### ISSUE TITLE
Support for multiple bladeIDs

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1548]
Resource harvesting tool that works on trees and rocks

**Comment by Ongjming** [comment]
Note to self BladeID format: Where X, A and B = numeric whole number
Single BladeID in .dat files -
BladeID A
Multiple BladeID in .dat files -
BladeIDs X
BladeID_0 A
BladeID_(X-1) B

Used in weapons (melee/guns) and objects (Resource).
Normal vanilla trees doesn't have BladeID (Anything can damage it except for fist).
