### ISSUE TITLE
Blacklist asset support for crafting recipes

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1549]

**Comment by NoThreat** [comment]
Very very useful, it will be great to add in next update or next next update

**Comment by Ongjming** [comment]
Self note: This was introduced in [3.20.5.0 Update] (https://store.steampowered.com/news/app/304930/view/3460398821839264087)
It was used in the level.asset of the map, usually located somewhere in the "Bundles" folder. Asset v2.
In level.asset to add "Crafting_Blacklists" +[{"GUID" "guidnumbers"}]
In craftingblacklist.asset to add "Type" "SDG.Unturned.CraftingBlacklistAsset, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" + Whatever was mentioned in https://github.com/SmartlyDressedGames/U3-Docs/blob/master/CraftingBlacklistAsset.md
