### ISSUE TITLE
UI Script Is Not Running

### ISSUE THREAD

**Issue by CapScroLL** [SmartlyDressedGames/Unturned-3.x-Community#1552]
I'm creating a script for the UI and it works when I test it on Unity, but it doesn't work inside the game. I created a text showing the real time and updated it with the Update() function, but the text does not change in the game.

**Comment by erik7302** [comment]
The Bundle tool or the master one doesnt export scripts so u hav to do that with a plugin(only on a server) or a Module(disabling BattleEye).

**Comment by CapScroLL** [comment]
> The Bundle tool or the master one doesnt export scripts so u hav to do that with a plugin(only on a server) or a Module(disabling BattleEye).

Thanks!
