### ISSUE TITLE
sendUIEffects Send More Than 4 Arguments

### ISSUE THREAD

**Issue by CapScroLL** [SmartlyDressedGames/Unturned-3.x-Community#1555]
I want to send more than 4 arguments for the UI Effect, but I have no idea what to do. sendUIEffect has up to 4 arguments, when I searched for previous issues, I saw the sendUIEffectText method, but I think it was removed. Can you show me sample code about how to do it?

**Comment by Raxul257** [comment]
I think that ``sendUIEffectMassTextReplace(short key, CSteamID steamID, bool reliable, string[] childNames, string[] texts)`` (as described in  #1481)  and ``sendUIEffect(ushort id, short key, CSteamID steamID, bool reliable, string[] childNames, string[] texts)`` would be a good solution.

**Comment by SDGNelson** [comment]
You are right that `sendUIEffectText` should do the trick for now. Basically you spawn a UI with a "key" and then can update the text at any point later by referring back to your key.

e.g. spawning a menu with key 30000 and then later you want to change some text `sendUIEffectText(30000, player, true, "my_label", "new text")`
