### ISSUE TITLE
[France] cannot turn of vehicle spawn

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#1556]
i cannot turn of vehicle spawn on france map, where as the same setting is working with russia, washington, yukon, germany,pei
here is my vehicle settings:
`      "Max_Instances_Tiny": 0,
      "Max_Instances_Small": 0,
      "Max_Instances_Medium": 0,
      "Max_Instances_Large": 0,
      "Max_Instances_Insane": 0
`

**Comment by SDGNelson** [comment]
Earlier this year (I think in part due to this point) it was changed so the map can only override the config if the server is using the default, so it should be possible to disable vehicles on France nowadays.
