### ISSUE TITLE
[Modding] My vehicle has no engine sound

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1557]
So I imported ExampleAssets.unitypackage, copied the Firetruck folder, and made my vehicle. Everything is ok, except for one thing: the engine sound isnt playing when Im driving the vehicle. How do I fix it? Also it would be good to fix the vehicles in original ExampleAssets.unitypackage so that it wont happend again.

**Comment by 0AlexSashka0** [comment]
Try it like this.

![image](https://user-images.githubusercontent.com/51301017/78767885-747d3880-798b-11ea-8ad2-36f2cfda5d49.png)

**Comment by DerpyHoowes** [comment]
Спасибо, и правда помогло
