### ISSUE TITLE
[Question] Can i make a custom launcher with my roleplay project unturn 

### ISSUE THREAD

**Issue by TonySerum** [SmartlyDressedGames/Unturned-3.x-Community#1559]
Hello, I want to create a custom launcher allowing to modify the behavior of vanilla items (IE: with files dat> blueprint product and others), add functionality of industrial machinery items, deactivate certain game options and others that I have can be forgotten to promote the gameplay and give a taste for the community

I would never use the game / launcher to make money and steal the game code

And I wanted to thank you for a while, I am very fan of your work since 2016 I play this last Waiting for patiament Unturn 4

thank you for all

PS : https://youtu.be/FRQ-5T-TMtQ

**Comment by SDGNelson** [comment]
If the goal is custom gameplay with custom code then it is probably fine. Your launcher can also make use of the "modules" feature to have code loaded automatically by the game similar to RocketMod.

Thanks for your support. I hope 4.0 is worth the wait!

**Comment by TonySerum** [comment]
Yes thank you very much for everything, but I don't really like rocketmod and making modules through it, I think I can create from A to Z what I need ... I also need to remove some access to menus, if you allow me ... I would like to know if I can also modify the dll for cella ... or tell me how I could do with modules I must do to prevent such behavior, I want also create new ui for machine thanks to the sleek button and others, I have so much idea ...

but it's already huge that you allow me to create a custom launcher with custom code

Thank you in advance for the time you have given me.
