### ISSUE TITLE
Stuck at Queue position: #1

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#1562]
Hello,

starting from last about 7-10 days, I am not able to join a lot of servers, 
I get stuck at Queue position: #1, sometimes if I press leave then try to join again , I manage to get in , but this doesn't always work, sometimes even if I keep trying, I stay stuck!!

Greetings

**Comment by joeymisfit** [comment]
Hello @nanashi88,

Try removing all of your Unturned workshops and load back in, see if that works.  Make sure you have exited out of Unturned and if you have Unturned installed on your **C** drive you'll want to go to **Program Files (x86)** -> **Steam** -> **steamapps** -> **workshop** then delete **app_workshop_304930.acf** and continue by going to **content** -> and delete the folder labeled **304930**.

Let me know if that works for you!

**Comment by nanashi88** [comment]
@joeymisfit thank you for fast reply. 
but unfortunately this didn't work :(

**Comment by nanashi88** [comment]
I am admin on servers that I am not able to join, in the logs it show that I connected, but it doesn't show that I disconnected (even after pressing on leave):
`[3/30/2020 5:24:31 AM] BattlEye Server: Player #1 # (#.#.#.#:#) connected
[3/30/2020 5:24:31 AM] BattlEye Server: Player #1 # - BE GUID: #
[3/30/2020 5:24:31 AM] Connecting: PlayerID: # Name: # Character: #
....
[3/30/2020 5:41:24 AM] BattlEye Server: Player #2 # (#.#.#.#:#) connected
[3/30/2020 5:41:24 AM] BattlEye Server: Player #2 # - BE GUID: #
[3/30/2020 5:41:24 AM] Connecting: PlayerID: # Name: # Character: #`

also I am a module developer, and I see that Player.onPlayerCreated is broadcated too.

**Comment by SDGNelson** [comment]
Thanks for the server logs. That gives us an interesting view into how far it is getting on the server-side. Hopefully we can figure out where it is going wrong.

After you get stuck and it has supposedly connected you on the server-side could you attach the client-side `Client.log` file please? In particular it will be interesting to see if "Accepted by server" is logged.

**Comment by nanashi88** [comment]
SDGNelson thanks for response,
"Accepted by server" is not logged when it get stuck at queue screen.
2 log files attached.

- in log1, I am trying to join serverA, 3 times , but always stuck at queue #1, so I press on leave button.

-in log2 file, tried to join serverB, got stuck at queue #1, after more than one minute I pressed leave button. then tried to join the same server again, and I was able to join normally, then I exited from the server in normal way, and joined again, and was able to join normally again. then exited the game.

my friends told me that they see me online in the server for about 1 minute, then auto disconnect (even when I don't press leave)
btw, I have 4k+ Unturned hours, and I got this issue only recently.

Greetings
[log1_(3 times stuck at queue 1).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4406881/log1_.3.times.stuck.at.queue.1.log)
[log2_(first connect got stuck at queue 1, then two successful join).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4406882/log2_.first.connect.got.stuck.at.queue.1.then.two.successful.join.log)

**Comment by SDGNelson** [comment]
Thank you for the detailed logs and descriptions! This is such a bizarre bug. I wish we could find some way to replicate it. 

Scratching my head thoroughly examining the relevant code I do not see why it is failing. Especially why it fails to send a message after they have already exchanged several. The server is definitely sending the accept packet, and there is no reason for the client to discard it. Only thing I can think of at the moment is to add further logging on client and server side to hopefully catch it... 😞

**Comment by rube200** [comment]
Could the problem be the "verifyNextPlayerInQueue" method malfunctioning?
I already gave you the patch with a plugin and never noticed this problem again.

```CSharp
private static void VerifyNextQueue()
        {
            var accepts = 0;
            foreach (var player in Provider.pending.ToList())
            {
                if (Provider.maxPlayers < Provider.clients.Count + accepts + 1)
                    return;


                if (player?.hasSentVerifyPacket ?? true)
                    continue;


                accepts++;
                player.sendVerifyPacket();
            }
        }
```

**Comment by SDGNelson** [comment]
@rube200 It looks like your change is accepting several players in the queue at once depending on the available space. In vanilla the server accepts one player from the front of the queue at a time. This makes me wonder if there is some edge case where `verifyNextPlayerInQueue` is not called. I will investigate!

**Comment by rube200** [comment]
```CSharp
private static void receiveServer(CSteamID steamID, byte[] packet, int offset, int size, int channel)
{
	...
	if (esteamPacket == ESteamPacket.CONNECT)
	{
		if (Provider.isWhitelisted || !SteamWhitelist.checkWhitelisted(steamID))
		{
			Provider.pending.Add(new SteamPending(...));
			if (Provider.pending.Count == 1)
			{
				Provider.verifyNextPlayerInQueue();
			}
			return;
		}
	}
	...
}
```
This forces the server to only accept if the pendant list is 1, in the case of @nanashi88 gets stuck but the server accepts the other players, so I think it was something after that.

**Comment by nanashi88** [comment]
just to make the issue a little bit more complicated:
some players claimed that the issue is from the ISP, and changing the ISP could solve the problem.
so I tried free VPN, and it worked!! when I am inside the game if I turn on the VPN and join a server I could join normaly, then if I turn off VPN, and try to join I get the issue back and get stuck!!
but I don't have issues with other games, and my ISP is considered the best here, so it is not an easy option to change ISP.

**Comment by nanashi88** [comment]
more new info: one of the servers I have issue joining , are hosting another game, called Soldat, on same machine that Unturned is hosted on. I am able to join and play Soldat without issues.

**Comment by SDGNelson** [comment]
@rube200 To clarify about the verifyNextInQueue: I do not think either of those is the problem. verifyNextInQueue is working correctly for nanashi88 because the client is asked for authentication details. Still looking into this. For your reference, here is the source code related to what you posted:

	// If server is not whitelist-only then whitelisted players are treated as VIPs.
	bool prioritizeInQueue = !isWhitelisted & hasPermit;

	if(prioritizeInQueue)
	{
		if(pending.Count == 0)
		{
			pending.Add(newPendingPlayer);
			verifyNextPlayerInQueue();
		}
		else
		{
			// Player at front of queue is already in the process of being verified.
			pending.Insert(1, newPendingPlayer);
		}
	}
	else
	{
		pending.Add(newPendingPlayer);

		// If there are other players in the queue then they are already being verified.
		bool nobodyElseInQueue = pending.Count == 1;
		if(nobodyElseInQueue)
		{
			verifyNextPlayerInQueue();
		}
	}

**Comment by SDGNelson** [comment]
For the next update I have introduced significantly more logging to both the client and server sides related to joining and leaving. Hopefully it will give us an idea of what is actually received by the client. One change that may be particularly useful server-side is logging why the front of queue player timed out (vac, economy, group) - though I do not think that is the case here.

Will remove the next update label for to-do list tracking purposes, but feel free to comment and I will follow up after the update. Fingers crossed.

**Comment by nanashi88** [comment]
thank you for adding more logs.
in the following file , first it shows a failed try to join server(get stuck at queue), then it show a successful join for another server:
https://discordapp.com/channels/586771596488867841/645970747344420865/711360537061228594
hope this gonna help

**Comment by SDGNelson** [comment]
Thank you for sharing the log file!

Is the failed to join server one you have control over? The server-side logs may have further details, in particular if the `-ConstNetEvents` command-line option is enabled.

On another note, it is odd that the successful connection does not log "Connection pending verification" whereas the unsuccessful one does. This is not a big deal but odd...

**Comment by nanashi88** [comment]
I don't have control, I am admin and developer on those servers, I will ask the owner to open test server with -ConstNetEvents
thank you for fast response

**Comment by SDGNelson** [comment]
Thank you for trying with that option. Fingers crossed that the server log helps us finally track this down!

**Comment by nanashi88** [comment]
I have tried to join a server with -ConstNetEvents command-line option is enabled.
here is logs:
[UT_logs.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4640278/UT_logs.txt)

**Comment by SDGNelson** [comment]
Thanks for sharing that log. Is that sever running the latest version? The server log is missing several entries, for example it should say "Added player 77561198028565546".

It looks like the connection got further that time, as your client actually logged in and spawned the player character, but the server was ignoring the inputs. The missing server-side logs are a mystery however... will investigate.

**Comment by nanashi88** [comment]
"Added player 77561198028565546" was printed at client side only.
also I tried a local server, and it didn't print  "Added player 77561198028565546"  on server side!
(btw, I don't have issues joining local server)
here is new logs after updating the test server:
first I try to join 3 times, but it all fail, then another players success to join after me
[UT_logs2.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4640828/UT_logs2.txt)

**Comment by SDGNelson** [comment]
Which server log file is it? I just double-checked and my local server does log "added player". The server log file should be at: `U3DS/Logs/Server_(server name).log`

What we do know is that locally it is creating the player for yourself, but not creating any of the other players on the server. It will be interesting to see in the full log whether it is running into an exception when sending that information or what.

**Comment by nanashi88** [comment]
ops, what have I posted is copy -paste of server console messages

**Comment by SDGNelson** [comment]
Ah, thanks! Since it may be a big or private file feel free to email instead: nelson@smartlydressedgames.com

**Comment by nanashi88** [comment]
[Server_test.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4640946/Server_test.log)
I just finished faking ips and ids.
next time I will mail it, this good and easy option ^^

**Comment by SDGNelson** [comment]
Thanks for the server log file! Okay what we can see here is:

- First attempt was kicked because BattlEye could not establish a connection. Did you get any BattlEye message on the client side for this one?

- The second and third attempts closed because the Steam session was ended ~30 seconds afterwards. My guess is that this was when you clicked the Cancel button on the queue screen.

Do you know what the `MMod_plyrCreated_PIN1010` is? It is probably unrelated, but is a potential lead.

On the client side we know that the only player you were told about is yourself, so only the first `connected` message went through. Thinking about what this means now. 🤔

**Comment by nanashi88** [comment]
after I submited these logs, I will try summary my issue:
- I always has played Unturned on our servers without issues, this issue happened suddenly. 
- I don't have this issue with all Unturned servers, some servers I manage to join (also some of it I manage to join after multiple tries, not from first try)
- I think this issue is not related to modules/plug-ins, cuz we have tried with test server, without any modules
- if I use VPN, the issue disappear ( so the issue could be ISP related)
- I was able to join other multi-player game (called Soldat), which is hosted on same machine that our Unturned servers hosted on. so most likely it is Unturned related issue.
- I am not the only one having this issue, very few players, reported this issue (from different contries)
- this issue is not so popular, because we are hosting multiple servers, and most of the time servers are very busy ( a lot players online without issues)
- when I connect and get stuck (at queque #1), other players inside server see that I am online, and they are able to see my character ( btw I don't hear any in-game sounds, even if they kill me)
- the server auto disconnect my server-side character after less than minute, and players can't see my name inside server anymore, but for me (client side) I stay stuck at queque #1 until I press leave.
- if I press leave from begining (without waiting), my server-side charater will disconnect too (if I am remembering well)


> First attempt was kicked because BattlEye could not establish a connection. Did you get any BattlEye message on the client side for this one?

I don't remember if I got message or not. but in general, I don't get any message.

> The second and third attempts closed because the Steam session was ended ~30 seconds afterwards. My guess is that this was when you clicked the Cancel button on the queue screen.

true, but in general, when this amount of time already passed, I know that I am stuck, because noramlly it takes much less than that to join server after seeing queue #1 screen.

> Do you know what the MMod_plyrCreated_PIN1010 is? It is probably unrelated, but is a potential lead.

it is from our module, binded to Player.onPlayerCreated, but I still having the issue even when server running without modules. also our servers so busy, so I think no issues from our module.

> 
On the client side we know that the only player you were told about is yourself, so only the first connected message went through. Thinking about what this means now.

sorry, forgot to say there was no players in the test server when I tried to join, other players joined later.

**Comment by SDGNelson** [comment]
This is just so bizarre. I've re-read this and the code several times, but there seem to be no leads to go off of. No errors in the logs, working with VPN, working for other players... Bah.

You mention that you still have this issue when the server is running without modules. To double-check for my sanity, can you give that another try? i.e. temporarily running a test instance on that server without RocketMod and without your custom module and trying to connect.

**Comment by PandahutMiku** [comment]
This might not help, but I figure it would be worth mentioning. Back in ~2017-2019? there used to be an issue just like this where you would get stuck on Queue Position 1 however be loaded into other players. You could even hear the game audio, punch, and hear yourself punching. This used to just be able to be fixed by verifying files via Steam. 

Back then in the top left when that happened you would get stuck on loading "Lighting" if I remember correctly.

**Comment by SDGNelson** [comment]
Unfortunately @PandahutMiku in this case it is stuck earlier in the loading process. (Lighting and other requests are handled later after being fully accepted into the server.)

**Comment by nanashi88** [comment]
sorry for late response, previous days were busy days.
disabling all modules haven't solved the issue.
also tried to disable VAC and Battleye, but didn't help
I did 4 tests on this, I will send all logs (my logs , friend logs, servers logs) to nelson@smartlydressedgames.com

**Comment by SDGNelson** [comment]
(following up through email)

**Comment by nanashi88** [comment]
apparently the recent game update (rewrite of NetTransport) has solved the issue.
I am so happy, finally I don't need to pay for 2 ISPs :)
@SDGNelson thank you 👍

**Comment by SDGNelson** [comment]
Phew! Glad to hear that the new Steam Networking has resolved the issue.
