### ISSUE TITLE
Swapping secondary shoots primary

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1565]
Probably the drag-drop event is not handling the click so it is handled by the gun input instead.

https://www.youtube.com/watch?v=60ljC-wS8M8

**Comment by GoryBark** [comment]
Very annoying glitch - especially in survival or when you are speaking to someone and accidentially tap em on the noggin :D

**Comment by SDGNelson** [comment]
Should be fixed in the next update!
