### ISSUE TITLE
i have seen alot of hackers on my server they used these hacks

### ISSUE THREAD

**Issue by Erkan53** [SmartlyDressedGames/Unturned-3.x-Community#1569]
there are alot of hackers on my server
on some people their hacks can be seen through using spy i can see they are using ESP hack
and some are using vehicles to fly anywhere and also they can place any item anywhere i saw a metal base under seattle base was very big
these hacks need to be fixed i cant even see these hacks on spy which alot of players gets called hacker and when i spy them i see nothing
once i spied someone they said im being spied in chat i banned that player immediately
these hacks needs to be fixed

**Comment by Johnanater** [comment]
There are tons of them :(

**Comment by SDGNelson** [comment]
With more players online during the quarantine there have unfortunately been more cheaters as well. BattlEye has been banning huge numbers of players every day.

If anyone would like to report new cheat software please send reports to nelson@smartlydressedgames.com and I will ensure it gets to BattlEye.

**Comment by GazziFX** [comment]
Make your own server AC for check abuse, Ive made one, that can fix a lot of types of hacks

**Comment by nanashi88** [comment]
@GazziFX could explain more. what is AC?

**Comment by GazziFX** [comment]
Anti-Cheat

**Comment by GazziFX** [comment]
Block actions and log in file
https://youtu.be/H2L4JWhGhIU
![image](https://user-images.githubusercontent.com/43498426/78348384-9b61f600-75aa-11ea-950b-6cf8dd3edc93.png)

**Comment by Erkan53** [comment]
@GazziFX 
is this a plugin ? where do i find this?

**Comment by Erkan53** [comment]
also why are you sharing hacks on your channel
stop it

**Comment by GazziFX** [comment]
Its private plugin

**Comment by GazziFX** [comment]
Firstly I created and modified cheats, and now I create plugins

**Comment by nanashi88** [comment]
So you are Gazzi himself!!
your cheats has done a lot of damage to servers and players, don't you think it is time to repent.
no one know when Unturned gonna vanish, you have the chance now, take the chance before it is no more. please help Unturned community by publishing your AC plug-in for free. 
for me, the main issue is ESP and aimbots (when using random parts/hit chance), @GazziFX any tips is appreciated.
Thank you

**Comment by GazziFX** [comment]
> for me, the main issue is ESP and aimbots
My plugin cant fix all features. ESP Blocker only limit draw distance, players are vanished but relative for each player

**Comment by nanashi88** [comment]
@GazziFX thank you for replying

**Comment by TH3AL3X** [comment]
I am creating a plugin for rocketmod to avoid all kinds of cheats, contact with me on discord TERROR#2080

**Comment by nanashi88** [comment]
if Gazzi saying "cant fix all features" , while he is known cheat developer.
how come your plugin avoiding all kinds of cheats?!!
@TH3AL3X is your plug-in able to detect aimbot on random parts or with "hit chance" ?

**Comment by GazziFX** [comment]
@TH3AL3X try to prevent norecoil or at least detect it

**Comment by SDGNelson** [comment]
I would recommend against anti-cheat plugins. Anything that should be safely preventable from server-side is built-in to the base game. I have been checking in with BattlEye, and again feel free to report any cheats about through the grapevine

**Comment by TH3AL3X** [comment]
Can detect NoClip cheats, but I am trying to implement to detect the silent aim

**Comment by GazziFX** [comment]
> I am trying to implement to detect the silent aim

Me too, silent for static objects fully fixed
