### ISSUE TITLE
Barricademanager.dropBarricade issue with locked doors storage units etc

### ISSUE THREAD

**Issue by Edsparr** [SmartlyDressedGames/Unturned-3.x-Community#157]
If you summon a vault door for example via barricademanager just summoning it the player ingame thinks it's locked for him EVEN IF he can salvage it. I can't find a method updating this any help? or can you (Nelson Sexton) just fix it in the dropbarricade method itself?

**Comment by aviadmini** [comment]
It's your problem, not Nelson's

**Comment by Edsparr** [comment]
You truely love me Sam dont you? Its My problem i asked for a fix, its his game, his glitch. If he has and externa method Why not make it in the dropBaricadrr method.

**Comment by SDGNelson** [comment]
Double-check that the correct state array is passed in: currently the first 8 bytes should be the owner's steamID and the next 8 bytes their group steamID.

**Comment by aviadmini** [comment]
Worked fine for me  ¯\_(ツ)_/¯

**Comment by nn653** [comment]
`byte[] state = new byte[16];
Array.ConstrainedCopy(BitConverter.GetBytes(owner), 0, state, 0, 8);
Array.ConstrainedCopy(BitConverter.GetBytes(group), 0, state, 8, 8);

barricade.state = state;`
