### ISSUE TITLE
Method SDG.Unturned.Provider.listenServer(System.Int32 channel); takes seconds to run

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#1571]
Sometime this method takes several seconds to run. Which leads players to disconnect by timeout. Last time it took 9 seconds for 10 runs per frame. It happens randomly on different servers. Have any ideas?

**Comment by SDGNelson** [comment]
Is your plugin directly calling that function? 

Or you tracked the timeout to it? In this case I wonder if a plugin is doing a slow action in response to an event indirectly called by that, e.g. querying a database.

**Comment by D-AIRY** [comment]
I'm measuring time caused by some main functions, to track lags. Not sure about plugins, how to check that

**Comment by D-AIRY** [comment]
Not found anything related to `onServerReadingPacket`, `onServerWritingPacket` or patching in installed plugins

**Comment by PandahutMiku** [comment]
https://github.com/ImperialPlugins/UnturnedProfiler might help tracking down the plugin causing it

**Comment by D-AIRY** [comment]
Already using it. Didn't help to find the exact reason

**Comment by D-AIRY** [comment]
I've set up profiling for steam calls, will see if that make it clear

**Comment by SDGNelson** [comment]
It can really be anything because `listenServer` is responsible for calling RPCs and indirectly triggering almost all game events. For example if a plugin is doing a database read from the onPlayerConnected event it would be stalling `listenServer`.

**Comment by SDGNelson** [comment]
In a similar vein some built-in logging for when more than 1.5s pass between server ticks was added earlier this year. RPC performance is unlikely to change on a broad scale, but improving the net read/write portion of performance is one of my goals in 2021.
