### ISSUE TITLE
Bug with nodes location 

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#1574]
When we put a node location in a building it tp us on the roof.

**Comment by SDGNelson** [comment]
This was changed a while ago because some maps raised the terrain over a location node preventing the player from teleporting there. What sort of location do you have in mind? Depending if this is for a quest system you can use the teleport markers to bring them into the building.

**Comment by MonsterGeeks** [comment]
It's the nodes location in editor. Look the picture please:
https://imgur.com/gallery/76tUpcz

**Comment by Spebby** [comment]
I ran into this problem on Easter Island quite a bit. People try to teleport to Terevaka's node and end up under the volcano. I get a ton of bug reports relating to this bug, and it's sorta annoying I can't really do anything about it besides move to node off of the Volcano.

**Comment by SDGNelson** [comment]
My guess for Spebby's case is that they are in singleplayer so the collision for the volcano is disabled at the time of the teleport request. For now the safe/intended option is to place them on the terrain if players should be able to teleport to them.

**Comment by SDGNelson** [comment]
There was a change at some point after this to only raycast from slightly above the location node so that teleporting to indoor locations worked better, but the recommendation would still be to place them on the terrain because in singleplayer the distant objects are disabled.
