### ISSUE TITLE
Allow bed on vehicle options

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1575]
- Default to allow in singleplayer
- Optional for servers

**Comment by rube200** [comment]
Add that option for sentry's too

**Comment by GoryBark** [comment]
YES

**Comment by CatzMR** [comment]
If allowed to make the game more interesting
For example: RV, mobile fortress

**Comment by SDGNelson** [comment]
Added in the next update as: `Bypass_Buildable_Mobility`
