### ISSUE TITLE
Bug with the APC vehicle

### ISSUE THREAD

**Issue by Denwer-hub** [SmartlyDressedGames/Unturned-3.x-Community#1576]
Hello there, I came here to report 2 really annoying bugs which allows you to easily kill someone who in a APC. Even tho APC is armored vehicle which can't be destroyed with normal bullets, it is still possible to bug "into" the vehicle from outside and kill the driver / other people inside the vehicle.

Number 1 

It is not that known and easy as number 2 to do it, but it is still possible... 

 https://youtu.be/ttl-R8c5pfk

Number 2 

That one is way to easy to use and it should be repaired as fast as possible.

https://youtu.be/sJ06GxQu3kA

Hope you fix these bugs as fast as possible. Have a nice day!

**Comment by SDGNelson** [comment]
Thanks for the reports. I believe these are both related to the changes to overlapped movement in this issue: #1566 In particular with number 2 the floating movement would move it downward into the player, allowing them to move inside it.

**Comment by SDGNelson** [comment]
Both of these are probably still somewhat possible, but the overlapped movement is a "between a rock and a hard place" problem. Eventually I intend to replace the CharacterController with something custom.
