### ISSUE TITLE
unturned.log (in rocket folder) eating 100% of disk

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1577]
Can't tell if its just random issue, but after server restart, it didn't launch for couple minutes (no response on console). Checked task manager, unturned.log was using 100% of disk

**Comment by SDGNelson** [comment]
What was being spammed into the log?

**Comment by baranmod** [comment]
It was empty at the moment I was trying to launch server, when I succeeded - there were some typical stuff I am getting for ages now. But once I launched, there were no further problems with that. So I guess it might be just some random glitch with windows or something.
