### ISSUE TITLE
Get Door Health

### ISSUE THREAD

**Issue by Maxim-Yarovoi** [SmartlyDressedGames/Unturned-3.x-Community#1578]
How can I find out the amount of HP at the door, I tried to use the code "barricadeRegion.barricades [(int) index] .barricade.health" but nothing worked, it shows on the barricades and there is no door, but why is the door also a barricade.

**Comment by SDGNelson** [comment]
That looks correct to me, and is how functions like BarricadeManager.sendHealthChanged get it. I think the most likely issue is the region or index being wrong there.

**Comment by Maxim-Yarovoi** [comment]
> That looks correct to me, and is how functions like BarricadeManager.sendHealthChanged get it. I think the most likely issue is the region or index being wrong there.

I try to use this code, but now I do not have the output of HP of any construction.
![2323123123123](https://user-images.githubusercontent.com/62555722/78507403-732fee00-7788-11ea-9d20-021fb03ab8e2.png)

**Comment by surv0013** [comment]
Old bug, use it:
```CSharp
if (Physics.Raycast(UPlayer.Player.look.aim.position, UPlayer.Player.look.aim.forward, out RaycastHit hit, 32f, RayMasks.BARRICADE))
{
     if (hit.GetComponent<InteractableDoorHinge>() != null)
     {
          hit= hit.transform.parent.parent;
     }

     if (BarricadeManager.tryGetInfo(hit, out byte x, out byte y, out ushort plant, out ushort index, out BarricadeRegion region))
     {
          BarricadeData data = region.barricades[index].baricade.health;
     }
}
```

**Comment by SDGNelson** [comment]
Ah, when dealing with raycast results you should use call `DamageTool.getBarricadeRootTransform` with the hit transform. The returned transform will be the right one for `tryGetInfo`

**Comment by Maxim-Yarovoi** [comment]
> Old bug, use it:
> 
> ```cs
> if (Physics.Raycast(UPlayer.Player.look.aim.position, UPlayer.Player.look.aim.forward, out RaycastHit hit, 32f, RayMasks.BARRICADE))
> {
>      if (hit.GetComponent<InteractableDoorHinge>() != null)
>      {
>           hit = hit.transform.parent.parent;
>      }
> 
>      if (BarricadeManager.tryGetInfo(hit, out byte x, out byte y, out ushort plant, out ushort index, out BarricadeRegion region))
>      {
>           BarricadeData data = region.barricades[index].baricade.health;
>      }
> }
> ```


Thanks, there will be time I will check.
