### ISSUE TITLE
HUD system

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#158]
Currently, making any type of interactive hood (e.g. buttons you can press) is possible but painful. It's limited and iit doesn't work well enough to use in production.

So here's a few options I see for HUD implementations

## Runtime generation
Do similar thing to what Rust guys did (afaik) - they allow sending JSON that is parsed on client and it composes UI on the go.

Pros:
* Quite easy to implement
* Easy to use (for devs)
* Can enforce UI style to not mess up the game style
* No Workshop needed

Cons:
* Quite limited

## Workshop asset based

Pros
* 100% customizable (including UI animations etc)
* Not too difficult to use

Cons
* Requires Workshop
* Cannot enforce UI style to not mess up the game style (I bet you will see all sort of ugly UI on servers)

## Challenges
1. UI focus (give player mouse control)
When playing, focus is mostly on look direction. To get focus on UI player needs to open some UI or chat. So, this must be considered when showing custom HUD - should it get mouse focus or nope. Effects will be sorta no-focus UI in next update (#96), but HUD will still need focus
2. Triggering UI
Good idea to have buttons to trigger UI (#114)

## What if community made it ;)
I'd offer to make it a community open source module. Unturned perfectly allows this. 
The only issue is usage of client module which would require to be signed

**Comment by SDGNelson** [comment]
Server -> client UI is low priority, but I'd most likely go the runtime generation route.
