### ISSUE TITLE
glitching under the map

### ISSUE THREAD

**Issue by Erkan53** [SmartlyDressedGames/Unturned-3.x-Community#1580]
you can glitch under the map with vehicles
to do this glitch
get 2 vehicles carjack one get to the other vehicle drive it when the carjacked vehicle hits the vehicle youre driving sometimes it pushes you down under the map

**Comment by SDGNelson** [comment]
Thanks for the report. I believe this is related to the changes to overlapped movement in this issue: #1566

**Comment by SDGNelson** [comment]
This should be fixed in the 2020-05-15 update. There are fixes to movement, as well as changes to teleport players underneath the map back up to the surface.

**Comment by Erkan53** [comment]
also i found that you can do the same with driving 2 apc's or cars works better with apc driving 2 apcs together sometimes one apc gets on top of other and pushes it underground
