### ISSUE TITLE
Allowing a barricade to be both a claim flag and a generator

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#1581]
This is strange request, but it would be nice if a barricade could do both, and possibly overall extend the barricade system to allow more objects to be multi-role. I understand if this isn't worth the time for you.

**Comment by SDGNelson** [comment]
It would make sense to be able to do that, but those behaviors are a bit of a mess to mix together right now. Maybe if the barricade/structure features get a nice refactor some day!
