### ISSUE TITLE
steam://connect/ip:port is not working

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#1582]
When using steam://connect/ip:port -- steam couldn't find the server.
When using steam://connect/ip:port+1 -- unturned launches, but it cannot find the server

**Comment by SDGNelson** [comment]
This is reported from time to time, but "it works for me" and I am fairly confident in that. The port number is the game traffic port, whereas port+1 is the Steam query port which is why Steam can find it. When the game gets the port+1 launch argument it tries to connect to port and should join properly. Personally testing with a steam connect URL like that it connects fine for me.

**Comment by D-AIRY** [comment]
It works for one server, but won't with others. Could you check that one steam://connect/95.163.78.10:27017 ?

**Comment by D-AIRY** [comment]
I just found that string: `port -= port % 3;`
So it will work only if server port number is multiple of 3

**Comment by SDGNelson** [comment]
Where do you see `port -= port % 3` in the code?
Bear in mind that the each server uses 3 ports at a time, so you should be using 27015, 27018, 27021, etc.

**Comment by D-AIRY** [comment]
CommandLine::tryGetConnect(string line, out uint ip, out ushort port, out string pass)

It's not always possible to use such port numbers. Could you just use port -= 1 when launching from stream?

**Comment by SDGNelson** [comment]
Ah, the reason for `port % 3` there is so that the command-line arguments 27015, 27016 and 27017 would all point at the correct server regardless. Why is it not possible to use the 27015+ port numbers?

**Comment by D-AIRY** [comment]
Port numbers assigned sequentially based on which is free. If there are another game servers (which required one or two ports), that sequence could be broken

**Comment by SDGNelson** [comment]
Ah I see. Thanks for raising that point. I will change it to only `-1`.

**Comment by SDGNelson** [comment]
This has been changed for the next update.

**Comment by D-AIRY** [comment]
Hello. Did you forget to subtract 1?

**Comment by SDGNelson** [comment]
This is part of the reason it originally was %3, the port passed in seems to be different between different systems. I removed the subtract 1 after testing with several of the different events. Is the steam://connect passing +1?

**Comment by D-AIRY** [comment]
steam://connect just passes given port to +connect arg. So it's Steam query port

**Comment by D-AIRY** [comment]
But when launching from steam server browser, it starts game with the right port. So it will be better to try both, port and port-1 to handle both cases

**Comment by SDGNelson** [comment]
Forgot to follow up on this after the .3 patch: it should have been corrected in that patch, and after trying to track down all the different cases that pass +connect args (URL, rich presence, server browser, external join) I decided to prioritize the query port case so steam://connect should always work.

**Comment by Johnanater** [comment]
Can confirm steam://connect/ip:port works with the query port (server port + 1)
