### ISSUE TITLE
Vehicle invisible in multiplayer and gives object reference not set to instance of an object error in console

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#1584]
https://media.discordapp.net/attachments/527924306924142592/696589354960683008/unknown.png
Very weird, also the game spawns a ghost vehicle of the last vehicle spawned in when you try to spawn  the wanted vehicle in

**Comment by tankirules** [comment]
![image](https://user-images.githubusercontent.com/35437320/78551881-cddd4e80-7849-11ea-9561-42d0c20f6b56.png)
could this be related?

**Comment by SDGNelson** [comment]
My guess is that the second error image you posted is probably related to an auto convex mesh collider.

As for the first error: does the vehicle have turrets? Does the server have the right vehicle asset? In general that function already guards against most error cases so I'm surprised there isn't more context. Does it say "Exception while spawning vehicle: ###"?

**Comment by tankirules** [comment]
> My guess is that the second error image you posted is probably related to an auto convex mesh collider.
> 
> As for the first error: does the vehicle have turrets? Does the server have the right vehicle asset? In general that function already guards against most error cases so I'm surprised there isn't more context. Does it say "Exception while spawning vehicle: ###"?

there is no exception, it has turrets, and the server is synced to a github repo containing the mod files so it has the right assets

**Comment by tankirules** [comment]
Since it works in singleplayer do you think it is a problem with clip.prefab?

**Comment by tankirules** [comment]
Turns out i was missing a seat in clip.prefab

**Comment by SDGNelson** [comment]
Thanks for the info! I will add a proper error message for this and prevent it from throwing an exception.

**Comment by SDGNelson** [comment]
In the next update it will spawn default seat transforms and log a warning.
