### ISSUE TITLE
UnityEngine issue with rocketmod in linux

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1585]
![image](https://user-images.githubusercontent.com/13141042/78566452-8510a000-781f-11ea-9e46-e82393510715.png)

Some commands are not working in the console, in **windows** is working fine for some reasons

**Comment by SDGNelson** [comment]
Can you update to the officially-maintained version of RocketMod from the Extras directory please? It should fix that, among other bugs.

**Comment by TH3AL3X** [comment]
Now i can't type in the console

**Comment by TH3AL3X** [comment]
Fixed it with -ThreadedConsole
