### ISSUE TITLE
Military Hour, day/night in game.

### ISSUE THREAD

**Issue by mandrien** [SmartlyDressedGames/Unturned-3.x-Community#1587]
Hello world,

how to find the military time of the game. Because it is to make PNJ which spawn only at night.

Thank you , Adrien.

**Comment by SDGNelson** [comment]
Can you elaborate on what you are trying to do please?

**Comment by mandrien** [comment]
I try to make a npc which spawn either day or night but it does not work. I then have to find the time value of my map and adapt it to the condition.

**Comment by SDGNelson** [comment]
The "time of day" condition is formatted in minutes, and is only skewed by the day-night ratio. For example 43200 should be noon regardless of the map set up.

**Comment by mandrien** [comment]
okay, because I thought the time started at 0 seconds. (/ time set 0)
