### ISSUE TITLE
Incorrect Tip on Loading Screen

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#159]
![fb6598c3cc73550cdce1023d06cf6c18](https://user-images.githubusercontent.com/7349712/34546418-b36450b0-f0c1-11e7-9c26-850727667ebc.png)

I assume there should be Mythical added.

**Comment by MoltonMontro** [comment]
Maybe, but you could argue against it due to Mythical being relatively exclusive to flavor text, some Easter Egg items, and one curated vehicle. Could give the false impression of gear that doesn't exist. 🤔

**Comment by Torubloo** [comment]
Mythical is a skin rarity, this tip is for items you can actually find.

**Comment by N1GHTPATROL** [comment]
Shadowstalker Mk.2 is mythical rarity, but not a skin... also you can put "Rarity Mythical" in a config file to make an item mythical, so it is indeed a rarity.

**Comment by Torubloo** [comment]
hmm

**Comment by aviadmini** [comment]
Freighterpack!

**Comment by SDGNelson** [comment]
Originally yes mythical was excluded because there weren't any in-game objects with that rarity, but I'll add it to the list now.
