### ISSUE TITLE
More ragdoll effects

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1590]
Ever since you added the 0 Kelvin kit, I feel like you've completely forgot the whole existence of it. It would be great if you could add more cool effects.

**Comment by SDGNelson** [comment]
I added the 0 kelvin kit when adding the trophy award ragdoll effects (gold, silver, bronze) because it seemed a shame that most players wouldn't get to see them. It would be fun to add a few more.

**Comment by SDGNelson** [comment]
Closing because I do not have plans for more ragdoll effects (yet), but it might happen in the future.
