### ISSUE TITLE
Stereos 

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1591]
Apparently you can walk through the stereo. Is that supposed to happen?

**Comment by Spebby** [comment]
Considering it's a small enough barricade, it's probably intended.

**Comment by AwesomeGOAT** [comment]
I stacked up a bunch of

**Comment by AwesomeGOAT** [comment]
I stacked up a bunch of them and made a wall to confuse other players

**Comment by SDGNelson** [comment]
It is unclear why it was setup like that, so I will change this for one of the next updates.
