### ISSUE TITLE
sendUIEffectImageURL cache

### ISSUE THREAD

**Issue by Raxul257** [SmartlyDressedGames/Unturned-3.x-Community#1592]
For me it usually takes around 1-2 seconds to load an image in UI that I often use. Cache will speed this up of course.

It would be nice to have ability to clear cache. For example: ``sendUIEffectImageURL(short key, CSteamID steamID, bool reliable, string childName, string url, bool refreshImage = false)``

Also please take a look at #1555

**Comment by SDGNelson** [comment]
Makes sense, will do. In general the client does cache remote images (e.g. server browser) but that component was originally only used for the main menu announcements so it must have been overlooked.

**Comment by SDGNelson** [comment]
In the next update images are cached by default, but plugins can disable caching per-url and force a refresh.
