### ISSUE TITLE
Standalone dedicated server not visible

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#1593]
Server hosted with standalone dedicated server AppID 1110390 not visible in Internet and unable to connect using IP
`Unturned.exe -nographics -batchmode +InternetServer/name`
But with Unturned 304930 works well.
Also tried to add in Commands.dat
`Bind 194.58.69.97`

**Comment by SDGNelson** [comment]
If it works with the game but not the standalone dedicated server it might be a firewall issue. Bind command should not be necessary in this case.
