### ISSUE TITLE
Fog Override Volumes looks weird at different times of the day

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1595]
Fog Override can look really weird/unsettling due to not changing colour. If the fog is a thick white, then it stays that, even when it's pitch black out, looking really weird and out of place.
Perhaps a system similar to the world fog could be attached to the volumes, transitioning between 4 desired states.

Fog Override's settings also make it very hard to have nice looking fog that's non-conventional colours, usually becoming super intense and bloom inducing when turned above .8 in any category, or above 1 in intensity.

**Comment by SDGNelson** [comment]
Giving it some further thought, the skybox should probably be blending toward the fog override color similar to with rain. That aspect at least should get fixed.

**Comment by SDGNelson** [comment]
While more light options are on the eventual to-do, in the meantime an `Override_Atmospheric_Fog` setting has been added to ambiance volumes in the next update. Several map makers requested the ability to opt-in to the current non-sky fog, so it is hopefully the best of both worlds.
