### ISSUE TITLE
Add OnCallReceive event to SteamChannel

### ISSUE THREAD

**Issue by CyberAndrii** [SmartlyDressedGames/Unturned-3.x-Community#1597]
I want to add some additional checks before executing RPC and cancel it if the checks fail.

Params that I need:
`CSteamID caller, SteamChannel channel, SteamChannelMethod method, object[] objects, ref bool cancel`

**Comment by SDGNelson** [comment]
Considering this would be for built-in RPCs, what sort of extra checks do you have in mind?

**Comment by CyberAndrii** [comment]
For example distance check: cheaters can forage all bushes on a map. It becomes more critical if there is an NPC that buys berries/vegetables.

**Comment by SDGNelson** [comment]
You are right: that is missing a distance / visibility test at the moment. Thank you for bringing it to my attention! I will get it fixed up for the next patch.

**Comment by SDGNelson** [comment]
Thanks again for the report. This is fixed in the next update.

**Comment by GazziFX** [comment]
Useless thing, you can just add jmp that calls your method in front of the method body that how you can make any event that you need without Harmony patching

**Comment by Trojaner** [comment]
@GazziFX read Harmonys code to see what it does. It does exactly that. Also the main point of Harmony is to provide a way where multiple plugins can patch the same method. If you patch jmp's directly, your plugin would conflict with any other plugin that patches the same method.
