### ISSUE TITLE
Full screen exclusive mode

### ISSUE THREAD

**Issue by triatomic** [SmartlyDressedGames/Unturned-3.x-Community#16]
Is this possible to implement or not ?

**Comment by SDGNelson** [comment]
Unfortunately as far as I'm aware this can't be changed at runtime in Unity - it's an option in the Player Settings. If that's not the case feel free to correct me and re-open the issue.

**Comment by triatomic** [comment]
Do you mean selecting "Fullscreen" in Display ? Then that is not the case sir. The fullscreen is just border-less window which has increased input delay due to windows DWM triple buffering. If you disable dwm the difference is night and day in regards of game response.
