### ISSUE TITLE
Unturned vehicle glitch.

### ISSUE THREAD

**Issue by GoryBark** [SmartlyDressedGames/Unturned-3.x-Community#1600]
https://www.youtube.com/watch?v=-Wj24hFXeg4 I believe it is due to some sort of collisions. Easier to replicate with vehicles with on/off parts, like a modded truck with a back that goes down when a button is pressed. Place an item in the way and the vehicle starts moving very funky.

**Comment by GoryBark** [comment]
I can provide more vids if need be

**Comment by SDGNelson** [comment]
Is that the vanilla black helicopter with the vanilla large generator? I will give it a look because that should definitely not be happening.

**Comment by GoryBark** [comment]
Only in 3rd person for heli - all POVs for the modded truck. <3

**Comment by GoryBark** [comment]
Also nelson thank you for making unturned xD

It was literally my childhood <3

**Comment by SDGNelson** [comment]
Sorry for the long period between report and me trying it. I put the industrial generator on the spec ops hummingbird and it seemed to fly okay: https://i.imgur.com/kebvTk8.png

Does it happen for you in vanilla? (wondering if it might actually be a custom / mod helicopter)

Thanks for playing Unturned. I am happy to hear that you have fond memories of it. :)

**Comment by GoryBark** [comment]
It only happens when it is placed in a certain place on the heli. You can also recreate it by putting a modded locker, in my case, on it and pulling out a weapon or punching with your fists in one of the side seats. A bit confusing, I know, but I believe that *something* is colliding, most likely the player, somehow. The items used for the first glitch were both vanilla items, albeit on a modded server.

**Comment by GoryBark** [comment]
Try placing the generator a bit further foward, also. Might help with it. The server I was on also disabled vehicle damage, so that might help. (:

**Comment by SDGNelson** [comment]
This morning I've tried a few variations of your suggestions, unfortunately no luck yet. In multiplayer, switching seats, punching and equipping items, with the generator in a few places. Even tried disabling placement while in vehicle restrictions. Are you able to recreate it consistently somehow?

**Comment by GoryBark** [comment]
Not consistently, no. Sorry. I really don't exactly know how it happened in the first place. Sorry again (:

**Comment by SDGNelson** [comment]
No worries. I will close for the meantime and keep an eye out. Feel free to comment if you run into it again.
