### ISSUE TITLE
Softlock

### ISSUE THREAD

**Issue by IChicken31** [SmartlyDressedGames/Unturned-3.x-Community#1601]
If you press esp and die at the same time (especially) while flying the jet I haven't tried getting shot) your game soft locks and you have to close it with task manager or wait for time out.

I couldn't get a picture but it soft locks on the frame when you would time out or get banned/kicked from a server.

**Comment by SDGNelson** [comment]
By opening the pause menu at the same time as death? I will try replicating it.

**Comment by IChicken31** [comment]
Ok, try it. If you press escape [Esp] while crashing with a jet in the same
second then you should be able to replicate it. Thanks for the response btw
im very happy to be talking/writing with the owner of my favorite game. :))
Thanks alot

Am Di., 14. Apr. 2020 um 01:56 Uhr schrieb Nelson Sexton <
notifications@github.com>:

**Comment by SDGNelson** [comment]
Thanks for the report! I will mark with the "next patch" label so that I remember to give it a try.

**Comment by IChicken31** [comment]
Ok, thanks alot! :))

Am Mi., 15. Apr. 2020 um 21:59 Uhr schrieb Nelson Sexton <
notifications@github.com>:

**Comment by SDGNelson** [comment]
I am happy to hear that it is one of your favourite games. :)

Trying to replicate this I tried ~15 times following these steps:
1. Local vanilla server with PEI map
2. Spawn default jet [ID 140]
3. Press Esc at time of death or spamming escape key while exploding

Unfortunately no luck. Does that sound right? Do you know if it is a particular spot/map/plugin/etc?

**Comment by SDGNelson** [comment]
Feel free to comment and I will re-open. There have been further reports of something along these lines, but it is difficult to reproduce (and I have not been able to reproduce in debug conditions unfortunately).
