### ISSUE TITLE
Problem finding a server

### ISSUE THREAD

**Issue by SrKevincito0011** [SmartlyDressedGames/Unturned-3.x-Community#1602]
This problem is with a server that occupies a vps to host the other servers. They come out in the search. I can normally play in them, but in this specific server it does not allow searching and if I connect through the IP it does not appear, any solution?

**Comment by SDGNelson** [comment]
Multiple gameserver instances are hosted on this VPS, but one of them cannot be reached? My first thought is to double-check that the configured ports are correct and the firewall inbound/outbound rules allow access for those ports.
