### ISSUE TITLE
When my friend enters any server the game crashes

### ISSUE THREAD

**Issue by erik7302** [SmartlyDressedGames/Unturned-3.x-Community#1603]
He tried: 
Cache integrity check.
Reinstalling BE
Windows Compatibly mode 7/8
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4465769/Client.1.log)
[output_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4465770/output_log.1.txt)
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4465771/error.log)
[crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4465776/crash.zip)
What i can highlight is this:
```
0x00007FF988B13674 (hmpalert) (function-name not available)
0x00007FF988B345DB (hmpalert) A3
0x00007FF988B344C3 (hmpalert) LoadLibraryW
0x00000215AC104E75 (Mono JIT Code) (wrapper managed-to-native) BattlEye.BEClient:LoadLibraryW (string)
0x00000215AC022D63 (Mono JIT Code) SDG.Unturned.Provider:receiveClient (Steamworks.CSteamID,byte[],int,int,int)
0x00000215AC01A913 (Mono JIT Code) SDG.Unturned.Provider:listenClient (int)
0x00000215AC01A1D3 (Mono JIT Code) SDG.Unturned.Provider:listen ()
0x00000215E52BF6A3 (Mono JIT Code) SDG.Unturned.Provider:Update ()
```

**Comment by Trojaner** [comment]
Looks like a crash caused by battleye

**Comment by SDGNelson** [comment]
It appears that "HitmanPro Alert" is blocking the game from loading the BattlEye DLL. Your friend may need to consult their anti-virus support site for information on whitelisting the game.
