### ISSUE TITLE
Getting stuck under the tree while breaking it (3.20.3.2)

### ISSUE THREAD

**Issue by Mikeliro** [SmartlyDressedGames/Unturned-3.x-Community#1604]
Sometimes, when I'm very close to a tree, when I cut it down, I get stuck to the root.

**Comment by SDGNelson** [comment]
This has still been happening in 3.20.3?

**Comment by Mikeliro** [comment]
Yes, it happened to me about 5 more times this week

**Comment by SDGNelson** [comment]
Sorry that I didn't reply on this. I think it must have been fixed, but if not please feel free to re-open.
