### ISSUE TITLE
New method "sendUIEffectImageRaw"

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#1607]
@SDGNelson, add the ability to send a picture from the server to the client, please

```CSharp
EffectManager.sendUIEffectImageRaw(short effectKey, CSteamID steamID, bool reliable, string childName, byte[] raw)
```

Also please take a look at #1539

**Comment by Trojaner** [comment]
This was already requested earlier.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1474

**Comment by SDGNelson** [comment]
Closing because duplicate as Trojaner mentioned. Sending raw images is low priority for now, and is more likely to happen after the netcode is improved.
