### ISSUE TITLE
Lag issues or cheat? 

### ISSUE THREAD

**Issue by selfish69** [SmartlyDressedGames/Unturned-3.x-Community#1608]
https://cdn.discordapp.com/attachments/697661225571581982/699654013422927872/is_this_hax_or_lag_or_both_edit.mp4

**Comment by Trojaner** [comment]
This could be a so called "silent aim" where the person shooting will always shoot at your direction regardless of their actual aim position.

**Comment by selfish69** [comment]
Thank you for answering! Appreciate it

2020 m. bal. 14 d., an 20:11, Enes Sadık Özbek <notifications@github.com>
rašė:

**Comment by SDGNelson** [comment]
I agree with Trojaner.
