### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1609]
[![](http://img.youtube.com/vi/dFhghLTTSg0/0.jpg)](http://www.youtube.com/watch?v=dFhghLTTSg0"")

When I spawn a vehicle, it gets under the ground

**Comment by SDGNelson** [comment]
It looks like the is specifically with a plugin "/v" command because it is spawning them too close to the ground. The built-in vehicle spawning command places them in the air so that they fall to the ground.

**Comment by TH3AL3X** [comment]
Negative, since we have an NPC that spawns vehicles and the vehicles fall under the map

**Comment by SDGNelson** [comment]
Using the vehicle NPC reward? In that case you should raise the spawnpoint above the ground enough that the vehicle does not spawn intersecting the ground.

**Comment by TH3AL3X** [comment]
For some reasons in single player it’s working fine but with dedicated server version it’s not working every vehicle it’s going to underground

**Comment by ZoomGYT** [comment]
uploaded the map, the errors are these:
(There are about 15 equal lines)
(Filename: Line: 0)
(Filename: Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "PlayLife V1/Objects/144/Nav"

[VIDEOO] https://youtu.be/8zTociaDVGk

I have the asset mods pack installed and I have tried to remove it to put it and it still does not go

**Comment by SDGNelson** [comment]
In the video it looks like the spawnpoint is intersecting the ground. Again, I think it will work fine if you raise the spawnpoint so that the vehicle lands on the ground. You can verify by using the built-in vehicle command to check that the vehicle lands properly.
