### ISSUE TITLE
Workshop Crates

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#161]
This is something i never understood, why do workshop crates that are MONTHS old still drop? what's the point in calling it January 2017 Workshop Crate #1 when it still drops in January 2018!!! in my opinion they should start dropping at the first of the month then stop at the end, this would for starters make more sense, also it would boost the market prices

Either that or they should be renamed to simply Workshop Crate #<NUMBER>

**Comment by SDGNelson** [comment]
They're prefixed with the month/year to help make it easier to tell them apart aside from a single number. The January 2017 workshop crate hasn't been dropping for quite some time - it's only available on the market/trading.
