### ISSUE TITLE
Turret yaw angles for driver position not overwritten

### ISSUE THREAD

**Issue by MaikeeMaous** [SmartlyDressedGames/Unturned-3.x-Community#1611]
Turret yaw angles set in the vehicle's dat file are not applied for the driver seat (currently uses the default driver viewing angles instead of 20 degrees). The rest of the attributes such as pitch works as intended.

Portion of the vehicle's dat file I used for reference:
```
Turrets 1
Turret_0_Seat_Index 0
Turret_0_Item_ID 1300
Turret_0_Yaw_Min -10
Turret_0_Yaw_Max 10
Turret_0_Pitch_Min 63
Turret_0_Pitch_Max 96
```

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix.

**Comment by SDGNelson** [comment]
Should be fixed in the next update. The only vehicle with a driver turret in vanilla is the fighter jet so I modified it a bit to test temporarily, but feel free to comment if you run into other problems.
