### ISSUE TITLE
When player names enabled (shift+f7) it shows different names than in player list

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1613]
What is the reason behind that? I believe it shows private name? From my experience, it is really confusing when you need to open player list and go through whole list to find the right person for some reason.

**Comment by Bradler26** [comment]
It works the same way that groups work and groups show private names

**Comment by SDGNelson** [comment]
Originally the player name overlay was groups-only, so it assumes that you are a member of the same group and shows nicknames. I will mark this as a bug and make the names consistent with the player list. Thanks for the report!

**Comment by CatzMR** [comment]
Hope to show the player's distance on shift + F7

**Comment by SDGNelson** [comment]
Fixed for the next update.
