### ISSUE TITLE
Visual glitch with weapons on POV

### ISSUE THREAD

**Issue by GoryBark** [SmartlyDressedGames/Unturned-3.x-Community#1615]
Visual glitch. If i have a modded weapon and an unmodded/different one of the same weapon type, the picture in the POV doesn't switch if i directly switch the weapons. This is regarding the 1 and 2 slot pov. (:

**Comment by SDGNelson** [comment]
By "picture in the POV" are you referring to the thumbnail in the inventory? It might be that the custom item is missing a thumbnail camera. If you attach the Client.log file it might provide some insight.

**Comment by GoryBark** [comment]
Do you know how I would be able to do that? And if possible, are you able to contact me on discord to explain? I rarely go on GitHub. My discord is GoryBark18481#2387
Thanks (:

**Comment by SDGNelson** [comment]
In Steam Library go to Unturned > Properties > Local Files > Browse Local Files. Client.log should be in the Logs directory.

To add the thumbnail transform create a child transform named "Icon" in the Item.prefab.
