### ISSUE TITLE
Problems with player interaction on the server

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#1616]
Sometimes it appears in the server, there are 24 players in the server, only 23 players are displayed in the player list, all players in the server can't see him, the player shows [?] After being killed by others, he killed you, he is in other The player remains invisible, the reason for triggering this BUG is unknown, hope to find a fix
Another bug is that after the player is reborn on the server, he cannot see the movement of other players, showing that all players are in their original positions
These two bugs have been around for more than 2 years, I hope to find a fix

**Comment by SDGNelson** [comment]
Hmm unfortunate to hear that this is happening (still or again). The player gets created on the server but other clients are not getting the "connected" packet. One of the goals reworking the netcode is to have better debugging tools to track down issues like this. 

I still think that the most likely cause at this point is a plugin binding `onServerWritingPacket` and screwing with the memory. This is a long shot but do you know if any of the plugins on your server are using that?

**Comment by CatzMR** [comment]
I checked the plugin and asked the developer, no plugin used onServerWritingPacket.

**Comment by CatzMR** [comment]
@SDGNelson Is there any good way to detect this bug or solve it? When the number of servers is relatively large, it is particularly easy to trigger this bug.

**Comment by CatzMR** [comment]
@SDGNelson  Is there any good way to detect this bug or solve it? It is especially easy to trigger this bug when there are many server players.

**Comment by SDGNelson** [comment]
Thanks for asking them about that. I am surprised if this is easy to trigger with many players - do any other hosts reading this thread often run into this? I will ask a few other hosts as well.

**Comment by SDGNelson** [comment]
From talking with a few hosts it sounds like this must be related to some plugins on your server. (others are not running into it) I recommend disabling one or two at a time to try and narrow down which plugin it is. If you find an answer and can share that would be much appreciated!

**Comment by CyberAndrii** [comment]
Players do not see the movement of the other player like in the video? https://youtu.be/7CVVuD2XaDw

I think that's because some plugin teleports that player before spawning (like I do).

#### Steps to reproduce (same as in the video):
P1: already connected
P2: connects
Plugin: teleports P2 (probably no matter where to)

P1: cannot see the movement of the P2
P2: sees the movement of the P1


#### The plugin that I used in the video:
```csharp
using Rocket.Core.Plugins;
using Rocket.Unturned;
using Rocket.Unturned.Player;
using UnityEngine;

public class PlayerDesyncTestPlugin : RocketPlugin
{
    protected override void Load()
    {
        U.Events.OnPlayerConnected += PlayerConnectedEventHandler;
    }

    protected override void Unload()
    {
        U.Events.OnPlayerConnected -= PlayerConnectedEventHandler;
    }

    private void PlayerConnectedEventHandler(UnturnedPlayer player)
    {
        player.Teleport(new Vector3(0, 40, 0), 0);
    }
}
```
I used  `U.Events.OnPlayerConnected` , but as I remember with `UnturnedPlayerEvents.OnPlayerRevive` works too.

**Comment by CatzMR** [comment]
There is another BUG that the player is killed by [?] ?, and the player who killed him is invisible, and he is not in his player list. May I ask what is going on. @CyberAndrii

**Comment by SDGNelson** [comment]
@CyberAndrii interesting case. That is fortunate you tracked down the cause. It would seem reasonable to expect to be able to teleport the player during those events, but as you found there must be some unexpected behavior. I will see about deferring teleportation requests in those cases or something.

**Comment by CatzMR** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4543707/Client.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4543710/Client_Prev.log)
@SDGNelson

**Comment by CatzMR** [comment]
[new 1.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4567588/new.1.txt)
