### ISSUE TITLE
Random Battleye ban

### ISSUE THREAD

**Issue by fatalchickenrape** [SmartlyDressedGames/Unturned-3.x-Community#1619]
As the title says, I got banned from playing multiplayer for no reason that I could come up with. I didn't use any hacks or similar software and I had legitimate software running in the background(Twitch, Steam Desktop Authenticator, Steam, EGS and such). I wanted to appeal on Steam for an unban but there is no way since it is a game ban not a VAC ban.
This is my Steam profile: https://steamcommunity.com/id/chris_kz2/

**Comment by archie426** [comment]
It’s probable you are HWID banned by BattlEye. I believe that was added a few updates back. I feel there should be an appeal for shit like this....

**Comment by fatalchickenrape** [comment]
I've never been banned by BattlEye

**Comment by SDGNelson** [comment]
For the meantime here is the BattlEye-specific appeal site: https://www.battleye.com/support/
