### ISSUE TITLE
Community Module

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#162]
As apparently @aviadmini also suggested we (any developer who wants to contribute) can make an open source community module which ships with Unturned. This allows developers to participate on Unturned clientside code without Unturned itself being open source and having issues with licenses.

I know about the Unturned and the framework modules but that's not what I meant (they can still be open source too!). I mean a new module which only contains community contributed code (especially SteamCalls). Of course the Unturned code itself has to contain required hooks so we can actually change behaviour of the game.

Ideally the module is soft-depend (only loaded but not referenced directly) and Unturned can work without it.

Of course someone also would have to approve all changes and coordinate it. *cough cough*

To prevent custom compiled modules (and cheating) a strong key or even better a hash check for each release could be used. (You could send hash of all modules to server like it does with the Assembly-CSharp.dll but dont forget to also calculate the hashes of any included library)

As license GPL would not work as Unturned is proprietary but LGPL, MIT, Apache 2 or BSD would do it (I would prefer MIT)

**Comment by aviadmini** [comment]
I would contribute 
Apache 2 for the license

**Comment by SDGNelson** [comment]
This could be done through a public repository accepting pull requests from community contributors, and compiling before each update release. I'm not sure about the time requirements of moderating all the pull requests, but I'm sure we could find some interested devs (sounds like you would be). I'll look into setting it up soon.

**Comment by Torubloo** [comment]
Good idea but the lead for this project should either be you yourself Nelson, or someone else who has experience with leading open source "official" projects like Sven and not someone who's only suggesting this so it is easier for him/developers on his site to make plugins and sell them so he profits

**Comment by Trojaner25** [comment]
Firstly, I do not make new plugins. So this does not increase sells for me in any way.
Secondly, we, the IP developers are those who mostly push for changes to make better plugins.

I have experience in open source, I have written 150.000+ lines of Java source code for about 10 Minecraft plugins and not only managed ImperialPlugins, but also the open source @Static-Interface repo. I think I have enough experience in Open-Source and management to deal with this.

@Torubloo Liking your own message? Seriously?

**Comment by SDGNelson** [comment]
Opened a repository for this here: https://github.com/SmartlyDressedGames/Unturned-3.x-Community-Module

**Comment by aviadmini** [comment]
Alrighty, time to add some fun

**Comment by SDGNelson** [comment]
It'll be a learning experience for me! Let me know if anything needs better configuring for the pull requests.

**Comment by Trojaner25** [comment]
I made a pull request which should structure the project so that it is proper formatted.

**Comment by SDGNelson** [comment]
Thanks for the information and cleanup commit! I've enabled the CLA - wouldn't have though to include that.
