### ISSUE TITLE
Mass DC bugged

### ISSUE THREAD

**Issue by bjorn29922** [SmartlyDressedGames/Unturned-3.x-Community#1621]
Like every 1 hour my servers will Mass DC everyone 
Is there any way to fix this

**Comment by tankirules** [comment]
You should probably attach logs

**Comment by SDGNelson** [comment]
From talking with a few reputable hosts recently it sounds like this had been related to specific RocketMod plugins. I recommend trying to disable a few at a time and seeing which ones are causing the mass disconnects. In the next update I am also going to make it harder for plugins to clobber packets which is probably relevant in this case.

**Comment by SingleThreadedWorld** [comment]
I know servers can "blacklist" clients if they send too many packets and stop receiving information from them, but is it possible for clients to do this to servers? Sometimes when there is a lot of stuff going on there will be a mass disconnect, the server will say all players finished their sessions, and clients will say the server stopped sending them input. Some players have to restart their game after this to rejoin.

**Comment by SDGNelson** [comment]
@SingleThreadedWorld any code that blacklists a connection like that goes through `Provider.refuseGarbageConnection`, so we would see a message about it in the client log if that were the case. Back when there were some peer-to-peer packets for voice chat it could happen between clients, but I have not seen the client ignoring the server in any of these mass DC cases.
