### ISSUE TITLE
NPCs and items issue

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1623]
Ok, kind a old bug which still exists. You can config a reward for NPCs. Nevermind, dialogue, response, or quest. And if you do more than 1 amount of item, NPC will "read" and perceive only first item from reward. Remaining items becoming cursed. NPC don't see them. You can't trade it, and it ignores conditions. 

This is not all. Even if you drop remaining items, they will be still cursed. It's a bit annoying you need to do a lot of rewards giving players only one item.

**Comment by SDGNelson** [comment]
To double-check before digging further: has this happened to you recently? I believe it was fixed in one of the past few updates.

**Comment by NoThreat** [comment]
Ok it is good now, I found my mistake. Sorry for bothering.
