### ISSUE TITLE
Check If Player Currently Exists On Server

### ISSUE THREAD

**Issue by Cameron-HTML** [SmartlyDressedGames/Unturned-3.x-Community#1624]
Is there a way to check if a player exists on the server at the time of check?

**Comment by rube200** [comment]
if u mean offline,
u can check if he have files on players data

**Comment by Cameron-HTML** [comment]
Well, right now my issue is that when a player joins the server I store stats about that player like SteamID. Each player is given a rank based on those stats, even if the player is offline their rank is updated. My issue is that when I update the UI I’m just sending the effect to all the stored SteamIDs and if the player isn’t connected to the server it throws a NullException error. Is there a way to get a list of online players or just check if the player exists on the server?

**Comment by DiFFoZ** [comment]
use this to get all online players:

`Provider.clients`

**Comment by rube200** [comment]
@DiFFoZ is right for online player use `Provider.clients`

**Comment by Cameron-HTML** [comment]
Can I get the players `CSteamID` from `Provider.clients`?

**Comment by Cameron-HTML** [comment]
I looked into it and realized that `Provider.clients` is a `CSteamID`, sorry!

**Comment by rube200** [comment]
Pls close this issue
