### ISSUE TITLE
Vehicle glitching

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1629]
When I try vehicle on singleplayer - it works perfectly in most cases. But when I test it on the server - it becomes laggy when trying to drive into steep hill (example in a video).

It seems like its happening because Wheel_Collider_Mass_Override. If I set it to higher (eg. 5) - it glitches even more (set to 4 in video example). Yet If I set it to lower - vehicle starts acting like its on Mars or something. Now, if I remove Wheel_Collider_Mass_Override - vehicle becomes useless as its speed drops to 15~ no matter what I set in config.

Wheel colliders are set exactly as vanilla cars on example package.

I believe that I am just missing some row in config or misconfigured unity part but I think answer to this might help for more modders because I've seen alot of vehicles on workshops which are acting the same (works perfectly on singleplayer but not on server).

https://streamable.com/giga2p

**Comment by tankirules** [comment]
I believe setting Wheel_Collider_Mass_Override to 2 is standard for most mods

**Comment by baranmod** [comment]
I actually checked 10 random vehicle mods on workshop - 6 had it set to 5 and 4 vehicles didn't have this (these 4 had a speed problem). I believe this is because there were lots of recommendations on modder discord groups to use value of 5. And it actually makes vehicle controls much better.

My point is, if this glitching is solved - we could actually make vehicles more diverse (not only this "jelly on moon" version)

I also checked Experimentation physics profile which have wheel mass set to 7. And this profile makes car much more stable on ground but glitching (when driving into steep hills) is worse too

**Comment by SDGNelson** [comment]
It looks like your physics configuration is good, but in multiplayer the moves are being rejected because it is driving uphill so quickly. Unfortunately the physics are not deterministic so the client simulation is used, so there are some basic restrictions on how far each vehicle can move on each axis. For your case I think it would make sense to have an option to raise the vertical limit.

**Comment by SDGNelson** [comment]
For the next update I have added `Valid_Speed_Up` and `Valid_Speed_Down` to vehicles. Measured in meters per second.

**Comment by baranmod** [comment]
Great news! Thanks :)

**Comment by SDGNelson** [comment]
No worries, let me know if you still have issues after the update.
