### ISSUE TITLE
Hello Nelson 

### ISSUE THREAD

**Issue by Weeezy420** [SmartlyDressedGames/Unturned-3.x-Community#1631]
I got a battle eye ban for no reason i was playing on a server when i suddenly got banned. I really really like ur game and i even bought Gold upgrade to support ur work!
pls help

**Comment by surv0013** [comment]
Do you make some of the biggest and most creative plugins for this game?.. No?! Then you have no chance.

**Comment by Trojaner** [comment]
@surv0013 Game4Freak has very good reputation and a lot of people in the community trust him. Of course, with his reputation, chances for higher that Nelson himself checks the appeal. Someone who just opened his GitHub account just to create this issue has lower chances that Nelson will help, they must contact Battleye directly.

Regardless of who they are, everyone will go through the same procedure of getting their case checked.

**Comment by surv0013** [comment]
@Trojaner I understand that reputation matters, it was just a joke.

But seriously, it’s no secret that BE anti-cheat is not doing its job. Cheaters have played and continue to play.

**Comment by Trojaner** [comment]
| But seriously, it’s no secret that BE anti-cheat is not doing its job. Cheaters have played and continue to play.

I agree on that, sadly Battleye does not really have the same priority and protection on Unity based games as other engines...

**Comment by Weeezy420** [comment]
So bois what am I supposed to do

**Comment by Trojaner** [comment]
Contact Battleye support

**Comment by Weeezy420** [comment]
where?

**Comment by educatalan02** [comment]
https://www.battleye.com/support/

**Comment by SDGNelson** [comment]
@Trojaner's reply is well-worded and accurate. @educatalan02 is correct that official BattlEye support is the right place to contact for now.

Recently Escape from Tarkov, a popular game using Unity, integrated BattlEye which has led to some detection improvements. While potentially a bad metric: there are more cheaters being banned than ever. While sometimes there are worse months than others, I do think BattlEye is overall doing a good job. SDG pays a monthly fee to BattlEye so it is something I keep tabs on.
