### ISSUE TITLE
[BUG] Able to bake Devkit Foliage in singleplayer/multiplayer

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1633]
Pretty minor, but can lag the game pretty bad, and causes all resources to swap to Skybox models, might be problematic in PvP situations. Might be easier to just prevent the Devkit Editor from being opened while in Singleplayer/Multiplayer.

**Comment by SDGNelson** [comment]
Odd case, will fix.
