### ISSUE TITLE
[FEATURE] Stereo rework

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1634]
It's really good thing you can add songs and listen to them in-game. But isn't possible to rework the process of creation? .content not really good for this, especially you can't even give names for songs without changing in-game files. 

Maybe it will be possible to change this in future, doing it as masterbundle or unity3d?

**Comment by SDGNelson** [comment]
Allowing master bundle to be used instead makes sense - it is essentially the same. As for changing the display name it should be possible with the translation file, but similarly it would make sense to allow the legacy language.dat file.

**Comment by SDGNelson** [comment]
Added for the next update.
