### ISSUE TITLE
[FEATURE REQUEST] Option for "Fire" animation

### ISSUE THREAD

**Issue by XtremelyEvilGumDrop** [SmartlyDressedGames/Unturned-3.x-Community#1635]
Currently, the player needs to stop ADSing after firing for bolt-action and pump-action guns in order to fire again.  However, because many other FPS games allow you to keep ADSing with these types of guns, I would like to see a new data option that can be set True or False that lets you shoot this way, or even a new type of Action.  The exception to this would be scoped weapons, but for iron sight snipers, shotguns, and even lever-action rifles, this would be a nice feature.  I also would like to have the "Hammer" animation play during full auto because it would be interesting for guns that require manual input.  One example would be a crank operated Gatling gun, but I'm specifically interested in making a fan-fire style revolver based on the Peacekeeper revolver from Battlefield 1.  With the current data, I made it bolt-action with a custom hammer animation, but there is too much delay between each shot to make it effective, no matter how short I make the animation.  Maybe it's because of my mouse, but it's also full auto in BF1, so if you could ADS and full auto with a hammer animation, weapons such as this would be so much smoother and more practical to use.

**Comment by tankirules** [comment]
Please yes, guns like the Lee enfield could cycle the bolt while retaining a sight picture and that is exactly what I want to do
