### ISSUE TITLE
Navmesh zombie spawns

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#1636]
While helping some friends we have noticed, that at some point zombiespawns in navmeshes with a higher indexes dont seem to spawn zombies. On the map zombies spawned in navmeshes with indexes <= 37 and didnt in navmeshes with indexes >= 39 (we couldnt find the 38 on the map).
They are using a large map.

**Comment by SDGNelson** [comment]
Are you sure that none of the navmesh bounds (purple and white lines) are intersecting? Only one navmesh is loaded at a time, so it may appear zombies are not spawning because the lower indices are given priority.

**Comment by Game4Freak** [comment]
They had some overlapping navmeshes

**Comment by Game4Freak** [comment]
thanks btw :)
