### ISSUE TITLE
All transport on the server has stopped working!

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1638]
He does not respond to blows, it is impossible to get into it, buildings cannot be removed and interaction cannot be made.
Although, if you reconnect to the server, you have 2 seconds to get into it

Watch the video to make sure:
https://www.youtube.com/watch?v=w3qKoygnw6U&lc=UgzHOCqnmlpWqXFzFCh4AaABAg

**Comment by SDGNelson** [comment]
It looks like something specific to that custom license plate or the custom vehicle. If you look at a vanilla vehicle I assume it works properly?

**Comment by MrGoBi** [comment]
No, all transport on the server does not work, even vanilla

![image](https://user-images.githubusercontent.com/46658857/79850985-5f61ca00-83cd-11ea-9b10-4dc5bc3ecee0.png)

**Comment by educatalan02** [comment]
What OS is your server using? @MrGoBi

**Comment by MrGoBi** [comment]
> Какую ОС использует ваш сервер? @MrGoBi

Windows

**Comment by SDGNelson** [comment]
Hmm there isn't any server option to disable those interactions. Could you attach the Client.log file after trying to interact with the vehicle please? It may have some vehicle-related error.

**Comment by MrGoBi** [comment]
People say that the problem started last night, but not everyone had it. I restarted the server and became all without exception. However, again, if you stand on the roof (or hood) of the machine and enter the / whois command, it will show the owner. If you do this from the side, then nothing will work. With other similar commands does not work at all.
And yet, if you reconnect to the server you have 2 seconds to manage to interact with the transport or the buildings on it, and after this time the problem returns.

[Server_TEST_UPDATE.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4511136/Server_TEST_UPDATE.log)

[0Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4511144/0Client.log)

**Comment by SDGNelson** [comment]
The client log unfortunately does not suggest anything. Are you able to interact with other objects e.g. dropped items?

It may be worth comparing on another map, or disabling a few plugins at a time to track down what is causing it.

**Comment by MrGoBi** [comment]
Everything works and I can interact with all buildings, except those in transport.
Removing all plugins did not fix the situation

**Comment by SDGNelson** [comment]
I wondered if the interaction physics trace was maybe getting blocked by an invisible collider on the Vehicle layer, but if you can interact with everything else that is mostly ruled out. Unless dropping an item right next to the car cannot be picked up.

Do you mind sharing the server IP and making SteamID 76561198036822957 admin? I will connect in debug mode to see what might be preventing interaction on the client.

**Comment by MrGoBi** [comment]
185.66.84.235:25444

**Comment by MrGoBi** [comment]
![image](https://user-images.githubusercontent.com/46658857/80017727-b35bd400-84dd-11ea-9d4d-2e12c27a6aea.png)

**Comment by MrGoBi** [comment]
Yes, objects cannot be raised either, hmm

![image](https://user-images.githubusercontent.com/46658857/80017996-10f02080-84de-11ea-893e-c85363901749.png)

**Comment by SDGNelson** [comment]
I forgot that I will get kicked by BattlEye. 🤦‍♂️ For the next update I will change that.

The fact that you cannot pickup the item nearby suggests it is related to a collider - maybe a Trigger collider on an unexpected layer. Potential suspects:
- Effect spawning near the vehicle?
- Map objects in the area?
- User Interface objects?

**Comment by MrGoBi** [comment]
I am not a programmer. Just making modifications. And I thought this, could there be a problem in that the license plate collider is too small (0.04)? There are a lot of transport on the server, and as a result there are twice as many license plates.

**Comment by SDGNelson** [comment]
To clarify: I think there is a BIG collider somewhere.

Considering the vanilla vehicle had the same problem on that map I think it is a collider related to the map or server (effects, map objects, user interface).

You mentioned that items can be picked up in most places, but cannot be picked up near the spot where the vehicle cannot be entered. From that I think it would be worth trying to narrow down where exactly on the map is having the problems (e.g. by dropping items and seeing if they can be picked up) and what objects or effects are in the area causing the problem.

**Comment by CyberAndrii** [comment]
@MrGoBi These items in your `pgsrp.masterbundle` have too big colliders.

![Screenshot_1](https://user-images.githubusercontent.com/37713088/80255818-5f402380-8686-11ea-998a-e35aafe77906.png)

**Comment by SDGNelson** [comment]
Thanks @CyberAndrii for helping out! That does look like the cause. It was nice of you to examine the asset bundle.

**Comment by Papa1234567** [comment]
Did you finally fix it?
