### ISSUE TITLE
OK Button, please!

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#1639]
From the very existence of the game, the reason for kicking the server is visible to the player for only a few seconds, after which the window goes to the main menu. Maybe it's time to add the “OK” button so that you can read the reason for the kick/ban from the server?

This button is desirable for all other cases when important information is written on the screen.
![image](https://user-images.githubusercontent.com/17459138/79804943-1b8fa600-8376-11ea-9b10-187927f742a6.png)

**Comment by MrGoBi** [comment]
+

**Comment by SDGNelson** [comment]
You raise a good point! It should be straightforward to take care of for the next update.

**Comment by Greenorine** [comment]
You can press "esc" some times btw xd

**Comment by SDGNelson** [comment]
This has been annoying for a long time. Finally added in the next update.
