### ISSUE TITLE
Game freeze when buildings appear/disappear

### ISSUE THREAD

**Issue by LOOMICode** [SmartlyDressedGames/Unturned-3.x-Community#164]
Hello,

We've noticed some troubles with the server.
When the buildings appear or disappear (the base in the background) we're getting lag (and in my case not responding game - as You can see on the attached video + dead shortly after reconnect to the server).

Please fix this because the biggests servers are unplayable because of this game breaking render bug.

Proof link:
https://www.youtube.com/watch?v=RWOgyYNHm1c

**Comment by SDGNelson** [comment]
Ideally the instantiation would be spread across multiple frames and info across more packets, but there are some complications to implementing it at this point.

**Comment by LOOMICode** [comment]
Okay, thanks for the answer :)
We will wait for the fix and I wish you all of the best @SDGNelson :)

I hope that this will be fixed as fast as possible :)
