### ISSUE TITLE
Vehicle Battery issue

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1641]
I don't know what is happening, but vehicle batteries are consumed when you press RMB in plane, heli or boat. But they don't have sirens or headlights. It's annoying because you need to change batteries very often. Please, fix it.

**Comment by SDGNelson** [comment]
Thanks for the report, I will check it out.

**Comment by SDGNelson** [comment]
Should be fixed in the next update.
