### ISSUE TITLE
ERROR SERVERS

### ISSUE THREAD

**Issue by ZoomGYT** [SmartlyDressedGames/Unturned-3.x-Community#1645]
Hello, I want to know if you can help my friend, this always happens to him.
I have a problem with servers not spinning when I try to connect to any server that automatically disconnects me in the 30s, I have already reinstalled the game several times and it has not worked. As you can see in the video during those 30s, I can play normally, and I have a good connection I need help

VIDEO: https://mega.nz/file/c3RDCKiQ#o7LH7vE47uQdGmL3nkQPZ0AAGOdTbe1I7hlwSEIBooI

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time! It looks like the video expired, but if you are still experiencing the issue feel free to comment and I will re-open. For anyone coming across this there is a new support site with guides for this kind of issue: https://support.smartlydressedgames.com/hc/en-us
