### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by moysture** [SmartlyDressedGames/Unturned-3.x-Community#1646]
so me and my friends where raiding a base on russia so i spawned in a tank next to a tree it suddenly just glitched out and the half of the tank is underground so when i leaved the tank i got spited out of the map and i am stuck under the ground now in a pool of water help.

**Comment by SDGNelson** [comment]
Sorry for not replying to this at the time! I must have missed it. IIRC nowadays it should automatically life you up because only certain areas of the map are designated as underground-allowed.
