### ISSUE TITLE
[FEATURE REQUEST] Pump-action and Break-action guns should not delete empty mags by default / add Should_Delete_Empty option for magazines

### ISSUE THREAD

**Issue by XtremelyEvilGumDrop** [SmartlyDressedGames/Unturned-3.x-Community#1647]
Observed this issue making a mag for the Bluntforce, where the mag disappeared after it had emptied and the gun was reloaded.  I double checked to see if Delete_Empty had been removed from my mag's item data and it was, so I changed the action of the Bluntforce to Bolt, which made the mag work properly. 12 gauge already has Delete_Empty, so having this true for the gun as well is a bit overkill.  It limits choices for cool (and rare) mags that shouldn't disappear in real life.

**Comment by danaby2** [comment]
Should_Delete_Empty_Magazines False
add this to ur gun ^

**Comment by XtremelyEvilGumDrop** [comment]
It's for the Bluntforce though.  I want to make a reusable mag for pump-action shotguns without overriding the game files in any way.  I tried Should_Delete_Empty False for my magazine as well, didn't work.

**Comment by XtremelyEvilGumDrop** [comment]
This will help with some of my existing guns though.

**Comment by Spebby** [comment]
then perhaps an override option should be added to Magazines.

**Comment by XtremelyEvilGumDrop** [comment]
Agreed, that would be much better.
