### ISSUE TITLE
Allow disabling death music serverside

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#165]
I know you can manually disable it in client settings, but I'd like to add some custom death sound effect which might collide with client sound :0

Should be pretty easy to make 💪 

### Alternatively
Give server config option to set effect IDs to play on death 😉

**Comment by Torubloo** [comment]
Pointless aviadmini is just asking for things he can add to his plugins to make money off you but aren't things that are going to be generally used/are useful

**Comment by aviadmini** [comment]
Here we go, blind lewis

Read the *alternative* part: it doesn't have anything to do with plugins

**Comment by N1GHTPATROL** [comment]
Maybe instead of Nelson using his time to help you make money, for a feature you'd be the first to ask for, he can use his time to make more useful additions/fixes. Just my opinion.

**Comment by aviadmini** [comment]
Pfft, look who's talking 🙉  https://vgy.me/Md2KQ5 

Anyway, this is not the right place to discuss it. Nelson can do whatever he wants to

**Comment by WarpKat** [comment]
I wouldn't even give this a priority.  There are other issues that need to be fixed.

**Comment by SurvivorCDG** [comment]
Yes, it's not so important, but I get annoyed by the standard sound at death, perhaps it's because he associates me with the loss of loot. :D

**Comment by aviadmini** [comment]
As player, you can turn it off in settings. However I'm asking for an option for servers/plugins to set custom sounds
