### ISSUE TITLE
Unturned Linux Servers

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1650]
For some reason this morning my server has stopped working, I have been investigating and I cannot find a solution, nor does it allow me to enter steamcmd 
![image](https://user-images.githubusercontent.com/13141042/80216773-dd78d780-863e-11ea-8b90-1a76262ec7cc.png)

**Comment by SDGNelson** [comment]
Looks like it could not find a Steam Connection Manager server. Maybe they are back online now?

**Comment by TH3AL3X** [comment]
I'm trying to contact here https://github.com/ValveSoftware/steam-for-linux/issues/7063
It is all very strange, because my server has been open for 4 months and I have touched absolutely nothing, and this morning everything stopped working ...
