### ISSUE TITLE
Could you explain the editing of gun files

### ISSUE THREAD

**Issue by WolfCaesar** [SmartlyDressedGames/Unturned-3.x-Community#1651]
Hi, I am a server developer in Unturned and am currently editing weapons. And I ran into difficulties in understanding exactly what I should edit.
Could you use the example of this source to list each line.

"
Type Gun
Rarity Legendary
Useable Gun
Slot Primary
ID 37300

Can_Ever_Jam
Jam_Quality_Threshold 0.9
Jam_Max_Chance 0.5
Unjam_Chamber_Anim Reload

Size_X 5
Size_Y 2
Size_Z 0.4
Size2_Z 0.7

Magazine 37301
Barrel 37302
Sight 37305

Hook_Tactical
Hook_Sight

Ammo_Min 5
Ammo_Max 20

Safety
Semi
Auto

Caliber 37299

Range 200
Firerate 5
Action Trigger

Player_Damage 78
Player_Leg_Multiplier 0.7
Player_Arm_Multiplier 0.5
Player_Spine_Multiplier 0.7
Player_Skull_Multiplier 1.1

Zombie_Damage 90
Zombie_Leg_Multiplier 0.5
Zombie_Arm_Multiplier 0.5
Zombie_Spine_Multiplier 0.7
Zombie_Skull_Multiplier 1.2

Animal_Damage 90
Animal_Leg_Multiplier 0.5
Animal_Spine_Multiplier 0.7
Animal_Skull_Multiplier 1.2

Barricade_Damage 30
Structure_Damage 30
Vehicle_Damage 30
Resource_Damage 30
Object_Damage 30

Durability 0.3

Spread_Aim 0.005
Spread_Hip 0.4

Recoil_Aim 0.625
Recoil_Min_X 1
Recoil_Min_Y 2.5
Recoil_Max_X 3
Recoil_Max_Y 4

Recover_X 0.3
Recover_Y 0.75

Shake_Min_X -0.0025
Shake_Min_Y 0.0025
Shake_Min_Z -0.01
Shake_Max_X 0.0025
Shake_Max_Y -0.0025
Shake_Max_Z -0.015

Muzzle 4

Blueprints 1
Blueprint_0_Type Repair
Blueprint_0_Supplies 2
Blueprint_0_Supply_0_ID 67
Blueprint_0_Supply_0_Amount 3
Blueprint_0_Supply_1_ID 18215    
Blueprint_0_Supply_1_Amount 2
Blueprint_0_Tool 76
Blueprint_0_Level 2
Blueprint_0_Skill Repair
Blueprint_0_Build 27

Bypass_Hash_Verification
"

**Comment by SDGNelson** [comment]
If you have a more specific question we might be able to help, but for general information MoltonMontro wrote this item documentation: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ItemData.md
