### ISSUE TITLE
Repair Event for Barricades and Structures

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#1652]
It would be nice to have an event for blowtorch repairs natively. There doesn't seem to be one right now, even though it does pass through DamageTool.
From what I understand:
UsuableMelee
DamageTool.damage(..., isReparing: true, ...)
BarricadeManager.repair
Send to clients & remove health

It would be nice if we had an event from DamageTool something like DamageTool.onRepair(Transform, healamount, times, instigator)

I understand this is low priority, but would be grateful if it was considered.

**Comment by SDGNelson** [comment]
Would make sense to have. It would also make more sense if modifying health were just a positive or negative value rather than a bool... anyway this should be added at some point.

**Comment by SDGNelson** [comment]
For anyone looking back on this: it was added as OnRepairRequested and OnRepaired
