### ISSUE TITLE
Some modding suggestions that can help us out some more

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1653]
This issue is about nothing much, as I don't have too many to think in mind about. So let's get straight to it:

* It would be nice for us modders if you can give us the option to use the Action Break to support the Unplace & Replace we have.
* Try to make it so that 2 reloads can be played if the gun is still empty or not. Like in some way, repurpose the Hammer to play when the gun is empty. Oh, and if possible, try to make an option for Action Bolt to play the hammer after reload or not. It makes it convenient for animators.
* Give vehicle modders the option to make the first seat a turret seat. It gives us the edge to make nice turrets.
* Give melees more animations to play. Make it so that if something like Weak, Weak1, or more exist, they alternate between animations. Also applies to Strong. Again, gives animators more options.
* ~~Oh, & finally, make it so that magazines & all attachments multiply or reduce damage. Initially, I wanted to mod viable slugs but that was limited as of now.~~

**Comment by FalkenJr** [comment]
To add on your last point: perhaps add spread and range modifiers to magazines/other attachments?

Could be useful for your shotgun slug idea, with the modifiers the slugs won't have to be nullified by the short range and high spread

**Comment by XtremelyEvilGumDrop** [comment]
Agreed.  I tried to add bullet drop to my slugs but they don't travel far enough to make a difference.

**Comment by XtremelyEvilGumDrop** [comment]
Also the damage modifier does work on magazines for slugs, but only on people and zombies.  It didn't seem to apply to cars and structures last I checked though.  It would be nice if they were included or had a separate modifier at least.

**Comment by OneManOperative** [comment]
When I tried doing by testing it on what used to be a hollow point magazine for the Scalar, it didn't multiply damage & the gun just worked as normal. Unless I used the wrong one (Used the sample from the Makeshift Muffler), the effect did nothing at all.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
