### ISSUE TITLE
Tactical attachment suggest

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#1654]
Light and Laser tactical has children on Unity which means they are able to toggle on/off. Problem is activating those childrens on light or laser must contain light or laser on dat file which they must work as light or laser. Tactical that can toggle on/off but has no function has lot's of possibilities like custom tactical lights or laser.

**Comment by SDGNelson** [comment]
What sort of custom lights/laser do you have in mind without using the built-in functionality? For example, a custom laser still needs the built-in laser in order to draw the beam.

**Comment by FalkenJr** [comment]
Seems like they're interested in doing custom lasers and lights that behave similarly to how 2.0's tactical lights/lasers worked (moves around with the viewmodel and/or weapon animations?)

**Comment by XtremelyEvilGumDrop** [comment]
I think it would be cool if you could change the color of a laser or light if you can't already.  I tried copying the laser attachment and making everything green but it didn't work. :(

**Comment by sam9612** [comment]
> What sort of custom lights/laser do you have in mind without using the built-in functionality? For example, a custom laser still needs the built-in laser in order to draw the beam.

For lights, put some cookie on it so that it can make some better lights. Also spot light that attached on children will point exact where the gun point is.
Changing colour of laser beam need some extra work like modules.
Other way utilizing this could be make appear extra sights or extra gun parts like grenade launcher sights. Further more I have succeeded gun stock move backward when tactical turned on using joints that attached on children.

**Comment by SDGNelson** [comment]
I could see about adding some options for laser and light colors. Attaching them directly to the item rather than using the built-ins will be problematic however because the viewmodel is at the world origin, and the third-person item model will not line up with the camera - its animation might even be disabled while in first-person.
