### ISSUE TITLE
Car Lift issue

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1655]
Car lift a good object which can help upgrade vehicles, but it doesn't work properly a lot of time already. I remember when they worked well. The object can't lift car without driver inside. Also car can't fall after lowing object. Items can low but can't lift. 

WIll be great fix it in future. 
![20200426123437_1](https://user-images.githubusercontent.com/59829274/80303838-69177300-87bb-11ea-908f-2438f36bd44b.jpg)
![20200426123443_1](https://user-images.githubusercontent.com/59829274/80303841-6d439080-87bb-11ea-9fb6-5e2e1421bb7c.jpg)
![20200426123458_1](https://user-images.githubusercontent.com/59829274/80303843-6d439080-87bb-11ea-9151-b618afa8ce55.jpg)
![20200426123502_1](https://user-images.githubusercontent.com/59829274/80303844-6ddc2700-87bb-11ea-8b0e-bc1dbd4aa58f.jpg)

**Comment by SDGNelson** [comment]
The vehicle rigidbody is sleeping, but not waking up when the mesh animates. A dirty fix would be waking up any nearby rigidbodies when an interactable mesh is toggled. Will think about it.
