### ISSUE TITLE
Possible NullReference in NPCAnimalKillsCondition

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#1656]
This may occur in method `formatCondition(Player player)` in string.Format() because text isn't checked to be not null

for instance, `NPCHordeKillsCondition` has null check

edit: same goes for `NPCObjectKillsCondition`, `NPCPlayerKillsCondition`, `NPCTreeKillsCondition`, `NPCZombieKillsCondition`

**Comment by SDGNelson** [comment]
Thanks for the report! It should be using a default from the player localization file if unset, so I will get that fixed for the next update.

**Comment by SDGNelson** [comment]
Defaults for the kill quest conditions have been added for the next update.
