### ISSUE TITLE
Servers are not displaying on the Internet list

### ISSUE THREAD

**Issue by thereis** [SmartlyDressedGames/Unturned-3.x-Community#166]
After this last update, my servers are not displaying on the masterservers list.

IP: 177.234.152.42
Website: https://global-z.com.br

I've 9 servers running in the same ip. When they are empty, they display in the list, but when someone joins in the server, they simply disappear.

My filters are setted to default.

**Comment by N1GHTPATROL** [comment]
I've heard some other people complain about this issue as well.

**Comment by Torubloo** [comment]
Both of you hit me up on Discord, pretty sure I know the problem but gotta ask you a few questions

**Comment by thereis** [comment]
@Torubloo My discord: Reis#8021

**Comment by thereis** [comment]
Ok, the issue was responsible for the plugin HidePlugins.

Disabling the `<Enable_LargeServer>false</Enable_LargeServer>`, it was able to show my servers on the list.

Thanks @Torubloo for the support.
