### ISSUE TITLE
Makeshift Vehicle

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1660]
I don't know if it has already been reported or not, but I should have done it a long time ago, when a player equips a makeshift the error appears on the console but the 'gameplay' remains the same.
![IMG_20200427_171446](https://user-images.githubusercontent.com/20555316/80395055-9d1d9180-88aa-11ea-9d88-0185ea818f93.png)

**Comment by SDGNelson** [comment]
Labeling this as "next patch" so that I remember to give it a try in the next couple days.

**Comment by SDGNelson** [comment]
Thanks for the report! This led to an underlying issue as well - both will be fixed in the next update.
