### ISSUE TITLE
Root_#_Spawn_Override compatibility between different mods

### ISSUE THREAD

**Issue by XtremelyEvilGumDrop** [SmartlyDressedGames/Unturned-3.x-Community#1662]
Currently, Root_#_Spawn_Override is problematic because if there are multiple mods that use this option or utilize vanilla spawns, they do not interact well together.  For instance if one mod overrides a spawn table while the other adds to it, the latter mod will be overwritten.  Furthermore, it doesn't seem like different mods can override the same table, and that tables that have Override as their root weight cannot be used as roots.   As a result, mods that override spawns are incompatible with mods that use the same method or add to vanilla spawns, which should not be the case.

**Comment by SDGNelson** [comment]
Do you have any proposals on making them work better together? Spawn overrides were intended for developers working on "total conversion" style mods. (Multiple total conversions enabled at the same time is tricky to resolve.)

**Comment by XtremelyEvilGumDrop** [comment]
Maybe mods that use Override as a spawn weight should have an equal non-zero weight.

**Comment by XtremelyEvilGumDrop** [comment]
I think the problem is because Override has no weight that also makes such tables unable to be used as roots, so giving Override weight might also fix this issue.

**Comment by SDGNelson** [comment]
That is how it works at the moment. (Override weights are taken into account.)

**Comment by XtremelyEvilGumDrop** [comment]
Perhaps I am doing something wrong then.  I have two tables that both override the carepackages in Washington, but only one seems to work at a time.

**Comment by SDGNelson** [comment]
To double-check this I created two spawn tables with weight 1 that override the Horde Beacon (ID 1) spawn table. Then in the spawn editor they both show at 50%.

Perhaps your overrides do not have a weight set? There may be some warnings in the Menu > Workshop > Errors list.

That said, why does your mod have two separate spawn tables both overriding one?

**Comment by XtremelyEvilGumDrop** [comment]
Thanks Nelson.   My overrides didn't have a weight!  I thought that Override was the weight!

**Comment by SDGNelson** [comment]
No worries. For the next update I have made the Weight default to 1 when using the Override flag!
