### ISSUE TITLE
[FEATURE] Steam Achievements rework

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1664]
A lot of people likes achievements. But they are kind a obsolete. Why not to refresh icons and add new achievements? Players could suggest their thoughts in discussion somewhere on forum or Steam. 

Also it will be good to delete achievements related to removed curated maps. Like Hawaii.

**Comment by TheTioSweet** [comment]
I was also wondering why there's still Hawaii clothing on the game's files. E.g, Coastguard top and bottom.

**Comment by Spebby** [comment]
Some curated assets were added to the core game files, though not many.

**Comment by SDGNelson** [comment]
Closing because I do not foresee achievement changes anytime soon. There may be new achievements for new features and new maps in the future, but there are none planned yet.
