### ISSUE TITLE
[Question] Water Volumes Limit ?

### ISSUE THREAD

**Issue by TonySerum** [SmartlyDressedGames/Unturned-3.x-Community#1665]
Good evening, Nelson ..

I wanted to have a clarification, on the devkit and the possibility of creating Water Volumes ...

I would like to know the limit of this tool at cella level

I did an experiment below with the following graphics card:
- Nvidia GeForce 1060TI
- I7 8700K overclocked

Before the screen: 170fps ultra
After the screen: 150 to 140 fps ultra watching them all

Would it be possible to apply a LOD to this tool in native code? or through a module

![Screenshot_1](https://user-images.githubusercontent.com/45904163/80540274-4ea2ec80-89a9-11ea-8fcb-37157dead8b9.png)

**Comment by SDGNelson** [comment]
Why do you need so many? In general they are best used in sizes 1000 x 1000+ because the game will spawn water prefabs for each 1000 x 1000 area.

**Comment by SDGNelson** [comment]
Feel free to comment and I will re-open. Eventually I would like to update the water for performance and nicer quality.
