### ISSUE TITLE
RocketMod UnturnedPlayer.Ban Unexpected Behavior

### ISSUE THREAD

**Issue by Kr4ken-9** [SmartlyDressedGames/Unturned-3.x-Community#1667]
I believe, although I cannot be sure, that UnturnedPlayer.Ban is using Provider.ban as seen [here](https://github.com/RocketMod/Rocket.Unturned/blob/legacy/Rocket.Unturned/Player/UnturnedPlayer.cs#L275)

Using Provider.ban results in the player being kicked but the duration not applying, and the ban not being saved in SteamBlacklist.list.

If someone were to use UnturnedPlayer.Ban they would probably expect it to last the duration they specify. To correct this, I believe UnturnedPlayer.Ban should be using Provider.requestBanPlayer instead.

**Comment by PandahutMiku** [comment]
Might be better to submit in the Rocket Repository Nelson created: https://github.com/SmartlyDressedGames/RocketMod/issues

**Comment by Kr4ken-9** [comment]
Honestly didn't realize that repo existed. In that case I will just make a PR
