### ISSUE TITLE
[FEATURE] Confirm "Sub" button use

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1668]
In "Editor" tab there are "Sub" button to delete map. I had cases when you accidently delete map without possible way to restore it. Why not to add confirm for this option, like in Inventory?

**Comment by SDGNelson** [comment]
I think the buttons were labeled like that because I liked the symmetry of "add" and "sub" - dumb. When clicked however the remove button does confirm Yes/No. For the next update I will change the text to "Delete" to clarify.
