### ISSUE TITLE
Magazine blueprints suggestion

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#1669]
Currently magazine blueprints are written just like normal blueprints. Problem is, if there are lot's of different magazine with same caliber for example 5.56mm NATO 30 Rounds, 20 Rounds, 10 Rounds, 50 Rounds, Magpul P-Mag etc we have to write all blueprints one by one.  Instead of writing all of them, Share_Caliber would be nice so that same caliber magazines can share ammo with bunch of different magazines.

**Comment by SDGNelson** [comment]
I agree this would make sense. The crafting features are unlikely to be reworked, but it might happen eventually.
