### ISSUE TITLE
For a particle system on a projectile with layer and tag, "Logic, and "ground", the particle system renders at all ranges in singleplayer, but not in multiplayer

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#1672]
I was told on the forums this would render a projectile at all distances(for spotting artillery) but it only works in singleplayer

**Comment by SDGNelson** [comment]
Which feature is spawning the particle system? In multiplayer clients are only told about effects that the server thinks are relevant to them.

**Comment by FalkenJr** [comment]
If I'm reading the U3-Docs right (please correct me if I'm wrong) adding `Spawn_Explosion_On_Dedicated_Server` to the .dat of the weapon or ammo that creates the explosion effect should force it to render for all players by spawning it serverside

IE
`Explosive`
`Explosion [insert ID here]`
`Spawn_Explosion_On_Dedicated_Server`

**Comment by SDGNelson** [comment]
@FalkenJr you have a good point, but even in that case the explosion might not be considered relevant to the player depending on distance. Different features have different relevancy distances, so we might need a setting to override the distance per-effect.

**Comment by tankirules** [comment]
> Which feature is spawning the particle system? In multiplayer clients are only told about effects that the server thinks are relevant to them.

There is a particle system for the explosion effect, and a seperate one for the projectile. Problem is, past like 200m, you cannot see the explosion and therefore cannot adjust for fall of shot.

**Comment by SDGNelson** [comment]
Effects spawned from missiles as well as the explosion each have their own maximum distance server-side. I will mark this as next patch to allow overriding the max distance.

**Comment by SDGNelson** [comment]
This has been tidied up a fair bit for the next update. You can override the distance players will see the effect in multiplayer, and the per-gun spawn explosion setting should no longer be needed.
