### ISSUE TITLE
Continous Crashing

### ISSUE THREAD

**Issue by Topguy2205** [SmartlyDressedGames/Unturned-3.x-Community#1676]
When I join a unturned server I load into the server then after about 5 minutes unturned stops responding and must be closed down, I've checked logs and I get this
[2020-05-01 21:37:48] Server computed GUID: c0a921b4e058dc54e896019b725532cd
[2020-05-01 21:40:58] Kicked from server
Does anyone know how I can fix this?
I've tried everyhing, reinstalling unturned, reinstalling battleye, unsubscribing from all workshop items and validating game files.
How can i fix this???

**Comment by SDGNelson** [comment]
You are stuck on the loading screen, or are you able to move around before it crashes at 5 min?
Are there any other details later in the log? I will change it to log the kick reason in the next update.

**Comment by Topguy2205** [comment]
Im able to move around before it crashes, and I cannot see any other reason for it to crash in the logs

**Comment by SDGNelson** [comment]
Is there anything else after being kicked in the log though? It may hint toward what the game was actually doing when it crashed.

**Comment by Topguy2205** [comment]
There's nothing after the kicked log unfortunately. I can attach the log file if you wish.

**Comment by SDGNelson** [comment]
If the kick is the very last line in the log I will take your word for it then. Does your computer have less than 4 GB of RAM - in which case does the Task Manager indicate it is approaching 100% before the game crashes?

Being kicked shortly after joining is often related to BattlEye deciding something is wrong. In that case BattlEye might also be crashing. Might be worth comparing on a non-BE server or uninstalling unofficial code (if any).

**Comment by Topguy2205** [comment]
I've got 8GB of RAM, I'll try comparing the results of the game on a BE server and non-BE server.

**Comment by GazziFX** [comment]
Delete Unturned folder and install it again

**Comment by Topguy2205** [comment]
I had it working for a few hours, then it started crashing again, the update to the logs you have done has worked the log now says:
[2020-05-16 18:35:06] Kicked from server. Reason: 'BattlEye: Unofficial Modules not supported'

**Comment by SDGNelson** [comment]
Do you have RocketMod installed on your client? The Modules folder should be empty on the client when playing with BattlEye enabled. Thanks for following up with the logging!

This is one reason that using the standalone dedicated server is preferable: the server can have the server-side modules installed without interfering with the client.

**Comment by Topguy2205** [comment]
I doubt I have RocketMod installed, I checked the modules folder and There's a folder in it containing all the official maps and a gitignore file,

**Comment by SDGNelson** [comment]
Are you sure you were looking in the Modules folder and not the Maps folder? Anyway: if you delete the contents of the Modules folder you should be able to join properly again.

**Comment by Topguy2205** [comment]
Yes I am quite sure I was in the modules folder, I'l ldelete them now,
