### ISSUE TITLE
Deprecation of onServerReadingPacket, onServerWritingPacket, and onTriggerReceive

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1677]
To any plugin developers: are you manually binding any of these delegates (or onTriggerSend)? If so, I would like to know why so that a better alternative can be officially included. In the next update there will be a command-line flag to pass a copied buffer to these delegates so that they cannot write to the game's network traffic.

The events will remain supported for the foreseeable future, but are not ideal.

**Comment by CyberAndrii** [comment]
RocketMod uses these events so this should be enabled by default.

**Comment by warren39** [comment]
`SteamChannel.onTriggerSend += OnTriggerSend;`
I can get many events by using this delegate, such as "tellVehicleBatteryCharge", "askProject", "askToss" etc. I just listen, not write. It works well.

**Comment by SDGNelson** [comment]
> `SteamChannel.onTriggerSend += OnTriggerSend;`
> I can get many events by using this delegate, such as "tellVehicleBatteryCharge", "askProject", "askToss" etc. I just listen, not write. It works well.

Thanks for sharing. I think an event in UseableThrowable as added for askToss recently, and I will make a note about battery charge and projectiles.

**Comment by nanashi88** [comment]
Hi,
"are you manually binding any of these delegates"
sry idk what that mean, but we do the following:
SteamChannel.onTriggerSend += (...)=>{...};
Provider.onServerWritingPacket += (...)=>{...};

we use onTriggerSend to catch:
1- "tellSetGroup" , to log group changes during game, to solve issues between players, and know exactly who was in group , and when ...
2- "tellDeath" :  to log more data about deaths, like death location, and more details.

we use onServerWritingPacket to catch:
1- "VERIFY": to temporay save details (about players) that not gonna be available at "REJECTED" phase  
2- "REJECTED": to see who of our players was banned by Battleye/VAC
3- "KICKED": to see who of our players get banned by Battleye, while playing on our servers
we consider this very important to our servers, and we use it everyday

I guess the events at onTriggerSend could be catched at onServerWritingPacket.
also I haven't tried to search for alternatives.
I haven't tried to update this section of our module.
as module developer, I would like to have as much power , as possible, to reach events, and change data. I mean I don't like to be limits
but I understand, that this might cause bugs (if this is the reason for deprecating it)

**Comment by SDGNelson** [comment]
Thanks for sharing, @nanashi88. You are right that the reason to avoid them going forward is to prevent bugs. I will add proper built-in events for these uses you describe.

**Comment by nanashi88** [comment]
thank you very much.
btw, if you gonna add event for "REJECTED" I guess you gonna add it at the begining of function provider.reject()
then the event gonna be fired before the execution of rejection (specially Provider.pending.RemoveAt(i);)
then I would still have access to the target player at Provider.pending list from inside the event
then I don't need anymore to take copy of Provider.pending list at "VERIFY" phase.
so I won't need to catch "VERIFY" anymore :)

**Comment by Trojaner** [comment]
I think sending a copy of the buffer would be the best solution, I don't know any plugin that modifies it - and even if it did, it could cause desync issues.

**Comment by nanashi88** [comment]
about editing the Buffer, I have had an idea before ( haven't tried to implement it yet) which is to give the ability to not send Connected event to clients for specific steam account (admin account).
this way, this account will be hiden from all players (when admin connect with it, and cheat tools won't be able to see him ( because cheat tools like Egguware are able to detect admins in vanish!)
but this idea, has some challenging sides because a lot of events based on client index, and this might cause mismatch betweend cleints index at server vs at client side. (when new players connect)
still if this feature is very useful, because then it is not only the admin is hidden from cheat tools, he also hidden from players list

**Comment by nanashi88** [comment]
I guess this is too far away ... plz don't mind my silly ideas XD

**Comment by SDGNelson** [comment]
You are right that not sending information about an admin connection would cause problems for now. Maybe in the future it could be supported. IIRC the Rocket vanish mode sets the admin position outside the height limit, which cheats are probably detecting as "player outside the height limit = vanish".

**Comment by nanashi88** [comment]
here is Egguware code for detecting vanish:
`        void VanishPlayerWindow(int winid)
        {
            GUILayout.Space(0);
            foreach (SteamPlayer player in Provider.clients)
                if (Vector3.Distance(player.player.transform.position, Vector3.zero) < 10)
                    GUILayout.Label(player.playerID.characterName);
            GUI.DragWindow();
        }`

at our servers (and I think rocket do the same) we do vanish by:
`playerMovement.canAddSimulationResultsToUpdates = false;`
the problem that this option teleports admin to (0,0,0) (at not owner clients).
I wonder why, I haven't tried to go deep into this before.
btw, either using this method, or tpaing him outside map border, if they set ESP to max distance they will see him (not real location though)

**Comment by nanashi88** [comment]
Thank you very much for adding onRejectingPlayer and onBattlEyeKick :)
I have updated our module, so there is no need (for us) to use onServerWritingPacket.
but we still using onTriggerSend  (for reasons mentioned above)
so, is there an event to catch on player group change , and his new group id?

**Comment by SDGNelson** [comment]
Thank you for updating your code!
Yep, a static event was added for group change as well: `PlayerQuests.onGroupChanged` It includes the sender, old group, old rank, new group, and new rank.

**Comment by nanashi88** [comment]
awesome, thank you 👍

**Comment by nanashi88** [comment]
oh I see PlayerLife.onPlayerDied 
module is updated, I don't need to use onTriggerSend or onServerWritingPacket anymore
now testing time, I hope everything goes well
Nelson thank you very much for your support to module creators
