### ISSUE TITLE
Scrolling down in Devkit auto scrolls up

### ISSUE THREAD

**Issue by Ubetaro** [SmartlyDressedGames/Unturned-3.x-Community#1678]
https://i.imgur.com/DqeGpX9.gif

Any time I scroll down in the Devkit, it auto scrolls back up. Mouse is working fine.

**Comment by SDGNelson** [comment]
Do you run into the same problem with the main menu news scroll bar? Both are the "UGUI" built-in scroll views. I will mark this as next patch to see if there is are any settings discrepancies between them.

**Comment by Ubetaro** [comment]
> Do you run into the same problem with the main menu news scroll bar? Both are the "UGUI" built-in scroll views. I will mark this as next patch to see if there is are any settings discrepancies between them.

News scroll bar in the menu is perfectly fine. Problem exists only in the devkit editor.

**Comment by SDGNelson** [comment]
Thanks for the info. For the next update they should be setup more similarly. I will remove the "next patch" label, and hopefully it will work properly for you. Let me know how it goes!
