### ISSUE TITLE
make canteens/rain barrels more realistic and less annoying

### ISSUE THREAD

**Issue by ogbaba** [SmartlyDressedGames/Unturned-3.x-Community#1679]
Drinking the content of a 100L rainbarrel removes 35% thirst, lol.
Canteens should at least remove 50% thirst and rainbarrels should contain more than 1 water unit (water tanks should therefore be able to contain more water too) 👌

**Comment by Johnanater** [comment]
It makes sense if you're a HydroHomie

**Comment by Spebby** [comment]
It's the way that it is to prevent players from never leaving their base, all though players can easily just add more barrels. It's a balancing act. If nothing else we can infer that the Unturned player is one thirsty guy.

**Comment by SDGNelson** [comment]
Logically yes the rain barrels would contain more water, but as-is the low quantity is a reason to build multiple.

**Comment by ogbaba** [comment]
> Logically yes the rain barrels would contain more water, but as-is the low quantity is a reason to build multiple.

then make it fill only 20% after a rain and make 20% fill a single canteen
getting water is really not fun, it's not even realistic
