### ISSUE TITLE
My friend can't join my server.

### ISSUE THREAD

**Issue by jorenVDZ** [SmartlyDressedGames/Unturned-3.x-Community#168]
As the title says friends can't join my server. I opened all the ports (27015-27018) in my router and on my firewall. I can join with my loopback adress but my external ip doesnt seem to work.
Can someone help me to figure out what the problem is.

**Comment by Trojaner25** [comment]
Maybe your ISP uses CGN which means your IP is shared.

**Comment by jorenVDZ** [comment]
Is there any way to check and how do i fix it. Also maybe i should say that everything worked perfectly till last update.

**Comment by thereis** [comment]
Which plugins are you using?

**Comment by jorenVDZ** [comment]
Nope, but i were hosting the server on my friends pc. I also think i know whats causing the problem. My ISP lowered my internetspeed and i think that might have something to do with it. Tnx anyway.

**Comment by Torubloo** [comment]
GitHub issues is not for help related issues, it is code related, feel free to join the Unturned Official Discord @ http://unturned.chat and ask there it would also be much easier because it's a chat program and not just commenting

**Comment by Torubloo** [comment]
Why did they lower your internet speed? if it was because you went over a monthly limit of data, then you would have EXTREMELY slow speeds and that would be the problem

**Comment by Trojaner25** [comment]
No one asked yet..
Can you host other games or applications?
