### ISSUE TITLE
[BUG] Quest bug on the server

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#1683]
If there are objects in the quest that should disappear after completing the quest, then they do not completely disappear, leaving their own collider. As a result, it is impossible to go through them.

P.S. This problem is **only on the server**, in singleplayer everything works.

[Video on YouTube](https://www.youtube.com/watch?v=W9fAicCGgTM)

**Comment by SDGNelson** [comment]
This is intentional: collision can only be enabled or disabled for all players at once (unfortunately). In vanilla any per-player quest object has trigger colliders rather than blocking colliders.

**Comment by surv0013** [comment]
> 
> 
> This is intentional: collision can only be enabled or disabled for all players at once (unfortunately). In vanilla any per-player quest object has trigger colliders rather than blocking colliders.

Can I ask for a method to enable/disable an object for all players on the server?

**Comment by SDGNelson** [comment]
There are only a couple built-in conditions that are consistent between all players: in-game time of day and holiday events (e.g. halloween).
