### ISSUE TITLE
Include military assets in ExampleAssets.unitypackage

### ISSUE THREAD

**Issue by khakers** [SmartlyDressedGames/Unturned-3.x-Community#1685]
Recently I noticed that the example assets unitypackage doesn't include the Beret or any of the other military assets (barracks and other map colored things) that previously had their own package within the examples folder. It would be great if these could be included with the examples again with the next update.

**Comment by SDGNelson** [comment]
Sure thing. I will put them on the list for the next update. (quite a few requested assets will be added)

**Comment by SDGNelson** [comment]
It looks like the military buildings are already in the example assets, but some of the crates and the beret will be added

**Comment by khakers** [comment]
Turns out I was looking under medium instead of Large... Thanks for the inclusion!
