### ISSUE TITLE
Shutdown Event

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#1686]
Right now it looks like the Shutdown event is called too far down the stack to be useful and doesn't serve much purpose.
It would be nice if we had a shutdown event before any players were kicked, this would be really useful for plugins to save everything before shutdown.

**Comment by SDGNelson** [comment]
Taking a look I am not sure if there even is a shutdown event built-in. I will take care of this for the next update!

**Comment by rube200** [comment]
@SingleThreadedWorld 
You should save things also when the server is saved because if for some reason it crashes you lose everything, besides when shutdown is called the save is run automatically

**Comment by SingleThreadedWorld** [comment]
> @SingleThreadedWorld
> You should save things also when the server is saved because if for some reason it crashes you lose everything, besides when shutdown is called the save is run automatically

Thanks for your suggestion, I was looking to do something only on shutdown though, not on every save.

**Comment by SDGNelson** [comment]
This has been added in the next update: `Provider.onCommenceShutdown`
It will be called prior to disconnecting any players and the built-in shutdown code.
