### ISSUE TITLE
[FEATURE REQUEST] Add a working rangefinder for vehicle turrets

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1689]
You can attach a rangefinder to a gun, and it will work, but if you set this gun to a vehicle turret, the rangefinder wont work. Adding rangefinder for some vehicle turrets is important, especially for some artillery or tanks,

**Comment by Alex-Well** [comment]
We began to develop our own mechanics of artillery guns. By measuring the range of the projectile at different angles of inclination of the gun’s barrel, we can develop a system that can show how far the projectile will fall at the current incline. In the future, it is planned to transfer this distance to a certain coordinate plane represented by the UI and replacing a completely standard sight.
