### ISSUE TITLE
The ability to add a landscape from Unity to Unturned.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#169]
**Good afternoon**, I want to suggest a way to create a landscape in unity and add it to Unturned. I have so far carried out the test and added the landscape as the "Large" object.

I know that there is a regular editor and a deva kit, but the usual editor cuts the possibilities, and the whale deviants hang up at me and work in it is not convenient

**I conducted the test, and the conclusions are as follows:**
1. It's very convenient
2. The problem with the drawing distance (the relief is turned off at a distance of 500 meters, perhaps because I added it as an object).
3. Another problem is that when you place objects on it, the beam from the mouse is ignored by the landscape, and objects on it do not fit.
4. Placing materials and grass give me a lot of opportunity.

**I want to say that I can be wrong, but this opportunity would not be superfluous for those who know how to do something.**

**Sorry for my English.
Thank you for attention!**

![image](https://user-images.githubusercontent.com/32962870/34773504-409a3426-f64f-11e7-9895-ea7fecfbbb85.png)

**Comment by Trojaner25** [comment]
I dont think this is easy to do
The scripts you would add, the objects etc would probably conflict with Unturneds own system

**Comment by VitaxaRusModding** [comment]
Add a type for example "Terrain" and make it so that it does not disappear and everything.
Let everyone choose what suits him.

**Comment by SDGNelson** [comment]
Very few people would find this useful, so I'm not going to add it. One option if you want to use the Unity terrain tools: you could export your heightmap/splatmap from Unity and import them into Unturned.
