### ISSUE TITLE
Cursor For UI Effect Button

### ISSUE THREAD

**Issue by CapScroLL** [SmartlyDressedGames/Unturned-3.x-Community#1690]
I'm making clickable UI effect but I have to go to the menu with the "ESC" key to click the buttons ... Can we show the cursor without going to the menu?

**Comment by CyberAndrii** [comment]
```cs
player.enablePluginWidgetFlag(EPluginWidgetFlags.Modal)

player.disablePluginWidgetFlag(EPluginWidgetFlags.Modal)
```
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/788#issuecomment-557320373

**Comment by CapScroLL** [comment]
> ```cs
> player.enablePluginWidgetFlag(EPluginWidgetFlags.Modal)
> 
> // disable when closing UI
> player.disablePluginWidgetFlag(EPluginWidgetFlags.Modal)
> ```
> 
> [#788 (comment)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/788#issuecomment-557320373)

Thank you
