### ISSUE TITLE
[Bugs Found]

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1693]
1. On the skin: BONESPORT COMPOUND BOW with spikes in the center, polygons turned inward!

2. Switchable items do not update their status on the server! Flashlight, NVD and Headlamp, Tactical range finder, laser and Flashlight transmit information about switching on to other clients through the server, however, they do not update their own state on the server. This can be seen if you add a collider to a switchable GameObject. On the server, it will not turn on and off.
Perhaps this can be solved if you add a parameter for configuring items so that they are loaded on the server. It would be great if items equipped on the player were immersed on the server, be it weapons or a hat!

**Comment by SDGNelson** [comment]
1. Thanks for the report! I will adjust that mesh for the update.

2. You are correct that clothing and item prefabs are not instantiated (or even loaded) on the server. Having colliders on them in multiplayer would be problematic anyway because the server does not play their animations. What did you have in mind?

**Comment by Alex-Well** [comment]
I would use this as a switch that activated the functions processed by the server. For example, turn on and off the force field or the player’s teleport built into the item.
By the way, I even made a jetpack! True, it only works on the client. I really want to be able to load some prefabs on the server.

https://youtu.be/UGwH0my-Dqg

**Comment by SDGNelson** [comment]
Haha that is pretty creative! Off the top of my head the only per-player item prefab loaded on the server is the equipped weapon, so you might be able to do something with it. Otherwise the server tries to be relatively barebones.
