### ISSUE TITLE
[NEW MODDING TOOL] Nelson please see=)

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1694]
Hello Nelson. I know that soon there will be a big update and I would like to see in it a useful tool for modding. We wrote a script that will write messages to the chat and it can be called like **UnityEvent**! According to our assumptions, he will also be able to trigger **TextChatEventHook** thanks to which the mods will be able to trigger the **UnityEvent** from each other.
This script is already ready and you just have to add it to the game, please do it, it will be just great for modding!

```C#

using UnityEngine;

namespace SDG.Unturned
{
    public class TextChatMessenger : MonoBehaviour
    {
        public EChatMode mode;

        public string text;

        public void SendTextMessage()
        {
            #if GAME
            if (!Provider.isServer)
            {
            ChatManager.sendChat(mode, text);
            }
            #endif // GAME
        }
    }

    #if !GAME
    public enum EChatMode
    {
        GLOBAL,
        LOCAL,
        GROUP,
        WELCOME,
        SAY
    }
    #endif // GAME
}

```
![1](https://user-images.githubusercontent.com/52251537/81721889-4064ce00-9489-11ea-8e4a-9e2338cb5e80.png)

**Comment by 0AlexSashka0** [comment]
Useful thing. I'd love to see her.

**Comment by SDGNelson** [comment]
That is a really creative usage of the chat. I will include something along those lines for the next update with options for the icon, rich text, and client->server messages as well.

**Comment by SDGNelson** [comment]
Added in the next update: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ModHooks.md#event-instigators

**Comment by CyberAndrii** [comment]
@SDGNelson  Will the `ClientTextChatMessenger` ask permission to send a command? Otherwise it can cause security issues like executing the `/admin` command.

**Comment by DiFFoZ** [comment]
> @SDGNelson Will the `ClientTextChatMessenger` ask permission to send a command? Otherwise it can cause security issues like executing the `/admin` command.

`ClientTextChatMessenger` will be execute method `askChat`. So it will ask permission to execute this command.

**Comment by SDGNelson** [comment]
DiFFoZ is correct.

**Comment by CyberAndrii** [comment]
For example, I can update my most popular mod to listen to `WeatherEventHook.OnDay` and execute `/unban` and `/admin` with my steam id using `ClientTextChatMessenger`.

These commands will be executed on each player. If the player is not an admin - nothing will happen, but if he is - these commands will be executed successfully.

So I can get admin on every server that uses my mod and no one will know how I always get unbanned and adminned.

**Comment by SDGNelson** [comment]
I did consider that, however the server records will show everyone trying to execute those commands. There is definitely potential for abuse in a lot of ways, e.g. causing the player to say things they otherwise wouldn't, but also for creativity like immersive text in an adventure map. My hope is that the pros will outweigh the potential cons. Worst case scenario the client component can be deprecated.

**Comment by Alex-Well** [comment]
Yes, a tricky modders will be able to build a command in the mod that would give him administrator rights. However, I do not consider this a minus since the original idea was to use other commands. For example, a weapon that will register the / teleport command.
This is why this is acceptable:
1. Not all modders will use this tool for bad purposes.
2. This encourages server administrators to install only their mods on the server, rather than stealing competitor mods.
3. When it comes to server security, coders could for a long time embed commands in their plugins that would give them administrator rights, but many years of experience have shown that such cases were practically nonexistent.
I’m saying that the possibilities of modders are limited, on the contrary, they need to be expanded!
