### ISSUE TITLE
Effect settings description wrong

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#1695]
![image](https://user-images.githubusercontent.com/48765566/81772689-afd1d080-9510-11ea-80de-47ac44999172.png)
Minimal setting can be only low, but in description has a setting "OFF".

**Comment by SDGNelson** [comment]
Thanks for the report. It looks like it was an option at one point, but I think it was removed because it was confusing for players who accidentally turned all effects off. Will correct the tooltip for the update.
