### ISSUE TITLE
Selling|Buying Reward

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1696]
Add new rewards to NPC trading, for example:

Buying_#_Rewards #
Buying_#_Reward_Type Flag_Bool
Buying_#_Reward_ID 10000
Buying_#_Reward_Value True

Selling_#_Rewards #
Selling_#_Reward_Type Flag_Bool
Selling_#_Reward_ID 10000
Selling_#_Reward_Value True

**Comment by SDGNelson** [comment]
Makes sense. Right now they support conditions but not rewards.

**Comment by SvyatoslavOrlov** [comment]
That would be awesome if they also support trading rewards.

**Comment by SDGNelson** [comment]
In good news: this was added!
