### ISSUE TITLE
[NEW MODDING TOOL] Nelson, we have another cool idea!

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1697]
Hello Nelson. I suggest adding another useful modding tool. This is an **AnimationEventHook** that can be added to _Item, Vest, Hat, Mask, Glasses, Bacpack,_ and will call **UnityEvent** during the specified animation the character is playing. Thanks to this, it will be possible to do amazing things, for example, replace the model of a melee weapon during an enhanced attack or play the animation of a gun during its reload, activate different effects of clothes during running, and much much more.
The script is already written by us and you just have to add it to the game, however you will have to add a small piece of code to **PlayerAnimator** so that it triggers the **Event**, we also wrote it for you. Please add this and many modders will be grateful to you!

AnimationEventHook:

```c#

using UnityEngine;
using UnityEngine.Events;

namespace SDG.Unturned
{
    public class AnimationEventHook : MonoBehaviour
    {
        public EAnimationType Animation;

        public UnityEvent OnPlay;

        protected bool isListening;

        #if GAME
        protected void OnEnable()
        {
            if (!isListening)
            {
                var animator = GetComponentInParent<PlayerAnimator>();
                if (animator)
                {
                    animator.onAnimated += OnAnimationPlay;
                    isListening = true;
                }
            }
        }

        protected void OnDisable()
        {
            if (isListening)
            {
                var animator = GetComponentInParent<PlayerAnimator>();
                if (animator)
                {
                    animator.onAnimated -= OnAnimationPlay;
                    isListening = false;
                }
            }
        }
        #endif // GAME

        public void OnAnimationPlay(string name)
        {
            if (name == Animation.ToString())
            {
                OnPlay.Invoke();
            }
        }

        public enum EAnimationType
        {
            Equip,
            Use,
            Aid,
            Inspect,
            Weak,
            Strong,
            Start_Swing,
            Stop_Swing,
            Aim_Start,
            Aim_Stop,
            Attach_Start,
            Attach_Stop,
            Hammer,
            Reload,
            Scope,
            Sprint_Start,
            Sprint_Stop,
            Idle_Stand,
            Idle_Crouch,
            Idle_Prone,
            Move_Walk,
            Move_Run,
            Move_Prone,
            Move_Crouch,
            Gesture_Arrest,
            Gesture_Pickup,
            Punch_Left,
            Punch_Right,
            Idle_Climb,
            Idle_Swim,
            Move_Climb,
            Move_Swim,
            Idle_Sit,
            Idle_Drive,
            Gesture_Surrender,
            Gesture_Point,
            Gesture_Wave,
            Idle_Zip,
            Gesture_Salute,
            Gesture_Inventory,
            Gesture_Rest,
            GestureFacepalm,
            Idle_reclined,
            Idle_Bicycle
        }
    }
}

```

PlayerAnimator Code snippet:

```c#
public void play(string name, bool smooth)
		{
			bool flag = false;
			if (this.firstAnimator != null)
			{
				flag |= this.firstAnimator.play(name, smooth);
			}
			if (this.thirdAnimator != null)
			{
				flag |= this.thirdAnimator.play(name, smooth);
			}
			if (this.characterAnimator != null)
			{
				flag |= this.characterAnimator.play(name, smooth);
			}
			if (flag && this.gesture != EPlayerGesture.NONE)
			{
				this._gesture = EPlayerGesture.NONE;
			}
			onAnimated?.Invoke(name);
		}
		
public Animated onAnimated;

public delegate void Animated(string name);

```
![2](https://user-images.githubusercontent.com/52251537/81832380-1a9dfe80-9547-11ea-8b34-e70ce00ccbed.png)

**Comment by Bulka148** [comment]
It really can be useful for people who make mode

**Comment by Letomaniy** [comment]
bullshit

**Comment by SDGNelson** [comment]
It could have some interesting possibilities, but this one is less likely to be added. The item prefab is shared between world drops, icons, storage, etc so the component would spawn and run in all those cases unnecessarily. Not to mention that it would not be instantiated on the server. I will think about if there is a straightforward approach.

**Comment by Alex-Well** [comment]
@SDGNelson 
According to our assumptions, EventHook will be activated only for those prefabs that are equipped with a character or are in his hands.

**Comment by GazziFX** [comment]
> the component would spawn and run in all those cases unnecessarily

Only player prefab contains PlayerAnimator component that means it can be only used if AnimationEventHook is child of player. You can do smth additional to this script, for example:

```c#
void Start()
{
    if (!GetComponentInParent<PlayerAnimator>())
    {
        UnityEngine.Object.DestroyImmediate(this);
    }
}
```

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
