### ISSUE TITLE
[FEATURE REQUEST] Spy full desktop

### ISSUE THREAD

**Issue by Erkan53** [SmartlyDressedGames/Unturned-3.x-Community#1702]
It will be easier to find people if they are using hacks
/spy will capture full desktop but it will shrink to unturned's size so it will show only the game
because most of the unturned hacks doesnt show up on spy it shows up like normal

someone was called a hacker on my server when i asked him to share his full desktop then play unturned he closed unturned then tried to screen share

**Comment by SDGNelson** [comment]
Capturing the desktop would be a privacy concern. For example, if banking details were open above the game window.
