### ISSUE TITLE
Issue with storages

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1705]
When I enter one storage (ex, locker) and close it - I can't access another locker or any other virtual storage. Any ideas what this might be related to? It seems like only UI disappears when I close it but player is still in locker somehow because when I try to access virtual storage (ex, vault) after closing locker - it gives me error "can't access vault while using other storage"

**Comment by SDGNelson** [comment]
Hmm this is probably due to the rate limiting changes. Walking 20m away from the locker will close it server-side as a temporary workaround. I will make sure that opening a new storage cleans up the old storage / closes it.

**Comment by SDGNelson** [comment]
The 3.20.5.1 patch is released and should have resolved this problem, along with the asset bundle hashing and some minor camera issues.
