### ISSUE TITLE
Cannot equip items

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#1707]
Cannot get items in hands. Equip does nothing

Tested on server without plugins with updated rocketmod.

**Comment by aman7** [comment]
well same happening with me

**Comment by Gsechs** [comment]
Can confirm, a handful of my players are experiencing this issue on all servers (including servers that aren't mine). 

She however was able to equip items in singleplayer.

**Comment by DiFFoZ** [comment]
Maybe wrong hash on Client or Server?

**Comment by SDGNelson** [comment]
This was a stupid oversight on my part. The asset bundles are different per-platform so hashing is causing issues e.g. windows client on linux server. This hashing will be disabled in the patch soon.

**Comment by SDGNelson** [comment]
The 3.20.5.1 patch is released and should have resolved this problem, along with storage rate limits and some minor camera issues.
