### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1708]
Support for server and client modules.
I don't know how battleye works, but for example if a server had a module that was a client or server-client, the server should send the module to the client and then ask battleEye to add it to the "whitelist" through hash, this will allow customers to have battleEye modules provided by the server. (Again I don't know how battleye works and I don't know if this can be possible)

In case the player goes to another server with this module disabled or that the server does not use, he would be forced to restart the game.

**Comment by SDGNelson** [comment]
Unfortunately as you say this is not possible with BattlEye. Client module auto-install is also unlikely to be added because they are not sandboxed.
