### ISSUE TITLE
Tabbing Freezes Game On Main Menu

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1709]
Quite a weird bug as I don't really know how it works but it never happened before. When I tab out of unturned to restart my servers for example and then tab back in the mouse doesn't move and the game seems frozen. It seems you have to be tabbed out for at least 1minute as tabbing quickly between doesn't seem to cause any issue.

**Comment by SDGNelson** [comment]
Gave this a try with borderless and exclusive fullscreen modes. Waited 1min+ but no luck. Did it happen to you multiple times? If you can attach the `Client.log` file after it happens I will take a look.

**Comment by Bradler26** [comment]
Yeh its happened a few times now. Client.log doesn't seem to show anything from what I can see but ill send it anyways. It *May* be caused by the server shutting down and forgetting to click confirm on the new popup but I'll send more info when it happens again 
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4636874/Client_Prev.log)

**Comment by SDGNelson** [comment]
So the popup is stuck but you cannot click the confirm button?

**Comment by Bradler26** [comment]
That happened at one stage and then the other time my mouse was just stuck on the home menu.

**Comment by SDGNelson** [comment]
Bizarre, we will see if anyone else reports anything similar to go off of.

**Comment by Bradler26** [comment]
Happened again. This time it took a good ~5min. The order that I followed was

Booted
Attempted to join my server
Got rejected due to wrong steam version
tabbed out to update servers and then tabbed back in and was frozen.

Sorry if this info isn't very helpful but I can't really think of anything else that would even cause it.

**Comment by Bradler26** [comment]
After the latest bug fix I haven't experienced this anymore.
