### ISSUE TITLE
Removal of Stat Track counters from skins

### ISSUE THREAD

**Issue by ChubbyQuokka** [SmartlyDressedGames/Unturned-3.x-Community#171]
This is not an issue, I just didn't know where else to post this.

I think it would be a good idea if users were allowed to remove the Stat Track additions to skins after they've been added, just in-case someone adds it to the wrong gun or doesn't like the way it looks.

**Comment by SDGNelson** [comment]
At the moment I don't think this will be added, as stat counters help to provide an item sink in the economy.
