### ISSUE TITLE
Left mouse button bug still exists 

### ISSUE THREAD

**Issue by KennysBoat** [SmartlyDressedGames/Unturned-3.x-Community#1710]
When I hit LMB i still move left.

**Comment by KennysBoat** [comment]
I also cannot move things in my inventory.

**Comment by SDGNelson** [comment]
Do you have LMB bound to move left? In the controls settings the movement keys can be rebound, and if move left was accidentally clicked twice it may have been bound to move left.

**Comment by KennysBoat** [comment]
Yeah I did. I just thought to check that and tell the forum I found what was wrong.
