### ISSUE TITLE
Map Objects [And Editor]

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1712]
When I start the server and load the map, I get errors of this type:
BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "FANYPLAY/Objects/42101/Nav"

Or such:
Object with no asset in region 28, 28: 14003 Office_4 3b7b7dbc-01b8-4acc-804e-e50277958d01

But these modifications have long been missing or they do not work, but I can not remove them. For example, you can create a window with a hierarchy of objects where you can search for supplied objects by ID or GUID.

I apologize for using the translator :3

**Comment by SDGNelson** [comment]
The box collider warning is annoying and unfortunately cannot be disabled, but should not be a problem.

If you definitely want to delete the missing assets you can run the game with `-NoPreserveMissingObjects` launch option and re-save the map.

**Comment by FANYPLAYRU** [comment]
Thanks.
And another question, when the player logs in, the following error occurs:

DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
 
(Filename:  Line: 543)
 
Connecting: PlayerID: 76561198857499447 Name: FANYPLAY Character: [Полиция]Андрей Волк[Глава]
[Полиция]Андрей Волк[Глава] connected with IP 95.32.130.196 from Russia

I don't know exactly what it's about, but it's also annoying and may cause objects to break.
And they break very strangely!
They seem to change places and if for example to pick up a lamp, then the hands are taken for example a table or the like. Or it is not taken at all due to the fact that the object does not belong to the player (the Objects just change places under the guise of others)

**Comment by SDGNelson** [comment]
That error is related to using an old version of RocketMod. You should update to the officially maintained version from the Extras directory.

**Comment by FANYPLAYRU** [comment]
Ok. Thanks.

**Comment by FANYPLAYRU** [comment]
DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
 
(Filename:  Line: 543)
 
Connecting: PlayerID: 76561198857499447 Name: FANYPLAY Character: [Полиция]Андрей Волк[Глава]



This is after updating the RocketMod [Extras]

**Comment by SDGNelson** [comment]
Thanks for updating your RocketMod installation. It must be a plugin calling DontDestroyOnLoad then. Updating RocketMod to v4.9.3.1 will have removed some of those calls because its player component was calling DontDestroyOnLoad improperly (fixed in the 4.9.3.1 you installed), but there may be plugins using it incorrectly. Either way it should not have any negative side effects fortunately.
