### ISSUE TITLE
Fallback handler could not load library [Help please]

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1714]
When a plugin or rocket is loaded this appears:

Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library Unturned_Headless_Data/Mono/advapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.so
Fallback handler could not load library Unturned_Headless_Data/Mono/advapi32
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library Unturned_Headless_Data/Mono/advapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.so
Fallback handler could not load library Unturned_Headless_Data/Mono/advapi32
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library Unturned_Headless_Data/Mono/libadvapi32.dll

And this:

Fallback handler could not load library Unturned_Headless_Data/Mono/data-0x5596898675b0.so
Fallback handler could not load library Unturned_Headless_Data/Mono/data-0x55968979af10.so

How can I fix this?

**Comment by Trojaner** [comment]
These arent errors you can just ignore them

**Comment by FANYPLAYRU** [comment]
I don't know much about C# and I don't know if it's important or not.

**Comment by Gicminos** [comment]
What's the cause of this? Is there a way to prevent to show it if it is not an issue?
