### ISSUE TITLE
Vehicle underwater sound bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1716]
[![](http://img.youtube.com/vi/-ZFq6gqs3c8/0.jpg)](http://www.youtube.com/watch?v=-ZFq6gqs3c8"")

**Comment by SDGNelson** [comment]
Hmm it might be a plugin trying to change stances or something, but I will take a look for the patch. Thanks for the report!

**Comment by TH3AL3X** [comment]
I don't think, cuz i already tested without plugins

**Comment by SDGNelson** [comment]
Thank you for bringing this to my attention! It should be fixed in the .2 patch on Monday.
