### ISSUE TITLE
Web Console

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1718]
After updating the mod to the version of Nelson, the web console stopped working, before that I used the latest version of the mod from the mod developers themselves.
Is there any way to fix this?
The servername.console file has stopped working and commands are not sent to the server.

I apologize for using the translator!

**Comment by SDGNelson** [comment]
The servername.console file is written by the very old "RocketLauncher.exe". Your web console could be adjusted to read the Logs/Server_servername.log file perhaps? Alternatively a custom implementation of IConsoleInputOutput could be written for complete control from a web console. As for the commands: how are they passed to the server? Nothing there changed I think

**Comment by FANYPLAYRU** [comment]
It used to work, but the host did not find any methods other than RCON, and I can't use RCON because it is busy with the plugin and other users must also have access to the console, and knowing the password to RCON can do harm.

**Comment by FANYPLAYRU** [comment]
If I install the old version, the console will work, but some commands will be output with an error. The error indicates that this command is only for use by the player on the server.

**Comment by SDGNelson** [comment]
Is it an RCON plugin? There is no built-in RCON implementation (yet). It sounds like their command executor needs to pass the steamID of the player executing the command.

**Comment by FANYPLAYRU** [comment]
Rocket Mod has RCON, but before your fix, the web console was working, and now it doesn't work. Even when I put the old Rocket Mod the console works, but the Rocket Mod itself does not work correctly (old).
Your Rocket Mod works correctly but without the necessary functions.

I can throw off the version where the web console works

**Comment by SDGNelson** [comment]
What works incorrectly when using the old Rocket?

I will prioritize implementing official RCON support so that the Rocket one is not required.

**Comment by FANYPLAYRU** [comment]
In the old Rocket Mod does not work a lot of things, although I have a fix but it also broke.
If you go to the game and the server, all the commands work and work correctly, and you can use the console to register shutdown and bans, and the other gives an error:

Plugin(s) using unsafe onTriggerReceive, please consider an alternative
An error occured while executing ban [76561198964191292, Test]: System.NotSupportedException: This function should only be called from the game thread. (e.g. from Unity's Update)
  at SDG.Unturned.ThreadUtil.assertIsGameThread () [0x0000c] in <e212057839f3481c9bf390f0168cfcd0>:0 
  at SDG.Unturned.Provider.ban (Steamworks.CSteamID steamID, System.String reason, System.UInt32 duration) [0x00000] in <e212057839f3481c9bf390f0168cfcd0>:0 
  at SDG.Unturned.SteamBlacklist.ban (Steamworks.CSteamID playerID, System.UInt32 ip, Steamworks.CSteamID judgeID, System.String reason, System.UInt32 duration) [0x00000] in <e212057839f3481c9bf390f0168cfcd0>:0 
  at SDG.Unturned.Provider.requestBanPlayer (Steamworks.CSteamID instigator, Steamworks.CSteamID playerToBan, System.UInt32 ipToBan, System.String reason, System.UInt32 duration) [0x00031] in <e212057839f3481c9bf390f0168cfcd0>:0 
  at SDG.Unturned.CommandBan.execute (Steamworks.CSteamID executorID, System.String parameter) [0x000e8] in <e212057839f3481c9bf390f0168cfcd0>:0 
  at SDG.Unturned.Command.check (Steamworks.CSteamID executorID, System.String method, System.String parameter) [0x00018] in <e212057839f3481c9bf390f0168cfcd0>:0 
  at Rocket.Unturned.Commands.UnturnedCommands+UnturnedVanillaCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x0004c] in <d97a7b6e07e84732934032fc52b1dcfa>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <42b9432d1ede4060ab7b64e73c43b05c>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x00176] in <42b9432d1ede4060ab7b64e73c43b05c>:0

The commands do not work if they return a similar error.
I don't know if this can be fixed.

**Comment by SDGNelson** [comment]
Ah, that is one of the reasons to use the newer versions: the old versions of RocketMod are unsafely executing commands on other threads.

**Comment by FANYPLAYRU** [comment]
So the console doesn't work in the new Rocket Mod

**Comment by SDGNelson** [comment]
The console does work in the latest version of RocketMod, but there is no official RCON support yet

**Comment by FANYPLAYRU** [comment]
I don't need RCON (I don't speak for everyone). I need the old Web console support, like in the old Rocket Mod

**Comment by Trojaner** [comment]
You can create webconsoles with RCON. I don't know what software you use for web consoles, but they abused the console file of RocketMod which was only meant for the launcher.

**Comment by FANYPLAYRU** [comment]
Я не могу использовать RCON по многим причинам, от того что это использует плагин до того что это не безопасно.

**Comment by FANYPLAYRU** [comment]
I can't use RCON for many reasons, from the fact that it uses a plugin to the fact that it's not secure.

**Comment by FANYPLAYRU** [comment]
Is it possible to return the old web console?

**Comment by FANYPLAYRU** [comment]
> Ah, that is one of the reasons to use the newer versions: the old versions of RocketMod are unsafely executing commands on other threads.

Is there any way to return this method?

**Comment by SDGNelson** [comment]
Your web console could be updated in one of the ways described earlier (reading the .log files instead of RocketLauncher's .console file, or implementing ICommandInputOutput). The older versions of RocketMod have multiple issues like the multithreading described, so they are not an option if you want to execute commands.

**Comment by FANYPLAYRU** [comment]
Well. Can you tell me what was responsible for this? So that we can return this plugin, thank you in advance.

**Comment by SDGNelson** [comment]
Responsible for which?

By returning the plugin do you mean that a plugin store sold you this web console plugin? It should be relatively straightforward for the developer to adjust the plugin to work properly.

**Comment by FANYPLAYRU** [comment]
No, it used to be in the Rocket Mod itself, but in the new one we don't know what was removed, and if we know what you removed, we can return it using the plugin.

**Comment by SDGNelson** [comment]
If you want to add the web console yourself using a plugin then you should definitely do it by implementing the intended interface: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/CommandIO.md

For the patch I will also add the ability to have multiple simultaneous implementations in order to allow external web console at the same time as the default console.

**Comment by FANYPLAYRU** [comment]
Well, what was responsible for multithreaded mode?
I would like to return the old method as it is more convenient

**Comment by FANYPLAYRU** [comment]
Are there any examples of using Command IO in Unturned?

**Comment by SDGNelson** [comment]
`ConsoleInputOutputBase` has a simple implementation as a point of reference. `ThreadedConsoleInputOutput` is the default on Windows and will soon be the default on Linux.
