### ISSUE TITLE
[BUG] Post Processing in First and Third person is different

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1720]
Obvious when staring at the sun

**Comment by BREEZEXPVP** [comment]
Yes. Pretty shure that First person  Post Processing Bloom Effect is not equal  to the Third person  view.
Nelson should make them use same post Post Processing profile , if that doesnt help add option like the new ambient occlusion one , to enable & disable bloom effect fps view.

**nelson please fix :).**

here is some obvious results
FPS Post Processing :
![20200516103522_1](https://user-images.githubusercontent.com/40163506/82115276-0a15a000-9762-11ea-9076-a1f368f88b08.jpg)
TPS Post Processing :
![20200516103530_1](https://user-images.githubusercontent.com/40163506/82115279-0da92700-9762-11ea-94ee-9bc6c76a4f9c.jpg)
FPS Post Processing :
![20200516103602_1](https://user-images.githubusercontent.com/40163506/82115287-1568cb80-9762-11ea-95bc-b9f5a6d77d57.jpg)
TPS Post Processing :
![20200516103609_1](https://user-images.githubusercontent.com/40163506/82115290-18fc5280-9762-11ea-9143-63eb39356289.jpg)

**Comment by TH3AL3X** [comment]
What do you mean, it's the same

**Comment by SDGNelson** [comment]
Thanks for the report. The third-person bloom must not be getting disabled while in first-person. Will fix in the patch.

**Comment by SDGNelson** [comment]
My suspicion is that the 1st-person effect is blooming the clamped final color when compositing the 1st and 3rd person cameras, whereas the 3rd-person effect has the full emissive color. I don't want to get into a big mess of adjusting how the post-processing effects work internally, so the 3rd-person bloom intensity is now reduced in 1st-person to be more consistent instead. After the patch it is mostly just noticeable with the sun shafts enabled.
