### ISSUE TITLE
[BUG] Custom Weather events cause weird issues when returning to the main menu/loading another map

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1722]
Loaded the example weather event on a custom test map, then started rain, returned to the main menu and the sky was white. Loaded into another map, and it wasn't raining, but weather event hooks for rain was activated.

Was on forward rendering.

**Comment by SDGNelson** [comment]
Thanks for the report. This feature is still WIP (e.g. it is not hooked up to the weather event timer yet), but should get some more improvements in the next update.

**Comment by SDGNelson** [comment]
The custom weather improvements won't be in the next update yet, but this skybox fog bug will be fixed in the next update.
