### ISSUE TITLE
[QUESTION] Masterbundle doesn't compress audio files?

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1723]
Well, new stereo rework is good and useful, it finally works, but masterbundle created to unite and compress files, yes? So why it doesn't compress audio files?

**Comment by GazziFX** [comment]
In import settings of audio file has compression property

**Comment by NoThreat** [comment]
It is, but masterbundle don't optimize them. The same size from Unity. This should be like this?

**Comment by GazziFX** [comment]
Maybe your audio already compressed or have high entropy

**Comment by NoThreat** [comment]
I mean, standart mod, for example, shirts can be compressed and optimized by masterbundle into ~0,3MB. Why this doesn't happen with pure audio files?

**Comment by SDGNelson** [comment]
By default Unity asset bundles use LZMA compression, and the data exported by Unity (should?) be packaged in a per-platform optimized format. 🤷‍♂️
