### ISSUE TITLE
 [FEATURE] Remove or add ability to disable echo when leave Ambience Volumes

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1727]
Sometimes it's annoying and it causes unpleasant cases, I think will be good to disable it or even config.

**Comment by SDGNelson** [comment]
Can you clarify? I don't think the effect node / ambiance volume create an audio revert component.

**Comment by NoThreat** [comment]
You can even check default game sounds, for example I took Wrench effect. Simple effect with linear rolloff. How it works:

When you enter volume - increasing echo
When you are in volume N time - strait sound
When you leave volume - decreasing echo

In editor no echo were found.

Here is the video: https://youtu.be/p0CvwcK288M

**Comment by SDGNelson** [comment]
Can you make the video public or unlisted? It is private right now.
The audio is played on a 2D audio source without any special effects. Are you sure you do not have a reverb component, maybe on one of your objects? For Easter Island they placed some reverb components which might be in your map.

**Comment by NoThreat** [comment]
Sorry about it, check video again. I was checking this thing on Destruction map. There are no something like reverb.
https://youtu.be/p0CvwcK288M

**Comment by SDGNelson** [comment]
Listening to the video I do not hear any reverb? The audio is repeating because the audio source loops the clip. Did you want to disable looping?

**Comment by NoThreat** [comment]
I want to remove this echo effect when enter and leave zone. Because sound itself don't have this feature. Or I just don't understand something?

**Comment by SDGNelson** [comment]
Ah the volume fading in and out. I think it would be jarring without any fading whatsoever. What sort of effect do you have in mind?

**Comment by NoThreat** [comment]
Simple sound effects, linear rolloff

**Comment by SDGNelson** [comment]
For a simple 3D sound effect it would be easier to put your own audio source on an object. The ambiance thing is intended for a single global 2D audio clip.

**Comment by NoThreat** [comment]
But it's more simple to use in big amounts and easier to config, got some disappointment, by the way, thanks for spending time on me.

**Comment by SDGNelson** [comment]
What about how the Germany waterfalls are setup? They are effects so you can config multiple in the level editor.

**Comment by NoThreat** [comment]
I don't like Effect volumes because they have strange configuration and it is not useful to make ambient, for example, on different floors, which placed above and down.
