### ISSUE TITLE
Tactical laser and light not pointing to the correct direction when you go into the attachments menu

### ISSUE THREAD

**Issue by AwesomeGOAT** [SmartlyDressedGames/Unturned-3.x-Community#1729]
![20200517130408_1](https://user-images.githubusercontent.com/57503102/82154942-44a13a80-983f-11ea-8c90-d45558ffd47a.jpg)
![20200517130347_1](https://user-images.githubusercontent.com/57503102/82154948-4d920c00-983f-11ea-9a7e-3a8025655bba.jpg)
The light and laser are not pointing to the correct direction. It would be pretty cool if they change directions when you go into attachments menu or inspecting the gun.

**Comment by SDGNelson** [comment]
In Unturned II the laser and light follow the model, and this approach might make its way back into Unturned at some point. Closing to reduce the number of active issues however.
