### ISSUE TITLE
Queue stuck problem.. again..

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#173]
Facing queue problems again. First login smooth, then disconnected and some weird sh** started when trying to log to my server. Stuck on queue position "lightning". Queue position changing randomly from 1 to 154 all over again. Some servers face tons of errors in console, commands not working etc. Waiting for fix

**Comment by thereis** [comment]
You can expect a new different issue every friday...

**Comment by N1GHTPATROL** [comment]
Even better:
![image](https://user-images.githubusercontent.com/7349712/34899830-3efa8fc8-f7c9-11e7-824b-3667a66d40da.png)

Many servers including mine are faced with this error which clearing the barricades.dat file (rip) fixes. Completely unacceptable, at this point each update does more harm then good, considering last week's update took over a day to fix.

**Comment by Hexadec1ma1** [comment]
Looks like this was the error message when the bug where you're stuck in the queue happens: 
![unknownerror](https://user-images.githubusercontent.com/32914055/34900338-0e155c7c-f7cd-11e7-8214-a22713cc861e.PNG)
Not sure if the latest update fixed it or not, still waiting on everything to update

**Comment by baranmod** [comment]
indeed. Changing the map or (probably) clearing barricades.dat will fix. But forced partial wipes for like majority of servers as a fix? Well, thats a bit of a fail speaking lightly :D

**Comment by baranmod** [comment]
ohhh god... Now everything would be like ok. Server not showing on servers browser list tho...

**Comment by Trojaner25** [comment]
#176

**Comment by Trojaner25** [comment]
After deleting the barricades.dat, does the problem occur again after some time?
If not, I would suggest closing the issue.

**Comment by SDGNelson** [comment]
Forgot to respond day-of, but it should have been addressed in the patch. This update took care of some bigger serverside changes, so the foreseeable future should not have any similar server issues following the patches.
