### ISSUE TITLE
EDamageOrigin vehicles "Vehicle_Collision_Self_Damage" bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1730]
damageOrigin "Vehicle_Collision_Self_Damage" it's not working fine, when you hit an animal or person or a zombie the function is activated, which should not be, since it means that when the vehicle is damaged when you hit something, check it please

**Comment by SDGNelson** [comment]
Vehicles taking damage during all collisions is intentional. Is that the question?

**Comment by TH3AL3X** [comment]
I mean, when u hit a zombie or a animal is doing this event, "Vehicle_Collision_Self_Damage"
And you need to fix that, because is when you crash the vehicle and get damage

**Comment by SDGNelson** [comment]
Yes: hitting animals, players, zombies, trees, objects, etc all cause crash damage of type `Vehicle_Collision_Self_Damage`.

**Comment by TH3AL3X** [comment]
But, "SELF DAMAGE", when you hit a zombie or a player doesn't get hurt the vehicle

**Comment by TH3AL3X** [comment]
For example i did this plugin, and is working fine, but the problem is "Vehicle_Collision_Self_Damage" when i crash to a player with the car is doing that event by no reasons, when the event say "Selft damage" [![](http://img.youtube.com/vi/_QsJbH93VFY/0.jpg)](http://www.youtube.com/watch?v=_QsJbH93VFY"")

**Comment by SDGNelson** [comment]
The reason it does that event when you crash into a player is that the vehicle takes 2 damage from player collisions.

Are you trying to handle world collisions different from the other collisions? Right now there would not be a great way to do that, but one option could do is spawning a custom component on the bumper to listen for collisions. It would just need to implement `void OnTriggerEnter(Collider other)`
