### ISSUE TITLE
Confirm button when you connect to a server

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1733]
[![](http://img.youtube.com/vi/qJkCTp2wuCg/0.jpg)](http://www.youtube.com/watch?v=qJkCTp2wuCg"")

Confirm button should be cancel button, and it's not working when you click it, can't cancel the action

**Comment by SDGNelson** [comment]
This has been changed in the .2 patch actually: #1717
