### ISSUE TITLE
[BUG] Server Kick Confirm Button

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#1736]
I use on my server the /exit command to leave it, the command basically kicks you from the server with the reason : You exited. And I noticed something strange recently 
![Bug](https://user-images.githubusercontent.com/48290038/82388312-52a1b780-9a07-11ea-8e34-1057ea8b3215.png)

The confirm button had no text in it.

**Comment by WW-TC** [comment]
Here's what one of my members got when I kicked him for testing.

![Bug2](https://user-images.githubusercontent.com/48290038/82388808-7adde600-9a08-11ea-8a85-d28e2600fa4d.png)

**Comment by Alex-Well** [comment]
I confirm, I also met this problem. Most likely this is due to the fact that the game did not register the exit from the server in the standard way through the Exit button.

**Comment by SDGNelson** [comment]
Thanks for the report. It turns out the dismiss button is getting re-created after the connection alert. Will fix for the next patch.

**Comment by SDGNelson** [comment]
Should be fixed in the .4 patch early next week.
