### ISSUE TITLE
Sun Rays from 1-st and 3-rd person are different

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1738]
Something strange happened after update. Lightning is different. Especially sun rays. Works on every map.
![20200520195743_1](https://user-images.githubusercontent.com/59829274/82474763-34ee5400-9ad4-11ea-95e6-7b32953dbb8c.jpg)
![20200520195745_1](https://user-images.githubusercontent.com/59829274/82474770-36b81780-9ad4-11ea-9300-fbeb72e12432.jpg)

**Comment by SDGNelson** [comment]
IIRC this was fixed in the patch after that update
