### ISSUE TITLE
I found a Bug and i have video 

### ISSUE THREAD

**Issue by SavageWraith** [SmartlyDressedGames/Unturned-3.x-Community#1739]
my discord Savage Wraith#0559
or my steam https://steamcommunity.com/profiles/76561198448460684/

https://youtu.be/wonGZQjyy5s

**Comment by TH3AL3X** [comment]
Welcome to unturned, nelson can fix that in few seconds....

**Comment by SDGNelson** [comment]
In 3rd-person view your bullets aim toward your crosshair, but still originate from your head. (otherwise it would be impossible to hit anything) It can result in some wacky angles like this, but I think it is preferable rather than shooting straight ahead in that case.
