### ISSUE TITLE
AoE Kills from Explosive Magazine Attachments not Counted as Kills

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#174]
Killing a zombie, animal, or player via an explosive magazine attachment does not register on the tracked kills. This may apply to any explosive ranged weapon in general, although I have not tested that.

**Comment by aviadmini** [comment]
It's registered as splash damage from server :(

**Comment by aviadmini** [comment]
No I was wrong, it's registered as splash damage from killer. Guess it's just tracking issue
