### ISSUE TITLE
Something is wrong with view model

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1740]
Stuck while i put the camera on thirdperson and i put my mouse up
[![](http://img.youtube.com/vi/fDxOGPX8CV8/0.jpg)](http://www.youtube.com/watch?v=fDxOGPX8CV8"")

**Comment by SDGNelson** [comment]
It seems to happen occasionally on a few surfaces - my guess is that the camera starts too low while prone. I will adjust for the next patch.
