### ISSUE TITLE
Bug Video Player

### ISSUE THREAD

**Issue by SrZanahorio** [SmartlyDressedGames/Unturned-3.x-Community#1741]
I want to create an Intro for my server but the "Video Player" I use to do it does not work is something of unturned?

**Comment by Alex-Well** [comment]
I also noticed that Videoplayer is not working. Most likely, Nelson did not add his support when switching Unturned from Unity 5.5 to Unity 2017-2018.

**Comment by SDGNelson** [comment]
It is probably because movie textures have to be in the built-in StreamingAssets. There are a few other potential causes, but it is unlikely to be officially supported anyway.

https://docs.unity3d.com/Manual/class-MovieTexture.html

**Comment by SrZanahorio** [comment]
"But i was using VideoPlayer with a RenderTexture not a Movie Texture also the video was on mp4"
