### ISSUE TITLE
Feature Request: Unturned Top in Unturned.

### ISSUE THREAD

**Issue by GoryBark** [SmartlyDressedGames/Unturned-3.x-Community#1744]
![top](https://user-images.githubusercontent.com/48866020/82568149-4daf4600-9b76-11ea-9674-b17a23e35d7b.jpg)
 No explenation needed.

**Comment by SDGNelson** [comment]
Nice one

**Comment by Johnanater** [comment]
Epic

**Comment by thereis** [comment]
Ahhahahaha, nice one

**Comment by GoryBark** [comment]
<3

**Comment by GoryBark** [comment]
Seriously though, could we have this in game? It would look DOPE! :D
