### ISSUE TITLE
Kills_Zombie condition does not work

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1746]
Did a quest at the NPC. I decided to protest and noticed that killing zombies does not change the counter for completing tasks. Redid, but still such an error occurs.

Overlay id excluded.

Conditions 2

Condition_0_Type Kills_Zombie
Condition_0_Zombie None
Condition_0_ID 26550
Condition_0_Value 16
Condition_0_Reset

Condition_1_Type Item
Condition_1_ID 12261
Condition_1_Amount 1
Condition_1_Reset

**Comment by SDGNelson** [comment]
At the moment zombie kills conditions need the `_Nav` property set to a navmesh index, but it would make sense to allow zombie kills anywhere on the map when unset.

**Comment by SvyatoslavOrlov** [comment]
I hope this feature is added soon.

**Comment by SDGNelson** [comment]
Sorry that it was not mentioned here, but in one of the Elver updates this was added so if _Nav is unset then _Radius is used instead.
