### ISSUE TITLE
Hide Crosshair

### ISSUE THREAD

**Issue by CapScroLL** [SmartlyDressedGames/Unturned-3.x-Community#1748]
How can I hide the player crosshair?

**Comment by Jerico97** [comment]
Hey
Just check config.json in the server folder

**Comment by CapScroLL** [comment]
> Hey
> Just check config.json in the server folder

Can we do this with a plugin?

**Comment by CapScroLL** [comment]
Maybe these codes will work? xd
Provider.configData.Easy.Gameplay.Crosshair = false;
Provider.configData.Normal.Gameplay.Crosshair = false;
Provider.configData.Hard.Gameplay.Crosshair = false;

**Comment by Trojaner** [comment]
Yes it will work, although it will only work for new connected players.

**Comment by CapScroLL** [comment]
> Yes it will work, although it will only work for new connected players.

Thx
