### ISSUE TITLE
[Feature Request] NEW EventHook For Items & Animations , (Wait Until) 

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1749]
Hi 
I would like to improve my mod by adding this feature, Since the game is providing us with more event hooks like the new one custom weather event and others stuff, and i wanted to thank you for adding new features like this it improves our mods, But for me i always wanted a event hook for items and animations to improve my mod, for example i made a Item that holds a particle system and i wanted it to spawn after the Weak animation is played.
this could work for stuff like if have an item that holds 2 particle systems then it could play the first one for weak and the other one for strong, Or maybe if a have a Chest closed it could open it up after the Use animation.

i hope you get the point
this could open a lot of possibilities for us.

could use something like this 

public UnityEvent Animation_Equip;
public UnityEvent Animation_Inspect;
public UnityEvent Animation_Use;
public UnityEvent Animation_Weak;
public UnityEvent Animation_Strong;
public UnityEvent Animation_Start_Swing;
public UnityEvent Animation_Stop_Swing;
public UnityEvent Animation_Aim_Start;
public UnityEvent Animation_Aim_Stop;
public UnityEvent Animation_Attach_Start;
public UnityEvent Animation_Attach_Stop;
public UnityEvent Animation_Hammer;
public UnityEvent Animation_Reload;
public UnityEvent Animation_Sprint_Start;
public UnityEvent Animation_Sprint_Stop;

get the animation name if it matchs the name for example "Use" , wait until the animation finish then invoke Animation_Use;

idk if this is how you do it i'm not a coder, i'm just trying to help :> , 
i hope this is not hard to make, and it will improve some of my items 

sorry for my english, And Thank you !

**Comment by Alex-Well** [comment]
I offered the same thing, only a more advanced version supporting other character animations. We wrote all the code, Nelson had to add it.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1697

**Comment by BREEZEXPVP** [comment]
very nice ! we just have to wait 👍

**Comment by BREEZEXPVP** [comment]
closing this issue since you already have a better informative issue @Alex-Well
