### ISSUE TITLE
Unturned Public Test Branch

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#175]
Something like the PUBG Test Server (not as a steam branch like OPERATIONMAPLELEAF, but as a separate start option / game or something like that)

Why use separate start option instead of steam branch? I think if its a steam branch not many players will use it.  It needs to be something that can run side by side with the normal branch, not something mutually exclusive.

Basically before an update comes out it gets released on the test branch for the players and server hosters to test it out. After about a week (when the next update comes), it gets released to all players. Test branch can have very experimental stuff too, it can get updates daily etc.

Also we all would really appreciate it if you test updates on linux servers too before releasing them.

Why I am suggesting this? Well the last updates broke a lot of stuff, especially for linux servers. Its really frustrating. I can't blame Nelson as he can't test everything alone (even with maybe 20+ testers that's not enough, and would also be very time consuming). We shall not forget that Nelson is a solo developer and not a big studio with an own testing unit.

**Comment by Gigawiz** [comment]
I definitely agree, this is an awesome idea. I'd be up to help testing the test branch as well (i have both windows and linux servers)

**Comment by SDGNelson** [comment]
This is going to be in the initial 4 release - having a separate app on Steam for preview/test releases before making their way onto the stable version.
