### ISSUE TITLE
A collection of useful improvements for modding.

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1750]
Hello Nelson, in this issue I have collected the most interesting ideas that would improve Unturned modding. There will be a lot of information, but I hope it will be easier for you to perceive it.

1. Add settings to the config for the bayonet of a knife worn on a weapon. It was offered here:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1688

2. Add the ability to set a custom effect when you turn on the NVD, Headlamp, flashlight, as well as a tactical flashlight, laser and rangefinder. Most likely it is a Vision user effet. Something similar was offered here:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1654

3. Add AnimationEventHook. According to our assumptions, it will work well as it listens to events from the PlayerAnimator character in the hierarchy. If the object lies on the ground, then accordingly the events will not be heard, as we intended. We wrote the code and all you have to do is check and add it to the game. Add this tool not only I suggested.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1697
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1749

4. Make it possible to run UnityEvent at TextChatEventHook on the client side as well. (Now it runs only on the server) It is also possible to make ClienTextChatMesseger launch TextChatEventHook, bypassing the Allow_Client_Messages option restriction. At the moment, this is used so that the mods do not force the players to write offensive phrases in the chat, however, this blocks the ability of the mods to launch Events from each other. Back in 2018, I suggested using chat as a universal channel of communication between mods and now it is possible. However, when the option is enabled, the commands sent by the mods will be visible, and when turned on, they will stop working. Is it possible to create an additional chat that will not be visible to the players and at the same time will be available by default on the server so that ClienTextChatMesseger can activate TextChatEventHook?

5. Make a universal UnityEvent binary state. Something like IOBS, but allowing you to add it to any object, whether it be Item or Vehicle. The main idea is that it would have two UnityEvent - ON and OFF, as well as a logical variable True / False. The server will monitor the hierarchy of which GameObject the script is in and send it the value of the variable from which UnityEvent will be launched. You may have to use a non-standard SteamCall, but I think it will not be so difficult to do. The task is to transfer the current state of the script from the server to the client and from the client to the server in order to get full synchronization of events.

**Comment by Bulka148** [comment]
Someone sleeps at home, someone sleeps with parents, someone sleeps with a girl, but Alex sleeps on GitHub

**Comment by Trojaner** [comment]
More than half of what you have written has it's own issues. No need to duplicate it. There is also no need to create issues which are collections of ideas. They should be separated.
