### ISSUE TITLE
Automatically shut down the server bug

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#1751]
[2020-05-22 19:04:12] BattlEye Print: Could not connect to BE Master
[2020-05-22 19:04:12] BattlEye Print: Disconnected from BE Master

I only found this in the log

**Comment by CatzMR** [comment]
@SDGNelson

**Comment by SDGNelson** [comment]
It might be simply that the BattlEye-enabled server cannot function without a connection. Once the connection was restored is it working properly?

**Comment by CatzMR** [comment]
@SDGNelson 
When this error occurs, the server will shut down abnormally. I do n’t know how to deal with this error. This error will appear shortly after the server is turned on, and the server will automatically shut down

**Comment by SDGNelson** [comment]
Is it consistently unable to connect to BattlEye, and then shuts down? Perhaps the firewall or security systems are preventing BattlEye from connecting?

**Comment by CatzMR** [comment]
Yes, it has been unable to link to BattlEye

**Comment by SDGNelson** [comment]
Unsure what to recommend because filtering outbound connections will be specific to your setup. It may be worth double-checking that the server does work properly with BattlEye disabled.
