### ISSUE TITLE
[Request] Developer mode

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1752]
Developer mode for easiest code tests with fast game/server start-up, auto LAN/WAN(IP and Port in launch arguments) server join, optimizations.

**Comment by Greenorine** [comment]
Good suggestion!

**Comment by Trojaner** [comment]
You can already start server fast with -SkipAssets, but keep in mind that you can not join it then

**Comment by Greenorine** [comment]
Thanks, very usable.

**Comment by erik7302** [comment]
> You can already start server fast with -SkipAssets, but keep in mind that you can not join it then

If u use -SkipAssets too(in client) u can, now joining without it idk.

**Comment by Sl4vP0weR** [comment]
> You can already start server fast with -SkipAssets, but keep in mind that you can not join it then

But, for real, testing code with my old PC is very hard.

**Comment by SvyatoslavOrlov** [comment]
good idea

**Comment by Charterino** [comment]
What optimizations do you think it would contain? Why would Nelson add any optimizations to this "development mode" but not to the actual server? I see no purpose in this. Also you can remove all maps from the Maps folder except for PEI, that would make loading process faster.

**Comment by Sl4vP0weR** [comment]
> What optimizations do you think it would contain? Why would Nelson add any optimizations to this "development mode" but not to the actual server? I see no purpose in this. Also you can remove all maps from the Maps folder except for PEI, that would make loading process faster.

Already did it, but it are helpless.

**Comment by archie426** [comment]
Why don't you just patch the game assembly yourself in the meantime and make the optimisations you want to make?
