### ISSUE TITLE
Level files just disappeared after restart

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1753]
To start with, I am always doing clean shutdown (/shutdown). Shutdown server for simple restart (nothing new added, nothing changed). Launched a server and all level files disappeared. The only file I found in levels folder after restart was vehicles.dat (which, of course, ended up in frozen server). Happily got some week-old backups. Any ideas what might have triggered this? I've faced similar problems in the past. But files were corrupted (most probably of wrong shutdown (by simply closing console)) and level files weren't wiped. 

Getting this exception on server launch. Yet, been getting this for a long time now:
```
[Exception] Rocket.Unturned >> Exception in Update: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) SDG.Unturned.VehicleManager.DMD<DMD<save_Patch1>?-548581376::save_Patch1>()
  at SDG.Unturned.SaveManager.save () [0x00062] in <9f4f953307a14568b0ad80e23d7dc383>:0 
  at Rocket.Unturned.Utils.AutomaticSaveWatchdog.checkTimer () [0x00036] in <59f13c7b8fd2452db84433be578fe6c9>:0 
```

**Comment by Trojaner** [comment]
You are using a plugin that patches the save method of Unturned, so this is not an Unturned related issue. Sadly, due how patching works, we can not know what plugin causes it.

**Comment by baranmod** [comment]
well, I strongly doubt this error could have wiped level data, because as I mentioned its been here for a very long time - but faced this issue just couple days ago.

**Comment by Trojaner** [comment]
Some plugins can get updated in the background, which can cause such issues suddenly.
