### ISSUE TITLE
Suppressors are not working fine on easy mode

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1754]
Something is wrong, why suppressors break in easy mode, should be not break
[![](http://img.youtube.com/vi/ZmQLDaCL3nE/0.jpg)](http://www.youtube.com/watch?v=ZmQLDaCL3nE"")

**Comment by Johnanater** [comment]
They still break, just as arrows do (iirc)

**Comment by TH3AL3X** [comment]
Aight, but nelson ignores this, and that this error takes a long time in the game

**Comment by SDGNelson** [comment]
Some items (like suppressors) are balanced by their durability so they take damage in all modes.
