### ISSUE TITLE
SteamCMD is installed in Temp

### ISSUE THREAD

**Issue by ZoomGYT** [SmartlyDressedGames/Unturned-3.x-Community#1755]
Hello nelson, in your dedicated Server repository, in the link that SteamCMD for Windows is installed, it is broken, since it is installed in Temp, and when you restart you have to re-install it because it is deleted, I solved it by going to the web steamcmd and downloading it from there. A greeting

**Comment by SDGNelson** [comment]
That depends where you install steamcmd. The link in the documentation downloads steamcmd.zip to your downloads folder. From there it is up to you where to extract and install it to.
