### ISSUE TITLE
Ace with scope?!

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#1757]
Hello,
a player killed a cheater (as he claims) , and he found Ace with scope among his items.
here is a screenshots
https://cdn.discordapp.com/attachments/612059834396966942/714247503763210292/unknown.png
Greetings

**Comment by nanashi88** [comment]
an admin said: this is a gun which can obtained by the scientist npc on russia

sry for disturb

**Comment by SDGNelson** [comment]
You are right that this item was probably acquired from the quest. (cheaters cannot attach items that violate attachment rules)
