### ISSUE TITLE
Add additional Devkit foliage settings to non-Germany foliage

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1759]
Currently, the Germany foliage has some nifty settings that the other foliage could benefit having, namely
```
"Cast_Shadows" "false"
"Tile_Dither" "true"
"Draw_Distance" "-1"
```
All Russia, PEI and Washington foliage lack these settings, and it could potentially improve performance.

-------------------------

EDIT:
Germany foliage .assets are structured slightly differently than non-Germany foliage, Germany foliage also has a density of "512", while all other foliage has a density of "2". thought it was worth mentioning, though I doubt this is worth changing.

**Comment by SDGNelson** [comment]
I think most likely the Germany grass had the default values written out because the assets were created in the devkit rather than manually. (e.g. Tile_Dither defaults to true, Cast_Shadows defaults to false) Will double-check the density though.

**Comment by SDGNelson** [comment]
All current values in the foliage are correct. Density is the target meters squared per instance.
