### ISSUE TITLE
Servers started to not show up after recent update

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#176]
Edit: Apparently a lot of people don't have any humor and can't take a joke.

NOTE: Plugins cause this mostly, but at the moment it is not known why.

Mostly people who use bots to fake player count are affected, but others who dont do that are affected too. In any way this is connected to plugins which mess with the steam server metadata

**Comment by baranmod** [comment]
What bots are you speaking about? I use Sam's lobby mess plugin though.

**Comment by Trojaner25** [comment]
Such plugins use a feature called "bot players" of steam. Its not real bots like they would be ingame. Its just faking player count

**Comment by baranmod** [comment]
maybe you have a list of the plugins having this feature?

**Comment by Trojaner25** [comment]
Any plugin that changes how servers appear.
* plugins that remove workshop stuff,
* plugins which can hide plugins,
* plugins which mess with player count
etc

**Comment by baranmod** [comment]
So basically Sam's lobbymess plugin? Paid plugin from imperialplugins.com you selling?

**Comment by Trojaner25** [comment]
This is what you paid for? You paid for changing how the server looks and Nelson decided to block such servers?

Anyway contact Sam on resolving the issue with the plugin

**Comment by baranmod** [comment]
I paid for "List your server as non-workshop and get more visibility for your server" feature (line from imperialplugins). Thats it. If thats somehow illegal - that thing shouldn't be listed for sale at the first place, I believe.. And no need to threaten with bans, especially when you selling tools to make forbidden things...

**Comment by Trojaner25** [comment]
You paid for that and Nelson decided to remove such servers from the list. 
Its not something forbidden, its something Nelson decided to block

**Comment by baranmod** [comment]
ohh, how nice. So IF buying some other plugin I need to know what Nelson's future plans are? Whats next? Forbidden vault, airdrops or something else? And all you say is "its none of our business, its Nelson's decision"? Nice approach.. A simple "sorry, XX plugin listed on our directory is no longer functioning properly" but instead of that you just suggesting to ban users from github using this plugin...

**Comment by Trojaner25** [comment]
Oh I'm responsible for Nelson suddenly blocking such stuff?
Please be more reasonable

**Comment by baranmod** [comment]
I'm not saying that. You are calling me as some cheater who "should be banned on github" while all I'm doing is using the plugin which I bought on your platform. No reports, nothing have been said that this plugin shouldn't be used etc. So all I am saying is just that the problem is in the plugin hosted on imperialplugins. But the only guilty person in this situation is me? Ohh, okay then..

**Comment by Trojaner25** [comment]
I did not claim you should be banned,  I claimed people who use bots should be banned and that wasnt even a serious one. 

Do you think we  have the ability to see the future? Like we can write "WARNING: in 3 months Nelson will block this plugins X feature! Be advised that we cant do anything about it!"

Didn't I also say that the plugin will get updated?

**Comment by baranmod** [comment]
I guess its not the best place for jokes, is it? "Autoban people from GitHub who say their servers do not show up in server list". So thats exactly what you said.

I am not asking a warning 3 months before it happens. You could just mentioned that after this happened. As I know, this happened already before yesterday's update. So some notification in discord channel could've been enough. 

Discussion closed from my side. Thanks.

**Comment by Trojaner25** [comment]
To be honest I though it should be obvious that this isn't serious...It was to raise attention about the issue with bots

**Comment by WarpKat** [comment]
Github isn't a place for this kind of self-centered dribble, Trojaner.

**Comment by Torubloo** [comment]
No ServerDetailsEditor is not effect, I didn't put it in there for a reason, to stop people finding out that bit of code and abusing it

**Comment by Torubloo** [comment]
Secondly this is not Unturned related and you can't ban people from GitHub you can report someone to GitHub if they are spamming issues and they might stop them from commenting on your things but you CANNOT auto ban people

**Comment by Torubloo** [comment]
Any plugin using the bit of code for SetBotPlayerCount(1); is effected, any plugin not doing this is not effect

May I say this is one of the most retarded issues you've ever pushed, and that's saying something

**Comment by Trojaner25** [comment]
@WarpKat well @baranmod went way offtopic and was very unreasonable
@Torubloo no one asked your opinion, and this is Unturned related, as Nelson pushed code which filters servers on the INTERNET tab, and that has apparently cought some wrong servers.

People who used ServerDetailsEditor or AviLobbyMess report that it worked again after removing those plugins.

So stop wasting our time with your half-knowledge.

**Comment by Trojaner25** [comment]
Here, I reverse engineered how Unturned filters servers:
![](https://vgy.me/SzksEB.png)
We can clearly see that it filters servers with botCount now, previously the `else` part was not here, so it did not filter for Plugins: ANY. That means it now filters servers with botCount > 1

So for sure people who suddenly report that their server is not show up have a botCount > 1 and hence they are faking player count.

**Comment by Trojaner25** [comment]
I will make a new issue since this one was too offtopic...

**Comment by Torubloo** [comment]
As i said my plugin doesn't have fake player count for a reason (see for your self https://github.com/Torubloo/ServerDetailsEditor/blob/master/ServerDetailsEditor.cs) and never has, so no my plugin does and has never been effected by this
