### ISSUE TITLE
[Problem] Save and Load issues

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1760]
1. My plug-in adds custom component to barricades transform, when server trying to save all - it breaks Level's saves
2. BarricadeManager.Load executes "spawnBarricade" method, that contains onBarricadeSpawned event call, when I subscribed on this event - Level.Load wont to call my handler.
![image](https://user-images.githubusercontent.com/42337892/82807757-00efa600-9ebb-11ea-80b0-eb98af32a091.png)
Screenshot after Level save bug

**Comment by SDGNelson** [comment]
So it works with your plugin disabled, but throws an exception when your plugin is enabled? Do you set any of the vanilla fields to null during your custom code? (StructureManager.save would only be hitting a null reference exception when accessing StructureRegion.structures and StructureRegion.drops, whereas saveRegion does most of the saving and is not in the posted callstack)

**Comment by Sl4vP0weR** [comment]
I didn't set to null something in StructureManager, just gave my own behaviours for barricades when BarricadeManager already loaded.
I had another trouble with barricades before - some barricades have component, some not, but I tried to add component for all barricades in all regions, this is was strange. 
I tried to change my code for solving problem and now I have this "save Level bug".

**Comment by SDGNelson** [comment]
You bind onBarricadeSpawned, and all your method does is add a component? That should be fine. If you are adding the component in onBarricadeSpawned then it should not be necessary to iterate barricades in all regions. Perhaps if you upload the server log from Logs/Server_(server name).log it will highlight the cause?

**Comment by Sl4vP0weR** [comment]
> log it will highlight the cause?

I dont think so

**Comment by Sl4vP0weR** [comment]
Here is my code
![image](https://user-images.githubusercontent.com/42337892/82860341-d3067200-9f4b-11ea-9ef0-cb791aef68dc.png)
![image](https://user-images.githubusercontent.com/42337892/82860384-f0d3d700-9f4b-11ea-9197-8209c1eb0404.png)

**Comment by SDGNelson** [comment]
For example there might be an exception earlier that causes the exception during save. If you would like to email me the log file that may be better for privacy.

Regarding your code snippet: you should not call DontDestroyOnLoad on the component, there will be a lot of warnings in your log file related to that.

**Comment by Sl4vP0weR** [comment]
> you should not call DontDestroyOnLoad on the component

without this method my component will be destroyed by a game.

**Comment by Sl4vP0weR** [comment]
From last log
`
[2020-05-25 19:05:54] DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
[2020-05-25 19:05:54] 
[2020-05-25 19:05:54] DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
[2020-05-25 19:05:54] 
[2020-05-25 19:05:54] Static weather override: NONE
[2020-05-25 19:05:54] DivideByZeroException: Attempted to divide by zero.
[2020-05-25 19:05:54] SDG.Unturned.LightingManager.updateLighting () (at <9f4f953307a14568b0ad80e23d7dc383>:0)
SDG.Unturned.LightingManager.onLevelLoaded (System.Int32 level) (at <9f4f953307a14568b0ad80e23d7dc383>:0)
SDG.Unturned.Level+<init>d__128.MoveNext () (at <9f4f953307a14568b0ad80e23d7dc383>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
`

**Comment by SDGNelson** [comment]
I will get that lighting exception fixed up - thanks for the stack trace!

The component will get destroyed when the barricade is destroyed. Calling DontDestroyOnLoad on it is not doing anything other than logging the warning you see.

**Comment by Sl4vP0weR** [comment]
@SDGNelson I need make "checkBarricades" task for my plugin.
Event "onBarricadeSpawned" useless for this situation. 
I need set some routine with delay, that will check an behaviour for barricades with certain ids. I did it, but some barricades when I use GetComponent give me null value. What the reason ? 
Routine:
![image](https://user-images.githubusercontent.com/42337892/83287069-9d93aa00-a213-11ea-8a35-2277005f2b47.png)
Method "BarricadeSpawnedHandler" you saw before.

**Comment by SDGNelson** [comment]
Some plugin might be setting `cycle` to zero, but in the .4 patch it will reset to 3600 if set to zero.

**Comment by Sl4vP0weR** [comment]
> Some plugin might be setting `cycle` to zero, but in the .4 patch it will reset to 3600 if set to zero.

Its cant be cuz I tested only this plugin on my server

**Comment by Sl4vP0weR** [comment]
> There is only one place in vanilla code that spawns barricades, and it calls the event when it does.
> 
> Your coroutine should not be necessary. It sounds like a plugin may be manually spawning barricades incorrectly and inserting them into the lists.

U are misunderstood me, sometimes onBarricadeSpawned event doesn't calls my handler when level loading.

**Comment by SDGNelson** [comment]
In that case you might be binding `onBarricadeSpawned` late. (after level loading)

**Comment by Sl4vP0weR** [comment]
> In that case you might be binding `onBarricadeSpawned` late. (after level loading)

Plugin can be reloaded what means the behaviour will be destroyed. I should make check every plugin loads or make check schedule when plugin loading

**Comment by Sl4vP0weR** [comment]
> I should make check every plugin loads or make check schedule when plugin loading

I did it, but its doesnt works

**Comment by DiFFoZ** [comment]
![image](https://user-images.githubusercontent.com/48765566/83330573-0df50680-a2ba-11ea-8cbc-ef87210c144a.png)
I don't have problems with `onBarricadeSpawned`

**Comment by Sl4vP0weR** [comment]
> I don't have problems with `onBarricadeSpawned`

Where is mine problem ?

**Comment by Sl4vP0weR** [comment]
[2020-06-03 17:20:50] Ready to connect
[2020-06-03 17:20:53] Connection pending verification
[2020-06-03 17:20:53] Authenticating with server --- TicketLength: 240 ProofLength: 16
[2020-06-03 17:20:54] Accepted by server
[2020-06-03 17:20:55] Discarding old unacknowledged input packets (25/24)
![image](https://user-images.githubusercontent.com/42337892/83619804-f621c900-a5be-11ea-9e9c-a36f2084b4dd.png)
