### ISSUE TITLE
(Request) add ability to remove prefix from the notification of kick, ban and onCheckValidWithExplanation

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1761]

**Comment by SDGNelson** [comment]
The plugin prefix? It is like that to make it clearer that the rejection was not VAC / BattlEye related. Though there are still some plugins that frustratingly use inappropriate messaging. What is your message?

**Comment by baranmod** [comment]
Just want to make message as clean as possible (look like vanilla one with no indications of custom plugin). Yet, I see your point about inappropriate usage.
