### ISSUE TITLE
Error in DamageTool.damagePlayer

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#1762]
While looking around in the DamageTool class, I found this at the end of the damagePlayer function:
```
parameters.player.life.serverModifyFood(parameters.foodModifier);
parameters.player.life.serverModifyWater(parameters.foodModifier);
```
The food modifier is reused instead of the waterModifier, which I think is the intended behaviour.

**Comment by SDGNelson** [comment]
Good catch, thanks for the report! Will get that corrected for the next patch.
