### ISSUE TITLE
Play static sound effect to player

### ISSUE THREAD

**Issue by RestoreMonarchy** [SmartlyDressedGames/Unturned-3.x-Community#1763]
Hey,
How can I play sound effect to player that isn't based on position, so no matter what position player is it will play the same volume loudness (I mean it won't change over range from point specified with `EffectManager.sendEffect`)?

For example when player plants the bomb I want to play him a sound "Bomb has been planted" but while it's playing he's running away from the position where it was played, so it's loudness becomes lower what gun shoots becomes almost inaudible. So if it doesn't exist I think it'd be useful for many other plugins too.

Thanks

**Comment by DiFFoZ** [comment]
Add `Audio Source` to canvas

**Comment by CyberAndrii** [comment]
Change Spatial Blend to 2D

![42148-audio-2d-to-3d-unity-5](https://user-images.githubusercontent.com/37713088/82951402-bf8cf280-9faf-11ea-8381-f7f1d944f7c4.png)

**Comment by RestoreMonarchy** [comment]
and then send with `EffectManager.sendUIEffect` then?

**Comment by RestoreMonarchy** [comment]
> 
> 
> Change Spatial Blend to 2D
> 
> ![42148-audio-2d-to-3d-unity-5](https://user-images.githubusercontent.com/37713088/82951402-bf8cf280-9faf-11ea-8381-f7f1d944f7c4.png)

I did it this way and it works!
Thank you both
