### ISSUE TITLE
Force player to clear ragdolls

### ISSUE THREAD

**Issue by RestoreMonarchy** [SmartlyDressedGames/Unturned-3.x-Community#1764]
I'm asking for a feature that allows server to force player to reset (clear) all player bodies and blood around the map. This would be very useful for rounds based plugins. 

I'm not sure if there isn't a way for it already tho I couldn't really find it, can you hook me up with it then?

Thanks

**Comment by TH3AL3X** [comment]
Good idea :-) pd, we can clear lag with that

**Comment by Trojaner** [comment]
I am pretty sure these do not cause lag

**Comment by SDGNelson** [comment]
This is available, used in arena mode to clean up between rounds: the poorly named `EffectManager.askEffectClearAll`

**Comment by TH3AL3X** [comment]
> I am pretty sure these do not cause lag

If you have in skills "boost blood" thats can do FPS lag on the server... anyways is not much

**Comment by SDGNelson** [comment]
At the moment it clears everything, sorry. There isn't one specifically for UIs / non-UIs

**Comment by rube200** [comment]
we can have an event for when ''EffectManager.askEffectClearAll" happens, this allowed the plugins to show UIs again automatically

**Comment by RestoreMonarchy** [comment]
I mean I wanted the specific tell method to be added for clearing ragdolls, because I'm clearing them at the beginning of new round, so players are still viewing scoreboard and other UIs, they will just close and because they are slow I think it will look bad.
And yeah the main thing is that I'd have to reopen their UIs every round.
