### ISSUE TITLE
Vehicle turrets not spinning more than 360 degrees on the yaw

### ISSUE THREAD

**Issue by rkrause4** [SmartlyDressedGames/Unturned-3.x-Community#1767]
Before the most recent update, vehicle turrets with Yaw_Min set to -360 and Yaw_Max set to 360 would never be stopped at a point while spinning. 

After the update, I've noticed that vehicle turrets set to the same Yaws as mentioned above, are now stopping after one full rotation. That would be 360 degrees in this case in either direction (whether the player starts spinning in the counter or clockwise direction). Once it stops the player has to reverse their spin to get to the other side (Similar to the default forest tank).

I wasn't sure if this was intentional or not in the last update as I didn't see anything mentioned in the Patch notes.

**Comment by SDGNelson** [comment]
Sorry about this, not intentional. The turret yaw must be getting clamped before the angle is brought back into the looping range. Will fix for the next patch.

**Comment by rkrause4** [comment]
Ok, thank you for taking the time.
