### ISSUE TITLE
Unity 2019

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1771]
can the game update to Unity 2019 this upcoming months or next year?

i'm realy Hyped for Unturned II , but at the same time i would love to see Current 3.0 updating to Unity 2019 mainly for features like ShaderGraph , Visual Effect Graph, , timeline etc.

i'm pretty sure that 2019 would break all shaders even game code,
if its major game code breaking we could keep 2018.4

if not U3 could use the Universal RP but we lose most of PBR options
what U3 should use is the High DifinitionRP. adds more options .

i'd love to hear your opinion, Thanks.

**Comment by Trojaner** [comment]
How exactly do you think will Unity 2019 benefit you?

All of the features you described can not be added as they would require a switch to a scriptable renderpipeline, which would break all workshop mods. Beside that Unity 2018 already supports these.

From plugins perspective there is no need for it at all.

**Comment by BREEZEXPVP** [comment]
@Trojaner 
Yes i understand your comment , this will be a major game breaker  mods included and since plugins are the most used in servers,  Unity 2019 could or already by updating break the code and shaders , and it will be pain in the a@# to reimport and rework all mods or dlls . thats a fair point.

i use 2018.4 almost alll the time,

closing this issue like you said highly doubt Nelson updating to 2019.
