### ISSUE TITLE
Shutdown command

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1776]
I think it's time to update the shutdown command (At least in Rocket Mod).
It is not convenient to write like this - /shutdown 4/Shutdown_Reason
Just in the Rocket Mod itself, the commands are updated and do not require "/" and have a way to highlight parentheses - /ban "Nickname/Steam64ID" "Reason with spaces" "Time"
I would like to see this with shutdown
/shutdown "Time" "Reason"
And also when specifying the time, so that the chat is written not only the time before shutdown, but also the reason immediately.

**Comment by SDGNelson** [comment]
This is just how the old commands parse inputs. Custom commands can call `Provider.shutdown(int timer, string explanation)` if you want. If the built-in commands get a rework the input parsing will probably be changed to not do the weird '/' delimiter.
