### ISSUE TITLE
Server Description Russian Letters Issue

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1778]
I don't know, but something is not ok with russian letters and server config descriptions. I will show only full one, but hint and server list has same thing.

There are 100% normal English full server description. Everything is ok here.
![dL6gU1Wvp7c](https://user-images.githubusercontent.com/59829274/83346900-54357e80-a329-11ea-90fc-5b9e6d2da76c.jpg)

This is same description, but on Russian language.
![MIlWGh3rR8E](https://user-images.githubusercontent.com/59829274/83346923-87780d80-a329-11ea-9db9-fdbd7ca5571d.jpg)

It doesn't show properly, cuts symbols and even can't display some. So what is wrong?
**Used Sublime Text 3 for editing config**
**Used WindowsSCP for FTP work**

**Comment by surv0013** [comment]
I think the problem is not the language, but the number of characters

**Comment by NoThreat** [comment]
It has almost same number of characters. I tried adding more English symbols and it was ok

**Comment by DiFFoZ** [comment]
Because the Russian letter takes 2 bytes instead 1 byte from English letter

**Comment by Sl4vP0weR** [comment]
> Because the Russian letter takes 2 bytes instead 1 byte from English letter

I dont think so, cuz we have some encoders, like UTF8, where all chars is 1 byte, why it should to be 2 bytes ?

**Comment by Trojaner** [comment]
UTF8 character sizes are between 1 and 4 bytes. Only ASCII encoding uses 1 byte.
