### ISSUE TITLE
Automatically backup and clear broken level files

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#178]
Exceptions which occur during loading broken files prevent the server from starting and / or players joining.
I would suggest that if a file can not be loaded, it will be renamed to something like `<FileName>.<ext>.bak.<timestamp>`. The file can not be recovered anyway so there is no point in keeping it (except if there is a backup from a working state).

For example:
Barricades.dat fails loading -> Its renamed to Barricades.dat.bak.121321323 and it will create and load a fresh new Barricades.dat. Maybe show a big red error in console when this happens.

Would fix issues like #173 

Of course this doesnt fix the root problem, which causes those files to get broken in first place..

**Comment by SDGNelson** [comment]
Further save changes are unlikely at this point, but for future additions it would make sense to better bulletproof that code.
