### ISSUE TITLE
Important 3.20.5.4 API changes

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1781]
`BarricadeRegion` has been extended by `VehicleBarricadeRegion`, so a new property `BarricadeManager.vehicleRegions` has been added. The older `BarricadeManager.plants` cannot directly return the `vehicleRegions` list, so instead a copy is constructed when requested if dirty.

`CommandWindow.setIOHandler` now calls the new `CommandWindow.addIOHandler`, so replacing the IO handler requires extra care.

**Comment by SingleThreadedWorld** [comment]
What's the updated method to use instead of BarricadeManager.tryGetPlant?
Is BarricadeManager.dropPlantedBarricade obselete since it calls TryGetPlant?

Would be nice if you had a list of the outdated methods and which to use instead.

**Comment by SDGNelson** [comment]
You are correct that `BarricadeManager.tryGetPlant` and `dropPlantedBarricade` are *NOT* obsolete. The only public `BarricadeManager` API change was replacing the `plants` list with the `vehicleRegions` list (because they have different types), so only plugins iterating the `plants` list will be effected, and even then it should still work albeit with a minor performance penalty.

**Comment by nanashi88** [comment]
what did BarricadeManager.plants contain other than barricades that are on vehicles?

**Comment by SDGNelson** [comment]
They both contain barricades that are on vehicles. It had to be renamed because the type changed from `BarricadeRegion` to `VehicleBarricadeRegion`. Not to mention the name `plants` was... questionable.
