### ISSUE TITLE
[New Map Size?]

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#1783]
Not sure if this is possible, Insane is capable of frying servers completely and yet Large is only adequate but you might want a tad more space to fit in a few more locations. For beefier computers/servers I think there should be a size called Colossal, 6096 metres squared (just over 6km squared) the equivalent of 9 Medium maps. If any other mapmakers want to give their view on this feel free, I personally think this would be a great option for the map creation community.

**Comment by DMJaxun** [comment]
If you are going to react with a negative reaction please give reasoning as to why, thanks.

**Comment by SDGNelson** [comment]
Unlikely to be more map sizes anytime soon, but long-term one goal is to make the map size more customizable (i.e. no specific size value).
