### ISSUE TITLE
Localization Question

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1784]
How does they work? No, I mean, I fully understand how they works. You do folder, name it as language you want to do a translation. For example, French. Then you can translate map adding folder names Maps and .dat file with localization named as map (PEI.dat). It fully works. 

But there are no info about translating bundles. Sometime ago you said that localization was never supposed to manual install and it can be installed just using subscribe button. 

I tried added Bundles folder into French folder. Then create Items folder, Clouds folder and Umbrella_Black. And then just put French.dat with item localization. It doesn't work. So how to do it?
(French/Bundles/Items/Clouds/Umbrella_Black/French.dat)

**Comment by SDGNelson** [comment]
At the moment translating individual items like that can only be done by the creator. For example, placing a `French.dat` file alongside the `English.dat` file. Originally the intention of the translation reworks was to allow specifying a key by path like "SDG.Eaglefire.Name" without per-asset files, but the assets have not been reworked for that (yet?). In the future there could be support for what you describe, or something similar like an `Assets.dat` file in the French folder.

> Sometime ago you said that localization was never supposed to manual install and it can be installed just using subscribe button.

That is correct. There were (and are) a lot of translations published to the workshop whose descriptions said a manual installation was required, but this was never intended. At the time the workshop item had to follow a specific format to be detected properly, but to make it easier I improved the detection to work with most of the common ways they were being uploaded.

> Then you can translate map adding folder names Maps and .dat file with localization named as map (PEI.dat). It fully works.

This is a special case added specifically for maps. It was requested to translate maps created by other teams.

**Comment by NoThreat** [comment]
Will wait for this rework, it could be very useful and players finally get simple localization which contains everything necessary, including bundles.

**Comment by TheTioSweet** [comment]
> How does they work? No, I mean, I fully understand how they works. You do folder, name it as language you want to do a translation. For example, French. Then you can translate map adding folder names Maps and .dat file with localization named as map (PEI.dat). It fully works.
> 
> But there are no info about translating bundles. Sometime ago you said that localization was never supposed to manual install and it can be installed just using subscribe button.
> 
> I tried added Bundles folder into French folder. Then create Items folder, Clouds folder and Umbrella_Black. And then just put French.dat with item localization. It doesn't work. So how to do it?
> (French/Bundles/Items/Clouds/Umbrella_Black/French.dat)

In my case I do something that Nelson mentioned, make a [Language].dat file that holds the same information as English.dat but translated. The game should detect the changes as long as that language folder exists in "Localization".
 
> This is a special case added specifically for maps. It was requested to translate maps created by other teams.

Once again, thank you so much. This is very useful.
