### ISSUE TITLE
Additional IP Address not showing on server list

### ISSUE THREAD

**Issue by ModernMoGamer** [SmartlyDressedGames/Unturned-3.x-Community#1787]
Hi, I can replicate this issue to an extent using servers from 2 different Dedicated Machine providers.
Both are running Ubuntu 18.04 and I believe I've partially seen it on Windows (Cannot confirm windows)

When having a machine with additional IP addresses (more than 1 IP) binding a Unturned Server to the default IP that came with the machine will work when direct connecting and searching on the Master Server List.
Though when using an additional IP address (which is setup and pings correctly) can only be direct connected to and cannot be found on the server list.

The Bind command in Commands.dat doesn't allow for any of the external IP's and will only accept 0.0.0.0 The servers are running in a docker instance which allow only specific access to a set IP and ports (This shouldn't be the issue as it works with default IP).

This means Unturned Servers on the same machine must have unique ports and only use the default IP assigned to the machine. The idea with this is meant to be able to have different IP's but use the default port of 27015 like in many other games.

This seems to have to be with the master server list as Steam is able to see a server on 27016 (the query port not the main port like we see with all Unturned Servers).

I'd like to be able to have these additional IP server's show in the master server list. Please and 
Thank you.

**Comment by SDGNelson** [comment]
Do you host any Valve games with a similar setup? It might simply be a limitation of the master server if connecting directly is working as expected.

**Comment by ModernMoGamer** [comment]
I have seen this working for Rust, I currently don't have any instances off hand, though I know others have this working with the Steam Server List.

**Comment by SDGNelson** [comment]
To give you a better understanding of what is going on under the hood, here is the function that the IP from the "bind" command is passed to: https://partner.steamgames.com/doc/api/steam_gameserver#SteamGameServer_Init

As far as I can tell that is the only place on the game side of the Steam API responsible for the server's address.

When you use the "bind a.b.c.d" command it parses it into a host order uint32 as described.

**Comment by ModernMoGamer** [comment]
I don't believe the issue is with the bind command itself here. The server can still be connected to by direct connect and displayed when you do steam://connect/IP:QUERYPORT meaning that steam recognizes the server. I would believe strongly it is to do with the listing and its detection for placing into the server list.

**Comment by SDGNelson** [comment]
The listings are entirely handled by the Steam master server after the game server is logged on. Detection by the master server can be finicky sometimes - it might be worth double-checking that all the appropriate Steam ports are forwarded and not blocked in the firewall.

**Comment by ModernMoGamer** [comment]
This is looking like a docker issue. https://github.com/pterodactyl/panel/issues/459
Thank you.

**Comment by SDGNelson** [comment]
Glad you found the problem. I will try to remember this issue to link other hosts to in the future.

**Comment by Mxthic** [comment]
@ModernMoGamer You ever get a fix for it. Having same problem but Rust
