### ISSUE TITLE
Private Workshop

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#179]
This is one off the unlikeliest to-be-added requests I have done yet, however its very important for many server owners.

Most server owners want their very own workshop maps, items, clothings etc. But due the nature of the workshop, its easy to copy workshop items.

Why is it unlikely to be added?
Due the nature of the workshop, its easy to copy workshop items.

There might be still some way:
Like adding a file to the workshop item, which specifies server IPs which are allowed to use or which are blocked from using it. The client which connects could check if the server IP matches one of those and load the workshop item based on that.

But even that wouldn't work well because people just could rip off the files and re-upload them. However that would be a copyright violation and a DMCA takedown request could easily be sent to Steam (DMCA requests for *using* workshop items are likely not valid).

Most people would not risk uploading stolen files since it means that the Steam Account can get restrictions like a steam ban from the community (e.g. workshop, commenting). New accounts / smurfes can not upload to workshop, as those are restricted until they spent at least 5 USD.

**Comment by KrYojeNiX** [comment]
Sounds great in theory, and as a server owner and creator of content for the game, this is something I would also like to see.
I'm sure many other creators and server owners would too.

**Comment by H3xxdump** [comment]
That would be a great advantage for server networks. Especially modding-services like Moon-Modding would profit from it. Also for me there would be many benefits.

**Comment by Trojaner25** [comment]
Well this wasn't suggested with services in mind but that would be an advantage for them too ofc

**Comment by VitaxaRusModding** [comment]
Yes =)
