### ISSUE TITLE
[BUG] Vanish mode bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1790]
When someone shoots in vanish mode it will be reflected in the weapons of other players the shot, no matter the distance
[![](http://img.youtube.com/vi/aj2bjvur09s/0.jpg)](http://www.youtube.com/watch?v=aj2bjvur09s"")

**Comment by Sl4vP0weR** [comment]
U need go to the rocketmod on github with this bug, here only the game issues :/

**Comment by TH3AL3X** [comment]
-_- nelson can fix it, because he is updating rocketmod two

**Comment by SDGNelson** [comment]
When Rocket puts players in vanish mode it teleports them near the first-person viewmodel, so the muzzle flash is lighting up the viewmodel. While odd I don't think it's a big deal.
