### ISSUE TITLE
Dissable Voice chat

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#1792]
Add disabling voice chat to plugins, some servers really need this function.

**Comment by Sl4vP0weR** [comment]
> Add disabling voice chat to plugins, some servers really need this function.

._.
PlayerVoice.onRelayVoice or player.voice.allowVoiceChat are useless ?

**Comment by SDGNelson** [comment]
Sl4vP0weR is correct that plugins can do this.
