### ISSUE TITLE
[Feature Removal Request] Suggestion to remove RocketMod's reload option

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1794]
Hello @SDGNelson,

Since you are maintaining RocketMod with future releases of Unturned, I'd like to possibly see the removal of rocket reload for individual plugins and for all plugins as it literally breaks most current plugins for Unturned. Not to mention those that are new to Unturned Hosting tend to be lazy and use rocket reload to reload modified plugin configs, see a bunch of other plugins break and start screaming, rather than simply restarting the instance. 

Thank you!

**Comment by baranmod** [comment]
Maybe its easier not to use it than remove it? Personally, there are dozen of plugins which work just fine for me with reloading them and I can simply avoid restarting whole server if I do minor changes on configs.

**Comment by joeymisfit** [comment]
Try telling that to new server owners, that don't have a clue on how to use it properly? lol

**Comment by baranmod** [comment]
will learn over time

**Comment by m0r3d** [comment]
rocket reload works well with a lot of plugins
if someone dont know how use it that's his problem

**Comment by SDGNelson** [comment]
While it may be problematic for some hosts and developers, my inclination is to keep the feature considering others find it useful.

**Comment by erik7302** [comment]
and a bool for each plugin so set if it supports reload and its default to true?

**Comment by SDGNelson** [comment]
Making it optional per-plugin seems reasonable to me.

**Comment by Trojaner** [comment]
I strongly support the removal too. It doesn't make much sense (most of the time, it kicks everyone), doesn't work correctly (many plugins do not support this properly) and causes other kind of bugs.

Keep in mind that Rocket has a functionality that allows to reload plugins one by one, which is a much better alternative.

**Comment by SDGNelson** [comment]
With Trojaner supporting it (given his expertise) maybe removal is the right thing to do.

**Comment by Paradox304** [comment]
So remove /rocket reload and keep the individual rocket reload still in.

**Comment by FANYPLAYRU** [comment]
Why delete a useful function? I use it all the time, Yes, some plugins give an error after that, but there is /rocket reload <Plugin Name> for this, and it is convenient. Why spoil the RocketMod if you can make it better. You just delete useful features from it, and after that people don't want to update to new versions and are thus susceptible to hacking/attacks. Yes, you can say that this is their problem, but you create these problems for them.

**Comment by Edbtvplays** [comment]
Also strongly support the removal of the overall command, Unturned server help sections are filled with "why did i get this error after running /rocket reload or why did this stop working after /rocket reload".  It would be useful to remove the whole command so it cant happen. I still would like to see it have in inital plugins however as that is very useful. If a plugin does not support it it should just return "this plugin does not support /rocket reload please restart".

**Comment by XanderCodes** [comment]
I'm on the side of only allowing specific plugins to be reloaded. Having the server break on a full reload can be difficult to understand for new server owners... and even if the server can still break while doing `/rocket reload <plugin name>` I still find that better than restarting the entire server, especially on the server I develop for, where there's an unhealthy amount of plugins to load on server start... I don't want to restart and kick everyone for a little configuration change

**Comment by Johnanater** [comment]
Maybe having to confirm the `/rocket reload` would be a good idea, along with a warning message indicating that bugs may occur.

**Comment by Gsechs** [comment]
While it seems the discussion has mostly ended, I would like to say that if any change is made, it should absolutely be the removal of “rocket reload” as a whole. However, it’s very useful to reload specific plugins, saving owners from a restart. Individual plugin reload should be kept.

**Comment by SDGNelson** [comment]
This change will be in the next update. In case anyone is interested, here is the commit: https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/commit/bad399177172ddce665b105e782d83df2cd472d0

**Comment by ennerperez** [comment]
This was a great terrible idea. @SDGNelson you can't do this just cuz 2 or 3 "experts" say you should. This is a community repo. You can ask, vote or something, also, already have pulls requests from months ago... Where this "feature" come from? From nothing! This is absolutely absurd to maintain a repo on this way.

**Comment by joeymisfit** [comment]
@ennerperez You can still reload individual plugins and permissions, mysql based plugins do not work well with rocket reload, and most plugins don't work properly with a rocket reload, you literally have to restart the server for it to completely refresh. Those comments weren't really necessary.

**Comment by XanderCodes** [comment]
> This was a great terrible idea. @SDGNelson you can't do this just cuz 2 or 3 "experts" say you should. This is a community repo. You can ask, vote or something, also, already have pulls requests from months ago... Where this "feature" come from? From nothing! This is absolutely absurd to maintain a repo on this way.
> 
> // Btw, why this discussion happens here instead the (LMD) repo?

What a stupid thing to say. Why not fix the thing that's broken? If he removed something from the core game that has been broken for years, would you run a poll?

This is not the place to argue, and I would encourage you to not speak like that here. This forum is for civilised discussion, not offensive language or insults.

**Comment by archie426** [comment]
@ennerperez Well if you had an objection you should've raised it at the time...? No one is stopping you from using a legacy build lol.
No, it's not absurd, but I'll tell you what is, making a vote for something like this. Most of the community agreed, it is being removed to prevent plugins causing serious issues, in fact in some cases, data loss. It is simply a preventative measure. 

Also it is kind of annoying that you put experts in quotes as if you don't agree with it. I mean, are you seriously suggesting one of the maintainers isn't informed about they're own software?

**Comment by ennerperez** [comment]
> @ennerperez Well if you had an objection you should've raised it at the time...? No one is stopping you from using a legacy build lol.
> No, it's not absurd, but I'll tell you what is, making a vote for something like this. Most of the community agreed, it is being removed to prevent plugins causing serious issues, in fact in some cases, data loss. It is simply a preventative measure.
> 
> Also it is kind of annoying that you put experts in quotes as if you don't agree with it. I mean, are you seriously suggesting one of the maintainers isn't informed about their own software?

Maybe cuz I was watching the wrong Rocket repo?

**Comment by SDGNelson** [comment]
Note that the methods for reloading all plugins still exist, so if you know that all the plugins on your server support reload properly you could have a custom dev command to reload all. The only change was to disable "/rocket reload" with a warning message, not to remove the underlying functionality.

**Comment by ennerperez** [comment]
> Note that the methods for reloading all plugins still exist, so if you know that all the plugins on your server support reload properly you could have a custom dev command to reload all. The only change was to disable "/rocket reload" with a warning message, not to remove the underlying functionality.

Yeah thnks already working on it.

**Comment by vanya890** [comment]
> /rocket reload <plugin>)

It doesn't work for all plugins. Some plugins simply require a complete reboot of Rocket.
Deleting a command is very annoying, you have to constantly restart the server, which is very, very long, especially if there are several of them.

**Comment by vanya890** [comment]
> Also strongly support the removal of the overall command, Unturned server help sections are filled with "why did i get this error after running /rocket reload or why did this stop working after /rocket reload". It would be useful to remove the whole command so it cant happen. I still would like to see it have in inital plugins however as that is very useful. If a plugin does not support it it should just return "this plugin does not support /rocket reload please restart".

Restart is a very long time. /Rocket reload is much faster and more convenient

**Comment by vanya890** [comment]
The point is not even in this plugin.
It is much faster to just restart everything if I know that my plugins do not break, than to restart dozens of plugins individually.

**Comment by vanya890** [comment]
> Note that the methods for reloading all plugins still exist, so if you know that all the plugins on your server support reload properly you could have a custom dev command to reload all. The only change was to disable "/rocket reload" with a warning message, not to remove the underlying functionality.

How do I enable or create this command?

**Comment by Paradox304** [comment]
> > Also strongly support the removal of the overall command, Unturned server help sections are filled with "why did i get this error after running /rocket reload or why did this stop working after /rocket reload". It would be useful to remove the whole command so it cant happen. I still would like to see it have in inital plugins however as that is very useful. If a plugin does not support it it should just return "this plugin does not support /rocket reload please restart".
> 
> Restart is a very long time. /Rocket reload is much faster and more convenient

Go to the commit that Nelson made for the removal of this command and reverse engineer the command. Then it should be "faster" and "more convenient"

**Comment by Paradox304** [comment]
https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/commit/bad399177172ddce665b105e782d83df2cd472d0

Here's the commit.

**Comment by Paradox304** [comment]
Checking the code, it's just one method you have to run -_-

Create a command which runs the method R.Reload();
