### ISSUE TITLE
How to Fix this seed?

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1795]
The problem is that on the one hand there is a texture, and on the other it is absent.
I took everything from your examples and only changed the texture.
Used The Bundle Tool
Although in Unity it shows the texture on both sides
![Снимок экрана (290)](https://user-images.githubusercontent.com/65422793/83899218-bb579680-a760-11ea-98c9-79157353418f.png)
![Снимок экрана (291)](https://user-images.githubusercontent.com/65422793/83899224-bd215a00-a760-11ea-8c82-0d6393ea6958.png)
![Снимок экрана (292)](https://user-images.githubusercontent.com/65422793/83899229-bf83b400-a760-11ea-950a-cfbfd41d6d9d.png)

**Comment by FANYPLAYRU** [comment]
![image](https://user-images.githubusercontent.com/65422793/83899614-6bc59a80-a761-11ea-9a83-00e83afffe7a.png)
![image](https://user-images.githubusercontent.com/65422793/83899632-73853f00-a761-11ea-88f1-82a847f37e2a.png)

**Comment by SDGNelson** [comment]
Most likely the game is auto-converting the shaders because it thinks it is an old asset bundle. You can set Asset_Bundle_Version to 3 to disable that.

**Comment by FANYPLAYRU** [comment]
Ok.
Im test this

**Comment by FANYPLAYRU** [comment]
Thank you, it helped!
