### ISSUE TITLE
Hiden chat option

### ISSUE THREAD

**Issue by sacarusan3** [SmartlyDressedGames/Unturned-3.x-Community#1796]
I would like to be able to modify the chats size to the point where it is unreadable or directly if there is a hidden chat option

**Comment by FANYPLAYRU** [comment]
In the game directory there is a file Preferences.json
It has a chat setting, you can configure it as convenient or remove it altogether

**Comment by sacarusan3** [comment]
so i have to restart the game in order to get the launcher updated when i want to talk in chat?
I am asking for an ingame option

**Comment by TH3AL3X** [comment]
Nelson need to add that to gameplay in game, it's a good idea

**Comment by SDGNelson** [comment]
The closest option is the one in the options menu which disables text chat from everyone except yourself.
