### ISSUE TITLE
Trojaner25

### ISSUE THREAD

**Issue by Cyphierion** [SmartlyDressedGames/Unturned-3.x-Community#180]
@Trojaner25 150,000 lines of Java source code is literally nothing. Minecraft Plugins are easy as fuck to make, don't even try to claim you accomplished something. Managing something means nothing. Imperial Plugins are trash because everything has a price on it and it isn't hard at all to replicate their entire plugin database. Ooooo!!!! "I wrote half of the RocketMod rework, I'm special" Yeah, you really are. You say you have enough experience but you don't even have good credibility at all since you're getting roasted, I mean fucking roasted by other devs in the awful C# Plugin Development community. Knowing which commands and functions are dangerous literally means nothing, a five year old knows that. Stop whining like a baby that you're getting trashed on and stop making your shit open source. Everyone has been ripping off RocketMod, I mean everybody. This whole open source crap is definitely the way to get ripped off since half of all code out there is not copyrighted and has no case in a court room. Grow the fuck up and learn how to life properly. You're autistic for sure.

**Comment by Cyphierion** [comment]
Trojaner Fag of 25 Years, this is my real account. Get the fuck over it. Minecraft is full of shitty kids like you. Go back to your creative mode Minecraft server with your squad of insecure bullies with failing grades. Nice Edit for my account creation date, you have zero comebacks on me because you have zero ammunition to use against me that actually would mean anything. Bruh, fucking duh -- take a sarcastic statement over code security. Learn a real fucking language like C++ or Assembler x86_64, that will actually make you smart, not this ASP.NET or C# garbage you claim is actually good to learn about. What developers are on your side??? 14 year olds on your side because they love your shitty programmed plugins and thinks they are all decent. Congratulations, you gave candy to young teenagers. "Serious experience in programming" -- but you obviously don't understand you have zero rights to the code you write. Holy shit this kid is salty as fuck... "I don't even want to respond to this, but maybe it will educate you a bit:" Bro, this isn't school, why are you responding to some random person on the internet and losing? To win something that literally means nothing? Copyright... fucking duh, is your education level in the 5th grade? Oh my god, someone give this man a cookie.

**Comment by Alekaei** [comment]
your comments speak for themselves.

**Comment by Trojaner25** [comment]
Please stop responding you will kill me from laughing.
25 years? Me or you? Regardless of the result its funny, either because you write stuff like this at that age or because I am 19 years old and you made this up.
  
Assembler is not a language, maybe you are referring to "assembly". Beside that, no real software uses assembly any more those days, because its outdated and not needed anymore.

I'm sure you didn't know what ASP.NET was until today.
You could be really good friends with "Torubloo", since you both like to claim stuff without evidence.

**Comment by Alekaei** [comment]
Trojaners that is, he sucks and cant program for shit

**Comment by Trojaner25** [comment]
Yea I agree this issue changed my view of life, I will quit programming today and repeat high school from 9. grade, to get re-educated and start a new career as professional cleaner of too much poop that is stuck in toilet

**Comment by Cyphierion** [comment]
"Beside that, no real software uses assembly any more those days" -- xD Every program you compile runs assembler. Google Assembler. Look at result number 1. Holy shit... Real autism here; pretending to laugh won't make you win an argument you already lost.

**Comment by Alekaei** [comment]
its funny how cyphier is convinced hes won something on the internet. congrats man

**Comment by Trojaner25** [comment]
What I mean was that no program is written in **assemb~~ler~~ly** anymore

**Comment by Cyphierion** [comment]
Nah suck it up kids. Spam Spam Spam.

**Comment by Cyphierion** [comment]
Apparently you never bothered to Google Assembler. Good job. -20 points of credibility.

**Comment by Trojaner25** [comment]
I dont care about assembler I'm going to be a poop cleaner

**Comment by Cyphierion** [comment]
Useless discussion? Why are you responding to it then? Complete Paradox of your whole argument xD

**Comment by Alekaei** [comment]
cause you're a meme

**Comment by Jonnyfencing1** [comment]
I don't understand why you felt the need to make this a public issue, you're clearly trying to embarrass someone who you can't embarrass and you're also looking for attention.

**Comment by zoomy500** [comment]
Assembly is generally only used now in reverse engineering, hacking (be it ethical or not), and programming microcontrollers. Anywhere else other languages can be used simply for convenience.

**Comment by Trojaner25** [comment]
guys, stop feeding the troll..

**Comment by Alekaei** [comment]
assembly isnt a language

**Comment by Trojaner25** [comment]
you mean assembler Alekaei but i dont know what im talking about, im not a dev, im a poop cleaner

**Comment by Trojaner25** [comment]
also @Cyphierion thanks for the laughs and memes we had in discord.

![](http://prntscr.com/i1b2q5)
Maybe this will make you feel better

**Comment by Shadow041717** [comment]
After reading this I think I literally got cancer -_-

**Comment by SDG-Nelson** [comment]
I've made the decision to leave this issue open because @Trojaner25 needs to be publicly embarrassed, or the other guy (can't remember)

**Comment by Trojaner25** [comment]
IM DEAD

**Comment by SDG-Nelson** [comment]
[*]

**Comment by SDG-Nelson** [comment]
I'm gay

**Comment by Jonnyfencing1** [comment]
God damn Nelson came out OMG a tremendous achievment @SDG-Nelson #prayfornelson #supportnelson #fixlinux

**Comment by SDGNelson** [comment]
Both Cyphierion and SDG-Nelson have been blocked from the organization. Closing this issue.
