### ISSUE TITLE
"No_Abandon" option for Quests

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1800]
Something like `No_Abandon` for Quest assets to remove Abandon option. It can be very useful for adventure maps, where player got consistent quests one by one, and sometimes really good to remove "Abandon" button from them, because it can simplify map creation, because player can't accidently or not abandon quest and brake all.

**Comment by SDGNelson** [comment]
Intend to add at some point, but closing this one in the meantime because it is the same as #1772.
