### ISSUE TITLE
Friends Can't Join My Server

### ISSUE THREAD

**Issue by RecoTG** [SmartlyDressedGames/Unturned-3.x-Community#1802]
I have made a server on Windows and Linux the first problem that Windows Server Wont let my friends join and the other problem with Linux That the Commands.dat folder is not loading with the server.

**Comment by educatalan02** [comment]
You should post your server logs.

**Comment by RecoTG** [comment]
Logs?

**Comment by RecoTG** [comment]
There Is nothing in the logs
execpt start up things
