### ISSUE TITLE
Can I make this type of food?

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1803]
I can make such a Cracker that will be added to take away Food and Water?

**Comment by iBowie** [comment]
#1522

**Comment by FANYPLAYRU** [comment]
Is it added?

**Comment by iBowie** [comment]
no, but i made a free plugin that will work only on server with Rocket installed that adds these missing fields (view my repos if you're interested)

**Comment by FANYPLAYRU** [comment]
> no, but i made a free plugin that will work only on server with Rocket installed that adds these missing fields (view my repos if you're interested)

I looked and found nothing.
Is this in your Rocket Mod or a separate plugin?

And what's the problem with Nelson adding this to the game?

**Comment by iBowie** [comment]
repo name is BowieD.Unturned.AssetExpander

**Comment by FANYPLAYRU** [comment]
Thanks
