### ISSUE TITLE
Mode Is Stuck on Normal

### ISSUE THREAD

**Issue by RecoTG** [SmartlyDressedGames/Unturned-3.x-Community#1804]
I have A Server Which I Have Switched From PEI to Germany and When i join I See normal Zombies 
instead of the Easy Type Zombies And in the config file it says Mode Easy and yet it still starts with Normal Zombies and in the Server's Desc it says Easy mode

**Comment by SDGNelson** [comment]
Are they in the higher-tier areas like the burned town and military base? Germany has the quirk of per-area zombie types that do not respect the global settings.

**Comment by TH3AL3X** [comment]
Send your config.json here
