### ISSUE TITLE
Map Object Player Damage

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#1807]
Is there anyway to make a map object do damage to players, like the barbed wire for example? If there, isn't could it be possible to add one?

**Comment by SDGNelson** [comment]
This is on the eventual to-do list, but more and more requests keep getting piled on. Issue #1220 has more details about what should be added.

In the meantime you could place barbed wire in the level editor. Sooner than later (i.e. sooner than #1220) an option will be added for placement of indestructible / permanent barricades from the level editor.
