### ISSUE TITLE
Map editor will not put down the vehicles I have set to spawn in.

### ISSUE THREAD

**Issue by KennysBoat** [SmartlyDressedGames/Unturned-3.x-Community#1808]
My map editor will ONLY spawn in blue hatch backs when I have several military vehicles with rarity and spawn rates. Earlier it was spawning random civ vehicles, so I got rid of all vehicle spawns and made only one military spawn. But its now only spawning blue hatchbacks

**Comment by TH3AL3X** [comment]
Do you save it?

**Comment by SDGNelson** [comment]
Probably confusion about spawn table IDs vs asset IDs, but feel free to comment and I will re-open.
