### ISSUE TITLE
Color model vertex editor

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#181]
I want to offer something similar to this [editor](http://unitylist.com/r/385/face-paint), it is very convenient and will help to change the color of objects when developing maps. I understand that this is not easy to do, I just want you to think about this idea.
I think this tool will make the game more diverse and beautiful.

**Comment by SDGNelson** [comment]
I agree that would be useful for sure, but I think outside the scope of the in-game editor. I'll put it on the backlog for now.
