### ISSUE TITLE
Vehicle Id

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1811]
'spawn Vehicle', 'spawnLockedVehicleForPlayer', 'spawnVehicle Internal' should return the vehicle InstanceID.
I know it is possible to make a patch but I think this should be implemented by default

**Comment by SDGNelson** [comment]
In the next update there are two new methods `spawnVehicleV2` and `spawnLockedVehicleForPlayerV2` that return the `InteractableVehicle` spawned.
