### ISSUE TITLE
Load Workshop Assets during Server Connection

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#1813]
Hello Nelson, 
In my opinion, due how are workshop assets loaded at the start of the game, there are alot of bugs like some items got the same ID.

I would recommend you to load Workshop Assets while you're joining a server. (For example if a server requires the mod 2000XXX, the game will only load 2000XXX).

With that all that bugs will dissapear.

**Comment by SDGNelson** [comment]
Mods loaded while connecting to the server override any existing loaded IDs. Unturned's loading is definitely not ideal, but the only long-term solution is to gradually convert everything to use the GUIDs.

**Comment by SDGNelson** [comment]
@PandahutMiku that could maybe work. Re-building the ID-to-asset dictionaries depending on multiplayer/singleplayer/editor. Guids are the ideal long-term solution, but maybe a workaround is the correct thing to do in the short term.
