### ISSUE TITLE
[BANNED] Banned while playing my own server

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1814]
Today I was on my server so calm when suddenly I received a ban by BattleEye for no reason, I am very confused, I have not used cheats in unturned in my life, I'm very nervous because I don't know what happened. 

Also one of the reasons, is it why i'm going to **hack when I have put money in skins in unturned**? By donating to nelson in this way ...

Also the contributions I give to the Plugins community, and game bugs, The truth is that I am very confused, this is a mistake, I hope there is a solution, GameForFreak received a ban too for no reason, and it just happened to me.

**My account:**
https://steamcommunity.com/id/psychiatry/

**Battleye ban**
![image](https://user-images.githubusercontent.com/13141042/84491404-c6508080-aca4-11ea-9de7-6d322815b89f.png)

**Some proofs of false ban:**
[![](http://img.youtube.com/vi/OXMKxPdJBmU/0.jpg)](http://www.youtube.com/watch?v=OXMKxPdJBmU"")

**Screenshot from a user:**
![image](https://user-images.githubusercontent.com/13141042/84491631-20514600-aca5-11ea-95cb-1d3fe43eba1f.png)

**Comment by WhyRegisterToReportBug** [comment]
Yes, can confirm. Am kaakeli. Terror is a server owner and very good one, this morning he got randomly Battleye banned all of sudden.

**Comment by kahin598** [comment]
I was with him he was chatting with us in the server and left randomly.After some minutes he got banned with BattlEye 2 or 3 times

**Comment by kahin598** [comment]
To be honest i know the guy and now im scared that innocent people getting banned

**Comment by xshinax5** [comment]
The owner of this server is very good and he never use cheat before but for no reason he got banned by battleye

**Comment by desban** [comment]
This person is innocent of the ban since he only creates plugins and creates servers and as seen in the video he is not a fake figense at the time of the log and everything.

**Comment by Gerkune** [comment]
The server owner is a fair guy, innocent got banned randomly while playing

**Comment by DARKNESS-FOREIGN** [comment]
Imagine being banned by Battleye, so-called the most superior anti-cheat just for testing on your own server. In all honesty, such an unpredicted ban because the man was innocent. Please fix Nelson, and fix the game while you're at it.

**Comment by jatapa** [comment]
This rly is not the place for this.
Only way you will ever get unbanned is by contacting battleye and waiting.
Talking about it anywhere else will not get you unbanned.

**Comment by TH3AL3X** [comment]
> This rly is not the place for this.
> Only way you will ever get unbanned is by contacting battleye and waiting.
> Talking about it anywhere else will not get you unbanned.

I do it so Nelson can see it, nothing else, but i got innocent ban

**Comment by jatapa** [comment]
> > This rly is not the place for this.
> > Only way you will ever get unbanned is by contacting battleye and waiting.
> > Talking about it anywhere else will not get you unbanned.
> 
> I do it so Nelson can see it, nothing else, but i got innocent ban

Sure but the only way to proof that you got false banned is to get an unban from battleye those screenshots proof nothing

**Comment by MrObi123** [comment]
> > > This rly is not the place for this.
> > > Only way you will ever get unbanned is by contacting battleye and waiting.
> > > Talking about it anywhere else will not get you unbanned.
> > 
> > 
> > I do it so Nelson can see it, nothing else, but i got innocent ban
> 
> Sure but the only way to proof that you got false banned is to get an unban by battleye those screenshots proof nothing

^

**Comment by TH3AL3X** [comment]
> Sure but the only way to proof that you got false banned is to get an unban by battleye those screenshots proof nothing

Yes, but if you look at the ban time and the log messages, and when I uploaded the video, it can't give me time to start the unturned without the hack activated, Anyway, why i'm going to hack a game that I spent hours on and dedicated to contributing, plus I have purchased skins, and i was in my own server

**Comment by TH3AL3X** [comment]
I have nothing to do, just wait, because I don't know what happened, I can't present any more evidence, and I also sent a request to battleye to review my case, thank you anyways @jatapa

**Comment by TH3AL3X** [comment]
[UnityDebug_Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4771128/UnityDebug_Client.log)
[UnityDebug_Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4771131/UnityDebug_Client_Prev.log)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4771132/Client.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4771133/Client_Prev.log)

**Comment by SDGNelson** [comment]
It does not show up on the support site yet, but it should later today so I will check back soon.

**Comment by TH3AL3X** [comment]
Np, take your time, but i hope this is solved

**Comment by akyudumsu** [comment]
This person is a known game hacker, no wonder he got banned.

Some comments from his profile:
![grafik](https://user-images.githubusercontent.com/45712012/84525027-a3918c80-ace3-11ea-93fe-7bb5821d8e67.png)

![grafik](https://user-images.githubusercontent.com/45712012/84525192-eeab9f80-ace3-11ea-8754-9640d5c1e6b6.png)

He is also in various cheating groups:
https://steamcommunity.com/groups/ExMarineHittingP
https://steamcommunity.com/groups/ayywar3
https://steamcommunity.com/groups/HvHitler

Video where he is hacking, uploaded by himself
https://www.youtube.com/watch?v=OPIeIujcaak
https://www.youtube.com/watch?v=jxFS70ICsFU
https://www.youtube.com/watch?v=yu0KOXV0rWk

He probably underestimated Battleye and is just really disappointed that his cheat got detected.

**Comment by TH3AL3X** [comment]
And thats means i'm hacking on Unturned?, dude the CSGO one was with "insecure" nothing else and that doesn't damage the game, its just a HvH community, and comments doesn't mean i'm cheating on a game, because everyone can get comments like that by no reasons, but if you, I do not judge your ideals, they are your thoughts

**Comment by TH3AL3X** [comment]
Why i'm going to hack unturned for get a ban? and why in my own server, thats doesn't make sense, anyways i play unturned everyday for do productive things like plugins etc... , pd CSGO was "insecure" parameter so that doesn't damage players.

**Comment by akyudumsu** [comment]
You don't really do plugins except cracking ones or stealing open source ones. You are not a reputable person in the plugin community. You also just released the source code of your plugins to get better conditions in this appeal.

**Comment by TH3AL3X** [comment]
No, before I had a plugin community and it was closed because of that I am publishing all the origin of all my plugins for free https://plugins.darknesscommunity.club/

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/84526537-c5881080-acdd-11ea-8d87-0939006b3ca2.png)

**Comment by TH3AL3X** [comment]
I just close it, and i don't understand what do you mean with "code stealing"

**Comment by TH3AL3X** [comment]
Well, these are things I don't know where you would have got it from, but you think that and I accept it

**Comment by TH3AL3X** [comment]
> This person is a known game hacker, no wonder he got banned.
> 
> Some comments from his profile:
> ![grafik](https://user-images.githubusercontent.com/45712012/84525027-a3918c80-ace3-11ea-93fe-7bb5821d8e67.png)
> 
> ![grafik](https://user-images.githubusercontent.com/45712012/84525192-eeab9f80-ace3-11ea-8754-9640d5c1e6b6.png)
> 
> He is also in various cheating groups:
> https://steamcommunity.com/groups/ExMarineHittingP
> https://steamcommunity.com/groups/ayywar3
> https://steamcommunity.com/groups/HvHitler
> 
> Video where he is hacking, uploaded by himself
> https://www.youtube.com/watch?v=OPIeIujcaak
> https://www.youtube.com/watch?v=jxFS70ICsFU
> https://www.youtube.com/watch?v=yu0KOXV0rWk
> 
> He probably underestimated Battleye and is just really disappointed that his cheat got detected.
> 
> https://github.com/kahin598
> https://github.com/xshinax5
> https://github.com/desban
> https://github.com/Gerkune
> https://github.com/DARKNESS-FOREIGN
> 
> They all registered on June 12, coincidence?
> Except for some people from his server and 5 accounts who joined GitHub today, this person has no one supporting him.

Pd again, All those who recently registered are players from my server who saw what happened

**Comment by TH3AL3X** [comment]
And add me on discord, i want to talk with you, TERROR#2080

**Comment by archie426** [comment]
@akyudumsu You remind me of torubloo. Stop being a little busybody shit. Oh no! He knows some cheat developers! Must mean he uses them! On top of this, these are completely different games....
On top of this, these videos are from FIVE years ago (one of them was two but same point)........

Now, I do know that a bypass has been patched recently. Could be because of this but there is literally no way of knowing.

**Comment by nanashi88** [comment]
everything is possible, I can't witness if he did use something or not!
but as a player at his server I could confirm the following:
- he is the server owner
- he put a lot effort on creating plug-ins with unique and creative features
- he has created Anti-cheat system for his server (DAC), and I think it is doing good
- he fly a lot in his server (as an admin to check issues), so I wonder if this could be the reason
- I haven't noticed that he play at his server as a player, he just get in to solve issues and check on the server, then disconnect

**Comment by SDGNelson** [comment]
I made sure to double-check considering Game4Freak's false-positive from plugin development, but after double-checking I have no doubt that you have been cheating in Unturned. Not to mention your profile screams cheater (e.g. the spinbotting gif), and all of the examples akyudumsu kindly shared.

**Comment by archie426** [comment]
@nanashi88 BE won’t detect anything like that - just to clarify

**Comment by TH3AL3X** [comment]
I just can't give more information about my profile, but i'm saying the true, this is not normal, by ban is gonna keep because i have "cheater profile" i said the true, i just cheat in CSGO without VAC "insecure" parameter, i play HvH Community Servers, nothing else, thats doesn't mean i'm cheating on Unturned.

**Comment by TH3AL3X** [comment]
I don't know but right now it's giving me anxiety, I don't know what to do and seeing everything, I don't think there's hope for anything because I didn't do anything wrong, I just dedicate myself to making plugins for this game and moderating on my server, I don't do anything else

**Comment by DARKNESS-FOREIGN** [comment]
This is outrageous, not going to want to be rude but this is so unfair. Terror is a server owner with tens of contributions to the community of unturned, and making a server isn't easy when basically 100 percent of his plugins are hand made. Now I see a reason with all that being done, to decide to cheat in the game he has a passion for. Now I'm currently talking to him on a discord call and he sounds really distraught and sad over the fact that he got a ban for literally no reason whatsoever, and is kept banned due to the looks of his profile? Let me state that counterstrike has HVH enthusiasts, one being terror and myself. We never cheat in a competitive state (Like games of competitive, or in this case on servers) but we engage in cheating on -insecure servers **MADE** for it. Now, that being said I understand the phrase "once a cheater is always a cheater", but why would he do it? Like actually why? He has a reputation and even a server, which he pays for, knowing that he'll eventually be banned, why would he risk it all? His money and hard work, your donations to you? I myself have over 2k hours now on Unturned and this is kind of disappointing knowing that he is being kept banned, even though his respect for the game is through the roof. I don't also see how the aesthetics of his profile and groups have ANYTHING to do with a ban in YOUR game and not counterstrike. I'm not a bot that was made by terror, to help him back himself up, as though I've made this account today due to the fact I wanted to help him, and without an account that wouldn't be possible. If you have your doubts still I don't understand what else to tell you but this is mind-boggling. Thanks for the read, Foreign. (FOREIGN#6283)

**Comment by DARKNESS-FOREIGN** [comment]
Notice also how nowhere on his "cheater profile" or his "cheating groups" (This is so dumb that I even have to point it out) states that what he does in CS, he does in Unturned. How does his hobby of HVH'ing in CS got to do with a ban in Unturned?! Also notice how all of the evidence that guy has attached is AGAIN in no corrolation whatsoever, my account was made today but it wouldn't of had if this ban didn't take place, especially because it's unfair. All of the videos in the "proof" are also in other games, none of them being UNTURNED.

**Comment by akyudumsu** [comment]
Please close this issue for discussions, at this point its only spamming inboxes and notifications of about 40 people

**Comment by jatapa** [comment]
He did close it

**Comment by akyudumsu** [comment]
I mean closing it for discussions, as in restricting further comments

**Comment by TH3AL3X** [comment]
@akyudumsu are you happy about this? because you don't know how i feel right now

**Comment by SDGNelson** [comment]
I should clarify: while his profile is suspicious, my comment is based on the BattlEye ban for Unturned. Has has multiple cheating accounts, all BattlEye banned from Unturned.
