### ISSUE TITLE
[Fixed Bug] Quest 'The One That Got Away'

### ISSUE THREAD

**Issue by MrObi123** [SmartlyDressedGames/Unturned-3.x-Community#1815]
People were having issues with the quest 'The One That Got Away'. If they abandonned it, they couldn't start it again since it was a reward from the quest before. So I edited the pirate's files and now it's fixed so you can start it again.

DM me on Discord so I can send the files in a ZIP-file. [MrObi#9157]

**Comment by educatalan02** [comment]
Send them over here, or just upload it to a Website.

**Comment by MrObi123** [comment]
https://filebin.net/9gsb7vuytevh55fd/Pirate.zip?t=dcgnil84

**Comment by MrObi123** [comment]
So... This bug wont be fixed in the next patch? 🤔

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix. Off the top of my head it might not have been repeatable to prevent spawning multiple of the blueprint item, but there could be a separate option to restart the quest.

**Comment by MrObi123** [comment]
In the files I've sent here, I made it so you need to click a message to accept the quest, so you can restart when you abandon it. But yes, respawning would be a problem.

Maybe there's some way to unlock the crafting recipe itself without needing the item?

(Feel free to use the code I made, it was ment for you anyways)

Hit me up if you need help with fixing a NPC bug, perhaps I can help again since I already help a lot of people.

**Comment by MrObi123** [comment]
In the files I've sent here, I made it so you need to click a message to accept the quest, so you can restart when you abandon it.
But yes, respawning would be a problem.

Maybe there's some way to unlock the crafting recipe itself without needing the item?

**Comment by MrObi123** [comment]
> Thanks for the report! Will fix. Off the top of my head it might not have been repeatable to prevent spawning multiple of the blueprint item, but there could be a separate option to restart the quest.

Wait actually. The quest I fixed was the quest where you had to fish up the squid and not 'The Ultimate Fishing Rod'. You could always restart that quest to get a new blueprint.

You receive the 'The One That Got Away' quest after you crafted the fishing rod. So it wouldn't make sense if you couldn't restart this, since you don't get anything when you start it.

So I think you got a little confused with the wrong quest. ;)

**Comment by SDGNelson** [comment]
This should be fixed in the next update.
