### ISSUE TITLE
After Unity update my objects works wrong

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1818]
When 3.20.5.4 came out, my mods stopped working on server properly. Everything ok except the fact that when object has conditions and somehow disappears, on server collision still there. When player goes through it, he starts lagging. 

Where did I made a mistake? After update I set 23f1 (I used 0f1 before). It was not good, I changed it to 14f1. It has same situation.

**Comment by TH3AL3X** [comment]
What do you mean with 23f1, the version of unity?

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/84565842-763cf100-ad6c-11ea-89dc-8ddb76d95aa6.png)

**Comment by NoThreat** [comment]
#f1 - this is subversion of Unity. But I think it has some weight in mod making. And I want to know what is.

**Comment by SDGNelson** [comment]
The only conditions that should be used for objects with collision are ones consistent for all players because collision is not per-player. For example, time of day is okay for collision.

**Comment by NoThreat** [comment]
I set time of day and it still lagging. All objects from exact mod is lagging, nevermind what condition was made.

**Comment by NoThreat** [comment]
Ok. I even tried  `Master_Bundle_Override` and `Bundle_Override_Path` and took from core.masterbundle vanilla non-destroyable medium object with collision. It was "Pipe_0".  

I set
**Conditions 2
Condition_0_Type Time_Of_Day
Condition_0_Second 79200
Condition_0_Logic Less_Than_Or_Equal_To
Condition_1_Type Time_Of_Day
Condition_1_Second 28800
Condition_1_Logic Greater_Than_Or_Equal_To**

Then I tested it on custom map on vanilla server (no rocket) and it lags on server. Singleplayer works   absolutely normal. Visually object disappears, but collision not. I guess something in-game broken. Please, check it.

**Comment by SDGNelson** [comment]
Double-checking, it looks like quest conditions have never been supported for object visibility on the server. The only supported object visibility on the server is for holiday events like the snowmen.

In the vanilla game any object with conditional visibility does not have player collision, e.g. the objects for Liberator quests.

What object do you have in mind that toggles collision at different times of day?

**Comment by NoThreat** [comment]
I wanted to do an object which appear on day and decay at night. It is medium object with collision. As I said, I took "Pipe_0" as example.

I didn't know about lack of support of conditional visibility for server. Maybe it will be good to do it then? It has a thousands of usage e.g adventure maps, quest lines and not only.

**Comment by SDGNelson** [comment]
What is the intended object you want to make though? (not Pipe_0)

**Comment by NoThreat** [comment]
Any medium or large object with collision. Box or mesh, nevermind. And I want to apply conditions on it.

**Comment by SDGNelson** [comment]
What do you actually have in mind though? For example some sort of door, tree, fish, etc. I am curious because there might be an alternative way to do it in the meantime, and also to keep in mind for future features.

**Comment by NoThreat** [comment]
Not Binary_State objects, not resources, not fish. Just simple object to block way of player. I don't see alternatives, maybe you can help? 

I want to do a location which opens for people only in exact time. The objects blocks way by collision. I don't want to do event hooks thing etc. Only object with condition.

**Comment by SDGNelson** [comment]
Fair enough.

**Comment by SDGNelson** [comment]
For context: this led to a discussion about per-player conditional collision on the server which might happen eventually, especially if the newer Unity physics engine becomes default, but is unlikely for the meantime.
