### ISSUE TITLE
[BUG] projectiles not rendering while the player is moving backwards (Server-side)

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1819]
after playing with projectiles i've noticed , when the player is moving backwards the projectile will not render for some reasons, In Singleplayer even if the player is moving backwards the projectile still renders but why the server side does not render the projectile, 
The server can render projectiles that where shot while the player is moving forward or idle , but yet when the player is moving backwards server can not render the projectile , 

For my test i used the Rocket launcher (works fine in Singleplayer)
i hope this will be fixed. 
its a bit frustrating when you can not see the projectile.

Thanks !

**Comment by SDGNelson** [comment]
Thanks for the report. Marking with the "next patch" label so that I remember to check this out for the next patch.

**Comment by SDGNelson** [comment]
Should be fixed in the next update!
