### ISSUE TITLE
Error will exporting Masterbundle

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#1820]
![unknown](https://user-images.githubusercontent.com/48290038/84584578-2265f280-add4-11ea-8844-8be26acd016c.png)
Each time I try exporting my master bundle I get this, any idea what could cause this? Here what I tried to fix, all of them failed :
- Shutdown anti-virus
- Run Unity as admin
- Restarted PC and only running Unity for exporting
- Verify for tools newer versions (the EditorAssetBundleHelper was not the latest one, did nothing)
- Moving file manually

I'm using Unity 2018.4.23f1

**Comment by TH3AL3X** [comment]
I think the temporary file is being used by Unity .. Try to cut that file and paste.

**Comment by WW-TC** [comment]
I'll try

**Comment by WW-TC** [comment]
![image](https://user-images.githubusercontent.com/48290038/84604973-afa65700-ae67-11ea-9f6d-340948c54ac2.png)
That's what happens if I move the file manually

**Comment by TH3AL3X** [comment]
What are you trying to do, please be more specific, because i think that file is a file of "Unity program" and not a mod

**Comment by TH3AL3X** [comment]
You are trying to move the file called "unitystream.unity3d" to directory called "D:/Unturned_Uploads/TruckMod/TruckMod" ?

**Comment by WW-TC** [comment]
hummmm
I just noticed something
it should be like that D:\Unturned_Uploads\TruckMod\truckmod

**Comment by WW-TC** [comment]
![image](https://user-images.githubusercontent.com/48290038/84605386-c5694b80-ae6a-11ea-9897-26ba5237cefe.png)

**Comment by WW-TC** [comment]
![image](https://user-images.githubusercontent.com/48290038/84605398-d6b25800-ae6a-11ea-873e-bd9efc4f2b2c.png)

**Comment by TH3AL3X** [comment]
Try without capitals in the end of the route...

**Comment by WW-TC** [comment]
![image](https://user-images.githubusercontent.com/48290038/84605426-1ed17a80-ae6b-11ea-874d-200ad2df2fa7.png)

**Comment by WW-TC** [comment]
it happens while I'm exporting

**Comment by WW-TC** [comment]
I'll try

**Comment by WW-TC** [comment]
I did that
![image](https://user-images.githubusercontent.com/48290038/84605448-4de7ec00-ae6b-11ea-809d-de931523de3a.png)
gave me same result as the first error

**Comment by WW-TC** [comment]
I'll try again without anti-virus

**Comment by WW-TC** [comment]
I'll try again without anti-virus
It also gives me an error in Unity Console
![image](https://user-images.githubusercontent.com/48290038/84605498-c51d8000-ae6b-11ea-87cf-6cc3bb0cc76d.png)

**Comment by TH3AL3X** [comment]
move truckmod.masterbundle and then do it again, because i can't see anything, add me on discord TERROR#2080

**Comment by WW-TC** [comment]
I send you friend on Discord, I changed Unity Security perms on my PC to full access, lets give it a shot

**Comment by Trojaner** [comment]
For God's sake, the GitHub issue tracker isn't some kind of chat platform.
You keep spamming notifications and emails to people who aren't related.

**Comment by TH3AL3X** [comment]
Fixed, just srry we was trying to figure it

**Comment by WW-TC** [comment]
Thanks for the help
