### ISSUE TITLE
Overturned vehicles in safezones

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#1821]
I am having trouble getting rid of these
![Screenshot_2](https://user-images.githubusercontent.com/35383961/84606112-ecc31700-ae70-11ea-9a10-e6996a199a58.png)

**Comment by TH3AL3X** [comment]
I do not think its the unturned, also the safe areas are protected from the carjack, possibly it is a player who gets into the helicopters and jumps ...

**Comment by Mithallas** [comment]
What are you talking about? The problem is there is no way to remove these overturned vehicles. All it takes is a player to invert their vehicle while above the liberator and then jump out.

**Comment by SDGNelson** [comment]
Air traffic control on the Liberator is not happy about this. How about if the carjack is changed to allow admins to use it in the safezone, but not regular players?

**Comment by Mithallas** [comment]
I had instances where people get them stuck inside the liberator or glitched halfway in the walls, might be tough to get those out with a carjack...Would it be possible to allow admins to destroy the vehicles somehow in cases where they still cannot be moved by a carjack?

**Comment by SDGNelson** [comment]
Will do the carjack change. In the meantime there are some plugins with commands to destroy focused items like that, but I would also like to add a built-in function for it at some point.

**Comment by Mithallas** [comment]
Oh I wasn't aware cartman updated WreckingBall a few weeks ago, sorry if this issue was unnecessary! Thanks Nelson, always a pleasure

**Comment by Johnanater** [comment]
I've found an APC *inside* the Liberator on my server before, so some sort of Vanilla tool to deal with this would be nice. Maybe something to move/teleport the vehicle away like admins can with buildables?

**Comment by SDGNelson** [comment]
In the next update tools like carjacks and lockpicks can be used by admins in the safezone to cleanup stranded vehicles.

**Comment by PandahutMiku** [comment]
> In the next update tools like carjacks and lockpicks can be used by admins in the safezone to cleanup stranded vehicles.

Is there anyway it could be a configurable option to let all Players use carjacks, maybe just on the vehicles they or their group owns?

**Comment by SDGNelson** [comment]
Hmm... I would suggest an event that plugins can use to override item usage in safezones, but the clients need to predict the usage as well.

**Comment by SDGNelson** [comment]
I think the intention was originally to prevent griefers from interfering with other players cars in the safezone, so it should be fine to allow non-admins to carjack their own vehicles and repair the tires in safezones. This has been changed for the next update.
