### ISSUE TITLE
mega zombie bug

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#1827]
on maps like russian, france and germany, we have found a bug related to mega zombie.
1. you get the quest and and wait for mega zombie to spawn
2. you leave the server and join with different character from lobby
3. you kill the mega 
4. again you leave the server and join with different character.
players are killing alot of mega zombie like this and getting huge amount of loot.
also sorry i dont remember the names of the quest.

**Comment by SDGNelson** [comment]
Interesting way to abuse it... Maybe there should be a timer between spawns for quests? Will think about it.

**Comment by aman7** [comment]
also found that they place bed there and tpa request to friend, who have active quest. this is also a way to spawn the mega. for modded servers.

**Comment by SDGNelson** [comment]
In the next update an option has been added to gameplay config for the minimum interval between boss spawns for quests. The default is 10 minutes, and resets if the boss despawns.
