### ISSUE TITLE
BattlEye Halo

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#1828]
Hi Nelson,
I've seen that there is a BattlEye Halo now that is given to people that were banned by BattlEye falsely.
As you might remember, I was falsely banned too but haven't got that item.
Would be awesome if you could somehow give me that item too, so I can remember how you helped me ❤️

**Comment by SDGNelson** [comment]
Sure, it has now been granted to your inventory. The item was added recently otherwise you would have it from your unban.
