### ISSUE TITLE
How to fix this Animation?

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1829]
https://www.youtube.com/watch?v=WcWQ5hgVJUU

I created this Animation in Blender 2.8
It's Human from Unturned

**Comment by SDGNelson** [comment]
Outside the scope of this repo, but there are some tips for exporting animations here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Animation.md
