### ISSUE TITLE
Incorrect collision handling

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1830]
When I tested **CollisionEventHook** on **Item** in detail, I noticed that if the trigger collider is less than _1x1x1_, then during the player’s movement, it doesn’t work correctly. I conducted an experiment, made a collider that constantly crosses the player’s collider, even taking into account the twitching of my hands while running, and assigned the function **GameObject.SetActive(true)**. As a result, it was called many times, although the trigger collider still crossed the player’s collider, but if you make a size of _1x1x1_ or more, then everything works fine. Why does Unturned handle collisions this way? This is normal?

**Comment by SDGNelson** [comment]
There could be a variety of reasons, for example the player sweep might skip through it at certain angles. If your collider has a rigidbody then enabling CCD might help.
