### ISSUE TITLE
france vehicle spawn issue

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#1834]
in France map, i have set all vehicle's max instance to 1 in config.json
`"Max_Instances_Tiny": 1,
      "Max_Instances_Small": 1,
      "Max_Instances_Medium": 1,
      "Max_Instances_Large": 1,
      "Max_Instances_Insane": 1
`
 but when i load the server, i see something like this in console
Level Overrides Config: Vehicles.Max_Instances_Large -> 48
also the same 48 i see while joining the server.
![france](https://user-images.githubusercontent.com/6502438/85099118-294c9500-b21a-11ea-8446-dd6d804a63cd.png)

any idea or suggestion how to fix it?

**Comment by SDGNelson** [comment]
"Level Overrides Config" means the France map has specified a different value for Max_Instances_Large. This feature should probably be changed to override the default unless the server owner has specified a value.

**Comment by SDGNelson** [comment]
In the next update level configs only override the server config if the server is using the default value. (on a per-property basis)
