### ISSUE TITLE
Firerate value for modded tactical attachment

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1835]
Noticed that firerate value for adaptive chambering is 1 by default. If you want to set bigger value for it - next value which does impact is "2" which is way too big. If I set it to 1.2 - it breaks attachment and doesn't give any boost for firerate. Maybe its possible to make decimals work for this so we could increase firerate in small steps?

**Comment by SDGNelson** [comment]
Unfortunately this will probably not be changed because the firerate is measured in a fixed number of ticks. Hypothetically I would like to rewrite some of the related code, but that would be after the netcode and UI reworks.
