### ISSUE TITLE
Devkit LandscapeHoleVolume bug

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1836]
So I was making trenches for my map in Devkit and I placed plenty of LandscapeHoleVolumes. The problem is, after placing some amount of LandscapeHoleVolumes I had trouble with placing more: They would actually appear in the hierarchy, I could move them, but they wouldnt have the highlighted collider thing and wouldnt cut out the terrain. So basically they were useless. Is this a bug or its supposed to be this way? If yes, then how can I make trenches for my map, because I will need plenty of LandscapeHoleVolumes to cut out the terrain for all the trench lines.
![20200619213151_1](https://user-images.githubusercontent.com/59206749/85196356-74ca7600-b2e2-11ea-8076-0d5ec22532b7.jpg)

**Comment by Renaxon** [comment]
I would assume you hit the limit of the hole volumes (16). Hole volumes are quite performance intensive so it's not really a good idea to utilise them in this way. For what you are doing it'd probably be best to have some objects resembling your trench portions and add some dirt objects to make them flow with the terrain (once again custom objects for dirt in this case would help).

**Comment by SDGNelson** [comment]
Renaxon is correct that there is a limit of 16 holes. I agree with him that for trenches the best approach would be a skirt of dirt around the lip, and to simply lower the heightmap underneath the trench models.
