### ISSUE TITLE
Problems with logic in NPCs

### ISSUE THREAD

**Issue by DevInc0** [SmartlyDressedGames/Unturned-3.x-Community#1839]
Can not add logic for item condition in responses.
I just can not check the absence of the item in the player's inventory.
```
Response_#_Condition_#_Amount 0
Response_#_Condition_#_Logic Equal
```
or
```
Response_#_Condition_#_Amount 1
Response_#_Condition_#_Logic Less_Than
```
does not work

**Comment by MrObi123** [comment]
Can you show me your full code please? Maybe I can help out like I've helped many people on the discord.

**Comment by MrObi123** [comment]
I reviewed the code and it should work, but it doesn't.
It's probably something in the Unturned logs that is configured this way, so you can't make anything equal to 0.

**Comment by SDGNelson** [comment]
Interesting case. Right now the item condition assumes you want `>= amount`. Converting this to a "logic" condition seems reasonable.

**Comment by MrObi123** [comment]
> Interesting case. Right now the item condition assumes you want `>= amount`. Converting this to a "logic" condition seems reasonable.

Is there a way you can fix this, or ain't it possible?

**Comment by DefaultDev0x101** [comment]
This would be a very useful addition.

**Comment by MrObi123** [comment]
> > Interesting case. Right now the item condition assumes you want >= amount. Converting this to a "logic" condition seems reasonable.
> 
> This would be a very useful addition.

Yes it would.

**Comment by MrObi123** [comment]
I'm surprised nobody else noticed this before.
