### ISSUE TITLE
Unofficial modules not supported kick

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#184]
So, simple as that: players getting kicked out from the server after a short time due to unsupported modules.

**Comment by Trankvil** [comment]
i have problec kicked BattleEye

**Comment by Trojaner25** [comment]
Temporary Workaround: Delete Community Module in Unturned/Modules.

**Comment by aviadmini** [comment]
It's been deleted with *another* update
#closerequest
