### ISSUE TITLE
EPluginWidgetFlag for hiding health bars and chat from a plugin.

### ISSUE THREAD

**Issue by XanderCodes** [SmartlyDressedGames/Unturned-3.x-Community#1840]
Heyo!

I currently have a custom UI plugin in the works for an RP server, and in using EPluginWigetFlags.Modal, I was unpleasantly surprised that it didn't hide the game chat, hot bar, or most annoyingly, the health bar panel. For something like what I'm developing, which takes up a large amount of screen real estate, it would be super nice to be able to do this. I know it's possible to outright disable them with a custom map, but having the ability to toggle them on and off if you don't want to make custom health bars and death screens would be super helpful!

Cheers!

**Comment by TH3AL3X** [comment]
Duplicated post https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1242

**Comment by XanderCodes** [comment]
> I think nelson forgot to add that function ...
> Duplicated post #1242

Haha, I see, well hopefully he can add it, would be a great thing to have!

**Comment by SDGNelson** [comment]
Earlier this year flags to hide the life stats and status icons were added, and it is possible to layer plugin UIs over the game UI now.
