### ISSUE TITLE
How to off Blood?

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1841]
When you hit someone many times, there is a lot of blood because of which frames per second (FPS) are greatly lost

Please note that this did not happen before, it has appeared since version 3.20.5.0

Thank you for your attention

**Comment by TH3AL3X** [comment]
You can do it with a plugin

**Comment by TH3AL3X** [comment]
https://github.com/TH3AL3X/AntiBlood/releases/tag/0.0.0.0
I think it also removes UI's too

**Comment by DiFFoZ** [comment]
> When you hit someone many times, there is a lot of blood because of which frames per second (FPS) are greatly lost

In options has `Show Blood Splatters`. Turn off this.

**Comment by FANYPLAYRU** [comment]
It's just that before you could turn it off in the game settings, but now this setting is not available, which is strange.

When the setting was and could be turned off, it was not particularly lagged because of the blood, and then removed and still lags with a large amount.



> In options has `Show Blood Splatters`. Turn off this.

Okay I'll try

**Comment by FANYPLAYRU** [comment]
Don't working

**Comment by FANYPLAYRU** [comment]
I don't have this option

**Comment by TH3AL3X** [comment]
> Don't working

You mean the plugin yes ?

**Comment by DiFFoZ** [comment]
> I don't have this option

You're sure u don't have this? 
![image](https://user-images.githubusercontent.com/48765566/85744339-05fc7b00-b72f-11ea-879a-23be65537630.png)

The option in `Configuration->Options->Show Blood Splatters`.

**Comment by TH3AL3X** [comment]
> > I don't have this option
> 
> You're sure u don't have this?
> ![image](https://user-images.githubusercontent.com/48765566/85744339-05fc7b00-b72f-11ea-879a-23be65537630.png)
> 
> The option in `Configuration->Options->Show Blood Splatters`.

I think he means, he wanted for his server

**Comment by FANYPLAYRU** [comment]
No, I meant for myself. I didn't know what was moved to another section, thank you for your time!
