### ISSUE TITLE
Steam groups bypass group limit

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#1847]
Steam groups are bypassing max group limit setting in config.json

**Comment by SDGNelson** [comment]
That member limit is for the in-game "dynamic" groups players can create. Unturned has no control over Steam groups, so an option there might be to disable Steam groups and use in-game groups instead.

**Comment by rube200** [comment]
U can use a plugin to check and Kick the player, warning him to change his group
