### ISSUE TITLE
Problem with human Animation

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1848]
Why can't I animate the character completely, but only my hands?
If there is a problem with the constant animation of the character (in the sense of moving the body when turning the character up and down), then you can add a degree to the current position of the body or head(neck) during animation.
If there are no problems, then why not make it possible to animate the entire body of the character.

I think that some mods can be made more realistic and correct.

Example: I have a mod for the shield, I made an animation of the impact for it and added a recoil effect (Turning the body back a little and automatically stabilizing the head (As in reality)), but it didn't work, only the hands worked.

Yes, there may be problems with moving the entire character, but I think this is the problem of those who create mods.

Still have a few ideas if you implement this, add option (in config or unity) position the camera in the game with animations (If false then the camera position will be static if set to true it will move on animation)
Add the ability to move the character itself (in the game) when playing the animation (Example: Mod for parkour or workout, the character jumps and climbs on the roof of the house, when the animation ends, it remains on the roof, and does not return to its place) (false/true)
False/true position of the hit box during animation (follow the character or not)
The ability to link an object to the left hand (the same example with Boxing gloves)
Ability to play animation by item ID (Example: /animation "Item ID" "Name of Animation" /animation 15 Equip or /animation 15 1 (1 is the item ID in Animations prefab))
You can make reverse animations (Example: the animation is Played as the player took out the item, you can also enable the animation to be ignored as he puts it back.) And do this to everything, for example the player puts the item, put and pulls the hand back (For example in animations where the player actually puts the item (useful for LifeRP), although this can be implemented without back animation)
Add the ability to animate a character when using transport, input/output, horn, lights, Music, etc. (Ctrl)
Add animating when using the items (B/N) (Example: Inclusion of headlamp torch, the animation plays as the player touches the "button" of the torch and at the specified timing in the config item it is included, also with an ordinary torch (+ a playing sound), also possible to make a radio (earphones/columns))

A lot of things still come up, think there is a chance that it is implemented and I can do the normal animation for his shield, or the following mods (If I leave the game)
I will be very grateful if you do at least part of what I have listed! And I will be glad if you read it all!

**Comment by FalkenJr** [comment]
Most of these changes are coming in Unturned II (or 4.0, whichever name you prefer) as the 3.0 character rig is horrible compared to the newer one and the character systems being built for UII will have much better support for character animations than 3.0's

As for the other additions, it's (in my opinion) far too late in Unturned 3's lifespan to have most of the stuff you want done - Nelson's devoting most of his time to Unturned II now, while I won't speak for him I won't assume he'll be interested in spending time implementing any of your feature requests

**Comment by FANYPLAYRU** [comment]
> Most of these changes are coming in Unturned II (or 4.0, whichever name you prefer) as the 3.0 character rig is horrible compared to the newer one and the character systems being built for UII will have much better support for character animations than 3.0's
> 
> As for the other additions, it's (in my opinion) far too late in Unturned 3's lifespan to have most of the stuff you want done - Nelson's devoting most of his time to Unturned II now, where all these feature requests may have a better shot at being implemented


I agree with you, but:

I'm just starting out and it's easier for me to work in Unity, I haven't worked in UE and it will be difficult to get used to something different and new.

Players who do not have powerful computers will not be able to play 4.0

Some people don't like 4.0 and may stay in the old one

Especially it is not visible that Nelson devoted time to 4.0, as there were many bugs that were not even answered, including mine. (I may be wrong because I didn't check and I don't know how and what Nelson does himself)

There will be a lot of people left in this game, and even adding one of the above will give it a fresh breath of air

Making something for those who can't play or don't want to play 4.0 is nice enough

**Comment by FalkenJr** [comment]
> I'm just starting out and it's easier for me to work in Unity, I haven't worked in UE and it will be difficult to get used to something different and new.
> Players who do not have powerful computers will not be able to play 4.0
> Some people don't like 4.0 and may stay in the old one

100% fair, I'm not moving to Unreal either since Unity's so much better for performance (and I've also got experience with it too)

> Especially it is not visible that Nelson devoted time to 4.0, as there were many bugs that were not even answered, including mine. (I may be wrong because I didn't check and I don't know how and what Nelson does himself)

Honestly I'm not sure what's going on either, since 4.0's development seems fairly slow going so far (I'm assuming most of the work is being done on internal code stuff rather than proper assets though, explains why only now we're getting trees and day/night cycle after about 2 years)

> There will be a lot of people left in this game, and even adding one of the above will give it a fresh breath of air
> Making something for those who can't play or don't want to play 4.0 is nice enough

Personally I think the curated map teams and code-savvy server hosters are doing a good enough job of keeping the game going, but I also think open-sourcing the game and looking into community-submitted updates might be a very interesting option (plus it'd let everybody work on adding their feature requests instead of adding them to Nelson's backlog)

**Comment by FANYPLAYRU** [comment]
Yes, good. I'll wait for an answer from Nelson

**Comment by SDGNelson** [comment]
Again sorry, but FalkenJr is correct that these are almost definitely not going to happen in 3. The animation blending is very simple in that it plays the movement animation, layers any weapon animation onto the arms, and then rotates the torso for the aim pitch. On the bright side they are already supported in 4.
