### ISSUE TITLE
Problem with Example 

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1849]
I noticed that there are no necessary objects or I don't know where to get them, for example, a Headset, I want to try to make something like headphones.

Also, I didn't find the sound of pressing the flashlight button (in aitem), so there is no way to notice this sound, or am I wrong?

**Comment by FANYPLAYRU** [comment]
Or walkie-talkie for example, there is also no sound when the microphone of the walkie-talkie is turned on or off (when you press the Alt)

**Comment by FalkenJr** [comment]
For the most part you'll have to trial-and-error item models like headphones, the example packages are the **bare minimum** necessary for you to get started with modding
Walkie-talkie and flashlight sounds are handled by audio source effects in Unturned\Bundles\Effects\General, though I believe walkie-talkie sounds are hardcoded into the game (not sure why)

**Comment by FANYPLAYRU** [comment]
Yes, you are right

**Comment by SDGNelson** [comment]
Sorry, but FalkenJr is correct that those effects are hardcoded for the moment. Aside from the hardcoded IDs those items are set up the same as a normal item.
