### ISSUE TITLE
Youtube videos or stream from server to client

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#185]
What about playing youtube videos or just mp3 files from server to client?
First option: Streaming videos by URL
Second option: Having all MP3 files on serverside and just stream to client (No need for workshop).
Another option: send calls from server to client and then play the music from client.
Right now you need to make effect per file and etc.. (Also takes a lot of space)
Thanks, Roy.

**Comment by Trojaner25** [comment]
I have an idea for this and I'd love to add it to the community module after my pull request gets accepted:
Streaming mp3 etc directly from server would cause a lot of bandwidth and lag. Instead the clients have to fetch the audio from the internet.

I could implement .m3u which is an audio format to stream music into the module. The Unturned server itself would not stream those, another server instance (e.g. your own one or a public radio for example) would do that.

**Comment by Trojaner25** [comment]
Btw, YouTube ToS would not allow that

**Comment by RoyIL** [comment]
Oh right, Forgot about community module.
So probably sending calls to client gonna do that.
I just think having 500MB - 1.5GB of music is useless.

**Comment by LuxarPL** [comment]
What about streaming radio stations like in ETS2?

**Comment by Trojaner25** [comment]
I dont know what ETS2 uses for that but I think it uses m3u too; at least its possible with that too

**Comment by Trojaner25** [comment]
Can be closed?
