### ISSUE TITLE
[BUG] Friendly and neutral animals going straight to the player

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#1850]
`AlertTool.alert` calls `Animal.alertPlayer` for every player nearby, but `Animal.alertPlayer` does not check if the animal is `EAnimalBehaviour.OFFENSE`, causing every animal trying to hunt the player

**Comment by SDGNelson** [comment]
Are you calling either of those functions? `AlertTool.alert` only calls `Animal.alertPlayer` if the animal behavior is `EAnimalBehaviour.OFFENSE`.

**Comment by iBowie** [comment]
But how to explain defense animals running right to the player after getting hit?

**Comment by SDGNelson** [comment]
What did you damage them with? Weapons should be calling `Animal.alertDamagedFromPoint` which should cause non-aggressive animals to run away.

**Comment by iBowie** [comment]
Sorry for bothering you, i couldn't reproduce this bug in the latest version. I just remember this bug was a thing.

**Comment by SDGNelson** [comment]
Thanks for the confirmation.

**Comment by iBowie** [comment]
https://www.youtube.com/watch?v=P-zt0UnWFAM

**Comment by iBowie** [comment]
@SDGNelson i was able to recreate it. Deer started to run in to me after i walked close to him on the ice

**Comment by SDGNelson** [comment]
Odd, thanks for the video. Depending on the map it might somehow be related to the ice being over the water. I will check into it for the next update.

**Comment by SDGNelson** [comment]
Does your server have any plugins that affect the animals? Since you mention those functions in your original post I wonder if your code might be calling them. I double-checked and there is nowhere in the vanilla code that would be doing this, nor was I able to replicate it.

**Comment by iBowie** [comment]
No, every plugin that is on the server is made by me, and I'm sure that none of them is calling AlertTool.alertPlayer. Also, if it helps, when i got closer to the coast deer ran onto it. So something related to ice and water being underneath

**Comment by SDGNelson** [comment]
I think there might have been some fix related to water? Feel free to comment and I will re-open.
