### ISSUE TITLE
Give us modders the warm & burn effect from the campfire

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1852]
Make it so that we can use the warm & burn effect from the campfire for modding purposes. This can be useful to make more items, effects, objects or whatever like flamethrowers & molotovs. We **_somehow_** got access to the acid effect but it would be nice to have what the campfire had.

Unless talented modders out there can figure how to get it, I'm assuming that we can't have our hands on this feature.

**Comment by SDGNelson** [comment]
In which context? I think someone made a molotov grenade recently. Fire should be an option anywhere the acid is an option.

**Comment by OneManOperative** [comment]
I'm guessing that we couldn't get the warm & burn effect as easily as the acid. I'm not skilled in making effects but I just think it is inaccessible for now.

**Comment by SDGNelson** [comment]
For an effect asset? Setting the Splatter_Temperature to Burning should do the trick.
