### ISSUE TITLE
A bug affecting pvp

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1855]
[![](http://img.youtube.com/vi/l14nWnecjsw/0.jpg)](https://www.youtube.com/watch?v=l14nWnecjsw"")

**Comment by SDGNelson** [comment]
Which area / model were you standing on in the video? The server version of its collision might be mismatched blocking the shots.

**Comment by TH3AL3X** [comment]
It's the washington crane

**Comment by TH3AL3X** [comment]
Anyways i got this video from a user of my server, but i can't test it if is a problem of easy mode and normal mode

**Comment by baranmod** [comment]
Its pretty old bug. Some barricades aren't rendered yet player still gets hitmark

**Comment by SDGNelson** [comment]
Double-checked and the crane collision does match. Most likely @baranmod is right that the client did not locally have the barricades. Ideally the replication distances will be made consistent with future network upgrades - players are loaded at all distances for now. Recently the **draw** distances were finally made consistent between players and structures.
