### ISSUE TITLE
Ignored parameter in ChatManager.say

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#1857]
In this function in `ChatManager`, the `mode` parameter is ignored.

```
public static void say(CSteamID target, string text, Color color, EChatMode mode, bool isRich = false)
{
	SteamPlayer steamPlayer = PlayerTool.getSteamPlayer(target);
	if (steamPlayer == null)
	{
		return;
	}
	ChatManager.serverSendMessage(text, color, null, steamPlayer, EChatMode.SAY, null, isRich);
}
```

**Comment by SDGNelson** [comment]
The `ChatManager.say` method is quite old, and was primarily kept for backwards compatibility with plugins. Prior to `ChatManager.serverSendMessage` being added the `mode` parameter was more important, whereas now the distinction is essentially a client->server flag for who to send the message to. Does your plugin use mode for something?

**Comment by TH3AL3X** [comment]
Probably is ignored by CSteamID target

**Comment by IAmSilK** [comment]
I'm not using the command for anything, it was just something I happened to spot. Didn't know it was a discontinued command and I see now the client doesn't use it for anything when receiving a message.
