### ISSUE TITLE
Request: No build volumes

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1858]
Would it be possible to implement some kind of no build volumes (dev kit editor) which would prevent players placing barricades/structures in it? I'm aware there are some plugins which might help to do this, but it would be much more comfortable to have such feature in map editor

**Comment by Renaxon** [comment]
This can already be achieved by placing player clip volumes and disabling the player clip on them.

**Comment by baranmod** [comment]
ahh, thanks for this tip!
