### ISSUE TITLE
Server disappearing from list from time to time. No BOTS or other forbidden stuff.

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#186]
Title basically says everything. My servers keep disappearing from server browser list. Only way to fix it is to change server name. But its temporary, until restart. Then I need to change it again...

Tried to delete plugins one by one (using avilobbymess, aviadmintools plugins which I believe might be somehow related to this issue). Trojaner explained that these plugins doesn't mess with bot counts though. Anyways, after deleting these two plugins, issue still remains.

**Both servers are hosted on different hosts, so the problem can't be in ports etc.

**Comment by baranmod** [comment]
Update #2 
Deleting mentioned plugins actually helped. So the problem is in these plugins. Even though these plugins don't mess with bot counts.  So need answers if its forbidden to change lobby (the way it looks) and list server as a non-workshop server even if these workshops are simple UI effects...

**Comment by KlaasM** [comment]
Probably something to do with the faked player counts tweak as documented in the [3.23.2.0 Update Notes](http://steamcommunity.com/games/304930/announcements/detail/1582318407721833475)

Most likely one or more plugins with >1 bot players which causes the server to not show up in the server list.

**Comment by KlaasM** [comment]
#143

**Comment by baranmod** [comment]
Thats the thing. There are no plugins which faking players count. Avilobbymess nor aviadmintools messes with bot counts, but still getting banned because of these (not sure which one exactly)

**Comment by KlaasM** [comment]
As far as I know there's no documentation on anything other than faked player counts causing the server to not show up in the server list. We'll have to wait for Nelson to confirm this.

**Comment by baranmod** [comment]
So now I am pretty sure that servers disappearing from list issue isn't related to plugins at all. I've tried to run server without most of the plugins (only uconomy and shop). Same thing happens...

**Comment by Trojaner25** [comment]
Does the server appear in friends / favorites or the steam server browser?

**Comment by baranmod** [comment]
yes, it does

**Comment by baranmod** [comment]
Oh, it actually appears on history and favorites tabs. Can't find it in friends tab tho. Even if some steam friends are playing on it

**Comment by SDGNelson** [comment]
Yep @KlaasM, the only change preventing server visibility was for >1 bot players.

**Comment by baranmod** [comment]
well, then something broke in some other part. I can repeat: I've never used any kind of plugins to increase bot size over this 1 default bot (not even sure why this "1" exists) and I've never actually heard of possibility to add these bots until this issue appeared for me. Server simply disappears from list randomly, no errors, no warnings etc...
