### ISSUE TITLE
Bug with ChatManager

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1861]
ChatManager.serverSendMessage

Since with long texts this method stays between the lines and get bugged, I don't have a photo to show and I can't show you anything either, I'm banned, pd this issue happens when you write 3 lines in the chat, I think the solution is very basic, changing the size of the writing chat.

Weird example maded in painterino:
![image](https://user-images.githubusercontent.com/13141042/86542382-a57ef200-bf15-11ea-837f-c549da2dd181.png)

**Comment by SDGNelson** [comment]
The difference is Rocket's `UnturnedChat` methods split long messages into multiple calls to `serverSendMessage`. Ideally the client UI will support vertical layout at some point, but no ETA on that.
