### ISSUE TITLE
Big problem with ban via console

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1863]
For some reason it does not allow putting links with ban command via console

**Example:** /ban STEAMID "Appeal here: https://discord.gg/D6ZubUv" 3600

Video example of the problem
[![](http://img.youtube.com/vi/69Of0L-RPzk/0.jpg)](https://www.youtube.com/watch?v=69Of0L-RPzk"")

**Comment by SDGNelson** [comment]
Unfortunately Unturned's commands split on '/', and do not support escapes. Unturned II handles this better.
