### ISSUE TITLE
Arena airdrop

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1864]
Currently the config `Use_Airdrop` does not stop airdrops on arena

**Comment by SDGNelson** [comment]
Interesting point. At the moment it enables the timer for airdrop events. I will change it to apply to arena as well.

**Comment by SDGNelson** [comment]
Thanks for raising this! In retrospect from a player's perspective this would definitely be viewed as a bug. Fixed in the next update.
