### ISSUE TITLE
Some more of my suggestions for modding, this time for melee

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1865]
The first one would be for my upcoming mod but the others are for other projects or for modders hoping to make more melee stuff in the workshop. 

- As seen from the consumables giving an item once used, make it so that melees have something similar or identical to it wherein once the melee item is broken, it will change to a different item. Optionally, this feature could come with an auto-equip data that lets you equip the resulting item that came from the previous melee item you broke.

- Give melees the option to have a range of where it can aggro AI so that modded melees can attract every AI around it or not aggro at all when used.

- If possible, try to make stun open to customization. Give melees the option to either stun by damage amount (the stun mechanic we have rn) or stun depending on number values. This makes melee stun randomly, always if 100%, or not stun at all if put down on 0%.

- Final time I'll say this because it is personally one of my most wanted features to come for melee but it's getting repetitive. Give melees more animation options, let sprinting animations play as an option when running with melees. And again for the last time, if possible, let at least 3 swinging animations play when using either weak or strong attacks. This is somewhat possible because animals can have up to 3 sounds when they themselves are either in panic or when roaring. Nelson could try to replicate this to melees but if this is really hardcoded, luckily this is the last time I'll ask for it.

These are all of the suggestions I could think of for now for the modder's galore. I might come up with some more in other modding aspects so that's all for today. Modders if one of these is possible please tell me, I don't remember every modding feature so some stuff that I mention might already exist.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
