### ISSUE TITLE
Little kid wants white beret

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#1866]
![image](https://user-images.githubusercontent.com/43498426/86803391-9cf5fb00-c07e-11ea-95a5-2f063e39e759.png)

> Здравствуйте,я по делу.Дело в том,я хочу получить белый берет от нельсона и для этого,мне нужны исходники работающего читы.Manager или как там его,что обходит баттл ай.Готов заплатить,если вы будете согласны.

What to do with this guy?
https://vk.com/id416082372

**Comment by TH3AL3X** [comment]
This doesn't apport anything to the community, don't make Nelson waste his time...

**Comment by GazziFX** [comment]
@TH3AL3X If he gives such a task, then he should be responsible
