### ISSUE TITLE
FPS Lag spikes while load big structures

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1867]
Hello good afternoon, I wanted to report that this problem has been with us for a long time, many players report that there is a load LAG, and this makes it impossible to play or have a PVP, we do not use any workshop mod and we have a good server, when we remove structures it improves a little but it is still a nuisance, and I wanted to see if you could solve this optimization problem.

Server **CPU** and **RAM**:
![image](https://user-images.githubusercontent.com/13141042/86817282-185aab00-c085-11ea-9673-006f6a31ede7.png)

Please solve this problem, also I have previously made a post about this and you did not check it, I have this old video where I show the problem, I cannot record anything because I am banned from unturned.
[![](http://img.youtube.com/vi/jA7eCRuTI2E/0.jpg)](http://www.youtube.com/watch?v=jA7eCRuTI2E"")

**Comment by PandahutMiku** [comment]
I think you're talking about
#936
#1273

This is a really old issue that isn't that simple for Nelson to fix. Perhaps Nelson could give us a configuration option to have clients load in the entire map's barricades/structures always. I don't know about the performance implications though.

You might want to try searching for an issue to see if it was already reported before opening two issues about the same thing

**Comment by TH3AL3X** [comment]
> I think you're talking about
> #936
> #1273
> 
> This is a really old issue that isn't that simple for Nelson to fix. Perhaps Nelson could give us a configuration option to have clients load in the entire map's barricades/structures always. I don't know about the performance implications though.
> 
> You might want to try searching for an issue to see if it was already reported before opening two issues about the same thing, Although I wouldn't be too surprised if you searched and didn't find those issues at first, GitHub Search isn't the best.

The truth is that it takes too long, and I think it should be a priority since, for these consequences, some servers are unplayable and require maintenance with administrators...

**Comment by PandahutMiku** [comment]
> > I think you're talking about
> > #936
> > #1273
> > This is a really old issue that isn't that simple for Nelson to fix. Perhaps Nelson could give us a configuration option to have clients load in the entire map's barricades/structures always. I don't know about the performance implications though.
> > You might want to try searching for an issue to see if it was already reported before opening two issues about the same thing, Although I wouldn't be too surprised if you searched and didn't find those issues at first, GitHub Search isn't the best.
> 
> The truth is that it takes too long, and I think it should be a priority since, for these consequences, some servers are unplayable and require maintenance with administrators...

This bug really doesn't make any server unplayable. It is certainly annoying and even is in video's like Nylex's (in his latest series he has a lag line right in the doorway of his shop which he tries to cut around, just unfortunate). But I wouldn't say it makes anything unplayable and the changes that would involve fixing it would be large. In my opinion it doesn't make much sense for Nelson to redo a system for Unturned 3.0 instead of just focusing on Unturned II.

**Comment by TH3AL3X** [comment]
> > > I think you're talking about
> > > #936
> > > #1273
> > > This is a really old issue that isn't that simple for Nelson to fix. Perhaps Nelson could give us a configuration option to have clients load in the entire map's barricades/structures always. I don't know about the performance implications though.
> > > You might want to try searching for an issue to see if it was already reported before opening two issues about the same thing, Although I wouldn't be too surprised if you searched and didn't find those issues at first, GitHub Search isn't the best.
> > 
> > 
> > The truth is that it takes too long, and I think it should be a priority since, for these consequences, some servers are unplayable and require maintenance with administrators...
> 
> This bug really doesn't make any server unplayable. It is certainly annoying and even is in video's like Nylex's (in his latest series he has a lag line right in the doorway of his shop which he tries to cut around, just unfortunate). But I wouldn't say it makes anything unplayable and the changes that would involve fixing it would be large. In my opinion it doesn't make much sense for Nelson to redo a system for Unturned 3.0 instead of just focusing on Unturned II.

In my server it is very serious for us, since there are many people who have big bases, not even with a decay plugin are we controllers to handle this, and the only way is to do wreck and wreck, and probably that roleplay servers are also affected by this.

**Comment by SDGNelson** [comment]
Thanks for linking the relevant post @PandahutMiku! There has been some work on step 1 since then, but other tasks have taken priority.
