### ISSUE TITLE
Kicking for inactivity still crashes servers

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#187]
For some reason this issue is still a problem, though noted in the patch notes a few weeks back.

Logs: https://pastebin.com/MWU8ACLi

**Comment by WarpKat** [comment]
Is it a player that becomes inactive or AFK?  I've not seen this issue, but I'm also not automatically kicking them for this.  I do it manually, but it doesn't seem to crash anything.  Maybe it's a plugin issue?

**Comment by Trojaner25** [comment]
It was confirmed by Nelson that this is an issue (#154 )

**Comment by N1GHTPATROL** [comment]
No, this problem is indeed still active.
