### ISSUE TITLE
Crafting bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1870]
I got so many reports from users, they told me "crafting" like beds, oxygenators etc.. are not working, they can't craft it, and we don't have any craft plugin or something else

**Comment by PandahutMiku** [comment]
Any mod the client has installed will show the crafting recipe regardless if the server has it or not. It just won't work if they try to craft it.

**Comment by SDGNelson** [comment]
Thanks for the report! This should be fixed in the .1 patch shortly.
