### ISSUE TITLE
New "h" character is a bit messy

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#1871]
![image](https://user-images.githubusercontent.com/66274985/87190321-2b21e980-c2ea-11ea-9b6d-c997a5830415.png)

Hard to explain but on the lowercase h, there's a bit of an error on the curve where it is not smooth.

**Comment by SDGNelson** [comment]
Unfortunately this is a limitation of signed distance field text rendering. It sounds like the text will get a bit crisper in future TMP versions however.
