### ISSUE TITLE
Vehicle Physics

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#1872]
It seems with the latest update Physics are wonky now. You can get practically sucked into the ground as a race car and getting out will put you at the nearest spawn point.
https://www.youtube.com/watch?v=DpiBdlF9up8&feature=youtu.be

Putting stuff on vehicles just generally seems to bug stuff out.

Here's an endlessly flipping APC
https://www.youtube.com/watch?v=u0tGhPdMGWI&feature=youtu.be

It seems putting a plate on the front of a vehicle makes it literally stuck to the ground
https://www.youtube.com/watch?v=Avs_MV6NdeU&feature=youtu.be

You can get your vehicle stuck in the ground pretty easily, and getting out will sometimes put you at a spawn point since it can't find an exit location.

Oddly enough, none of this happens in singleplayer. But as far as I know, all vehicle physics are client-side.

**Comment by TH3AL3X** [comment]
You should to fix this, i have a own Anti-Cheat for detect noclip with vehicles, and some people are getting banned by those bugs... @SDGNelson

**Comment by SDGNelson** [comment]
This is fixed in the .1 patch which should be up soon. It depended on the order of the "bumper" collider because that gets destroyed on the client 🤕 

Generally I recommend against custom "anti-cheat" plugins because any reasonable checks are already done in the base game.

**Comment by PandahutMiku** [comment]
For a bit, it was a good feature
https://youtu.be/T1N43TA3VJM
