### ISSUE TITLE
Unrecognizable characters

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#1873]
![Image](https://github.com/warren39/un/blob/master/img/i1.png?raw=true)

![Image](https://github.com/warren39/un/blob/master/img/i2.png?raw=true)

**Comment by warren39** [comment]
![i1](https://user-images.githubusercontent.com/64722485/87215118-c99f6080-c365-11ea-8acf-a66b40619690.png)
![i2](https://user-images.githubusercontent.com/64722485/87215119-cb692400-c365-11ea-99b0-1518f1070c34.png)

**Comment by TH3AL3X** [comment]
That's normal, unturned is using default character of unity

**Comment by TH3AL3X** [comment]
Pd, is so hard work, because he need to change in every sign the character...

**Comment by warren39** [comment]
Before version 3.20.6.0, It is displayed normally. By the way, How to change the default character to UTF-8 or other?

**Comment by TH3AL3X** [comment]
> Before version 3.20.6.0, It is displayed normally. By the way, How to change the default character to UTF-8 or other?

Idk I didn't know that, probably was a unity update or something else idk

**Comment by SDGNelson** [comment]
Where uGUI and IMGUI used FreeType to dynamically render those glyphs on-demand, unfortunately this newer TMP setup has a pre-rendered atlas for characters. In the meantime it would be possible to use custom signs with the simplified Chinese atlas pre-rendered. I will think about how to handle this for the next update (probably after Elver), perhaps with a per-language default font.

Regarding UTF-8: all game text (e.g. chat, signs, console) uses UTF-8 by default, so you do not need to explicitly change anything.

**Comment by warren39** [comment]
Thanks for help. And the Elver, what is that? looks I miss something.

**Comment by PandahutMiku** [comment]
> Thanks for help. And the Elver, what is that? looks I miss something.

Unturned map coming out this Friday
https://steamcommunity.com/games/304930/announcements/detail/2533786899906381002

**Comment by warren39** [comment]
Oh. Thanks!

**Comment by SDGNelson** [comment]
Good news: this will be resolved on the preview branch in the next day or two, and then in the update on Friday. I evaluated a few options and decided on Noto Sans CJK by Google. Any custom signs using the default ASCII font will automatically have this added as a fallback, so CJK text should work anywhere. There is a fairly high limit on the generation, but a future TMP update will add multi-atlas support for unlimited generations.
