### ISSUE TITLE
How to defend against A2S_INFO DDOS?

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#1876]
A2S_INFO DDOS can also be used to attack Unturned servers. Usually 100 packet servers will not be searchable. Ordinary DDOS defense cannot mitigate this kind of attack. I hope that game authors can give a solution. It is recommended to improve the server to query data. The carrying capacity of the bag!
Or you can add a layer of packet verification to determine whether the real player is querying the server!
An attacker is already collecting the real player IP, and forged the real player IP to attack our server!

**Comment by CatzMR** [comment]
https://security.stackexchange.com/questions/168375/how-to-prevent-tsource-engine-query-ddos-attack/178721

**Comment by SDGNelson** [comment]
I think you brought this up before in issue #1627

It might be possible to bring under the game's control with `MASTERSERVERUPDATERPORT_USEGAMESOCKETSHARE`, but has not been reported as high priority by hosts, and this is the default behavior for most Steam games. Has anyone else been running into issues with Steam query spam?

**Comment by CatzMR** [comment]
@SDGNelson These two are not a problem at all. If you don’t understand what I mean, I suggest you go to Google to search for A2S-INFO DDOS. This attack can be applied to any Steam game server!

**Comment by CatzMR** [comment]
@SDGNelson https://security.stackexchange.com/questions/168375/how-to-prevent-tsource-engine-query-ddos-attack

**Comment by Trojaner** [comment]
I believe this problem must be solved on Steamworks level and not on Unturneds level. You can mitigate it yourself by updating your firewall rules to filter out such traffic.

**Comment by CatzMR** [comment]
@Trojaner The attacker also assumed an Unturned server on the Internet to collect real-time normal player IP addresses, forged normal player IP addresses to attack our servers, and any of our firewall policies were invalid.

**Comment by CatzMR** [comment]
@SDGNelson I hope that the Unturned server can increase the capacity of Steam query data packets. Currently, only 100 Steam query data packets are needed, and the server will start to respond!
Or maybe add a special layer of verification to the game to determine if the real player is querying server information!

**Comment by CatzMR** [comment]
The attack traffic has reached 200Mbps, we cannot defend, hope to get a special mitigation program!
@SDGNelson @Trojaner

**Comment by Trojaner** [comment]
Please stop spamming my inbox.

Like said earlier, the code responsible for handling A2S_INFO is not written by SDG or Nelson. It is written by Valve. Complain to Valve instead here. There is nothing Nelson or anyone else except Valve can do. You can set up a firewall rule that filters out these packets. 

If you have 200 Mbps traffic normal DDoS protection should work. Otherwise, you did not set up your protection correctly.

Consider switching to a GSP that can block these attacks.

More information.
https://security.stackexchange.com/questions/168375/how-to-prevent-tsource-engine-query-ddos-attack
https://forums.alliedmods.net/showthread.php?t=276041
https://forums.alliedmods.net/showthread.php?t=149911

**Comment by nanashi88** [comment]
@CatzMR 
"An attacker is already collecting the real player IP, and forged the real player IP to attack our server!"
could you explain what does that mean?
is it possible to get players ip from other than server side ?

**Comment by CatzMR** [comment]
"Browser": {
    "Icon": "",
    "Thumbnail": "",
The attacker used this setting to collect the player's IP address.
@nanashi88

**Comment by sky-xk-nge** [comment]
@CatzMR They don't use images to get player ip's, they set up an unturned server and use third party software to grab packets containing features, and this server doesn't return any information to the player, the captured ip's are used in UDPcc attacks to fake ip's to attack the server!

**Comment by sky-xk-nge** [comment]
I think the option to not upload server information to the steam list could be added to config, which could bypass the A2S_INFO type of request by allowing players to use a direct connection to the server, or use third-party software to access the server, etc. I m not sure if this idea will work!

**Comment by PandahutMiku** [comment]
Never had issues personally with this, but it's worth noting that it looks like it is patched now (and you can use environment variables to further harden): https://steamcommunity.com/discussions/forum/14/2974028351344359625/

**Comment by SDGNelson** [comment]
The Steam changes mentioned by Miku were a nice surprise. Hopefully they are default soon. In the meantime I will close this issue.
