### ISSUE TITLE
Add support TMP for UI

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#1877]
Can you add support TMP Text, InputField, Button for UI? Unity build-in Text is blurry and not beautiful. 

If signs now support TMP so UI also can support

**Comment by SDGNelson** [comment]
Fair point. Will mark as next update, but that might end up meaning the one after Elver.

**Comment by SDGNelson** [comment]
Added support for the 3.20.7.0 update this Friday.
