### ISSUE TITLE
Modding Problem

### ISSUE THREAD

**Issue by Papa1234567** [SmartlyDressedGames/Unturned-3.x-Community#1878]
Hello, when i use the BundleTool.cs, console give me this errors.
Despite this, the program lets me get the file from unity3d or whatever it's called.
But when I press the item in the Editor to place it, nothing appears. It just doesn't place anything on me.
Many people told me that this is because I am from MAC, but how can I fix it?
![Captura_de_pantalla_2020-07-12_a_las_16 20 36](https://user-images.githubusercontent.com/67819900/87254875-73611900-c45c-11ea-8e36-1306cb85f335.png)

**Comment by SDGNelson** [comment]
It looks like you are using Unity 2019.2+ which may be problematic. The game is currently using Unity 2018.4.23f1 LTS. Off the top of my head I think the line ending warnings are because Unity's older "new script" had LF endings that got mixed with CRLF endings when edited.
