### ISSUE TITLE
Servers keep disconnecting players and freezes

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#188]
Another issue from last week's update. Some servers are freezing randomly, disconnecting all players and when trying to join server again - timeout error. Restart fixes it until another freeze. No errors in console, nothing. However, sometimes server crashes and getting crash log (attached)
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1649332/error.log)

**Comment by N1GHTPATROL** [comment]
Same here. Was just about to make a thread about this. More details >> Players time out upon joining, seeing green on the debug text on the queue screen then going red again as they time out. In addition, this issue seems to happen when logging out in an area of many barricades.

**Comment by joeytheadmingamer** [comment]
Issue is existing here as well, a few unturned servers I am now managing are timing out players as they join, "queue of 1", it seems to exist around barricades and for individuals with slower internet connection speeds.

**Comment by thereis** [comment]
The servers are receiving alot of TCP connections from STEAMPS3 and them freezes and disconnect all players.

**Comment by SDGNelson** [comment]
The STEAMPS3 issue has always existed. I remember posting on the forum about it in 2014 but didn't hear anything back, and it seemed to show up in other games that routed Steam output to the console e.g. ARK Survival Evolved.

In the patch last night I fixed one potential issue that might be kicking a large group of players at the same time.

**Comment by KlaasM** [comment]
Hello @baranmod and @N1GHTPATROL ,

An unstable connection between client and server is causing TCP packet loss.

I've not seen this error on Linux before so it might be a Windows specific issue.

Source: [Problem: AsyncTCPSocket created / destroyes](https://rocketmod.net/forum/thread/4053-problem-asynctcpsocket-created-destroyes/?postID=13384&highlight=STEAMPS3#post13384)

**Comment by baranmod** [comment]
@SDGNelson  this didn't help. Server freezed like 10 minutes after I updated it

**Comment by baranmod** [comment]
Here is the screen showing how often it happens. Every "freeze" generates new crash report. 
![errors logs](https://user-images.githubusercontent.com/14231707/35434647-8e1cd512-0290-11e8-93a5-7f8182ce2d01.png)

And here is the full output log: https://pastebin.com/FQ424Y45

@SDGNelson Please let us know if something gonna be done about this issue...

**Comment by N1GHTPATROL** [comment]
@baranmod I noticed you are using my killfeed or balance display. You are getting errors which were common with an older build of the plugin. Have you updated to the latest build, available on I.P.?

**Comment by baranmod** [comment]
I actually haven't updated uconomy display. Will let know if it somehow related with this issue

**Comment by SDGNelson** [comment]
In your log the exception which is likely triggering the crash is this:

IndexOutOfRangeException: Array index is out of range.
at radicalmemexd_QWERTyUIOPASDFGHJKLZXCVB.radicalmemexd_QWeRTYUIOPASDFGHJKLZXCVB (SDG.Unturned.SteamChannel,Steamworks.CSteamID,byte[],int,int) <0x000d2>
at (wrapper delegate-invoke) SDG.Unturned.TriggerReceive.invoke_void__this___SteamChannel_CSteamID_byte[]_int_int (SDG.Unturned.SteamChannel,Steamworks.CSteamID,byte[],int,int) <0x00089>
at (wrapper dynamic-method) SDG.Unturned.SteamChannel.receive_Patch2 (object,Steamworks.CSteamID,byte[],int,int) <0x0009c>
at SDG.Unturned.Provider.receiveServer (Steamworks.CSteamID,byte[],int,int,int) <0x003fe>
at SDG.Unturned.Provider.listenServer (int) <0x00099>
at SDG.Unturned.Provider.listen () <0x000b2>
at SDG.Unturned.Provider.Update () <0x00128>

Considering it mentions patched methods and "radicalmemexd_QWERTyUIOPASDFGHJKLZXCVB.radicalmemexd_QWeRTYUIOPASDFGHJKLZXCVB" certainly isn't official code I wonder if you have a plugin that's doing something odd in SteamChannel.receive?

**Comment by N1GHTPATROL** [comment]
That's my plugin's obfuscation at work, and I assume seeing that he hasn't replied maybe he decided to update the plugin as I recommended for him to do.

**Comment by Kenzim** [comment]
My servers do this too. No errors, no nothing. They just freeze up, CPU usage drops to 2% and you can't join. From the server list it appears that there are players on, but its only the people who were on when it froze. I'm on ubuntu 16.04. Same problem with 14,.04, but less frequent on 16.
