### ISSUE TITLE
Issues with TPA + Home after update

### ISSUE THREAD

**Issue by Gsechs** [SmartlyDressedGames/Unturned-3.x-Community#1880]
Myself and other server owners I've talked to are experiencing issues with TPA and Home after the update on Friday. Actually; I have been experiencing them since I updated my servers' rocket to the LDM version. I understand there were some teleportation changes so I'm sure it's linked to that. 

The issue is specifically that /home or /tpa can bug in which if for example: Bob sends a tpa to Jim. Jim accepts but bob is not teleported. With home, I type /home and the server informs me that I was sent home but in reality I was not.

**Comment by SDGNelson** [comment]
Ideally the plugins with those commands (in this case it sounds like TpUtils) would be updated to directly use the Player.teleportToX helper methods. Right now they are silently failing the overlap tests.

The tests are important however: for example a standing player can TPA request a crouching player to glitch inside an object. These cases are requesting a teleport to location, so the Rocket teleport method has no way to know that they are trying to teleport to a player.

**Comment by TH3AL3X** [comment]
If you are using uEssentials, here you have proper fix.
https://github.com/TH3AL3X/uEssentials

**Comment by Projoker** [comment]
What about default Rocket home command? It doesn't work too

**Comment by Gsechs** [comment]
> Ideally the plugins with those commands (in this case it sounds like TpUtils) would be updated to directly use the Player.teleportToX helper methods. Right now they are silently failing the overlap tests.
> 
> 
> 
> The tests are important however: for example a standing player can TPA request a crouching player to glitch inside an object. These cases are requesting a teleport to location, so the Rocket teleport method has no way to know that they are trying to teleport to a player.

Thanks for the reply. Are you suggesting that the plugins for m Tpa/Home, (RocketModTPA and ZaupHomeCommand respectively) need to updates?

**Comment by TH3AL3X** [comment]
Use the uEssentials i sent, has little fixed for tpa and home
