### ISSUE TITLE
Mod in Unturned (Animals)

### ISSUE THREAD

**Issue by CTEI1AH** [SmartlyDressedGames/Unturned-3.x-Community#1881]
Hi, please help me create an animal in Unturned. I can make mods, but I can’t understand animals. I already made a model and all the animations, but what to do in Unity?

**Comment by SDGNelson** [comment]
Sorry this is outside the scope of the issue tracker, but I recommend you import the Example Assets package and set your custom animal up based on one of the included example animals: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GettingStarted.md
