### ISSUE TITLE
Vehicle spawns are not working.

### ISSUE THREAD

**Issue by KennysBoat** [SmartlyDressedGames/Unturned-3.x-Community#1883]
I set the spawns on my map to spawn military vehicles with no ids for blue hatchbacks and the only thing that spawns are blue hatchbacks, I have tried other IDs to no avail.

**Comment by TH3AL3X** [comment]
I remember someone reported this like 1 month ago ...

**Comment by SDGNelson** [comment]
Did you accidentally put the ID into the Asset ID field rather than Spawn ID? Spawn ID is for references to spawn tables.
