### ISSUE TITLE
Sentries/Powered Barricades randomly turning off

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#1884]
There's been a new issue cropping up as of lately, where seemingly randomly sentries and such will appear off for clients. All clients will see the item as off (even ones joining after the issue has started). Although the sentry appears off for all the clients, the server still thinks that is powered and it will shoot you. (This "visual" glitch can be fixed by just turning the local generator off & on again).

The server this issue was spotted on/that recording is from has zero Harmony or Redirection and none of it's plugins even touch sentries or electricity (At most, we have a decay plugin that is damaging/healing them).

Unfortunately I don't have any exact steps you can use to replicate the issue or more of a root cause, but I figured I would report it anyway and perhaps someone else is having the issue or if this is to do with a recent change.

![sentry](https://user-images.githubusercontent.com/17209937/87626631-d4a61800-c6fa-11ea-9238-4c64a9db061a.gif)

Edit: To Expand, this happens randomly to sentries mostly. It's never the same sentry either. The sentry is well within the range of the generator and the generator is fully fueled. It's only popped up recently.

**Comment by SDGNelson** [comment]
Thanks for the example gif. It looks like the indicator switches from green to red, and the shooting effects are playing, so some events are going through. Is the main issue that the aiming and turning animations are not playing?

If you can share the Client.log after this happens to you again that might be helpful to see if there is an exception during the sentry initialization or something.

**Comment by PandahutMiku** [comment]
> Edit: I misread the code when I was double-checking and you are right that the turning animations are not playing because locally it thinks it is not powered.
> If you can share the Client.log after this happens to you again that might be helpful to see if there is an exception during the power update or something.

Thanks for your quick reply.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4934885/Client.log)

Here's logs of when I booted up my game, joined the server, and instantly the sentry appeared off even though it is powered and killed me. The "Unable to register installed item during startup" stuff is just because I manually cleared my workshop files to force it to redownload stuff a bit ago and unrelated to this issue. Unfortunately I don't see much of interest in it, nothing obvious.  I'll be sure to update this issue if I find a way to reliability reproduce this.

**Comment by SDGNelson** [comment]
Thanks for sharing the log. It appears you are right that there are no power or sentry related warnings. There is a warning about the vanilla book and note, so I will fix that.

I will take another look at the power code with fresh eyes soon.

Anyone reading the repo: have you run into this issue on your servers?

**Comment by SDGNelson** [comment]
Meant to reply in the past week, but unfortunately I have not been able to track this down yet. Today I got an email from a player describing something similar: they built an industrial generator near one of the Northern ice lakes on Yukon, but some of the safezone radiator placements refused to turn on. I will try that out shortly. If anyone else is running into issues like this your description might be helpful for replicating it.

**Comment by nanashi88** [comment]
I ran into similar issues before.
I remember that I was seeing the sentry OFF, while my friend seeing it ON.
this happened a lot of times in the past, but idk if it is the same issue.
also recently I have had similar issues with sentries at Germany. but I don't remember exact details, or anything could be helpful to regenerate it.

**Comment by nanashi88** [comment]
now I remember that I have had one industrial generator, and multiple small generators.
turning off the generator, then turning it on again fix the issue if I am not mistaken (as PandahutMiku said).

**Comment by SDGNelson** [comment]
Good news: I am fairly confident that this is fixed in the next update which should be on Friday the 11th.

Sorry that it took so long to track down. The problem was that `getRegionsInRadius` assumed the input radius would only ever cover 4 cells at most, but at some point the maximum electric distance was raised breaking that assumption. 🤕

**Comment by SDGNelson** [comment]
This is a really old issue, but if anyone is still subscribed I wonder if you have encountered it after the fix back in September?

**Comment by PandahutMiku** [comment]
I haven't heard anything about it since then.

**Comment by SDGNelson** [comment]
Glad to hear it! Thanks for the confirmation.
