### ISSUE TITLE
Rocket reload [plugin] breaks the plugins. I need "Rocket reload".

### ISSUE THREAD

**Issue by vanya890** [SmartlyDressedGames/Unturned-3.x-Community#1885]
I need to reload the plugins, but Rocket reload [plugin] breaks them, the changes don't apply.
Everything worked fine with Rocket Reload. But you deleted this command, leaving the comment "Please reload individual plugins instead".
I need the Rocket full reboot command.

**Comment by vanya890** [comment]
I worked with the uEssentials plugin. Changing the TPS.

And it is inconvenient to restart the server each time to apply config changes. It runs a long time on my machine. Rocket Reload is much faster.

**Comment by Trojaner** [comment]
This is not an Unturned nor a LDM issue. Contact the plugin author.

**Comment by vanya890** [comment]
> This is not an Unturned nor a LDM issue. Contact the plugin author.

Changing and deleting "Rocket reload" creates problems for me. What does the plugin author have to do with it?

You deleted "Rocket reload" because it broke some plugins. Your alternative "Rocket reload <plugin>" breaks the others.

I need the "Rocket reload" command, restarting the server completely is long and inconvenient, kicking all players.

**Comment by vanya890** [comment]
Or how to activate this command forcibly?

**Comment by Trojaner** [comment]
The plugin you are using does not support reloading, this is not related to RocketMod.

**Comment by vanya890** [comment]
This plugin works stably with " Rocket Reload"

**Comment by vanya890** [comment]
The point is not even in this plugin.
It is much faster to just restart everything if I know that my plugins do not break, than to restart dozens of plugins individually.

**Comment by vanya890** [comment]
"Note that the methods for reloading all plugins still exist, so if you know that all the plugins on your server support reload properly you could have a custom dev command to reload all. The only change was to disable "/rocket reload" with a warning message, not to remove the underlying functionality."
How do I make this custom command?
I need it, but I have no experience in creating commands.

**Comment by Trojaner** [comment]
For God's sake can you stop spamming. You can edit your answers instead of forcing GitHub to send me 7 emails.

**Comment by vanya890** [comment]
![image](https://user-images.githubusercontent.com/19227465/87777493-42a12b00-c832-11ea-89bf-93c43116e8bc.png)
I'm sorry, I'm going to edit my messages in the future.

Also, the "Rocket Reload" team helped in installing plugins, without players leaving the server

**Comment by Trojaner** [comment]
![image](https://user-images.githubusercontent.com/1809172/87780759-0a9ce680-c838-11ea-88de-519a3de8dd69.png)
This message is not related to /rocket reload. It is caused by the plugin, it has a bug.
You can install new plugins with /rocket load.

**Comment by vanya890** [comment]
The screenshots above show that I tried to install uEssentials via rocket load. He doesn't see it.

**Comment by Trojaner** [comment]
Did you try `uEssentials` instead of `uessentials` instead?

**Comment by vanya890** [comment]
When the plugin is already installed:
![image](https://user-images.githubusercontent.com/19227465/87788722-7f771d00-c846-11ea-938c-31f64520210a.png)

When the plugin is not installed and I want to load it via " Rocket load":
![image](https://user-images.githubusercontent.com/19227465/87788891-d2e96b00-c846-11ea-8dd4-6d3eb73c0210.png)
![image](https://user-images.githubusercontent.com/19227465/87788933-e5fc3b00-c846-11ea-9c79-30bbe5be6a50.png)

**Comment by Raxul257** [comment]
![image](https://user-images.githubusercontent.com/10651703/87914276-b29cf480-ca70-11ea-9407-0b68fa6c6b52.png)

**Comment by vanya890** [comment]
I wish to reload all plugins. I'm not comfortable working with them individually when installing them.

"Rocket load" does not load plug-ins that were not initially available at launch. And "Rocket reload" loads them.

**Comment by Trojaner** [comment]
I wonder how often you install and remove new plugins, based on your writings it must be something done all the time

**Comment by cartman-2000** [comment]
This isn't a base game issue, and not really even a rocket issue, proper reloading is handled in the plugin, if a plugin doesn't reload properly, the plugin author should be notified.

By the looks of the error, the error is a duplicate player SteamID key(stored in a ulong format, unsignd 64 bit number, prfixed with 7656119 for the first part of the number.). If the plugin stores steam id's in the config fire, you should see if there's multiple copies of that steam id in the file, and remove any that show up.

**Comment by tankirules** [comment]
/rocket load plugin does not work on loading new plugins dropped into the plugin folder, only a full /rocket reload

**Comment by vanya890** [comment]
> I wonder how often you install and remove new plugins, based on your writings it must be something done all the time

Not so often. But in fact, every time when I'm working on a complete redesign of the server. This is very disturbing.

**Comment by vanya890** [comment]
> /rocket load plugin does not work on loading new plugins dropped into the plugin folder, only a full /rocket reload

"Rocket reload" is disabled...~

**Comment by educatalan02** [comment]
I think rocket reload must be optional configurable, but by default disabled

**Comment by tankirules** [comment]
> > /rocket load plugin does not work on loading new plugins dropped into the plugin folder, only a full /rocket reload
> 
> "Rocket reload" is disabled...~

i know, it's quite annoying

**Comment by vanya890** [comment]
> I think rocket reload must be optional configurable, but by default disabled

I think so too

**Comment by vanya890** [comment]
Also, "Rocket reload" is required to restart permissions

**Comment by rube200** [comment]
no, it isn't.
/p reload should work

**Comment by joeymisfit** [comment]
Rocket load plugin is meant for plugins inside of the plugin folder, that has never worked for plugins that you are just adding. Since rocket reload is unsafe and breaks a lot of plugins "especially mysql based plugins" the only option is to fully restart the server instance to implement new plugins, to reload permissions it should only require p reload unless you are doing something that errors the permissions file. Just take the extra time to restart the server as the rest of us have been doing it for quite awhile.

**Comment by vanya890** [comment]
> Rocket load plugin is meant for plugins inside of the plugin folder, that has never worked for plugins that you are just adding. Since rocket reload is unsafe and breaks a lot of plugins "especially mysql based plugins" the only option is to fully restart the server instance to implement new plugins, to reload permissions it should only require p reload unless you are doing something that errors the permissions file. Just take the extra time to restart the server as the rest of us have been doing it for quite awhile.

Restarting it is terribly inconvenient. Long loading, throws all players off the server. If people break plugins at the same time, let them restart, but why should people who use "rocket reload" and everything is normal for them, have to suffer because "rocket reload" was deleted? Nelson already wrote in one of the questions that the function itself remained. But no one answers me how to turn it on.

**Comment by TH3AL3X** [comment]
> > Rocket load plugin is meant for plugins inside of the plugin folder, that has never worked for plugins that you are just adding. Since rocket reload is unsafe and breaks a lot of plugins "especially mysql based plugins" the only option is to fully restart the server instance to implement new plugins, to reload permissions it should only require p reload unless you are doing something that errors the permissions file. Just take the extra time to restart the server as the rest of us have been doing it for quite awhile.
> 
> Restarting it is terribly inconvenient. Long loading, throws all players off the server. If people break plugins at the same time, let them restart, but why should people who use "rocket reload" and everything is normal for them, have to suffer because "rocket reload" was deleted? Nelson already wrote in one of the questions that the function itself remained. But no one answers me how to turn it on.

I don't understand anything you are talking about, but I'm sure your brain has died, just stop using that command and that's it, very easy, we all win

**Comment by vanya890** [comment]
> > > Rocket load plugin is meant for plugins inside of the plugin folder, that has never worked for plugins that you are just adding. Since rocket reload is unsafe and breaks a lot of plugins "especially mysql based plugins" the only option is to fully restart the server instance to implement new plugins, to reload permissions it should only require p reload unless you are doing something that errors the permissions file. Just take the extra time to restart the server as the rest of us have been doing it for quite awhile.
> > 
> > 
> > Restarting it is terribly inconvenient. Long loading, throws all players off the server. If people break plugins at the same time, let them restart, but why should people who use "rocket reload" and everything is normal for them, have to suffer because "rocket reload" was deleted? Nelson already wrote in one of the questions that the function itself remained. But no one answers me how to turn it on.
> 
> I don't understand anything you are talking about, but I'm sure your brain has died, just stop using that command and that's it, very easy, we all win, check OpenMod if you want more features

This command is convenient for me. It is very problematic to restart the server every time.

OpenMod is not supported by autodonation, so I am unable to use it normally.

**Comment by Trojaner** [comment]
> OpenMod is not supported by autodonation, so I am unable to use it normally.

Anything that supports RocketMod also supports OpenMod.

**Comment by vanya890** [comment]
I know. But OpenMod won't give me anything new, because: 1)There are conflicts of Permissions. 2)Auto-donates work exactly with RocketMod, granting privileges through its Permissions. It is very inconvenient to configure Rocket Permissions and OpenMod Permissions separately.

I checked OpenMod a few months ago, maybe something changed, but at that time there were not even so many plugins.

**Comment by Johnanater** [comment]
I do have a plugin that can load other plugins from the .dll.
https://github.com/Johnanater/LoadPlugin

As for /rocket reload'ing. Some plugins are just poorly written and don't have unload code. ¯\_(ツ)_/¯

**Comment by vanya890** [comment]
> As for /rocket reload'ing. Some plugins are just poorly written and don't have unload code. ¯_(ツ)_/¯

Thank you, I'll try it now
