### ISSUE TITLE
My server disappears completely from the server list and you can't connect after 10 minutes of uptime.

### ISSUE THREAD

**Issue by GAMEX1337** [SmartlyDressedGames/Unturned-3.x-Community#1887]
So me and my friend decided to make a server, we got through the setup and the portforwarding pretty well (I have a Huawei HG8247H Router) The port is set to 27015 in the commands.dat, he can join just fine but after 10 minutes of uptime he can't join through the internet nor the friends tab and it doesn't even work if he writes the ip (it worked in the first 10 minutes). 
I tried using no-ip, I didn't really understand it but I made the 3 things green on the DUC program. 
I tried writing bind ipv4 in the commands.dat but when I started up the server, halfway through the loading it always crashed no matter what I tried.
So yeah, did anyone have this problem or does anyone know how to solve it? I can provide more information but I think this should be enough. Thanks!:)

**Comment by Trojaner** [comment]
You must also open port 27016
