### ISSUE TITLE
Road line asset's white stripes dont aline with Road Tee Cap #2's white stripes

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1888]
https://imgur.com/a/kCoDQHp

obviously the least, tiniest, non-problem there is, but Road Line asset's white stripes dont aline with Road Tee Cap #2's white lines haha.

Yellow line aligning with road line asset is parking line #2 I was using to see if it was true haha

**Comment by SDGNelson** [comment]
Unplayable! Labeling this "next update" so that I remember to check it out, but if there are no other bugs requiring the asset bundles to be rebuilt I will hold off on it to avoid requiring a big download.

**Comment by INeedHelp225** [comment]
haha great news!
