### ISSUE TITLE
[Request] Remake ZombieTool

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1890]
Make method `giveZombie(Player player, byte type, byte speciality, byte shirt, byte pants, byte hat, byte gear, byte move, byte idle, Vector3 position, float angle)`
Like method from AnimalManager.

**Comment by XanderCodes** [comment]
I can vouch for that

**Comment by GazziFX** [comment]
But you can use System.Reflection to access spawn methods

**Comment by Sl4vP0weR** [comment]
> But you can use System.Reflection to access spawn methods

Game hasn't original methods to spawn zombies everywhere.

**Comment by Sl4vP0weR** [comment]
@SDGNelson

**Comment by SDGNelson** [comment]
[Netcode rewrites](https://blog.smartlydressedgames.com/unturned-in-2021/) are one of the main goals for 2021, but zombies in particular not yet. This might happen further down the road but not soon.
