### ISSUE TITLE
Leftover tempbe masterbundle files are causing loading issues

### ISSUE THREAD

**Issue by khakers** [SmartlyDressedGames/Unturned-3.x-Community#1891]
Not sure if there's really much you can do about this, but the temp battleye halo masterbundle files (that were removed in 3.20.6.0) are occasionally causing the game to stop loading at asset 816. In order to get the game to load again, people have to go and manually delete `tempbe.masterbundle`.

**Comment by SDGNelson** [comment]
It's unclear why Steam hasn't auto deleted it for some players. Validating the game files should clear it out. I suspect something similar will happen when deleting the Elver radio tower easter egg, so I will see about preventing the error from breaking loading.

**Comment by SDGNelson** [comment]
The stuck error should be fixed in the coming update, and hopefully the stray asset bundle gets removed during a Steam validate game files eventually.
