### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1892]
If you play in the first person, the FPS drops.
Sometimes when playing from a third person, the FPS increases, and if you enable Shift+F1, the FPS increases significantly (from 60 to 80-110)

**Comment by SDGNelson** [comment]
One reason for this might be that the first-person viewmodel is rendered separately and layered on top of the world image. That does seem like an unusually large difference though. I will check into it, but the performance is similar for me - perhaps it depends on whether your PC is CPU vs GPU bound.

**Comment by FANYPLAYRU** [comment]
Ok. I tested on PEI
