### ISSUE TITLE
About Client Text Chat Messenger

### ISSUE THREAD

**Issue by prank0011** [SmartlyDressedGames/Unturned-3.x-Community#1893]
If cheating is not enabled on the server and the user is not an administrator, the mod hook cannot use commands on the server.I want to make a haunted house so that the players who enter can automatically use / effect * *, and suddenly pop up a horror picture, but it can't succeed.

By the way, can you add an instruction to teleport to the spawn point? It is the spawn point placed by devkit.

**Comment by SDGNelson** [comment]
Using them for a haunted house is an awesome idea!

Does using the EffectSpawner component work instead? It does not require admin permissions.

In the meantime there is the NPC teleport instruction, however that cannot easily be directly linked with the Unity events.

**Comment by prank0011** [comment]
Thanks. Effectspawner does work.
If I can use ClientTextChatMessenger without turning on permissions, I can change the flag value so that the effect appears only once per person.
Or do other interesting things, such as: NPC stores that change every day, the production table that can only be used in a specified range.
If it's too much trouble to make a transmission command, forget it. I just want to know if the teleport gun can be made. I can put the spawn point into the blast effect.

**Comment by prank0011** [comment]
> 把它们用在鬼屋里是个很棒的主意！
> 
> 使用EffectSpawner组件是否有效？它不需要管理权限。
> 
> 在此期间，有NPC传送指令，然而，这不能很容易地直接链接到统一事件。



> Using them for a haunted house is an awesome idea!
> 
> Does using the EffectSpawner component work instead? It does not require admin permissions.
> 
> In the meantime there is the NPC teleport instruction, however that cannot easily be directly linked with the Unity events.

Thanks. Effectspawner does work.
If I can use ClientTextChatMessenger without turning on permissions, I can change the flag value so that the effect appears only once per person.
Or do other interesting things, such as: NPC stores that change every day, the production table that can only be used in a specified range.
If it's too much trouble to make a transmission command, forget it. I just want to know if the teleport gun can be made. I can put the spawn point into the blast effect.

**Comment by prank0011** [comment]
> Using them for a haunted house is an awesome idea!
> 
> Does using the EffectSpawner component work instead? It does not require admin permissions.
> 
> In the meantime there is the NPC teleport instruction, however that cannot easily be directly linked with the Unity events.

Thanks. Effectspawner does work.
If I can use ClientTextChatMessenger without turning on permissions, I can change the flag value so that the effect appears only once per person.
Or do other interesting things, such as: NPC stores that change every day, the production table that can only be used in a specified range.
If it's too much trouble to make a transmission command, forget it. I just want to know if the teleport gun can be made. I can put the spawn point into the blast effect.

**Comment by SDGNelson** [comment]
Sorry, but that is unlikely because it would be abused - that is why there is a setting to disable the messenger in the first place. A teleport gun is a cool idea but not possible yet.

**Comment by Alex-Well** [comment]
> Sorry, but that is unlikely because it would be abused - that is why there is a setting to disable the messenger in the first place. A teleport gun is a cool idea but not possible yet.

I am ready to argue with you =)
https://youtu.be/pIDzjMfwpr8

Of course this is not a teleport gun, but it performs its function! In fact, modders can create amazing things if Nelson gives tools.

**Comment by prank0011** [comment]
11

**Comment by prank0011** [comment]
> Sorry, but that is unlikely because it would be abused - that is why there is a setting to disable the messenger in the first place. A teleport gun is a cool idea but not possible yet.

I think about it carefully. It's really not right to open permissions. I didn't consider so much. I'm sorry.
If you can, can you make a ModHook to change the player's flag value instead?

**Comment by prank0011** [comment]
> > Sorry, but that is unlikely because it would be abused - that is why there is a setting to disable the messenger in the first place. A teleport gun is a cool idea but not possible yet.
> 
> I am ready to argue with you =)
> https://youtu.be/pIDzjMfwpr8
> 
> Of course this is not a teleport gun, but it performs its function! In fact, modders can create amazing things if Nelson gives tools.

Nelson was right. If someone made a map with instructions for ban hidden in it, some players might not be able to use the map.
