### ISSUE TITLE
Unity 2019

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#1894]
[Read with the voice of an old American movie trailer narrator]
After the ground-breaking [Unity 2017](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/55) issue and it's mind-blowing [Unity 2018](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/826) sequel, the Unity upgrade requests saga gets to an end with the Unity 2019 upgrade request issue! (Jokes aside, the saga doesn't end and there will be more requests hahaha) (hopefully someone got the reference)

**Why do we plugin devs want another upgrade?**
- Although Unity 2018.4 "supports" .NET Standard 2.0, it does not fully implement it. Some .NET Standard 2.0 methods are missing like the Unsafe.* methods. This prevents using modern libraries like Pomelo.EntityFrameworkCore.MySql, System.Memory, System.Span etc. This is a big problem for [openmod](https://github.com/openmod/openmod). Notice that this is not a request to switch to the .NET Standard 2.0 target framework! The .NET Framework 4.6.1 target includes .NET Standard 2.0 compatibility, but both targets lack the mentioned implementations.
- Mono has a lot of bugs and upgrading the engine may fix some of them
- As always, upgrading Unity should fix bugs and improve stability
- Plugins are unlikely to break with this upgrade
- No idea how it would affect workshop mods

**Comment by SDGNelson** [comment]
Haha, yes the game will probably continue to follow the Unity LTS releases. I have not personally tried updating yet because 2019.4 LTS only came out in June, but my guess is before the end of 2020.

**Comment by SDGNelson** [comment]
2019 LTS update is now on the beta branch! #1994
