### ISSUE TITLE
Can anyone tell me where I can get the plugin development documentation?

### ISSUE THREAD

**Issue by y1meng** [SmartlyDressedGames/Unturned-3.x-Community#1898]
**Please help me, thank you very much!**

**Comment by Trojaner** [comment]
OpenMod has a rich documentation: https://openmod.github.io/openmod-docs

**Comment by y1meng** [comment]
> OpenMod具有丰富的文档：[https](https://openmod.github.io/openmod-docs) ://openmod.github.io/openmod-docs[](https://openmod.github.io/openmod-docs)

Thank you for your help
