### ISSUE TITLE
Black Roadster is faster

### ISSUE THREAD

**Issue by xdlewisdx** [SmartlyDressedGames/Unturned-3.x-Community#19]
Black Roadster has a Speed_Max of 23 and all the others Roadster's have a Speed_Max of 19

**Comment by Adripps** [comment]
This is intentional and has been around forever

**Comment by MoltonMontro** [comment]
It has been around for forever! Secretly a political statement? 🤔

**Comment by xdlewisdx** [comment]
@khakers just because its been around forever doesn't mean its intentional, could he a overlook, @MoltonMontro statement saying blacks are faster?...

**Comment by FredMods** [comment]
Black cars.

**Comment by SDGNelson** [comment]
Thanks for the report!
