### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by Adamv21** [SmartlyDressedGames/Unturned-3.x-Community#190]
Nope

**Comment by aviadmini** [comment]
Nah, this is not needed and makes little sense. Everyone's screen is different and you won't know what exactly is happening there. 

P.S. I'll be making something for the community module later. That would use RPC and will be made to fit Unturned style. Probably a bit inspired by Rust community UI thingie, just better 🍡

**Comment by Adamv21** [comment]
@aviadmini
