### ISSUE TITLE
California Feature Request

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1901]
If any of these requests are unlikely to be implemented, please inform ASAP so we can course correct.

Needed at Launch
-------------------------

- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1019
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1526
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1637
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1843
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3019
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3265
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3343
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3474
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1904
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2901

Non-Critical
-------------------------

- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1452
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1906
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1924
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2830
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1436
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3326
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3573
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3574
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3576 (Would be extremely useful in general)
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3577 (Would be extremely useful in general)
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3533
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3581 (Would be very useful :) )
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1514
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1518
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1595
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1644
- ✅ https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1897

Would be nice!
-------------------------

- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1544
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1630
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1969
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1992
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3287
- https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3476

**Comment by Trojaner** [comment]
You should create separate issues to make tracking them and assigning status per request easier.

**Comment by Spebby** [comment]
good idea
will split them up

**Comment by Spebby** [comment]
ok isa done. Will leave this closed due to not being relevant to anyone but me, and perhaps Nelson to better track which specific request I've made.

**Comment by MoltonMontro** [comment]
@SDGNelson At'ing you, as many/all(?) of the linked issues pertain to requests desired for California's continued development, and I believe Spebby has recently updated or otherwise revised some of the linked issues to provide more context and other clarifications as to what the Cali team is wanting to do with those features.

**Comment by Spebby** [comment]
reopening to make it clear this is still a thing.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
