### ISSUE TITLE
[FEATURE REQUEST] Reward_Skill

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1903]
Reward_Skill <Skill> <Amount> 
Would reward a specific skill upon completing a request, amount of levels rewarded can be customized. Would be useful for "Training Quests" which level the player while teaching them certain mechanics.

(Split from Mega Request to allow for easier tracking of status)

MrObi123 also makes a good suggestion for "Condition_Skill".

**Comment by MrObi123** [comment]
Condition_Skill could be cool aswel

**Comment by Ankumo** [comment]
Also easy doable with plugins...

**Comment by MrObi123** [comment]
> Also easy doable with plugins...

That's a really dumb answer. If you want to implement this into a map, then everyone needs a plugin, which is also not possible in singleplayer.

**Comment by Ankumo** [comment]
Oh I've even forgot about this feature in the game xD Is there really anyone who'll play Unturned singleplayer? And btw that'd be better to create your super mega duper single player project with some module or plugins with tons of abilities to make whatever you want, isn't it?

**Comment by Spebby** [comment]
curated projects are not allowed to use modules.

**Comment by Ankumo** [comment]
Oh okay... That's sad though. And i hope that's not just your presumptions

**Comment by MrObi123** [comment]
> Oh I've even forgot about this feature in the game xD Is there really anyone who'll play Unturned singleplayer? And btw that'd be better to create your super mega duper single player project with some module or plugins with tons of abilities to make whatever you want, isn't it?

I'm talking about every server needing a plugin for a map. That's just dumb. Also, yes, a lot of players play singleplayer..

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
