### ISSUE TITLE
Option to enable tree regrowing if stump is blocked in config

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1907]
I noticed a new feature in update note
`Trees no longer respawn while a player or barricade is on the stump.`

Would it be possible to add an option to re-enable tree regrowing if stump is blocked in server config? I believe, its only a matter of time when a player who dislike trees (or just to troll) will come to server and start blocking all trees from regrowing

**Comment by SDGNelson** [comment]
Interesting point. I will add an option for this in the patch

**Comment by SDGNelson** [comment]
This should be resolved in the 3.20.8.1 patch: https://steamcommunity.com/app/304930/discussions/0/2785991898397739840/
