### ISSUE TITLE
Rejected for unknown reason? 

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1909]
A player on my server encountered the following problem
![image](https://user-images.githubusercontent.com/65422793/89073504-4fba3000-d383-11ea-85db-cd8a73f13522.png)

**Comment by SDGNelson** [comment]
Ah... the econ hash kick is 38, but it happens earlier in the connection process than the version check. They are actually running a different version than the server, but it is telling them about this new kick instead. I will change the order so version number check happens earlier

**Comment by SDGNelson** [comment]
This should be resolved in the 3.20.8.1 patch: https://steamcommunity.com/app/304930/discussions/0/2785991898397739840/
