### ISSUE TITLE
I don't think flying spartans are normal...

### ISSUE THREAD

**Issue by ZanyTheEagleman** [SmartlyDressedGames/Unturned-3.x-Community#191]
so In servers whenever I entered the gunner seat of the new vehicles with turrets (i.e Cerberus, Spartan chariot) and turn the gun, it freaks out, like it spins in circles and start to fly in the air.
I have asked the server owner and he says it might be a game problem.
I'm no programmer but I can safely say that this is a bug.

**Comment by Mithallas** [comment]
It happens when you place objects like lockers or plates on the vehicle as well

**Comment by ZanyTheEagleman** [comment]
yeah it pretty makes the vehicle unusable

**Comment by SDGNelson** [comment]
This happens if the child colliders aren't marked to ignore buildable collision. I'll follow up with the Greece map developers.
