### ISSUE TITLE
Rotated items in inventory do not cull properly when scrolling

### ISSUE THREAD

**Issue by alexkmnsky** [SmartlyDressedGames/Unturned-3.x-Community#1912]
Item thumbnails/icons which are rotated in the inventory do not cull in the correct direction when they are scrolled past. To reproduce:

1. Put on enough clothing so that you are able to use the scroll bar in the inventory.
2. Rotate an item 90 degrees.
3. Scroll the item off the screen.

![Example](https://i.ibb.co/Kz46Bd5/Annotation-2020-08-01-154658.png)

**Comment by SDGNelson** [comment]
Unfortunately known, this will not be fixable until the game updates to one of the newer non-IMGUI systems.
