### ISSUE TITLE
Change key datatype to ushort in EffectManager.sendUIEffect

### ISSUE THREAD

**Issue by Paradox304** [SmartlyDressedGames/Unturned-3.x-Community#1913]
It's bad that sometimes we can't have the id of the UI as the key because it's over the limits of the short datatype. Was there a reason in making this the short datatype?

**Comment by iBowie** [comment]
As a workaround you can use `(short)(effectID - short.MaxValue)`

**Comment by SDGNelson** [comment]
The intention was that only some UI effects need a key for updating, and in that case you have some internal management that tracks the IDs. For example you have a map of player to ID pool, and claim/release IDs as needed. I thought plugin systems like Rocket would want to handle that, but it might help to build into the base game.

**Comment by Paradox304** [comment]
> As a workaround you can use `(short)(effectID - short.MaxValue)`

Never though of this, would use this from now on.

**Comment by Paradox304** [comment]
> The intention was that only some UI effects need a key for updating, and in that case you have some internal management that tracks the IDs. For example you have a map of player to ID pool, and claim/release IDs as needed. I thought plugin systems like Rocket would want to handle that, but it might help to build into the base game.

Oh ok.
