### ISSUE TITLE
[Question] What's this enumeration value for?

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#1914]
Recently i found new values in ENPCHoliday enum, these values are: "April_Fools" and "Max". I understand what "April_Fools" is for, but "Max"? Is this just a placeholder value that will do nothing? Or is it something meaningful? I would want to know this because i'm making the app for creating NPCs, and i would want to give explanation on this value in this app.

**Comment by SDGNelson** [comment]
Cool idea. That enum value is only used for determining the number of values, e.g. `scheduledHolidays = new DateTimeRange[(int) ENPCHoliday.MAX];`
