### ISSUE TITLE
[Feature Request] Road Line (Object)

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1916]
I think you can do for it the effect of multiplying textures (I don't know how it is called correctly, you can correct it)
When making a city, you always have to put a lot of road objects, which loads the processor (as I think), I noticed that on objects like boulders and lava, when you change the size, the texture multiplies, and does not evade. I think that you can also do with the road item and not put 10 items each time, but just increase their size.

**Comment by Spebby** [comment]
While on the topic of the road lines, it'd be nice if they were changed box colliders instead of mesh colliders for performance reasons :)
