### ISSUE TITLE
MK II achievement not working

### ISSUE THREAD

**Issue by TNTblowup** [SmartlyDressedGames/Unturned-3.x-Community#1920]
My friend and I followed the steps to get the MK II twice, on 2 different lan severs, and both got the Shadowstalker MK II, but we didn't get the achievement.

**Comment by SDGNelson** [comment]
Thanks for the report! Sorry about that. I will get this sorted out for the next update

**Comment by TNTblowup** [comment]
Thank you so much for responding! I'm glad to hear that it's going to be fixed!

**Comment by SDGNelson** [comment]
Apologies again for the delay. This is fixed in the coming update.
