### ISSUE TITLE
Hello, what should I do and I go to Unturned, the game starts loading, but wait a little and the music started playing and an endless download started, what should I do help?

### ISSUE THREAD

**Issue by Global332** [SmartlyDressedGames/Unturned-3.x-Community#1922]

**Comment by SDGNelson** [comment]
Endless download while joining a server? It might be that background downloads are disabled. If you subscribe to the item from the server details screen (+) it will download ahead of time.

**Comment by Global332** [comment]
Hello, what should I do when I enter the game it comes to Wait a little, the music started playing and the game freezes endless loading, what should I do?

**Comment by Global332** [comment]
when exactly do i enter the game

**Comment by SDGNelson** [comment]
Depending on the amount of content in the mod it may take a while to load, or there may be an error with it, alternatively you can unsubscribe and try a different server without mods.

**Comment by Global332** [comment]
I removed the game mods all removed

**Comment by SDGNelson** [comment]
Sorry if I did not respond - did we resolve this by email?
