### ISSUE TITLE
Getting Hwid with SteamPlayer getting only zero

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1923]
I'm trying to do a ban system in my own server for ban people via Hardware-ID, but it's only getting "00000..." numbers, i use this thing and i have the latest RocketMod version from Extras files:

**player.SteamPlayer().playerID.hwid;**

**Comment by SDGNelson** [comment]
If the client cannot get a hwid it will generate a random one instead, so the zero hwid might be from a cheat. Considering your history are you testing your plugin on yourself while you are using a cheat?

**Comment by TH3AL3X** [comment]
Impossible, i'm testing those things with normal users, I don't have cheats, and when i touch unturned with BattlEye servers i get after 5 minutes a ban, so...
![image](https://user-images.githubusercontent.com/13141042/89467906-bcb03a00-d776-11ea-8450-7cd85b60a953.png)

**Comment by tankirules** [comment]
> If the client cannot get a hwid it will generate a random one instead, so the zero hwid might be from a cheat. Considering your history are you testing your plugin on yourself while you are using a cheat?

Will this generated random hwid be consistent through different accounts and such on the same hardware?

**Comment by SDGNelson** [comment]
Perhaps your code is allocating a new SteamPlayerID somewhere? (it shouldn't be, but in that case if a hwid was not provided it would be zero)

Random hwids are only used if an actual hwid cannot be used, so no it is not consistent.

**Comment by TH3AL3X** [comment]
> Perhaps your code is allocating a new SteamPlayerID somewhere? (it shouldn't be, but in that case if a hwid was not provided it would be zero)
> 
> Random hwids are only used if an actual hwid cannot be used, so no it is not consistent.

I'm using this **UnturnedPlayer otherPlayer = UnturnedPlayer.FromName(commands[1]);** , and i tried with a guy online in my server idk and still the same...

**Comment by SDGNelson** [comment]
Perhaps the player does not exist? Some of the Rocket FromX methods return UnturnedPlayers without a valid connected player.

**Comment by TH3AL3X** [comment]
Idk how to do it, anyways i saw this part of code in a source, what it does, because you asked before that "SteamPlayerID"
**Provider.onCheckBanStatusWithHWID += CheckBanned;**

**Comment by TH3AL3X** [comment]
So you told me to do this yes?, call me idiot, i'm brain dead
            **UnturnedPlayer otherPlayer = UnturnedPlayer.FromName(commands[1]);
            CSteamID steamId;
            steamId = otherPlayer.CSteamID;
            UnturnedPlayer PlayerID = UnturnedPlayer.FromCSteamID(steamId);**

**Comment by educatalan02** [comment]
Try doing it with that:

UnturnedPlayer unturnedPlayer = UnturnedPlayer.FromName(commands[1]);

unturnedPlayer.Player.channel.owner.playerID.hwid

**Comment by tankirules** [comment]
> Perhaps your code is allocating a new SteamPlayerID somewhere? (it shouldn't be, but in that case if a hwid was not provided it would be zero)
> 
> Random hwids are only used if an actual hwid cannot be used, so no it is not consistent.

Shouldn't it return something consistent like 0 or something so it can be known if a player is using a cheat to obstruct this?

**Comment by PandahutMiku** [comment]
> > Perhaps your code is allocating a new SteamPlayerID somewhere? (it shouldn't be, but in that case if a hwid was not provided it would be zero)
> > Random hwids are only used if an actual hwid cannot be used, so no it is not consistent.
> 
> Shouldn't it return something consistent like 0 or something so it can be known if a player is using a cheat to obstruct this? Also can lead to false positives/negatives when checking for alts

A Player with a cheat could send literally anything in place of their actual HWID, not just full Zeros. There isn't any way the server could know the player is lying. The HWID is made Client-side, hashed by the client, and send to the server by the client on join.

**Comment by TH3AL3X** [comment]
> Try doing it with that:
> 
> ```
> UnturnedPlayer unturnedPlayer = UnturnedPlayer.FromName(commands[1]);
> 
> unturnedPlayer.Player.channel.owner.playerID.hwid
> ```



> Try doing it with that:
> 
> ```
> UnturnedPlayer unturnedPlayer = UnturnedPlayer.FromName(commands[1]);
> 
> unturnedPlayer.Player.channel.owner.playerID.hwid
> ```

Thank you so much, it's working now 👍

**Comment by TH3AL3X** [comment]
I know what is happening, why i got that, only zeros, it's because my Login_Token is banned by unturned, so thats why, i tested that without that empty and now it's working fine...

**Comment by TH3AL3X** [comment]
I found the problem, but i don't know what is causing it, i'm not using other plugin that can cause that, and i'm using the latest version of RocketMod, please help me....

[![](http://img.youtube.com/vi/BpiJgXKJD5w/0.jpg)](http://www.youtube.com/watch?v=BpiJgXKJD5w"")

**Comment by SDGNelson** [comment]
> i'm not using other plugin that can cause that

Well, if it happens when other plugins are installed, but not when other plugins are not installed, it sounds like the other plugins are the cause.

**Comment by TH3AL3X** [comment]
Aight it's a plugin loader...
