### ISSUE TITLE
[New Bug] Vehicle object

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1925]
If you put Locker on the transport, it will not open, if you put for example Note, you can open it, but you can not write it.
And you can't take this item back.

**Comment by SDGNelson** [comment]
Perhaps caused by a specific custom vehicle or plugin? I have not heard this reported anywhere else, so it seems unlikely that there is a bug affecting all storage on all vehicles like that.

**Comment by FANYPLAYRU** [comment]
I don't think the problem is with plugins, since the problem appeared after the update (Maybe even earlier but I only found out now)

Video - https://youtu.be/RHeu9uj4ic8

**Comment by SDGNelson** [comment]
Perhaps the server version of one of the colliders (e.g. the license plate) is obstructing the storage line trace? There was a similar case where the item colliders were huge and preventing items from being picked up.

**Comment by educatalan02** [comment]
It looks like the collider of the License Plate is too big

**Comment by educatalan02** [comment]
Could you send us the Workshop Mod of the License Plate? @FANYPLAYRU

**Comment by FANYPLAYRU** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2183470943
