### ISSUE TITLE
Character Mesh Replacement Question

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#1926]
Hi, does someone know how to create character's mesh replacement from Blender to Unity? I made everything, modeled a mesh from Animation.blend in Sources, exported it in Unity, configured imported model like example, then configured everything else and bundled unity3d. In-game it looks like this
![image](https://user-images.githubusercontent.com/69295711/89501713-7e456a00-d7cc-11ea-9f57-f1b8f432acf1.png)

I'm making character model with bones, not static model. What did I miss? Am I need to export model from Blender somehow else? Or am I need to do something in Unity? Please help

**Comment by SDGNelson** [comment]
Most likely different bone axis during export. You can preview the mesh in Unity to compare. This guide has the proper Blender to Unity export settings: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Animation.md
