### ISSUE TITLE
Possible to include punching with Player.animator.onGestureUpdated?

### ISSUE THREAD

**Issue by Eiromplays** [SmartlyDressedGames/Unturned-3.x-Community#1927]
Hello, just wondering if it would possible to make punching registered using the onGestureUpdated event. It would save me some time and I am sure it would save other people some time as well.

**Comment by SDGNelson** [comment]
What did you want to use the event for, e.g. to cancel punches? At the moment that gesture is only used to play the animation for all players

**Comment by Eiromplays** [comment]
I am using OpenMod and at the moment they have no gesture event included, I know rocketmod has a gesture event included but yeah. I am working on a plugin, so that is mainly why I need it, so I can do stuff  when the player punches and looks at something

**Comment by SDGNelson** [comment]
Fair enough.
