### ISSUE TITLE
Startup Command Priority

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1929]
Over the last few days ive been experimenting with servers and how to limit player slots per client. I see many other hosts that have a similar issue which allows players to simply edit the Maxplayers in commands.dat to get as many slots as needed.
I originally thought that setting the max players in startup parameters of a server would resolve this as hosts can make it so clients can't edit their startup parameters. Sadly this isn't the case and it seems that any conflicts between startup and commands.dat are overpowered by commands.dat as it seems to have priority.
If possible could an update be made that gives startup parameters higher priority than commands.dat as it saves hosts trying a bunch of janky and often complex methods just to limit player count.

**Comment by SDGNelson** [comment]
Can you clarify about limiting the player slots? Are you trying to restrict them to a certain maximum value, or reserve special slots that normal players cannot connect into? By startup parameters are you referring to the command-line parsing of commands?

**Comment by IAmSilK** [comment]
I'll chime in as Brad and I are working on the same thing.

Many server hosts sell servers by the vanilla player slot - nothing to do with reserved/special slots. Currently, the commands in the Commands.dat file run after the command-line arguments are parsed giving the Commands.dat priority.

This request is to switch the priorities and have the command-line arguments parsed after Commands.dat. This will make it easier for server hosts to set maximum player slots without the need for custom modules, editing of binaries, etc. as users can't change the command-line arguments which are preset by server hosts, but they can change the Commands.dat file.

**Comment by SDGNelson** [comment]
Hmm... rather than priority between the two ways of setting startup commands, how about a command-line option that specifically restricts the maximum player value? This sounds like it could be useful for other hosting services as well. For example something like: `-HostingSlotLimit=16`

**Comment by Bradler26** [comment]
Yep that would be perfect as well. Would really be appreciated if you could do that.

**Comment by SDGNelson** [comment]
In the next update a "-MaxPlayersLimit" parameter has been added, e.g. "-MaxPlayersLimit=16". It will log and clamp if anything tries to set the max players above this value.
