### ISSUE TITLE
Server Name Characters Limit Increase

### ISSUE THREAD

**Issue by UncleLYHME** [SmartlyDressedGames/Unturned-3.x-Community#193]
I'd love to see an increased limit on how long your server name can be as it's currently 50.

**Comment by N1GHTPATROL** [comment]
Same here, maybe custom colors or symbol support to make titles more unique. Formatting would be good to see too.

**Comment by Jonnyfencing1** [comment]
^ also Maybe increased server slots and a way to edit Locker sizes in intractable item just while we're on the topic of changing things

**Comment by Trojaner25** [comment]
I agree, however maybe its a limit of Steam

Colors would be really great

**Comment by ItzEdInYourBed** [comment]
As a server owner I would also like to see an increase in server names' character limit. The current amount seems too small. Color would also be nice.

**Comment by AlphaOneYT** [comment]
i agree with @N1GHTPATROL, as well as i think the character slots should be increased

**Comment by thereis** [comment]
Character slots and players slots...

The UX inside the UI in Unturned is terrible... must be unique and modified. The game is not anymore in alpha, but have the same UI, the same features since the game in EA.

**Comment by SDGNelson** [comment]
Hmm it should be 64 based off of:

/// Set name of map to report in the server browser
///
/// @see k_cbMaxGameServerName
virtual void SetMapName( const char *pszMapName ) = 0;

const int k_cbMaxGameServerName = 64;

Though at the moment the longer names don't display nicely in the server list. What other information would you be wanting to put in the title - perhaps the description would be better suited?

**Comment by N1GHTPATROL** [comment]
Well, when you consider the titles often having their region, server name, possibly server number, and then maybe 10-15 chars to tell the entire world what you're server is about, most owners find them self using every last character- me included. Any further info players can view on the server menu while browsing all servers would be great.

**Comment by Jonnyfencing1** [comment]
I agree with n1ghtpatrol trying to fit in Jonny’s PVP eu whatever number then x10 loot etc is almost impossible 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SDGNelson** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/262

**Comment by negrifelipe** [comment]
Maybe with the new server list this can be increased ? i think it would be a nice addition

**Comment by ItzEdInYourBed** [comment]
> Maybe with the new server list this can be increased ? i think it would be a nice addition

You commented on an issue from 6 years ago. SIX
The issue was closed and marked as completed along with the update notes that involved this change.
