### ISSUE TITLE
Some basic changes on modules

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1931]
I am asking that a pre-initialization method be added to `IModuleNexus`, so modules other modules can change their behavior depending on the active modules or subscribe to the `public event ModuleInitialized onModuleInitialized` event in the class modules.

This behavior would be:
* Scan all modules
* Loading of modules
* Pre Initialization of modules
* Initialization of modules

----
If you don't want to add the Pre-Initialization, I would like you to at least reconsider creating the instances of all modules first and then initializing them. 
Currently:
```cs
if (this.isEnabled)
{
    this.load();
    this.initialize();
}
else
    this.shutdown();
```

**Comment by SDGNelson** [comment]
Can you elaborate on your use case? Ending up with a bunch of pre/post events is not ideal.

Depending on what you have in mind it might be possible to use the existing inter-module dependencies list which causes yours to load after its dependencies, or to bind the ModuleHook.onModulesInitialized event which is called after all modules are initialized.

**Comment by rube200** [comment]
i need exactly the opposite, i need my module to be called before rocketmod is initialize to apply a patch to it.  If all modules are instantiated before they start to be initialized, that would be enough.

**Comment by SDGNelson** [comment]
What aspect of Rocket are you patching? i.e. what are you changing?

It sounds like it might help to have some sort of "initialize before" property where modules can request to be initialized before or after others, and then the game sorts them accordingly.

**Comment by rube200** [comment]
I found that I don't need this anymore but that would also be welcome. 
Rocket only calls `internal void Initialize ()` when `Provider.onServerHosted` occurs.

**Comment by SDGNelson** [comment]
Glad that there is a good workaround for the meantime. 

Will leave this open, but the "initialize before" option is low priority unless needed.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
