### ISSUE TITLE
[Feature request] ObjectHoleVolume

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#1932]
Do the same as with Landscaping
But to cut the texture of the object, the Collider and the Collider on the server.

**Comment by iBowie** [comment]
I don't think it's possible due to objects being separate models, while terrain is generated from heightmaps

**Comment by Trojaner** [comment]
I think this will have a negative impact on performance

**Comment by alexkmnsky** [comment]
What would the purpose of this be? Is this for some specific use case?

**Comment by iBowie** [comment]
I checked that Unity does not support holes in objects

**Comment by Spebby** [comment]
unity does support Mesh editing (See Polybrush), however, it's very finicky, and likely not possible to implement in a standalone editor.

**Comment by SDGNelson** [comment]
Sorry, but I do not foresee this being added.
