### ISSUE TITLE
Add OnDestroy() for optimization!

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1934]
Nelson, please add an **OnDestroy ()** event to the **ActivationEventHook**. Initially, I offered a script that supported it, but for some reason you decided to remove this event.
It may seem strange to you that I am asking to add it. The fact is that I used in my mods a function that allows you to move a child object outside the hierarchy of the parent. Naturally, when the parent object is destroyed, its child remains on the scene, which is a bad optimization. I found a temporary solution using the scripts **MythicLocker** and **MythicLockee**, they work perfectly except for **Update()** which assigns rotation from parent to child. I only need **position** assignment.

**Comment by SDGNelson** [comment]
Why are you moving the child outside the parent hierarchy? Is it because you want the position to be the same and not the rotation, or a different reason? What is the object/effect you are using this for?

**Comment by Alex-Well** [comment]
> Why are you moving the child outside the parent hierarchy? Is it because you want the position to be the same and not the rotation, or a different reason? What is the object/effect you are using this for?

It can be used in many places. But at this particular moment, I need to move the UI outside the Item hierarchy so that the UI does not twitch during the Use animation. (If you want, I can introduce you in more detail into the course of my developments.)

**Comment by SDGNelson** [comment]
In the meantime one workaround to destroy the UI when the item is destroyed would be to use the OnDisabled event - it should be fired when the item is destroyed as well.

**Comment by Alex-Well** [comment]
> In the meantime one workaround to destroy the UI when the item is destroyed would be to use the OnDisabled event - it should be fired when the item is destroyed as well.

Yes, but you didn't take into account that I used this for the Item. The character always holds two copies of the item. When the player switches between the first and third person views, these items are mutually turned on and off. Because of this, OnDisabled() will destroy the object when simply switching the view. However, I found a way out of the situation, you can call a function through the OnDisabled() event that will return the child object back to the hierarchy. However, you have to use two scripts for the objects to be switched, but this is not a big problem. Thanks for the quick response anyway.
