### ISSUE TITLE
character mesh replacement Separate part

### ISSUE THREAD

**Issue by JorelDecker3000** [SmartlyDressedGames/Unturned-3.x-Community#1935]
Help, can replace the model of the character through character mesh replacement , but I saw that one person was able to do so the main character model has not changed, and over it was applied a new model which is tied to the bones. But I don't understand how to do it.

Sorry about the language, I live in Ukraine and use a translator.

![image](https://user-images.githubusercontent.com/56679667/89916196-04641500-dc00-11ea-8b1a-0ae9575386ed.png)

**Comment by SDGNelson** [comment]
They based their mesh on the existing character model, i.e. their mesh replacement includes the original mesh.

**Comment by JorelDecker3000** [comment]
How did they make the material? I found a team that makes a three-dimensional set with standard material, that is, you can change the face and skin color. But in this case, the jacket also has a flesh color of the skin. How can I apply the material to it separately? Maybe you need to make a second material under a certain name?
Command itself:Has_Character_Material_Override False

**Comment by JorelDecker3000** [comment]
I understand that they have a mesh character Unturned, but how did they make this mesh superimposed with a standard material that allows you to change the color of the skin and face.
