### ISSUE TITLE
unturned character mesh replacement PART 2

### ISSUE THREAD

**Issue by JorelDecker3000** [SmartlyDressedGames/Unturned-3.x-Community#1936]
Dear Nelson, Last time you told me that the author of the mod had a standard mesh, I understand that they have a mesh of the character Unturned, but how did they do so that this mesh was superimposed with a standard material that allows you to change the color of the skin and face.

And is it related to the command: Has_Character_Material_Override False?

**Comment by SDGNelson** [comment]
Must have missed this at the time, but yes if material override is False then the built-in material with skin and face is used instead.
