### ISSUE TITLE
Missing localization for #ITEMS_OBSTRUCT_TREE_RESPAWNS

### ISSUE THREAD

**Issue by alexkmnsky** [SmartlyDressedGames/Unturned-3.x-Community#1939]
![Issue](https://i.ibb.co/pvw8mbv/Annotation-2020-08-14-152546.png)

**Comment by SDGNelson** [comment]
Thanks, will fix!

**Comment by Sagnoir** [comment]
Which file was this line in?

**Comment by SDGNelson** [comment]
That would be in MenuPlayConfig.dat - if not present it will use the variable name, but you can specify one with Items_Obstruct_Tree_Respawns.

**Comment by Sagnoir** [comment]
Thanks. It's not present, so I guess I don't have to translate it.
