### ISSUE TITLE
Workshop Map Issue

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1942]
Hello @SDGNelson,
I was just wondering if you've heard anything about a workshop bug where modded maps are passing the wrong version with a server restart? I'm working on a group of dedicated servers that use the dsa and we are using the workshopdownloadconfig.json though for some reason when we use maps like California, France, Hawaii, or even PEI players get errors like 
_The server is running a different version of the map: 3.20.1.2_ 
or
_The server is running a different version of the map: 3.0.0.0_

and requires at least 1 or 2 restarts for that error to disappear. The maps aren't in any other folders whatsoever, and I've deleted all workshop cache, yet that error still exists.

Any advice or assistance would be greatly appreciated!

**Comment by SDGNelson** [comment]
You mention they are modded versions of the maps. Do they have the same name as the vanilla maps? If so, it is probably using the version number of the vanilla map rather than the modded map. (maps should have unique names)

The version displayed by that message is the version loaded by the server. Does it match the one shown in the client menus?

**Comment by joeymisfit** [comment]
Hi there, what I mean't was that some of them you get off of the workshop by the original creators, so modded, like California, Hawaii, and France. The version does match, which is quite weird for it to be throwing an error like that.

**Comment by SDGNelson** [comment]
From double-checking the related code I see no issues, but I will make a couple changes for the next update. Namely to report which version the client has in that message to see if it is identical.

**Comment by DomingoTapita** [comment]
Hi Nelson, we tried the option that you recommended, but I jump a new error in a map modified by us, remember that it is not an original map of Unturned, if not made by us.
Now you can see that magically the map is in another version: 3.0.0.0
hahaha

![unknown](https://user-images.githubusercontent.com/70148952/91111361-b961ed00-e656-11ea-9c05-7d3731486881.png)

**Comment by SDGNelson** [comment]
In the next update it will log both version numbers.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
