### ISSUE TITLE
All transport on the server has stopped working! #2

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1948]
Hello, in April I wrote about a bug in this post: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1638#issuecomment-619236528%C3%A7

I managed to fix all the errors in the modpack that they wrote to me about, 
https://user-images.githubusercontent.com/37713088/80255818-5f402380-8686-11ea-998a-e35aafe77906.png
 but the bug still repeated.

The same video about the bug I'm talking about: 
https://www.youtube.com/watch?v=w3qKoygnw6U

Can someone come across this and help me solve this problem? Please

**Comment by SDGNelson** [comment]
Are all vehicles on that map still having issues, and the vehicles work fine on other maps/servers?

If you share the server details and make 76561198036822957 an admin I will connect in debug mode - I did make the change so BattlEye will not kick me this time.

**Comment by MrGoBi** [comment]
On my server, this bug will happen very soon (I think in a week). You ask - how did I understand this? The fact is that at first, commands like /whois (from Avi) and the like, which can interact with the transport by looking at it, stop working. I've already had this ~ 5 times .. After a week or two, the situation is aggravated and you can't even get into any transport (as in the video). I can write when this happens. Or check now, because the transport is no longer all right

185.66.84.235
25444

**Comment by SDGNelson** [comment]
I teleported around a bit looking for cars and they seemed normally interactable. Is there a specific vehicle or in a specific place? If you can tell me where to teleport to a vehicle that is not working that may help.

Anecdotally connecting did lead to the discovery of an unrelated bug. :)

**Comment by MrGoBi** [comment]
Oh no. At the moment, you can interact with all vehicles, but soon it will not be possible. I will write here how it will happen.
The fact is that commands like /whois do not work when I look at the transport. A similar incident has already happened several times.

**Comment by SDGNelson** [comment]
In that case let me know once the interaction runs into issues and I will connect again shortly thereafter? I will try to join relatively soon after you report it so that it can be resolved for the players on the server.

For the /whois command I guess it would depend what layermask they are using for the raycast.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
