### ISSUE TITLE
Tree Climbing

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#1949]
It would be useful if we had some sort of a configuration option or some way to disable climbing up trees. You probably know, but right now you can slowly snake up the sides of one if you are prone and holding down W facing the tree. This seems unintended, and is fine on it's own, but can cause problems on some specific servers where people can camp on top of trees where they shouldn't be allowed to or use it to get over base defenses.

**Comment by SDGNelson** [comment]
This is something I would like to sort out. On my to-do list is seeing about using the Controller.Move result to catch those hits.

**Comment by SDGNelson** [comment]
This might have changed a bit with the movement improvements late 2021. There are still some ways to stand on steep surfaces unfortunately. :/
