### ISSUE TITLE
User can chat and use commands after death

### ISSUE THREAD

**Issue by thereis** [SmartlyDressedGames/Unturned-3.x-Community#195]
A user of my server, reported a game issue that he can execute commands even after dead.

He was able to: `/tpa`, `/kits`, `/etc` 

After that, he can't leave the game, only finishing the proccess.

[Image](https://media.discordapp.net/attachments/361671981612924941/405502369510457364/unknown.png?width=621&height=466
)

**Comment by SDGNelson** [comment]
These aren't official commands - the plugin developer would have to check whether the player is dead or not.
