### ISSUE TITLE
CEF UI

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#1950]
I think community need new ability. Ability to easily developing UI with CEF.
Here the sample - https://github.com/aleab/cef-unity-sample

**Comment by SDGNelson** [comment]
Sorry, but this will definitely not be added. Also that CEF plugin has not been updated in 3 years from Unity 5

**Comment by Sl4vP0weR** [comment]
@SDGNelson, CefGlue still supported by developers, this repository was a sample, we can try to do something about it, It'll be very helpful to Unturned developers to create better UI using JS, HTML and RPCs

**Comment by GazziFX** [comment]
What benefits of using heavy browser engine instead of Unity UIElements which planned in Unturned?
