### ISSUE TITLE
Problem in the map and terrain editor

### ISSUE THREAD

**Issue by DomingoTapita** [SmartlyDressedGames/Unturned-3.x-Community#1952]
Hello Nelson, sorry for bothering you, the truth is that I have a problem, which I consulted in the Discords of unturned in their respective channels under the name of "Domingo Tapita" and nobody could answer me or help in this problem, since it was out of the normal.
The problem is like this. I am editing a map and when entering the edited map in single player mode, everything is normal, I can walk, I can fly I can do the basics. When I enter the map on the server, with its respective workshops, this happens to me at the time ... I send you a video that I recorded so that you understand the problem better. I will also give you the map workshop..

Video: https://www.youtube.com/watch?v=MtLChJQ-iHw&feature=youtu.be
Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2207410347

Log:
[Rocket (1).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5118156/Rocket.1.log)

**Comment by SDGNelson** [comment]
It looks like the map loaded by the server is probably different than the one loaded by the client. For example the ground is much lower or perhaps flat.

**Comment by DomingoTapita** [comment]
Hi Nelson, the map is the same loaded on both the client and the server ... Is it very weird? Any solution?

**Comment by SDGNelson** [comment]
I recommend temporarily disabling your local copy of the map, and connecting with the workshop one. You can also force the files to match with the Should_Verify_Objects_Hash setting described here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/LevelConfig.md

**Comment by DomingoTapita** [comment]
Hi Nelson, we tried the option that you recommended, but I jump a new error in a map modified by us, remember that it is not an original map of Unturned, if not made by us.
Now you can see that magically the map is in another version: 3.0.0.0
hahaha
![unknown](https://user-images.githubusercontent.com/70148952/91111426-e57d6e00-e656-11ea-9fa4-219b1184d8f4.png)

**Comment by SDGNelson** [comment]
That's because each map can have its own version number. The "Version" parameter is documented in the same article I linked. For example each vanilla map has a different version number.
