### ISSUE TITLE
Example FBX files don't work for Blender anymore

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#1953]
Blender received some updates not very long time ago, but example FBX models don't imports to it now. 
Blender says that **ASCII files are not supported**. It's really bad because to learn measurements and all model aspects users need FBX from examples.

**Comment by SDGNelson** [comment]
Which FBX models are those? Off the top of my head the only FBX files in the examples would be in the Unity packages needed for importing the models into Unity. Any example models intended for reference in Blender should be shared as Blend files.

**Comment by aladairmaxwell** [comment]
Every example FBX. But not all game assets have blend for reference in Blender, this is why I have to use FBX instead.

**Comment by FalkenJr** [comment]
Autodesk's FBX converter can fix your ASCII FBX files, though it doesn't play nice with model scaling and armatures
(The object scale in Blender is shrunk down to 0.010, and armatures are just outright broken)

https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives

There may also be addons for Blender that let it import ASCII FBX without any conversions, but I'm not aware if any are updated to the newer versions
