### ISSUE TITLE
Some devkit questions

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#1955]
• **How does game mode changes work?** Type Browser tab:
![image](https://user-images.githubusercontent.com/69295711/91434323-5302e780-e86d-11ea-88a2-8ddcd5197695.png)
I tried to use them but nothing happened. I bet there are some special way to use it. I want to change survival game mode to arena game mode.

• **What function does Terminal Window tab?**
![image](https://user-images.githubusercontent.com/69295711/91434756-f48a3900-e86d-11ea-96bc-329458d2b3ec.png)

I think it's supposed to be console to execute different commands, but I tried some and nothing happened. Maybe there are something more valuable for this feature?

• **How to create Insane or Tiny map?**
I think devkit used for it. Of course I can download insane or tiny template, but they were created somehow too, don't they?

**Comment by SDGNelson** [comment]
The game mode is specified when creating the level. You can replace the Level.dat with one from an Arena map. The terminal was used for commands, but was eventually replaced when all of the logging was unified. The only way to create other map sizes was early in 3's development.
