### ISSUE TITLE
Physics Project Settings

### ISSUE THREAD

**Issue by FabianWongJingLin** [SmartlyDressedGames/Unturned-3.x-Community#1956]
@SDGNelson 

Dear Nelson,

Do you mind letting us know the project settings on physics for Unturned?

**Comment by SDGNelson** [comment]
If you import the Project.unitypackage it should include the Physics Settings. Described here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GettingStarted.md

**Comment by FabianWongJingLin** [comment]
![image](https://user-images.githubusercontent.com/17795973/91536183-e9570c00-e946-11ea-8eea-5c542e03cb70.png)
Thank you for the quick reply. When I imported it, it seems that all the layers collides with one another. So, I was wondering if this is the same as the original layer collision.

**Comment by FabianWongJingLin** [comment]
One more question, are the new hooks - particularly the Timer and Activation hook, works on server side. Let say if I use the buttons in Unity, to deactivate a gameobject. Will the activation hook detect the deactivation and carry out the events on both client and server side?

**Comment by SDGNelson** [comment]
It looks like you are right that the collision layer matrix is not included in the project package yet. Will include for the next update.

The timer and activation hooks are only synchronized if the same object is activated and deactivated on both sides. Primarily the intention is to use them on the server to trigger something that can be replicated.
