### ISSUE TITLE
[Feature Request] Item usage reward

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1959]
An ability to give player an item after he uses water, food, medical item and e.t.c. would be a nice feature for the mods. Like giving an empty can to a player after he eats canned food, empty syringe after using adrenaline, or an infected filter when you change the filter for your gasmask (which you can later desinfect). This would also be a nice feature for mods based on crafting, like More Farming Mod, so you would have to craft a pile of some special materials, which you use (and it takes some time) and only then get the item you wanted to craft.

**Comment by SDGNelson** [comment]
For consumeable items? This should be possible with the `Quest_Rewards` property which supports all the reward types e.g. `Quest_Reward_0_Type Item`
