### ISSUE TITLE
Grass density setting overwrite for server

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1960]
Curious if its possible to add some setting for server to overwrite player's grass density setting? Asked multiple players what is an actual impact to performance with grass density set to low/medium/high/ultra. Only a few players noticed any impact when grass is set on ultra while low/medium/high doesnt give any noticeable impact. Speaking about players with pretty outdated PCs (from gtx 650 and up) who barely gets 20 fps.

Personally, on 1060 gtx I don't see any impact on ultra density.

Another setting is "terrain transition" - no impact even for those who got a small impact with ultra grass density.

**Comment by SDGNelson** [comment]
Sorry, but this is unlikely to happen yet because grass performance is bad on PCs that do not support instanced rendering. (you can tell if there is a warning symbol about instancing next to the setting) Maybe someday.
