### ISSUE TITLE
(Unity)Camera Component not working on First Person View?

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#1962]
I attached camera component on Sight or Tactical and use render texture to display them but it didn't work well. Problem was Every Mesh was in correct position but only Camera was stuck on world position not local position. I tried component that can hold(like fixed joint) it didn't work. Also tried changing Tag and Layers but none of them was able to fix it. Is this meant to be like this or some sort of bug? Hope this can be fixed because able to attach camera in first person can be really useful to make Live GPS, Thermal Vision Scope(sort of), Barricade Detector(good for server admin) and Lot's of different stuff.

(Note that screenshot was captured on Third Person freecam. Not first Person View. Also Scope Lens part was set to Enemy)

![2020-08-25 (2)](https://user-images.githubusercontent.com/57828757/91850019-dd957d80-ec97-11ea-9eaa-22221c7c978d.png)

**Comment by SDGNelson** [comment]
Interesting idea. The viewmodel is in a fixed position and only rotates which is why the camera would not work properly there. Supporting cameras on the viewmodel is unlikely to happen. There might be some clever workaround to get this working as is, but nothing off the top of my head.
