### ISSUE TITLE
tellBarricade and BarricadeManager

### ISSUE THREAD

**Issue by Fruten** [SmartlyDressedGames/Unturned-3.x-Community#1963]
Hello.
Can you add a method to make it easier to create barricades in the world and on transport? BariccadeManager.instanceCount is private, so you can't get it and add +1 for InstanceID from a barricade, for example, and so on.

**Comment by SDGNelson** [comment]
Use `dropPlantedBarricade` for vehicles and `dropNonPlantedBarricade` for non-vehicles.
