### ISSUE TITLE
Dedicated Server doesn't update mods

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#1965]
If you set some mods for Dedicated Server, then launch it, it won't see map received an update and do nothing to start shutdown. Also, if mod received an update, it don't update current downloaded version in server folder. But when player join server, he will receive last mod version. 

I have to clear mod folder everytime I need last map or mod version for server. Any solutions?

**Comment by joeymisfit** [comment]
@aladairmaxwell If you add them to **WorkshopDownloadConfig.json** it will automatically detect workshop updates per set interval in config and restart your server for that said update to take effect.

**Comment by aladairmaxwell** [comment]
I do it using WorkshopDownloadConfig, but nothing happens

**Comment by SDGNelson** [comment]
Steam should be detecting updates, but if not you can change `Use_Cached_Downloads` to `false` in the workshop download config. Unfortunately there is no good way for the game to detect if the installed files are up-to-date (yet), so it is up to Steam.
