### ISSUE TITLE
[Plugins/Modules] How to remove a vehicle?

### ISSUE THREAD

**Issue by Fruten** [SmartlyDressedGames/Unturned-3.x-Community#1966]
Hello.
Is there any way to remove a vehicle without using Harmony or Hooks?
NotSupportedException: This function should only be called from the game thread. (e.g. from Unity's Update)

**Comment by SDGNelson** [comment]
You can use `VehicleManager.askVehicleDestroy`, but judging from the exception you posted you are calling from a separate thread.

**Comment by Fruten** [comment]
I call this from the plugin when a player leaves the server using only Rocket and without threads.

**Comment by SDGNelson** [comment]
Well, wherever you are calling it from is running on another thread. Maybe async.

**Comment by Fruten** [comment]
Thanks.
