### ISSUE TITLE
[Plugins/Modules Question] How do I delay a player when connecting?

### ISSUE THREAD

**Issue by Fruten** [SmartlyDressedGames/Unturned-3.x-Community#1967]
Hello.
I use the delegate UnturnedPermissions.OnJoinRequested, which is based on Provider.CheckValid, making an async query to MySQL to give the player a new character name when connecting, but sometimes the database does not have time to send the value and the player comes with the old nick. Is there an earlier delegate or a way to hold up the player on connection?

**Comment by Trojaner** [comment]
There is no built-in way to do this. You would have to patch some methods to do this

**Comment by Fruten** [comment]
Thank you very much. I will listen to what Nelson will say (I know he will say the same x) ) and close the question.

**Comment by SDGNelson** [comment]
Trojaner is right that there is unfortunately no built-in way to do this (yet). I am working on abstracting the "transport layer", so at some point you could theoretically proxy the transport layer to delay connections until ready - not ideal but something at least.
