### ISSUE TITLE
Vehicle noclip

### ISSUE THREAD

**Issue by wristcry** [SmartlyDressedGames/Unturned-3.x-Community#1968]
Hi
Im writing some sort of serverside anticheat(cuz hwid banned by be 0_o), so i need to fix vehicle noclip.
It works by changing Rigidbody.useGravity to false, Rigidbody.isKinematic to true and by calling Rigidbody.MovePosition, but as i understand vehicle gameobject(and its components as well) are clientsided, so is there any way to get or set this variables values from serverside?

Removing players from vehicle if its 15m from the ground is good, but i think thats not a proper way to fix vehicle noclip 0_o

**Comment by SDGNelson** [comment]
You can move the vehicle server-side and it will override the client-side value if the difference is big enough, but the server already does any checks that I felt were reasonable.

**Comment by Fruten** [comment]
> You can move the vehicle server-side and it will override the client-side value if the difference is big enough, but the server already does any checks that I felt were reasonable.

The vehicles can fly if their position is changed from the client's side. Bad checks)))

**Comment by GazziFX** [comment]
lol
https://youtu.be/H2L4JWhGhIU

**Comment by wristcry** [comment]
> lol
> https://youtu.be/H2L4JWhGhIU

ok cool
but i needed to full fix this thing(fly ability too), not only ability of vehicle to clip thru the walls 0_o
actually i got same fix, but thats not what i wanted
