### ISSUE TITLE
Scroll the chat window will cause game crash

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#1970]
Scroll the chat window to top, sometimes Unturned will stuck about 10 seconds (00:04 - 00:14 in video), and then automatic exit, without popping the crash window. 

I think it just my computer's problem. But after more and more Player reports this, it may have a problem in my server. 

I use API `UnturnedChat.Say()` to send message in the plugin. It shouldn't cause game crash. 

How to locate problem and fix it? I have no idea!

Video:
https://youtu.be/yJ6Dx6UyW2g

Log:
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5183167/Client_Prev.log)

**Comment by educatalan02** [comment]
Send the log of the server too

**Comment by warren39** [comment]
Server log shows :
[Info] Disconnecting: PlayerID: 765611988...

It is Info level. can't find any Warning or Error level log.

**Comment by SDGNelson** [comment]
Off the top of my head the only difference with UnturnedChat.Say would be because Rocket (UnturnedChat) splits long strings into multiple messages, but crash-wise that should be no different than players chatting multiple messages.

Are any other hosts running into this issue?

**Comment by SDGNelson** [comment]
Sorry about the issue. It looks like this is probably related to the older IMGUI system being used for the game HUD. It should be fixed when the UI text is updated to use TMP, but that is a big rewrite which I do not have an ETA for yet. :/

**Comment by warren39** [comment]
Oh! Rewrite the IMGUI system really isn't an easy! Suggest provide a temporary solution: Add a config option to disable the chat window scrollable in server Config.json
And then player can't scroll the chat window in the server.
The server can use a EffectUI plugin to show more chat history. I can make the plugin.

**Comment by SDGNelson** [comment]
Definitely not easy. My plan is to abstract the IMGUI vs uGUI vs UIElements implementation so the existing UI code can remain relatively the same for now. Here is the issue if you want to subscribe for updates: #1234

**Comment by SDGNelson** [comment]
Happy to say the uGUI refactor is now on a beta branch! #2059
