### ISSUE TITLE
Error! Incorrect display of the character's hands!

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1973]
When I make a pivot turret for a driver with a seat index 0. When the turret is rotated, the character's hands in the first person view remain flying in the air and are not tied to the turret rotation. I propose to introduce an option to disable the display of hands in the first person.
![1](https://user-images.githubusercontent.com/52251537/93003993-f29dc680-f54b-11ea-9df4-12765970a614.png)

**Comment by SDGNelson** [comment]
For the meantime the closest option would be to use one of the alternative sitting poses, or the camera attached to the turret.
