### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nazmiyigitefe** [SmartlyDressedGames/Unturned-3.x-Community#1975]
![unknown-18](https://user-images.githubusercontent.com/71214979/93016767-44863100-f5cc-11ea-93a4-e755dfabc521.png)
We're using a plugin and We're taking that error. And The Developer Says:
Cuz regions are out of sync
You have to talk to Nelson bout this

Have A Nice Day.

**Comment by GazziFX** [comment]
I've never had this problem, even with a lot of plugins interacting with barricades. I think you need to clear the map, if it doesn't help, then the problem is with this plugin

**Comment by rube200** [comment]
Problem is maybe the plugin is bad coded, that was a very old problem.
What does the plugin do? (don't need details)

**Comment by SDGNelson** [comment]
From your "We're using a plugin and We're taking that error" are you saying it only happens with a specific plugin? In that case it is up to the plugin developer to resolve the issue.
