### ISSUE TITLE
[Question: NPC] Is it possible to code an NPC to give a quest wherein you have to mine x boulders or cut x trees?:

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1977]
I was thinking about a new quest to make for an NPC, and I thought perhaps to do a quest where you've got to cut a few trees down, is this possible in the current NPC framework?

**Comment by iBowie** [comment]
Yes it's possible, yet not documented in the official guide.

**Comment by INeedHelp225** [comment]
How so?

**Comment by SDGNelson** [comment]
It was added relatively recently IIRC. The condition type is `Kills_Tree`, and has a `_Tree` property which is the GUID of the resource asset to mine.

**Comment by INeedHelp225** [comment]
That's neat! I'll be sure to use that. Is there one for boulders specifically, or can kills_tree be used with the boulder GUID rather than a tree GUID?

**Comment by SDGNelson** [comment]
Yes, boulder GUIDs can be used as well.
