### ISSUE TITLE
[Feature Request] More perks for servers using GSLTs

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#1978]
What the title says. Some ideas could be an official and an unofficial server section maybe (official servers are using GSLTs but unofficial servers are not). Or instead of that a tag gets added to the server name that says something about it being official or verified.

**Comment by GazziFX** [comment]
It doesn't make sense for players.
In CSGO GLST is required to get cases

**Comment by SDGNelson** [comment]
It would be nice to require GSLTs for listing, but this is up to Valve, and the game has no way to check if the server has one or not.
