### ISSUE TITLE
Vehicle Drivewheel

### ISSUE THREAD

**Issue by FabianWongJingLin** [SmartlyDressedGames/Unturned-3.x-Community#1979]
Hi Nelson,

May I know which are the drive wheels of the vehicle?

**Comment by SDGNelson** [comment]
The first two wheels are steering, and the other wheels are powered.

**Comment by FabianWongJingLin** [comment]
I am assuming by other wheels, you meant that tire_2 to tire_X where X is > 2 right? If that's the case, how is the motor torque given to each tire. Let say the motor torque is 100. Is the motor torque divided and distributed to all the drive wheels or each drive wheels have a 100 motor torque?

Finally, the speed_max and min determine the motor torque given to the drive wheel right? may I know the formula?

**Comment by SDGNelson** [comment]
> you meant that tire_2 to tire_X where X is > 2 right?

Yes

> Let say the motor torque is 100. Is the motor torque divided and distributed (100/drivewheels) to all the drive wheels or each drive wheels have a 100 motor torque?

Each drive wheel has a motor torque determined from the speed values.

> Finally, the speed_max and min determine the motor torque given to the drive wheel right? Or a motor torque is randomly given, but you limit the speed to max and min?

You are correct that the speed values determine the motor torque, but the motor torque is also raised and lowered if the vehicle is moving faster or slower than expected.

**Comment by FabianWongJingLin** [comment]
Thank you for replying so quickly. Hmm, I cant seems to get the vehicle to work with more than 4 wheels. It basically starts to move like a tortise when more than 4 wheel contacts the ground. I was thinking it could be the mass of the vehicle + tires, but didnt come to a conclusion. Perhaps you can enlighten me?

**Comment by SDGNelson** [comment]
Perhaps related to the wheel friction if it is moving slowly while contacting the ground? Unfortunately the game overrides those values by default for backwards compatibility, but you can set your own values with a vehicle physics profile: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/VehiclePhysicsProfile.md

**Comment by FabianWongJingLin** [comment]
Thank you again for the quick reply, I will play around with it when I have time.
