### ISSUE TITLE
No option to upload Maschinengewehr skins

### ISSUE THREAD

**Issue by danaby2** [SmartlyDressedGames/Unturned-3.x-Community#198]
https://gyazo.com/6c1d691e763ff40fec25ac20d95d5e6b

Theres is no option to upload skins for the german maschinengwmwehmsme gun thing pls fix

**Comment by SirAdyUnleashed** [comment]
Yeah, it should also be mentioned that there is no option to upload Train type vehicles to the Workshop neither. Should probably get tweaked too.

**Comment by SDGNelson** [comment]
Will fix both. It may have been listed under MP40 at one point.
