### ISSUE TITLE
The ability to disable vehicle movement

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1980]
So Im trying to make an aircraft carrier vehicle, but to do that I need to somehow disable the vehicle's movement when the Headlights are turned on (Ctrl key is reserved for the magnet just like in skycrane) or when the driver's seat is empty using ModHook. If I wont find a way to disable it's movement, then the carrier will drown the second you land a plane on it, because this is just the way vehicles interact with each other. The thing is, I dont know how to do that. Can someone tell me the right combination of unity components or anything that could result such option for the vehicle. Any other solution for avoiding the colliding problems between planes and the aircraft carrier itself would also be nice.
Turning off gravity or setting rigidbody as kinematic wont work for sure, since Unturned uses it's own vehicle physics system.

**Comment by FabianWongJingLin** [comment]
You can try the new mod hook, if the headlight is disable/enable, enable an object that has a fixed joint attached to the vehicle with a rigidbody that freezes the position and rotation if you dont want it to rotate

**Comment by SDGNelson** [comment]
Ideally landing the jet on the boat would just work, but that is easier said than done.

In the future a component that overrides some vehicle properties like whether physics are enabled could be added, but for the meantime a fixed joint as FabianWongJingLin describes is probably your best bet.
