### ISSUE TITLE
My server doesn't work properly with -NetTransport=SteamNetworkingSockets

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#1981]
I put it into my command-line arguments
![image](https://user-images.githubusercontent.com/69295711/93633038-fa031b00-f9f6-11ea-85b5-ae4f2a8e7264.png)

Server decided not to follow my Commands.dat and other things such download config. What should I do to test it?
I'm using dedicated server.

**Comment by SDGNelson** [comment]
Unfortunately it is probably treating "Testing -NetTransport=SteamNetworkingSockets" as the server id. If you put the -NetTransport=SteamNetworkingSockets after .bat it should work.

**Comment by aladairmaxwell** [comment]
Yes, that's helped. I tested the new netcode with people, and it's almost perfect! Now skycrane and some modded tow trucks can drag vehicles like normal. Car "crashes" with other players now work fine, cars don't fly in all sides after impact. That means a lot.
Will wait for other netcode changes in near future!

**Comment by SDGNelson** [comment]
Glad to hear that it has been working well for you so far!
