### ISSUE TITLE
Stuck on Waiting for Steam servers...

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#1982]
After this recent patch, most of my servers are being affected by this issue. The server will load all of the plugins but then get stuck on saying "Waiting for Steam servers..." (I saw this is the Server_unturned.log)

Screenshot of console:
![unknown (2)](https://user-images.githubusercontent.com/42988619/93635041-33b43180-f9b7-11ea-80ac-dffe12ccf925.png)

Snippet from Server_unturned.log:
`[2020-09-18 12:58:48] BattlEye Print: Initialized (v1.217)
[2020-09-18 12:58:48] Using login token
[2020-09-18 12:58:48] Parsed '-NetTransport' as 'SteamNetworkingSockets' from command-line
[2020-09-18 12:58:48] Initializing ServerTransport_SteamNetworkingSockets
[2020-09-18 12:58:48] Server listen socket bound to [::]:27025
[2020-09-18 12:58:48] Waiting for Steam servers...
[2020-09-18 12:58:53] Can't add script behaviour . The script class can't be abstract!**`

Server_unturned.log:
[Server_unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5247680/Server_unturned.log)

**Comment by SDGNelson** [comment]
It might simply be temporary maintenance or temporary loss of connection to the Steam backend, because "waiting for Steam servers" is waiting for the game server login (unaffected by these changes). Note I recommend using the default net transport for now in order to narrow down bugs.

**Comment by Ascivv1** [comment]
> It might simply be temporary maintenance or temporary loss of connection to the Steam backend, because "waiting for Steam servers" is waiting for the game server login (unaffected by these changes). Note I recommend using the default net transport for now in order to narrow down bugs.

Hmm, ok. This has been happening for a few hours though, so I don't know if this temporary issue should be lasting this long.

**Comment by SDGNelson** [comment]
If you try launching without plugins does it connect? (the reason I assume it is a connection issue is that lots of servers seem to be connected normally)

**Comment by PandahutMiku** [comment]
Shot in the dark: Try copying your map files to a different directory and starting with a fresh map/no map files. I swear I remember having this issue before with a corrupt map. That's just my best guess though.

**Comment by jatapa** [comment]
the issues is the token I tried with a new token and it did not load the server removing the token fixes it

**Comment by PandahutMiku** [comment]
> the issues is the token I tried with a new token and it did not load the server removing the token fixes it

Apparently it was
![image](https://user-images.githubusercontent.com/17209937/93638867-163a9400-f9c6-11ea-9a9b-e1916bcbe33e.png)
However all of our 19 Servers are running with Tokens with zero issues. I think his tokens just expired due to inactivity. Steam is kind of strict on them. Would be nice if Nelson could have it automatically fall back to not using them if it hits an error using them.

**Comment by jatapa** [comment]
Yes he found the issue because I told him it

**Comment by Ascivv1** [comment]
Yeah the issue has been taken care of, thanks jatapa for the input and fix.

**Comment by SDGNelson** [comment]
Thanks jatapa and Miku! Off the top of my head I am not sure if there is a callback for failed token logon, but I will check into it.

**Comment by SDGNelson** [comment]
For the next update there will be messages in the console and logs when the connection to Steam fails or is lost
