### ISSUE TITLE
Servers aren't starting since latest update

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#1983]
Many errors preventing servers from starting up, this is happening on 4 seperate servers.

Log is attached:
[Server_x.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5247999/Server_x.log)

**Comment by SDGNelson** [comment]
Sorry for the issue, and thanks for the log! In the meantime if you remove the "Owner" command from Commands.dat it should work properly. I will fix that in a patch.

**Comment by lourenco321** [comment]
Same I run a public server with around 30 average users and this just happened to me 

What can we do?

**Comment by lourenco321** [comment]
> Sorry for the issue, and thanks for the log! In the meantime if you remove the "Owner" command from Commands.dat it should work properly. I will fix that in a patch.

Thank you :)

**Comment by AdamDN** [comment]
> Sorry for the issue, and thanks for the log! In the meantime if you remove the "Owner" command from Commands.dat it should work properly. I will fix that in a patch.

I can confirm this fixed the issue. Thanks!

**Comment by SDGNelson** [comment]
Since it is the only bug reported so far and minor / easy to work around, I will wait until the next update on Friday the 25th to include the fix so players do not have to download as many updates. The next update will make the new Steam Network V2 default.
