### ISSUE TITLE
My Server Including alot of others arent working!

### ISSUE THREAD

**Issue by xMagicc** [SmartlyDressedGames/Unturned-3.x-Community#1984]
**Alot of my friends and mine servers arent working since the new update. First when we updated our servers we werent able to start the server at all. It was saying we started it but the console was empty. Then i decided to reinstall my server and i did but now its showing something even more weirder to me  
[Server_server.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5248012/Server_server.log)

Please check this out and try to help us. We all are having the same issue!
Thanks alot     -Kozawa**

**Comment by jatapa** [comment]
same as #1983

**Comment by SDGNelson** [comment]
Sorry for the issue, and thanks for the log! In the meantime if you remove the "Owner" command from Commands.dat it should work properly. I will fix that in a patch.

**Comment by xMagicc** [comment]
Thank you for your Help it has fixed all of our servers!

**Comment by joeymisfit** [comment]
@SDGNelson Both myself and Miku we're talking about possible causes and it seems that lowercase "o" in owner throws the servers into an infinite restart loop. However capital "O" in Owner doesn't. Hope this helps!

**Comment by SDGNelson** [comment]
Since it is the only bug reported so far and minor / easy to work around, I will wait until the next update on Friday the 25th to include the fix so players do not have to download as many updates. The next update will make the new Steam Network V2 default.
