### ISSUE TITLE
Server is not starting up after latest update

### ISSUE THREAD

**Issue by roysushi** [SmartlyDressedGames/Unturned-3.x-Community#1985]
After I have updated the server to the latest version, I can't seem to turn my server back up.
This is the error that is showing on my server :

[2020-09-19 04:32:52] NullReferenceException: Object reference not set to an instance of an object
[2020-09-19 04:32:52] SDG.Unturned.Provider.listenClient () (at <5994837968aa4ababc780312c58791ac>:0)
SDG.Unturned.Provider.listen () (at <5994837968aa4ababc780312c58791ac>:0)
SDG.Unturned.Provider.Update () (at <5994837968aa4ababc780312c58791ac>:0)

**Comment by SDGNelson** [comment]
Do you have the "Owner" command in Commands.dat? For the meantime removing that should work, and will be fixed in the patch.

**Comment by roysushi** [comment]
alright, it worked after I have removed the Owner in the commands.dat
Thank you so much

**Comment by SDGNelson** [comment]
Sorry about that. Will be fixed in the patch!
