### ISSUE TITLE
Steam can not be initialized: Steamworks GameServer is not initialized. after last update

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#1986]

**Comment by SDGNelson** [comment]
Unfortunately GameServer Init can fail for quite a few reasons without an error code. Would suggest running steamcmd and server -validate to ensure everything is updated.

**Comment by D-AIRY** [comment]
Validating didn't help. Issue solved by replacing steamclient.so file with file from another game
