### ISSUE TITLE
RocketMod AddPlayerToGroup, RemovePlayerFromGroup not working properly

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1987]
I'm using that inside of `private void OnPlayerConnected(UnturnedPlayer player)` and it's not working for some reasons in this new update, was working before idk

**Comment by SDGNelson** [comment]
Those events are still invoked at the same times, so what seems to be the issue? i.e. what aspect is not working?

**Comment by TH3AL3X** [comment]
> Those events are still invoked at the same times, so what seems to be the issue? i.e. what aspect is not working?

I will check it again, :/
