### ISSUE TITLE
Loot spawn does not work on interaction with the box

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#1988]
Hello everyone, today, while creating a cool mod, I ran into the problem that loot will not spawn on my server after I clicked the "Use" button on the box. At the same time, everything works in the single player. 
Help me solve this problem (I have not found any examples of work.)
**P.S. I suppose some tags are needed Drop**

**Comment by aladairmaxwell** [comment]
Oh, that's easy enough. Just add GameObject called "Drop" and add tag and layer for objects (e.g small, medium, large). Make sure nothing blocks Drop.

**Comment by PARTOVIY** [comment]
The fact of the matter is that Drop does not block anything.
I added this Drop point and in multiplayer nothing will spawn anyway

**Comment by PARTOVIY** [comment]
@SDGNelson

**Comment by DerpyHoowes** [comment]
Did you add it to the Clip prefab too? Clip is basically the way server reads your object, so if you applied something to the main prefab but didn't add it to the Clip, it wont work on servers

**Comment by PARTOVIY** [comment]
> Вы тоже добавляли его в префаб Clip? Clip - это в основном способ, которым сервер читает ваш объект, поэтому, если вы применили что-то к основному префабу, но не добавили его в Clip, он не будет работать на серверах.
Thanks <3
