### ISSUE TITLE
bug seeds

### ISSUE THREAD

**Issue by eumodded** [SmartlyDressedGames/Unturned-3.x-Community#1989]
seeds almost instant grow i tested it on 4 server on works on all with maxskills

https://youtu.be/nYgnG8pXIlw

**Comment by PandahutMiku** [comment]
Are you sure this isn't a quirk/setting of the server you are playing on? Are they your servers, and did you try running with no plugins? I cannot replicate this on my own server with max skills, it just slowly goes up like normal.

**Comment by eumodded** [comment]
I tryed it on a vanille server 
But i Will do more testing tomorrow

**Comment by SDGNelson** [comment]
Closing because it was probably config (and I could not reproduce at the time either), but feel free to comment and I will re-open.
