### ISSUE TITLE
PSA: Unity 2019 LTS

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1994]
The game has been updated to Unity 2019.4.10f1 LTS on the `unity-2019` branch.

Please comment here if you run into any issues.

**Comment by baranmod** [comment]
Just tested, bundles/plugins seem to work fine at first sight, one error appears to be spamming in player logs:
https://pastebin.com/YAkj3NKq

**Comment by SDGNelson** [comment]
Thanks for testing with your plugins. I got that error today when double-checking on Mac (had only tested 2019 on Windows the past week or two), but not Windows. Which map + platform did you get it on?

**Comment by baranmod** [comment]
It was on Windows + custom map

**Comment by Johnanater** [comment]
I tried it just now using the Linux client. I tried going into a PEI singleplayer map, but it stalled with a ton of errors in the log. It looks like asset loading issues :(

https://gist.github.com/Johnanater/211deaf39eb81086765bc4201e07f7b6

**Comment by SDGNelson** [comment]
This morning I put up a patch that seems to have resolved that bug. As for the Linux loading, I must have missed the Linux asset bundles when setting up the project in Unity 2019 (the asset bundles are not kept in source control) - now they are rebuilt and should load properly. 🤞

**Comment by PandahutMiku** [comment]
Is this planned to come out this Friday or are you waiting for more time/more people testing it?

**Comment by TH3AL3X** [comment]
@SDGNelson One thing I said in another post about the problem with server startups, when I started two servers at the same time there were no problems, but instead when I started a server and it loaded correctly, and started the other server, the first server was it crashed, and all this in the same instance, and it came out as a memory leak I suppose it will be solved, but I say it for you to look at that, thanks ....

**Comment by SDGNelson** [comment]
> Is this planned to come out this Friday or are you waiting for more time/more people testing it?

Since the Steam Networking Sockets are becoming default today the Unity 2019 update will wait to space out the big changes. That said, the Unity 2019 update seems fairly stable.

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/95613518-622ca600-0a65-11eb-9610-0c9e58f708f4.png)

**Comment by SDGNelson** [comment]
@TH3AL3X responding in the other thread because this topic is for Unity 2019

**Comment by PandahutMiku** [comment]
> > Is this planned to come out this Friday or are you waiting for more time/more people testing it?
> 
> Since the Steam Networking Sockets are becoming default today the Unity 2019 update will wait to space out the big changes. That said, the Unity 2019 update seems fairly stable.

I hate to bother you again about this, but do you plan to push unity 2019 this friday or no? It has some nice additions, and seems GameServerNetworking is stable enough besides Valve-specific issues.

**Comment by SDGNelson** [comment]
> I hate to bother you again about this, but do you plan to push unity 2019 this friday or no?

Not a bother. It does seem stable so I am thinking about doing the transition after Halloween, playing it safe in case there is a Halloween surge, but I will make sure to provide plenty of heads up. I have been working for 3-4 weeks now on the UI refactor which will be on a separate beta branch and release sometime after 2019 is merged.

**Comment by SDGNelson** [comment]
Unless any issues are reported this should be on track to release November 13th!
