### ISSUE TITLE
NPC can't be talked to

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1995]
Sorry to bug you all with NPC issues every other week, I promise I'll get better at this.
I've made an NPC who is supposed to give a quest when asked about his worried disposition, but no matter what I do, the game does not recognize the dialogue as dialogue. I've verified the NPC does indeed link his dialogue right, and have redone his and his diag's GUIDs a million times now.
Strangest thing being that if I copy another working NPC's asset diag, it works fine. I have no idea what I've done wrong.

Asset:

GUID afc89ab8b3e04fb193588f903cd1b317

Type Dialogue
ID 30220

Messages 3

Responses 5

//other faction hostile diag
Message_0_Pages 1
Message_0_Responses 1
Message_0_Response_0 5
Message_0_Conditions 1
Message_0_Condition_0_Type Flag_Short
Message_0_Condition_0_ID 3017
Message_0_Condition_0_Value -1
Message_0_Condition_0_Logic Less_Than_Or_Equal_To

//after quest is done dialogue
Message_1_Pages 1
Message_1_Responses 3
Message_1_Response_0 0
Message_1_Response_1 5
Message_1_Response_2 3
Message_1_Conditions 1
Message_1_Condition_0_Type Flag_Short
Message_1_Condition_0_ID 30212
Message_1_Condition_0_Value 1
Message_1_Condition_0_Logic Equal

//Work Pathway
Response_1_Dialogue 30201
Response_1_Conditions 1
Response_1_Condition_0_Type Quest
Response_1_Condition_0_Logic Equal
Response_1_Condition_0_ID 30208
Response_1_Condition_0_Status None

//Complete Quest
Response_2_Dialogue 30207
Response_2_Quest 30208
Response_2_Conditions 1
Response_2_Condition_0_Type Quest
Response_2_Condition_0_Logic Equal
Response_2_Condition_0_ID 30208
Response_2_Condition_0_Status Ready
Response_2_Condition_0_Reset

//nervous main neutral no faction no finished job
Message_2_Pages 1
Message_2_Responses 5
Message_2_Response_0 0
Message_2_Response_1 1
Message_2_Response_2 2
Message_2_Response_3 5
Message_2_Response_4 3

//ask about what he does
Response_0_Dialogue 30205

//ask about what hes building
Response_5_Dialogue 30206 

English:

Message_0_Page_0 Out of here, ape.
Message_1_Page_0 Thanks for your work!
Message_2_Page_0 Oh, man... Ohhhh, man! Uhhh... errrmmm, oh mann....

Response_0 What do you do?
Response_1 What's wrong, man?
Response_2 Here he is!
Response_3 Goodbye
Response_4 Ooohaa-oh-oh-oh-aaa monkey!
Response_5 What'cha building?

**Comment by iBowie** [comment]
You've set response count to 5, when you actually have 6 responses. This might be an error here.

**Comment by INeedHelp225** [comment]
@iBowie I have just tried that to no avail unfortunately

**Comment by INeedHelp225** [comment]
I just changed the ID of the npc for the tenth time and it worked for some reason. Thank you for the response!
