### ISSUE TITLE
Unturned T-Shirts

### ISSUE THREAD

**Issue by GoryBark** [SmartlyDressedGames/Unturned-3.x-Community#1996]
Hello Nelson! Recently, i have been wondering if i would be able to make some Unturned related t-shirts, and sell them to friends/people online through word of mouth. This would probably break some sort of copyright rule, and i was wondering if i could get your permission/guidance when doing this. Thanks!

**Comment by Gandalf-png** [comment]
Make a rip off called turned, fixed your problem.

**Comment by GoryBark** [comment]
Boi

**Comment by GoryBark** [comment]
Answer me nelson or i shall smite thee spinal cord into he twelfth dimension!

**Comment by GoryBark** [comment]
Nelsoooon ):

**Comment by Trojaner** [comment]
Please stop spamming our emails and close the issue. Obviously this has very little chances on get accepted.

**Comment by GoryBark** [comment]
Sorry ):
