### ISSUE TITLE
invisible players

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#1997]
Hello,
there was an invisible player who could see me and shoot me, but I can't see him.
I have encountered this issue about a month ago on sandbox servers, but I thought it might be their plug-ins ..
before few days a player reported same issue at our servers.
and today a friend encoutered the same issue on different servers.

here is some videos:
https://www.youtube.com/watch?v=6gpFYxdiys4&ab_channel=Zenmaster

I would like to qoute what he said:
...
as you see in the video
he neither does sound at shooting
but he does at reloading ...
it was bug 100% cause my friend relogged and could see him
while i couldnt
then he relogged (the suspect) and i could see him

**Comment by nanashi88** [comment]
here is another video
https://www.youtube.com/watch?v=nb2PO5pRINQ

**Comment by TH3AL3X** [comment]
It's something related of Max Players, someone plugins can override that and bypass the queque position, like 32/24, etc... , thats make those bugs

**Comment by nanashi88** [comment]
btw, about what happened to me, it was on 3/7/2020, but I noticed some difference that the killer name doesn't show , it shows like ?[?]
so maybe that is different bug.

**Comment by nanashi88** [comment]
> 
> 
> It's something related of Max Players, someone plugins can override that and bypass the queque position, like 32/24, etc... , thats make those bugs

I could confirm that at least two of the servers has this feature
@TH3AL3X thank you

**Comment by rube200** [comment]
What happen when do u teleport to that invisible player?

**Comment by TH3AL3X** [comment]
> What happen when do u teleport to that invisible player?

I think you can't, because doesn't appear in the user list

**Comment by PandahutMiku** [comment]
> What happen when do u teleport to that invisible player?

It would probably work because the server is still sending/receiving from them, since they are still connected, thus they're probably in the server's Provider.clients list, and commands execute on the server.

I wonder if Nelson changed some way the networking works to cause issues if there are more players then max players allows. I've seen this way in the past, but thought it was just a fluke, and heard nothing more about it. Would be nice if he just let servers go up to 48 slots at least without being delisted, although "you should do it because all of the servers bypass this anyway" isn't the best argument for it.

**Comment by nanashi88** [comment]
there was something at 11/9 game update :
> "-HostPlayerLimit" command-line parameter for hosting providers.

what is this for? is it related to add extra players slots?

**Comment by rube200** [comment]
in case the problem is the maximum fake slots, this can be steamworks itself because I didn't find anything that could cause this on unturned code

**Comment by TH3AL3X** [comment]
> there was something at 11/9 game update :
> 
> > "-HostPlayerLimit" command-line parameter for hosting providers.
> 
> what is this for? is it related to add extra players slots?

No realmente, el problema viene cuando el servidor esta utilizando un plugin que haga un salto del Queque position.

**Comment by SDGNelson** [comment]
Judging especially by the "? [?]" text, it appears the client has not received the packet informing them the other player has connected. The other player does exist on the server, but not specific clients. If you do have plugins affecting the login queue or tampering with packets those are likely causes. With the future netcode improvements I would like to make this harder to break.

> what is this for? is it related to add extra players slots?

It was requested by hosting providers to limit servers to particular max players. For example if a customer is renting an 8 slot server they can set max players to 8, but any higher value will be clamped to 8.

**Comment by nanashi88** [comment]
we have disabled the module that adds extra slots few days ago, and unfortunately we just received the following report:
```
cheater on russia 1
invisible nickname
i cant find him in menu
```

**Comment by TH3AL3X** [comment]
nanashi88 , where i can contact with you? , add me via discord if you can, i want to talk with you 
TERROR#1337

**Comment by nanashi88** [comment]
@TH3AL3X 
sorry, just noticed.
I have added you

**Comment by baranmod** [comment]
I think thats a very big issue currently. Usually, there are 2-3 invisible players per day, sometimes it starts in waves and one player becomes invisible after another. Not sure if its actually slot extending plugin's fault or not (it happened once with 15~ players online). If it is, then, honestly, those slot limitations should be lifted. Most of somewhat popular servers are way above 24 players and large map + 24 players gives a death taste to the game..

**Comment by SDGNelson** [comment]
Is this slot extending plugin on GitHub? I can take a look and see what it might be doing that would cause issues.

**Comment by PandahutMiku** [comment]
> Is this slot extending plugin on GitHub? I can take a look and see what it might be doing that would cause issues.

I believe it is: https://github.com/Tortellio/MaxplayerModifier/blob/master/Main.cs

The bug itself is strange though. We use our own custom max players plugin, but have had zero reports of any invisible players, even with servers up to 30+ players.
![image](https://user-images.githubusercontent.com/17209937/95140475-f7196180-073c-11eb-9756-63b5d082ba60.png)
(Graph is just of player count per server, with each server being colorized, might not be best way to show that data)

It might be because that plugin is constantly changing the max-players up and down that causes this issues with clients?

**Comment by baranmod** [comment]
Personally, using custom one. Also, questioned one "invisible player" a bit today. He mentioned that his teammates (steam group) seen him normally while others couldn't. Can't tell if he became invisible for others at the moment he connected to server or later. Checked his client log, didn't see any errors on connection

**Comment by TH3AL3X** [comment]
It's very weird, because I remember, if you reconnected you could see the player for strange reasons....

**Comment by SDGNelson** [comment]
Thanks Miku. Looking at the related code nothing jumps out at me as a huge issue, e.g. nothing uses a cached MaxPlayers pre/post those OnPlayerX events, but it does feel precarious especially if other plugins are also using those events and might run into unexpected behavior. By default the game assumes MaxPlayers is not changed after startup (MaxPlayers command is pre-launch only), but I do not see anything that would break in the base game if it changes.

**Comment by rube200** [comment]
> > Is this slot extending plugin on GitHub? I can take a look and see what it might be doing that would cause issues.
> 
> I believe it is: https://github.com/Tortellio/MaxplayerModifier/blob/master/Main.cs
> 
> The bug itself is strange though. We use our own custom max players plugin, but have had zero reports of any invisible players, even with servers up to 30+ players.
> ![image](https://user-images.githubusercontent.com/17209937/95140475-f7196180-073c-11eb-9756-63b5d082ba60.png)
> (Graph is just of player count per server, with each server being colorized, might not be best way to show that data)
> 
> It might be because that plugin is constantly changing the max-players up and down that causes this issues with clients?

I have a plugin that just change max player at load and still bypass max players.
I have some reports from the server about the invisible problem.
So I am about sure that problem can be in steamworks

**Comment by TH3AL3X** [comment]
And another thing @SDGNelson , Do you remember the post I made about the hwid getting the number 0 always?, Well, it was a plugin of this type that gave this type of bug ...

**Comment by SDGNelson** [comment]
Even the built-in MaxPlayers command can be set to 100. The difference is setting the advertised max players to 24. In the next update the client will only show servers with >24 max players OR >24 current players when the `Show_Servers_With_Greater_Than_Recommended_Players` preference is enabled to prevent that unintended workaround.

If you can link the problem-causing plugin's code I can take a look.

**Comment by baranmod** [comment]
If I understood correctly, this option (to show servers above 24 player) will be disabled by default? If so, why is it so? It reminds me the workshop filter when it was set to false by default and only minority of players were able to find modded servers. I believe, players should be able to decide themselves which server is having a suitable performance for them. While owner of a server should be testing various options to find a sweet spot for their community.

On top of that, you can get better performance on large (more detailed) map with 48 players online than on Russia map on empty server.

**Comment by TH3AL3X** [comment]
> Even the built-in MaxPlayers command can be set to 100. The difference is setting the advertised max players to 24. In the next update the client will only show servers with >24 max players OR >24 current players when the `Show_Servers_With_Greater_Than_Recommended_Players` preference is enabled to prevent that unintended workaround.
> 
> If you can link the problem-causing plugin's code I can take a look.

It's from imperialplugin so i cannot give you the source.

**Comment by SDGNelson** [comment]
> If I understood correctly, this option (to show servers above 24 players) will be disabled by default? If so, why is it so? It reminds me the workshop filter when it was set to false by default and only minority of players were able to find modded servers. I believe, players should be able to decide themselves which server is having a suitable performance for them. While owner of a server should be testing various options to find a sweet spot for their community.

That option has existed in the game for a long time, and has always defaulted to false. The difference now is that servers advertising a fake max player count will properly be hidden when the option is disabled. It only affects the internet server list, so e.g. the favorite and history lists are unaffected.

Long-term the netcode performance will be improved to better support higher player counts.

> It's from imperialplugin so i cannot give you the source.

Which plugin and creator? I will ask Trojaner about it.

**Comment by baranmod** [comment]
Could you clarify if a count in server lobby will be affected by this change? For example, on server list it shows 24/24 while on lobby it shows 48/24?

**Comment by rube200** [comment]
@SDGNelson I have one of that plugins not release yet, do u want me to send to your email that part?

**Comment by TH3AL3X** [comment]
> > If I understood correctly, this option (to show servers above 24 players) will be disabled by default? If so, why is it so? It reminds me the workshop filter when it was set to false by default and only minority of players were able to find modded servers. I believe, players should be able to decide themselves which server is having a suitable performance for them. While owner of a server should be testing various options to find a sweet spot for their community.
> 
> That option has existed in the game for a long time, and has always defaulted to false. The difference now is that servers advertising a fake max player count will properly be hidden when the option is disabled. It only affects the internet server list, so e.g. the favorite and history lists are unaffected.
> 
> Long-term the netcode performance will be improved to better support higher player counts.
> 
> > It's from imperialplugin so i cannot give you the source.
> 
> Which plugin and creator? I will ask Trojaner about it.

https://imperialplugins.com/Unturned/Products/QueueBypasser
**Adam**

**Comment by SDGNelson** [comment]
To clarify: I doubt that calling SteamGameServer.SetMaxPlayers is the cause of the problem.

> For example, on server browser list it shows 24/24 while on lobby it shows 48/24?

It looks like you are right that the master server returns the min of player count, max players so the situation will continue as it is for now.

> do u want me to send to your email that part?

Sure, if you would like I can take a look.

> QueueBypasser

I will ask Trojaner about it.

**Comment by nanashi88** [comment]
> To clarify: I doubt that calling SteamGameServer.SetMaxPlayers is the cause of the problem.
for reference: our servers were using the following code (after Level.isLoaded is true):
```
  Provider.maxPlayers = (byte)this.config.MaxPlayers;
  SteamGameServer.SetMaxPlayerCount(24);
```
but we have disabled this feature.
and there was no more reports on invisible players since we disabled this feature.

**Comment by baranmod** [comment]
Noticed one more detail. When I stay in server for a pretty long time (half an hour~) without doing anything, I noticed that alot of players became invisible for me. When I turn on player nicknames - I see nicknames moving around, but not the actual players. So I thought it might be related to this issue. Might be wrong though. Those heavy desync issues if staying afk have been happening for a while, just didn't notice that I can see nicknames moving around until now.

**Comment by baranmod** [comment]
another thing (not sure if someone mentioned it already). Somehow, 1 player was invisible for me, yet later I noticed that another player killed him ( and then he became visible for me too. So, some players are able to see those invisible players and some not, and killing them makes them visible again

**Comment by PandahutMiku** [comment]
> another thing (not sure if someone mentioned it already). Somehow, 1 player was invisible for me, yet later I noticed that another player killed him and then he became visible for me too. So, some players are able to see those invisible players and some not, and killing them makes them visible again

Do you still get the issue? It's still reported once every blue moon (like once every 2 weeks) for  us.

**Comment by baranmod** [comment]
yeah, its still happening. The problem is that not every player notice that they can't see some other players so reports are not really common. Yet if you stay online for a while and turn on spectate mode in crowded areas - you can usually see at least one player who is invisible for you. Still not sure what this is related to. Had some thoughts about avi plugins (as I had some strange issues in the past with some of them, like duplicated player spawn on the dead player with avikillingspree plugin once killstreak reached), but having no errors which might help to solve it
