### ISSUE TITLE
Zombie Pushing Vehicle

### ISSUE THREAD

**Issue by FabianWongJingLin** [SmartlyDressedGames/Unturned-3.x-Community#1999]
Dear Nelson,

Could you explain how zombies are pushing vehicles? There seems to be a force that overwhelms the weight of the vehicle pushing it far whenever the zombie made contact with/attack the vehicle. I tried increasing the mass of the vehicle, but nothing seems to work. Perhaps I didn't increase it enough? If I increase it any further, it is harder to get the vehicle to work properly. 

Can you provide me with a viable solution? Thank you!

Best Regards,
SMD

**Comment by warren39** [comment]
Try  a smaller vehicle.

**Comment by FabianWongJingLin** [comment]
Uhm, any other solutions?

**Comment by SDGNelson** [comment]
Unfortunately there is no way to prevent this at the moment because zombies use Unity character controllers, and disabling physics forces caused by them leads to worse problems. The most likely solution would be converting them to use physics driven movement, but there is no ETA for that.
