### ISSUE TITLE
[Minor] Bug with rotating items off the ground, then equipping them

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2000]
Selecting an item off the ground in the inventory gui, rotating it, and dragging it to the equip spot will result in its rotation being saved and looking, well, odd.
![image](https://user-images.githubusercontent.com/17209937/94357393-a0d65f80-0066-11eb-8a22-fbcba07790c1.png)
![rotate](https://user-images.githubusercontent.com/17209937/94357447-f3b01700-0066-11eb-9c03-a9c6e26b47d3.gif)

(This is super minor but probably easily fixable considering you already do this right if its dragged from the inventory after being rotated. It's been around for a super long time too)

**Comment by SDGNelson** [comment]
That is weird... thanks for the report!
