### ISSUE TITLE
Add GUIDs to Items, which persist over moving them

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#2001]
This would be very helpful, but probably low priority. 

Just a GUID for each generated item which persists up until they are deleted from existence

**Comment by SDGNelson** [comment]
This would be great, but messy to resolve unless items are getting some rewrites in general. Item data is replicated and stored differently in different places e.g. crates manually serialize them, so I am hesitant to add more data until that is cleaned up.
