### ISSUE TITLE
Custom Actions hints

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2002]
Actions is a nice option for items, but I'm a bit dissapointed I can use only 4 already made tips, `Craft Rag`, `Craft Bandage`, `Craft Dressing`, `Craft Seed`. I want to write custom hint. How about rework this thing a bit and allow custom hints in localization .dat files? Something like that.

**Comment by SDGNelson** [comment]
This is currently possible if you set Action_#_Text and Action_#_Tooltip rather than Action_#_Key.
