### ISSUE TITLE
The new radio functions

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2003]
How we can add more songs to the radio, because all of those songs are connected via spotify

![image](https://user-images.githubusercontent.com/13141042/94370769-26532180-00f2-11eb-998d-9c3cadc816f3.png)

**Comment by SDGNelson** [comment]
They were recently changed to be easier to setup. Here is the documentation: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/StereoSongAsset.md
