### ISSUE TITLE
Switch Unturned to URP

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#2004]
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.2/manual/universalrp-builtin-feature-comparison.html

Pros:
- [URP is more performance-focused than Built-In](https://blogs.unity3d.com/2019/09/20/how-the-lightweight-render-pipeline-is-evolving/)
- Better transparency 
- Single-pass shading
- Easier Shader creation with Shader Graph for modders
- Better post-processing
- Colour Textures
- Likely more future-proofed, iirc URP is supposed to replace Built-In, and will get more support going forwards

Cons:
- Lighting systems would have to be redone
- Potential issues with modded content due to using materials using incompatible shaders
- Not stable (yet)
- Many vanilla shaders would likely have to be rewritten
- Forward & Deferred rendering get removed (Huge roadblock)
- Depth + Normal maps not supported (Though normal maps on their own are supported)
- Lotta work

**Comment by Trojaner** [comment]
Switching to URP isn't easy and requires a lot of time as it basically breaks all shaders. Would be another workshop nightmare after the 5.5->2017 upgrade. 

Related
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1084
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1177#issuecomment-546986812

**Comment by SDGNelson** [comment]
Unlikely to happen until URP is further stabilized, i.e. 2020 / 2021 LTS. There are still several important features like deferred rendering "in research". It will be a **huge** amount of work.

**Comment by Spebby** [comment]
> I think switching to URP isn't easy and requires a lot of time as it basically breaks all shaders. Would be another workshop nightmare after the 5.5->2017 upgrade.

I've had my own nightmares with upgrading to URP with my own smaller game projects, and yeah, wasn't very fun weekends. Of course Unturned is a way more complex game, so it'd take way more time. Shaders aren't as much of an issue due to potentially being able to Auto detect and switch old shaders out for new ones, though there would likely still be compatibility issues with custom shaders.

**Comment by SDGNelson** [comment]
Sorry, but I do not foresee this being worked on any time soon, so I am closing to reduce the number of active issues.
