### ISSUE TITLE
Players can't connect to server

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2005]
I've been having this issue for a couple months now, where rarely one of my servers will restart, be fully online and functional - commands can be run through console etc. But players aren't able to connect, it immediately says "Server not responded". 

I've fixed this issue in the past by deleting the groups.dat file from the world, but today that fix doesn't seem to be working. 

Has anyone got any suggestions/other fixes?

**Comment by SDGNelson** [comment]
Can you attach the Server_(name).log file from the Logs folder please? There might have been an exception during startup.

**Comment by AdamDN** [comment]
Oops, my mistake. I found the issue while looking through the log and I was able to fix it. 

The issue with groups.dat is a different bug which I don't have a log for at the moment, but I will open a new issue next time it happens.

**Comment by AdamDN** [comment]
Hi there, I experienced this issue again while updating to version 3.20.12.1. 
Restarted the server 2 times - players were unable to connect. 
I deleted groups.dat and the issue was fixed. 
I have attached the server_x.log from before I deleted the .dat
[Server_X.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5358192/Server_X.log)
