### ISSUE TITLE
Safezone volume on devkit

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2008]
Is it possible to place a safezone in devkit? Can't find safezone volume but maybe there is some workaround to achieve it?

**Comment by SDGNelson** [comment]
Sorry, right now they can only be setup with the original editor.

**Comment by baranmod** [comment]
ahh, no problem. Would be nice to have such option in the future though

**Comment by Spebby** [comment]
this has been added, please close!
