### ISSUE TITLE
[Minor]Custom Shell effect not working on Sentry

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2009]
Custom muzzle effect works on sentry but custom shell doesn't work.

![2020-10-01 (7)](https://user-images.githubusercontent.com/57828757/94819659-7a377080-043a-11eb-9c84-7eb0139c8557.png)
On player's hand

![2020-10-01 (9)](https://user-images.githubusercontent.com/57828757/94819706-88858c80-043a-11eb-91b2-faa29bf965ef.png)
On Sentry

**Comment by SDGNelson** [comment]
Thanks, will fix!
