### ISSUE TITLE
Option to force GPS

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#201]
For easier servers, a server option to always open the GPS view of a map would be quite nice, especially how nice the GPS looks compared to the chart.

**Comment by Eatric** [comment]
Can not this be done in Config.json?

**Comment by N1GHTPATROL** [comment]
No, you can enable/disable the chart but if the chart is disabled you see nothing. I believe you always have to manually change to GPS via the selecter (If the server is easy mode)

**Comment by ChubbyQuokka** [comment]
I would love to see this; I'm surprised it's not already a feature.

**Comment by SDGNelson** [comment]
In the next update I've changed this to default to GPS view if Satellite is enabled in the config and the chart isn't available.
