### ISSUE TITLE
Possible effect volume issue when out of bounds

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2010]
I have set audio effect with an effect volume outside of bounds. For some reason that sound is audible all around the map. Same with ambience volume - if I set it outside of bounds it seems to start raining all around the map (even though I disabled rain/snow in devkit for that volume) but not in the actual ambience volume, and sound effect isn't audible.

Was using ambience volume multiple times in the past and it seemed to work ok, but never tried these volumes outside of bounds before, so not sure if its actually an issue with outside bounds or I missed something in configuration.

**Comment by SDGNelson** [comment]
Out of bounds should not matter for those - it is a simple radius test and does not use the bounding grids. Perhaps there is a giant effect/ambiance volume covering the entire map?

**Comment by baranmod** [comment]
Double checked - there wasn't giant volume, but removed the small one and everything went back to normal. Will try to re-do it from start though
