### ISSUE TITLE
Rect Tool for map editor

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2011]
Would it be possible to add rect tool for map editor in this stage of the game? The scale tool alone is not really useful when you need to align object by scaling on one side only -> basically using scale tool for such situations is very time-consuming.
![image](https://user-images.githubusercontent.com/14231707/94979441-599b1380-052b-11eb-9d67-ff77f8c7ce5c.png)

If possible, it would be super useful to have this tool on devkit editor too

**Comment by SDGNelson** [comment]
Would make sense to add if reworking some of the editor tools, especially original editor, but there are no plans to do that soon.

**Comment by SDGNelson** [comment]
Sorry, but I do not foresee this being added any time soon, so I am closing to reduce the number of active issues.
