### ISSUE TITLE
[Unturned 2 Suggestion] Random, scrapable junk items.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2012]
Excuse the editing spam, I accidentally posted without any content, then had to close and re-open.
But the idea is what if there was just junk found in towns and locations? Scrappable junk items like old computers or paint cans or something.
Survival games usually have a lot of this, many RPGs having it too, though usually just for set dressing. A great example is Fallout 4, wherein the character can go about the map collecting useless junk items for to scrap into useful components for building and gun modification. Elver also got me thinking about this. In Elver the player goes about the whole map looking for items to progress further in the game itself, crafting together important resources instead of running headfirst into an important, high-end location to progress.
I think it would be neat for there to be such junk, with two versions perhaps of them, one static being put in the editor, like the tank assets, and one usable item node, like the tank, but an item node rather than a vehicle node. Perhaps you set up a spawn table for "Civilian junk" and it could be percentages of assorted things you'd find in a home, books, cans, alarm clocks, and other knick-knacks. 
An alarm clock could be scrapped into metal, plastic, and perhaps low-grade circuitry, which could then be used to make a low-grade makeshift red dot sight, used until a better version is found or made with higher-grade junk items.

I think it would also be pretty great for building, as you could pick up a bunch of old furniture and put it in your base for purely aesthetic reasons. Someone could get a bunch of unmarked cans from eating beans or drinking soda and put them up for targets.

I would think that the assorted junk items would also be great for NPC quests, maybe a civilian asks for a lightbulb or a new pilot light for his oven. A Coalition commander asking for more high-grade circuitry, then telling the player where it may be.

It would also be another reason to use the crafting system, as maybe some high-grade junk items having better crafting recipes than that of regular lootable weaponry, to reinforce the survival aspect of Unturned.

Perhaps the items could even be used as trophies, with someone keeping the first toilet plunger, or an NPC giving a quest where they'll give you a microwave for giving them a pie. Maybe they could even have high value to NPC vendors, with some being highly contested commodities to sell to NPCs, or even bragging rights on multiplayer servers.

But, I'm certainly no game-designer and the whole junk idea may just be asset and ID spam, or could be overlooked for faster and more instant action. Thanks for reading.

**Comment by Trojaner** [comment]
Please use the smartlydressedgames forum for Unturned II related suggestions, this is not the place for it.
