### ISSUE TITLE
How do I restart "permissions" on an enabled server?

### ISSUE THREAD

**Issue by vanya890** [SmartlyDressedGames/Unturned-3.x-Community#2016]
I need to restart Permissions without restarting the entire server. How can this be done?

**Comment by TH3AL3X** [comment]
/p reload
p reload

**Comment by rube200** [comment]
why people keep open issues on unturned, if it is a rocketmod issue

**Comment by TH3AL3X** [comment]
> why people keep open issues on unturned, if it is a rocketmod issue

Supposedly Nelson now updates rocketmod or i'm confused?

**Comment by rube200** [comment]
> > why people keep open issues on unturned, if it is a rocketmod issue
> 
> Supposedly Nelson now updates rocketmod or i'm confused?

That is true but they are still different projects
