### ISSUE TITLE
Unturned FreeCam hand/ Bug

### ISSUE THREAD

**Issue by petrosuyn** [SmartlyDressedGames/Unturned-3.x-Community#2017]
Pressing F6 from 1st person then pressing F1-F4 will cause this bug (Look at the FPS/Ping HUD) Check the video
[bugreport.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5341371/bugreport.zip)

**Comment by SDGNelson** [comment]
Not a big deal, but will prevent build mode in first person for the update.
