### ISSUE TITLE
How do I go about turning off the underground killzone?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2018]
In sewers under a city in my map players are reporting instant-dying, despite no cracks or holes being in the sewer system itself, as ctrl + b then ctrl + n was used to snap together a perfect line.
So, how would I go about turning that instakill off?

**Comment by TH3AL3X** [comment]
If I remember correctly, in the map of Washington, in Scorpion the same thing happens when you go under the map, you could use the old trick of the .unlocker file and see what you have with the devkit

**Comment by SDGNelson** [comment]
Some objects like the bunkers and Russia metro have kill zones built-in, as opposed to placed in the level editor. If your sewers are intersecting one of the those built-in kill zones there is unfortunately no way to disable them at the moment.

**Comment by INeedHelp225** [comment]
Hmm. That's interesting, guess then people will need to be cautious underground.
