### ISSUE TITLE
Modded: Vehicle carjacking and and refueling, carjacks and gas can cannot interact with vehicle.

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2019]
Hmm neither can punches get to the vehicle's box collider.
I am very new to all these, still exploring as I go. I read through topics via search "vehicle" "vehicle carjack" "carjack" "gas can" "collision", can't seemed to find a similar one hence this new post.

For making vehicle, there are box colliders plating all over the vehicle already so player can stand on the vehicle or go within it just fine. The nav covers the whole vehicle as well. Tried in singleplayer but the vehicle cannot interact with gas cans nor carjacks, I can still headbump the vehicle with my character's head to "carjack" it though.

Anyone have any clue what should be changed/added in order to make the vehicle be like how vanilla ones are?

**Comment by TH3AL3X** [comment]
Silly question, what version of Unity are you using

**Comment by Ongjming** [comment]
Oh I am using Unity 2018, I saw the 2019, used it but couldn't get another mod thingy to work so switched back to 2018.
Yea I am probably doing something wrong but I don't really know if it is the nav being too big/small or I should replace the box colliders, or change some other setting that I have no clue about which can enable interaction with carjack/fuel can.

**Comment by Ongjming** [comment]
Hmm currently tried making barricades/structures, but can't seem to get the collision to work either. They behave like the vehicle I was fiddling with earlier. Is there something missing that I need to import within unity for unturned for collisions to work?

**Comment by educatalan02** [comment]
You must use 2018.4 LTS version.
Also remember you need to set all Layers & Tags correctly

**Comment by Ongjming** [comment]
> 
> 
> You must use 2018.4.X LTS version.
> Also remember you need to set all Layers & Tags correctly

I am using unity 2018 version as stated above. Layers and tags are set correctly too but not really sure if they are what I should be seeing. Would be good to have a positive example screenshot.

**Comment by educatalan02** [comment]
The examples are set already with the Tags & Layers (You need to import first the Project.Unitypackage, and then Examples)

**Comment by Ongjming** [comment]
> 
> 
> The examples are set already with the Tags & Layers (You need to import first the Project.Unitypackage, and then Examples)

To ellaborate, yes I did those and followed those examples and still couldn't get the mod item to work properly.

**Comment by Ongjming** [comment]
Maybe related observation:
Tried to make a blank wall object and item.
Added physics material (Item: Barricade and Clip; Object: Object, Clip, Clip's Block, Object's Block)
The item and object does end up blocking movement and all, can be salvaged etc., but when I tried punching them it doesn't give off the physic material sound and particle effect.
Hmm probably should bundle them all together in some file structure or something, idk....
