### ISSUE TITLE
Bug report: Reload & hammer sounds staying in place instead of the player

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2020]
I have discovered an issue wherein the sounds occurred from reloading & hammering the weapon stay in one position & not with the player. It is really noticeable when doing so while moving.

**Comment by SDGNelson** [comment]
Sorry about the bug. This is already fixed on the preview branch, and will be included in tomorrow's update.

**Comment by OneManOperative** [comment]
That's quite fast, I also discovered that the equip sound suffers the same issue. Is that included?

**Comment by SDGNelson** [comment]
(it was reported and fixed last week)
It was fixed for all sounds.
