### ISSUE TITLE
Physical Bug on Unity 2019 version.

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#2021]
When I change the mass of the wheel collider in the Unity or redefine it through the config, the camera of the character in the car starts to twitch. It seems to me that this is due to incorrect processing of physics and the wheel of the car is partially stuck in the ground collider. Interestingly, vanilla vehicles where the mass of the wheel collider is more than 1 kg behave normally. (Possibly because their assets remained in the previous version.)

**Comment by SDGNelson** [comment]
Does the same thing happen when you use that config in the 2018 version? The vanilla asset bundles were already updated to Unity 2019, so there would be no difference between them and yours.

**Comment by Alex-Well** [comment]
Then what could be the reason?

**Comment by SDGNelson** [comment]
You could compare to the vehicles in the ExampleAssets package to see the Unity differences, but otherwise the only difference would be whatever settings are overridden in your vehicle physics profile.
