### ISSUE TITLE
Players can't connect after update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2023]
Reverted to old steam networking, it seems players can connect without problems rightnow.

 Basically, 11 players connected on one server, and 12 connected on another. And other players couldnt connect (timed out). Those players who connected first were able to play just fine

found this on player logs:

``2020-10-09 13:41:23] Successfully refreshed the master server.
[2020-10-09 13:41:26] Initializing ClientTransport_SteamNetworking
[2020-10-09 13:41:56] Server did not reply to workshop details request
[2020-10-09 13:41:56] Returning to main menu
[2020-10-09 13:41:56] Disconnected
[2020-10-09 13:41:57] Applying graphics settings
[2020-10-09 13:41:57] Applied graphics settings
[2020-10-09 13:41:57] Featured Workshop 2136497468 [7/16/2020 5:00:00 PM, 7/31/2020 5:00:00 PM]
[2020-10-09 13:41:57] Singleplayer map selection empty
[2020-10-09 13:41:57] This server lost your connection

**Comment by Projoker** [comment]
Same...

**Comment by Gsechs** [comment]
I third this

**Comment by PandahutMiku** [comment]
Haven't had any complaints yet, are you using login tokens?

**Comment by baranmod** [comment]
yeah

**Comment by SDGNelson** [comment]
From the log you included it looks like the client was unable to connect with the old transport layer "Initializing ClientTransport_SteamNetworking"

Is there anything in the logs on the client or server when using the new Steam Networking?

**Comment by baranmod** [comment]
will check once I get home, pretty limited options while on the road

**Comment by Bradler26** [comment]
I've had reports with this error. I don't know if it's related or if there is a fix I'm meant to do but someone  just sent me this screenshot
![image](https://user-images.githubusercontent.com/47075751/95623947-61504000-0a76-11eb-8e00-bfd87d197702.png)

**Comment by SDGNelson** [comment]
Which server is that @Bradler26? I will connect and see what gets logged.

**Comment by Bradler26** [comment]
its my server - 89.34.97.144:27015

Ive just connected to it now and didn't have any problem joining. It could just be that one person having and issue and he has gone AFK now so I can't get any more info. It also may be something that has been changed in my config as I haven't been working on my server files for a while so someone else could have changed something. Here is my clientlog if it helps at all and if not you can try to join but I have only had 1 report so it could be a false alarm. 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5357226/Client.log)

**Comment by SDGNelson** [comment]
One issue that has become apparent: tags are used to specify which transport implementation the server is using, so if your plugins call `SteamGameServer.SetGameTags` they may be clobbering the tags.

**Comment by SDGNelson** [comment]
Thanks @Bradler26, I was able to connect as well, but I will keep investigating

**Comment by SDGNelson** [comment]
Following up on my earlier comment: my guess is that the servers experiencing issues are using a plugin that calls SetGameTags in order to hide information from the server list. If you disable that plugin for the meantime it should work properly.

I have confirmed this in a few cases where up-to-date servers have tags that are clearly overridden and based on formats from previous versions of the game.

For a patch later today I will put together a workaround so that there is no mismatch in the default case.

**Comment by Bradler26** [comment]
I managed to get the client log of a failed connection. Hope it can help out although I don't think it really gives enough info to find the cause from what I can see. 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5357379/Client.log)

**Comment by baranmod** [comment]
double checked, and that log I dropped initially, was right after update before I reverted server to old steam networking. So if I understood correctly, its something related to the plugins like avilobbymess, which in this case I use to overwrite server plugins list, right? Question is, should I disable it completely or it might be compatible with new networking on this upcoming patch?

**Comment by SDGNelson** [comment]
@Bradler26 from the logs it looks like they should have the appropriate certificates, but it is failing anyway. I have posted a question to the GameNetworkingSockets repo asking about this error.

@baranmod That might be the cause yes, but ideally anything calling `SetGameTags` should not do so because it may cause other issues in the future.

**Comment by SDGNelson** [comment]
The 3.20.12.1 patch has been released and should fix the mismatch when tags are different, and hopefully fix the certificate issue. There are a few other misc fixes, and logging for the tag problems.

**Comment by Gsechs** [comment]
> The 3.20.12.1 patch has been released and should fix the mismatch when tags are different, and hopefully fix the certificate issue. There are a few other misc fixes, and logging for the tag problems.

Appears to have fixed my issue. Thanks Nelson, 

-Dolph

**Comment by SDGNelson** [comment]
Following up on the client "unable to trust host encryption certificate" issue:

There was a regression in the version of OpenSSL used by Steam. Unfortunately this older version of OpenSSL has a bug with certain laptop chipsets. Valve are going to fix this regression ASAP, probably early next week as part of the usual Tuesday maintenance.

As a temporary workaround it may be worth trying this Unturned launch option:

1. Right-click Unturned in your Steam Library
2. Select Properties then "Set Launch Options..."
3. Type "-SNS_AllowWithoutAuth" without quotes
4. Click Ok and launch the game

SNS here stands for "Steam Networking Sockets". This option *might* allow you to connect without certificate validation until the proper fix.

Alternatively if you host your own server you can also set the "-NetTransport=SteamNetworking" command-line option to use the old Steam networking until the fix.

**Comment by baranmod** [comment]
It seems like now more players can connect, yet once it reached 23 players - others can't join again. Will update shortly. Disabled lobby-interacting plugin btw

**Comment by SDGNelson** [comment]
@baranmod If you have a plugin adjusting maxPlayers it might be worth temporarily disabling that. When accepting a connection the server checks `hasRoomForNewConnection` (which uses maxPlayers and queue size), and if not it closes the connection. There may also be some info in the server log e.g. `Server failed to close connecting connection`

**Comment by baranmod** [comment]
hmm, did indeed find some rows with `Server failed to close connecting connection` so it might be an issue. Guess I will have to stay with old networking for now

**Comment by SDGNelson** [comment]
@baranmod Steam's documentation says the client may get a timeout error if the server is slow to accept them, for example if there is a long blocking operation. There might be some mention in your log of a slow operation prior to the failure e.g. plugin connecting to a database on the main thread. For the next update the game will log if the server takes more than one second between calls to Steam run callbacks.

Is anyone else having players report issues of "lost connection" during connect like that?

**Comment by MarshiMello** [comment]
> Following up on the client "unable to trust host encryption certificate" issue:
> 
> There was a regression in the version of OpenSSL used by Steam. Unfortunately this older version of OpenSSL has a bug with certain laptop chipsets. Valve are going to fix this regression ASAP, probably early next week as part of the usual Tuesday maintenance.
> 
> As a temporary workaround it may be worth trying this Unturned launch option:
> 
> 1. Right-click Unturned in your Steam Library
> 2. Select Properties then "Set Launch Options..."
> 3. Type "-SNS_AllowWithoutAuth" without quotes
> 4. Click Ok and launch the game
> 
> SNS here stands for "Steam Networking Sockets". This option _might_ allow you to connect without certificate validation until the proper fix.
> 
> Alternatively if you host your own server you can also set the "-NetTransport=SteamNetworking" command-line option to use the old Steam networking until the fix.

Hello,

This fix that _might_ work has not worked for me, I still get Unable to Trust Host Encryption Certificate.
Log:

Client bypassing test for Steam Network availability
Client connecting to (IP address of server)
Client connection problem detected locally (4003) "Bad cert: CA key 18220590129359924542 is not known to us"
Client transport failure: Unable to trust host encryption certificate.

(Copied from phone)

**Comment by SDGNelson** [comment]
@MarshiMello Alright, sorry not to have a workaround for the meantime. I will remove the suggestion from the posts.

**Comment by MarshiMello** [comment]
> @MarshiMello Alright, sorry not to have a workaround for the meantime. I will remove the suggestion from the posts.

@SDGNelson it's no worries mate, 
As stated I'm down to try any other potential ideas you may have, deleting or changing files or whatnot. Just shoot a reply and I'll send results

**Comment by MarshiMello** [comment]
@SDGNelson 

Attached is a simple workaround in a bat file (zipped up) for the "unable to trust host encryption certificate" issue. Unzip and place in unturned main directory (If unturned is installed to default location, otherwise edit bat file and point it to the unturned folder) and run it.

Code inside bat:
cd C:\Program Files (x86)\Steam\steamapps\common\Unturned
set OPENSSL_ia32cap=:~0x20000000
unturned_BE.exe


[Start-Unturned.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5358381/Start-Unturned.zip)

**Comment by MarshiMello** [comment]
> 
> 
> @SDGNelson
> 
> Attached is a simple workaround in a bat file (zipped up) for the "unable to trust host encryption certificate" issue. Unzip and place in unturned main directory (If unturned is installed to default location, otherwise edit bat file and point it to the unturned folder) and run it.
> 
> Code inside bat:
> cd C:\Program Files (x86)\Steam\steamapps\common\Unturned
> set OPENSSL_ia32cap=:~0x20000000
> unturned_BE.exe
> 
> [Start-Unturned.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5358381/Start-Unturned.zip)

Logs before and after fix, just as evidence.

[Client After Fix.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5358394/Client.After.Fix.log)
[Client Before Fix.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5358395/Client.Before.Fix.log)

**Comment by baranmod** [comment]
> @baranmod Steam's documentation says the client may get a timeout error if the server is slow to accept them, for example if there is a long blocking operation. There might be some mention in your log of a slow operation prior to the failure e.g. plugin connecting to a database on the main thread. For the next update the game will log if the server takes more than one second between calls to Steam run callbacks.
> 
> Is anyone else having players report issues of "lost connection" during connect like that?

But wouldn't it eventually let player to connect? I mean, currently, server doesn't let to connect only for some specific players and they couldn't connect whatever they do while others connecting without a single timeout

**Comment by TH3AL3X** [comment]
> > @baranmod Steam's documentation says the client may get a timeout error if the server is slow to accept them, for example if there is a long blocking operation. There might be some mention in your log of a slow operation prior to the failure e.g. plugin connecting to a database on the main thread. For the next update the game will log if the server takes more than one second between calls to Steam run callbacks.
> > Is anyone else having players report issues of "lost connection" during connect like that?
> 
> But wouldn't it eventually let player to connect? I mean, currently, server doesn't let to connect only for some specific players and they couldn't connect whatever they do while others connecting without a single timeout

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2025

**Comment by baranmod** [comment]
dont think its anyhow related to groups.dat corruption thing. there are no errors leading to that and if I recall correctly - non of the players would be able to connect if one of the level data files gets corrupted

**Comment by SDGNelson** [comment]
@MarshiMello 

Good find, in case you are interested the full description is here https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html, but based on trying to get players to use workarounds involving scripts in the past I decided it would be calmer to wait the couple days. Maybe a bad decision.

@baranmod 

> But wouldn't it eventually let player to connect? I mean, currently, server doesn't let to connect only for some specific players and they couldn't connect whatever they do while others connecting without a single timeout

In your earlier comment you were saying it happened to all players once the server was full, but from this comment it sounds like you are saying it only happens to a few specific players. What is happening now, and do you still have the new networking enabled?

> #2025

This is definitely a separate issue, unrelated.

**Comment by baranmod** [comment]
I meant, reports were coming from same players (for roughly 30min~ after update). While other players connected without a single issue, those others - couldn't connect in any way (some of them tried 5+ times and at least couple even did files validation - didn't help either.

Servers currently launched under old networking, but I might jump on new one to gather some more details.

**Comment by MarshiMello** [comment]
> @MarshiMello
> 
> Good find, in case you are interested the full description is here https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html, but based on trying to get players to use workarounds involving scripts in the past I decided it would be calmer to wait the couple days. Maybe a bad decision.
> 
> @baranmod
> 
> > But wouldn't it eventually let player to connect? I mean, currently, server doesn't let to connect only for some specific players and they couldn't connect whatever they do while others connecting without a single timeout
> 
> In your earlier comment you were saying it happened to all players once the server was full, but from this comment it sounds like you are saying it only happens to a few specific players. What is happening now, and do you still have the new networking enabled?
> 
> > #2025
> 
> This is definitely a separate issue, unrelated.

Me personally I built it as an exe file, renamed unturned_br to unturned_br_vanilla and the script as unturned_br, pointed it to the proper client and Walla. Runs from steam with all its features. For other players im sure they can wait but for me I'm inpatient aha

**Comment by joeymisfit** [comment]
Do we still use the **-NetTransport=SteamNetworking** startup arg, or would it cause issues as you backdated the update?

**Comment by SDGNelson** [comment]
@joeymisfit That argument is the current default so you do not need to include it, but there is no harm in including it. Once the Steam OpenSSL regression is released from the Steam client beta the new networking will become default again.
