### ISSUE TITLE
Groups.dat preventing players from connecting

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2025]
The issue with groups.dat is a different bug which I don't have a log for at the moment, but I will open a new issue next time it happens.
_Originally posted by @AdamDN in https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2005#issuecomment-700210698_

Hi there, I experienced this issue again while updating to version 3.20.12.1.
Restarted the server 2 times - players were unable to connect.
I deleted groups.dat and the issue was fixed.
I have attached the server_(name).log from before I deleted the .dat
[Server_X.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5358203/Server_X.log)

**Comment by SDGNelson** [comment]
Thanks for the report. Do you still have the Groups.dat file in your recycle bin? If so, I could load it up to replicate the bug.

**Comment by Johnanater** [comment]
This happens when the Groups.dat gets corrupted. I've had it happen when the server hangs during shutdown. Restoring from a backup/deleting it fixes the issue.

**Comment by SDGNelson** [comment]
My guess is that there is a casting exception when saving, but without the saving log we cannot be sure. Anyway in the next update it should be able to read the corrupted Groups.dat file, and that cast exception should not happen.
