### ISSUE TITLE
I get an error when i start my .Bat File

### ISSUE THREAD

**Issue by Speedyriley** [SmartlyDressedGames/Unturned-3.x-Community#2026]
Here are The code and the error.

![Screenshot (76)](https://user-images.githubusercontent.com/56953807/95649469-68f30180-0ad5-11eb-865d-4401361fe2b9.png)
![Screenshot (78)](https://user-images.githubusercontent.com/56953807/95649473-6d1f1f00-0ad5-11eb-9314-a60e5a8eaf85.png)

**Comment by TH3AL3X** [comment]
yo, read errors xd
