### ISSUE TITLE
Missing Server Configuration Translations

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2028]
This is relatively minor, but the Dying Light Red/Blue Volatile Spawn Chance, as well as the Elver Boss Stomper Spawn Chance Config.json options do not have any translations in the Server View Screen
![image](https://user-images.githubusercontent.com/17209937/95676968-4e319300-0b90-11eb-9b67-b8a13b0207d7.png)
I've had a few people ask me what they were, and I had no idea myself until I connected the dots that DL = Dying Light.
Figure you're pushing a patch (hopefully) early next week to fix the openssl issues, might as well report this now as well.

Thanks for your time

**Comment by SDGNelson** [comment]
Whoops! Recently I made a change that config entries without a translation entry would prettify the field name, but the server info screen was missing that. In this case it would probably make sense to have a display name anyway because "DL Red Volatile Chance" is not particularly helpful.
