### ISSUE TITLE
Why are some servers constantly pinged 0?

### ISSUE THREAD

**Issue by vanya890** [SmartlyDressedGames/Unturned-3.x-Community#2029]
Some servers are listed with ping 0. In contrast to other server.

I am sure that this is not the Internet, because even in the local network there is a delay. Also, their ping does not jump at all.
![image](https://user-images.githubusercontent.com/19227465/95761397-ee80d800-0cb4-11eb-8299-49e92ce36911.png)

**Comment by SDGNelson** [comment]
Unturned simply displays the value of `gameserveritem_t.m_nPing` there, so it is probably a bug in the Steam API.

**Comment by vanya890** [comment]
> Unturned simply displays the value of `gameserveritem_t.m_nPing` there, so it is probably a bug in the Steam API.
Each of these servers has a FixConsole plugin from One-Host hosting. I wrote to them and asked why they have it fixed, but they say "we can't tell you about it".
