### ISSUE TITLE
Increase Life Unturned 3.0 

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#203]
**Good afternoon. Thank you for reading this post!**
The recent time according to the polls of the CIS countries, many people stopped playing our favorite game "Unturned". But the problem is not even that ...
Very well helps the game live, you need to improve the life of developers. (Thanks for the UI interface!)
**My opinion:** Adding maps "Curator" very few people are interested. Therefore, you need to improve the life of a regular developer (servers, plug-ins, mods, maps).
Yes, I would like to see the ability to code in the game! =)
**What I want to convey to the developer:** Everything I say is really important. I understand that you are busy with Unturned 4.0, but the players who play in 3.0 they are watching you, so they will go to 4.0, but if the players stop playing in 3.0, most of them just go to other games, you need a little of your effort, further all the guys will do.)
**I suggest:**
  **Most importantly**: Each developer of servers and mods tries to hide their mods so that they are not stolen by another server, and really good work is done in the studio and they are not seen by the main audience. (Which is very sad.) (Private fashion, protection against theft.)

**1. "Modules"** I worked with them, they could be used to expand the editors. (I tried but ran into the loading problem,
all that I changed via "Module" is not saved, yes I can write to files, but there will not be a load without a module.)
**2. "Simple animation editor"** Recording animation objects directly in the editor would be really cool. (Moving, rotating)
**3. The Devkit.** As I understand you liked the chips in Unreal Enigen 4 and you made Devkit. Devkit is an excellent vesh, but not everyone knows how to use it, it would be cool if we were able to expand its capabilities.
**4. "Unity"** Often, the objects in the unit do not look like they are in the game. (It's clear that the game has many factors in it.) I suggest previewing the object as it will look in the game.
Similarly, with a weapon to make a really high-quality weapon, it is very often necessary to reload files, which is sad.
It would be cool to do in the unit hone the weapon, a preview of how it will behave in the game. (The same thing about other content).
**5. "Editors"**
Simplify the development of the NPC, now the NPCs are all avoiding (Especially the quests).
It would be cool if the Bundle Tool created a config with the settings specified in its window. (I wrote a script for this kind of work, for myself.)
**Conclusion:**
You can translate a lot of ideas. (color chat; D)
 I assure you 3.0 will live if you now apply effort.
Sorry for my English!
**Thank you for attention! Good luck in developing the game.**

**Comment by Eatric** [comment]
I agree with comrade. And give life for Community Module(credit Trojaner25). It would be great if you made more opportunities for modifying the game for example allowed to change stamina because (askRest doesnt work) it would also be great if we could blind the player.

**Comment by SDGNelson** [comment]
At the moment stamina is deterministic (i.e. client and server both spend and restore it on the same ticks, using an item which recovers stamina grants it on the same ticks) so it doesn't support RPCs.

Blinding wise do you mean the blindfold item, or flashbangs?

**Comment by SDGNelson** [comment]
Coding-wise I've tried to open this up a little with the CommunityModule. Unfortunately Unturned 3 isn't designed for 3rd party extension, but I'm making sure to leave everything very open in 4 both to blueprints, and to c++ similar to how Unreal Tournament source code is available.

This late into development I think it's a better time investment to build great tools from the beginning for 4 than to retrofit new tools into 3, but I definitely agree that the .dat files and whatnot in 3 aren't desirable.

**Comment by N1GHTPATROL** [comment]
I agree with Nelson, which is to make sure 4.0 has these features instead of spending the time fixing 3.0 to have them. But Nelson, since you are using 4.0 as an excuse for many of 3.x's problems (which is fine) do you have a date for when we can expect the first public build of 4.0?

**Comment by Eatric** [comment]
@SDGNelson, flashbangs
