### ISSUE TITLE
Custom effect problem (Most likely caused by Rocket.cs script)

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2030]
So I decided to make an airstrike mod, or to be more correct, a V-1 rocket call-in mod. I made a binoculars item, which is a gun with explosive ammo. Effect, attached to this explosive ammo contains the rocket itself with animation and Rocket.cs script. It all works fine, except for one thing: almost half of the times I call in rocket, rocket just wont spawn. And the problem isn't about effect itself, because when I attached a separate particle system to it, it would always spawn normally. All the tags and layers are set to the Trap. just like the projectile in Rocket Launcher example folder (Also when the tags and layers weren't set to trap, the rocket script didn't work on impact with ground, so this is another reason why I set up tags and layers this way). So the problem is exactly about rocket prefab, and, most likely, Rocket.cs script attached to it. What's also weird, is that reloading the effect asset usually allows you to call in rockets once again for a certain amount of times, until it breakes again. Im very confused, but I assume that this entire problem is somehow caused by the way game interacts with Rocket.cs script. I really need to find the solution for this problem, because the mod is done, but this glitch makes it useless.

Here is the video showing this glitch:
https://www.youtube.com/watch?v=jGQl7FrnPvA&feature=youtu.be

And here are the screenshots of effect in unity:
![изображение](https://user-images.githubusercontent.com/59206749/95778607-26961400-0cd1-11eb-958f-6054488c9da5.png)
![изображение](https://user-images.githubusercontent.com/59206749/95778655-3e6d9800-0cd1-11eb-98b3-12029608bbf8.png)
![изображение](https://user-images.githubusercontent.com/59206749/95778672-44fc0f80-0cd1-11eb-91d9-99ddc6f7314b.png)
(Ignore the Trail prefab, it's just a particle system)

**Comment by SDGNelson** [comment]
The most likely reason that it works again after reloading the asset is effects are recycled rather than repeatedly instantiating/destroying them. I'm not familiar with the "Animator" component, so it might be worth trying with the "Animation" component which has an option to PlayOnAwake.
