### ISSUE TITLE
Why is there a large ping in the list of servers?

### ISSUE THREAD

**Issue by vanya890** [SmartlyDressedGames/Unturned-3.x-Community#2035]
When checking my ping via cmd, or sites for checks, my ping is in the region of 1.
![image](https://user-images.githubusercontent.com/19227465/95854434-a10d7500-0d5f-11eb-882e-c85179ddbb51.png)
![image](https://user-images.githubusercontent.com/19227465/95854547-c8644200-0d5f-11eb-885d-308573a1f5c9.png)

Why does the ping go above 30 in the list of servers? It also fluctuates a lot
![image](https://user-images.githubusercontent.com/19227465/95854924-4cb6c500-0d60-11eb-9328-9946793af300.png)

And in the game itself, the ping is stable at less than 20.
![image](https://user-images.githubusercontent.com/19227465/95854842-327ce700-0d60-11eb-8a63-8c8d49eecf3f.png)

How to deal with this so that it shows stable ping in the list of servers?
What ping is shown in the list? From me to the server? Or from Steam to the server?

**Comment by SDGNelson** [comment]
Ping command sends an ICMP echo request, whereas the in-game ping includes game processing time. The server list ping is handled by Steam and I think shows the ping from your PC to the server, but may include Steam internal processing time.
