### ISSUE TITLE
[ERROR] Server Starting Error

### ISSUE THREAD

**Issue by nazmiyigitefe** [SmartlyDressedGames/Unturned-3.x-Community#2036]
![error](https://user-images.githubusercontent.com/71214979/96025209-7dc8ef80-0e5d-11eb-88c0-4d5ca39acdcc.png)
We Are Thaking That Error When We Want To Start The Server.

**Comment by rube200** [comment]
please stop having 3iq and read what is written on picture/console

**Comment by TH3AL3X** [comment]
If you want to do a server use this...
**GameAPP**: 1110390
https://store.steampowered.com/app/1110390/Unturned__Dedicated_Server/
