### ISSUE TITLE
Small visual bug for character slots

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2040]
Occurs after leaving/losing connection to a server. Seems to be repeatable. 
https://imgur.com/9Lc8bzp

**Comment by AdamDN** [comment]
Actually I've just tested it a bit more, it looks like it's constantly like this - even immediately after launching the game.

**Comment by TH3AL3X** [comment]
Only in that server?

**Comment by TH3AL3X** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2041

**Comment by AdamDN** [comment]
> #2041 Duplicated

This is 2 different bugs. The game launching in the wrong resolution issue has existed forever, the character slots issue is new to recent updates. 

> I mean, can you resize ur resolution? or try removing ur config of Unturned here, "C:\Program Files (x86)\Steam\userdata" search this folder there "304930" and remove it, that is gonna reset ur settings, make a backup before you delete it

Tried this, resetting settings didn't fix either of the issues.

**Comment by SDGNelson** [comment]
Unfortunately snuck in when fixing some menu issues, but will fix for the next update.
