### ISSUE TITLE
Resolution on 4k Monitors

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2041]
Launching the game on a 4k monitor sets the display to 1920x2160 instead of 3840x2160: 
![image](https://user-images.githubusercontent.com/71527679/96187292-aa036f80-0f34-11eb-8c38-e62ccb45edd0.png)
I have to go to Config>Display and set the correct resolution every time I launch the game.

**Comment by SDGNelson** [comment]
To force Unity to use a specific resolution your best option would be to set the `-screen-width 3840` and `-screen-height 2160` command-line options.
