### ISSUE TITLE
A universal tool or how to free Nelson from a large number of requests.

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#2042]
Hi, I had an idea for a long time to create a universal modding tool that would help solve most of the problems for modders. Unity Events is an amazing thing that expands the possibilities, however it is very limited in functionality and we have to constantly request new Unity Events. Why not just make a one-size-fits-all tool that saves you future inquiries?
I suggest adding something to the game like this: https://assetstore.unity.com/packages/tools/integration/event-delegate-system-68785#releases
My coder and I wanted to rewrite this and add a script that would also allow you to override the target for which the method will be called. For example, what would he find a game object by Name, Tag, distance, and then call the selected method for him in advance. You could, for example, get a player and call a method that would add and then play a custom animation clip. Or, use a weapon to get a car and call a method that would replace the model for it.
However, it's best if you look at it yourself and do it in the best way possible. But if you don't have time, let me know, we will be ready to get to work ourselves!

**Comment by ZoliWorks** [comment]
As someone who's work wouldn't even be possible without scripts and events, I fully support this idea. This would be a great addition to expand upon what we currently have.

**Comment by GazziFX** [comment]
Yeah, great idea! I think we also need to implement a component for calling an event by index from the server.

**Comment by Gekk-Here** [comment]
Nice idea

**Comment by SDGNelson** [comment]
Unfortunately the events will always be limited compared to running custom code, but another big factor is which aspects of the game are intended to be used this way. Aside from the upcoming netcode improvements (e.g. allow any object to address another) something generic like this is unlikely to be added. Best to open individual issues for features that would benefit from event hooks and/or reuseable components.
