### ISSUE TITLE
Servers are spoofing user list

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2045]
This happened in 2018, but it was patched, it is back again ...

Old plugin https://github.com/IcePlugins/ExtraPlayerSpoofer

[![](http://img.youtube.com/vi/PsDCqYkamsE/0.jpg)](http://www.youtube.com/watch?v=PsDCqYkamsE"")

**Comment by SDGNelson** [comment]
Thanks for the report. Historically RocketMod set the bot player count to one, but in the most recent update that was finally changed to zero, so plugins must have started setting it to higher values. For the next update the game will subtract bot players from the player count.
