### ISSUE TITLE
Servers Crashing

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#2047]
Recently all my servers seem to crash with the same stack trace. I'm currently running the default steam networking and this happens. Originally it seemed to only happen every time a specific player joined. After banning them things seemed to be fine for a while but now its reappeared again. It could be a player joining but it doesn't seem as constant as before. I've attached the latest 2 error.logs

[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5411373/error.log)
[message (11).txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5411380/message.11.txt)

**Comment by SDGNelson** [comment]
Unfortunately there is not much to go on here except that it crashed in steamclient64.dll. Can you check if there are any .dmp files in `%USERPROFILE%\AppData\LocalLow\Smartly Dressed Games\Unturned` please?

**Comment by Bradler26** [comment]
I don't have any folders relating to SDG or unturned in my Locallow folder. The only place seems to be in the Local Folder which is where I got the error.logs. For some reason, the LAST crash on my RP server doesn't have any .dmp files but the other crash that I believe was my arena server does. Here it is [crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5414177/crash.zip)

**Comment by SDGNelson** [comment]
Hmm it looks like a couple one-off crashes from August 23rd in Unity internals. The original crash you posted mentioned a crash report in `%TEMP%/2/Smartly Dressed Games/Unturned` which I figured would get moved to the usual location, but maybe the crash info stills exists there?

**Comment by Bradler26** [comment]
Sorry for the late reply.

That file path you posted I believe is where I've been getting all the files I originally sent from. The only place I seem to find any crash logs in is 

``C:\Users\Administrator\AppData\Local\Temp\2\Smartly Dressed Games\Unturned\Crashes``

Nothing mentioning SDG or Unturned in LocalLow or any other folders from what I can see.

**Comment by SDGNelson** [comment]
And there are no .dmp files in the Crashes folder? Without those we do not know which code path is causing the crash unfortunately.

The manual way to track down what is causing the crash would be to see if it can happen in vanilla, or if a specific plugin is causing the issue. How frequently is it crashing? If possible I would recommend disabling one or a few plugins at a time and seeing what happens.

**Comment by Bradler26** [comment]
There are dmps found in the crash folders. For some reason, all 3 servers were crashing originally but only my Arena server made any crash logs. At first, we thought it was the person who when he joined the server crashed so after banning him it seemed to stop quite a bit. Then recently my RP crashed and made a crash log but with no dmp. The crashing isn't very common at all and it hasn't happened since I reported the issue. I was just told to open a github issue by devs as they thought it could be related to the steam networking changes. I will make sure to send any extra info I get but it could quite possibly be a plugin causing the crash as I was trying some new ones. The issue can be closed if your happy that it's not related to the recent updates.

**Comment by SDGNelson** [comment]
Glad that it hasn't crashed again. I will close for now, but if the same crash happens again with a .dmp file, or you notice it is an issue in the base game, feel free to re-open.
