### ISSUE TITLE
Server crashing every hour or so

### ISSUE THREAD

**Issue by diamondpumpkin** [SmartlyDressedGames/Unturned-3.x-Community#205]
I recently updated to Ubuntu 16.04.2 due to my previous version (15.04) failing to install updates because it's no longer supported. I am now having issues with Unturned, logs are showing nothing helping (I'll post them anyways). Every 40-60 minutes my servers will go down for no apparent reason, I have an auto restart script that will boot them back up when down, so it's just a matter of not crashing. I am running a dedicated server with an Intel Xeon E3-1230v2 @3.5GHz (4Cores/8Threads) with 32GB DDR3 RAM and a 512GB SSD. I installed all of the pre-requisites as stated [here](https://github.com/RocketMod/Rocket.Unturned/tree/master/Rocket.Unturned/Scripts/Linux). Even with the packages installed, the servers are still unable to stay up consistently. I'm going to see if I can't dig up an error later, as it's 3:38 AM at the time of this being posted.

[Unturned.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1691535/Unturned.1.txt)

[Rocket.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1691534/Rocket.1.txt)

**Comment by Trojaner25** [comment]
No crash appears in the logs.

**Comment by diamondpumpkin** [comment]
I'm going to figure all this out now, 3 AM when I posted this.

**Comment by diamondpumpkin** [comment]
I dug up a few more log files, none are helpful. When the server crashes, it just closes, I am running a test server without the screen program when it does crash I'll have the full log in my SSH session. I also tried to run a vanilla server which for me hasn't never work, not even on 15.04. The server doesn't even start, likely due to the GameServer API not starting. 

[Server_russia1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1692104/Server_russia1.log)
[Server_russia1_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1692105/Server_russia1_Prev.log)
[Server_test.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1692106/Server_test.log)
[Server_test_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1692107/Server_test_Prev.log)

**Comment by Trojaner25** [comment]
Did you try the workaround for linux servers?

**Comment by diamondpumpkin** [comment]
Yes, the Rocket servers start fine, they just don't stay started.

**Comment by Trojaner25** [comment]
Someone else (@thereis) also reported this

**Comment by diamondpumpkin** [comment]
After a couple hours, the test server finally crashed. Here is the report:

```
Stacktrace:

Native stacktrace:

        mono() [0x49ff2f]
        mono() [0x4f390e]
        mono() [0x426c19]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7fd070d38390]
        mono() [0x5e8100]
        mono() [0x5e886f]
        mono() [0x5ea8e7]
        mono() [0x5eca95]
        mono() [0x5dfd7e]
        mono() [0x5ce266]
        [0x4026d9f2]

Debug info from gdb:

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

./serverstarter.sh: line 39: 14900 Aborted mono RocketLauncher.exe $INSTANCE_NAME
```

**Comment by aviadmini** [comment]
Are you using mono 3.12.1? If not, you should

**Comment by diamondpumpkin** [comment]
> Are you using mono 3.12.1? If not, you should

Ubuntu 16.04.2 does not go down to that version. 
Available versions:
```
root@s114323:/home/main# apt-cache policy mono-runtime
mono-runtime:
  Installed: 4.2.1.102+dfsg2-7ubuntu4
  Candidate: 4.2.1.102+dfsg2-7ubuntu4
  Version table:
 *** 4.2.1.102+dfsg2-7ubuntu4 500
        500 http://mirror.cogentco.com/pub/linux/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```
