### ISSUE TITLE
Menu dosent appears 

### ISSUE THREAD

**Issue by detektywdywan** [SmartlyDressedGames/Unturned-3.x-Community#2050]
Hello, my game just keep freezing/not loading? (i mean to game menu) after the game loads correctly. screenshot here: https://imgur.com/a/epXT2vi   
( I am not the only one with this problem )

**Comment by SDGNelson** [comment]
Hmm... it looks like it has loaded into the menu scene, but is stuck before creating the user interface or downloading the recent news. I have been looking into a few menu issues recently (e.g. the rare load order one) and freezing after actually getting into the menu is an improvement at least. Unfortunately when getting log files for these there is nothing out of the ordinary. 

If you play the game in Steam Offline Mode does it let you get into the menu properly? The reason I ask is the game disables the news feed in offline mode. https://support.steampowered.com/kb_article.php?ref=3160-agcb-2555

**Comment by detektywdywan** [comment]
Still not working but I have the impression that it is due to a new update because it has not worked since then ( i dosent mean hallowen update but one earlier

**Comment by SDGNelson** [comment]
Sorry not to have any other workarounds to suggest for the meantime. Thanks for giving that a try. I do have two hunches of potential causes, so I will get fixes for those up on the preview branch ASAP. Hopefully we can get this resolved by Friday!

**Comment by detektywdywan** [comment]
Thanks

**Comment by SDGNelson** [comment]
Today I put the speculative fixes in version 3.20.13.1 on the preview branch if you would like to see if it works now:
1. Right-click Unturned in your Steam Library
2. Select Properties and switch to the Betas tab
3. From the dropdown select "preview"

**Comment by detektywdywan** [comment]
still not working, sorry for taking a long time for a reply

**Comment by SDGNelson** [comment]
Sorry that it didn't fix the problem. That is worrying - I have no clue what the problem could be then.

Is it still freezing at the same spot? With only the scrollbar visible, and then it says Unturned is not responding?

If you can attach or email me the following files I am hopeful that one of them might contain a lead:
1. Client.log from the Unturned/Logs folder
2. remote folder from the C:/Program Files (x86)/Steam/userdata/ (your steam id) /304930

**Comment by detektywdywan** [comment]
I mean, yes its still freezing on same spot but unturned is working (like responds, i can click the scrollbar but can't go up or down
 ( i sended client.log to nelson@smartlydressedgames.com (email)

**Comment by SDGNelson** [comment]
Thanks for sending me that log! It contains a very useful error message, so I think we can get this patched now.

**Comment by detektywdywan** [comment]
Ok, 
and when can you fix it?

**Comment by SDGNelson** [comment]
The fix is now up on the preview branch! It should automatically update soon, or you can "verify game files" to force the update. Let me know how that goes. 🤞

**Comment by detektywdywan** [comment]
Yeah! it works,
thank you very much
and sorry for the long replies

**Comment by detektywdywan** [comment]
But when i try joining any serwer that kicks me out and says "server is running version 3.20.13.0 of game, whereas you are running version 30.20.13.1"

**Comment by PandahutMiku** [comment]
> But when i try joining any serwer that kicks me out and says "server is running version 3.20.13.0 of game, whereas you are running version 30.20.13.1"

If you are trying the preview branch, yea it's a "preview"  version and not the same version the servers are running, hence why you can't join any server. If you want to join servers, switch out of the beta.

**Comment by detektywdywan** [comment]
But unturned only works on "preview beta"

**Comment by iBowie** [comment]
You'll have to wait some time until Nelson pushes changes from "preview" to release branch

**Comment by detektywdywan** [comment]
Ok, thx i will wait

**Comment by SDGNelson** [comment]
Glad to hear that resolved it! In that case I will plan to release the preview changes this coming Friday.
