### ISSUE TITLE
Found a 0day

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2051]
Hello Nelson, I want to report a private vulnerability to skip the BattlEye, I leave you my discord here I would like to contact you privately: TERROR#1337

**Comment by jatapa** [comment]
Enail him nelson@smartlydressedgames.com

**Comment by TH3AL3X** [comment]
> nelson@smartlydressedgames.com

I think this is the best way

**Comment by SDGNelson** [comment]
Closing because I replied to the private email.
