### ISSUE TITLE
I cant even download workshop mods (k_EResultFail)

### ISSUE THREAD

**Issue by LautaroDeLaPuente** [SmartlyDressedGames/Unturned-3.x-Community#2052]
The thing is simple, im hosting on a vps but when i go to WorkshopDownloadConfig.json and write the workshops id that i want, when i start the server it says the following message; 

Download workshop item 2088862222 failed, result: k_EResultFail
Downloading workshop item: 928394140
Download workshop item 928394140 failed, result: k_EResultFail
Downloading workshop item: 2235585190
Download workshop item 2235585190 failed, result: k_EResultFail
Downloading workshop item: 2218113945
Download workshop item 2218113945 failed, result: k_EResultFail
Downloading workshop item: 2209916386
Download workshop item 2209916386 failed, result: k_EResultFail
Downloading workshop item: 2203951443
Download workshop item 2203951443 failed, result: k_EResultFail
Downloading workshop item: 2218114825
Download workshop item 2218114825 failed, result: k_EResultFail

And does that with every each workshop, so i tried to install them manually, nothing changed, same thing.
I even reinstalled the entire server directory, nothing changed, i changed the mods that i chose, nothing happened.
Hope someone with same error or Nelson can help me with this

**Comment by TH3AL3X** [comment]
> The thing is simple, im hosting on a vps but when i go to WorkshopDownloadConfig.json and write the workshops id that i want, when i start the server it says the following message; 
> 
> 
> 
> Download workshop item 2088862222 failed, result: k_EResultFail
> 
> Downloading workshop item: 928394140
> 
> Download workshop item 928394140 failed, result: k_EResultFail
> 
> Downloading workshop item: 2235585190
> 
> Download workshop item 2235585190 failed, result: k_EResultFail
> 
> Downloading workshop item: 2218113945
> 
> Download workshop item 2218113945 failed, result: k_EResultFail
> 
> Downloading workshop item: 2209916386
> 
> Download workshop item 2209916386 failed, result: k_EResultFail
> 
> Downloading workshop item: 2203951443
> 
> Download workshop item 2203951443 failed, result: k_EResultFail
> 
> Downloading workshop item: 2218114825
> 
> Download workshop item 2218114825 failed, result: k_EResultFail
> 
> 
> 
> And does that with every each workshop, so i tried to install them manually, nothing changed, same thing.
> 
> I even reinstalled the entire server directory, nothing changed, i changed the mods that i chose, nothing happened.
> 
> Hope someone with same error or Nelson can help me with this

Are you using Steam Network v2?

**Comment by LautaroDeLaPuente** [comment]
How can I see that?

**Comment by LautaroDeLaPuente** [comment]
Im using the one that came with the server when I installed it

**Comment by SDGNelson** [comment]
Typically this would be caused by a temporary loss of connection to the workshop servers, e.g. for maintenance. If you can attach the `workshop_log.txt` file from your `U3DS/Logs` folder however Steam may have logged some information about why it failed.

Hid TH3AL3X's comment as it would not be related to that.

**Comment by LautaroDeLaPuente** [comment]
How could i fix this?

**Comment by LautaroDeLaPuente** [comment]
Theres none file like that
![Uploading IMG_20201024_181308.jpg…]()

**Comment by SDGNelson** [comment]
My bad: for steamcmd it would be at `steam/logs/workshop_log.txt`

**Comment by LautaroDeLaPuente** [comment]
Got the error, it says that theres no enough disk quota? What is it?

**Comment by SDGNelson** [comment]
Do you have enough space on the drive for it to download?

**Comment by LautaroDeLaPuente** [comment]
Yes, a lot

**Comment by SDGNelson** [comment]
Perhaps Steam does not have read/write permissions there?

**Comment by TH3AL3X** [comment]
He is using root directory, he has all permissions

**Comment by TH3AL3X** [comment]
> Typically this would be caused by a temporary loss of connection to the workshop servers, e.g. for maintenance. If you can attach the `workshop_log.txt` file from your `U3DS/Logs` folder however Steam may have logged some information about why it failed.
> 
> Hid TH3AL3X's comment as it would not be related to that.

Please check my emails

**Comment by jatapa** [comment]
he fixed it already he had to reinstall steamcmd

**Comment by mir1907** [comment]
I'm getting the same error for the Total War Attila game. I cannot install new mods or update existing mods. I get the k_EResultFail message that the mod could not be created in the workshop. If anyone knows the solution to this problem, please write.

**Comment by mir1907** [comment]
> Aynı hatayı Total War Attila oyunu için de alıyorum. Yeni modlar yükleyemiyorum veya mevcut modları güncelleyemiyorum. Modun atölyede oluşturulamadığına dair k_EResultFail bir mesaj alıyorum. Bu sorunun çözümünü bilen varsa lütfen yazsın.

**Comment by mir1907** [comment]
> I get the same error for the Total War Attila game. I can't install new mods or update existing mods. I'm getting a k_EResultFail message that the mod can't be created in the workshop. If anyone knows the solution to this problem, please write.
