### ISSUE TITLE
Abstract Saving

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#2053]
I know this is a big ask, but it would be useful if the Map Saving and Player data saving (inventory, xp, group, all other player files) were abstracted like how Connections and Transports are now. Then we could drop in our own saving code to do other things like saving to database, not saving at all, etc. 

I understand if this is too much for Unturned 3.0, but it would be nice if you would consider something like this for Unturned II.

**Comment by SDGNelson** [comment]
It is abstracted in Unturned II so that plugins can provide a custom "persistence backend" that has asynchronous methods for world and player data, but this is unlikely to happen in Unturned because it is relatively low priority compared to the other ongoing refactors (currently UI).
