### ISSUE TITLE
[Feature Request] More magazine options

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2058]
1) The ability to override the sound of shot by attaching a special magazine. The sound could be inside magazine folder, and some special tag in the magazine asset like Shot_Sound_Override would make it work
2) Interaction between barrel attachment and the magazine. It would be nice to be able make it, so that you can attach certain magazines to a gun, only if it has special barrel attached. The barrel would just add new magazine caliber for the gun (and perhaps removing the others/some of the others, depending on their position, like Remove_Magazine_Caliber 0), This would allow making ammo type conversion attachments
3) The ability to override reload animation with a special magazine
4) The ability to override gun's action type with a special magazine, like converting Trigger based weapon into a bolt-action one, or even a rocket launcher
5) The ability to modify gun's ballistic properties with a special magazine. Ballistic_Steps, Ballistic_Drop, Ballistic_Travel would be set in the magazine asset and override the gun's default ballistic properties

I know the last two are probably not possible, because all this is probably hard-coded into the game, but the first 2 are kinda possible, I suppose. Well, at least the second.

**Comment by DerpyHoowes** [comment]
The reason why I believe first feature is possible, is because we already can override shooting sounds by attaching some special barrel, so why wouldn't that work with magazines, I suppose?

**Comment by SDGNelson** [comment]
Especially point 1 is still kind of a question in Unturned II, determining which attachments should override certain properties without hardcoding that "barrels" override silencer sound. Maybe a priority number.

**Comment by DerpyHoowes** [comment]
Well, can we actually expect some of these features in Unturned 3.0? I mean, all this stuff that is going to be in Unturned II is cool and all, but right now the only game we can play is Unturned 3.0...

**Comment by SDGNelson** [comment]
There will continue to be more feature updates for Unturned, but the highest priority are features for map projects and the refactors.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
