### ISSUE TITLE
PSA: uGUI Refactor

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2059]
In the "glazier" Steam beta branch the game has been updated to use uGUI rather than IMGUI. The goal at the moment is seamless compatibility, so if you run into any bugs please report them, whereas quality improvements will be done later down the road.

This will affect any plugins with custom menus. Any custom canvas with a sort order >15 will show over top of the built-in UI, and <15 will show underneath.

1. Right-click Unturned in your Steam Library
2. Select Properties and switch to the Betas tab
3. From the dropdown select "glazier"

Originally described in issue #1234

**Comment by PandahutMiku** [comment]
Loading into Singleplayer and quitting back to menu doesn't load the menu again at all. 
![Unturned_aBnA6MQHQ8](https://user-images.githubusercontent.com/17209937/97770049-5a14d300-1b06-11eb-9204-53176f3ca02b.png)

Throws a null reference with something to do with Glazier. Logs Attached
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5468452/Client.log)

Also, for some items with longer names the quality overlaps the name. This even happens at higher resolutions
![Unturned_dOWitqxI65](https://user-images.githubusercontent.com/17209937/97770035-449fa900-1b06-11eb-8c85-9c5511d1f34c.png)

**Comment by SDGNelson** [comment]
Thanks for trying it out, and for the log file! I will get all of those fixed up.

**Comment by MoltonMontro** [comment]
Left-clicking/right-clicking while dragging an item in inventory does not work (item cannot be manually dragged to a different inventory slot).

**Comment by SDGNelson** [comment]
Thanks Molt! How did item drag-dropping manage to break between yesterday and today?!

**Comment by educatalan02** [comment]
I found another bug, related to the chat itself.
It would be good if people cant use things like <color=Red>//<size=50>//<b>

Also here is the video https://youtu.be/ozWYHAbxvZg
And here is the Client.log: 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5468953/Client.log)

**Comment by Trojaner** [comment]
It would be great if this system could be used to create GUIs from code instead of having to use Unity. Rust uses json that describes what UI elements to create and what properties they have (e.g. anchors, callbacks on click/submit, etc.).

**Comment by SDGNelson** [comment]
@educatalan02 The server should be rejecting client messages with tags (same as current release version), so I will double-check that. I will also fix the chat field to not format rich text tags. The shadows are similar to the shadows/outlines on the current release version.

@Trojaner The current way plugins are creating UIs is not really intentional, originally someone realized they could spawn uGUI canvases and went from there. I agree that long-term plugin UIs would need a way to use the game UI code, in particular to work with UIElements down the road.

**Comment by 01-Feli** [comment]
I have found a bug with the spy in lower resolutions


Video: https://youtu.be/L_-0PSG4UGY

**Comment by SDGNelson** [comment]
I've just released a patch which should fix all of the bugs reported so far. 🙂 

Thanks for the report 01-Feli! - Will fix. (not fixed in the patch just released)

**Comment by 01-Feli** [comment]
I have found a new bug in this case is related to scopes.
First Bug:
When you have graphics presets in medium and higher a really wired circle
Second Bug:
When you have low quality in your scope when you try to enter in the escape menu you cant see itt because of the scope quality 

Video: https://www.youtube.com/watch?v=CV2Czu2nKk8 (Sorry for my friend voice i forgot to mute my discord and my sellf  😂)

**Comment by 01-Feli** [comment]
I haave found another big bug for lower resolutions
If you use a lower resolution in the mune you can see some buttons and you cann click then while you are in the menu ui|
Video: https://youtu.be/IeOuFs2WX5M

I have another question: if it is a problem for you if i post a lot of bugs in diferent comments

**Comment by 01-Feli** [comment]
I don't know if this a bug cause by the game ui

You cant select spawned objects in the beta version

Video: https://youtu.be/MeyoXFm9MeY

Client Log: https://pastebin.com/raw/6GNY100c

**Comment by 01-Feli** [comment]
The last bug i found is this:

This bug is related to the devkit ui, i can't interact with, the same happends when i tried to use it in the editor
Video: https://youtu.be/oi0G4WxViR4

**Comment by SDGNelson** [comment]
> if it is a problem for you if i post a lot of bugs in diferent comments

@01-Feli it is preferable to consolidate into a single comment to avoid spamming everyone. If you want to report others separately then please email me instead.

**Comment by iBowie** [comment]
Cyrillic fonts (and probably some other languages) have issue with letters being too far from each other
![fonts](https://user-images.githubusercontent.com/31174978/97800912-c1dc3280-1c5a-11eb-91f4-180b1c10bb28.png)
Also shadows are not applied everywhere or applied not enough, leading to some not appealing and mixed with backgrounds results.
![fonts2](https://user-images.githubusercontent.com/31174978/97800945-f6e88500-1c5a-11eb-87df-f150927cab07.png)
![fonts3](https://user-images.githubusercontent.com/31174978/97800951-04057400-1c5b-11eb-9848-26ef849ea8f6.png "Oxygen amount is barely visible")

**Comment by SDGNelson** [comment]
@iBowie the spacing in the tooltip was made wider to prevent the shadows from conflicting, but I agree it does not look very good. I will experiment with a box soft shadow behind the tooltip to reduce the text shadow.

The other text shadows closely match the current shadows in the IMGUI version, but especially on the life bars they could use a contrast boost.

The clicked state is because uGUI keeps a "selected" control for gamepad/keyboard navigation, though it does look a bit odd. Maybe I will disable the selected visual for now.

**Comment by warren39** [comment]
Missing Chinese text in Workshop:
![workshop](https://user-images.githubusercontent.com/64722485/98498266-45aca500-2281-11eb-9d47-41a6dbfb92b1.png)

**Comment by warren39** [comment]
Text shadow inconsistent between English and Chinese
![txt](https://user-images.githubusercontent.com/64722485/98498593-22362a00-2282-11eb-98db-ad3cf0bec078.png)

**Comment by SDGNelson** [comment]
Thanks @warren39! I will check into those

**Comment by gegtor** [comment]
The gamma issue is fixed and besides the issues mentioned above everything seems to work on macOS

As a big bonus, something about this reworked GUI gave macOS big performance boost around 20+ FPS

**Comment by SDGNelson** [comment]
@warren39 those issues should now be fixed on the beta branch. The problem with the workshop details in the server info screen was insufficient vertical space causing the text to truncate, so I reviewed all the shorter labels in the game to hopefully ensure no other labels would have problems with CJK text.

**Comment by SDGNelson** [comment]
With misc changes yesterday/today I think the uGUI update might be ready to go for next Friday!

**Comment by PandahutMiku** [comment]
> With misc changes yesterday/today I think the uGUI update might be ready to go for next Friday!

That's exciting, the new UI does seem better mostly.

I'm not sure how open to changes you are willing to make for the sake of appearance, but there are a few annoying things.

The menus being generally "lighter" and less shaded does look better in some spots but causes issues in others

![image](https://user-images.githubusercontent.com/17209937/100494368-0a2e2980-310f-11eb-8a82-2fd7062978ba.png)

That's how the Skills menu used to look, and this is how it looks now:
![image](https://user-images.githubusercontent.com/17209937/100494353-ef5bb500-310e-11eb-9c0d-88afb8c216b9.png)

Before:
![image](https://user-images.githubusercontent.com/17209937/100494395-334eba00-310f-11eb-9799-7c4502e8cbc1.png)
New UI:
![image](https://user-images.githubusercontent.com/17209937/100494400-3e094f00-310f-11eb-971b-6844459e289e.png)
Before:
![image](https://user-images.githubusercontent.com/17209937/100494406-4bbed480-310f-11eb-9f8a-eadb5d54793c.png)
New UI:
![image](https://user-images.githubusercontent.com/17209937/100494407-50838880-310f-11eb-9df0-dff44186c86a.png)

Before:
![image](https://user-images.githubusercontent.com/17209937/100494415-6e50ed80-310f-11eb-8fc4-133cc2569e31.png)
New UI (ignore the film grain, the text is just harder to read:
![image](https://user-images.githubusercontent.com/17209937/100494418-7446ce80-310f-11eb-8855-8ff43caa8e47.png)

The text shadows as well can look iffy in some parts, although that's more up to personal preference I suppose:
Before:
![image](https://user-images.githubusercontent.com/17209937/100494432-950f2400-310f-11eb-957e-8b38b68b278e.png)
New UI:
![image](https://user-images.githubusercontent.com/17209937/100494426-84f74480-310f-11eb-9ed1-b62841f4a723.png)

Some of the menus look better with lighter shading/more sleek, like the weapons menu.

Of course, most of that is just my opinion, and I understand if you don't really think it's worth it to clean up those minor appearance things, still more gained than lost. 

I would say the most annoying thing is just the shading for inspecting an item in your inventory with the new glazier UI. As shown above, it's too light and makes the text hard to read vs the text behind it.

**Comment by SDGNelson** [comment]
Thank you for the feedback Miku! Thanks for trying it out again, much appreciated.

I agree with your comparison of how the UI appears "lighter", good point, and will make it more opaque accordingly.

Unfortunately making the text outline match between them is more challenging. uGUI uses distance fields which are not pixel-perfect, so the shadow has to be a bit stronger to show consistently at different sizes. The current settings have been revised several times, can adjust more with further feedback, but I'm hopeful that they're okay.

**Comment by PandahutMiku** [comment]
> Thank you for the feedback Miku! Thanks for trying it out again, much appreciated.
> 
> I agree with your comparison of how the UI appears "lighter", good point, and will make it more opaque accordingly.
> 
> Unfortunately making the text outline match between them is more challenging. uGUI uses distance fields which are not pixel-perfect, so the shadow has to be a bit stronger to show consistently at different sizes. The current settings have been revised several times, can adjust more with further feedback, but I'm hopeful that they're okay.

Thanks for hearing me out.

I realized after that I was taking those screenshots with super modified UI Colors. The issues are pretty much the same/not affected by it, but the new UI does look a decent bit better using default colors.

I feel like a lot of people are going to dislike the text shadows at first, but to be honest, I've kind of grown to like them. Gives me old fallout games UI Vibes.

With the default settings, because of the "lightness" of the menu, it's really hard to see your "typing spot indicator" when uploading workshop or searching for servers. At first, I thought it was gone completely. 
![menu](https://user-images.githubusercontent.com/17209937/100497511-f7751e00-3129-11eb-987d-0fe57e5a6e34.gif)
The same thing for selecting, really can't tell what I have selected.
![select](https://user-images.githubusercontent.com/17209937/100497558-40c56d80-312a-11eb-97b5-9a3a65ca53cd.gif)


One last thing, all of the text boxes now flash at you when you start typing in them, the ones on the main menu (server searching, etc) and even Signs
![Flash](https://user-images.githubusercontent.com/17209937/100497669-090af580-312b-11eb-9767-8a4919ac66c7.gif)
They didn't use to do it before.
![NoFlash](https://user-images.githubusercontent.com/17209937/100497696-2d66d200-312b-11eb-8f6f-0a45c821e3ec.gif)
The effect kind of feels jarring

**Comment by SDGNelson** [comment]
Currently the text field selection color is (1 - textcolor) because the text color is configurable, but it does look really difficult to see there. Will experiment with a different approach - maybe it should be handled differently for light/dark theme.

Agreed the flash when starting editing is annoying. I will change that to use the selected sprite instead.

**Comment by SDGNelson** [comment]
Misc fixes and changes have been uploaded to the beta branch now. For the text field selection color I tried a few alternatives taking into account the background color, but settled on using the separate foreground color setting with 50% transparency. By default this contrasts with the background and text, and looks better with custom color schemes.

Edit: server beta is broken right now, will fix.

**Comment by SDGNelson** [comment]
Closing this issue because the rewrite has been released, so reported issues will be handled separately.

**Comment by PandahutMiku** [comment]
It might be worth considering, in the future, more publicly announcing these betas, if you do another. Maybe announce alongside a game update, asking for any feedback, and also on the SDG Forums/wherever possible. Just something to try to encourage people to explore the Betas and provide feedback before they hit live.

**Comment by SDGNelson** [comment]
Fair point. It would be nice to have more participation next time
