### ISSUE TITLE
Lag On Newer Maps

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#206]
Hello Nelson,

I've been running servers for a while, and I constantly notice that the newer maps tend to make people lag. Not really FPS lag, but instead rubber banding. Size of map doesn't really matter according to my findings. I'm wondering if the problem is with Unturned itself, seeing that small workshop maps as small as a 15MB medium sized map can cause rubber banding, while maps like Canada+ made back in 2015-16 can do just fine. I'm nearly certain it isn't the machine- I'm running an i7-4790k with 16gb RAM, plenty for a single server. Please let me know if you need any other information. Thanks!

EDIT: I'm thinking maybe some of the new devkit features may be causing the lag, or maybe your new models available to be put into the world. But if so- is this an optimization issue that can be fixed, or if not, would it be possible to possibly make a purge feature to remove all of the potentially laggy stuff?

**Comment by WarpKat** [comment]
Does it happen on the stock maps?  I think the only issue I've seen after he fixed the original rubber-banding problem is where I stepped onto a sidewalk in Washington, but it's not show-stopping like it was a few weeks ago.

**Comment by N1GHTPATROL** [comment]
I don't think so, the workshop maps which are newer seem to lag a lot more than vanilla maps.

**Comment by SDGNelson** [comment]
This happens when the serverside collision-only representation of the object doesn't match the clientside version. I fixed up some of these objects on the M2M maps, but there might still be some mismatched objects. Do you know any specific objects you encountered this with?

**Comment by N1GHTPATROL** [comment]
This seems to happen with really any maps made in 2017 and 2018. Seems fine at first, but people begin to report rubber banding. I've even noticed it on a test server with just me on it. When I spawn holding shift, I rubber band until I stop running. It can't be the server either since it was the only server running on the machine.

**Comment by N1GHTPATROL** [comment]
I'm not sure of any specific objects, but I do know that the Russia rocks were on all maps this happens with.
