### ISSUE TITLE
Battleye Corrupted Data kick

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2060]
Getting reports from lots of players lately and I just got a kick myself too. After kick from server - you can re-join without any issues and without reinstalling BE or even relaunching game.

![image](https://user-images.githubusercontent.com/14231707/97781704-e3271b00-1b95-11eb-8fea-2ffa943f0ab7.png)

**Comment by SDGNelson** [comment]
Thanks for the report, I will ask BattlEye about this.
