### ISSUE TITLE
Some bug with "Trigger" type weapons with explosion damage

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2061]
Noticed that trigger type guns with explosion damage (non-projectile) are now able to one-tap players even if explosion damage is set to very low one. Curious if something been changed which might be related to it with recent updates? I haven't changed anything for these weapons. Got one plugin which tweaks explosion damage in some ways but it hasn't been changed for a long time too.

**Comment by SDGNelson** [comment]
Several updates ago the explosion damage was changed to falloff based on distance to the closest point on the character, rather than to the center of the character. That is the most likely difference

**Comment by baranmod** [comment]
still think something is wrong with this explosion damage. It won't bug every time but sometimes it takes only one hit to kill player with full HP, equipped with 80% armor multiplier clothes (+ same explosion armor multiplier) with a relatively low damage gun which technically should deduct 10HP~ with that one hit. Explosion damage on that gun's mag is set to 5.

This situation is only an example, same bug happens with every gun which have explosion damage set on its mag. I double checked all configs - they seems to be fine and these configs haven't been changed for ages.

**Comment by SDGNelson** [comment]
Hmmm I will double-check for the next update to be safe

**Comment by SDGNelson** [comment]
Have you noticed this after the recent updates? There was a minor change to ensure the distance to the closest point was actually still less than the radius of the explosion.
