### ISSUE TITLE
RAM Allocation Issue

### ISSUE THREAD

**Issue by NoSharp** [SmartlyDressedGames/Unturned-3.x-Community#2062]
An Unturned Server allocated 4GB of DDR4 RAM will not go above 1GB of RAM.

**Comment by educatalan02** [comment]
If you dont provide some details this issue would be closed/ignored

**Comment by NoSharp** [comment]
The only other information I can provide is: x64 Ryzen7 3800x CPU with 64GB of RAM. Using Docker & Pterodactyl with an allocation of 100% and 4GB of RAM.

**Comment by educatalan02** [comment]
OS?
Logs?

**Comment by Trojaner** [comment]
Unturned, like all other programs, only uses as much memory as it needs, it doesn't use all available RAM...
No issue here imo.

**Comment by NoSharp** [comment]
It just seemed a little strange how it wasn't able to go over 970MB when 20 players where on as oposed to when there was 0 players on.

**Comment by SDGNelson** [comment]
Agreed that this sounds like a non-issue

**Comment by ModernMoGamer** [comment]
I'm running pterodactyl myself and my clients (and my own) server's can use from 800 mb to 5.5 Gb's of RAM usage.

**Comment by NoSharp** [comment]
It wasn't to do with that, the server was just running at 1gb of ram which was surprising 🤷‍♂️
