### ISSUE TITLE
Unable to connect to steam servers issue

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2063]
Hey @SDGNelson, 
A few hosting servers that I help maintain are experiencing a bug with 
_Failed to connect to Steam servers because k_EResultInvalidParam, no longer retrying_ 
is there a reason behind that fail, as steam servers aren't down at the moment and I know you were trying out different variables with the NetTransport Rewrite.

**Comment by SDGNelson** [comment]
There might be more details in the Server_ (name) .log file, but from context I wonder if the GSLT is formatted correctly?

**Comment by joeymisfit** [comment]
It was due to saving workshops inside of Bundles rather than using the workshopdownloadids.json this has been fixed, thank you for the immediate response.
