### ISSUE TITLE
Instant VAC (Game-ban)

### ISSUE THREAD

**Issue by Opelek** [SmartlyDressedGames/Unturned-3.x-Community#2064]
so i decide to use cheats in unturned and i got vac, when i want back without cheats bcuz this game make my feels when i want back to game i got insta van in new account, pls help me fix this bcuz , i regret my actions.

pls give me one chance

**Comment by TH3AL3X** [comment]
Your HDD,SSD serials are banned by BattlEye, Nelson can't do nothing, welcome!

**Comment by Opelek** [comment]
@SDGNelson is there chance to make some with it? i promise i will never use cheats again.

**Comment by iBowie** [comment]
Basically you can't, vac is given permanently, and battleye won't unban you
