### ISSUE TITLE
Campfires and Ovens on all vehicles won't cook items.

### ISSUE THREAD

**Issue by Stalionn** [SmartlyDressedGames/Unturned-3.x-Community#2065]
So today I thought I would bring this up but, if you place a Fire or a Stove on any vehicle (Helicopters/boats/cars) and you try to cook or craft something that involves heat it won't work. It works for (I think) everything that involves being crafted with heat. I would say it's a pretty big bug in unturned. I also did some experimenting with trains, it also doesn't work. I also leaked a video of me testing. (I'm also not sure if this is a bug already reported but I just wanted to let you guys know about it.)  

Here's my steam profile if needed: https://steamcommunity.com/profiles/76561199012846877/

And here is the YouTube video I made of it: https://www.youtube.com/watch?v=6VPcbIhDX74

**Comment by SDGNelson** [comment]
Thanks for the report. Marking this as next update, but I am not sure which update it will be fixed for.

**Comment by Stalionn** [comment]
No problem!

**Comment by SDGNelson** [comment]
Fixed for the next update
