### ISSUE TITLE
Emission doesn't work in materials with Transparent render mode

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2066]
I create material, choose Transparent render, pick up texture, edit transparency and enable emission. And emission just doesn't work in game, it doesn't appear.
I'm using Unity 2018.4.14f1.

It's an object with Binary_State. When I activate it, emission works. I used white color in emission to keep emission everytime. 

What can I do to fix this problem?

**Comment by SDGNelson** [comment]
Asset bundle version is probably not set so it is trying to replace the material - if you set Asset_Bundle_Version to 3 it should work.

**Comment by aladairmaxwell** [comment]
It doesn't.

**Comment by SDGNelson** [comment]
Re-reading your original post I think I misunderstood. You do not want the emissive material to be turned on/off when the object is turned on/off? By default it will enable/disable emission on the "Toggle" GameObject, and there is no way to opt-out of that at the moment except using a different name.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
