### ISSUE TITLE
WorkshopDownloadConfig downloading all dependencies 

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#2068]
Is there anyway you can add an option to let us use the WorkshopDownloadConfig to download only specific mods and ignore their dependencies and such? Some mods use "dependencies" to show off their optional mods. 

For example,
this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1857442843
Requires Vanilla Spawn Overrides: https://steamcommunity.com/workshop/filedetails/?id=2068309538
Which requires all of the mod maker's other mods.
Which is not what we want, we didn't even want Vanilla Spawn Overrides to begin with. So instead we manually install the mod and get warned every time on start up to add it to the config and remove it from files.

I understand this is kind of an issue on the mod maker's side as well, but it would just be nice to optionally ignore those dependencies. If that is handled by steam/nothing you can touch, maybe let us blacklist/ignore specific Workshop IDs? It would just be nice to use the new system without being forced to download more mods then you want.

**Comment by SDGNelson** [comment]
Makes sense. The game finds dependencies, so it would be straightforward to optionally ignore dependencies on a per-file basis. I will mark this as "next update" to do soon.

**Comment by SDGNelson** [comment]
Added for this coming Friday's update.
