### ISSUE TITLE
Interact colorful text

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2069]
Is it call Rich Text, or something, when you can add <color=></color> etc. to text?
Well, why Interact text for Quest interactability object in localization.dat item file doesn't support it? I wanted to add some colors, but it just don't apply.

**Comment by SDGNelson** [comment]
Yes, that is rich text markup. Currently it's only enabled for NPCs and conditions, but I will enable it for quest interact as well.

**Comment by SDGNelson** [comment]
Enabled for this coming Friday's update.
