### ISSUE TITLE
Server crash, need help

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2073]
Recently, the server often crashes. I don't know if it's a plug-in issue or a mod issue. Log shows it might be a BattlEye connection problem. Log ends with:

`
[2020/11/11 22:18:28] [Info] BattlEye Server: Failed to receive from BE Master (10054)

[2020/11/11 22:18:28] [Info] BattlEye Server: Disconnected from BE Master
`

The crash dmp files:
[Crashes.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5525213/Crashes.zip)

I don't want to disable BattlEye. What should I do

**Comment by SDGNelson** [comment]
Thanks. It does appear to be a BattlEye internal crash. I have forwarded the .dmp to BattlEye.

**Comment by SDGNelson** [comment]
BattlEye sent over new versions of the files for this Friday, but if you would like to try updating it early you can replace this dll: https://drive.google.com/file/d/13gSc_BaR4rAPwpCwFqtH8G84fUQme1-M/view?usp=sharing

**Comment by TH3AL3X** [comment]
Will this patch the vuln that i found Nelson?

**Comment by warren39** [comment]
OK, I will try the new version, Thanks!
