### ISSUE TITLE
Swimming on land animation bug

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2075]
Seen this a couple times this month - sometimes the animation doesn't end after exiting water.
[https://imgur.com/ul30fYE](https://imgur.com/ul30fYE)
Haven't been able to recreate it on purpose.

**Comment by SDGNelson** [comment]
Odd, thanks for the report. I will mark this as "next update" so that I remember to look into it, however it will probably not make it into Friday's Unity 2019 update.

**Comment by SDGNelson** [comment]
The stance change RPC was marked unreliable for some reason, so that was probably the cause. If you run into it after the next update feel free to comment and I will re-open
