### ISSUE TITLE
High cpu usage in idle

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#208]
Empty server without plugins or mods consumes about 20% cpu core in idle.
OS: Ubuntu 14.04 with latest updates
CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz

**Comment by Trojaner25** [comment]
Do you have plugins?
If yes, does this happen without RocketMod?

**Comment by D-AIRY** [comment]
Tested with and without RocketMod, results the same

**Comment by Trojaner25** [comment]
Sorry I did not read your first message correctly, which already states that it happens without plugins or mods.

Does it happens with a fresh new level after wipe?

**Comment by D-AIRY** [comment]
Yes, the same

**Comment by D-AIRY** [comment]
There is strace of idle server for 60 seconds
```
# strace -c -p 96445
Process 96445 attached
[ Process PID=96445 runs in 32 bit mode. ]
^CProcess 96445 detached
System call usage summary for 32 bit mode:
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 75.17    0.015594           0    121915       813 futex
 23.23    0.004819           0    166663           gettimeofday
  1.30    0.000270           0      2991           write
  0.10    0.000021           0      1480      1480 recvfrom
  0.07    0.000015           0      1482           select
  0.06    0.000013           0       402           stat64
  0.06    0.000013           0      7221           clock_gettime
  0.00    0.000000           0         9           open
  0.00    0.000000           0         7           close
  0.00    0.000000           0        11           time
  0.00    0.000000           0        61           _llseek
  0.00    0.000000           0        73           nanosleep
  0.00    0.000000           0         7           ftruncate64
  0.00    0.000000           0        36           lstat64
  0.00    0.000000           0        16           fstat64
  0.00    0.000000           0         2           send
  0.00    0.000000           0        68           semop
------ ----------- ----------- --------- --------- ----------------
100.00    0.020745                302444      2293 total
```
There alot of `gettimeofday` syscalls, about 2777 per second. Why it doesn't handle with vDSO?
CPU usage holds at 40%

**Comment by Trojaner25** [comment]
Because this is Unity's / monos issue and not Unturneds. Unturned does not have native code or code which is this low level.

**Comment by D-AIRY** [comment]
So there is no way to fix it?

**Comment by Trojaner25** [comment]
A fix would be to update Unity probably, but this will likely not happen at all.
Updating Unity breaks almost everything in Unturned, and since Nelson is already working on Unturned 4, he will likely not spend any time to do that
