### ISSUE TITLE
Strange loading screen

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2080]
![image](https://user-images.githubusercontent.com/14231707/99110507-27cda000-25f3-11eb-909f-45602771227e.png)

**Comment by jatapa** [comment]
Already fixed in the new patch

**Comment by SDGNelson** [comment]
I accidentally mistyped an 'r' into the Status.json file when I incremented the version number before releasing the patch. 🤕

**Comment by baranmod** [comment]
ahh, patch just showed up on steam. Thanks :)

**Comment by SDGNelson** [comment]
It might be an off day. I went to make coffee just now and absentmindedly poured the grounds in my cup by mistake.
