### ISSUE TITLE
Weird bug with shaders/lightning on Linux

### ISSUE THREAD

**Issue by kotyk7** [SmartlyDressedGames/Unturned-3.x-Community#2081]
Hello, found a weird lightning/shaders problem on my modded RP server.
I'm on Linux (Pop!_OS 20.10), my friends on Windows don't have this bug.

I think the picture describes the problem the best
![Screenshot_from_2020-11-13_20-14-24](https://user-images.githubusercontent.com/35780035/99113270-4336ac00-25ef-11eb-89dd-619e99c0c528.png)

Can reproduce it on Curated maps:
 - France, the trees are completely black
 - Elver, some trees and some objects have weird black shadow
 - California, trees and parts of the Bixby Bridge are black

But on official maps I couldn't reproduce the problem anywhere.

This is the map that has this problem: https://steamcommunity.com/sharedfiles/filedetails/?id=2125200799
List of assets used by this map: https://hastebin.com/mevocugefi.rb

My client.log
https://paste.gg/p/anonymous/bf0d9f2304a144669057fc5fa0b68ba9

Everything worked before the update that came out today (3.20.14.0).
Hope it gets fixed soon.

**Comment by SDGNelson** [comment]
Uh oh! Per-platform incompatibilities was unexpected... I will update the Hawaii and Greece asset bundles today, as for the curated maps and mods it will be gradual.

**Comment by SDGNelson** [comment]
The Hawaii Assets and Greece workshop files have been updated now.

**Comment by kotyk7** [comment]
Thank you so much! Going to update it ASAP

**Comment by averycoolbean** [comment]
i seem to still be having this issue with most if not all buildings from france (both on france and on workshop terrains utilising its assets, pictured in the first 2 is kyushu)
![Kyushu](https://user-images.githubusercontent.com/32810451/146353244-1b75c9f3-d44e-47a2-8714-bd1485f441ec.png)
![Kyushu](https://user-images.githubusercontent.com/32810451/146353360-ab97d5fb-d7d6-4b42-8727-b74fd1154a75.png)
![France](https://user-images.githubusercontent.com/32810451/146353765-4513b294-e09d-4b31-aba0-5ab69e79da23.png)

so to put it bluntly, is this still getting fixed for other curated maps or am i better off just playing through proton?
like genuinely, not trying to be rude, i understand that curated maps are outside your control, but a full year has passed and the issue still persists and i just need a solution

**Comment by averycoolbean** [comment]
apparently cars are affected as well, just about everything from france is, notably i see trees working just fine though

**Comment by KaloyanMarinoff** [comment]
2022, I still have these issues with trees in France. OS is Ubuntu and GPU is ATI RX 570
