### ISSUE TITLE
Forward/redirect server traffic to another IP

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#2085]
I'm trying to host an Unturned server, where the setup involves a VPS with a dedicated IP, and another box with the Unturned server running on it. They're connected with Wireguard, and I am able to connect to the server through Wireguard or on the local network. The issue is that I want users to be able to connect to the VPS and have it forward the traffic over to the server.

With Minecraft for example, this is as simple as forwarding TCP traffic with `socat` or `iptables`.

I see that Unturned uses UDP & TCP, so my first attempt was to try and use `socat` like this:

```bash
socat tcp-listen:27015,fork,reuseaddr tcp:srv0:27015 &
socat tcp-listen:27016,fork,reuseaddr tcp:srv0:27016 &
socat tcp-listen:27017,fork,reuseaddr tcp:srv0:27017 &
socat udp-recvfrom:27015,fork udp-sendto:srv0:27015 &
socat udp-recvfrom:27016,fork udp-sendto:srv0:27016 &
socat udp-recvfrom:27017,fork udp-sendto:srv0:27017 &
```

That didn't work unfortunately. When connecting to the IP the server name and stuff would show, but when I click on connect, it would say something about being disconnected from Steam.

Any ideas are appreciated. I don't know a lot about Unturned though since I don't play it. Just hosting for a friend.

**Comment by SDGNelson** [comment]
Sorry, but if forwarding the traffic did not work then I am not sure what to suggest. It might not be supported for the meantime. (personally unfamiliar with a setup like this)

**Comment by asineth0** [comment]
Alright, thanks anyway.

**Comment by gibsonpil** [comment]
For those who find this post on Google as I did, I had success with the following commands:
`
socat tcp-listen:27015,fork,reuseaddr tcp:srv0:27015 &
socat tcp-listen:27016,fork,reuseaddr tcp:srv0:27016 &
socat tcp-listen:27017,fork,reuseaddr tcp:srv0:27017 &
socat udp-listen:27015,fork,reuseaddr udp:srv0:27015 &
socat udp-listen:27016,fork,reuseaddr udp:srv0:27016 &
socat udp-listen:27017,fork,reuseaddr udp:srv0:27017 &
`
