### ISSUE TITLE
Option to lock graphics settings on servers

### ISSUE THREAD

**Issue by Tyranork** [SmartlyDressedGames/Unturned-3.x-Community#2086]
Just give server admins the ability to lock graphics settings (At the very least let us force low grass) in their servers. I'm tired of the current state of Unturned 3.0. I'm working on a hardcore survival themed server, like how Unturned used to be.

**Comment by Tyranork** [comment]
I understand that you don't want to block out people from playing multiplayer because of servers forcing higher settings, but the community will always support itself if given the *option* to lock graphics. FOr every server that does lock I'll bet my mouse that there will be two more (5x, max vehicles, tp, home, *No locked graphics*) servers.

**Comment by SDGNelson** [comment]
Sorry, but this is unlikely to happen in the near future. It is more likely that the game will enforce low grass (rather than grass off) globally at some point. For what it's worth 4 is also keeping in mind some minimum graphics and minimizing gameplay impact.
