### ISSUE TITLE
Linux server console not working

### ISSUE THREAD

**Issue by AustinCZ** [SmartlyDressedGames/Unturned-3.x-Community#2087]
Hi, console stopped working after the latest update on linux servers. It doesnt output anything except the initial
```
Set current directory to xyz
Found path: xyz/Unturned_Headless.x86_64

```
./StartUnturnedDedicated -ThreadedConsole -port 27632 -logfile console.log -batchmode -nographics +secureserver/27632

**Comment by SDGNelson** [comment]
In the past there have been problems with Unity redirecting standard input/output, especially on Linux. If you change "-logfile console.log" to "-logfile 2>&1" does it work as expected?

**Comment by AustinCZ** [comment]
Yes, that seems to do the trick :) stdout works, stdin also. It wont output the command you type in, but that is not that of a big problem.

**Comment by rivermigue** [comment]
This seems to be an issue for me too under Ubuntu 18.04 64 bits. I'm starting a sceen console with ./ServerHelper.sh -logfile 2>&1 +secure/Server

And it just starts the screen session with the output mentioned above, stdin doesnt seem to work, I tried to run Shutdown and nothing happened, it just displays the ran command in console as previous mentioned.

**Comment by rivermigue** [comment]
After a bit of testing, it works for me when I add -logfile within quotes like this:

./ServerHelper.sh "-logfile 2>&1" +secureserver/Server1
