### ISSUE TITLE
Gameplay Issues in 3.0 and their solutions aswell as 4.0 community suggestions

### ISSUE THREAD

**Issue by Amket** [SmartlyDressedGames/Unturned-3.x-Community#209]
This is going to be a very long essay that I've made multiple drafts and a youtube video of.
Link to the video is here:https://www.youtube.com/watch?v=Kb7dbCJoxHE&t=202s
(skip to around the 1:47 mark, it's kind of awful at the beginning)
.
.
.
.
Issue #1:
Stamina
.
The first issue I'd like to mention is not a major issue from a developers standpoint, but is massive in terms of how badly it hinders gameplay. The skills and stamina system. The fact is, what turns a lot of people away from joining new servers in unturned is the fact that they have to scavenge a huge map with about 10 seconds of sprint time before waiting 30 seconds for their stamina to replenish. This, and the fact that new players often die from using all their stamina to cross terrain meaning when they are engaged, they're left to die in the open. Here is my solution to both problems, have a walk speed, a jog speed and a run speed. In this theory, The walk and jog speed are infinite, but the run speed has a small limit, used for pushing between different obstacles and into cover when engaged meaning it's a lot easier to get to cover when scavenging. This would also make for interesting gameplay, as players in urban environments would have to try and predict whether or not their enemies can sprint to a cover point.
.
.
.
.
Issue #2:
Starting a new game
.
Unturned 2.0, and even Dead-zone (Roblox Unturned) didn't suffer from this. There is a huge lack of basic civilian weapons like aces and Hawk-Hounds in unturned 3.0, as opposed to 2.0, where I was actually able to not compete against, but defend against better equipped players. Now all there really is to find is some rotten cheese and a green t-shirt. The solution that would work best to combat this would have to be an increase in basic, civilian weapons as well as a buff to mele weapons, meaning that a 200iq player with a kitchen knife can outplay a 12iq player with an ak-47.
.
.
.
.
Issue #3:
Progression
.
In Unturned, once you've gotten a maple-strike and military clothing there is very little to do other than get more maple-strikes and military clothes. There is so little incentive to go on and do more instead of just logging off with a full inventory. My solution to this issue would be to make new weapons craftable by combining old ones. I literally mean it when I say taping two ak-47s together to make them fire simultaneously. It's very hard for me to explain this in a small amount of words, but I give a much better solution in my video at 14:49.
.
.
.
.
Community suggestions:
These are the best community suggestions I could find for 4.0. My YouTube video best explains them:
https://www.youtube.com/watch?v=Kb7dbCJoxHE&t=202s
(Go to 9:18)
.
.
.
.
However, if you are still reluctant to watch the video, I have some, but not all of them in a series of images here.
.
This is my hypothetical concept of how the coalition should operate in 4.0. Look at this location:
![doomsville1](https://user-images.githubusercontent.com/36281390/36000822-25e031d8-0d1c-11e8-8956-d4831134ea51.png)
Now, as we can see here, a large amount of violence has occurred in this location:
![doomsville2](https://user-images.githubusercontent.com/36281390/36000823-26052704-0d1c-11e8-9140-ec8fcb8b3b8e.png)
Hypothetically, these helicopters would fly in via a pre built path. (The soldiers A.I. is explained after this)
![doomsville3](https://user-images.githubusercontent.com/36281390/36000824-263a4efc-0d1c-11e8-916e-f9edb79c212c.png)
Now, once the soldiers have cleared out all player built objects and zombies, they proceed to build a pre-designed base.
![doomsville4](https://user-images.githubusercontent.com/36281390/36000825-26683d80-0d1c-11e8-80d0-10ec2495bf6d.png)
This base now becomes an NPC hub for trade and can be used as shelter for players or PvE against coalition soldiers.
![doomsville5](https://user-images.githubusercontent.com/36281390/36000821-25bb110a-0d1c-11e8-83bc-a88ad3ca148f.png)
.
.
Here is a diagram or "Algorithm" for a PvE coalition soldier A.I. I made:

![nav3](https://user-images.githubusercontent.com/36281390/36000650-7e6af0d2-0d1b-11e8-88fd-1cd42d0a02eb.png)

![nav4](https://user-images.githubusercontent.com/36281390/36000652-7e932106-0d1b-11e8-8a70-b0cbca9a50c9.png)

![nav5](https://user-images.githubusercontent.com/36281390/36000654-7ec838e6-0d1b-11e8-9373-bc4d03398579.png)

![nav6](https://user-images.githubusercontent.com/36281390/36000655-7f148520-0d1b-11e8-9d4d-ee0253941ab3.png)

My main point is that coalition bases already exist in the game, and this would mean that coalition soldiers could make for interesting PvE while players aren't around and provide more co-op options for low population servers. If you want to do anything involving combat on a low pop server, you really can either kill off the other two people on the server and have them never return or fight zombies (which gets very boring, very quickly).

Gonna be honest, I've been sending Nelson this exact message for the past month and a half and can't find the energy to re-write this exact goddamn essay again only for it to be seen by no one. Just watch the video past the 9:18 mark for community suggestions and watch the video from 1:47 for what I have written hear articulated better. I think overall you would enjoy video, although it does begin very slow.

Please reply-

-one of the few, concerned and sensible people who are still giving feedback (or atleast trying to)

**Comment by Trojaner25** [comment]
Please do 4.x requests in SmartlyDressedGames/Unturned-4.x-Community

**Comment by SDGNelson** [comment]
I appreciate/enjoy listening to these sorts of analysis videos - keep it up! Some of these suggestions are not easily feasible e.g. the dynamic Coalition encampments, but good to take into consideration for the long term.
