### ISSUE TITLE
Issue with connecting to Steam Servers.

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2090]
Hey @SDGNelson,
I've noticed quite often the errors; 
_Lost connection to Steam servers because k_EResultServiceUnavailable_
and
_Failed to connect to Steam servers because k_EResultNoConnection, still retrying_ 

on multiple server consoles and when players try to connect they get stuck on queue position 1 and then it reverts back to the default load screen and says you've lost your place in the queue. On one of the servers I am using the startup argument **-NetTransport=SteamNetworking**. 
Could you possibly provide some insight why these issues keep occuring?

**Comment by joeymisfit** [comment]
To add, when looking at client.log locally I see the following;
[2020-11-18 00:12:18] Connection pending verification
[2020-11-18 00:12:18] Authenticating with server --- TicketLength: 252 ProofLength: 964 Hashes: 0
[2020-11-18 00:12:18] Rejected by server (LATE_PENDING) --- Reason: '' Explanation: ''
[2020-11-18 00:12:18] Cancelled auth ticket
[2020-11-18 00:12:56] You lost your place in the queue.

**Comment by SDGNelson** [comment]
Probably the usual Tuesday afternoon maintenance

**Comment by TH3AL3X** [comment]
> Probably the usual Tuesday afternoon maintenance

Aight, https://partner.steamgames.com/doc/api/steam_api
k_EResultServiceUnavailable, 20, The requested service is currently unavailable

**Comment by SDGNelson** [comment]
Following up, I assume it started working again after maintenance ended?

**Comment by Ehclipze** [comment]
I am trying to host a server and it says Failed to connect to Steam servers because k_EResultNoConnection
