### ISSUE TITLE
Server 32 bit systems compatibility

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#2091]
In steamcmd on server installing I got this ERROR.
ERROR! Failed to install app '1110390' (Requires 64bit operating system)
Can I somehow install server for 32 bit system ?

**Comment by TH3AL3X** [comment]
@sSteamCmdForcePlatformBitness 32
If i remember you need to add this parameter to the steamcmd....
Pd: Here you have all parameters for steamcmd: https://github.com/dgibbs64/SteamCMD-Commands-List/blob/master/steamcmd_commands.txt

**Comment by SingleThreadedWorld** [comment]
> @sSteamCmdForcePlatformBitness 32
> If i remember you need to add this parameter to the steamcmd....
> Pd: Here you have all parameters for steamcmd: https://github.com/dgibbs64/SteamCMD-Commands-List/blob/master/steamcmd_commands.txt

I don't think that will work, Unturned Dedicated Server does not have a 32-bit depot.

`Can I somehow install server for 32 bit system ?`
Install 64-bit OS

**Comment by TH3AL3X** [comment]
> > @sSteamCmdForcePlatformBitness 32
> > If i remember you need to add this parameter to the steamcmd....
> > Pd: Here you have all parameters for steamcmd: https://github.com/dgibbs64/SteamCMD-Commands-List/blob/master/steamcmd_commands.txt
> 
> I don't think that will work, Unturned Dedicated Server does not have a 32-bit depot.
> 
> `Can I somehow install server for 32 bit system ?`
> Install 64-bit OS

Idk, but who use 32bits in 2k20....

**Comment by Sl4vP0weR** [comment]
> Idk, but who use 32bits in 2k20....

Notebook

**Comment by Sl4vP0weR** [comment]
> @sSteamCmdForcePlatformBitness 32
bad result

**Comment by TH3AL3X** [comment]
> > @sSteamCmdForcePlatformBitness 32
> +sSteamCmdForcePlatformBitness 32
> bad result

**Comment by Sl4vP0weR** [comment]
> > > @sSteamCmdForcePlatformBitness 32
> > 
> > 
> > bad result
> 
> +sSteamCmdForcePlatformBitness 32

Thats didnt help

**Comment by PandahutMiku** [comment]
Yea as far as I know that command would only force steamcmd to target
32-bit depots. Unturned dedicated server literally only has 64 bit depots
and releases. I'm pretty sure the only way you could get this fixed is if
nelson compiled and released 32 bit versions/depots of unturned dedicated
server or you just upgraded to 64 bit

**Comment by Sl4vP0weR** [comment]
@SDGNelson

**Comment by educatalan02** [comment]
32 Bits is not supported, that's all

**Comment by educatalan02** [comment]
32 Bits has alot of different crashes

**Comment by SDGNelson** [comment]
Miku is correct. The dedicated server is only available for 64-bit.

**Comment by Sl4vP0weR** [comment]
Create 32 BIT SERVER IS POSSIBLE!
1. Remove all RET IL instructions(ignore last) from "Assets.Start" method. 
2. Set dedicated server app id in steam_appid.txt.
3. PROFIT
