### ISSUE TITLE
Nelson It happened again :(

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#2092]
I really dont want to write it here again but I havent even got a response from BattlEye from the last time.
Maybe you remember this issue: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1618
Well it somehow happened again.
Im very busy at work etc. at the moment so I havent played Unturned in the past few months (In fact I last played it on the 17th June).
So Im very supprised and confused that I got another Unturned BattlEye ban again today without even playing for quite some time.

I hope you can help me solve the issue <3
Thanks in advance

**Comment by SDGNelson** [comment]
If you re-open Steam do you get the unbanned notification? There were a few false bans this morning that got reverted already, so it might have already been resolved. Sorry for the trouble. Owch two false bans...

**Comment by Game4Freak** [comment]
Yeah its gone.
Thank you <3

**Comment by TH3AL3X** [comment]
Why you don't use "-insecure" parameter if you're debugging
