### ISSUE TITLE
Too much RAM allocation(?)

### ISSUE THREAD

**Issue by LabodiDavid** [SmartlyDressedGames/Unturned-3.x-Community#2093]
![image](https://user-images.githubusercontent.com/40663270/99800487-b763d900-2b34-11eb-96f9-e996b47606f2.png)
![image](https://user-images.githubusercontent.com/40663270/99800850-4d97ff00-2b35-11eb-8f72-73fa93e3ddec.png)
I think it's too much RAM allocation.
Is it normal for unturned? There is a way to reduce this?
Currently the server is consuming the virtual memory without players.

I know i didn't have too much RAM but i think it's too much allocation, i didn't ever seen this amount of allocation when hosting another game servers.

**Comment by Trojaner** [comment]
This is normal if you have a lot of workshop assets.

**Comment by LabodiDavid** [comment]
> This is normal if you have a lot of workshop assets.

It's a freshly installed server, without rocketmod or any plugin.
