### ISSUE TITLE
Russia Bug - Get into Places (Rocks, Floor, ...)  (probably works on "all" maps)

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#2094]
hello, let me sum up and take up less time.
I was playing on a Russia Map server, and I saw a player leaving an inaccessible place, I was confused and started looking for a "Bug", tried it in several ways and managed to find it, recorded it on the video as I did (without sound, F). But to understand how it worked, I tested it more than once in more than one place and it worked several times, it seems that having -30 ~ 40% of the bed inside somewhere makes it possible for the player to respawn on it.
see the 2 videos to understand better, sorry bad english.
my Nickname: PINGUIN.ZIP

1º - https://youtu.be/rd6fiHqpBcw
2º - https://youtu.be/8WSh0oz9gk8

**Comment by SDGNelson** [comment]
Thanks for the report, however this is why beds cannot be placed on vehicles by default. I only recommend enabling that setting on servers with friends.
