### ISSUE TITLE
New Update Door Issues

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2095]
It seems on the new update, opening doors is impossible. The menu doesn't pop up, even on singleplayer fresh world. On multiplayer it seems the same way.

Probably wasn't updated for new hierachy?

[2020-11-20 12:47:44] NullReferenceException: Object reference not set to an instance of an object
[2020-11-20 12:47:44] SDG.Unturned.InteractableDoor.overlapBox (UnityEngine.BoxCollider boxCollider) (at <fd39285cd1464631a4d037d8dadf2522>:0)
SDG.Unturned.InteractableDoor.checkToggle (Steamworks.CSteamID enemyPlayer, Steamworks.CSteamID enemyGroup) (at <fd39285cd1464631a4d037d8dadf2522>:0)
SDG.Unturned.InteractableDoorHinge.checkUseable () (at <fd39285cd1464631a4d037d8dadf2522>:0)
SDG.Unturned.InteractableDoorHinge.checkHint (SDG.Unturned.EPlayerMessage& message, System.String& text, UnityEngine.Color& color) (at <fd39285cd1464631a4d037d8dadf2522>:0)
SDG.Unturned.PlayerInteract.Update () (at <fd39285cd1464631a4d037d8dadf2522>:0)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5575242/Client.log)

Edit 2: It seems the "Locked" and "Close" GUI is fine, just not opening them.

**Comment by Gsechs** [comment]
Can anyone else confirm before I update my servers?

**Comment by SDGNelson** [comment]
Uh oh! Thanks for the report. You are right that it is a problem with the hierarchy update. Easy fix, but I will wait a short period in case other problems with the hierarchy changes are reported.

**Comment by SDGNelson** [comment]
Looks like vehicle bumper hitboxes and traps (specifically when damaging players) make a similar bad assumption that the hit entity has a parent.

**Comment by PandahutMiku** [comment]
> Uh oh! Thanks for the report. You are right that it is a problem with the hierarchy update. Easy fix, but I will wait a short period in case other problems with the hierarchy changes are reported.

I've been waiting/listening for a bit, but the only issues I've seen reported are the InteractableTrap issues (#2096), Vehicle bumper issues, and the reported door issues. Would be nice if they got patched sooner then later, as they are spamming client/server logs and making it hard to even find other issues.

Otherwise, this might be a good opportunity for door DLC. For $10 USD today buy access back to using doors! Force clans to have an assigned door opener ;p

Some people have reported that they have got better performance. Of course, if you were GPU-bound before, this performance optimization wouldn't help them, but it's still nice!

**Comment by baranmod** [comment]
some issues with UI (buttons on custom UIs not working, UI doesn't disappear etc), but I guess these will have to be fixed plugin/workshop side? Trying to re-export on unity 2019 right now

**Comment by PandahutMiku** [comment]
> some issues with UI (buttons on custom UIs not working, UI doesn't disappear etc), but I guess these will have to be fixed plugin/workshop side? Trying to re-export on unity 2019 right now

For me, everything works fine besides trying to clear the UI.

Using this
`                EffectManager.instance.channel.send("tellEffectClearAll", player.CSteamID(), ESteamPacket.UPDATE_RELIABLE_BUFFER, (object[])Array.Empty<object>());`

**Comment by SDGNelson** [comment]
D'oh the update just finished building and now there is this UI bug.
Those methods were changed because previously all elements in the Effects transform could be destroyed, but now they specifically destroy a registered list and return anything to the pool. Double-checking now

**Comment by SDGNelson** [comment]
The "clear all" method is used in vanilla to reset the debris, blood splatters, ragdolls, etc. between arena rounds. I am surprised to hear that it is being used by plugins on a regular basis, as using it to clear the UI would also cause all effects to be destroyed. Nothing should have changed behavior wise between the old update and this one, so I wonder if you can elaborate more on how it is being used.

In the meantime I will upload the patch because the door and trap stuff is affecting a lot of players

**Comment by PandahutMiku** [comment]
> The "clear all" method is used in vanilla to reset the debris, blood splatters, ragdolls, etc. between arena rounds. I am surprised to hear that it is being used by plugins on a regular basis, as using it to clear the UI would also cause all effects to be destroyed. Nothing should have changed behavior wise between the old update and this one, so I wonder if you can elaborate more on how it is being used.
> 
> In the meantime I will upload the patch because the door and trap stuff is affecting a lot of players

I wouldn't say used by plugins on a regular basis. I was using it for a specific WIP UI for something not released. I was aware of the side effects of it with clearing smoke and such, but they weren't a concern. Was just surprised to see it suddenly stop working for UI.

**Comment by SDGNelson** [comment]
@baranmod when you say UI doesn't disappear, which method are you using?

Will experiment around more with the UI clearing to see what is going on. It might also make sense to add a separate RPC specifically for clearing all UI.

**Comment by baranmod** [comment]
EffectManager.askEffectClearByID

**Comment by jatapa** [comment]
Nelson just going to make sure you meant to update the preview version about 10min ago and not the public version

**Comment by PandahutMiku** [comment]
> @baranmod when you say UI doesn't disappear, which method are you using?
> 
> Will experiment around more with the UI clearing to see what is going on. It might also make sense to add a separate RPC specifically for clearing all UI.

Sorry, not my intention to throw you for a loop mentioning a function no UI devs use. Was more like even the function that is supposed to clear everything doesn't work.

AskEffectClearByID Doesn't seem to work either

i.e

` EffectManager.sendUIEffect(MainInputController.CellPhoneUI, MainInputController.CellPhoneKey, player.CSteamID, true);
            EffectManager.askEffectClearByID(MainInputController.CellPhoneUI, player.CSteamID);`

No errors or anything in log of Client or Server.

And the UI is still on screen. It seems all the other functions work fine (spawning UI, spawning another UI with the same key and having it replace it, buttons, not sure on InputField).

**Comment by SDGNelson** [comment]
@jatapa Yes, each update goes onto the preview branch first for a quick client-server test and then goes live. It should be up now.

Hmm regarding both questions, I wonder if anything in the UI uses a UnityEvent to call Destroy? The reason I wonder is that `GameObjectPool.DestroyAll` currently returns rather than continues (will fix) when a null entry is hit.

I will also try out with the built in effect tests

**Comment by muertoof** [comment]
Yeah, I have a same problem with the my UI.

**Comment by PandahutMiku** [comment]
Running other people in vehicles, landmines, and opening doors do work now.

UI askEffectClearByID remains

**Comment by PandahutMiku** [comment]
Well doors/etc are fixed. Just not askEffectClearByID, #2097 is already made for that specifically anyway.
