### ISSUE TITLE
Level Picture and Map Description for server

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2099]
![image](https://user-images.githubusercontent.com/69295711/99872193-04a58080-2bf1-11eb-94f9-f90c0046e7e4.png) ![image](https://user-images.githubusercontent.com/69295711/99872210-2dc61100-2bf1-11eb-95be-9486f52cfefd.png)

Ok, server has space for Level.png and Description of the map. It's ok with Official maps. But if the map from workshop, I'm a bit confused it appears if player has this map downloaded/in-game only. Server already can accept custom icons and thumbnails by URL.
Maybe there will be a rework about level pic and description to be displayed in server panel somehow without download of the map?

**Comment by SDGNelson** [comment]
As you guessed, that only uses locally available files at the moment. If they are subscribed to it then it will display properly

**Comment by aladairmaxwell** [comment]
But will it be displayed without subscribing in future?

**Comment by SDGNelson** [comment]
Probably not - there is currently no way for the client to recover those details unless it became something the server was responsible for
