### ISSUE TITLE
Unturned FPS Drops/Issues with draw distance and loading bases.

### ISSUE THREAD

**Issue by Glass47** [SmartlyDressedGames/Unturned-3.x-Community#2100]
The way draw distance currently works in Unturned is not the best, it's really not good, if specific server has some big bases or multiple smaller ones and you enter in range where your draw distance has to render them, your game FPS will significantly drop, or it will even freeze your game for split second or more, depending how many bases aka player buildings it has to render. Nelson i must say that you did great job with last update optimizing game. I had 140-200fps on that specific server, now i usually get over 300 to 400 FPS. This rendering bug / issue needs to be fixed, it's destroying game experience insanely. I don't really have low end computer which means anyone with worse CPU/Ram/GPU has higher fps drops which are noticeable and destroying game experience as a shutter or freeze by the reason how bad draw distance works. I hope you can find solution and solve this issue. Best regards to you!

**Comment by PandahutMiku** [comment]
Probably talking about #936
