### ISSUE TITLE
Unturned vehicles flipping bug/glitch

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2102]
https://drive.google.com/file/d/1BVmQu6A_H_odoNgnIDMGf1GpFP88fRCK/view

Hello! Unturned vehicles bug/glitch. I can flip all vehicles without carjack on the server or in singleplayer. So I hope you will respond on it.

**Comment by SDGNelson** [comment]
It's a catch-22 between either players applying odd forces like this, or sometimes being able to walk through vehicles. Ideally the movement code will get rewritten at some point

**Comment by schelchok** [comment]
Can you consider this a bug? Will I get any achievement? I think it's very
seriously bug because I can flip any vehicles without carjack. Thanks for
responding!


сб, 21 нояб. 2020 г. в 22:53, Nelson Sexton <notifications@github.com>:
