### ISSUE TITLE
Text on signs

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2103]
Text isn't formatting on signs and placards correctly since the update
![3](https://user-images.githubusercontent.com/71527679/99891956-833d0500-2c67-11eb-8b95-4dd004829428.png)

**Comment by SDGNelson** [comment]
It looks like this happens if you pad a lot of newlines, but if you have actual text it does not happen. Is there any actual text that causes a problem? The game could trim newlines from the start and end to prevent this.

**Comment by AdamDN** [comment]
I think it's just with new lines, I haven't seen it happen with only text. 
Trimming newlines from the start and end would remove a lot of formatting options though, especially for new players that just want small text and don't understand how to use rich text.

**Comment by SDGNelson** [comment]
Well, judging from the report using newlines as a formatting trick to reduce the font size does not currently work

**Comment by SDGNelson** [comment]
Closing because the start/end trimming was added.
