### ISSUE TITLE
BSOD on Launch

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2104]
Today i tried to launch Unturned and instantly got BSOD with error "KERNEL_SECURITY_CHECK_FAILURE".
I'm absolutely sure that Unturned or BattlEye is the reason because i had no BSODs on my desktop for years.

Some technical info that may be useful

OS: Windows 10 Pro 1909
CPU: AMD FX-4350

upd: after restart game appeared uninstalled, checked 'appmanifest_304930.acf' - it was completely filled with empty bytes

**Comment by TH3AL3X** [comment]
> Today i tried to launch Unturned and instantly got BSOD with error "KERNEL_SECURITY_CHECK_FAILURE".
> 
> I'm absolutely sure that Unturned or BattlEye is the reason because i had no BSODs on my desktop for years.
> 
> 
> 
> Some technical info that may be useful
> 
> 
> 
> OS: Windows 10 Pro 1909
> 
> CPU: AMD FX-4350
> 
> 
> 
> upd: after restart game appeared uninstalled, checked 'appmanifest_304930.acf' - it was completely filled with empty bytes

Idiot question, are you using a modified Windows like patch guard mode, because probably is blocking the kernel, and BE works on kernel

**Comment by iBowie** [comment]
The thing is - i'm not using the patched version of the Windows, and before it worked

**Comment by TH3AL3X** [comment]
> The thing is - i'm not using the patched version of the Windows, and before it worked

Idk, it can be a program or a error of BE, try uninstalling BE and install it again and then restart your computer

**Comment by iBowie** [comment]
looks like the problem is gone, scary nonetheless

**Comment by archie426** [comment]
I've still got this recently - taking a look at the kernel crash dump it is almost definitely related to BattlEye. @iBowie By any chance, do you have any reversing tools installed such as Ghidra, IDA etc?
