### ISSUE TITLE
Horde mode

### ISSUE THREAD

**Issue by molecule31** [SmartlyDressedGames/Unturned-3.x-Community#2105]
Hello Nelson, would you like to know if "Horde mode" development will continue in Unturned 3.0?
Now I am making a map of this type, and I do not like the fact that zombies cannot see you, and can get stuck and not teleport to their original position, as is done in Horde Beacon, if you plan to do something with this mode, please tell me.

**Comment by SDGNelson** [comment]
Sorry, but it is unlikely that there would be any more work on horde mode in 3. It never really got off the ground because it was a low priority, so the base featureset was never finished
