### ISSUE TITLE
Flying Fern on Hawaii

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2106]
![image](https://user-images.githubusercontent.com/69295711/100139103-0779cd00-2ea0-11eb-91db-92f47cffd217.png)
It's fern and it's flying. It is located near road not far from safezone (Unyielding HQ). It is very noticeable.

**Comment by SDGNelson** [comment]
Thanks for the report, however this will be low priority to fix unless I am fixing something else on the Hawaii map
