### ISSUE TITLE
Blizzard button in legacy editor doesn't work

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2107]
I have Can Snow check, I press Blizzard and nothing happens. No settings related to ambience volume in map config. When I spawn blizzard with /weather blizzard it works. 

Storm button works, however.

**Comment by SDGNelson** [comment]
To test this I loaded up the Yukon map, clicked the Blizzard button, and it previewed a blizzard as expected

**Comment by aladairmaxwell** [comment]
I was testing it on custom created maps, not existing ones. It works on Yukon, yes. But not on other maps for some reason. I tried editing Russia, PEI and not only, and nothing happened.

**Comment by SDGNelson** [comment]
Were you within the snow height range?

**Comment by aladairmaxwell** [comment]
Guess snow level was at zero after update on all maps by default, because early snow was working. Sorry for bothering.
