### ISSUE TITLE
[Feature Request] Сhanging prices and quests for NPCs through the server config.

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#2108]
Server developers often encounter disbalanced prices and misbehaving prices, they need to quickly fix this error, but this does not work for them because they need to change the NPC, load the modpack, restart the server, thereby kicking all players from the server. The same is the case with quests. Why don't you do a server side NPC change or just add the ability to change prices and quests on the server side.

We really need this function, please add it.

**Comment by SDGNelson** [comment]
Sorry, but I do not foresee this being added any time soon, so I am closing to reduce the number of active issues.
