### ISSUE TITLE
Linux settings issues

### ISSUE THREAD

**Issue by Varden17** [SmartlyDressedGames/Unturned-3.x-Community#2109]
I found two small bugs in the settings while playing the game on Linux (Manjaro)
1. Scrolling (in the settings etc.) is inverted
2. I'm unable to change stuff like FOV, Volume and inbound voice gain by simply dragging the volume bar. You have to click on the line in order to change it.

**Comment by SDGNelson** [comment]
Was this in the current release, or on the Glazier / uGUI beta branch? If it was the current release then chances are they will be fixed in the Glazier / uGUI update.

**Comment by Varden17** [comment]
It was in the current release. Tried Glazier, and it's working flawlessly there

**Comment by SDGNelson** [comment]
Awesome!
