### ISSUE TITLE
Zombies Failing to Move Using Navmesh

### ISSUE THREAD

**Issue by Shayna82101** [SmartlyDressedGames/Unturned-3.x-Community#2110]
I've been having issues with a custom map I'm making, I've spend alot of time working on making the landscape and towns themselves and the zombies did work in the beginning using the standard navigation meshes, but eventually the navigation mesh in one town stopped working. Zombies would remain still no matter what you did, shooting guns near them, punching them, coming within alert range, etc. The other nav mesh worked just fine, and I looked up tutorials and forum posts online of people who had similar issues and they just deleted all their nav meshes and replaced them as well as the zombie spawns. I did this multiple times, but this failed to yield any results. The only thing that changed was once a zombie moved towards an exploded vehicle, and they will occasionally move a few feet when punched but they won't show movement animations or make the alert sounds. 

After removing the nav mesh for the other area which worked previously, it also began to fail to work. It's really odd, because the nav meshes are baked and I didn't do anything to the zombie spawn files before this started happening, and all I did after was move them from the folder, load the map, unload it, and then put them back in to reset them, but it didn't work. I'm at the end of my rope, and I need to release this map by the first of next month, does anyone have any suggestions?

Thank you so much.

**Comment by SDGNelson** [comment]
If you can either upload the map files here or send them to me by email (nelson@smartlydressedgames.com) I will load it up and take a look - where is this town on the map?

**Comment by Shayna82101** [comment]
I emailed the files to you in an email taglined Navmesh Map failure, there are three nav meshes with the issue on the map, two of them are together in the northwest part of the map, and the third is a small one on it's own in the northeast.

Also, I wanted to say your game is what launched me down my current path of coding and has brought me countless hours of enjoyment, thank you so much

**Comment by SDGNelson** [comment]
Happy to hear you have enjoyed the game and that you are learning coding! Thanks for sending the map files - I was able to replicate the problem. Debugged a little bit, but unsure what is causing it yet. In the meantime it should be fine to continue working on the map, and I will figure this out for the next update.

**Comment by Shayna82101** [comment]
Alright, sorry for taking so long to get back to you on this! Thank you so much for your help, I love making maps for your game and I love the game itself. I'll let you know if the fix works after the update :)

**Comment by SDGNelson** [comment]
The problem was an unbaked navmesh underneath the center of the map. For the next update I have fixed unbaked navmeshes from causing this problem, however the map will need to be re-saved in the new version to apply the fix. Closing, but feel free to comment if there is an issue after the update and I will re-open.

**Comment by Shayna82101** [comment]
Thank you! I can't find the unbaked navmesh to remove in my version of the map, is there any way to do a universal navmesh wipe?

**Comment by SDGNelson** [comment]
Only by deleting the Flags.dat file in the level folder, but I would recommend waiting for the update to avoid breaking anything
