### ISSUE TITLE
Error in NPC asset on Hawaii

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2111]
It doesn't look like much, but still dialogue that is located at "NPCs\Hawaii NPCs\Dialogues\Engineer_Thomas\Engineer_Welcome" has an error in it. Response with index 3 references message with index 3, but there are only 2 messages in this dialogue. It doesn't look like it generates an asset error anywhere, but i noticed it while i was making import function for my NPC Maker.

**Comment by SDGNelson** [comment]
Thanks for the report! I will see about adding an error message for that

**Comment by SDGNelson** [comment]
Added the error message for the next update, as well as the opposite - messages referencing an invalid response.
