### ISSUE TITLE
How would I go about making custom zombie difficulty navigations like in Germany?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2112]
I want to make zombies more difficult in the deadzones, so I used the navigation codes from Germany.
However, I've only recently discovered that those block horde beacon placement, making several NPC quests thereby impossible.
So how would I go about making one of these custom difficulties?

**Comment by SDGNelson** [comment]
Thanks for the report, horde beacons should be placeable by default. Will fix for the next update. In the meantime you can create custom ones by copying the defaults in Assets/Zombie_Difficulty.
