### ISSUE TITLE
Assertion Failed: SDR service thread gave up on lock after waiting 50ms

### ISSUE THREAD

**Issue by ModernMoGamer** [SmartlyDressedGames/Unturned-3.x-Community#2114]
Hi, I'm currently experiencing the following error in console spammed for a few seconds every couple hours.
```/data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 50ms.  This directly adds to delay of processing of network packets!```
While this is happening, The server lags (Ping raises) similar to the server freezing.

I had previously seen this on multiple servers, after a reboot of the machine, only one seems to be having the issue still.
This is same issue as here: https://forum.smartlydressedgames.com/t/assertion-failed-sdr-service-thread-gave-up-on-lock-after-waiting-56ms/16052/4

Running Ubuntu 18.04 using Docker.

Thanks.

**Comment by Trojaner** [comment]
This is not the cause of your lags, but a result of them.

**Comment by TH3AL3X** [comment]
> This is not the cause of your lags, but a result of them.

I'm having this experience with the new SteamNetworking, anyways my server is going to the hell by it self...
