### ISSUE TITLE
Sometimes dropped items goes through floor

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2116]
I noticed that sometimes when you drop some item it goes through floor. By "floor" I mean, ground or even through objects floor. But it doesn't just bug through floor as you can still see the item far away while looking to that spot you drop it at, but you can't reach to pick it. Happened for both, vanilla and modded items.

Someone sent me a video a while ago, will try to find it.

**Comment by SDGNelson** [comment]
What do you mean by:

> But it doesn't just bug through floor as you can still see the item far away while looking to that spot you drop it at

The dropped item is visible through walls? It sounds like the dropped item might be on the viewmodel (first-person arms) layer which would explain why its collision is broken and it is visible through objects, but there should be warnings about that and none of the vanilla items should have that problem - though you mention it happens with vanilla items.

**Comment by SDGNelson** [comment]
Feel free to comment and I will re-open.
