### ISSUE TITLE
I fix right now

### ISSUE THREAD

**Issue by AuD1tek** [SmartlyDressedGames/Unturned-3.x-Community#2117]
![Screenshot_1](https://user-images.githubusercontent.com/41921371/100527816-c4409680-31de-11eb-85d0-d072be4d6f70.png)

**Comment by rube200** [comment]
1st wrong rep
2nd there is no need to "fix" it

**Comment by SDGNelson** [comment]
To clarify, this is in Rocket code, not official Unturned code. My guess is that at the time (~5 years ago?) Sven did not realize the CSteamID struct had a public uint64 field. The "fix" is what the code should have been originally, however I am hesitant to change any Rocket code just for the sake of change. For an objectively cleaner codebase you might want to look at OpenMod.
