### ISSUE TITLE
Another observation while fiddling, probably not an issue.

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2118]
For the past week have been continuing with my fiddling, this time trying to make a custom NPC.
Some snippets:
Character's Asset.dat
ID 60000
Type NPC
Shirt 54918
Pants 54919
Vest 34137
Backpack 34198
Hat 225
Glasses 34261
Has_Christmas_Outfit True
Christmas_Shirt 177
Christmas_Pants 54919
Christmas_Vest 415
Christmas_Backpack 7902
Christmas_Hat 430
Christmas_Glasses 44077
Primary 23964
Secondary 57101
Equipped Primary
Face 0
Beard 6
Hair 2
Color_Skin #F4E6D2
Color_Hair #000000
Pose Crouch

Dialogue 60001

English.dat
Name QuestHouse Master
Character QuestHouse Rex

The first Conversation's asset.dat

Type Dialogue
ID 60001
Messages 2
Message_0_Pages 1
Message_0_Conditions 1
Message_0_Condition_0_Type Flag_Bool
Message_0_Condition_0_ID 60010
Message_0_Condition_0_Value True
Message_0_Condition_0_Logic Equal

Message_1_Pages 1
Message_1_Conditions 1
Message_1_Condition_0_Type Flag_Bool
Message_1_Condition_0_ID 60010
Message_1_Condition_0_Value False
Message_1_Condition_0_Logic Equal
Message_1_Condition_0_Allow_Unset
Message_1_Rewards 1
Message_1_Reward_0_Type Flag_Bool
Message_1_Reward_0_ID 60010
Message_1_Reward_0_Value False

Responses 6
Response_0_Dialogue 60003
Response_0_Conditions 1
Response_0_Condition_0_Type Flag_Bool
Response_0_Condition_0_ID 60010
Response_0_Condition_0_Value True
Response_0_Condition_0_Logic Equal
Response_0_Rewards 1
Response_0_Reward_0_Type Flag_Short
Response_0_Reward_0_ID 60009
Response_0_Reward_0_Value 0
Response_0_Reward_0_Modification Increment

Response_1_Dialogue 60002
Response_1_Conditions 1
Response_1_Condition_0_Type Flag_Bool
Response_1_Condition_0_ID 60010
Response_1_Condition_0_Value False
Response_1_Condition_0_Logic Equal
Response_1_Rewards 1
Response_1_Reward_0_Type Flag_Bool
Response_1_Reward_0_ID 60010
Response_1_Reward_0_Value True

Response_2_Dialogue 60011
Response_2_Conditions 2
Response_2_Condition_0_Type Flag_Bool
Response_2_Condition_0_ID 60010
Response_2_Condition_0_Value True
Response_2_Condition_0_Logic Equal
Response_2_Condition_1_Type Flag_Short
Response_2_Condition_1_ID 60009
Response_2_Condition_1_Value 1
Response_2_Condition_1_Logic Greater_Than_Or_Equal_To

Response_3_Dialogue 60012
Response_3_Conditions 2
Response_3_Condition_0_Type Flag_Bool
Response_3_Condition_0_ID 60010
Response_3_Condition_0_Value True
Response_3_Condition_0_Logic Equal
Response_3_Condition_1_Type Flag_Short
Response_3_Condition_1_ID 60009
Response_3_Condition_1_Value 1
Response_3_Condition_1_Logic Greater_Than_Or_Equal_To

Response_4_Dialogue 60013
Response_4_Conditions 1
Response_4_Condition_0_Type Flag_Bool
Response_4_Condition_0_ID 60010
Response_4_Condition_0_Value True
Response_4_Condition_0_Logic Equal

First conversation's English.dat
Message_0_Page_0 Welcome to the QuestHouse, <name_char> .
Message_1_Page_0 Welcome to the QuestHouse!

Response_0 Are there any quests that I can go on?
Response_1 Hey there, I am <name_char> ! You are...?
Response_2 How much QP do I roughly have?
Response_3 What do you sell?
Response_4 What do you trade with?
Response_5 See you around!

(EDIT1: Gee didn't know github turns ------- border into bold the whole paragraph, it wasn't my intent so I removed it, hope it is still readable)

Assuming that all the other files that aren't shown have the correct flow in them and there are no longer any sort of duplicate IDs between anything, I noticed that the game **simply skips the first line of every file.**
Since the first line are all GUID lines in the asset.dat, they are still working correctly.
However, for the English.dat, what was observed was that everything in every English.dat's first line would be omited.
This led to the NPC only showing the second conversation (The second conversation was the first since it gives the flag), Quests have their Name omited but description stays, etc.
The message would appear as if it weren't there : #Message_0_Page_0
The Quest Name would appear as : #NAME
Also the NPC itself in the editor would appear as #NAME
In game the NPC appears as the name given in the second line.

Not quite sure what I did wrong or was it a quirk of the game version. Every single try perfected the flow more till I realised this was the remaining stumble block (the puzzling observation).

Thanks if anyone read to this point, hope that I will be enlightened to something that I wasn't aware of.

**Comment by Ongjming** [comment]
Placeholder post:
To confirm my speculation I am gonna add this line : //Workabout for the one line erase thingy
to the start of every English.dat.
If it works then whew, if nah, then probably something else I did wrong somewhere.

**Comment by SDGNelson** [comment]
It might be that some old code is not handling a byte order mark correctly, will investigate. If you can attach your actual .dat file that would confirm if there is a BOM on the first line

**Comment by iBowie** [comment]
It definitely is byte order mask, my app generates these files, and they are generated with this BOM-mask in front, so i have to add comment to make it work properly.

**Comment by SDGNelson** [comment]
Should be fixed in the coming update! Some very old (pre-2014?) code which read the file as a byte array has been replaced with a call to `File.ReadAllText`. If there are further issues with this after the update feel free to comment and I will re-open.

**Comment by Ongjming** [comment]
Thanks!
