### ISSUE TITLE
A question about Devkit foliage

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2119]
Why does map's files size becoming so big after using devkit foliage? It's very bad that even simple map start from 50MB. And insane maps go up to 2GB. I don't understand. 

Will maps have normal file size in future or it's impossible?

**Comment by SDGNelson** [comment]
You might be able to save some file size by limiting the foliage to within the playable map borders. Where other games procedurally place the grass on the terrain only, Unturned saves the placement of every individual instance. While this has the tradeoff of file size, it has the benefit of ensuring all players see the exact same cover placement, the grass loading is really fast (as opposed to generating it on the fly), and is consistent on non-terrain surfaces like the grassy mesh objects.
