### ISSUE TITLE
Blacklist it nelson

### ISSUE THREAD

**Issue by zoomy500** [SmartlyDressedGames/Unturned-3.x-Community#212]

**Comment by Kr4ken-9** [comment]
+1

**Comment by zoomy500** [comment]
@SDGNelson

**Comment by DefCon42** [comment]
10/10

**Comment by Tidizzle** [comment]
Im extremely dissapointed. Just so its clear, all of the other commenters in this are cheat developers for "thanking", ill link it so you can check it out yourself. http://ironic.services/

**Comment by SDGNelson** [comment]
Closing issue following DMCA takedown request
