### ISSUE TITLE
Masterbundle not working

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2120]
I encountered this problem when I just masterbundled my project the other day. That time, I was using what seems to be an older version of the masterbundle tool & an older project package. It gave me an error that all of the items in-game has their game object missing.

So I imported what I assume is the newer version of the project package straight from the game files, & all of this was in a new Unity project as well. So this should fix the problem right? Well, when I masterbundled my project again with the new package, it still does not work, giving me the same error wherein every item has a missing game object.

All this was happening in Unity 2019.4.15f1. Does anyone know the solution or an idea on why this is happening?

**Comment by SDGNelson** [comment]
The game is updating from 14f1 to 16f1 today, so your 15f1 asset bundle should work properly after the update.
