### ISSUE TITLE
Bug with UI related with Alt Tabbing

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2121]
If you hold left mouse over an element and then Alt + Tab the game, it will stay in "clicked" state
![image](https://user-images.githubusercontent.com/31174978/101193824-f2125900-367e-11eb-943d-e1860bb2892c.png)

**Comment by SDGNelson** [comment]
Thanks for the report. This would be a bug with uGUI, sigh. I will clear the button focus when the application loses focus for the next update/patch.

**Comment by SDGNelson** [comment]
Unfortunately there does not seem to be a straightforward way to workaround this, but it is not a big deal anyway
