### ISSUE TITLE
Server list headers can be misaligned by 30 pixels

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2122]
Favorite servers are not aligned with top line
![image](https://user-images.githubusercontent.com/31174978/101194364-b926b400-367f-11eb-93a6-5f7e85d0eb66.png)

**Comment by iBowie** [comment]
Same when no servers are found
![image](https://user-images.githubusercontent.com/31174978/101194470-dd829080-367f-11eb-9ec1-017b31bb47c3.png)

**Comment by iBowie** [comment]
Same for LAN
![image](https://user-images.githubusercontent.com/31174978/101194690-233f5900-3680-11eb-9621-8fb448147ac0.png)

**Comment by SDGNelson** [comment]
Renamed because it was a little overdramatic. Will fix. In the old UI the lists would not expand when the scrollbar was hidden, so it looks like this case was missed when fixing those up.

**Comment by SDGNelson** [comment]
Fixed for the .2 patch tomorrow morning
