### ISSUE TITLE
No margins in crafting menu

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2124]
It is indeed at least inconsistency because skills and player list have margins
![image](https://user-images.githubusercontent.com/31174978/101195334-166f3500-3681-11eb-9b72-306f676d4e2d.png)

**Comment by SDGNelson** [comment]
This is because the crafting list pools the visible buttons now, however the inconsistency is a fair point. Will add support for padding between entries.

**Comment by iBowie** [comment]
It's also worth noticing that "Max" and "Craft" buttons have different text color

**Comment by SDGNelson** [comment]
Changed for the .2 patch planned for tomorrow morning
