### ISSUE TITLE
Text selects when you hit Enter in chat

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2129]
![glitch](https://user-images.githubusercontent.com/31174978/101196088-1c194a80-3682-11eb-83ab-a14221ca9769.gif)

**Comment by SDGNelson** [comment]
That does appear to be the case, however is there anything bad about that?

**Comment by iBowie** [comment]
Nothing, just kind of irritating to see this. Nothing more than this.

**Comment by SDGNelson** [comment]
Will see about preventing that, but low priority.

**Comment by SDGNelson** [comment]
Fixed for the .2 patch planned for tomorrow morning
