### ISSUE TITLE
Sometimes when you open inventory scoping animation repeats

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2132]
Most certainly not related to last update, if you hold RMB, open Inventory, release RMB and then close inventory, animation will repeat itself.
https://www.youtube.com/watch?v=qrEi2oPKYR4

**Comment by SDGNelson** [comment]
Will investigate for one of the updates after these UI bugs are fixed.

**Comment by SDGNelson** [comment]
Tried with both hold and toggle aim modes in a few scenarios but was unable to replicate it. Perhaps it was related to the UI stuff. If you know a way to reproduce it feel free to comment and I will re-open.
