### ISSUE TITLE
Plugin Widget Modal - Cursor displaying

### ISSUE THREAD

**Issue by FillipoPL** [SmartlyDressedGames/Unturned-3.x-Community#2133]
Cursor displays below the widget

**Comment by SDGNelson** [comment]
Interesting case. The cursor is on the same canvas ZOrder as the game canvas. I will add an override canvas for the cursor with a high ZOrder so that it shows above plugin UIs with high ZOrders.

**Comment by SDGNelson** [comment]
Fixed for .1 patch this afternoon
