### ISSUE TITLE
Rich Text in chat don't work sometimes

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2134]
Original line:
![original](https://user-images.githubusercontent.com/31174978/101197268-b4fc9580-3683-11eb-84ab-09edfdca69b8.png)

Formatted result:
![result](https://user-images.githubusercontent.com/31174978/101197280-b928b300-3683-11eb-8728-0ac75d9aa135.png)

I think it's related to cyan color that was valid before the update, but now it doesn't seem to be the case.

**Comment by PandahutMiku** [comment]
It looks like chat is now using TMP and all of its rich text stuff, the same system signs now use

**Comment by SDGNelson** [comment]
Miku is correct that TMP has slightly different markup. I would encourage using <color=#xxxxxx>in case Unity changes which color names are supported again, and the game uses that style as well.
