### ISSUE TITLE
Unicode no longer recognized by rich text

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2137]
Not a major issue, but it worked prior to the update
![image](https://user-images.githubusercontent.com/71527679/101198859-0002b280-365c-11eb-9085-185b27fab0f8.png)
![image](https://user-images.githubusercontent.com/71527679/101198804-f11c0000-365b-11eb-942e-588e091c94a7.png)

**Comment by SDGNelson** [comment]
With IMGUI the game used Unity's built-in Arial font, whereas now it uses TMP Liberation Sans + Google Noto CJK. I guess the fallbacks do not have some symbol characters like that. Low priority to add symbol fallbacks however.
