### ISSUE TITLE
Plugin Hotkeys triggering when typing inside of UIs

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2139]
Plugin hotkeys are firing when editing signs or typing inside of the chat box, or inside of any typing UI (crafting interface, etc), fires even when typing inside of effect text boxes.
(i.e setup UI to spawn off Plugin Hotkey #1 - ',', hit , when trying to type a sentence, opens UI)

**Comment by iBowie** [comment]
Related to #2125

**Comment by SDGNelson** [comment]
Should be fixed in the .1 patch later this afternoon
