### ISSUE TITLE
tellChat: color parameter is ignored on rich = true

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#214]
Chat is just a sad gray on player related modes, and green on alert

**Comment by SDGNelson** [comment]
Those messages could get wrapped in a <color=colorparam> </color> tag, but that may conflict with inner color tags. All of the rich text in the game defaults to the medium gray color.

**Comment by Trojaner25** [comment]
Isn't it possible to change that "defaulted" color to the specified color?

**Comment by SDGNelson** [comment]
Yeah true actually - wasn't thinking, haven't touched that code in years. Will open another issue for that.
