### ISSUE TITLE
Flicker/artifact when chat window open during screen updates

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2140]
Title says it all. Hit J, K, or L to chat. As screen updates occur the FPS, chat, mouse cursor and menu flash with a combination of white or black bounding boxes.

**Comment by PandahutMiku** [comment]
I think that's related to #2127. It's really odd/random though.

**Comment by WCPistolPete** [comment]
Yes and no. Maybe. Just had more artifact. Got a screenshot at the moment of the crash.
[Crash_2020-12-04_204816294.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5645435/Crash_2020-12-04_204816294.zip)

![Artifact](https://user-images.githubusercontent.com/53093137/101214272-c1fc9300-3649-11eb-9d0f-739357e4d8c8.jpg)

**Comment by WCPistolPete** [comment]
All of this started with the upgrade to Unity2019. uGUI update did not help.

**Comment by SDGNelson** [comment]
Since the artifacts have persisted despite workarounds I am going to update the IMGUI implementation with support for some of the newer features (e.g. right now the IMGUI implementation scroll rects are broken), and support IMGUI as a fallback.
