### ISSUE TITLE
Random white images appearing(UI bug)

### ISSUE THREAD

**Issue by Pablo8241** [SmartlyDressedGames/Unturned-3.x-Community#2141]
Whenever I hover over a button, spam the esc button or to open and close inventory, sometimes these white images appear for a split second and then disappear. Everytime I do it it's a different image.
![image](https://user-images.githubusercontent.com/62928442/101200530-19612a00-366f-11eb-8d80-8e7942b0dc6f.png)
![image](https://user-images.githubusercontent.com/62928442/101200622-3990e900-366f-11eb-8404-88fc865cefed.png)
![image](https://user-images.githubusercontent.com/62928442/101200707-5b8a6b80-366f-11eb-9d1b-c01de8efd53a.png)

**Comment by PandahutMiku** [comment]
I think that's related to #2127. It's really odd/random though.

**Comment by Pablo8241** [comment]
Oh yeah, I guess it is.

**Comment by SDGNelson** [comment]
After investigating I think it is this Unity bug from 2015-present... sigh: https://forum.unity.com/threads/5-3-elements-in-the-ui-flicker-between-different-sprites.373098/
Will experiment with workarounds.

**Comment by SDGNelson** [comment]
I have put together some speculative fixes for the .2 patch tomorrow morning, so fingers crossed 🤞

**Comment by PandahutMiku** [comment]
> I have put together some speculative fixes for the .2 patch tomorrow morning, so fingers crossed 🤞

This issue still exists it seems, multiple people still reporting it after patch. Here's a video if that helps:


![issue](https://user-images.githubusercontent.com/17209937/101261732-609af980-3707-11eb-8124-07f0baadc26e.gif)
Asked them for their client.log as well, will update if they send it, not sure if that's needed though.

**Comment by SDGNelson** [comment]
Thanks for the gif Miku. It looks like that might be the grid one, so hopefully the random sprites one in the OP is fixed. I have two more ideas/speculative fixes for workarounds which I will do for the next patch

**Comment by SDGNelson** [comment]
Since the artifacts have persisted despite workarounds I am going to update the IMGUI implementation with support for some of the newer features (e.g. right now the IMGUI implementation scroll rects are broken), and support IMGUI as a fallback.

**Comment by PandahutMiku** [comment]
> Since the artifacts have persisted despite workarounds I am going to update the IMGUI implementation with support for some of the newer features (e.g. right now the IMGUI implementation scroll rects are broken), and support IMGUI as a fallback.

Do you still want reports or where they are happening or no?

One right now I know of is with opening the map:
![Flash Gif](https://user-images.githubusercontent.com/17209937/101969461-6ce4f200-3bf2-11eb-8958-bdde52d7526a.gif)

**Comment by SDGNelson** [comment]
@PandahutMiku usually I would appreciate more reports (thanks!), but since there are no more known workarounds it is kind of pointless for the meantime. Until there is an official fix from Unity the game's solution will be to support IMGUI and uGUI.
