### ISSUE TITLE
Performance issues after todays update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2142]
Reported by multiple players. FPS dropped from 160 to 100~. Personally, for me it also dropped (had a pretty stable 144fps on vsync, now it dropping to 120-100). Also, some players crashing when opening map.

**Comment by FillipoPL** [comment]
Related to #2125 and #2135

**Comment by PandahutMiku** [comment]
It would probably be helpful to get some more info about the users (i.e Operating system and such). I've seen a few people saying they get better performance now on mac, but the same performance on Windows.

**Comment by baranmod** [comment]
Well, I am on Win 10, 5800x ryzen/3080/32GB RAM. And I am seeing a performance drop for around 100 fps if we talking about vsync disabled. Other player systems: from intel pentium G4560 to I9-9900k - facing same issues

**Comment by iBowie** [comment]
FPS also drops when you just open the map
In my case from 60 to 30 with vsync on

**Comment by baranmod** [comment]
could it be related to teammates icons on map? I mean, when I turn on spectating (shift + f7), FPS goes from 300~ to 100~. FPS also drops when you got lots of teammates. Thats been happening since player icons in spectator mode became a thing but now it seems to drop even more.

**Comment by SDGNelson** [comment]
Are you still experiencing poor performance after the .1 patch? I suspect a big part of it was the error log spam

**Comment by baranmod** [comment]
Just questioned some players who reported it earlier - still facing the same issue (drop by 20-40 fps~). For me, drop is a bit lower I believe (hard to measure when having 300-400) but opening map/inventory/player list - freezes game for a second.

**Comment by SDGNelson** [comment]
Makes sense that it would be lower for some players because uGUI does a lot more stuff that we disabled for IMGUI (e.g. layout). IMGUI generated a ton of garbage every frame leading to expensive GC, so it may tradeoff for some players. The hitch opening some menus is because there is overhead to create the uGUI components. Considering pooling the GOs or revising those menus, but that will be a future update.

**Comment by SDGNelson** [comment]
Closing this issue, but for feel free to open new ones for specific issues. There have been quite a few optimizations for #2203
