### ISSUE TITLE
Option not to fade out text

### ISSUE THREAD

**Issue by SvenDingens** [SmartlyDressedGames/Unturned-3.x-Community#2144]
Chat is disappearing despite the "true" in the config.json 

"Chat_Always_Use_Rich_Text": true,

**Comment by PandahutMiku** [comment]
I believe one of the perks of the new UI was that even Rich Text can fade away now without issue, hence why even forcing stuff to all be rich text, doesn't stop it from fading.

**Comment by SDGNelson** [comment]
Miku is correct that rich text fade out is supported now.

**Comment by SvenDingens** [comment]
Is there a way to have the chat permanent again? Our server and the players liked that a lot.

**Comment by SDGNelson** [comment]
Hmm okay sure, I will do it for one of the next updates (not a priority for the .1 patch though)

**Comment by SvenDingens** [comment]
Thanks man!

**Comment by SDGNelson** [comment]
Added an Enable_Fade_Out preference to the .2 patch for tomorrow morning, defaults to true because I suspect most players want it

**Comment by SvenDingens** [comment]
I'm sorry Nelson, I can't find the Enable_Fade_Out in the config.json. Where do I find it?

**Comment by PandahutMiku** [comment]
It's a client setting in Preferences.json, not Config.json. I.e configurable by clients, not servers. It defaults to true (i.e fade out by default).

**Comment by SvenDingens** [comment]
Thanks!
