### ISSUE TITLE
Multiple selection in groups

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2147]
If you hover over "Reset" or "Edit" buttons textbox also selects
![image](https://user-images.githubusercontent.com/31174978/101205861-0f9bee80-3690-11eb-9396-a7b7fa8850b9.png)

**Comment by iBowie** [comment]
It's also misaligned

**Comment by iBowie** [comment]
Also for player list

**Comment by SDGNelson** [comment]
Thanks for the report. Will fix, but not in the .1 patch

**Comment by SDGNelson** [comment]
Fixed for the .2 patch planned for tomorrow morning
