### ISSUE TITLE
rich text doesn't work

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#215]
e.g.
`<b>asdasf</b>` will just show a gray `<b>asdasf</b>` in chat

Also related to #214 

(only tested with EChatMode set to player messages)

Edit:
On alert messages it shows green.
Some examples provided by AppleJuice:
```cs
UnturnedChat.Say(caller, "<b>b1g meme</b>", true);
(args: player, message, isRich; EChatMode is Alert by default) 
```
![](https://i.imgur.com/pRWqnR5.png)

**Comment by SDGNelson** [comment]
Judging by the green text those messages aren't getting sent as rich text. UnturnedChat isn't an official class and probably has to be updated to pass the bIsRichText parameter.

**Comment by Trojaner25** [comment]
Requesting re-open since the bIsRichText parameter gets actually sent. (UnturnedChat is from RocketMod and it was updated to support rich text)
@SDGNelson

**Comment by SDGNelson** [comment]
If it were getting sent then the chat would be a medium gray color. Have you personally tried the rich text feature? (It looks like you posted a lot of reports by AppleJuice which turned out to be incorrect.)

**Comment by Trojaner25** [comment]
Yes, I tested this myself with the tellChat SteamCall getting called directly
