### ISSUE TITLE
Some menus are opening with lag

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2150]
I noticed singeplayer config and some crafting menus, wasn't the case before the update

**Comment by SDGNelson** [comment]
The hitch opening some menus is because there is overhead to create the uGUI components. Considering pooling the GOs or revising those menus, but that will be a future update.

**Comment by FalkenJr** [comment]
Legacy map editor is probably the worst case so far - in my case doing anything with the object menu other than scrolling causes massive hitches (changing filters, hiding UI)
In one case hiding the UI completely crashed my game, though output logs didn't show anything of note

**Comment by SDGNelson** [comment]
Fair point about the objects list @FalkenJr - gotten several emails about that overnight and will patch for this morning

**Comment by SDGNelson** [comment]
Important cases (e.g. crafting and editor) should be sorted out by now. Singleplayer config menu is unlikely to change however.
