### ISSUE TITLE
Blowtorch Broke After Update?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2153]
I had a few reports from a few server owners and dev's about the blowtorch having issues so I thought I'd open up an issue about it. Basically when you equip a blowtorch there is a delay before it picks it up under crafting and if you have two in your inventory for some of the crafting it says missing. Attached is a screenshot, which hopefully explains what I mean.
![blowtorchwut](https://user-images.githubusercontent.com/20868143/101224898-d38f6c00-3644-11eb-9e70-f7d8adc320b6.jpeg)

**Comment by educatalan02** [comment]
Try no equipping the Blowtorch

**Comment by joeymisfit** [comment]
> Try no equipping the Blowtorch

I tried that just now and it's still the same thing it shows for one item and not the other, so somethings bugged/broken somewhere.
![blowtorchwut2](https://user-images.githubusercontent.com/20868143/101225307-f706e680-3645-11eb-87a9-9c02741224df.jpeg)

**Comment by SDGNelson** [comment]
Thanks for the report. I think this is related to #2151, will fix.

**Comment by SDGNelson** [comment]
Fixed for the .2 patch tomorrow morning
