### ISSUE TITLE
Bones don't heal in all these ways

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#2154]
Hello, bones don't heal in all these ways:

Player.life.tellBroken(Provider.server, false);
Player.life.tellBroken(p.CSteamID, false);
Player.life.channel.send("tellBroken", ESteamCall.OWNER, ESteamPacket.UPDATE_RELIABLE_BUFFER, new object[]
{
false
});
Player.life.serverSetLegsBroken(false);

**Comment by SDGNelson** [comment]
`life.serverSetLegsBroken(false);` would be the correct way to go. Are you sure your code is being executed?

**Comment by Fruten** [comment]
By the way, DamagePlayerHandler-should allow = false, but the bones keep breaking without damage.

**Comment by SDGNelson** [comment]
@Fruten in what context? They would still break from fall damage, but if shouldAllow is false then no damage is dealt.

**Comment by Fruten** [comment]
> `life.serverSetLegsBroken(false);` would be the correct way to go. Are you sure your code is being executed?

The player loses the icon and can run on the client, but the server teleports when he jumps and runs back.

**Comment by SDGNelson** [comment]
Sounds like something else on the server is re-breaking their legs, and maybe without calling the RPC properly

**Comment by Fruten** [comment]
> Sounds like something else on the server is re-breaking their legs, and maybe without calling the RPC properly

But it was tested on 2 different servers and 2 different clients. With and without plugins.

**Comment by DiFFoZ** [comment]
Just tested with this code and it works
```
await UniTask.SwitchToMainThread();
            var user = (UnturnedUser)Context.Actor;
            user.Player.Player.life.serverSetLegsBroken(true);
            await UniTask.Delay(2500);
            user.Player.Player.life.serverSetLegsBroken(false);
            return;
```

**Comment by Fruten** [comment]
I think it has to do with events in rocketmod because they only process the trigger send event.  So, can you add a broken bone delegate with the next update or make a broken bone through the delegate request damage parameters?

**Comment by DiFFoZ** [comment]
You can use Harmony patch or the best option that move to OpenMod

**Comment by Fruten** [comment]
> You can use Harmony patch or the best option that move to OpenMod

My clients use only rocketmod. And Harmony may not be used if you can use the standard hooks. And the hooks are not the best solution.
