### ISSUE TITLE
Game stopped loading when reloading assets

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2159]
I press Page Up button, I wait and game stopped loading at `Loading miscellaneous...` stage. I can move cursor, but nothing more. I have to restart the game then. What's wrong?

**Comment by SDGNelson** [comment]
Double-checked and it may have been inadvertently fixed by one of the patches since then. Feel free to comment if it's still happening and I'll re-open

**Comment by aladairmaxwell** [comment]
This problem still exist.
