### ISSUE TITLE
Vanilla welcome messages don't work

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#216]
They apparently are missing the "rich" bool parameter, and are showing wrong encoded messages instead.

(Welcome messages defined in Commands.dat)

Reported by: AppleJuice

**Comment by ExtraConcentratedJuice** [comment]
This was an issue with my server's installation, not Unturned. I had renamed Unturned.exe (BattleEye keeps my game open when I'm running the server as Unturned.exe) and the corresponding Unturned_Data folder to something else and the server didn't update properly, welcome messages worked as expected after I properly updated my server. Should probably close this issue
