### ISSUE TITLE
Right-click on mouse isn’t working 

### ISSUE THREAD

**Issue by Rosibles** [SmartlyDressedGames/Unturned-3.x-Community#2161]
My right click on my mouse isn’t working. Updated my game and had this issue and was wondering why? This is only happening in unturned and nothing else. Was playing yesterday in the morning and everything was working fine. I’m use to right clicking to drop things in my inventory.

**Comment by SDGNelson** [comment]
In last week's update I restored right-click functionality to some buttons (e.g. right-click while dragging cancels), but if there is a wider issue with right-click in the UI there will be an option to use IMGUI (old hud) in tomorrow's update.
