### ISSUE TITLE
UI Effect (idea for buttons)

### ISSUE THREAD

**Issue by Foks132** [SmartlyDressedGames/Unturned-3.x-Community#2165]
Hi!
How can I add my script for alpha channels to customize the UI effect button?

I suggest adding something like this to the game so that modders can build the UI.
![Снимок](https://user-images.githubusercontent.com/54231406/101247305-b2a94280-373a-11eb-85a3-99fd49d32a64.PNG)
![Снимок3](https://user-images.githubusercontent.com/54231406/101247336-edab7600-373a-11eb-9835-15b4fe67f120.PNG)
![Снимок2](https://user-images.githubusercontent.com/54231406/101247339-f1d79380-373a-11eb-8669-045906dcc4f9.PNG)

**Comment by Foks132** [comment]
I will add: this script changes the area of ​​the button click (so that the click area is on the whole image, not just on the square of the square button)

**Comment by SDGNelson** [comment]
No current/planned way to support this sorry
