### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by Buldozeris** [SmartlyDressedGames/Unturned-3.x-Community#2166]
So far only negative. Drop of fps by ~30%, stutters, freezes on opening lockers, map, inventory. Fonts terrible. Layout terrible.  Those freezes sometimes cause game crash. I went from ~150 fps to 110 right after update. Friends having same problem, those with weak pc now crashing/freezing. Also random flashing on opening inventory. Previous hud was way better - opinion of majority. Well, only one good thing - smaller character, so you can better see it while you have opened inventory. Now i have lower fps than i had before fps boost update. Reverse it.

**Comment by LuisDavid1198** [comment]
Previous hud was way better yes

**Comment by SDGNelson** [comment]
Issues described in the OP should be fixed from the patches/updates

Regarding the flickering however: workarounds did not resolve it, so IMGUI (old HUD) support is being restored in tomorrow's update until there is a fix from Unity
