### ISSUE TITLE
Game after the update.

### ISSUE THREAD

**Issue by matt5782** [SmartlyDressedGames/Unturned-3.x-Community#2167]
After the updates yesterday,I've encountered couple of problems. 
1. My fps dropped from 100 to 60 and when I open lockers or anything it drops to 7
2. U can't loot with f and it takes an eternity to right click stuff or scroll down, also when u decide to change the ui scale it doesn't apply.
3. My guns in-game don't shoot sometimes and they glitch for some reason.
4. The font chat and ui itself is terrible.
5.when I go through doorways half of the time I can't go through and I smget stuck into the wall.
Please just fix the game asap, and if possible, reverse the patches and updates from yesterday. Sincerely a person who has played and enjoyed your game since it first came out.

**Comment by mcdiggle** [comment]
Going back to the older version  would mean going back to stuff that unity has bot rly supporter for years just wait for stuff to be fixed and tweaked and you will get used to the ui in no time

**Comment by SDGNelson** [comment]
Issues described in the OP should be resolved from the patches/updates
