### ISSUE TITLE
Horizontal scroll bar is missing in storages

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2173]
![image](https://user-images.githubusercontent.com/14231707/101260522-5396fe00-3739-11eb-9004-5ff0d4380405.png)

**Comment by baranmod** [comment]
same with other storages (plugin side)

**Comment by PandahutMiku** [comment]
It's definitely gone, and lower resolution players can no longer scroll.

A workaround, for now, is to go to a lower resolution where the storage is below the clothing instead of to the right.

No errors in client.log

You can replicate this on 1600x900 if you want an exact resolution.

**Comment by baranmod** [comment]
yeah, another temp solution is to scale down UI a bit

**Comment by SDGNelson** [comment]
Explanation here https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2123#issuecomment-739119909

Might sort out a workaround this week (before the 12th), but it will be messy.

**Comment by PandahutMiku** [comment]
> Explanation here [#2123 (comment)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2123#issuecomment-739119909)
> 
> Might sort out a workaround this week (before the 12th), but it will be messy.

Opps, I didn't see you mentioning that it would be broken in that post.

It would be much less of an issue if not for modded servers loving to have huge lockers and storage. I would say a large percentage of modded servers use large modded storage containers, hence why this was reported so fast and repeatedly. On Vanilla it happens rarely as you said.

**Comment by SDGNelson** [comment]
Thought about it more: easier solution is to have a horizontal scrollbar per-container which works around the issue, and better for moving items between containers than the old way too

**Comment by SDGNelson** [comment]
Resolved for the next update
