### ISSUE TITLE
Issue with minimap

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2175]
![image](https://user-images.githubusercontent.com/69295711/101261231-b9d64d80-3746-11eb-8cb7-d2d6dde33a38.png)

I have 2560x1440 resolution screen. This happens. This is the default stage of map's zoom. It looks like this.

![image](https://user-images.githubusercontent.com/69295711/101261285-28b3a680-3747-11eb-95e4-
f68e516be586.png)

Other stages looks fine.

Fully zoomed out looks normal too.

![image](https://user-images.githubusercontent.com/69295711/101261319-6adce800-3747-11eb-8ae6-25736cb93cd9.png)

**Comment by SDGNelson** [comment]
Will think about what to do about this, hmm...

**Comment by aladairmaxwell** [comment]
Well, after update the problem still exist. I can even see secret locations by it. It is very annoying to see. 
![image](https://user-images.githubusercontent.com/69295711/101942324-678ba580-3bfa-11eb-9726-5da8b0d32ca5.png)

**Comment by SDGNelson** [comment]
Did not get to it for today's update, but I do have a plan and will mark this as "next update"
