### ISSUE TITLE
Character in inventory is too big

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2176]
This boy looks too big for the frame on 2560x1440 screen resolution. He a bit is out of bounds. That doesn't look well and annoy a lot.
![image](https://user-images.githubusercontent.com/69295711/101261418-16863800-3748-11eb-804b-343559f120ac.png)

**Comment by Tairiku-Ookami** [comment]
Mine looks fine

**Comment by baranmod** [comment]
I think smaller character before the .2 patch looked good as you could see whole character, especially if some modded (thick) items are equipped

**Comment by SDGNelson** [comment]
Prior to the uGUI update the character preview had a max height in pixels depending on the render texture height. uGUI does not have a straightforward way to clamp the height however, so I decided to fit it in that space with some extra padding on the sides.

Some players felt that was too small, so the extra padding was change to 200% of the background which does make it noticeably expand outside the box on tall displays like yours. Clicks should respect the depth of the inventory however.

Eventually it would be nice for that part of the inventory to scale horizontally better.
