### ISSUE TITLE
Craft all is gone

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2177]
The Craft and Craft all buttons are gone on each crafting recipe

**Comment by Tairiku-Ookami** [comment]
![image](https://user-images.githubusercontent.com/75531507/101261997-da7bb480-3700-11eb-8439-8cb431d1b3de.png)

**Comment by SDGNelson** [comment]
This is how it was 2014-2018, you can hold CTRL to craft all
