### ISSUE TITLE
Still cant swap items.

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2179]
You still cant swap items in inventory. Reverting might be the best option.

**Comment by SDGNelson** [comment]
Are you sure you were on the .2 patch?

**Comment by Tairiku-Ookami** [comment]
yep I still cant swap

**Comment by SDGNelson** [comment]
Hmm... next time it happens could you take a screenshot please? Then I will try recreating with the same layout.

**Comment by SDGNelson** [comment]
I notice you closed this - is it working properly for you? If there is still a bug I definitely want to sort it out
