### ISSUE TITLE
Update Loading Screen Image

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#218]
In my opinion, a new game loading screen image replacing the one image taken way back long ago, would be a good effort to keep Unturned 3 fresh a little bit longer. Now that Unturned has the new trees and more graphics options, this should have been done before. Just a recommendation :D

**Comment by SDGNelson** [comment]
The screenshot contest brought with it quite a few new loading images, but I kept the original around because I like seeing how far the game's come every once in a while when it's randomly picked. :)
