### ISSUE TITLE
Despawned item icon stuck to cursor.

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2180]
If an item despawns while moving to inventory, its icon remains stuck on the cursor.
![20201205115815_1](https://user-images.githubusercontent.com/53093137/101263018-61845900-3710-11eb-9c6a-2bd90f62a528.jpg)
![20201205115845_1](https://user-images.githubusercontent.com/53093137/101263020-634e1c80-3710-11eb-9959-a3f8948d6bae.jpg)

**Comment by SDGNelson** [comment]
Thanks for the report, will fix

**Comment by SDGNelson** [comment]
I believe the related cases are fixed for the next update, but if it happens again and you can attach the Client.log that would be helpful for making sure
