### ISSUE TITLE
Ctrl issue

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2182]
Can't do quick action with Ctrl as fast dequip in Inventory or erase whole word using Ctrl + Backspace in chat.

**Comment by SDGNelson** [comment]
To double-check that we are on the same page: when I ctrl+leftclick the equipped weapon it drops, and when I ctrl+rightclick it dequips. Is it working differently for you?

**Comment by aladairmaxwell** [comment]
I'm talking about menu inventory, with cosmetics. Also there are no animations like leftclick for rightclick.

**Comment by SDGNelson** [comment]
Oh I see thank you, will fix

**Comment by SDGNelson** [comment]
It looks like this does actually work properly, so I assume this is related to your other issue where your keys were not bound how you thought they were
