### ISSUE TITLE
Crashing vehicles has a chance to cause softlock? 

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2183]
I've only seen it since the updates, but I can only recreate it on 1 of my servers. Anyone else experiencing this?
https://imgur.com/a/9wkPzTo

**Comment by SDGNelson** [comment]
From the video it looks like you got teleported off into space. There was a bug fixed related to dying in exploding vehicles that happened most often with jets earlier this year, but that seems unrelated. At the time of your report I tried reproducing but no luck. If you notice a pattern or it is consistently happening feel free to comment and I will re-open.
