### ISSUE TITLE
Words cut

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2184]
If we send a long message in chat window:
`balabala1 balabala2 balabala3 balabala4 balabala5 balabala6 balabala7 balabala8 balabala9 balabala10`
It will automatically split to two lines.
But after HUD updated, It just abandoned words, if we chat with Chinese:
`测试文字1 测试文字2 测试文字3 测试文字4 测试文字5 测试文字6 测试文字7 测试文字8 测试文字9 测试文字10`

![p1](https://user-images.githubusercontent.com/64722485/101276032-12f4be80-37e5-11eb-8604-622ecdb29bca.png)

`Broadcast` command and Rocket API `UnturnedChat.Say()` are also running into this issue.

**Comment by SDGNelson** [comment]
Thank you for the report, and for the example text. This is probably because the Chinese characters are slightly taller and getting truncated. I will see if increasing the vertical padding slightly fixes this for the next patch

**Comment by SDGNelson** [comment]
Fixed for the next update
