### ISSUE TITLE
Can't use Shift for fast skill upgrade

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2188]
Before update I could use Shift + LMB to instantly upgrade max skill. Now I can't, I have to use Ctrl instead.

**Comment by mcdiggle** [comment]
Think it has always been ctrl

**Comment by SDGNelson** [comment]
mcdiggle is correct that it should use your "Quick Action" key. Do you have quick action bound to Ctrl instead of Shift?

**Comment by aladairmaxwell** [comment]
No, I always had Shift. Why did it changed to Ctrl?

**Comment by SDGNelson** [comment]
It was not changed. Is your quick action bound to Shift?

**Comment by aladairmaxwell** [comment]
It was set to Ctrl for some reason. I don't understand why. I remember of using Shift for quick skill upgrade, I don't understand what happened.
