### ISSUE TITLE
Open a chat for a client from plugin*

### ISSUE THREAD

**Issue by 0x59R11** [SmartlyDressedGames/Unturned-3.x-Community#2189]
Is it possible to somehow enable chat for a client using a plugin?
If not I think it would be a very good modification for game servers. Make a function that will accept a string, and if you call this function for the player, then he will open a chat where the value of the input field will be equal to the string parameter.

![image](https://user-images.githubusercontent.com/41921371/101288714-b0112080-3800-11eb-8668-5cec8a257245.png)

(I can offer my help in implementing this function)

I hope you hear me :) Thanks

**Comment by AuD1tek** [comment]
@SDGNelson  :)

**Comment by Charterino** [comment]
1) I dont see the point of this. You can implement similar functionality with UIs or just wait from the input from the chat. 
2) Why do you all ping Nelson lmao

**Comment by z1net** [comment]
> 1. I dont see the point of this. You can implement similar functionality with UIs or just wait from the input from the chat.
> 2. Why do you all ping Nelson lmao

не выебывайся сука

**Comment by educatalan02** [comment]
> > 1. I dont see the point of this. You can implement similar functionality with UIs or just wait from the input from the chat.
> > 2. Why do you all ping Nelson lmao
> 
> не выебывайся сука

No russian here.

**Comment by rube200** [comment]
> > 1. I dont see the point of this. You can implement similar functionality with UIs or just wait from the input from the chat.
> > 2. Why do you all ping Nelson lmao
> 
> не выебывайся сука
Look at me, someone gave their opinion on something so I'll insult them in another language to see if you don't understand

**Comment by TH3AL3X** [comment]
> 1) I dont see the point of this. You can implement similar functionality with UIs or just wait from the input from the chat. 
> 
> 2) Why do you all ping Nelson lmao

Why are you so toxic?

**Comment by Charterino** [comment]
> > 1. I dont see the point of this. You can implement similar functionality with UIs or just wait from the input from the chat.
> > 2. Why do you all ping Nelson lmao
> 
> Why are you so toxic?

Oh, I didn't mean to offend anyone. Sorry if my message seemed rude. I just honestly don't see a good reason to add this feature.

**Comment by z1net** [comment]
на самом деле мне похуй, закройте свое ебало и не выебывайтесь

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
