### ISSUE TITLE
Christmas questions

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2192]
First week of winter is nearly over, and festive atmosphere coming faster and stronger. I want to ask about some points.

1. When will the Christmas event come to Unturned? Last year it was 6th December.
2. Will other official maps besides PEI become festive too? 
3. Will be added something new like event-only weather (snow storm) or holiday zombie clothes?

**Comment by SDGNelson** [comment]
This coming Friday
