### ISSUE TITLE
New font styling that came along with the UI upgrades...

### ISSUE THREAD

**Issue by XanderCodes** [SmartlyDressedGames/Unturned-3.x-Community#2193]
So... this new font. It's definitely _different_. I noticed some people on Steam weren't liking it, and I mostly agree with them, but I think I could get used to it... **EXCEPT** for one place it's being used, the debug information, and the game chat. This black border is SUPER eye-grabbing, and not in a good way. I think all it needs is a colour change, but I just thought I would throw it up here so people can voice their opinion...

![image](https://user-images.githubusercontent.com/19631080/101349596-b62afe00-38e1-11eb-8f34-f4ea558364e3.png)

**Comment by Johnanater** [comment]
I think it looks great

**Comment by SDGNelson** [comment]
For the next update I have changed the font back to the IMGUI font (Arial)
Curious if you would like to preview it #2203

**Comment by XanderCodes** [comment]
Hey @SDGNelson, thanks for taking the time to address this.

I read #2203, and noticed your comment here...

> Personally I do not see much of a difference between the uGUI default font (liberation sans) and IMGUI (arial), but the font has been changed to Arial.

After reading that, I think I've actually used the wrong term for what I'm describing. The actual font itself is good (arial vs. liberation sans), and I really like the change, but the black outline used specifically in the game chat, and for the FPS/Ping display, is what concerned me.

Hope that clears it up.

**Comment by XanderCodes** [comment]
To add, I've noticed the same outline in the map selection screen, where I think it really works: 
![image](https://user-images.githubusercontent.com/19631080/101592942-36b54000-3a43-11eb-9e9a-b107a81a923c.png)

But in chat, I think it's a lot on the eyes to read that constantly while playing, especially on busy servers.

**Comment by SDGNelson** [comment]
Ah. The strong outline is used anywhere that the text can be against a colorful backdrop. Revising the shadows in other parts of the UI is on my to-do for the update still. Unfortunately the uGUI text does not have a pixel-perfect shadow (like the IMGUI text did) so the shadow is a bit stronger to be safe at different scales.

**Comment by XanderCodes** [comment]
Looks like the latest update has made it much _much_ nicer.

Thanks as always for taking the time to listen to your community, it's well appreciated! 😄
