### ISSUE TITLE
Fuel Capacity

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2196]
Not exactly an issue but something that doesnt really make sense. Why does the Fuel Tank only have capacity for half as many fuel cans as the Industrial generator. I think that the item specifically made to store fuel should be at least on par in fuel capacity as the generator if not more. Half just doesnt really make any sense.

**Comment by SDGNelson** [comment]
From their appearance it is odd, however the industrial generator requires a lot more supplies to build. The industrial generator also needs to be able to power sentries overnight while players are offline. I don't think it is a big deal, and am hesitant to mess with any game balance values at this point.
