### ISSUE TITLE
Allow_Placement_On_Vehicle false not working on barricades with a landmine .dat as an example

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2197]
I was making a landmine that cannot be attached to vehicles but it seems to not work, on my end at least.

Unless I was missing something, Allow_Placement_On_Vehicle set to false on it does not work, so my landmine still can be placed on cars & whatnot, which is not intended.

This is what I put in my .dat file:
![image](https://user-images.githubusercontent.com/48363842/101412084-d6819b00-3896-11eb-9294-9e3bf789918a.png)

Is it just me, or is this bug present for someone else by any chance? And if it's not a bug, please do tell me where I am wrong.

**Comment by SDGNelson** [comment]
It does not apply if Bypass_Buildable_Mobility is enabled in game config

**Comment by OneManOperative** [comment]
Oh that's a thing? My bad
