### ISSUE TITLE
Vehicles glitch/debugger's beret

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2198]
https://drive.google.com/file/d/1BVmQu6A_H_odoNgnIDMGf1GpFP88fRCK/view
Can you consider this vehicles glitch? I think it's very
seriously bug because you can flip any vehicles without carjack. Thanks for
responding! Also, i wanna my beret, bereeeeet

**Comment by DiFFoZ** [comment]
Duplicate of #2102

**Comment by iBowie** [comment]
I think it's just russian's mentality, but let's not get in to this topic. I've posted quite a lot issues here, but I never ask for beret because all these issues don't worth it.

**Comment by schelchok** [comment]
> I think it's just russian's mentality, but let's not get in to this topic. I've posted quite a lot issues here, but I never ask for beret because all these issues don't worth it.

Why don't worth? Wdym?

**Comment by schelchok** [comment]
> Duplicate of #2102. Also, why many Russians trying to get a beret?

Idk lmao. But it's srs glitch

**Comment by SDGNelson** [comment]
As mentioned by DiFFoZ, this is a known issue - "between a rock and a hard place" type situation.
