### ISSUE TITLE
Spawn Tables remove button issue

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2200]
I just can't remove item from table. I press Remove and nothing happens. That's all.

**Comment by SDGNelson** [comment]
Double-checked removing items from the Spawns > Items tables and was unable to replicate. If you can send over your Client.log if you can get it to happen again there might be some error information

**Comment by aladairmaxwell** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5665217/Client.log)
Sure. And here is some errors in Client log. Please look.

**Comment by SDGNelson** [comment]
Oh in the main menu, thanks for the report.
