### ISSUE TITLE
No animation for RMB

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2204]
Before interface update RMB on item, setting or something else had "emission", like when you click with LMB. Now it looks a bit rough to use RMB and don't see it again. Will it come in Unturned again?

![image](https://user-images.githubusercontent.com/69295711/101601911-4fefc980-3a0e-11eb-8f7a-8eeea434d94d.png)

**Comment by SDGNelson** [comment]
Seeing about enabling the effect for right mouse is on my to-do so I will mark this next patch, but it depends how extensible the UI.Button class is
