### ISSUE TITLE
You Have Lost Your Place In Queue Error

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#2205]
I have recently been getting a lot of people struggling to join my servers even when they are no where near full. Not sure if its related to a plugin or something but it seems to have started getting bad after the latest update. It seems pretty much identical to #306. 
Is this a possible bug or is there any way to work around this? I attached my client.log that might help 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5665930/Client.log)

**Comment by SDGNelson** [comment]
If you look in the server log there should be a line like:
"Front of queue player timed out: {0} Ready: {1} Auth: {2} Econ: {3} Group: {4}"
Can you paste what it says please? Will indicate what it was waiting for.

**Comment by Bradler26** [comment]
Here is one of the lines I found. They all seem to have the same info as well

```[2020-12-09 08:34:08] Front of queue player timed out: 76561198417358366 Ready: False Auth: False Econ: True Group: True```

It seems to go in waves and at one point nobody could join at all till I restarted the server. I will try timeout setting soon but it seems to be a full server issue that everyone is effected by.

**Comment by SDGNelson** [comment]
According to that line they are still waiting for their authentication ticket to be verified. If a plugin is doing something weird during `onCheckValidWithExplanation`  or `onCheckValid` that could be a potential cause, but I think it is most likely that Steam is being slow to authenticate the ticket.

To clarify: raising the `Timeout_Queue_Seconds` value will give more time for Steam to authenticate their ticket.

**Comment by Bradler26** [comment]
Sorry for the late reply got busy. After raising timeout to 60s I still seem to be getting this. I am looking at getting a plugin made that listens for other plugins using ``onCheckValidWithExplanation`` or ``onCheckValid`` which i'm hoping is the issue. A restart seems to fix this for a while until it happens again then almost nobody could join. 

This could be a long shot but could it be in any way related to me using a steam ``Login_Token`` in my config.json?

**Comment by SDGNelson** [comment]
In regards to login tokens: if so there would probably be a message earlier along the lines of "Lost connection to Steam servers because X"

I do think the onCheckValid case is really unlikely. Even if they throw an exception the game would be handling that, only if the callback was returning true but manually cancelling their ticket or something weird like that.

According to the `SteamGameServer.BeginAuthSession` documentation the only callback is `ValidateAuthTicketResponse_t` which the game does listen for, and handles all result states.

If you can share the server log, perhaps by email if you are concerned about privacy, I can take a look.

**Comment by Bradler26** [comment]
Sure. I have sent you a email to nelson@smartlydressedgames.com

**Comment by SDGNelson** [comment]
Thanks for the log. Nothing jumps out at me as particularly unusual. It might be worth trying disabling a few plugins at a time to see if it is associated with one of them

**Comment by Bradler26** [comment]
It hasn't happened in a while and the only guess is that I was accidentally running a duplicated config.json on my test server so 2 servers where running the same Login_Token. I also see your latest update adds more details for the queue bug which should help resolve it if it happens again. For now I will close this.

**Comment by SDGNelson** [comment]
Thanks for the update. Hopefully it does not crop up again

**Comment by Bradler26** [comment]
I haven't had any reports of this happening anymore besides the odd case but attempting again seems to resolve it so i haven't thought much of it. I did notice this in logs quite often and wondered if it provides any useful info as it could be players trying to connect and failing 

```src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (1935) : Assertion Failed: [#579068838 UDP steamid:76561198963144398@90.211.232.59:51905] packet number not properly initialized!
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (1935) : Assertion Failed: [#579068838 UDP steamid:76561198963144398@90.211.232.59:51905] packet number not properly initialized!```

**Comment by SDGNelson** [comment]
Another host reported that popping up over Christmas as well. I wonder if it was a bug in Steam's December 21st update. If it persists then I will open an issue on the GameNetworkingSockets repo for it.

**Comment by joeymisfit** [comment]
I still experience this error when I play the game and I see the exact same error on multiple panel servers I help maintain.

**Comment by Bradler26** [comment]
Yeh i've been seeing the error ever since the update I just never thought much of it.

**Comment by SDGNelson** [comment]
Okay thanks for the reports. I will open an issue on the GNS repo.

**Comment by Bradler26** [comment]
Hey.

Did you manage to get any update from GNS? I still see these errors spammed almost every join

**Comment by SDGNelson** [comment]
Here's the issue, no news on it though: https://github.com/ValveSoftware/GameNetworkingSockets/issues/156
