### ISSUE TITLE
100% GPU usage in main menu cause my pc reboot automatically(high temperatures)

### ISSUE THREAD

**Issue by ozzysunn** [SmartlyDressedGames/Unturned-3.x-Community#2206]
My pc specs
CPU: Ryzen R7 3700X
GPU: Radeon RX 5700XT
RAM: DDR4-2400 16GB*2

https://user-images.githubusercontent.com/54042811/101633811-c74f4880-3a62-11eb-962a-7637a3b10267.png

**Comment by Kenzim** [comment]
get better cooling dude, your gpu overheating is not a game problem its a cooling problem. alternatively undervolt or underclock so it isnt using so much power.

you can use vsync or something to cap your frames instead

**Comment by SDGNelson** [comment]
Enabling vsync is the intended way to limit the framerate at the moment
