### ISSUE TITLE
Chat Limit Very Short

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#2207]
After the latest update it seems that chat has a very short cut off limit and when people type it cuts their messages off. Is there anyway chat can be extended again to last about 2 lines? With a suffix and [Global] around a persons name it really leaves with with just a few words to type before it runs out.

**Comment by SDGNelson** [comment]
Chat length is the same, but certain characters could cause it to get vertically truncated. Fixed in the next version
