### ISSUE TITLE
Using Ctrl + Backspace to erase whole word doesn't work

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2208]
It's very hard to write now in game chat. Before update I could use Ctrl + Backspace to erase whole word at once. Now it's disabled. I can only erase one character.             

![image](https://user-images.githubusercontent.com/69295711/101729034-84c05700-3ac8-11eb-8b7e-9df131159f86.png)

**Comment by SDGNelson** [comment]
Unfortunately not supported by the uGUI text fields. An alternative is to press ctrl+shift+left to quickly select the text you want to erase
