### ISSUE TITLE
The plugin crashes the game

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#2209]
Hello!

After the release of the 3.20.16.0 update, my plugin, which had previously been running smoothly, started crashing the game. I tried everything I could try: delete the mods and run the server with it, delete other plugins and leave only MiglioreMode, put the vanilla PEI map without mods, tried to fix it in the code. But nothing worked.

This plugin adds a skill system to my medieval server and packs in a lot of features. He uses a lot of UI.

The server does not give any errors in the logs, as well as the game logs. 

Please, help!

https://youtu.be/v3Bp0HC4va8

**Comment by FireRain4** [comment]
[RocketWithoutPlugin.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5672870/RocketWithoutPlugin.log)
[RocketWithPlugin.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5672872/RocketWithPlugin.log)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5672876/Client.log)

**Comment by SDGNelson** [comment]
Are you running a bunch of stuff when the player connects? May be worth enabling/disabling that piece by piece to narrow down what exactly is freezing the player

**Comment by Paradox304** [comment]
I am also experiencing this issue where I give skills depending upon the clothing the player wears. Same is happening for AntiSkills plugin which prevents player from levelling up their skills too much. After the recent update, something with skills have changed that either freezes the game for 10 seconds or crashes the game entirely. Nothing appears in logs.

**Comment by Paradox304** [comment]
I'll look into which method exactly crashes the game when used too much.

**Comment by SDGNelson** [comment]
There was actually a problem with the skills menu causing a freeze on death, so your case @Paradox304 should probably be back to normal after the update

**Comment by Paradox304** [comment]
I'll check

**Comment by Paradox304** [comment]
Update fixed the problem I had, thankls @SDGNelson !
