### ISSUE TITLE
Strange flickering on UI

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2210]
One player dropped me a video, UI is flickering for him when moving cursor around (backgrounds, texts), custom UI works fine though. Not sure if its just some specific setting he set but enabling vsync made it flickering less a bit. Will try to get video/hardware specs a bit later

**Comment by baranmod** [comment]
https://medal.tv/clips/38498865/d1337RIK9jEx got myself a bit different flickering (when opening inventory). It seems it doesn't flicker in first person and only flickers when you heading to some specific direction

**Comment by SDGNelson** [comment]
Interesting that it does not happen with custom UI. One difference that comes to mind: does the custom UI contain any of the RawImage component? The game uses the RawImage component for backwards compatibility and downloaded images, but I imagine custom UIs probably only use the Image component.

**Comment by SDGNelson** [comment]
Since the artifacts have persisted despite workarounds I am going to update the IMGUI implementation with support for some of the newer features (e.g. right now the IMGUI implementation scroll rects are broken), and support IMGUI as a fallback.

**Comment by TH3AL3X** [comment]
It's happening to me on Windows, i will record a video about it

**Comment by TH3AL3X** [comment]
https://www.youtube.com/watch?v=K3Ze0BoZrFs
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/K3Ze0BoZrFs/0.jpg)](https://www.youtube.com/watch?v=K3Ze0BoZrFs)

How it looks like:
![dfe0535904e2e073a10848d0fb6b1d25](https://user-images.githubusercontent.com/13141042/102546871-969d8d80-40b8-11eb-968a-b4a5f7e83985.png)
