### ISSUE TITLE
Scrollbars still seems a bit buggy

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2211]
By default when you use mouse wheel to scroll - it will scroll horizontally and vertically it will only scroll when you hover on on vertical scrollbar. It will use vertical scrollbar if your cursor is not hovered on item slots.

Also, maybe its possible to make horizontal scrollbar sticky at the bottom so you don't need to scroll down to the very bottom to see it? Like in this spot: 
![image](https://user-images.githubusercontent.com/14231707/101941052-1d9dc200-3bf0-11eb-9c50-e209295263fc.png)

**Comment by SDGNelson** [comment]
Unfortunately I believe this is a limitation of uGUI. I looked into overriding it, but my understanding is that uGUI only routes `OnScroll(PointerEventData)` to the first component which implements it, rather than allowing components to conditionally handle the event.

**Comment by WCPistolPete** [comment]
It actually won't scroll if your cursor is over any area defined as a slot when viewing/moving inventory.

**Comment by Tairiku-Ookami** [comment]
Yea im getting the same problem this is super annoying. You cant scroll when the mouse is over inventory slots. This will make it much more difficult to move items around the inventory.

**Comment by SDGNelson** [comment]
Since there has been a lot of concern about this I will go the drastic route and fork uGUI to change how the scroll wheel is handled.

**Comment by SDGNelson** [comment]
Fixed for the next update
