### ISSUE TITLE
Color gone on names of avaliable selections

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2212]
The numbers 1/1 and the price for said item when you had it used to be green however now all of the text is white regardless.
![image](https://user-images.githubusercontent.com/75531507/101945612-13f66900-3bb4-11eb-8246-f56fe6aef7b2.png)

**Comment by SDGNelson** [comment]
This was an intentional change as part of reducing potentially conflicting colored text throughout the UI. Now if you do not have any of the item to sell it will be disabled, and likewise any items you cannot afford to buy are disabled.
