### ISSUE TITLE
Status meter bug

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2213]
Sometimes one of the numbers on my status bar will change from 100% to 0/1
![image](https://user-images.githubusercontent.com/75531507/101946232-57e96e00-3bb4-11eb-886b-dff8da2c93ea.png)

**Comment by Tairiku-Ookami** [comment]
![image](https://user-images.githubusercontent.com/75531507/101956123-b0c10280-3bc4-11eb-98a4-ca103a56dca4.png)

**Comment by SDGNelson** [comment]
Thanks for the report! Really weird... Will investigate for the next update.

**Comment by Tairiku-Ookami** [comment]
This time is changed my quadbarrel from 2 to 0/1

**Comment by Tairiku-Ookami** [comment]
![image](https://user-images.githubusercontent.com/75531507/101960263-ae62a680-3bcc-11eb-8dac-4bacee5a4554.png)
And this time an HMG box in my inventory

**Comment by aladairmaxwell** [comment]
![image](https://user-images.githubusercontent.com/69295711/101984892-58a60100-3c95-11eb-9692-aa6b436714ea.png)
Something totally broke

**Comment by SDGNelson** [comment]
I am fairly confident that the image problems are sorted out in tomorrow's update, but the text and disabled button ones remain a mystery. I have fixed some potential causes, and added a bunch of logging to hopefully catch stragglers.

**Comment by SDGNelson** [comment]
After my previous comment I added a bunch more sanity checks and logging in the 3.21.1.0 update, but unfortunately the text and buttons remained a mystery. For the next update I have reworked the pooling to eliminate this for good - references to the old components are cleared to prevent the old owner from using them, and the new owner is always a new instance of the wrapper classes.

**Comment by SDGNelson** [comment]
With today's update it should not be possible for this to happen anymore, but whatever remaining case(s) was causing it will break when it does happen and should log a helpful error in the Client.log file.
