### ISSUE TITLE
Unity AppData Shortcut not linked properly

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2214]
Hey Nelson,
I also just realized that the Unity AppData Shortcut that you have in the DSA links to _"%USERPROFILE%\AppData\LocalLow\Smartly Dressed Games\Unturned"_ when it should be linked to _"%USERPROFILE%\AppData\Local\Temp\2\Smartly Dressed Games\Unturned"_.

**Comment by SDGNelson** [comment]
Unity writes the Player.log file to LocalLow, and writes crash dumps to Local\Temp. If Unity crashes then it will log the crash path in the Player.log file.
