### ISSUE TITLE
ubuntu black screen then crash

### ISSUE THREAD

**Issue by assasinwar9** [SmartlyDressedGames/Unturned-3.x-Community#2217]
so im on ubutnu and... when i start unturned its just a black screen for a while then crash
the logs are completely empty in the log folder
it worked fine on this pc when it was on windows 10, so i know its not a hardware issue

and i know its not a issue caused by the swap from windows to ubuntu since i reformated my entire harddrive etc for the swap

**Comment by SDGNelson** [comment]
When you say the logs are empty, you are checking the Unturned/Logs folder?
One potential issue: I wonder if you have Steam proton enabled for the game? If it is enabled it might be worth trying disabled.

**Comment by assasinwar9** [comment]
iv tried with proton disabled and with it enabled, with proton enabled the game dont even show up at all except in the system monitor and yes i was looking inot the unturned/logs folder for the logs

**Comment by SDGNelson** [comment]
Hmm... it might be a missing dependency. Unity itself might be writing a log file with more details to:
`~/.config/unity3d/SmartlyDressedGames/Unturned/Player.log`

**Comment by assasinwar9** [comment]
only thing in that file that stands out is 
WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
ERROR: Shader Hidden/Nature/Terrain/Utilities shader is not supported on this GPU (none of subshaders/fallbacks are suitable)

seems i have a problem with ubuntu where its not using my main graphics card lmao, my bad and thanks for the help
