### ISSUE TITLE
Skin bug

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2218]
I found smth about when I wear Cyborg Implant (glasses) and Grim Necromancer Mask (mask). In the video u can see that mask covers glasses that can't look at it.
https://drive.google.com/file/d/1TZL2WzkylfhBEMNaQosOmo1dgpCu9TNz/view

**Comment by SDGNelson** [comment]
The video is private so I cannot see, but it sounds like those two items were simply not designed with each other in mind. The line between glasses/mask for face covering items is a little blurry so not all items work nicely together

**Comment by schelchok** [comment]
> The video is private so I cannot see, but it sounds like those two items were simply not designed with each other in mind. The line between glasses/mask for face covering items is a little blurry so not all items work nicely together

Lemme check settings

**Comment by schelchok** [comment]
Now it's public

**Comment by SDGNelson** [comment]
From the video sorry those items are not compatible. If you purchased them recently it may be an option to ask Steam support for a refund if you would like.
