### ISSUE TITLE
Lost connection to host or steam network

### ISSUE THREAD

**Issue by z1net** [SmartlyDressedGames/Unturned-3.x-Community#2219]
![Screenshot_1](https://user-images.githubusercontent.com/65300126/101989495-5fd70a00-3ca9-11eb-81d0-4680f736f0f5.png)

When i connecting on my localhost server, im see this panel with text, how i can fix it?
3 days ago, its worked

**Comment by SDGNelson** [comment]
Duplicate of issue you opened in the other repository
