### ISSUE TITLE
add server support for Linux For Niggers

### ISSUE THREAD

**Issue by b1gpaster** [SmartlyDressedGames/Unturned-3.x-Community#222]
title says it all

**Comment by b1gpaster** [comment]
why did u close

**Comment by Vulby** [comment]
Your choice of words is the reason he closed this

**Comment by Trojaner25** [comment]
![image](https://user-images.githubusercontent.com/1809172/36584409-a156e5c2-188a-11e8-8f8b-5bd8862c46f9.png)

![image](https://user-images.githubusercontent.com/1809172/36584428-b0d2e316-188a-11e8-9ee7-750b60a836a0.png)
