### ISSUE TITLE
Swapped icons in crafting menu

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2220]
Maplestrike and Fusilaut were in the inventory at the time
![unknown](https://user-images.githubusercontent.com/71527679/102001462-794c7600-3cea-11eb-8d1a-4e9aa42f06e8.png)

**Comment by SDGNelson** [comment]
Thanks for the report. Closing because it is the same underlying bug as #2213
