### ISSUE TITLE
Option to go back to old font.

### ISSUE THREAD

**Issue by Glass47** [SmartlyDressedGames/Unturned-3.x-Community#2221]
Hello, i would like to suggest Nelson to add option to go back to old font since i have visibility issues with new font and colors.

**Comment by SDGNelson** [comment]
Can you share which menus you are having visibility issues with? It might be something that should get adjusted.
As a fallback I am going to add support for using the old UI system again however.

**Comment by Glass47** [comment]
The bars for health/food etc is hard for me to read, my eyes struggle to read and it takes me a bit more time for my brain to process what numbers are exactly, before it was just split second and i could tell to my friend how many hp i have for example. 
1. ![image](https://user-images.githubusercontent.com/55170107/102020087-456b6200-3d77-11eb-9578-f59b6a013ff5.png)
2. ![image](https://user-images.githubusercontent.com/55170107/102020246-320cc680-3d78-11eb-8eea-5685bad9be4f.png)
3. ![image](https://user-images.githubusercontent.com/55170107/102020269-5a94c080-3d78-11eb-8d55-c7b5d485b9ec.png)


Also the building menu is though for difficult for me to read it because font itself is causing me problems, i would greatly appreciate if there is "checkpoint" to enable/disable new font/ui and go back to old. The number/latter(s) are close from each other, i am not sure how do i explain that exactly. (
![image](https://user-images.githubusercontent.com/55170107/102020371-21a91b80-3d79-11eb-86b8-f5331f2dbfdd.png))

And i forgot to mention that we can't hold CTRL and backspace to delete whole sentience for example, you must tap 1 by 1 backspace to delete things in chat.

**Comment by SDGNelson** [comment]
Thanks for the examples! I have made a note of them on my to-do list.

As for ctrl+backspace, unfortunately it's not supported by the uGUI text fields. An alternative is to press ctrl+shift+left to quickly select the text you want to erase.
