### ISSUE TITLE
My invetory,map  and HUD flashing ,random white and red thinks 

### ISSUE THREAD

**Issue by Starkman56** [SmartlyDressedGames/Unturned-3.x-Community#2225]

**Comment by Starkman56** [comment]
![image](https://user-images.githubusercontent.com/75947368/102019612-d2f98280-3d74-11eb-99a3-c0bb52443e2b.png)

**Comment by schelchok** [comment]
Same #2224

**Comment by SDGNelson** [comment]
Sorry for the trouble. uGUI is causing artifacts for some players, so I am restoring support for the old HUD in the next update
