### ISSUE TITLE
Lost connection to host or Steam network, still a bit of an issue.

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2226]
I was playing on a PVP server and got disconnected after a bit of being on it. From looking at the client.log I did notice a lot of discarding old unacknowledged input packets before disconnect. Attached is the client.log, hopefully it helps as my internet didn't die at all, I was on an uninterrupted discord call and on twitch without issues.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5686492/Client.log)

**Comment by SDGNelson** [comment]
Since this was a one-off thing it probably was what it says on the tin - dropped connection
