### ISSUE TITLE
bug on unturned

### ISSUE THREAD

**Issue by HaruNoAi** [SmartlyDressedGames/Unturned-3.x-Community#2227]
when i play there is constant stuttering of white lines and occasionally rainbow ones and makes my screen looks funny and when i pick up a gun there is a chance it drops it immediately it also happens to other items and also ping increase on the recent updates
also when i open up my inventory the stuttering happens i am guessing its from the new hud cuz the color changes when you change your font in the settings

**Comment by SDGNelson** [comment]
Sorry for the trouble. uGUI is having these artifacts for some players, so I am adding optional support for the old HUD for the next update
