### ISSUE TITLE
Inventory scroll trouble.

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2228]
I can't scroll through my inventory when cursor is in slots. It appeared with new update.
https://drive.google.com/file/d/1JYMpaO5Q_dedIuYrCNzleMsWZ1f2x83s/view

**Comment by SDGNelson** [comment]
Sorry for the trouble. It is on my to-do for the next update. Closing because this is a duplicate of #2211
