### ISSUE TITLE
Chat trouble. Can't clean letters faster with CTRL + BACKSPACE

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2229]
Of course it appeared in new update. As u see I can't remove words faster with CTRL + BACKSPACE. It used to be possible before update.
https://drive.google.com/file/d/1mraWb0DX7aruIUVBL1uSmUpaurEa-DuY/view

**Comment by SDGNelson** [comment]
Unfortunately not supported by the uGUI text fields. An alternative is to press ctrl+shift+left to quickly select the text you want to erase
