### ISSUE TITLE
More example packages?

### ISSUE THREAD

**Issue by Hexadec1ma1** [SmartlyDressedGames/Unturned-3.x-Community#223]
It would be very helpful to have the barracks models (Barracks_4, Barracks_5, and Barracks_6) added to the example Object Unity package. This way modders can easily create other military colors.

Could we also get the rest of the vines (Vines_1, Vines_2, Vines_3, and Vines_4)? in the example Vines Unity package.

**Comment by AnimaticFreak** [comment]
This is always a welcomed addition, maybe a weather example too :')
