### ISSUE TITLE
Resolution settings bug

### ISSUE THREAD

**Issue by schelchok** [SmartlyDressedGames/Unturned-3.x-Community#2230]
https://drive.google.com/file/d/1SRotT4gLyh7F3EI4ZyxiyHsvUU9oLtj3/view
It's smth wrong with order of resolution screen

**Comment by SalgadinhoRoxo** [comment]
i think this is part of the new HUD code on the game, my game is fully broken. im waiting for a update to see if this fix my problem

**Comment by SDGNelson** [comment]
Interesting. Thanks for the report. Unity returned that list sorted by default in the past, but I guess we need to sort it ourselves now.
