### ISSUE TITLE
Game doesn't  load main menu or something like that

### ISSUE THREAD

**Issue by SalgadinhoRoxo** [SmartlyDressedGames/Unturned-3.x-Community#2231]
My game just got insanely buggy, when it is loading there's nothing but a black screen, and when the loading finishes there's just the barn from the main menu and a scrollbar on the right
![20201214091701_2](https://user-images.githubusercontent.com/68348974/102127089-d0596480-3e2a-11eb-9153-a40813d28ee4.jpg)

**Comment by SDGNelson** [comment]
Can you attach your Client.log file please? It ought to have an explanation:

1. Right-click Unturned in your Steam Library
2. Select Properties > Local Files > Browse Local Files
3. Open the Logs folder
4. Attach the Client.log file

**Comment by SalgadinhoRoxo** [comment]
Ok, here it is.

[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5692186/Client.log)

i think some of the mods i installed just broke my game, because i just reinstalled everything and now it's working ok.

**Comment by SDGNelson** [comment]
Was that log from after you re-installed everything? Because there do not appear to be any errors in it.
