### ISSUE TITLE
PSA: IMGUI on the Preview Branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2234]
If you are experiencing visual artifacts and flickering with uGUI, it may be worth trying the "public test branch" now. Using the old UI system (IMGUI) will be an optional fallback. There is still a bunch of stuff to do this week, but if you run into any bugs I would appreciate the reports.

**Comment by warren39** [comment]
Backpack Width:13 & Height: 18
![p1](https://user-images.githubusercontent.com/64722485/102437697-f1ea6400-4055-11eb-8720-bee176c6dfb0.png)

**Comment by warren39** [comment]
Click & Drop item events  not work at the first column of Inventory:

![p2](https://user-images.githubusercontent.com/64722485/102438695-bea8d480-4057-11eb-821c-aa9d93f349c8.gif)

**Comment by warren39** [comment]
Cannot input G in the chat window:

![p3](https://user-images.githubusercontent.com/64722485/102440496-4a703000-405b-11eb-8dd2-79b919a019f6.gif)

**Comment by SDGNelson** [comment]
Thanks for the reports. I will check into scroll one, and the chat one is an easy fix: the dashboard key was being used as an escape key.

As for the items in the upper-left of the inventory it is probably the same as #2237 and fixed in the preview version that went up earlier this evening. The character image was overlapping behind the inventory grids to the right of it which is not supported by IMGUI.

**Comment by warren39** [comment]
Yes, it is the same as #2237. I found that in version .255 . Now fixed in version .254

**Comment by schelchok** [comment]
![bug](https://user-images.githubusercontent.com/74832662/102687172-ad51fa80-4206-11eb-8e07-cbcaa3d3c3b5.png)
it will happen if u put some item on hotkey 4
