### ISSUE TITLE
1st and 3rd person inconsistencies

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2235]
The headlamp light is not visible while prone on a flat surface in 1st person, the light source is underground.
It is visible while prone in 3rd person:
![headlamp](https://user-images.githubusercontent.com/71527679/102300122-34277e80-3f4c-11eb-9dfd-a77e7618e6dd.gif)

Bullet casings can be seen falling forever through objects in 1st person.
They are not visible through terrain in 3rd person:
![casings](https://user-images.githubusercontent.com/71527679/102299226-8071bf00-3f4a-11eb-8075-2ffed87c55bf.gif)

**Comment by SDGNelson** [comment]
Thanks for the reports. 

1. Unsure what is going on here, so I will investigate.
2. Happens because the first-person arms are away in the skybox. Ideally will be merged with the third-person body at some point, but no ETA.

**Comment by SDGNelson** [comment]
The first-person light had some offset from the camera position. This was probably intentional at some point to more closely match how the third-person light source is offset, but for the next update I have moved it to the camera position for usability.
