### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#2236]
OS: Windows 10

[Crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5704854/Crash.zip)
(Connection log looks normal)

This arena server crashed with normal gameplay I'm not sure if the player '76561198440457678' is related to this but at least this happened(Packet) whenever he joined (x2): `src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (1935) : Assertion Failed: [#3658422452 UDP steamid:76561198440457678@(HIDING THE IP):2131] packet number not properly initialized!`

**Comment by SDGNelson** [comment]
Apparently it was a crash in UnityWebRequestProto. It looks like other games have reported the same crash, so hopefully it will be fixed soon. The dedicated server does not make any web requests, so whichever code is instigating the request must be a plugin.
