### ISSUE TITLE
Unable to move items in inventory - IMGUI

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2237]
I can only swap weapons by dropping them on the ground then picking them up in the order I want. Items in inventory can not be moved from one slot/area to another unless they are stored in pants. Tooltips and action boxes may or may not appear.

**Comment by SDGNelson** [comment]
I suspect you ran into a bug that is fixed for the next preview version - the character image was overlapping behind the inventory grids to the right of it which is not supported by IMGUI.

**Comment by WCPistolPete** [comment]
Now works properly in test branch. Will open a new ticket if it resurfaces.
