### ISSUE TITLE
Moon zombies are not giving damage

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2238]

**Comment by WCPistolPete** [comment]
IMGUI beta - I just tested this. I found that if one is moving away it's very difficult for zombies to register damage compared to what they used to do during a full moon. If one is barely moving barely moving they still hit with full force.

**Comment by SDGNelson** [comment]
Nothing has changed with the zombies recently. I also double-checked by resetting my singleplayer world and getting attacked by zombies during the full moon. Perhaps related to config?

**Comment by TH3AL3X** [comment]
> Nothing has changed with the zombies recently. I also double-checked by resetting my singleplayer world and getting attacked by zombies during the full moon. Perhaps related to config?

"Zombies": {
      "Spawn_Chance": 0.58,
      "Loot_Chance": 0.57,
      "Crawler_Chance": 0.0,
      "Sprinter_Chance": 0.0,
      "Flanker_Chance": 0.0,
      "Burner_Chance": 0.0,
      "Acid_Chance": 0.0,
      "Boss_Electric_Chance": 0.0,
      "Boss_Wind_Chance": 0.0,
      "Boss_Fire_Chance": 0.0,
      "Spirit_Chance": 0.0,
      "DL_Red_Volatile_Chance": 0.0,
      "DL_Blue_Volatile_Chance": 0.0,
      "Boss_Elver_Stomper_Chance": 0.0,
      "Respawn_Day_Time": 360.0,
      "Respawn_Night_Time": 30.0,
      "Respawn_Beacon_Time": 0.0,
      "Quest_Boss_Respawn_Interval": 600.0,
      "Damage_Multiplier": 0.75,
      "Armor_Multiplier": 1.25,
      "Backstab_Multiplier": 1.25,
      "NonHeadshot_Armor_Multiplier": 1.0,
      "Beacon_Experience_Multiplier": 10.0,
      "Full_Moon_Experience_Multiplier": 3.0,
      "Min_Drops": 4,
      "Max_Drops": 5,
      "Min_Mega_Drops": 11,
      "Max_Mega_Drops": 15,
      "Min_Boss_Drops": 8,
      "Max_Boss_Drops": 10,
      "Slow_Movement": false,
      "Can_Stun": true,
      "Only_Critical_Stuns": false,
      "Weapons_Use_Player_Damage": false,
      "Can_Target_Barricades": true,
      "Can_Target_Structures": true,
      "Can_Target_Vehicles": true,
      "Beacon_Max_Rewards": 25,
      "Beacon_Max_Participants": 0,
      "Beacon_Rewards_Multiplier": 10.0
    },

**Comment by TH3AL3X** [comment]
> Nothing has changed with the zombies recently. I also double-checked by resetting my singleplayer world and getting attacked by zombies during the full moon. Perhaps related to config?

When a player stands still he does not receive damage, it is very strange, today a player from my server reported it

**Comment by TH3AL3X** [comment]
Is very weird, i found the problem.... was a plugin for ignore zombies, but idk why is happening now this when it was working fine before
