### ISSUE TITLE
Animal Aggression Tweak

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2240]
Currently, even aggressive animals will startle and run if you are to shoot them from a distance where the player cannot be seen. This is troubling when creating boss monsters, as people can sit and shoot at a distance and be completely unharmed. Requesting either a change to aggressive animals or a dat feature when when shot, the animal will instead charge in the direction of the shot to prevent the pushing over of animals designed as powerful enemies.

**Comment by SDGNelson** [comment]
What you describe is how it should be working at the moment. When an animal is damaged a function `alertDamagedFromPoint` is called which then calls `alertGoToPoint` or `alertRunAwayFromPoint` depending on the behavior. In what context are they running away?

**Comment by Dumfoozler** [comment]
Seems there was an error from my end, testing vanilla animals shows this to be true but although my animal is listed as aggressive it doesn't seem to behave that way. I'll have to look into my Unity and see what went wrong.
