### ISSUE TITLE
Crouching/proning issues

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2242]
Seems like 'hold' option for crouching/proning is not working (still toggles if you set to 'hold').
Also, there is pretty big delay between changing positions (not sure if its intended change)

And you can't change back from proning by using spacebar anymore (can't remember actually if it was a thing before, but got a report from one player)

**Comment by SDGNelson** [comment]
Thanks for the report. It looks like hold only works if holding for longer than the cooldown between stance changes. I had cleaned up some of that code for a fix, but it looks like that stance change cooldown only applied when standing up before, not for standing to crouch/prone. Will fix, and I will re-evaluate the purpose of that cooldown and whether it is too long.

**Comment by SDGNelson** [comment]
Thankfully this seems to have been the only issue with the update. The patch is now out. I also made an improvement to how those inputs are handled on the server so that crouch/prone are more responsive.
