### ISSUE TITLE
iGUI branch - "Blocked" window blocks "Write" and "Cancel"

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2245]
Not a big deal for me because I'm on the IMGUI branch where the buttons work as intended, however, for the iGUI users that place signs/placards/flags and have more than one in inventory: The "Blocked" information/tooltip window blocks one half of the "Write" and "Cancel" buttons and does not allow click-throughs,
![20201218174555_1](https://user-images.githubusercontent.com/53093137/102668315-999c8a80-4159-11eb-9bbb-5255d678f033.jpg)

**Comment by SDGNelson** [comment]
Thanks, will fix
