### ISSUE TITLE
Some observations (not related to update)

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2246]
Here are some stuff bothering me for a long time (not really big issues or anything like that, just would be cool to fix/add them)

1. /vanish mode in rocketmod is a bit broken. If you stay afk in vanish mode for a long time - all players will start to see you. Also, those who join server - will see you even if its not that long of afk time (need to take one step to become invisible for them).

2. Workshop mod icons could be exported to a separate folder. Its pretty disturbing to look for specific item between all those icons (especially if you export icons of some big mod with a lot of items)

3. Not sure if its possible, but would be cool to be able to zoom in / zoom out map with a mouse wheel (just a small handy feature)

**Comment by iBowie** [comment]
About vanish - it works as intended. When you move your player model teleports very high to everyone else, and when you don't move your model stays where you are for new players.

**Comment by TH3AL3X** [comment]
> Here are some stuff bothering me for a long time (not really big issues or anything like that, just would be cool to fix/add them)
> 
> 1. /vanish mode in rocketmod is a bit broken. If you stay afk in vanish mode for a long time - all players will start to see you. Also, those who join server - will see you even if its not that long of afk time (need to take one step to become invisible for them).
> 2. Workshop mod icons could be exported to a separate folder. Its pretty disturbing to look for specific item between all those icons (especially if you export icons of some big mod with a lot of items)
> 3. Not sure if its possible, but would be cool to be able to zoom in / zoom out map with a mouse wheel (just a small handy feature)

I already report the vanish thing like 6 months ago

**Comment by WCPistolPete** [comment]
Vanish has always worked that way as long as I can remember. I just tell players I've /homed if they ask where I suddenly went. ;)

**Comment by SDGNelson** [comment]
1. iBowie is correct about how vanish works. It was originally hacked together by Sven, so it would be better to have proper support in the game. As part of netcode rewrites I intend to support making players unknown to each other (e.g. far away), so that would be a good point to support vanish.

2. Could add a path option for exporting icons. Relatively low priority though.

3. Agreed that it would be a nice improvement. First step was uGUI support, so it is more likely now.
