### ISSUE TITLE
there is some weird glitch where some things say x0 instead of what its supposed to be

### ISSUE THREAD

**Issue by Nerfboy-NEO** [SmartlyDressedGames/Unturned-3.x-Community#2247]
![wtf happened here](https://user-images.githubusercontent.com/76239255/102681660-fe230e00-4188-11eb-8ca8-8c342d1ba41e.PNG)
 so i was playing the game and well i noticed something up with some of the map markings and some things in settings, there will be something that says x0 and for some reason my player marker says 0/1.

**Comment by warren39** [comment]
![p1](https://user-images.githubusercontent.com/64722485/102693365-12344180-4255-11eb-8e2a-77538a122dd4.png)

![p2](https://user-images.githubusercontent.com/64722485/102693366-16f8f580-4255-11eb-8fa5-2c8febca430f.png)

**Comment by SDGNelson** [comment]
After this happens to you again could you attach the Client.log please? I added a bunch of logging in the update to hopefully catch whatever is causing this.

**Comment by Nerfboy-NEO** [comment]
how can i find this? (sorry this is a first time im finding weird bugs like this)

**Comment by Nerfboy-NEO** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5720568/Client.log)
hopefully this will help you @SDGNelson

**Comment by SDGNelson** [comment]
Thank you for the log Nerfboy-NEO! There were two helpful errors in there that I will fix for the next update.

**Comment by SDGNelson** [comment]
Forgot to mark as next update, but those errors are fixed for tomorrow's update.
