### ISSUE TITLE
Linux build crashes after joining a server

### ISSUE THREAD

**Issue by tenten8401** [SmartlyDressedGames/Unturned-3.x-Community#225]
Not sure what's up with this one, but the game runs great on Linux until I join any server at all, and then seemingly randomly crashes with no real explanation of what's going on at all. Sometimes I've been able to play for up to an hour without an issue, and other times it'll crash instantly upon joining.

Here's a video of the issue:
https://youtu.be/GliUyoo_jlg

I have tried the following to fix it:
- Verified game cache
- Tried on a different machine
- Tried a different Linux distribution
- Turning down the settings

Logs:
- [Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1756588/Client.log)
- [Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1756589/Player.log)

Specs:
- Ryzen 5 1600
- 16 GB RAM
- GTX 1070

Software:
- Solus Linux
- Kernel 4.15.5
- KDE Plasma
- Proprietary NVIDIA drivers (390.25, have observed on 384 too.)

I can provide additional logs/info if needed.

**Comment by KlaasM** [comment]
I'd recommend Ubuntu 16.04 or 14.04 as Unturned is simply unstable on any other platform/distro.
Please share your logs though.

**Comment by tenten8401** [comment]
I did share my logs as seen above, and I have tried it on KDE Neon (Ubuntu 16.04 w/ KDE repo)

**Comment by Trojaner25** [comment]
The logs you shared show a native crash, which isn't fixable.
Only Unity or NVIDIA could fix it.
