### ISSUE TITLE
Interacting with signs, placards, notes and books - IMGUI interface only

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2250]
Type something on the sign, click "Write". Try to interact again or move... Nothing. At this point all keyboard commands do nothing. The player can only spin in place using the mouse. One must hit the left or right mouse button or hit "Escape", then return to the game in order to restore keyboard function. Most likely an overlay issue. **IMGUI only**. An oddity: the first edit on a freshly-placed book or note does not have the bug, however, interacting with them a second or subsequent time induces the bug.

**Comment by WCPistolPete** [comment]
Additional: A carriage return/line feed to start a new line of text changes the focus from the sign to the game overlay. At that point in time any assigned letter causes it's function to occur. It is necessary to click back in the text box to enter text, if one hasn't been booted by an assigned key action.

**Comment by SDGNelson** [comment]
Thanks for the report, will check into it

**Comment by WCPistolPete** [comment]
The issue persists after the patch. IMGUI only.

**Comment by SDGNelson** [comment]
The most recent patch was on December 18th, so it was probably a workshop file update you saw.

**Comment by WCPistolPete** [comment]
Found this in the logs after a focus change while typing text for a sign:
[2020-12-27 23:22:21] NullReferenceException: Object reference not set to an instance of an object
[2020-12-27 23:22:21] SDG.Unturned.PlayerBarricadeSignUI.onTypedSignText (SDG.Unturned.ISleekField field, System.String text) (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierStringField_IMGUI.OnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierBase_IMGUI.ChildrenOnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierBase_IMGUI.OnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierBase_IMGUI.ChildrenOnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierBase_IMGUI.OnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierBase_IMGUI.ChildrenOnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.GlazierBase_IMGUI.OnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)
SDG.Unturned.Glazier_IMGUI.OnGUI () (at <5a5449143cb1457db72f1f273bc817a2>:0)

**Comment by SDGNelson** [comment]
All three of these bugs should be fixed for the next update.
