### ISSUE TITLE
First click on "Rest" puts player into crouch instead of a seated position.

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2251]
Occurs in both iGUI and IMGUI.

**Comment by SDGNelson** [comment]
Thanks for the report, will check

**Comment by WCPistolPete** [comment]
The issue persists after the update.

**Comment by SDGNelson** [comment]
The most recent patch was on December 18th, so it was probably a workshop file update you saw.
