### ISSUE TITLE
I can't connect to my local server

### ISSUE THREAD

**Issue by DomingoTapita** [SmartlyDressedGames/Unturned-3.x-Community#2252]
Hello good morning, create a local server to play with my friends. I opened the ports and my friends can enter except me. I put my public ip or "localhost" and I cannot enter the server. I attach a photo.
The server has a workshop and it is downloaded without any problem. The only one who cannot enter the server is me.
It should be noted that I use OpenMod, only for plugins. Try uninstalling OpenMod and also the same problem keeps happening.

![image](https://user-images.githubusercontent.com/70148952/102699252-24e15300-4222-11eb-954b-8611225d9616.png)
![image](https://user-images.githubusercontent.com/70148952/102699256-2e6abb00-4222-11eb-83dc-8b87464485fe.png)
![image](https://user-images.githubusercontent.com/70148952/102699269-3d516d80-4222-11eb-83fb-9b910a1a48f4.png)
![image](https://user-images.githubusercontent.com/70148952/102699275-493d2f80-4222-11eb-882a-8cac6569c013.png)
![image](https://user-images.githubusercontent.com/70148952/102699284-4e9a7a00-4222-11eb-967b-c10556aeae8c.png)

**Comment by SDGNelson** [comment]
Unusual that your friends can connect but not you. If you enter "127.0.0.1" instead of localhost does it work? (should be the same, but maybe worth a try) 

Double-checked on my PC and connecting to a local dedicated server is working properly.

**Comment by DomingoTapita** [comment]
I just tried 127.0.0.1 and it won't let me in.

**Comment by SDGNelson** [comment]
Sorry, I am not sure what else to suggest. Usually it is the other way around: players who can join their local server, but whose friends cannot join because they did not port-forward correctly. Nobody has reported something like this before.

If you are using a VPN or any other network-related system extensions it might be worth trying disabling them.

**Comment by DomingoTapita** [comment]
Hi Nelson, I've been seeing the problem. Download the Unturned Dedicated Server from steam in my library. I started the server and it wouldn't let me enter the server. Until I tried STEAMCMD following the steps and finally I was able to enter ... Will it be a problem installing the Unturned Dedicated Server from Steam?
![image](https://user-images.githubusercontent.com/70148952/102724506-b1594780-42ee-11eb-8a79-8261406c7f16.png)

**Comment by SDGNelson** [comment]
Glad you found a workaround. Installing the Dedicated Server through the Steam Library should work fine though - personally I use it to test as well because it is conveniently auto-updated.

**Comment by educatalan02** [comment]
You should not open the Unturned Dedicated Server with the "Play" Button

**Comment by educatalan02** [comment]
I got it installed via Steam so it'll autoupdate 
![image](https://user-images.githubusercontent.com/34221626/102726356-6e16cd00-431e-11eb-9ef2-80b5e3c38b8f.png)

But the server works perfectly if you run it with the  ServerHelper.bat
