### ISSUE TITLE
Cannot exit server

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2254]
Some player reports that they cannot exit my server by press Exit button. Nothing happened when they press Exit. 
One of player's  Logs:

[Logs.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5720694/Logs.zip)

**Comment by SDGNelson** [comment]
Thanks for the log! There is a related error in here which I will fix for the next update.

**Comment by SDGNelson** [comment]
This particular case should be fixed for the next update.
