### ISSUE TITLE
IMGUI - DevKit bug | Invisible Cursor and No Interactive Map (chart/gps)

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#2255]
Hello, I was editing my maps and when I needed to use (DEVKIT) and found a bug that is:
the mouse cursor is invisible when using devkit (after pressing the key =  '   )

I tested on two computers with and without IMGUI.

With: -Glazier=IMGUI (Invisible Cursor)
Without: -Glazier=IMGUI (works normal)

if necessary prints I can send.

Thanks nelson.

**Comment by GabrielMaestre** [comment]
Another bug that I noticed,
the same applies to the map / gps you cannot move the map if you are using the new IMGUI but without it it is possible to move

**Comment by SDGNelson** [comment]
Will see about the cursor, but the map dragging is not going to be supported with IMGUI sorry.

**Comment by GabrielMaestre** [comment]
A suggestion, and if on IMGUI you could use the arrows to move the map. Thanks you

**Comment by SDGNelson** [comment]
Thanks for the report. Fixed for the next update
