### ISSUE TITLE
When I shoot, punch with a melee or eat something the item unequips.

### ISSUE THREAD

**Issue by SnixFix** [SmartlyDressedGames/Unturned-3.x-Community#2256]

**Comment by SnixFix** [comment]
It happends all the time and on every server, I try restarting unturned but nothing happends.

**Comment by SDGNelson** [comment]
If you check the Controls menu do you have Dequip bound to Left Mouse?

**Comment by SnixFix** [comment]
No but, i had left click for 9 on the hot bar so when i shot i would press 9 and unequip it, thank you.
