### ISSUE TITLE
Unturned Horizontal grip swaping bug.

### ISSUE THREAD

**Issue by Stalionn** [SmartlyDressedGames/Unturned-3.x-Community#2257]
So basicly, the horizontal grip wont switch/swap with other grips. Other items other than grips let it swap. 

Video of bug: https://www.youtube.com/watch?v=Ld99axayrog&feature=youtu.be

Steam if needed: https://steamcommunity.com/profiles/76561199012846877/

**Comment by SDGNelson** [comment]
Looks like it must be a bug with swapping rotated items. Thanks for the report! Will investigate

**Comment by SDGNelson** [comment]
Sorry my bad: I should have marked this as next update in order to remember to find it again. I have not fixed this for tomorrow's update yet (3.21.1.0), but I will do it for the next-next update.

**Comment by SDGNelson** [comment]
Turns out this was not supported in the first place. Was a bit of a mess to clean up, but I have added support for swapping rotated items in the next update.
