### ISSUE TITLE
Deadzone infection health problem.

### ISSUE THREAD

**Issue by Stalionn** [SmartlyDressedGames/Unturned-3.x-Community#2258]
Wouldn't say this is a pretty important bug but, if you enter the dead zone and die inside of it from infection or without a gasmask, you'll respawn with 99% infection. 

Video of bug: https://www.youtube.com/watch?v=_9HAIXwLBV0&feature=youtu.be

Steam profile (Incase): https://steamcommunity.com/profiles/76561199012846877/

(Going to keep my eyes peeled for more stuff like this.)

**Comment by SDGNelson** [comment]
Interesting, thanks for the report. Will fix

**Comment by SDGNelson** [comment]
Should be fixed for the next update.
