### ISSUE TITLE
Support for lights that turn on at night 

### ISSUE THREAD

**Issue by AnimaticFreak** [SmartlyDressedGames/Unturned-3.x-Community#226]
I mean its in game already, maybe give us some sort of line of text we can add to our .dats so we can have them turn on automatically?

**Comment by SDGNelson** [comment]
Right now those objects have a script attached inside Unity to enable/disable at night. I'll add a .dat option to automatically add that script.

**Comment by SDGNelson** [comment]
In the next update this is turned on with: Add_Night_Light_Script
The default Light_2 and Light_3 objects have been changed to use the option.
