### ISSUE TITLE
Bug when entering a car

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#2260]
Take a look of the video:
https://youtu.be/WOgRVKh7ugY

Here's the Client.log: 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5726388/Client.log)

**Comment by SDGNelson** [comment]
Thanks for the report. Looks like the player could not exit the prone stance when entering. Will fix.

**Comment by SDGNelson** [comment]
Fixed for the next update.
