### ISSUE TITLE
Mannequin Hair

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2261]
Please make the Apply Cosmetics button also apply your hair color to the mannequin or some other way to change its set color so this doesnt happen. 
![image](https://user-images.githubusercontent.com/75531507/102823170-030dda80-43a0-11eb-906f-f64a38e1c173.png)

**Comment by Tairiku-Ookami** [comment]
Hats based on hair color can only be black

**Comment by SDGNelson** [comment]
Good catch. Right now mannequins do not have hair color so no ETA when this will be taken care of, but I will mark it next update.

**Comment by Tairiku-Ookami** [comment]
Do you think I could get the debuggers beret? The color is my favorite and ive reported a couple bugs that youve fixed now ;3 I would greatly appreciate it. My steam is https://steamcommunity.com/id/TairikuOokami/

**Comment by SDGNelson** [comment]
For the next update the mannequin's body color will be used for hair as well.
