### ISSUE TITLE
Props going inside of other props.

### ISSUE THREAD

**Issue by Stalionn** [SmartlyDressedGames/Unturned-3.x-Community#2262]
So, me and my friends were building and stuff when we accidently set something down in the same spot, I don't know how long this bug has been around for so I decided to report it.

Video: https://www.youtube.com/watch?v=niJPeFXG_-k&feature=youtu.be 

Steam (Incase.): https://steamcommunity.com/profiles/76561199012846877/

**Comment by SDGNelson** [comment]
Thanks for the report, unfortunately this is a known issue yes: #1520. I am planning to properly sort it out in early 2021.
