### ISSUE TITLE
Skycrane bug

### ISSUE THREAD

**Issue by ZeroZeroHD** [SmartlyDressedGames/Unturned-3.x-Community#2263]
https://www.youtube.com/watch?v=5EPlaevMwzI so this is a bug that i discovered years ago but i never reported it for some reason
So this bug happens when a skycrane attaches its self to a vehicle and when someone builds on that vehicle the skycrane starts flying (this works on any vehicle)
my steam profile is this https://steamcommunity.com/profiles/76561198155367047/ (posting my steam profile maybe if i get the beret)

**Comment by SDGNelson** [comment]
Interesting find, thanks for the report. Might disable building on towed vehicles as a simple fix.

**Comment by ZeroZeroHD** [comment]
nelson is this bug find worth giving me the debugger's beret cause i really want it

**Comment by SDGNelson** [comment]
Sorry, but while all bug reports are appreciated, historically the Debugger's Beret was an extra-special show of appreciation to players who helped investigate multiple critical bugs. Unfortunately it has gotten a bit diluted over time, but anyone who truly earned it knows who they are.

**Comment by ZeroZeroHD** [comment]
its ok thanks for reviewing my bug found

**Comment by SDGNelson** [comment]
For the next update players cannot build on hooked vehicles anymore.
