### ISSUE TITLE
Clipping issue between spec-ops vest and alice pack

### ISSUE THREAD

**Issue by MaxSimpson** [SmartlyDressedGames/Unturned-3.x-Community#2265]
![image](https://user-images.githubusercontent.com/41491414/102914801-d6fd6280-444e-11eb-9c56-59b22ab6b980.png)
The top bar of the spec-ops bag face is the same as Alice pack side leading to the flickering of the faces. Only noticeable in 3rd person. If you have any more questions I can try to help more.

**Comment by SDGNelson** [comment]
Will adjust, but low priority.
