### ISSUE TITLE
Mythical affect problem. 

### ISSUE THREAD

**Issue by Stalionn** [SmartlyDressedGames/Unturned-3.x-Community#2266]
So what happened was, mythic normally show there affect around the cosmetic. In this case, the blood sucker mythical was kind of "inside" the cosmetic, not showing up around it. Other mythic I showed were showing the mythical affects around the cosmetic.

Video of problem: https://www.youtube.com/watch?v=_cq3SSvwaT0

Steam (If needed.): https://steamcommunity.com/profiles/76561199012846877/

**Comment by Stalionn** [comment]
Don't know if it's the same for some other mythic affects, but I hope it helps.

**Comment by SDGNelson** [comment]
This is only in the preview screen, not in-game. The reason is that the preview only captures fully opaque pixels.
