### ISSUE TITLE
Cant apply modifiers to weapons

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2267]
Ive noticed that I can only apply modifiers like Zero Kelvin and kill counters to skins when I first open the game. If I join a server and leave then I wont be able to do it anymore till I restart my game entirely.

**Comment by SDGNelson** [comment]
Thanks for the report! Will check into this for the next update.

**Comment by Tairiku-Ookami** [comment]
Do you think I could get the debuggers beret? The color is my favorite and I've reported a couple bugs that you've fixed now ;3 I would greatly appreciate it. My steam is https://steamcommunity.com/id/TairikuOokami/ And of course I will continue to find and report important bugs I spot to you.

**Comment by TH3AL3X** [comment]
> Do you think I could get the debuggers beret? The color is my favorite and I've reported a couple bugs that you've fixed now ;3 I would greatly appreciate it. My steam is https://steamcommunity.com/id/TairikuOokami/ And of course I will continue to find and report important bugs I spot to you.

it's that a joke?

**Comment by Tairiku-Ookami** [comment]
> > Do you think I could get the debuggers beret? The color is my favorite and I've reported a couple bugs that you've fixed now ;3 I would greatly appreciate it. My steam is https://steamcommunity.com/id/TairikuOokami/ And of course I will continue to find and report important bugs I spot to you.
> 
> it's that a joke?

No, But I think you are. <3

**Comment by SDGNelson** [comment]
Sorry, but while all bug reports are appreciated, historically the Debugger's Beret was an extra-special show of appreciation to players who helped investigate multiple critical bugs. I have been considering adding a more general purpose bug reporter thanks item, but considering what a nightmare the beret has become I am concerned it would make the situation worse.

**Comment by SDGNelson** [comment]
Should be fixed in the next update (tested). I am fairly confident that it was the same as the item alert cleanup bug.
