### ISSUE TITLE
"Infinity" as player name prevents joining servers

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2268]
Using "**Infinity**" as a **public/private name** will prevent the player from joining servers due to it being read as **just a number**.

**Comment by SDGNelson** [comment]
Interesting catch. 😮 
Safest not to change though because if parsing functions interpret that as a number (in this case float.TryParse) it may have unintended side effects with both the core game and plugins.
