### ISSUE TITLE
Is there a way to make the barricade visible from any distance (or at least from far away)

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2271]
I tried tinkering around with the LODs for my barricade, but it still disappears when Im 300 meters away or so. Is there a way to fix it and make my barricade still visible even from high distances. I dont really need it to be visible all across the Large sized map, just something around 500 unity length units.

**Comment by iBowie** [comment]
There is no way at this moment - they are coded in the way that they are not only not rendering, but don't exist on client.

**Comment by SDGNelson** [comment]
It might become configurable after further netcode rewrites next year, but iBowie is correct that they do not exist on the client past that point.
