### ISSUE TITLE
Shadows don't apply to everything

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2272]
Looks like shadows apply selectively in text, and most likely they apply only to English text.
I set shadow color to (255;0;0) and now i can see where shadows were applied and where weren't.
![shadows](https://user-images.githubusercontent.com/31174978/103093682-d5819500-461c-11eb-92b6-e2a282af9295.png)

**Comment by SDGNelson** [comment]
If you restart the game does it apply correctly? TMP creates new materials for dynamic fonts, so when the shadow color is changed the game is not finding the dynamically created materials.
