### ISSUE TITLE
UI of the plug-in, any new developments?

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#2273]
Are there any updates, such as progress bars, that move in 3D coordinates and are not broken
I do not speak English, I use the automatic translation, please forgive me

**Comment by SDGNelson** [comment]
There is no straightforward way to do progress bars or 3D UI yet, sorry. The next development for plugin UI at some point will be allowing the server to use the "glazier" UIs.
