### ISSUE TITLE
Server Ports.

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2276]
Hello could you please add possibility to specify gane ports because now you can specify only 1 and i need to specify all of 3 ports .

**Comment by SDGNelson** [comment]
Why do you need to be able to specify them separately? Currently it uses Port, Port +1, and Port +2. For example if you specify port 27018 then it will use 27018, 27019 and 27020.

**Comment by Dudewithoutname** [comment]
I have some problems with hosting etc.
Never mind anyway thanks for response.
