### ISSUE TITLE
Inspect bug 

### ISSUE THREAD

**Issue by GrandChefCookingMasterKocik** [SmartlyDressedGames/Unturned-3.x-Community#2278]
To replicate the bug you go into third person, inspect your gun, aim and go into first person.

https://user-images.githubusercontent.com/76628714/103158122-50f35b80-476f-11eb-867c-426326c5e0d8.mp4
_note: i have weapon fov set higher up so it wont look the same_

**Comment by SDGNelson** [comment]
Same problem as #2253, but I will leave this open because Alex closed that one. Low priority though

**Comment by SDGNelson** [comment]
I was wrong this is a separate problem: locally the player starts aiming, and then the inspect animation was confirmed by the server which interrupts the aiming animation. (not related to the perspective change) For the next update the player will locally start the inspect animation instead.
