### ISSUE TITLE
OnInventoryItemClicked

### ISSUE THREAD

**Issue by Adamv21** [SmartlyDressedGames/Unturned-3.x-Community#228]
Hi! Most people can probably recall to the minecraft times, right? 1 thing i personally loved to make (or see it working) was tje interactable GUI! This might not be as good as it was in minecraft But its still super useful! 

This event would be fired when someone clicked an item in the invetory (storage container as well) and when you just try to move it. 
It would have a ref bool cancel argument (and all the other essential arguments like page, x, y etc). It would have some effect (like in minecraft where it just pops back) which would look nice.

I would really appreciate IF This got added!

**Comment by Jonnyfencing1** [comment]
Another good one Adam

**Comment by SDGNelson** [comment]
What's your intended serverside use for this? Like prompting a player to select an item, and then waiting for the client->server clicked event? (closing, but subscribed to the issue)
