### ISSUE TITLE
Player Collision in Vehicle

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#2280]
Hi Nelson, I would like to ask if the player collider is disabled when the player enters the vehicle. I wanted to use the Collision Event Hook to detect the player seat position in the vehicle but it doesn't seem to trigger. Can you advise me on how can I get it to work?

**Comment by SDGNelson** [comment]
I would not recommend that approach even if it does maybe work because it will break when I get the chance to rewrite some of those systems. Would the VehicleEventHook work? If not, what does it need?

**Comment by SMDIndomitable** [comment]
The vehicleEventHook is awesome but is only available for the driver. Is it possible that you add the other seats as well?

**Comment by SDGNelson** [comment]
Hmm... one option could be an array on the component with seat indexes and corresponding events.

**Comment by SDGNelson** [comment]
Closing because ultimately the end goal is the same as #1958
