### ISSUE TITLE
Stuck at screen menu

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2281]
[_client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5744783/_client.log)

edit: Ignore those lines 
`Discarding old unacknowledged input packets (25/24)`
` Failed to find player: 1`
I'm just experimenting with my plugin

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix

**Comment by SDGNelson** [comment]
This particular case (item alerts) should be fixed in the next update
