### ISSUE TITLE
Losing my cosmetic top

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2282]
When restarting Unturned after a graphics crash my cosmetic top (I've tried different ones) is no longer equipped. I have to go into the inventory screen and re-equip it. 99% of the crashes occur when joining a server just after the,  "Area Inventory Life Clothing" line appears in the upper left hand corner.

**Comment by WCPistolPete** [comment]
Latest crash. Those darn boxcolliders.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5745840/Client.log)

**Comment by WCPistolPete** [comment]
One last note: Other cosmetics such as pants and hat are unaffected.

**Comment by SDGNelson** [comment]
After checking the related code I cannot imagine why this would happen because the selected items are only saved when exiting the survivors menu. Did this happen multiple times?

**Comment by WCPistolPete** [comment]
It's happened several times. I can't quite pin down the events that cause it. Start the game, join a server, go to place cosmetics on a mannequin, top missing. Leave game, equip, it's good for a while. Check the other servers, no issue. Crash, restart, still equipped. Check the servers again, all good. Stay signed in, come back a bit later, top no longer equipped. The last time I lost my top the events were: graphics crash, restart, new item in inventory (bulldozer hoodie), USA top no longer equipped. I'll keep an eye out and see if it's related to new inventory item awards.

**Comment by SDGNelson** [comment]
Since the IMGUI overlays (e.g. new item alert) do not block mouse clicks, perhaps you accidentally clicked in a spot that happened to be over top of your menu character's shirt? (Clicking the 3D menu character dequips items.)

**Comment by WCPistolPete** [comment]
Not caused by an errant mouse click.

I have confirmed that the game crashes are the sole cause of the loss of the cosmetic top. I 
don't lose it after every crash, but the crashes are the only cause.

99.9% of the time the crash is just after the "Area Inventory Clothing" phrase, the instant before the game environment screen would appear. I've sent the crash logs separately.
