### ISSUE TITLE
APC bug

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2283]
![20201228205909_1](https://user-images.githubusercontent.com/69295711/103234269-4ba13700-4950-11eb-8554-78093848e8d4.jpg)

Headlights don't have emission (that's not skin problem). Also there are no smoothing on skin. That's all.

**Comment by SDGNelson** [comment]
Thanks for the report. Will fix, but low priority.
