### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2284]
I had a pretty cool idea that you should make weapon skins be applied like the car skins. Where you can right click the gun and apply paintjob, also allowing it to be dropped and picked up by other players with your skin on it until it is despawned/scrapped/or unapplied.

**Comment by SDGNelson** [comment]
Unfortunately unlikely to happen unless items get a refactor, but that would be at least a year+ from now.

**Comment by Tairiku-Ookami** [comment]
Think about how cool that would be tho. Being able to let friends use yours skins, or even steal others skins during a raid. Until something like you losing it or a server wipe. Just keep it in mind ;3
