### ISSUE TITLE
Sandpiper model bug

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2285]
![image](https://user-images.githubusercontent.com/69295711/103234991-054cd780-4952-11eb-835e-9475913d47e4.png)

Something wrong with model of Sandpiper plane. Main wings placed wrong or something. It has open spaces in these bars

**Comment by SDGNelson** [comment]
Thanks for the report. Will fix, but low priority.
