### ISSUE TITLE
Wardrobe

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2286]
You should add some kind of wardrobe item that lets you change your cosmetics while in game. Perhaps also some armory for weapon skins or just letting the wardrobe do that too. Would be very cool and I think a lot of people would enjoy.

**Comment by SDGNelson** [comment]
It would be nice to support changing Steam items in-game, but there are a several things that would need cleaning up first. No ETA / low priority.
