### ISSUE TITLE
Vertical and horizontal item/barricade blocker

### ISSUE THREAD

**Issue by UserSqc101** [SmartlyDressedGames/Unturned-3.x-Community#2287]
Horizontal item/barricade blocker works past 4096 meters from map center but...
<img src="https://user-images.githubusercontent.com/76745950/103303327-bd43b880-4a16-11eb-9eba-16480a1aa0d3.png" data-canonical-src="https://user-images.githubusercontent.com/76745950/103303327-bd43b880-4a16-11eb-9eba-16480a1aa0d3.png" width="480" height="270" />

vertical does't have such strict border
<img src="https://user-images.githubusercontent.com/76745950/103303405-f2e8a180-4a16-11eb-88ec-34feb97cb8ef.png" data-canonical-src="https://user-images.githubusercontent.com/76745950/103303405-f2e8a180-4a16-11eb-88ec-34feb97cb8ef.png" width="480" height="270" />

https://user-images.githubusercontent.com/76745950/103303259-908fa100-4a16-11eb-89a6-8367851950fa.mp4

personally i would really appreciate if horizontal blocker worked the same way as vertical one 
or at the very least to have bigger area before items and barricades could be neither spawned nor placed

**Comment by SDGNelson** [comment]
Sorry, but none of the older systems are intended for use past the original 4km away from origin border. This is unlikely to change anytime soon unfortunately.
