### ISSUE TITLE
SDG.Unturned.DamageTool.getPlayerArmor acts strange

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2289]
![ELimb](https://user-images.githubusercontent.com/31174978/103349131-dfdcdc80-4abd-11eb-8259-99dd799af127.png)
Some of these limbs aren't actually used in getPlayerArmor method.
Used ones: LEFT_FOOT, LEFT_LEG, RIGHT_FOOT, RIGHT_LEG, LEFT_HAND, LEFT_ARM, RIGHT_HAND, RIGHT_ARM, SPINE and SKULL. 
Unused: LEFT_FRONT, RIGHT_FRONT, LEFT_BACK and RIGHT_BACK.

getZombieArmor also ignores these limbs.

**Comment by SDGNelson** [comment]
Front/back are only used by four-legged animals. Obviously an enum for the damage regions was an awful choice, but this is code from 2013-2014.
