### ISSUE TITLE
On(Barricade/Structure)Damaged

### ISSUE THREAD

**Issue by Adamv21** [SmartlyDressedGames/Unturned-3.x-Community#229]
Pretty self explanitory, right?

This is already possible But IT doesnt have a cancel bool + IT doesnt have the damager which could be very useful. Previous health and new health and the barricade ofc!

Would open up alot of Doors IF This got added <3

Thanks in advance

EDIT:
ref newHealth
Instead of
ref cancel
It would be a bit better for some people maybe?

**Comment by Jonnyfencing1** [comment]
definitely needed

**Comment by Adamv21** [comment]
Before people roast me. I’m aware this is possible already, I just want it inbuilt. More clean and more people can use it.

**Comment by Adamv21** [comment]
Because Nelson apparently hasn't seen this thread / ignore it I can post source to do it yourselfs I guess.

```    [HarmonyPatch(typeof(SDG.Unturned.StructureManager), "damage")]
    public class DamageStructurePatch
    {
        public delegate void StructureDamaged(Transform structure, Vector3 direction, float damage, float times, bool armor, ref bool cancel);
        public static event StructureDamaged OnStructureDamaged;

        [HarmonyPrefix()]
        public static bool Prefix(Transform structure, Vector3 direction, float damage, float times, bool armor)
        {
            bool cancel = false;
            OnStructureDamaged(structure, direction, damage, times, armor, ref cancel);
            return invert(cancel);
            
        }

        public static bool invert(bool boolean)
        {
            if (boolean == false) return true; else return false;
        }

    }``` This code requires Harmony, you also have to patch it. This works for Barricades and vehicles too.

**Comment by SDGNelson** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/261
