### ISSUE TITLE
SDG.Unturned.DamageTool.getPlayerExplosionArmor doesn't count every single part of clothing

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2290]
Right now it only counts pants, shirt, vest and hat, despite the fact that every single clothing type has explosionArmor since they all derive from ItemClothingAsset

**Comment by SDGNelson** [comment]
Backpacks, masks, and glasses do not provide non-explosive armor either. An argument could be made that perhaps backpacks should provide armor from behind, and masks/glasses should count towards head armor, but as-is this is intentional.
