### ISSUE TITLE
PSA: 3.21.1.255 on the Preview Branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2291]
In case you are interested, the next update is now on the preview (public test) branch. Here is the pending changelog:

### Added
- Command-line flag "-AggressiveGC" (test).
- BattlEye disabled warning opens the BattlEye directory on Windows.

### Changed
- Increased gesture menu spacing to accomodate longer non-English strings.
- Profanity filter matches leetspeak replacements.
- Banned workshop files are shown with red name.
- Steam inventory page buttons loop around.
- Server rejects building on constrained vehicles. (e.g. hooked by skycrane)

### Fixed
- Entering vehicle while unable to stand up from crouch/prone.
- Devkit cursor IMGUI implementation.
- Item alert exception after regular text alert.
- Off-by-one error loading empty character name.
- In-game group overlay cleanup exception.
- Browser request exception after re-joining server.
- Server groups exception when received before UI after re-joining server.
- Dishwasher intersecting wall at a Yukon campsite.
- Navmesh gap between lights and Germany barracks.
- Taking a point of radiation damage after respawning from deadzone.
- Editing signs that have been destroyed while typing.
- Mannequin hat hair color matches body color.
- Stay crouched while resting with hold crouch mode, and next press exits rest.

**Comment by warren39** [comment]
UI works well. But there still some exceptions:
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5757613/Client.log)

**Comment by SDGNelson** [comment]
Glad to hear it, and thanks for the log! The exception in this log is one of the sanity checks I introduced not taking into account pooling fortunately.
