### ISSUE TITLE
Ignore_Children_File_IDs

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2292]
I am posting on behalf of another.
Currently the server that was run by her, there are IDs placed within the [] of this tag.
(Dependencies stated from another 2 mods the server is subbed to.)
Looking at the log files, it seemed to work the first time round as it wasn't queued. (but it didn't seemed ignored either as no line states that)
Immediately after the first pass, the server did a second pass and downloaded the dependencies stated within the tag anyway.

Was wondering if there was any particular way the IDs of the mods to be ignored should be typed, or it is good enough that it was typed the same way as the IDs to be downloaded (File_IDs)?

**Comment by SDGNelson** [comment]
They are typed the same way as File_IDs, yes. 
To clarify: it will skip the children of the provided file IDs, not those file IDs themselves. During the query process it will say "Ignoring ### children of (ID)"

**Comment by Ongjming** [comment]
Thanks I will convey this to her :)
From her logs that she showed me, there wasn't a line saying "Ignoring ### children of (ID)" so probably there might be something missing somewhere.
The ids typed there are the children (dependencies stated) of the mods that the server is subscribed to.

Just in case, the mods with dependencies in question are
https://steamcommunity.com/sharedfiles/filedetails/?id=1629340468
and
https://steamcommunity.com/sharedfiles/filedetails/?id=2077990646

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
