### ISSUE TITLE
Vendor NPCs not working

### ISSUE THREAD

**Issue by ZapperPlayz** [SmartlyDressedGames/Unturned-3.x-Community#2293]
Every time I go to talk to my NPCs they dont allow anybody to go and access there vendor shops I've been working on them for quite a few days now and cant seem to figure out why my NPCs wont allow anyone to purchase any of the items nor be able to go into there shops it would be much appreciated if you could get ahold of me and help me fix this issue thank you

**Comment by SDGNelson** [comment]
If you look in the Menu > Workshop > Error Logs list are there any warnings?

**Comment by ZapperPlayz** [comment]
I wouldnt know because I was told to use Bowied NPC maker cause I couldnt figure out how to do it with the files

**Comment by ZapperPlayz** [comment]
I'm going to send you them give me a minute

**Comment by ZapperPlayz** [comment]
(VendorAsset)01289ba854de49dfab6fedb743741a5e_4024[4024]:short ID is already taken by (VendorAsset) Farmer_NPC_Shop

They all say the same thing except the ID and farmer shop thing and the long number is all changed for them all but same error

**Comment by ZapperPlayz** [comment]
Sorry it took so long my unturned loads up slow I run it on a laptop

**Comment by iBowie** [comment]
It means that ID is taken, you better try to change both GUID and ID to new values.

**Comment by ZapperPlayz** [comment]
Well idk how they are taken because I made the NPCs both of them and even took out the old ones even better deleted the whole workshop of the NPCs I made and completely went and Remade there dialogue and character ID idk y I get that error

**Comment by iBowie** [comment]
Just change IDs

**Comment by ZapperPlayz** [comment]
For the Vendors?

**Comment by SDGNelson** [comment]
Thanks for helping @iBowie, yes the problem is that asset IDs must be unique.

**Comment by ZapperPlayz** [comment]
Thank you is there a certain range for them? I also wanted to say they weren't visible for some reason I don't know if that could be the case

**Comment by SDGNelson** [comment]
For annoying reasons the range is 2001-65535.

**Comment by ZapperPlayz** [comment]
Good to know thank you I'm going to go and test them now I finished changing all the IDs
