### ISSUE TITLE
Mannequin Issue

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2295]
When the mannequin is set to mirror the gears on the piston pack are inverted so you can see the inside.
![image](https://user-images.githubusercontent.com/75531507/103442765-c56e4480-4c1e-11eb-9416-80d6929371ef.png)
![image](https://user-images.githubusercontent.com/75531507/103442766-cd2de900-4c1e-11eb-8430-185f681ed909.png)

**Comment by SDGNelson** [comment]
Thanks for the report. Will fix!
