### ISSUE TITLE
Some mod hooks ideas

### ISSUE THREAD

**Issue by UserSqc101** [SmartlyDressedGames/Unturned-3.x-Community#2296]
Would be useful for CollisionEventHook to utilize other layers and tags instead of just player and TextChatEventHook to work in handheld items in firstperson

**Comment by Alex-Well** [comment]
I and many other modders have suggested this to Nelson several times already. I even have a ready-made script that can only be added to the game. Unfortunately, Nelson does not understand that modders are not using CollisionEventHook for their intended purpose.
```csharp
using UnityEngine;
using UnityEngine.Events;

namespace SDG.Unturned
{
	public class ExtendedCollisionEventHook : MonoBehaviour
	{
		public string objectTag;

		public UnityEvent OnColisionEnter;

		public UnityEvent OnColisionStay;

		public UnityEvent OnColisionExit;

		private void OnTriggerEnter(Collider other)
		{
			if (other == null)
				return;

			if(!string.IsNullOrEmpty(objectTag) && !other.CompareTag(objectTag))
				return;

			OnColisionEnter.Invoke();
		}

		private void OnTriggerStay(Collider other)
		{
			if (other == null)
				return;

			if (!string.IsNullOrEmpty(objectTag) && !other.CompareTag(objectTag))
				return;

			OnColisionEnter.Invoke();
		}

		private void OnTriggerExit(Collider other)
		{
			if(other == null)
				return;

			if (!string.IsNullOrEmpty(objectTag) && !other.CompareTag(objectTag))
				return;

			OnColisionExit.Invoke();
		}
	}
}
```
For example, we can place a CollisionEventHook inside a car with a slot for setting up a barricade. This barricade will simulate the player in the collider, which will allow the function to be activated inside the car when the barricade is placed on it. For example, without plugins, we can assign different physical properties to the car depending on the installed engine. This method is universal and allows you to associate activations within any objects whose colliders intersect.
A video of my friend in which the above method is applied. (This is no plugins, just logic) https://youtu.be/c1Mrvggphh8
Nelson does not understand the importance of this script, and if in future updates he abandons the tags, many of these mods will be broken. Nelson, we need a universal working method that won't break in the future.

**Comment by SDGNelson** [comment]
Alex, as you briefly mention in your post and as I explained when you asked about it, a system based on gameObject.tag will not be added because the usage of gameObject.tag should be reduced over time.

In the long term it may be useful to have something along the lines of https://docs.unrealengine.com/en-US/ProgrammingAndScripting/Tags/index.html

**Comment by UserSqc101** [comment]
little offtopic
Nelson you cheeky bastard
0.810045 is very specific number

**Comment by Alex-Well** [comment]
Hopefully in the future you will not break CollisionEventHook and it will continue to work on GameObjects that only simulate player properties with a Player tag. As a reminder, many modders use CollisionEventHook in this way. I even have a whole logical system built on this mechanics.

**Comment by SDGNelson** [comment]
Cheeky number? 😕 

> As a reminder, many modders use CollisionEventHook in this way. I even have a whole logical system built on this mechanics.
Oof. This is exactly why I am cautious adding new components like this. 👀

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
