### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by z1net** [SmartlyDressedGames/Unturned-3.x-Community#2297]
![Screenshot_1](https://user-images.githubusercontent.com/65300126/103464655-2476ab00-4d3e-11eb-849d-1ac11c430267.png)
![Screenshot_2](https://user-images.githubusercontent.com/65300126/103464656-250f4180-4d3e-11eb-9626-05444988b086.png)

**Comment by SDGNelson** [comment]
Sorry about this. Same as #2213. In this past Friday's update I fixed several more potential cases and added hundreds more sanity checks, but since it is still happening I will rework how those are pooled in the next update.
