### ISSUE TITLE
Unturned.exe parameter to disable certain modules

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#230]
It would be very helpful to have the ability to disable certain modules, such as RocketMod, on a certain server. For example, in the Shortcut of Unturned.exe it would look like `Unturned.exe -nographics -batchmode +disableModule/RocketMod +secureServer/MyServer` or something like that. I'm not exactly sure that's how it would work, but that ability would be extremely helpful.

**Comment by Trojaner25** [comment]
Why would this be needed?

**Comment by N1GHTPATROL** [comment]
Multiple servers on one install of Unturned. Cleaner, more efficient, and synchronous with some custom stuff of mine.

**Comment by Trojaner25** [comment]
It would be better if you can specify which modules to use in config.json, instead of command line

**Comment by SDGNelson** [comment]
Off the top of my head config.json is probably loaded far after the modules. This sounds like a useful feature.
