### ISSUE TITLE
Map optimization

### ISSUE THREAD

**Issue by clbt404** [SmartlyDressedGames/Unturned-3.x-Community#2300]
All Vanilla map objects should be under one texture to prevent lag issues with detailed maps. + SpeedTrees are super un-optimized. Combining those two, detailed maps with thick forests cause massive lag especially on servers.

**Comment by SDGNelson** [comment]
The game does have custom runtime batching for map objects, but it was disabled a few years ago. After some of the recent optimizations it might be worth trying again. SpeedTrees will probably be removed at some point.
