### ISSUE TITLE
Invisible people

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2301]
Invisible user in the server, some players have previously reported it and today I have been able to verify it. Just in case, the server has 56 slots, at this moment it was full and with a queue, I don't know if it will have anything to do with it, but it is relevant data. It mainly happened after this update, I dont know 
I don't know if it's her fault, first time I see an invisible player. 
It has no administrator and I have been able to verify that it was not in vanish or anything. He was a completely normal user, I gave him a car to show that he was invisible.

https://user-images.githubusercontent.com/75626024/103585812-14003500-4ee4-11eb-8cfa-bf7b3a78e988.mp4

**Comment by SDGNelson** [comment]
In this issue #1997 there was talk of it being related to plugins bypassing the max players limit, so considering the 56 slots it could be related. I am hoping that some of the netcode improvements planned for early this year will help narrow down remaining network errors like this.
