### ISSUE TITLE
Request for projectile guns to use magazine's explosion override

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2303]
Title. But for further explanation, if a military fragmentation magazine is loaded into a gun, the impact has a small explosion.

But because of how it works, it does not have the render distance capability of a projectile weapon like the rocket launcher, which from testing, always renders on a certain distance given to the explosion effect in Unity. 

The reason I reported this is because it makes explosions created by ballistic weapons to render at longer distances & to play sounds throughout long distances. I rely on the ballistic system for my grenade launchers to make them register hits consistently & more importantly, to also switch explosion effects back & forth, which is not on the projectile system (which would make more sense here, & in fact, should have been here by now).

**Comment by SDGNelson** [comment]
IIRC a setting was added for that distance, so I will mark this as next update to remember to double-check that.

> to also switch explosion effects back & forth, which is not on the projectile system (which would make more sense here, & in fact, should have been here by now).

Can you clarify what you mean by this please?

**Comment by SDGNelson** [comment]
Double-checked and yes, if your effect has `Relevant_Distance` set then it will override the gun default.

**Comment by OneManOperative** [comment]
> Double-checked and yes, if your effect has `Relevant_Distance` set then it will override the gun default.

Can you give a rundown on what this does? Despite looking easy to use, the U3 Docs tend to not give guides about the latest additions to the game.



> IIRC a setting was added for that distance, so I will mark this as next update to remember to double-check that.
> 
> > to also switch explosion effects back & forth, which is not on the projectile system (which would make more sense here, & in fact, should have been here by now).
> 
> Can you clarify what you mean by this please?

It is the basically the item data that military fragmentations have. They change add explosions & change the impact effects of raycasted projectiles if they hit something.

**Comment by SDGNelson** [comment]
The docs repo should be completely up-to-date on any of the features that are included there, but since it was started much later in development there are lots of undocumented features like the effect assets.

Relevant_Distance is measured in meters, and determines how far away players can be before the effect should not be sent to them.

> It is the basically the item data that military fragmentation magaziness have. They add explosions & change the impact effects of raycasted projectiles if they hit something.

If I understand correctly you are requesting that magazines can override the explosion effect for projectile weapons?

**Comment by OneManOperative** [comment]
> The docs repo should be completely up-to-date on any of the features that are included there, but since it was started much later in development there are lots of undocumented features like the effect assets.
> 
> Relevant_Distance is measured in meters, and determines how far away players can be before the effect should not be sent to them.
> 
> > It is the basically the item data that military fragmentation magaziness have. They add explosions & change the impact effects of raycasted projectiles if they hit something.
> 
> If I understand correctly you are requesting that magazines can override the explosion effect for projectile weapons?

Well said. That is what I'm referring to. Would there also be a possibility to try to optimize the hit registration of projectiles if they travel quicker than the vanilla Rocket Launcher?

**Comment by SDGNelson** [comment]
The only option for fast physics projectiles is CCD, which the game enables by default IIRC. For ballistics system is much better for that than physics objects.

**Comment by OneManOperative** [comment]
That's by all means alright. So is it possible to override explosion effects for the projectile weapons at least?

**Comment by SDGNelson** [comment]
No, currently only the gun explosion is used, sorry. Might make sense to use the magazine explosion in that case though.

**Comment by OneManOperative** [comment]
> No, currently only the gun explosion is used, sorry. Might make sense to use the magazine explosion in that case though.

That is unfortunate. Although, as a final question, will we ever see this apply to projectile models as well?

**Comment by SDGNelson** [comment]
Magazine replacing projectile model? Would mean the magazine needs to load a projectile prefab as well. Maybe I should make a field day of it someday and add an MGL too.

**Comment by OneManOperative** [comment]
That sounds promising. Well thank you for giving a say on this issue. It would aid a lot of modders like me to create more pleasing items for the community.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
