### ISSUE TITLE
Trophy Cases

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2304]
Trophy cases need to be 3 slots tall so I can display my absolute beast of a weapon the Hell's Fury. Also its kinda dumb that a massive trophy case has the same storage size as a tiny rifle rack.

**Comment by SDGNelson** [comment]
Fair point. For tomorrow's update I have increased their storage height from 2 to 3, and adjusted their crafting requirements accordingly.
