### ISSUE TITLE
steamclient.so issues

### ISSUE THREAD

**Issue by Kiteflow** [SmartlyDressedGames/Unturned-3.x-Community#2305]
Hi there,
I keep on experiencing errors when trying to run my unturned server on Ubuntu.
I've tried Ubuntu 16.04, 18.04 and 20.04 and it is all the same error.
```
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
dlopen failed trying to load:
/root/.steam/sdk64/steamclient.so
with error:
/root/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /root/.steam/sdk64/steamclient.so
Setting up 1 worker threads for Enlighten.
```

I've checked and there doesn't appear to be a /.steam/sdk64 folder, so I don't know what the issue could be

Thanks

**Comment by TH3AL3X** [comment]
Just change the directory to ur /root/.steam/steamapps/common/U3DS/Linux64/steamclient.so
Be careful with capitals too...

**Comment by SDGNelson** [comment]
Are you using steamcmd (recommended) to download/update the dedicated server? By default steamcmd should be including and keeping those files up to date.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.

**Comment by Hagvan** [comment]
I am having the same issue. I made a server before and it all worked alright first try. 

At first, I tried to make a second instance using the same game files but it crashed the first server which was running.
After that, I downloaded the entire server to a different folder, tried there, and got the issue mentioned here.
Lastly, I tried to download to a whole different user, and still no success.

**Comment by SDGNelson** [comment]
@Hagvan getting this error after copying the game to a different folder would suggest it cannot find the Steam libraries anymore. One option would be to copy within the steamapps folder so that the relative path is the same.

**Comment by Hagvan** [comment]
I didn't copy it though, I installed another server using force_install_dir.

**Comment by SDGNelson** [comment]
Hmm maybe only the regular Steam client can find the Steam install dir... anyway, one workaround might be to direct force_install_dir to the steamapps folder.

Though Steam should be downloading steamclient.so into the U3DS/linux64 directory as well, so I wonder are you using the force 32-bit option as well? (Unturned dedicated server is 64-bit only)

**Comment by ReedEggleston** [comment]
Howdy, just ran into this issue tonight. 
I took a wild guess that it was looking for this file:  /.steam/steamcmd/linux64/steamclient.so
Made the /.steam/sdk64 directory and copied that file to it.
It worked. 👍🏻

**Comment by kantraksel** [comment]
We are looking at the second error, but more important is the first one. Unturned x64 is distributed with steamclient.so x86. Replacing it with 64bit version (from steamcmd files) makes it working again. Tested on Ubuntu 20.04

**Comment by amorous-monk** [comment]
cp ~/.steam/steam/linux64/steamclient.so ~/.steam/steam/linux64/

**Comment by ibrahim-totten** [comment]
i just made a symbolic link to the actual location of the file in the directory it was trying to look in, because i was using a snap pack (ik, I'm sorry, i was just trying to download steam asap), and it worked
ln -sr *source_.steam* *the_location_its_asking_for_.steam*

**Comment by wistox07** [comment]
I tried this and it worked
ln -s /home/wistox07/.steam/debian-installation/linux64/steamclient.so /home/wistox07/.steam/sdk64/steamclient.so
--------------------------------------------------------------------------------------------------------------
[S_API] SteamAPI_Init(): Loaded '/home/wistox07/.steam/sdk64/steamclient.so' OK.

**Comment by metacop** [comment]
my solution

log in as root

su root
cd /home/steam
steamcmd
...it will download files again
exit

we must create the .steam and sdk64 folder

cd /root
mkdir .steam
cd .steam
mkdir sdk64

ln -s /root/.local/share/Steam/steamcmd/linux64/steamclient.so /root/.steam/sdk64/

**Comment by EntityinArray** [comment]
This issue is still occurring, any plans to fix this? Why is the issue closed?

**Comment by arthurcrm** [comment]
Same issue here.

SwitchToLoop levelload requested:  id [2] addons []
SV:  Level loading started for 'de_mirage'
CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
SwitchToLoop game requested:  id [2] addons []
SteamGameServer_Init()
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/ubuntu/.steam/sdk64/steamclient.so
with error:
/home/ubuntu/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or 
directory
[S_API] SteamAPI_Init(): Failed to load module '/home/ubuntu/.steam/sdk64/steamclient.so'
Failed to initialize Steamworks SDK for gameserver.  Failed to load module '/home/ubuntu/.
steam/sdk64/steamclient.so'
 0 Failed to initialize Steamworks SDK for gameserver.  Failed to load module '/home/ubunt
u/.steam/sdk64/steamclient.so'

Segmentation fault (core dumped)

**Comment by GazziFX** [comment]
> Same issue here.

But its Unturned related thread not CS2

**Comment by AlaskanDruid** [comment]
Yep. Bug still exists.

**Comment by aurorapar** [comment]
Was having some issues with another server through steamcmd. When linking steamclient.so make sure to specify the absolute path to steamclient.so, not just a relative one.

**Comment by azadbilge** [comment]
solved after 2 days consuming.

I see many path discussed in internet. probably all was correct. however, for today, find your steamclient.so by 
`find / -name steamclient.so 2>/dev/null`
and link it where it is wanted to be
```
mkdir -p /home/steam/.steam/sdk32 && \
ln -s /home/steam/server/steamclient.so /home/steam/.steam/sdk32/steamclient.so 
```
and you will see
> S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
