### ISSUE TITLE
uh an issue with hitsounds :[

### ISSUE THREAD

**Issue by absolutestfu** [SmartlyDressedGames/Unturned-3.x-Community#2307]
so all of the sudden my hitmarker sounds just go BRRR, its the weirdist thing o_o

https://user-images.githubusercontent.com/40752712/103961691-ebc73f00-514c-11eb-8d7e-abcbd4272d4a.mp4

**Comment by Coopyy** [comment]
not appropriate.

**Comment by N1GHTPATROL** [comment]
please delete this is offensive just like pogchamp emote>:(
