### ISSUE TITLE
Probably a minor stuff, with regards to Ladder placement.

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2309]
I just noticed after the latest update but I am not sure if this has been like this for a long while or was it intended.
(but I vaguely remembered that ladder used to not pass through objects/barricades).

![Ladder cannot fixed on barricades nor object ladders 2](https://user-images.githubusercontent.com/28900564/104048755-bdb22f80-521e-11eb-83d4-9da9e94b08fc.png)
![Ladder cannot fixed on barricades nor object ladders 3](https://user-images.githubusercontent.com/28900564/104048760-bf7bf300-521e-11eb-90fc-3fd8670450bd.png)
![Ladder cannot fixed on barricades nor object ladders](https://user-images.githubusercontent.com/28900564/104048761-c0ad2000-521e-11eb-8e77-9a6ce8caa735.png)

The middle screenshot shows the same thing in single player (Germany map). The other 2 is from multiplayer server.
The last screenshot shows that ladder can only interact with the sides of a map object ladder unlike buildable ladders (which it still snaps together fine).
The first screenshot shows that the ladder doesn't even show up on a large metal plate (barricade).
Middle screenshot shows that the ladder can still be build on the ground where the generator is at. The large pine plate blocks the build but the ladder placeholder outline just passes through it instead of snapping onto it.

Ladders so far snaps to each other fine (barricade ladders), and snaps to sides of object walls/buildings and structures fine.

EDIT: The picture order seemed correct but I tried to make the pic small, they still turned out to be quite huge, sorry for the messy display.

EDIT2: I didn't realised that a bit after this was posted, there was a new unturned update. I didn't test this in the new version yet.
The above behaviours were observed in the version prior to this latest one.

**Comment by SDGNelson** [comment]
Thanks for the report. For whatever reason this does appear to be intentional - ladder placement ignores barricades, and it looks like this has not changed for at least 3 years (ran git blame). Whether it should be changed to allow placing ladders on the sides of barricades... I am unsure / hesitant, but open to feedback if you want to lobby for that on the forum.

**Comment by Ongjming** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2416803973
I fiddled a bit and made a work about for ladders placement onto barricades.
The ladderbracket item in the mod have the "Climb" slot so that ladder can then be placed at wherever the Cagelight type item can be placed.
Just wanted to type this since managed to find a work about within the current building intended feature.

Thanks!
