### ISSUE TITLE
Bullet casings fall forever

### ISSUE THREAD

**Issue by Hexadec1ma1** [SmartlyDressedGames/Unturned-3.x-Community#231]
https://www.youtube.com/watch?v=-YpEkdosTgY&feature=youtu.be

**Comment by DieselsiselMedia** [comment]
It's because the Unturned playermodel camera renders certain layers above everything else. The same reason why weapons don't clip through walls in first person. A solution to this would be to layer the bullet casing effect with a layer the playermodel camera doesn't put above everyhting else.

**Comment by DieselsiselMedia** [comment]
Correct me if I'm wrong I should add.

**Comment by SDGNelson** [comment]
Diesel is right! Unfortunately this isn't easily resolved. For 4 I have two copies of the bullet casings - one for first person and one for third person both of which collide with the world.
