### ISSUE TITLE
Player stance upon exiting water

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2310]
Prior to this patch, and for as long as I can remember: No matter the player's stance upon entering water and swimming, when exiting the player was standing and able to run. Now when the swimming player returns to the shoreline, but is still in the water, the player can run, but clear the waterline and the player reverts to the stance prior to entering the water.

**Comment by SDGNelson** [comment]
Thanks for the report. The "wants to prone/crouch" input flag is probably not being reset while swimming. Will fix.

**Comment by SDGNelson** [comment]
Fixed for the next update.
