### ISSUE TITLE
Cant get experience to be servers currency

### ISSUE THREAD

**Issue by ZapperPlayz** [SmartlyDressedGames/Unturned-3.x-Community#2311]
I've got uconomy installed and I cant seem to figure out why every time I kill a zombie I dont get the 45 experience I have set but it gives me it in a different experience currency yet I have tried multiple times to change it from XP to were it says you got so and so amount of experience from a zombie and that experience can be used on there player but instead it adds it as if it were there balance and doesnt allow them to use it could you help me with this?

**Comment by SDGNelson** [comment]
You might be able to get help with this in one of the plugin / hosting communities. I cannot help with plugin configuration sorry.
