### ISSUE TITLE
How to reset the display resolution

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2316]
![screen](https://user-images.githubusercontent.com/64722485/104144317-b6954800-53fd-11eb-9ef3-6d1dfa16f1cc.png)

Cannot click Configure button.

**Comment by MoltonMontro** [comment]
Edit the following file:

`...\Steam\userdata\...\304930\remote\Settings\Graphics.json`

By default, "UserInterfaceScale" should be set to "1", and "Resolution" should be set to your monitor's native resolution.

**Comment by warren39** [comment]
It works! Thanks.
