### ISSUE TITLE
Players and vehicle fell through the ice on Yukon

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2318]
Two players in one vehicle reported a "square" that didn't render near the docks. As the vehicle passed over, it fell through the ice. I couldn't duplicate the issue but they did point out the exact spot. Position coordinates 782.19 62.25 322.70. I teleported them out but the vehicle was stuck below, even with my ramp of freedom.
![20210111000842_1](https://user-images.githubusercontent.com/53093137/104152068-8f625a80-53ac-11eb-9f2f-45bf83a8a765.jpg)
![20210110235813_1](https://user-images.githubusercontent.com/53093137/104152069-8ffaf100-53ac-11eb-95ad-e55eb5b3a00a.jpg)

**Comment by SDGNelson** [comment]
Nice ramp of freedom haha!
My guess is that the square of ice did not load in on the client while they were driving over it, and the server could not fix them up because technically the ice is not ground. For the next update I will see about raising up the terrain underneath the ice patches.

**Comment by SDGNelson** [comment]
Changed for the next update.
