### ISSUE TITLE
Projectiles with high velocity have very bad collision on thin objects, terrain & resource

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2319]
A large problem regarding projectiles from a gun item is their collision on most objects, terrain & resource if they travel too fast. It just phases through them instead of colliding & creating an explosion effect.

Not too long ago, Nelson mentioned there is CCD that is active by default in the game. Apparently, it doesn't work too well & the problem persists.

I'm not sure how this would be dealt with, but it is too persistent to leave behind. It is kind of a growing problem IMO.

**Comment by SDGNelson** [comment]
You can enable CCD on the projectile prefab, but it looks like CCD by default was only changed for throwables and fishing rods. Will enable by default for guns.
