### ISSUE TITLE
Steam overlay not working.. Still

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#232]
So its been some time since steam overlay stopped working. I am not sure if @SDGNelson know it or not, but it would be really nice to fix it ASAP. Also not sure if its really unturned related, but from what I saw, its working on other games.

**Comment by MoltonMontro** [comment]
This is a BattlEye issue.

"Unfortunately a side effect of the BattlEye upgrade to enhance anti-cheat measures has been blocking the Steam Overlay from hooking into Unturned. The BattlEye team is aware and has been continuing to work on a fix, but from the sounds of things it's a tricky problem. They're confident it's possible, however."

**Comment by Jonnyfencing1** [comment]
@baranmod please check other issues before opening a new one that is the same as one that has already been discussed in length
