### ISSUE TITLE
[Feature Request] UI suggestions

### ISSUE THREAD

**Issue by muertoof** [SmartlyDressedGames/Unturned-3.x-Community#2323]
Hey Nelson. As everyone knows, plugin developers are provided with rather meager functionality to serve up the UI's. And so I'd like to ask you to add some convenient functions for us, if this does not bother you and does not entail any problems.

`.askEffectClearByKey(short key, CSteamID steamID)` - I'm not the first to suggest it, but it'll be quite useful for server developers where many UI elements are used with different keys.

`.CheckEffectChildVisibility(short key, CSteamID steamID, string childName)` - Those who have developed complex UI's may have encountered this problem, for example, when creating any notifications in the interface, like an error or confirmation of something. To remove the old notification, we have to completely hide all possible notifications in order to correctly display the new one (hope I explained it understandly :D). The condition would simplify this process.

`.CheckEffectVisibility(ushort id, CSteamID steamID)` - Works similarly to the previous suggest, but relates to the effect, not the child. Checks if the effect is sent to the player.

`.setUIEffectImageColor(ushort key, CSteamID steamID, bool reliable, string childName, string colorString/UnityEngine.Color color)` - Changes the color of the image.

Also implement functionality for progress bars. Many are waiting for it

If anyone has any ideas on my suggest, please complete it. Thanks for attention!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
