### ISSUE TITLE
Server Hosting and Workshop Mods

### ISSUE THREAD

**Issue by Puruuuu** [SmartlyDressedGames/Unturned-3.x-Community#2326]
Workshop Mods, they won't spawn naturally on my server. I downloaded them via WorkshopDownloadConfig.json
But they spawn naturally on singleplayer.

I have tried it also by adding the files manually to the server, in other files, like bundles, etc...

But nothing seems to fix it.

**Comment by SDGNelson** [comment]
On the same map as in singleplayer? Can you attach the server log please? (inserting the mods into default spawns should be logged)

**Comment by Puruuuu** [comment]
Which logs do you mean, rocket or?

**Comment by Puruuuu** [comment]
[Rocket.1610632552.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5815981/Rocket.1610632552.log)

**Comment by Puruuuu** [comment]
[Server_Default.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5816027/Server_Default.log)

**Comment by SDGNelson** [comment]
Thanks for the logs, yes Server_(name).log is the correct built-in log. Anyway the relevant line is:

`Link spawns: 7 children, 827 sorted/normalized and 753 parents`

Which means that 7 mod spawn tables have inserted themselves into parent spawn tables (probably vanilla). There are no warnings about finding parent spawn tables, so I think it is probably working as intended. What seems to be the problem?

**Comment by Puruuuu** [comment]
They don't spawn normally, the workshop mod developer added spawns for vanilla maps. And they do not spawn. I have to spawn them in myself.

**Comment by SDGNelson** [comment]
Which workshop file is it?

**Comment by Puruuuu** [comment]
Every one of them that has default spawns. But now it should only be WindCars2 ( https://steamcommunity.com/sharedfiles/filedetails/?id=2309977886 ) and Sly's Weapon pack ( https://steamcommunity.com/sharedfiles/filedetails/?id=2284489843 )

**Comment by SDGNelson** [comment]
I added a command-line option to log spawn changes, and enabled that weapons pack on a test server. These were the insertions:
Spawn Hellfire_all inserted into Peaks_Coalition_Low_Peaks
Spawn Hellfire_all inserted into Peaks_Guns_Peaks
Spawn Hellfire_all inserted into Peaks_Military_High_Peaks
Spawn Hellfire_all inserted into Peaks_Military_Low_Peaks
Spawn Hellfire_all inserted into Peaks_Prison
Spawn Hellfire_all inserted into Peaks_Special_Low_Peaks
Spawn Hellfire_all inserted into Peaks_Syndicate
Spawn Hellfire_all inserted into PEI_Military_Canada
Spawn Hellfire_all inserted into Russia_Guns_Russia
Spawn Hellfire_all inserted into Russia_Military_Low
Spawn Hellfire_all inserted into Russia_Police_Low
Spawn Hellfire_all inserted into Washington_Guns_America
Spawn Hellfire_all inserted into Washington_Military_America
Spawn Hellfire_all inserted into Yukon_Research

That's more than the 7 mentioned in your log, so it might be worth validating your files with steamcmd in case something is missing.

**Comment by Puruuuu** [comment]
Hmm, okay. Ill mess around a bit more, and see if it starts working or not.

**Comment by Puruuuu** [comment]
Yeah, my files are all validated, I even re-downloaded the workshop mods 5 times, but still nothing.

**Comment by SDGNelson** [comment]
Hmm... I'm not sure what else to suggest for the meantime, but that extra logging in the next update (probably the 22nd) might highlight something. If you would like to try it now you can temporarily download the preview version of the dedicated server (-beta preview) and add this to the server command line arguments: -LogSpawnInsertions

**Comment by Puruuuu** [comment]
Okay, I'll just wait for the update to come on the 22nd since I have to think of an alternative. If it gets a fix after the 22nd update, I'll prob keep mods, but if the update won't say the reason, ill just have to switch to vanilla.

**Comment by Puruuuu** [comment]
[Server_Default.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5974466/Server_Default.log)

Lets try it again now, this is the newest log, after i updated the server.

**Comment by Puruuuu** [comment]
I know it took so long, but I kinda gave up with it at one point.

**Comment by SDGNelson** [comment]
It looks like the "-LogSpawnInsertions" command-line option was not enabled in that log. If you can re-upload the log after enabling the option there may be more details.

**Comment by Puruuuu** [comment]
[Server_Default.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5976246/Server_Default.log)

**Comment by Puruuuu** [comment]
There ya go. Should have it now

**Comment by SDGNelson** [comment]
According to the log these are the spawns being modified:
Spawn Wind_Cars_2_Civilian inserted into Peaks_Civilian_Peaks
Spawn Wind_Cars_2_Civilian inserted into PEI_Civilian_Canada
Spawn Wind_Cars_2_Civilian inserted into Russia_Civilian_Russia
Spawn Wind_Cars_2_Civilian inserted into Washington_Civilian
Spawn Wind_Cars_2_Civilian inserted into Yukon_Civilian_Arctic
Spawn Wind_Cars_2_Fire inserted into Fire
Spawn Wind_Cars_2_Police inserted into Police

Digging further, it looks like the Hellfire spawn file names have inconsistent capitalization. On Linux file names are case sensitive, so Hellfire_all not matching Hellfire_All.dat is preventing them from working on Linux.

**Comment by Puruuuu** [comment]
Yeah, it seems to work now, after I changed it to Hellfire_all.dat
