### ISSUE TITLE
[Minnor Bug]/[Feature Request] - Inbound Voice Gain

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#2328]
Hello, how doing? One thing I witnessed a few times. Basically the game's General Volume interferes with the separate Voice Volume. It would be interesting to be able to decrease the sound of the environment among others, and that the voice chat sound is separated to achieve better interactions (for example on servers: Roleplay or in PvP between clans). Thanks!

![volume](https://user-images.githubusercontent.com/25484986/104779513-fe013880-575d-11eb-9cad-8deb0ee18313.png)

**Comment by SDGNelson** [comment]
Ideally yes, it would be nice to separate out the audio into multiple sliders. Unity added Audio Mixers for that a few years into the game's development, so all of the content will need to be updated to use them. It might happen eventually, but is relatively low priority.
