### ISSUE TITLE
Radio Music plz

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2329]
Make a simple way to add your own audio files to the radio the give it more purpose. obviously wouldnt be syncd between players unless it had the same file name or something.

**Comment by SDGNelson** [comment]
Relatively recently (well, 5 months ago apparently) it was made easier to setup custom songs: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/StereoSongAsset.md
