### ISSUE TITLE
Unturned server on Windows uses much more resources

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#2330]
Since Unturned has some problems on Linux https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2088

I need to move my server network to a windows host
On the exact same dedicated server that I ran my network, I installed Windows Server 2019

I moved my Servers/ folder so everything is exactly the same as on Linux and installed the unturned as per https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md
And when launching 4 out of my 8 servers my CPU is maxed out to 100% and i can't launch more

On Linux 8 of those servers use only about 50% CPU when idle and 80% when full 

Is hosting servers on Windows different and I'm doing something wrong or Windows is just super unoptimized

Hardware specs
Ryzen 3600X 6 core 12 threads 
64GB RAM
Nvme ssd

**Comment by SDGNelson** [comment]
One difference is Unity headless mode is not as supported on Windows as it is Linux. This might be one of their goals in 2021 considering their renewed focus on multiplayer. As far as the game code is concerned both platforms behave the same.
