### ISSUE TITLE
[Bug] Nailgun Magazines do not delete if combined

### ISSUE THREAD

**Issue by NSTM9** [SmartlyDressedGames/Unturned-3.x-Community#2331]
When two special military magazines are combined (i.e. Tracer, Fragmentation) empty magazines are automatically deleted.
With the nailgun magazines, an empty magazine is left behind (which has no purpose).
The nailgun itself deletes empty magazines, but the nailgun magazines do not auto delete.

**Comment by Tairiku-Ookami** [comment]
because you can fill empty mags with nails lol

**Comment by NSTM9** [comment]
You can't, actually. https://gyazo.com/598ce90a02ab8acbb23671d7097b8a8f

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix for the next update.

**Comment by NSTM9** [comment]
Seems that this also applies to paintball hoppers, actually.

**Comment by SDGNelson** [comment]
Fixed for the paintball hoppers and nailgun in the next update.
