### ISSUE TITLE
[Bug Report] - recieve "infinite" XP and Items

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#2332]
Hello, this bug may seem a little stupid but I tested it on my singleplayer and on my online server.
Two things can happen in this bug, a little difficult for me to explain and sorry for my English.

**1- Some maps / mods have NPC'S that give you a mission like official maps. But there is a bug that I discovered right now, which is possible (spam) of buttons and clicks and generate "Infinite" XP / Item. Firstly, this bug I found in the mod: UNTURNOV1.5 when talking to NPC who gives you the initial items and xp (making it keep giving infinitely).**

**2-I tested this part in singleplayer: Russia Map I went to liberator I talked to mechanic npc, I took the necessary items and the reward would be:
-25XP
-5Reputation**

to spamar (short period of time, and I imagine it works with autoclicker / macro) I received: 75xp (reputation for some reason in my singleplayer did not work)
But I believe that other npc's that can generate items can be circumvented and generate / drop several items (tested on my singleplayer and my online server with players).

**I'm sorry for the message size**

If necessary I can record how it is happening. (It might take a while).

**Comment by SDGNelson** [comment]
Thanks for the report. It looks like this depends how the quest is setup, but I will double-check the quest checks for the next update.

**Comment by SDGNelson** [comment]
The mechanic quests provides 75 XP and 5 reputation (not 25 XP), so it was the correct amount. I double-checked the related server-side code and am confident it is fine, however I will prevent clicking multiple times because the client may mispredict certain effects like NPC flags incrementing multiple times.
