### ISSUE TITLE
Hawaii CPU usage

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#2334]
Not too sure if this is the best place to report this as the map isn't official but you may be able to provide some insight/advise on how to fix it.

Over the last few weeks i've noticed some of our clients hosting servers with us have quite high CPU usage compared to others and from what I can see the common denominator is workshop content but more often than not its the Hawaii map. Servers running with just hawaii seem to have 2.5x-3x the CPU usage than servers running another map such as PEI or washingon.

I'm not too sure why but i have occasionally seen this error which may have something to do with it
```
ArgumentException: You have already claimed the path with that object (Zombie (AIPath)). Are you claiming the path with the same object twice?
  at Pathfinding.Path.Claim (System.Object o) [0x00036] in <a23632a44996440884ec006f84e207aa>:0 
  at AIPath.OnPathComplete (Pathfinding.Path _p) [0x0001c] in <a23632a44996440884ec006f84e207aa>:0 
  at Seeker.OnPathComplete (Pathfinding.Path p, System.Boolean runModifiers, System.Boolean sendCallbacks) [0x00097] in <a23632a44996440884ec006f84e207aa>:0 
  at Seeker.OnPathComplete (Pathfinding.Path p) [0x00000] in <a23632a44996440884ec006f84e207aa>:0 
  at Pathfinding.Path.ReturnPath () [0x00008] in <a23632a44996440884ec006f84e207aa>:0 
  at AstarPath.ReturnPaths (System.Boolean timeSlice) [0x0005c] in <a23632a44996440884ec006f84e207aa>:0 
  at AstarPath.Update () [0x0005a] in <a23632a44996440884ec006f84e207aa>:0 
 
(Filename: <a23632a44996440884ec006f84e207aa> Line: 0)
```

Of course I could just limit their CPU usage but I find that unfair on the client but then again a client choosing to use the hawaii map is pretty much using the CPU usage of 3 people for the cost of 1 which obviously isn't ideal. Is there anything I can tell our clients/do to try lower the CPU usage without capping them as that would just make their server run laggier and have lower TPS.

NOTE: I believe some other modded maps and even items can also cause higher CPU usage but I am just wondering if there is anything that could be done about it to stop unoptimized workshops hogging all the resources?

**Comment by SDGNelson** [comment]
For the meantime deciding on a per-instance CPU limit is probably the best option. Hawaii vs Russia would be a closer comparison than Hawaii vs PEI / Washington due to the size and density.

The next performance improvements will be the network stuff described in the 2021+ blog post, but after that it might be nice to revisit what can be done for some of these larger maps.

As for the pathfinding exception, it seems similar to the one reported by MihailHavenT in #2279. Odd because the game does not (IIRC) to anything weird there and it has gone unchanged for years, but I might have to start re-evaluating moving over to Unity's newer built-in pathfinding.

**Comment by Bradler26** [comment]
My only concern with limiting the CPU, of course besides the obvious performance hit, is that I have been seeing quite a few of these errors happening recently 
```
src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1276) : Assertion Failed: SDR service thread gave up on lock after waiting 66ms.  This directly adds to delay of processing of network packets!
```
which I can only assume is coming from the fact that the CPU usage is quite high due to a bunch of our clients using hawaii on that machine as compared to our other machine which is at around 50% CPU usage with similar amounts of servers (I assume just less hawaii servers)

I saw in one of your other posts that the error means the server is running at less than 20TPS which is obviously very bad. I might try restarting the machine to see if it will help settle some things down but what I have noticed is the longer the server is online for the higher the CPU usage seems to climb and after a restart it drops down a fair amount.

As for comparing Russia I have just run the server on Russia and CPU usage is between PEI and hawaii so maybe it is just based on the map size.

**Comment by SDGNelson** [comment]
66ms would indicate the server is at less than 15 TPS. It should still be functional however (regardless of warning).

Interesting that the CPU usage rises... In the past I have run servers for extended periods to monitor for leaks, and maybe I should do that again soon.

Russia and Hawaii are the same size, though Hawaii does have the stacked caves underneath the volcano areas.

**Comment by Bradler26** [comment]
And I am correct in saying that TPS error occurs because the cpu is under heavy load? 

I found it interesting how we have similar amounts of servers on an i7 6700 and a ryzen 3600 yet the 3600 is at about 40% while the i7 is almost maxed. It's either just a coincidence that the user have laggier servers and seem to use Hawaii more or ryzen handles servers far better

**Comment by SDGNelson** [comment]
Yes, I believe it's a warning when the server is not polling data from the Steam networking API frequently enough. The server polls all available messages once per tick.

One major difference there is the Ryzen runs more threads in parallel right?

**Comment by Bradler26** [comment]
Yes the ryzen does have 2 more physical cores but i wouldnt think it would mean more than 2x the performance. I also transferred a test server from 1 machine to the other and ran HTOP to see its CPU usage on each machine. The usage seems pretty much the same between both. Maybe its just cause the i7 is slightly weaker it can't handle as many servers with higher usage. 

Either way i think i'll just get a CPU upgrade for that machine in the future, was just interested to know. Thanks for your info on the steam networking and pathfinding. You can close this if you want (leaving it open myself just in case you want a reminder about changing pathfinding like you mentioned before)

**Comment by SDGNelson** [comment]
Okay. I will close this for the meantime. Doing something about the pathfinding will be more of a long-term project.
