### ISSUE TITLE
Migrated servers don't show up under new IP 

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#2336]
I recently migrated my servers from one VPS to other and changed IP

I told my players to type in the new IP and add the server to the favourites again and 90% of my players can't join manually 

The server doesn't respond to some and it does to others

The rest of the players didn't have to do anything and the servers showed up under the new IP automagically in the favourites tab

What is happening here? Why some players can't connect even manually and some got the servers automatically in the favourites tab 

I will add that I'm using Steam GSLT

Is there some sort of mechanism that controls that? When will the servers show up with the new IP Is it time-based?

**Comment by SDGNelson** [comment]
Keeping favorites after IP change is supposedly a benefit of GSLTs. This Steam master server is kind of a black box though, so I do not have a good answer for you.

By "90% of my players can't join manually" they type in the IP and port but the query does not go through? First guess would be the firewalls / address binding setup on the server side.

**Comment by gegtor** [comment]
Yes I told them to type in the IP and port directly and they report `Failed to find a server`

The server is completely exposed to the internet has no firewall 

I have 1 NIC with public IP

Should I use `bind xxx.xxx.xxx.xxx`?

**Comment by gegtor** [comment]
bind did not help

**Comment by SDGNelson** [comment]
Failed to find server indicates the Steam query did not get a response. Is each server 3 ports apart e.g. 27015, 27018, 27021, etc?

**Comment by gegtor** [comment]
Okay the issue was OVH GAME Anti-DDoS + firewall 

By default, it's very aggressive 

But OVH even advertises Unturned as one of the games it's firewall can protect well soo
<img width="553" alt="Screenshot 2021-01-18 at 22 13 01" src="https://user-images.githubusercontent.com/10978723/104963256-6b210200-59da-11eb-9318-03ee0e691e8b.png">
