### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2337]
![p1](https://user-images.githubusercontent.com/64722485/105059154-f28d7480-5ab1-11eb-91fd-53f9c98f0ebf.png)

![p2](https://user-images.githubusercontent.com/64722485/105059177-f91bec00-5ab1-11eb-9618-70521a1b5f30.png)

[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5837036/Client.log)  [Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5837038/Client_Prev.log)

Subscribe a curated map, play it, and then I get this issue.

**Comment by SDGNelson** [comment]
Thanks for the report and logs. I will get this sorted out for the next update.

**Comment by SDGNelson** [comment]
Fixed for the next update.
