### ISSUE TITLE
Loot Spawn Protection

### ISSUE THREAD

**Issue by MihailHavenT** [SmartlyDressedGames/Unturned-3.x-Community#2340]
_Prevent players from building at loot spawns!_

**Add in config.json**

```
"Allow_Placing_On_Vehicles": false or true
"Allow_Structures": false or true
"Allow_Barricades": false or true
```

**Comment by Puruuuu** [comment]
Well, there are plugins for that. Pretty much adding this option would render all the plugins people have made about it useless.

**Comment by iBowie** [comment]
> 
> 
> Well, there are plugins for that. Pretty much adding this option would render all the plugins people have made about it useless.

It's always good to have built-in implementation since some map makers don't make maps only for their own servers
