### ISSUE TITLE
Steam Networking issues?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2341]
Hey @SDGNelson,
I've noticed that people are still experiencing issues with _"The game  server did not receive a response from the Steam authentication servers."_ and it's a persistent issue for Lyhme Hosting and Lyhme Community Servers. I have one Client.log which I'll attach for further review, and once I get some more from players I'll drop them in this thread, perhaps you could give some insights as to why it's still occurring? I'd greatly appreciate it!

[Client (4).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5852336/Client.4.log)

**Comment by SDGNelson** [comment]
Unfortunately there is nothing we or server hosts can do about this. It not related to the Steam networking, rather the Steam authentication services. Occasionally they go offline / become temporarily unresponsive in which case the game server cannot verify the player identity.
