### ISSUE TITLE
Inventory glitch/bug.

### ISSUE THREAD

**Issue by 1Aceeeee** [SmartlyDressedGames/Unturned-3.x-Community#2343]
it always happened, when I open my inventory, it keeps glitching. you needs have to press the inventory twice to get it gone.
(pls fix its annoying.)

**Comment by SDGNelson** [comment]
What do you have your key bound to? And are you pressing specifically the inventory key, or the dashboard key (toggles inventory/crafting/skills/map regardless of active)?

**Comment by 1Aceeeee** [comment]
when i press "e" i keeps glitching like when you Drag an item, u need u press "e" twice so that it get gone.

**Comment by 1Aceeeee** [comment]
It happens all the time when i open my inventory.

**Comment by SDGNelson** [comment]
Is it only when dragging an item? If so, IIRC that was added as an extra way to cancel the drag.

**Comment by 1Aceeeee** [comment]
> What do you have your key bound to? And are you pressing specifically the inventory key, or the dashboard key (toggles inventory/crafting/skills/map regardless of active)?

    Yes, when dragging an items only, it happens all the time when i open my inventory.

**Comment by 1Aceeeee** [comment]
Yes, when dragging an item, it happens all the time when I open my Inventory.

**Comment by SDGNelson** [comment]
I was wrong: the newer way to cancel drag is the escape key. 

Unable to reproduce the G to close inventory while dragging problem though. Perhaps you have multiple actions bound to the same key, for example rotate or dashboard on the same key as inventory?
