### ISSUE TITLE
Lost the blowtorch icon in inventory.

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2345]
It shows only as two black boxes. Same if it's in the primary or secondary slot. Not visible in right-click information box.

**Comment by aladairmaxwell** [comment]
Crossbow too.

**Comment by SDGNelson** [comment]
Sorry, this will be fixed in the next patch, but holding off until next week to avoid disturbing servers over the weekend. Closing because duplicate of #2342
