### ISSUE TITLE
Option for Icon bound

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2347]
Add dat something like Auto_Icon_Camera True/False so that mod makers can set item icon as set in Unity. Fitting icon size perfectly into bound is unecessary sometimes.

**Comment by SDGNelson** [comment]
Which items should not have their size automatically determined?

Note currently particle and line renderers aren't handled properly, but that will be fixed.

**Comment by SDGNelson** [comment]
Added "Use_Auto_Icon_Measurements False" per-item setting for the next patch.
