### ISSUE TITLE
For Future Updates

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#2348]
Hello, Nelson. I know that combining different issues into one release is not practical. However, this was done on purpose since many issues have been remaining unresolved. I have combined both old and new issues that require your attention. I know that you have to ignore many issues as there are higher priority tasks. However, I hope that in future you can dedicate one of the updates to solve these problems. Therefore, I publish this list and I hope to hear your opinion on which of these feature may be added in the future.

1. Add a parameter that allows you to override the radius of sound playback for weapons and used items. It is desirable that this parameter could be specified individually for each audio clip. For example Minigun_Sound_Radius_Override; Use_Sound_Radius_Override; Reload_Sound_Radius_Override etc.
    
2. Add a parameter that allows you to override or remove damage from zombie Acid for clothes and vehicles. For example Proof_Acid; Acid_Armor or something like that. (At the moment, this is the most imbolant and unregulated type of damage in the game.)

3. Add a parameter that allows you to override the threshold for reproduction of damage effects in vehicles. At the moment, the values ​​are constant and are not displayed correctly when the vehicle's health is high. For example Health_Level_Smoke_0; Health_Level_Smoke_1.

4. Add a parameter to control the speed of transition of the fade effect and sound from AmbianceVolume. At the moment, there is no way to make the transition to different zones sharper or smoother. When the player moves abruptly (teleport) to another location, the effect lasts for about 8 seconds. This needs to be fixed.

5. Add a parameter to disable the rendering of objects from the first person in the form of a mask. It would be helpful to display the item in your hands using real distance as if it were in a third person perspective. For example 1P_Item_Render_Override.

6. Fix turret packs of vehicles. At the moment, you can make a rotary turret for the driver of the vehicle and it will work both in the single player and on the server. However, the problem is that the rotation change is not propagated to other clients when playing on the server. This bug needs to be fixed.

7. Add AnimationEventHook. The addition of this tool has requested and supported many people. This would be an extremely useful modding tool. You do not need to sync with the prefabs of the items in the inventor. This tool is supposed to be used on any objects in the player's hierarchy during the playback of certain animation clips or actions performed by the player. Link to a more detailed issue: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1697

8. Add a KeyEventHook which will fire the UnityEvent when a key is pressed. At the moment, the game has the ability to specify 5 custom keys labeled as "Mods / Plugins". However, against all odds, modders do not have a tool to interact with this setting. (This needs to be corrected. Otherwise the word "Mods" in the description of this function is false)

9. Add SpeedEventHook. A universal script that can be added to any GameObject with a Rigidbody (Projectile, Throwable, Vechicle, Animal, etc.). When the Rigidbody reaches the specified speed threshold, a UnityEvent will be triggered.
A simple and useful tool.

```c#
using UnityEngine;
using UnityEngine.Events;

namespace SDG.Unturned
{
    public class SpeedEventHook : MonoBehaviour
    {
        public Rigidbody Target;

        public float TriggerSpeed;

        private float LastSpeed;

        public bool IgnoreVerticalSpeed;

        public UnityEvent OnTargetSpeedUp;

        public UnityEvent OnTargetSpeedDown;

        private void FixedUpdate()
        {
            Vector3 velocity = Target.velocity;

            if (IgnoreVerticalSpeed)
                velocity.y = 0;

            float sqrSpeed = velocity.sqrMagnitude;

            float sqrTrigSpeed = TriggerSpeed * TriggerSpeed;

            if ((LastSpeed < sqrTrigSpeed) && (sqrSpeed >= sqrTrigSpeed))
            {
                OnTargetSpeedUp.Invoke();
            }
            else if ((LastSpeed >= sqrTrigSpeed) && (sqrSpeed < sqrTrigSpeed))
            {
                OnTargetSpeedDown.Invoke();
            }

            LastSpeed = sqrSpeed;
        }
    }
}
```

10. Add a wider list of events to VehicleEventHook. For example OnPassengerAdd; OnLocalPassengerAdd; OnExplosion; OnSirensEnabled (To activate server side functions when the siren is on)

11. Add support for projectile variants for Guns. It would be helpful to have Projectile_0; Projectile_1; Projectile_2, etc.
This would make it possible to create a weapon that uses a loop of several projectiles when firing.
For example a weapon has two projectile variants. Accordingly, I will use projectile_0 => projectile_1 => projectile_0 = projectile_1 => ...
(I hope explained clearly)

**Comment by z1net** [comment]
Good idea!

**Comment by z1net** [comment]
but it maybe added in 2077 in unturned 9.0

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
