### ISSUE TITLE
ace bug on servers

### ISSUE THREAD

**Issue by aldayg** [SmartlyDressedGames/Unturned-3.x-Community#2349]
I seen you tried fixing ace's infinite ammo in 2019 but I have an issue on my server and seen it on other servers where aces cant be equipped, used or dropped from the inventory (only way to drop it is to take ur clothes off with it in ur inventory.) Weirdly I had a player on my server who could use, equip and infinitely shoot the ace but everyone else cannot even equip it

**Comment by SDGNelson** [comment]
This happens because somehow the Ace files in particular got out of sync for a lot of players. If you validate the game files on both client and server it should fix itself. You can double-check by making sure there are only two files in /Bundles/Items/Guns/Ace
