### ISSUE TITLE
Is selling plugins for Unturned legal?

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#2354]
Hi Nelson,

So Paypal decided to close my account because they say, selling plugins for Unturned is illegal.
You support plugin development for a very long time now (btw thanks for that <3) and I'm pretty sure you are aware of ImperialPlugins etc.
Also (atleast what I understood) the Unturned EULA doesn't say selling plugins is not accepted.

So I'm here to ask if you could confirm if selling plugins for Unturned is legal or not.
It would really help me, because after all the information I send them, still nothing happened.

Thanks <3

**Comment by SDGNelson** [comment]
Classic PayPal.

Unturned does not have a per-game EULA outside of the Steam Subscribed Agreement (SSA).

I think it is safe to say that SDG is fine with developers selling plugins which enhance the server-side Unturned software. In the future if restrictions are imposed there will be plenty of advanced notice. Off the top of my head the only issue (same with CS:GO, TF2) would be if plugins were misrepresenting player inventories and gold status, so as long as nobody does that it can happily continue as-is.

**Comment by TH3AL3X** [comment]
> Hi Nelson,
> 
> 
> 
> So Paypal decided to close my account because they say, selling plugins for Unturned is illegal.
> 
> You support plugin development for a very long time now (btw thanks for that <3) and I'm pretty sure you are aware of ImperialPlugins etc.
> 
> Also (atleast what I understood) the Unturned EULA doesn't say selling plugins is not accepted.
> 
> 
> 
> So I'm here to ask if you could confirm if selling plugins for Unturned is legal or not.
> 
> It would really help me, because after all the information I send them, still nothing happened.
> 
> 
> 
> Thanks <3

Who use PayPal in 2k21, use stripe and other payment methods
