### ISSUE TITLE
No Unturned II access

### ISSUE THREAD

**Issue by NoAccessToBetaII** [SmartlyDressedGames/Unturned-3.x-Community#2355]
I recently got 1250 hrs on Unturned and received the invitation ticket thing. I however can't access the beta. There is no "claim access." There is no Unturned II in library, nothing

**Comment by SDGNelson** [comment]
Are you on Mac? Sorry to say, but there is no Mac version yet.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
