### ISSUE TITLE
I can't launch the game. (unity error)

### ISSUE THREAD

**Issue by Twqy** [SmartlyDressedGames/Unturned-3.x-Community#2356]
When I launch Unturned im prompted with a unity launch error.

**Comment by SDGNelson** [comment]
Sorry for the trouble. Can you email me (nelson@smartlydressedgames.com) these files please?
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file to your reply email
5. Return to the Unturned folder
6. Open the Unity AppData folder
7. Attach the Player.log file to your reply email
