### ISSUE TITLE
Projectile weapon magazines multipliers do not apply on multiplayer

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2357]
I tested this awhile ago & apparently this bug occurs on projectile weapons. This somehow works in singleplayer.

I cannot find the reason behind this, but apparently it has something to do when the magazine disappears when shot or when the launcher deletes the magazine after it's shot.

These .dat files are the ones that I worked with that didn't work:

- **Weapon .dat**

> GUID e994fb48f20f471f88a1f4fcff8bf998
Type Gun
Rarity Epic
Useable Gun
Slot Primary
ID 58076

> Size_X 5
Size_Y 2
Size_Z 0.45
Size2_Z 0.65

> Magazine 58077

> Hook_Sight

> Ammo_Min 0
Ammo_Max 1

> Safety
Semi

> Attachment_Calibers 1
Attachment_Caliber_0 56200

> Magazine_Calibers 1
Magazine_Caliber_0 56014

> Replace 0.3

> Firerate 50
Action Trigger

> Player_Damage 125
Zombie_Damage 125
Animal_Damage 125
Barricade_Damage 300
Structure_Damage 200
Vehicle_Damage 375
Resource_Damage 500
Object_Damage 400
Explosive
Explosion 55107

> Range 12

> Durability 1
Wear 5

> Spread_Aim 0.1
Spread_Hip 0.22

> Ballistic_Force 8500

> Recoil_Min_X -20
Recoil_Min_Y 25
Recoil_Max_X 20
Recoil_Max_Y 30

> Recover_X 0.5
Recover_Y 0.5

> Shake_Min_X -0.005
Shake_Min_Y 0.005
Shake_Min_Z -0.025
Shake_Max_X 0.005
Shake_Max_Y -0.005
Shake_Max_Z -0.05

> Should_Delete_Empty_Magazines true

> Blueprints 2
Blueprint_0_Type Repair
Blueprint_0_Supplies 1
Blueprint_0_Supply_0_ID 67
Blueprint_0_Supply_0_Amount 6
Blueprint_0_Tool 76
Blueprint_0_Level 3
Blueprint_0_Skill Repair
Blueprint_0_Build 27
Blueprint_1_Type Tool
Blueprint_1_Supplies 1
Blueprint_1_Supply_0_ID 58076
Blueprint_1_Product 67
Blueprint_1_Products 3
Blueprint_1_Build 27
 
- **Magazine .dat**

> GUID 17ae802911e74025b906844bf60dc077
Type Magazine
Rarity Epic
ID 58135

> Size_X 5
Size_Y 1
Size_Z 0.35

> Amount 1

> Calibers 1
Caliber_0 56014
Delete_Empty

> Projectile_Blast_Radius_Multiplier 0.75
Projectile_Launch_Force_Multiplier 1.25
Projectile_Damage_Multiplier 2.67

> Explosive
Explosion 55108

Again, like usual, there might be a quick fix to this. So anyone is open to bring up a solution to this if this is a bug that can be easily discarded without Nelson fixing it.

**Comment by SDGNelson** [comment]
Thanks for the report. It looks like the magazine can get deleted before applying its properties, so I will get this fixed for the next update.
