### ISSUE TITLE
Interface + Icon bug

### ISSUE THREAD

**Issue by z1net** [SmartlyDressedGames/Unturned-3.x-Community#2358]
![Screenshot_2](https://user-images.githubusercontent.com/65300126/105922625-ab6c2a00-6043-11eb-9e22-930d4c363672.png)
![Screenshot_1](https://user-images.githubusercontent.com/65300126/105922628-ad35ed80-6043-11eb-8b13-e9b2913b1639.png)

**Comment by SDGNelson** [comment]
Thanks for the report, but closing because it is a duplicate / fixed for the next update #2342
