### ISSUE TITLE
Old Curated Map Bundles causing Conflicts (greece version mismatch error)

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2359]
Some old maps which used to be Curated and included with the base game are causing asset bundle version mismatches.

For example, for Greece, the comment section is filled with people complaining about "Greece version mismatch": https://steamcommunity.com/workshop/filedetails/?id=1702240229

It seems that people still have these old curated maps inside of their actual unturned install's map folder, and its loading the Greece bundle from that map directory first, and then when trying to connect to a server it tries to load the workshop Greece too but refuses to load since it already has Greece loaded from map directory and kicks for version mismatch since the masterbundle hash of the clients (old bundle from map directory) differs from the servers (workshop item).

For Example:
[Client (2).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5877624/Client.2.log)
```

[2020-12-24 22:05:23] Loaded master bundle async: E:\Program Files (x86)\Steam\steamapps\common\Unturned\Maps\Greece\Bundles\greece.masterbundle
[2020-12-24 22:06:52] Found duplicate of master bundle 'greece.masterbundle' originally in 'E:\Program Files (x86)\Steam\steamapps\common\Unturned\Maps\Greece\Bundles' at 'E:\Program Files (x86)\Steam\steamapps\workshop\content\304930\1702240229\Greece\Bundles'
[2020-12-24 22:06:54] The AssetBundle 'Content\greece.content' can't be loaded because another AssetBundle with the same files is already loaded.
[2020-12-24 22:08:50] Rejected by server (WRONG_HASH_MASTER_BUNDLE) --- Reason: '"greece" version mismatch' Explanation: '"greece" version mismatch'
```

A Quick-fix might be just making it so Unturned on startup removes all the old curated maps from the unturned map directory directly.

**Comment by SDGNelson** [comment]
It looks like you are correct. 🤔 

One reason for Steam not to delete files when they are deleted from the upstream game is if they have been locally modified, but even the map editor would not explain the asset bundle. Similar unexplained issue for some players with the Ace and the BattlEye halo item...

Actually if a player has contacted you about this, I wonder if "validating game files" deletes the map? 

I would be hesitant to blindly delete maps named "Greece" in the Maps folder during startup because almost certainly some mappers will have copied it there to edit. :/

**Comment by PandahutMiku** [comment]
> It looks like you are correct. 🤔
> 
> One reason for Steam not to delete files when they are deleted from the upstream game is if they have been locally modified, but even the map editor would not explain the asset bundle. Similar unexplained issue for some players with the Ace and the BattlEye halo item...
> 
> Actually if a player has contacted you about this, I wonder if "validating game files" deletes the map?
> 
> I would be hesitant to blindly delete maps named "Greece" in the Maps folder during startup because almost certainly some mappers will have copied it there to edit. :/

They said they did try to verify their files twice and also were instructed how to delete all their workshop files manually to try to force re-downloading, only when they sent their logs and I told them to delete "Greece" from the Maps folder itself did it work. They said they didn't put it there to edit or anything.

I'm not really sure how Steam verifying actually works, maybe if you had verified after the update to remove Greece was released, it would have removed it. However, it doesn't seem to remove it now at all.

Maybe instead of blindly deleting, you could refuse to load any map bundles from Unturned's map directory until the player tries to actually join the map? This would still allow issues if someone was joining a Greece Server, but there is [virtually zero greece servers](https://www.battlemetrics.com/servers/unturned/stats?options%5Bcf8b1dd2-88aa-11e9-9a0b-e332042de7f6%5D=f72af1d0-88ac-11e9-b31a-f7978f511cc4%2Cf72acac0-88ac-11e9-b31a-f7978f511cc4%2Cf72acac1-88ac-11e9-b31a-f7978f511cc4%2Cf72af1d2-88ac-11e9-b31a-f7978f511cc4%2Cf72b18e2-88ac-11e9-b31a-f7978f511cc4), an average of 8 whilst there is a lot of other maps and servers which use Greece Content like Unturnov, where this issue occurs at the most.

The only thing I can think of besides that is going with the approach I suggested in another issue, loading zero content besides the main game masterbundles at game load, and only loading whatever each server requires on server join, unloading on exit. Load all the client's workshop content only if the player loads Singleplayer or map editor.

**Comment by SDGNelson** [comment]
Unfortunately as mentioned in other issues the not loading assets until the map/server, while it makes sense, is unlikely to happen anytime soon. The closest will be #2078, but that will not resolve this particular case because the asset bundle (greece.masterbundle) has the same file name.

For the meantime the "official answer" is that players need to delete the files manually, and I will help anyone who contacts support about that. In the future if important files are removed from the base game then I will include some code to delete them on startup as a safety precaution.

**Comment by PandahutMiku** [comment]
I was reminded of this recently because it's still a minor issue, and thought it would be worth noting that this seems to be a confirmed steam behavior if someone misses an update For example, Version .12 removes map, .13 changes other stuff, player doesn't launch steam in time to get .12, they will update all of the modified files but not delete any files. Works fine for most people, as long as they download first .12 and .13 one at a time. Might be worth being aware of in the future.
