### ISSUE TITLE
Trouble connecting to server

### ISSUE THREAD

**Issue by gitrous** [SmartlyDressedGames/Unturned-3.x-Community#2360]
I'm hosting an Unturned server using Vultr and Ubuntu 20.10 x64, and I got everything working, but I was unable to connect to the server. Figuring it was a port problem, I played around with the firewalls for a little, and now I'm getting a different error. Here are my port settings and the error.

#firewall-cmd --list-ports
27015-27018/tcp 27015-27018/udp

[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
RecordSteamInterfaceCreation (PID 8390): SteamNetworkingUtils 003 / 
RecordSteamInterfaceCreation (PID 8390): SteamNetworkingSockets008 /
Warning: failed to init SDL thread priority manager: SDL not found
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
RecordSteamInterfaceCreation (PID 8390): SteamNetworkingUtils 003 / 
Waiting for Steam servers...
Failed to connect to Steam servers because k_EResultNoConnection, still retrying
Failed to connect to Steam servers because k_EResultNoConnection, still retrying
Failed to connect to Steam servers because k_EResultNoConnection, still retrying

**Comment by SDGNelson** [comment]
Perhaps your server has an outbound firewall preventing it from connecting to Steam?

**Comment by gitrous** [comment]
Something was wrong with my steamclient.so files, but I was able to correct it.
