### ISSUE TITLE
Use delegates for netcode/channel methods

### ISSUE THREAD

**Issue by archie426** [SmartlyDressedGames/Unturned-3.x-Community#2361]
Right now reflection is purely used for calling steam channel methods when the client/server receives a packet. I was thinking it would be better to use delegates as they are wayyy faster. The only issue I could think of with this is that I believe the methods have to be static, so the instance would have to be passed as a parameter but personally I think the pros outweigh the cons. (This would mean though all members should be public but personally I think thats better for plugins also, less reflection required). This all can still work with the current attribute setup (just convert the MethodInfo to delegate in the constructor of SteamChannelMethod)

Source: https://codeblog.jonskeet.uk/2008/08/09/making-reflection-fly-and-exploring-delegates/, https://docs.microsoft.com/en-us/dotnet/api/system.delegate.createdelegate

**Comment by iBowie** [comment]
Making private members public can affect plugins that were made with reflection as this will change their metadata, so some old plugins will stop working. I agree that this can improve CPU usage, but we should at least take in account backward compatibility.

**Comment by archie426** [comment]
Just have public properties accessing the private fields then...

**Comment by iBowie** [comment]
It's about CPU usage on servers, since they have to register all the data through these reflected methods. It directly affects ping.

**Comment by SDGNelson** [comment]
Good timing - this is one of the aspects I intend to improve with the netcode rewrites this year. In particular RPCs should be tackled within the next few months. Most recently I have been working on the new serialization/deserialization code which should be stable within the next couple weeks. Will leave this issue open until the RPC stuff is rewritten.

**Comment by archie426** [comment]
Great to hear

**Comment by SDGNelson** [comment]
Closing because this has all been rewritten now. (and is using delegates, not `MethodInfo.Invoke`)
