### ISSUE TITLE
Boombox links dont work

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2362]
Im not sure if this is for just me but any url links to songs on the boobox do nothing. For neither my own mod or even the music added by Elver.
![image](https://user-images.githubusercontent.com/75531507/106046498-f28c0680-60a7-11eb-9041-0f120d2e671c.png)

**Comment by SDGNelson** [comment]
Thanks for the report - it looks like I broke this during the uGUI update. Will fix for the next patch!
