### ISSUE TITLE
Missing Terrain Check

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2363]
I've had a few reports over the last couple months of 2 separate players being able to see through terrain. 
Today I managed to grab screenshots from one of these players. 
![spy](https://user-images.githubusercontent.com/71527679/106093790-da100080-6128-11eb-884d-8bb1e1259b58.png)
![Screen_Shot_2021-01-27_at_8 53 01_PM](https://user-images.githubusercontent.com/71527679/106093312-ef385f80-6127-11eb-92c4-07af074cf16e.png)
I've spoken to this player and I'm certain he didn't do it on purpose -- but he also has no intention of fixing it as it gives him an edge on PVP servers. 

Could you add some sort of file check for terrain to prevent players doing this intentionally? 

I searched through their spy logs and I can see that he's been able to see through terrain since 11/13/2020 which was the day of an update, if that helps.

**Comment by archie426** [comment]
Looks like the first screenshot is where the person is disconnecting so movement checks by the server will not be in action. The second one it looks like the person is missing an asset file. It's not an issue on Unturned's side as far as I can see.

**Comment by AdamDN** [comment]
> Looks like the first screenshot is where the person is disconnecting so movement checks by the server will not be in action. The second one it looks like the person is missing an asset file. It's not an issue on Unturned's side as far as I can see.

This isn't an issue to do with them disconnecting, that's just a coincidence. I have over 900 /spy screenshots of them playing on 2 separate servers with no terrain for the past 3 months.

My guess is a missing/altered asset as well, which is why I'm asking if it would be possible to add a file check (either while the game is loading, or while they're connecting to servers etc) so that players aren't able to remove this asset intentionally to gain an advantage

**Comment by SDGNelson** [comment]
Unfortunately it is a problem with terrain on older versions of macOS. It seems to happen even with the built-in Unity terrain shaders. The only workaround I am aware of is for them to update to a newer release, at the time of writing Mojave/Catalina/Big Sur.
