### ISSUE TITLE
energized effect glitch

### ISSUE THREAD

**Issue by Openrome** [SmartlyDressedGames/Unturned-3.x-Community#2368]
https://imgur.com/a/e6DXRNQ

I don't know if this is a glitch but the effect is so far down from the goggles?

**Comment by SDGNelson** [comment]
The preview item is setup differently than the one on your character so the effect displays properly on your character, but I will fix the placement on the preview item.

**Comment by SDGNelson** [comment]
Deciding not to fix this particular case because there are a lot of items with discrepencies, and the item preview will be replaced to use character preview whenever Steam item inspecting releases.
