### ISSUE TITLE
PLEASEEE change disabling UI location 

### ISSUE THREAD

**Issue by aldayg** [SmartlyDressedGames/Unturned-3.x-Community#2369]
Hey nelson can you please change the location of the disabling UI (GUN UI AND HEALTH UI) to the server config.json instead of the map config.json (as i cannot modify the standard russia config.json without going through drama of uploading and having players download a modified russia map and then still having "Server was using a modified version of the map" issue would make it soo much easier if you moved the location to the config.json in the server file. PLEASE NESLON ILL LOVE you for ever, Its because I have a paid plugin that uses a workshop UI but it clashes with the generic UI. thank you bby i love u <3

**Comment by SDGNelson** [comment]
This will be added at some point, but no ETA yet.
