### ISSUE TITLE
Bloom graphics setting doesn't work in 1st person

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2371]
![20210201160744_1](https://user-images.githubusercontent.com/69295711/106462962-d1f8ed80-64a7-11eb-99e5-350f4ceece01.jpg)
![20210201160749_1](https://user-images.githubusercontent.com/69295711/106462965-d32a1a80-64a7-11eb-8353-3ba359499e4f.jpg)
![20210201160814_1](https://user-images.githubusercontent.com/69295711/106462966-d32a1a80-64a7-11eb-95c9-51055b86e22b.jpg)
![20210201160823_1](https://user-images.githubusercontent.com/69295711/106462968-d3c2b100-64a7-11eb-9dae-70322004ae97.jpg)

Every emission don't have promised "blur glowing halo" around it. But only in First person. 
![image](https://user-images.githubusercontent.com/69295711/106463158-1ab0a680-64a8-11eb-98f5-1ed4ca3025eb.png)

**Comment by SDGNelson** [comment]
It does not surprise me that it does not work properly on some setups because the first person view is rendered separately and just happens to layer properly, but eventually I would like to merge the first and third person views which will properly fix this.
