### ISSUE TITLE
Disabled Information Bug

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2373]
Hey,
I found out that if you disable information you can still access there by keyboard shortcut.
![image](https://user-images.githubusercontent.com/54103088/106566850-2b592f00-6531-11eb-8cb9-d4e220e9ac20.png)

**Comment by SDGNelson** [comment]
Thanks for the report, will check it out.

**Comment by SDGNelson** [comment]
Looks like this happened with crafting and skills too! Fixed for tomorrow's update.
