### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Openrome** [SmartlyDressedGames/Unturned-3.x-Community#2374]
Is it possible for the sound of the hitmarker and crits be changed like tf2
Will there ever be a way to make a hud for this game or never?

**Comment by SDGNelson** [comment]
1. No sorry, those are not customizable at the moment.
2. There are only a few HUD sprites, so it would not be very customizable. It was supported in the very early versions but never used, and nowadays there are the HUD coloring options.
