### ISSUE TITLE
Bug - Removing Hook_Sight from dat of a gun breaks the sight picture

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#2376]
With Hook_sight it looks normal: 
![image](https://user-images.githubusercontent.com/35437320/106766346-e7c80780-668d-11eb-8556-31946be4def1.png)
But without it, it looks completely wack:

![image](https://user-images.githubusercontent.com/35437320/106766399-f0204280-668d-11eb-9343-3b2f4de501fd.png)
What is going on?

**Comment by SDGNelson** [comment]
It is used as the default sight alignment, so without it the game does not know where to put the camera.
