### ISSUE TITLE
Mannequin Hair

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2378]
Looks like the Mannequin hair thing I reported a while ago that you said you had fixed still isnt fixed. 
![image](https://user-images.githubusercontent.com/75531507/106776804-0389ca00-660a-11eb-8f49-f8b2c80ba84c.png)

**Comment by Real-DJ-Lucky** [comment]
Its only white now. Doesnt change to my set color.

**Comment by SDGNelson** [comment]
Previously the mannequin hair color defaulted to zero, but now defaults to the same color as the body. Using the character's hair color might be supported at some point but is low priority. The way placed items savedata is setup at the moment it is tricky to handle backwards compatibility with new data.
