### ISSUE TITLE
Please add something to help this

### ISSUE THREAD

**Issue by Openrome** [SmartlyDressedGames/Unturned-3.x-Community#2379]
Hey nelson just wondering if this is possible to add like a ctrl A in the inventory screen when try to scrap i have like 7 inventory of shirts https://imgur.com/a/QTL8zyA

**Comment by SDGNelson** [comment]
In the Preferences.json file you can change Allow_Ctrl_Shift_Alt_Salvage to true, and then holding Ctrl+Shift+Alt while left-clicking the item will immediately salvage it.
