### ISSUE TITLE
Non-existent existing item.

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2380]
Hey Nelson I was wondering if you could tell me if a pair of Lucky Coins Dango Streetwear pants even exist. Im trying to complete my set but as far as I've looked none even exist tho I'm pretty sure they're supposed to be able to be unboxed. You dont have to tell me who has them or anything but just being able to know if they exist or even can would be nice. Thanks for everything you do. ^^ 
![image](https://user-images.githubusercontent.com/75531507/106936113-ca248d80-66e1-11eb-9ad4-5469cadd0221.png)

**Comment by SDGNelson** [comment]
It looks like yes, it should be _possible_ for them to exist (itemdefid 86613). Sorry I do not have any way to check whether a pair has been unboxed though. Hopefully eventually a pair surfaces! I think Valve is/was working on a tool to examine the global item database, but not available yet as far as I know.

**Comment by Real-DJ-Lucky** [comment]
Thanks for the info! I guess now I just have to maybe unbox a bunch of dango cases to try and get it. Unless you wanna be cool and change out my lucky coins elver pants I have for dango ones 👀 lol
