### ISSUE TITLE
Teleport glitched

### ISSUE THREAD

**Issue by Openrome** [SmartlyDressedGames/Unturned-3.x-Community#2382]
https://cdn.discordapp.com/attachments/793907142431080468/807303376572121109/unknown.png 
so in this picture we have the plated car on the right side and the swat van that is stuck between a police station in vanilla sever i rammed my plated car into the swat van and forced it like that and the owner of the car hoped out and when he did he got teleported to clear water campground

**Comment by SDGNelson** [comment]
This is intentional, albeit unintuitive: if there is no valid exit position for the passenger it will use a player spawn point as a fallback.
