### ISSUE TITLE
[Request] User Friendly icon generating tool

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2383]
In the latest update you've removed all item icons from Extras/Icons folder, which my app (NPC Maker) kind of relied on. So now when all the icons in the app are gone, i'm not saying that you should add these icons back. I'm asking if you could make it more user-friendly. Right now it's not intuitive in any way.

**Comment by SDGNelson** [comment]
While not user-friendly, if you go to Menu > Workshop > Press F1 and click "All Items" it should export the exact same icons as were in the Icons folder. Does it work to cache those icons?

**Comment by iBowie** [comment]
It works, yes. Looks like i'll need to add some message to the app telling people to do these steps.

**Comment by SDGNelson** [comment]
Sorry for the hassle / trouble. There are a variety of improvements I would like to make to the icons, but no ETA yet (relatively low priority) it causes some headaches on my side too - e.g. the economy icon setup is not as streamlined as it should be.
