### ISSUE TITLE
BUG IN LINUX

### ISSUE THREAD

**Issue by ZoomGYT** [SmartlyDressedGames/Unturned-3.x-Community#2384]
Hi Nelson, I don't know if you remembered me, the problem is that I contacted you 6 months ago for an error on a map. My map cost me a lot to do, but when I install my map on a Linux server this happens: https://gyazo.com/c3b176f22e4706e92f660ac30c071864
Basically I teleport anywhere, spawn cars and it's all in the water.
But the other day I installed it on a windows server and everything worked perfectly, it also works well in the single player world. Please nelson help me I have more than 3000 hours in your game and that map took me to do it +200 hours

map: https://steamcommunity.com/sharedfiles/filedetails/?id=2365176328

**Comment by SDGNelson** [comment]
If you can share the server log file from /Logs/Server_ (name) .log there may be some further details. It sounds like the terrain is not being loaded on the server.

**Comment by ZoomGYT** [comment]
[Server_unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5935679/Server_unturned.log)

**Comment by SDGNelson** [comment]
It looks like only one landscape tile is being loaded:

> Loading 1 landscape tiles

That seems unusually low. Are you using the "devkit" terrain, or the regular editor terrain?

**Comment by ZoomGYT** [comment]
devkit some things, if you want look at it I have passed you the map

**Comment by ZoomGYT** [comment]
also it makes me strange that it works in a player and then in linux not

**Comment by SDGNelson** [comment]
Where did you send the map?

**Comment by SDGNelson** [comment]
The problem is that you renamed "Heightmap.png" in the Terrain folder to "heightmap.png" - Linux is case sensitive, so it cannot load the file. If you name it "Heightmap.png" again it will load properly.
