### ISSUE TITLE
Help none can go in my server! "This server is using Modified code!"

### ISSUE THREAD

**Issue by G0ldenHD** [SmartlyDressedGames/Unturned-3.x-Community#2385]
Hello, so i wanted to create some server where me and my friends could play unturned, now we didn't know how, since i am the smartest out of the group i had and idea to make a server! Now when i made one my friends needed to leave, so i went in the server by my self to test things , it worked out but then next day my friend went in, and then me and friend nr. 2 wanted go in too but couldn't. Now i only Friend Nr.1 can go in and me, and Friend Nr.2 can't.

Any help on the problem?

**Comment by G0ldenHD** [comment]
Oh btw, after a few restarts friend Nr.1 also couldn't join..

**Comment by SDGNelson** [comment]
Are both the server and clients on version 3.21.5.0? If you "verify game files" it might update something.

**Comment by G0ldenHD** [comment]
I will try it tommarrow, for me rn is kinda late so yeah.

**Comment by G0ldenHD** [comment]
it seems to be that verifying did nothing, also  the server is outdated, the game it self isnt the server is on 3.21.4.0 but the game is 3.21.5.0

**Comment by G0ldenHD** [comment]
I guess the situation here is that i played on my own server BEFORE update 3.21.5.0 on 3.21.4.0 same as the server, but then the game got updated to  3.21.50 but the server didn't... I will reinstall or make a new server, will be back with an update on the situation..

**Comment by G0ldenHD** [comment]
Update : So updating the game or the server using app_update will fix the problem!

**Comment by G0ldenHD** [comment]
If you still have the problem then seek further help..

**Comment by SDGNelson** [comment]
Glad to hear that it is working for you. Closing the issue.
