### ISSUE TITLE
BattlEye: Bad Service Version

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#239]
Players consistently get kicked from servers within a few seconds/minutes of joining with the message "BattlEye: Bad Service Version"

**Comment by Trojaner25** [comment]
Nelson reverted BattlEye, it broke Unturned.

**Comment by Mithallas** [comment]
And the revert has been reverted. I miss steam overlay :( Closing issue.

**Comment by SDGNelson** [comment]
BattlEye's plan was to revert the BEService version until the Steam overlay issue is fixed, but there were some unintended side effects.
