### ISSUE TITLE
TP to SPAWN randomly

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2392]
Sometimes some users are instant teleported to the spawn without context, no one teleported him is random, sometimes is when they are walking, or driving and get out of the car.

https://user-images.githubusercontent.com/75626024/107152975-631a0980-696b-11eb-8177-0be2dbb06722.mp4

**Comment by iBowie** [comment]
The game simply can't find a suitable place for them to spawn when they exit the vehicle, so it fallbacks to spawnpoints

**Comment by SDGNelson** [comment]
iBowie is correct, thanks. Intentional, albeit unintuitive. Someday perhaps there will be a better way to find a suitable exit point, but at the moment it does consider left/right/front/back/top/bottom before failing.
