### ISSUE TITLE
Workshop mods constantly fail to submit

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2394]
Not sure if this is a game or Steam issue, but I had difficulties submitting an updated mod to workshop. Any ideas on why this happens?

**Comment by joeymisfit** [comment]
@OneManOperative This is due to a recent Steam License Agreement change, go to this link [https://steamcommunity.com/workshop/workshoplegalagreement/](https://steamcommunity.com/workshop/workshoplegalagreement/ ) and re-accept the workshop agreement, then try uploading the updated workshop.

**Comment by SDGNelson** [comment]
Thanks @joeymisfit
