### ISSUE TITLE
PSA: OnServerReadingPacket and OnServerWritingPacket will be disabled

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2395]
The next step of the network rewrite will be refactoring routing and serialization/deserialization of messages. Afterwards these two events will no longer be called. Currently there is a warning when they are used.

If you are using them, please comment here and we will find a replacement or alternative.

**Comment by DiFFoZ** [comment]
What about a `SteamChannel.onTriggerReceived` and `SteamChannel.onTriggerSend` they are will be disabled?

**Comment by SDGNelson** [comment]
Not disabled yet, but they will be later this year. I will add events for all the Rocket usage of onTriggerSend/Received to avoid breaking that compatibility.
