### ISSUE TITLE
NPC cancel server side

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#2397]
Hello Nelson, could you add some way to prevent the player from opening an NPC if the server refuses or at least some way to force the closure of the npc interface on the server side?

Also i'm not sure but i think if server send "tellstoring" while player is in npc interface may bug (not sure, i didnt test)

**Comment by SDGNelson** [comment]
What do you have in mind? i.e. Why is the NPC not interactable?

**Comment by rube200** [comment]
This feature is not for me but i can think in some reasons.
Ex:
Npc just can be used by player in the first hour of join the server for the first time (controlled by plugin)
or
Npc is blocked until player do some stuff "asked" by plugin

**Comment by SDGNelson** [comment]
In those cases the better option would be to use `PlayerQuests.sendSetFlag` and set up the logic in the NPC assets.
