### ISSUE TITLE
vehicle main driver Launching missiles bug

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#2398]
aircraft
As shown in the video, the shells will disappear into the ground and then explode outside the attack site
https://youtu.be/kCn3W6iEHvM

Tank
As shown in the video, the shell will disappear on the ground and will not explode
https://youtu.be/sks0oNB2h7Q

The interesting thing is that there is no problem with single player.
Upload the module, give it to the server to use, then join the server and it will look like this.

aircraft DAT
GUID 087cfde1e8804949a81fc8d5602a7e2f
Type Vehicle
Rarity Legendary
ID 4667

Speed_Min -4
Speed_Max 36

Steer_Min 8
Steer_Max 32

Brake 32
Lift 5

Fuel 1000

Health_Min 600
Health_Max 800
Health 1000

LockMouse
Engine Plane
Sleds
Traction
Reclined

Cam_Follow_Distance 8

Air_Turn_Responsiveness 4
Air_Steer_Min 32
Air_Steer_Max 64

Trunk_Storage_X 3
Trunk_Storage_Y 3

Explosion 20
Invulnerable
Tires_Invulnerable

Pitch_Drive 0.008

Turrets 1
Turret_0_Seat_Index 0
Turret_0_Item_ID 46667
Turret_0_Yaw_Min -135
Turret_0_Yaw_Max 135
Turret_0_Pitch_Min 85
Turret_0_Pitch_Max 180
Turret_0_Ignore_Aim_Camera

Tank DAT
GUID 59e5c039af6f4c3ab177f5cbadb06ba2
Type Vehicle
Rarity Legendary
ID 46665

Speed_Min -4
Speed_Max 8

Steer_Min 24
Steer_Max 48

Brake 24

Fuel_Min 200
Fuel_Max 400
Fuel 2000

Health_Min 1100
Health_Max 1200
Health 1250

Exit 4

Cam_Follow_Distance 7.5
Cam_Driver_Offset -0.0625
Bumper_Multiplier 2
Passenger_Explosion_Armor 0.2

Traction

Trunk_Storage_X 6
Trunk_Storage_Y 6

Explosion 20
Invulnerable
Tires_Invulnerable

Turrets 2
Turret_0_Seat_Index 0
Turret_0_Item_ID 1300
Turret_0_Yaw_Min -135
Turret_0_Yaw_Max 135
Turret_0_Pitch_Min 65
Turret_0_Pitch_Max 100
Turret_1_Seat_Index 1
Turret_1_Item_ID 46667
Turret_1_Yaw_Min -25
Turret_1_Yaw_Max 25
Turret_1_Pitch_Min 65
Turret_1_Pitch_Max 100
Exclude_From_Master_Bundle

**Comment by hksz** [comment]
Original tank transformation ：https://youtu.be/D4nCaDKuZfk

**Comment by SDGNelson** [comment]
I double-checked with the vanilla tank in multiplayer and it worked as expected. My guess is that the turret setup, in particular the "Aim" transform, does not match between the "Vehicle" and "Clip" prefabs.

**Comment by hksz** [comment]
> I double-checked with the vanilla tank in multiplayer and it worked as expected. My guess is that the turret setup, in particular the "Aim" transform, does not match between the "Vehicle" and "Clip" prefabs.

So what should I do

**Comment by hksz** [comment]
> I double-checked with the vanilla tank in multiplayer and it worked as expected. My guess is that the turret setup, in particular the "Aim" transform, does not match between the "Vehicle" and "Clip" prefabs.

Is this my mistake

**Comment by hksz** [comment]
I readjusted the "Clip" without any change

> I double-checked with the vanilla tank in multiplayer and it worked as expected. My guess is that the turret setup, in particular the "Aim" transform, does not match between the "Vehicle" and "Clip" prefabs.

I re-adjusted "Clip", but it's still wrong

**Comment by SDGNelson** [comment]
Do the vanilla vehicles with cannons work properly for you on your server? Tank_Russia is included in the examples package as a point of comparison.

**Comment by hksz** [comment]
> Do the vanilla vehicles with cannons work properly for you on your server? Tank_Russia is included in the examples package as a point of comparison.

The original version of the carrier with missiles on the server works fine.
I've uploaded a new video, it's a bit long, please be patient and watch it.
https://youtu.be/KNZZjT1zPi8

**Comment by SDGNelson** [comment]
Tip: for testing on the server you can put the files in the "Sandbox" folder rather than uploading to Steam.

In the video it looks like the problem is with the tank that has driver + gunner in the same seat? Currently projectiles are not supported when driving the vehicle, only bullets, and off the top of my head bullets might only be supported when driving with a fixed camera.

**Comment by hksz** [comment]
> Tip: for testing on the server you can put the files in the "Sandbox" folder rather than uploading to Steam.
> 
> In the video it looks like the problem is with the tank that has driver + gunner in the same seat? Currently projectiles are not supported when driving the vehicle, only bullets, and off the top of my head bullets might only be supported when driving with a fixed camera.

Will you support it in the future?

**Comment by SDGNelson** [comment]
It might be added, but probably at least not until after the player input netcode rewrite later this year, sorry.
