### ISSUE TITLE
3.21.6.0 patch: Broken toggles

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2399]
Cosmetics, skins and mythics off in-game. Toggles don't work. Affects both IMGUI and iGUI.

**Comment by SDGNelson** [comment]
Hmm it looks like equipped Steam items are not getting sent to the server, investigating.

**Comment by SDGNelson** [comment]
Sorry for the trouble - this is fixed in the patch up now.
