### ISSUE TITLE
Steam Overlay - Update 3.23.7.0

### ISSUE THREAD

**Issue by joeytheadmingamer** [SmartlyDressedGames/Unturned-3.x-Community#240]
Hello @SDGNelson I saw in one of your release notes dated 23/03/2018 that you defaulted back a version for battleye until the overlay issue gets fixed. While that update was received, and I was uploading a couple of map workshops I did notice Unturned requiring me to restart the game for the overlay to work before submitting files. The game recognized the overlay as working but every time I used the overlay shortcut it would basically recognize my character in-game as opening my inventory. So at this point in time, I'm not sure where that leads us in this development with getting the overlay fixed, but clearly the overlay does need to be fixed and the current version of Unturned should probably be looked a bit after as well. Since most Unturned Communities are taking affect of the current version becoming obsolete by means of lack of player base on servers due to not as many implementations or improvements have been added that we as server owners have hoped for.

**Comment by Jonnyfencing1** [comment]
The version was reverted again because of BattlEye

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Trojaner25** [comment]
The revert got reverted.
#239

**Comment by PrimeOpalGamer** [comment]
so Overlay is still confirmed Broken as of today?

**Comment by joeytheadmingamer** [comment]
Correct. :(

**Comment by PrimeOpalGamer** [comment]
Update 3.23.9.1 fixed Overlay issue
