### ISSUE TITLE
My server crash when 1 player join  (Error logs in the console)

### ISSUE THREAD

**Issue by Peubo** [SmartlyDressedGames/Unturned-3.x-Community#2401]
BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Davy Jones [Aiyanna [HotNati]]/Third/Skeleton/Left_Hip/Left_Leg"
(Filename:  Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Davy Jones [Aiyanna [HotNati]]/Third/Skeleton/Right_Hip/Right_Leg"
(Filename:  Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Davy Jones [Aiyanna [HotNati]]/Third/Skeleton/Spine/Left_Shoulder/Left_Arm"
(Filename:  Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Davy Jones [Aiyanna [HotNati]]/Third/Skeleton/Spine/Right_Shoulder/Right_Arm"
(Filename:  Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Davy Jones [Aiyanna [HotNati]]/Third/Skeleton/Spine/Skull"
(Filename:  Line: 0)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Davy Jones [Aiyanna [HotNati]]/Third/Skeleton/Spine"
(Filename:  Line: 0)

**Comment by TH3AL3X** [comment]
I'm pretty sure your server is not crashing, is just normal error messages....

**Comment by SDGNelson** [comment]
Unfortunately those warnings cannot be disabled, but I have bugging Unity about it for years. (axis aligned negative scaling works fine)

You can ignore those without issue. If the server is actually crashing feel free to comment and I will re-open.
