### ISSUE TITLE
Is there any line of code to spawn zombies?

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2402]
I tried the "ZombieManager.instance.addZombie" but I can't get it to work ...
I suppose it will be a problem with the config.json, since there is limitation of zombies ...

**Comment by SDGNelson** [comment]
Currently zombies can only be respawned, not added.

**Comment by TH3AL3X** [comment]
> Currently zombies can only be respawned, not added.

Pd, can you add that function in a future ?
