### ISSUE TITLE
Cannot run with BattlEye

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [SmartlyDressedGames/Unturned-3.x-Community#2403]
Whenever I try to run Unturned 3 with BattlEye, I get a small popup window that looks like some log which after a while just closes and nothing happens. I have tried reinstalling BattlEye and verifying game file integrity, but nothing appears to work.
Running without BattlEye works just fine, but that obviously prevents me from joining most servers.

The window in question is
![Weird log window](https://user-images.githubusercontent.com/23404706/107881274-eb585b80-6ee3-11eb-854d-e315ec408c19.png)

**Comment by Trojaner** [comment]
Are you using Reshade? If yes, remove it.

**Comment by PlanetTeamSpeakk** [comment]
> Are you using Reshade? If yes, remove it.

No, I'm not. I am not using any mods of any sort.

**Comment by SDGNelson** [comment]
Sorry for the trouble. I recommend trying the relevant suggestions from the BattlEye FAQ here: https://www.battleye.com/support/faq/
If that does not work, then BattlEye support may be able to help find the problem: https://www.battleye.com/contact/

**Comment by TH3AL3X** [comment]
Call me idiot, but this reminds me patchguard mode
