### ISSUE TITLE
skin assets bug

### ISSUE THREAD

**Issue by NikolaiMalashenko** [SmartlyDressedGames/Unturned-3.x-Community#2404]
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5978424/Player.log)

**Comment by SDGNelson** [comment]
It looks like the crash is more likely to related to all the D3D11 errors. The driver being used is unusual:

    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Microsoft Basic Render Driver (ID=0x8c)
    Vendor:   (null)
    VRAM:     949 MB

Do you have a dedicated graphics card?

**Comment by NikolaiMalashenko** [comment]
no i dont have a graphics card

**Comment by NikolaiMalashenko** [comment]
however my cpu has hd graphic capabilities

**Comment by SDGNelson** [comment]
I'm sorry, but in that case I don't think the game can run on your system. Your card does support DX10+, but does not have enough VRAM. I will make a note to benchmark how much VRAM is needed and update the store page min requirements.

**Comment by NikolaiMalashenko** [comment]
i played this game with this pc

**Comment by NikolaiMalashenko** [comment]
i just changed os
from windows 10 basic to windows 10 pro

**Comment by NikolaiMalashenko** [comment]
in fact i have played 1940.6 hours with this pc

**Comment by SDGNelson** [comment]
Interesting that it worked in the past... the reason that I said it had insufficient VRAM is that the error code 0x8007000e is E_OUTOFMEMORY "Direct3D could not allocate sufficient memory to complete the call."

It might be worth checking if there is a driver specific to your integrated graphics, e.g. Intel HD driver, as I assume the Microsoft basic driver is a default fallback. Also if you installed any workshop files recently that might explain an increase in VRAM usage. https://steamcommunity.com/my/myworkshopfiles/?appid=304930&browsefilter=mysubscriptions

**Comment by NikolaiMalashenko** [comment]
no i thought it was the workshop so i de subbed from everithing and reintalled the game

**Comment by NikolaiMalashenko** [comment]
but before i was subbed to like 10 whole pages of workshop items of sort of high quality models mods ranging from super hd vehicles and guns to vanilla looking ones

**Comment by NikolaiMalashenko** [comment]
i also tried force ccommands that jatapa told me to use

**Comment by NikolaiMalashenko** [comment]
and the problem is that the game stops loading at "Found skin assets:447" and then crashes

**Comment by SDGNelson** [comment]
Did you check for a graphics driver? Would google your laptop or CPU name plus graphics driver.

**Comment by NikolaiMalashenko** [comment]
so i cant get the thing it says i dont met the minimum requirements

**Comment by NikolaiMalashenko** [comment]
btw i have an intel i5 7400 3ghz

**Comment by SDGNelson** [comment]
It looks like this might be what you need: https://downloadcenter.intel.com/download/30148/Intel-Graphics-Windows-10-DCH-Drivers

**Comment by NikolaiMalashenko** [comment]
so it is for windows 64 and i got 32

**Comment by SDGNelson** [comment]
Are you sure? According to this it is a 64-bit processor:
https://ark.intel.com/content/www/us/en/ark/products/97147/intel-core-i5-7400-processor-6m-cache-up-to-3-50-ghz.html

**Comment by NikolaiMalashenko** [comment]
yes its 64 but the os is 32

**Comment by NikolaiMalashenko** [comment]
cause the dude who installed it said that he tought that it was 32 and that i have to pay him again for the new software

**Comment by SDGNelson** [comment]
Nowadays Microsoft lets you upgrade to 64-bit for free, but you will have to reinstall Windows. That is not something I can help with however.
