### ISSUE TITLE
[Stockpile Suggestion] Inspecting before purchasing

### ISSUE THREAD

**Issue by AnimaticFreak** [SmartlyDressedGames/Unturned-3.x-Community#2408]
Considering the stockpile is now embedded in the game, could there be a way to preview or inspect cosmetics and skins before you buy them?

**Comment by SDGNelson** [comment]
On my wish list, but I did not get to it in time for the initial release. Steam will eventually add support for Inventory Service (non-Valve) games to have inspect item buttons, so the in-game Stockpile inspect will probably be added around the same time.
