### ISSUE TITLE
[Issue] Engine Helicopter custom audio pitch arguments

### ISSUE THREAD

**Issue by ZoliWorks** [SmartlyDressedGames/Unturned-3.x-Community#2410]
Hello

Came across this while working on some stuff:
**Pitch_Idle** and **Pitch_Drive** arguments are overwritten by default values when using **Engine Helicopter**
Seems to work fine with **Engine Plane** however, so I thought I'd pop it here. 

If possible, a fix would be very appreciated!

Cheers, 
Zoli

**Comment by SDGNelson** [comment]
Would make sense to enable this. I will mark it as "next update", but not for this coming Friday to keep the potential problems minimal for Elver.

**Comment by ZoliWorks** [comment]
Appreciate it. I'll use a workaround till then

**Comment by SDGNelson** [comment]
Added for the next update. The helicopter default is 0.03 and the blimp default is 0.1.
