### ISSUE TITLE
Game Update follow-able channel in discord.

### ISSUE THREAD

**Issue by NoSharp** [SmartlyDressedGames/Unturned-3.x-Community#2412]
A followable channel which announces when the game updates, I'm saying this is do-able with just a simple Webhook which gets triggered by a release or any "github action" or whatever Ci/CD system is used.
It's extremely aggreviating when I'm late to an update because it's not posted anywhere. For context, I manually patch the updates so if you're able to get this working I can finally automate this without having to ping steam every 10 minutes.

**Comment by NoSharp** [comment]
If you wanted to improve QOL using Unturned perhaps an RSS feed would work.

**Comment by SDGNelson** [comment]
Sorry for the aggravation. The patch this morning was an optional Win64 client only BattlEye update, but I realize there is no way to test that externally at the moment.

Discord hook was on my to-do list a while ago but I never got around to it. I will read about it today.

**Comment by SDGNelson** [comment]
I cleaned up some of the build release process and integrated the Discord hook, so starting this Friday there will be automatic notifications on the official Discord server containing the Steam BuildID and version.

**Comment by Trojaner** [comment]
>  For context, I manually patch the updates so if you're able to get this working I can finally automate this without having to ping steam every 10 minutes.

It is 2021, time to use harmony

**Comment by NoSharp** [comment]
> 
> 
> > For context, I manually patch the updates so if you're able to get this working I can finally automate this without having to ping steam every 10 minutes.
> 
> It is 2021, time to use modules and harmony

I do use harmony for a majority of my stuff, but my entry point is manually patched.

**Comment by NoSharp** [comment]
Thank you very much @SDGNelson for doing this so quickly.
