### ISSUE TITLE
Requesting sentry custom target acquired/lost effects

### ISSUE THREAD

**Issue by obfuscateClarity** [SmartlyDressedGames/Unturned-3.x-Community#2414]
Hey hope you've been well! Need some assistance with this one.
Currently if a sentry is alerted, the effect manager calls effect 92. When the sentry loses lock, effect 93 is called. 
Requesting an option to manually replace/overwrite with a custom effect. Hoping to publish a custom sentry mod.
Thank you!

**Comment by SDGNelson** [comment]
Yeah would make sense to update these as not hardcoded. Originally the sentry was not moddable.

**Comment by obfuscateClarity** [comment]
> Yeah would make sense to update these as not hardcoded. Originally the sentry was not moddable.

That's great, thank you!
