### ISSUE TITLE
skin assets bug

### ISSUE THREAD

**Issue by NikolaiMalashenko** [SmartlyDressedGames/Unturned-3.x-Community#2418]
i have played 1940 hours of unturned with this pc but i changed os to windows 10 pro and now i cant play unturned

**Comment by NikolaiMalashenko** [comment]
i got 16gb ram an intel i5 and 1tb of storage space

**Comment by Trojaner** [comment]
Please stop spamming. GitHub issues is not a chat program. Please don't spam issues either. Your issue was already closed at https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2404.

**Comment by SDGNelson** [comment]
Closing to re-open the other duplicate issue.
