### ISSUE TITLE
Server didn't download the newest mod

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2419]
Logs:
Workshop item found in cache: 1729289235
Installing workshop item: 1729289235
Installed workshop item: 1729289235

Server load the Workshop files by using cache everytime. It is old version files. I have already updated the mod. 
The `Workshop\Steam\appworkshop_304930.acf` file shows:

		"1729289235"
		{
			"size"		"81833034"
			"timeupdated"		"1611331878"
			"manifest"		"7698254446269528689"
		}

`1611331878` means `2021-01-23 00:11:18`,  and I have already updated the mod twice after 23 Jan.

![p1](https://user-images.githubusercontent.com/64722485/108365356-17e8dc00-7232-11eb-9262-f416e039f372.png)

Server logs:
[Server_PEI.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6003181/Server_PEI.log)

appworkshop_304930.acf:
[appworkshop_304930.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6003184/appworkshop_304930.zip)

**Comment by SDGNelson** [comment]
The game checks whether the file is flagged as needing an update (k_EItemStateNeedsUpdate), but that does not seem to always be set. For the next update I will add a check comparing the online created/updated timestamp to the local timestamp.

**Comment by SDGNelson** [comment]
Added for the update. Thanks for bringing this up!

**Comment by warren39** [comment]
@SDGNelson, Sorry to tell you that the Client also run into this issue. Not only the Server.
Some players report   they cannot join my server. I found that their workshop files were outdated. And need to delete the cache files at `steamapps\workshop\content\304930` by manually. Or reinstall Unturned.

**Comment by SDGNelson** [comment]
The timestamp comparison was only added to the server for now, but I suppose the client could do something similar. I would be more hesitant on that side though because the Steam client should be better about keeping workshop files up-to-date in accordance with the player's settings. Players can also "verify game files" to force a workshop update.

**Comment by warren39** [comment]
Steam keeps files up-to-date all the time. But since recently updates (may be after a month ago), it looks like to not work anymore in some players. I will try to find the reason if player reports this next time.

**Comment by warren39** [comment]
Player Logs:
[2021-02-21 20:56:18] Initializing ClientTransport_SteamNetworking
[2021-02-21 20:56:23] Server specified 1 workshop item(s), querying details
[2021-02-21 20:56:24] Server's allowed IP for Workshop downloads: 127.0.0.1
[2021-02-21 20:56:24] Installing cached workshop item: 1729289235

Player File `steamapps\workshop\appworkshop_304930.acf`:

		"1729289235"
		{
			"manifest"		"7698254446269528689"
			"timeupdated"		"1611331878"
			"timetouched"		"1613877049"
			"BytesDownloaded"		"39156816"
			"BytesToDownload"		"39156816"
		}

Cached at "1611331878", I have already updated the mod twice after 23 Jan.
It is same problem with Server side.

**Comment by SDGNelson** [comment]
Hmm... I suppose I will do a similar check on the client. It feels messy though. 😟

**Comment by warren39** [comment]
Thanks for support. You can release a preview version to find out whats going on. I can join the preview Server with an outdate workshop mod.

**Comment by SDGNelson** [comment]
Added for the next update. :)
