### ISSUE TITLE
Gasmask issue

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2420]
When a gasmask is dropped onto the ground it doesnt show up in nearby inventory. Been like this for a while and pretty annoying. Please fix <3

**Comment by SDGNelson** [comment]
Checked by dropping a gasmask and it showed in nearby inventory even after returning, however the center is near the edge of the collider so I can imagine it would be obstructed in some cases.

**Comment by SDGNelson** [comment]
Adjusted for the next update.
