### ISSUE TITLE
Bullcrap drop rate.

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2423]
I literally unboxed 125 Elver II cases and only got 1 frickin mythical. What the hell Nelson. 3% my ass.

**Comment by SDGNelson** [comment]
Sorry to hear of your unfortunate luck. :(
The odds really are 3% however. On the generator side it is hardcoded at 3%, and then independently a separate program verifies that the mythical drop chances are 3% (among other error checks) before submission to avoid what happened to TF2 last year. I also just manually checked and it is 3%.
