### ISSUE TITLE
PSA: `receiveClient` and `receiveServer` rewrite now on preview branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2424]
This should not break any plugins unless you were using `OnServerReadingPacket`, `OnServerWritingPacket`, or were injecting code into the message routing. If you were doing some low-level network patching it is probably worth trying the preview branch to double-check whether your plugins need adjustments, in which case I will try to help.

Next week I will also replace all of Rocket / LDM's usage of `OnTriggerSend` with new events in order to start prepping for deprecating that.

**Comment by SDGNelson** [comment]
This brings the colossal mess of `Provider.cs` down a couple thousand lines. 😃

**Comment by warren39** [comment]
Exception on .255:

[2021-02-23 21:06:10] Exception raised when RPC invoked askEquip:
[2021-02-23 21:06:10] Already at the end of stream
[2021-02-23 21:06:10]   at SDG.Unturned.NetPakReader.ReadBits (System.Int32 valueBitCount, System.UInt32& value) [0x00050] in <3404c20ff3ac46598cd640f9848ec6e9>:0 
  at SDG.Unturned.SystemNetPakReaderEx.ReadUInt8 (SDG.Unturned.NetPakReader reader, System.Byte& value) [0x00000] in <3404c20ff3ac46598cd640f9848ec6e9>:0 
  at SDG.Unturned.NetPakBlockImplementation.read (System.Type type) [0x00139] in <3404c20ff3ac46598cd640f9848ec6e9>:0 
  at SDG.Unturned.NetPakBlockImplementation.read (System.Int32 offset, System.Type[] types) [0x0000d] in <3404c20ff3ac46598cd640f9848ec6e9>:0 
  at SDG.Unturned.SteamPacker.getObjects (Steamworks.CSteamID steamID, System.Int32 offset, System.Int32 prefix, System.Int32 size, System.Byte[] bytes, System.Type[] types) [0x00020] in <3404c20ff3ac46598cd640f9848ec6e9>:0 
  at SDG.Unturned.SteamChannel.receive (Steamworks.CSteamID steamID, System.Byte[] packet, System.Int32 offset, System.Int32 size) [0x00398] in <3404c20ff3ac46598cd640f9848ec6e9>:0

**Comment by warren39** [comment]
UI issue:


https://user-images.githubusercontent.com/64722485/108857527-26663780-7626-11eb-987f-9ac0300890cd.mp4

**Comment by warren39** [comment]
Some RPC method won't work anymore, if we call by this way:
`VehicleManager.instance.channel.send("tellVehicleDestroy", ESteamCall.ALL, ESteamPacket.UPDATE_RELIABLE_BUFFER, vehicle.instanceID);`
Now only working by `VehicleManager.askVehicleDestroy(vehicle);`
That will be breaking many plugins I guess.

**Comment by SDGNelson** [comment]
Thanks for these reports and trying it out! Will investigate today.

**Comment by SDGNelson** [comment]
@warren39:

1. In which context are you calling the "tellVehicleDestroy" RPC, and how is it not working - e.g. does it throw an exception? The askVehicleDestroy method still calls channel.send the exact same way:

2. Funny catch about askEquip. When dequipping the client was not sending the hash, instead relying on the server reading some garbage data as the hash. With these rewrites the server has some debug-only exceptions which caught that. Will fix to not rely on that.

**Comment by PandahutMiku** [comment]
I tested it a fair bit without issues, and most plugins didn't need any upgrading.

The Server Viewer UI pointing out the server is outdated/disallowing Join is a really nice addition. I assume you added it because of the breaking netcode changes. It would be nice if it clearly stated "Your Client is outdated, you can re-open unturned to update it" or "This Server is outdated and needs to be updated by the Server Owners", but I understand the way it is right now is that they are just strings and this wouldn't be the easiest thing to add. Every Friday though, there are always people confused by the update and have to be reminded to update their games or wait for the server to update. I can almost guarantee you some people are going to be confused by the missing Join Button and not read the numbers.

**Comment by warren39** [comment]
Oh, I forget to update my dll Referenes in IDE. The RPC method running well now. My bad XD

**Comment by baranmod** [comment]
just checked, getting this exception in client log while trying to join server. What could this be related to? https://pastebin.com/7TUENQB4
On first try it doesn't show cancel button and need to close unturned with alt+f4, on second try it stucks on queue position and shows cancel button

**Comment by SDGNelson** [comment]
Thanks @PandahutMiku! Good idea about the better messaging. I will do those suggestions today.

@warren39 actually I forgot to mention: invoking RPCs by name will also probably be removed. Why are you invoking it manually rather than using askVehicleDestroy?

@baranmod those exceptions and error checks will only be in the debug builds, so it should work normally in the actual release. It sounds like the plugins are manually sending the kicked packet without the reason strings which is why the client reads further.  Why are they manually sending it rather than using `Provider.kick`? Manually doing it will almost certainly cause problems.

**Comment by warren39** [comment]
> @warren39 actually I forgot to mention: invoking RPCs by name will also probably be removed. Why are you invoking it manually rather than using askVehicleDestroy?

I'm already changed into using askVehicleDestroy. But some RPCs have no corresponding methods. Such as `tellAnimal`, I can't find any `askAnimal` or `sendAnimal` method. And about `SDG.Unturned.PlayerInventory#sendItemRemove`, It is privated level. I can't used it.

**Comment by SDGNelson** [comment]
@warren39:

There is no supported way to spawn new animals at the moment aside from the admin command for testing, but it might be added eventually after animals get some improvements. By default the game recycles existing animals once the pack is all dead. 

sendRemoveItem is automatically called when removing an item, so if you are manually calling it there is probably a bug. Also if the item is equipped then PlayerEquipment needs to be notified separately at the moment, again something which ought to be cleaned up eventually.
