### ISSUE TITLE
xd

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2425]
https://youtu.be/fmww6ADT-J8
Proof of my cursed unboxing of 125 cases and only 1 mythical. Im not the only one this happened to. It happened to both of us in the same video something is definitely off. 250 and only 3 myths, one of then being is literally the last 4 cases. Please do me justice Nelson <3 https://steamcommunity.com/id/DJ_Lucky/

**Comment by SDGNelson** [comment]
That's a ton of boxes. First of all I should have said before, and on behalf of danaby2 and Renaxon as well: thank you for the financial support!
Unfortunately it is just purely random. It would be unfair of me to intervene.
