### ISSUE TITLE
Chat Command Bug

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#2429]
I noticed that after the last few updates the @weather 0 (@weather null) command stopped disabling custom weather.

**Comment by SDGNelson** [comment]
Are you using the scheduled weather, or triggering it by guid? For scheduled weather "None" needs to be used instead of zero.

**Comment by SDGNelson** [comment]
It might also be an error with the weather if you can attach the Client.log file.

**Comment by Alex-Well** [comment]
@SDGNelson 
The problem is observed even when calling vanilla custom weather existing as an example.
/weather 819982d7a2b6453488a8c4c5d9efe67f

**Comment by SDGNelson** [comment]
Whoops - thanks for the report! When reworking the events for NPCs it was mistakenly changed to broadcast an event for the disabled weather. Fixed for the next update.
