### ISSUE TITLE
Linux Vanilla Server throws abort/segfault errors during startup

### ISSUE THREAD

**Issue by JohannesWeitnauer** [SmartlyDressedGames/Unturned-3.x-Community#243]
I tried to set up a vanilla server on Ubuntu Server 16.04.3 multiple times now, but can't get it to work.

I installed steamcmd via apt-get install steamcmd and successfully downloaded the game via ID (304930). I then started steamcmd in a seperate screen and logged in to ensure that steam was running.

But if i then enter sudo ./Unturned.x86_64 -nographics -batchmode +lanserver/test it instantly gives me a Segmentation Fault (Core dumped) error and in the log it says that the gameserver api couldnt be initialized.

If I try to start the server with sudo xvfb-run ./Unturned.x86_64 -nographics -batchmode +lanserver/test it gets to "Importing game controller configs" but after a few seconds also throws the error Aborted (Core dumped).

I tried many different solutions, reinstalled steamcmd and the server multiple times, tried copying the steamclient.so files and tried to use the RocketLauncher as many guides suggested, but nothing worked for me.

I really want to host unturned vanilla on my linux machine because it is the place where I host other gameservers and I dont want to get an additional server just for unturned and want to keep my electricity cost down.

Any help would be greatly appreciated ;)

**Comment by Jonnyfencing1** [comment]
Have you tried using WINE

**Comment by JohannesWeitnauer** [comment]
For a second yeah, but not in-depth. Do you have any guide that uses wine for me?

**Comment by Jonnyfencing1** [comment]
That's for Rocket but I'll try to find the guide I used to install it and post it here

**Comment by Jonnyfencing1** [comment]
http://ubuntuhandbook.org/index.php/2015/12/install-wine-1-8-stable-new-ppa/

**Comment by JohannesWeitnauer** [comment]
But that's just for wine, not for unturned?
RocketLauncher still means vanilla unturned, right?

**Comment by Jonnyfencing1** [comment]
RocketLauncher will have some basic Rocket commands but essentially yes

**Comment by JohannesWeitnauer** [comment]
steamcmd.exe wont work for me, as it requires a GUI, and I'm on ubuntu server, so no gui..

**Comment by Jonnyfencing1** [comment]
get  the linux version then u can do ./steamcmd.sh

**Comment by JohannesWeitnauer** [comment]
Will try that, I previously had it installed as a package with apt-get install steamcmd, and that worked fine. But I think that RocketLaucher / Unturned don't like that, as at least one of them seems to require the steamcmd as a .sh in a defined folder..

**Comment by Jonnyfencing1** [comment]
do ./start.sh

**Comment by JohannesWeitnauer** [comment]
From within the scripts folder? you refer to the RocketLauncher here, right? I am currently working on getting my Mono to 3.12 instead of 4.whatever to get the guide from the unturned wiki to hopefully work..
http://unturned.wikia.com/wiki/Hosting_a_Dedicated_Server

**Comment by JohannesWeitnauer** [comment]
b/c other guides moved the start and update scripts inside the unturned folder

**Comment by JohannesWeitnauer** [comment]
I have resolved the issue by rolling Mono back to 3.12 and then following the guide on the wiki: http://unturned.wikia.com/wiki/Hosting_a_Dedicated_Server . I had to send the RocketLauncher.exe to my Server via scp, as it wasn't included in the zip I acquired via wget for some reason. But after that, everything worked fine. Now the only thing left is customizing and port forwarding.

**Comment by JohannesWeitnauer** [comment]
If anyone else stumbles over this thread, you can contact me at jojogamesdev@gmail.com, if you need assistance, I *might* be able to help.

**Comment by Jonnyfencing1** [comment]
If you could contact me via discord Jonny#9247 I'd like to talk to you
