### ISSUE TITLE
[Feature Request] "Reclined" sitting position for vehicle passenger seats

### ISSUE THREAD

**Issue by ZoliWorks** [SmartlyDressedGames/Unturned-3.x-Community#2430]
Currently the driver can either sit normally, or in a reclined position. Would it be possible to expand upon this and either make it affect the passenger seats or create a new argument that affects passenger seats? (just like **cam driver** and **cam passenger** offset)

Cheers,
ZWS

**Comment by SDGNelson** [comment]
Sorry, but this is unlikely to happen anytime soon because the current animation setup is not very extendable for new poses like that. It is something I intend to work on, but no ETA.

**Comment by ZoliWorks** [comment]
Understandable, no problem.
