### ISSUE TITLE
Feature Request: Native Rcon

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2433]
Hey Nelson,

I remember seeing somewhere that someone requested rcon to be added to the game itself. I was wondering what the status of that request might be, as some individuals plan on using AMP by CubeCoders but it isn't really possible at this time due to rcon not actually in the game.

Thank you!

**Comment by SDGNelson** [comment]
Briefly looked it up, do they have an RCON protocol? It is still relatively low priority but will be easier now that the message handling has been rewritten.

**Comment by SDGNelson** [comment]
Closing because there is the existing issue #1726, but feel free to comment and I will re-open.
