### ISSUE TITLE
Failed to stream non chunk.

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#2434]
Recently updated the server and I am getting reports that nobody can join. Only error I see is "Failed to stream non chunk." and disconnect messages from the players. Booting my game now to see if I can test some more but is this potentially a bug from the recent update?

**Comment by Jerico97** [comment]
Similar
Kicked from the server without reason

**Comment by SDGNelson** [comment]
That would happen if something is calling `SteamChannel.closeWrite` with wrong packet type, but plugins should not be calling that in the first place. If the dev can post an issue I can help find an alternative, but none of the vanilla code would be causing that (all of the older packet types are marked obsolete and would cause a warning).

**Comment by Bradler26** [comment]
Ok thanks for the info. Will go through plugins now and i'll close this with the plugin causing the issue once I find it so it can help others.

**Comment by Bradler26** [comment]
Ok turns it out was a custom plugin that makes doors openable by in-game groups instead of steam groups. Thanks for the info. 

If its not too much to ask would it be possible to build in a form of debugging that says the plugin thats using code thats depreciated? I see there are a few errors showing on boot saying some plugins are using events that are about to be depreciated and it would be quite useful if it could list the plugin name/s

**Comment by baranmod** [comment]
lots of servers down. It didn't have any issues on preview branch, however, after update it gives "kicked because:" message once someone tries to join. Some players join, some others getting kicked. No errors in client or server logs whatsoever

**Comment by dzonyloker** [comment]
> lots of servers down. It didn't have any issues on preview branch, however, after update it gives "kicked because:" message once someone tries to join. Some players join, some others getting kicked. No errors in client or server logs whatsoever
> 
> Was removing plugins one by one with a hope to find a corrupted one. I thought I found the right one, removed, didn't kick for a while. Once other players started connecting to server, most of them getting kicked
> 
> Edit: ok, seems like 50%++ of plugins just broke. Cosmetics, garages etc etc. Once player does something which goes through some plugin - he just gets kicked without a reason listed

![unknown](https://user-images.githubusercontent.com/13457675/109347076-e051e380-7872-11eb-8b69-711e563568f1.png)

**Comment by Bradler26** [comment]
Yeh turns out the failed to stream non chunk is unrelated. I'm still getting the kick error without any errors in console. It looks to be Uconomy plugin that I use so the dev is taking a look now but any advise would be appreciated.

**Comment by SDGNelson** [comment]
@Bradler26: unfortunately there is no straightforward way to log that, and there are also lots of plugins doing things in unexpected ways. I have been aiming to preserve compatibility as much as possible, but some things will inevitably have to break. Glad to hear you found the plugin in your case however.

@baranmod sorry to hear that so many are affected. :/
Only the plugin devs can fix, but I am open to assist and add events or public API as-needed.

**Comment by Buldozeris** [comment]
> > lots of servers down. It didn't have any issues on preview branch, however, after update it gives "kicked because:" message once someone tries to join. Some players join, some others getting kicked. No errors in client or server logs whatsoever
> > Was removing plugins one by one with a hope to find a corrupted one. I thought I found the right one, removed, didn't kick for a while. Once other players started connecting to server, most of them getting kicked
> > Edit: ok, seems like 50%++ of plugins just broke. Cosmetics, garages etc etc. Once player does something which goes through some plugin - he just gets kicked without a reason listed
> 
> ![unknown](https://user-images.githubusercontent.com/13457675/109347076-e051e380-7872-11eb-8b69-711e563568f1.png)

Same. I ended up deleting half of the plugins. Few kicked right on the connect, deleted those, but after that i noticed, that multiple other plugins kick players for different events, like using garage, jump, cosmetics...

**Comment by baranmod** [comment]
> @Bradler26: unfortunately there is no straightforward way to log that, and there are also lots of plugins doing things in unexpected ways. I have been aiming to preserve compatibility as much as possible, but some things will inevitably have to break. Glad to hear you found the plugin in your case however.
> 
> @baranmod sorry to hear that so many are affected. :/
> Only the plugin devs can fix, but I am open to assist and add events or public API as-needed.

I would deal with that if it only happens to me and wait for devs to fix plugins. But seems like its happening for everyone who is using any plugins. So waiting for devs to fix something when none of the devs can actually tell where is the problem is not really a solution

**Comment by SDGNelson** [comment]
@baranmod Public APIs should still behave the same and are used by the game, but recompiling plugins may highlight some problems. Anything using reflection or patching to use private APIs may be missing or broken, and is unsupported, but a public API can be added if the devs post here.

**Comment by SDGNelson** [comment]
My bad with the enum ordering change. In the .1 patch now the older values (15 and 16) are remapped to new ones, but where possible recompiling is recommended. Anywhere that any of you are manually sending RPCs please let me know (separate issue) and I will be happy to add a maintained alternative.
