### ISSUE TITLE
OnGestureChanged_Global isn't a complete replacement of UnturnedPlayerEvents.OnPlayerUpdateGesture

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2435]
OnGestureChanged_Global isn't firing for punches but is for everything else. Not really sure why either, will try to look at it again in a bit.

Edit 2: It looks like punches is sent to sendGesture without sending to all, so it's sent as ESteamCall.Not_Owner which excludes the server, so the server never receives it, itself. Might make more sense to move the OnGestureChanged_Global down to the sendGesture method.

The replacement for that event, in general, isn't very clean

```csharp        
internal static void InternalOnGestureChanged(PlayerAnimator animator)
        {
            UnturnedPlayerEvents instance = animator.GetComponent<UnturnedPlayerEvents>();
            UnturnedPlayer rp = UnturnedPlayer.FromPlayer(animator.player);
            try
            {
                // This is how Rocket converted the enum prior to onTriggerSend rewrite.
                PlayerGesture rocketGesture = (PlayerGesture) Enum.Parse(typeof(PlayerGesture), animator.gesture.ToString());
                OnPlayerUpdateGesture.TryInvoke(rp, rocketGesture);
                instance.OnUpdateGesture.TryInvoke(rp, rocketGesture);
            }
            catch { }
        }
```
As far as I know, that will never fire and always error into the empty catch method since the spelling case of the two enums (Rocket's vs Unturned's Native) is different. It seemed it worked before because the case got changed somewhere after.

It would probably make more sense to use a case statement

```csharp       
 internal static void InternalOnGestureChanged(PlayerAnimator animator)
        {
            UnturnedPlayerEvents instance = animator.GetComponent<UnturnedPlayerEvents>();
            UnturnedPlayer rp = UnturnedPlayer.FromPlayer(animator.player);
            try
            {
                // This is how Rocket converted the enum prior to onTriggerSend rewrite.
                PlayerGesture rocketGesture = ConvertGesture(animator.gesture);
                OnPlayerUpdateGesture.TryInvoke(rp, rocketGesture);
                instance.OnUpdateGesture.TryInvoke(rp, rocketGesture);
            }
            catch (Exception exception)
            {
                Logger.LogException(exception, $"Error on Gesture Change {animator}, {animator.gesture}");
            }
        }

        internal static PlayerGesture ConvertGesture(EPlayerGesture input)
        {
            switch (input)
            {
                case EPlayerGesture.NONE: return PlayerGesture.None;
                case EPlayerGesture.INVENTORY_START: return PlayerGesture.InventoryOpen;
                case EPlayerGesture.INVENTORY_STOP: return PlayerGesture.InventoryClose;
                case EPlayerGesture.PICKUP: return PlayerGesture.Pickup;
                case EPlayerGesture.PUNCH_LEFT: return PlayerGesture.PunchLeft;
                case EPlayerGesture.PUNCH_RIGHT: return PlayerGesture.PunchRight;
                case EPlayerGesture.SURRENDER_START: return PlayerGesture.SurrenderStart;
                case EPlayerGesture.SURRENDER_STOP: return PlayerGesture.SurrenderStop;
                case EPlayerGesture.POINT: return PlayerGesture.Point;
                case EPlayerGesture.WAVE: return PlayerGesture.Wave;
                case EPlayerGesture.SALUTE: return PlayerGesture.Salute;
                case EPlayerGesture.ARREST_START: return PlayerGesture.Arrest_Start;
                case EPlayerGesture.ARREST_STOP: return PlayerGesture.Arrest_Stop;
                case EPlayerGesture.REST_START: return PlayerGesture.Rest_Start;
                case EPlayerGesture.REST_STOP: return PlayerGesture.Rest_Stop;
                case EPlayerGesture.FACEPALM: return PlayerGesture.Facepalm;
            }
            Logger.LogError($"Error, could not resolve {input} via ConvertGesture to send out OnPlayerUpdateGesture");
            return PlayerGesture.None;
        }
```

It's not clean and rocket really shouldn't have its own gesture stuff anyway, but it would ensure backwards compatibility.

ps. I had to recompile some plugins for this update, but having zero issues with Pandahut servers right now besides the punch event replacement. 400 Players Online.

**Comment by SDGNelson** [comment]
Glad to hear your servers have been working nicely. Phew!

Sorry about the punching oversight. I am surprised about the parsing though because neither the Rocket nor Unturned naming would have changed in years, so I would think it was broken beforehand too?

What are you using the punching event for? A vanilla event should just be added for it.

**Comment by PandahutMiku** [comment]
> Glad to hear your servers have been working nicely. Phew!
> 
> Sorry about the punching oversight. I am surprised about the parsing though because neither the Rocket nor Unturned naming would have changed in years, so I would think it was broken beforehand too?
> 
> What are you using the punching event for? A vanilla event should just be added for it.

I think it wasn't broken before because the letter case got changed from when it was outgoing as a packet and re-parsed by Rocket. If you re-place the empty catch statement and Log the result, it spits out errors about the case being different/unable to find the enum every time you change gesture. The Enum Parse method also has an overload for ignoring the case, which might work as well.

We were using the punch event for custom barricade/structure commands, i.e punch a sign and have it execute a specific command.

**Comment by SDGNelson** [comment]
Outgoing it was casted from byte to enum, so the string should have been the game's. 😕 Regardless I will replace the string parse with your switch, and add a punching event for this afternoon.

**Comment by PandahutMiku** [comment]
> Outgoing it was casted from byte to enum, so the string should have been the game's. 😕 Regardless I will replace the string parse with your switch, and add a punching event for this afternoon.

Thanks!

Just in case someone goes through this in the future, the added event was PlayerEquipment.OnPunch_Global
