### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by vloviuby** [SmartlyDressedGames/Unturned-3.x-Community#2437]
After the last update, an error appeared with which you can put any server. If, when receiving damage from zombies with 1 - 5 hp, you write the /home command, then during the TP the zombies will kill you and all players on the server will crash. Works on all servers. An urgent fix is ​​required.

**Comment by The-Emperator** [comment]
https://disk.yandex.ru/i/6bk_NSqHtl7SNg

**Comment by SDGNelson** [comment]
Will double-check in vanilla, but if it only happens with plugins then the plugins will need to be updated.

**Comment by vloviuby** [comment]
Now I will throw the video on YouTube

**Comment by vloviuby** [comment]
https://youtu.be/noqgX47lrnw 
Please watch this video

**Comment by vloviuby** [comment]
Nelson, fix it with a fork...) Plugins flew, commands don't work, kicks from servers. Frequent kick reasons: /home, /kit, Player kills, etc.

**Comment by SDGNelson** [comment]
I don't think this is a vanilla bug, and the packet type remapping in the patch should resolve older plugins, but feel free to comment and I will re-open.
