### ISSUE TITLE
Kicking for inactivity still a problem

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#244]
Hey Nelson, please consider fixing this bug. If it's a plugin or Rocket, please let me know. However, many people have told me their server does this, and I believe these messages are vanilla.

![image](https://user-images.githubusercontent.com/7349712/38166674-d6a2e56e-34f5-11e8-9701-cb5c76ab203a.png)

**Comment by SDGNelson** [comment]
You're right: that's a vanilla kick. Double-checked and it should only be kicking in these circumstances:

1. Last packed was received more than Server.Timeout_Game_Seconds config value seconds ago.
2. They joined more than Server.Timeout_Game_Seconds seconds ago, and their ping is higher than Server.Max_Ping_Milliseconds.

It's possible that some sort of stall is causing the server to think their ping has spiked and kicked everyone. I'll add investigating a fix for this to my to-do. In the mean time could you try increasing that Max_Ping_Milliseconds value to see if it prevents these kicks?

**Comment by N1GHTPATROL** [comment]
I doubled my value from 750ms to 1500ms, so I'll reply back if the problem persists. Thanks for the response :)

**Comment by ConorJLH** [comment]
My server also started doing this today! Let me know if you can grab a fix. 

Best Regards,
Conor

**Comment by RainOfPain125** [comment]
Not sure if this is the same problem, or already pointed out by Nelson, but this error popped into console - then it kicked someone for inactivity

Rocket.Unturned >> Failed to receive packet "tellLife" -> Exception in <bindDelegates>b__16_2: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Events.UnturnedPlayerEvents.TriggerSend (SDG.Unturned.SteamPlayer s, System.String W, ESteamCall X, ESteamPacket l, System.Object[] R) [0x00000] in <filename unknown>:0
Kicking for inactivity: PlayerID: 76561198275290235 Name: kscepanovCSGOWitch.com Character: kscepanov
Broadcast: kscepanov disconnected from the server.
Disconnecting: PlayerID: 76561198275290235 Name: kscepanovCSGOWitch.com Character: kscepanov

**Comment by N1GHTPATROL** [comment]
This still seems to happen on my servers, even with a higher max ping and packets per second.

**Comment by RainOfPain125** [comment]
> This still seems to happen on my servers, even with a higher max ping and packets per second.
Same. Updated my timeout to 500 instead of 350 and it's virtually the same. Your timeout of 1500 seems like a bit of a ridiculous number... 750 sounds high enough already ,_, @N1GHTPATROL

**Comment by DronXa** [comment]
As a temporary solution try to put Timeout_Game_Seconds to higher values.

**Comment by SDGNelson** [comment]
For the next update I've cleaned up this code a bit to make it clearer, and adjusted the ping calculation to subtract that frame's processing delay in case the server was stalling for a long time. We'll see if that makes a difference.

**Comment by RainOfPain125** [comment]
2 weeks later this is still a recurring problem on all of my servers, despite turning the timeout higher in the config.

```
Kicking for inactivity: PlayerID: 76561198256001813 Name: ~>N![k]olo' ΓêÜ[!] Character: #~> N![k]olo' [!]
Disconnecting: PlayerID: 76561198256001813 Name: ~>N![k]olo' ΓêÜ[!] Character: #~> N![k]olo' [!]
Kicking for inactivity: PlayerID: 76561198345620961 Name: ≡ƒöÑ≡ƒÆÑσ¥öJUNIOR ≡ƒÆÑ≡ƒöÑ Character: smokey
Disconnecting: PlayerID: 76561198345620961 Name: ≡ƒöÑ≡ƒÆÑσ¥öJUNIOR ≡ƒÆÑ≡ƒöÑ Character: smokey
Kicking for inactivity: PlayerID: 76561198343598979 Name: Noob- Character: Noob-
Disconnecting: PlayerID: 76561198343598979 Name: Noob- Character: Noob-
Kicking for inactivity: PlayerID: 76561198356017670 Name: AxusGame Character: AxusGame
Disconnecting: PlayerID: 76561198356017670 Name: AxusGame Character: AxusGame
Kicking for inactivity: PlayerID: 76561198310813483 Name: herkuxzx Character: herkuxzx
Disconnecting: PlayerID: 76561198310813483 Name: herkuxzx Character: herkuxzx
```

**Comment by Jonnyfencing1** [comment]
@RainOfPain125 that would be because there haven't been any updates

**Comment by RainOfPain125** [comment]
Yeah, sorry. I thought there was a hotfix and thought said hotfix was supposed to fix this bug.

**Comment by SDGNelson** [comment]
3.23.9.1 included the processing delay adjustment. If that didn't take care of it then I think it's either a very long (30 seconds +) serverside stall which would be extreme, or something lower level that temporarily prevents packets from going through.

**Comment by RainOfPain125** [comment]
@SDGNelson This is still a prevailing problem to say the least. It seems radical to think that something would temporarily prevent packets from going through, such as an anti-virus software (which I dont have). My servers have sufficient resources and shouldn't be stalling at all, yet I continue to have this bug.

Are you sure theres no other possibilities? Could you consider adding an option to disable kicking for 'inactivity'?

**Comment by SDGNelson** [comment]
Here's the relevant line that causes the vanilla inactivity kick:

Time.realtimeSinceStartup - clients[index].timeLastPacketWasReceivedFromClient > configData.Server.Timeout_Game_Seconds || (Time.realtimeSinceStartup - clients[index].joined > configData.Server.Timeout_Game_Seconds && clients[index].ping > configData.Server.Max_Ping_Milliseconds / 1000f)

So to completely disable the vanilla test you could set Timeout_Game_Seconds and Max_Ping_Milliseconds to very large numbers?

**Comment by Jarshoowa69** [comment]
This still happens in 2020, it still happens in my servers even if my config look like this

    "Max_Ping_Milliseconds": 900,
    "Timeout_Queue_Seconds": 15.0,
    "Timeout_Game_Seconds": 200.0,
    "Max_Packets_Per_Second": 80.0,

Is there going to be any fix? Do i really have to make the number 5 digits long to prevent this?
