### ISSUE TITLE
Servers kick players

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2440]
Last update broke a lot of plugins?, idk, but my server works well and when I got 10 players, I think this kick all the players suddenly, i dont know if is for the quantity of players or some plugin, but a lot of servers are broken and a lot of them will need to wait to the devs to fix all the plugins they use. Today will be another update? Or we can just wait to the "devs" fix all, because a lot of devs will not fix the plugins today or tomorrow, or never. And a lot of servers will be closed for this. Thanks for reading, I only want a response, because I can wait, but the users of the servers not.

**Comment by SDGNelson** [comment]
Unfortunately those plugins need to be recompiled for the update, but should not require changes by the devs (yet).

**Comment by ElRicki7u7** [comment]
So... today will be another update or not?
