### ISSUE TITLE
Server will not Connect to Server Panel

### ISSUE THREAD

**Issue by odstfive** [SmartlyDressedGames/Unturned-3.x-Community#2442]
Hi was told to open a separate issue by nelson. Essentially what happens is that since this new update came out, my server and multiple others using Lyhme Hosting are not able to connect our Server Panel to our Server when we open it up it displays the images below. When I try to shut it down it says "Unable to connect to server". I'm not sure what to do, I contacted Lyhme they said that the nodes are down, and I'm not quite sure what that means. But this only happened when I restarted the server after the new update.
![1](https://user-images.githubusercontent.com/79761518/109398449-05923080-790b-11eb-83ff-c9689ecba621.png)
![2](https://user-images.githubusercontent.com/79761518/109398451-06c35d80-790b-11eb-8cd0-ea6c7b85bdb5.png)
![3](https://user-images.githubusercontent.com/79761518/109398452-088d2100-790b-11eb-9292-e7210d79e5df.png)

**Comment by odstfive** [comment]
![Desktop Screenshot 2021 02 27 - 14 50 19 72](https://user-images.githubusercontent.com/79761518/109398467-23f82c00-790b-11eb-8a7f-0f1c443bc939.png)
Note: This is what happens when I try to shut it down or restart it or go to any of the files.

**Comment by Trojaner** [comment]
This issue has nothing to do with Unturned

**Comment by odstfive** [comment]
> This issue has nothing to do with Unturned

I was told to make a new separate issue report by nelson, ill just close it then, I'm just weirded out because this only happened with the new update...
