### ISSUE TITLE
ui scale does not work

### ISSUE THREAD

**Issue by buttsmasher69** [SmartlyDressedGames/Unturned-3.x-Community#2445]
ui scale does not work, and it is not epic

**Comment by SDGNelson** [comment]
Seems to be a troll account and issue.

**Comment by buttsmasher69** [comment]
isnt a troll account, it is named after my steam account lol but it actually doesnt work for me

https://user-images.githubusercontent.com/79774411/109636979-34cabc80-7b1a-11eb-8d01-244dec5f5ca8.mp4

**Comment by 01-Feli** [comment]
@buttsmasher69 did you press enter to apply the ui scale?

**Comment by educatalan02** [comment]
Click on Back and there you go.
