### ISSUE TITLE
Invisible character names

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2446]
Had a player on the server today with a blank character name. It was intentional as he left after being warned and came back with a character name of, "visivle name" (visible name).
![20210228152129_1](https://user-images.githubusercontent.com/53093137/109433223-45c1e380-79dd-11eb-81aa-b52954290a02.jpg)

SteamID provided upon request.

**Comment by SDGNelson** [comment]
The official answer is to use the "Filter" command which restricts names to a subset of English characters, or to use a custom plugin. Maybe a customizable "valid letters" list should be added in the future.
