### ISSUE TITLE
Add replaces for tellLean.

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#2448]
Add a replace for tellLean that rn only can be trigger by the event TriggerSend.

**Comment by SDGNelson** [comment]
If I understand correctly you need an event for when the lean changes between left/right/none?

**Comment by 01-Feli** [comment]
Yes, It is used for that thing

**Comment by Senior-S** [comment]
> 
> 
> If I understand correctly you need an event for when the lean changes between left/right/none?

Yes

**Comment by SDGNelson** [comment]
Okay, will add for the next update.

**Comment by SDGNelson** [comment]
Added `PlayerAnimator.OnLeanChanged_Global`
