### ISSUE TITLE
BattlEye false ban.

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#2450]
My steam profile: https://steamcommunity.com/id/MaxPawer
My steam id: 76561198815821887

Hello, 10 days ago i was banned by BattlEye and this are a false positive, i already sent a mail to the support but i don't have any response so maybe here nelson or other persons can help me.
I'm a plugin developer and i test a lot of plugnis in unturned, the last plugin that i tested before the ban was this: 
[plugin.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6065435/plugin.zip)
This version don't work correctly and if you test it will crash your unturned and i think battleye detected this like a false cheat.
Steps to reproduce the crash:
- Spawn a vehicle.
- Enter in the vehicle.
- Lock and unlock the vehicle.
- Don't get down of the vehicle and wait 10 seconds, the vehicle will be clear and your unturned will crash.

I did it 2 times because when i tested it i though that the crash was a problem from my pc and not from the plugin becasue my pc is not the best and sometimes it crash when i'm playing any game, i really want to get a response and a unban because i use my account to test all of my plugin and create a new account only for test my plugins are not in my plans.

If you need more information just tell me.

**Comment by Trojaner** [comment]
Of course I don't know if he is really innocent, but I can confirm that he is a known plugin developer and maybe its a similar case to @Game4Freak's

**Comment by nanashi88** [comment]
I think he has used Unturned cheats before! I won't be surprised if tried that again.

**Comment by Senior-S** [comment]
> 
> 
> I think he has used Unturned cheats before! I won't be surprised if tried that again.

What is your reason to say that? I never used any cheat for unturned and i don't will conden my account of 2500+ hours only for cheating, how i sayed, i just do plugins for unturned and i tested a plugin that i think can have a reason to be detected like a false cheat.

**Comment by SDGNelson** [comment]
Considering Game4Freak's case in the past and Trojaner's comment I will open a BattlEye ticket about this.

**Comment by SDGNelson** [comment]
It sounds like they have lifted it giving you the benefit of the doubt. To be on the safe side make sure you are only modifying the dedicated server, not client files.
