### ISSUE TITLE
Battleye unofficial moduls not supported

### ISSUE THREAD

**Issue by Alex998878** [SmartlyDressedGames/Unturned-3.x-Community#2451]
While im playing an server in Unturned in a 30 or 2 minutes im being kicked for reason: Battleye unofficial moduls not supported
Also when the server has battle eye required this happens.

**Comment by educatalan02** [comment]
The reason is because you are using a module in your client.

**Comment by Alex998878** [comment]
So how can i fix it?

**Comment by Trojaner** [comment]
Delete your modules folder

**Comment by nanashi88** [comment]
also some cheats cause this issue.
so if you are trying to use cheats you better chill before receiving hit by Battleye Hammer!

**Comment by SDGNelson** [comment]
To expand on the other answers, the most common reason being if you installed Rocket on the client.
