### ISSUE TITLE
It closes every time i enter (32 bits)

### ISSUE THREAD

**Issue by mohamed44j5** [SmartlyDressedGames/Unturned-3.x-Community#2452]
When i open Unturned it opens normally and it starts loading, when its loading characters it crashes.Im in 32 bits computer

**Comment by SDGNelson** [comment]
Sorry for the trouble. If you can email me these files I will take a look:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file to your email
5. Return to the Unturned folder
6. Open the Unity AppData folder
7. Attach the Player.log file to your email

**Comment by mohamed44j5** [comment]
Here it is:

**Comment by SDGNelson** [comment]
It looks like you emailed them to GitHub. Could you email them to me at nelson@smartlydressedgames.com please?
