### ISSUE TITLE
Unturned Map Editor Bug

### ISSUE THREAD

**Issue by CharonStix** [SmartlyDressedGames/Unturned-3.x-Community#2453]
I can't really send an image for this.

Hello, the bug is quite simple, when i got an object (for exemple, a road line) and i want it to make it rotate at a perfect angle, i use the moving globe (the tricolor one) and i use ctrl+mouse for it to move with steps to rotate more precisely.
But, it's not working for me, when i use only mouse to move, it work to rotate, but when i use CTRL+mouse, it just stop, and doesn't want me to rotate it.
The bug happen in a map in particular, it work fine for the others, i tried duplicate the map to another file, but the same bug is here.

Can you please help ?
Thanks.

**Comment by SDGNelson** [comment]
Since the snapping interval is saved per-map perhaps it is a very small number? In the bottom left of the editor they are 1m and 15 degrees by default.
Perhaps your snapping key was rebound in the controls settings?

**Comment by CharonStix** [comment]
AH, i'm so dumb ... you are right, it is written at the bottom left, it was on 0 and 0, how can i hadn't seen that ?
Thanks you, and really sorry for making you loosing your time. It is entirely my fault.

PS : You are making a good job on that game and 4.0 too, good job and thank you for all the memories i got with this game in 5 years, have a great day ! 

Really, really sorry for my dumb mistake.

**Comment by SDGNelson** [comment]
No worries, glad to hear it is resolved!
