### ISSUE TITLE
Changing barricade ownership of signs still allows the original owner to change the sign

### ISSUE THREAD

**Issue by Paradox304** [SmartlyDressedGames/Unturned-3.x-Community#2454]
I am using BarricadeManager.changeOwnerAndGroup to set the owner and group to 0 for signs. I can still access and change the sign after the code has run.
![unknown](https://user-images.githubusercontent.com/28902525/109997321-e7289c80-7d31-11eb-9231-d72d67581fd5.png)
The sign text has been changed, but I can still access and change the sign as shown in the picture. Here's the snippet of code that is there.

            Logger.Log("Changing the owner and group of barricade to 0");
            BarricadeManager.changeOwnerAndGroup(transform, 0, 0);
            Logger.Log(sign.owner.ToString());

HexxisSigns >> Changing the owner and group of barricade to 0
HexxisSigns >> 76561198367660843

It still shows me as the owner after changing the owner of the barricade.

**Comment by DiFFoZ** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/701 (similar).

You need manually built a new state and sent it to clients

**Comment by Pustalorc** [comment]
Yeah, surprised that it doesn't just use a centralized/global ownership for it all and has the ownership split into 3 classes: `BarricadeData`, `Interactable2` and specific types that inherit `Interactable`.

**Comment by SDGNelson** [comment]
Unfortunately yes, as DiFFoZ and Pustalorc pointed out fully changing the owner is messy. Very old code has the savedata and network state tightly intertwined, and is something I intend to gradually unravel e.g. netcode rewrites working on separating the network state out. Before salvaging was added only a few items had ownership info, so the change owner method updates the newer salvaging and health owner (BarricadeData and Interactable2), but not the case-by-case packed owner.
