### ISSUE TITLE
Vehicle based projectile weapon Client-Server Sync issue

### ISSUE THREAD

**Issue by ZoliWorks** [SmartlyDressedGames/Unturned-3.x-Community#2455]
Hello, 

Since you are actively working on networking, I thought now would be a good idea to bring this issue up:
As the title states, the topic of this discussion will be the sync issue between vehicles on clients and server.

As per my understanding, vehicles are made out of 2 gameobjects: namely Vehicle and Clip, where Clip is what the server uses to determine collision and certain aspects of the vehicle while there isn't a player inside. Once a player enters the driver seat, the Vehicle prefab's data is used, this is why certain aspects of advanced vehicle features designed by modders work flawlessly on single-player but require extra efforts and workarounds to make them functional in multiplayer, however, that is a topic for another time. This time, I'd like to talk about Projectile based weapons being fired from vehicle turrets.

Due to the way vehicles are synced between clients and server, movements and transitions appear smooth on the client generating the movements, while the same movements appear jittery and out of sync on servers and for every other client. This wouldn't be much of an issue on it's own, if it wasn't for projectile based weapons. Hitscan (bullet) based weapons will always hit the same spot on server as they hit on the client that used the weapon, regardless of where the vehicle's turret Aim gameobject is pointing at on the server. Projectile based weapons on the other hand seem to generate 2 instances of the projectile, one clientside from the client's perspective of the vehicle and one server side from the server's perspective of the vehicle. Due to the sync issues, the client inside the vehicle is aiming at point A but the same vehicle on the server and for every other client is aiming at point B. This wouldn't be an issue if the projectile based weapon would detect hits the same way the hitscan weapons does: the hit occurs according to what the shot hit on the shooter's side, not according to what the shot hit on server side. When the user is using a projectile based weapon on foot, this desync no longer applies.

To illustrate what I meant with the previous wall of text, here's a video demonstration of shooting a projectile based weapon as the pilot of an aircraft and later shooting it while on foot.

https://user-images.githubusercontent.com/51713401/110001692-4d56f480-7d1d-11eb-83f6-b11fce4bb1e1.mp4

I Hope something can be done regarding this issue, as server-client sync issues are a major setback for modders working with vehicle mounted projectile based weapons. I could easily replace the missile pods with hitscan based weapons and maybe even create a custom smoke trail for them, however that takes away a lot of freedom of customization it in comparison to projectile weapons, such as custom projectile models, custom projectile origins, multiple separate projectiles with each shot or offsetting projectiles from the Aim gameobject for various reasons.

P.S. I'm using a custom projectile setup with scripts, but I've tested this previously with a vanilla projectile setup (tank cannon with more ballistic force) and the result is the same.

Cheers,
Zoli

**Comment by SDGNelson** [comment]
Awesome helicopter!

If I understand correctly you are the driver of the vehicle in this case? Currently projectile weapons are not supported as driver (#2398). One good alternative for the meantime might be to give the driver a hitscan gun, and the gunner seat a missile launcher.

Both improving the projectile syncing and adding support for driver projectiles are on my wishlist for after the netcode rewrites, but no ETA yet.

**Comment by ZoliWorks** [comment]
Appreciate it.

I would like to add that what you see on the video is a helicopter with regular turret configuration, as in, the player perspective aka the projectile origin point is moved to the **Aim** gameobject. After realizing this, I added **Turret_0_Ignore_Aim_Camera** to the pilot's turret, as this would force the server to spawn the projectile and sync it as if it were fired **on foot**. Result? Projectiles are in perfect sync both client and server side. We can consider the issue partially resolved i suppose? lol

I hope this workaround-fix will prove useful for other user encountering this same issue.

https://user-images.githubusercontent.com/51713401/110016891-3bca1880-7d2e-11eb-9d47-ed39b1da7b37.mp4

P.S. What can be seen in the video is still a work in progress version which uses the flight setup of an AH-6 Little Bird, that's why it's soo fast and agile.

**Comment by SDGNelson** [comment]
Glad that you found an acceptable workaround. I think that should be ok for planes and helicopters, whereas tank turrets need to be able to turn.
