### ISSUE TITLE
[DevKit Issue] Effect in viewport.

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#2456]
![image](https://user-images.githubusercontent.com/65422793/110103443-04537e80-7db7-11eb-9cb6-2ec515e8ea25.png)
![image](https://user-images.githubusercontent.com/65422793/110103463-09183280-7db7-11eb-95d7-a06bafcbf39d.png)
How to fix?

**Comment by FANYPLAYRU** [comment]
![image](https://user-images.githubusercontent.com/65422793/110104519-4f21c600-7db8-11eb-9d4b-0d64efea5ea7.png)
Off this, and fix this

**Comment by SDGNelson** [comment]
Glad you found a workaround. At this point my plan is to merge all the devkit tools (e.g. landscape) into the original editor, and then delete the devkit code because it is a mess.
