### ISSUE TITLE
Plugins were broken by the latest update

### ISSUE THREAD

**Issue by kenonen** [SmartlyDressedGames/Unturned-3.x-Community#2460]
The uessentials plugin is not working after the last update. Nelson, please fix it as it was in the last update

**Comment by Trojaner** [comment]
I believe it is time to move to different plugins like OpenMod NewEssentials that have the same features but are still maintained

**Comment by SDGNelson** [comment]
I agree with Trojaner. There are a lot of known issues with the old version of uEssentials e.g. TPA'ing out of bounds.
