### ISSUE TITLE
Linux crashes exacerbted

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2461]
JustOneMoreBlock set the cycle time on the JPH servers to two hours some time ago as no solution to the crashes around the 2.5 hour mark was ever found. Now they're crashing just after 1.5 hours.

And, of course, plugins and plugin permissions were hosed with this update.

**Comment by SDGNelson** [comment]
It is bizarre that JPH is crashing so much... my Linux 24h server is fine, but obviously it is not an ideal test. (2022 goals?) 

Nothing in this update should aggravate issues. Is it still the same mono GC crash?

**Comment by TH3AL3X** [comment]
Idk for me is working fine, I didn't got a crash since 2018 using Ubuntu

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
