### ISSUE TITLE
WorkshopDownloadConfig.json Fails  - AppID Mismatch

### ISSUE THREAD

**Issue by Brittank88** [SmartlyDressedGames/Unturned-3.x-Community#2462]
For every single addon the server attempts to download:
`[AppID 1110390] Wrong AppID 304930 in workshop item details for <whatever the file ID is>`

Not sure why the server is checking to see if the AppID matches its own, and not that of the Unturned client...

[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6095120/workshop_log.txt)

**Comment by SDGNelson** [comment]
Sometimes it seems like Steam is missing the metadata to realize that it has permissions for Unturned. There was a similar issue about multiplayer authentication the other day #2449.

If you validate the server install perhaps it will find it?
https://developer.valvesoftware.com/wiki/SteamCMD#Validate

**Comment by Brittank88** [comment]
I'll check it out!

Also, is it any issue that I didn't install the server with SteamCMD? It was just already in my steam library. Not sure if that makes a difference but I thought I'd note it.

**Comment by SDGNelson** [comment]
Using it installed from the Steam library should be fine. I test with a Steam library copy of the dedicated server before each update. That is even weirder though because the Steam client knows about all public Steam apps. You are launching it from a script though right, not the "Launch" button in the library?

**Comment by Brittank88** [comment]
Ahhh I was indeed launching it from the Steam library. If you're not supposed to do this would be cool if there was something written somewhere to warn about that (and hey, if there was and I missed it I apologise!).

**Comment by SDGNelson** [comment]
I agree it should behave better when launched from the library. Been meaning to do something about that...

Here is the official setup tutorial (to make a script):
https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md#How-to-Launch-Server-on-Windows

Let me know if you run into the same problem.

**Comment by Brittank88** [comment]
Confirming that using the batch files in the install directory works flawlessly. All downloads are currently succeeding!

**Comment by SDGNelson** [comment]
Glad to have it resolved. Yesterday I changed the launch from library configuration to run the default script, but there is not much that can be done aside from that.
