### ISSUE TITLE
Bullet cells bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2463]
If you shoot in the third person, you see the bullets fall to the ground, but as soon as you get in the first person the bullets disappear, pd If you shoot in the first person looking at the ground you see the bullets fall to the most infinite...

[![Video](https://img.youtube.com/vi/hGz3tUvbTX4/0.jpg)](https://www.youtube.com/watch?v=hGz3tUvbTX4)

**Comment by SDGNelson** [comment]
Limitation of the viewmodel at the moment. It has always been like this. Something I intend to revamp eventually as part of pulling in the near clip plane.
