### ISSUE TITLE
Change "VAC Secure" to something more reasonable

### ISSUE THREAD

**Issue by archie426** [SmartlyDressedGames/Unturned-3.x-Community#2465]
Small issue but eh

Valve Anticheat isn't actually in place on Unturned as far as I'm concerned, I believe in this case it stands for the protection against cracked gold/skins? Either way, it should probably be changed to something less misleading for server owners

**Comment by SDGNelson** [comment]
VAC is enabled for Unturned. Protection against spoofing DLC ownership is handled by Steam authentication tickets, not VAC.

**Comment by TH3AL3X** [comment]
> Small issue but eh
> 
> Valve Anticheat isn't actually in place on Unturned as far as I'm concerned, I believe in this case it stands for the protection against cracked gold/skins? Either way, it should probably be changed to something less misleading for server owners

uh? we have BottlEye too
