### ISSUE TITLE
Zombie Draw Distance makes Fighter jet and other modded strafing vehicles useless.

### ISSUE THREAD

**Issue by Toximisity** [SmartlyDressedGames/Unturned-3.x-Community#2466]
So, as it says in the title, im asking if there is a way to get a setting added to increase zombie draw distance, using high tiered planes for strafe runs is basically a kamikaze mission, because unless the area is complete devoid of hills and trees, you WILL die, it's not an if. When you go in for the run, the zombies don't spawn until your front end is basically kissing the pavement, and when you do pull it off, you can't pull up quick enough 80% of the time. This makes these vehicles basically useless. So having an increase to zombie draw distance, as well as bullet draw distance (So that the bullets don't disappear in the void since they seem to have the same view distance, if you aren't in the same range as the zombies they don't take effect) would allow a usage for these vehicles. I hate getting better at one thing, just to find out, that it was pointless to use the vehicle for anything other than transport.

**Comment by SDGNelson** [comment]
Currently the client loads one "zombie area" at a time. Explosive weapons should deal damage regardless of whether the client has the area loaded. Increasing the load distance and removing the zombie areas ought to be plausible once the netcode rewrites this year are finished, but no ETA.
