### ISSUE TITLE
[FEATURE_REQUEST] Animal Attack and Bullet/Projectile Modhooks

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2468]
Hello! I'd like to ask if you could add in hooks to detect an animal attack as well as for the generation of a bullet/projectile. I want to create a script that would allow for animals to attack at range with projectiles, and thought the most ideal way to do it would be to set the range to something large, 30m or so, and the damage to 0, then have it generate a projectile aimed at the player on attack. This would allow me much more flexibility in my Fallout content pack for getting animals such as Bloatflies and also adding in a "Raider" or "Supermutant" animal that actually wields a weapon. If you are not able to do this, I would really appreciate any ideas you may have to achieve this same effect.

**Comment by SDGNelson** [comment]
I agree that it would be interesting to have projectile enemies to fight. Right now even if there were attack Unity Events for that it would have no way to target the player yet. I can definitely see projectile enemies being added, and in particular bringing over the AI drone concept from 4, but there are a variety of other tasks that need to be completed first e.g. animal pathing.

**Comment by SDGNelson** [comment]
Fair enough. Since it sounds like you are really determined then you could do it this way in the meantime:
1. Enable "Should_Play_Anims_On_Dedicated_Server true" in the animal asset
2. Spawn projectile using EffectSpawner triggered by the Attack animation
Spyjack did something along those lines for Tales of Terror IIRC.
