### ISSUE TITLE
Server crash - no idea why

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#247]
This is a little old, so I'm sorry if this was already fixed. However, here it is.

[2018-03-11_172606.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/1883729/2018-03-11_172606.zip)

**Comment by N1GHTPATROL** [comment]
Are you trying to launch multiple servers at the same time?

**Comment by RainOfPain125** [comment]
Not sure what happened, as it was a month ago. But I'm almost certain I wasn't *launching* servers, they were all already open and it simply crashed

**Comment by N1GHTPATROL** [comment]
If this is a month old, I'm not sure this is the best place for your issues.

**Comment by RainOfPain125** [comment]
k then
