### ISSUE TITLE
Server override stance inputs

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2470]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2432#issuecomment-795877147

**Comment by PandahutMiku** [comment]
Any chance this will be added before the netcode changes go live this Friday? It would be helpful to know

**Comment by SDGNelson** [comment]
Sorry, but not in this next update. I have some networked input improvements in mind and this would make sense to do as part of that update.
