### ISSUE TITLE
Legacy Decals question

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2472]
Is there any way to create a decal using Small, Medium etc. tags, not auto-generated Decal type? It has it's own advantages, I want decal like this.

**Comment by SDGNelson** [comment]
The "Type" needs to be set to "Decal".

**Comment by aladairmaxwell** [comment]
That's why I asked about legacy way to create decals, like vanilla ones.

**Comment by SDGNelson** [comment]
How come? They were a hassle to manually set up.

**Comment by aladairmaxwell** [comment]
Because I guess legacy decals were made using mesh and material. I want to experiment with different shaders and emission, which doesn't work for auto-generated decals. 
Maybe it's a real disaster, but I still wish to create some.

**Comment by SDGNelson** [comment]
They do not support different shaders or meshes sorry. Only cubes with diffuse shading. If / when support is added for those in the future it will be added to the auto-generated decals.
