### ISSUE TITLE
Ability to send UI to the client.

### ISSUE THREAD

**Issue by NoSharp** [SmartlyDressedGames/Unturned-3.x-Community#2473]
This would be a cool feature, Atleast creating an RPC message that would be able to receive a string of text and convert it into UI (Take a look at Rust CUI if you wanted an example). Doesn't need to be fancy it would just allow many people the ability to create UI's without having to use Unity all of the time and have more flexibility in doing so.

**Comment by Trojaner** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/158
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2059#issuecomment-719936507
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2059#issuecomment-719969183

**Comment by NoSharp** [comment]
I'm aware of that but those issues are months old, plus there is no active issue for this. So, it's worth a shot :)

**Comment by SDGNelson** [comment]
There are two prerequisites:
1. Netcode rewrite (active WIP)
2. Support for UIElements to stabilize what UI abstractions are needed going forward

Then a new feature for plugins to create UI primitives server-side will be added, and the client will use the appropriate IMGUI / uGUI / UIElements implementation.
