### ISSUE TITLE
Weapons Use Player Damage functions poorly

### ISSUE THREAD

**Issue by embermctillhawk** [SmartlyDressedGames/Unturned-3.x-Community#2477]
On the surface level it works, weapons do their listed player damage.
However, no Armor Multiplier options work. Neither of the Zombie Armor Multipliers work, and I tested the Player Armor Multiplier to see if the option made zombies use that instead, and that had no effect.

Weapons Use Player Damage presents an interesting tilt to the game balance, but, makes zombies very tanky, with no recourse, unless one makes ammunition significantly more available, which presents its own balance issues.

**Comment by SDGNelson** [comment]
This is how it is supposed to work - making zombies more tanky. Interesting point about the global multipliers though.

**Comment by embermctillhawk** [comment]
Yeah, that's what I mean. The option itself works, but it breaks the multipliers.

**Comment by embermctillhawk** [comment]
The fix was in 3.21.27.0, only got around to testing in 3.21.28.0, the multipliers work now.
