### ISSUE TITLE
RPC Rewrite on Preview Branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2479]
Hoping to do an initial release on the 26th (next week, not this week). The most noticeable improvement is an increase in voice chat quality. Feel free to ask any questions here. I am still working on converting `SteamChannel.send` to `MethodHandle.Invoke`

These are the API changes relevant to plugins:

- `SteamChannel.closeWrite` and related methods are deprecated stubs. These were manually packed, so prone to breakage between versions anyway if plugins were manually calling them. If your plugin WAS manually calling please explain here and maybe we can figure out an alternative.

- Methods which took a first `CSteamID senderId` parameter have been marked obsolete, and replaced by an overload which takes `in ClientInvocationContext context` or `in ServerInvocationContext context`. Where possible the old method calls the new one. These should not have been getting called directly by plugins, instead by the RPC system, but if your plugin WAS manually calling them please discuss here and we will find an alternative.

- `onTriggerSend` and `onTriggerReceive` are only invoked for RPCs going through the old `SteamChannel` system.

Dangers:

- `_NetMethods` classes are generated with read/write methods for RPCs. Would recommend caution patching or calling these because they are only public for net invoke, and ought to be moved into a separate assembly.

- `NetId` is the replacement for `SteamChannel.id`. Any class with RPCs is given a unique net id when spawned. Eventually some existing RPCs will be moved into other classes for async loading, in which case backwards compatibility with SteamChannel will break if the object does not exist yet, so updating from using `SteamChannel.send` may be necessary for future compatibility.

- `NetId` size may change. I suspect we can get away with 22-26 bits by recycling ids, and use another bit to indicate whether it is larger.

- `NetReflection` and the associated `Handle` classes are not finalized yet, and some are not all the static/instance variants are added yet, so ideally using maintained methods is preferable.

**Comment by SDGNelson** [comment]
The preview branch temporarily has tomorrow's changes on it.

Meanwhile there has been more progress on the RPC rewrites, and I will put those back up either tomorrow afternoon or Saturday.

**Comment by SDGNelson** [comment]
Two experimental changes on the latest preview version that may affect plugins, but should be backwards compatible (thanks Trojaner!):
- Steamworks.NET code moved into Steamworks.NET.dll from Assembly-CSharp-firstpass. The game binds OnResolveAssembly and will redirect Assembly-CSharp-firstpass references to the new assembly.
- NetTransport moved into SDG.NetTransport.dll from Assembly-CSharp. The game binds OnTypeResolve to redirect references, but this one I am less sure about and would be curious to see your server log if this fails.

Ideally all of Assembly-CSharp would be moved into an "assembly definition", but I am not aware of a way to redirect Unity's type loading (e.g. monobehaviour components) which would break all mods - no go.

More of the old RPC code has been converted and the new API is starting to stabilize a bit more. Here is an example from `PlayerClothing`:
```
[System.Obsolete]
public void askSwapPants(CSteamID steamID, byte page, byte x, byte y)
{
	ReceiveSwapPantsRequest(page, x, y);
}

private static readonly ServerInstanceMethod<byte, byte, byte> SendSwapPantsRequest = ServerInstanceMethod<byte, byte, byte>.Get(typeof(PlayerClothing), nameof(ReceiveSwapPantsRequest));
[SteamCall(ESteamCallValidation.ONLY_FROM_OWNER, ratelimitHz = 2, legacyName = nameof(askSwapPants))]
public void ReceiveSwapPantsRequest(byte page, byte x, byte y)
```

**Comment by rube200** [comment]
Is Rocket updated (on preview branch)?

**Comment by SDGNelson** [comment]
@rube200 yes, and the Rocket version on the main branch is the same as the Rocket version on the preview branch.

**Comment by PandahutMiku** [comment]
Any chance with or after this netcode rewrites, we would get server-side ballistics?

It would be really nice and stop a lot of the obvious rage hackers from shooting people through walls and such, although some higher ping players might see the netcode rewrites as a step back due to it.

I believe way back, it was mentioned you tried it out but it was too inconsistent or something, so you ended up not going with it.

**Comment by warren39** [comment]
Assembly-CSharp-firstpass.dll does not in /Unturned_Data/Managed anymore. But the /Extras/Rocket.Unturned/Rocket.Unturned.dll needs this dll reference:

![image](https://user-images.githubusercontent.com/64722485/111998492-03607200-8b57-11eb-8f51-5f8a94b7adc2.png)

![image](https://user-images.githubusercontent.com/64722485/111999251-c5178280-8b57-11eb-8c58-e2164635bff4.png)

So I cannot complie my plugin now. Did I miss something?

**Comment by DiFFoZ** [comment]
Instead of `Assembly-CSharp-firstpass` use `Steamworks.NET`

**Comment by warren39** [comment]
Oh thanks @DiFFoZ

**Comment by SDGNelson** [comment]
These rewrites will probably be pushed back to April 2nd because the WIP changes to remove once per connection client->server RPCs are touching some fragile player code. Nervous 😟 

Thanks @DiFFoZ. I will update the Rocket source when this update goes out, but kept it this way in the meantime in order to test that the game's redirect worked properly.

@PandahutMiku doing all of the hit detection on the server like Counter Strike would be great, but is a big challenge requiring the ability to rewind time and perfectly sync everything between server and client. Even Fortnite does client hit detection with server validation (this is what Unturned does). In good news however: after this batch of rewrites I intend to make the server sendrate configurable and significantly increase the defaults, which will allow the server validation to be tightened down.

**Comment by warren39** [comment]
@SDGNelson Some bugs on Preview Branch:

![a1](https://user-images.githubusercontent.com/64722485/112023511-4bd75a00-8b6e-11eb-9214-362740557032.png)

https://user-images.githubusercontent.com/64722485/112023610-5f82c080-8b6e-11eb-9183-3786669d9d06.mp4

[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6183744/Client_Prev.log)

**Comment by SDGNelson** [comment]
@warren39: thanks for the report, will fix. This is because of a small mistake getting the magazine change RPC handle. Before the next preview version I will add a warning to catch other cases like that.

**Comment by PandahutMiku** [comment]
> @PandahutMiku doing all of the hit detection on the server like Counter Strike would be great, but is a big challenge requiring the ability to rewind time and perfectly sync everything between server and client. Even Fortnite does client hit detection with server validation (this is what Unturned does). In good news however: after this batch of rewrites I intend to make the server sendrate configurable and significantly increase the defaults, which will allow the server validation to be tightened down.

Yea that is understandable, it's not easy thing, just thought it was worth mentioning.

I tested out the preview update a bit and plugins/etc seem to be mostly a-ok. Some harmony patches will definitely break due to the new methods. I haven't tested it out properly with more then one player though.

Is there a reason why the preview build's minor build version is .10? Usually it's .255 or something to make it very distinct from other versions, confused me for a bit, wasn't sure if I was running preview or not.

**Comment by SDGNelson** [comment]
@PandahutMiku Glad that your stuff is working mostly okay so far. As for the version: I was going back and forth between the branches and forgot to change the number before uploading. 🤦‍♂️

**Comment by SDGNelson** [comment]
The latest preview version has two changes that will break backwards compatibility for some plugins:

- "Once per player" RPCs have been removed. These were sent from the client after initialization finished, and the server would reply with details about clothing, inventory, skills, etc. This was necessary with the old system could not process RPCs until after `Start` which ran the next frame. Any plugins patching `askInventory`, `askClothing`, `askQuests`, etc will need updating because the old methods are obsolete and empty.
- Any logic which ran in `Start` has been moved to `InitializePlayer`. The ordering is the same, but I am nervous this probably broke some things - fixed quite a few that I came across so far. This means the player is fully initialized by the time any plugin code runs, and RPCs can immediately be called. Any plugins patching `Start` will need updating because those methods have been removed, but those methods were all private.

In other good news: all client->server RPCs have been converted in this version!

**Comment by aviadmini** [comment]
Hi, I'm migrating old code base to support new system and would really like some clarifications.

1)
Firstly, is it safe to keep `SteamChannel.send` calls to send RPCs to clients?
Example: when players skills are changed serverside, there's no specific method that sends `tellSkills` RPC. So I'm currently using this piece of code taken from `SendInitialPlayerState`:
```csharp
            PlayerSkills ps = player.skills;
            for (byte idx = 0; idx < ps.skills.Length; ++idx) {

                byte[] numArray = new byte[ps.skills[idx].Length];
                for (byte idx2 = 0; idx2 < numArray.Length; ++idx2) {
                    numArray[idx2] = ps.skills[idx][idx2].level;
                }

                ps.channel.send("tellSkills", player.GetSteamId(), ESteamPacket.UPDATE_RELIABLE_BUFFER, idx, numArray);

            }
```

This is the an example case of not having correct RPC to call - there's many more examples as such and manually adding serverside methods is probably not a good solution - some low level custom calls are a better alternative. I hope we can work out a better one.

2)
Is changing all calls with `ESteamCall.SERVER` (now obsolete) to direct calls to server methods a proper way of handling this?
Example: 
```csharp
player.channel.send(nameof(Player.askTeleport), ESteamCall.SERVER, ESteamPacket.UPDATE_RELIABLE_BUFFER,
                                position, rot);
```
change to 
`player.askTeleport(position, rot);`

3) A proper way to get player steam id or steam group?
Currently using `player.channel.owner.playerID.steamID` and such

4) There's cases where I patch methods that use `closeWrite`. I cancel the original call, instead I call `closeWrite` with custom values. Any low level alternative to that?

**Comment by SDGNelson** [comment]
@aviadmini thanks for updating.
1. That particular bit of code has not been converted to the new system yet, but when the update releases none of the vanilla code will use SteamChannel.send. For the foreseeable future SteamChannel.send will work for _most_ existing methods, but new features added in the coming years will not support SteamChannel, and existing features like barricade RPCs will be moved into per-class instance methods for a variety of reasons.
For that case I assume you are doing something like `ServerUnlockAllSkills`?

2. One of the `teleportToPlayer`, `teleportToLocation`, `teleportToRandomSpawnPoint`, `teleportToBed`, `adjustStanceOrTeleportIfStuck`, or worst case `teleportToLocationUnsafe` should be used instead.

3. That is how the vanilla game gets the steamid and groupid for now. There are helper methods in PlayerQuests for group affiliation. Ideally eventually steamid will be moved behind an abstraction but that is a long time away.

4. What are you patching? Not ideal and the packing of that data could change. In particular the movement state will be improved.

5. That is one of the many cases where the old SteamChannel method has been marked obsolete, but still calls the new one. In that case `ReceiveAirdropState`. Every old RPC method is or will be marked obsolete.

**Comment by aviadmini** [comment]
Thanks for quick response \(^_^)/

1. Yes I'm using existing methods where possible. I use `ServerUnlockAllSkills` when but that doesn't work when only one skill needs to be changed to a specific value on the serverside.
2. Thanks for specifying, I didn't know those existed 👍 . There's an alternative in case of this case, but the rest? Manually adding a method for each call community asks might be not an option imo .
3. Gotcha, I'm guessing SteamPlayer stuff isn't going away for now.
4. I was patching askBarricades/askVehicles/askStructures pre-update plus calls that change those elsewhere. For now I migrated that to cancelling original RPCs and calling modified RPCs instead (altho I'll need to update the code if savedata changes). There's other solutions but they have their own drawbacks.
5. I must have been looking at old assembly code. Seems correct now. Although `public static void airdrop(Vector3 point, ushort id, float speed)` still calls `tellAirdropState`. 

Would it be possible to make server-> client RPC delegates public (ClientStaticMethod stuff)? That's a selfish request that would reduce this kind of boilerplate:
![image](https://user-images.githubusercontent.com/5710176/112186654-07999780-8c0a-11eb-84fd-19d4d4c9b848.png)

**Comment by SDGNelson** [comment]
@aviadmini 
1. Okay, I will add a public method for setting the level of an individual skill.
2. There have been a lot of community requests addressed on the other thread so far. Inevitably anything remaining will be called via reflection or patching.
3. Unfortunately that class name is here to stay for the foreseeable future.
4. :/
5. Some methods are being called through the SteamChannel backwards compatibility at the moment on the preview branch to check that it works properly until they are all converted.
6. They will probably be made public once I am finished converting everything and the API is essentially finalized.

**Comment by SDGNelson** [comment]
Once again the preview branch temporarily has tomorrow's changes on it. After the update is determined to be stable I will upload the newest RPC rewrite version which has replaced quite a few more of the server->client invocations.

**Comment by rube200** [comment]
Did you pushed the correct version?
(`Assembly-CSharp-firstpass` is back and `Steamworks.NET` is gone)

**Comment by SDGNelson** [comment]
The newest version on the preview branch now is getting fairly close to ready. Most server->client invocations are converted, I just need to do a pass replacing all `ESteamCall.All` usage and then it should be "complete".

I can probably convert all of those on Monday. Then I will fix a regression in VOIP, add a bunch more sanity checks to hopefully catch basic mistakes, and host a public server for a few days playing to find new problems.

**Comment by aviadmini** [comment]
A few thoughts about latest preview:
- First and most important: making server->client API public asap would be really helpful. There's plenty of cases where there are no suitable manually added methods - and migrating those is quite pita without public access. Please consider making it public on next preview update.
- Method naming is inconsistent for `PlayerLife.serverSetXxx`, `PlayerLife.serverModifyXxx` and `PlayerSkills.ServerSetExperience` (lowercase and uppercase). I believe there should be some uniformity.

**Comment by SDGNelson** [comment]
@aviadmini 
1. The problem is I want to move them into a separate assembly, but first need to tidy up their dependencies because they cannot depend on Assembly-CSharp. If I make them public now it makes backwards compatibility after move harder.
2. Newer code is moreso following standard C# naming conventions, but older code cannot be changed without breaking plugin compatibility.

**Comment by aviadmini** [comment]
1. I understand, guess I'll just wait for final release then.
2. One way is to make old code obsolete and redirect to new methods, giving everyone time (many months) to migrate.

**Comment by SDGNelson** [comment]
@aviadmini 2. That is what I did when revising the RPC methods, and will continue doing with future improvements, but not a bulk renaming across the entire codebase.

**Comment by SDGNelson** [comment]
Happy news: all of the game RPCs have been upgraded on the preview branch! 🥳

Still a few things to do this evening and tomorrow, but from there it should be stable testing.

**Comment by aviadmini** [comment]
Thanks for the push. Could you give a brief explanation on the differences of `ClientStaticMethod` methods `Invoke` and `InvokeAndLoopback`?

**Comment by SDGNelson** [comment]
@aviadmini On the dedicated server `Invoke` only calls the method on remote clients, whereas `InvokeAndLoopback` calls the method on remote clients and then locally.

**Comment by SDGNelson** [comment]
In case anyone is interested in trying to break the game there is a public test server on the preview branch at: 54.214.10.254

Caught a bunch of stuff with the automated tests this morning. Only known issue on the preview branch at the moment is owner-only quest state gets sent to non-owner clients.

**Comment by PandahutMiku** [comment]
It looks like the rate limiting is too strict on first join. 

Right after I join, it complains about this:

```[2021-04-01 11:51:00] Connecting: PlayerID: 76561198138254281 Name: Miku Character: Miku
[2021-04-01 11:51:06] steamid:76561198138254281 SDG.Unturned.PlayerInput.ReceiveInputs: ignoring because limit exceeded (16 of 15)
[2021-04-01 11:51:06] Did not read to end of invocation SDG.Unturned.PlayerInput.ReceiveInputs from client steamid:76561198138254281 (8 of 90 bytes)
[2021-04-01 11:51:06] steamid:76561198138254281 SDG.Unturned.PlayerInput.ReceiveInputs: ignoring because limit exceeded (17 of 15)
[2021-04-01 11:51:06] Did not read to end of invocation SDG.Unturned.PlayerInput.ReceiveInputs from client steamid:76561198138254281 (8 of 90 bytes)
[2021-04-01 11:51:06] steamid:76561198138254281 SDG.Unturned.PlayerInput.ReceiveInputs: ignoring because limit exceeded (18 of 15)
[2021-04-01 11:51:06] Did not read to end of invocation SDG.Unturned.PlayerInput.ReceiveInputs from client steamid:76561198138254281 (8 of 90 bytes)
[2021-04-01 11:51:30] steamid:76561198138254281 SDG.Unturned.PlayerInput.ReceiveInputs: ignoring because limit exceeded (16 of 15)
[2021-04-01 11:51:30] Did not read to end of invocation SDG.Unturned.PlayerInput.ReceiveInputs from client steamid:76561198138254281 (8 of 90 bytes)```

**Comment by SDGNelson** [comment]
@PandahutMiku thankfully (albeit unfortunately) this is how it was prior to the rewrite as well. The client falls behind on input ticks when handling all of the initial state RPCs, and then overcorrects. So far while testing that has been the only warning logged 🙂 This extra verbose logging will all be disabled / stripped in the Friday release. I intend to improve the input netcode later this year.

**Comment by nanashi88** [comment]
Hi,
thank you for keeping enhancing the game, and for the support to plugins makers :)
I would like to ask the following question:
how to reset specific player skills to zero (based on this new changes)?
ofc there is `ServerSetSkillLevel(...)` . but is it ok to loop through all skills and use this method for each of it in one single tick?

**Comment by SDGNelson** [comment]
Thanks everyone for working with me to update! This will be releasing today in the 3.21.13.0 update.

@nanashi88 It should be okay to loop through all skills with ServerSetSkillLevel yes.

**Comment by aviadmini** [comment]
`EffectManager.askEffectClearByID` with CSteamID parameter isn't marked obsolete while `sendUIEffect` equivalent is

**Comment by SDGNelson** [comment]
@aviadmini thanks, will mark obsolete.
