### ISSUE TITLE
Currency numbers disappeared from NPC vendor window

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2480]
It was suppose to be something like this.
![image](https://user-images.githubusercontent.com/69295711/111301499-5a4fde00-8663-11eb-9157-f404d4782a4f.png)
Here are 1,2,5,10,20,50,100 numbers near money items. 

Now it's empty. What happened? I would note, that moving cursor on it don't display anything. 
![image](https://user-images.githubusercontent.com/69295711/111301692-8ff4c700-8663-11eb-9786-fc2b9a18fb7a.png)

**Comment by SDGNelson** [comment]
Off the top of my head I think it was something to do with the text contrast between the label and icon. Will see about adding back that information.

**Comment by SDGNelson** [comment]
Thanks for bringing this up! It looks like it was a bug - the labels were meant to be kept, but were getting vertically truncated. Fixed for the next update. Tooltips on images was removed during the Glazier refactor, but it would be nice to restore that when adding UIElements support.
