### ISSUE TITLE
Can I activate server authoritative movement somehow?

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#2482]
The boats that I use do not accelerate more than 15km and decelerate very fast, so if someone needs to move they can walk/run on top of the boat, or the one who handles the rudder can maintain a medium speed so that they can board or fire at other ships without being static, if the captain accelerates to maximum speed they can get on (f) to not clip trough the boat
I still do not know how strong the rubberband is when moving in this way but worse is nothing, the only thing I need is that the boat does not sink just by standing up or moving
Another alternative is a plugin that freeze the vehicle when the driver leaves but it is not very practical since I would like naval combat in motion ( I didnt test if the boat sinks when the driver or other person is inside )

https://www.youtube.com/watch?v=okrJ306uIzA

https://www.youtube.com/watch?v=y4nLUSE9Cow

https://www.youtube.com/watch?v=zYZ4GllyYOg

(https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2478)

**Comment by SDGNelson** [comment]
Server authoritative is the default for internet servers unless `misc.dont_enable_this` is enabled. It is also disabled for LAN servers. Either way walking on top of vehicles will not work well at the moment until I add support for relative movement sometime after the RPC rewrites.
