### ISSUE TITLE
Discord Rich Presence question

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2483]
Maps had option such as `Has_Discord_Rich_Presence` which was adding Discord integration I guess, and I remember when you view profile of DIscord user, you could find out which map they are playing. What happened? Why this feature was removed? Will it be revised again like Steam enhanced info such as multiplayer, singleplayer or editor?

**Comment by SDGNelson** [comment]
Discord support was disabled after an update which caused the API initialization to crash on PCs without Discord installed. IIRC the game-specific integration was in beta at that point, but now that it is presumably more stably released it might make sense to restore.
