### ISSUE TITLE
Hello! Can I add scripts to the UI when I use unity?

### ISSUE THREAD

**Issue by 2629180692** [SmartlyDressedGames/Unturned-3.x-Community#2484]
Hello! Can I add scripts to the UI when I use unity?

**Comment by SDGNelson** [comment]
Sorry, but the only scripts that can be added are ones that are included in the base game. I do have a plan to address this longer term but it will have to wait until after the netcode rewrites and the UIElements integration.

**Comment by 2629180692** [comment]
thanks
