### ISSUE TITLE
Server wont connect to steam

### ISSUE THREAD

**Issue by Alex998878** [SmartlyDressedGames/Unturned-3.x-Community#2485]
When my friend starts his server (he has port forward) it kicks him out for reason: Lost connection to host or steam network
Yesterday it was working but today it has a error.

**Comment by SDGNelson** [comment]
There might be a more detailed explanation in his Logs/Client.log file, or the server's Logs/Server_ (id) .log file. Usually it is some temporary interruption.

**Comment by Alex998878** [comment]
Let me try

**Comment by Alex998878** [comment]
It says:
[2021-03-17 20:51:59] Lost connection to Steam servers because k_EResultNoConnection




Type a message

**Comment by SDGNelson** [comment]
In that case it's probably temporary maintenance. Usually it happens on Tuesday afternoon.

**Comment by Alex998878** [comment]
@SDGNelson
![image](https://user-images.githubusercontent.com/79898290/111529296-e80df500-8759-11eb-930c-538b09055068.png)

**Comment by SDGNelson** [comment]
Hmm perhaps something (e.g. firewall) is blocking the server from connecting to Steam?

**Comment by Alex998878** [comment]
No firewall before 3 days it was working we fixed our rocket at that day and after that night the server had this error

**Comment by SDGNelson** [comment]
If you can zip up your steamcmd/logs folder and email it to me nelson@smartlydressedgames.com I will take a look. In particular the Steam connection log might have some explanation why it is failing.

**Comment by Alex998878** [comment]
It may take a time because im using phone rn and im not at my house i well send when im at my house

**Comment by Alex998878** [comment]
Okay you can close the issue i guess.

**Comment by SDGNelson** [comment]
I assume that means it is working again, but feel free to comment and I will re-open.
