### ISSUE TITLE
[FEATURE REQUEST] Clothing Priority

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2487]
I have been experimenting with how the pants and shirts load in within the game, and how full body textures do or do not take priority. My test showed that pants take priority over clothing and, in the scenario that both are a full body texture, only the pants will show up and mask over the shirt on the third person model, and in first person as only the arms are rendered, the arms texture shows up. I was wondering if it would be possible to add a line of text such as Clothing_Priority or whatever syntax would be preferred, and have it apply to shirts to render over pants so that things such as a lab coat could exist entirely as a shirt and have no need for the bottom half of an labcoat to be stuck onto a pants texture. This would make it so that wearing only one piece or mixing tops and bottoms together would look much nicer, and would only require for the shirt to take priority in the texture render

Please give me your thoughts on this as I was really hoping to be able to get this functional so things like a modular lab coat to cast over any pants can exist.

**Comment by Dumfoozler** [comment]
![image](https://user-images.githubusercontent.com/76188059/111517251-3f48a100-872b-11eb-807a-7ffccf3a3f80.png)
In this very fast test you can see that the default unturned texture is the shirt, and the pink color is the pants, where the transparency in the pink texture is where the shirt can show through. this makes things like overalls possible, but unfortunately makes it so that labcoats with a slight overhang all need an accompanying bottom and cant have any level of customizability. If the ability to allow shirts to have priority was to be added, it would be the best of both worlds ideally.

**Comment by SDGNelson** [comment]
I would like to rewrite the clothing system at some point, in particular to replace the hardcoded slots. Agreed this would be a useful improvement for then - overalls and full body suits have long been something I'd like to improve.

**Comment by Dumfoozler** [comment]
Until that point would implementing a 'quick fix' to allow the shirts to render overtop be possible? there are a lot of long clothing items in fallout and unfortunately its difficult to do a majority of them and allow them to be customizable like we had hoped for.

**Comment by SDGNelson** [comment]
Hesitant to do that because some mods are probably already relying on pants being layered after shirts unfortunately. :/

**Comment by Dumfoozler** [comment]
Understanding of that totally, but I think having it as a flag on the .dat of a shirt such as "Clothing_Priority" rather than applying by default would allow for the best of both worlds, as then mods that choose to use it can and mods that do not won't have to worry about it.

And alternately, if one wants pants not be overwritten at all, "Clothing_Priority" can apply to pants as well and when it's detected on both shirt and pants it just displays as it would if it were not present on either of the items.

**Comment by Dumfoozler** [comment]
Or, it can be a feature that applies to pants as a flag like "Show_Under_Shirt" so it will only underlay when it is intended to for the composition of the mod. The only detriment to this would be that overlay shirts would not overlay on vanilla pants or other mods that do not utilize the overlaying effect of pants by default.

**Comment by MoltonMontro** [comment]
> Hesitant to do that because some mods are probably already relying on pants being layered after shirts unfortunately. :/

I'm fairly certain that there are curated cosmetics that do this too. Dango Streetwear Pants immediately come to mind.

**Comment by Dumfoozler** [comment]
Yes, but I think having it be toggleable per-item would be a non-intrusive way to introduce it and also allow for an issue with current clothing, that being the split of things like coats, to have a simple fix for now.

**Comment by SDGNelson** [comment]
Adding a priority setting specifically for shirts vs pants now would be another hack to remain backwards compatible with when revamping clothing. Sorry to disappoint for the meantime.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
