### ISSUE TITLE
Unturned Linux server not showing any output or taking input

### ISSUE THREAD

**Issue by Gladuin** [SmartlyDressedGames/Unturned-3.x-Community#249]
Hello,

I managed to launch my server on Debian 9.3 by issuing the command ``./Unturned_Headless.x86 +secureserver/Test``. I expected that I got output just like I get on my Windows box. It also doesn't take any input like `shutdown` it only shows this:

`Set current directory to /home/USERNAME/servers/Unturned
Found path: /home/USERNAME/servers/Unturned/Unturned_Headless.x86
Mono path [0] = '/home/USERNAME/servers/Unturned/Unturned_Headless_Data/Managed'
Mono path [1] = '/home/USERNAME/servers/Unturned/Unturned_Headless_Data/Mono'
Mono config path = '/home/USERNAME/servers/Unturned/Unturned_Headless_Data/Managed'`

It does show the output I was expecting when I add the command `-logfile`

Am I missing an option?

Thanks for the help!

**Comment by Trojaner25** [comment]
This is normal. It is related to UnityEngine.

To have some sort of console, you should install RocketMod.
