### ISSUE TITLE
[Feature Request] Max Car Locks per player.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#2490]
Can you please implement a maximum amount of locked cars on the server side, please?
Same way you can limit the amount of players on a same group and all.

Thank you very much!

**Comment by educatalan02** [comment]
This could be made easily with plugins

**Comment by Lion4K** [comment]
> This could be made easily with plugins

Can, has been, but why rely on a plugin that needs to be updated and has the chance of the plugin owner no longer wanting to, that can not play well with other plugins, etc etc etc when it could be implemented natively?

**Comment by educatalan02** [comment]
Rely on a plugin because then you can simply set max vehicles based on permissions

**Comment by Lion4K** [comment]
> Rely on a plugin because then you can simply set max vehicles based on permissions

What plugin? The one I know Conflicts with more needed plugins.

**Comment by educatalan02** [comment]
I will publish one soon

**Comment by Lion4K** [comment]
> I will publish one soon

When you do please link me there.

Thanks !

**Comment by Lion4K** [comment]
> I will publish one soon

Have you published it?
