### ISSUE TITLE
How to remove "Out of Bounds"

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#2493]
https://user-images.githubusercontent.com/65422793/111948085-a5e50a80-8aef-11eb-945f-c9e368f34878.mp4

**Comment by SDGNelson** [comment]
Is it outside the map size border? In that case it cannot be disabled because the netcode will not properly handle it.

**Comment by FANYPLAYRU** [comment]
I can disable this with plugin?

**Comment by SDGNelson** [comment]
If it is outside the map size border then no, sorry.
