### ISSUE TITLE
[U3DS] How to fix closing(crash) server after bind IP

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#2496]
After I bind the IP address to the server, the server does not start. The console closes

The behavior does not change after deleting the RocketMod

**Comment by PandahutMiku** [comment]
Usually that happens after trying to bind an invalid IP (i.e one that
doesn't exist on any of your network adapters)

**Comment by FANYPLAYRU** [comment]
I take IP - (2ip.ru)

**Comment by FANYPLAYRU** [comment]
Otherwise, the server cannot be found from the Internet, the ports are open.

**Comment by SDGNelson** [comment]
Yes Miki is correct, thanks Miku. Manually setting the IP is rarely necessary, most likely if the server was not accessible from the internet the port forwarding was incorrect.
