### ISSUE TITLE
Any possibility add quests with a plugin?

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2497]
For example, when you do a quest with an NPC, you get a little message on the screen, I would like to know if it could be integrated into the rocketmod, to be able to show personalized messages and not use the UI with the effects

**Comment by SDGNelson** [comment]
The quest details are controlled by the asset, but a plugin can add quests with `sendAddQuest`.

**Comment by TH3AL3X** [comment]
> The quest details are controlled by the asset, but a plugin can add quests with `sendAddQuest`.

It would be a good idea, although you could also integrate a UI somewhere on the screen that the game brings up and you can put whatever you want as sendBrowserRequest

**Comment by SDGNelson** [comment]
Sorry, but that is unlikely to be added anytime soon.
