### ISSUE TITLE
Perspective Both Missing?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2499]
Hey Nelson, 

Did you do anything with the perspectives recently? 
For some reason when my test server starts to load it says failed to find perspective both when added to Commands.dat. I was just wondering if it was changed or if there's something to remedy the situation.

Thank you!

**Comment by SDGNelson** [comment]
No, nothing has changed with perspective recently.

**Comment by joeymisfit** [comment]
Ahh nevermind it's the case sensitivity, thank you for the fast response though!

**Comment by ZWMizuno** [comment]
I'm also getting the same error, and after trying both uppercase and lowercase, I found that somehow I added an extra spacebar after "both"😂
