### ISSUE TITLE
GroupManager - Corrupted (Groups.dat)

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#25]
`[Error] ArgumentOutOfRangeException: < 0
Parameter name: count - System.IO.FileStream.Read (System.Byte[] array, Int32 offset, Int32 count)
SDG.Unturned.River.readString ()
SDG.Unturned.GroupManager.load ()
SDG.Unturned.GroupManager.onLevelLoaded (Int32 level)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)`

**Comment by Trojaner25** [comment]
Apparently at some point wrong data gets written which corrupts the file.
A lot of people (at least 10) have reported this issue to me.

A workaround is to delete the Groups.dat file.

**Comment by xdlewisdx** [comment]
Happens a lot of the time if you force close (press X button) instead of using the shutdown command

**Comment by D-AIRY** [comment]
Still happens on linux servers. 
There is problem file: [Groups.dat](https://ds-servers.com/uploads/files/Groups.dat)
It seems file not fully writen
