### ISSUE TITLE
damagePlayerRequested not working when fall damage.

### ISSUE THREAD

**Issue by wsmajt** [SmartlyDressedGames/Unturned-3.x-Community#2503]
so i found out that the `DamageTool.damagePlayerRequested` is not working when player will took fall damage, and here is my question, is there any alternative pre-damage event where i could simply prevent player to took damage from falling?

**Comment by SDGNelson** [comment]
Only weapon damage goes through that event. In the meantime the options are the FallDamageOverride component, disabling fall damage on the object, or disabling fall damage in the server config. Did you have something more fine-grained in mind?

**Comment by wsmajt** [comment]
i want to check when player hits 0 hp and then prevent them from dying like in `DamageTool.damagePlayerRequested` where i can just `shouldAllow = false`. I think if there was something like `DamageTool.damagePlayerRequested` but for all the damage player get it would be nice.

**Comment by SDGNelson** [comment]
Ah. In that case there are multiple other damage causes not routed through the weapon damage event, e.g. starvation. Some plugins have found workarounds to prevent death, but for the meantime I cannot officially support it until I add a built-in "down but not out" state.
