### ISSUE TITLE
Sound sync

### ISSUE THREAD

**Issue by Buldozeris** [SmartlyDressedGames/Unturned-3.x-Community#2504]
Good to see some refreshments, but i think you need to sync new sounds to animation. Sound itself is good, but out of sync. Talking about running, it is too fast and sounds like u are a riding horse :D

**Comment by SDGNelson** [comment]
Unfortunately the sounds have never been synced with the animation. I would like to revisit the animations in the future. I am not sure if "animation events" were around when the current setup was first made back in 2013-2014. Would be nice if Unity had something more along the lines of Unreal's "anim notifies".
