### ISSUE TITLE
Barricade Sync/Save Problem

### ISSUE THREAD

**Issue by MaSSive16** [SmartlyDressedGames/Unturned-3.x-Community#2505]
Video outlining the problem : https://www.youtube.com/watch?v=jOVcNE6ey0A

![unknown](https://user-images.githubusercontent.com/81435548/112668932-1f725500-8e70-11eb-83be-73ccddb88067.png)

**Comment by SDGNelson** [comment]
Are you using any plugins which patch the barricade systems?

**Comment by MaSSive16** [comment]
No

**Comment by SDGNelson** [comment]
One of those is almost definitely causing the problem, so only the plugin devs can fix it, sorry. I do have a plan to rework how that data is managed to prevent it from getting out of sync when plugins do unexpected things, but no ETA yet.
