### ISSUE TITLE
add bulk selling to npcs

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2508]
it would be more convenient than spam clicking on them

**Comment by SDGNelson** [comment]
Yeah, I agree this would be a good improvement. In particular after seeing bulk-selling on RP servers. No ETA however.

**Comment by ddxn78096** [comment]
just add a thing that lets you hold ctrl when you click on the sell option of said item you are selling

**Comment by Kenzim** [comment]
nelson please do this i will gift 10 gold upgrades in unturned discord please lord

**Comment by Paradox304** [comment]
> nelson please do this i will gift 10 gold upgrades in unturned discord please lord

😆
