### ISSUE TITLE
steamclient.so path issues due to missing folder 

### ISSUE THREAD

**Issue by Adfee** [SmartlyDressedGames/Unturned-3.x-Community#2509]
When the Shell Script "ServerHelper.sh" tries to copy steamclient.so file when starting up the dedicated server on headless linux machine to this directory: `Unturned_Headless_Data/Plugins/x86_64/steamclient.so` it fails due to missing x86_64 folder inside Plugins. That causes the server to spit Error about missing steamclient.so file later on. I had to make this folder manually to get it working. I'm not sure that is intended, but it would be nice to include the directory by default in the dedicated server files that is directly downloaded through steamcmd or make it so "ServerHelper.sh" creates it, because cp command doesn't create parent directories.

**Comment by SDGNelson** [comment]
Thanks for the report. That folder must have stopped being created after some assemblies were rearranged. I will fix this for the next update.

**Comment by SDGNelson** [comment]
Should be fixed in the next preview branch version.
