### ISSUE TITLE
Unfortunate side effect with the "new" explosion damage falloff calculations

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#2510]
Hey Nelson,
Version 3.20.9.0 brought changes to the explosion damage falloff calculations to make them more intuitive however this had the unfortunate side effect of ruining some already existing unintentional mechanics that brought more enjoyment and diversity to unturned vehicle combat.

Since the calculations were based of a single point(center) in the old calculations, each point on a vehicles hitbox would deal different amounts of damage to the whole vehicle. This had the side effect of being a way to simulate armour on vehicles since its possible to move the center around.

The new system although great for larger vehicles and explosions is a lot more rigid. It is possible to achieve something somewhat resembling the old system but it isn't ideal since the best you can accomplish is dealing the entire explosion damage on some parts of the vehicle.

I am suggesting giving mod authors the ability to choose between the explosion damage falloff calculations as a line in the guns item.dat(`legacy_explosions true`).

What was possible with the old explosion calculations:
![Tiger 2weak](https://user-images.githubusercontent.com/70017362/112749488-cbc45080-8fc2-11eb-9b4e-7e09962755de.png)
![Black Prince Weak](https://user-images.githubusercontent.com/70017362/112749506-f44c4a80-8fc2-11eb-9a50-5b8822fe2f1a.png)

**Comment by SDGNelson** [comment]
Interesting use. Ideally it would make more sense to add proper armor / regional damage. How do you imagine setting it up if the game did have that?

**Comment by Gamingtoday093** [comment]
Well yes, ideally creating proper armour would be the best move however I was hoping for a possible `legacy_explosions true` or something similar to fix some current really important mod balance breaking issues.

Anyways, moving on to possible implementations of armor / regional damage brought to you by myself, Zoliworks and Pixel:

**My implementation**
I would use an additional hitbox to serve as a representation of the interior of the vehicle. When the vehicle is shoot, project a ray from the outer hitbox until it hits the interior hitbox. The distance measured can then be used as a multiplier on the damage for armour thickness. I also suggest having an extra setting in the vehicles.dat with something along the lines of `armor_multiplier 0.75` for different mod balances. I prefer my method because it allows for less hitboxes overall and can easily be implemented into all vehicles.

**Zoliworks**
> well based on the thickness of box colliders
Detect where the vehicle got hit, project a ray from the impact point with the length set in the dat of the gun, check if the Ray can reach the other side of the box collider
If it does, full damage, if it doesn't, no damage or partial damage based on settings
Or an armor value script
Assign a penetration value to the gun, then use the script to give each collider its armor value
Damage occurs if the hit colliders armor value is below the armor value of the gun

**Pixel**
Make multiple materials for each thickness and give each hitbox their corresponding thickness.
