### ISSUE TITLE
Object visibility condition does not affect collision

### ISSUE THREAD

**Issue by muertoof** [SmartlyDressedGames/Unturned-3.x-Community#2511]
Hey Nelson.

I know you are busy rewriting the network code right now. But I would like you to just pay attention to my request.

So, now we can set visibility conditions for map objects, this works fine, except for one but. Unfortunately, when the condition is triggered and the object becomes invisible, its collision does not disappear. This is very annoying and literally throws players back.

After doing a little investigation, I found out that this works correctly on the local server and the collision disappears along with the visibility of this object. But on the dedicated server, the collision remains and blocks the ability to go through the object.

It would be great if the condition of the object would also affect its collision. With this, a lot of interesting things could be done.

Thanks for attention :)

**Comment by SDGNelson** [comment]
This has definitely been a popular request. It requires per-player collision on the server however and I do not have an ETA for that. None of the built-in objects with conditional visibility have blocking collision.
