### ISSUE TITLE
Rocket builds on preview branch

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2512]
Working on preparing my plugins for the upcoming net code changes. I currently can't use any Rocket methods which use `CSteamID` as it has been moved to `Steamworks.NET.dll`. Would be nice if the Rocket build in the preview branch is updated for the game binaries on the preview branch as well.

**Comment by SDGNelson** [comment]
The reason I did not update it yet was to test that redirecting older plugins to the new assembly would work properly. Is there an exception when the server loads your plugin, or what seems to be the issue?

**Comment by rube200** [comment]
It makes projects to be impossible to compile.
@IAmSilK I suggest you to clone ldm and compile it yourself.

**Comment by IAmSilK** [comment]
There's a compile time error stating `Assembly-CSharp-firstpass.dll` must be referenced. Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/16708907/112776577-744fd000-9016-11eb-929e-19ba3e180d9f.png)

**Comment by Trojaner** [comment]
@SDGNelson this should be a compile time issue only, should still work at runtime

**Comment by SDGNelson** [comment]
Ah, okay. I will update the LDM dev branch and the Extras build in the next preview update.

**Comment by SDGNelson** [comment]
Updated for the next preview version.
