### ISSUE TITLE
Modded clothes doesn't works correctly .

### ISSUE THREAD

**Issue by Raptor-UA** [SmartlyDressedGames/Unturned-3.x-Community#2518]
In this mod work helmet and vest , but other clothes top and bottom do not work correctly . 
I was told that clothes do not work with all encodings . And now we are waiting for an update in which this will be fixed .
This photo shows this problem .
![Uploading  #IMG_20210327_153352.jpg…]()

**Comment by SDGNelson** [comment]
Only the mod creator can fix the items.
