### ISSUE TITLE
Test branch

### ISSUE THREAD

**Issue by Buldozeris** [SmartlyDressedGames/Unturned-3.x-Community#2519]
I see preview branch is being updated almost everyday. And kinda makes no sense to test everything out properly before release. Tested yesturday, everything was ok, now i see it was updated again, throwing errors, server not launching. I think it would be better to release final version of upcoming update and keep it for a week. Those last minute changes is like cat in the bag.

**Comment by SDGNelson** [comment]
It has not changed much this week. There were a few minor fixes for bugs found while testing, and the update yesterday was only to disable the extra error logging.
