### ISSUE TITLE
many arg in sendUIEffect

### ISSUE THREAD

**Issue by Trankvil** [SmartlyDressedGames/Unturned-3.x-Community#252]
i want many format arguments in sendUIEffect. arg0, arg1, arg2, arg3 - little for me

**Comment by Trojaner25** [comment]
You are doing something wrong if you need more.

**Comment by Trankvil** [comment]
What can I do wrong if there is no arg5 or parat object in the SendUIEffect?

**Comment by Trojaner25** [comment]
For example, instead of this:
`{0} said {1)`
do only
`{0}`

If it doesn't work because you use multiple `Text` objects, just split your effect...

**Comment by SDGNelson** [comment]
Trojaner is right - I doubt there would be reason for more than a couple parameters, but if there really is then more could be added. There is a 255 character limit on string RPC parameters.
