### ISSUE TITLE
Players unable to move / do anything after joining

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2520]
It looks like this is quest-related somehow, something to do with a specific quest being updated on join, but I could not replicate

```[2021-04-02 18:42:08] NullReferenceException: Object reference not set to an instance of an object
[2021-04-02 18:42:08] SDG.Unturned.NPCItemCondition.formatCondition (SDG.Unturned.Player player) (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerLifeUI.UpdateTrackedQuest () (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerLifeUI.OnTrackedQuestUpdated (SDG.Unturned.PlayerQuests quests) (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerLifeUI..ctor () (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerUI.Start () (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)

[2021-04-02 18:42:08] NullReferenceException: Object reference not set to an instance of an object
[2021-04-02 18:42:08] SDG.Unturned.PlayerUI.message (SDG.Unturned.EPlayerMessage message, System.String text, System.Single duration) (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerLifeUI.onSafetyUpdated (System.Boolean isSafe) (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerMovement.updateRegionAndBound () (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerMovement.simulate (System.UInt32 simulation, System.Int32 recov, System.Int32 input_x, System.Int32 input_y, System.Single look_x, System.Single look_y, System.Boolean inputJump, System.Boolean inputSprint, UnityEngine.Vector3 clientResultPosition, System.Single delta, System.Boolean clientEnteredTeleporter) (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
SDG.Unturned.PlayerInput.FixedUpdate () (at <9c0c7e0bcc244cbca676ee184ef3b376>:0)
```

There is a lot more other spamming errors after those two about null refs with ui classes.
Two Player's logs who are affected by it:

[message (11).txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6250542/message.11.txt)
[Client (9).log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6250543/Client.9.log)

**Comment by SDGNelson** [comment]
Thank you for the report! I will get these fixed in a patch ASAP depending whether other reports come in as well.

**Comment by Mumei-San** [comment]
> Thank you for the report! I will get these fixed in a patch ASAP depending whether other reports come in as well.

Got the same problem myself. 
1 day ago, went to complete the quest "Smartphone search", in the France map. I found the phone but it didnt allow me to actually pick it up, so it would become an eternal loop on "grab and do nothing". 
After this patch, I enter the server and all I'm able to interact with is the cursor itself, while the quest name shows up in the side and all I can do sit and do nothing.
![image](https://user-images.githubusercontent.com/81824573/113438153-e68e2f00-93df-11eb-9852-d8dd321d8062.png)
here's a print of it.

**Comment by SDGNelson** [comment]
The reason this happened was the item condition in the tracked quest depended on the quests UI translation file, but due to the player initialization order changes it was not loaded yet. I did of course test quests in multiplayer and logging in with tracked quests, but not that particular combination of first login with an item tracked quest unfortunately. Double-checked in the patch with the squeaky motor quest on Russia tracked and it should be fixed.

Since it is the only bug reported in the update so far 😃 waiting for the build and upload.

**Comment by TH3AL3X** [comment]
Oh shit here we go again

**Comment by Mumei-San** [comment]
> The reason this happened was the item condition in the tracked quest depended on the quests UI translation file, but due to the player initialization order changes it was not loaded yet. I did of course test quests in multiplayer and logging in with tracked quests, but not that particular combination of first login with an item tracked quest unfortunately. Double-checked in the patch with the squeaky motor quest on Russia tracked and it should be fixed.
> 
> Since it is the only bug reported in the update so far 😃 waiting for the build and upload.

That's the major bug I'm finding so far, but offline maps will go into a eternal loading screen (workshop ones at least).

**Comment by Mumei-San** [comment]
Also, only discovered it now. Nice update on the voice/audio quality.

**Comment by Buldozeris** [comment]
probably your plugins causing this problem

**Comment by SDGNelson** [comment]
The patch is up. Hopefully nothing else arises!

**Comment by Buldozeris** [comment]
I think updates should be on mondays, so we can play and chill during weekends :D

**Comment by Mumei-San** [comment]
> The patch is up. Hopefully nothing else arises!

Seems to be in order yes, thanks for helping. Do you happen to know if the quest bug is still ocurring tho?

**Comment by PandahutMiku** [comment]
Validated as fixed, thanks for the fix. Haven't seen any other issues being reported.
