### ISSUE TITLE
Chat and color variables and others..

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2523]
Description problem and Unturned chat in general with <color => or any other variable to change the font size, when I write for example with ChatManager.sendmessage for some reason the <color> characters or another variable count as word and this makes the text shorten, I put an example

Here we can see is taking <color=grey> </color> is taking the end part of color "<", there should be some way that variables are not counted as words to be able to put the longer text without problems
![image](https://user-images.githubusercontent.com/13141042/113444696-ae451b80-93f4-11eb-83ac-9e707ebea13c.png)

**Comment by SDGNelson** [comment]
The limits are determined by the master server buffer sizes, so changing them is outside of our control.
