### ISSUE TITLE
Server dont start

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2525]
[2021-04-02 22:29:15] IOException: Authentication failed because the remote party has closed the transport stream.
[2021-04-02 22:29:15] Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status) (at :0)
(wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus)
Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) (at :0)
Mono.Net.Security.AsyncProtocolRequest+d__24.MoveNext () (at :0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at :0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at :0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at :0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at :0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () (at :0)
Mono.Net.Security.AsyncProtocolRequest+d__23.MoveNext () (at :0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at :0)
Mono.Net.Security.MobileAuthenticatedStream+d__47.MoveNext () (at :0)
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at :0)
System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) (at :0)
System.Threading.Tasks.Task.Wait () (at :0)
Mono.Net.Security.MobileAuthenticatedStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) (at :0)
Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) (at :0)
System.Net.WebConnection.CreateStream (System.Net.HttpWebRequest request) (at :0)
Rethrow as WebException: Error: SecureChannelFailure (One or more errors occurred.)
System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) (at :0)
System.Net.HttpWebRequest.GetRequestStream () (at :0)
HyperLoader.PluginsManager.LoadLicensedPlugins () (at <07d4be03d3a14516a466d1fc61e831de>:0)
HyperLoader.PluginsManager.Awake () (at <07d4be03d3a14516a466d1fc61e831de>:0)
UnityEngine.GameObject:AddComponent()
HyperLoader.Main:initialize()
SDG.Framework.Modules.Module:initialize()
SDG.Framework.Modules.Module:set_isEnabled(Boolean)
SDG.Framework.Modules.ModuleHook:initializeModules()
SDG.Framework.Modules.ModuleHook:start()
SDG.Unturned.Setup:Awake()
[2021-04-02 22:29:15] Redirecting Assembly-CSharp-firstpass to Steamworks.NET for Rocket.Unturned, Version=4.9.3.5, Culture=neutral, PublicKeyToken=null

This is what first appear when is started the server stops suddenly when start to load plugins

**Comment by surv0013** [comment]
In plugin "HyperLoader" old libraries, contact the developer.

**Comment by ElRicki7u7** [comment]
I fixed that, but still dont start 
![Captura de pantalla 2021-04-02 224820](https://user-images.githubusercontent.com/75626024/113453336-10f2e300-9406-11eb-9ad9-a2da8fcbbce6.jpg)

**Comment by ElRicki7u7** [comment]
In the middle of loading plugins it stops
