### ISSUE TITLE
Unable to load into Any Worlds or Server After 3.21.13.0 Update 

### ISSUE THREAD

**Issue by Lego1upMushroom** [SmartlyDressedGames/Unturned-3.x-Community#2526]
After today's latest update i am unable to even load into anything past the title screen. every single thing freezes at the end of the loading screen. i have verified its not a client side issue by restarting my computer and re downloading the game.
I have also talked to others who are having the same issue as well.

**Comment by SDGNelson** [comment]
Has your game updated to 3.21.13.1 yet? You can force it to update by:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files
3. Click "Verify integrity of game files..."

**Comment by Lego1upMushroom** [comment]
sorry for the late response

at the time i made this post i was playing on 3.21.13.1 however since the 3.21.13.2 update issue has fixed itself

thanks for the help.

**Comment by SDGNelson** [comment]
Glad to hear it! Sorry for the trouble.
