### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by ElRicki** [SmartlyDressedGames/Unturned-3.x-Community#2527]
When the Unturned Update comes up, I update the server with steam, and the server didn't start, after so many hours, I saw that I have to update also RocketMod, I updated it, and nothing. The server CRASH exactly before the "Steam server is ready!"

**Comment by SDGNelson** [comment]
There are a variety of plugin startup exceptions in the log. It might be worth enabling a few at a time to see if the update is not backwards compatible with an out-of-date plugin.

**Comment by TH3AL3X** [comment]
Just remove Avi
Look "[2021-04-02 23:25:52] AviRockets.Gateway >> Gateway: initiating warp sequence" and then you have like 1 thousand errors

**Comment by ElRicki7u7** [comment]
That will stop the server crashing?

**Comment by TH3AL3X** [comment]
> That will stop the server crashing?

100% try

**Comment by ElRicki7u7** [comment]
> > That will stop the server crashing?
> 
> 100% try

Still not working ... the log is the same but no avi errors

**Comment by TH3AL3X** [comment]
> > > That will stop the server crashing?
> > 
> > 
> > 100% try
> 
> Still not working ... the log is the same but no avi errors

Anyways i see here an avi plugin is outdated
[2021-04-02 23:25:59] TypeLoadException: Could not load type of field 'avirockets.unturned.AviAdminTools.TeleportBedCommand:_currentBeds' (0) due to: Could not load file or assembly 'Assembly-CSharp-firstpass, Version=0.0.0.0.
Pd, try to remove plugin per plugin, cuz i don't see anything else

**Comment by TH3AL3X** [comment]
And bruh, remove that logs, is providing your discord webhook url lmfao

**Comment by ElRicki7u7** [comment]
Yes, two private channels... I will remove the log

**Comment by TH3AL3X** [comment]
Pd, Linux or Windows ? maybe i can help you in a call

**Comment by ElRicki7u7** [comment]
Windows
