### ISSUE TITLE
UnturnedPlayerEvents.OnPlayerDeath,UnturnedPlayerEvents.OnPlayerRevive BUG

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#2528]
UnturnedPlayerEvents.OnPlayerDeath,UnturnedPlayerEvents.OnPlayerRevive BUG
There was no response

**Comment by rube200** [comment]
These events are related to LDMnot unturned itself, please report under LDM repository

**Comment by hksz** [comment]
have already been solved

PlayerLife.RocketLegacyOnDeath
PlayerLife.OnSelectingRespawnPoint
