### ISSUE TITLE
Fix BattleEye

### ISSUE THREAD

**Issue by thereis** [SmartlyDressedGames/Unturned-3.x-Community#253]
Fix BattleEye to solve the Steam overlay problem.

**Comment by Trojaner25** [comment]
This is the third or forth issue regarding overlay...

**Comment by thereis** [comment]
There is no problem if many of this appears, it is a issue since march and there is no feedback or announcement from @SDGNelson

**Comment by baranmod** [comment]
Agree, I don't see a problem if someone reminds of this issue from time to time, as we see that either Nelson forgot about it or he chooses to ignore it and let it sink.. Its been 2 months if not more after all.

**Comment by thereis** [comment]
@SDGNelson Waiting for a answer.

**Comment by N1GHTPATROL** [comment]
I agree, I don't care if people are getting mad. It's a huge issue and Nelson has made no attempts since weeks ago to fix it. BattlEye team doesn't respond, and Nelson doesn't keep us informed. @thereis has a right to be upset, and I am too.

**Comment by PrimeOpalGamer** [comment]
Temporary fix: 
Start without BattlEye to be able to upload mods/download mods while in game

**Comment by PrimeOpalGamer** [comment]
Issue is Fixed officially! 3.23.9.1
