### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by iGodCrewKODAK** [SmartlyDressedGames/Unturned-3.x-Community#2531]
There's some sort of issue that's happening in my server, the UI doesnt seem to be affected, so when players shoot each other or at a buildable, the UI does nothing, and stays at 100%

**Comment by SDGNelson** [comment]
The player health stays at 100%, or the buildable health stays at 100%?

**Comment by iGodCrewKODAK** [comment]
Both, I'll try my best to find a video

**Comment by iGodCrewKODAK** [comment]
Here they are:
https://youtu.be/YgYsvg4DOFQ
https://youtu.be/EGRI05xsdRs

**Comment by SDGNelson** [comment]
Could you send me the client and/or server log files to nelson@smartlydressedgames.com please? Hopefully there may be a clue about what is causing the problem. The client log file is in Unturned/Logs/Client.log, and the server log file in U3DS/Logs/Server_ (name) .log.

**Comment by iGodCrewKODAK** [comment]
I just sent it to you

**Comment by SDGNelson** [comment]
600,000 lines of exceptions, yikes! Considering the huge number of errors I would suggest disabling a few plugins at a time and seeing if the problem stops, as well as checking for plugin updates if you have not already.

**Comment by iGodCrewKODAK** [comment]
Ahhhh!!! I could thank you even further, it helped, but I have one more issue, do you know how to fix it when zombies does not do damage to you?

**Comment by SDGNelson** [comment]
Glad you were able to sort it out. If disabling some plugins fixed the players, perhaps another plugin is causing problems with zombies? It may be worth further experimenting with disabling. It could also be a misconfiguration in the Config.json zombies section.
