### ISSUE TITLE
Walkie-Talkie Question

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2532]
Why there are no outcome voice from the player using walkie-talkie? It would be such a nice detail to hear the player's voice instead of silence if they use walkie-talkie. 

Will this thing be added in near future? Because the voice chat have changed and there are voice channels thing planned in Roadmap.

**Comment by SDGNelson** [comment]
Can you elaborate please? Are you saying there is a bug with the walkie talkie?

**Comment by aladairmaxwell** [comment]
No, this is not a bug. I just wanted to suggest when player talks in walkie-talkie, other players nearby can hear them.

**Comment by SDGNelson** [comment]
Ah - that is intentional for private walkie-talkie conversations, but maybe it should be a separate keybinding or something.
