### ISSUE TITLE
Empty ServerInvocationContext for plugin support

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2533]
If possible, it would be nice to be able to construct an empty `ServerInvocationContext` based on an instance of `ITransportConnection` for simulating game mechanics. Currently all the constructors are internal and for simplicity sake, I'm still using some deprecated methods which construct the `ServerInvocationContext` for me.

**Comment by SDGNelson** [comment]
What do you have in mind? i.e. what method are you trying to call, and why?

**Comment by IAmSilK** [comment]
One I had in mind when I made this issue was `BarricadeManager.ReceiveStorageRequest` (don't remember the exact name). I have a plugin where when people attempt to open a storage, a code lock pops up on their screen and they must enter a code to access it. I would like to be able to simulate them opening it normally, including calling the `onOpenStorageRequested`, doing distance checks, etc.

This is just one example, but I could likely make a list if necessary.

**Comment by SDGNelson** [comment]
Hmm I think ideally there would be an event for plugins to override the request handling in that case. Not to step on your toes but for what it's worth code locks are on the roadmap https://trello.com/c/ztdXjXPm/3-digital-and-combination-locks

**Comment by IAmSilK** [comment]
I've already made the plugin and its in use, but this is besides the point.

Plugins often like to simulate and trigger game mechanics. We must use reflection to create instances of `ServerInvocationContext` or use deprecated methods which do it for us at the moment.

**Comment by IAmSilK** [comment]
Closing as this has gone stale and official support is unlikely.
