### ISSUE TITLE
OnPlayerHealed Event

### ISSUE THREAD

**Issue by maxim563328** [SmartlyDressedGames/Unturned-3.x-Community#2535]
Good day, I want to know how I can handle the "OnPlayerHealed()" event or get information that someone heal the player (the player did not heal himself)
And I found this appeal but i don't know how to use this event ---> https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/897
![image](https://user-images.githubusercontent.com/56736526/113591800-8d7ffe80-965e-11eb-8587-526a7c27891e.png)

Thank you in advance and sorry for my English

**Comment by SDGNelson** [comment]
Sorry, I should have mentioned in my comment then. The events added were `UseableConsumeable.onPerformingAid` (pre) and `UseableConsumeable.onPerformedAid` (post).
