### ISSUE TITLE
Mods don't work well in server

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2536]
This error shows when server load the mods
![unknown](https://user-images.githubusercontent.com/75626024/113629046-1c444980-9666-11eb-8aad-4832e6f00eac.png)

And also some food mods doesnt work well, having no animation

**Comment by SDGNelson** [comment]
Up to the mod creator if they want to fix those.

**Comment by ElRicki7u7** [comment]
But, this only occurs on my server

**Comment by ElRicki7u7** [comment]
I tried on singleplayer and works

**Comment by ElRicki7u7** [comment]
Also this errors come up 
![image](https://user-images.githubusercontent.com/75626024/113767379-e616d080-971e-11eb-9c28-0f0854553681.png)

**Comment by ElRicki7u7** [comment]
@SDGNelson

**Comment by SDGNelson** [comment]
The mod would need to be fixed for multiplayer by the creator. This is not a game bug.
