### ISSUE TITLE
[CODE] Proposal to add Bulk action methods to BarricadeManager and StructureManager

### ISSUE THREAD

**Issue by Pustalorc** [SmartlyDressedGames/Unturned-3.x-Community#2539]
The following is a full code proposal which includes full modified code.
The reason to get bulk action methods (BulkDestroy and BulkDamage) added to BarricadeManager and StructureManager is so that plugins that do multiple checks whenever something is destroyed or damage can handle these changes better, specially when another plugin (or the game itself) want to do multiple destroy/damage in quick succession.
The other changes selected for this proposal are:
- #1943 (Suggestions to Barricade & Structure events) 
- #1737 (New event for BarricadeManager.destroyBarricade and StructureManager.destroyStructure)
- #1652 (Repair Event for Barricades and Structures)

# The changes
The following is a summary of all the changes to be done, including new classes, delegates, method changes, etc.
All of the changes are available as pure code at: [UnturnedBulkMethods.cs](https://github.com/Pustalorc/BaseClustering/blob/custom-unturned-patch/UnturnedBulkMethods.cs)

### New Classes
- `BarricadeLocation`
- `BarricadeDamage`
- `InternalBarricadeDamage`
- `StructureLocation`
- `StructureDestroy`
- `StructureDamage`
- `InternalStructureDamage`
- `BuildableDamageDetails`

### New Delegates
- `BarricadeDeployed(BarricadeData, BarricadeDrop)`
- `BarricadeTransformed(byte, byte, ushort, uint, Vector3, byte, byte, byte)`
- `BarricadeDestroying(BarricadeData, BarricadeDrop, ref bool)`
- `BarricadeDestroyed(BarricadeData, BarricadeDrop)`
- `BarricadeDamaged(BarricadeRegion, ushort, ushort, CSteamID, EDamageOrigin)`
- `BarricadeRepairing(BarricadeRegion, ushort, ref ushort, ref bool)`
- `BarricadeRepaired(BarricadeRegion, ushort, ushort)`
- `StructureDeployed(StructureData, StructureDrop)`
- `StructureTransformed(byte, byte, uint, Vector3, byte, byte, byte)`
- `StructureDestroying(StructureData, StructureDrop, ref bool)`
- `StructureDestroyed(StructureData, StructureDrop)`
- `StructureDamaged(StructureRegion, Vector3, ushort, ushort, CSteamID, EDamageOrigin)`
- `StructureRepairing(StructureRegion, ushort, ref ushort, ref bool)`
- `StructureRepaired(StructureRegion, ushort, ushort)`
- `BuildablesDestroyed(List<uint>)`

### New events
- `BarricadeTransformed OnBarricadeTransformed`
- `BarricadeDeployed OnBarricadeDeployed`
- `BarricadeDestroying OnBarricadeDestroying`
- `BarricadeDestroyed OnBarricadeDestroyed`
- `BuildablesDestroyed OnBulkBarricadesDestroyed`
- `BarricadeRepairing OnBarricadeRepairing`
- `BarricadeRepaired OnBarricadeRepaired`
- `BarricadeDamaged OnBarricadeDamaged`

### Method changes
- `InternalSetBarricadeTransform` -> After calling `SendTransformBarricade.InvokeAndLoopback` it should raise the `OnBarricadeTransformed` event as follows: `OnBarricadeTransformed?.Invoke(x, y, plant, instanceID, point, angle_x, angle_y, angle_z)`.
- `dropBarricadeIntoRegionInternal` -> Cloned to `DropBarricadeIntoRegionInternal` with a redirect from the original to this new method. `DropBarricadeIntoRegionInternal` should also rename `out uint instanceID` to `out uint instanceId`. An `Obsolete` attribute is to be added to `dropBarricadeIntoRegionInternal` as follows: `[Obsolete("Please use DropBarricadeIntoRegionInternal instead (Change: Correct naming)")]`. After running `region.barricades.Add(data)` the method should raise the `OnBarricadeDeployed` event as follows: `OnBarricadeDeployed?.Invoke(data, region.drops.Last())`.
- `destroyBarricade` -> Cloned to `DestroyBarricade` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `destroyBarricade` as follows: `[Obsolete("Please use DestroyBarricade instead (Change: Correct naming)")]`. Before running `region.barricades.Remove(data)` the method should raise the `OnBarricadeDestroying` event as follows: `OnBarricadeDestroying?.Invoke(data, drop, ref cancel)`, it should also check that if `cancel` is true, the rest of the method does not run. Additionally, after calling `SendTakeBarricade.InvokeAndLoopback` it should raise the `OnBarricadeDestroyed` event as follows: `OnBarricadeDestroyed?.Invoke(data, drop)`.
- `damage` -> Cloned to `Damage` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `damage` as follows: `[Obsolete("Please use Damage instead (Change: Correct naming)")]`. After calling `data.barricade.askDamage(num2)` it should raise the `OnBarricadeDamaged` event as follows: `OnBarricadeDamaged?.Invoke(region, index, num2, instigatorSteamID, damageOrigin)`.
- `repair` -> Cloned to `Repair` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `repair` as follows: `[Obsolete("Please use Repair instead (Change: Correct naming)")]`. Before calling `internalBarricade.askRepair(amount)` it should raise the `OnBarricadeRepairing` event as follows: `OnBarricadeRepairing?.Invoke(region, index, ref amount, ref flag)`. Additionally, after calling `internalBarricade.askRepair(amount)`, it should raise the `OnBarricadeRepaired` event as follows: `OnBarricadeRepaired?.Invoke(region, index, amount)`

### New methods
- `BulkDamageBarricades(IEnumerable<BarricadeDamage>)`
- `InternalBulkDamageBarricades(List<InternalBarricadeDamage>)`
- `InternalBulkSendHealthChanged(List<BarricadeLocation>)`
- `BulkDestroyBarricades(IEnumerable<Transform>)`
- `InternalBulkDestroyBarricades([NotNull] List<BarricadeLocation>)`

### Steamcall/netpak method hooks:
- `ReceiveBulkHealthChanged(in ClientInvocationContext)`
- `private static readonly ClientStaticMethod SendBulkHealthChanged = ClientStaticMethod.Get(ReceiveBulkHealthChanged);`
- `ReceiveTakeBulkBarricades(in ClientInvocationContext)`
- `private static readonly ClientStaticMethod SendTakeBulkBarricades = ClientStaticMethod.Get(ReceiveTakeBulkBarricades);`

### New events
- `StructureTransformed OnStructureTransformed`
- `StructureDeployed OnStructureDeployed`
- `StructureDestroying OnStructureDestroying`
- `StructureDestroyed OnStructureDestroyed`
- `BuildablesDestroyed OnBulkStructuresDestroyed`
- `StructureRepairing OnStructureRepairing`
- `StructureRepaired OnStructureRepaired`
- `StructureDamaged OnStructureDamaged`

### Method changes
- `InternalSetStructureTransform` -> After calling `SendTransformStructure.InvokeAndLoopback` it should raise the `OnStructureTransformed` event as follows: `OnStructureTransformed?.Invoke(x, y, instanceID, point, angle_x, angle_y, angle_z)`.
- `dropReplicatedStructure` -> Cloned to `DropReplicatedStructure` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `dropReplicatedStructure` as follows: `[Obsolete("Please use DropReplicatedStructure instead (Change: Correct naming)")]`. After calling `region.structures.Add(data)`, it should raise the `OnStructureDeployed` event as follows: `OnStructureDeployed?.Invoke(data, drop)`.
- `destroyStructure` -> Cloned to `DestroyStructure` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `destroyStructure` as follows: `[Obsolete("Please use DestroyStructure instead (Change: Correct naming)")]`. Before running `region.structures.Remove(data)` the method should raise the `OnStructureDestroyed` event as follows: `OnStructureDestroyed?.Invoke(data, drop, ref cancel)`, it should also check that if `cancel` is true, the rest of the method does not run. Additionally, after calling `SendTakeStructure.InvokeAndLoopback` it should raise the `OnStructureDestroyed` event as follows: `OnStructureDestroyed?.Invoke(data, drop)`.
- `damage` -> Cloned to `Damage` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `damage` as follows: `[Obsolete("Please use Damage instead (Change: Correct naming)")]`. After calling `data.structure.askDamage(num2)` it should raise the `OnStructureDamaged` event as follows: `OnStructureDamaged?.Invoke(region, index, num2, instigatorSteamID, damageOrigin)`.
- `repair` -> Cloned to `Repair` with a redirect from the original to this new method. An `Obsolete` attribute is to be added to `repair` as follows: `[Obsolete("Please use Repair instead (Change: Correct naming)")]`. Before calling `internalStructure.askRepair(amount)` it should raise the `OnStructureRepairing` event as follows: `OnStructureRepairing?.Invoke(region, index, ref amount, ref flag)`. Additionally, after calling `internalStructure.askRepair(amount)`, it should raise the `OnStructureRepaired` event as follows: `OnStructureRepaired?.Invoke(region, index, amount)`

### New methods
- `BulkDamageStructures(IEnumerable<StructureDamage>)`
- `InternalBulkDamageStructures(List<InternalStructureDamage>)`
- `InternalBulkSendHealthChanged(List<StructureLocation>)`
- `BulkDestroyStructures(IEnumerable<StructureDestroy>)`
- `InternalBulkDestroyStructures(List<StructureLocation>)`

### Steamcall/netpak method hooks:
- `ReceiveBulkHealthChanged(in ClientInvocationContext)`
- `private static readonly ClientStaticMethod SendBulkHealthChanged = ClientStaticMethod.Get(ReceiveBulkHealthChanged);`
- `ReceiveTakeBulkStructures(in ClientInvocationContext)`
- `private static readonly ClientStaticMethod SendTakeBulkStructures = ClientStaticMethod.Get(ReceiveTakeBulkStructures);`

**Comment by Pustalorc** [comment]
I wanted to add some performance tests using BaseClustering and both its abstraction feature (to build an abstracted collection for both Barricades and Structures), and its clustering feature (to build a collection that defines what a "base" is) to hammer the point of why this kind of feature can be useful.

The code used for this test is available on the [BaseClustering Repository, under the custom-unturned-patch branch](https://github.com/Pustalorc/BaseClustering/tree/custom-unturned-patch).
Whilst that repository doesn't include the `/damage` command nor the one-to-one code, the changes for getting those added are simple and boil down to copying and pasting the wreck command in order to create `/damage` but making it use `BulkDamageX` methods, and for one to one actions it is just changing the lines where `StructureManager` and `BarricadeManager` are referenced to `foreach (var build in collection) build.SafeDestroy();`.

# Performance Tests
All these tests were ran with no players online and on a laptop with an I7-9750H processor (though other background tasks were running, so results may slightly vary)
Do also note that damaging does result in destruction of any elements that drop to 0 health, which for BulkDamage results in BulkDestroy being called.
Finally, One to One destruction was slightly altered to allow logging after all barricades get destroyed and all structures get destroyed, but the way the plugin functions with abstracting, this split is not needed, nor does it change performance, as they will still call the same end points.

The quick summary of the results boils down to:
- If its just the base game, performance gain is **1.46x with one to one operations for pure destroy**, and **1.01x with bulk operations for damaging**. In short: Base game barely benefits from bulk operations.
- If there's a single plugin doing something as basic as creating abstractions for both Barricades and Structures, performance gain is **9.58x with bulk operations for pure destroy**, and **1.42x with bulk operations for damaging**. In short: Abstractions for buildables gain a considerable benefit from bulk operations.
- If there's multiple plugins doing multiple complicated things (in this test its abstractions + clustering), performance gain is **194.14x with bulk operations for pure destroy**, and **19.88x with bulk operations for damaging**. In short: Abstractions and clustering gain a massive benefit from bulk operations.

## Tests with Clustering and Buildable abstraction disabled
### One to One Destruction
![image](https://user-images.githubusercontent.com/17557714/115997263-d3d3d800-a5e2-11eb-8b35-d564b778a3d0.png)

### Bulk Destruction
![image](https://user-images.githubusercontent.com/17557714/115997580-db47b100-a5e3-11eb-926b-d52c9c2ff00e.png)

### One to One Damaging
![image](https://user-images.githubusercontent.com/17557714/115997383-31682480-a5e3-11eb-8022-c4772e21878a.png)

### Bulk Damaging
![image](https://user-images.githubusercontent.com/17557714/115997719-85273d80-a5e4-11eb-948b-4096d3b53f81.png)

## Tests with Clustering disabled
### One to One Destruction
![image](https://user-images.githubusercontent.com/17557714/115996667-82c2e480-a5e0-11eb-91d9-b4aac4773fa3.png)

### Bulk Destruction
![image](https://user-images.githubusercontent.com/17557714/115996915-7be8a180-a5e1-11eb-94c5-9e3bb1abf7dc.png)

### One to One Damaging
![image](https://user-images.githubusercontent.com/17557714/115996797-11cffc80-a5e1-11eb-99e0-36aef14277b6.png)

### Bulk Damaging
![image](https://user-images.githubusercontent.com/17557714/115997023-deda3880-a5e1-11eb-93af-96c1ded9dfa8.png)

## Tests with nothing disabled
### One to One Destruction
![image](https://user-images.githubusercontent.com/17557714/115998877-ba825a00-a5e9-11eb-9e4f-66b18e71940c.png)

### Bulk Destruction
![image](https://user-images.githubusercontent.com/17557714/115999244-5b254980-a5eb-11eb-8ab9-5e43d6ed84d8.png)

### One to One Damage
![image](https://user-images.githubusercontent.com/17557714/115999088-b0149000-a5ea-11eb-9519-6fa5d9369d76.png)

### Bulk Damage
![image](https://user-images.githubusercontent.com/17557714/115999393-c838df00-a5eb-11eb-9ead-bb7dfed2e23e.png)

**Comment by Charterino** [comment]
Finally Pustalorc proposed to Nelson. Somebody please wipe off my tears.

**Comment by blazethrower320** [comment]
What a good looking couple

**Comment by SDGNelson** [comment]
You put a lot of thought into this, nice work!

Changes along these lines will happen across the course of 2021. It looks like your improvements would help plugins in the short term, but all of this will get rewritten with the coming changes anyway. The planned improvements should help plugins and general buildable performance. [More details here.](https://blog.smartlydressedgames.com/unturned-in-2021/)

If one of the main things is the repair events I will take care of that for the next update.

**Comment by Pustalorc** [comment]
Thanks for the response.
Glad to hear that the changes will come along the way as well as with other rewrittes. I've read through the changes and I'll be ready for them and hyped for all of the other ones that are on the way!
And you are right, these are definitely more helpful in the short term. The biggest benefit from them all is the bulk destroy (and its event), as that way a plugin doesn't need to do the same iteration (say its not my BaseClustering plugin and its something else like SignCommands) to get an element from their own collection every time one buildable gets destroyed, as they can just perform the iteration once and get rid of all of the affected ones.
The code on this proposal also suffers from something on the post that you linked, and it's that it does all of the bulk actions in one frame, so having the ability to defer things will be the one big change that we'll all hopefully be excited to see.
