### ISSUE TITLE
method not found

### ISSUE THREAD

**Issue by Trankvil** [SmartlyDressedGames/Unturned-3.x-Community#254]
i want use method DamageTool.damage. And i have error: System.MissingMethodException: Method not found: 'SDG.Unturned.DamageTool.explode'.
how fix? or this error game tools?

**Comment by Trojaner25** [comment]
Update your Assembly-CSharp.

**Comment by Trankvil** [comment]
i have last version Assembly-CSharp

**Comment by Adamv21** [comment]
Obivously not, update again 😉
