### ISSUE TITLE
cannot switch weapons when weapon is not horizontal

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2541]
![image](https://user-images.githubusercontent.com/81492602/113950161-b0d1b780-97de-11eb-90c9-6cf0f102a2d2.png)

**Comment by ddxn78096** [comment]
it works when it has enough space for the gun i have equipped right of it because it refuses to rotate the gun to the right orientation and only tries the horizontal orientation

**Comment by SDGNelson** [comment]
Thanks for the report! This will be fixed in tomorrow's update.
