### ISSUE TITLE
NPCs issues for a lot of players

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#2542]
Hello, I'm creating this issue as a lot of players are experiencing issues with NPC vendors. The way this issue works is that you open the vendor, you click on an item, but nothing happens. It doesn't take your XP, it doesn't give you the item etc.
Here are some videos I've got from different people. All of them are from multiplayer. Note that in one video a player even gets something completely else than he was supposed to get. That NPC seems to make issues after the performance update which is weird (I havent touched that NPC for 16 days).
https://user-images.githubusercontent.com/81763752/114054495-3497ac80-9890-11eb-8c66-e97e31ef9351.mp4
https://user-images.githubusercontent.com/81763752/114054759-6e68b300-9890-11eb-90fe-3d9c3db97ac8.mp4
https://user-images.githubusercontent.com/81763752/114054893-893b2780-9890-11eb-9405-db501fa413ea.mp4

My own issue is that I've made an NPC with a lot of vendors and if you try to buy a certain vehicle in multiplayer, it doesn't work, BUT it works in singleplayer (Note that it's a vanilla vehicle and spawnpoints are set correctly).
https://user-images.githubusercontent.com/81763752/114056443-f602f180-9891-11eb-9f89-c09f4ab31959.mp4
https://user-images.githubusercontent.com/81763752/114056473-ff8c5980-9891-11eb-828b-e8760b4e6883.mp4

Here's a picture of the NPC which gave the person a wrong item. As you can see, the vendor is set correctly. (Minimally 3 other players reported this same issue to me)
https://user-images.githubusercontent.com/81763752/114057850-3c0c8500-9893-11eb-8e51-a54de3f679ed.png

**Comment by LocoCZ** [comment]
Is there a way to update it so both client and server version have the same vendor asset? Once the whole server was not able to buy anything from any npcs, then I only updated the modpack (changed literally nothing) and after server restart it worked for everyone (except the npc with cars I have posted above, that remained broken). Can't there be a vendor limit for npc for multiplayer? The NPC contains 63 vendors in total (its weird that the position of vendors that are not working are random...).

For the npc which sold something else that it should have, I'll try to change the IDs again.

**Comment by SDGNelson** [comment]
Assuming you are using the "WorkshopDownloadIDs" list it should be keeping them both up-to-date. If you are manually installing the mod however that would be a problem. Number of NPCs / vendors should be essentially unlimited. If I get the chance to do the bulk buy/sell feature soon it would make sense to add a vendor integrity check as well.
