### ISSUE TITLE
Unicode / rich text

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2543]
I opened an issue about this back in December. #2137 
I'm opening one again about this because I'm a little confused. 
It now seems to be working on one of my servers, but not the other servers - and I can't work out why.
The plugin version and config is the same on both of these servers, and both servers have the same libraries and modules installed.

Any ideas as to what may be different? 
<img width="56" alt="star1" src="https://user-images.githubusercontent.com/71527679/114067861-3152ef80-9895-11eb-95e5-4cb68e7c0840.png">
<img width="69" alt="star2" src="https://user-images.githubusercontent.com/71527679/114067863-3152ef80-9895-11eb-81a4-d85c75f740cd.png">

**Comment by TH3AL3X** [comment]
How is that possible ? Wtf

**Comment by SDGNelson** [comment]
¯\_(ツ)_/¯

**Comment by Skepay** [comment]
I'd love to work on the development of future issues. 
:)
