### ISSUE TITLE
Unturned audio stops working after my wireless headset dies

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2545]
if i am playing unturned and my headset runs out of battery the audio doesnt play because i am pretty sure it tries to switch to my laptop speakers and then tries to switch back to my headset

**Comment by SDGNelson** [comment]
Sorry for the trouble. This is outside the control of the game unfortunately, not much of the underlying FMOD API is exposed by Unity. If output device becomes settable via the API in the future I will add an option in the game's audio menu.
