### ISSUE TITLE
onDequipRequested is not consistent

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2548]
This event triggers only when player tries to equip something, but doesn't when player just dequps item without equipping other

**Comment by SDGNelson** [comment]
It should be invoked in either case. Are you sure? Is there a specific way of dequipping an item which you are running into?

**Comment by iBowie** [comment]
When player moves item in inventory and then they move item that is already equppied it dequips without firing this event.

**Comment by SDGNelson** [comment]
Ah, moving an item equipped in the backpack does dequip it. Hmm... will think about what to do because lots of the game expects the dequip method to actually dequip. Maybe there should be a "user requested" parameter which triggers the event.
