### ISSUE TITLE
BattlEye: Unofficial Modules not supported

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#255]
Many servers are BattlEye kicking players after a minute of being on the server with the message
"You were kicked from this server because: BattlEye: Unofficial Modules not supported"
This started happening immediately after the update today.

**Comment by Trojaner25** [comment]
Usually this is an client side issue, e.g. when players install Rocket to the Unturned instance they use to play on. But since 2 people wrote me about this it might be  some update that caused it..

**Comment by N1GHTPATROL** [comment]
For my server, disabling BattlEye (at the time of the issue) on my server fixed the problem entirely. Maybe that'll help Nelson, idk.

**Comment by Trojaner25** [comment]
I suppose this was  fixed?

**Comment by SDGNelson** [comment]
(was rolled back 20 min after the update, .1 release resolved it)
