### ISSUE TITLE
Unturned DS debug builds

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#2552]
A way for plugin developers to use Unturned in Unity development mode so we can debug our plugins. At the moment there is no way at all to debug plugins, so we are stuck with stuff like Console.WriteLine's which isn't really efficient.  

Maybe it could be done using a separate branch? I know this may result in some additional effort but it would be really helpful for plugin developers.

**Comment by SDGNelson** [comment]
I have actually been thinking of something along those lines: a separate app in "development build" mode with dedicated server enabled and misc debug tools. The regular game could be made faster by moving all validation, error checking, tools, etc into this separate app.

**Comment by TH3AL3X** [comment]
That's a good idea, I've always wondered why this function has never been added

**Comment by GazziFX** [comment]
@SDGNelson you forgot that? Also can you make server builds with Unity 2020 so large projects can decide for themselves whether they need a new version?

**Comment by CyberAndrii** [comment]
If you wanna make dev build you can replace your game files with the ones from your Unity installation.

Example path: `D:\UnityEditors\2019.4.30f1\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\win64_development_mono`.

IIRC you only need `UnityPlayer.dll`, `WinPixEventRuntime.dll`, and `MonoBleedingEdge/`.

Then in `Unturned_Data/boot.config` add `player-connection-debug=1`.

Also, add `wait-for-managed-debugger=1` if you want to make the game wait for a debugger on startup.

**Comment by GazziFX** [comment]
Thanks!
