### ISSUE TITLE
feature request, unloading mods when joining servers

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2554]
when you join a server it would be nice if it unloaded all of the mods that the server did not have on it so you dont have crafting options that appear to be there but dont do anything

**Comment by TH3AL3X** [comment]
aight, is a good idea, since some mods override others etc...

**Comment by SDGNelson** [comment]
Something along the lines of what you describe is planned for later this year: #2078
