### ISSUE TITLE
Small River request

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2555]
Just a small request to make patching some stuff a bit nicer - could the `River.stream` type be changed to `Stream` rather than `FileStream`? I'm currently working on a plugin which syncs player data on an SQL server to better allow players to have their characters on multiple servers and this change would make patching the loading/saving much much easier.

From what I can tell, there isn't any reason the type can't become Stream and simply initialize as a FileStream.

**Comment by SDGNelson** [comment]
Yeah seems reasonable. Eventually there should be a cleaner way to replace the savedata backend.
