### ISSUE TITLE
Switching measurement system (KPH/MPH) requires reloading level

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2556]
Switching between metric/imperial measurement system, while already in a level, does not work for the interface showing a vehicle's speed. Players must leave and reenter the level for the change to take effect.

This issue does not seem to affect other locations where imperial/metric is shown (e.g., an active Rangefinder). Ideally, the measurement system setting should be fully changeable while already in a level.

**Comment by SDGNelson** [comment]
Thanks for the report, will check into this.
