### ISSUE TITLE
[Bug] OnUseableChanged_Global

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2557]
Event doesn't work when player equip item. Probably problem is `isDedicated`.

![image](https://user-images.githubusercontent.com/17459138/115052962-9d65d100-9eef-11eb-89d9-fef7edf1ffbe.png)

**Comment by SDGNelson** [comment]
Thanks for the report, will fix. That code was supposed to go after the useable is equipped.
