### ISSUE TITLE
Add WebImage script to Unity Editor Bundle

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2558]
I was wondering if it's possible to add the WebImage script to the Unity editor bundle to allow TimerEvent/Activation hooks to access the components methods. Not sure if this is easily implementable, but throwing this here just in case.

**Comment by SDGNelson** [comment]
Hmm it should probably be fine to include this. I will mark it next update and double-check.

**Comment by SDGNelson** [comment]
After giving this more thought I wonder what you have in mind? Since the URLs would be predefined if set from unity events it would be more efficient to include the images in the asset bundle.

**Comment by IAmSilK** [comment]
It's a bit of an edge case - I'd like to be able to send images by URL and have them cached, but also be able to reset an object's image without clearing the cache. My thought was by being able to access the WebImage, I could trigger an activation hook which clears the WebImage, then resend a new image. Resulting in the cache remaining, but the image set to a new one.

**Comment by SDGNelson** [comment]
Reset to an empty image? I could add support for that, but is it different from changing the visibility to hidden?

To clarify the caching: `forceRefresh` only removes that particular URL from the image cache, not all images. Perhaps I am misunderstanding your question however?

**Comment by IAmSilK** [comment]
Since revisiting this idea, it's apparent there are better solutions.

**Comment by aviadmini** [comment]
@SDGNelson I'd like to add on to this:

Having something like WebImage loaded event hook in Unity could allow us to have some default image (or other UI) on screen until web image is actually loaded. Currently when WebImage starts loading stuff it completely disables the image component and there's no good way to overcome this, except preloading images to be available from cache. But that doesn't exactly solve the problem, plus it also completely fails when you have dynamically generated images.
