### ISSUE TITLE
[UI] Progress bar support

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2559]
Please allow plugins to send progress bar levels to clientside effects.

**Comment by TH3AL3X** [comment]
> Please allow plugins to send progress bar levels to clientside effects.

Uh? You can do it wdym

**Comment by aviadmini** [comment]
> > Please allow plugins to send progress bar levels to clientside effects.
> 
> Uh? You can do it wdym

Show me daddy

**Comment by TH3AL3X** [comment]
> > > Please allow plugins to send progress bar levels to clientside effects.
> 
> > 
> 
> > Uh? You can do it wdym
> 
> 
> 
> Show me daddy

I saw plugins that can do it, idk how cuz I didn't touch UI since 2018

**Comment by aviadmini** [comment]
> I saw plugins that can do it, idk how cuz I didn't touch UI since 2018

They fake it with some black magic (there's at least 2 ways I know). That doesn't change the fact that we don't have proper progress bar support and that's why I'm requesting it.

**Comment by educatalan02** [comment]
> > I saw plugins that can do it, idk how cuz I didn't touch UI since 2018
> 
> They fake it with some black magic (there's at least 2 ways I know). That doesn't change the fact that we don't have proper progress bar support and that's why I'm requesting it.

I agree with you, there shouldn't be needed to use black magic to do it

**Comment by Paradox304** [comment]
> > I saw plugins that can do it, idk how cuz I didn't touch UI since 2018
> 
> They fake it with some black magic (there's at least 2 ways I know). That doesn't change the fact that we don't have proper progress bar support and that's why I'm requesting it.

Yeah and that black magic breaks on lower resolutions.

**Comment by aviadmini** [comment]
@Paradox304 That black magic is different shade of black from the ones I know then. 

Anyways we'll be real happy if @SDGNelson adds first class support for progress bars so we can practice magic other than tones of black.

**Comment by Paradox304** [comment]
> @Paradox304 That black magic is different shade of black from the ones I know then.
> 
> Anyways we'll be real happy if @SDGNelson adds first class support for progress bars so we can practice magic other than tones of black.

Maybe you were talking about the black magic where you create different variants of the bar filled and then change it.

**Comment by educatalan02** [comment]
> Maybe you were talking about the black magic where you create different variants of the bar filled and then change it.

That's not the real black magic

**Comment by DerEnte** [comment]
> > I saw plugins that can do it, idk how cuz I didn't touch UI since 2018
> 
> They fake it with some black magic (there's at least 2 ways I know). That doesn't change the fact that we don't have proper progress bar support and that's why I'm requesting it.

Artificial Loading Bars

**Comment by Dudewithoutname** [comment]
Well i kinda found a way how to get around it.
i created "custom font" that contains rounded square characters  and square character

Here is link for it.
https://mega.nz/file/O6RT3QjB#PnhLb_zzlw3E6uSChLl_o12vLXhFHwdbR00jPTOKL1k

![image](https://user-images.githubusercontent.com/54103088/116819550-cda8a300-ab70-11eb-885d-d7bc87b94867.png)

Usage:
B is for left rounded square
A is for square
C is for right rounded square

**Comment by Dudewithoutname** [comment]
if you want it gradient i think you can use 
https://github.com/mob-sakai/UIEffect
but i am not sure

**Comment by aviadmini** [comment]
Nice custom font way is one of two viable ones afaik

**Comment by Paradox304** [comment]
> Well i kinda found a way how to get around it.
> i created "custom font" that contains rounded corner characters and square character
> 
> Here is link for it.
> https://mega.nz/file/O6RT3QjB#PnhLb_zzlw3E6uSChLl_o12vLXhFHwdbR00jPTOKL1k
> 
> ![image](https://user-images.githubusercontent.com/54103088/116819550-cda8a300-ab70-11eb-885d-d7bc87b94867.png)
> 
> Usage:
> B is for left rounded corner
> A is for square
> C is for right rounded corner

On lower resolutions the UI will auto adjust and then the whole thing will break afaik. I go for the same thing except background color and whitespaces to send to a text box.

**Comment by Greenorine** [comment]
> > > I saw plugins that can do it, idk how cuz I didn't touch UI since 2018
> > 
> > 
> > They fake it with some black magic (there's at least 2 ways I know). That doesn't change the fact that we don't have proper progress bar support and that's why I'm requesting it.
> 
> Yeah and that black magic breaks on lower resolutions.

Guys it's not black magic and it's pretty easy. And also it can be very good on any resolution. I started new issue and if Nelson will be not so happy with it I'll share my way.

**Comment by GazziFX** [comment]
> 
> Yeah and that black magic breaks on lower resolutions.

My doesnt breaks, and can be with any shape
![image](https://user-images.githubusercontent.com/43498426/125293347-fd6fe600-e32b-11eb-9dd7-3cd987f750eb.png)

**Comment by Greenorine** [comment]
> > Yeah and that black magic breaks on lower resolutions.
> 
> My doesnt breaks, and can be with any shape
> ![image](https://user-images.githubusercontent.com/43498426/125293347-fd6fe600-e32b-11eb-9dd7-3cd987f750eb.png)

Yep, this is the way, but it more bad than steam call for fill(

**Comment by Dudewithoutname** [comment]
> > 
> > Yeah and that black magic breaks on lower resolutions.
> 
> My doesnt breaks, and can be with any shape
> ![image](https://user-images.githubusercontent.com/43498426/125293347-fd6fe600-e32b-11eb-9dd7-3cd987f750eb.png)
> 

Did you do it manually or do you have an editor script for it ?

**Comment by GazziFX** [comment]
> 
> Did you do it manually or do you have an editor script for it ?

Created own editor script

**Comment by BarehSolok** [comment]
> Yep, this is the way, but it is more bad than steam call for fill(
Is it possible to call steamcall which does not exists in the client and send it to the client? how did you do it? i find both way above are very unpleasant to use, one require you to create 1-100 empty child just for changing fill amount, and the other one use text to simulate fill progress and should be calculated very well so it doesn't get out of bound

**Comment by educatalan02** [comment]
> > Yep, this is the way, but it is more bad than steam call for fill(
> 
> Is it possible to call steamcall which does not exists in the client and send it to the client? how did you do it? i find both way above are very unpleasant to use, one require you to create 1-100 empty child just for changing fill amount, and the other one use text to simulate fill progress and should be calculated very well so it doesn't get out of bound

I guess you can create steamcalls but you might create a clientside module that includes it. (However it will make you to not use battleye)

**Comment by GazziFX** [comment]
I think the most useful and universal way is create component with several UnityEvent<T> (for types: int, float, Vector3, string, etc) which will be executed by RPC. It can be used for progress bars, moving UIs, and more other cases

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
