### ISSUE TITLE
[Editor help] How would I go about creating a custom weather? 

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2561]
I'm making a desert map, and have passively observed the various mentions of custom weather in patchnotes. Seeing this has brought me to wonder how I would go about and create my own weather, namely a sandstorm.
I've found the weather in the bundles folder, and have attempted to patch together a custom weather through use of the example weather and default rain folders, but the weather does not appear nor work.
I want to make the sandstorm turn everything sandy colored, of which I understand to a basic level, I want it to increase wind drastically, thrashing trees and bushes about, and to cause a damaging effect for standing in the open area, like the Yukon snow defect that only goes away when inside a structure or campfire. I also want to use the wind sounds, and the occasional tree felling particle to blow about, acting as debris in the storm.

Is such a weather possible, if so, how would I go about making it? Also, how would I implement it into the map itself? Is there a devkit weather node or something of the like? Apologies for the essay.

**Comment by SDGNelson** [comment]
This documentation covers all your questions: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/WeatherAsset.md

There is no option for shelter from weather damage yet however.
