### ISSUE TITLE
[Feature Request] OnPlayerCatch(player, item, cancel) 

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2563]
It would be nice if we can easily use this event since Player.onPlayerStatIncremented doesn't include Fished item and can't be canceled.

**Comment by educatalan02** [comment]
Why you don't use Player.Inventory.onInventoryAdded? and then remove the item if it's a fish?

**Comment by Dudewithoutname** [comment]
Thanks

**Comment by Dudewithoutname** [comment]
Well, but how am i supposed to check EItemOrigin of it ? since Item doesn't have that value
