### ISSUE TITLE
[Minor] Log position reset to spawn point due to not enough space

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2566]
It would be really nice if Unturned logged when it reset someone's location due to not enough space. Logging their past position would help as well, just something like "{playerName} [steamID} was reset to spawn position from {oldCoords} due to not enough space" 

Somewhat often players are confused why they logged on and are now at a spawn point, and if it was logged it would be a lot easier to figure out.

**Comment by surv0013** [comment]
But you can do it with the plugin... Unturned has an event that is triggered when the player join to server, after determining the spawn point.

**Comment by PandahutMiku** [comment]
> But you can do it with the plugin... Unturned has an event that is triggered when the player join to server, after determining the spawn point.

You can do that to log the player's spawn position always, sure. But that's not what this is about, Unturned resets players to spawn points if they don't have enough room when leaving a vehicle, as well as on login if their saved position doesn't have room. The respawn event doesn't provide a way to tell if the player needs a new spawn point just because their saved position doesn't have enough space.

I could use harmony and patch my way through this stuff, but not probably not the best idea to patch the spawn code, and this is fairly minor, as well as a frequent thing players get confused about in general. 

Thanks though for the suggestion.

**Comment by SDGNelson** [comment]
Sure good idea, I will add this for tomorrow's update.
