### ISSUE TITLE
Weapon and Vehicle UI Removal

### ISSUE THREAD

**Issue by Paradox304** [SmartlyDressedGames/Unturned-3.x-Community#2567]
Don't know if this is already created yet, ability to remove vehicle and weapon UI from the player's screen like you can for StatusIcons and the bars.

**Comment by Dudewithoutname** [comment]
I am not sure if you can do this via plugin but iirc you can hide weapon UI in map configuration via "PlayerUI_GunVisible": false

**Comment by Paradox304** [comment]
> I am not sure if you can do this via plugin but iirc you can hide weapon UI in map configuration via "PlayerUI_GunVisible": false

You can't do this via plugin but can do through map, but through plugin would be nice.

**Comment by SDGNelson** [comment]
Good news: these were actually added as part of the 3.21.18.0 update: ShowUseableGunStatus and ShowVehicleStatus UI flags.
