### ISSUE TITLE
Server list not working on bind IPs

### ISSUE THREAD

**Issue by JustOneMoreBlock** [SmartlyDressedGames/Unturned-3.x-Community#257]
Hello,

In the issue #172 where Linux Servers won't start, and I found a workaround to at least allow players to play the game.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172#issuecomment-359150349

I mentioned there were some caveats:
- Not listing all servers on the server using the internet search.
- On the internet search, it's always 1/24~ players.
- Click on favorites will show the proper player count.

Recently, it's come to my attention that some servers are not having this problem, and that's because they're using one IP address and different ports.

In my setup, I'm using two dedicated servers, and each server has it's own `Dedicated IP` address using `bind,` and I'm using the default port `27015.`

The result is it's showing the first server from each dedicated, and why the listed caveat "Not listing all servers on the server using the internet search." is still present.

In the issue #177, it states something in regards to plugins and fake players. I only use 24 players on all my servers, and I don't use any plugins that should affect the way this connects.

Sure, I could switch to ports and would correct the issue. However, the point of using `bind` is a `dedicated IP` and using the same port. 

For the time being, I've disabled the `bind` option in Commands.dat and using different ports.

After changing all the servers to a different port. I found one server no longer showing up after I've disabled bind, and no other server is using this port on the server, and it's the default port `27015.`

Kind Regards,
- Cory

**Comment by PrimeOpalGamer** [comment]
Hey Cory,

I don't know personal know much about this situation but I've seen your server's page and am i correct that your using a Domain for the Dedicated IP. Are all the Domains registered or connected to different Static IPs?

**Comment by SDGNelson** [comment]
The intended usage is for the 1st server to be on port 27015, 2nd on 27018, etc. If you want your server computer to have a static LAN IP you can probably configure that in your router's settings (which is what I've done in the past), and for a static WAN IP you would contact your ISP.

**Comment by JustOneMoreBlock** [comment]
The purpose of `bind` is to use a different IP, and then you can use the _same port._

Then the `direct connect` can be masked by a domain name and you don't have to change any ports.

**Comment by SDGNelson** [comment]
I'm not sure if that's the case, as the value set in bind is just directly passed to the IP parameter of SteamGameServer_Init which has no documentation for what IP does. If I recall correctly the bind command was added in 2014 in case the IP parameter were important in some cases, but the consensus was that it should always be 0 (the default value).

**Comment by JustOneMoreBlock** [comment]
The IP address was binding successfully to unique dedicated IP addresses and the same port. This ceases to stop working soon after the #172 bug appear.

**Comment by ModernMoGamer** [comment]
Hi, I can replicate this issue to an extent using servers from 2 different Dedicated Machine providers.

When having a machine with additional IP addresses (more than 1 IP) binding a Unturned Server to the default IP that came with the machine will work when direct connecting and searching on the Master Server List.
Though when binding to an additional IP address (which is setup and pings correctly) can only be direct connected to and cannot be found on the server list.

This means Unturned Servers on the same machine must have unique ports. The idea with this is meant to be able to have different IP's but use the default port of 27015 like in many other games.

This seems to have to be with the master server list as Steam is able to see a server on 27016 (the query port not the main port like we see with all Unturned Servers).

I'd like to be able to have these additional IP server's show in the master server list. Please and Thank you.

**Comment by PandahutMiku** [comment]
> Hi, I can replicate this issue to an extent using servers from 2 different Dedicated Machine providers.
> 
> When having a machine with additional IP addresses (more than 1 IP) binding a Unturned Server to the default IP that came with the machine will work when direct connecting and searching on the Master Server List.
> Though when binding to an additional IP address (which is setup and pings correctly) can only be direct connected to and cannot be found on the server list.
> 
> This means Unturned Servers on the same machine must have unique ports. The idea with this is meant to be able to have different IP's but use the default port of 27015 like in many other games.
> 
> This seems to have to be with the master server list as Steam is able to see a server on 27016 (the query port not the main port like we see with all Unturned Servers).
> 
> I'd like to be able to have these additional IP server's show in the master server list. Please and Thank you.

This is an old closed issue, regardless this issue definitely doesn't exist on Windows. It might on Linux, in that case, you might want to make a new issue and include server logs and the exact configuration.

**Comment by ModernMoGamer** [comment]
#1787
