### ISSUE TITLE
[Minor] Hour Requirements / Descriptions of the Triple and Double Berets are different in steam vs in-game

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2570]
The steam description says 5,000 for Double Experience Beret and 10,000 for Triple Experience.
The in-game description says 4,800 hours for Double Experience and 9,600 for Triple Experience
Really minor, but super confusing, not sure which one is correct.

**Comment by SDGNelson** [comment]
The Steam description (5,000 and 10,000) is the correct one. Unfortunate but this will get synced up whenever the next patch is.
