### ISSUE TITLE
UI Progress Bar Support via Image Fill Amount

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2572]
Extension of #2559

Progress bars are a feature many plugin developers would love to have as the current solution which few use is a very 'hacky' method which can barely scale well with different resolutions.

A nice solution to this requested feature would be an RPC to set `Image.fillAmount` of a given element. This would allow for vertical, horizontal, and circular progress bars, and is a clean implementation of the concept.

**Comment by Paradox304** [comment]
> Extension of #2559
> 
> Progress bars are a feature many plugin developers would love to have as the current solution which few use is a very 'hacky' method which can barely scale well with different resolutions.
> 
> A nice solution to this requested feature would be an RPC to set `Image.fillAmount` of a given element. This would allow for vertical, horizontal, and circular progress bars, and is a clean implementation of the concept.

Would love this to be added tbh, so many ideas can be done with this.

**Comment by IAmSilK** [comment]
@SDGNelson, thoughts?

**Comment by SDGNelson** [comment]
It will probably happen after UI Elements and server-side UI support, but for the meantime no new additions for UI are planned.

**Comment by aviadmini** [comment]
In the meantime a pretty simple RPC would be great to have

**Comment by educatalan02** [comment]
Any news here? @SDGNelson

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
