### ISSUE TITLE
[Feature Request] A way to place Pillars and Walls on top of each other without roofs in between.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#2573]
Lets say you wanna make a 3 story high wall, you go, place the floor, the pillars the walls. no need for the roofs on level 1, 2.

or multiple heights of pillars and walls.

**Comment by SDGNelson** [comment]
This the sort of thing that will get revised with https://trello.com/c/auvkzChQ/30-base-building however pillars in general might not be necessary, we will see.

**Comment by Lion4K** [comment]
Thanks!
