### ISSUE TITLE
Player.onPlayerStatIncremented doesn't have EPlayerStat.TRAVEL_FOOT

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2575]
I tried to filter  stats in that function but it seems like EPlayerStat.TRAVEL_FOOT is not updating while player is running

**Comment by SDGNelson** [comment]
IIRC that event was only added for plugin backwards compatibility. Some stats are tracked by the client. If you want to measure how far the player has moved you could periodically record their position (which is what travel_foot does).
