### ISSUE TITLE
[Bug] Sending same image URL to component causes deactivation

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2578]
Currently, when sending the same image URL without forcing refresh, the image component is disabled and is no longer visible. This is because the `Image` component is disabled in `EffectManager.ReceiveUIEffectImageURL`, then the `WebImage` component attempts to refresh it, but returns before re-enabling the image in `WebImage.setAddressAndRefresh` as the new URL is equal to the old URL.

`component.enabled = false` should be moved into `WebImage.setAddressAndRefresh` and be called just before `WebImage.Refresh`.

**Comment by SDGNelson** [comment]
Thanks for the report, will fix for the next update.
