### ISSUE TITLE
Error on Ireland map for servers on Startup (Still runs)

### ISSUE THREAD

**Issue by PrimeOpalGamer** [SmartlyDressedGames/Unturned-3.x-Community#258]
> NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.InteractableVehicle.getTrainCar (UnityEngine.Transform root)
SDG.Unturned.InteractableVehicle.init ()
SDG.Unturned.VehicleManager.addVehicle (UInt16 id, UInt16 skinID, UInt16 mythicID, Single roadPosition, Vector3 point, Quaternion angle, Boolean sirens, Boolean blimp, Boolean headlights, Boolean taillights, UInt16 fuel, Boolean isExploded, UInt16 health, UInt16 batteryCharge, CSteamID owner, CSteamID group, Boolean locked, Steamworks.CSteamID[] passengers, System.Byte[][] turrets, UInt32 instanceID, Byte tireAliveMask)
SDG.Unturned.VehicleManager.onLevelLoaded (Int32 level)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

> NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.InteractableVehicle.Start ()

But Cant connect

**Comment by SDGNelson** [comment]
Should have been fixed in .2
