### ISSUE TITLE
Vehicle without horn still triggers zombies when pressing horn button

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2587]
Hey,
While testing my plugin i found this kinda strange bug that zombies will still get triggered even if the vehicle doesn't have horn sound.

https://user-images.githubusercontent.com/54103088/116902630-a965c880-ac3b-11eb-903e-236f1cb3148d.mp4

**Comment by SDGNelson** [comment]
Funny case. Right now the server does not know whether the vehicle has a horn or not.
