### ISSUE TITLE
VehicleManager.ServerForcePassengerOutOfVehicle()

### ISSUE THREAD

**Issue by wsmajt** [SmartlyDressedGames/Unturned-3.x-Community#2591]
so we got `VehicleManager.ServerForcePassengerIntoVehicle()`, now we need `VehicleManager.ServerForcePassengerOutOfVehicle()`

**Comment by SDGNelson** [comment]
That is available as `VehicleManager.forceRemovePlayer`, older than force into vehicle.

**Comment by wsmajt** [comment]
i was testing it out and it looks like it's only update client side.

**Comment by wsmajt** [comment]
https://youtu.be/4aSPHzATbJc

**Comment by wsmajt** [comment]
nevermind
fixed the issue
