### ISSUE TITLE
[Mod hook request] Some sort of event hook for the player's equipped weapon?

### ISSUE THREAD

**Issue by benvalkin** [SmartlyDressedGames/Unturned-3.x-Community#2593]
I had the idea for an event hook like this simply because (for ranged weapons) it seems as though it would work in exactly the same way as the VehicleTurretEventHook which was added recently. It should allow the player's equipped ranged weapon to receive events, specifically:
- OnShotFired
- OnReloadingStarted
- OnChamberingStarted

Not sure if it's necessary to think about the other types of equippable items that are not ranged weapons, but this is just an idea.

**Comment by SDGNelson** [comment]
I know there is definitely interest for this, and past issues on GitHub, but the reason is the Item prefab is shared between a lot of uses. In the future a specialized prefab for the equipped item will be added (e.g. for item animations) and event hooks like this can be added to that.
