### ISSUE TITLE
Gun cosmetic issue

### ISSUE THREAD

**Issue by Divisioniz** [SmartlyDressedGames/Unturned-3.x-Community#2594]
Some parts of the gun lose texture if you equip it for the first time and but if you unequip it and reequip it fixes it self. It also seems to be a one-time thing for that gun as it does not reoccur if you join a different server or another singleplayer map, it can also be seen by other players on the server.

![Capture](https://user-images.githubusercontent.com/47481002/117487849-4d20e280-af74-11eb-82b4-8f74524e5582.PNG)

**Comment by SDGNelson** [comment]
Thanks for the report, this should be fixed in a .1 patch this afternoon.
