### ISSUE TITLE
Needing to know the sound and particle ".prefabs" for custom weather.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2596]
Trying further into the custom weather category.

I need to know of the ".ogg" sound category for a wind sound, as somewhere there is a wind sound in the game I believe, perhaps a storm related sound effect?
I am also trying to find the ".prefab" particle category for the dead tree felling particle.

What I mean by the sound and particles .prefab or of .ogg is of this:
Particle/Effect:
"Prefab" "Effects/Volumes/Volume_Fire_0/Effect.prefab"
Sound:
"Ambient_Audio_Clip" "Effects/Weather/DefaultRainAmbience.ogg"

If it is not too difficult or tiresome, could I be supplied of the names in the format found in the custom weather files?
If not, could a way to obtain said sounds and particles be supplied?
Thank you, apologies for the exhaustive questions about the weather.

**Comment by SDGNelson** [comment]
Sure, I will make a note to include in the examples package. You can also currently look at the weather .asset files in the Bundles/Assets/Weather folder.

.prefab is any Unity GameObject saved as an asset
.ogg is an audio file format just like .mp3 or .wav
