### ISSUE TITLE
Thunder and tree bug

### ISSUE THREAD

**Issue by Bird9508** [SmartlyDressedGames/Unturned-3.x-Community#2597]
No idea if I'm the first to report this or if this is the right place to report the bug but:
When thunderstorms appear now I went and cut a tree down, and another, and another and it did not drop any logs or sticks.

**Comment by SDGNelson** [comment]
I saw you sent an email about this as well, but replying here in case anyone else runs into it.

Double-checked by triggering a thunderstorm and was able to retrieve logs and sticks from a felled tree as normal. Are you sure it is related to the lightning, or did you recently adjust your gameplay config perhaps? (accidentally changing resource drops to zero)

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
