### ISSUE TITLE
Will enter the cycle trigger event

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#2598]
In the following events:
UnturnedPlayerEvents.OnInventoryRemoved
UnturnedPlayerEvents.OnPlayerInventoryRemoved
PlayerInventory.onInventoryRemoved
Items.onItemRemoved

use：
player.Inventory.items[(byte)page].removeItem(index);
player.Inventory.removeItem((byte)page, index);
Will enter the cycle trigger event
I just want to delete items before they fall to the ground

**Comment by hksz** [comment]
Is it possible to provide a call that does not trigger onItemRemoved

**Comment by hksz** [comment]
OnBackpackChanged_Global event, the obj.visualBackpack is always 0

**Comment by CyberAndrii** [comment]
> I just want to delete items before they fall to the ground

You need to subscribe to `PlayerInventory.onDropItemRequested`, set `ref bool shouldAllow` to false and call `inventory.removeItem(...)`.

**Comment by hksz** [comment]
> > I just want to delete items before they fall to the ground
> 
> You need to subscribe to `PlayerInventory.onDropItemRequested`, set `ref bool shouldAllow` to false and call `inventory.removeItem(...)`.

When taking off the backpack, dropping items from the backpack does not trigger "playerInventory.onDropItemRequested"
[https://youtu.be/f3yZu0lkfIg](url)
but
"UnturnedPlayerEvents.OnInventoryRemoved", "UnturnedPlayerEvents.
OnPlayerInventoryRemoved", "UnturnedPlayerEvents.
OnInventoryRemoved", "PlayerInventory.
"Items.onItemRemoved" can be triggered, but executing player.Inventory.items [(byte)page] .removeItem(index) inside;
player.Inventory.removeItem ((byte)page, index);
This will trigger the above four events infinitely

**Comment by hksz** [comment]
> What is your end goal? i.e. what are you trying to do or need the event for?

My ultimate goal is to stop players from throwing certain items, which includes dropping them on death, putting them in a locker, and not dropping them when taking off the backpack

**Comment by hksz** [comment]
> > What is your end goal? i.e. what are you trying to do or need the event for?
> 
> My ultimate goal is to stop players from throwing certain items, which includes dropping them on death, putting them in a locker, and not dropping them when taking off the backpack

Although "onDropItemRequested" can be triggered when the player manually drops it, it won't be accepted when the backpack is removed.
So I removed it in "OnPlayerInventoryRemoved" so that it wouldn't fall to the ground
However, unfortunately"Inventory.removeItem((byte)page, index)" will trigger OnPlayerInventoryRemoved again

**Comment by hksz** [comment]
It's 03:30 CST, I'm going to bed

**Comment by hksz** [comment]
> Hmm sorry to say there is not a good way to completely prevent item transfers at the moment. As CyberAndrii mentioned you can prevent dropping, but there are a lot of other places that move or copy items. In the future I would like to rewrite items to be more extendable e.g. per-item events and data which would be a good time for something like that.

I am glad that you can accept my opinion and hope to see the update soon
