### ISSUE TITLE
Ability to set explosion effect separately for throwables

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2599]
Explosion XXXX (as it is for projectile type weapons). Currently, explosion effect will spawn in the same rotation as projectile lands. Its bad if you want explosion effect to spawn at some specific rotation (ground impact for example). Or maybe there is some workaround to achieve it?

**Comment by SDGNelson** [comment]
Sorry, there is not an option to use the impact normal yet. Out of curiosity what sort of effect is it?

**Comment by SDGNelson** [comment]
Closing, but feel free to comment if I misunderstood and I will re-open.
