### ISSUE TITLE
Pre-login checks before downloading server workshop content and loading level

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#2600]
When we join a whitelist server, it downloads the mods and then checks that you are whitelist. The reverse should be done. Check that you are a whitelist then download the mods. Players waste time downloading mods when they are not whitelists.

**Comment by MonsterGeeks** [comment]
Do you think you will do it ?

**Comment by SDGNelson** [comment]
Not anytime soon sorry.
