### ISSUE TITLE
Modding questions: Bullet casing & projectile hit registration

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2601]
This is not really an issue, rather 2 questions to help me clarify things that I do not understand ATM so they might be resolved if there's actual issues with them.

Anyway:
- Is there a current way to use bullet casing impact SFX via .dat editing or is it Unity-related? I'd love to use it to create custom bullet casings with custom impact SFX.
- Taking an issue that I brought up months ago regarding projectile hit registration is still a problem to me. I had some projectile weapons with velocities of 8K+ & their rigidbodies collision detection set to Continuous Dynamic; But they still phase through steep terrain & thin map objects. Not sure what's connected to this that might be the issue, & while I've heard complaints that Unity has problems related to objects travelling at high velocities not stopping when hitting, let's say a wall, I'm not sure if this is true or not. So if no one has a fix for this as of now, will this be further investigated for the future?

**Comment by SDGNelson** [comment]
Sorry, but the custom impact effects are not moddable yet. It has been a gradual work-in-progress over the last couple months replacing some of the vanilla audio. I suspect it will be moddable within another few months.

For really fast weapons the best option would be a bullet instead. In the future sweeps for projectiles similar to bullets might be added.
