### ISSUE TITLE
[Feature Request] SendUIEffectImageFillAmount

### ISSUE THREAD

**Issue by Greenorine** [SmartlyDressedGames/Unturned-3.x-Community#2602]
Hello, Nelson. I made good tool for making progress bars for unturned but I realised it's not need because you can add little method in game for easy implementation for progress bars and many another features.

So here is code (it's change of code that was given by dnspy for one of simillar methods):
```csharp
private static readonly ClientStaticMethod <short, string, float> SendUIEffectImageFillAmount = ClientStaticMethod <short, string, float>.Get(new ClientStaticMethod <short, string, float>.ReceiveDelegate(EffectManager.ReceiveUIEffectImageFillAmount));

public static void sendUIEffectImageFill(short key, ITransportConnection transportConnection, bool reliable, string childName, float fillAmount) 
{
	var reliability = reliable ? ENetReliability.Reliable: ENetReliability.Unreliable;
	EffectManager.SendUIEffectImageFillAmount.Invoke(reliability, transportConnection, key, childName, fillAmount);
}

[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public static void ReceiveUIEffectImageFillAmount(short key, string childName, float fillAmount) 
{
	if (!EffectManager.indexedUIEffects.TryGetValue(key, out
	var gameObject)) {
		UnturnedLog.info("tellUIEffectImageFillAmount: key {0} not found (childName {1} text {2})", new object[] {
			key,
			childName,
			fillAmount
		});
		return;
	}

	if (gameObject == null) {
		UnturnedLog.info("tellUIEffectImageFillAmount: key {0} was destroyed (childName {1} text {2})", new object[] {
			key,
			childName,
			fillAmount
		});
		return;
	}

	var transform = gameObject.transform.FindChildRecursive(childName);
	if (transform == null) {
		UnturnedLog.info("tellUIEffectImageFillAmount: childName '{0}' not found (key {1} text {2})", new object[] {
			childName,
			key,
			fillAmount
		});
		return;
	}

	var component = transform.GetComponent<Image>();
	if (component != null) {
		component.fillAmount = fillAmount;
		return;
	}

	UnturnedLog.info("tellUIEffectImageFillAmount: '{0}' does not have a text component (key {1} text {2})", new object[] {
		childName,
		key,
		fillAmount
	});
}
```

**Comment by Greenorine** [comment]
I know about [it](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2572#issuecomment-828016418)
But this feature is really easy and needable.

**Comment by aviadmini** [comment]
How many issues do we need to make it work? I bet ~14

**Comment by Greenorine** [comment]
> How many issues do we need to make it work? I bet ~14

Probably... yep

**Comment by SDGNelson** [comment]
Sorry, but this is not going to happen until UI Elements and server-side UI support. Not good to increase dependency on features that will be deprecated.

**Comment by aviadmini** [comment]
What about just mark it obsolete right away?

Jokes aside, it's better to have the functionality half year before the UIElements support is done than not have it

**Comment by Greenorine** [comment]
> What about just mark it obsolete right away?
> 
> Jokes aside, it's better to have the functionality half year before the UIElements support is done than not have it

Yep, and it's annoying that we're need to make bad ways to implement easy function. You said you don't know when you will make server-side UI support. Why you (Nelson) can't make some needable functions and mark them obsolete in future?

**Comment by Zikkey** [comment]
Add this PLEASE I NEED IT SO MUCH PLEASE

**Comment by Dudewithoutname** [comment]
Someone should make documentary film about this.

**Comment by Jdance-Media** [comment]
@Greenorine Am I able to just patch this into EffectManager? This is very useful.

**Comment by Greenorine** [comment]
> @Greenorine Am I able to just patch this into EffectManager? This is very useful.

No, it is client side too.
