### ISSUE TITLE
[Feature Request] More keys allowed for plugins

### ISSUE THREAD

**Issue by Cubody** [SmartlyDressedGames/Unturned-3.x-Community#2605]
Bro, we need to move this game, I know you're working so hard with Unturned 4 but vanila game is "la classic" and we need to have it LTS with good features.

I want to ask you again to think about more keys for server-listen. You gives so small key set for it and it's really sad. Community of delevopers will always ask you to add it. I'm not asking about full keyboard, but why not, many games have it (again). At least all well-known like I (inventory), O (Friends), F (Extra Interact), J (Journal) and etc.

Also we all know about plugin keys and that every player can bind it, but not so many players uses it (really). And it's easier for server and for players to set some good well-known for all buttons and not ;',./ that nobody uses.

P.S. And yes, I can make inventory, but it's not about it, this button can be used for many features

**Comment by hksz** [comment]
I would like to have support for many function keys, such as tab

**Comment by aviadmini** [comment]
keylogger time 🍡 

we had this discussion back in the day, and we won't get _specific_ keys, but I believe we can get a few more of those _plugin keys_ if we bug Nelson a lot

**Comment by Greenorine** [comment]
> keylogger time 🍡
> 
> we had this discussion back in the day, and we won't get _specific_ keys, but I believe we can get a few more of those _plugin keys_ if we bug Nelson a lot

Yes, I know about many disscussions about this thing, but it's really bad that we haven't most known keys for binding...

**Comment by SDGNelson** [comment]
It would be straightforward to increase the number of plugin hotkeys, but there are not many unbound default keys to use left. What keys do you propose binding by default?

**Comment by aviadmini** [comment]
Well, since there aren't many unbound keys, we could either use those (and have another set of commas and dots) or opt in to allowing some of bound keys to be processed. I don't think this would be of much security concern if server doesn't know the exact key, but only the internal action code. Also, I believe inputs should be disabled when unturned window isn't focused (don't know how easy is that or if it's done already)

**Comment by Greenorine** [comment]
> Well, since there aren't many unbound keys, we could either use those (and have another set of commas and dots) or opt in to allowing some of bound keys to be processed.
> 
> I don't think this would be of much security concern if server doesn't know the exact key, but only the internal action code.
> 
> Also I believe inputs should be disabled when unturned window isn't focused (don't know how easy is that or if it's done already)

I agree. It would also be nice to include support for those keys that are binded by default to implement any additional functions, and I would also like to see an event that will allow you to track the Home key press in order to hide the custom UI

**Comment by surv0013** [comment]
> keylogger time 🍡
> 
> we had this discussion back in the day, and we won't get _specific_ keys, but I believe we can get a few more of those _plugin keys_ if we bug Nelson a lot

Pressed keys are sent to the server only when the user is focused on the game window, so the keylogger cannot be done.

**Comment by Greenorine** [comment]
> > keylogger time 🍡
> > we had this discussion back in the day, and we won't get _specific_ keys, but I believe we can get a few more of those _plugin keys_ if we bug Nelson a lot
> 
> Pressed keys are sent to the server only when the user is focused on the game window, so the keylogger cannot be done.

And here is noway to discuss about secure I think.

**Comment by Jdance-Media** [comment]
> It would be straightforward to increase the number of plugin hotkeys, but there are not many unbound default keys to use left. What keys do you propose binding by default?

The Middle Mouse Button would be great as a default, it's unused by the game and it's good for like quick actions such as gaining your special ability quick.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
