### ISSUE TITLE
[Feature Request] Super Aggressive Animals

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2606]
Essentially, aggressive animals are extremely easy to cheese because you can shoot, move, shoot again, move, and keep doing it until they die, allowing basically anyone with a gun to kill any level of monster or just lure them away with ease. For the intents I am trying to do this completely breaks my map, and I would like if there would be the option for either an edit to aggressive behavior or a new behavior in which animals will instantly aggro and start chasing you when shot. This will make it so that animals cannot be cheesed nearly as easily and allow for the animals lurking around to hold some challenge and danger to unprepared players.

Thank you!
- Dumfoozle

**Comment by SDGNelson** [comment]
I suppose it could be added, but needs a few changes to the code where damage is applied, no ETA.
