### ISSUE TITLE
Pls fix `BarricadeManager.onBarricadeSpawned` and `StructureManager.onStructureSpawned`

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2608]
`BarricadeManager.onBarricadeSpawned` is called while `BarricadeRegion` `drops` and `barricades` are desynced

Using it might lead to unnecessary issues, so I strongly suggest moving it to a place where those two are in sync

Same goes for structures>>

**Comment by SDGNelson** [comment]
Fair point, will move when that is called to `dropBarricadeIntoRegionInternal` and `dropReplicatedStructure`
