### ISSUE TITLE
BarricadeManager.ReceiveTransformBarricade rotation question

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2609]
In `BarricadeManager.ReceiveTransformBarricade` method there's a line that assigns rotation to barricade drop:
```csharp
barricadeDrop.model.rotation = Quaternion.Euler(...);
```
Why does it use `.rotation` while every other call place seems to use `.localRotation`?

Pardon if I'm asking a dumb question, but I've stumbled upon this and it stated to haunt me.

**Comment by SDGNelson** [comment]
`rotation` is worldspace whereas `localRotation` is in the space of the parent transform. The barricade editor sends transforms in world space. There are a lot of improvements that could be made there e.g. sending normalized quaternion instead of euler angles, but it is what it is for now.
