### ISSUE TITLE
Rain Barrel Issue

### ISSUE THREAD

**Issue by HLFthemax** [SmartlyDressedGames/Unturned-3.x-Community#2610]
I have had quite a lot of rain and heavy rain on my map and I have my rain barrels on the outside but it seems that none of those have been filled by the rain. It seems like the rain barrel dont fill at all now.

**Comment by SDGNelson** [comment]
To double-check I placed some rain barrels on PEI and triggered a rain storm. (/weather d73923f4416c43dfa5bc8b6234cf0257) They were refilled as expected. I wonder did you wait for the rain to fully transition in before ending it? Counter-intuitively the rain barrels do go from 0% to 100% once the rain storm begins transitioning out from 100% intensity.

**Comment by HLFthemax** [comment]
Well after some experimentation from my side, i noticed that they do fill but only once the rain stop (or at least from my experience). then again, i experienced on France map so it might be specific to that one. I will try to see if i have the same problem on pei.

**Comment by SDGNelson** [comment]
Yes, they refill when the rain stops.
