### ISSUE TITLE
[Feature Request] Animal Diversification

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2615]
Hello!

With how the animals function in the game currently, it makes it difficult to experiment with new and exciting creatures for the game without them feeling identical to everything else or carrying no real threat to them.

I am seeking to create some more challenging animal types to serve as more dangerous to even armed players within my Fallout project because, as you probably already know, Fallout is teeming with deadly wildlife.

Unfortunately, this is made difficult by the fact that the **[Offense]** animal AI can be broken with extreme ease by walking circles around an animal while shooting it and it will not be able to become aggro to you unless you walk too closely.

What I'm hoping as a fix for this is some more diverse animal classes to be taken advantage of to make some really uniquely style gameplay feature animal dominant locations and a much more drastic presence of animals throughout a map. I'm hoping that you can help me to accomplish this by implementing a few things.

**[Defense]** I see a defense animal working as an ignore animal by default, but when startled will switch to Offense behavior for a time, similar to how the Neutral mobs in a game like Minecraft function. This would allow for making animals that resemble guards with use of projectile attaching or other animals that would not attack on sight but would not hesitate to defend themselves either.

**[Deadly]** As a solution to the Offense AI cheesing without having to alter how the original animals work, I think that adding a new type of hyper-aggressive animal would work. This could have an increased range to notice players, and start to attack the nearest player directly when startled rather than running or slowly walking towards the location of the noise. I think this would provide an excellent challenge for players as it would be a fair fight for those willing and a frightening enemy to try and avoid, and impose a new level of challenge to animals.

**[Variable Range]** Lastly, I think some way to edit the detection radius of an animal could be very nice, especially for animals that would have some form of projectile being able to engage you from a distance rather than needing to be approached. This also could serve as a fun gameplay mechanic for a stalker type enemy, something stealthy that can see you from great distances away and track you.

Whatever you decide to be the best course of action, I truly hope that some form of these features can be added, as without any level of change I don't know how I'm going to be able to implement Fallout creatures that will have any level of genuine danger to them and they will be something to distract rather than a dangerous enemy.

Thanks for your time,
_Dumfoozle_

**Comment by piotrus101** [comment]
Devs can also use this in new animal packs, such as the bootleg one I am currently developing. These new additions would widely change how animals are used in the game and make an awesome addition to new servers.

**Comment by bluefireexplosion** [comment]
Expressing my support for this, I think new animals like this could add a new dimension to survival gameplay and make animal interactions in general more interesting and varied than simply creatures to chase/hunt for food.

**Comment by Gekk-Here** [comment]
I totally agree with him, these are crucial features that for some reason are not yet in the game.

**Comment by DerEnte** [comment]
I support this. I would love to see animals to be a actual threat to the player. It would be really funny to see an animals interfere in a gunfight causing someone to lose due to the animal.

**Comment by Tiway-Paper-Guy** [comment]
Some features may not be easy/appropriate to make (like the ranged attack), but i think most unturned players are used to zombies and vanilla animals. Being able to customize creatures to make them more intimidating, and a bigger threat for players would be a cool addition for better content.

**Comment by ZoliWorks** [comment]
Agreed, would be a nice boost for devs working on animals.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
