### ISSUE TITLE
[Feature Request] BarricadeManager.changeOwnerAndGroup

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2617]
Currently changing the owner of a barricade is a bit confusing. For starters if I just do `BarricadeManager.changeOwnerAndGroup(transform, otherplayer.CSteamID.m_SteamID, otherplayer.SteamGroupID.m_SteamID);`                      
it gives the player permissions to salvage it but they still cannot interact with it when it's a locked barricade, so I have do:
`byte[] arr = new byte[17];
                        BitConverter.GetBytes(otherplayer.CSteamID.m_SteamID).CopyTo(arr, 0);
                        BitConverter.GetBytes(otherplayer.SteamGroupID.m_SteamID).CopyTo(arr, 8);
                        BitConverter.GetBytes(false).CopyTo(arr, 16);
                        BarricadeManager.updateReplicatedState(transform, arr, 17);
                        BarricadeManager.changeOwnerAndGroup(transform, otherplayer.CSteamID.m_SteamID, otherplayer.SteamGroupID.m_SteamID);`
just to get the barricade fully changed over to the new owner. I never ever thought of doing that until someone actually told me what was going on with that. BarricadeManager.changeOwnerAndGroup should also change the state to make it easier for those who need to change over ownership without all the hassle.

**Comment by DiFFoZ** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2454#issuecomment-790790336

**Comment by Jdance-Media** [comment]
Another issue with the current method I'm using is that when transferring ownership for a barricade the data like text and items are gone.

**Comment by BarehSolok** [comment]
thanks, i'm looking for this code :D
