### ISSUE TITLE
[Feature Request] Can_Be_Salvaged and Can_Be_Equipped Options for Buildables

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2618]
Hello! I saw today that the Can_Be_Damaged feature was added for all buildables. This is great as it allows a big step in using interactables/buildables as map objects, however two small features that I think would perfect the map buildables are Can_Be_Salvaged and Can_Be_Equipped. This would both disallow any player from being able to remove the buildables with salvage, and also prevent players (if they manage to access the item) from being able to pick it up and place it as that would become a problem with no way to remove it. If these two features would be able to be added, then barricades could be introduced with the purpose of being map objects seamlessly.

Thank you for your time,
Dumfoozle

**Comment by SDGNelson** [comment]
These are both already supported actually:
- `Unpickupable` key disables salvaging the item
- Omitting the `Useable` key prevents the item from being equipped
