### ISSUE TITLE
[UI] Support for child path instead of child name in set text/visibility calls 

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2619]
This has the following advantages:
1) optimization*: eliminates the need for runtime search through all children
2) QOL: allows us to have multiple children with same name, which makes usage of prefabs for multiple similar objects much better since you won't have to manually rename each child we want to be available to plugins

**Comment by SDGNelson** [comment]
2. The name only has to be unique within the prefab, so it is fine to use the same name between multiple prefabs.

It is unlikely for there to be more changes to these features however considering proper support for plugin UIs are planned.
