### ISSUE TITLE
[Question/Feature Request] Is it possible to make a player need to wear a fireman uniform in an area?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2622]
I'm making a deadzone that is supposed to be very hot, I want to necessitate the full use of a fireman's uniform. Is this possible? Can a node necessitate a full fireman's uniform to take damage?

If not, I believe this to be an interesting feature to possibly add.

**Comment by SDGNelson** [comment]
Sorry, there is not a setting for this at the moment.

**Comment by Jdance-Media** [comment]
This would be cool to include a setting as tho. I've always wanted to make special zones where you have to wear special equipment.

**Comment by prank0011** [comment]
Some unofficial mod hooks can make Barricade with extensive flame damage, but other restrictions can only be updated.

**Comment by Jdance-Media** [comment]
Try this, you would need to create an object in Unity and the attach the bundle to the https://github.com/olie304/UnturnedScripts/blob/master/TemperatureTrigger.cs
