### ISSUE TITLE
Possibility to stream mp3 audio through VoiceChat

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2623]
Hey, it would be cool if developers could add something like music bot to the unturned.

**Comment by Jdance-Media** [comment]
This would cause spam and annoyance to everyone on the server. If you'd like to listen to music with friends go to a discord call or have it go thru the mic.

**Comment by DiFFoZ** [comment]
I was tried made that https://youtu.be/Eo9CQ46t4Yc

**Comment by Dudewithoutname** [comment]
> This would cause spam and annoyance to everyone on the server. If you'd like to listen to music with friends go to a discord call or have it go thru the mic.

Well, i meant like imagine having nightclub at roleplay server and you want to play some music but some players are too lazy to go to a discord and i don't think that it would cause annoyance since you are able to mute it + it would be only possible to stream it only from server to client.

**Comment by Raptor-UA** [comment]
> Это вызовет спам и раздражение всех на сервере. Если вы хотите послушать музыку с друзьями, отправляйтесь на звонок Discord или попросите ее пройти через микрофон.

+

**Comment by Jdance-Media** [comment]
If it's a role play server then just add a stereo mod to the server. Then the DJ can easily play music using a stereo. If you have your own music you'd like to add make your own music bundle and get it added to the server.

Instead of playing mp3s thru the mic a better solution would be to have the option to open a MP3 in a stereo and play it.

**Comment by Dudewithoutname** [comment]
Well that's true but you can't play music from youtube instantly.

**Comment by Jdance-Media** [comment]
You brought up the topic as streaming MP3 audio thru the mic and Nelson wouldn't want to take the time to put in a YouTube feature. Like most developers he would have to risk getting a lawsuit because of it.

**Comment by SDGNelson** [comment]
Sorry, but this is unlikely to happen unless Unity exposes a built-in audio streaming compression API to c#, otherwise it would be a lot of work for a feature the base game would not use. (Voice data is compressed and decompressed by Steam)
