### ISSUE TITLE
[Help] Need to fix .config file.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2624]
I don't really understand .config files and json linters, so I need help with this.

{
"Trains":
[
{
"VehicleID": 186,
"RoadIndex": 15
},
{
"VehicleID": 187,
"RoadIndex": 16
},
{
"VehicleID": 15100,
"RoadIndex": 1

},
]
    "Tips": 14,
    "Weather": { "GUID": "d241cb77e1f44fabad8c7226568231c6" } 
}

Want it to have three trains, one orange boxcar, one blue flatbed, and one ireland passenger.
I also want it to have custom tips, and (a) custom weather(s)? (Is two custom weathers possible?)
I can also provide the english file with the tips if needed.
Thank you

**Comment by Jdance-Media** [comment]
Multiple custom weathers is a thing. I personally don't know how it works but I know for sure you can do it.

**Comment by SDGNelson** [comment]
Json linter means a tool like this, you paste your text here and it will show you the problem: https://jsonlint.com/

For an example of Tips I would recommend the Dango or Elver map config.
For an example of Weather I would recommend the vanilla levels in Bundles/Assets/Levels and the PEI, Washington, or Russia map config.
