### ISSUE TITLE
Last update crashed my server

### ISSUE THREAD

**Issue by Raptor-UA** [SmartlyDressedGames/Unturned-3.x-Community#2625]
Hello, your update makes my server crash while loading
![Screenshot_2021-05-23-12-50-20-717_com android     chrome](https://user-images.githubusercontent.com/81715836/119256262-84c09900-bbc8-11eb-8a15-2b0012005179.jpg)
[]()

P.S. please add unit tests

**Comment by Raptor-UA** [comment]
![Screenshot_2021-05-23-13-22-20-875_cn wps xiaomi abroad lite](https://user-images.githubusercontent.com/81715836/119256568-fc42f800-bbc9-11eb-8750-e71592be4530.jpg)
![Screenshot_2021-05-23-13-22-24-422_cn wps xiaomi abroad lite](https://user-images.githubusercontent.com/81715836/119256571-ff3de880-bbc9-11eb-80de-02f8852ad3f1.jpg)

**Comment by Jdance-Media** [comment]
The box collider errors are just a warning and do not do anything to the server. The object with no asset error is most likely from a broken mod you added. The vehicle manager error could be from a plugin of yours or you not updating RocketMod on your end.

**Comment by Jdance-Media** [comment]
Please try updating RocketMod via file manager on your panel or ask the support team to help you.

**Comment by Raptor-UA** [comment]
My server has RocketMod last version

**Comment by Raptor-UA** [comment]
> Ошибки коллайдера боксов являются просто предупреждением и ничего не делают с сервером. Скорее всего, объект без ошибки ресурса - это неработающий мод, который вы добавили. Ошибка диспетчера транспортных средств может быть связана с вашим плагином или вы не обновляете RocketMod на своей стороне.

On vanilla map server normal working , but on my modified map server doesn't work normal

**Comment by SDGNelson** [comment]
Jdance-Media is correct, thanks. If you can post your log file I might be able to point to which workshop file is missing.

**Comment by Raptor-UA** [comment]
> Jdance-Media is correct, thanks. If you can post your log file I might be able to point to which workshop file is missing.

[Server_SRVGame_5.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6528615/Server_SRVGame_5.log)

**Comment by Jdance-Media** [comment]
MyPlugin on your end is registering duplicates of the same command, this shouldn't be happening? If your making a version of the command for each permission group just instead check if the player has certain perms and then execute the command.

**Comment by SDGNelson** [comment]
It looks like the map is using assets from Carpat, France, Greece, Kuwait, and maybe others, but adding those maps to the dependencies should fix most of the loading errors.

There is also an error in there related to formatting an error message for a missing tree which I will get fixed.

**Comment by Raptor-UA** [comment]
> It looks like the map is using assets from Carpat, France, Greece, Kuwait, and maybe others, but adding those maps to the dependencies should fix most of the loading errors.
> 
> There is also an error in there related to formatting an error message for a missing tree which I will get fixed.

Thanks !
