### ISSUE TITLE
Request: Raycast/projectile lifetime for ranged weapons

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2626]
Improving projectile weapons seems to take longer than I thought. There should be a raycast/projectile lifetime property option to make raycasts or projectiles last for the inputted duration before it despawns.

It's really just something small that shouldn't be of priority, but depending on the code that ties to this, it should be implemented easily to the game.

**Comment by SDGNelson** [comment]
The lifespan of bullet is controlled by `Ballistic_Steps`, and the lifespan of physics projectiles is 30 seconds. Out of curiosity did you think the projectile lifespan was very short, or did you want to shorten it?

**Comment by OneManOperative** [comment]
I wanted to prolong the duration of certain projectile weapons to suit the needs of, for example, a flare gun or artillery round so that they can travel long distances while maintaining low velocities.

But also, thank you for clarifying the Ballistic_Steps' purpose a bit more but in a few words. For a long time I thought it was only a range amplifier, which I didn't fully understand until today due to the ItemData docs being outdated for awhile of new & hidden features.

**Comment by SDGNelson** [comment]
Sure, that is a straightforward change so I will add it in the next update.

**Comment by Ongjming** [comment]
Note for self: (from 3.21.19.0 Update Notes)
Projectile_Lifespan (Numeric value in seconds)
Default is 30 seconds.
