### ISSUE TITLE
[Feature Request] Spectator Tools 2.0

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2627]
Spectator tools so far in the game have been really useful, but what if it's improved?

- A player can be set into spectator mode via plugin
- Players and Plugins will have the option to have the camera track another player
- New options in game settings to show more player details above their name such as their group and even CSteamId

I'm not sure if some of these features would be possible but it would be a great QoL update to make.

**Comment by nanashi88** [comment]
I would like to request similar feature too, to the normal free camera.
-the option to have the free camera track another player
- the option to spectate player same as his 1st or 3rd perspictive
cheat tools already have similar feature, so I think this would be useful for admins too.
