### ISSUE TITLE
How to change a map to a bigger size

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#2628]
Any way to change map size from example medium to insane without lossing structures / Terrain?

**Comment by SDGNelson** [comment]
You can copy the Level.dat file from a map of your desired size to resize your level, but there is no built-in way sorry. In order the resize the terrain properly you would need to manually edit the heightmap file, or convert to devkit landscape first - either way no good option.
