### ISSUE TITLE
Workshop maps stops loading at 1/4

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#2629]
Fix?

**Comment by Lancer-TG** [comment]
(2 of the map i use)

**Comment by SDGNelson** [comment]
If it stops loading on the client then if you can attach Client.log, or if it stops loading on the server then if you can attach Server_ (name) .log I will take look.

**Comment by Lancer-TG** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6541147/Client.log)
((( [2021-05-25 14:10:04] FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
[2021-05-25 14:10:04] System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.String.Format (System.String format, System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
SDG.Unturned.UnturnedLog.error (System.String format, System.Object[] args) (at <6d98f1558dd24d908a76069bf666e795>:0)
SDG.Unturned.LevelGround.loadTrees () (at <6d98f1558dd24d908a76069bf666e795>:0)
SDG.Unturned.LevelGround.load (System.UInt16 size) (at <6d98f1558dd24d908a76069bf666e795>:0)
SDG.Unturned.Level+<init>d__128.MoveNext () (at <6d98f1558dd24d908a76069bf666e795>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <51725b129ecd4967a9a213c1ae65b295>:0) )))

**Comment by SDGNelson** [comment]
Ah, sorry about that, it will be fixed in this Friday's update. It is a formatting error when a tree asset is missing. If you have a guess as to which tree(s) are missing then subscribing to their workshop files would fix it in the meantime.
