### ISSUE TITLE
[Feature Request] Make Gasoline and Water deposits not refill.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2630]
Gasoline and water deposits, like the wells and gas stops, should not refill anymore. While helpful, it would certainly promote the building of rain barrels and pump jacks. It would allow for a bigger challenge later game, and also promote the movement across the map for to find gasoline and water deposits.
For servers and individuals, it could be a player/server choice, like zombie or item spawns in the difficulty menu. It could have a choice to enable/disable it, and could have a refill/multiplier speed setting.
For maps like Kuwait where it does not rain, it could be a config file setting, like 
"Water_Renewable": False/True
"Gas_Renewable": False/True

**Comment by SDGNelson** [comment]
If you want you can effectively disable it by setting Fuel_Reset_Multiplier and/or Water_Reset_Multiplier to a large value in the level or server config.
