### ISSUE TITLE
[Custom maps] Map stop loading

### ISSUE THREAD

**Issue by 01-Feli** [SmartlyDressedGames/Unturned-3.x-Community#2631]
Hello, i when i try to edit my map or to join the map the loading bar stops.
![imagen](https://user-images.githubusercontent.com/64453816/119571032-40c7c280-bd87-11eb-8fcf-90a6a7ed9aff.png)

Error in client.log:
[2021-05-25 18:27:09] IndexOutOfRangeException: Index was outside the bounds of the array.
[2021-05-25 18:27:09] (wrapper managed-to-managed) System.Object.ElementAddr_4(object,int,int,int)
SDG.Unturned.LevelGround.load (System.UInt16 size) (at <954d524638934ee8ab8962a55093b26e>:0)
SDG.Unturned.Level+<init>d__128.MoveNext () (at <954d524638934ee8ab8962a55093b26e>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <0789f95526694a309f40946809b4111c>:0)

**Comment by SDGNelson** [comment]
Sorry for the trouble. Can you send the map file to me at nelson@smartlydressedgames.com please? I will load it up and see what is happening.

**Comment by 01-Feli** [comment]
Okey give me a minute

**Comment by 01-Feli** [comment]
I have just sent it my email is felinegri5@gmail.com

**Comment by SDGNelson** [comment]
Thanks for sending the map file. I was able to load it up in singleplayer and the editor, so my guess is that it was actually the missing tree asset formatting error fixed for this coming update. I will leave this issue open until we know for sure, but it should be fixed on Friday. In the meantime if you know which tree has id 4004 that seems to be the one missing.

**Comment by 01-Feli** [comment]
Okey thanks ! I will check when i update the game and i will coment here if it works.

**Comment by 01-Feli** [comment]
Thanks nelson the bug is now fixed. Everything works correctly
