### ISSUE TITLE
"Already Connect" Server Error Message

### ISSUE THREAD

**Issue by SUNRISENETWORK** [SmartlyDressedGames/Unturned-3.x-Community#2633]
Hello Nelson, I have been having this Error for the last couple of days with a server i am trying to host, I am not the best when it comes to making servers but i have been having an issue where when i would join my server to check on the progress of Mods, Plugins, Etc... that i have added to the server and it gives me an error message after loading into the server saying "You are already connected to this server." this happens after i load into the server, But before it gives me the error message it doesn't just go through the loading process once but twice and i dont know why if you could shed some light on what might be the issue i would be greatly appreciative.

**Comment by SDGNelson** [comment]
It sounds like a plugin is doing something weird during the connection setup. If you can attach the Server_ (name) .log file there may be a related exception.
