### ISSUE TITLE
Infinity loading of maps assets

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#2634]
Steam telling that the hash of Unturned is ok, but Unturned is crashing at the loading screen.
Player.log
![image](https://user-images.githubusercontent.com/42337892/119618959-14b74a80-be36-11eb-8e64-aa9935dd1888.png)
No crash folder at AppData
Client.log
![image](https://user-images.githubusercontent.com/42337892/119618538-978bd580-be35-11eb-831a-c63a16e51dc8.png)

**Comment by DiFFoZ** [comment]
The crash log file should be at: `C:\Users\USERNAME\AppData\Local\Temp\Smartly Dressed Games\Unturned\Crashes`

**Comment by Sl4vP0weR** [comment]
> The crash log file should be at: `C:\Users\USERNAME\AppData\Local\Temp\Smartly Dressed Games\Unturned\Crashes`

> No crash folder at AppData

**Comment by Sl4vP0weR** [comment]
Now game loading to the main menu, BUT, when I do any input game is shutting down automatically.
@SDGNelson What can it be ?

**Comment by SDGNelson** [comment]
Is it showing the Unity crash screen with the zombie face and red '!' exclamation mark, or is it silently closing?

**Comment by Sl4vP0weR** [comment]
> Is it showing the Unity crash screen with the zombie face and red '!' exclamation mark, or is it silently closing?

nope

**Comment by SDGNelson** [comment]
In that case is there any more information in the Client.log, or is that it? If it is silently closing without writing anything to the log it might be an external application like anti-virus closing the game.

**Comment by Sl4vP0weR** [comment]
> In that case is there any more information in the Client.log, or is that it? If it is silently closing without writing anything to the log it might be an external application like anti-virus closing the game.

I closed many applications to see how it will change a situation, but I'm sure that it's in the game. (And I didn't install anything that can close applications or change their memory)

**Comment by Sl4vP0weR** [comment]
![image](https://user-images.githubusercontent.com/42337892/119848053-12d8ae80-bf3e-11eb-9323-5bb389e762cf.png)
Server also crushing after some time
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6554918/error.log)

**Comment by SDGNelson** [comment]
The server call stack appears to be crashing in mono when allocating some strings for a file watcher. Unturned does not watch any files for changes by default, so assuming it is a plugin does it work when you disable the plugin?

Going back to closing the game: do you have any anti-virus software though?

**Comment by Trojaner** [comment]
It looks like he is using OpenMod which uses a lot of file watchers. Since the crash happens with strings, maybe its related to the server path containing unicode characters?

**Comment by Sl4vP0weR** [comment]
> Going back to closing the game: do you have any anti-virus software though?

No, I don't have any anti-virus, Windows Defender also turned off.

**Comment by Sl4vP0weR** [comment]
> It looks like he is using OpenMod which uses a lot of file watchers. Since the crash happens with strings, maybe its related to the server path containing unicode characters?

D:\Steam\steamapps\common\U3DS\Servers\TestServer\OpenMod

**Comment by Sl4vP0weR** [comment]
Again this issue, but now at maps assets loading and not crashing.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6564227/Client.log)
![image](https://user-images.githubusercontent.com/42337892/120062760-4f1f2280-c096-11eb-866d-5a1b22d361b3.png)
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6564231/Player.log)

**Comment by Sl4vP0weR** [comment]
@SDGNelson, check it out.

**Comment by Sl4vP0weR** [comment]
The main issue turned back too.

**Comment by SDGNelson** [comment]
In this case you got win32 error 1392 which means ERROR_FILE_CORRUPT. You might be able to use the Windows disk repair utility to fix it, or the hard drive might be failing.

**Comment by Sl4vP0weR** [comment]
I don't know what is happening with Unturned, other apps and games feel great. I played Unturned before on this pc without any issues.

**Comment by SDGNelson** [comment]
Was the startup crash fixed after disk repair? Since your server crash was related to IO as well (file watcher) it seems possible to me that all of these crashes are caused by a faulty drive.

**Comment by Sl4vP0weR** [comment]
> Was the startup crash fixed after disk repair? Since your server crash was related to IO as well (file watcher) it seems possible to me that all of these crashes are caused by a faulty drive.

nope, not fixed.

**Comment by SDGNelson** [comment]
In that case you may need to research other options for repairing your drive.

**Comment by Sl4vP0weR** [comment]
> In that case you may need to research other options for repairing your drive.

![image](https://user-images.githubusercontent.com/42337892/120136693-4e58ce80-c205-11eb-9614-d3ea53a24e0c.png)
Victoria HDD Scan + Remap.

**Comment by Sl4vP0weR** [comment]
I still think that problem in the Unturned.

**Comment by SDGNelson** [comment]
If you can attach your Client.log again we can check if the error is still due to a corrupted file.

If your drive _is_ actually fine then it may be worth manually deleting the Unturned folder (rather than Steam deletion) to ensure the file is actually gone, and then re-installing the game through Steam.

**Comment by Sl4vP0weR** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6576218/Client.log)
After click on any UI button - game silently crashing

**Comment by Sl4vP0weR** [comment]
> If you can attach your Client.log again we can check if the error is still due to a corrupted file.
> 
> If your drive _is_ actually fine then it may be worth manually deleting the Unturned folder (rather than Steam deletion) to ensure the file is actually gone, and then re-installing the game through Steam.

I repeat, game reinstalling or deletion of the game directory does not fix it.

**Comment by Sl4vP0weR** [comment]
I want to reinstall my Windows, I hope it's will fix my issue. I don't know what else can help me more.

**Comment by Sl4vP0weR** [comment]
> I want to reinstall my Windows, I hope it's will fix my issue. I don't know what else can help me more.

The issue still not fixed.

**Comment by Sl4vP0weR** [comment]
> The issue still not fixed.

I started Unturned, not from Steam, just executed Unturned.exe and it fixed the issue somehow.

**Comment by SDGNelson** [comment]
In the most recently attached Client.log there do not appear to be any errors anymore, so that is a good step I suppose.

Next time it crashes there might be more information in Unity's Player.log file, or perhaps a new entry in Unity's Crashes folder.

**Comment by Sl4vP0weR** [comment]
> In the most recently attached Client.log there do not appear to be any errors anymore, so that is a good step I suppose.
> 
> Next time it crashes there might be more information in Unity's Player.log file, or perhaps a new entry in Unity's Crashes folder.

As I said, nothing changed after Windows reinstallation, no errors in Player.log, Client.log; no crashes logs.

**Comment by SDGNelson** [comment]
There is nothing I can do to help then, sorry. The only clue at the moment is the potential disk problems.

**Comment by Sl4vP0weR** [comment]
> There is nothing I can do to help then, sorry. The only clue at the moment is the potential disk problems.

I don't have the same issues in other programs or games, only in Unturned.

**Comment by Sl4vP0weR** [comment]
Bad OS caused these issues. Issue closed.

**Comment by SDGNelson** [comment]
For players in the future who find this: do you mind sharing what you mean by "Bad OS" please? i.e. how did you fix it?

**Comment by Sl4vP0weR** [comment]
Bad Windows OS image (ISO) (Repack with changed kernel or other changes)

**Comment by SDGNelson** [comment]
Thanks for sharing.
