### ISSUE TITLE
the effect ui causes the client to crash

### ISSUE THREAD

**Issue by Nacho-Neko** [SmartlyDressedGames/Unturned-3.x-Community#2636]
Unity 2019.4.20f1c1

The I send the UI  , The client will crash 

Effect
[Effect.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6558040/effect.zip)

Crash  : 
[Crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6558037/Crash.zip)

**Comment by SDGNelson** [comment]
I believe this crash is related to a Chinese patch for the game. It came up in an email crash report a few months ago. Unfortunately the only workaround at the moment is to disable the Chinese patch, sorry.

**Comment by Nacho-Neko** [comment]
hot to  disable the Chinese patch ? @SDGNelson

**Comment by SDGNelson** [comment]
Do you have a Chinese patch installed? Or installed replacement dlls / exes to the game before?

**Comment by Nacho-Neko** [comment]
no , i dont have  Chinese patch , i reinstall unturned for test,but it alse crash.

**Comment by SDGNelson** [comment]
Hmm the reason I ask is because the crash happened in "textinputframework" some sort of virtual keyboard. Is it an on-screen keyboard app that shows when you type in the game's text boxes?

**Comment by Nacho-Neko** [comment]
@SDGNelson no ， not shows any thing

**Comment by Nacho-Neko** [comment]
@SDGNelson  looks like Microsoft’s input method has bug..

**Comment by SDGNelson** [comment]
Since you closed this, did you find a workaround / fix?
