### ISSUE TITLE
arcing shots with snipers usually dont register hits

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2638]
if you are using a mod that has guns that shoot 500+ yards the bullet arcs so much and if it arcs over something it almost never registers a shot on them

**Comment by SDGNelson** [comment]
Sorry, but currently the server only validates line of sight between the bullet origin and the bullet hit point. The vanilla gun range is low enough that this is rarely an issue, but it would be nice to improve in the future.
