### ISSUE TITLE
Bug: Tracer effect rendering before gun is fired

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2640]
I experimented adding a looping audio source & particles beforehand to a custom tracer effect. The effect was applied to both a vehicle turret gun & the magazine it uses. The results were quite where what I hoped for, but this also lead to the tracer rendering on the player before the vehicle turret gun is fired.

It also meant that the audio source played during this bug, although when the gun fires & the shot with the tracer effect collides with an entity, the audio source lingers at that location where it landed.

**Comment by SDGNelson** [comment]
What did you have in mind for the audio? This is not something currently supported sorry.

**Comment by OneManOperative** [comment]
I tried to put an audio source in the tracer to mimic the rocket mid-air audio source that is doable on projectiles. As a result, however, that is not the case. But I tried, so now I learned that it is not supported unfortunately. I'm still certain that particle effects rendering from a pre-firing gun is a bug, however. Is that correct?

**Comment by SDGNelson** [comment]
Using the rocket sound on the bullet? Right now there is some hardcoded support for bullet flyby sounds, but that would make less sense for a looping clip.

Looping particle effects for bullets are not supported either. Currently the built-in tracers emit one particle per simulation step.

**Comment by OneManOperative** [comment]
Thank you. I'll try to keep that in mind next time. I just hope there are more options in the future to make these effects more creative.
