### ISSUE TITLE
[Question] Holiday-exclusive NPCs?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2646]
Wanting to make a Santa NPC for Christmas and a Halloween NPC.
Is there a line that will make NPCs only appear during Halloween or Christmas, like the [HW] or [XMAS] objects?
If so, what is it?
Thank you.

**Comment by SDGNelson** [comment]
Yes, the same as the _HW or _XMAS assets you can set:
`Holiday_Restriction Halloween`
