### ISSUE TITLE
Failed getting load state of FSB for audio clip

### ISSUE THREAD

**Issue by wsmajt** [SmartlyDressedGames/Unturned-3.x-Community#2647]
I created UI that play an audio.
![Zrzut ekranu (275)](https://user-images.githubusercontent.com/70204246/121260682-ef085780-c8b1-11eb-870c-71e382f5b6be.png)

and sometimes its working, sometimes its not, so i tried to fix the problem.
I started search for my problem in logs and i found that line.

`[2021-06-08 23:31:10] Failed getting load state of FSB for audio clip "house_unlock"`

I tried to find a solution to my problem on the internet, didn't find one yet. 
so i write my problem here.

i exported audio into  .ogg vorbis , mp3, wav, nothing was working until i found temporary solution. 
I just duplicated my effect files and now unturned are not loading two files.

`[2021-06-08 23:31:10] Failed getting load state of FSB for audio clip "house_unlock"
[2021-06-08 23:31:10] 
[2021-06-08 23:31:10] Failed getting load state of FSB for audio clip "close"`

but beacause i duplicated my files

`[2021-06-08 23:31:10] (EffectAsset) house_lock_f [13111]: short ID is already taken by (EffectAsset) house_lock [13111]!
[2021-06-08 23:31:10] (EffectAsset) house_unlock_f [13112]: short ID is already taken by (EffectAsset) house_unlock [13112]!
[2021-06-08 23:31:10] (EffectAsset) sound_lock_f [13108]: short ID is already taken by (EffectAsset) sound_lock [13108]!
[2021-06-08 23:31:10] (EffectAsset) sound_unlock_f [13109]: short ID is already taken by (EffectAsset) sound_unlock [13109]!`

the other duplicated one are loading.
nelson please fix.

**Comment by SDGNelson** [comment]
It looks like a Unity known issue: https://forum.unity.com/threads/error-failed-getting-load-state-of-fsb.728615/

May be worth experimenting with the audio import settings. It does not happen with vanilla audio clips, so may be worth comparing against example assets.
