### ISSUE TITLE
DMCA and Server Hosting Rule Changes Reminder

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#2649]
Hi everyone, I want to contact the developer and pay attention to my emails that I sent back in 2018-2019, these requests related to servers that violate my DMCA rights under mods, as well as servers that violate the modern rules of the game "Server Hosting Rules", how do I file a complaint about this and get a response?

since I sent complaints to steam, they block violators according to the rules of the DMCA, but the game allows you to simply re-install the mod and that's it, the server is working again

**Comment by SDGNelson** [comment]
Yes, you can contact me by email at: nelson@smartlydressedgames.com

If a server you report repeatedly infringes workshop author's copyright then we will block it from the game.
