### ISSUE TITLE
[Feature Request] Layer Original Materials under Custom Mesh

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2653]
Hello! Currently, the custom mesh is a full replacement of the vanilla mesh and therefore allows none of the original materials to shine through. However, in an attempt to make an overcoat of sorts I would like for the players skin, face, hair, etcetera to remain on the model, along with the pants.

Is there currently a way to do this? If not, would there be a way that you can add a feature to enable hair, beard, face, skin, pants, etc for the player mesh replacements?

**Comment by Dumfoozler** [comment]
I'm thinking some type of option that is an alternative to override, instead just placing the custom mesh material on the top of the render order then rendering everything else in the standard order the vanilla player model renders.

**Comment by SDGNelson** [comment]
Right now the closest option is to use a replacement mesh without a replacement material.

**Comment by Dumfoozler** [comment]
Is there any way you could add some feature to have a priority material as an alternative option to a complete override, or some way to include the original materials under the overridden? I want to make overcoats and currently the bottom is eaten up by the pants.

**Comment by SDGNelson** [comment]
Priority material unlikely soon. Obviously layered clothing would be better, but at the moment in the vanilla items like that are split into top and bottom, so you could use the mesh replacement with separate top and bottom items.

**Comment by Dumfoozler** [comment]
That would defeat my purpose as the pants still take priority over a custom mesh shirt.

**Comment by SDGNelson** [comment]
I guess like your other request #2487

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
