### ISSUE TITLE
GameQ not able to get server Information

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#2656]
This is quite an old issue at this point but I have tried contacting everyone I can to get an answer and I am not getting much luck. I have been told to ask you for some information that could fix this

Pretty much whats happening is there is a PHP library called GameQ that some people use to get server information. In my case its used for our panel to display the number of players on the panel. 

For some reason after the 3.21.18.0 update it randomly stopped working. After a lot of tests I have narrowed it down to Unturned servers running 3.21.18.0+ in a pterodactyl docker container. It weirdly seems to work for any other type of servers (windows, linux, servers on tcadmin, etc) but just doesn't work on any server running pterodactyl unless the server is running an older version of unturned.

I have tested this by putting in the IP and ports of a range of servers and it confirmed my theory. I ran the tests directly with GameQ and the servers that worked returned all relevant information while those that did not returned empty values.

Do you know what may be causing this or what was changed around the 3.21.18.0 update so I can try and find someone to patch or adjust GameQ to work.

GameQ - https://github.com/Austinb/GameQ

**Comment by SDGNelson** [comment]
The main thing that comes to mind is that Valve have been working on upgrades to the server query features relatively recently. Since you mention it only happens in Pterodactyl containers I would guess it is related to some sort of firewall or network restrictions.

**Comment by Bradler26** [comment]
I would of also assumed it to be a firewall or network setup but the fact that any server running an older version of unturned works perfectly fine until its updated is what makes me think its something that was changed in an update that GameQ for some reason doesn't like.

**Comment by SDGNelson** [comment]
That update did also add server links and the monetization setting to the queryable server data. It is only more information available however, I doubt that would have made a difference unless GameQ had an implementation specific to Unturned relying on the order of data.

**Comment by Bradler26** [comment]
Thought that too but when I queried the servers that aren't running pterodactyl it returned all of that new information perfectly fine. If you can't think of anything else that could potential cause this then feel free to close this and I will likely just look for a new query library to use.

**Comment by SDGNelson** [comment]
Sorry, nothing else comes to mind.
