### ISSUE TITLE
local lan server cannot join in

### ISSUE THREAD

**Issue by ohh25** [SmartlyDressedGames/Unturned-3.x-Community#2657]
I started a local server through SteamCMD and changed the map to Kuwait by workshop, I  can join the server locally but my mates can't join in and kept appearing 'steamnetworkingsickets_endreason_remote_badcert / _timeout'
I have tried using '-NetTransport=SteamNetworkingSockets' but the problem still
pls help

[U3DS COMMAND LINES.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6661938/U3DS.COMMAND.LINES.txt)

**Comment by SDGNelson** [comment]
From the log it looks like Steam servers were probably temporarily down so it was unable to get an encryption certificate. If you try again now / later does it work properly?

**Comment by ohh25** [comment]
> From the log it looks like Steam servers were probably temporarily down so it was unable to get an encryption certificate. If you try again now / later does it work properly?

the problem still

src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#297387333 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#297387333 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2361217397 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2361217397 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4090683946 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4090683946 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2316048434 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2316048434 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#1081828221 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#1081828221 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2473984566 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2473984566 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#417351726 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#417351726 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#3401463481 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#3401463481 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2997842830 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2997842830 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#768696438 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#768696438 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#1783226382 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#1783226382 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2561458893 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2561458893 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4026101921 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4026101921 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#3668921368 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#3668921368 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2655562721 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#2655562721 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4293538834 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4293538834 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4144374554 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#4144374554 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#3109519709 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#3109519709 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#1064865051 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2613) : Assertion Failed: [#1064865051 UDP steamid:76561198812211712@192.168.2.9:51599] problem (5002) We don't have cert, and self-signed certs not allowed, but connection already dead (0 5002 We don't have cert, and self-signed certs not allowed)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp (1231) : Assertion Failed: GetState() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally

**Comment by SDGNelson** [comment]
Does the server not have access to the internet? Or perhaps the firewall is blocking it from connecting to Steam?

In the meantime a workaround would be to use -NetTransport=SystemSockets which has lower performance but should be fine for LAN.

**Comment by ohh25** [comment]
thank you, i got it solved through syssockets
