### ISSUE TITLE
Bolt action gun does not play hammer animation in multiplayer!

### ISSUE THREAD

**Issue by kotyaraaa** [SmartlyDressedGames/Unturned-3.x-Community#2658]
I made gun with custom projectile and added "Action Bolt" line into its .dat file. This weapon works perfectly in singleplayer. But hammer animation is not played after shooting in first person cam on the server. Here is video where i tested this gun with my friend. You can hear hammer sound from him (animation is played). But hammer animation does not want to be played on my hands!

I have tested vanilla rocket launcher (using modded magazine with 3 shots and "Action Bolt" line) and found the same problem.

https://user-images.githubusercontent.com/85970851/122223204-a35e3b00-cebb-11eb-88f3-98b374cbd073.mp4

**Comment by SDGNelson** [comment]
Can you attach the Client.log file please? There might be an asset-related error.

**Comment by kotyaraaa** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6664362/Client.log)

**Comment by SDGNelson** [comment]
You are right that there does not seem to be anything about your gun. Sorry I missed that it was specific to projectiles in your original post. Taking a look at the code I see that it is a bit different in that respect between bullet guns and projectile guns. Will check into this properly for hopefully the next update.

**Comment by SDGNelson** [comment]
Thanks for the report, this should be fixed for tomorrow.
