### ISSUE TITLE
Console Error: steamnetworkingsockets_lowlevel.cpp

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#2659]
My console saying a lot of times:
"src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1425) : Assertion Failed: SDR service thread gave up on lock after waiting 50ms. This directly adds to delay of processing of network packets!"

Hi, this is the first time I see this error on my console.
![log-host](https://user-images.githubusercontent.com/25484986/122315477-8728c100-cef0-11eb-87f4-3334b856e7c2.png)

I am with:
RocketMod and OpenMod.
Using few plugins, I'm pretty sure this isn't plugins.
I will link my server log here.

One other thing I wanted to mention aside, that my server is suffering several DDoS attacks, I'm not sure if this error appeared because of the attacks.

**Comment by SDGNelson** [comment]
This just means the server is running at less than 20 ticks per second. Sorry to hear your server is being attacked, but that is probably what is slowing it down.
