### ISSUE TITLE
Suggestion: Set the size of all the server descriptions to the same value

### ISSUE THREAD

**Issue by 01-Feli** [SmartlyDressedGames/Unturned-3.x-Community#2660]
I am oppening this issue because i think the server list looks horrible with things like tthe image i posted here, i think would be a good idea to all the servers have the same size in their descriptions because it looks more cleaner and clear and it isnt ugly
![imagen](https://user-images.githubusercontent.com/64453816/122413585-df95a800-cf5c-11eb-90d5-9be6e4ede79a.png)

**Comment by 01-Feli** [comment]
In some cases the description is bigger than the title. Like you can see in the image

**Comment by educatalan02** [comment]
They are using <size> tag

**Comment by 01-Feli** [comment]
I know, that is why i am suggesting to remove it

**Comment by SDGNelson** [comment]
Thanks for the report, good point. I will change this for the next update.

**Comment by 01-Feli** [comment]
Thanks nelson

**Comment by SDGNelson** [comment]
Re-opened so that I would not forget to fix. Sorted out for tomorrow!

**Comment by kotyk7** [comment]
![image](https://user-images.githubusercontent.com/35780035/122613268-dc95d700-d084-11eb-8235-5dcb4a20dfeb.png)

huh
![image](https://user-images.githubusercontent.com/35780035/122613321-f1726a80-d084-11eb-8cee-853f47a02e84.png)

**Comment by SDGNelson** [comment]
@kotyk7 Thanks for the report! It looks like they changed their rich text to uppercase, but unfortunately the old method I used for this check was case sensitive. I will update the older code to be case insensitive.
