### ISSUE TITLE
Unturned Server issue : You lost your place in the queue..??

### ISSUE THREAD

**Issue by Era5eZ** [SmartlyDressedGames/Unturned-3.x-Community#2661]
Im newbie server dev and stuck with only one problem when some of my tester try to connect to my server an it said "You lost your place in the queue", all of the tester that failed to connect have low tier spec is this a Problem?? or it can be fix, almost of my server map was Custom workshop map like Chernarus and Ural I try to change my config about Queue but nothing change If anyone can help or just recommend please.

sorry if my english was so bad but ill do my best, Thx for reading my post

**Comment by SDGNelson** [comment]
The easiest option is to increase Queue_Timeout_Seconds in the server's Config.json from 15 to something like 60.

**Comment by Era5eZ** [comment]
> The easiest option is to increase Queue_Timeout_Seconds in the server's Config.json from 15 to something like 60.
thx ill try it

**Comment by Era5eZ** [comment]
Thx ill try it
