### ISSUE TITLE
[Suggestion] Projectiles depending on magazines

### ISSUE THREAD

**Issue by kotyaraaa** [SmartlyDressedGames/Unturned-3.x-Community#2662]
Is it possible to add a feature for magazines that could set custom different projectiles to one gun (without adding projectile prefab into gun folder)? I think it would be useful for some kind of weapons like grenade launcher or shotguns with specific ammo.

**Comment by SDGNelson** [comment]
This would be a cool feature, closing only because there is an existing similar request #1899
