### ISSUE TITLE
[2021-06-18 21:14:21] TypeLoadException: Could not resolve type with token 0100004b (from typeref, class/assembly UnityEngine.TransformExtension, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2663]
this exception spamming after recent update, no changes done to server

**Comment by SDGNelson** [comment]
Sorry, I moved some extension methods into UnityEx and SystemEx assemblies. Surprised anyone was using those! Out of curiosity which method was it?

**Comment by baranmod** [comment]
no idea...

**Comment by baranmod** [comment]
something in airdrops modifying plugin

**Comment by baranmod** [comment]
guess I can close issue since its on my end

**Comment by rube200** [comment]
Yeh it broke one of mine to.
i was using `getOrAddComponent` (that now is `GetOrAddComponent` at UnityEx)
