### ISSUE TITLE
Suggestion: Remove gold server tabs

### ISSUE THREAD

**Issue by 01-Feli** [SmartlyDressedGames/Unturned-3.x-Community#2664]
The gold tab is useless because there are no servers for gold probably 1 or 2 so why just remove that tab but keep the ability to make gold server just something like a gold color in the image that shows the server like in this image (Sorry i am not really good using paint): 
![imagen](https://user-images.githubusercontent.com/64453816/122624174-5e7e0400-d075-11eb-9aee-b8ddf4743646.png)

And if a player that doesnt have gold try to join just reject him with something like: This is a gold server you can buy it at <the unturned page>

**Comment by SDGNelson** [comment]
Official servers would probably be in the gold servers list. In the meantime worst case scenario it is an easy way to increase server visibility.
