### ISSUE TITLE
Request/question: Lockable water/fuel tanks and Generators/pumpjacks.

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2668]
According to https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ItemData.md#Barricades
"Locked: Usability/interactivity access restricted to owner."
Owner=(person placing the barricade + their group at time of placement)
I found someone to help me test this together in a multiplayer server.
For the water/fuel tanks, there was a red outline, but the non owner could still pour and take away water/fuel to and from it.
For the generator, everyone could still pour/takeaway and switch the generator on and off.

Question: I am assuming that the game currently does not support "Locked" option for anything other than doors/gate/hatch/shutter/sign/placards and storage barricades, is that right?

Request: If my assumption above is true, would it be possible for "Locked" option to be applicable to every other interactable barricades as well?
(Bed is kinda locked by default in a sense if you claim it, thinking of this, would it be possible to have such toggle-able lock for other barricade types? Kinda like vehicles' lock and unlocking)

**Comment by SDGNelson** [comment]
Sorry, the "locking" system is a bit of a mess as you found. Older barricade types track the owner/group in two separate places... I would like to refactor this and allow other lock types as part of: https://trello.com/c/ztdXjXPm/3-digital-and-combination-locks

**Comment by Ongjming** [comment]
Thanks, am looking forward to this :)
