### ISSUE TITLE
[BUG] OnConsumeRequested

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2669]
Event `OnConsumeRequested` does not prevent the replenishment of water, food, etc. Method `invokeConsumeRequested` is executed after the characteristics have changed. This way you can farm stats.

**Comment by SDGNelson** [comment]
OnConsumeRequested is called for using on self, whereas onPerformingAid is called for using on another player. Energy, hallucination, oxygen, and warmth cannot be cancelled because they are locally predicted, but all other stats can be cancelled.
