### ISSUE TITLE
UseableGun state problem

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2671]
Guns with projectile e. g.  bow, rocket launcher aren't updating state current ammo  
on the `UseableGun.onBulletSpawned` event.
Is this bug or is that how it's supposed to be?

**Comment by SDGNelson** [comment]
It looks like that happens a bit later in the code. What do you have in mind?

**Comment by Dudewithoutname** [comment]
Well, i was creating custom hud for the game and it would be nice if i could keep track of a weapon's ammo without making fake ammo counter.

**Comment by SDGNelson** [comment]
In the meantime the best way to do that would probably be to listen for the state updated event, or to compare the current ammo against the previous frame ammo and only send the text changed event when that changes.
