### ISSUE TITLE
Possibility to change asset values for a single instance in runtime

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2674]
hey, well so my idea was to make the vehicle upgrading plugin but later i've realised that you can't actually change properties of it without manipulating with a asset, so why not to make something like AssetOverride class that could override some asset values for a single instance or atleast add
`InteractableVehicle.setMaxSpeed();`
`InteractableVehicle.setMaxFuel();`
`InteractableVehicle.setMaxBattery();`

I think that a lot of modders would appreciate that <3.

**Comment by SDGNelson** [comment]
Sorry, but this is unlikely to happen anytime soon because those values are not replicated. The game currently depends on the value being the same between the client and server.
