### ISSUE TITLE
The edge will block the player from moving forward

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2676]
Sometimes, the edges of Barricade, Structure, Object will block the player from moving forward:

https://user-images.githubusercontent.com/64722485/123543023-44cc7300-d77f-11eb-8459-2a0de436cc47.mp4

https://user-images.githubusercontent.com/64722485/123543033-501f9e80-d77f-11eb-9a14-c5d78d12786e.mp4

https://user-images.githubusercontent.com/64722485/123543053-5f9ee780-d77f-11eb-8450-94fcbe280809.mp4

This is not a big problem, but it will confuse the player.

**Comment by SDGNelson** [comment]
Unfortunately this is not fixable at the moment:

1. Unity's "CharacterController" can be abused to move through some specific shapes, for example walking into an inward-curving ceiling like the barracks interior is an easy way to walk through a wall.
2. To prevent this, Unturned reverts the move if CC went through a wall.
3. If a CC substep went around a corner, like falling off a ledge, it will get incorrectly reverted.

We need a replacement for the CC which I would like to do as part of this card, but easier said than done: https://trello.com/c/NP73WOyZ/4-movement-enhancements
