### ISSUE TITLE
Improve of sendRelayToServer

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#2678]
Would it be possible to add some parameter to send date?
In my case, I wanted to know, on the server side, the origin of the redirect (self redirect, or which server redirected the player)

I use self redirect to relog the player when he left admin mode (reset spec mode since it is not possible to force it in other way)

**Comment by SDGNelson** [comment]
If I understand correctly the real issue is that disabling freecam should force them out of freecam? That should be fixed, will do.

**Comment by rube200** [comment]
No, the freecam stuff iis just the example.
What i really want is to know if player got a redirect join or connect from menu and if it is a readirect which server did it

**Comment by GazziFX** [comment]
You can make your own referrer system, save sendRelayToServer calls to database with origin/reason

**Comment by rube200** [comment]
this implies several lines of codes and several ifs to check if the connect is really that one or not.  eg the player canceled and then clicked to enter manually.
On client side it just need to send the Ip of last server(if redirect) or 0 if normal connect

**Comment by DiFFoZ** [comment]
i think you could generate id and then passes it as a password, so you'll know if it redirects or not
