### ISSUE TITLE
Unconfirmed Bug: /animal creates spawns

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2679]
Despite knowing that this exists way back, I have people telling me that using this command also creates an animal spawn.

I am not entirely sure if this is true, so I am reporting this as an assumption.

**Comment by DiFFoZ** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/623#issuecomment-466841377

**Comment by SDGNelson** [comment]
Sorry, but DiFFoZ link is correct. It would get improved when/if some of the animal netcode (among other animal feature requests) gets improved.

**Comment by Johnanater** [comment]
If you write some cursed code, spawning a singular animal is possible :)
