### ISSUE TITLE
Unity Visual Script (Bolt) How to launch things where i look?

### ISSUE THREAD

**Issue by HKristof78** [SmartlyDressedGames/Unturned-3.x-Community#2680]
I have a problem in unity!I use Bolt visual scripting and use Rigidbody.AddForce and i want to launch things at the direction where i look.
This is the script i have so far:
![unknown](https://user-images.githubusercontent.com/79401796/124171784-48c30280-daa9-11eb-8ee2-0b2a0e87e29e.png)
 
Can someone help me with it?

**Comment by SDGNelson** [comment]
It looks like the force passed into AddForce is zero. You probably want to use the "forward" direction multiplied by a larger number like 100.

That being said, it is not possible to use custom scripts in asset bundles, sorry.
