### ISSUE TITLE
Water Volume FPS Drops

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2681]
I've noticed that adding a water volume in devkit severely impacts FPS for players. 
Looking in the direction of the water volume(s) from anywhere on the map cuts the FPS in half.
Has this always been an issue, or is there a trick to fix it?

**Comment by SDGNelson** [comment]
Are planar reflections enabled on that water volume? It requires rendering the scene a second time upside down which is why it severely impacts performance.

**Comment by AdamDN** [comment]
I've just tested disabling reflection - you're right that's definitely the cause.
That's a shame, it looks much better with reflections enabled. Is there any possibility of it being optimized in the future?

**Comment by SDGNelson** [comment]
Due to how it works (rendering the scene multiple times) there is not much else that can be done to reduce its performance impact. The game already aggressively filters which objects are eligible for reflection. Other games like CS:GO limit the scene to one reflective surface at a time.
