### ISSUE TITLE
Jamming

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2682]
I tried to put jamming on my weapon, but I don't have a sound when jamming, although hammer is in the folder, and the nelson sound is used. What could be the reason?
![image](https://user-images.githubusercontent.com/83378019/124195261-bf282a80-dad2-11eb-9c30-cbfb4c70d415.png)

**Comment by MoltonMontro** [comment]
IIRC, the jam audio should be called ChamberJammed.

**Comment by JorelDecker** [comment]
> IIRC, the jam audio should be called ChamberJammed. Similarly, the unjam animation would be UnjamChamber.

I'll try it now

**Comment by JorelDecker** [comment]
> IIRC, the jam audio should be called ChamberJammed. Similarly, the unjam animation would be UnjamChamber.

![image](https://user-images.githubusercontent.com/83378019/124196309-cf410980-dad4-11eb-82ea-2acf91e1a571.png)
Like this?

**Comment by JorelDecker** [comment]
> IIRC, the jam audio should be called ChamberJammed. Similarly, the unjam animation would be UnjamChamber.

Thank you, it helped now.
