### ISSUE TITLE
Spec Ops Helmet unobtainable on Russia/Germany

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2683]
This item is missing from the Special_Low_Clothes spawn table, resulting in it being unobtainable on the Russia and Germany maps.

**Comment by SDGNelson** [comment]
I am not sure if it was supposed to be obtainable. Originally there was the spec ops beret to go with the spec ops armour. The helmet was added later by popular request.

**Comment by SDGNelson** [comment]
Oh, thanks for checking that! Okay: I will add today.
