### ISSUE TITLE
Object can not be placed in map editor

### ISSUE THREAD

**Issue by kotyaraaa** [SmartlyDressedGames/Unturned-3.x-Community#2684]
My object can't be placed in map editor like it has no object asset. But error log is empty and all files and folders are named correctly. Also this lines appear when i try to place the object:

[2021-07-03 00:25:08] InvalidCastException: Specified cast is not valid.
[2021-07-03 00:25:08] SDG.Unturned.LevelObject..ctor (UnityEngine.Vector3 newPoint, UnityEngine.Quaternion newRotation, UnityEngine.Vector3 newScale, System.UInt16 newID, System.String newName, System.Guid newGUID, SDG.Unturned.ELevelObjectPlacementOrigin newPlacementOrigin, System.UInt32 newInstanceID, SDG.Unturned.AssetReference`1[T] customMaterialOverride, System.Int32 materialIndexOverride, System.Boolean newIsHierarchyItem) (at <d38e57d7c7f4440982a4a014f8efe40e>:0)
SDG.Unturned.LevelObject..ctor (UnityEngine.Vector3 newPoint, UnityEngine.Quaternion newRotation, UnityEngine.Vector3 newScale, System.UInt16 newID, System.String newName, System.Guid newGUID, SDG.Unturned.ELevelObjectPlacementOrigin newPlacementOrigin, System.UInt32 newInstanceID) (at <d38e57d7c7f4440982a4a014f8efe40e>:0)
SDG.Unturned.LevelObjects.addObject (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Vector3 scale, System.UInt16 id, System.String name, System.Guid GUID, SDG.Unturned.ELevelObjectPlacementOrigin placementOrigin) (at <d38e57d7c7f4440982a4a014f8efe40e>:0)
SDG.Unturned.ReunObjectAdd.redo () (at <d38e57d7c7f4440982a4a014f8efe40e>:0)
SDG.Unturned.LevelObjects.register (SDG.Unturned.IReun newReun) (at <d38e57d7c7f4440982a4a014f8efe40e>:0)
SDG.Unturned.LevelObjects.registerAddObject (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Vector3 scale, SDG.Unturned.ObjectAsset objectAsset, SDG.Unturned.ItemAsset itemAsset) (at <d38e57d7c7f4440982a4a014f8efe40e>:0)
SDG.Unturned.EditorObjects.Update () (at <d38e57d7c7f4440982a4a014f8efe40e>:0)

What is the reason? I just copied prefabs and .dat files from my other objects that work correctly

**Comment by SDGNelson** [comment]
Hard to say for sure, but my guess is a child transform named "Block" with a non-BoxCollider component. Old bad code.

**Comment by kotyaraaa** [comment]
I used non-BoxCollider components on some of my objects and they work perfectly. Ok, i will consider this
