### ISSUE TITLE
Feature request: Volume config options for shoot/reload/hammer sounds on weapon's .dat

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2685]
Similar as on barrel. For example, volume_shoot / volume_reload / volume_hammer. It takes quite a while to tweak sound clip's volume to perfection (to avoid ear rape situations) and config option would help alot I believe.

**Comment by SDGNelson** [comment]
It would be a nice quality of life feature.

**Comment by baranmod** [comment]
it would also be cool to have an option for barrel to simply use weapon's shoot sound and tweak its volume instead of using separate sound for barrel

**Comment by baranmod** [comment]
One more thing (not anyhow related to above ones, but don't want to spam). Is it possible to add an option for sentry guns to aim for head instead of chest?

**Comment by SDGNelson** [comment]
Technically the sentry guns use probability rather than actually aiming, but it might make sense to add at some point.

**Comment by baranmod** [comment]
And one more thing. This would help to improve skins system for modded servers I suppose. Currently, you can do skins by doing separate mods for items, with separate configs etc, then plugin converts one item to another on pickup/equip for example. So maybe its possible to make so you can add multiple prefabs in one folder which would be under the same config (i.e. Item/Vest/Vest_1/Vest_2....)  and then plugin would have an ability to read those separate prefabs for players who have permissions to them? Example:
![image](https://user-images.githubusercontent.com/14231707/125117099-5bb38380-e0f6-11eb-8bb8-f32cee7df750.png)

I am not sure if its somehow possible or not to achieve it, but if not - it could be another CoL feature eliminating all the fuzz with dozens of separate configs for the same item.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
