### ISSUE TITLE
Bullets don't explode!

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#2687]
See the video：https://youtu.be/PkyVWTOdDHE

The bullet didn't explode on contact with the ground, it passed through!

**Comment by SDGNelson** [comment]
That is unusual. Thanks for the report. I will mark this "next patch" so that I remember to investigate further.

**Comment by hksz** [comment]
> That is unusual. Thanks for the report. I will mark this "next patch" so that I remember to investigate further.

Have you made any progress?

**Comment by SDGNelson** [comment]
I did not look into it until today. Tried reproducing with the Maplestrike + Explosive Magazine, but the explosive bullets hit that road as expected. It could be that something is corrupted with that particular road object on your client, in which case if you "verify game files" in Steam it might repair?

**Comment by hksz** [comment]
> I did not look into it until today. Tried reproducing with the Maplestrike + Explosive Magazine, but the explosive bullets hit that road as expected. It could be that something is corrupted with that particular road object on your client, in which case if you "verify game files" in Steam it might repair?

Even if I completely uninstall and reinstall
Exploding bullets have a chance of disappearing when I play on the server

**Comment by hksz** [comment]
> I did not look into it until today. Tried reproducing with the Maplestrike + Explosive Magazine, but the explosive bullets hit that road as expected. It could be that something is corrupted with that particular road object on your client, in which case if you "verify game files" in Steam it might repair?

I didn't have any problems with the single player game

**Comment by SDGNelson** [comment]
Ah, sorry for my misunderstanding - I tested in singleplayer. I will reinvestigate in multiplayer.

**Comment by hksz** [comment]
> Ah, sorry for my misunderstanding - I tested in singleplayer. I will reinvestigate in multiplayer.

OK, I'll wait for your news

**Comment by hksz** [comment]
> Ah, sorry for my misunderstanding - I tested in singleplayer. I will reinvestigate in multiplayer.

It's strange, I was able to fire the gun when I tried to drive the tank before but it turned out that the shells went underground and the single player had no problems. The problem is very similar!

**Comment by hksz** [comment]
The problem this time is that I am using the original 363 and 1200 and have not modified it

**Comment by SDGNelson** [comment]
Thank you for bringing this to my attention! Indeed it was not working properly on the server. This should be fixed now for the next update.
