### ISSUE TITLE
Item animation import problem

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2689]
I made an animation for useable item and had to change scale of the arm bone. To avoid the stretching of it's child bones, I unchecked "Inherit Scale" option both for Hand bone and Hook bone, yet when I import this animation clip to unity, these bones still inherit scale and stretch out. How do I disable this scale inheriting option in unity?

![изображение](https://user-images.githubusercontent.com/59206749/124606591-b7230e80-de75-11eb-8043-cca8db754193.png)
![изображение](https://user-images.githubusercontent.com/59206749/124606646-c2763a00-de75-11eb-9a9a-dfbbd387c07d.png)
![изображение](https://user-images.githubusercontent.com/59206749/124606825-ee91bb00-de75-11eb-8bdf-bc1193b14834.png)

**Comment by SDGNelson** [comment]
Depends on what is supported by the Unity importer. Note drugs are not allowed on the workshop.
