### ISSUE TITLE
Umbrella icons aren't centered

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2690]
Umbrella icons aren't centered with the new automatic image scaling. I assume it has to do with the canopy not having a collider around it, so instead it's just centered around the handle. Original on the left, new on the right:

<img src="https://user-images.githubusercontent.com/7608445/124811795-79cb8900-df28-11eb-86d0-4f98a6a15601.png" alt="Original scaling" width="360px"> <img src="https://user-images.githubusercontent.com/7608445/124811800-7c2de300-df28-11eb-88d3-5b3a4faab889.png" alt="New scaling" width="360px">

**Comment by SDGNelson** [comment]
To clarify: the icons use the renderer bounds, not collider bounds. That being said I am not sure why it is wrong here. Will investigate.

**Comment by SDGNelson** [comment]
Ah, I forgot the automatic measurements are disabled for rotated icon cameras. Will enable the old manual icon transform for the umbrellas!
