### ISSUE TITLE
Sentries ignore firerate

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2691]
Some weapons (e.g. the Luger and Paintball Gun) fire much faster in sentries than they can shot by players. 
This also affects some modded bolt-action and pump-action weapons in the same way, which quickly becomes overpowered.

**Comment by SDGNelson** [comment]
Sentry guns do respect fire rate, and actually use a firerate 3.3x lower than players, however for guns with the max firerate like the Luger this is very fast.
