### ISSUE TITLE
Shadowstalker Mk. II 

### ISSUE THREAD

**Issue by RamiiwasTaken** [SmartlyDressedGames/Unturned-3.x-Community#2692]
In Singleplayer if u blow yourself up with a Shadowstalker Mk. II bullet u get player kills
![Unturned 2021  07  08  10_36_20](https://user-images.githubusercontent.com/87120514/124893893-71805600-dfdb-11eb-9a78-7d88a59d1879.png)

**Comment by SDGNelson** [comment]
Indeed that seems to be the case. Unfortunately this will be tricky to patch with how that code works at the moment. Thankfully a relatively minor problem. Not sure if/when it will be fixed.
