### ISSUE TITLE
[Feature Request}

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#2694]
Is there any way of making servers that have over 24 slots to appear in the server list by default?

**Comment by Jdance-Media** [comment]
Use Preferences.json

**Comment by SDGNelson** [comment]
Jdance-Media is correct that until/unless the recommended max players is raised Show_Servers_With_Greater_Than_Recommended_Players can be changed to true in Preferences.json.
