### ISSUE TITLE
[[Request for a token for NPC]]

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#2695]
### Add an OR parameter to the conditions for example:

Response_#_Dialogue 
Response_#_Conditions 1
Response_#_Condition_0_Type Quest
Response_#_Condition_0_Logic Equal
Response_#_Condition_0_ID 41760
Response_#_Condition_0_Status Active
Response_#_Parametr OR
Response_#_Condition_0_Type Quest
Response_#_Condition_0_Logic Equal
Response_#_Condition_0_ID 41760
Response_#_Condition_0_Status Ready

**Comment by SDGNelson** [comment]
Unfortunately this is indeed a huge limitation on the NPCs right now. I do want to address it, but not sure when it will happen: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1769#issuecomment-635426956
