### ISSUE TITLE
Anti Cheat for servers

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#2697]
I think you need to make anti-cheat settings for servers. Cheaters fly with cars, They do this by use `useGravity = false` inside the vehicle rigidbody. There are plugins that do this, but I think you should come up with a free remedy for this.

Plugins:
https://missileplugins.com/store/plugin?id=212
https://missileplugins.com/store/plugin?id=227

**Comment by GazziFX** [comment]
Maybe then you can offer code so that Nelson can easy integrate it?

**Comment by fahrettinenes** [comment]
> Maybe then you can offer code so that Nelson can easy integrate it?

I don't think he need it :D He can fix most cheats with a few `if`s.

**Comment by SDGNelson** [comment]
The "anti-cheat" plugins just tighten the current built-in server tests beyond my recommendations. The recommended values will be tightened up with further netcode improvements.
