### ISSUE TITLE
Where can I find Decal templates?

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2698]
I want to use decals in Effects, I attached Decal script to my GameObject and set to my material, I use "Decal/DecalShader" shader and it looks a bit ugly. I want to use Unturned shaders "Decal/Diffuse" or "Decal/Diffuse-Alpha" but it doesn't present in example assets.

**Comment by SDGNelson** [comment]
Sorry, but decals are only supported as map objects at the moment.

**Comment by GazziFX** [comment]
But it works, can you at least publish the shader sources?
![image](https://user-images.githubusercontent.com/43498426/125536200-39b5b4dc-65ec-4374-8b8e-a9f3cbdd220c.png)

**Comment by SDGNelson** [comment]
I do not intend to support it for cases where it is not automatically generated until there is a plan for decal support with the eventual render pipelines update (URP / HDRP / built-in).
