### ISSUE TITLE
[Request] Respawn Method

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#2701]
Hey Nelson, 
It would be good if you add a properly respawn method for PlayerLife.

The current "ReceiveRespawnRequest" works, but with the Timer_Respawn Configuration

Issue Showcase: https://gyazo.com/aa3fdbe305c8c3e42087f03df6805a7a

**Comment by DiFFoZ** [comment]
Use this method to revive: https://paste.mod.gg/wahonidoli.csharp

**Comment by SDGNelson** [comment]
It looks like DiFFoZ method works as well, but sure I will add this for the next update because it is very straightforward.
