### ISSUE TITLE
[Question] Do animal bones have to stick to original hierarchy?

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2702]
Since vanilla animals have this hierarchy, where back legs come first, than the Spine, and the front legs along with the Skull are children to the Spine bone, it gets very limiting and frustrating trying to stick to this hierarchy when making custom animals, especially with some non-humanoid shapes. Can I use any hierarchy I want, with just keeping the original names for bones I want to have hitboxes (Left_Back, Spine, Skull e.t.c.) or do animals have to have exact same hierarchy as vanilla ones in order to work properly?

**Comment by SDGNelson** [comment]
It should work to use a different hierarchy and different names, however they cannot have custom damage multipliers yet. (they use the body damage)
