### ISSUE TITLE
Joining Server Issue

### ISSUE THREAD

**Issue by griffindor301** [SmartlyDressedGames/Unturned-3.x-Community#2703]
I haven't been able to join servers for awhile it either kicks me back to the main menu or completely crashes my game. Here are the logs that I think are related from client.log
```[2021-07-16 00:58:19] Unable to parse net transport tag for server "Kodak SemiVanilla #2 |5x Loot|Tpa|Maxskill|Airdrop" from "PVP,<gm>SemiVanilla</gm>,CHn,NRM,2Pp,WSn,F2P,BEy,<tn>https://gyazo.com/fdd270006512e9ce83dfbaf8055a6265.png</tn>" [2021-07-16 00:58:19] Unable to parse net transport tag for server "[US] Mythical PvP #6 |Vault|Kits|Shop|Tpa|Loot+|" from "PVP,<gm>Survival</gm>,CHn,NRM,4Pp,WSy,F2P,BEy,<tn>http://mythicalservers.net/images/mythos.png</tn>" [2021-07-16 00:58:21] Unable to parse net transport tag for server "Kodak SemiVanilla #2 |5x Loot|Tpa|Maxskill|Airdrop" from "PVP,<gm>SemiVanilla</gm>,CHn,NRM,2Pp,WSn,F2P,BEy,<tn>https://gyazo.com/fdd270006512e9ce83dfbaf8055a6265.png</tn>"```

**Comment by SDGNelson** [comment]
Is one of those the server you are trying to join? Some servers use plugins which overwrite the listing tags which prevents the correct net transport from being initialized.

**Comment by griffindor301** [comment]
Yeah this happens to my own server and i don't have anything on it changing tags it happens on every one that I have tried to join.

**Comment by SDGNelson** [comment]
What happens when you join your server? Do you get an error message on the main menu? Can you post the full Client.log please?

**Comment by griffindor301** [comment]
[Client_Prev.log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6833164/Client_Prev.log.txt)
There is no error on the main menu it typically just crashes the game

**Comment by SDGNelson** [comment]
From this log it looks like the game was closed cleanly about 1 min after starting the connection. Did it crash in this case, or did you close the game?
