### ISSUE TITLE
teleportation after force removing player out of the car not working.

### ISSUE THREAD

**Issue by wsmajt** [SmartlyDressedGames/Unturned-3.x-Community#2705]
[https://www.youtube.com/watch?v=iI7z-we1iuk](url)

as in the title

`VehicleManager.forceRemovePlayer(veh, uPlayer.CSteamID);
uPlayer.Player.teleportToLocationUnsafe(schoolPos, uPlayer.Player.look.yaw);`

**Comment by SDGNelson** [comment]
To do it that way the teleport would have to happen the frame after the vehicle exit "teleport" happens unfortunately, but a workaround would be to call InteractableVehicle.forceRemovePlayer and then VehicleManager.sendExitVehicle using your position instead.
