### ISSUE TITLE
[Issue] Animal Audio Source still playing after animal's death

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2707]
I tried to make a running sound for my animal, by adding a prefab with Audio Source which is turned off by default but gets turned on by Run animation and gets turned off by the end of it. It works fine, except for one thing: even after animal's death the sound is still repeating. This was unexpected since I thought that animal itself just gets removed from the game once it dies and it just spawns a ragdoll. Is there a way to fix it or perhaps implement walking sounds in some different way?

https://user-images.githubusercontent.com/59206749/126039667-532f0b29-331f-417f-b192-f8ada0815f52.mp4

**Comment by DerpyHoowes** [comment]
Also two more questions (so that I wont have to create new posts):
1) How the attack speed of an animal is defined? I thought it depends on the attack animation length, but it doesnt seem to.
2) How the detection radius of an animal is defined and is there a way to decrease or increase it?

Also getting some new animal behaviour type just like the "Ignore" type used for Cows and Pigs but which would make an animal attack player if he attacks it would be nice, because the entire reason I need to configure the detection radius is to decrease it to minimum so that the animal attacks the player only if it gets way too close. If we had this new behaviour type, this could be easier.

**Comment by SDGNelson** [comment]
Sorry, but there is not a good way to do footsteps on animals yet. It is on the roadmap and will use the moddable physics materials: https://trello.com/c/bzrWy53W/19-animal-zombie-footsteps

Attack speed uses the animation length if `Should_Play_Anims_On_Dedicated_Server true` is set on the animal asset, and there is no way to configure the detection radius yet sorry.
