### ISSUE TITLE
The player overturns the vehicle hitting its collider

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#2708]
Hello! I am the owner of one RP life server and I have been worried about one problem for a long time. It often happens that players overturn cars due to this bug. Because of this, the vehicle falls under the map or very far from the place where it was previously parked. Already a lot of players know about this bug and it's not good. How exactly they do this, I showed in the video, but in short, the player touches the transport collider.
Please sort it out, if possible
https://www.youtube.com/watch?v=pwsy95EEIIg&ab_channel=niuzmuu

**Comment by SDGNelson** [comment]
Sorry, it is annoying, but is the lesser of two evils at the moment. My hope is that we can properly resolve it once Unity's new physics engine is default. It was a tricky problem in Unreal as well actually - there we have two copies of the car collision, one for players and one for regular physics.
