### ISSUE TITLE
Feature request / Question - Change player character color, beard, face and others

### ISSUE THREAD

**Issue by Jtinha2000** [SmartlyDressedGames/Unturned-3.x-Community#2709]
I'm not sure if this is possible, but anyway:
I would like to know if there is how to change things of the player's character through a plugin, while the player is on the server or even keeping the changes for later...
-------------------------------------------------------------------------------------------------------------------------------------------------
Character character = new Character( );
Observation: I found this function but I'm not sure how to implement it in the player, like:
player.Player.Character = character; or other ways

**Comment by SDGNelson** [comment]
Sorry, but this is not currently changeable and unlikely to be added.
