### ISSUE TITLE
Fire on the territory (Through the effect)

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2710]
Welcome. I want to make a fire effect on the territory. I made an effect, showed him the config with fire. I inserted such an effect into a grenade, everything works, there is fire damage. But as soon as I spawn it through devkit, there is no fire damage, there is no fire icon at all. How can I fix this? I need to have a fire effect (Like a campfire) on the territory.

![image](https://user-images.githubusercontent.com/83378019/126070792-da4a0434-4f62-43c3-bbc6-ecb56c38ef1f.png)
![image](https://user-images.githubusercontent.com/83378019/126070784-ba7212d4-14f6-4207-972b-825663b87f61.png)

**Comment by SDGNelson** [comment]
Sorry, but the temperature is not expected to be used that way at the moment. It might be interesting to add though.

**Comment by JorelDecker** [comment]
> Sorry, but the temperature is not expected to be used that way at the moment. It might be interesting to add though.

And will it be possible to do this through effecEventtHook?
