### ISSUE TITLE
[Problem with UI]

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#2713]
I created a plugin that allows you to create in-game books and scraps without being tied to a unique item. That is, the player can write something on this book and transfer it to another player.

However, I ran into a problem related to editing the pages of a book / note. The point is that you cannot delete any specific characters of the UI. You can only either completely delete all the text, or just add new characters. This causes some discomfort.

Is there anything you can do about it? 

It would be wonderful if I could access the player UI directly. For example if I could get the GameObject of a specific effect from List <EffectManager.UIEffectInstance> uiEffectInstances or something else that you could suggest.

**Start at 0:50
The actual editing of the page, where you can only erase the old text, begins at 1:20** 

https://youtu.be/oqqfThK485g?t=51

**Comment by DiFFoZ** [comment]
In TODO: https://trello.com/c/crkUBc1q/9-custom-ui

**Comment by SDGNelson** [comment]
Nice implementation! It looks like the InputField component must be resetting the Text component text once selected. DiFFoZ is correct that there is a proper long term plan for custom UIs, and I do not intend to add more APIs for the existing uGUI workarounds, but it seems reasonable to also check for InputField in `sendUIEffectText` to fix this.

**Comment by SDGNelson** [comment]
Changed for the next update!
