### ISSUE TITLE
(Custom Weather) Custom Weather particles and sound not working.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2714]
I've set up a custom weather for a map, and it largely does what is desired, but it does not play sound or produce the particles needed for the weather.
Here it is:

"Metadata"
{
	"GUID" "d241cb77e1f44fabad8c7226568231c6"
	"Type" "SDG.Unturned.WeatherAsset, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
}
"Asset"
{
	"Volume_Mask" "1"
	"Fade_In_Duration" "25.0"
	"Fade_Out_Duration" "15.0"
	"Water_Per_Second" "-0.095"
	"Override_Fog" "true"
	"Override_Atmospheric_Fog" "true"
	"Shadow_Strength_Multiplier" "0.15"
	"Fog_Blend_Exponent" "1.25"
	"Cloud_Blend_Exponent" "1"
	"Wind_Main" "1.5"
	"Dawn"
	{
		"Fog_Color"
		{
			"R" "161"
			"G" "123"
			"B" "84"
		}
		"Fog_Density" "1.0"
		"Brightness_Multiplier" "0.8"
	}
	"Midday"
	{
		"Fog_Color"
		{
			"R" "148"
			"G" "108"
			"B" "65"
		}
		"Fog_Density" "1.0"
		"Brightness_Multiplier" "0.8"
	}
	"Dusk"
	{
		"Fog_Color"
		{
			"R" "128"
			"G" "95"
			"B" "61"
		}
		"Fog_Density" "1.0"
	}
	"Midnight"
	{
		"Fog_Color"
		{
			"R" "51"
			"G" "42"
			"B" "33"
		}
		"Fog_Density" "1.0"
		"Brightness_Multiplier" "0.8"
	}
	"Effects"
	[
		{
			"Prefab" "Effects/Weather/DefaultRainParticles.prefab"
			"Emission_Exponent" "2.0"
			"Pitch" "75.0"
			"Translate_With_View" "true"
			"Rotate_Yaw_With_Wind" "true"
		}
	]
	"Ambient_Audio_Clip" "Effects/Weather/DefaultSnowAmbience.mp3"
}

**Comment by SDGNelson** [comment]
By default those paths use the closest asset bundle up the hierarchy, so you probably want:
```
"Ambient_Audio_Clip" 
{
    "MasterBundle" "core.masterbundle"
    "AssetPath" "Effects/Weather/DefaultSnowAmbience.mp3"
}
```

**Comment by INeedHelp225** [comment]
Thanks! That cleared up the issue.
