### ISSUE TITLE
Troubles with custom vehicle

### ISSUE THREAD

**Issue by kotyaraaa** [SmartlyDressedGames/Unturned-3.x-Community#2715]
I made a modded vehicle. The problem is that its turret does not turn black when the vihicle is destroyed despite they use same material and texture. Also there is problem with engine sounds. When i spawn the vehicle the engine sound is playing (entering and leaving car cures it until i re-join the map near this vehicle). So is there some way to fix it?

**Comment by SDGNelson** [comment]
When the vehicle is destroyed it looks for Model_# as children of the turret pitch and yaw transforms to darken. Currently the engine audio should be set to 0 volume in Unity and the game updates it later.
