### ISSUE TITLE
Suggesting features that slows down player movement for servers

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2718]
### DISCLAIMER: Hear me out & take this issue with a grain of salt, because some of the stuff mentioned here are based on my opinion & ideas which not everyone would agree on. Also sorry if this issue too long, especially at the end, as it may look like a small rant so bear with me at the end.

- There should be server configurations to slow down the movement of players. They should, at the very least, slow down the stance changes such as slowing down the animation length & have the option to add more delay to the seconds that sends inputs to change stance.
- 
- Because slowing down stance changing animations wouldn't really affect faster players who rely too much on movement, there should be a pseudo-momentum part of the stance changing that slows players down to a hard-capped amount of seconds compared to the animation length of the stance changing. This should only occur when changing stance & the player speed when changing stances can be optionally a setting or a hardcoded amount. As for it to be a default option can be an on or off setting.
- 
- Jumping movement should also be configurable for the server, one thing I can think of that is a must-have is jumping delay settings to discourage bunny-hopping. Another must-have for this to work effectively is to add another pseudo-momentum system where in the player cannot change direction mid-air to prevent jump strafes. It can be a server option or not to have this on or off.

Why am I suggesting this? Well, just like most of my issues I submitted here, they are for reasons that people can find useful. These suggested features can help server hosts prevent players to use gameplay features (or sometimes limitations) that make them very mobile for servers that prefer to have slower gameplay or just have very little focus on the PvP aspect. Because I expect most of the playerbase of Unturned to be against my suggestion if they were to be a hardcoded feature, I decided to make the suggestions an on & off option for server configurations.

Although, a reason why I find this to be game-changing for certain servers is because server hosts would finally have options to encourage other aspects than moving as fast as possible to win every encounter, or to make it so that some servers that don't focus on fast-paced aspects limit it to almost none. I find it that Unturned has all these fast movements that make it more like a fast-paced PvP genre of a game, making the survival aspect of the game sadly the secondary focus of the game as it is not true anymore because there would be players that use a lot of the movement that the game has currently. So having these would benefit a lot for many servers that don't have fast-paced PvP as their primary focus.

Anyway, there are players, especially popular ones, that also take advantage of the speed in this game. I feel like they would be against my suggestion if these features were hardcoded to the game, so them being a setting would be better for people divided about the game's movement. But honestly, I hope there can be more ways to change player settings in servers so that the fast-paced PvP aspect can be toned down more. No hard feelings for you all, this is for the other side of the community that just want a different experience that isn't entirely focused around fast-paced PvP.

_If you have read all the way to the end to see this, thank you for sticking around. I just wanted to suggest & share an honest issue. Have a great day :)_

**Comment by TH3AL3X** [comment]
I think i can do a plugin for that, i will try...

**Comment by TH3AL3X** [comment]
It works perfectly, but you should implement if you have the ability to jump that does not block that you have more jump, since it is by default at 2. https://github.com/TH3AL3X/AntiBunnyHop/releases/tag/0.0.0.0

**Comment by Ongjming** [comment]
I was wondering if there could be some line on the .dat file that could alter player's movement speed as well.
Currently increasing the movement skill "Exercise" makes your character goes faster than the default. Then there is the recent level overwrite for max skill level.
If the .dat line on clothes/consumables could somehow boost/reduce whatever the "Exercise" skill is affecting when worn/for fixed period of time on consumption, or that it could cap the max skill level of "Exercise" when worn/for fixed period of time on consumption, then it could be great for movement speed modifying. (Without a hard serverwide cap)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
