### ISSUE TITLE
NPC Global Hook

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2719]
Can someone explain how the new Global NPC event hook works?

**Comment by iBowie** [comment]
Reward of type 'Event' triggers hooks by ID

Example of this reward that will trigger hooks with ID 'test'

`Reward_0_Type Event
Reward_0_ID test`

**Comment by SDGNelson** [comment]
Sorry for my delay. Thanks iBowie!
