### ISSUE TITLE
Linux Workshop Uploading

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#2720]
![image](https://user-images.githubusercontent.com/65422793/126726286-5637d3db-0494-4b77-8a22-fd8449eeeb7f.png)

Game dont have permissions for self path

**Comment by FANYPLAYRU** [comment]
![image](https://user-images.githubusercontent.com/65422793/126726832-5b8e76d9-797c-45f7-a708-6c7014e0bd29.png)
Dont see other disks in PC

DIsk mounted and Steam use this disks

![image](https://user-images.githubusercontent.com/65422793/126726894-ea71b56e-519a-4661-8f73-858764dba217.png)

**Comment by SDGNelson** [comment]
The game simply uses the .NET built-in IO methods e.g. Directory.Exists for those. I am not sure why it would not be working. I am not particularly familiar with the intricacies of Linux file permissions, but perhaps the application needs more permissions to be able to read/write the other disk and that path?

**Comment by FANYPLAYRU** [comment]
After the post, I issued all the permissions that I could and it did not give any result. 

As a result, I just installed Windows 11
