### ISSUE TITLE
Sound problem in custom map.

### ISSUE THREAD

**Issue by DomingoTapita** [SmartlyDressedGames/Unturned-3.x-Community#2721]
Hi, I have created a map for my server. When loading the map on the server, the sounds of weapons, cars, blows, footsteps and all kinds of sounds from objects and vehicles are not reproduced. Only the ambient sound that I have on the map is reproduced.

https://streamable.com/zj6sqn

I thought it was my problem, but the same thing happened to my friend too. When uploading the map to the server this problem happens, but not in singleplayer.

RocketLog: 

[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6873093/Rocket.log)

**Comment by Jdance-Media** [comment]
Hey DomingoTapita,

I watched the video and I see what you are talking about. When you create a new map and play on it in singleplayer does audio work on it?
The issue could also be coming from an object or something you placed that is interfering with the audio file. Remember to not place "Barricades" and "Structures" as they really shouldn't be on the map, you can disable these in the object browser filter by unchecking them.

**Comment by DomingoTapita** [comment]
When I create another map or play a vanilla, the sound plays without any problem. I guess it will be some object problem as you said

**Comment by SDGNelson** [comment]
Sorry for my delay. The most likely reason is that there are too many sounds playing at the same time. If there are any objects with audio sources nearby it may be worth checking those. Otherwise if you can send the Client.log after it happens in multiplayer there might be an error logged.
