### ISSUE TITLE
[Question/Feature Request] Landscape Hole Volume but with Objects?

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2722]
As most of you know the Landscape Hole Volume allows you to cut holes right into the land for making mines, basements, secret bunkers, and many more underground things, but what if we were to be able to cut thru mesh on objects? I have no idea if this is possible or not, but it would help if we wanted to cut thru like a barrier of some sorts.

**Comment by SDGNelson** [comment]
Sorry, but this is very unlikely to happen for meshes. It would require support for [constructive solid geometry (CSG)](https://en.wikipedia.org/wiki/Constructive_solid_geometry)
