### ISSUE TITLE
Send chat messages with Enter key

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2723]
Currently, players can only send messages with the Return key. Some keyboard setups can make sending chat messages more complicated than it should be. Additionally, not ever keyboard device has a Return key.

Having both keys work identically would be ideal. Alternatively, the "send message" function could be made configurable from the Controls menu.

**Comment by SDGNelson** [comment]
Interesting point. I suppose a GUI button to send could be added. The limiting factor with key bindings here is IMGUI+uGUI+? support.

**Comment by SDGNelson** [comment]
Added the UI button for the next update! Hopefully a hotkey will be possible later down the line.
