### ISSUE TITLE
(Russia Question) How were the MK2 & Soulcrystal quests made?

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2724]
Been wondering for a time how the MK2 and Soulcrystal Russia quests were made. There's nothing in the editor to suggest them to be special in a devkit-altered way, nor in the files. Tried using the Anastasia chamber door and soul crystals in another world, attempting to make a similar easter egg questline for a workshop map, but find they do not work. 
How come the Anastasia door works in Russia, the soul crystal absorb souls, and the lab soul crystal teleport the player? 
Thank you.

**Comment by SDGNelson** [comment]
Unfortunately they are hardcoded for Russia. Over time their features have been made more generic e.g. the TextChatEvent component, but the area teleporter and area kill detector are still hardcoded.
