### ISSUE TITLE
ClientTextChatMessenger Bug

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#2726]
![image](https://user-images.githubusercontent.com/17795973/127204466-e170b570-dff3-4cd1-8d57-d5628aa5019f.png)

Inside the ClientTextChatMessenger script, it says that 'Only nearby players will see the message.' when set to local. I tested in my server and found out that though the message state [Area] seems to display globally. For example in the picture above, my friend is in Jhavesk and I am in Silo 22, both players seem to send the message despite being very far away from each other. Is this supposed to happen? I have no idea how it works, is there a distance parameter for the script?

**Comment by SDGNelson** [comment]
Hmm the range is the same as if the player had sent a local message (128m), but I will double-check what is going on here.

**Comment by SMDIndomitable** [comment]
Another question I would like to ask is if you're planning to make a hook for synchronizing between client and server? The client text chat and Textchathook seem to do the trick, but it just doesn't feel right using it xD.

**Comment by SDGNelson** [comment]
Like events specifically for mods to message back and forth between client and server?

**Comment by SMDIndomitable** [comment]
Nope, is for synchronizing animations that involve colliders. For example, this is something I made. 
https://youtu.be/onI3a65ohoE?t=10
(Just need to watch for a few seconds)
When the animation is played, the colliders are rotated so it is able to "stand" on the ground. However this animation is not synchronized on the server, hence when the clip object takes over for collision, the vehicle will sink to the ground. A friend of mine called Alex introduced me to the Client text chat messenger and the text hook which made it possible for the clip to play the animation for synchronizing the colliders. I personally think that this feature would make modding a lot more interesting. Also, is it possible to add more buttons for vehicles other than headlights and sirens? 

I know you're busy, hence these are just some thoughts of mine. Thank you so much for the amazing game!

**Comment by SDGNelson** [comment]
Impressive turret! If the animation is triggered by something synchronized (e.g. "sirens") then it will be synchronized-ish, but there needs to be a more general purpose way to identify objects over the network before there can be general purpose networked components. Most likely some root game objects like vehicles and barricades will be assigned an ID, and then a combination of ID + relative transform name path can be automatically found. That would allow infinite buttons as well. It is on my radar, and the next update's barricade+structure net id rewrite is a step in that direction.

**Comment by SDGNelson** [comment]
Checked into it and think the local/area chat is working as expected, but looking again at your server console it appears both players are actually **sending** the chat message. Is that intentional? It would explain why you are both seeing it.

**Comment by SMDIndomitable** [comment]
Nope, is not intentional. I used the Client text chat messenger to send a chat message and set it to local, but somehow even if the player is very far away from the other, the Clientextchat messenger seems to trigger for both players.  So it feels like the local and global doesn't make a difference

**Comment by SDGNelson** [comment]
To clarify: local vs global affects who **receives** the message, not who **sends** it. So if it is triggered on both clients then both are sending it.
