### ISSUE TITLE
[Bug] Setting vehicle life, fuel, and battery

### ISSUE THREAD

**Issue by 01-Feli** [SmartlyDressedGames/Unturned-3.x-Community#2728]
Some users of my plugin OnlineVehicles and VirtualGarage
When i spawn the vehicle and i send to it a determinated life, fuel and battery but they are having a problem, the values that i send to the vehicle arent sending but when i enter the vehicle and start using it the fuel goes to the correct value but the life and battery stays the same.

I tried using: 
VehicleManager.ReceiveVehicleHealth and VehicleManager.sendVehicleHealth
VehicleManager.ReceiveVehicleFuel and VehicleManager.sendVehicleFuel
VehicleManager.ReceiveVehicleBatteryCharge and VehicleManager.sendVehicleBatteryCharge

This was working before but some days ago i got this report form the users

**Comment by DiFFoZ** [comment]
use method `VehicleManager.SpawnVehicleV3(VehicleAsset asset, ushort skinID, ushort mythicID, float roadPosition, Vector3 point, Quaternion angle, bool sirens, bool blimp, bool headlights, bool taillights, ushort fuel, ushort health, ushort batteryCharge, CSteamID owner, CSteamID group, bool locked, byte[][] turrets, byte tireAliveMask)`

**Comment by 01-Feli** [comment]
Okey i will try that

**Comment by 01-Feli** [comment]
But shouldnt the other methods works ?

**Comment by SDGNelson** [comment]
To modify the spawned values DiFFoZ (thanks!) method is the best option. To modify the values after spawning is inconsistent (sorry for all the cruft), but if you look in those methods you listed with a tool like dnspy it should be more apparent.

**Comment by 01-Feli** [comment]
Okey
