### ISSUE TITLE
Plug-in problem

### ISSUE THREAD

**Issue by Night-Matt** [SmartlyDressedGames/Unturned-3.x-Community#2730]
Hello, Nelson, I am a plug-in author. I have some difficulties in writing plug-ins. I want to ask you for help. The difficulty is that I use the onPluginKeyTick field of the class "PlayerInput" to monitor the keyboard strokes of players. Is this correct? And is the key of each key on this keyboard the same as the key code on the network?

**Comment by SDGNelson** [comment]
The `key` passed to that function is an index [0, 5), not directly related to a keycode because it can be rebound by the client. The intention is that your feature can display them in the UI with the token "<plugin_#/>" and it will show the appropriate hotkey.
