### ISSUE TITLE
[Bug] Player movement not registering

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2731]
Hello, I made a custom gamemade using a plugin to make it so players can be teleported into battle easily. Every time a player respawns they will be teleported back to their teams spawnpoint, but the issue is that for some players there's visual glitches.

Players that have the glitch will see the rest of the players frozen at the spawnpoint on their screen, any weapon actions are shown on their screen, but any movement is not registered. This could be a bug involving too many players being teleported at a time which creates the bug. I could not find a good enough fix for this glitch and it's rare-ish.

**Comment by SDGNelson** [comment]
When are you doing the teleport? From your description I think PlayerLife.OnSelectingRespawnPoint would be the safest to avoid problems.

**Comment by Jdance-Media** [comment]
Hey Nelson, I use PlayerLife.OnSelectingRespawnPoint to bring the player back to the lobby for the game, after 6 seconds or so they are teleported back into the Arena. We needed this to stop players from constantly spam attacking.

**Comment by SDGNelson** [comment]
Hmm... I trust you are not patching `PlayerMovement.updates` nor `PlayerManager`? It sounds like the affected clients are not receiving other players position (sent by that code mentioned), but there is nothing conditional there that would stop sending them.

**Comment by Jdance-Media** [comment]
I am not patching anything, the plugin is running on the server with LDM and OpenMod installed. Others have told me that they have had the same issue in the past with their plugins. It seems to be an issue with the game not keeping up with so many positions changing at once.

**Comment by SDGNelson** [comment]
That is an interesting point, I will add some logging to see if something is overflowing there, but it should catch up. How many players do you have online simultaneously?

**Comment by Jdance-Media** [comment]
Well we can get almost a full server at times (24 players) and it happens more then. Players have to rejoin to fix the bug most of the time. I've gotten a lot of complaints in the past, but I just say it's their computer not catching up, because it's never happened for some.

**Comment by SDGNelson** [comment]
In today's update there is now a warning if movement gets clogged up on the server-side, so we will see if it is that. Nothing came to mind on the client side but I would like to rewrite that code to use the the newer netcode soon anyway.

**Comment by Jdance-Media** [comment]
Alright thank you! I'll try and test it sometime.
