### ISSUE TITLE
UI button to change chat mode

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2734]
It would make sense to implement a straightforward QoL feature of letting players switch between World/Area/Group chat mode by clicking on the chat mode UI element (e.g., **[World]**). This would just be a quality-of-life addition, as unlike the Return key all the relevant inputs are configurable, and every keyboard configuration should already have the necessary tools to switch chat mode.

This quality-of-life suggestion would allow people to change chat mode without having to consider three/four different keys, and it lets people change chat mode after already having typed their message in the chat box.

Additionally, @PandahutMiku voiced their opinions on the recent chat change regarding the placement of the "Send Message" button. https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2717#issuecomment-890123668. If graphical design is a concern, having it horizontally aligned with the scrollbar (or the scrollbar aligned with the send message button) would likely look better.

**Comment by SDGNelson** [comment]
Makes sense, will do as part of revising the send button.
