### ISSUE TITLE
Requesting option to disable ADS offset when sights are removed

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#2735]
**Hey Nelson!**
Yes this has already reported in: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2376

However, I am simply asking for a clarification. Why does adding `Hook_Sight` to a gun's .dat file move the sight camera away from the already designated camera position using `Sight` in the gun's `Item`?

`Sight` as positioned in the gun's `Item`
![image](https://user-images.githubusercontent.com/70017362/127845469-b7ccc7c2-3b3f-49e3-90c8-2346a58811b1.png)

**No** `Hook_Sight` present in the .dat, Works perfectly and is aligned with the gun's `Sight`
![image](https://user-images.githubusercontent.com/70017362/127845661-5a8a27f7-c0d0-4b4e-a3dd-6797ed7ac7f5.png)

`Hook_Sight` is present in the .dat, Sight picture is miss-aligned with the gun's `Sight`
![image](https://user-images.githubusercontent.com/70017362/127845689-32e05541-e4b6-4aa3-b7b4-911bad6351c9.png)

Could you explain the benefit of moving the sight picture away from the gun's already set `Sight`? (Or perhaps this is a bug?) I find it very confusing and annoying that I would require to use an additional sight attachment to correct this. Thank you in advance!

**Comment by SDGNelson** [comment]
The reason there is a hardcoded offset when the gun supports sight attachments (Hook_Sight) but does not have a sight attached is because all of the vanilla rifles allow the iron sights to be removed. It might make sense to add an option to disable this.

**Comment by Dumfoozler** [comment]
I think you would be able to navigate around this by using the View prefab to your gun and lining it up exactly where you would like to aim down sight. When present, sight will only determine where the attachments mount, and view will determine where you aim down sight.

**Comment by Gamingtoday093** [comment]
> I think you would be able to navigate around this by using the View prefab to your gun and lining it up exactly where you would like to aim down sight. When present, sight will only determine where the attachments mount, and view will determine where you aim down sight.

Hey that Worked! Thanks!
