### ISSUE TITLE
Unturned Crash

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#2736]
Hello, I got a friend whose game is crashing constantly I will attach the error log
[error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6916403/error.log)

**Comment by SDGNelson** [comment]
Sorry for the trouble. It looks like they are probably running out of memory. I would recommend either temporarily unsubscribing from workshop files not in use, or disabling them in Menu > Workshop > Manage Subscriptions. The reason unsubscribing might be preferable is if any of the workshop files are being used by the server they are joining.

For any further help I would ask your friend to please email support@smartlydressedgames.com that way I can ask for other crash files if necessary.
