### ISSUE TITLE
CommandAdmin gives admin to the random people

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2737]
When using command `/admin` without steamId parameter, it gives admin to the random people.

I think it's possible to reproduce it with 2 players

Edit: looks like it choose the first connected player.

Also, maybe add check or ignore in `CommandUnadmin` that player is not admin.

**Comment by SDGNelson** [comment]
It looks like that does not check whether the string is empty, so I will change that. And I will change unadmin to not send the update if the player is already not an admin, though that should not have any negative side effects.
