### ISSUE TITLE
A backpack with a skinned mesh render disappears

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2742]
![image](https://user-images.githubusercontent.com/83378019/128380344-a6a92a0d-730a-4a03-bfa7-12b024152b25.png)
When I put on a backpack, it just disappears, it is the model that disappears. Other models that are not Skinned mesh render are visible

**Comment by JorelDecker** [comment]
> The cloth might be falling out of view, if you try disabling the Cloth component is it visible?

Yes, if I turn off the fabric, it is visible in unity, there is no one in the game

The lods are configured

**Comment by SDGNelson** [comment]
Sorry, not sure what else to suggest in that case. Most Unturned items are non-skinned meshes.
