### ISSUE TITLE
[Feature Request] Weapon that restores health

### ISSUE THREAD

**Issue by prank0011** [SmartlyDressedGames/Unturned-3.x-Community#2745]
Current guns heal broken bones and bleeding, but do not restore health.Hopefully this will be added to the game, preferably with a range of healers like a rocket.

**Comment by Ongjming** [comment]
Adding onto this, was wondering if the game read lines with -negative values.
Like Player_Damage -10 would heal them for 10 hp.

**Comment by prank0011** [comment]
> Adding onto this, was wondering if the game read lines with -negative values.
> Like Player_Damage -10 would heal them for 10 hp.

At present, weapon damage cannot be negative.

**Comment by prank0011** [comment]
> Adding onto this, was wondering if the game read lines with -negative values.
> Like Player_Damage -10 would heal them for 10 hp.

At present, weapon damage cannot be filled in negative value.

**Comment by Jdance-Media** [comment]
Yes indeed, weapons cannot be filled with a negative value. It works using plugins however.

**Comment by SDGNelson** [comment]
Checked into this a little bit and there are a few places it expects damage to be positive. It could be an interesting change though.

**Comment by prank0011** [comment]
> Checked into this a little bit and there are a few places it expects damage to be positive. It could be an interesting change though.
Er... I don't know what you're saying, are you saying there's a way to make a weapon that restores health?

**Comment by SDGNelson** [comment]
> Er... I don't know what you're saying, are you saying there's a way to make a weapon that restores health?

Sorry, no, there is not yet an option for it.

**Comment by prank0011** [comment]
> > Er... I don't know what you're saying, are you saying there's a way to make a weapon that restores health?
> 
> Sorry, no, there is not yet an option for it.

My English is poor.
I hope you can include this option in your plan.

**Comment by Jtinha2000** [comment]
### A fast plugin for this!
**Plugin page:**

https://github.com/Jtinha2000/HealWeapon

**Configuration:**

- [ ]  Singular configuration with weapon ID
- [ ]  Heal victim with a configurable health (Opitional)
- [ ] Heal shooter with a configurable health (Opitional)
- [ ] Needed Permissions configurable (Opitional)
- [ ] Can cancel the weapon damage/effects (Opitional)
- [ ] Configurable messages (Opitional)
- [ ] Needed weapon firemode to heal (Opitional)

**Why?**

I don't know if you think of this as a Plugin, but because I'm bored and scrolling through the Unturned issue pages, I've made it here for you until Nelson doesn't add it to the game. (Yeap my english is horrible)

Att: Yeah i'm the doggu
For: @prank0011 

![download (60)](https://user-images.githubusercontent.com/77682013/128917979-248827df-760b-40f4-8771-9b8f6977ca80.jpg)

**Comment by prank0011** [comment]
> ### A fast plugin for this!
> **Plugin page:**
> 
> https://github.com/Jtinha2000/HealWeapon
> 
> **Configuration:**
> 
> * [x]   Singular configuration with weapon ID
> * [x]   Heal victim with a configurable health (Opitional)
> * [x]  Heal shooter with a configurable health (Opitional)
> * [x]  Needed Permissions configurable (Opitional)
> * [x]  Can cancel the weapon damage/effects (Opitional)
> * [x]  Configurable messages (Opitional)
> * [x]  Needed weapon firemode to heal (Opitional)
> 
> **Why?**
> 
> I don't know if you think of this as a Plugin, but because I'm bored and scrolling through the Unturned issue pages, I've made it here for you until Nelson doesn't add it to the game. (Yeap my english is horrible)
> 
> Att: Yeah i'm the doggu
> For: @prank0011
> 
> ![download (60)](https://user-images.githubusercontent.com/77682013/128917979-248827df-760b-40f4-8771-9b8f6977ca80.jpg)

Thank you very much. I don't know how to use it, but I'll download it and ask someone who knows about plug-ins.

**Comment by Jtinha2000** [comment]
> > ### A fast plugin for this!
> > **Plugin page:**
> > https://github.com/Jtinha2000/HealWeapon
> > **Configuration:**
> > 
> > * [x]    Singular configuration with weapon ID
> > * [x]    Heal victim with a configurable health (Opitional)
> > * [x]   Heal shooter with a configurable health (Opitional)
> > * [x]   Needed Permissions configurable (Opitional)
> > * [x]   Can cancel the weapon damage/effects (Opitional)
> > * [x]   Configurable messages (Opitional)
> > * [x]   Needed weapon firemode to heal (Opitional)
> > 
> > **Why?**
> > I don't know if you think of this as a Plugin, but because I'm bored and scrolling through the Unturned issue pages, I've made it here for you until Nelson doesn't add it to the game. (Yeap my english is horrible)
> > Att: Yeah i'm the doggu
> > For: @prank0011
> > ![download (60)](https://user-images.githubusercontent.com/77682013/128917979-248827df-760b-40f4-8771-9b8f6977ca80.jpg)
> 
> Thank you very much. I don't know how to use it, but I'll download it and ask someone who knows about plug-ins.

You need go there : https://github.com/Jtinha2000/HealWeapon/blob/main/HealWeapons/HealWeapons/bin/Debug/HealWeapons.dll
Download the Dll and the Libraries, and use in your rocket, like dll in server>rocket>plugins and the libraries in server>rocket>libraries

**Comment by prank0011** [comment]
> > > ### A fast plugin for this!
> > > **Plugin page:**
> > > https://github.com/Jtinha2000/HealWeapon
> > > **Configuration:**
> > > 
> > > * [x]     Singular configuration with weapon ID
> > > * [x]     Heal victim with a configurable health (Opitional)
> > > * [x]    Heal shooter with a configurable health (Opitional)
> > > * [x]    Needed Permissions configurable (Opitional)
> > > * [x]    Can cancel the weapon damage/effects (Opitional)
> > > * [x]    Configurable messages (Opitional)
> > > * [x]    Needed weapon firemode to heal (Opitional)
> > > 
> > > **Why?**
> > > I don't know if you think of this as a Plugin, but because I'm bored and scrolling through the Unturned issue pages, I've made it here for you until Nelson doesn't add it to the game. (Yeap my english is horrible)
> > > Att: Yeah i'm the doggu
> > > For: @prank0011
> > > ![download (60)](https://user-images.githubusercontent.com/77682013/128917979-248827df-760b-40f4-8771-9b8f6977ca80.jpg)
> > 
> > 
> > Thank you very much. I don't know how to use it, but I'll download it and ask someone who knows about plug-ins.
> 
> You need go there : https://github.com/Jtinha2000/HealWeapon/blob/main/HealWeapons/HealWeapons/bin/Debug/HealWeapons.dll
> Download the Dll and the Libraries, and use in your rocket, like dll in server>rocket>plugins and the libraries in server>rocket>libraries

Oh!! thank you very much.
