### ISSUE TITLE
[Bug] WTF is with Russia acting up

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2749]
https://media.discordapp.net/attachments/859922243761078323/873552976348844052/unknown.png

The picture shown above shows map spawns moving with the editor camera and being on a slant, I have no idea how and why this happened. I placed another safezone with a boat out near the liberator and when I went into the game a random zone in between Novobrisk and all of Moscow was a safezone.

**Comment by SDGNelson** [comment]
If you can send the Client.log after opening the map there might be an exception, or if you can send the zipped map to my email I can load it up to try and reproduce.

**Comment by Jdance-Media** [comment]
Alright I figured out that it was another version of the map on my workshop, but the safezone stuff was before that too. Confusing.

**Comment by Jdance-Media** [comment]
Alright, I haven't see any problems since and I started the game too many times so I lost the .log files, but if something comes up I'll notify you. I had issues with safezones randomly appearing around the map when it's not there in the editor and this was when I was unsubbed to my map.

**Comment by SDGNelson** [comment]
Glad to hear you got it sorted out!
