### ISSUE TITLE
How was this created? 

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2750]
![image](https://user-images.githubusercontent.com/83378019/128610032-5ed36244-b8ad-4071-b482-8a5aa9f7806b.png)
![image](https://user-images.githubusercontent.com/83378019/128610040-c9d8a169-5a34-422e-8602-faa787b5d267.png)
How was this created? When fired, the shutter is pulled back

**Comment by JorelDecker** [comment]
I know you have plans for this implementation, but someone has already done it without updating

**Comment by SDGNelson** [comment]
Dug and Toothy Deerryte told me yesterday about this, but mentioned that they heard about it from someone else on a modding Discord. They created the gun animations in Unity's animation editor with the Item prefab parented under Right_Hook, and named the Item prefab according to its ID. This works because Unity's animation component looks for the transforms by name.

**Comment by JorelDecker** [comment]
> Dug and Toothy Deerryte told me yesterday about this, but mentioned that they heard about it from someone else on a modding Discord. They created the gun animations in Unity's animation editor with the Item prefab parented under Right_Hook, and named the Item prefab according to its ID. This works because Unity's animation component looks for the transforms by name.

Can you explain in more detail how?

**Comment by SDGNelson** [comment]
For example if the gun's ID was 42 they would create a Unity animation clip with the Item.prefab renamed to "42" and parented under the Right_Hook transform, and then any of the item's transforms can be manipulated as part of the animation clip.

**Comment by prank0011** [comment]
I can't understand how it was done, but whoever came up with it was amazing.

**Comment by prank0011** [comment]
OK, I will. The key is to grow multiple bones in the Right_Hook in Blender, and add corresponding subitems in the project file of Item. Others are made according to normal firearms mod process.
[``](![1](https://user-images.githubusercontent.com/68633558/128629465-2d5392d7-9a1a-4dc3-8ed9-84617c144a36.png)
![2](https://user-images.githubusercontent.com/68633558/128629466-7b56287c-47e8-411c-8b4e-7819192a7d2f.png)
)

**Comment by JorelDecker** [comment]
> OK, I will. The key is to grow multiple bones in the Right_Hook in Blender, and add corresponding subitems in the project file of Item. Others are made according to normal firearms mod process.
> [``](![1](https://user-images.githubusercontent.com/68633558/128629465-2d5392d7-9a1a-4dc3-8ed9-84617c144a36.png)
> ![2](https://user-images.githubusercontent.com/68633558/128629466-7b56287c-47e8-411c-8b4e-7819192a7d2f.png)
> )

If you succeeded, can you send me an example?
If you can come here Inglorious Bastard#1488

**Comment by prank0011** [comment]
> > OK, I will. The key is to grow multiple bones in the Right_Hook in Blender, and add corresponding subitems in the project file of Item. Others are made according to normal firearms mod process.
> > [``](![1](https://user-images.githubusercontent.com/68633558/128629465-2d5392d7-9a1a-4dc3-8ed9-84617c144a36.png)
> > ![2](https://user-images.githubusercontent.com/68633558/128629466-7b56287c-47e8-411c-8b4e-7819192a7d2f.png)
> > )
> 
> If you succeeded, can you send me an example?
> If you can come here Inglorious Bastard#1488

This is an example of success. .

**Comment by JorelDecker** [comment]
> > > OK, I will. The key is to grow multiple bones in the Right_Hook in Blender, and add corresponding subitems in the project file of Item. Others are made according to normal firearms mod process.
> > > [``](![1](https://user-images.githubusercontent.com/68633558/128629465-2d5392d7-9a1a-4dc3-8ed9-84617c144a36.png)
> > > ![2](https://user-images.githubusercontent.com/68633558/128629466-7b56287c-47e8-411c-8b4e-7819192a7d2f.png)
> > > )
> > 
> > 
> > If you succeeded, can you send me an example?
> > If you can come here Inglorious Bastard#1488
> 
> This is an example of success. .

When I do the same, my weapons turn 90 degrees. And not only the models, but all the components
![image](https://user-images.githubusercontent.com/83378019/128633975-a8061cfb-eb4d-4959-be02-2a6d4523a65d.png)

**Comment by JorelDecker** [comment]
> > > OK, I will. The key is to grow multiple bones in the Right_Hook in Blender, and add corresponding subitems in the project file of Item. Others are made according to normal firearms mod process.
> > > [``](![1](https://user-images.githubusercontent.com/68633558/128629465-2d5392d7-9a1a-4dc3-8ed9-84617c144a36.png)
> > > ![2](https://user-images.githubusercontent.com/68633558/128629466-7b56287c-47e8-411c-8b4e-7819192a7d2f.png)
> > > )
> > 
> > 
> > If you succeeded, can you send me an example?
> > If you can come here Inglorious Bastard#1488
> 
> This is an example of success. .

![image](https://user-images.githubusercontent.com/83378019/128633994-d22d4ab2-ee0d-4680-8673-019aa0d4ee65.png)
![image](https://user-images.githubusercontent.com/83378019/128634005-d69e0606-f3d1-470a-881a-15dbbbdf2428.png)

**Comment by prank0011** [comment]
You can rotate ID's skeleton by 90 degrees and then make the action. Because the project file for item has been rotated -90 degrees on the X axis.
