### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2752]
when crafting anything more than 40-ish, it lags my game for like 3 or 4 seconds and you can only craft 64 items at a time.
also you cant fire when you were sprinting, but try to shoot as you stop sprinting when you are done sprinting it still does not fire, same applies to aiming

**Comment by SDGNelson** [comment]
The first is an optimization issue that could be addressed when I get the chance to rewrite some of the inventory code. And the second would be a nice input improvement, but no ETA. Maybe as part of the input/movement rewrites planned.
