### ISSUE TITLE
[QoL Feature Request] Devkit Save Checkbox to Filter

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2753]
Currently when saving your map and having .unity3d mods installed the save tab (DevKit) has the .unity3d assets and the map save checked. When saving the map with the assets checked it interferes with the assets making them broken for some people. I propose that a checkbox is added to filter out any save files that are not related to the map.

Along with that when saving with those .unity3d assets checked it makes a .asset file for each of them, and those are not deleted when unsubscribing from the mods. This makes people think that their game is broken or that their computer cannot work with Unturned.

**Comment by SDGNelson** [comment]
It sounds like it thinks the .unity3d assets are dirty and need saving. Do you know an example asset type? Or could you send me one of the assets that is improperly dirty please?

**Comment by Jdance-Media** [comment]
Hey, I'll recreate one in an hour. These dirty assets sometimes show up as
backpacks ingame??? Must be from pento's or something

**Comment by Jdance-Media** [comment]
Alright I checked this one off in the devkit and it made a .asset for em.

`"Metadata"
{
	"GUID" "924e5342b37c490592cd7396174d2ff6"
	"Type" "SDG.Unturned.VehicleAsset, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
}
"Asset"
{
	"ID" "36030"
}`

This is the .dat file for it too, the funny part is that this isn't even unity3d this time. It's using a masterbundle format.

GUID bb4625d972b342f382b2074aa5dc56e5
Type Vehicle
Rarity Common
ID 36030

Physics_Profile dd5b9ad652da4e61b76a946d6365878a
Fuel_Burn_Rate 1.4

Speed_Min -6
Speed_Max 22

Steer_Min 18
Steer_Max 30

Brake 28

Fuel_Min 200
Fuel_Max 400
Fuel 950

Health_Min 350
Health_Max 450
Health 650

Cam_Passenger_Offset -0.05

Trunk_Storage_X 3
Trunk_Storage_Y 3

Explosion 20

Bumper_Invulnerable
Valid_Speed_Horizontal 60

**Comment by SDGNelson** [comment]
From this pack? https://steamcommunity.com/sharedfiles/filedetails/?id=2365700338
I will try installing it and see if the bug happens. Marking "next update" so I do not forget.

**Comment by Jdance-Media** [comment]
Thanks, I have no idea why this happens at all, but it would help if there was filters for the DevKit save window that way I don't have to uncheck them all every time and so I'm not an idiot and break my assets.

**Comment by SDGNelson** [comment]
It looks like the reason is that the black mustang has a duplicate guid, so it got marked dirty. Considering that those assets cannot be properly saved by the editor anyway I have disabled marking assets dirty when they have duplicate guids for the next update.
