### ISSUE TITLE
[GLITCH] Strange POV bug on new server of mine.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#2754]
I am one of the owners and developers for a server called Uncreated Warfare. We recently rewrote our entire server, which brought a very strange bug that I've never seen before. Theres a youtube video linked below that shows many player's points of views (photos and videos). Basically they're just running around or driving and all the sudden their screen cuts to a low fov closeup of some iron sight or something. This happens to most of our players regularly, and seems to happen more as the player count rises. At the end of the video you can also see some desync that I assume is linked to this. I haven't been able to establish why it's happening, it seems so random.
[https://www.youtube.com/watch?v=HBfoilkpclw](url) (only the fades are different video clips, jump cuts are part of one clip)
I've also attached a few client logs that were sent to us by players. there's nothing in the server log to indicate any problems, but I attached a server log as well.

What seems to happen in the client logs for each player is it sends 
```
[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6952504/Rocket.log)

[2021-08-08 21:53:03] Saved item hotkeys
```
then immediately starts spamming this in FixedUpdate until the player is kicked or their game is alt-f4'd.
```
[2021-08-08 21:53:03] NullReferenceException: Object reference not set to an instance of an object
[2021-08-08 21:53:03] SDG.Unturned.Glazier_uGUI.LateUpdate () (at <febd787eb4b7412eb99c84755174c3ee>:0)

[2021-08-08 21:53:03] NullReferenceException: Object reference not set to an instance of an object
[2021-08-08 21:53:03] SDG.Unturned.Glazier_uGUI.LateUpdate () (at <febd787eb4b7412eb99c84755174c3ee>:0)

[2021-08-08 21:53:03] NullReferenceException: Object reference not set to an instance of an object
[2021-08-08 21:53:03] SDG.Unturned.Glazier_uGUI.LateUpdate () (at <febd787eb4b7412eb99c84755174c3ee>:0)

[2021-08-08 21:53:03] NullReferenceException: Object reference not set to an instance of an object
[2021-08-08 21:53:03] SDG.Unturned.Glazier_uGUI.LateUpdate () (at <febd787eb4b7412eb99c84755174c3ee>:0)
```
Any help would be appreciated as I have no clue where to go from here.
[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6952505/Rocket.log) // server log
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6952507/Client.log)    // one hour behind server
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6952509/Client_Prev.log)  // one hour behind server
[Client2.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6952511/Client2.log) // same tz as server (not in the same session as the server log above)
[Client1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6952518/Client1.log) // 2 hrs behind server

**Comment by SDGNelson** [comment]
Since they all seem to happen with that particular iron sight, can you narrow down which iron sight has that shape? Some mods attach Cameras with special depth or render target setups, so perhaps one of those is getting activated at the wrong time.

**Comment by DanielWillett** [comment]
![image](https://user-images.githubusercontent.com/12886600/128741154-d78bbd4c-b485-4b3b-be5b-1e678d1d4a8b.png)
You hit that right on the money, thanks for the quick reply.
He left the camera in by accident trying to line up the sign.

We are having another bug, not sure if I should create another ticket or just ask but teleporting players with `Player.teleportToLocation` is desyncing them for some people, where they see them just floating, not receiving movement but they do see them crouch, shoot, etc, just no movement, same as the last clip in the video in the other post, thought it was related but apparently not.

**Comment by DanielWillett** [comment]
Actually, scratch that the bug is still happening, the same error in log about Glazier UI. This time instead of going to the camera on the Tig-R, it just starts making the players pov more grainy, not clearing UIEffects, etc. Screenshot attached. Hand bobbing continues.

![image](https://user-images.githubusercontent.com/12886600/128751518-30eadd8d-82e4-477e-bd7b-960f1792f376.png)
![image](https://user-images.githubusercontent.com/12886600/128751743-b6c9de4b-d38b-482e-861b-08e23d0d3a6a.png)

https://user-images.githubusercontent.com/12886600/128751907-cd8767b4-aa67-463e-bbf7-ded17dc2bd44.mp4

**Comment by CyberAndrii** [comment]
```
Exception invoking SDG.Unturned.EffectManager.ReceiveUIEffect1Arg from server:
Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
```

These indexes must start from zero (1 and 3 in your case):

![image](https://user-images.githubusercontent.com/37713088/128759036-2c15116b-01e5-4702-bf20-fb4e6f3dc916.png)

**Comment by DanielWillett** [comment]
That was almost 30 seconds after it started though, it is a problem but it has been working for everyone else.

**Comment by SDGNelson** [comment]
Judging by how the UI elements become darker one of your plugins may be respawning all of the UI elements every frame. If one of the UIs is a fullscreen grainy image that would explain why it gradually gets grainier. The only thing that would throw a null reference exception in Glazier_uGUI.LateUpdate is EventSystem.current, so my guess is that the huge number of UI elements is breaking something in Unity.

**Comment by DanielWillett** [comment]
Ok, we are currently testing removing the vehicle mod we have with a lot of people on and so far we haven't had any issues, with 33 people on, is there anything you could think of in a mod that would cause this?

**Comment by DanielWillett** [comment]
Never mind, it's still happening, we aren't sending UI every frame, how much could be considered "a lot", also would the format error mentioned by CyberAndrii cause this?

**Comment by CyberAndrii** [comment]
I was able to replicate the exact result by removing myself on the client side (by calling `Provider.removePlayer(byte index)` through RPC).

It looks like `Provider.clients` array desync. I would recommend checking how your plugins handle players connecting/disconnecting.

See my code

```cs
using System;
using SDG.NetPak;
using SDG.NetTransport;
using SDG.Unturned;

public void CrashClients()
{
    for (var i = 0; i < Provider.clients.Count; i++)
    {
        // This RPC will call on client side SDG.Unturned.ClientMessageHandler_PlayerDisconnected.ReadMessage(NetPakReader reader)
        // which will call SDG.Unturned.Provider.removePlayer(byte index)

        // The original Unturned code does the opposite to my code - it sends this to everyone else except the kicking player
        SendMessageToClient(
            EClientMessage.PlayerDisconnected,
            ENetReliability.Reliable,
            Provider.clients[i].transportConnection,
            writer => writer.WriteUInt8((byte) i));
    }
}

// Same as SDG.Unturned.NetMessages.SendMessageToClient(...) but not internal
private static void SendMessageToClient(
    EClientMessage index,
    ENetReliability reliability,
    ITransportConnection transportConnectio,
    Action<NetPakWriter> callback)
{
    var writer = new NetPakWriter
    {
        buffer = Block.buffer
    };

    writer.Reset();
    writer.WriteEnum(index);
    callback(writer);
    writer.Flush();
    transportConnectio.Send(writer.buffer, writer.writeByteIndex, reliability);
}
```

**Comment by benvalkin** [comment]
After looking at what @CyberAndrii suggested, we removed all our async method calls and it seems to be working better. Not 100% sure the glitch is completely gone yet, but it hasn't occurred yet with relatively high player count

**Comment by DanielWillett** [comment]
Going to close the issue because I believe it is fixed.

**Comment by SDGNelson** [comment]
Glad to hear you sorted it out. Thanks CyberAndrii! And yes, it is not safe to call non-thread-safe methods from multi-threaded code.
