### ISSUE TITLE
Bug in BarricadeManager.onTransformRequested when shouldAllow is false

### ISSUE THREAD

**Issue by Freenex1911** [SmartlyDressedGames/Unturned-3.x-Community#2755]
I recently found a bug where a barricade disappears (or spawns completely elsewhere) when you set the referenced bool `shouldAllow `of `BarricadeManager.onTransformRequested` to false **and** the barricade is part of a vehicle. Without placing it on a vehicle everything works fine and I think it's due to the fact that you're resetting the position to the local instead of global position when `shouldAllow` is false.

```
if (!flag)
{
	point = this.serversideData.point;
	angle_x = this.serversideData.angle_x;
	angle_y = this.serversideData.angle_y;
	angle_z = this.serversideData.angle_z;
}
```
Instead it should use `this.model.position` and `this.model.eulerAngles` .

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix.

**Comment by SDGNelson** [comment]
As a temporary (or perhaps not so temporary) hack it will use the model worldspace transform in the next update. Ideally it should operate in local space in the future.
