### ISSUE TITLE
Auto-recreate cloud files in case of corruption/error reading

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2756]
Currently, some files like the Graphics.json file will auto-recreate if they are unreadable/corrupt, but other files like Characters.dat, Controls.dat, Filters.dat, won't.

Here's a player log of a player affected by this:
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6957874/Client.log)

This is particularly nasty because verifying/reinstalling unturned even reinstalling the entire PC won't fix this, since this is all synced in Steam's Cloud, it will keep syncing down corrupt files.

It would be nice if the game would just automatically recreate the defaults of all cloud-synced files if unreadable. The player is going to lose their settings either way if the file corrupted itself, this way they just don't need to manually delete them.

(ps. I'm not saying there's a new bug with unturned doing this, in this case, the user stated they had an HDD Failure and some other issues. They were just super confused as they reinstalled their entire PC, reinstalled unturned, etc, and no fix until I told them to manually delete those files)

Thanks!

**Comment by SDGNelson** [comment]
Thanks for the log! The parser knows the json file is improperly formatted so it can re-save it, but unfortunately there is no integrity information in the older binary settings files, so the game does not know something is wrong. For the meantime I will see about adding a command-line option to reset the cloud savedata, and fixing the particular exception reported in that log.

**Comment by SDGNelson** [comment]
My guess is that player's "selected character" index was out of range. This will be clamped during load in the next update.

As for a temporaryish workaround, I have also added a "-DisableSteamCloudRead" command-line flag for the next update.
