### ISSUE TITLE
getting caught on flat surfaces when trying to fall off of them

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2757]
when running of of a perfect flat surface, sometimes you get "caught" on it and have to exit sprint mode to be able to fall down
if you dont exit sprint mode it is like you are teleported back up but if you continue moving you keep falling and getting tp'd

**Comment by SDGNelson** [comment]
This happens if one of the character controller physics substeps moved the player around a corner. Unfortunately it is a necessary evil until the movement can be replaced with something custom because otherwise there are ways to force the default character controller through walls.
