### ISSUE TITLE
[FEATURE REQUEST] Shoot Animation Hook

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2759]
https://youtu.be/3IxI1Q1jkLY

As you can see, we have gotten fully animated and functioning rigged guns into the game. However, the only sad part is that as there is no actual animation for shooting, we are unable to rig the gun to hit back on every shot. If you could add something like an OnShootHook or essentially any way to have a unity trigger based on a shot in-game, we would be able to do this.

Thank you,
- Dumfoozle

**Comment by SDGNelson** [comment]
There are existing requests for this e.g. #2740 and it will happen once there is an optional prefab for equipped items, but no ETA. The reason for delay is ideally this separate prefab would be async loaded unlike the current item prefab.
