### ISSUE TITLE
if storage gets too far it doesnt let you interact, but if it gets close enough again it still doesnt

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2764]
if i am in the second seat trying to grab stuff in area inventory, car drives off and then it drives back it doesnt refresh the items in area storage

**Comment by SDGNelson** [comment]
It would make sense to update while moving, but currently it only refreshes nearby items when opening the inventory or when an item is dropped/picked up.
