### ISSUE TITLE
Storage rebuildState() optimization

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2765]
I think `rebuildState()` should not be called so often as it now.
For example if we add items.
I know that I can use `tryAddItem(Item item, bool isStateUpdatable)` and then call `onStateUpdated()` but storage 'whole state' is only necessary when we saving barricades.
So it can be replaced with `shouldRebuildState` property and then rebuild state when saving map, also I dont understand why storage contains `owner` and `group` and saves it to state if `BarricadeData` already has it.
And I think state should not be saved when `despawnWhenDestroyed` is checked, current workaround that I use in my plugins `storage.items.onStateUpdated = null;`

**Comment by SDGNelson** [comment]
The state stuff does suck, and is gradually being replaced.
