### ISSUE TITLE
Make disconnect player packet by NetId, not index of the list

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2766]
Maybe will be better todo that. I'm about a class: `ClientMessageHandler_PlayerDisconnected`

**Comment by SDGNelson** [comment]
Will probably happen at some point, but the netid stuff was not added yet when I did the messaging rewrite.

**Comment by GazziFX** [comment]
Is it stable enough?
