### ISSUE TITLE
Unturned Modules

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#2767]
I recently started getting interested in unturned modules.

But there is too little information in the unturned module.
I also watched and followed the tutorial in the link below.
https://steamcommunity.com/sharedfiles/filedetails/?id=834599848

But I don't see the Modules folder in the Workshop.

I would like to see more detailed documentation on unturned modules.

**Comment by SDGNelson** [comment]
There is some documentation here: https://steamcommunity.com/sharedfiles/filedetails/?id=790629631
The modules folder is in U3DS/Modules or Unturned/Modules
I would also recommend looking at Bundles/Sources/UnturnedExampleMod

**Comment by Blackwolf7704** [comment]
Yes. I've already looked at ExampleMod, and put Examplemod in the Modules folder in my private client, but it didn't work.

Also, I couldn't find Modules at all in the Workshop.

**Comment by SDGNelson** [comment]
Did you run with BattlEye disabled?

Modules are not available on workshop because they can contain malicious code.

**Comment by Blackwolf7704** [comment]
Yes. Executed after disabling Battle Eye.

**Comment by SDGNelson** [comment]
For a different example, Rocket (/LDM) and OpenMod both use the Modules feature.
