### ISSUE TITLE
The problem remains

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#2768]
#2687 [https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2687](url)

**Comment by hksz** [comment]
I find that the problem still exists. Why

**Comment by SDGNelson** [comment]
With that particular road model? When I checked it seemed fine after that patch but I will check again.

**Comment by baranmod** [comment]
I believe its not really related to object. I noticed similar results on landscape and it seems its related more to shooting angle. Vehicle turrets, guns sometimes don't explode on impact (like bullets going through)

**Comment by hksz** [comment]
> With that particular road model? When I checked it seemed fine after that patch but I will check again.

https://youtu.be/fgCL1VPzOHc
From the second minute onwards

**Comment by SDGNelson** [comment]
Thanks for the video! It looks like hits against the terrain and roads - specifically the spline roads between locations - are getting rejected when the server also hits the terrain or road. This should be fixed for the next update!
