### ISSUE TITLE
Add vision events

### ISSUE THREAD

**Issue by Jtinha2000** [SmartlyDressedGames/Unturned-3.x-Community#2770]
Add view events, not like NightVision/Headlamp events, but events related to when player has changed view by moving mouse for example or when the visibility changes

This can help with SCP Fundation plugins like a Peanout plugin(if you doesn't knows what is the Scp Fundation, and this example you can see this fast document: https://scp-wiki.wikidot.com/scp-173, but for resume, when you look for the Peanout he completly stops and when you stop looking he starts moving), also can be used with the visibility changes events to for give for peanout the chance to move when the lights goes off

**Comment by SDGNelson** [comment]
Considering how frequently the player's view changes it would be better to poll the player viewpoints periodically from your plugin.
