### ISSUE TITLE
Check Item durability

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#2771]
I want to get or modify the durability value of an item.
But even if I look for such a variable, it doesn't exist.

**Comment by SDGNelson** [comment]
Unturned refers to the item durability as `quality`.

**Comment by Blackwolf7704** [comment]
```
public byte durability
     {
       get => this.quality;
       set => this.quality = value;
     }

```
Looking through the code, I found that the item part of the Assembly-Chsarp file has something to do with that durability. But I don't know how to load durability.
