### ISSUE TITLE
[Feature Request] Possibility to load vanilla icons / mod images to UI images.

### ISSUE THREAD

**Issue by Cubody** [SmartlyDressedGames/Unturned-3.x-Community#2772]
I was thinking about how to make a beautiful and extensible UI that would give the best UX to the player. In the inventory, the icons are preloaded, but in the UI we have to send them by link, which makes it difficult and slows down the transfer of images. It would be very good if you implemented a method by which you can take an image from a mod(from its assets) and insert it into the UI image for the player. And also the ability to insert an icon of a vanilla object in this way.

Something like it for example for mod images:
```csharp
void RequestSetUIModImage(ulong modId, string modImageName, short uiKey, string uiImageName)
```
And for vanilla/mod items something like:
```csharp
void RequestSetUIItemIcon(ushort itemId, short uiKey, string uiImageName)
```

**Comment by Sl4vP0weR** [comment]
Steam mod Id is UInt64, not Int32.

**Comment by aviadmini** [comment]
I'd rather have an option to **reliably** preload the images, preferably during connection to server
Sadly there's plenty of mods that don't work well with Nelson's icon renderer

**Comment by Greenorine** [comment]
> I'd rather have an option to **reliably** preload the images, preferably during connection to server
> Sadly there's plenty of mods that don't work well with Nelson's icon renderer

Yep! It can be good too.

**Comment by Greenorine** [comment]
Btw in game code we have ItemTool.getIcon and it'll be good if you'll pass it on some method for load icon into UI image.

**Comment by Sl4vP0weR** [comment]
@SDGNelson, check out.

**Comment by aviadmini** [comment]
> Btw in game code we have ItemTool.getIcon and it'll be good if you'll pass it in some method for load icon into UI image.

That's the feature which some workshop items don't work well with (creators fault, not Nelson's)

**Comment by Greenorine** [comment]
> > Btw in game code we have ItemTool.getIcon and it'll be good if you'll pass it in some method for load icon into UI image.
> 
> That's the feature which some workshop items don't work well with (creators fault, not Nelson's)

Welp not really big problem but your idea is cool, I want it to be implemented too

**Comment by GazziFX** [comment]
I think it should also have skinID and itemState args

**Comment by Sl4vP0weR** [comment]
> I think it should also have skinID and itemState args

or just Item class instead

**Comment by PARTOVIY** [comment]
I support, innovation is very necessary. @SDGNelson please add!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
