### ISSUE TITLE
Barricade region on vehicle out of sync while saving: 1469

### ISSUE THREAD

**Issue by TeemoCell** [SmartlyDressedGames/Unturned-3.x-Community#2773]
![image](https://user-images.githubusercontent.com/11705513/129573377-1cc8b631-a182-4c47-8300-141760f18a37.png)

**Comment by SDGNelson** [comment]
Do you have any plugins related to barricades? Also technically this warning should not really matter anymore because the out-of-sync list is only kept for backwards compatibility.

**Comment by TeemoCell** [comment]
Yeah, i have a few plugins related barricades but i thought it's a bug from a game and since it says "Bug Nelson about this", thought it would be important.
