### ISSUE TITLE
MasterBundle and UI

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#2774]
I can't make a UI in masterbundle.

[2021-08-17 03:19:10] Failed to analyze C:\Program Files (x86)\Steam\steamapps\workshop\content\304930\2375790659/FPHUD/FPHUD.dat: Missing effect gameobject

**Comment by SDGNelson** [comment]
Does the path relative to MasterBundle.dat appended to the Asset_Prefix match your path in Unity? https://github.com/SmartlyDressedGames/U3-Docs/blob/master/AssetBundles.md

**Comment by GazziFX** [comment]
I always use MB for UIs and it works

**Comment by FANYPLAYRU** [comment]
My issue, i compilling MB in Assets/FPUI/MasterBundle/
