### ISSUE TITLE
unturned server character

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#2776]
How does the server block the multiple character slots available for Unturned Gold accounts?

ex)
Slot 1 Character A
Slot 2 Character B

When connecting as A and then as B, the account must be blocked or items must be shared.

There seems to be a file that configures it in commands.dat or config, but I can't find it.

**Comment by SDGNelson** [comment]
The option is Allow_Per_Character_Saves in Config.json, and treats all slots as slot 1.
