### ISSUE TITLE
RAM Investigation

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#278]
Continuation of the RAM improvement adventures! Cleaned up asset bundle loading stuff significantly in #266, but it's still twice as much as I thought it should be on Russia.

- Async skin loading on demand seems to make a minimal impact unfortunately.
- [x] Consolidate shaders in map asset bundles.

**Comment by AthenaDev** [comment]
I'm currently on a Mac with a good amount of RAM, so I can run Unturned, but I have friends who are on Windows with either the same amount of RAM or less and it's a painful experience for them. It seems like the rendering also causes some issues as changing settings back to Legacy versions improves their FPS, but not by much.

I'm excited to see future performance improvements like this.
