### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#2780]
So i've been working on my server's map and I needed to go from one editor to the other and now the map isn't loading, it get's stuck at like 30% I have 2000 fps and nothing is going on. Any clue on what's going on?

**Comment by 01-Feli** [comment]
Not sure but can be the same issue as i had a long time > ago. https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2631

**Comment by SDGNelson** [comment]
Can you send the map file to me at nelson@smartlydressedgames.com please? I will load it up and see what is happening. Sorry for the hassle.

**Comment by WhiteBlaaack** [comment]
Fo sho, I'l send asap

**Comment by WhiteBlaaack** [comment]
And since we're talking about the map, is there any way I can resolve the decals bugging through walls for other players?

**Comment by SDGNelson** [comment]
It looks like the terrain heightmaps/splatmaps files were manually replaced without replacing the Level.dat, or vice versa. If you replace the Level.dat with one from a map of the same size (like Russia) it can load again.

What do you mean by decals bugging through walls?

**Comment by WhiteBlaaack** [comment]
Oh yeah I think I remember when I did that, I put that by mistake when I tried to get an older map

And about the decals, the default editor is using the type of decals that i can move in devkit like the playerclips and things like that and I can see the decals on the surface cause I made the map, but my players see them buggin' into the surface

**Comment by SDGNelson** [comment]
Those players might be using forward rendering while you are using deferred rendering, in which case make sure you move the decals out of the surface slightly rather than directly even with the surface.
