### ISSUE TITLE
Vehicle prefabs does not disappear with distance

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#2781]
Hello! I am the owner of a pp life server and have noticed one unpleasant problem for a long time. Over a long distance, the vehicle model does not disappear, although the LOD is configured correctly. And vanilla transport behaves the same way ..
Because of this, the FPS on the server is extremely reduced. Can this be fixed somehow?
Below I have attached a screenshot, see what I mean.

![image](https://user-images.githubusercontent.com/46658857/130141548-9a90980f-5089-4ad9-80e5-e7ff718bfa80.png)
![image](https://user-images.githubusercontent.com/46658857/130144261-5b367103-d693-4863-b81f-0a2462fd32d8.png)

**Comment by SDGNelson** [comment]
Your LODs are probably configured correctly, but keep in mind the LOD group uses the size on screen so they are visible when you fly the camera into the distance to see them like that.
