### ISSUE TITLE
Berries can't be harvested from the bush

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#2783]
So i noticed on my server/map that players can't harvest berries. I tried replacing the berries on my map and it didn't work, then I jumped on washington and I can't harvest berries there too so I think it must be a bug

**Comment by littlecatking** [comment]
This is happening on all maps

**Comment by Rho1Cancri** [comment]
The last time berries functioned normally was three days ago, I think.

**Comment by SDGNelson** [comment]
I guess there **was** a reason the player could interact with the Water layer! As to why the berries were on the water layer, hmm... Will patch this afternoon. Thanks for the report!

**Comment by SDGNelson** [comment]
Should be fixed now!
