### ISSUE TITLE
Questions about server players

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#2784]
Q1. If the number of players on the server exceeds 24, it will not appear on the Internet list. Do you have any plans to increase the number of players?

Q2. The server doesn't seem to be utilizing the CPU and RAM properly. This seems to cause unusually high pings on the server. When using the server, the CPU is only running up to 50%, and so is the RAM.

Q3. There is a phenomenon in which all users are suddenly expelled from the server when there are many server players. What causes this phenomenon?

**Comment by SDGNelson** [comment]
1. Sorry no plans on this until server performance is better.
2. Sounds like the server is running at target frame rate so does not need to use more CPU. This is a good thing.
3. What reason does it say? Might be worth disabling the Enable_Kick_Input_Spam and Enable_Kick_Input_Timeout settings in Config.json
