### ISSUE TITLE
[Minor thing, just aesthetic] Desc_Hint and server name are not aligned ...

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2786]
![image](https://user-images.githubusercontent.com/13141042/130363799-0efc289e-8d83-4fdd-8fa8-e9f30ba0af1f.png)

**Comment by surv0013** [comment]
Everything is fine
![image](https://user-images.githubusercontent.com/17459138/130367341-17930ff2-dc6d-4d5e-a303-c32324f24a88.png)

**Comment by TH3AL3X** [comment]
I mean it should be centered with the details two

**Comment by SDGNelson** [comment]
surv0013 is correct, but I feel like this is going to annoy me now as well. Might increase the width of the Players list and pad the right side of the title to align the middle column with the title.
