### ISSUE TITLE
[Question]Devkit teleport point fail

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2788]
I have some problem with teleport function. Teleport works in single player but doesn't work in server. I'm using interactable custom object. Here is the info where the point is
1. Inside effect volume
2. inside dead zone
3. decal and small objects nearby
4. no spawn point nearby(zombie, item, vehicle, player etc)
 Space size doesn't seems to be issue because there is much smaller space completely surrounded and works fine. Error log and server console message doesn't appear as well. Other custom interactable object with similar dat works well. Is there any way to solve it or least find error logs?

**Comment by SDGNelson** [comment]
If the teleport fails it should log either that the spawnpoint was not found, or the destination was obstructed. Did you check U3DS/Logs/Server_ (name) .log? It should be the same between singleplayer and multiplayer though, so maybe the server has a different version of the map?

**Comment by prank0011** [comment]
This is also the case when some OBjs do not finish the Clip.
