### ISSUE TITLE
[Feature Request] Adjustable Light LOD transitionStart/End Value

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2789]
Could light LOD can be adjustable using tool(script)? Lights that has high range but completely fade out in short distance could be very useful for interior or underground memory performance. Adjustable transitionStart and End value will be able to make better light. This is bit more further, can adjustable culling mask can be added? Like items are culled in long distance.

**Comment by SDGNelson** [comment]
Hmm right now it is not intended to be manually edited, rather the game automatically adds the component to some objects. Ideally for underground areas some culling feature should be added to the game that the lights would automatically work with.
