### ISSUE TITLE
[Server] Too much CPU usage

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#2790]
Servers run 24 hours a day and are usually not CPU intensive. But suddenly CPU usage goes from 70% to over 80%.
Also, there is very little change in server users. (about 30 people)
Any idea why the CPU usage is high?

PC Specifications
i5 - 6500 / ddr3 8GB

**Comment by SDGNelson** [comment]
After running for a while it suddenly spikes? Does it stay high or does it go back down? Are there any errors in the console and/or in the Logs/Server_ (id) .log file?

**Comment by Blackwolf7704** [comment]
There are no errors in the log. Also, the usage suddenly goes up and it stays there.

**Comment by SDGNelson** [comment]
Hmm that does not leave much to investigate. Is there any correlation between something happening on the server and when the usage spikes?

**Comment by GazziFX** [comment]
That maybe caused by some of your plugins

**Comment by TH3AL3X** [comment]
> That maybe caused by some of your plugins

Surely it is a plugin abusing threading
