### ISSUE TITLE
[BUG] Using a 2d axis in the normal editor

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#2791]
When using the normal editor with CTRL + Left Click Drag it affects and the not used axis (e.g Using X+Y square moves the Z axis too for the distance of the "Snap transform")

**Comment by SDGNelson** [comment]
Ugh that old code is so wonky. I used some workarounds because I did not understand the math to do it properly back then. Fixed the level editor and in-game editor plane snapping for the next update.
