### ISSUE TITLE
[BUG] Waterfall and Devkit assets disappear in darkness nodes

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#2792]
![image](https://user-images.githubusercontent.com/59327136/130545237-77ef8e5e-4304-4c8d-ae6f-5fb9c16e2cf9.png)
without darkness node
![image](https://user-images.githubusercontent.com/59327136/130545577-65ebdc11-c316-47bf-bba7-18c2cc8fe6e9.png)
with darkness, flashlight
![image](https://user-images.githubusercontent.com/59327136/130545590-2065e6a2-5291-4c9e-bcf7-9fb2a800340b.png)
without flashlight, with darkness

It appears that waterfall 1 and devkit waterfall effects (same as Germany Zugspitze Peak waterfalls) disappear/dissipate  in darkness nodes. I don't know if it can be fixed, but it is there.

**Comment by SDGNelson** [comment]
Unfortunately since they use unlit shaders you would need to use a custom effect in this case, sorry.
