### ISSUE TITLE
PlayerDashboardInformationUI Players Tab lag issue

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2794]
When opening the players tab the game recalculates and recreating buttons, icons, etc... So it causes a lag.

So need to:
1. Maybe create a pool of `SleekPlayer`.
2. Create a pool of `Group` textures.
3. Sort players when the group is changed, a player is connected or disconnected.

Also, on opening, it calculates everytime if a player has gps and chart, so maybe use `PlayerInventory.doesSearchNeedRefresh`?

**Comment by SDGNelson** [comment]
These would probably be beneficial. Similar optimizations were done to the map itself during the glazier rewrite.

**Comment by SDGNelson** [comment]
Sorry that this got forgotten! I particularly wanted to do it after playing on servers with ~100 players after the limit was raised. The performance in the next update should be better. Not great, but better.
