### ISSUE TITLE
PSA: Buildable pooling on preview branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2795]
All structure items and some barricade items are now pooled by default. You can disable pooling per-item by setting `Eligible_For_Pooling false` in the .dat file. On Miku's example Washington save it is much quicker to teleport between buildable-dense locations like Seattle!

Many barricade item types still have pooling disabled. I need to go through and update their code to reset properly.

**Comment by DiFFoZ** [comment]
This check is good for the barricade that is not in the pool and active?
```cs
InteractableGenerator? generator = FindGenerator();
if (generator != null && !generator.GetNetId().IsNull()) { ... }
```

**Comment by SDGNelson** [comment]
@DiFFoZ that depends what your FindGenerator method does. None of the vanilla methods will return barricades that are in the pool however. Nevertheless an easy check would be `GameObject.activeInHierarchy`

**Comment by SDGNelson** [comment]
Essentially every barricade type on the preview branch is now pooled! I tested with every *type* of item so far, but will play around some more to hopefully catch any mistakes.

**Comment by SDGNelson** [comment]
The past couple days I have profiled and optimized many of the hitches related to adding/updating barricades. There are a few hitches left that are tricky to resolve yet e.g., electricity needs a proper rewrite eventually, but in general the drive from Kent to Seattle on Pandahut's save is now smoother.

**Comment by PandahutMiku** [comment]
I was messing around testing the current stable vs preview on the map we gave you, and it seems the changes helped a fair bit. Of course, these benchmarks are pretty rudimentary and just involved flying a jet over Seattle, from Clearwater to Kent, but it seems this update helped raise 1% low framerates a fair bit. It felt like a fair bit less hitching as well.

Current Stable (3.21.25.1);
Unturned.exe benchmark completed, 3893 frames rendered in 43.625 s
                     Average framerate  :   89.2 FPS
                     Minimum framerate  :   52.5 FPS
                     Maximum framerate  :  100.9 FPS
                     **1% low framerate   :   36.0 FPS**
                     0.1% low framerate :   16.2 FPS
![MSIAfterburner_QcthALjMHM](https://user-images.githubusercontent.com/17209937/132040554-2a9393eb-d3f2-4b89-ac83-906fccb076ed.png)

Current Preview (3.21.26.0):
Unturned.exe benchmark completed, 4094 frames rendered in 44.078 s
                     Average framerate  :   92.8 FPS
                     Minimum framerate  :   59.7 FPS
                     Maximum framerate  :  100.9 FPS
                     **1% low framerate   :   52.7 FPS**
                     0.1% low framerate :   17.1 FPS
![MSIAfterburner_9WbbwRMTop](https://user-images.githubusercontent.com/17209937/132040678-7a68871f-4936-4d32-9d37-baa501e214f1.png)

Of course, your mileage will vary. Hopefully, this will help people with lower specs as well. I raised the concern in the GitHub issue with the barricade/structure changes last month, but quite a few people were complaining about worse performance after those barricade/structure changes. Thanks for taking the time to address those issues.

**Comment by SDGNelson** [comment]
Glad to hear that you saw some improvement Miku! Also perhaps I misunderstood your benchmark, but the biggest improvement will be when re-visiting areas. For example loading Seattle, unloading, and then reloading it is much faster because all of the items are already in the pool.

**Comment by PandahutMiku** [comment]
> Glad to hear that you saw some improvement Miku! Also perhaps I misunderstood your benchmark, but the biggest improvement will be when re-visiting areas. For example loading Seattle, unloading, and then reloading it is much faster because all of the items are already in the pool.

Hm, I thought you were using a more generic object pooling (i.e just pooling each Barricade/Structure instance & game object and reusing them when having to spawn another). Didn't realize you were instead pooling each specific barricade/structure.

I think most of the performance benefit/lower microfreezes I got was just from the barricades/structures's game objects not being destroyed when being unloaded. (Even with unloading being deferred, in past versions you could still see your fps drop when you were unloading a large region, afaik UnityEngine.destroy is just expensive)

Testing at least on my rig between going back to Seattle when it's already loaded vs restarting & going there for the first time, I can visually see it load much faster, but the benchmark numbers are within a margin of error from each other.

**Comment by PandahutMiku** [comment]
Ouch: Looks like something slipped through.

Claim flags don't show radius & say the area is claimed by someone else when they are loaded back in. (i.e they look/appear fine when you first place them, but if you TP away and come back, they appear owned by someone else)

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like the ordering of their initialization is slightly different now causing the problem. Double-checking a fix and will upload as a .1 patch shortly.
