### ISSUE TITLE
Chef Plush Cosmetic Mis-colored + missing code

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2797]
There's 11 miscolored pixels on the upper lip of the zombie chef plush cosmetic - is this intentional? 
It's subtle, but very noticeable when using a blue light night-mode filter.
I've taken it into photoshop to make it more visible. 
<img width="202" alt="2" src="https://user-images.githubusercontent.com/71527679/131049695-7d74ff9d-a23d-4429-a5e9-10801c04ed17.png">
<img width="202" alt="3" src="https://user-images.githubusercontent.com/71527679/131049744-6273d7f8-1bcc-41d1-9003-ed14ee588169.png">

Also, I purchased 2 plushies from Makeship, but only received 1 steam cosmetic code. I've contacted them about this but they haven't gotten back to me - are they the right people to contact, or should I send my order information elsewhere?

**Comment by SDGNelson** [comment]
It looks like the compression was discolouring it. The texture is tiny, so I have opted to disable compression on it.

Makeship confirmed that they will be sending emails to any customers who purchased more than one plush, so my guess/hope is that it would be sorted out this week.
