### ISSUE TITLE
Rigidbody Elevator Clipping Issues

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#2799]
I have come across an issue on my model identical to that on the car lift, whereby if a vehicle is driven and parked on the elevator and the elevator ascends or descends the vehicle remains in place because the rigidbody hasn't reacted. However, I have noticed that vehicles spawned directly onto the elevator have no issues with the rigidbody always reacting. Is there any potential foreseeable fix for this problem?

**Comment by SDGNelson** [comment]
Sorry, this is a longstanding issue that sleeping rigidbodies are not awoken by animations. It might be addressed eventually but is relatively low priority #1655
