### ISSUE TITLE
[Feature Request] Mirror Unity Camera

### ISSUE THREAD

**Issue by connorgillespie** [SmartlyDressedGames/Unturned-3.x-Community#2800]
So recently, I have been brainstorming a few plugin ideas. I came across the idea of having a command that allows staff to "spectate" a player and view the perspective of the player. At least from my knowledge, there is no way to currently duplicate the camera sent to a player. So instead, I was forced to teleport the player to the location of the player. This obviously had some underlying issues. 

I request that you add some sort of way to mirror a player's Unity camera to another player. 

This idea could also be used to improve on the Arena game mode. Maybe when a player is dead or in the spawn area, they can have the option to spectate other players. This would probably end the boredom of sitting in the spawn for 15 minutes waiting for the round to finish. 

Likewise, this could also be used as a default staff utility similarly to `/spy`. Since `/spy` has it's downsides, this utility could be used by online staff members to better determine if a player is cheating.

**Comment by SDGNelson** [comment]
This would happen if spectating is added, but low priority sorry.
