### ISSUE TITLE
Particle System Collision Audio script seems to Material Property Name

### ISSUE THREAD

**Issue by benvalkin** [SmartlyDressedGames/Unturned-3.x-Community#2802]
I've been trying to make a custom shell casing effect with collision sounds that are different depending on which material the collides with, much like the vanilla shell casing effect. I've been trying to do this by adding multiple Particle System Collision Audio scripts onto the Effect gameobject like this:
![image](https://user-images.githubusercontent.com/69928007/131344847-b90af9c5-0980-461b-8a2b-8db31a4004f3.png)
Unless I'm doing something wrong, it seems as though the collision sound is played regardless of what 'Material Property Name' is set to. So in this case with multiple scripts added, each added script plays its own sound whenever the shell collides with anything.

Not sure if this is worth adding: I have also tried using the Unity .physicsMaterial names instead of the EPhysicsMaterial enum values, doesn't change anything

**Comment by SDGNelson** [comment]
The intention is that custom properties will be associated with physics materials by name. For the meantime the built-in property names are "BulletCasingBounce" and "ShotgunShellBounce". Once that gradual rewrite is complete you can use your per-surface sounds, but currently the only options are the built-in or a single custom sound (Audio Def).
