### ISSUE TITLE
unable to trust host encryption certificate

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2804]
what does this mean? i was gone for a few hours and now this happens it has never happened before
![image](https://user-images.githubusercontent.com/81492602/131396764-c2fcabdf-cbf6-4f37-916e-6587201c3bd9.png)

**Comment by SDGNelson** [comment]
You might not be connected to Steam. i.e., lost connection at some point in those few hours. It should fix itself by re-acquiring the up-to-date certificates.
