### ISSUE TITLE
Bayonet knife

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2805]
Is it possible to change the animation of the bayonet knife somehow? For example I want to make a blow with the butt

**Comment by SDGNelson** [comment]
Sorry, there is not currently a way to animate the bayonet. I was thinking about adding an event for it to UseableGunEventHook though.

**Comment by prank0011** [comment]
> Sorry, there is not currently a way to animate the bayonet. I was thinking about adding an event for it to UseableGunEventHook though.

However, UseableGunEventHook can only trigger gun actions, not character actions.
Will it be increased together in the future?
