### ISSUE TITLE
Animation replay when changing between first and third person view

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2806]
I've been working a lot of joints and animation on items. one thing never solve is animations are replayed when changing first and third person view. This happens on gun event hook, but I have no idea which one should I touch. I tried change culling type, play automatically(turn off makes animation not be played), wrap mode etc but none of them was able to solve it. This also happens to hinge which hinge movements are replayed. In Gun Event Hook, when 'bool play automatically' or 'bool enabled' is set, animation play after view has been changed then replayed again changing first and third person view.
Are there any solution of those problem?

**Comment by SDGNelson** [comment]
What are you triggering the animations from? The first-person game objects are disabled while in third-person (and vice versa), but off the top of my head the only event that would be repeating when switching perspective is the Activation event component.

**Comment by sam9612** [comment]
some are very simple like opening the brief case which animation is attached directly to moving part. Like gun event hook, I tried to make pistol slide movement using Animation.Rewind/AnimationClip clip/bool enabled/bool PlayAutomatically to move slide but didn't work well. Animation.Rewind makes animation replay when change perspective, AnimationClip clip/bool enabled/bool PlayAutomatically makes animation play after change perspective then replay. Could game object position in Unity affect them? Or did I just set animation component wrong?

**Comment by SDGNelson** [comment]
Play automatically is triggered whenever the animation component is enabled which would explain why it happens when you switch perspectives. Unfortunately the only good trigger for animations would be from one of the "event" components.

**Comment by sam9612** [comment]
Understood, Still one problem is Gun Event Hook. If I disable Play Automatically on component(attached on moving part), animation never plays it even Events are triggered like Animation Rewind, Animation Clip, bool Enabled etc. If Play Automatically is turned on, it work but animation replay again after change perspective. Sorry for keep asking, but this is really hard to do without any example :(

**Comment by SDGNelson** [comment]
Which event are you using? What is GunEventHook attached to?

**Comment by sam9612** [comment]
Event is 'On Reloading Start' and event script is attached to 'Item'.  Here is the image how I set.
![2](https://user-images.githubusercontent.com/57828757/131998748-86712cb8-fec6-4393-8e32-49b7ee7f3fb2.png)
![1](https://user-images.githubusercontent.com/57828757/131998759-d148b253-e2df-44a7-a76e-7be799130734.png)

**Comment by SDGNelson** [comment]
It looks like "play automatically" is still enabled on that screenshot.

**Comment by sam9612** [comment]
Umm.. if play automatically is not enabled, animation never plays it

**Comment by SDGNelson** [comment]
Play automatically is why it is playing when you change perspective though. If you change Animation.Rewind to Animation.Play with play automatically disabled that might do the trick.

**Comment by sam9612** [comment]
Really weird that Animation.Play does not exist. No Console error log as well.
![2021-09-05 (2)](https://user-images.githubusercontent.com/57828757/132101486-021267e5-dc58-4e6d-8a5c-ab5d5366806e.png)

**Comment by SDGNelson** [comment]
Oh I see. 😕 I am not sure why the Play method is not available. (double-checked and it is not available when I look either) Maybe the Animator component would work then?

**Comment by sam9612** [comment]
If Animator is enabled, perspective replay happens again. Tried using Animator.Playing event(int, string) while animator component is disabled, animator doesn't play. If Animation.Play is broken or something, I might just wait for next patch.

**Comment by prank0011** [comment]
It looks like when the activity switches from off to on, it plays an animation.
Switching perspective affects the activity of the entire item.
I use the opening activity and timing hook to control the opening animation.
After the animation is played, the timing hook will close the subitems with animation components.

**Comment by sam9612** [comment]
That is really smart way to do it. Does Play Automatically needs to be turned off? Animation works well if played only on one perspective view. Still replays it after changing view...

**Comment by prank0011** [comment]
This is my setting parameter.
![1](https://user-images.githubusercontent.com/68633558/132127054-5401d07f-7d12-4dd5-9fee-8f01b7c2f59e.png)
![2](https://user-images.githubusercontent.com/68633558/132127056-f6709c0e-ce4e-4273-9c9f-39befd763221.png)
![3](https://user-images.githubusercontent.com/68633558/132127064-60631e6b-8741-4ef6-aaaa-36b311cdcd6a.png)
The last value set by Fire is the length of animation.
I must remove the animation when it is finished, otherwise it will trigger the animation when I am holding a gun.
I can't explain why a timing hook should be added to the process.
Because when I don't add a timing hook, I sometimes switch perspectives and still trigger animation.

**Comment by sam9612** [comment]
It work! thank you so much!
