### ISSUE TITLE
[Bug] Incompatibility between Armor_Multiplier and Weapons_Use_Player_Damage

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2808]
The **Armor_Multiplier** and the **Weapons_Use_Player_Damage** config settings for zombies do not interact with each other. **Armor_Multiplier** does not influence damage sources that are affected by **Weapons_Use_Player_Damage** being set to true. Functionally, this makes the **Armor_Multiplier** setting useless, as the only things it affects are static damage sources such as Fists and Bayonets.

I believe there should be some sort of interaction going on here. Otherwise, a disclaimer marking their incompatibility with each other.

https://www.reddit.com/r/unturned/comments/phc1yb/zombie_armor_multiplier_bug/

**Comment by SDGNelson** [comment]
Hmm... right now it uses the Players.Armor_Multiplier option when Zombies.Weapons_Use_Player_Damage is enabled. I can see why it would make sense to still use the zombie/animal armor multiplier options though.
