### ISSUE TITLE
[Feature / Change Request] Nametag optimization.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#2810]
Any chance we could have some fps optimization for when a lot of group member name tags are on the hud (10+). Servers with large groups (like a server with 2 teams) tend to have low fps when the hud isn't hidden or when GroupHUD is enabled.

Even better in my case would be an RPC to tell a player to hide or show another player's nametag if it's not too much trouble.

Thanks.

**Comment by SDGNelson** [comment]
It should already be fairly optimized. I will mark this "next update" so that I remember to profile it. 😕

**Comment by DanielWillett** [comment]
Yea it's fine until you get big groups on lower-end pcs. Thanks for the quick reply, appreciate it.

**Comment by DanielWillett** [comment]
Actually now we're thinking it isn't nametags specifically but all group-related UI (mainly nametags and compass), it's caused by something to do with being in large groups. I went in-game to test some more, this is without nametags but with a compass on 64GB ram with i9-9900K and an RTX 2080 SUPER.

                      IN 17 PERSON GROUP     OUT OF GROUP
  UI SHOWN   60 - 75 fps                       90 - 110 fps
  UI HIDDEN   90 - 115 fps                     100 - 115 fps

**Comment by SDGNelson** [comment]
Sorry that this got forgotten! I have taken care of a few potential problems in there for the next update, so the performance impact from large groups in the hud should be marginal.

**Comment by DanielWillett** [comment]
Thanks for taking a look.
