### ISSUE TITLE
[Minor bug] Something related to the colors and strings

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2811]
The <colors> or any type of format should be removed and not counted as a character, because if not, this happens ...
![image](https://user-images.githubusercontent.com/13141042/132096338-11b1a933-9a67-4d58-aa8c-cad7857d0b92.png)

**Comment by TH3AL3X** [comment]
You can see a line </, and that is quite annoying, in addition to taking away space to write more...

**Comment by SDGNelson** [comment]
The length limit is on the Steam API side, so this cannot be changed.
