### ISSUE TITLE
Disable Plugin Keys when chatting

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2812]
When I type in chat and press plugin key it will open UI

**Comment by SDGNelson** [comment]
On the client side the game does check that UI does not have focus. Which key do you have it bound to? Listening for PlayerInput.onPluginKeyTick?

**Comment by GazziFX** [comment]
```
private void onPluginKeyTick(Player player, uint simulation, byte key, bool state)
{
	if (key != 2 || !state || player.inPluginModal || player.equipment.isBusy)
		return;
        // show ui and etc
}
```

**Comment by GazziFX** [comment]
> On the client side the game does check that UI does not have focus. 

I mean in-game chat

**Comment by GazziFX** [comment]
Oh sorry I have client modifciations

**Comment by SDGNelson** [comment]
Ah right, I forgot you are a cheater. 🙄
