### ISSUE TITLE
[Feature Request] Browsing Filter For Amount of Mods

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2816]
Currently not all computers can support many servers because of their limited RAM, so a nice feature would be able to filter out servers that have lets say 8 mods or less. More of a QoL feature.

**Comment by rube200** [comment]
Just check if server have workshop or not

**Comment by Jdance-Media** [comment]
> Just check if server have workshop or not

Some people want mods but not that many.

**Comment by Jdance-Media** [comment]
> > Just check if server have workshop or not
> 
> Some people want mods but not that many.

Let's say I have a 8 GB RAM computer but I want to save some of my memory for Discord and web browser tabs as well. I'd want to go on a server that has a limited amount of mods but enough to keep me busy and happy.

**Comment by educatalan02** [comment]
Servers cannot hide workshop mods, so check the lobby

**Comment by Jdance-Media** [comment]
> Servers cannot hide workshop mods, so check the lobby

Yes, I'm going to check the lobby of every damn server on the list just to find one that has a good amount of mods. My suggestion is to add a filter based off of a integer.

**Comment by surv0013** [comment]
There are different mods. Some large projects add many items to one mod, so you won't be able to estimate the load on your PC by the number of mods on the server anyway.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by Jdance-Media** [comment]
I was looking through the issues recently and I wanted to comment on this again as my opinion and perspective on it has obviously changed.

My idea for the most part revolved around arbitrary workshop item counts. This is not a good measure of actual memory usage. Overall the idea isn't the best. I do believe that if we have some means of estimating either file size or the size of asset bundle contents, then it would be worth doing.

It was not a good idea in general. Forgive my brief stupidity.
