### ISSUE TITLE
[Feature request] fps limit at main menu

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#2817]
Hello,

it would be nice to be able to limit frame rate at main menu. because if leave game idle at main menu it take almost 100% from GPU power!

![image](https://user-images.githubusercontent.com/59157332/132503837-41d6ae54-9ede-450b-81c8-f2cf3d1c820d.png)

**Comment by surv0013** [comment]
I think the FPS limit is needed not only in the menu, but in the game as a whole. In Unity, this is not difficult to implement.

**Comment by baranmod** [comment]
![image](https://user-images.githubusercontent.com/14231707/132509498-97b4cfd3-2271-4f6d-94c0-aa540e5b2a28.png)

**Comment by SDGNelson** [comment]
Thanks baranmod! Yes: FPS can be limited with VSync or the Limit Framerate option, but VSync is preferable.

**Comment by nanashi88** [comment]
I am aware of VSync and FPS limit features that already in game.
some players doesn't prefer VSync and prefer to keep fps unlimited, they claim this be more smooth because VSync cause intentional lag.
Idk how much this is true, so I prefer to keep fps unlimited.

sometimes I use fps limit at main menu when I expect long time idle, or doing other heavy work on pc.
but this is not conveintient to keep changing this settings.

at first place why default game behaviour is that main menu run on full gpu power ?!

anyway, I still can live with current situation. this is just a not urgent suggestion

**Comment by SDGNelson** [comment]
Since it is running at 600 FPS on your main menu, maybe you could always keep the FPS limit enabled with a value of ~120?

**Comment by nanashi88** [comment]
this is an acceptable solution, thank you.

in the future if there was such a feature available, I guess I will limit fps at main menu to 24 or 30
