### ISSUE TITLE
[Question] Interactability Condition Type Multiple Items

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2819]
I tired to make interactable object that requires some items, but I can't find multiple item require. I know I can use multiple Interactability Conditions, but this mean it requires all items not one any of them(Kinda 'If or'). Is this kind of condition exist?

**Comment by SDGNelson** [comment]
Unfortunately no, this is a frustrating limitation at the moment. I would like to add support for boolean algebra in conditions eventually.
