### ISSUE TITLE
Change ESteamConnectionFailureInfo.PING localization 

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2820]
Right now, when a player joins a server before it is fully started, it often kicks them for this reason, which is localized to "This server only accepts really fast internet." a fair number of people get confused by this, and it also kind of implies that it's a server setting limiting them from joining. Maybe something like "This server did not respond to you in time" would be more accurate.

**Comment by SDGNelson** [comment]
Ideally the server should not be initialized until it can definitely accept connections. That code is really old and fragile however. I will check into this for the next update.

**Comment by SDGNelson** [comment]
For the meantime at least this will be better communicated in the next update: it will say "Rejected because your calculated ping (X ms) exceeded the server maximum of Y ms"
