### ISSUE TITLE
new glitch

### ISSUE THREAD

**Issue by Legno1312** [SmartlyDressedGames/Unturned-3.x-Community#2823]
Just find this bug on server 
![Untitled](https://user-images.githubusercontent.com/90780305/133454682-668b2d1b-a931-42e8-bb97-2572f9f90871.png)

**Comment by SDGNelson** [comment]
Do you know how they got under there? I have seen some reports that vehicles falling on players heads are pushing them into the ground (on my list to double-check), so this might also be that.

**Comment by Legno1312** [comment]
i was on freezzer sandbox server i spawn skijeck 
by accident above me and suddenly I was teleported under the map

**Comment by GazziFX** [comment]
> i was on freezzer sandbox server i spawn skijeck 
> by accident above me and suddenly I was teleported under the map

Freezzer has forceTrustClient option, so maybe this bug is only client-side

**Comment by SDGNelson** [comment]
Unfortunately teleporting back to the surface requires authoritative movement at the moment. This is all because I experimented with enabling character overlap recovery again though, so it is reverted to disabled in the next update.
