### ISSUE TITLE
Weapons can damage/harvest berry bushes

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2825]
Weapons such as firearms (e.g., a PDW) and melee weapons (e.g., a Chainsaw) can be used to damage and harvest berry bushes.

Berry bushes are resource assets, but are only intended to be foraged (not destroyed). When destroyed, the game uses the default values for Reward_Min and Reward_Max, resulting in 6 to 9 berries dropping per berry bush. This allows the player to farm large quantities of berries at once.

**Original report:** https://www.reddit.com/r/unturned/comments/porqim/a_chainsaw_can_save_you_from_starvationdehydration/

**Comment by SDGNelson** [comment]
So *that's* why they were on a different layer. Well, good to find it out so that the server properly checks whether it should be killable/foragable.

**Comment by SDGNelson** [comment]
For the next update I have fixed it so the bushes can be killed using melee/gun, but the items will no longer drop.
