### ISSUE TITLE
onBarricadeDestroyed event

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2828]
After introducing of the barricade pool, I ran into a lot of problems in my plugins that checked that the barricade was destroyed like this `if (!drop.model)`, now I checking `if (!drop.model || !drop.model.gameObject.activeSelf)` but it can be still buggy.
I want new event to safely handle barricade destroy, but it can be also useful for other cases

**Comment by SDGNelson** [comment]
Where are you getting references to barricades in the pool? The vanilla methods would not be returning them.

**Comment by GazziFX** [comment]
I save BarricadeDrop to list and then check in update if unity object will dead, I need it to hold some additional data, like password of doors, and today I got bug: I placed new door and it already has password

**Comment by SDGNelson** [comment]
Checking them every Update like that is not ideal. Would recommend a component using OnDisable to reset the data.
