### ISSUE TITLE
Double Feature Ideas: Multiple weapon support for vehicle turrets & configuration option to change player render distance

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2833]
I made thoughts on what features that Nelson could add next with what I think is implementable with Unturned's code. I am not familiar with the game's code, but the feature ideas I thought of is based on how much I understand the game's logic so far.

So to start, let's go to the idea of making a feature for vehicle turrets to support more weapons. Despite being mentioned & suggested several times before, I bet this is pretty easy to implement with little to no difficulty. The way I'd see this work in Unturned modding is that it lets a single turret seat support more weapons without relying on duplicating the same seat in Unity just to integrate weapon switching. It can work like a custom but locked item hotkey system that is separate from the player's hotkeys. Once a user is seated into the turret seat, they are given the available guns that are already placed into hotkeys on default. It should support the maximum amount of 10 turret guns, in case someone wants an OP vehicle turret. I see this feature beneficial & it allows vehicles like tanks to support coaxial weapons & smoke countermeasures, professional vehicle content creators will especially be happy with this addition.

The second & last feature idea is fairly simple, which is to have a configuration option to change the player's render distance. I know that Unturned is not exactly the type of game that has long-range interactions, but there are several servers that have them otherwise because they have mod content like vehicles that render at extreme distances & guns with that exact capable range. At best, the configuration should at least support the maximum amount of 2000 meters, which I think is at least comparable with the maximum render distance of large objects (correct me if I'm wrong). This would then allow the option of servers to have potential in long-range gameplay like looking through binocular items of any kind & even longer range sniping.

That's all stuff I can think of ATM. I don't think my ideas shouldn't be a primary focus, but I think they are easy enough to add to the game without making too much hassle.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
