### ISSUE TITLE
Availability of audio clips in ExampleAssets.unitypackage

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2834]
Would it be realistic for us to update the ExampleAssets.unitypackage to include many of the consolidated audio clips? E.g., placement sounds for metal or wood barricades, car engine ignition, car engine horn, doors opening, etc.. As far as I'm aware, the clips that were consolidated are no longer available in the latest version.

The /Sounds directory these files are now contained in does not seem to be included with the ExampleAssets.unitypackage, making them unavailable. Ideally, modders should still be able to use these audio clips.

**Comment by SDGNelson** [comment]
Mods *should* still be able to use those clips by referencing them the same way the vanilla assets do. In retrospect however I need to be more careful with the audio. Most of the original audio is self-recorded or CC0, but new clips are purchased from stock libraries. Specifically for audio going forward I want to start tracking the license alongside the files.

**Comment by MoltonMontro** [comment]
How should a mod reference a consolidated audio clip? For example, "**PlacementAudioClip Sounds/WoodenPlacement.mp3**" is what official wooden barricades use. But, it searches the core.masterbundle to do this, so it cannot be verbatim copy-pasted onto modded items afaik. Can modders search a different masterbundle specifically just for the audio clips?

**Comment by SDGNelson** [comment]
Oh, it should be parsing anything before ':' as the asset bundle name, but it is not doing that. Thanks for the report! For example `PlacementAudioClip core.masterbundle:Sounds/WoodenPlacement.mp3` should work. I will fix that for the next update.

**Comment by SDGNelson** [comment]
Fixed for the next update!
