### ISSUE TITLE
-Port command line argument ignored

### ISSUE THREAD

**Issue by Salnex** [SmartlyDressedGames/Unturned-3.x-Community#2835]
Including -port/27030 doesn't seem to change the steam query port from the default. Not sure if normal port is also affected but it is  the steam query port the console lets me know if cannot bind and highlights it is trying to bind the incorrect port

The server is being run in linux

**Comment by SDGNelson** [comment]
Thanks for the report. This might be related to the command parsing issue in #2829. I will check into it for the next update!

**Comment by SDGNelson** [comment]
It looks like it should actually be "-port 27030" rather than "-port/27030". For my test I used "-port 27030 +InternetServer/Test" and it worked as-expected. Sorry, Unturned's built-in command system is a confusing low-quality mess as-is.
