### ISSUE TITLE
[Feature Request] More Fishing Rod Options

### ISSUE THREAD

**Issue by P9ndx** [SmartlyDressedGames/Unturned-3.x-Community#2837]
There has been a bug fix where the catch timer on fishing rods didn't get randomized recently so I thought about this:

Currently, there is barely any support for fishing rods or unturned fishing customization. 
I think it would be extremely helpful and open new doors for future maps if some more features could be added:

- Time it takes to pull the fish in ( random time between 2 values)
- Time it takes for a fish to get hooked (random time between 2 values)
- Chance for the fish to flee

Fishing in Unturned doesn't get much recognition currently, only with Elver has it actually becomes somewhat useful. 
I wish there were more options for map creators and modders to play around fishing.

**Comment by P9ndx** [comment]
Edit: Possibly also adding the support for durability, for modders to be creative

**Comment by Nuhm** [comment]
So durability could effect reel chances and time taken?

**Comment by GlockStone** [comment]
I would suggest just having the entire fishing system scrapped and reworked. Fishing tables are currently determined by the fishing rod, not the location. This means that you can catch any time of fish at any type of location. I personally, dislike this and would prefer it to be based on location than the fishing rod. Players shouldn't be able to catch lobsters in a river. Just doesn't make sense.

I think the best way to do this would be to just create a node. You place the node, give it a name, scale it up or down, and then enter a GUID. The GUID that is entered would be the same GUID as a regular fishing rod table.

I had a plugin commissioned to fix this problem. It works with advanced regions. Basically, you create a region and give it a name. Then you type that name into the fishing plugin config and set the percentage chances of what you'd like to catch. 

I have not yet tested the plugin, but the commission was complete. So, if anyone would be interested in using it, shoot me a message on Discord: GlockStone#0001

I'm planning on having a body of water in deep caves, with a kill volume and lava placed over it. I wanted to create lava fishing as well as specific location fishing like deep oceans, oceans, shores, rivers, lakes, etc... for my medieval project
