### ISSUE TITLE
Minor observation: Possible 0 player damage guns not giving exp for zombie kills.

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2838]
Fiddled around and group a pack of gun overwrites to see how each value would work in game. There is one gun within with 0 player damage (There are positive values on zombie, animal and resources damage).
Somehow on zombie being killed, it doesn't award any exp.
For guns with 1 player damage, they still do award the usual exp.

Not sure if this is intended or not, hence the title. (Could be an interesting feature even if not intended :) )

**Comment by SDGNelson** [comment]
I tried to test this now by setting the Eaglefire's `Player_Damage` to 0, and it seemed to give XP when killing zombies as normal. With `Weapons_Use_Player_Damage` enabled it did not damage the zombie. Looking at the code I also do not see a problem. Are you able to reproduce this or send over an example gun where this happens?

**Comment by SDGNelson** [comment]
My guess is that the explosive damage from the magazine is what is actually killing the zombie, and XP is not awarded for explosive kills. I am not sure what the original reasoning is for explosives not rewarding XP... it might have been considered too powerful.

**Comment by Ongjming** [comment]
Thanks, hmm it could be a great feature for controlling the amount of exp people get from certain weapons just by adding the explosive magazine.

Once again, thanks so much for exploring this!
