### ISSUE TITLE
[Bug] Blueprint Supply amount mismatch

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2841]
BlueprintSupply has amount as ushort, but ItemAsset reads it as byte, this causes overflow and defaults amount to 1

**Comment by SDGNelson** [comment]
It looks like there are a variety of other places which assume amount is a byte, so I am hesitant to change this. I do want to rewrite the crafting system at some point so this would be uncapped when/if that happens.
