### ISSUE TITLE
Dis-allow placing CHARGE barricade outside of the map

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2842]
or in PlayerClip

**Comment by P9ndx** [comment]
Since this is a topic I feel like charges should also be salvage-able by others possibly. Right now if you see a charge somewhere there is no use for it but to destroy it which doesnt feel right

**Comment by SDGNelson** [comment]
How come?

Also good point, it would make sense to add an option allowing non-owners to salvage item types.
