### ISSUE TITLE
Cant join some unturned servers

### ISSUE THREAD

**Issue by Alex998878** [SmartlyDressedGames/Unturned-3.x-Community#2849]
before i was playing on an unturned server and after they switched the hosting i could not join anymore i cant join some other servers to 
i contacted the owner he suggested my to contact hosting and i did hosting told me to try again it did not work i told them maybe the hosting blocked my IP they said that is not possible and i need a help because i really want to play on the server

**Comment by Alex998878** [comment]
here

**Comment by Alex998878** [comment]
yes i can see servers but not all servers some servers my friend invite me i cant find and when i enter ip and port it wont work
and i cant see the server that i was playing before

**Comment by SDGNelson** [comment]
Thankfully that does seem to be the most recent version.

Do you have a firewall and/or anti-virus software? If so, can you check that Unturned's outbound connections are not restricted?

**Comment by Alex998878** [comment]
yes but i cannot use vpn due to an error rn
and ye it worked when i used VPN and i could join

**Comment by Alex998878** [comment]
IP and Port to server or my network

**Comment by SDGNelson** [comment]
I took a look at that server "USemiRP" and it is using the new Steam networking, but is that the server you were trying to connect to before? Or is this the server you are able to play on?

**Comment by SDGNelson** [comment]
In the two comments above you linked the USemiRP server. Is USemiRP the server you were originally talking about? Because when you tried with the VPN you mentioned Elitelupus RP. Are you able to join USemiRP?
