### ISSUE TITLE
PSA: Breaking steam://connect/ip:port

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2854]
Less dramatic than the subject would suggest. The update next Friday (2021-10-22) is going to make the query port the same as the configured port, rather than plus one. This means any Steam browser protocol links will need their port decreased by one. For example [steam://connect/127.0.0.1:27016](steam://connect/127.0.0.1:27016) should be changed to [steam://connect/127.0.0.1:27015](steam://connect/127.0.0.1:27015).

You can try on the preview branch now. I still need to double-check that a few related features like joining by friends list, by lobby, etc. have been updated properly, but I figured best to give as much heads up as possible.

To make up for the hassle, the "recommended max players" limit has been removed. There are still many network optimizations needed, but ideally with the improvements so far this year and future plans it would have needed to be removed at some point anyway.

**Comment by GlockStone** [comment]
"the "recommended max players" limit has been removed."

Does this mean that servers that have player limits like 64 and 100 will now pop up on the Internet tab when the new update comes out?

**Comment by SpectrEXP** [comment]
Would this change port forwarding in any way possible for unturned? just to clarify since I'm still having a problem with port forwarding for some reason even after adding firewall exceptions and having the correct private IP address in the port forwarding rule.

**Comment by SDGNelson** [comment]
> Would this change port forwarding in any way possible for unturned?

Nope, no change, except that the docs should be updated to mention only two ports are necessary now.

**Comment by DronXa** [comment]
> > most of the players can't see the server on server list, tokens are set (updated to new one just now), same couple players joining server
> 
> #2866 I'm having this same issue still, not sure why. A couple of my servers are showing up like normal, the rest aren't visible on the server list at all. The Steam tokens are all up to date etc.

I have had the same issue on my OVH servers for some reason since september, my servers sometimes show up in the internet browser and sometimes not.
