### ISSUE TITLE
Connecting to a server with 2 IPs

### ISSUE THREAD

**Issue by ibrahimozkn** [SmartlyDressedGames/Unturned-3.x-Community#2858]
I am having issues with voxility in my host and I asked a IP without a voxility protection. They gave me a second IP to use. I removed all bind configuration inside Command.bat and restarted my server. However, after this, connections are still available with my first voxility protected IP and I cannot access to my server with my second IP.  I am using Windows 2012 server

**Comment by SDGNelson** [comment]
If both addresses point at the same machine I would assume it should work when not binding to a specific address, but I am inexperienced / not knowledgeable about that layer of the network stuff, sorry.
