### ISSUE TITLE
Issue - Servers not showing on Server list

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2866]
Since the latest update many server are not appearing on the in-game server list despite being online. 
They can be connected to via direct connect.

**Comment by AdamDN** [comment]
Just an update - despite #2854 being closed, this is still an ongoing issue. 
Some servers do not appear on the in-game server browser for unknown reasons.

**Comment by SDGNelson** [comment]
The Steam server list is a mysterious black box - I remember having issues with this back in 2014 as well. I assume there are no other unusual errors being listed in the console / log?

**Comment by PandahutMiku** [comment]
If you're hosting on windows:
Check in the root u3ds folder your steamclient.dll / steamclient64.dll last modified versions.
I noticed that with versions last modified 9/15/25, whenever the dedicated server picked UDP to connect to steam over, it would fail to list. If it picked websockets, it would list fine.

Manually updating those dlls either from your own client or from a fresh server install seemed to fix the issue. This was annoying to track down though, and I made a few other changes around the same time as well, so not 100% sure if that was the issue or not, but I feel confident it was. 

(I'm really not sure how these dlls are updated. I would assume they're updated based on the steamworks SDK redis, as it was last modified 9/14, but it appears the steamcmd tool also grabs the latest ones from another source whenever you install the server fresh, although it doesn't do that even if you run validate on an existing install. I recall linux unturned had some related issues at one point)

**Comment by SDGNelson** [comment]
Thanks Miku! Interesting, it's bizarre that the Steam redist files get out of date sometimes. I wonder if a check should be added to the game itself warning about Steam redist version.

**Comment by AdamDN** [comment]
> Manually updating those dlls either from your own client or from a fresh server install seemed to fix the issue (I copied steamclient.dll, steamclient64.dll, tier0_s.dll, tier_s64.dll, vstdlib_s.dll and vstdlib_s64.dll). This was annoying to track down though, and I made a few other changes around the same time as well, so not 100% sure if that was the issue or not, but I feel confident it was.

Thanks for the suggestion but still not luck. 
I've just replaced these 6 files on a server that's not showing up on the list with copies from a working server, and the server is still not listed. 
Any other ideas I could try?

**Comment by PandahutMiku** [comment]
> > Manually updating those dlls either from your own client or from a fresh server install seemed to fix the issue (I copied steamclient.dll, steamclient64.dll, tier0_s.dll, tier_s64.dll, vstdlib_s.dll and vstdlib_s64.dll). This was annoying to track down though, and I made a few other changes around the same time as well, so not 100% sure if that was the issue or not, but I feel confident it was.
> 
> Thanks for the suggestion but still no luck. I've just replaced these 6 files on a server that's not showing up on the list with copies from a working server, and the server is still not listed. Any other ideas I could try?

What's the date modified on the files you replaced yours with? Copying from a "working server" isn't guaranteed to work, as even with the broken files there is a 50% chance it picks UDP (and doesn't list), or websockets (and does list). The ones we updated ours with were from 10/13/21. I would recommend just making a fresh install and copying from there. Of course, after you replace the files, you need a full restart (you need the server stopped to even replace them in the first place).

If that still doesn't work, you could check u3ds/logs/connection_log_27015.txt for any obvious errors/issues, if it picks a server and times out, etc.

**Comment by AdamDN** [comment]
> > > Manually updating those dlls either from your own client or from a fresh server install seemed to fix the issue (I copied steamclient.dll, steamclient64.dll, tier0_s.dll, tier_s64.dll, vstdlib_s.dll and vstdlib_s64.dll). This was annoying to track down though, and I made a few other changes around the same time as well, so not 100% sure if that was the issue or not, but I feel confident it was.
> > 
> > 
> > Thanks for the suggestion but still no luck. I've just replaced these 6 files on a server that's not showing up on the list with copies from a working server, and the server is still not listed. Any other ideas I could try?
> 
> What's the date modified on the files you replaced yours with? Copying from a "working server" isn't guaranteed to work, as even with the broken files there is a 50% chance it picks UDP (and doesn't list), or websockets (and does list). The ones we updated ours with were from 10/13/21. I would recommend just making a fresh install and copying from there. Of course, after you replace the files, you need a full restart (you need the server stopped to even replace them in the first place).
> 
> If that still doesn't work, you could check u3ds/logs/connection_log_27015.txt for any obvious errors/issues, if it picks a server and times out, etc.

Copying over from a fresh Steam installation has worked 👍 
You're definitely right about the UDP vs. websockets, both of the servers I was having issues with were using UDP in the connection_log_27015.txt while all the visible servers were websockets. 

Thanks for the help Miku

**Comment by SDGNelson** [comment]
For what it's worth: in the next update the game will error during startup if the steamclient64.dll or steamclient.so files are out of date. I guess we will see whether it catches anything.

**Comment by AdamDN** [comment]
Just a thought, is this issue related in any way to whatever causes server to be randomly removed from people's favorites?
Even with Login tokens set, servers will randomly be removed from everyone's favorites list, usually after a routine server restart maybe once per month.
It has a noticeable impact on server population every time it happens so if there's a similar fix as simple as updating Steam files that would be great to know

**Comment by SDGNelson** [comment]
:confused: It is a mystery, maybe the game should track its own favorites list aside from using Steam favorites.

**Comment by AdamDN** [comment]
> :confused: It is a mystery, maybe the game should track its own favorites list aside from using Steam favorites.

If that's doable then I definitely think players would appreciate having a more reliable system in place. 
I've had people assuming that servers have been shutdown for days, simply because it's missing from their favorites and they haven't thought to re-search for the server.

Also, if favorites were being tracked then in the future you could add a way to sort the server list by most favorited, which would help new players find high quality servers rather than just busy/nearby ones. 
Not sure how well it would work in the long run, but it could potentially remove the need for third party server list websites.

**Comment by TH3AL3X** [comment]
> that with versions last modified 9/15/25, whenever the dedicated server picked UDP to connect to st

Did you fixed the problem?, i'm having the same issue

**Comment by TH3AL3X** [comment]
> > 😕 It is a mystery, maybe the game should track its own favorites list aside from using Steam favorites.
> 
> If that's doable then I definitely think players would appreciate having a more reliable system in place. I've had people assuming that servers have been shutdown for days, simply because it's missing from their favorites and they haven't thought to re-search for the server.
> 
> Also, if favorites were being tracked then in the future you could add a way to sort the server list by most favorited, which would help new players find high quality servers rather than just busy/nearby ones. Not sure how well it would work in the long run, but it could potentially remove the need for third party server list websites.

Remove or put a new "Login_Token" if you have a one
