### ISSUE TITLE
got a battleye ban

### ISSUE THREAD

**Issue by NotWaterScriptNhttp** [SmartlyDressedGames/Unturned-3.x-Community#2869]
ok so i got a battleye ban, the ban is HWID and i have it since 2019.
i got the ban by just jumping/running and getting into a car.
since it was 2 years ago i don't really remeber the details.
did i every cheat in unturned: No
do i have reverse/cheat programs: Yes
are they for unturned: No if you don't count (smi - sharp mono injector)
SID: 76561198868004957

**Comment by SDGNelson** [comment]
Sorry, only BattlEye support can check into the HWID ban: https://www.battleye.com/contact/
