### ISSUE TITLE
Re-investigate updating to a Unity LTS version

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#288]
### Update: With Apple's announcement that OpenGL will be deprecated this becomes higher priority, as more recent versions of Unity will have better Metal support

Currently updated to 2017.4.3f1 with initial errors that prevent compiling and crashes sorted out. The issues I'd noted down when attempting to update Unity to 2017.x previously appear to be fixed.

- [x] Automatically mark foliage materials to enable instancing 
- [x] Merge new standard shader changes into custom standard shader variants
- [x] Fix news image shading
- [x] Fix chat text field not registering input
- [x] Merge new speedtree shader changes
- [x] Remove GUILayer components
- [x] Fix issues preventing Win64 builds
- [x] Remove OSX32 build
- [x] Replace OSX32 depot with OSX64 depot
- [ ] Fix updating content bundles
- [ ] Fix Hawaii
- [ ] Fix Greece
- [ ] Remove Linux32 builds - Note: how does this impact the existing headless Linux32 build?
- [ ] Update bundling tools, specifically make sure loading materials from newer bundles works

**Comment by ChubbyQuokka** [comment]
Let’s do it!

**Comment by LuxarPL** [comment]
![investigate](https://user-images.githubusercontent.com/10651703/40273013-bbed98b0-5bb8-11e8-9fb2-40fdd1349dcd.png)

**Comment by DefCon42** [comment]
Asset bundles aren't cross version compatible if I recall correctly, so wouldn't this break literally every single workshop asset?

**Comment by aviadmini** [comment]
I think asset bundles are compatible up to 2018.1, at least I noticed that only when I used 2018.2 after 2018.1 they failed to work

**Comment by RoyIL** [comment]
Any updates? @SDGNelson

**Comment by SDGNelson** [comment]
This weekend was working on allowing multiple game assets to be loaded from the same parent asset bundle, and converted Greece and Hawaii to use this. Will make it easier for workshop creators to update their content in-bulk for 2017.4. Currently planning to have an opt-in beta for a while, but no idea when. Deadline at the latest for updating Unity is January 2019.

**Comment by gegtor** [comment]
> Remove Linux32 builds - Note: how does this impact the existing headless Linux32 build?

This could break Linux Servers because they still run on 32 bit unturned build

**Comment by aviadmini** [comment]
Surprise. It's possible to run 64 bit build on Linux (Ubuntu 16.04 & 18.04 tested)

**Comment by SDGNelson** [comment]
Working for the most part, will open individual issues now as-needed. Beta out today probably

**Comment by Kenzim** [comment]
unturned on ubuntu 14+ is a no go. no good mono support = broken unturned. hopefully not with this new unity, though.
