### ISSUE TITLE
Bug or Question: Server Error Logs

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2880]
![image](https://user-images.githubusercontent.com/48363842/140611337-6947647d-e12d-4ab0-b3e9-3c79020fd002.png)

I am not sure what it means, but putting it here may help me understand it.

![image](https://user-images.githubusercontent.com/48363842/140611488-c6eaee67-57df-41cc-a6f9-5891644c9bf5.png)

This is another new error log after the server restart.

I don't know much about understanding them, which is why I want anyone's help on why these 2 happen.

**Comment by GazziFX** [comment]
Can you post full stacktrace of second error, or drop logs

**Comment by rube200** [comment]
First error doesn't show much.
The second need the full trace but is related to rocketmod.
Some time ago I got similar error to that, the origin was my plugin changing the players cloths cause RM to change cloud event to print errors

**Comment by SDGNelson** [comment]
Something in PlayerInput is unexpectedly null, so if you can send me the Server_ (id) .log there might be an earlier exception indicating what caused it.
