### ISSUE TITLE
query doesnt work

### ISSUE THREAD

**Issue by arduinka55055** [SmartlyDressedGames/Unturned-3.x-Community#2881]
Hello, i got problem after update, query doesnt work. trying to connect to the server with python valve querier, but getting error
valve.source.NoResponseError: Timed out waiting for response.

this code worked previously, but now it is broken. fix this please!! it is critical for my discord bot existance.

using code from here: https://python-valve.readthedocs.io/en/latest/source.html#example
```py
import valve.source.a2s

SERVER_ADDRESS = (..., ...)

with valve.source.a2s.ServerQuerier(SERVER_ADDRESS) as server:
    info = server.info()
    players = server.players()

print("{player_count}/{max_players} {server_name}".format(**info))
for player in sorted(players["players"],
                     key=lambda p: p["score"], reverse=True):
    print("{score} {name}".format(**player))
```

also nmapping query port says it is closed

**Comment by GazziFX** [comment]
Switch query and connection port

**Comment by SDGNelson** [comment]
Sorry, GazziFX is correct that the latest update swapped the query and connection port. For more details: #2854

**Comment by arduinka55055** [comment]
thanks

**Comment by arduinka55055** [comment]
btw, this lib(valve.source.a2s) is dead, use this instead:  [https://github.com/Yepoleb/python-a2s](https://github.com/Yepoleb/python-a2s)
