### ISSUE TITLE
`formatPluginHotkeysIntoUIEffect` issues

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2882]
### First issue:
`formatPluginHotkeysIntoUIEffect` only works for static effects that are created using `EffectManager.sendUIEffect` with string parameters. It doesn't work for text dynamically changed by `EffectManager.sendUIEffectText`. Having that would help

### Second issue (minor):
All inputs are still being sent to server even when client is in menu, e.g. changing hotkeys

**Comment by GazziFX** [comment]
Its not an issue, you should call `EffectManager.sendUIEffectText` with gameobject name, which has text component attached

**Comment by aviadmini** [comment]
> Its not an issue, you should call `EffectManager.sendUIEffectText` with gameobject name, which has text component attached

I don't think you understood what I was talking about. This is specifically about formatting hotkey names into a non-static effect

**Comment by aviadmini** [comment]
### 1
Thanks a lot!

### 2
No, that observation was done on a fully legit client with BattleEye on a server that requires BattleEye. I currently use the provided delegate `PlayerInput.onPluginKeyTick` for reading inputs, but I'm considering using a patch instead. This way I could read all plugin hotkey inputs at the same time _once_ instead of having 5 callbacks, one for each code key.

##### How did I actually notice the issue:
I have a UI that lights up when player presses code hotkeys and it did just that while I was testing hotkey swap in the game controls menu. 

This actually brings up another thing I noticed - if client changes the hotkeys there's no way server know about it (which is good and should stay as is) and the effect which was on screen doesn't change hotkey value. I don't think it's worth investing time into because the case is too rare, but it's there.

P.S. shameless plug, but could you look at #2844 ?

**Comment by SDGNelson** [comment]
2. For the next update plugin keys will be false while rebinding in the controls menu. They are false while typing in a text field, but true when menus are open so that plugins have full control of custom menus.

**Comment by aviadmini** [comment]
@SDGNelson I assume that the keys sent as false now

#### Proposal

I'd like to request a small improvement - letting plugins know when keys are released forcefully instead of being initiated by player. 

#### Use case
A minigame that triggers an event on key release (player holds a key for some time and then releases it)

#### Implementation
A public field or property in PlayerInput (e.g. `PlayerInput.pluginKeysRestricted` would work)

#### Privacy considerations
I don't think that exposing that keys are forcibly not sent has any privacy issues 

Please let me know if this could be added

**Comment by educatalan02** [comment]
> @SDGNelson I assume that the keys sent as false now
> 
> #### Proposal
> I'd like to request a small improvement - letting plugins know when keys are released forcefully instead of being initiated by player.
> 
> #### Use case
> A minigame that triggers an event on key release (player holds a key for some time and then releases it)
> 
> #### Implementation
> A public field or property in PlayerInput (e.g. `PlayerInput.pluginKeysRestricted` would work)
> 
> #### Privacy considerations
> I don't think that exposing that keys are forcibly not sent has any privacy issues
> 
> Please let me know if this could be added

About Privacy.
Make sure keys are not logged when Chat is open, or the window isnt focused.

**Comment by surv0013** [comment]
> @SDGNelson I assume that the keys sent as false now
> #### Proposal
> 
> I'd like to request a small improvement - letting plugins know when keys are released forcefully instead of being initiated by player.
> #### Use case
> 
> A minigame that triggers an event on key release (player holds a key for some time and then releases it)
> #### Implementation
> 
> A public field or property in PlayerInput (e.g. `PlayerInput.pluginKeysRestricted` would work)
> #### Privacy considerations
> 
> I don't think that exposing that keys are forcibly not sent has any privacy issues
> 
> Please let me know if this could be added

I think it's not about privacy, because the keys are not sent anyway, if the user is not focused on the game window.

**Comment by aviadmini** [comment]
Well I actually tested the keys and here's what I figured out:

1. **Keys are still recorded in menus**. Guess this hasn't been implemented yet. I hope we can still access keys while in inventory and similar, but not while in game menu (e.g. controls)

2. Some keys have issues with registering properly when multiple plugin keys are pressed.

examples:
key 0 = `;`
key 1 = `'`
key 2 = `,`
key 3 = `.`
key 4 = `/`

if you press key 0+1+2+3 in that order key 3 will not get registered (false will be sent)

same with F1-F2-F3-F4-F5 - you can press f1 f2 f4 f5 together

I'm not sure if that's a game issue, unity issue, windows issue or my pc issue, but that's what happens here.

Code I used to spam the heck into the console:
```csharp
PlayerInput.onPluginKeyTick +=  _logger.LogInformation("key {K} state {S}", key, state);
```

P.S. I managed to get to register all 5 keys when I changed `.` binding to F1
