### ISSUE TITLE
Addition request: UI Effect parent's set to player game object transform

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#2886]
To better explain the title, I'm requesting that UI effect game object's parent be set to the player's game object. Currently, UI effect game object's do not have a parent and are positioned wherever Unity decides to position them. By adding this feature, it opens up the possibilities for devs to spawn effects which are local to the player. No existing functionality will be removed, but additional functionality will grant better abilities.

For my example, I'd like to create a minimap including spawning a camera above the player and having a UI display this camera's view. This camera would follow the player as the effect's parent would be set to the player.

**Comment by GazziFX** [comment]
I think it could be buggy because player has different gameobjects for Third and First person, which placed in root player gameobject.
Anyways, patch Assembly-CSharp.dll and try if it works as expected on local server, but you also need to add assembly hash to "/Bundles/Sources/Animation/appout.log" or patch ReadWrite.appIn on server

**Comment by fahrettinenes** [comment]
If this is added, really great things can be done. @SDGNelson

**Comment by IAmSilK** [comment]
> I think it could be buggy because player has different gameobjects for Third and First person.
Yes, but there is one parent for both of these which is the player's game object. This one can be used.

> Anyways, patch Assembly-CSharp.dll and try if it works as expected on local server
I've already tested using a client side module and it works great. There's no need to manually patch game files when there's a supported client side modding framework 😛.

**Comment by IAmSilK** [comment]
@SDGNelson thoughts?
