### ISSUE TITLE
[Bug Troubleshooting] Some quarry objects not visible while playing

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2887]
I made a map with a mine. The mine had several quarry objects inside of it like platforms, stairs, and supports. The mine also has a volume for no lighting. My current issue is that when I go into singleplayer the objects are not visible. Will follow up if I have further information on errors and such.

**Comment by Jdance-Media** [comment]
Workshop tab error logs says nothing about any errors regarding the quarry catwalk objects and the in-game logs doesn't show much connecting to it.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7550959/Client.log)

**Comment by SDGNelson** [comment]
Are they visible in your map in the level editor? If you can send the map zip to my email nelson@smartlydressedgames.com and where to look I can give it a try.

**Comment by Jdance-Media** [comment]
They are indeed visible in map editor. Will send map when at home!

**Comment by Jdance-Media** [comment]
[Colonial Roleplay.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7557575/Colonial.Roleplay.zip)

This is the collection of mods I use for this map (The are also the only mods I'm subbed to), sorry if that complicates things a bit: https://steamcommunity.com/sharedfiles/filedetails/?id=2657297503

**Comment by SDGNelson** [comment]
When I loaded the map in singleplayer I could see the quarry catwalks:
https://i.imgur.com/5rZCQxp.png

Are they inside a modded tunnel object? It might have the "interior culling" set hiding the objects.

**Comment by Jdance-Media** [comment]
I tried placing them in another tunnel that is the same in "Bree" and it worked there. I'm not really sure.

**Comment by SDGNelson** [comment]
What are they inside at the location they are not visible?

**Comment by Jdance-Media** [comment]
A modded cave object, by Sanders

**Comment by Jdance-Media** [comment]
Well it does indeed have something to do with that object, but I'm not sure why or how. Quarry objects were visible in another mine using the same object but not this one. Anyhow I removed the mine and subbed it for something else. Sorry about that. I've contacted Sanders about the issue and I'll be waiting for a response so he can fix it when he has time.
