### ISSUE TITLE
Camera Bug for Effect

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#2888]
hello, i made a minimap effect and managed to run it with the plugin. however, when i open the terrain transitions, the terrains appear black and besides, the roads always seem cut off due to the drawing distance. can you help with this issue?

images;

Terrain transition opened - ![image](https://user-images.githubusercontent.com/43903270/142345031-691d9fe6-4c69-4a0a-bb7b-553dff14626f.png)
Terrain transition closed (look at the roads) - 
![image](https://user-images.githubusercontent.com/43903270/142345141-4c2db9e0-a94f-4289-9175-c934bccca9bc.png)

My camera options;
![image](https://user-images.githubusercontent.com/43903270/142345480-3c804d5a-9288-4631-8069-7b210ccdd1a7.png)
![image](https://user-images.githubusercontent.com/43903270/142345496-355b47e6-696c-4ba1-a80e-37aca1d7e2bd.png)

**Comment by GazziFX** [comment]
For drawing distance you need to change QualitySettings.lodBias but its applies to all cameras.
Usage of second camera is big performance hit, you should better create scrollview with map texture and transform it with player position

**Comment by SDGNelson** [comment]
The terrain has different shader variants depending on forward/deferred mode and height transitions on/off, so I guess the minimap camera does not match the graphics settings render mode. I know some mods on the workshop have used a similar approach for minimaps, but I am not sure how they handle the render mode.

**Comment by fahrettinenes** [comment]
> For drawing distance you need to change QualitySettings.lodBias but its applies to all cameras.
> Usage of second camera is big performance hit, you should better create scrollview with map texture and transform it with player position

I don't use special module.

**Comment by GazziFX** [comment]
>  I don't use special module.

It can be done with unity components

**Comment by fahrettinenes** [comment]
> > I don't use special module.
> 
> It can be done with unity components

Can you add me from discord? **Fahrettin Enes#2827**
