### ISSUE TITLE
+20ms after recent update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2889]
Not sure what impacted this, but after todays update - latency jumped by 20ms. Have 2 servers on 2 different regions. Same issue on both.

And bouncing/knock-back works on all explosives. Maybe it would be wise to make it as an option for item or at least a configurable force for it

**Comment by SDGNelson** [comment]
Did you have authoritative movement disabled beforehand? There is increased performance cost now that it cannot be disabled, but 20ms seems like a rather large increase.

The default knockback speed is 10% of the player damage however it can be configured per-explosive with Explosion_Launch_Speed.

**Comment by baranmod** [comment]
yeah, had it disabled before update. Now on one server latency jumped from 60~ to 80~ and on another - from 120~ to 140~

**Comment by SDGNelson** [comment]
Are they custom barricades? It sounds like the Barricade.prefab (client) and Clip.prefab (server) do not match.

**Comment by baranmod** [comment]
yes, there is one mismatch after all. Thanks

**Comment by baranmod** [comment]
Explosion_Launch_Speed doesn't work for projectile weapons or am I doing something wrong? Tried to add on both: weapon and mag. It still knocking back according to weapon damage

**Comment by SDGNelson** [comment]
Sorry, for projectiles it is: Projectile_Explosion_Launch_Speed

**Comment by baranmod** [comment]
does it work for rail type guns too?

**Comment by SDGNelson** [comment]
Like with explosive bullets? Magazine assets can set Explosion_Launch_Speed as well.
