### ISSUE TITLE
Updated extras icons

### ISSUE THREAD

**Issue by thereis** [SmartlyDressedGames/Unturned-3.x-Community#289]
There are no images from recent added items. There is a plan to updated it?

**Comment by SDGNelson** [comment]
Good catch, will do

**Comment by N1GHTPATROL** [comment]
You should make a thingie to take pictures of all the guns loaded or something, it would be helpful for gun modders to have nice images of their guns.

**Comment by SDGNelson** [comment]
I've added the ability to take high res screenshots of workshop items by pressing F1 in the main workshop menu
