### ISSUE TITLE
Bypass_Hash_Verification

### ISSUE THREAD

**Issue by MichaelKol32** [SmartlyDressedGames/Unturned-3.x-Community#2891]
Bypass_Hash_Verification for clothes not working after update.

**Comment by SDGNelson** [comment]
Why do you want to disable file verification for clothes? It was added in case the clothing speed multiplier does not match between client and server.

**Comment by MichaelKol32** [comment]
To edit backpack capacity, armor and other stats.
Just to make custom balance.

**Comment by SDGNelson** [comment]
What I would recommend is to create new item assets, and then use the bundle override options to use the vanilla models. That being said I suppose I will add the Bypass_Hash_Verification option for clothes in a patch, sorry for the trouble.

**Comment by GazziFX** [comment]
> To edit backpack capacity, armor and other stats. Just to make custom balance for vanilla items.

If you edit from plugin it will not corrupt hash

**Comment by MichaelKol32** [comment]
Thanks for fix and for tips.
