### ISSUE TITLE
Kicking players when putting clothes or mod conflict after new update

### ISSUE THREAD

**Issue by ElRicki** [SmartlyDressedGames/Unturned-3.x-Community#2892]
Players get kicked after new update, when they put some clothes are kicked with this messages

![image](https://user-images.githubusercontent.com/75626024/142679905-ee5d1fd1-8d46-4ae6-9d7b-3664ac8ecc6d.png)

Also happens with vanilla clothes sometimes? I don't know, just updated the server and this started happening

**Comment by ElRicki7u7** [comment]
https://user-images.githubusercontent.com/75626024/142680562-967b24eb-dceb-470b-8012-0ff591eafe23.mp4

**Comment by SDGNelson** [comment]
This file integrity check was added in case the clothing speed multiplier does not match between client and server. If you run Steam validate on the server, or verify game files on the client it should repair whichever file has been modified.

**Comment by baranmod** [comment]
issue is with identical GUIDs for multiple items since Bypass_Hash_Verification seems to be inoperative now. I could be wrong though.

**Comment by SDGNelson** [comment]
@baranmod multiple assets cannot have the same guid (the game would assign a new random guid during load), but Bypass_Hash_Verification is available for clothes in the .1 patch soon.

**Comment by baranmod** [comment]
well, I had same GUID on few items and player was kicked with same error when he equipped those exact clothes

**Comment by SDGNelson** [comment]
@baranmod as in, you have multiple items that manually have the same guid assigned? In that case they should be updated with new (unique) guids.

**Comment by strongunturned** [comment]
Do I need to add Bypass_Hash_Verification to every garment?

**Comment by SDGNelson** [comment]
@strongunturned Have you modified the clothing files on your server? If not, you can validate files to ensure everything is using the latest version. If you have modified them then I would recommend making custom copies in order to avoid future issues, but enabling Bypass_Hash_Verification does work as a temporary workaround if only server-side properties like storage size and armor have been modified.
