### ISSUE TITLE
Can't open Unturned from steam on ubuntu 20.04

### ISSUE THREAD

**Issue by GirlGamer4521** [SmartlyDressedGames/Unturned-3.x-Community#2893]
I can't open Unturned from steam on ubuntu 20.04! Any suggestions?

**Comment by SDGNelson** [comment]
What happens when you try to launch the game? Have you been able to play it before but it only stopped after this update?

**Comment by GirlGamer4521** [comment]
> What happens when you try to launch the game? <
It just opens a blank(black) window and closes it in 5 secs or less
> Have you been able to play it before but it only stopped after this update? <
I've never played it before the update.

**Comment by GirlGamer4521** [comment]
Oops, sorry. Ignore the <> please!

**Comment by SDGNelson** [comment]
Could you send these two log files to nelson@smartlydressedgames.com please?

1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file to your email

1. Open ~/.config/unity3d/Smartly Dressed Games/Unturned
2. Attach the Player.log file to your email

**Comment by anushhkumar** [comment]
In case the game doesn't start on steam, you need to verify the Integrity of the game files. This can be done by Launch Steam, logging in to your account, and going to the Steam Library Folders. Now right-click on any game that you are having issues in starting launching before you choose the option of Properties. Then tap on the option of Local Files and press the option that states Verify Integrity of game files. Then wait for Steam to finish the file verification process. When Steam has verified the integrity of game files, try to open the Steam games that are having trouble and see if it is resolved or not. We hope that all those who are wondering, [why wont steam open](https://appuals.com/steam-wont-open/) will find this information helpful.
