### ISSUE TITLE
New bug with bounce charges

### ISSUE THREAD

**Issue by xlgamer** [SmartlyDressedGames/Unturned-3.x-Community#2894]
There is a bug with bounce charges that you can go all the way up to the sky limit and stay there for 2-3 seconds thats so overpowered you can raid skybases so easily you should limit the momentum like if u place 3 bounce charges you should go up like 300 units and if u place 5 bounce charges you should go 300 units too.

 İf u want to learn more about that bug contact with me 

discord/demise#5318

**Comment by SDGNelson** [comment]
This is intentional that the bounce charges should be fun and useful. The maximum fall speed is still the same as before however, and will probably be adjusted in the next regular update.
