### ISSUE TITLE
Explosive jump problem in PVE mod.

### ISSUE THREAD

**Issue by alsgur1638** [SmartlyDressedGames/Unturned-3.x-Community#2895]
In PVE mode, if use a any explosive weapon on the floor, body will rise into the air
If this isn't intended, can you fix it so it doesn't float?

https://user-images.githubusercontent.com/57933205/142718207-39d639ab-2e3c-4f09-8ffd-4af421e7e7de.mp4

https://user-images.githubusercontent.com/57933205/142718265-f2f50e8b-6a6d-4a35-b045-130b2129c78c.mp4

**Comment by SDGNelson** [comment]
For custom weapons if you would like to disable the explosion jumping you can add this line:
Explosion_Launch_Speed 0
For rocket launchers it is:
Projectile_Explosion_Launch_Speed 0
