### ISSUE TITLE
[Feature Request] Movement_Speed_Zero_Multiplier

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2896]
I noticed that you added a Movement_Speed_Multiplier in the most recent update. This is very helpful in creating the Power Armor from fallout in a more accurate and balanced way! However, I would like to request a per-item option for an override to the original number at zero percent. This would allow for the power armor to be "dead" at zero percent "charge" and give the player a dramatic slowdown effect. I see it as being the original speed multiplier at 1% and snapping to the Zero percentage at 0%, rather than slowly declining like the Armor value.

Thanks,
- Dumfoozle

**Comment by Meassas-GraphicalDesign** [comment]
Would be n great addition!

**Comment by DerEnte** [comment]
Honestly, I don't know if this really necessary, but you know, I support this

**Comment by aviadmini** [comment]
At this point just make a plugin for that
