### ISSUE TITLE
[Small Bug] Weird sounds and weird movement, when you are on top of a car

### ISSUE THREAD

**Issue by 01-Feli** [SmartlyDressedGames/Unturned-3.x-Community#2898]
With the new multiplayer movement improvements, there some strange things that happens when you on top of a car

Here is a video: https://youtu.be/2KY6J91xubk

**Comment by TH3AL3X** [comment]
For some reasons something of the "gravity" got changed, because players for some reason can glide in the air when they jump, it's very strange

**Comment by SDGNelson** [comment]
It looks like the collision on the hood of that Sedan does not match between client and server. I will make a note to check that particular model.

**Comment by SDGNelson** [comment]
Almost forgot to double-check this, but the sedan client and server models do indeed match fortunately. The vehicle movement in multiplayer is lower precision than barricades and structures so there is more room for misprediction, but I have been laying the groundwork to support moving relative to vehicles over the past few months which will help resolve it.

**Comment by SDGNelson** [comment]
(closing since the walking on moving vehicles is unrelated)
