### ISSUE TITLE
[Critical Bug] Velocity Bug

### ISSUE THREAD

**Issue by connorgillespie** [SmartlyDressedGames/Unturned-3.x-Community#2899]
With the new velocity changes, a few colleagues and I discovered a **critical movement bug that allows for practical instant teleportation across the map with materials that take mere minutes to acquire.**

Instead of releasing this bug to the public, I sent you an email at nelson@smartlydressedgames.com. You may want to check this as soon as possible. 

Sincerely, 
Fireside https://steamcommunity.com/id/firesidettv/
Loaf https://steamcommunity.com/id/Calerom/
AriJN https://steamcommunity.com/id/AriFX/

**Comment by SDGNelson** [comment]
Replying to the email in a minute.
