### ISSUE TITLE
Bicycle Can't Be Damaged by Low Caliber

### ISSUE THREAD

**Issue by AnimaticFreak** [SmartlyDressedGames/Unturned-3.x-Community#29]

**Comment by V1CeNtE** [comment]
Lol the bicycle looks immune

**Comment by glxygmng** [comment]
This doesn't appear to have been "fixed"

It's kind of ridiculous how civilian vehicles can be destroyed by chainsaws, mini-gun, etc. but a bicycle is invincible to a mini-gun.

It also clutters the vehicle cap as people don't bother to waste high caliber ammunition to remove bicycles.

**Comment by SDGNelson** [comment]
Racking my brain I have no idea how/why it has those current values. 🤔 
Will be correctly marked as vulnerable to low caliber in the next update!
