### ISSUE TITLE
Movement Feedback

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#2900]
I've been messing around with the new momentum added in the most recent update, but something's been bugging me. 

It strikes me as odd that the player still isn't affected by gravity. When falling the player is immedietly at terminal velocity. If the player jumps and hits their head they cling to the ceiling for a bit, still being pushed up. It may be more trouble then it's worth (I assume the Player's movement is an extension of Unity's inbuilt player controller or some odd homebrew setup that doesn't utalize rigidbodies) but it would be nice if this could get tweaks in comming updates to make the movement feel better all around.

**Comment by SDGNelson** [comment]
The player is affected by gravity, but gravity on players is higher, and the terminal velocity limit is quite low. Initially this was changed in the update but was reverted at the last minute, but will probably be changed in the next update.
