### ISSUE TITLE
Can't launch unturned due to missing file: Unturned.Exe

### ISSUE THREAD

**Issue by BobohZirka** [SmartlyDressedGames/Unturned-3.x-Community#2905]
![bo](https://user-images.githubusercontent.com/95142100/143690868-0e75eb42-6ec7-4f29-95fb-2d5952f7d7d4.PNG)
![o](https://user-images.githubusercontent.com/95142100/143690871-88928348-ce3a-4f8d-994f-aa17df1b033f.PNG)

**Comment by BobohZirka** [comment]
I do not even have a file called Unturned.Exe, but I do have an Unturned_BE

**Comment by GazziFX** [comment]
Check files integrity

**Comment by SDGNelson** [comment]
Do you have any anti-virus/firewall software installed? Usually this means the game exe/dlls were deleted by those programs.
