### ISSUE TITLE
Outdated ExampleServer.bat remarks

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2910]
The remarks in the U3DS's ExampleServer.bat regarding port forwarding appear to be outdated. Also, GSLTs are likely relevant to hosts nowadays as well, and should be mentioned too. Can we update the below text, and/or link to U3-Docs?

```bat
rem Running multiple internet servers simultaneously requires specifying different ports using the Port command. Unturned will
rem use the specified port for game traffic, port + 1 for server list queries and port + 2 for the Steam backend. Recommended
rem port values are 27015 for the first server, 27018 for the second server, so on and so forth. These can be set as a line
rem in Commands.dat e.g. "Port 27018" (without quotes) or on the command-line "-Port/27018" (without quotes).
```

https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md

**Comment by SDGNelson** [comment]
Good catch, thank you! I will change that for the next update.
