### ISSUE TITLE
[Feature Request/Fix] Make it so that projectile weapons read their explosion effect ID from the magazine asset

### ISSUE THREAD

**Issue by benvalkin** [SmartlyDressedGames/Unturned-3.x-Community#2911]
This is a small feature request for if you are ever going to rewrite projectiles.

Currently, it's not possible to make projectile weapons have different explosion/impact effects depending on what magazine if loaded. This works for normal bullet ranged weapons by specifying an effect ID for `Explosion` or `Impact` in the magazine asset's .dat file, but projectile ranged weapons seem to only read the effect from the weapon's .dat file.

It would be nice if the explosion effect for projectile weapons could also read from the magazine asset's .dat file in some way or another. This way we could create rocket launchers/tanks/aircraft with different ammo types that each have different explosion effects.

**Comment by SDGNelson** [comment]
Sure this would be an easy change because projectile weapons do not use the magazine's explosion effect for anything at the moment.
