### ISSUE TITLE
playerUpdateHealth event not work for bleeding

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#2912]
I made a custom hud with RM framework, but unturned native event is not working for bleeding.

![image](https://user-images.githubusercontent.com/43903270/144040343-27726270-bf39-4fdb-b2b6-80906cec7c58.png)

my dirty code;

```cs
            player.Player.life.onHealthUpdated = (health) =>
            {
                // some shitty senduieffectvisibility codes
            };
```

**Comment by GazziFX** [comment]
Why not `PlayerLife.OnTellBleeding_Global`?

**Comment by fahrettinenes** [comment]
> Why not `PlayerLife.OnTellBleeding_Global`?

Why not `PlayerLife.OnHealthUpdated`?

**Comment by GazziFX** [comment]
Because it stand for HP value change, but you need bleeding event

**Comment by fahrettinenes** [comment]
> Because it stand for HP value change, but you need bleeding event

The bug here is that the OnPlayerUpdateHealth event is not fired whenever bleeding drops health. Already I know, I should use BleedingUpdate method for get it. But I can't getting new health when bleeding updated to health.

**Comment by GazziFX** [comment]
Should be ok IDK
```csharp
if (this.isBleeding)
{	
				if (simulation - this.lastBleed > Provider.modeConfigData.Players.Bleed_Damage_Ticks)
					{	
					      this.lastBleed = simulation;						EPlayerKill eplayerKill4;
              this.askDamage(1, Vector3.up, EDeathCause.BLEEDING, ELimb.SPINE, Provider.server, out eplayerKill4);
					}	
}
```

**Comment by fahrettinenes** [comment]
> Should be ok IDK
> 
> ```cs
> if (this.isBleeding)				{					if (simulation - this.lastBleed > Provider.modeConfigData.Players.Bleed_Damage_Ticks)					{						this.lastBleed = simulation;						EPlayerKill eplayerKill4;						this.askDamage(1, Vector3.up, EDeathCause.BLEEDING, ELimb.SPINE, Provider.server, out eplayerKill4);					}				}
> ```
> 
> P.S. my phone is bad at code formatting

looks like bad. so, why OnHealthUpdated not work for bleeding?

**Comment by GazziFX** [comment]
Maybe try `PlayerLife.OnTellHealth_Global` instead of `OnHealthUpdated`?

**Comment by fahrettinenes** [comment]
> looks like bad. so, why OnHealthUpdated not work for bleeding?

ill try, but as i said. bleeding is changing health value, but event is not invoking. i can make this with another events or harmony, but thats a bug and it should be fix.

**Comment by SDGNelson** [comment]
onHealthUpdated is an older event only called on the client for the UI, whereas OnTellHealth_Global was added for RocketMod backwards compatibility during the RPC rewrite and is called on the server.
