### ISSUE TITLE
Unturned Gold Dlc bug

### ISSUE THREAD

**Issue by Just73339** [SmartlyDressedGames/Unturned-3.x-Community#2914]
first of all good day nelson
I'm a Turkish Unturned Player
I wanted to buy gold dlc on my side account while there are ready Steam Discounts.
yes i bought gold dlc from another account
and then I returned the gold dlc because I wanted to buy another game and it was accepted.
I looked at my inventory and what should I see The items given with the gold dlc are in my inventory
In-game gold dlc icon is also present
but actually there is no gold dlc !
this needs to be fixed.
sorry for my bad english i use a translator.
If you want more detailed information, you can reach me quickly from these addresses.
https://steamcommunity.com/id/god_of_ak-47/
Discord : Just#7330

In-game images
![steamacc1](https://user-images.githubusercontent.com/95298081/144073343-268e3312-b3da-4d31-b320-8d33f6470f51.JPG)
![steamacc2](https://user-images.githubusercontent.com/95298081/144073358-0cb28927-8682-43d3-b2f3-3b2509a3d8c5.png)
![steamacc3](https://user-images.githubusercontent.com/95298081/144073372-6d567cfd-f3ed-45b5-9c9d-ce06897e97dd.png)

**Comment by SDGNelson** [comment]
Thanks for the report, but this is a limitation because the gold DLC predates the Steam inventory service promo items. You can keep the gold items, or delete them if you really want.
