### ISSUE TITLE
Barbedwire Fence is more expensive than Ornamental Fence

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2915]
The Barbed Wire Fence has a different crafting cost than the Ornamental Barbed Wire Fence. It is worth taking a look at as we now enter December.

Currently, the normal fence requires **five (5)** barbed wire. Comparatively, the festive variant requires **three (3)** ornamental barbed wire. Note that the crafting recipes for barbed wire is the same regardless of it being normal/festive, and that the fences are identical in terms of stats.

**Comment by SDGNelson** [comment]
Whoops, good catch, thanks! Fixed for the next update.
