### ISSUE TITLE
Improving game chat

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#2916]
An excellent update for both PVE servers, where players often chat in chat, and for RP servers and possibly other main servers.

1. Extending the chat width-length on the screen
2. Increasing the length of the character's reply in the chat. Now, when a certain number of characters is reached, a transition to a line with a large space between the messages in the chat appears, which causes great discomfort when communicating with other players.

**Thank you for the attention!**

**Comment by SDGNelson** [comment]
Yes ideally these will happen, but the limiting factor is vertical layout support from the UI. Most likely after UIToolkit.

**Comment by FireRain4** [comment]
Thanks
