### ISSUE TITLE
Zombie Sounds Turn Off

### ISSUE THREAD

**Issue by FylRon** [SmartlyDressedGames/Unturned-3.x-Community#2917]
Hi, I wanna ask if there is any way of turning off the sound of Zombie (globally on Server).
For personal use.
We wanna make Zombies as rushing NPCs, so for more Experience we want to get rid of those Zombie Sounds.

**Comment by GazziFX** [comment]
Why not use virtual players like on my server?

**Comment by SDGNelson** [comment]
Sorry, there is not currently an option for this, and it is relatively unlikely to be added. Ideally animals will get pathfinding improvements eventually to be more useful for this kind of thing.
