### ISSUE TITLE
[Feature Request] Custom map markers for plugin creators

### ISSUE THREAD

**Issue by DerSpeedMann** [SmartlyDressedGames/Unturned-3.x-Community#2921]
I and other plugin creators would love an option to place custom markers on the map (The UI Map of the palyer).
The option to add custom icons and text would be nice as well, so people could make crate markers for airdrops, a skull marker for deaths, and so on.
I bet lots of plugins would love to include custom markers if it’s possible.

An additional option to show or hide it from compass would be also appreciated.
Because people where having problems with big groups (12-20 player) and people were losing 20-40 fps with their hud on from the compass markers.

**Comment by DanielWillett** [comment]
It would be nice to have a way of adding and removing to and from a list of global markers that aren't associated with players. Right now you have to override a player's marker or create dummy players, which brings a whole host of more issues. As he mentioned if we could have the ability to hide it from the compass it would be appreciated... I was the person he mentioned having problems with large groups creating lag ([Issue](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2810)). It would be fairly easy to implement, just a replicated list of global markers that you can remove via index or some other key with rpcs. Custom icons would also be cool, to have different types of markers (_A bank is being robbed, check your map_, then there's a bank icon on the map or something). Just throwing out ideas, but at least having the markers would be nice, even if icons didn't make it in.

**Comment by DanielWillett** [comment]
If you plan on doing this it may be easier to consolidate custom markers and player markers into a universal list of some kind of marker structure with a group id that can be Nil. If there's a group ID then compare it to the player's group id, else display it anyways. (and don't replicate markers of out-of-group players until they join a group). Another vulnerability (although not that important) is that everyone currently has the position of any player's marker, even if they're not in the group, it's just not displayed. In my last message, I mentioned using indexes like barricades but if we could use a custom key (like effects) instead to reference them it would be better so we could safely send markers to only some players.

**Comment by aviadmini** [comment]
Good stuff here. I especially like the idea of controlling which markers are visible to players and which are not. 
This whole thing might require a rework of compass/markers but might as well go for it while figuring out compass performance drops ;)

**Comment by DanielWillett** [comment]
Any update on this?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
