### ISSUE TITLE
Deleting navmesh then baking makes secondary terrain invisible

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#2922]
This bug was first reported by clue and the California team. I've verified that the bug exists and can be easily reproduced, and isn't map-specific.

**Issue:** In the legacy editor: deleting a navmesh, and then baking navigation (without creating a new navmesh first) causes Secondary Terrain to visually disappear.

**Workarounds:** Until the level is reloaded, secondary terrain is invisible, and the secondary terrain tool does not function. Alternatively, creating a new navmesh and then baking navigation will also fix the issue.

**Comment by SDGNelson** [comment]
Thanks, it looks like this is because it is baking the deleted navmesh, will fix for the next update.
