### ISSUE TITLE
Building Problem.

### ISSUE THREAD

**Issue by Ymabert** [SmartlyDressedGames/Unturned-3.x-Community#2923]
reduce the wood and the various materials useful for building walls, stairs, doors ... and therefore also reduce the quantity that is found for example by destroying a tree.  By doing so, if it is possible, you will have more space in the inventory, because I cannot understand the sense of having 9 wooden planks occupying 2 which when transformed into a piece of furniture occupy 4 (2x2), in my opinion this is a small problem on the balance of the materials used / constructions created ratio, so if possible solve it, even with other methods, perhaps more innovative or balanced than the one I recommended.

> ###

**Comment by SDGNelson** [comment]
I agree it is not great as-is, and intend to gradually rework e.g. item stacking, new crafting system, better placement system, etc.

**Comment by Ymabert** [comment]
@SDGNelson I would have liked to have more opinions, but to have one that gives me reason that something needs to change is already a lot, the developers I hope that at least they listen and above all they do not close these types of suggestions since if I write one I just want to accumulate as many comments as possible that they help me improve the suggested idea, so as to suggest it again but refined, so it would make more sense to close a suggestion and it would also help.
