### ISSUE TITLE
I cant download mods to my server, what can I do?

### ISSUE THREAD

**Issue by HairyNugg** [SmartlyDressedGames/Unturned-3.x-Community#2924]
When I try to start the server with elver in this case, it starts normal, but when it gets to the downloading part, it gives me this error

Downloading workshop item: 2136497468
Download workshop item 2136497468 failed, result: k_EResultFail

I dont know if this error has been already solved or if there is a solution, but please I would like to know how to solve it.

**Comment by SDGNelson** [comment]
Sorry for the trouble. If you can attach the log file from steamcmd/logs/workshop_log.txt there might hopefully be a more detailed error.

**Comment by HairyNugg** [comment]
There doesnt seem to be any kind of issue on that log, as it has been last updated 2 months ago
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7677809/workshop_log.txt)
.

**Comment by SDGNelson** [comment]
Sorry, workshop_log.txt might actually be in U3DS/logs or Servers/ (name) /Workshop/Steam/logs. Mine has logs in a bunch of places from the past few years because it has not been wiped.

**Comment by HairyNugg** [comment]
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7677853/workshop_log.txt)
 Hopefully this is the one.

**Comment by SDGNelson** [comment]
Thanks. It looks like the error message is:

Update canceled: File commit failed: staging file is missing (Missing update files) "E:\Steam\steamapps\common\U3DS\Servers\Default\Workshop\Steam\downloads\304930\2136497468\Elver\Bundles\Main\Animals\Metro_Chicken\English.dat"
Updating workshop item details failed with Access Denied

Maybe something is preventing Steam from writing the file? For example do you have any anti-virus software installed?

**Comment by HairyNugg** [comment]
I only have the default one for windows, I belive its windows security or something like that.

**Comment by HairyNugg** [comment]
Weird, I even tried turning it off while I set up the server and it gives the same result.

**Comment by SDGNelson** [comment]
Maybe if you try running the server as administrator? (should not usually be required, but maybe worth trying)

**Comment by HairyNugg** [comment]
Sadly it doesnt fix the issue.

**Comment by SDGNelson** [comment]
Hmm trying a different angle: does a different workshop file work? i.e., is it specifically Elver that is having problems downloading?

**Comment by HairyNugg** [comment]
Yeah, I tried downloading another mod and it worked correctly.

**Comment by SDGNelson** [comment]
Interesting, maybe the access denied error is a red herring. Perhaps something downloaded for Elver got into a bad state, e.g. corrupted cache file, and cannot recover. I am not exactly sure where this would be - if you look in U3DS\Servers\Default\Workshop\Steam\downloads\304930\2136497468 has it already downloaded anything? The nuclear option could be to delete U3DS\Servers\Default\Workshop\Steam entirely and see what happens.

**Comment by HairyNugg** [comment]
It doesnt go past /downloads, there isnt any number folder in there, I am going to go with the nuke option and just redownload U3DS.

**Comment by HairyNugg** [comment]
Wait, there folder with the numbers were in steam/content, and it has a folder named Elver and a file named "Map.meta"

**Comment by SDGNelson** [comment]
Okay, try deleting U3DS\Servers\Default\Workshop\Steam (not U3DS) and let's see what happens.

**Comment by HairyNugg** [comment]
Wow, it actually worked, now it lets me install elver and set it as a map, thanks a lot.

**Comment by SDGNelson** [comment]
What a relief! Happy to hear you got it sorted out. Sorry that it took so long to arrive at a solution. I will keep this post in mind in case anyone runs into a similar problem in the future.
