### ISSUE TITLE
New issues after update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2927]
Most players are stucking on queue #1, exceptions spamming in logs:
https://pastebin.com/ua17RGFq

**Comment by DiFFoZ** [comment]
![image](https://user-images.githubusercontent.com/48765566/145620818-24bf6932-dc8c-43c3-be82-c21c7fb89adb.png)
On my servers, all players look up for some reason

**Comment by aman7** [comment]
is chat working for you guys?

**Comment by SDGNelson** [comment]
sorry not sure yet why this was not caught, uploading quick test patch and should be fixed ASAP

**Comment by baranmod** [comment]
Seems like patch didn't fix the issue

**Comment by SDGNelson** [comment]
@baranmod do you have any patches on PlayerClothing save/load? Files with version number 6 save/load clothing with 16-bit asset id, whereas version 7+ now save/load guid.

**Comment by baranmod** [comment]
yeah, I guess some plugins will have to be updated

**Comment by SDGNelson** [comment]
@baranmod Okay, fingers crossed, let me know if there are any issues after they are patched. I have kept the API as backwards compatible as possible - e.g., all the ushort getters and setters work still - but unfortunately it would be impossible to improve the code base if officially supporting patching those kinds of methods. Eventually I would like to rewrite the save/load in general and allow plugins to append custom data.
