### ISSUE TITLE
My Server Workshop Mods are stuck in queue after update

### ISSUE THREAD

**Issue by ibrahimozkn** [SmartlyDressedGames/Unturned-3.x-Community#2928]
![image](https://user-images.githubusercontent.com/51259479/145621056-a2a83d56-336c-4f69-94aa-dc6c521ece7d.png)

**Comment by ibrahimozkn** [comment]
My workshop_log

`[2021-12-10 21:38:47] [AppID 304930] Loaded workshop items in "C:\SteamCMD\steamapps\common\U3DS\Servers\SethS2\Workshop\Steam" (112 installed, 112 needed)
[2021-12-10 21:38:48] [AppID 304930] Updating workshop item details failed with Access Denied`

**Comment by SDGNelson** [comment]
Based on the "access denied" error: maybe something is blocking it from writing the files? Or maybe something one of the workshop files is private?

**Comment by ibrahimozkn** [comment]
> Based on the "access denied" error: maybe something is blocking it from writing the files? Or maybe something one of the workshop files is private?

This happened after the update. I have been running my server with these mods for like 3 weeks

**Comment by SDGNelson** [comment]
If you can attach workshop_log.txt from the logs folder there might be a more detailed error message

**Comment by ibrahimozkn** [comment]
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7694926/workshop_log.txt)
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7694931/workshop_log.txt)

**Comment by ModernMoGamer** [comment]
Experiencing this issue on Linux, With workshop mod: [1731384487](https://steamcommunity.com/sharedfiles/filedetails/?id=1731384487) and [933868371](https://steamcommunity.com/sharedfiles/filedetails/?id=933868371)

Both have required workshop mods, which I believe is the issue. As long as the server doesn't have workshop with additional required workshop, then it will boot fine.

**Comment by ibrahimozkn** [comment]
> Experiencing this issue on Linux, With workshop mod: [1731384487](https://steamcommunity.com/sharedfiles/filedetails/?id=1731384487) and [933868371](https://steamcommunity.com/sharedfiles/filedetails/?id=933868371)
> 
> Both have required workshop mods, which I believe is the issue. As long as the server doesn't have workshop with additional required workshop, then it will boot fine.

You are totaly right! Thank you so much :) Bitcoin mod was having required workshop.

**Comment by ADXServers** [comment]
no need to remove them, just add them like this in the ignore_childer_file_ids

  "Ignore_Children_File_IDs": [
    1731384487,
    933868371
  ],

**Comment by SDGNelson** [comment]
Thanks for the catch @ModernMoGamer! Unsure yet whether this is a Steamworks 1.52 problem or whether maybe how the game uses those APIs, but as a workaround adding the file ID to the main list or ignoring children should work, and I will see about getting this sorted in a patch.

**Comment by SDGNelson** [comment]
Sorry for the multiple patches, I have now released the .2 patch which:
1. Replaces bind address Steamworks parsing with simple IPv4 parse until the cause for the Steamworks crash is sorted out.
2. Has a bandaid fix for querying nested workshop files - seems to be working fine now.
