### ISSUE TITLE
Server unplayable, everything broken. 

### ISSUE THREAD

**Issue by ElRicki7u7** [SmartlyDressedGames/Unturned-3.x-Community#2929]
Players can't get into vehicles, interact with other players (they can move only clientside, other players don't see them moving). In avarage... every plugin broken. Flying players. The server is in linux, and have been crashing, I found the plugin involved in that and removed, but when I started the server I found that happening. What a mess. Any solution?? Thanks for your attention. I’m looking forward to your reply.

**Comment by SDGNelson** [comment]
Sorry for the trouble, the .1 patch up a few minutes ago has a quick fix but I am checking into the other reports.
