### ISSUE TITLE
My servers on Windows dosnt work after update

### ISSUE THREAD

**Issue by dpr3000** [SmartlyDressedGames/Unturned-3.x-Community#2930]
Full log: https://pastebin.com/nC3WRFit

After update i got this error

> [2021-12-10 21:34:12] Initializing ServerTransport_SteamNetworkingSockets
> [2021-12-10 21:34:12] NullReferenceException: Object reference not set to an instance of an object
> [2021-12-10 21:34:12] Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ParseString (Steamworks.SteamNetworkingIPAddr& pAddr, System.String pszStr) (at <1a46152f1b124948af30484576ed09b6>:0)
> SDG.NetTransport.SteamNetworkingSockets.ServerTransport_SteamNetworkingSockets.Initialize (System.Action`1[T] connectionFailureCallback) (at <6b88a194790d4fd79c1d175c114aa726>:0)
> SDG.Unturned.Provider.openGameServer () (at <6b88a194790d4fd79c1d175c114aa726>:0)
> SDG.Unturned.Provider.host () (at <6b88a194790d4fd79c1d175c114aa726>:0)
> SDG.Unturned.Assets+<init>d__105.MoveNext () (at <6b88a194790d4fd79c1d175c114aa726>:0)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c58bc064d0ed420cb832da9d6d1cf9b6>:0

After it, console spams this and server became unreachable

> [2021-12-10 21:34:12] NullReferenceException: Object reference not set to an instance of an object
> [2021-12-10 21:34:12] SDG.Unturned.Provider.listenClient () (at <6b88a194790d4fd79c1d175c114aa726>:0)
> SDG.Unturned.Provider.listen () (at <6b88a194790d4fd79c1d175c114aa726>:0)
> SDG.Unturned.Provider.Update () (at <6b88a194790d4fd79c1d175c114aa726>:0)

That occurs only on servers with Windows, on Linux all fine

**Comment by SDGNelson** [comment]
Sorry for the trouble: it looks like a bug parsing the "bind" address in the new Steamworks version. For the meantime if you are able to disable the bind command it should work properly, and I will see about fixing or replacing the parse method.

**Comment by dpr3000** [comment]
thanks, that helps

**Comment by benvalkin** [comment]
@SDGNelson is the bind command only used in Commands.dat? My server (hosted on a hosting service) isn't using the bind command in Commands.dat, but it's also having this issue/

**Comment by MiKrOSaLeM** [comment]
> Sorry for the trouble: it looks like a bug parsing the "bind" address in the new Steamworks version. For the meantime if you are able to disable the bind command it should work properly, and I will see about fixing or replacing the parse method.

I don't have that command in commands.dat

**Comment by SDGNelson** [comment]
If you are getting this exception without the command could you attach your Server_ (id) .log file please? Will take a look.

**Comment by DanielWillett** [comment]
[Server_Saved.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7695100/Server_Saved.log)
Same issue

**Comment by SDGNelson** [comment]
Sorry for the multiple patches, I have now released the .2 patch which:
1. Replaces bind address Steamworks parsing with simple IPv4 parse until the cause for the Steamworks crash is sorted out.
2. Has a bandaid fix for querying nested workshop files - seems to be working fine now.
