### ISSUE TITLE
Steamworks

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2931]
How is it that you made the same mistake again that you made the last time you changed Steamworks library?
![image](https://user-images.githubusercontent.com/17459138/145625624-8e4bbfe3-e1bd-4aa9-9341-9b1b73cb1b4a.png)

P.S. Update Rocket.Unturned.dll, plz

P.S.S. I apologize for creating a topic here, not in LDM, it's just that the activity is higher here.

**Comment by SDGNelson** [comment]
Unturned automatically redirects references to Steamworks.NET.dll to com.rlabrecque.steamworks.net.dll, so everything should continue to load properly. The reason I did not update the LDM repo yet was to ensure the game handled the rename properly. (com.rlabrecque.steamworks.net is the official name Riley gave it, whereas Steamworks.NET.dll is the name I gave it when converting to assembly definitions)

**Comment by DanielWillett** [comment]
Its a new assembly name `com.rlabrecque.steamworks.net.dll`

**Comment by TaPok11211** [comment]
> Unturned automatically redirects references to Steamworks.NET.dll to com.rlabrecque.steamworks.net.dll, so everything should continue to load properly. The reason I did not update the LDM repo yet was to ensure the game handled the rename properly. (com.rlabrecque.steamworks.net is the official name Riley gave it, whereas Steamworks.NET.dll is the name I gave it when converting to assembly definitions)

And how fix it? I can't create plagin

**Comment by SDGNelson** [comment]
@TaPok11211 which error are you getting? If you pull the newest version of LDM it has the renamed Steamworks.NET dll.

**Comment by TaPok11211** [comment]
> @TaPok11211 which error are you getting? If you pull the newest version of LDM it has the renamed Steamworks.NET dll.

I create issue with problem, but I can give screenshoot
![Сним2ок](https://user-images.githubusercontent.com/57183585/145694030-eef555bb-2a30-44b7-8ac1-779b3c28eb37.PNG)
