### ISSUE TITLE
Server not opening after update

### ISSUE THREAD

**Issue by andreygamer74** [SmartlyDressedGames/Unturned-3.x-Community#2932]
Caught fatal signal - signo:11 code:1 errno:0 addr:0x55fe1651e9f0
Obtained 18 stack frames.
#0  0x007f99d5e263c0 in funlockfile
#1  0x007f99d54f2561 in mono_set_break_policy
#2  0x007f99d54dcfa4 in _init
#3  0x007f99d54dea1c in _init
#4  0x007f99d54e2712 in mono_print_method_from_ip
#5  0x007f99d54e30ac in mono_print_method_from_ip
#6  0x007f99d5653390 in (Unknown)
#7  0x007f99d565423d in (Unknown)
#8  0x007f99d69b9502 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#9  0x007f99d69b789a in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#10 0x007f99d699d6f7 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned long, unsigned int const&)
#11 0x007f99d6741c8d in std::vector<float, std::allocator<float> >::_M_fill_insert(__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, unsigned long, float const&)
#12 0x007f99d68a4d0e in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#13 0x007f99d68a4d51 in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#14 0x007f99d68a528a in int* std::_V2::__rotate<int*>(int*, int*, int*, std::random_access_iterator_tag)
#15 0x007f99d6a0fa8e in PlayerMain(int, char**)
#16 0x007f99d5c460b3 in __libc_start_main
#17 0x0055faa261b699 in _init
./ServerHelper.sh: line 34: 2786625 Aborted                 (core dumped) ./Unturned_Headless.x86_64 -batchmode -nographics "$@"

**Comment by SDGNelson** [comment]
Does it work if you temporarily disable your plugins? The reason I ask is there was a similar callstack where the crash seemed to be caused by a plugin injecting/patching Unturned code.
