### ISSUE TITLE
Player teleports a bit when hitting objects

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2933]
https://user-images.githubusercontent.com/48765566/145631307-62282b1a-ba5d-45cd-8155-2ed11ab47749.mp4

upd: that also works on the ground

https://user-images.githubusercontent.com/48765566/145631519-304d63bc-6038-4551-b2f3-c1f0df0bd986.mp4

**Comment by SDGNelson** [comment]
That is bizarre... It looks like maybe something on the modded item has collision on the server that is pushing the player? Does it happen for you when you shoot a vanilla gun? (with vanilla gun it did not happen for me)

**Comment by DiFFoZ** [comment]
Tested with Avenger (1021) and still teleports a bit

**Comment by SDGNelson** [comment]
Tried reproducing now with Avenger shooting bedroll underwater but no luck. Does anything else come to mind that might be different between our setups?

**Comment by GazziFX** [comment]
It might caused by my UAC its not updated on market yet

**Comment by DiFFoZ** [comment]
Yep, Gazzi was correct. I'll close the issue
