### ISSUE TITLE
Server does not start since update

### ISSUE THREAD

**Issue by AlerDerp** [SmartlyDressedGames/Unturned-3.x-Community#2936]
Since the update i cant start my server.
Tried without plugins etc. but nothing helps.
I get the following error:
`src/tier1/fileio.cpp (4914) : Assertion Failed: s_bExit
src/tier1/fileio.cpp (4914) : Assertion Failed: s_bExit
src/tier1/fileio.cpp (4916) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (4916) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
Bad thread localsrc/tier1/fileio.cpp (4976) : Assertion Failed: CFileWriterThread already exited
src/tier1/fileio.cpp (4976) : Assertion Failed: CFileWriterThread already exited
Bad thread localBad thread localsrc/tier1/fileio.cpp (4976) : Assertion Failed: CFileWriterThread already exited
src/tier1/fileio.cpp (4976) : Assertion Failed: CFileWriterThread already exited
Bad thread local[?1l>[39;49m`

**Comment by SDGNelson** [comment]
Sorry I think this was probably the same as the bind IP parsing issues, but if you still get this in the .2 patch could you attach your Server_ (id) .log file from the U3DS/Logs folder please?

**Comment by AlerDerp** [comment]
Hi,

Attached the server log and the LGSM console log ( seems to have more information ).
I updated to the newest version before testing, it didnt help.
[Server_untserver.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7695444/Server_untserver.log)
[untserver-console.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7695445/untserver-console.log)

**Comment by SDGNelson** [comment]
Thanks, it looks like it is quitting immediately because "GameServer API initialization failed". Usually that means the port is already in use or the bind IP is wrong. Perhaps somehow there is an old server process still running on that port?

**Comment by AlerDerp** [comment]
I checked, but there's none. Both of my servers are experiencing the same crash.

**Comment by SDGNelson** [comment]
Maybe a dumb suggestion but: have you tried rebooting the server machine? Just to see if it works from a clean state

**Comment by AlerDerp** [comment]
I just tried it, but that didnt fix it either. Errors remain the same.

**Comment by SDGNelson** [comment]
Unfortunately I am not sure what to suggest. You are sure no other servers are overlapping those ports? Maybe worth passing the -validate argument to app_update in order to ensure all the steam SDK files are up to date?

**Comment by AlerDerp** [comment]
Im using LGSM, im not sure how to change the steamcmd line. Also im very sure, because after restart nothing else is running.

**Comment by AlerDerp** [comment]
I have also checked open ports / ports the server is listening on right now, no port even nearby my Unturned server ports in there.

**Comment by SDGNelson** [comment]
Grasping at straws here, but if you try temporarily disabling plugins does it initialize? It is unfortunate that AFAIK there is no further error information about why GS init fails.

**Comment by Dudu-1967** [comment]
FYI only -- as a year's long Unturned afficionado, I only want to mention that most servers are offline right now. Isn't there some kind of rollback mechanism, like in CI/CD?

![image](https://user-images.githubusercontent.com/95946681/145657894-5ec04bca-3dab-4308-942d-02ce45b72145.png)

**Comment by SDGNelson** [comment]
@Dudu-1967 the known issues at least have been fixed so aside from a few one offs like this post as far as I know it should be working normally, are you getting an error with your server? Refreshing the public server list looks like there are a fair few players online.

**Comment by AlerDerp** [comment]
> Grasping at straws here, but if you try temporarily disabling plugins does it initialize? It is unfortunate that AFAIK there is no further error information about why GS init fails.

Also tried that, didnt help. I just found out mono was running on quite an outdated version (4.x), i've updated it but also didnt help.

**Comment by Dudu-1967** [comment]
@SDGNelson , thx for your prompt reply! 

Maybe expressed in 'numbers of players' things don't look bad - but here's my (local) view on 'number of servers'.  I would conclude there are many more offline than just 'the odd one off' ... ?
![image](https://user-images.githubusercontent.com/95946681/145666087-35af207f-4f46-47f8-bd25-c7b3f2cee112.png)

**Comment by luc13680as** [comment]
Hello, i've noticed something strange. When the update broke my servers, i tried to launch my development server as it was running using an egg from pterodactyl unlike my public servers that are using LinuxGSM. It didn't work so i was waiting for your patch. 

When you released 3.21.33.2, i updated all my servers including the development one. It didn't work ! However, i found a second development server on my panel so i launched it and big suprise, it finally worked ! So i tried one the first dev server to remove all plugins, remove Rocket and even purge Commands.dat but nothing worked so far with this one.

My guess is that server that already updated from 3.21.33.1 or 3.21.33.0 are not able to work with 3.21.33.2. 

Here's log from both my servers under pterodactyl + a LinuxGSM server running with 3.21.33.2
[Server_Default_Dev_not_working.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7696788/Server_Default_Dev_not_working.log)
[Server_Default_Dev_working.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7696790/Server_Default_Dev_working.log)
[Server_pastanetwork1_LinuxGSM_not_working.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7696791/Server_pastanetwork1_LinuxGSM_not_working.log)

**Comment by AlerDerp** [comment]
> Hello, i've noticed something strange. When the update broke my servers, i tried to launch my development server as it was running using an egg from pterodactyl unlike my public servers that are using LinuxGSM. It didn't work so i was waiting for your patch.
> 
> When you released 3.21.33.2, i updated all my servers including the development one. It didn't work ! However, i found a second development server on my panel so i launched it and big suprise, it finally worked ! So i tried one the first dev server to remove all plugins, remove Rocket and even purge Commands.dat but nothing worked so far with this one.
> 
> My guess is that server that already updated from 3.21.33.1 or 3.21.33.0 are not able to work with 3.21.33.2.
> 
> Here's log from both my servers under pterodactyl + a LinuxGSM server running with 3.21.33.2 [Server_Default_Dev_not_working.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7696788/Server_Default_Dev_not_working.log) [Server_Default_Dev_working.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7696790/Server_Default_Dev_working.log) [Server_pastanetwork1_LinuxGSM_not_working.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7696791/Server_pastanetwork1_LinuxGSM_not_working.log)

Are you getting the same error?

**Comment by DgtUC** [comment]
I'm having the exact same issue across all four of my servers. I didn't change any configuration on two of them before this update, while for the other two, I changed the map, but all four of them present the same issue. Also tried following all reasonable steps mentioned above to no avail, just in case.

**Comment by SDGNelson** [comment]
@luc13680as thank you for sharing your logs, there is an interesting point here that must be related:

```
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
BattlEye Server: Initialized (v1.218)
[S_API] SteamAPI_Init(): Loaded '/home/untserver/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
Missing interface adapter for SteamGameServer014
```

Where does this .steam/sdk64 folder come from? Does your container system manually install the Steamworks SDK, and if so maybe it is installing an older version than 1.52?

**Comment by AlerDerp** [comment]
> @luc13680as thank you for sharing your logs, there is an interesting point here that must be related:
> 
> ```
> dlopen failed trying to load:
> steamclient.so
> with error:
> steamclient.so: wrong ELF class: ELFCLASS32
> BattlEye Server: Initialized (v1.218)
> [S_API] SteamAPI_Init(): Loaded '/home/untserver/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
> Missing interface adapter for SteamGameServer014
> ```
> 
> Where does this .steam/sdk64 folder come from? Does your container system manually install the Steamworks SDK, and if so maybe it is installing an older version than 1.52?

Did you also find anything in my logs?

**Comment by SDGNelson** [comment]
@AlerDerp ah, sorry, you are right it is mentioned in your log as well, but I missed it because something was wrong with the prefix:
```
[37mdlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
[S_API] SteamAPI_Init(): Loaded '/home/gameserver/steamcmd/linux64/steamclient.so' OK.  (First tried local 'steamclient.so')
RecordSteamInterfaceCreation (PID 19925): SteamGameServer014 / 
Missing interface adapter for SteamGameServer014 
```
In your case it looks like it is loading the correct steamclient.so file. Unless /home/gameserver/steamcmd is not an up-to-date version of steamcmd?

I am wondering now whether Valve broke something in the newer Steam SDK versions, as post-1.52 is SteamGameServer014 in `isteamgameserver.h`, but pre-1.52 is SteamGameServer013. It might be worth us asking Valve about this on Monday.

**Comment by SDGNelson** [comment]
Edit/follow up: interestingly there are a bunch of bug reports online from Dota 2 players reporting missing Missing interface adapter for SteamGameServer014. This comment by kisek-valve https://githubmemory.com/repo/ValveSoftware/Dota-2/issues/1989 says it is probably out-of-date Steam client, though he was speculating I would not think it is an "official" answer. If you validate your steamcmd install then maybe it will repair something?

**Comment by luc13680as** [comment]
Hello, i was able fix my servers by removing the Steam folder and reinstalling it. Thank you for your help Nelson 🥇 !
Maybe you should try the same thing @AlerDerp

**Comment by AlerDerp** [comment]
> Edit/follow up: interestingly there are a bunch of bug reports online from Dota 2 players reporting missing Missing interface adapter for SteamGameServer014. This comment by kisek-valve https://githubmemory.com/repo/ValveSoftware/Dota-2/issues/1989 says it is probably out-of-date Steam client, though he was speculating I would not think it is an "official" answer. If you validate your steamcmd install then maybe it will repair something?

Hey Nelson,

that fixed my issue aswell.
Appareantly LGSM doesnt update that steamcmd...

Im online again, thx.

**Comment by SDGNelson** [comment]
Glad to hear you got it working! Sorry it took so long to get it figured out. I will keep this potential steamcmd out-of-date in mind for any similar future LGSM reports.
