### ISSUE TITLE
Steamworks.NET

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#2939]
Hello, probably Steamworks.NET changed, I can't use it. Please help.

![image](https://user-images.githubusercontent.com/43903270/145639904-dcc52f94-79e9-412d-ab22-a2d3610ee0ae.png)

not work;
![image](https://user-images.githubusercontent.com/43903270/145639958-ab87b240-31e6-4856-a538-c610d7832200.png)

**Comment by DanielWillett** [comment]
Also having same problem

**Comment by DanielWillett** [comment]
I think rocket dlls need rebuilt. I'm going to clone the repo and build them and see if it fixes it

**Comment by SDGNelson** [comment]
The game should redirect the reference, but I have also just updated the LDM repo with the newer Steamworks.NET dll name

**Comment by DanielWillett** [comment]
Rebuild worked. Thanks

**Comment by ddxn78096** [comment]
nelson, please retract this update until it works, plugins are broken, picking up items are broken, chat is broken

**Comment by DanielWillett** [comment]
I think it does work now, plugin authors just have a bit of work to do.

**Comment by ddxn78096** [comment]
> 

picking up items are broken bruh and chat is broken i dont understand how those two categories are able to be fixed by plugin authors

**Comment by DanielWillett** [comment]
Both of those work on my server... try removing your plugins.

**Comment by SDGNelson** [comment]
Glad to hear you got it working! I will also include the rebuilt Rocket in the next version. And @ddxn78096 as far as I know it is the plugins in that case, but feel free to open a new issue if you are getting an error / exception or think it is not plugins.
