### ISSUE TITLE
Add visible NPC names/subheading

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#294]
Would it be possible to make so NPC names would be visible for players from a specified distance? I know its quite small improvement but I believe it would be good option for roleplay servers with lots of NPCs and it wouldn't mix with players.

example:
![npcname](https://user-images.githubusercontent.com/14231707/40452200-b798d494-5ee9-11e8-98b5-31315cee459f.png)

**Comment by SDGNelson** [comment]
It would be helpful to identify NPCs at a glance. I'll see about implementing something like this, however the issues tracker is not intended for suggestions.

**Comment by MoltonMontro** [comment]
The correct place to suggest things is any of the official Unturned forums.

https://forum.smartlydressedgames.com/
https://steamcommunity.com/app/304930/discussions/0/
