### ISSUE TITLE
NPC Vendor Items not updating after getting different flag

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#2941]
Hello,
so after the latest update there's one issue. Let's say that if I buy something at a vendor, I want it to disappear after I buy it and I want another item to appear. What I've done in the video is pretty simple. Each time you buy an item, a flag 2000 will be incremented by 1. Each item has condition flag 2000/0, 1, 2 or 3. After buying the item, it won't let you buy more of these items until you reload the vendor (exit and open again) and new items won't appear.

https://youtu.be/a9HIdFhlWJs

Here's also the vendor asset if it somehow helps you.
```
// This NPC was made by Loco, taking and editing this NPC without his permission is not allowed.
GUID e6073ab63b314e81b89b9f68316e7e73
Type Vendor
ID 2003
Selling 4
Selling_0_ID 393
Selling_0_Cost 10
Selling_0_Conditions 1
Selling_0_Condition_0_Type Flag_Short
Selling_0_Condition_0_ID 2000
Selling_0_Condition_0_Value 0
Selling_0_Condition_0_Allow_Unset 
Selling_0_Condition_0_Logic Equal

Selling_0_Rewards 1
Selling_0_Reward_0_Type Flag_Short
Selling_0_Reward_0_ID 2000
Selling_0_Reward_0_Value 1
Selling_0_Reward_0_Modification Increment

Selling_1_ID 95
Selling_1_Cost 20
Selling_1_Conditions 1
Selling_1_Condition_0_Type Flag_Short
Selling_1_Condition_0_ID 2000
Selling_1_Condition_0_Value 1
Selling_1_Condition_0_Logic Equal

Selling_1_Rewards 1
Selling_1_Reward_0_Type Flag_Short
Selling_1_Reward_0_ID 2000
Selling_1_Reward_0_Value 1
Selling_1_Reward_0_Modification Increment

Selling_2_ID 394
Selling_2_Cost 30
Selling_2_Conditions 1
Selling_2_Condition_0_Type Flag_Short
Selling_2_Condition_0_ID 2000
Selling_2_Condition_0_Value 2
Selling_2_Condition_0_Logic Equal

Selling_2_Rewards 1
Selling_2_Reward_0_Type Flag_Short
Selling_2_Reward_0_ID 2000
Selling_2_Reward_0_Value 1
Selling_2_Reward_0_Modification Increment

Selling_3_ID 15
Selling_3_Cost 40
Selling_3_Conditions 1
Selling_3_Condition_0_Type Flag_Short
Selling_3_Condition_0_ID 2000
Selling_3_Condition_0_Value 3
Selling_3_Condition_0_Logic Equal

Selling_3_Rewards 1
Selling_3_Reward_0_Type Flag_Short
Selling_3_Reward_0_ID 2000
Selling_3_Reward_0_Value 1
Selling_3_Reward_0_Modification Increment
```

**Comment by SDGNelson** [comment]
Sorry for the trouble. In this update I optimized how vendors are updated - previously they would refresh everything for each individual experience, item, quest, etc change which would be terrible if buying/selling large numbers of items in bulk. It looks like the conditions are only refreshed when the vendor menu is first opened however, so I will change this for the next update to evaluate conditions on each refresh.

**Comment by LocoCZ** [comment]
> Sorry for the trouble. In this update I optimized how vendors are updated - previously they would refresh everything for each individual experience, item, quest, etc change which would be terrible if buying/selling large numbers of items in bulk. It looks like the conditions are only refreshed when the vendor menu is first opened however, so I will change this for the next update to evaluate conditions on each refresh.

Would it be possible to update dialogues as well? So when someone gets an X flag (condition for response 2) that’s a response 1 reward, the second response will show up?
Right now what I need to do is to add the reward to the message in order to update the dialogue for the player to see some certain responses.

**Comment by SDGNelson** [comment]
How are you setting the flag mid-conversation? Sorry I am not sure I understand.

**Comment by LocoCZ** [comment]
I'm sorry for explaining it like that.
Now I can't seem to recreate the issue, have you touched rewards/conditions for the NPCs by any chance? When a dialogue had a recursive call to the parent dialogue, some responses were still visible even after not meeting the right conditions. Player wouldn't be able to use this response - when they clicked it, it will disappear without doing anything.

**Comment by SDGNelson** [comment]
No worries - do not be sorry - I was just wondering for clarification.
Off the top of my head the dialogue stuff has not been touched recently.

**Comment by LocoCZ** [comment]
So yes, I can't re-do the issue again. I don't understand why, but it used to be like this:
If you clicked on a response that would redirect the player back to the same dialogue and when clicking on it, another response wouldn't disappear, but that doesn't seem like it's happening anymore. Maybe I'm doing some kind of a mistake that I learned not to do and I can't make it again. _(I tried literally everything... I was talking about this glitch with BowieD **30 days ago**.)_
---------------------------------------------------------------------------

I have one more issue about vendors though. I don't know if I should call this an issue, but we'll see. 
Let's say you have following response:
Vendor response - condition 2000/1

Inside of the vendor there's one item:
Item - reward 2000/ -1

Once you buy the item from the npc, you won't be able to buy/sell anything anymore and you'll still have the vendor opened even though you can't see the response anymore. Wouldn't it be good to **force quit** the vendor in this case? Force quit would happen only if the vendor response would disappear.
---------------------------------------------------------------------------

Now this is a question about dialogue/vendor. I know that there's supposed to be a dialogue connected to quest or vendor, but what I don't understand is following:
If you open a vendor, there are 2 ways to close it (everything is shown in the video). 

**IF** you close it via the 'Return' button, it is possible to click on any responses once you exit the vendor.
**IF** you close it via the 'F' key button, the responses become unresponsible and you have to exit the dialogue again via the same key button (doesnt even give you the box with F option).

https://user-images.githubusercontent.com/81763752/145883169-0171a212-3e26-47b2-897a-ee391ec20b39.mp4

Why is that? What's the difference between these 2 ways? Does the return button redirect you back to that dialogue and hitting F doesn't redirect you back?
---------------------------------------------------------------------------

And when I'm talking about the F button, it is worth mentioning it for dialogues as well. If you connect a dialogue to a response that has 1 message and 1 response (but the response will stay hidden under a condition that will never be given), you're able to read the message and when you click F, you'll get redirected back to the main dialogue. Why does this not work for the main dialogue? Why if Start Dialogue has only 1 message and 1 (hidden) response won't give you an option to click the F button and leave the dialogue completely in this case? _(You can still close it with the F button, but it doesn't give you the option inside of the dialogue)_

Start Dialogue that has 1 message and 1 response that is invisible because of condition (adds 'Goodbye' message on its own?):
https://user-images.githubusercontent.com/81763752/145885621-3ff131c3-f764-4082-88b4-4e47303ff2e6.mp4
```
ID 2005
Messages 1
Message_0_Pages 1
Responses 1
Response_0_Conditions 1
Response_0_Condition_0_Type Flag_Bool
Response_0_Condition_0_ID 2000
Response_0_Condition_0_Value True
Response_0_Condition_0_Logic Equal
```

Now a dialogue connected to another one where it's shown how(?) it should work:
https://user-images.githubusercontent.com/81763752/145885951-026edfaa-4527-4a9b-83c9-351bb5a72f40.mp4
```
ID 2007
Messages 1
Message_0_Pages 1
Responses 2

```
```
ID 2008
Messages 1
Message_0_Pages 1
Responses 1
Response_0_Conditions 1
Response_0_Condition_0_Type Flag_Bool
Response_0_Condition_0_ID 2000
Response_0_Condition_0_Value True
Response_0_Condition_0_Logic Equal
```
---------------------------------------------------------------------------

I still have some things regarding NPCs, but I would like to know your opinion about these first.
Thank you for your time.

**Comment by SDGNelson** [comment]
Would you mind separating those into new issues please? They are probably bugs, but I do not want to risk breaking anything for the map update this coming Friday, so I will do the separate ones later.

**Comment by SDGNelson** [comment]
Closing because the conditions portion is fixed. The follow-up issues are not fixed yet.
