### ISSUE TITLE
Sharing violation on server launch

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#2942]
So I noticed that sometimes my servers failed to reboot for seemingly no reason, just shutting down without any errors in the logs, but now I've noticed this pop up: 
[Server_Server_#1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7697005/Server_Server_.1.log)
[Server_Server_#2.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7697003/Server_Server_.2.log)
[Server_Server_#3.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7697004/Server_Server_.3.log)
There are a bunch of sharing violations in the logs but I have no idea why.

**Comment by SDGNelson** [comment]
Thank you for the logs! Unturned writes a steam_appid.txt file to ensure the correct appid is used, but maybe the multiple server processes are trying to write it at the same time. AFAIK the file handle is released as soon as it is written, but I will see whether there is a better approach or maybe we can set an environment variable instead.

**Comment by Daniil1288** [comment]
Okay, thanks! I've also noticed that there are sharing violations on a bunch of files in the Cloud folder, such as Visibility.config and Selection.tool, please check that out as well.
