### ISSUE TITLE
Steamworks.NET

### ISSUE THREAD

**Issue by TaPok11211** [SmartlyDressedGames/Unturned-3.x-Community#2944]
![Сним2ок](https://user-images.githubusercontent.com/57183585/145692854-a6e016c3-3df5-42fe-aeee-59c611f1162c.PNG)

How to fix this problem?

**Comment by 01-Feli** [comment]
You are using an older version of rocketmod

**Comment by TaPok11211** [comment]
> You are using an older version of rocketmod

@01-Feli I'm new in this sphere. How I can update?

**Comment by 01-Feli** [comment]
> > You are using an older version of rocketmod
> 
> @01-Feli I'm new in this sphere. How I can update?

Reference the latest rocket version and also make sure you referece com.rlabrecque.steamworks.net

**Comment by TaPok11211** [comment]
![Снимок3](https://user-images.githubusercontent.com/57183585/145695208-c9ac6ad8-755b-4179-a141-e7c6d69be0be.PNG)
@01-Feli Now new error

**Comment by DanielWillett** [comment]
You have to rebuild it manually from the ldm repository.

**Comment by TaPok11211** [comment]
> You have to rebuild it manually from the ldm repository.

I am rebuild, and again have Steamwork.NET error Xd

**Comment by TaPok11211** [comment]
Okey. What am i doing wrong? I am download lastest Rocket.Unturned https://github.com/SmartlyDressedGames/Legally-Distinct-Missile . And then I replacement this file in game's Extras directory. Then I copy this file to game's Modules directory. Then I update Rocket.API, Rocket.Core and Rocket.Unturned in my project. Then I add com.rlabrecque.steamworks.net in my project

**Comment by TaPok11211** [comment]
@SDGNelson god of this game, help me

**Comment by DanielWillett** [comment]
Don't download from releases that's out of date clone the repo and build them yourself. Make sure you choose a .NET Framework version less than or equal to what you're using.

**Comment by Jdance-Media** [comment]
Same issue, Removed the old reference and added the new one. Any RocketMod methods give off errors in visual studio.

**Comment by JustOneMoreBlock** [comment]
I'm annoyed. Might just switch to OpenMod. Be easier to write database convertors if plugins don't already have them.

**Comment by SDGNelson** [comment]
Sorry, maybe @warren39 was right that I repeated a mistake by not including pre-recompiled dlls. I will update the LDM releases momentarily.

@JustOneMoreBlock sorry what seems to be the issue with database converters? Nothing related comes to mind from this most recent update.

**Comment by TaPok11211** [comment]
> Sorry, maybe @warren39 was right that I repeated a mistake by not including pre-recompiled dlls. I will update the LDM releases momentarily.
> 
> @JustOneMoreBlock sorry what seems to be the issue with database converters? Nothing related comes to mind from this most recent update.

how long should we wait?

**Comment by SDGNelson** [comment]
@TaPok11211 you can download a pre-compiled copy here: https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/releases/tag/v4.9.3.13

**Comment by TaPok11211** [comment]
> @TaPok11211 you can download a pre-compiled copy here: https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/releases/tag/v4.9.3.13

Thank u ❤

**Comment by nanashi88** [comment]
remove reference to Steamworks.Net.dll and add new reference: com.rlabrecque.steamworks.net.dll
![image](https://user-images.githubusercontent.com/59157332/146794949-4815e6ac-2667-4edd-8228-69aa5b3646aa.png)
