### ISSUE TITLE
Clothing but no slots

### ISSUE THREAD

**Issue by Rokaskdn** [SmartlyDressedGames/Unturned-3.x-Community#2946]
Me and my friend were playing on elver when my friend said he has no clothing slots, but he had clothing. After he got off, I died to dehydration, came back, picked up my clothes but had no slots. Looks like you don't get any slots after dying or joining a server for the first time.

Here's how it looks
https://user-images.githubusercontent.com/96001002/145706829-b7dfba7b-f624-4736-9607-eb17f0458ef9.png

**Comment by ElRicki7u7** [comment]
Same problem video here

https://user-images.githubusercontent.com/75626024/145729010-99be5065-6e22-4fda-8187-f48b7eb8de2f.mp4

@SDGNelson

**Comment by CyberAndrii** [comment]
You need to contact a server owner and say he needs to update OpenMod.
