### ISSUE TITLE
Snow doesn't work on the map

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2947]
It is not possible to cause snow on the map. You can't cause snowy weather on the map, you can only rain. In the editor, I ticked "Snow", but it didn't help. The map still doesn't give me snow. I also tried: "weather_override": "snow" And "use_snow_volume": true,. But nothing helped, it's also raining on the map

I created a new map with 0, and snow didn't work there either, although I tried everything

**Comment by prank0011** [comment]
You may need to adjust the snow line.

**Comment by SDGNelson** [comment]
Do you have a level asset set in the Config.json file? If so, that takes priority over the older settings. Can you post your level's Config.json file please?

**Comment by JorelDecker** [comment]
I found the problem that the snow level in the editor I had at 0. However, the frostbite effect does not appear

**Comment by SDGNelson** [comment]
So you have snow working now? Do you have frostbite disabled in the level's Config.json file?

**Comment by JorelDecker** [comment]
> So you have snow working now? Do you have frostbite disabled in the level's Config.json file?

{
	"PlayerUI_HealthVisible": true,
    "PlayerUI_FoodVisible": true,
    "PlayerUI_WaterVisible": true,
    "PlayerUI_VirusVisible": true,
    "PlayerUI_StaminaVisible": true,
    "PlayerUI_OxygenVisible": false,
	"Terrain_Snow_Sparkle": true,
	"Category": "Workshop",
	"Version": "3.85.1.0",
	"Tips": 17
	"Use_Snow_Volumes": true,
	"Snow_Affects_Temperature": true,
}

**Comment by SDGNelson** [comment]
The trailing comma after true on the last line might be causing issues, but Snow_Affects_Temperature defaults to true anyway. Otherwise it depends whether the player height is above the level snow height.

**Comment by prank0011** [comment]
That "Tips: 17 "line seems to be missing a", "at the end.
I also suggest adding "Use_Legacy_Snow_Height: Flase".

If you see snow but no freeze damage, you need to add "AmbianceVolume" to Devkit.
The "Weather_Mask" is set to 3, which will allow rain and snow effects within the box.

**Comment by prank0011** [comment]
> > So you have snow working now? Do you have frostbite disabled in the level's Config.json file?
> 
> { "PlayerUI_HealthVisible": true, "PlayerUI_FoodVisible": true, "PlayerUI_WaterVisible": true, "PlayerUI_VirusVisible": true, "PlayerUI_StaminaVisible": true, "PlayerUI_OxygenVisible": false, "Terrain_Snow_Sparkle": true, "Category": "Workshop", "Version": "3.85.1.0", "Tips": 17 "Use_Snow_Volumes": true, "Snow_Affects_Temperature": true, }

Probably because you used "Use_Snow_Volumes: true", you had to use AmbianceVolume to do freeze damage.

**Comment by JorelDecker** [comment]
> > > So you have snow working now? Do you have frostbite disabled in the level's Config.json file?
> > 
> > 
> > { "PlayerUI_HealthVisible": true, "PlayerUI_FoodVisible": true, "PlayerUI_WaterVisible": true, "PlayerUI_VirusVisible": true, "PlayerUI_StaminaVisible": true, "PlayerUI_OxygenVisible": false, "Terrain_Snow_Sparkle": true, "Category": "Workshop", "Version": "3.85.1.0", "Tips": 17 "Use_Snow_Volumes": true, "Snow_Affects_Temperature": true, }
> 
> Probably because you used "Use_Snow_Volumes: true", you had to use AmbianceVolume to do freeze damage.

Can I get more details?

**Comment by prank0011** [comment]
You can try to set "Use_Snow_Volumes: true" and add an AmbianceVolume in the Devkit editor to see if players will feel freezing damage in the AmbianceVolume when it snows.

This was normal when I used Yukon's Level.asset, but I used snowy Weather.asset for the test.

**Comment by JorelDecker** [comment]
> You can try to set "Use_Snow_Volumes: true" and add an AmbianceVolume in the Devkit editor to see if players will feel freezing damage in the AmbianceVolume when it snows.
> 
> This was normal when I used Yukon's Level.asset, but I used snowy Weather.asset for the test.

Thank you very much
