### ISSUE TITLE
Modded weapons show vanilla weapons

### ISSUE THREAD

**Issue by X-Hellfire-X** [SmartlyDressedGames/Unturned-3.x-Community#2948]
I had gotten a few mods on my server, Most mods would have their weapons show vanilla weapons like the dragon fang or other weapons. The ids are not overlapping either. I am new to the github community so Idk if this is even the right place.

**Comment by GazziFX** [comment]
90% its GUID collision, saw something like this on RP server

**Comment by X-Hellfire-X** [comment]
> 90% sure its GUID collision, saw something like this on RP server

so how do i fix it?

**Comment by GazziFX** [comment]
Remove GUID line from .dat files and let Unturned to generate them, then upload mod to workshop

**Comment by X-Hellfire-X** [comment]
There is nothing in the commands.dat files...

**Comment by X-Hellfire-X** [comment]
I am really new to this bug so idk anything about it or how to fix it...

**Comment by SDGNelson** [comment]
I suspect GazziFX is correct that the modded weapons copied a vanilla item, changed the 16-bit ID, but did not change the GUID. The game warns about this, but unfortunately it seems there are quite a few items with this problem. In this case if you did not create the item yourself your best option is to ask the creator to remove and regenrate the GUIDs.

**Comment by X-Hellfire-X** [comment]
I have no idea what you just said... except the last part. How do i even know what mod it would be?

**Comment by SDGNelson** [comment]
Unfortunately there is not an easy way at the moment to track down which mod it might be. From the warnings you might be able to recognize the filename.

**Comment by SDGNelson** [comment]
This was somewhat improved last year with per-server asset list, and features will continue to be updated to use guids rather than ushorts.
