### ISSUE TITLE
Some issues after recent update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#295]
Getting disconnect and this message after some time

![battleye](https://user-images.githubusercontent.com/14231707/40555860-2241bdc8-6053-11e8-970e-64eaa306f2cc.png)

**Comment by baranmod** [comment]
here is a screenshot of chat: 
![chat](https://user-images.githubusercontent.com/14231707/40556252-ad02e800-6054-11e8-8b02-d6a74db3e820.png)

**Comment by Trojaner25** [comment]
Not an issue of vanilla Unturned.

RocketMod needs to update to fix this issue; will be likely the last update for RocketMod 4.

**Comment by baranmod** [comment]
for both issues?

**Comment by Trojaner25** [comment]
No; only the chat related one.

**Comment by Trojaner25** [comment]
The other one is an issue of Battleye Update; not directly caused by Unturned itself.
Bastian broke it :>

**Comment by baranmod** [comment]
and what the heck is this? :D 
![whaat](https://user-images.githubusercontent.com/14231707/40557212-101cd9e8-6058-11e8-9501-688b848dea6e.png)

**Comment by Trojaner25** [comment]
Well someone abuses the server icons...

**Comment by MazeW** [comment]
I wonder who would in their right mind do that...

**Comment by thereis** [comment]
omg nelson

**Comment by aman7** [comment]
trojaner will rocket team fix the issue or we will have to do it ourself?

**Comment by Trojaner25** [comment]
It was already fixed - https://github.com/RocketMod/Rocket.Unturned/commit/e770659cfe9e47b2121e15d4136eb04f4babe4c6

Update Rocket to apply chat fix.

**Comment by SDGNelson** [comment]
I don't think anything changed with BattlEye, but that's always the case when it turns out there's a new bug with Unturned's BattlEye implementation. I'll see if I run into the same kicks.

3.24.0.1 is out now and should help get rid of those rude garbage servers, as well as adding an option to disable the alt-tab pausing.

For plugins sending chat I would suggest using this unified send chat message which supports the new features: https://i.imgur.com/SeHhjGQ.png
Chat seems to work normally in vanilla, but some devs are reporting issues because they haven't updated the Rocket DLL reference yet.

**Comment by Trojaner25** [comment]
RocketMod itself will not expose the new Send Chat Message methods to plugins in version 4 (current version).

We will provide a better Chat API which utilizes the new Unturned Chat features in RocketMod 5.

**Comment by SDGNelson** [comment]
If plugin creators want to I suppose they can always link against Assembly-CSharp.dll directly

**Comment by aman7** [comment]
well i have updated my linux server 3.24.0.1, chat issue have not been fixed yet

**Comment by Trojaner25** [comment]
You have to update RocketMod.

**Comment by SDGNelson** [comment]
Played on a BattlEye Greece server for ~30min and didn't get that client kick fortunately. Seems that the spam servers are still coming through, investigating other options.

**Comment by aman7** [comment]
yea it worked thanks, will have to copy/paste this rocket.unturned.dll everytime when there will be an update?

**Comment by SDGNelson** [comment]
If compiling custom plugins, yes you will need to update your referenced rocket

**Comment by SDGNelson** [comment]
Have you still been having this issue Baron?

**Comment by thereis** [comment]
Players can't find/join in my servers...

**Comment by baranmod** [comment]
Everything seems to work fine now. No more kicking

**Comment by thereis** [comment]
My players are getting disconnect by Battleye: "Client not responding"

And my servers, they don't appear in the servers list.

**Comment by SDGNelson** [comment]
Reached out to BattlEye about the not responding issue.

Thereis what's your server's public IP? I'll double-check that it's not in the blacklist, though I doubt it is. The other thing that recently hid a lot of servers was spoofing higher player numbers using bot player count plugins.
