### ISSUE TITLE
NPC vendor not responding once vendor response doesn’t meet conditions anymore

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#2950]
Let's say you have following response:
Vendor response - condition 2000/1

Inside of the vendor there's one item:
Item - reward 2000/ -1

Once you buy the item from the npc, you won't be able to buy/sell anything anymore and you'll still have the vendor opened even though you can't see the response anymore. Wouldn't it be good to force quit the vendor in this case? Force quit would happen only if the vendor response would disappear.

**Comment by SDGNelson** [comment]
Actually thinking about this more: it might be better that the player chooses to leave the vendor, otherwise it could be confusing why it is immediately closing.
