### ISSUE TITLE
2 ways to close NPC vendor

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#2951]
I know that there's supposed to be a dialogue connected to quest or vendor, but what I don't understand is following:
If you open a vendor, there are 2 ways to close a vendor.

IF you close it via the 'Return' button, it is possible to click on any responses once you exit the vendor.
IF you close it via the 'F' key button, the responses become unresponsible and you have to exit the dialogue again via the same key button (doesnt even give you the box with F option).

Why is that? What's the difference between these 2 ways? Does the return button redirect you back to that dialogue and hitting F doesn't redirect you back? Wouldn’t it be good to make the player leave the dialogue completely if they hit F?

_I’ll add the videos to the comments if you’ll need it._

**Comment by SDGNelson** [comment]
Marking next update so that I remember to sort this out, but it will actually be the next-next update.

**Comment by SDGNelson** [comment]
It looks like there is a discrepancy between how 'F' and "Return" closes the vendor menu which I will fix, however when I tested with some of the vanilla vendors they both worked normally as-is. Out of curiosity which NPC has this problem?

**Comment by LocoCZ** [comment]
That's interesting. I haven't tried it on any vanilla NPCs, but when I was testing it on my custom ones, it did it like that. 

Here's a video that I've shown in the last issue:

https://user-images.githubusercontent.com/81763752/148107492-140114d7-cef5-49c1-8c8c-d2b5b7bfb6d6.mp4

**Comment by SDGNelson** [comment]
Closing because this was fixed in the 3.22.1.0 update.
