### ISSUE TITLE
F key button working differently for NPC dialogues

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#2952]
If you connect a dialogue to a response that has 1 message and 1 response (but the response will stay hidden under a condition that will never be given), you're able to read the message and when you click F, you'll get redirected back to the main dialogue. Why does this not work for the main dialogue? Why if Start Dialogue has only 1 message and 1 (hidden) response won't give you an option to click the F button and leave the dialogue completely in this case? (You can still close it with the F button, but it doesn't give you the option inside of the dialogue)

_If you’ll need to see the videos, I’ll post them in the comments._

**Comment by SDGNelson** [comment]
Marking next update so that I remember to sort this out, but it will actually be the next-next update.

**Comment by SDGNelson** [comment]
If I understand correctly: you have the main dialogue for the NPC configured with a permanently hidden response? Why?

And is the bug simply that the Interact prompt is not shown for the main dialogue when there are no responses?

**Comment by LocoCZ** [comment]
> Why?
Let's say you've got an NPC that wants to tell you something but you shouldn't answer them. Just some random message and what I wanted to achieve is that small F box at the bottom right corner which will show the player to leave. 

If there is 1 message and 0 responses, it adds a 'Goodbye' response on it's own. 
If there is 1 message and 1 response with flag the player doesn't have, it still adds that 'Goodbye' response.

https://user-images.githubusercontent.com/81763752/148108707-830c787d-c153-4e58-a987-832c8e0c7980.mp4


If there is a dialogue connected to main dialogue with 1 message and 1 response with flag the player doesn't have, it shows that [F] button and when you click on it, it brings you back. 

https://user-images.githubusercontent.com/81763752/148108726-f3ff81a7-15b5-417e-addc-d53188b92dfd.mp4




What would be nice is if you had [F] shown at the bottom right corner instead of a 'Goodbye' response that was added randomly on its own for the start dialogue.

**Comment by SDGNelson** [comment]
Note the goodbye response is not added randomly, rather it is added if an exit response was not defined. I suppose the map-wide default goodbye could be made customizable if you want something other than "Goodbye"?

**Comment by LocoCZ** [comment]
Yeah I'm sorry, random was wrongly used. 

If an exit response isn't defined, why not make the [F] button in the bottom right corner instead of a new response? It's already working when an exit response isn't defined if that dialogue is connected to another one. 

Couldn't it be same for Start Dialogue - but in this case [F] would leave the dialogue?

**Comment by SDGNelson** [comment]
That makes me wonder if it would make more sense to include [F] in the "Goodbye" text and/or response option. 🤔

**Comment by LocoCZ** [comment]
Yeah that would be nice. 

What would also be nice is if you could add an option (that you mentioned) to edit that goodbye response - as I have all of my text within NPCs white and this is the only response that would be grey.

**Comment by SDGNelson** [comment]
Added in the next update: "DefaultGoodbyeResponse" per-level override for NPC dialogue in level's translation file.
