### ISSUE TITLE
Issue when using the new gui or idk.

### ISSUE THREAD

**Issue by matthew57778** [SmartlyDressedGames/Unturned-3.x-Community#2953]
I have 16gb of ram and i do have pagefile on and i get this in my log
"Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak"
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7729494/Client.log)

**Comment by matthew57778** [comment]
I am using the new gui too btw.

**Comment by SDGNelson** [comment]
Unturned does not use the job system directly yet, so these would be Unity internal bugs maybe with graphics jobs ¯\\\_(ツ)_/¯

**Comment by matthew57778** [comment]
I am running windows 7 is it possible the new ui you added is for windiws 10 if so can you keep the old ui option in the game as i love unturned
