### ISSUE TITLE
[BANNED] Banned while playing my own server

### ISSUE THREAD

**Issue by sulong666** [SmartlyDressedGames/Unturned-3.x-Community#2954]
Today afternoon I and My friends was on my server so calm when suddenly I and Myfriends received a ban by BattleEye for no reason, I am very confused.I used unturned's teleport  test  in the my server. Then my friend and I were banned.But one of us was not banned.I think this should be a mistake.

My account:
https://steamcommunity.com/id/1919968044/

**Comment by SDGNelson** [comment]
BattlEye is enabled by default unless you explicitly disabled it. You would need to contact BattlEye support, sorry. https://www.battleye.com/contact/

**Comment by sulong666** [comment]
-
