### ISSUE TITLE
Mods don't update on client side

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#2958]
Hello,

If a mod get updated, then client who is not subscribed to that mod either won't be able to re-join server, or he can join but doesn't see the updated content!

I am talking about when the mod that is included with the map as "required item" (I haven't tested other cases)
also I am talking about a client that was inside the server before mod update and server restart. (that mean client still has the older version of the mod)
(btw even if client restart game, it doesn't help, since he is not subscribed to that mod)

**Comment by nanashi88** [comment]
Extra test:
I made simple Mod that contains locker and shirt.
I launched a local didcated server (mod id were added to the config.json)
I joined, and my game client downloaded the mod.
then I updated the mod by changing storage size of the locker and also changed storage size of the shirt.
I lauched again the dedicated server, and it detected that there is mod update, and that good
```
Workshop item 2988232177 found in cache, but remote (12/20/2021 7:29:25 PM) is newer than local (12/20/2021 7:15:33 PM)
Downloading workshop item: 2988232177
```
now I tried to join server again and I got the following error, and wasn't able to join: (M Top referes to the shirt)
![image](https://user-images.githubusercontent.com/59157332/146809673-4343a75b-9236-42d7-9476-a4d6fb83b71a.png)

**Comment by nanashi88** [comment]
Update: I restarted game and tried to join again and I was able to join!!
when I shuted down I noticed "-validating" next to Unturned in steam
and when I joined all is fine , and storage size updated
actually I am surprised, I encountered situations before, that restarting game didn't help!

**Comment by nanashi88** [comment]
Test2:
this time I updated the mod by adding new shirt.
client was able to re-join server without getting error, though by checking 
C:\Program Files (x86)\Steam\steamapps\workshop\content\304930\2988232177
I see it didn't update, and the new shirt is not there (and in server when I spawn it, I get shirt inventory storage but I don't see shirt on the body (topless) )
restarting game didn't update the mod, but when rejoined server (after shuting down game), client downloaded the updated mod while joining the server!

but shouldn't client side check if there is mod update everytime joining server?! (like the checks that dedicated server do when it get launched)

**Comment by nanashi88** [comment]
extra: I tried same tests on a test map while including the mod as "required item" at the map workshop page. and I got same results.

I am glad to see the mods get updated when joining server after restarting game, idk if this recent change to the game, because before I was recieving errors like "server running different map" or something like that.

I guess I will close this issue, or remove it :P

**Comment by nanashi88** [comment]
sorry, but re-opened issue again.
now I am having this issue in one of our servers ( not test server)
I get "This server is using a modified version of the map" !
I restarted game and tried to join, but it doesn't help.
I removed the map from client downloaded workshop files,
then tried to join again, 
I see client downloading fresh copy of the map while joining the server
but still after that I receive same error message!
there are other players online in that server
that mean it is one of the mods on my side causing this issue!
though error message says "modified version of the map" which seems false info!
doing more tests ....

**Comment by nanashi88** [comment]
confirmed that this error I receive because of mod, not the map.
the mod causes the issue is my mod, and it was modified on my side.
but I am still not able to reproduce it using my test server and test mod.
I have copies of the mod before and after, so I can do more tests later

**Comment by SDGNelson** [comment]
Similar to the server there should be a message in Client.log like "Workshop item 2988232177 found in cache, but remote (12/20/2021 7:29:25 PM) is newer than local (12/20/2021 7:15:33 PM)" Workshop files that the client already has loaded are typically a more complicated case.

"Modified version of the map" encompasses anything that would affect the level's hash. If your locally edited mod has assets used on the map that would explain why the hash is different.

**Comment by nanashi88** [comment]
thank you for replying.

yes, you are right, the mod has map objects and NPCs
now error message make sense.
so for now I will close case
if I was able to regenerate a situation where it could happen for normal players, then I will open again.
