### ISSUE TITLE
Help with plugin

### ISSUE THREAD

**Issue by TaPok11211** [SmartlyDressedGames/Unturned-3.x-Community#2959]
How can I find out what kind of weapon a player has in his hands now and current value of rounds, max value of rounds? And fire mod
What method or class store this information?

**Comment by GazziFX** [comment]
```csharp
if (player.equipment.useable is UseableGun gun)
{
   Print(gun.ammo);
}
```

Max ammo is `amount` in MagazineAsset

**Comment by TaPok11211** [comment]
> ```csharp
> if (player.equipment.useable is UseableGun gun)
> {
>    Print(gun.ammo);
> }
> ```
> 
> Max ammo is `amount` in MagazineAsset

Thank you

**Comment by TaPok11211** [comment]
> ```csharp
> if (player.equipment.useable is UseableGun gun)
> {
>    Print(gun.ammo);
> }
> ```
> 
> Max ammo is `amount` in MagazineAsset

 Mb u know how chang colors from plugin on Image? For Example, I have red icon, but when player hp == 100, I need change color from red to green

**Comment by GazziFX** [comment]
I make it with triggers which after activation deactivate itself and change some properties, for color you can activate animation controller

**Comment by TaPok11211** [comment]
> I make it with triggers which after activation deactivate itself and change some properties, for color you can activate animation controller

I try to use Script in Unity on Effect, 
public Gradient, but not working. I have two variant, mb I am make a mistake in unity script, or game don't want work with scripts in mods

**Comment by TaPok11211** [comment]
> I make it with triggers which after activation deactivate itself and change some properties, for color you can activate animation controller

I will try your way

**Comment by GazziFX** [comment]
> > I make it with triggers which after activation deactivate itself and change some properties, for color you can activate animation controller
> 
> I try to use Script in Unity on Effect, public Gradient, but not working. I have two variant, mb I am make a mistake in unity script, or game don't want work with scripts in mods

You can only use scripts which is actually presented in Unturned code

**Comment by TaPok11211** [comment]
> > > I make it with triggers which after activation deactivate itself and change some properties, for color you can activate animation controller
> > 
> > I try to use Script in Unity on Effect, public Gradient, but not working. I have two variant, mb I am make a mistake in unity script, or game don't want work with scripts in mods
> 
> You can only use scripts which is actually presented in Unturned code

Thank u

**Comment by TaPok11211** [comment]
> ```csharp
> if (player.equipment.useable is UseableGun gun)
> {
>    Print(gun.ammo);
> }
> ```
> 
> Max ammo is `amount` in MagazineAsset

Print(gun.ammo) don't work, they give me error
And in what method I can update information about gun? For example we use UnturnedPlayerEvents.OnPlayerUpdateHealth to update information about health, but what about guns? How can I update information? And how I can get information about current rounds in my mag

**Comment by GazziFX** [comment]
Why not just open Assembly-CSharp in ILSpy and not ask on how to do anything if you don't know the basics

**Comment by TaPok11211** [comment]
> Why not just open Assembly-CSharp in ILSpy and not ask on how to do anything if you don't know the basics

Thank u
Because it's faster
