### ISSUE TITLE
i foun new bag

### ISSUE THREAD

**Issue by paskin2021** [SmartlyDressedGames/Unturned-3.x-Community#2960]
i ca fly using carjack and Otter. You need to use the jack and crawl forward.
![Screenshot_5](https://user-images.githubusercontent.com/96479157/146933875-873a9ad5-8148-4cc8-b174-9befd7f4af04.png)
![Screenshot_6](https://user-images.githubusercontent.com/96479157/146933943-c5ecf644-4cb6-41a4-9587-78e24f3467f4.png)
![Screenshot_7](https://user-images.githubusercontent.com/96479157/146934469-3e4d77ed-cdd1-43ac-850a-971a77d9fe6a.png)
![Screenshot_8](https://user-images.githubusercontent.com/96479157/146934476-aefe9f9a-2161-4030-b8ee-62ad55194b50.png)
![Screenshot_10](https://user-images.githubusercontent.com/96479157/146934494-e44975be-8441-4a51-9d95-8a768910afb5.png)
![Screenshot_9](https://user-images.githubusercontent.com/96479157/146934514-50a38cb6-8eae-4fe3-bb18-5c48b6cb1ddf.png)

**Comment by SDGNelson** [comment]
As in you used the carjack and were able to enter the vehicle like that? My guess is that a plugin threw an exception during the carjacked event. If it is your server/plugin and you want to debug the plugin I can help, but otherwise I think this is a non-issue unless it can happen in vanilla.

**Comment by WCPistolPete** [comment]
Tricky, but can be done on vanilla with practice. Players used to do this years ago (2015-2016) by carjacking vehicles. Judicious use of the Flight perk can make for fun trips.

**Comment by paskin2021** [comment]
Yes it can happen in vanilla.I dont use the Flight perk.

**Comment by paskin2021** [comment]
This work also in singleplayer.I just checked.
 
С уважением,
Павел Чижов.
