### ISSUE TITLE
Will Unturned 4.0 (Unturned II) have Peer to Peer Multiplayer/CO-OP?

### ISSUE THREAD

**Issue by RealDoesStuff** [SmartlyDressedGames/Unturned-3.x-Community#2965]
I was wondering this, as currently playing the game with one friend on a dedicated server is a bit overkill.
And also makes loading into the game a bit more complicated compared to just loading in and clicking join game.

**Comment by GazziFX** [comment]
I can try to make module which will allow to host p2p multiplayer in Unturned 3.0

**Comment by RealDoesStuff** [comment]
That would be an interesting and very useful mod to simplify the current glaring problem with Unturned's multiplayer. At least for those who only play with 1-3 other people. And for those who can't port forward.

**Comment by SDGNelson** [comment]
Yes, the beta currently supports "listen server" hosting, and supporting non-dedicated servers has been a priority.

**Comment by GazziFX** [comment]
> I can try to make module which will allow to host p2p multiplayer in Unturned 3.0

I has some progress but there's a lot of problems when hosting inside singleplayer rather than a dedicated server
