### ISSUE TITLE
Update Unity version to 2021.2.7f1 Tech Stream

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#2967]
Unturned is too long being with Unity 2019 LTS.
The community needs to improve the game, so I guess we need to update the Unity version.
New features and improvements of Unity 2021.2 Tech Stream:
https://unity.com/releases/artist-features/2021-2-tech-tier2-features

The most valuable are support of: .NET 6(in future), .NET Standard 2.1, C# 8-9
https://forum.unity.com/threads/unity-future-net-development-status.1092205/

Will be helpful if you emote with "Like" under that comment, for Nelson's attention.

**Comment by SDGNelson** [comment]
Unity latest releases not stable enough, and even the update to 2019.4 LTS was awful. From now on Unturned is only updating to "legacy LTS" releases of Unity, so 2020.4 LTS sometime in 2022.
