### ISSUE TITLE
Instant salvage on death

### ISSUE THREAD

**Issue by sigataros** [SmartlyDressedGames/Unturned-3.x-Community#2968]
If you press F before dying, spawning in will salvage the next thing you are looking at without any delay, this is really bad in doorcamp situations: You open the door, try to close it and die, spawning in your bedroll you spawn looking at your door, it instant salvages and they can go full deep.

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time. This should be an easy fix, will do!
