### ISSUE TITLE
Handcuffed players are ignored by sentries even if the sentry mode is `Hostile` 

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2969]
https://user-images.githubusercontent.com/48765566/147667780-d9568d59-e538-4f61-90c2-3b5adbc1e69a.mp4

**Comment by rube200** [comment]
That is on porpoise
Friendly attacks u if u have a gun in hands.
Normal attacks u if u don't have in surrender mode.
Hostile attacks if u are not cuffed (example prisoners)

**Comment by SDGNelson** [comment]
@rube200 is correct that this is intentional to allow the sentry owner to escort prisoners through the base.
