### ISSUE TITLE
People Abusing Server List

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#297]
![unknown 1](https://user-images.githubusercontent.com/7349712/40557601-b0049764-601e-11e8-8fd1-45cb8e811b43.png)

![](https://cdn.discordapp.com/attachments/349610837729607690/449622147581607976/unknown.png)

May be a good idea to fix this because there is several of them

**Comment by SDGNelson** [comment]
3.24.0.1 should be out within the next hour which will hopefully help filter out this rude garbage, as well as add an option to disable the alt-tabbing pause.
