### ISSUE TITLE
Quit due to provider exception: GameServer API initialization failed!

### ISSUE THREAD

**Issue by Giuca002** [SmartlyDressedGames/Unturned-3.x-Community#2970]
When trying to turn on my Linux (Fedora) based server after the new update it starts then sends 
`Quit due to provider exception: GameServer API initialization failed!`
after a while then closes ,before the update i did not have this problem 

I looked everywhere but to no awnser

**Comment by SDGNelson** [comment]
Usually this means another process is using one of the ports. Are you running any other servers on the same machine?

There was recently a case where some hosts using Linux game server manager (LinuxGSM) had an out-of-date steamcmd install. Are you using any third party tools aside from steamcmd? If you can send me the full Player.log file (stdout) from the server there may be more details.

**Comment by Giuca002** [comment]
Yes, Im using LinuxGSM I was going to reinstall but dont know how so I will look into that.

**Comment by SDGNelson** [comment]
Good luck 👍 worst case you can also just run LinuxGSM's steamcmd.sh which will cause steamcmd to update itself.
