### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2971]
When I log in to the server, I have a black screen. There are some features: 
- Sometimes the black screen does not appear, but if I open the inventory, with a probability of 30 percent, the black screen will return. 
- The whole HUD, including the chat, is functioning normally, I don't see exactly the environment itself. 
- I deleted mods, did a cache check, reinstalled the game and steam. Nothing helped

My PC:
AMD Ryzen 3 1200 Quad-Core Processor 3.10GHz
RAM 16 GB
nVIDIA GeForce 9600 GT

**Comment by GazziFX** [comment]
Send `Client.log` and `Client_Prev.log` files from `Logs` folder

**Comment by JorelDecker** [comment]
> 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7794493/Client.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/7794494/Client_Prev.log)

**Comment by SDGNelson** [comment]
Thanks @GazziFX.

Maybe a silly question, but do you have a blindfold equipped?

Are you able to see the environment in singleplayer and/or other multiplayer servers? i.e. is it specific to just that server?

**Comment by JorelDecker** [comment]
> 

I have not tried to log in to other servers, but I have logged in to a single game, a black screen may be there. However, it may disappear if I go to the game menu, and return if I open the inventory. Also, sometimes a black screen is present in the game menu. (Buttons are visible, there is no background)

**Comment by SDGNelson** [comment]
Very unusual. Nothing comes to mind as a cause, but it might be worth trying this option:

1. Right-click Unturned in your Steam library
2. Click "Properties..."
3. Click "Select Launch Options..."
4. Add "-Glazier=IMGUI" without quotes

**Comment by ThreeshaStrong** [comment]
Hi! Your advice didn't help. Still, when entering the server, a black screen appears (only hud, chat, sounds, etc. are visible), Maybe there are some other ways out of this situation?

**Comment by SDGNelson** [comment]
Unfortunately no potential causes have occurred to me, and there are no relevant errors in the log.
If you add this command-line option and go directly into singleplayer does it happen?
"-NoWorkshopSubscriptions"
Does it only happen with the inventory, or also crafting/skills?

**Comment by ThreeshaStrong** [comment]
I can clarify the situation for you anew and in more detail:
I go to the server (With mods), I load completely and I have a black screen. At the same time, I see the hud and chat. I can hear the sounds of the game. I can write to the chat. I can speak in voice chat. I just have a black screen. By the way, when entering the inventory, I do not have a character model. It is simply missing. It very rarely happens when I go in and there is no problem, but after opening inventory, crafting or pressing "Esc" a couple of times, there is a 90% chance that this problem will appear again. I decided to go to another server, also with mods, but I'm fine there. Changing the graphics settings didn't help me in any way.

**Comment by ThreeshaStrong** [comment]
I have already unsubscribed from mods. I deleted them, installed them again, signed them. Nothing helps. I even reinstalled the game and STEAM! To no avail.

**Comment by ThreeshaStrong** [comment]
By the way, I was playing on the server now, and everything was fine and functioning perfectly, but after a while of the game I opened the inventory once again (before that I opened it and everything was fine) and everything broke and black again. :(

**Comment by SDGNelson** [comment]
To double-check: @ThreeshaStrong you are the same player as OP @JorelDecker?

If you humour me and use the "-NoWorkshopSubscriptions" option and then try singleplayer does it still happen?

**Comment by ThreeshaStrong** [comment]
@JorelDecker is the person who responded to help me and contacted you, and then taught me how to contact you. I'm the one with the problem.

There is no such thing in a single game, there is no such thing on other servers with mods and without them, only on a certain server with mods. They work properly, the problem is observed ONLY with me. Do you think it could be related to my video card? It has a memory capacity of 512 MB.

**Comment by ThreeshaStrong** [comment]
The problem occurs absolutely randomly, but very often.

**Comment by ThreeshaStrong** [comment]
As I understand it, if I enter this setting into the game, then I will not have mods? I need them to have on the server.

**Comment by SDGNelson** [comment]
So the black screen only happens on that one server with those mods? In that case it sounds like it is related to one of the mods. 😕

**Comment by ThreeshaStrong** [comment]
Hmm, then why is this problem observed exclusively with me? I have even reinstalled steam, and even reinstalled the operating system, nothing helped me. :(

**Comment by ThreeshaStrong** [comment]
I had already played on this server before, but on another PC, which was worse in terms of the characteristics of the current one (with the exception of the video card) and everything was fine.

**Comment by SDGNelson** [comment]
Unfortunately no idea why it is happening to you. If there were an error logged or some way to reproduce it I would hopefully be able to fix it. Also different when the problem is with custom/modded content than official/curated content. Sorry not to have a better answer.

**Comment by ThreeshaStrong** [comment]
Я в ближайшее время куплю себе более лучшую видеокару ( GTX 750ti ), если проблема исчезнет, то следует изменить системные требования игры описанные в стиме.
I will buy myself a better video card (GTX 750ti) in the near future, if the problem disappears, then the system requirements of the game described in the incentive should be changed.

**Comment by ThreeshaStrong** [comment]
I will buy myself a better video card (GTX 750ti) in the near future, if the problem disappears, then the system requirements of the game described in the incentive should be changed.
