### ISSUE TITLE
Serverside fast loot

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2972]
When you press Ctrl client find empty space in inventory and drag to it, but its bad for my stack system because client wont drag to existing item. It would be great if it would be similar to `ReceiveTakeItemRequest` send `to_page: 255`

**Comment by surv0013** [comment]
Wait bro, do you want the server to look for a free slot? This is not the best option, because it creates additional tasks for the server. The network code in the game is designed in such a way as to minimize the work of the server as much as possible.

**Comment by SDGNelson** [comment]
Sorry, but this is unlikely to happen until stacking gets proper built-in support with an eventual inventory rewrite.

**Comment by surv0013** [comment]
> Sorry, but this is unlikely to happen **until stacking gets proper built-in support** with an eventual inventory rewrite.

Are you planning to add support for custom inventory?

**Comment by SDGNelson** [comment]
@surv0013 not exactly custom inventory, but stacking for vanilla items, better item metadata, etc.
