### ISSUE TITLE
Lost connection to host or Steam network

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#2973]
Sometimes, some players cannot join my server:

![Lost_connection](https://user-images.githubusercontent.com/64722485/147815700-41f56205-3a09-426c-8b5a-5a01dad8fbb2.png)

I'm not sure if this is a client-side problem or a server-side problem. Does anyone know how to solve it?

Log from Client.log:

`
[2021-12-31 13:40:15] Initializing ClientTransport_SteamNetworkingSockets
`
`
[2021-12-31 13:40:15] Client testing for Steam Networking availability (k_ESteamNetworkingAvailability_Retrying)
`
`
[2021-12-31 13:40:16] Readiness to participate in authenticated communications changed to k_ESteamNetworkingAvailability_Retrying "Attempt #5 to fetch config from https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=304930"
`
`
[2021-12-31 13:40:16] Request prices result: k_EResultFail I/O Failure: False
`
`
[2021-12-31 13:40:36] Readiness to participate in authenticated communications changed to k_ESteamNetworkingAvailability_Failed "No response from server"
`
`
[2021-12-31 13:40:36] Client transport failure: Failed to initialize Steam network authentication.
`
`
[2021-12-31 13:40:37] Returning to main menu
`
`
[2021-12-31 13:40:37] Disconnected
`

**Comment by SDGNelson** [comment]
Looks like a client-side problem losing connection to Steam in general. When this happens the Steam Friends window probably appears offline for them as well.

**Comment by warren39** [comment]
![image](https://user-images.githubusercontent.com/64722485/147826401-4b3afd0a-fdc1-4ff0-901e-dd6a452b8223.png)

Recently there are some problems with the Steam client, which may be related to this.

**Comment by TH3AL3X** [comment]
> ![image](https://user-images.githubusercontent.com/64722485/147826401-4b3afd0a-fdc1-4ff0-901e-dd6a452b8223.png)
> 
> Recently there are some problems with the Steam client, which may be related to this.

Lol

**Comment by SDGNelson** [comment]
Do you know is global Steam actually inaccessible for you now? There were conflicting reports about whether it has been banned or whether it was a DNS poisoning attack.

**Comment by warren39** [comment]
I can access the Steam client normally, but some players have been affected a few days ago.
In just 10 minutes, I received feedback from two players on the above problem. In most cases, it will be normal for them to rejoin the server after a few minutes. I don't know why.

**Comment by warren39** [comment]
I setup a video to show this problem on my PC: https://youtu.be/1amYaV_Stvo

**Comment by SDGNelson** [comment]
From the video and log it sounds like the connection to Steam is intermittent. Hopefully it goes back to normal soon. :/

**Comment by jatapa** [comment]
There have been lots and lots of reports of this happening for the last week or so.

**Comment by SDGNelson** [comment]
@jatapa the extra zero is bizarre especially considering that Unturned overrides steam_appid.txt with the correct value, but otherwise it still sounds like usual Steam getting hammered during a holiday sale. Note that web API request is internal to SNS, not something Unturned is doing, nothing related has changed in Unturned in a while. It looks like the response to GetSDRConfig is rather large so that server must be kept pretty busy.

**Comment by jatapa** [comment]
Ye thought it has nothing to do with unturned just find it annoying when people come and ask why can't they join their lan server and can't really tell them anything to fix it
