### ISSUE TITLE
Looking for the map dev tools in virtual reality.

### ISSUE THREAD

**Issue by mateusorn** [SmartlyDressedGames/Unturned-3.x-Community#2977]
I remember that some years ago Unturned just had a VR version to map editors, this versions still existent in any place? If you need somebody else to test a VR version let me know! I love to edit maps and maybe do it in Vr would be really great!

**Comment by SDGNelson** [comment]
Sorry, the VR editor is not supported anymore. :(
If you are interested you can technically still download the old VR editor using steamcmd's `download_depot appid depotid manifestid` to get an old version - another player posted about doing this on the /r/unturned subreddit a couple days ago.
