### ISSUE TITLE
Latest update bug map

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2979]
![Screenshot](https://user-images.githubusercontent.com/13141042/147932034-d3a5d6d5-ef9a-46ab-821f-a8e5e1450c38.png)

It's not only for me, everyone can see it

**Comment by SDGNelson** [comment]
Is it a custom version of the map, or maybe placed by a player? I checked but there does not seem to be lights there.

**Comment by TH3AL3X** [comment]
I have been a little outdated, I thought that after the update these bundles were removed, sorry for the report

> Is it a custom version of the map, or maybe placed by a player? I checked but there does not seem to be lights there.

**Comment by TH3AL3X** [comment]
> Is it a custom version of the map, or maybe placed by a player? I checked but there does not seem to be lights there.

I have been a little outdated, I thought that after the update these bundles were removed, sorry for the report
