### ISSUE TITLE
DamageTool.damage(Zombie zombie...) doesn't work

### ISSUE THREAD

**Issue by SurvivorCDG** [SmartlyDressedGames/Unturned-3.x-Community#298]
The plugin is compiled successfully, but errors occur during operation.

**Rocket.log:**
[05/25/2018 12:43:52] [Error] MissingMethodException: Method not found: 'SDG.Unturned.DamageTool.damage'. - Plugin.Plugin.FixedUpdate ()

**Unturned.log:**
Missing method SDG.Unturned.DamageTool::damage(Zombie,Vector3,single,single,EPlayerKill&,uint&) in assembly /home/steam/Unturned_Headless_Data/Managed/Assembly-CSharp.dll, referenced in assembly /home/steam/Servers/Rocket/Rocket/Plugins/Plugin.dll

**Comment by SDGNelson** [comment]
Looks like you need to update to the latest Rocket .dll
