### ISSUE TITLE
Add ServerSetRadioFrequency

### ISSUE THREAD

**Issue by Paradox304** [SmartlyDressedGames/Unturned-3.x-Community#2983]
There is no way to currently change the frequency of a player, please add a method for that.

**Comment by SDGNelson** [comment]
`sendSetRadioFrequency` (older method) is called by the client which calls `SendSetRadioFrequencyRequest`, and then the server calls `SendRadioFrequencyState`. Technically you can call that now, but I will need to add a public method for it.

**Comment by Paradox304** [comment]
Yep, the timing
