### ISSUE TITLE
[Feature Request] Higher ID cap

### ISSUE THREAD

**Issue by BroXn** [SmartlyDressedGames/Unturned-3.x-Community#2984]
currently the id cap is 16^4 aka 65536 and slowly there is more items/workshop/curated content being made.

i dont know if this is a easy change or not but it would be usefull for modders to work on a bigger id scale with all the content that has come up.

**Comment by GazziFX** [comment]
> currently the id cap is 16^4 aka 65536 and slowly there is more items/workshop/curated content being made.
> 
> i dont know if this is a easy change or not but it would be usefull for modders to work on a bigger id scale with all the content that has come up.

Do you planning to install all workshop content on your client/server?

Unturned currently migrating to GUID 2^128 aka 3,4028×10^38

**Comment by SDGNelson** [comment]
Thanks @GazziFX, yes Unturned has gradually been transitioning to 128-bit IDs but there is a lot of existing code and assets.
