### ISSUE TITLE
Problems with dedicated server (December 2021, after Arid update)

### ISSUE THREAD

**Issue by DoomBoi113** [SmartlyDressedGames/Unturned-3.x-Community#2985]
I hosted a small dedicated server for me and few of my friends to play on, but ever since the arid update i haven’t been able to successfully connect to server. It starts just fine but when it comes to downloading workshop files every single file experiences this error e.g: “Download workshop item 877777769 failed, result: k_EResultFail”. Then, when i try entering server upon entering the right data (port password etc.) i am instantly notified that server cannot be found ("Failed to find server.") . I tried creating test server, with no workshop mods on it, and i couldn't connect on it either. I even tried the dafault U3DS server and once again i got "Failed to find server". If i find server through LAN servers tab, it's there but when i try connecting to it that way it starts loading than after 5 seconds i get "Lost connection to steam". I’ve never had any similar issues with Unturned Dedicated server tool. Is this some general issue that will be resolved and, if its not, can someone help me resolve it? Please note that i've hosted multiple servers before and had no issues like this whatsoever. Even this particular server was running just fine before that update. Any help would be greatly appreciated, i haven't been able to play Unturned with my friends since...

**Comment by GazziFX** [comment]
Windows or Linux?

**Comment by DoomBoi113** [comment]
Windows 10

**Comment by joeymisfit** [comment]
@DoomBoi113 What version of Unturned are you running 304930 or 1110390? Also do you have your internal/external firewalls on? Last but not least I'd suggest you upgrade to a windows server version as Windows 10 has limited features compared to the server versions.

**Comment by GazziFX** [comment]
What is your startup command? Connection problems maybe related to firewall rules. Also you can try to setup GLST token on your server.

**Comment by SDGNelson** [comment]
Based on your note about:

> Download workshop item 877777769 failed, result: k_EResultFail

There have been several reports of corrupted Steam install folders recently where for whatever reason Steam cannot install workshop files anymore. If you delete the Servers/ (your server id) /Workshop/Steam folder does it start working again?

**Comment by joeymisfit** [comment]
> Based on your note about:
> 
> > Download workshop item 877777769 failed, result: k_EResultFail
> 
> There have been several reports of corrupted Steam install folders recently where for whatever reason Steam cannot install workshop files anymore. If you delete the Servers/ (your server id) /Workshop/Steam folder does it start working again?

I've also noticed sometimes with hosting unturned the steam dll files are sometimes out of date, so I usually delete the steamapps folder and have it update/verify integrity. That or I've heard people replace the outdated ones with the ones from their pc, the updated version. Also, sometimes with the WorkshopDownloadConfig.json it doesn't automatically update the workshops after a restart or a pack update so I've heard people having to delete the workshop folder from the Servers/ (your server id) /Workshop/Steam folder before restarting.

It's quite odd how buggy workshops are.

**Comment by SDGNelson** [comment]
There are some head-scratching issues that come up from time to time. Unturned does perform some extra checks for example comparing the local timestamp to the online timestamp to see whether the files are out of date. The game also checks the Steam dll file versions to ensure they are mostly up-to-date, but for now I still have to manually update the version the game considers up-to-date.

**Comment by DoomBoi113** [comment]
Thank you all for your feedback! First, i'd like to note that, although i can't download workshop mods on my server, i also cannot connect to server with absolutely no workshop mods that i host. To answer @joeymisfit, when i start servers (Via U3DS tool) somewhere in the blackbox i get this: 'Setting breakpad minidump AppID = 3049300'. I'm not sure where to check the version of the Unturned itself. As for the firewalls i've checked them and there doesn't seem to be anything blocking unturned or U3DS tool.  To answer @GazziFX , i've tried setting GSLT but then my server wont even finish configurating (i dont know if i've noted that all my server finish configuration), i belive i get something like 'Failed to connect to steam, no retrying' or smh like that in black box. To answer @SDGNelson , i've tried doing that with servers i used to have workshop mods, but since i've out of desperation reinstalled steam in order to see if that will somehow work (i dunno, don't ask why i thought that'll solve it), i currently have no servers with workshop mods on it, obly the default and testing server i created. I remember however trying deleting those files but that didn't resolve my issue then. One more information that might be useful: when i've complained to my friend about this, he tried hosting a dedicated server himself, but had exact same problem as i. We live in the same city. Forgive me if im being dumb but, could this be something that is state/area related?

**Comment by SDGNelson** [comment]
Are you using steamcmd to download/install U3DS?
Can you send the U3DS/Logs/Server_ (id) .log file to nelson@smartlydressedgames.com please?

**Comment by DoomBoi113** [comment]
No, i just downloaded it through steam. Should i use steamcmd? And ofcourse, i'll be sending the file.

**Comment by SDGNelson** [comment]
Thanks for the log file! It looks like the wrong appid (3049300) rather than 304930 is being used which is really bizarre but gradually reported more recently. Two ideas come to mind:

1. Could you check the steam_appid.txt file(s) in the U3DS folder please? They should have a single line of text: 304930 The game overwrites these to ensure the correct appid is used, but maybe something has gone wrong there. 

2. Could you try with steamcmd please? My other theory is that maybe there is a bug in the latest steamclient.dll / steamclient64.dll installed with Steam adding an extra zero, in which case maybe this does not happen with the redist copy of the dlls. Here is the official guide: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md#How-to-Install-SteamCMD-on-Windows

**Comment by DoomBoi113** [comment]
I checked the steam_appid.txt file and there really was a number 3049300. I just deleted one 0 and successfully connected! I'll be trying downloading workshop files but i bet there wont be any issues now. @SDGNelson thank you very, very much and i thank all the others for proposing other possible solutions!

**Comment by SDGNelson** [comment]
Thanks, that is good news! Very bizarre... I will check into this steam_appid.txt thing for the next update 😕

**Comment by SDGNelson** [comment]
Hopefully the issue does not repeat, but I am very curious to hear if it does because the game is super paranoid about setting the Steam appid now.
