### ISSUE TITLE
Possible Unity Upgrade

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#2986]
Dear Nelson,

Hello Nelson, I understand this request would be very troublesome considering that alot of things would break. However, in Unity 2021.2.7f1, built-in shader are able to use Shadergraph 12.1. Since Unturned is not using any render pipeline or LWRP, I feels like this would help create amazing shaders. So, is it possible for an upgrade to a Unity version with Shadergraph for built-in shaders? Or is it possible to use URP?

Yours Sincerely,
SMD

**Comment by GazziFX** [comment]
Answer in https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2967

You can try this for shaders https://assetstore.unity.com/packages/tools/visual-scripting/amplify-shader-editor-68570

**Comment by SMDIndomitable** [comment]
I would prefer if I could just use a built-in vs paying for the editor. I am currently using ShaderForge, though is old, it still works to a certain point. I was just wondering if is possible for shadergraph support. Sounds like it would take another year. Thanks for the info

**Comment by SDGNelson** [comment]
Sorry, @GazziFX linked comment is the current "state of affairs". I am excited to eventually have shader graph available, but no ETA.
