### ISSUE TITLE
Object Display Issue 

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#2987]
After the update, the display of some objects does not work correctly. I tried to recreate the location again, but it still didn't fix the situation.

The problem is observed in different parts of the map. 
I don’t know what it’s connected with. Everything worked fine before. 

https://youtu.be/YORu_ozDtuc

**Comment by SDGNelson** [comment]
Is it affected when you change the "draw distance" setting in-game? My initial thought is that something might be wrong with LOD0 in Unity.

**Comment by FireRain4** [comment]
Lod is fine. Maybe because of this red indicator, everything is bad? 
![image](https://user-images.githubusercontent.com/75787898/148766077-30186956-3487-479d-bd6f-a702b95ab7fe.png)

**Comment by FireRain4** [comment]
The draw distance does not affect this, I want to show that it is enough for drawing objects

**Comment by SDGNelson** [comment]
Despite the red indicator it *should* still be drawing properly. Do you have the map and assets available (e.g. on workshop) that I could load it up and try reproducing?

**Comment by FireRain4** [comment]
I can send you a link to download the modification and the map

**Comment by SDGNelson** [comment]
Sure

**Comment by FireRain4** [comment]
I have sent to your mail nelson@smartlydressedgames.com a link to download modifications and maps.

**Comment by SDGNelson** [comment]
Thanks for the map file! It is gorgeous and impressively detailed. When I visited the location it rendered properly, but my guess is that there is a large object missing from my copy which has "interior culling" enabled and surrounding that tower. There are a lot more objects with this enabled than I would expect, and many of them should probably not have it enabled. Here objects in Red are culled, Green are visible, and Black have no child objects. You can add the line "LOD None" to disable per-object .dat file.

https://i.imgur.com/uNFUOCp.png

**Comment by FireRain4** [comment]
Thank you.

It turns out that in order for me to fix the display, I need to add the LOD NONE line to the object configs?

**Comment by FireRain4** [comment]
Now everything works for me! Thank you! You are my hero!

**Comment by SDGNelson** [comment]
Glad to hear you got it working! To clarify: you only need to add "LOD None" to large objects which should not hide objects inside them. For example I noticed the brick road mesh had that feature enabled rather than disabled. "LOD None" is a misnomer, a better name would be "Interior culling" i.e. hiding objects inside the object.
