### ISSUE TITLE
Damage Falloff: Have a 2nd version that doesn't affect ballistics

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2988]
Damage falloff is good as it is, no issue on the current system. But from minor testing, it seems to rely on the ballistic settings, making the falloff linear. Unfortunately, it's not that extensive if it were to be used in different ways like creating a gun with slow-travelling & heavy shots with damage that drops slow or fast. So I want to suggest an alternate version of the damage falloff that can be easily tuned to be user-friendly. This version differs from the current one in that it can be configured without affecting the ballistic behavior. It is also by no means a replacement, rather another version with different features.

For this version of damage falloff, it can have values like:
- Minimum Damage Falloff - The minimum distance the gun can deal the base damage. Any projectiles beyond this value starts to fall off by distance.
- Damage_Falloff_Multiplier - This value works differently in this iteration of the damage falloff. It serves as the resulting damage after reaching the maximum damage falloff value.
- Maximum Damage Falloff - The maximum distance the gun can deal the damage based on the values from `Damage_Falloff_Multiplier`. This can be set separate from the maximum gun range.

Using the Maplestrike as an example, the base damage of 40, including the limb multipliers, take effect from the minimum damage falloff up to 40 meters. The total damage fall off after this up to the maximum damage dropoff. With the Damage_Falloff_Multiplier of 0.75, upon reaching the maximum damage falloff of 75 results the total damage to output as 30 instead and is capped to that total throughout until the Maplestrike's max range: 200.

**Comment by OneManOperative** [comment]
It is one of the main differences, yes. The other difference is that I want to have an available option to set a minimum range which the total damage can be dealt before it exceeds it & drops off further. Somewhat similar to CoD's damage falloff for its guns.

**Comment by SDGNelson** [comment]
Can you elaborate what the difference between that and damageFalloffRange is please?

**Comment by OneManOperative** [comment]
IIRC, the effects of damageFalloffRange is based around the ballistic values of the gun, maybe a bit on range too. So the difference between that and my proposed option is that the latter does not require changing the ballistic values. This makes it so that you can change min and max falloff ranges to specified values without affecting the ballistic behavior of your gun, or changing it.

**Comment by SDGNelson** [comment]
It uses the gun's Range, so for example a falloff start of 0.25 with a range of 1000m would start at 250 meters.

**Comment by OneManOperative** [comment]
For clarification, this is the current damage falloff function right? Anyway, if that's how it works currently, I can narrow it down to just suggesting that there should be a max distance that the damage caps to, which should stop damage falloff if it reaches that point. Using your example, it's basically having the option to end the falloff at 0.5, causing the total damage to be static until the max range of 1000m.

For reference, Battlefield 4 has guns with maximum damage falloffs distances where the damage is static & stays that way even after 500m.

**Comment by SDGNelson** [comment]
In good news: this was added as Damage_Falloff_Max_Range
