### ISSUE TITLE
The word "Anime" is censored in chat why?

### ISSUE THREAD

**Issue by AtiLion** [SmartlyDressedGames/Unturned-3.x-Community#299]
Title explains it all

**Comment by N1GHTPATROL** [comment]
It's because Nelson blacklisted "Anime" instead of fixing the problem

**Comment by yegac1337** [comment]
Just nelson being retarded old nelson, Cant fix server crashing, Blurs out random words. Can't fix stupid man.

**Comment by MazeW** [comment]
This is cat bots all over again. Instead of fixing the problem, blacklist certain words.

**Comment by SDGNelson** [comment]
Worth noting that AtiLion and yegac1337 are associated with the server list spam

.2 patch has a better longer-term solution
