### ISSUE TITLE
Remove restrictions on the number of things in the storage.

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#2990]
Remove restrictions on the number of things in storage from 255 to infinity.

I would also like to see a feature so that you can put a barricade into textures and still be able to open it.

**Comment by GazziFX** [comment]
Infinity is not possible 😆
Expansion wouldn't not compatible with some things, but yeah ushort instead of byte would nice. But I think it will be only available in new Inventory system, which Nelson is planning

**Comment by GazziFX** [comment]
> I would also like to see a feature so that you can put a barricade into textures and still be able to open it.

Texture is image, maybe you mean obstacles? It can be done with patches, or maybe open it with plugin if its some sort of Vault

**Comment by PARTOVIY** [comment]
Ahem.. I don't quite understand what you're saying.

I will try to explain the essence of the second problem. I have a box, and I put it through the map editor a little into the textures, but because of this it does not open.

**Comment by PARTOVIY** [comment]
This can be done through the plugin, but it will not look quite right. Since the event to open the box will not work while the box is in other polygons.

> > I would also like to see a feature so that you can put a barricade into textures and still be able to open it.
> 
> Texture is image, maybe you mean obstacles? It can be done with patches, or maybe open it with plugin if its some sort of Vault

This can be done through the plugin, but it will not look quite right. Since the event to open the box will not work while the box is in other polygons.

**Comment by GazziFX** [comment]
I know that, its because Unturned has poor checks. You need to patch that in InteractableStorage.ReceiveInteractRequest

**Comment by PARTOVIY** [comment]
Stop what? How to do it?

**Comment by GazziFX** [comment]
https://harmony.pardeike.net/#getting-started

**Comment by GazziFX** [comment]
or maybe just replace read delegate

**Comment by PARTOVIY** [comment]
> 

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2990#issuecomment-1013429027

**Comment by PARTOVIY** [comment]
I'm just new to plugin writing, so I don't quite understand how things work in csharp.

**Comment by SDGNelson** [comment]
Sorry, yes this kind of thing should be addressed once I get the chance to rewrite parts of the inventory. Working on replacing all usage of item 16-bit IDs, and inventory will be the last step. Then stuff like stacking, quantities, metadata, etc.
