### ISSUE TITLE
Meme for coders

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2992]
No comment.
![image](https://user-images.githubusercontent.com/17459138/149630187-c6920057-ef83-4728-916a-2dee3cfcaa2d.png)

**Comment by SDGNelson** [comment]
¯\_(ツ)_/¯

**Comment by surv0013** [comment]
For the sake of interest, I checked the game code after the last update, the bug is not fixed... :(

**Comment by GazziFX** [comment]
There are more significant problems which still not fixed for half year and more

**Comment by GazziFX** [comment]
![image](https://user-images.githubusercontent.com/43498426/188502005-fae0e3cf-8d34-4338-8248-916be25eebaf.png)
