### ISSUE TITLE
Potential of client-side modules

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#2993]
Hey, i don't think that the potential of client-side modules is fully used thus why not to add an option (while client is connecting to a server) to accept loading custom modules provided by the server. 
Modules could be provided via workshop.

This could be a game changer because unturned will become theoretically limitless

**Comment by rube200** [comment]
Client modules are not secure and will not work with battleEye

**Comment by benvalkin** [comment]
I would also really like to see something like this, however I'm sure we all realise that it would be that simple, especially if battleye is an issue.

**Comment by surv0013** [comment]
I would also like modules to be loaded from the server automatically on connection, however it cannot be denied that modules are extremely vulnerable and provide unlimited possibilities. It would be great if the game had its own internal scripting language, which would have functionality restrictions to prevent hacking players' PCs, however, we have been waiting for over three years for a redesign of the interface that will allow us to create more complex interfaces through plugins without using mods, so I think that the internal programming language will not appear in the game soon.

_P.S. Do you think interface update will happen in February 2025 or 2029?_

**Comment by benvalkin** [comment]
> I would also like modules to be loaded from the server automatically on connection, however it cannot be denied that modules are extremely vulnerable and provide unlimited possibilities. It would be great if the game had its own internal scripting language, which would have functionality restrictions to prevent hacking players' PCs, however, we have been waiting for over three years for a redesign of the interface that will allow us to create more complex interfaces through plugins without using mods, so I think that the internal programming language will not appear in the game soon.
> 
> _P.S. Do you think interface update will happen in February 2025 or 2029?_

Is an entire internal scripting language really a good solution? I feel like it would take a lot of time and effort to make, and it might be slow and limited in the end. Although, I can't really think of any other solutions... Maybe whitelisting certain servers from sending client modules so potential abuse is limited?

**Comment by SDGNelson** [comment]
Sorry, as others have pointed out this is unlikely to happen for a variety of reasons - namely preventing cheating and protecting players from malicious code.
