### ISSUE TITLE
[Feature Request] Make audio sources on muzzle Effects play when a UseableGun fires

### ISSUE THREAD

**Issue by benvalkin** [SmartlyDressedGames/Unturned-3.x-Community#2994]
From what I understand, currently when a UseableGun fires, it uses an AudioSource component added to the gun via code (I think when the gun is equipped) in order to play the 'Fire' sound. It would be great if other AudioSources attached to the muzzle's Effect prefab could also play when when firing.

I am requesting this feature because I would like to be able to create distant sounds for weapons (I.e muzzle Effects with more than one sound clip that can be heard at different distances). I can't imagine that this will be difficult to implement since it's just getting and playing audio sources, but I'm not sure if there might be any issues with this design.

If not this, perhaps you might want to consider proper support for distant weapon sounds. They work really well for other games, and I think
they would really do a lot for Unturned by making gunshots sound better and more interesting.

**Comment by surv0013** [comment]
The game has a problem with the sounds of shots, they can be heard from everywhere, you can't specify the radius of the sound. :(

**Comment by SDGNelson** [comment]
Would be nice to have something like this, but currently there are multiple copies of the muzzle effects at once. This would be part of a longer-term plan to use the third-person model for first-person view.

**Comment by GazziFX** [comment]
You can implement it by yourself just spawn sound effect when player is shooting

**Comment by benvalkin** [comment]
@GazziFX could you explain what you mean a bit better?

**Comment by GazziFX** [comment]
> @GazziFX could you explain what you mean a bit better?

Calculate distance to each players if it greater than `n` play effect else play gun shot

**Comment by benvalkin** [comment]
So you mean with a server plugin by using EffectManager. SendEffect()?

**Comment by GazziFX** [comment]
Yes

**Comment by benvalkin** [comment]
That would work and I am happy to do that for my server, but it's quite silly to make a custom effect and send it to all players via an extra net call when someone shoots, which will also only work on servers with the plugin installed. I would like a proper solution, so we'll see what happens in the long term.

**Comment by surv0013** [comment]
> That would work and I am happy to do that for my server, but it's quite silly to make a custom effect and send it to all players via an extra net call when someone shoots, which will also only work on servers with the plugin installed. I would like a proper solution, so we'll see what happens in the long term.

I agree that the solution proposed by Gazzi is more expensive in terms of resources, but are you sure that you will live to see the update that Nelson writes about? You, apparently, are here for the first time, if Nelson wrote that this is planned in the future, then it remains to wait at least two years.

_P.S. Nelson, do not ban for the truth! 😆_

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
