### ISSUE TITLE
Navemesh and Animals

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2995]
I need to create an invisible object for animals. An invisible wall so that they don't get where they don't need to. The clip zone for killing animals does not work.

I would like to clarify, will the collider be restricted in the Navmesh prefab of animals? Or is it just for zombies?

**Comment by GazziFX** [comment]
Animals don't use navmesh they just go straight, I made plugin in old times which add AIPathvto animals and it works

**Comment by JorelDecker** [comment]
> 

The question is, will navmesh be able to stop the animals? So that they rest against an invisible wall

**Comment by JorelDecker** [comment]
> Animals don't use navmesh they just go straight, I made plugin in old times which add AIPathvto animals and it works

The question is, will navmesh be able to stop the animals? So that they rest against an invisible wall

**Comment by GazziFX** [comment]
> The question is, will navmesh be able to stop the animals? So that they rest against an invisible wall

As i know nav gameobject is spawn only while backing navmesh, this backed navmesh don't have collider, so it cant stop animal

**Comment by SDGNelson** [comment]
It looks like animal character controllers are on the "Agent" layer, so yes the navmesh colliders will block them.
