### ISSUE TITLE
Airdrop does not appear on the map

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2996]
Airdrop does not appear on the map. I set up several airdrop points on the map, when it is called, it does not appear. It's the same on pei, but it's called there

**Comment by GazziFX** [comment]
What ID is in airdrop point?

**Comment by JorelDecker** [comment]
> 

I entered the same as on Pei, it didn't give a result

**Comment by SDGNelson** [comment]
Do you have a custom level config and/or level asset configured? If so, they might be overriding some of the airdrop settings. Also make sure airdrops are enabled in your gameplay config.
