### ISSUE TITLE
Oh dear Nelson, my Steam account is blocked by VAC. Please help me!

### ISSUE THREAD

**Issue by chenyicheng311** [SmartlyDressedGames/Unturned-3.x-Community#2997]
@SDGNelson Dear Nelson sorry,I'm interrupting your rest. I'm from China. I really like Unturned. I'm a beginner MOD developer. When I made the MOD, I accidentally placed the finished MOD in multiple directories in the Unturned directory. This may have been detected by your anti-cheating system, and I meant no harm. I need to get VAC lifted, I can continue to upload my MOD. I SteamID76561198863841847 / (I'll buy your DLC) please help me!!!!!!!!!!!!
Thank you so much!     is BattlEye ban

**Comment by chenyicheng311** [comment]
sorry is BattlEye ban

**Comment by GazziFX** [comment]
Mod can't be detected by BattlEye because anticheat searching for executable memory sections, processes, drivers, etc. Maybe some of your programs is detected by BattlEye

**Comment by chenyicheng311** [comment]
i think so BUT I don't have hack and some what !

**Comment by GazziFX** [comment]
I think Nelson will reply: "Contact to BattlEye"

**Comment by chenyicheng311** [comment]
i know BUT BattEye not help me 。i really need to unban!!!  i need Nelson help!

**Comment by chenyicheng311** [comment]
you konw ,i'm very busy.

**Comment by chenyicheng311** [comment]
my players need my MOD

**Comment by chenyicheng311** [comment]
and i Modify game file .becuse i put my MOD in. i don't know is not well !!!

**Comment by chenyicheng311** [comment]
I even wrote an email to battleye, but my friend said it was useless! I need Nelson's help!

**Comment by SDGNelson** [comment]
Sorry, you will need to contact BattlEye support here: https://www.battleye.com/contact/

**Comment by chenyicheng311** [comment]
oh NO!!!!!!!!!!!!!!

**Comment by chenyicheng311** [comment]
BattlEye suppor NOT HELP ME!!!!!!!!!!!

**Comment by chenyicheng311** [comment]
PLSSSSSSSSSSSSSSSSSSSSSSS!!!!!

**Comment by educatalan02** [comment]
All the other mod developers aren't banned, so I don't think you placed it in a wrong folder.

**Comment by chenyicheng311** [comment]
i know .but i use Chinese&nbsp;patch.&nbsp;That modified the game file.Maybe I'm using some.exe program that the anti-cheat system considers to be cheating software. I can provide anything I use or test only on my server!! This is an incorrect ban!!I don't mean any harm. No violation of the rules of the game. I just want to upload my MOD to creative Workshop!!!!!!!!!!
help me please!!!!!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





 
所有其他 mod 开发者都没有被禁止，所以我认为你没有将它放在错误的文件夹中。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于iOS或Android
的 GitHub Mobile 随时随地对通知进行分类。 您收到此消息是因为您编写了该主题。
消息 ID：<SmartlyDressedGames/Unturned-3 。x-社区/问题/2997/1017677715 @ github 。com&gt;

**Comment by educatalan02** [comment]
Modified the game means the same (Cheating)

**Comment by chenyicheng311** [comment]
Oh no no no, I did not cheat at all ！！！！ Just accidentally changed the file, and it didn't bother anyone ！！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 上午7:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





 
修改游戏意思相同（作弊）
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
使用适用于iOS或Android 的GitHub Mobile 随时随地对通知进行分类。 
您收到此消息是因为您编写了该主题。消息 ID：<SmartlyDressedGames/Unturned-3 。x-社区/问题/2997/1018021850 @ github 。com&gt;

**Comment by GazziFX** [comment]
Stop spam

**Comment by chenyicheng311** [comment]
This is not spam!! I just want to unblock me!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 中午1:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





 
停止垃圾邮件
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于iOS或Android
的 GitHub Mobile 随时随地对通知进行分类。 您收到此消息是因为您编写了该主题。
消息 ID：<SmartlyDressedGames/Unturned-3 。x-社区/问题/2997/1018188878 @ github 。com&gt;

**Comment by GazziFX** [comment]
Its not possible

**Comment by chenyicheng311** [comment]
why




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 中午1:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





 
这是不可能的
 
-
直接回复此电子邮件，在GitHub上查看，或取消订阅。
使用适用于iOS或Android的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by chenyicheng311** [comment]
why no unban me?&nbsp;
tell me




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 中午1:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





 
这是不可能的
 
-
直接回复此电子邮件，在GitHub上查看，或取消订阅。
使用适用于iOS或Android的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by chenyicheng311** [comment]
怎么不说话了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmartlyDressedGames/Unturned-3.x-Community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





 
Its not possible
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by surv0013** [comment]
> 怎么不说话了？

尼尔森不会解除对你的阻挡，他不会干扰来自 BattlEye 的阻挡。 您将不得不等待 BattlEye 的回复，但他们也不太可能解除您的禁令，因为他们的禁令很少会发生错误。 此外，你自己写了你修改了游戏代码，这是 BattlEye 规则禁止的，即使你不想作弊。

**Comment by chenyicheng311** [comment]
It was inevitable. It was a mistake. I don't want to be banned from QAQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 晚上8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





  
怎么不说话了？
  
尼尔森不会解除对你的阻挡，他不会干扰来自 BattlEye 的阻挡。 您将不得不等待 BattlEye 的回复，但他们也不太可能解除您的禁令，因为他们的禁令很少会发生错误。 此外，你自己写了你修改了游戏代码，这是 BattlEye 规则禁止的，即使你不想作弊。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyicheng311** [comment]
I didn't change the game code with any malice. It's not hurting anybody. It's not hurting anybody






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmartlyDressedGames/Unturned-3.x-Community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





  
怎么不说话了？
  
尼尔森不会解除对你的阻挡，他不会干扰来自 BattlEye 的阻挡。 您将不得不等待 BattlEye 的回复，但他们也不太可能解除您的禁令，因为他们的禁令很少会发生错误。 此外，你自己写了你修改了游戏代码，这是 BattlEye 规则禁止的，即使你不想作弊。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyicheng311** [comment]
Also, thank you for replying to me in Chinese!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 晚上8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Oh dear Nelson, my Steam account is blocked by VAC. Please help me! (Issue #2997)





  
怎么不说话了？
  
尼尔森不会解除对你的阻挡，他不会干扰来自 BattlEye 的阻挡。 您将不得不等待 BattlEye 的回复，但他们也不太可能解除您的禁令，因为他们的禁令很少会发生错误。 此外，你自己写了你修改了游戏代码，这是 BattlEye 规则禁止的，即使你不想作弊。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
