### ISSUE TITLE
Steam Inventories are Bugging Out

### ISSUE THREAD

**Issue by AnimaticFreak** [SmartlyDressedGames/Unturned-3.x-Community#30]
(Itemdefid: 'insert number here')

**Comment by xdlewisdx** [comment]
Inventories work fine, restart Unturned/Steam

**Comment by AnimaticFreak** [comment]
I restarted Unturned and it didn't work,
Restarted Steam, that didn't work either. 
I'm just going to assume that this is Valve's issue and they haven't fully fixed it.

**Comment by V1CeNtE** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=1182184785

**Comment by xdlewisdx** [comment]
Fixed in latest update.
