### ISSUE TITLE
Did rendering distance and conditions change?

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3000]
Im having a problem with the rendering distance of effects: they seem to stop rendering when I go about 200 meters away from them. But when I go back into this radius, it renders again. I wouldn't have questioned it, if it wasnt different some time before, and it seems to be a recent change.
For example, I've been using Zoli's Scud-B mod, and I couldn't see this nuclear explosion when 200 meters away from it, but I can clearly remember that you could see it from any distance, even the maximum range of Scud weapon, and Zoli's videos also show that.

I've been having the same issue with my own effects too, and Relevant_Distance doesnt seem to affect that. I think that it must be a somewhat recent change, because I've been working with effects for several months now, and its the first time I encounter such problem.

P.S. My graphic settings are maxed out when it comes to rendering distance, so Its not the reason of this

**Comment by SDGNelson** [comment]
There should not have been any recent changes to this. The fact you do not see and then see it again makes me think it is one of the clientside culling settings, not network related. What layer is the renderer on? Does it have any lod groups configured?

**Comment by DerpyHoowes** [comment]
Figured out that it wasnt tagged Large
