### ISSUE TITLE
Unturned ValidateAssets invalid guid issue.

### ISSUE THREAD

**Issue by JuicyNuts** [SmartlyDressedGames/Unturned-3.x-Community#3001]
I keep getting this bug when trying to join a certain server (Brads RP, yes I play Brads because why not), Ive deleted my mods from my steam folder and I downloaded them again, worked for a bit and when the electricity went off (shitty country) I tried joining again and it said the same thing again. I verified game files, still didn't work. From what I know multiple people have been getting the issue. So any idea on how to fix this or? From what I heard it may be caused by the recent update which was 3.22.20.
![Screen Shot 2022-01-24 at 00 20 23](https://user-images.githubusercontent.com/74527962/150700434-10d7abbf-cb32-4c22-81bb-024fc2cc5f8b.png)

**Comment by SDGNelson** [comment]
This means the asset does not exist on the server. The client only sends guids which it knows the server will have loaded (at least in vanilla code) or if the client was able to load the asset locally. My guess is that a plugin on the server is doing something wonky with barricades/structures spawning assets that are missing from the server.

**Comment by JuicyNuts** [comment]
Ah, alright. Thank you.
