### ISSUE TITLE
Bug: Server kicks players due to Alicepack asset mismatch

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3003]
A friend is trying to join his server, but apparently can't due to the Alicepack???

![image](https://user-images.githubusercontent.com/48363842/150828081-ba45654f-cf50-473c-97ee-a534b7c2fb48.png)

I do not understand what causes this, so help would be appreciated.

**Comment by surv0013** [comment]
This error occurs when the file hashes on the client and server do not match. Tell him to verify the integrity of the game's hash.

**Comment by SDGNelson** [comment]
surv0013 is correct, but another potential cause is: have you modified the Alicepack on your server? If so, you can add this line to the .dat file: Should_Verify_Hash

**Comment by OneManOperative** [comment]
Thank you. The issue was gone beforehand but I'll keep that in mind.
