### ISSUE TITLE
Gold

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3006]
I have seen servers where Gold accounts are combined into one. How is this done?

**Comment by GazziFX** [comment]
Do you mean only 1 character per account? Im not sure if this setting is present in config, but you can just assign 0 to characterID when player connecting to server

**Comment by JorelDecker** [comment]
> Are you a plugin developer?

No

**Comment by CyberAndrii** [comment]
`Allow_Per_Character_Saves` in Config.json

**Comment by JorelDecker** [comment]
> 



> `Allow_Per_Character_Saves` in Config.json

Do you just need to enter this line or do you need to set the value to False?

**Comment by GazziFX** [comment]
Value to false

**Comment by JorelDecker** [comment]
> Value to false

Thank you very much. There is a question. After entering this line, what will happen to the rest of the characters?

**Comment by GazziFX** [comment]
> > Value to false
> 
> Thank you very much. There is a question. After entering this line, what will happen to the rest of the characters?

For those who use only main acc nothing, but for other it can wipe, be careful and set only when you decided to wipe server

**Comment by JorelDecker** [comment]
> For those who use only main acc nothing, but for other it can wipe, be careful and set only when you decided to wipe serv

Thanks. May the force come with you, good man
