### ISSUE TITLE
Server crashes when trading with NPCs while holding ctrl

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#3009]
Hey! A player on my server yesterday bought an item from an NPC with all his money and the server went down. exp he had a lot and about 10k items fell to the ground. I don't know if there is a limit, but it happened. It is not normal.
Also, people complain that it is inconvenient to trade with NPCs with a small frequency. It would be better if ctrl sold / bought NPC items in stacks, for example, 10 items. Or so that I can set it all up myself =)

**Comment by GGnebudet** [comment]
If you press ctrl when buying an item from the NPC, then you can buy a maximum of 64 items like

**Comment by MrGoBi** [comment]
Yes, you are right, but if you use your own currency, then crashing the server becomes real
![image](https://user-images.githubusercontent.com/46658857/151606508-25e92da1-314d-4691-b646-24e6f6d03025.png)

**Comment by SDGNelson** [comment]
Do the items have any special conditions that might be slower to process? Or was it just a regular item? How did it drop 10k items - was it dropping the currency?

**Comment by MrGoBi** [comment]
> Do the items have any special conditions that might be slower to process? Or was it just a regular item? How did it drop 10k items - was it dropping the currency?

Currency + purchased items.
Items have rewards in the form of reputation

**Comment by SDGNelson** [comment]
IIRC there were some changes to this. Sorry that I didn't reply at the time. If it is still a problem please feel free to comment and I will re-open.
