### ISSUE TITLE
"Your client and the server disagree about whether you have gold"

### ISSUE THREAD

**Issue by Discordcoder** [SmartlyDressedGames/Unturned-3.x-Community#3012]
No matter what server I join it tells me "Your client and the server disagree about whether you have gold" even though the server does not require gold. Also I have all the skillsets unlocked even though I don't have any gold. I did everything and nothing fixes the problem. I verified files, redownloaded 5 times, logged in and out, went on a different account and nothing works.

**Comment by SDGNelson** [comment]
This means your client thinks you own the gold upgrade, but the Steam servers disagree. Are you using a hack/cheat?

**Comment by GazziFX** [comment]
In BeyondCheats was that feauture, can you clear Unturned cloud saves?

**Comment by GazziFX** [comment]
It should be in `Steam\userdata\{your_steamid_32}\304930\remote`

**Comment by Discordcoder** [comment]
> This means your client thinks you own the gold upgrade, but the Steam servers disagree. Are you using a hack/cheat?

I don't use any cheats except for the cheat codes which are built into the game but I did play this game long ago and I could have maybe used cheats.

**Comment by Discordcoder** [comment]
> It should be in `Steam\userdata\{your_steamid_32}\304930\remote`

Deleted it all and then redownloaded the game and turned off cloud but IT STILL DOES NOT WORK WTF

**Comment by SDGNelson** [comment]
**Do** you own the gold upgrade? Or perhaps do you have a modification installed to Steam which bypasses DRM?

**Comment by Discordcoder** [comment]
> **Do** you own the gold upgrade? Or perhaps do you have a modification installed to Steam which bypasses DRM?

I do not own the gold upgrade and I don't think I have any modification.

**Comment by Discordcoder** [comment]
I litterly just downloaded the game and didn't do any cheats or anything like that I just wanted to start playing it since I saw it on youtube and when I tried joining a gold server it didn't let me. I did not modify anything with the game I just downloaded it from steam and then tried to join a server.

**Comment by SDGNelson** [comment]
If you uninstall the game and then look in your Unturned folder are any files left behind? I think the most likely explanation is that you have installed a hack/cheat in the past which Steam would not remove as part of uninstalling the game.

**Comment by Discordcoder** [comment]
> If you uninstall the game and then look in your Unturned folder are any files left behind? I think the most likely explanation is that you have installed a hack/cheat in the past which Steam would not remove as part of uninstalling the game.

There is and now I deleted it and it redownloaded the game and doesn't work.

**Comment by SDGNelson** [comment]
What happens when you try to play now?

**Comment by Discordcoder** [comment]
> What happens when you try to play now?

Same thing as I said before "Your client and the server disagree about whether you have gold"

**Comment by SDGNelson** [comment]
Sorry, I am not sure what else to suggest. I am fairly confident there is a hack/cheat leftover somewhere - i.e. this is not a problem with the game itself.

**Comment by SDGNelson** [comment]
Sorry for the long delay, but just in case I have added an option in this most recent update that should work around the kick:
1. Right-click Unturned in your Steam Library
2. Select Properties... > General
3. Find the Launch Options field
4. Type "-NoGoldUpgrade" without quotes

**Comment by Sas3y** [comment]
Is there a way to do this launch option not from within steam? I run a small server and hate that I can't launch unturned while the server is on, as on steam it says "stop" where "start" should appear. I launch E:\SteamLibrary\steamapps\common\Unturned\Unturned.exe but this one I cant seem to change to -NoGoldUpgrade.
Also I believe this issue is somehow connected when players from long ago played the game and stopped, as now me(5yr gap) and my friend(7yr gap) downloaded the game again and both got this issue.

**Comment by GazziFX** [comment]
If you click stop it should close Unturned_BE not the server. You can run with parameters not in Steam by creating link to Unturned_BE.exe and add -NoGoldUpgrade in the end after `"` in link properties
