### ISSUE TITLE
Navi clip volume cannot be selected

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3014]
I put navclipvolume in devkit, but it is impossible to select it to edit. At the same time, everything else stands out. Not only do I have such a bug, it does not stand out either from my friend who put this zone on a completely different map

**Comment by SDGNelson** [comment]
Sorry, do you have the "Navmesh" layer enabled in the Selection Tool layer mask?
