### ISSUE TITLE
Game crashes trying to join a server

### ISSUE THREAD

**Issue by BondarCalabria1** [SmartlyDressedGames/Unturned-3.x-Community#3015]
Whenever i try joining a server the loading screen appears and the game instantly stops working making me have to close it and not allowing me to play, i've unsubbed from all mods, resubed, unsubbed again tried without any mod but nothing works, how could i help identify the problem?

**Comment by SDGNelson** [comment]
Sorry for the trouble! Could you email me (nelson@smartlydressedgames.com) this file please? There may be a clue:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the "Unity Temp" folder
4. Zip and attach the Crashes folder to your email

**Comment by JuicyNuts** [comment]
@BondarCalabria1 Question, have you changed your chat logs length to an insane number in preferences.json? Or possibly changed something else? I had the same issue yesterday, I put my chat logs length to like 59999 while I was in game, I logged off. Woke up started the game and it didn't work. I thought maybe because I changed the chat logs length, so I went and changed it to 600 and guess what, it worked.

**Comment by BondarCalabria1** [comment]
> @BondarCalabria1 Question, have you changed your chat logs length to an insane number in preferences.json? Or possibly changed something else? I had the same issue yesterday, I put my chat logs length to like 59999 while I was in game, I logged off. Woke up started the game and it didn't work. I thought maybe because I changed the chat logs length, so I went and changed it to 600 and guess what, it worked.

No not really, only thing i ever touched on preferences.jason was the thing to make the game look more "vibrant" but that was like a year ago

**Comment by BondarCalabria1** [comment]
> Sorry for the trouble! Could you email me ([nelson@smartlydressedgames.com](mailto:nelson@smartlydressedgames.com)) this file please? There may be a clue:
> 
> 1. Right-click Unturned in your Steam Library
> 2. Select Properties... > Local Files > Browse...
> 3. Open the "Unity Temp" folder
> 4. Zip and attach the Crashes folder to your email

Hello yes, it doesent let me open the "unity temp" folder and googling the issue doesent show any result on how to get it to open, it says something about connection issue or not inserting the disc correctly but i dont know what to do about that

**Comment by BondarCalabria1** [comment]
After seeking for help and a solution on the discord server the problem seems to have been resolved for now, i hope it keeps beeing this way, if anything happens ill open another issue post here or ask again in the discord, thatnks for your time

**Comment by SDGNelson** [comment]
Glad to hear you got it working!
