### ISSUE TITLE
[Bug] Player Stance change can't Crouch to Prone

### ISSUE THREAD

**Issue by DerSpeedMann** [SmartlyDressedGames/Unturned-3.x-Community#3016]
If a player is crouched and tries to prone he will first change his stance to Stand before changing to Prone. So you could not detect if a player was crouched before going prone.

If a player is crouched and tries to prone he will first change his stance to Stand before changing to prone. So you could not detect if a player was crouched before going prone.

Tested on Rocket v4.9.3.13 for Unturned 3.22.2.0
with:
Player.stance.onStanceUpdated

EDIT:
This does not happen when changing from prone to crouch and pressing prone before the crouching animation has finished.

**Comment by SDGNelson** [comment]
Thanks for the report! I will get this fixed for the next update.

**Comment by SDGNelson** [comment]
Fixed for the next update!
