### ISSUE TITLE
NPCs Quest Hidden Conditions

### ISSUE THREAD

**Issue by Tiway-Paper-Guy** [SmartlyDressedGames/Unturned-3.x-Community#3019]
Hello!
Currently, when a player receives a quest, every condition is displayed. It would be great to be able to hide some conditions, and only show them when needed. This will allow quests with successive objectives to be more precise, and will allow people to make more complicated quests with twists for example.

Having conditions on conditions like this may be too complex, but it uses the standard condition features that already exists.
Conditions 1
Condition_0_**Conditions 1**
Condition_0_**Condition_0_.....**

As I see it, this feature should not disable a condition as if it was not required to complete the quest, but would hide it so it can be displayed later when a condition is met.

Thanks!

**Comment by SDGNelson** [comment]
I like it, that is a pretty cool/useful idea. Would probably format as something like `Condition_#_VisibilityConditions` for readability.

**Comment by surv0013** [comment]
> I like it, that is a pretty cool/useful idea. Would probably format as something like `Condition_#_VisibilityConditions` for readability.

You know what else is a pretty cool/useful idea? Add the ability to remove the quest UI from the top right of the screen. #3004

**Comment by Tiway-Paper-Guy** [comment]
> I like it, that is a pretty cool/useful idea. Would probably format as something like `Condition_#_VisibilityConditions` for readability.

Thanks! Will work fine, and it's easy to differentiate from the quest conditions themselves

**Comment by SDGNelson** [comment]
Why closed? It is a good idea

**Comment by Tiway-Paper-Guy** [comment]
My bad, I thought I could close it because you already saw it, sorry xD

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
