### ISSUE TITLE
ChatManager.serverSendMessage sends messages multiple times

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#302]
```cs
ChatManager.serverSendMessage("Hello :)", Color.red, fromPlayer, null /* toPlayer */, EChatMode.Global, iconUrl, true /* is rich */)
```
This sends message multiple times, as often as player count.
For example, if there are 3 players online, it will show "Hello :)" 3x to everyone.

It doesn't matter if toPlayer is null or not.

**Comment by SDGNelson** [comment]
All of the chat goes through serverSendMessage in 3.24 (e.g. chatting, vanilla command messages, alerts), but in vanilla they seem to go through correctly. Is there somehow a null entry in your server's Provider.clients? (Bot player for testing or something) I'll adjust that to not send to null clients in the next patch

**Comment by Trojaner25** [comment]
Nevermind, I found the issue; it was related to a mistake in my plugin.

Sorry for wasting your time.
The feature is really nice btw 👍
