### ISSUE TITLE
Armor-piercing cartridges

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3020]
I need to increase the damage of the weapon using the magazine. How do I do this? Without the use of explosive cartridges, because the minimum range to work, you need 3 meters. And this will already affect neighboring players.

**Comment by JorelDecker** [comment]
I tested Ballistic_Damage_Multiplier on the store, and shot at zombies. This had no effect. Maybe it doesn't work on zombies, but it works on the player

**Comment by SDGNelson** [comment]
It looks like Ballistic_Damage_Multiplier should work against the zombies. Maybe worth another try?

**Comment by JorelDecker** [comment]
> It looks like Ballistic_Damage_Multiplier should work against the zombies. Maybe worth another try?

I tried several times.  Can you write an example of how to apply this to a magazine?  Perhaps I entered something wrong.
I entered 10 Damage to zombies and Ballistic_Damage_Multiplier 15 in the magazine settings, it had no effect

**Comment by SDGNelson** [comment]
I will mark this as "next update" so that I remember to give it a try and double-check.

**Comment by SDGNelson** [comment]
Tested by adding this line to the 100-rnd military drum and comparing against the 30-rnd military magazine it worked as-expectd:

`Ballistic_Damage_Multiplier 5`
