### ISSUE TITLE
Tracking button clicks

### ISSUE THREAD

**Issue by Quzile** [SmartlyDressedGames/Unturned-3.x-Community#3022]
Hello! Tell me, please, how can I track the button pressing by an individual player? Somehow using PlayerInput.onPluginKeyTick?

**Comment by SDGNelson** [comment]
Did you want to track UI button components, or plugin key presses?

**Comment by Quzile** [comment]
Plugin key presses. For example, a player presses the [Q] key and an event occurs...

**Comment by Quzile** [comment]
Oh, I figured it out, I'm closing the topic :)
