### ISSUE TITLE
Unturned Hosting Server Problem

### ISSUE THREAD

**Issue by amidstacy** [SmartlyDressedGames/Unturned-3.x-Community#3023]
So this is my first time setting up the server, and "Failed to connect to Steam servers because k_EResultInvalidParam, no longer retrying" happened. I saw a thread but it wasn't my case as im using everything local and not workshop

Would appreciate a reply early, thanks

**Comment by SDGNelson** [comment]
Can you attach your Server_ (id) .log file please? It sounds like maybe an improperly formatted GSLT - if you remove the GSLT does it work?

**Comment by amidstacy** [comment]
It works, but only LAN server.
[Server_MyServer.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8019847/Server_MyServer.log)

**Comment by SDGNelson** [comment]
As in, it works without GSLT but only in LAN mode? Based on the error I do think the problem is the GSLT.

**Comment by amidstacy** [comment]
Actually- first i replaced the line on the config thingy about pasting your token there but all it did was a LAN server. So instead i did GSLT (login token) on commands. do i have to remove my token on my config thing and leave the other token as is?

**Comment by SDGNelson** [comment]
Commands.dat GSLT takes priority, if empty it uses the GSLT from Config.json

**Comment by amidstacy** [comment]
Then what do i do next? :( I've followed the steps correctly as far as i know

**Comment by SDGNelson** [comment]
So, if I understand correctly, it worked after you removed the GSLT from both? In that case I would recommend re-generating and putting into Config.json. For the next update I also added a warning message when the GSLT is improperly formatted.

**Comment by amidstacy** [comment]
Will try later, hopefully it gets fixed

**Comment by amidstacy** [comment]
Actually i'll do it now. this works?

"Login_Token": "token here",

**Comment by amidstacy** [comment]
Ok, sorry for replying late. didn't work. It's still a LAN server

**Comment by SDGNelson** [comment]
So you are still getting the "k_EResultInvalidParam" error? Can you post the most recent log file please?

**Comment by amidstacy** [comment]
No, I only get that when i put both login tokens in Commands and Config. This time I did it  on Config only
[Server_MyServer.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8084297/Server_MyServer_Prev.log)

**Comment by amidstacy** [comment]
Don't mind the Failed to convert. I was experimenting with the port because it didn't work. i used port 27015 again

**Comment by SDGNelson** [comment]
It looks like that log file is from the previous version, and it shuts down before it tries to connect to Steam. Could you update to the latest version and re-attach the log file after it errors please?

**Comment by amidstacy** [comment]
Oh. i probably shut it down while it was loading. ill redo the whole thing be right back

**Comment by amidstacy** [comment]
[Server_MyServer.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8084890/Server_MyServer.log)
again dont mind the map error lol

**Comment by amidstacy** [comment]
Ah oops. Didn't read it carefully. My game is up-to-date. do you mean the server? do i just click Unturned.exe on U3DS?

**Comment by SDGNelson** [comment]
That log file looks like it is on the previous version as well. To update you need to run app_update 1110390 in steamcmd.

**Comment by amidstacy** [comment]
not online or logged in to steam? im logged in to steam

**Comment by amidstacy** [comment]
[Server_MyServer.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8092167/Server_MyServer.log)
Updated it now my bad

**Comment by SDGNelson** [comment]
Thanks, it looks like it starts up mostly fine, however it is loading the PEI map because Arid is not in the workshop download config. What seems to be the problem now?

**Comment by amidstacy** [comment]
Oh. Soo it would show up now on the public server list?

**Comment by SDGNelson** [comment]
Yes: if you are not getting any errors anymore it should be listing correctly.
