### ISSUE TITLE
Return back NPC buy/sell rate

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3024]
Hi Nelson!
Can you return back npc buy/sell rate, becouse it's very terrible to buy either all or very slowly in 1 item.
I like new system, when you can press CTRL and and buy a bunch of items at once click, but if i need to buy 5 or 10 items I have to very slowly click on button.
P.S: I play on IMGUI, and pressing ctrl does not give any effect when buying/selling.

**Comment by SDGNelson** [comment]
Do the other "hold CTRL" buttons work for you like bulk crafting? The reason the rate limit was lowered was to prevent spamming huge orders, but the order size will probably have to be decreased to 8 or so anyway, so the rate limit will be raised.

**Comment by QERT2002** [comment]
Thanks for reply!
No, ctrl+ don't work in IMGUI.
I can craft all or one item by pressing buttons and it's very comfortably.
About the restrictions, you can add 2 void's, 1:Craft 32 items(64 very big), 2:Craft 1 item, and set different rate.

**Comment by QERT2002** [comment]
![image](https://user-images.githubusercontent.com/39222548/152934443-81c8ef3a-75ec-4b32-a1c7-caa5df90418f.png)
