### ISSUE TITLE
Time still Ticks while Paused

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#3027]
if you pause the game in singleplayer, the time rotation still applies, but nothing else does. you can see this in the video i have linked, where i pause mid air to show the game has truly paused, but the shadow of the tree still moves.

https://imgur.com/a/DjZRIgk

**Comment by SDGNelson** [comment]
Unfortunately this is a known issue. Tidied up some of the related stuff (2.0 time synced between SP and MP) later last year, and will hopefully continue this year.
