### ISSUE TITLE
[Useable Gun Event Hook] Hammer is missing

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3030]
Can you add a new feature for Hammer? It turns out funny. You need to make shutter movements when it is distorted. But the shutter animation happens on Hammer, not Reload. And you didn't add the Hammer function, you would need to fix it.

**Comment by SDGNelson** [comment]
In the UseableGunEventHook component it is called OnChamberingStarted

**Comment by JorelDecker** [comment]
> In the UseableGunEventHook component it is called OnChamberingStarted
It turns out that it will work with both Hammer and wedge?
