### ISSUE TITLE
Clothes Quality

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3032]
Firstly, the line on the disappearance at 0 strength, does not work on clothes. Secondly, I wanted to ask if there is any line to edit the strength of clothing? It is necessary that with several hits, it completely breaks down and disappears.

**Comment by SDGNelson** [comment]
Could you elaborate on your first point please? As for the second point: sorry, it is only one point of damage per hit currently.

**Comment by JorelDecker** [comment]
> Could you elaborate on your first point please? As for the second point: sorry, it is only one point of damage per hit currently.

I wanted the clothes to disappear when they lose their durability
