### ISSUE TITLE
The problem with BattlEye: Query Timeout

### ISSUE THREAD

**Issue by Carl6363346346** [SmartlyDressedGames/Unturned-3.x-Community#3034]
The problem is that I log on to the server and I get a BattlEye error: Querly Timeout and I can't log in and play calmly on the server, I reinstalled mods, the game, even BattlEye. Nothing helps helps, please help me friends! I will be grateful!

**Comment by SDGNelson** [comment]
Sorry, this is outside the game's control, I would recommend contacting BattlEye support here: https://www.battleye.com/contact/
