### ISSUE TITLE
Animal Animation Transitions

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3035]
Currently Animals Animations look very choppy. I think some proper Animation transitions could help a lot with the look of Animals.

I am not the most experienced person with Unity and Animating in it. Still, I believe if Animals were refactored to use a proper Animator instead of the Animation.Play function they could easily support transitions. Honestly this feels like something that would be apart of an Animal rework. Something which we are really due considering how basic and underdeveloped animals currently are.

Sorry if I come off as uninformed, I have a very basic knowledge of Animations in Unity.

**Comment by SDGNelson** [comment]
No disagreement here - I would like to upgrade Unturned's animations across the board - but no ETA.
