### ISSUE TITLE
Skins with identical names (Silver skins)

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3036]
**ISSUE:** There are two different skin patterns that are called "Silver". This issue stems from the introduction of trophy skins. Specifically, there is the possibility of **Silver Augewehr** (already exists) and a **Player's Silver Augewehr** (could exist).

**DETAILS:** The only difference being that trophy skins are prefixed with the player's name. However, there have been instances where player names have prefixed other skins as well (such as on fr34kyn01535's RocketMod Shirt).

**PROPOSAL:** My proposal is rename the **Silver Augewehr** skin (and any other future Silver skins) to "**Silvered Augewehr**". Trophy skins would be left unchanged. Alternatively, trophy skins are named to something such as "**Player's Silver Trophy Augewehr**".

**Comment by SDGNelson** [comment]
Good point: will rename Silver Augewehr to Silvered Augewehr like you proposed!

**Comment by SDGNelson** [comment]
Updated on the Steam backend, and the in-game text will change in the next client update.
