### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by symvizan** [SmartlyDressedGames/Unturned-3.x-Community#304]
Hi there Nelson!
I am just curious, how do people get access to the 3.x source code? Is it just for reputable modders and such, or is there a way to apply?
Thank you.

**Comment by Trojaner25** [comment]
Plugin developers usually decompile the Assembly-CSharp.dll to get the source code.
You can use .NET Reflector, IL Spy or dnspy to do that.

As far as I know only Nelson and Sven have access to Unturneds source code.

**Comment by SDGNelson** [comment]
Unfortunately the source code is not easily distributable for a variety of reasons e.g. licensing issues, size of assets - the link in the description is to reduce confusion between the two main repositories. Trojaner's right that the best option to peek at the code is to decompile Assembly-CSharp.dll.
