### ISSUE TITLE
Add resolution parameters for SDG.Unturned.Player.takeScreenshot()

### ISSUE THREAD

**Issue by Rlvx** [SmartlyDressedGames/Unturned-3.x-Community#3042]
Hello,

I'm currently trying to make an Unturned plugin which triggers a screenshot using a camera and i encountered an issue. The resolution of the texture2d created by the function **_Player.takeScreenshot()_** is **640** by **480** and it is not enough for what i want. I think it's possible to make **width** and **height** become defaultable parameters of the function (default = 640 / 480).

Thanks in advance

**Comment by SDGNelson** [comment]
Sorry, the screen capture is too performance intensive for unintended uses. Might someday be improved with a separate network channel for file transfers.

**Comment by GazziFX** [comment]
@SDGNelson you should use Graphics.Blit for image downscale, it is GPU accelerated and does a better result than current solution. I can provide code later
