### ISSUE TITLE
I can't see servers.

### ISSUE THREAD

**Issue by Ratmansupreme66** [SmartlyDressedGames/Unturned-3.x-Community#3043]
I am from the US and I like to play on an Australian unturned server. Until recently I've been able to play on it just fine but as of late I cannot see it in server browser, cannot connect to it via direct connect, or anything of the sort. I've made sure the filters are right when searching (direct connect didn't work either so I know that's not the issue) I've tried a VPN, tried it on my laptop on work wifi to see if it was an issue with my internet at home. I've tried another steam account among other things as well including reinstalling and verifying cache. I am unsure what else to do as are the server staff. In a final attempt of desperation I reach out to you unturned devs to help me return back to my mansion in game.

**Comment by SDGNelson** [comment]
That is odd. The fact directly connecting is not working either suggests something is blocking your traffic to the server. You are sure the server is online with the same IP and port as before? For example, checking on a site like battlemetrics? Do you have any anti-virus or firewall software installed? For example, perhaps Windows Firewall is blocking the traffic? Are you able to see other servers?

**Comment by Ratmansupreme66** [comment]
I am certain it's the same ip and port. I haven't tried battle metrics and I do have anti-virus and firewall at home, but I tried it at work too and I know for a fact they don't. I can see other servers, it just appears to be I cannot see theirs.

**Comment by SDGNelson** [comment]
If you can post the IP and port or the server name we might be able to check on some sites like battlemetrics. When you tried at work were you still using the same computer as at home?
