### ISSUE TITLE
Devkit viewport being foggy and gray, no clue how to fix this

### ISSUE THREAD

**Issue by tseardv** [SmartlyDressedGames/Unturned-3.x-Community#3044]
I have to work with devkit, I have done this before, but once I've started again I found that my viewport was deeply gray-tinted as shown below. This makes editing practically impossible and I am now waiting for a solution. Is there any way to fix this? So far I've tried verifying my game files, repeatedly re-entering the map and closing the viewport and creating a new one. I don't know what to do anymore please help me finish my map!

![afbeelding](https://user-images.githubusercontent.com/99840046/154351936-b05791e7-ce00-464b-87f2-a3117d1718eb.png)
![afbeelding](https://user-images.githubusercontent.com/99840046/154351974-f36909f0-b7cf-4b2d-975f-7d45b1bf52be.png)

**Comment by GazziFX** [comment]
Try to change anti-aliasing setting

**Comment by tseardv** [comment]
Oh my god you are a life saver, my problem is resolved!

**Comment by SDGNelson** [comment]
Glad to hear you got it working! Sorry that the devkit stuff kind of sucks, plan is to remove and reintegrate into original editor.
