### ISSUE TITLE
Bug: Unable to submit workshop item with a new thumbnail

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3045]
I am not entirely sure whether this is a problem on my end or the game's. I have tried updating a mod's thumbnail multiple times using both png & jpg formats, as well as using file sizes up down to 13.8 KB. To no prevail though, I still get the same error.

Any idea on what causes this issue?

**Comment by SDGNelson** [comment]
Sorry for the trouble! "I still get the same error" which error are you getting?

**Comment by SDGNelson** [comment]
Could you attach "C:\Program Files (x86)\Steam\logs\workshop_log.txt" please?

**Comment by OneManOperative** [comment]
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8109155/workshop_log.txt)

Sorry for the late reply, but here's the logs that I assume is what you're looking for.

**Comment by SDGNelson** [comment]
Thanks! Is your workshop file 1959614756? It looks like the error is:
"No content change detected for item 1959614756"
Perhaps the preview file cannot be updated without an update to the mod itself?

**Comment by Jdance-Media** [comment]
> Thanks! Is your workshop file 1959614756? It looks like the error is: "No content change detected for item 1959614756" Perhaps the preview file cannot be updated without an update to the mod itself?

Ran into this issue a couple times, would be a decent feature to make it so you can update the preview icon without needing to provide a filepath.
