### ISSUE TITLE
[Bug] Animal can't decide if it should Run or Walk

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3048]
If you set an Animal's `Speed_Run` to `8` and it's `Speed_Walk` to `4` it will vibrate between it's `Run` and `Walk` animations. This is only an issue in **Multiplayer** and does not appear in Singleplayer. I find this rather puzzling, if you increase the `Speed_Run` to `9` it will play the `Run` animation for slightly longer. I originally thought this was due to 8 being twice as large as 4 but that was disproven when I tried a `Speed_Run` of `10` and a `Speed_Walk` of `5` which didnt cause this issue.

By Vibrate I mean this:
![Dewback1](https://user-images.githubusercontent.com/70017362/154865869-7e53f2ca-4563-4d17-842c-4ce557fdc70b.gif)

**Comment by SDGNelson** [comment]
Unfortunately this is because the client plays the animation depending on the position difference between network updates. Animals in Unturned being janky is a common complaint and I do want to rewrite a bunch of that stuff sooner or later.

Epic tree in the background by the way! Is this a fantasy world you are creating?

**Comment by Gamingtoday093** [comment]
> Epic tree in the background by the way! Is this a fantasy world you are creating?

Oh this is just my test map, but yes I and a few other people are creating a Star Wars server! What you're looking at is a Wroshyr tree from the Wookie planet of Kashyyyk. Thanks for the compliment :)

**Comment by SDGNelson** [comment]
Wow that sounds amazing! I look forward to seeing / playing the release version. :)
