### ISSUE TITLE
The games closes it self at start up

### ISSUE THREAD

**Issue by rDnavx** [SmartlyDressedGames/Unturned-3.x-Community#3051]
When i open unturned, it starts mounting core in the download menu, after unity pops up then the game crashes
![image](https://user-images.githubusercontent.com/100154706/155433302-3151fd3c-4fcd-434a-aa06-d6a1a2983ebf.png)
Please help me... i tried to reinstall it and still the same..

**Comment by GazziFX** [comment]
Send file `Player.log` from (copy and paste that path in explorer) `%USERPROFILE%\AppData\LocalLow\Smartly Dressed Games\Unturned\`

**Comment by SDGNelson** [comment]
Could you send these Unity crash files to my email nelson@smartlydressedgames.com please?
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the "Unity Temp" folder
4. Zip and attach the Crashes folder to your email
