### ISSUE TITLE
[BUG] Player in group signifier on M missing after latest update

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3052]
Update that came out ~30 minutes ago made the white line that would signify people sharing the same group has disappeared.]
![image](https://user-images.githubusercontent.com/66274985/155773880-5e0dfc5b-40bd-4201-ac1c-57c46733e1f8.png)
(In the above image blue and red are two groups of people, no white lines linking them together)

**Comment by GazziFX** [comment]
From update:
Sort in-game player list by name rather than by group ID.

**Comment by SDGNelson** [comment]
Unfortunately I decided to remove that feature in favor of simplifying the player list (easier to virtualize) and sorting by name instead. Maybe a separate tab listing the groups on the server and their members should be added?

**Comment by DMJaxun** [comment]
> From update: Sort in-game player list by name rather than by group ID.

Ah mb, skimmed over that one, still a shame that the old functionality isn't available
