### ISSUE TITLE
Inappropriate topics in the game

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#3054]
First of all, I express my sympathy to the Ukrainian people, but the current situation in Ukraine is caused by himself, no one should be held responsible for him, from the moment Ukraine tried to join NATO, war will inevitably happen, no one is innocent of!
I regret the mentally retarded behavior of the Ukrainian government!

**Comment by CyberAndrii** [comment]
So you're crying now?

**Comment by CatzMR** [comment]
> 

All I can say is that I sympathize with your people's suffering.
What the Ukrainian government is doing now is caused by himself.
If that choice is made, then this war is unavoidable.

**Comment by kulkaGM** [comment]
And that's why you are posting it here in Unturned issues?

**Comment by CatzMR** [comment]
> 

The problem in the update bulletin, isn't it a problem?

**Comment by CatzMR** [comment]
> And that's why you are posting it here in Unturned issues?

https://github.com/kulkaGM

**Comment by kulkaGM** [comment]
I think games shouldn't react to stuff like this, but Nelson decided this way, so if you will make Issue about it here, that doesn't change his mind.

**Comment by CatzMR** [comment]
> I think games shouldn't react to stuff like this, but Nelson decided this way, so if you will make Issue about it here, that doesn't change his mind.

Games should not involve politics

**Comment by CatzMR** [comment]
> So you're crying now?

All I can say is that I sympathize with your people's suffering.
What the Ukrainian government is doing now is caused by himself.
If that choice is made, then this war is unavoidable.

**Comment by educatalan02** [comment]
> > I think games shouldn't react to stuff like this, but Nelson decided this way, so if you will make Issue about it here, that doesn't change his mind.
> 
> Games should not involve politics

It would involve politics if the creator wants to. There is no choice you can do.

**Comment by educatalan02** [comment]
> > > > I think games shouldn't react to stuff like this, but Nelson decided this way, so if you will make Issue about it here, that doesn't change his mind.
> > > 
> > > 
> > > Games should not involve politics
> > 
> > 
> > It would involve politics if the creator wants to. There is no choice you can do.
> 
> But I really think it would be bad to have politics in a game Everyone's political stance may be different, but you can still sit down and play the game together, but if the game involves political stance issues, I don't think it will end well There are still problems of ideological opposition in the world. In short, the game really can't have political topics.

That's something that cannot be discussed by me or you. If Nelson pushed the update is because he selected the best posibility.

**Comment by SDGNelson** [comment]
Regardless of any of our views on the politics and governments, I hope we can all agree that the innocent people affected deserve our support and sympathy.
