### ISSUE TITLE
New update seems to have a issue.

### ISSUE THREAD

**Issue by Glass47** [SmartlyDressedGames/Unturned-3.x-Community#3055]
Hello, i saw few people on Unturned reddit talking about it, looks like that new update broke Geforce now compatibility, if you try to play the game as soon as it launches the Geforce Now will kick you out of session. Also some of my friends which have bad computers can't play Unturned now, i hope that this can be solved, i don't know what is causing it. Probably something that triggers when you launch the game (at the start of entering into loading screen after launching) whatever is changed after update is causing it i would guess.

**Comment by SDGNelson** [comment]
Nothing on the game side would have affected this after Friday's update (for example, the engine upgrade was the update before this one), so I would recommend contacting GeForce Now support asking them to look into this.

**Comment by SDGNelson** [comment]
P.S. sorry for the trouble! :(
