### ISSUE TITLE
Cant PlayProject

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3056]
I cant make plugin that allow any weapon shoots projectile by instant item switching because of `ReceivePlayProject` check `player.equipment.isEquipped` and it will return false even with zero animation because `isEquipped` checks with `Time.realtimeSinceStartup - this.lastEquipped > this.equippedTime` but should be `>=`
or maybe just remove this check from `ReceivePlayProject`

**Comment by SDGNelson** [comment]
Hmm this seems awfully hacky, not supported sorry. Sooner or later I intend to separate projectiles out from guns/throwables to make them deterministic, and so that might be a good option once available.
