### ISSUE TITLE
PlayerEquipment.hotkeys access for plugins.

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3057]
If we could have access PlayerEquipment.hotkeys from plugins, it would be great.

**Comment by SDGNelson** [comment]
What do you have in mind? They are client side right now.

**Comment by fahrettinenes** [comment]
I want to make plugin like rust's hotbars. But I don't have access, because they are client-side :(

**Comment by xMagicc** [comment]
Basically what he wants to do is make a rust-like Hotbar so he can have all the items he puts on hotkeys into that Hotbar to be seen!

**Comment by Paradox304** [comment]
I would really like this to be added, and also ability to set those hotkeys to items in the inventory would be awesome!

**Comment by educatalan02** [comment]
It would be good to force the player to equip the hotkey item

**Comment by surv0013** [comment]
We need plugin flag to hide default hotkey bar.

**Comment by fahrettinenes** [comment]
@SDGNelson ??

**Comment by xMagicc** [comment]
@fahrettinenes 
![image](https://user-images.githubusercontent.com/48396003/156439182-7b9a9d5b-fd7d-41fd-b9d3-d5d4591398e8.png)
this image shows that its possible to remove the default vanilla UI (probably trough the map config files like its done for guns)

**Comment by GazziFX** [comment]
> @fahrettinenes ![image](https://user-images.githubusercontent.com/48396003/156439182-7b9a9d5b-fd7d-41fd-b9d3-d5d4591398e8.png) this image shows that its possible to remove the default vanilla UI (probably trough the map config files like its done for guns)

Looks like my UI but on my server vanilla hotbar isnt hidden

**Comment by xMagicc** [comment]
> > @fahrettinenes ![image](https://user-images.githubusercontent.com/48396003/156439182-7b9a9d5b-fd7d-41fd-b9d3-d5d4591398e8.png) this image shows that its possible to remove the default vanilla UI (probably trough the map config files like its done for guns)
> 
> Looks like my UI but on my server vanilla hotbar isnt hidden

which server do you own again?

**Comment by fahrettinenes** [comment]
Probably he forgot that and this issue will be open for a year.

**Comment by Paradox304** [comment]
@SDGNelson it would be great if you could give some input. Seems like a lot of devs want this

**Comment by xMagicc** [comment]
> > which server do you own again?
> 
> Again? What? Fox Studio Servers

Are you able to give me your discord by any chance?
