### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Finn39** [SmartlyDressedGames/Unturned-3.x-Community#3059]
Luger have 25 RPS. That makes it machine-gun in turret. 

Video:
https://drive.google.com/file/d/14McGPXXpMdaYNThcozW2ubw4__QbdbqN/view?usp=drivesdk

**Comment by SDGNelson** [comment]
Technically the sentry guns do have a fastest possible firerate, but I think the luger is fine here because the magazine size is small.
