### ISSUE TITLE
Bug report N2

### ISSUE THREAD

**Issue by Finn39** [SmartlyDressedGames/Unturned-3.x-Community#3060]
Just check that short video about farming in unturned.

https://drive.google.com/file/d/1-UOa5_mX8KuiXDFA8Nv68RFUuYAYATVV/view?usp=drivesdk

**Comment by SDGNelson** [comment]
Was this recorded in an older version? I think stacking plants was fixed in the most recent update. It might still work on ghillie netting though.

**Comment by MoltonMontro** [comment]
> It might still work on ghillie netting though.

I've verified that this still works on ghillie netting. **(Version 3.22.4.0)**

![image](https://user-images.githubusercontent.com/7608445/156483829-c52d1dae-651c-408f-a12d-ce8032302758.png)

**Comment by SDGNelson** [comment]
Thanks Molt! I suppose that should be changed. For anyone curious: prior to the data-driven physics material rewrite the planting restrictions were determined by the material name, so now there have been some items/objects with unexpected material configuration.

**Comment by Jdance-Media** [comment]
Dang, always figured plant on the net was a feature. Helped a lot when I farmed a lot in the game.

**Comment by MoltonMontro** [comment]
> Helped a lot when I farmed a lot in the game. Will the ability to plant more vertically be added? Nowadays on servers there is a base limit, so the number of crops you can have has been really limited by this.

For an alternative that is already available with the vanilla game content, you can stack two plots upon each other. For example, stacking them like this would allow for growing large crops on both the upper and and lower plots. This orientation also lets you replace the roof at any time, as the plots are low enough for it to not be considered "blocked".

![image](https://user-images.githubusercontent.com/7608445/156857107-3bd49906-de0e-4ea1-a6e2-07d86d5ecdd0.png)
