### ISSUE TITLE
Mythical

### ISSUE THREAD

**Issue by YAMUMSHORT** [SmartlyDressedGames/Unturned-3.x-Community#3069]
Hey Nelson I’m sure you’ve figured this out but I think the scrap feature is a bit dumb, and let me tenyou why. I have calculated the cost of scrapping epics for 5 cents (cheapest option) and scraping them for 4 scrap, and this equals out to 12.5 which for a average mythical I think is a bit silly, I know u probable can’t do anything like making a item cheaper than 0.03 cents but maybe u could add something like a bulk buy, where you can buy a couple of commons from a person like (10) for 8 cents or something. I know that’s probable too hard but maybe just make every item scrap for a little bit more or make the mythical thing 500 or 750 because most of the time it’s a bad item that’ll never be used

**Comment by SDGNelson** [comment]
Sorry, part of the goal with salvaging is to help get rid of the huge quantity of three cent items.
