### ISSUE TITLE
Animal Class has it's current Health Private

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3070]
Taken from the Animal.cs file:
```cs
private ushort health;
```
As you can see the health of the Animal is private making it impossible to *easily* access. You can obviously still get it through reflection but it's way slower than being able to access it directly.

I don't know if there is a proper reason for it being private such as a quirk with Animals but I'd be great to hear more about this from Nelson.

**Comment by Gamingtoday093** [comment]
Another Variable that should be available is the animals current targeted Player?
```cs
private Player player;
```

**Comment by SDGNelson** [comment]
Sorry, I have been overly cautious about which newer code is in the public API. This seems quite reasonable though - will do.

**Comment by SDGNelson** [comment]
Changed for the next update
