### ISSUE TITLE
Quick request re Asset.FriendlyName

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3071]
Would you mind making `Asset.FriendlyName` public when you have a chance?

**Comment by SDGNelson** [comment]
Sorry, I have been overly cautious about which never code is in the public API. This seems quite reasonable though - will do.

**Comment by DanielWillett** [comment]
Thanks

**Comment by SDGNelson** [comment]
Changed for the next update
