### ISSUE TITLE
Vehicle damage

### ISSUE THREAD

**Issue by Yzuuu123** [SmartlyDressedGames/Unturned-3.x-Community#3073]
I don't know why, but if I leave the plugin for more hours, it takes damage to the vehicle and the vehicle explodes.
Help me.

**Comment by GazziFX** [comment]
Please provide more details and plugin source

**Comment by SDGNelson** [comment]
Perhaps it is the built-in vehicle decay? The default value for `Decay_Time` is 7 days (604800) and `Decay_Damage_Per_Second` is 0.1.
