### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#3076]
Seems like recent update dropped FPS from stable 144 to 100~. Some other players started reporting game crashes and decreased FPS too. My guess its somehow related to fog as map seems really foggy right now (not sure if it was an intentional change)

**Comment by SDGNelson** [comment]
Odd, if anything performance should have improved. When testing both Molt and myself got a performance boost. If your players are reporting crashes could you ask them to email me nelson@smartlydressedgames.com please?

**Comment by baranmod** [comment]
I believe it was something with nvidia drivers. Downgraded it and FPS seem to be more or less stable now. Crashing issues were fixed by validating files for players
