### ISSUE TITLE
Rendering Issues; New update with mist.

### ISSUE THREAD

**Issue by Magiclime** [SmartlyDressedGames/Unturned-3.x-Community#3077]
The new update has a couple of rendering issues I noticed while playing on a server;
Mist seems to still render when not supposed to as show in these pictures.
https://cdn.axodouble.tech/v3/img/SHazOUkbOi.png
https://cdn.axodouble.tech/v3/img/nYsNxLDnbZ.png
https://cdn.axodouble.tech/v3/img/N3v2Zr2hHu.png

Mist renders in through one way glass, the same goes for the "High Tide" mythical which renders in oddly thru one way glass.
Just a couple small bugs I saw recently, that's pretty much all.

**Comment by SDGNelson** [comment]
Sorry about these. Deferred fog with transparent objects is tricky, but for the next update I will add a minimum transition fog distance which will help mitigate the windows, and I have been meaning to remove speedtrees at some point as well. (also upgrade the old tree models)
