### ISSUE TITLE
Incorrect format/label assigned to "Flower #1" toggle

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3082]
**Issue:** In the legacy editor, two of the toggles are labeled the same—both as "Flower #&#x2060;1". One of them is intended to have been labeled as "Flower #&#x2060;2" instead.

**Solution:** The EditorTerrainDetailsUI code mistakenly assigns the "Flower_0_ToggleLabelText" localization key to the Flower_1 toggle.  It should be assigning the "Flower_1_ToggleLabelText" localization key instead.

**Comment by SDGNelson** [comment]
Thanks, will fix!

**Comment by SDGNelson** [comment]
Fixed for the next update!
