### ISSUE TITLE
Streamer mode hides player lists entirely; doesn't rename players

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3085]
In the past, Streamer Mode would rename players in the player list (both in-game, and from the server list), and in chat. This no longer seems to be true, although I don't recall any changes happening to Streamer Mode specifically.

**Currently:** the player list is hidden entirely, with the "Players" button being renamed to "Streamer Mode". The server list's player list is hidden entirely unless the server listing is refreshed, which will show the names (unchanged). Names in chat will have their avatar hidden, but their name is unchanged.

Other features seem to work fine. E.g., it appears that the streamer's personal name is still changed in menus, and that the server name is hidden (when inside the server).

**Comment by SDGNelson** [comment]
Whoops! When I was refactoring that code I *thought* the player list was hidden in streamer mode, will double-check what happened here.

**Comment by SDGNelson** [comment]
I am a bit hesitant because I think this **was** intentional at some point (it has been like this for a while), but on the other hand the player names and avatars are redacted. For the next update it is re-enabled.
