### ISSUE TITLE
[BUG (?)] onInventoryAdded called once + onInventoryRemoved called twice when deploying barricade

### ISSUE THREAD

**Issue by BarehSolok** [SmartlyDressedGames/Unturned-3.x-Community#3086]
It only bugged when you have more than 1 corresponding item, 
for example if player A has 1 metal sign, and deployed it, only 1 onInventoryRemoved event is called,
but when player A has 2 or more metal sign, and deployed 1 metal sign, onInventoryRemoved called twice and onInventoryAdded called once

I'm not sure if it's bug or intended to work like that, i'm trying to create notification UI when player received/removed an item in their inventory

**Comment by iBowie** [comment]
It moves other item to the slot from which this item was used by removing and adding an item, thus calling onInventoryRemoved twice. I haven't seen code related to this, but this may be the most reasonable explanation to what is going on here.

**Comment by SDGNelson** [comment]
Thanks @iBowie, yes I think this is from the replacement item being moved.
