### ISSUE TITLE
Failed to connect to Steam servers because k_EResultInvalidPassword, no longer retrying

### ISSUE THREAD

**Issue by VeRMuT1** [SmartlyDressedGames/Unturned-3.x-Community#3087]
@SDGNelson Let me ask, on my server in the hosting console, the problem "Failed to connect to Steam servers because k_EResultInvalidPassword, no longer retrying" after this error, the disconnectin of all players, what could it be?
![image](https://user-images.githubusercontent.com/101873658/159000527-5f66c364-8e24-4194-9f8a-bb03eeb34b9e.png)

**Comment by SDGNelson** [comment]
Are you using the dedicated server installed through steamcmd? The "invalid password" could be invalid GSLT https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GameServerLoginTokens.md, but I think there is a separate error message for that so I wonder if you are hosting using the regular client

**Comment by VeRMuT1** [comment]
One-host via browser, this is the name of the hosting

**Comment by SDGNelson** [comment]
They might be hosting using a logged-in Steam user rather than anonymous gameserver login. Sorry to say it sounds like something you will have to sort out with their support. The server should be installed using steamcmd: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md
