### ISSUE TITLE
Unturned Editor Satelite baking not working.

### ISSUE THREAD

**Issue by badboi2004** [SmartlyDressedGames/Unturned-3.x-Community#3089]
https://pastebin.com/u8J5MuVz

**Comment by GazziFX** [comment]
Can you click "Unity AppData" link in Unturned directory and upload Player.log because it has actual offset of IL which caused error

**Comment by badboi2004** [comment]
@GazziFX  here you go,https://pastebin.com/J6MChuZE

**Comment by GazziFX** [comment]
Seems one of object has wrong asset

**Comment by GazziFX** [comment]
Do you have something like "Unable to find object" in Client.log?

**Comment by badboi2004** [comment]
well client log is hella long
and yes there are several instances of that.

**Comment by badboi2004** [comment]
pastebin won't let me send it
It's 902 kb big.

**Comment by badboi2004** [comment]
I have 2 mods for my map,City expansion 2 and prison expansion

**Comment by badboi2004** [comment]
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8309231/Client_Prev.log)

**Comment by GazziFX** [comment]
You should download mods for these objects or launch game with `-NoPreserveMissingObjects` parameter to delete missing objects

**Comment by badboi2004** [comment]
alright I'll try that one now

**Comment by badboi2004** [comment]
Alright I fixed it

**Comment by SDGNelson** [comment]
Sorry about this, thanks @GazziFX, I will add a check that the asset is not null for the next update.
