### ISSUE TITLE
Render Mode Bug

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3093]
Whenever baking 'Satelite' in the map editor your render mode switches from Deferred to Legacy. Not sure if this happens to anyone else but this is new since the new clouds and fog update.

**Comment by SDGNelson** [comment]
It has always temporarily switched from Deferred render mode to Forward, so my guess is that it is the same error as: #3089
Sorry for the hassle. For the meantime you can use the workaround from the other issue if you want, or I will fix for the next update.
