### ISSUE TITLE
Crashing when trying to open Russia

### ISSUE THREAD

**Issue by italoseara** [SmartlyDressedGames/Unturned-3.x-Community#3094]
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8311945/Player.log)

**Comment by SDGNelson** [comment]
It looks like there are a bunch of D3D12-related errors. Unturned does not enable D3D12 support yet, so do you have some command-line arguments trying to force-enable it?

**Comment by italoseara** [comment]
yes, i actually did because i was trying to solve this problem before, but it crashes anyways even without this

here is the crash log (without -force-d3d12): [Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8317028/Player.log)

**Comment by SDGNelson** [comment]
It looks like D3D11 is returning error code 887a0005 which means device removed / driver crashed. It might be worth checking for driver updates, but for a quick workaround using OpenGL instead might work:
1. Right-click Unturned in your Steam Library
2. Select Properties... > General
3. Find the Launch Options field
4. Type "-force-glcore" without quotes
