### ISSUE TITLE
NPC Bug Report : Vendor overrides response rewards

### ISSUE THREAD

**Issue by Tiway-Paper-Guy** [SmartlyDressedGames/Unturned-3.x-Community#3097]
Hi!
I recently realized one response could not have both rewards and a vendor, the vendor will trigger, but not the rewards.

Example :

```
Response_0_Dialogue 2
Response_0_Vendor 3
Response_0_Rewards 1
Response_0_Reward_0_Type Item 
Response_0_Reward_0_ID 14
Response_0_Reward_0_Amount 1
```
This would open Vendor 3, but won't give any bottled water.
Removing the vendor line will trigger the reward.

**Comment by SDGNelson** [comment]
It looks like the response is only registered with the server if it is a non-quest non-vendor option. Will see about registering always for the next update.

**Comment by Tiway-Paper-Guy** [comment]
Coo! Thanks!

**Comment by SDGNelson** [comment]
Sorry - I completely forgot about this for the update! Added to my to-do list now.

**Comment by SDGNelson** [comment]
Fixed for the next update!
