### ISSUE TITLE
Vehicle bug

### ISSUE THREAD

**Issue by fishingsman** [SmartlyDressedGames/Unturned-3.x-Community#3098]
I found new bug while was playing on Arid.
Appreantly, there is chance of getting such glitch, when you sit on a vehicle you go into third person, sit at the place you were before getting into vehicle (You just dont teleport to vehicle's seat), sometimes it can be fixed by sitting at other seat, but it happens not so usually.
This also maybe caused by a bug I spotted before this one where when you die, you respawn, but the death screen is still on, and to get rid off it you have to get to menu and back to the game.
However, I think this bug is only client sided, no claims from other players with which I was playing weren't told.
![image](https://user-images.githubusercontent.com/102311071/160144164-aa359814-4a87-48a5-a210-7f34bd56260e.png)
![image](https://user-images.githubusercontent.com/102311071/160144267-37c83f23-998f-40f6-98c3-f1f750e02faf.png)
![image](https://user-images.githubusercontent.com/102311071/160144346-cbc88a6a-f6e6-404f-89c9-3f216017b9f3.png)

(I think this bug can be abused in a form of looking out for any "tail" and see if somebody is following you, not sure if zombies can attack you when you experience such bug.)

**Comment by SDGNelson** [comment]
I have seen a few reports of this, but unable to track down or reproduce yet. One guess is that it might be related to a plugin doing something when entering a vehicle. 😕
