### ISSUE TITLE
The carjack abuse

### ISSUE THREAD

**Issue by fishingsman** [SmartlyDressedGames/Unturned-3.x-Community#3099]
Apparently, if you are in sz, or not even in sz, maybe anywhere else, have your car somewhere near a tree, and use carjack, your car will fly and damage the tree, making trees fall. This can be abused in Arid since there is trees in sz, but I think this can be abused also outside of sz but your car will get damaged.

**Comment by SDGNelson** [comment]
Sorry not sure I understand: what is the abuse? Note unless you are an admin you can only carjack your own vehicle in the safezone.

**Comment by fishingsman** [comment]
I mean by abuse that carjack can be used by the owner of vehicle, yes, but when used near a tree, it breaks down it, meaning without getting out of safe zone you can get wood materials.

**Comment by SDGNelson** [comment]
I suppose it is not exactly intentional, but sorry unless the general community consensus / feedback is that something should change here I think it is fine as-is.
