### ISSUE TITLE
[Feature Request] Primitive Objects for Editor

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3102]
Would it be possible to get a few basic primitive objects added into the Editor for map making purposes? 
Even just a single cube (maybe in a handful of colors) would open up infinite possibilities for customizing buildings, without having to resort to mods. 

It's already doable, but we have to resort to using random objects that can be difficult to use, and that have unnecessary polygons.
For example this "red carpet" is a stretched upside-down couch, and the black mat is a large flattened table. 
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/71527679/160451278-96fd33a1-16db-4519-bb90-e156b2b38926.png">

**Comment by SDGNelson** [comment]
I think there are some workshop mods which add primitive shapes in different colors, but eventually I would like to add a tool for blocking out primitives rather than using higher-overhead objects: https://trello.com/c/06Lk0IR3/11-level-blockout-tool
