### ISSUE TITLE
Question about weapon shoot sound range

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#3106]
I am curious what weapon shoot sound range depends on? I need to make a weapon which shoot sound would be audible in a small range (5-10 meters). Is it possible to do it? Tried to lower sound of the audio file, tried to make a a barrel with 0.25 sound value. Its still audible in 150-200 meters range.

**Comment by SDGNelson** [comment]
Sorry, right now this is hardcoded - IIRC because it overrides the falloff curve on the player's shared audio source. It would make sense to separate into its own audio source.

**Comment by GazziFX** [comment]
Did you tried `Gunshot_Rolloff_Distance` in dat?
