### ISSUE TITLE
[Feature Request] unturnedPlayer.Player.inventory.onDragItemRequested

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3107]
Why is onDropItem there, but onDragItem is not

**Comment by GazziFX** [comment]
When item is dragging it actually removes and adds again

**Comment by FANYPLAYRU** [comment]
Already figured it out. I needed this method to track dragging an item from the storage to the inventory.

**Comment by GazziFX** [comment]
https://harmony.pardeike.net/#getting-started

**Comment by FANYPLAYRU** [comment]
Another lib - cringe

**Comment by GazziFX** [comment]
It can be made without libs but require manual creating x86 jmp opcode in existing method
