### ISSUE TITLE
white water

### ISSUE THREAD

**Issue by fishingsman** [SmartlyDressedGames/Unturned-3.x-Community#3109]
water became racist with new update
![image](https://user-images.githubusercontent.com/102311071/161338139-0d765886-1c67-4139-ab8e-6e8f8a3529ad.png)
![image](https://user-images.githubusercontent.com/102311071/161338170-8457487d-2551-47d3-b790-5e215ea0cb0c.png)

**Comment by SDGNelson** [comment]
Hmmm fair point that the water looks really bad if there is a lot of contrast between water and sky color. Thanks for the report, I will get this fixed up for the next patch or update!

**Comment by SDGNelson** [comment]
Sorry, re-opening until I fix this

**Comment by SDGNelson** [comment]
This should now be fixed in the next update!

**Comment by GazziFX** [comment]
Water still looks kinda sick
![image](https://user-images.githubusercontent.com/43498426/188322609-e5082809-182b-4c0a-9d91-89289e7b7720.png)
