### ISSUE TITLE
Map editor issue & Feature request

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#3112]
I found some strange white objects placed under my map after some of my assets broke, however i can't remove since they are unselectable.
Maybe adding a hierarchy with possibility to select/deselect/remove objects would very useful in similar cases.
(to the default map editor)

![image](https://user-images.githubusercontent.com/54103088/161594003-2fbd7f48-ff14-402a-803f-d99ef9347fa1.png)

**Comment by SDGNelson** [comment]
There should not be a white placeholder for missing assets, so if this is an older map maybe it is the skybox terrain? Otherwise if you would like to send the map to nelson@smartlydressedgames.com I will take a look.

**Comment by Dudewithoutname** [comment]
Thanks for the explanation & time, 
but i don't think it is skybox terrain since it ends in the middle of the map
i've send you the mail with that map 
[image](https://user-images.githubusercontent.com/54103088/161615019-53cf7160-49c4-4164-a894-778e6133a923.png)

btw yes, map is old

**Comment by SDGNelson** [comment]
In the map you sent it looks like there is a terrain tile placed underneath the other terrains. If you open the map in the devkit you can remove the tile using the landscape tool, or you can remove this block from your map's Level.hierarchy file:
```
    {
		"Type" "SDG.Framework.Landscapes.Landscape, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
		"Instance_ID" "36"
		"Item"
		{
			"Tiles"
			[
				{
					"Coord"
					{
						"X" "0"
						"Y" "0"
					}
					"Materials"
					[
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
						{
							"GUID" "00000000000000000000000000000000"
						}
					]
				}
			]
		}
	}
```

**Comment by Dudewithoutname** [comment]
❤️ thanks for a new knowledge :)
