### ISSUE TITLE
Modified or corrupted asset issue

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3115]
![image](https://user-images.githubusercontent.com/48363842/162440487-f317c5a1-b267-402c-8f30-253ecba6e5a5.png)

I don't quite understand what causes this, it works fine for me but it's persistent for other people. Does anyone have any idea what does this?

**Comment by fishingsman** [comment]
Did you try to re-subscribe/re-install all the mods?

**Comment by SDGNelson** [comment]
This means the file on the client does not match the file on the server. Did you manually copy that file over to the server? If so, perhaps the copy uploaded to the workshop is out-of-date?

**Comment by OneManOperative** [comment]
The mod was updated, but it took awhile before the server updated it's files of it. I'll probably try to have the mod updated to fix this issue.
