### ISSUE TITLE
Extremely low performance on high end PC.

### ISSUE THREAD

**Issue by Magiclime** [SmartlyDressedGames/Unturned-3.x-Community#3116]
Here is currently what I am experiencing;
I have a solid 17FPS in most maps which is pure pain to play at, now it is odd that I have a relatively high performance build such as the following listed here;

Ryzen 9 5950X 16 Cores at 4.3GHz.
RTX 3060 TI
32GB's of RAM and a bit more not so interesting things.

I for the love of god cannot figure out why this is happening, have tried a couple things, launch options, just tweaking priorities, checking background processes, usage, but all of that is low whereas unturned is still getting issues playing at a reasonable FPS.

Sincerely sorry if this is a duplicate, but I am simply confused.

**Comment by Magiclime** [comment]
This all comes from apparently only in multiplayer.

**Comment by GazziFX** [comment]
Can you attach logs?

**Comment by Gamingtoday093** [comment]
Vehicles are a big FPS stealer. Try to minimize their amount and see if that helps?

**Comment by SDGNelson** [comment]
That does sound like a very powerful PC. I am no specs expert, but my PC gets ~150 FPS and is far worse than yours. You mention that it seems to be related to multiplayer - if you load up one of the vanilla maps like Russia in singleplayer do you get high FPS? Also, is your monitor perhaps plugged into your motherboard rather than GPU? Do you have the latest GPU drivers installed?

**Comment by Magiclime** [comment]
> That does sound like a very powerful PC. I am no specs expert, but my PC gets ~150 FPS and is far worse than yours. You mention that it seems to be related to multiplayer - if you load up one of the vanilla maps like Russia in singleplayer do you get high FPS? Also, is your monitor perhaps plugged into your motherboard rather than GPU? Do you have the latest GPU drivers installed?

I get 60fps max due to vsync on Russia in singleplayer, also have got all drivers plugs and other things checked, correct cables and everything, I only get this much of a performance impact on Unturned, I can run practically all other AAA games at max frames and max graphic basically.

**Comment by SDGNelson** [comment]
So you get stable 60 fps in Russia singleplayer, but drastically drops in multiplayer? To compare apples with apples - do you get significantly lower performance on Russia in multiplayer? Multiplier does tend to be a bit more performance intensive, for example due to large bases, but it should not be a *huge* difference. If Russia is significantly different in multiplayer I am trying to think if there is any non-game-related reason multiplayer would be different from singleplayer.

**Comment by Magiclime** [comment]
> So you get stable 60 fps in Russia singleplayer, but drastically drops in multiplayer? To compare apples with apples - do you get significantly lower performance on Russia in multiplayer? Multiplier does tend to be a bit more performance intensive, for example due to large bases, but it should not be a _huge_ difference. If Russia is significantly different in multiplayer I am trying to think if there is any non-game-related reason multiplayer would be different from singleplayer.

Have checked the same with Hawaii, Hawaii giving insane performance impacts, going from 239fps down to 13 average on multiplayer, it is genuinely god awful and I am confused as to why or how this is even happening, it seems pretty illogical, even with large bases existing it shouldn't have this much of a impact.

**Comment by SDGNelson** [comment]
Yeah 239 to 13 is insane and should definitely not be happening. One guess that comes to mind is maybe there is an error getting spammed to the log files - could you attach these files after it happens again please (after running in multiplayer)?
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file to your post
5. Return to the Unturned folder
6. Open the Unity AppData folder
7. Attach the Player.log file to your post

**Comment by Magiclime** [comment]
> 

Welp, went on a wee bit of a tyrade of experimentation, and turns out Vehicles are the main cause, especially modified vehicles or vehicles with animations or moving parts or just in general multiple models, for some reason those are a ton more taxing, after checking server info we found over 300! Needless to say we will be clearing a ton and I'll update the results here, just looks like they aren't too optimized.

**Comment by SDGNelson** [comment]
Glad to hear you found the problem!
