### ISSUE TITLE
[Bug] BarricadeManager.onDamageBarricadeRequested event doesn't contain instigator when damage is self damage to Trap

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3117]
As Taken from `InteractableTrap.cs`
```cs
BarricadeManager.damage(base.transform.parent, 5f, 1f, false, default(CSteamID), EDamageOrigin.Trap_Wear_And_Tear);
// It uses default CSteamID although it was a player who instigated the damage (Per say)
```
Considering that the Player did indeed Instigate the damage by walking into the trap it should use the player's steamID. This is Essential if you only want certain players to be able to damage barricades for example.

**Comment by SDGNelson** [comment]
Fair point, will change.
