### ISSUE TITLE
[Updated With Reproduction Steps] Unturned Client - Linux (Debian/Ubuntu Flavors) - Trouble With Servers With Modified Config.json

### ISSUE THREAD

**Issue by Defying00** [SmartlyDressedGames/Unturned-3.x-Community#3119]
When attempting to connect to any server with a drastically modified server.json file (it seems if more then like 15 things have been changed) the linux unturned client does not allow joining the server it claims that the server is using a mismatch version.

This is verified through my gaming community. Windows users are connecting to our server with no issues. Linux users are not able to connect to ANY  server with modified server.json.

**Comment by SDGNelson** [comment]
Sorry for the trouble. Is the version mismatch warning shown on the lobby screen, or does it get kicked back to the main menu? Does the lobby screen show the list of modified config and other lobby details?

**Comment by Defying00** [comment]
Hi!

It is on the  lobby screen on, it doe show the configuration changes (ive seen a version of this bug where it doesn't normally beacuse of error in the file),  but the join button is red with version 3.       (some servers show the current version instead of 3. and a few spaces)

**Comment by Defying00** [comment]
`{
  "Browser": {
    "Icon": "",
    "Thumbnail": "",
    "Desc_Hint": "V1 Community Server!",
    "Desc_Full": "V1 Community Server! Very Hard! PVPVE!",
    "Desc_Server_List": "V1 Community Server! Very Hard! PVPVE!",
    "Login_Token": "C88352BDD76D6D0F009D90BA3E96DCD2",
    "Monetization": "Unspecified",
    "Links": null
  },
  "Server": {
    "VAC_Secure": true,
    "BattlEye_Secure": true,
    "Max_Ping_Milliseconds": 750,
    "Timeout_Queue_Seconds": 15.0,
    "Timeout_Game_Seconds": 30.0,
    "Max_Packets_Per_Second": 50.0,
    "Fake_Lag_Threshold_Seconds": 3.0,
    "Fake_Lag_Log_Warnings": false,
    "Fake_Lag_Damage_Penalty_Multiplier": 0.1,
    "Enable_Kick_Input_Spam": false,
    "Enable_Kick_Input_Timeout": false,
    "Validate_EconInfo_Hash": true,
    "Validate_MasterBundle_Hashes": true
  },
  "UnityEvents": {
    "Allow_Server_Messages": false,
    "Allow_Server_Commands": false,
    "Allow_Client_Messages": false,
    "Allow_Client_Commands": false
  },
  "Easy": {
    "Items": {
      "Spawn_Chance": 0.35,
      "Despawn_Dropped_Time": 600.0,
      "Despawn_Natural_Time": 900.0,
      "Respawn_Time": 50.0,
      "Quality_Full_Chance": 0.1,
      "Quality_Multiplier": 1.0,
      "Gun_Bullets_Full_Chance": 0.1,
      "Gun_Bullets_Multiplier": 1.0,
      "Magazine_Bullets_Full_Chance": 0.1,
      "Magazine_Bullets_Multiplier": 1.0,
      "Crate_Bullets_Full_Chance": 0.1,
      "Crate_Bullets_Multiplier": 1.0,
      "Has_Durability": false
    },
    "Vehicles": {
      "Decay_Time": 604800.0,
      "Decay_Damage_Per_Second": 0.1,
      "Has_Battery_Chance": 1.0,
      "Min_Battery_Charge": 0.8,
      "Max_Battery_Charge": 1.0,
      "Has_Tire_Chance": 1.0,
      "Respawn_Time": 300.0,
      "Unlocked_After_Seconds_In_Safezone": 3600.0,
      "Armor_Multiplier": 1.0,
      "Child_Explosion_Armor_Multiplier": 1.0,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64
    },
    "Zombies": {
      "Spawn_Chance": 0.2,
      "Loot_Chance": 0.55,
      "Crawler_Chance": 0.0,
      "Sprinter_Chance": 0.0,
      "Flanker_Chance": 0.0,
      "Burner_Chance": 0.0,
      "Acid_Chance": 0.0,
      "Boss_Electric_Chance": 0.0,
      "Boss_Wind_Chance": 0.0,
      "Boss_Fire_Chance": 0.0,
      "Spirit_Chance": 0.0,
      "DL_Red_Volatile_Chance": 0.0,
      "DL_Blue_Volatile_Chance": 0.0,
      "Boss_Elver_Stomper_Chance": 0.0,
      "Respawn_Day_Time": 360.0,
      "Respawn_Night_Time": 30.0,
      "Respawn_Beacon_Time": 0.0,
      "Quest_Boss_Respawn_Interval": 600.0,
      "Damage_Multiplier": 0.75,
      "Armor_Multiplier": 1.25,
      "Backstab_Multiplier": 1.25,
      "NonHeadshot_Armor_Multiplier": 1.0,
      "Beacon_Experience_Multiplier": 1.0,
      "Full_Moon_Experience_Multiplier": 2.0,
      "Min_Drops": 1,
      "Max_Drops": 1,
      "Min_Mega_Drops": 5,
      "Max_Mega_Drops": 5,
      "Min_Boss_Drops": 8,
      "Max_Boss_Drops": 10,
      "Slow_Movement": true,
      "Can_Stun": true,
      "Only_Critical_Stuns": false,
      "Weapons_Use_Player_Damage": false,
      "Can_Target_Barricades": true,
      "Can_Target_Structures": true,
      "Can_Target_Vehicles": true,
      "Beacon_Max_Rewards": 0,
      "Beacon_Max_Participants": 0,
      "Beacon_Rewards_Multiplier": 1.0
    },
    "Animals": {
      "Respawn_Time": 180.0,
      "Damage_Multiplier": 0.75,
      "Armor_Multiplier": 1.25,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64,
      "Weapons_Use_Player_Damage": false
    },
    "Barricades": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Allow_Item_Placement_On_Vehicle": true,
      "Allow_Trap_Placement_On_Vehicle": true,
      "Max_Item_Distance_From_Hull": 64.0,
      "Max_Trap_Distance_From_Hull": 16.0
    },
    "Structures": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0
    },
    "Players": {
      "Health_Default": 100,
      "Health_Regen_Min_Food": 90,
      "Health_Regen_Min_Water": 90,
      "Health_Regen_Ticks": 60,
      "Food_Default": 100,
      "Food_Use_Ticks": 350,
      "Food_Damage_Ticks": 15,
      "Water_Default": 100,
      "Water_Use_Ticks": 320,
      "Water_Damage_Ticks": 20,
      "Virus_Default": 100,
      "Virus_Infect": 50,
      "Virus_Use_Ticks": 125,
      "Virus_Damage_Ticks": 25,
      "Leg_Regen_Ticks": 750,
      "Bleed_Damage_Ticks": 10,
      "Bleed_Regen_Ticks": 750,
      "Armor_Multiplier": 1.0,
      "Experience_Multiplier": 1.5,
      "Detect_Radius_Multiplier": 0.5,
      "Ray_Aggressor_Distance": 8.0,
      "Lose_Skills_PvP": 0.75,
      "Lose_Skills_PvE": 0.75,
      "Lose_Items_PvP": 1.0,
      "Lose_Items_PvE": 1.0,
      "Lose_Clothes_PvP": true,
      "Lose_Clothes_PvE": true,
      "Lose_Weapons_PvP": true,
      "Lose_Weapons_PvE": true,
      "Can_Hurt_Legs": true,
      "Can_Break_Legs": false,
      "Can_Fix_Legs": true,
      "Can_Start_Bleeding": false,
      "Can_Stop_Bleeding": true,
      "Spawn_With_Max_Skills": false,
      "Spawn_With_Stamina_Skills": false,
      "Allow_Instakill_Headshots": false,
      "Allow_Per_Character_Saves": true
    },
    "Objects": {
      "Binary_State_Reset_Multiplier": 1.0,
      "Fuel_Reset_Multiplier": 1.0,
      "Water_Reset_Multiplier": 1.0,
      "Resource_Reset_Multiplier": 1.0,
      "Resource_Drops_Multiplier": 1.0,
      "Rubble_Reset_Multiplier": 1.0,
      "Allow_Holiday_Drops": true,
      "Items_Obstruct_Tree_Respawns": true
    },
    "Events": {
      "Rain_Frequency_Min": 2.3,
      "Rain_Frequency_Max": 5.6,
      "Rain_Duration_Min": 0.05,
      "Rain_Duration_Max": 0.15,
      "Snow_Frequency_Min": 1.3,
      "Snow_Frequency_Max": 4.6,
      "Snow_Duration_Min": 0.2,
      "Snow_Duration_Max": 0.5,
      "Weather_Frequency_Multiplier": 1.0,
      "Weather_Duration_Multiplier": 1.0,
      "Airdrop_Frequency_Min": 0.8,
      "Airdrop_Frequency_Max": 6.5,
      "Airdrop_Speed": 128.0,
      "Airdrop_Force": 9.5,
      "Arena_Min_Players": 2,
      "Arena_Compactor_Damage": 9,
      "Arena_Compactor_Extra_Damage_Per_Second": 1.0,
      "Arena_Clear_Timer": 5,
      "Arena_Finale_Timer": 10,
      "Arena_Restart_Timer": 15,
      "Arena_Compactor_Delay_Timer": 1,
      "Arena_Compactor_Pause_Timer": 5,
      "Use_Airdrops": true,
      "Arena_Use_Compactor_Pause": true,
      "Arena_Compactor_Speed_Tiny": 0.5,
      "Arena_Compactor_Speed_Small": 1.5,
      "Arena_Compactor_Speed_Medium": 3.0,
      "Arena_Compactor_Speed_Large": 4.5,
      "Arena_Compactor_Speed_Insane": 6.0,
      "Arena_Compactor_Shrink_Factor": 0.5
    },
    "Gameplay": {
      "Repair_Level_Max": 3,
      "Hitmarkers": true,
      "Crosshair": true,
      "Ballistics": false,
      "Chart": true,
      "Satellite": false,
      "Compass": false,
      "Group_Map": true,
      "Group_HUD": true,
      "Group_Player_List": true,
      "Allow_Static_Groups": true,
      "Allow_Dynamic_Groups": true,
      "Allow_Shoulder_Camera": true,
      "Can_Suicide": true,
      "Friendly_Fire": false,
      "Bypass_Buildable_Mobility": false,
      "Allow_Holidays": true,
      "Timer_Exit": 10,
      "Timer_Respawn": 10,
      "Timer_Home": 30,
      "Timer_Leave_Group": 30,
      "Max_Group_Members": 0,
      "Explosion_Launch_Speed_Multiplier": 1.0,
      "AirStrafing_Acceleration_Multiplier": 1.0,
      "AirStrafing_Deceleration_Multiplier": 1.0
    }
  },
  "Normal": {
    "Items": {
      "Spawn_Chance": 0.35,
      "Despawn_Dropped_Time": 600.0,
      "Despawn_Natural_Time": 900.0,
      "Respawn_Time": 100.0,
      "Quality_Full_Chance": 0.1,
      "Quality_Multiplier": 1.0,
      "Gun_Bullets_Full_Chance": 0.05,
      "Gun_Bullets_Multiplier": 0.25,
      "Magazine_Bullets_Full_Chance": 0.05,
      "Magazine_Bullets_Multiplier": 0.5,
      "Crate_Bullets_Full_Chance": 0.05,
      "Crate_Bullets_Multiplier": 1.0,
      "Has_Durability": true
    },
    "Vehicles": {
      "Decay_Time": 604800.0,
      "Decay_Damage_Per_Second": 0.1,
      "Has_Battery_Chance": 0.8,
      "Min_Battery_Charge": 0.5,
      "Max_Battery_Charge": 0.75,
      "Has_Tire_Chance": 0.85,
      "Respawn_Time": 300.0,
      "Unlocked_After_Seconds_In_Safezone": 3600.0,
      "Armor_Multiplier": 1.0,
      "Child_Explosion_Armor_Multiplier": 1.0,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64
    },
    "Zombies": {
      "Spawn_Chance": 0.25,
      "Loot_Chance": 0.5,
      "Crawler_Chance": 0.15,
      "Sprinter_Chance": 0.15,
      "Flanker_Chance": 0.025,
      "Burner_Chance": 0.025,
      "Acid_Chance": 0.025,
      "Boss_Electric_Chance": 0.0,
      "Boss_Wind_Chance": 0.0,
      "Boss_Fire_Chance": 0.0,
      "Spirit_Chance": 0.0,
      "DL_Red_Volatile_Chance": 0.0,
      "DL_Blue_Volatile_Chance": 0.0,
      "Boss_Elver_Stomper_Chance": 0.0,
      "Respawn_Day_Time": 360.0,
      "Respawn_Night_Time": 30.0,
      "Respawn_Beacon_Time": 0.0,
      "Quest_Boss_Respawn_Interval": 600.0,
      "Damage_Multiplier": 1.0,
      "Armor_Multiplier": 1.0,
      "Backstab_Multiplier": 1.25,
      "NonHeadshot_Armor_Multiplier": 1.0,
      "Beacon_Experience_Multiplier": 1.0,
      "Full_Moon_Experience_Multiplier": 2.0,
      "Min_Drops": 1,
      "Max_Drops": 1,
      "Min_Mega_Drops": 5,
      "Max_Mega_Drops": 5,
      "Min_Boss_Drops": 8,
      "Max_Boss_Drops": 10,
      "Slow_Movement": false,
      "Can_Stun": true,
      "Only_Critical_Stuns": false,
      "Weapons_Use_Player_Damage": false,
      "Can_Target_Barricades": true,
      "Can_Target_Structures": true,
      "Can_Target_Vehicles": true,
      "Beacon_Max_Rewards": 0,
      "Beacon_Max_Participants": 0,
      "Beacon_Rewards_Multiplier": 1.0
    },
    "Animals": {
      "Respawn_Time": 180.0,
      "Damage_Multiplier": 1.0,
      "Armor_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64,
      "Weapons_Use_Player_Damage": false
    },
    "Barricades": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Allow_Item_Placement_On_Vehicle": true,
      "Allow_Trap_Placement_On_Vehicle": true,
      "Max_Item_Distance_From_Hull": 64.0,
      "Max_Trap_Distance_From_Hull": 16.0
    },
    "Structures": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0
    },
    "Players": {
      "Health_Default": 100,
      "Health_Regen_Min_Food": 90,
      "Health_Regen_Min_Water": 90,
      "Health_Regen_Ticks": 60,
      "Food_Default": 100,
      "Food_Use_Ticks": 300,
      "Food_Damage_Ticks": 15,
      "Water_Default": 100,
      "Water_Use_Ticks": 270,
      "Water_Damage_Ticks": 20,
      "Virus_Default": 100,
      "Virus_Infect": 50,
      "Virus_Use_Ticks": 125,
      "Virus_Damage_Ticks": 25,
      "Leg_Regen_Ticks": 750,
      "Bleed_Damage_Ticks": 10,
      "Bleed_Regen_Ticks": 750,
      "Armor_Multiplier": 1.0,
      "Experience_Multiplier": 1.0,
      "Detect_Radius_Multiplier": 1.0,
      "Ray_Aggressor_Distance": 8.0,
      "Lose_Skills_PvP": 0.75,
      "Lose_Skills_PvE": 0.75,
      "Lose_Items_PvP": 1.0,
      "Lose_Items_PvE": 1.0,
      "Lose_Clothes_PvP": true,
      "Lose_Clothes_PvE": true,
      "Lose_Weapons_PvP": true,
      "Lose_Weapons_PvE": true,
      "Can_Hurt_Legs": true,
      "Can_Break_Legs": true,
      "Can_Fix_Legs": true,
      "Can_Start_Bleeding": true,
      "Can_Stop_Bleeding": true,
      "Spawn_With_Max_Skills": false,
      "Spawn_With_Stamina_Skills": false,
      "Allow_Instakill_Headshots": false,
      "Allow_Per_Character_Saves": true
    },
    "Objects": {
      "Binary_State_Reset_Multiplier": 1.0,
      "Fuel_Reset_Multiplier": 1.0,
      "Water_Reset_Multiplier": 1.0,
      "Resource_Reset_Multiplier": 1.0,
      "Resource_Drops_Multiplier": 1.0,
      "Rubble_Reset_Multiplier": 1.0,
      "Allow_Holiday_Drops": true,
      "Items_Obstruct_Tree_Respawns": true
    },
    "Events": {
      "Rain_Frequency_Min": 2.3,
      "Rain_Frequency_Max": 5.6,
      "Rain_Duration_Min": 0.05,
      "Rain_Duration_Max": 0.15,
      "Snow_Frequency_Min": 1.3,
      "Snow_Frequency_Max": 4.6,
      "Snow_Duration_Min": 0.2,
      "Snow_Duration_Max": 0.5,
      "Weather_Frequency_Multiplier": 1.0,
      "Weather_Duration_Multiplier": 1.0,
      "Airdrop_Frequency_Min": 0.8,
      "Airdrop_Frequency_Max": 6.5,
      "Airdrop_Speed": 128.0,
      "Airdrop_Force": 9.5,
      "Arena_Min_Players": 2,
      "Arena_Compactor_Damage": 9,
      "Arena_Compactor_Extra_Damage_Per_Second": 1.0,
      "Arena_Clear_Timer": 5,
      "Arena_Finale_Timer": 10,
      "Arena_Restart_Timer": 15,
      "Arena_Compactor_Delay_Timer": 1,
      "Arena_Compactor_Pause_Timer": 5,
      "Use_Airdrops": true,
      "Arena_Use_Compactor_Pause": true,
      "Arena_Compactor_Speed_Tiny": 0.5,
      "Arena_Compactor_Speed_Small": 1.5,
      "Arena_Compactor_Speed_Medium": 3.0,
      "Arena_Compactor_Speed_Large": 4.5,
      "Arena_Compactor_Speed_Insane": 6.0,
      "Arena_Compactor_Shrink_Factor": 0.5
    },
    "Gameplay": {
      "Repair_Level_Max": 3,
      "Hitmarkers": true,
      "Crosshair": true,
      "Ballistics": true,
      "Chart": false,
      "Satellite": false,
      "Compass": false,
      "Group_Map": true,
      "Group_HUD": true,
      "Group_Player_List": true,
      "Allow_Static_Groups": true,
      "Allow_Dynamic_Groups": true,
      "Allow_Shoulder_Camera": true,
      "Can_Suicide": true,
      "Friendly_Fire": false,
      "Bypass_Buildable_Mobility": false,
      "Allow_Holidays": true,
      "Timer_Exit": 10,
      "Timer_Respawn": 10,
      "Timer_Home": 30,
      "Timer_Leave_Group": 30,
      "Max_Group_Members": 0,
      "Explosion_Launch_Speed_Multiplier": 1.0,
      "AirStrafing_Acceleration_Multiplier": 1.0,
      "AirStrafing_Deceleration_Multiplier": 1.0
    }
  },
  "Hard": {
    "Items": {
      "Spawn_Chance": 0.15,
      "Despawn_Dropped_Time": 600.0,
      "Despawn_Natural_Time": 3000.0,
      "Respawn_Time": 3600.0,
      "Quality_Full_Chance": 0.01,
      "Quality_Multiplier": 1.0,
      "Gun_Bullets_Full_Chance": 0.025,
      "Gun_Bullets_Multiplier": 0.1,
      "Magazine_Bullets_Full_Chance": 0.025,
      "Magazine_Bullets_Multiplier": 0.25,
      "Crate_Bullets_Full_Chance": 0.025,
      "Crate_Bullets_Multiplier": 0.75,
      "Has_Durability": true
    },
    "Vehicles": {
      "Decay_Time": 604800.0,
      "Decay_Damage_Per_Second": 0.1,
      "Has_Battery_Chance": 0.25,
      "Min_Battery_Charge": 0.1,
      "Max_Battery_Charge": 0.3,
      "Has_Tire_Chance": 0.7,
      "Respawn_Time": 300.0,
      "Unlocked_After_Seconds_In_Safezone": 3600.0,
      "Armor_Multiplier": 1.0,
      "Child_Explosion_Armor_Multiplier": 1.0,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64
    },
    "Zombies": {
      "Spawn_Chance": 0.15,
      "Loot_Chance": 0.5,
      "Crawler_Chance": 0.125,
      "Sprinter_Chance": 0.175,
      "Flanker_Chance": 0.03,
      "Burner_Chance": 0.03,
      "Acid_Chance": 0.03,
      "Boss_Electric_Chance": 0.0001,
      "Boss_Wind_Chance": 0.0001,
      "Boss_Fire_Chance": 0.0001,
      "Spirit_Chance": 0.0001,
      "DL_Red_Volatile_Chance": 0.0,
      "DL_Blue_Volatile_Chance": 0.0,
      "Boss_Elver_Stomper_Chance": 0.0009,
      "Respawn_Day_Time": 720.0,
      "Respawn_Night_Time": 90.0,
      "Respawn_Beacon_Time": 30.0,
      "Quest_Boss_Respawn_Interval": 600.0,
      "Damage_Multiplier": 1.4,
      "Armor_Multiplier": 0.75,
      "Backstab_Multiplier": 1.35,
      "NonHeadshot_Armor_Multiplier": 1.0,
      "Beacon_Experience_Multiplier": 3.0,
      "Full_Moon_Experience_Multiplier": 2.0,
      "Min_Drops": 1,
      "Max_Drops": 2,
      "Min_Mega_Drops": 5,
      "Max_Mega_Drops": 5,
      "Min_Boss_Drops": 8,
      "Max_Boss_Drops": 10,
      "Slow_Movement": false,
      "Can_Stun": false,
      "Only_Critical_Stuns": true,
      "Weapons_Use_Player_Damage": true,
      "Can_Target_Barricades": true,
      "Can_Target_Structures": true,
      "Can_Target_Vehicles": true,
      "Beacon_Max_Rewards": 8,
      "Beacon_Max_Participants": 10,
      "Beacon_Rewards_Multiplier": 1.0
    },
    "Animals": {
      "Respawn_Time": 180.0,
      "Damage_Multiplier": 1.5,
      "Armor_Multiplier": 0.75,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64,
      "Weapons_Use_Player_Damage": true
    },
    "Barricades": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Allow_Item_Placement_On_Vehicle": true,
      "Allow_Trap_Placement_On_Vehicle": true,
      "Max_Item_Distance_From_Hull": 64.0,
      "Max_Trap_Distance_From_Hull": 16.0
    },
    "Structures": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0
    },
    "Players": {
      "Health_Default": 100,
      "Health_Regen_Min_Food": 90,
      "Health_Regen_Min_Water": 90,
      "Health_Regen_Ticks": 60,
      "Food_Default": 85,
      "Food_Use_Ticks": 350,
      "Food_Damage_Ticks": 10,
      "Water_Default": 85,
      "Water_Use_Ticks": 320,
      "Water_Damage_Ticks": 15,
      "Virus_Default": 100,
      "Virus_Infect": 50,
      "Virus_Use_Ticks": 125,
      "Virus_Damage_Ticks": 25,
      "Leg_Regen_Ticks": 750,
      "Bleed_Damage_Ticks": 10,
      "Bleed_Regen_Ticks": 750,
      "Armor_Multiplier": 1.0,
      "Experience_Multiplier": 1.5,
      "Detect_Radius_Multiplier": 1.25,
      "Ray_Aggressor_Distance": 8.0,
      "Lose_Skills_PvP": 0.75,
      "Lose_Skills_PvE": 0.75,
      "Lose_Items_PvP": 1.0,
      "Lose_Items_PvE": 1.0,
      "Lose_Clothes_PvP": true,
      "Lose_Clothes_PvE": true,
      "Lose_Weapons_PvP": true,
      "Lose_Weapons_PvE": true,
      "Can_Hurt_Legs": true,
      "Can_Break_Legs": true,
      "Can_Fix_Legs": false,
      "Can_Start_Bleeding": true,
      "Can_Stop_Bleeding": false,
      "Spawn_With_Max_Skills": false,
      "Spawn_With_Stamina_Skills": false,
      "Allow_Instakill_Headshots": true,
      "Allow_Per_Character_Saves": true
    },
    "Objects": {
      "Binary_State_Reset_Multiplier": 1.0,
      "Fuel_Reset_Multiplier": 1.0,
      "Water_Reset_Multiplier": 1.0,
      "Resource_Reset_Multiplier": 1.0,
      "Resource_Drops_Multiplier": 1.0,
      "Rubble_Reset_Multiplier": 1.0,
      "Allow_Holiday_Drops": true,
      "Items_Obstruct_Tree_Respawns": true
    },
    "Events": {
      "Rain_Frequency_Min": 2.3,
      "Rain_Frequency_Max": 5.6,
      "Rain_Duration_Min": 0.05,
      "Rain_Duration_Max": 0.15,
      "Snow_Frequency_Min": 1.3,
      "Snow_Frequency_Max": 4.6,
      "Snow_Duration_Min": 0.2,
      "Snow_Duration_Max": 0.5,
      "Weather_Frequency_Multiplier": 1.0,
      "Weather_Duration_Multiplier": 1.0,
      "Airdrop_Frequency_Min": 0.8,
      "Airdrop_Frequency_Max": 6.5,
      "Airdrop_Speed": 128.0,
      "Airdrop_Force": 9.5,
      "Arena_Min_Players": 2,
      "Arena_Compactor_Damage": 9,
      "Arena_Compactor_Extra_Damage_Per_Second": 1.0,
      "Arena_Clear_Timer": 5,
      "Arena_Finale_Timer": 10,
      "Arena_Restart_Timer": 15,
      "Arena_Compactor_Delay_Timer": 1,
      "Arena_Compactor_Pause_Timer": 5,
      "Use_Airdrops": true,
      "Arena_Use_Compactor_Pause": true,
      "Arena_Compactor_Speed_Tiny": 0.5,
      "Arena_Compactor_Speed_Small": 1.5,
      "Arena_Compactor_Speed_Medium": 3.0,
      "Arena_Compactor_Speed_Large": 4.5,
      "Arena_Compactor_Speed_Insane": 6.0,
      "Arena_Compactor_Shrink_Factor": 0.5
    },
    "Gameplay": {
      "Repair_Level_Max": 3,
      "Hitmarkers": false,
      "Crosshair": false,
      "Ballistics": true,
      "Chart": true,
      "Satellite": true,
      "Compass": true,
      "Group_Map": true,
      "Group_HUD": true,
      "Group_Player_List": true,
      "Allow_Static_Groups": true,
      "Allow_Dynamic_Groups": true,
      "Allow_Shoulder_Camera": true,
      "Can_Suicide": true,
      "Friendly_Fire": false,
      "Bypass_Buildable_Mobility": false,
      "Allow_Holidays": true,
      "Timer_Exit": 10,
      "Timer_Respawn": 10,
      "Timer_Home": 30,
      "Timer_Leave_Group": 30,
      "Max_Group_Members": 0,
      "Explosion_Launch_Speed_Multiplier": 1.0,
      "AirStrafing_Acceleration_Multiplier": 1.0,
      "AirStrafing_Deceleration_Multiplier": 1.0
    }
  }
}`

Detials of config.json causing the offending problem. I am providing this out of worry I have done something wrong with the values which could be causing the linux client to fail a sanity handle check where the windows one isn't.  I have checked teh values and aside from some values outside the norm of an everyday unturned server I cant find an "error" in the json formatting or values.

**Comment by Defying00** [comment]
[https://ibb.co/qxKRbCW](url)

Screenshot of lobby.

**Comment by SDGNelson** [comment]
It looks like the "GameVersion" property is getting received as just "3." rather than "3.22.7.0". Other values with '.' like Elver boss chance seem to be coming through okay, so that probably rules out Steam client splitting them up incorrectly. Could you post the server IP:port please? I will check whether I can reproduce the wrong value.

**Comment by Defying00** [comment]
139.59.166.86:25000 (London PEI)

147.182.235.157:25132 (San fran - Russia)

Also if you rapidly click the join button  it will join to the server before it errors red lol (weird work around for the moment)

But the join button doesnt go red until the config.json loads.

**Comment by Defying00** [comment]
Reflecting on time line. I have a hunch that this bug has something to do with food and water consumption variables. As all other variables have been modified and set for many many days now. Though the last 48 hours we have been playing with the food and water consumption. However when we left the server yesterday after its midnight reset, linux players seeminigly were able to connect.

**Comment by Defying00** [comment]
@SDGNelson Hey apologies, no rush, or bother, but were you able to confirm or deny this bug? I only ask because I madly hunting something I have done wrong.

**Comment by Defying00** [comment]
[Update]

Linux clients now show version 3.21.8  displayed in red, with the join button greyed out. Servers have not been restarted though majority of linux clients have attempted reinstalling their game and restarting pcs several times. So this could be the result of a reinstall or computer restart.

I am launching a test server now so I can attempt to isolate which value exactly is causing this problem with out disturbing the regular players.

**Comment by Defying00** [comment]
[Update - Reproduction Steps]

This bug seems to spawn from the number of things  modified in the server config file.  Below are the steps to reproduce.

1. Start a vanilla server on a linux host using steamcmd.  --> Clients can connect fine
2. Use the following config https://pastebin.com/F1mDywyX
3. Set mode to hard in commands.dat
4. Start Server - > Clients can connect fine
5. Change 1 value anywhere in the "hard section" of the config (this was tested using true false properties for this step)
6. Restart Server - Linux clients can no longer connect fine, the join button cites version 3.21.7 and on rare occasions 3. with spaces for the other characters.

This bug has been reproduced now on two separate hosting companies (one of which I own) and three community members local linux machines and seems to reproduce with the above steps.

During testing every changed value in the provided config was tested with a restart and several linux flavors attempting to connect.  It was not until we started changing values in game play that the bug happened. Then we did testing to see if it was a numbers thing. It seems to not matter what section in the hard part of the json you use, after the values exceed an amount from default the server stops sending the correct version to linux clients.

**Comment by SDGNelson** [comment]
Sorry for my delay - usually I catch up on issues in the morning, but did not today until the evening. The server does indeed seem to be sending all of the correct values, so I wonder if maybe there is a smaller "rules" buffer size in the Steam Linux client. I will plan to make two related changes for the next update:
1. If parsing the server's game version tag fails (e.g. getting truncated here) then allow the server to be joined.
2. Will make all of the rule key names shorter to see if that works around the problem on Linux. (this would indicate it is hitting a max length)
For the meantime unfortunately it sounds like the only workaround would be disabling some of the config edits. :/

**Comment by Defying00** [comment]
Thanks for your update!

We did disable some of the configuration edits and servers are working fine and are join-able by all players! Looking forward to the update!

**Comment by Defying00** [comment]
[Update]
Out of curiosity the community did a very crude evaluation of unturned servers on the public list that suffered from this bug.

We found that about 1/3 of the unturned servers we were able to document as a group were unjoinable by players on linux clients.

(The methods we used to get this data are flawed at the core and the numbers should not be taken specifically, only to express that a large portion of unturned servers suffer from this bug and most likely their operators don't even know a decent portion of players cant play on their servers.)

**Comment by SDGNelson** [comment]
That is quite a few. Maybe it was a side effect of Valve's recent changes to add Fake IP support. Aside from the workaround for the next update we should also get that integrated into Unturned sooner than later.

**Comment by Defying00** [comment]
We believe also its something new cause we have never had this problem in the past.

**Comment by Defying00** [comment]
Would like to confirm that this bug has been fixed on the newest version! Thanks alot Nelson and we can close this out great work!

**Comment by SDGNelson** [comment]
Glad to hear it is working! I would just like to note that the underlying issue (something with Steam Linux client) has not been fixed, but it should be mitigated for a higher number of config and workshop entries in the meantime. Also the "different version" warning will no longer be shown if it failed to parse the version number, so worst case it should hopefully still be joinable.
