### ISSUE TITLE
After loading data the river doesn't closed

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#3120]
Methods that are loading data from `river` and then doesn't close it:

`GroupManager.load`;
`StructureManager.load`;
`ObjectManager.load`;
`VehicleManager.load`;
`LightingManager.load`;
`LevelManager.load`;
`SteamBlacklist.load`;
`SteamWhitelist.load`;
`SteamAdminlist.load`.

Also, the method `CharacterAnimator.getAnimationPlaying` has condition that always will be true:
```csharp
    return >>>!string.IsNullOrEmpty(name)<<< && anim.IsPlaying(clip);
```

maybe it should be:
```csharp
    return >>>!string.IsNullOrEmpty(clip)<<< && anim.IsPlaying(clip);
```

**Comment by SDGNelson** [comment]
Thanks for these reports! I will get them fixed for the next update.

**Comment by SDGNelson** [comment]
Fixed for the next update. Thanks again!
