### ISSUE TITLE
News and featured workshop ignore `UI Scale Factor` value

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#3123]
![image](https://user-images.githubusercontent.com/48765566/163589071-23ea20de-ba3c-4acd-8393-e4f4dfbef8ef.png)

**Comment by SDGNelson** [comment]
The featured workshop and news were manually created in uGUI before the Glazier rewrite. My hope is to convert them over to the same UI code as the rest of the game as part of supporting UI Toolkit. *fingers crossed*
