### ISSUE TITLE
Error with stairs on the map, they cannot be used

### ISSUE THREAD

**Issue by ElRicki** [SmartlyDressedGames/Unturned-3.x-Community#3127]
Suddenly, for no reason at least that I know of, an error with the stairs on the map started happening on my server. One day stopped working and another day started working for no apparent reason

This is what is happening

https://user-images.githubusercontent.com/75626024/164083770-9f4a6283-4660-4272-9c37-326dd36b3a80.mp4

**Comment by educatalan02** [comment]
Try to place them outside of the wall using the Map Editor.

**Comment by SDGNelson** [comment]
My guess is that the ladder does not exist on the server's version of the map, or at least the server's map is different. I would recommend enabling `Should_Verify_Objects_Hash` in the map's Config.json file https://github.com/SmartlyDressedGames/U3-Docs/blob/master/LevelConfig.md and setting the Version number to help narrow this down.

**Comment by dzonyloker** [comment]
> My guess is that the ladder does not exist on the server's version of the map, or at least the server's map is different. I would recommend enabling `Should_Verify_Objects_Hash` in the map's Config.json file https://github.com/SmartlyDressedGames/U3-Docs/blob/master/LevelConfig.md and setting the Version number to help narrow this down.

I experienced same bug on my server. I fixied it by delete vehicles.dat from Level.
