### ISSUE TITLE
HighlighterTool.remesh list comparison using ==

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#3128]
I've noticed that `HighlighterTool.remesh` compares lists using `==` which compares list object references rather than comparing items they contain.
That could be a decompiler issue, but please take a look ;)

**Comment by SDGNelson** [comment]
Mmm I think this is intentional but I am also hesitant to touch it because it is janky and seems to be working fine.
