### ISSUE TITLE
"Graced Bane" skin - localization typo

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3130]
Minor bug/typo with a **Graced** skin made available from the Greece Map Mystery Box.

The **[Graced Bane](https://steamcommunity.com/market/listings/304930/Graced%20Bane)** skin should instead be named the **Graced Devil's Bane**. (Similarly, it should be a "Legendary _Devil's Bane_ Skin", that "applies the Graced appearance to the _Devil's Bane_ in-game").

**Comment by SDGNelson** [comment]
Thanks for the report. Hmm I am not sure if this was intentional, but probably not. Will fix for tomorrow's update!

**Comment by MoltonMontro** [comment]
I wouldn't be surprised if it had actually been intentional at some point, considering https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1128
