### ISSUE TITLE
Quest response should not be confirmed with server until accepted/denied

### ISSUE THREAD

**Issue by Bigman345** [SmartlyDressedGames/Unturned-3.x-Community#3134]
Ive been playing arid at this moment and realised when you press f or deny the barter "quests" it still gives you them outright. Is this a bug or an intended feature because I don't remember this.

**Comment by SDGNelson** [comment]
Sorry, my bad, it looks quests not registering NPC response was intentional. I had changed vendor and quest responses to register with the server when they are clicked. Will fix in the patch!
