### ISSUE TITLE
Shader Crashing on Linux Server. 

### ISSUE THREAD

**Issue by ajsbeast** [SmartlyDressedGames/Unturned-3.x-Community#3137]
I've been getting these shader errors when trying to run my server that is running on Linux. They started after updating my map from legacy to the new landscapes. The map works fine on windows and is only crashing on the server. These errors are as follows:

“WARNING: Shader Unsupported: ‘Standard’ - All passes removed”
“WARNING: Shader Did you use #pragma only_renderers and omit this platform?”
“ERROR: Shader Particles/Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)”

The first two will spam repeat, while the last one will also be other names of shaders (Like instead of Particle/Additive it might be Hidden/Nature or something like that). 

I'm not sure what these errors really mean since I'm not using any additional shaders in my masterbundle and they should just be able to use the base unturned ones, but the crashing only happens when these errors are given, and reverting to before the update removes the error and the crash.

**Comment by SDGNelson** [comment]
Does the server crash, or does the client crash? Shader warnings on the server should be a non-issue because the server should not be using any graphics features. The safest option might be to re-export your asset bundle with multiplatform enabled in the latest Unity 2019 LTS release.

**Comment by ajsbeast** [comment]
It's the server that crashes when attempting to launch, the client works fine (at least on windows I'm not sure about mac or linux). My current export settings for the project is Unity 2019.4.36f1 and I've been doing multi-platform exports since from what I understand it won't work on mac or linux if I don't? 

I wouldn't think the server would crash from a shader issue since usually that sort of thing doesn't matter but that is the only error thrown between the old version that doesn't crash and the new that does. 

Maybe I'm exporting with the wrong modules? 
![image](https://user-images.githubusercontent.com/104280155/164949558-e5c75bb9-a87f-46a9-85ae-1b0ef1fd9459.png)

**Comment by SDGNelson** [comment]
Yes - multiplatform export is needed otherwise Mac (Metal) and Linux (Vulkan) shaders are not included.

Unturned updated to 38f1 from 37f1 yesterday, and while there should not be any crazy differences I think it is worth trying with 38f1 just in case.

Personally I only enabled Linux (Mono) and Mac (Mono) build support, not Linux (IL2CPP) or Documentation.

**Comment by ajsbeast** [comment]
The issue still seems to persist after updating the project to Unity 2019.4.38f1 as well as only using the Linux mono and mac mono modules. I read somewhere that it may be related to the shaders in the project settings? My project settings looks like this.
![image](https://user-images.githubusercontent.com/104280155/164950636-3c834bc1-76c6-4890-8e46-6f0d7703cbd1.png)

Also just trying to grasp at anything my image file settings are this:
![image](https://user-images.githubusercontent.com/104280155/164950672-b9d4b336-f18a-405d-bfc1-7222e3e1630c.png)

**Comment by ajsbeast** [comment]
Alright so I was able to get the server to launch still using the legacy map, and the errors are still persistent but the server is running. So while the shader errors are definitely new they don't seem to be related to the crash. The crash is likely related to something wrong with the masterbundle on Linux.

**Comment by SDGNelson** [comment]
By legacy map are you referring to prior to changing over your landscape? In that case this might be unrelated to shader warnings because the game uses terrain shaders included in the vanilla assets. To narrow down whether there is a problem specifically with the newer terrain: does your Linux server crash if you use the PEI map? (because PEI uses the newer terrain) Is there any crash information below the shader warnings in the log file? If you add the `-logfile pathtofile.txt` argument to your server launch arguments (e.g. to your server .sh script) then there might be more detailed crash information in this Unity file.

**Comment by ajsbeast** [comment]
Yeah I updated my map from the old landscape to the new tiles and am trying to get my materials masterbundle to work. It seems to be fine on windows but is crashing the linux server. I ran the server without specifying the map (I believe it defaults to PEI) and it didn't crash fine, so it seems to be an issue with loading the map itself. In the server's log files the error I was able to see just before crash said that it is loading 256 landscape tiles? The map I'm working on is an Insane sized map, and has 4 tile parameter outside the map so that there is natural looking mountains to enclose it. This amount of tiles wouldn't be the issue would it? I'll include the full log report in case you'd like to take a look. 

I've ran the server again using "-logfile pathtofile.txt" in the ExampleServer.sh script, but I'm not sure if they are supposed to create a new file or if I'm supposed to specify the name of a text file in place of "pathtofile.txt". 
[Server_unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8558273/Server_unturned.log)

**Comment by SDGNelson** [comment]
For example if you do: `-logfile unitylog.txt` I think it will create unitylog.txt in the working directory, or you could do `-logfile /var/log/unity.txt` to specify an absolute path.

256 landscape tiles seems like a lot. That is 16 by 16 km. I am not sure if the terrain upgrade has ever been used for such a big map. Perhaps the server is running out of resources or stalling while trying to load them all? Off the top of my head I think insane size was 8x8 tiles, so I would recommend removing the tiles outside a 10x10 area.

**Comment by ajsbeast** [comment]
I reduced the tiles to a perimeter of only 2 tiles around the outside and the crashing seems to be mostly resolved, it seems the crashing was related to this. In places with large mountains I'll reduce it further to 1. Thanks for looking into this for me I was so lost at what was causing it.

**Comment by SDGNelson** [comment]
Glad to hear you got it working! Hopefully this kind of thing will get easier to work on sooner as well because I am finally planning out how to unify the old-new terrain into the regular editor.
