### ISSUE TITLE
Editor for placing down vehicle spawns

### ISSUE THREAD

**Issue by JJacKWW** [SmartlyDressedGames/Unturned-3.x-Community#3138]
![image_2022-04-24_022435026](https://user-images.githubusercontent.com/92102142/164949284-b15ff5c6-2d97-4a9f-a43e-eb774a7743c5.png)
In the editor, when going into "spawns" and selecting "vehicles", I find it hard to rotate the vehicle spawn points correctly with having to move your mouse to the angle slider.

My solution would be to make it simpler is whenever you want to place down a vehicle spawn, you can rotate it at the same time.

By holding down left click the vehicle spawn locks in that spot where you clicked initially and by waving your mouse around the screen - the vehicles front faces the mouse direction. After letting go the vehicle spawn just faces the direction you last had your mouse looking at before letting go of left click. 

Thus making vehicle spawns a bit more easier to place down with not much of a hassle, rather than trying to align the angle you need with your eye.

(On the fly reference pic)

**Comment by SDGNelson** [comment]
It is definitely not user-friendly or intuitive as-is. I think it has not changed since late 2014. My goal is to allow the legacy editor selection / transform tools to be used with all of those sooner or later.
