### ISSUE TITLE
Edior (Environment > Navigation)

### ISSUE THREAD

**Issue by JJacKWW** [SmartlyDressedGames/Unturned-3.x-Community#3142]
I found out that by scaling the building [snap translation 1] the other side, the navigation system that the zombies use to pathfind - does not capture it as a building, thus not allowing them to navigate into it or onside of the said building
![image_2022-04-25_174121495](https://user-images.githubusercontent.com/92102142/165112611-2e82c735-22fe-4780-9a2f-da95ca73bce4.png)
![image_2022-04-25_174142059](https://user-images.githubusercontent.com/92102142/165112700-717339c6-7b05-43e7-89cb-b822460e32e9.png)

**Comment by SDGNelson** [comment]
Sorry, off the top of my head I think the limitation here is the navmesh generation will not use the inside-out normals. (Unity automatically inverts the negative-scaled normals for rendering, but the navmesh generator does not)
