### ISSUE TITLE
Stuck in queue

### ISSUE THREAD

**Issue by danielstankw** [SmartlyDressedGames/Unturned-3.x-Community#3143]
Hi,
I got the following issue. 
Every now and then when a player tries to connect to the server he gets stuck in a queue. Despite reaching queue timeout player isn't kicked out and he just stays in queue till decides to cancel the attempt to connect. 
A restart of the server solves the issue, but there are no errors in RocketLog or Server Log when it happens. 

We have been trying to narrow down the issue by replacing server tokens, plugins, and libraries but without success. 
We have two servers that are identical. One 100x loot and another 5x. Same plugins, libraries, and running on the same dedi. But one of them experiences the queue issue and another one doesn't.

Did anyone encounter that issue?

**Comment by SDGNelson** [comment]
Do you have any plugins which accept multiple players from the queue simultaneously? Vanilla processes the front-of-queue player one at a time, but I know there are some plugins which are probably breaking things by trying to accept multiple players at once.

Otherwise I would think either the client or server should be timing out as you mentioned. 😕

**Comment by SDGNelson** [comment]
First suggestion would be to try disabling that queue bypass plugin.

If you would like to post the IP:port I can try joining as well and debug what is happening on the client.

**Comment by danielstankw** [comment]
@SDGNelson if you could check it out that would help a ton.
IP: eu.syntale.net Port: 27060
Here are the details

**Comment by SDGNelson** [comment]
Does the server log any exceptions? I was able to get kicked for asset bundle hash mismatch but no response for a regular join which probably means something on the server side in Provider.accept is patched or throwing an exception.

**Comment by danielstankw** [comment]
The mod mismatch is probably due to a server having a lot of mods, so it would require deleting mods to get rid of the conflict. 
Unfortunately both in Rocket and Server Logs, there are no exceptions.

**Comment by SDGNelson** [comment]
To clarify: I intentionally got kicked for asset bundle hash mismatch to narrow down when the problem occurs. Unfortunately there is nothing else I can do to help from the client side except point out that it is probably in Provider.accept. I would recommend disabling a few plugins at a time to see if there is a specific plugin causing the issue.

**Comment by MillionthOdin16** [comment]
I've had the same issue for the last week. I get no errors as well. Haven't been able to figure out what causes it
