### ISSUE TITLE
[Feature Request] Adding an option for ADS sensivity

### ISSUE THREAD

**Issue by liebesleid-eth** [SmartlyDressedGames/Unturned-3.x-Community#3147]
Would be nice to be able to adjust an ADS sensivity multiplier so that we can have back the scope sensivity some of us are used to. Or a way to separate hipfire/scope sensivities separatedly

**Comment by SDGNelson** [comment]
The game automatically adjusts the sensitivity according to the zoom factor, but the next update will have "focal length sensitivity scaling" which is much better than manually configuring separate hip/ads sensitivity.
