### ISSUE TITLE
Quest abandon button doesn't turn from active -> none for character condition

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3149]
Hello, one day I noticed that if you use the abandon button, it won't make an NPC disappear that have `has quest: active` condition on them. Here's a quick video:

https://user-images.githubusercontent.com/81763752/165464385-e2a374eb-55a2-461e-873e-74780e497f79.mp4

However when I accept the quest again with the item in my inventory, it makes the NPC disappear. (Probably because the quest goes immediately to Ready rather than Active)

https://user-images.githubusercontent.com/81763752/165464645-6fa2fefb-550c-4b38-a820-c7793f934011.mp4

What I would do is get rid of the abandon button or at least having a map option which disables it. Right now I have to bulletproof every single quest, because when someone accepts a quest, they receive an item. Without protecting it, they can simply abuse the abandon button and spam accept the quest until they have infinite amount of X items. 
Same goes for NPCs that appear after accepting a quest. A player receives a flag to see a specific NPC, however when the player abandons the quest, they still have the flag and there's no way for me to bulletproof that.

**Comment by SDGNelson** [comment]
There are some optimization reasons for these kind of bugs: level objects only listen for certain events depending on their conditions. It looks like quest condition only listens for quest added events right now, so I will fix this to also look for quest removed events in the next update.
