### ISSUE TITLE
New Ladder mechanics broke some map design

### ISSUE THREAD

**Issue by embermctillhawk** [SmartlyDressedGames/Unturned-3.x-Community#3150]
Many maps have a feature where items spawn on small flat parts of radio towers as you climb up.
These items are now inaccessible with the new ladder mechanics. They still spawn in, but cannot be claimed.

Can we always prioritize picking items over picking the ladder?

**Comment by SDGNelson** [comment]
Unfortunately items cannot be prioritized over ladder with how the physics query works. I think this is a relatively minor issue though. Maybe it explains lore wise why those items got left there! 😉 Technically they can still be retrieved with some effort if the item is valuable.
