### ISSUE TITLE
"Glitch Skycrane"

### ISSUE THREAD

**Issue by WilliamB0rum** [SmartlyDressedGames/Unturned-3.x-Community#3151]
Destroying a Skycrane while a destroyed vehicle is attached will cause a reaction with extreme lag and Fps.

Watch this video ------> https://youtu.be/0wRKNJgowmM

**Comment by SDGNelson** [comment]
Thanks for the report! Haha
It looks like there is probably an exception when the skycrane explodes. I will check into this for the next update, as well as probably prevent picking up exploded vehicles.
