### ISSUE TITLE
" Tank Glitch "

### ISSUE THREAD

**Issue by WilliamB0rum** [SmartlyDressedGames/Unturned-3.x-Community#3152]
If you enter on top of the tank, you could be flying bug.

https://youtu.be/LD0tzm7xFS4

**Comment by SDGNelson** [comment]
Unfortunately this is a longstanding known issue, but the "lesser of two evils" for now. Sooner than later I am hoping to experiment with making vehicle physics fully server authoritative which (among other benefits) will allow some player movement changes to hopefully prevent this kind of thing.
