### ISSUE TITLE
[Bug] Blackscreen menu when exiting a game while in water

### ISSUE THREAD

**Issue by Tiway-Paper-Guy** [SmartlyDressedGames/Unturned-3.x-Community#3153]
Hello!

I experienced a blackscreen background in the menu of the game (image below)
![20220429101304_1](https://user-images.githubusercontent.com/84565748/165908177-17f2298b-ce6b-482a-8483-d5958a9e8f9c.jpg)

It seems like this happen when I exit a game (singleplayer in that case) while being underwater.

It could be linked to my graphic settings, so there they are just in case :
![20220429101609_1](https://user-images.githubusercontent.com/84565748/165908364-43a47c46-6c18-4608-a50b-ef1d8c15db91.jpg)
![20220429101612_1](https://user-images.githubusercontent.com/84565748/165908370-430e8d9e-dd59-4d79-8fa8-85546e92d48b.jpg)

**Comment by SDGNelson** [comment]
Sorry, this should be fixed in the next update!
