### ISSUE TITLE
Modified or corrupted asset issue.

### ISSUE THREAD

**Issue by JuicyNuts** [SmartlyDressedGames/Unturned-3.x-Community#3154]
So, I was testing stuff and I spawned in a Target from the mod "Furniture Expansion". For some reason when I placed it I crash, if I get near it I crash. Any idea on if it's a server issue or a me issue or the mod author's fault? I reinstalled, didn't work. And yes, i deleted all the mod files. Here's the message I get.

Modified or corrupted asset: "Target" File: "Target" Id: 48bf205f38c84d3cb7a6eeee36e649d3 Client: E2EABC11ECE551BEFE8D5224E43EF2772ADBA42 Server: 6C2E3EC0F8D29F85A1CD9DF3186FC6E27D38527

**Comment by JuicyNuts** [comment]
And also I've tried restarting the server, didn't work. I kept getting kicked when getting near it. If I get on another character far away from it then I won't crash.

**Comment by SDGNelson** [comment]
This means that the file installed on your client does not match the file installed on the server. There are a variety of reasons this could happen for example if the workshop version was updated and the client has the newer version while the server has the older version, or if you locally edited the file, or if the server host edited the file.
