### ISSUE TITLE
you are banned from multiplayer

### ISSUE THREAD

**Issue by Devachka123** [SmartlyDressedGames/Unturned-3.x-Community#3155]
Hello, I would like to ask you for help. The day before yesterday I created a new steam account, and downloaded Unturned, I go to any server, and after a couple of minutes I get kicked from the server and writes:"you are banned from multiplayer". If you go to the profile, you can see there that I was banned
Is there any solution to this problem?
Note: I have never used cheats

**Comment by educatalan02** [comment]
Why do you create a new account to play unturned if your main account isnt banned?

**Comment by Devachka123** [comment]
> Why do you create a new account to play unturned if your main account isnt banned?

It's just that I have other accounts for other games, where only they are, because of this I made a new account

**Comment by Devachka123** [comment]
> I know 2 guys that was banned for no reason yesterday one of these has 5k hours. I think something happened to BattlEye

waiting for a response from the developer

**Comment by SDGNelson** [comment]
Sorry, you would need to contact BattlEye support here: https://www.battleye.com/contact/
