### ISSUE TITLE
you are banned multiplayer

### ISSUE THREAD

**Issue by ScamTr0jan** [SmartlyDressedGames/Unturned-3.x-Community#3156]
Hello, I would like to ask you for help. Today I went into my account where 5 thousand hours, and downloaded Unturned, I go to any server, and after a couple of minutes I am kicked from the server and writes: "You are banned in multiplayer." If you go to the profile, it shows that I was banned. Is there any solution to this problem? 
This is my steam account: http://steamcommunity.com/profiles/76561198884363489
Note: I have never used cheats
![image](https://user-images.githubusercontent.com/104781263/166263486-1555fba1-6b7a-4e02-90bb-9200c340d0db.png)

**Comment by SDGNelson** [comment]
Sorry, you would need to contact BattlEye support here: https://www.battleye.com/contact/
