### ISSUE TITLE
[Feature Request] Throwables Spawning Raycast Bullet

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#3161]
Hello! I am attempting to create a one-time-use throwable spear as a weapon, and I have tried a number of methods such as making an impact grenade with no effect. However, I am struggling to get it to feel right as even with the impact grenade breaking on impact with a player, it doesn't work as intended because the "source" for determining damage is the player's feet and not the distance to any part of the body, so the range has to be fairly high to even hit correctly when attacking the head or upper body which gives the issue of a spear damaging an entire group of people. What I was hoping could be done would be either for throwables to be able to activate a raycast, regular gun like bullet that damages wherever it hits and still has drop, or to add an effect to projectile weapons/throwables that allows for them to damage whatever they hit based on bullet modifiers and not distance to feet.

Thank you!

**Comment by GazziFX** [comment]
Why not add custom component which will properly damage player when OnTriggerEnter?

**Comment by Dumfoozler** [comment]
> Why not add custom component which will properly damage player when OnTriggerEnter?

I have no idea what that means

**Comment by GazziFX** [comment]
I mean like

```csharp
public class CustomComponent : MonoBehaviour
{
   public void OnTriggerEnter(Collider col)
   {
      if (Physics.Raycast(...))
      {
         DamageTool.damagePlayer(...);
      }
   }
}
```

**Comment by Dumfoozler** [comment]
How/Where Do I use that on a throwable

**Comment by GazziFX** [comment]
```csharp
UseableGun.onProjectileSpawned += (UseableGun sender, GameObject projectile) => { projectile.AddComponent<CustomComponent>(); };
```
Understand?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
