### ISSUE TITLE
Scope quality Off - FOV&Sensitivity

### ISSUE THREAD

**Issue by freser15** [SmartlyDressedGames/Unturned-3.x-Community#3162]
After the FOV update, when selecting scope quality off in graphics settings, the FOV and sensitivity do not work correctly, even when changing `Field_Of_View_Aim` in preferences.json. Regardless of the value, the zoom is too much and sensitivity is too high (compared to scope quality off before the update).
I cannot get the 'old' zoom factor and sensitivity back for scope quality Off, tried a bunch of settings. Though on Ultra, `"Field_Of_View_Aim": 60.0` looks about right.

**Comment by SDGNelson** [comment]
The value in the preferences file is for the viewmodel itself, not the zoom factor. In good news however the next update has a "sensitivity scaling mode" option that lets you select the same behaviour as before the 3.22.8.0 update.
