### ISSUE TITLE
Invalid file integrity request guid

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3163]
I've currently got players unable to enter a specific area of the map on one of my servers, they get kicked with this error:

![image](https://user-images.githubusercontent.com/71527679/167012146-409a1bec-be7d-4310-9b17-1cb17b5cc5dd.png)
<img width="701" alt="image" src="https://user-images.githubusercontent.com/71527679/167012164-3dcf9a1e-3acc-4aff-91de-5f71faabd1d7.png">
The server is unmodded. 

Any ideas, or potential fixes that don't involve wiping the whole map? 

Exert from Server.log :

> 
> [2022-05-02 18:11:02] BattlEye Server: Player #28 Machi (202.231.98.222:50301) connected
> [2022-05-02 18:11:02] BattlEye Server: Player #28 Machi - BE GUID: 14e6f9ce3bdaaabc7b3cc420e46f8283
> [2022-05-02 18:11:02] Connecting: PlayerID: 76561198227729312 Name: Machi Character: Machi
> [2022-05-02 18:11:05] Long delay between Updates: 2.137504s
> [2022-05-02 18:11:10] Kicking steamid:76561198227729312 for invalid file integrity request guid: 2e756f796f6620722d2053743c62723e
> [2022-05-02 18:11:10] Disconnecting: PlayerID: 76561198227729312 Name: Machi Character: Machi
> [2022-05-02 18:11:10] BattlEye Server: Player #28 Machi disconnected
> [2022-05-02 18:11:10] [World] iliketoes504 [Pizzatime_exe]: "500 is 8 minutes"
> [2022-05-02 18:11:11] [World] C.I.A  Sharpie [sharpie]: "hey machi"
> [2022-05-02 18:11:16] [World] iliketoes504 [Pizzatime_exe]: "600 is 10"
> [2022-05-02 18:11:22] BattlEye Server: Player #28 Hopped (219.88.97.149:61432) connected
> [2022-05-02 18:11:22] BattlEye Server: Player #28 Hopped - BE GUID: 3677c18df6b4f3aa70e60fa52abfc9fc
> [2022-05-02 18:11:22] Connecting: PlayerID: 76561198875397345 Name: Hopped Character: Smile
> [2022-05-02 18:11:24] Long delay between Updates: 2.174278s
> [2022-05-02 18:11:26] Kicking steamid:76561198875397345 for invalid file integrity request guid: 493e7262ce3e3c9e6f6b732074206c6f
> [2022-05-02 18:11:26] Disconnecting: PlayerID: 76561198875397345 Name: Hopped Character: Smile
> [2022-05-02 18:11:26] BattlEye Server: Player #28 Hopped disconnected

**Comment by SDGNelson** [comment]
You mention unmodded, but this should only happen with plugins 😕 do you mean you do not have any workshop files, or does your server have any plugins that might be patching the barricade/structure methods?

**Comment by AdamDN** [comment]
Oops sorry should have been more specific; plugins yes, workshop no. 
If it's caused by patching the barricade methods there's a couple I can think of a couple that could potentially be causing it - I can try removing them and see if that fixes it

**Comment by AdamDN** [comment]
I've done a bit more testing - a plugin may have been the initial cause of the issue, but even with all modules and plugins completely removed the error is still there. (with a different GUID this time).

<img width="643" alt="image" src="https://user-images.githubusercontent.com/71527679/167061333-b0cf5f99-a645-4a2c-96de-81c82b695144.png">

It looks like it's being caused by a sign.

Client.log:
> [2022-05-06 04:54:46] Exception while spawning barricade: 1098 - Sign_Metal
> [2022-05-06 04:54:46] Destination array is not long enough to copy all the items in the collection. Check array index and length.
> [2022-05-06 04:54:46]   at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.BitConverter.ToUInt64 (System.Byte[] value, System.Int32 startIndex) [0x00023] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at SDG.Unturned.InteractableSign.updateState (SDG.Unturned.Asset asset, System.Byte[] state) [0x00117] in <e722b749a4ba496696325f210b77d83c>:0 
>   at SDG.Unturned.BarricadeManager.spawnBarricade (SDG.Unturned.BarricadeRegion region, System.Guid assetGuid, System.Byte[] state, UnityEngine.Vector3 point, System.Byte angle_x, System.Byte angle_y, System.Byte angle_z, System.Byte hp, System.UInt64 owner, System.UInt64 group, SDG.Unturned.NetId netId) [0x004ec] in <e722b749a4ba496696325f210b77d83c>:0 
> [2022-05-06 04:54:46] Context "Barricade" missing asset 493e7262ce3e3c9e6f6b732074206c6f
> [2022-05-06 04:54:46] Context "Barricade" missing asset 2e756f796f6620722d2053743c62723e
> [2022-05-06 04:54:46] Context "Barricade" missing asset 90000136e1018bcc10f6160001809547
> [2022-05-06 04:54:46] Context "Barricade" missing asset ecf2de308ec42fa86401001014876900
> [2022-05-06 04:54:46] Context "Barricade" missing asset 096ce981e38ef0280100100187870064
> [2022-05-06 04:54:46] Context "Barricade" missing asset 0000045c00000000ff1cb4470b170000
> [2022-05-06 04:54:46] Context "Barricade" missing asset 01640087ecf087ace051050000100120
> [2022-05-06 04:54:46] Context "Barricade" missing asset 016400878ce687d805ec1500001001dc
> [2022-05-06 04:54:46] Context "Barricade" missing asset 0164004bece9872a05ec1500001001dc
> [2022-05-06 04:54:46] Context "Barricade" missing asset 0164002dece487a8e051050000100120
> [2022-05-06 04:54:46] Context "Barricade" missing asset 0164004b8ceb875805ec1500001001dc
> [2022-05-06 04:54:46] Context "Barricade" missing asset 016400200cff87b484ac0b0000100120
> [2022-05-06 04:54:47] Kicked for sending invalid asset guid: 016400200cff87b484ac0b0000100120
> [2022-05-06 04:54:47] Shutting down BattlEye client
> [2022-05-06 04:54:47] BattlEye client shutdown result: True
> [2022-05-06 04:54:47] Client disconnect from 2528684751 result: True
> [2022-05-06 04:54:47] Cancelled auth ticket
> [2022-05-06 04:54:47] Returning to main menu
> [2022-05-06 04:54:47] Disconnected

**Comment by SDGNelson** [comment]
Thanks for the log! It looks like the sign "state" array is empty when it should always contain at least the owner information. The whole opaque "state" thing shared by barricades/structures/items really needs a rewrite and to be separated from savedata, sigh. Do any of the plugins that were on your server spawn barricades? My guess is that one of them spawned the sign without initializing the state. If that is the case there should also be a similar exception in your server log. I will see about better handling barricade/structure spawn exceptions on the server to delete the item rather than replicating to clients.
