### ISSUE TITLE
[Feature Request] Interactability triggered upon collision with a box collider.

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#3164]
Hello,

I would like to bring to your attention a suggestion that I think would majorly improve the possibilities of modding both in single player and multiplayer, and as far as I know, will not take long to implement.

Essentially, it is the same normal interactability component that is present in normal objects, but it can only be triggered via walking into a specified box collider. (Set through Istrigger in Unity).

Why should this be added?
- Removes the unnecessary collision_teleport component from Unity.
- Allows for incredibly complex chaining via event hooks & flags, giving possibility to create full animated cutscenes
- Opens many doors to modders for sharing components server wide without the use of third party plugins.

How should this be added?

While I have certainly no knowledge of the inner workings of your game code, my assumption would be something like this:
Since Interactibility has both Quest and Binary_State as the two possible states, making a new Interactibility subclass "Collision" would be the easiest choice.
Conditions would remain the same as all objects.
Interactibility_Conditions can be completely ignored/disabled as they are the same as normal Conditions.
To make an Interactibility Collisions object, all that is needed is to assign a box collider with "Istrigger" enabled in unity. 

Thank you, Dallas.

**Comment by GazziFX** [comment]
Im confused isnt it CollisionEventHook?

**Comment by DrDallas1** [comment]
I am not referring to the collision event hook, I am referring to the in game reward system (NPC rewards)

**Comment by SDGNelson** [comment]
So when the player touches the trigger it applies quest rewards if quest conditions match? That would definitely make a lot of sense to add, except that it is unfortunate that the colliders are not visible in the editor - it would be nice to configure the quest stuff on a trigger created in the level editor.

**Comment by DrDallas1** [comment]
I think colliders not being visible in the editor is a fine sacrifice, as it would not be hard to match it to an exact position via unity anyway. What you suggested is a good idea - but I feel like it will require too much time to add to have the same level of functionality as the Interactibility component. Making it through an object will allow for much higher degree of variability both through conditions and rewards.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
