### ISSUE TITLE
Airdrop animation does not match actual Carepackage position

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#3166]
In server. (works well in Singleplayer mode)

https://user-images.githubusercontent.com/64722485/167108235-b054a762-5bca-4665-8efa-c9dc7e7ea586.mp4

**Comment by SDGNelson** [comment]
Sorry about this - I have been planning a projectile rewrite that will properly fix this but in the meantime I should really add a placeholder fix.

**Comment by SDGNelson** [comment]
Should be (fixed?) better in the next update!
