### ISSUE TITLE
map not working

### ISSUE THREAD

**Issue by dtank09** [SmartlyDressedGames/Unturned-3.x-Community#3168]
Hello Nelson I have been trying to join a server and it keeps saying the server is running a map I do not have. I have verified my files, uninstalled my workshop mods, deleted and reinstalled unturned and it still won't work if you can help me I would appreciate it. thanks

**Comment by Akulation** [comment]
to add on to this, the server is working for anyone else who tries.
the map is a custom workshop map.

**Comment by SDGNelson** [comment]
Sorry for the trouble! Does that map show up in the Singleplayer menu? If you look in the Menu > Workshop > Manage Subscriptions menu is that map disabled? Also, if you were subscribed to it in the past and are currently unsubscribed then technically the "disabled" option still applies.

**Comment by dtank09** [comment]
Ok thank you Nelson when I am next on I will try
