### ISSUE TITLE
Clicking Bug

### ISSUE THREAD

**Issue by FengAndHive** [SmartlyDressedGames/Unturned-3.x-Community#3169]
So from 2 days ago something started my ingame clicks were going off countless times if i click on something and move my mouse it just keeps clicking in a really fast speed. I dont know whats causing it but it is ingame and in the menu i tried redownloading the game my mods checking the files but nothing has changed and it is certainly not my mouse since every other game and every other site on my pc is just fine.

Please if anyone knows how to fix this tell me i cannot play like this im not even able to equip items anymore and it seems like i cant do anything about it either.

**Comment by SDGNelson** [comment]
Sorry for the trouble! So for example if you right-click an item in your inventory it immediately clicks again preventing you from doing anything? If you have a fancy mouse maybe there is accidentally a macro or auto-click configured specifically for Unturned?

**Comment by FengAndHive** [comment]
> 
Thats not it my mouse doesnt have any macros its aa normal mouse it cant do anything it doesnt even have one of those fancy apps where you can configurate my cps its.
I also dont have macros an autoclicker or cheats thats why it is so complicated and i dont get it.
For the example if i click something it keeps clicking so fast that not even the Equip button can come for a second this is what is preventing me from doing anything also its only buttons that have to be pressed for example if i try to do the "emotes" like resting it punches its ingame and it is in menu.

**Comment by FengAndHive** [comment]
Addition: It seems like this bug is affecting RPG games from my pc but not steam games so it is something to do with my pc and not a unturned bug directly. 
Well thats what i am guessing

**Comment by SDGNelson** [comment]
Sorry, if it is happening with other games too that does seem to indicate it is not an Unturned bug. Aside from the macro/clickers nothing comes to mind, but best wishes and good luck to you troubleshooting the issue online!
