### ISSUE TITLE
Animal health points

### ISSUE THREAD

**Issue by DevInc0** [SmartlyDressedGames/Unturned-3.x-Community#3170]
There is a problem. I can't find a legal way (without the help of System.Reflection) to find out the current health of an animal. 

```class Animal``` has a private field called ```health```. 
But there is neither public property nor public method (like ```public float GetHealth()``` in ```class Zombie```).

It would be great if you add such a property or method, or suggest how I can find out the health of an animal in another way.

**Comment by GazziFX** [comment]
???
![image](https://user-images.githubusercontent.com/43498426/168143999-619a1bf7-69b7-4c91-a426-75afd2d2c162.png)

**Comment by DevInc0** [comment]
Ah, my bad. Used the old version. Thank you for help. I'll be more careful next time.
