### ISSUE TITLE
Make the Teleport command accent insensitive

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#3171]
Figured this is something I should've suggested before Rio released, but if possible the /Teleport command should be improved to also work when typing out a location name without accents.

i.e.: in Rio, I can't teleport to the city of Niterói if I type only "Niteroi". Either I remove the accent in the location node, or the player has to type the accent in

it's a pretty minor change but I suppose it would be a nice and convenient fix

**Comment by SDGNelson** [comment]
IIRC this was discussed a few other places at the time - good option would be to put the accent in the map's translation file
