### ISSUE TITLE
Maxskills and Execute config

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#3172]
Maxskills on commands bypass map skill limit, most if not all servers have admin with some type of maxskills plugin, its practically imposible to check on no skill drop servers, i want to desing the pvp on my rp without crosshair and high recoil but this ruins it for the few admins with maxskills because you need to die on 0.0 loss config to disable maxskills

If im using pterodactyl on ubuntu 20.04 and dont find Execute.config, i need to create it? Where?
I want to try “misc.dont_enable_this true” 
It reduces server load and rubber band on new physics?

**Comment by GazziFX** [comment]
> If im using pterodactyl on ubuntu 20.04 and dont find Execute.config, i need to create it? Where? I want to try “misc.dont_enable_this true” It reduces server load and rubber band on new physics?

`Execute.config` and devkit terminal was removed and `PlayerMovement.forceTrustClient` wont work with new physics

**Comment by SDGNelson** [comment]
Hmm for max skills some of the plugin-exposed code does not respect level restrictions, but I am not sure whether it should or not.

As for misc.dont_enable_this: since it was the only useful devkit terminal option it was moved to a command-line flag: `-ForceTrustClient`
