### ISSUE TITLE
Every landscape made with devkit editor disappeared

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#3173]
Not sure if its intentional, but every landscape made out of map bounds just disappeared. Is there any way to restore it?

**Comment by SDGNelson** [comment]
The terrains on vanilla maps were using devkit landscape already, so I wonder did you have both old and new terrain on your map simultaneously? Like the center terrain was regular editor (old) and you had created tiles out-of-bounds with devkit (new)? If so, the new update would be thinking that your map does not have landscape and auto-upgrade. The easiest way to fix is not exactly ideal but would be to copy the "tiles" portion of the landscape in Level.hierarchy, remove that landscape, then accept the auto-conversion and append your pre-conversion tiles list.

**Comment by UsernameIsUnavailible** [comment]
Got the same, All my terrain dissapeared from my maps and I'm unable to fix this as the new interface is extremely difficult & unfriendly for any map creator that does not know how it works or is used to the good interface (aka the old one)

**Comment by baranmod** [comment]
Sorry, could you be a bit more specific?

I tried to do it, but once I did it - landscapes outside map appeared but one tile (landscape) from inside map bounds disappeared. What could went wrong?

**Comment by SDGNelson** [comment]
I guess before being more-specific: was my guess correct i.e. is that the situation? (mix of old terrain with new)

**Comment by baranmod** [comment]
yea. I actually managed to fix that. New issue is with terrain holes. Where do I find this hole mask brush?

**Comment by SDGNelson** [comment]
Glad to hear you got it working! You can paint holes with Materials > Cut [R] tool. Holding shift restores cut terrain.

**Comment by baranmod** [comment]
awesome, thanks. The new tool looks really easy to use by the way. I suppose, hole volumes added through devkit can be removed now?

**Comment by SDGNelson** [comment]
Thanks! Yes: I removed all hole volumes from Germany, Hawaii, and Greece. Would recommend removing them because that way the game does not need to waste time converting them during load.
