### ISSUE TITLE
New map tools are extremely beginner unfriendly and experienced map creators IF you never learned/used them

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3174]
The new tools are garbage, They are extremely difficult and give no visual interface at all to tweak your tools. Keep devkit & nifty stuff in the seperate one & keep simple tools in the legacy editior I beg.

This update made me consider quitting unturned already...

**Comment by SDGNelson** [comment]
What do you mean by "no visual interface"?
Which aspect of the tools are you having trouble with?

**Comment by UsernameIsUnavailible** [comment]
Pretty much any tool, The old (legacy) editior had easy & quick to use tools, They had sliding bars to have your terrain & materials correct. 

I don't know why you removed the old editior and now "forcing" people to use devkit, Wouldn't it be better to pretty much keep legacy, & make the new/updated one the devkit variant? I'd then be able to make maps (and a ton more people) back with easy tools, even though I'd be unable to add in holevolumes as I'm used to the old devkit, I never used devkit for anything else as I found all tools on the legacy one.

Might be a messy text bubble but I'm not native english speaker.

**Comment by UsernameIsUnavailible** [comment]
Its just that if you've been editing maps for well over 3.5k hours or around 3-4 years and suddenly get forced to use new tools its depressing & makes people/me want to quit

**Comment by SDGNelson** [comment]
You can still type values into the text fields if you want, but as for the sliders the newer tools have hotkeys which are much faster. For example if you want to resize your brush you just hold 'B' and drag the mouse. This way the brush is exactly the size you need.

**Comment by SDGNelson** [comment]
Sorry but in general the newer tools are objectively better. As much as possible I adapted the settings to the style of the old tools. Everything possible with the old tools should be possible with then newer tools, and if there is something missing it can be added. For example in the Heights "raise/lower" mode set Brush Falloff to 1 and it behaves/looks exactly the same as the old tool.

**Comment by UsernameIsUnavailible** [comment]
Guess I'll quit making maps then
