### ISSUE TITLE
[Question] How to import custom materials into Tiles

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3179]
Hi, the latest update has removed custom materials from a map I am working on and under the new Tiles tab it says "Asset GUID" which is how I presume I am meant to import them but I have no idea how to get the GUID of the custom materials. Cheers.

**Comment by DMJaxun** [comment]
Rephrasing since I figured out each material has its own GUID now. How do we create a GUID for each material exactly?

**Comment by DMJaxun** [comment]
Nevermind, figured out how to do it but I must say it is quite an irritating addition.

**Comment by SDGNelson** [comment]
Sorry for the hassle!

If any of the textures in your Materials.unity3d file were from an official or already-converted map like Hawaii, Greece, PEI, etc this should thankfully be an easy fix:
1. Open the Tiles menu in the level editor
2. Select a layer in the bottom-right and then a new material from the Assets list
3. Click "Copy Layers to All Tiles" to apply the new materials to the entire level

If you had custom textures in your Materials.unity3d file then there are unfortunately more steps. On the bright side, once finished you can use different materials on each tile - for example Germany has the quarry rocks material only around the quarry. In retrospect I should have recorded the process of converting Greece's terrain Materials.unity3d to new material assets. D'oh.

Firstly the Materials.unity3d file needs to be converted to the "master bundle" format. The easiest option, especially if you do not still have the Unity project, is to just rename the file to something like "MyCustomMapMaterials.masterbundle" and create a MasterBundle.dat file, then move them into your map's Bundles folder. More info here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/AssetBundles.md

Secondly now you can create a Landscape Material Asset in your map's Bundles folder for each custom material on your map. The easiest way would be to copy one of the materials from Unturned's Bundles/Assets/Landscapes/Materials folder, change the GUID to a new one from https://guidgenerator.com/, and then update the "Texture" path to your master bundle and texture name.

**Comment by DMJaxun** [comment]
Hi, thank you. I set up the masterbundle and folders fine but the game is having trouble recognising the texture files and instead replacing them with pure black. Any idea what could be causing this?

**Comment by SDGNelson** [comment]
Sounds like you made good progress! So to double-check: your custom material asset is listed in the material editor, but when you paint it on the ground the texture is black? My guess is most likely a mixup with the Asset_Prefix in MasterBundle.dat. For example here is an overly verbose description of how I would reverse-engineer the very old PEI Materials.unity3d file:
1. Maybe I cannot remember exactly what the file names were. I can open Materials.unity3d in a text editor like VS Code and Ctrl+F search for "assets/". It looks like one of the file names was: "assets/game/bundles/terrain/devtest/materialspei_current_tweaked_alpha/grass.png"
2. All Unity files are in an "assets/" subfolder. The Assets_Prefix in MasterBundle.dat is a helper to avoid typing this same prefix over and over. If your textures are in a folder like "assets/myterrain" then you could set the prefix to this to make the path shorter, or you should just set it to "assets/".
3. In your Landscape Material Asset file ensure the "Texture" "Name" property matches your asset bundle name. For example the core vanilla asset bundle name is "core.masterbundle", but yours might be something like "myterrainmaterials.masterbundle". Then set the "Texture" "Path" to the file path relative to the Assets_Prefix. For example if I had set Assets_Prefix to "assets/game/bundles/terrain" then I could set path to "devtest/materialspei_current_tweaked_alpha/grass.png"

**Comment by DMJaxun** [comment]
Hi, instead of converting the original unity3d file I made it from scratch with the images. In Unity I have put my images under Assets>Aqaba>Terrain and I have masterbundled it as aqaba.masterbundle. I will send the Masterbundle.dat and Landscape Material Asset file examples below.

MasterBundle.dat:

Asset_Bundle_Name aqaba.masterbundle


Asset_Prefix Assets/Aqaba


Asset_Bundle_Version 3


Beach.dat:

"Metadata"
{
	"GUID" "8459db7a535d4efba6d54e3179a86f20"
	"Type" "SDG.Unturned.LandscapeMaterialAsset, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
}
"Asset"
{
	"ID" "0"
	"Texture"
	{
		"Name" "aqaba.masterbundle"
		"Path" "Terrain/Beach.png"
	}
	"Mask"
	{
		"Name" ""
		"Path" ""
	}
	"Physics_Material" "Concrete_Static"
}

I have talked to other members trying to fix this same issue on the Unturned Official discord, I will pass any information on to them and anyone else who needs help. Cheers.

**Comment by DMJaxun** [comment]
![image](https://user-images.githubusercontent.com/66274985/168404091-a9190b62-9ce7-4fa5-9834-b0c059dd9eae.png)
![image](https://user-images.githubusercontent.com/66274985/168404104-7c8347c4-5cf3-43a3-850d-7a06fdad6645.png)

**Comment by SDGNelson** [comment]
Hmm that all looks correct to me... One "gotcha" that comes to mind is Unity currently requires the texture to marked "CPU read/write enabled" because it generates the low-LOD texture on the CPU - I think this may have been fixed in the next LTS version (2019 to 2020) and hope to upgrade soon. With an old Materials.unity3d file they already would have CPU read/write enabled, but for a new asset bundle maybe it is not enabled. Otherwise could you upload your aqaba.masterbundle file please and I will try loading it up?

**Comment by DMJaxun** [comment]
Thanks, someone else who is working on it fixed the problem while I was asleep but I talked to other people who got it to work and people who didn't. It worked for people on 2019LTS but not for 2018LTS so I think that is indeed the root of the issue.

**Comment by DMJaxun** [comment]
^ That or you are forced to use Assets/Landscapes/Materials as the root
