### ISSUE TITLE
NPC shop list sorting bug?

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#318]
Not sure if this is a bug or made on some purpose, but shouldn't items in npc shop be listed as they are listed on asset config file? Now they are listed alphabetically, doesn't matter how its listed on config file.

**Comment by SDGNelson** [comment]
They're intentionally sorted in the UI (VendorItemNameAscendingComparator) because I figure in most cases you're just adding items to the end of the list. Do you think an option to disable sorting should be added to the vendor asset?

**Comment by baranmod** [comment]
yeah, I believe its must-to-do thing as I am probably not the only one who would like to implant some better hierarchy to shop which basically helps to improve overall buying/selling flow for players.

**Comment by SDGNelson** [comment]
Added Disable_Sorting option for vendor assets in the next update 👍
