### ISSUE TITLE
map materials broken

### ISSUE THREAD

**Issue by ElRicki** [SmartlyDressedGames/Unturned-3.x-Community#3180]
what tf happend
![image](https://user-images.githubusercontent.com/75626024/168367754-08ec4e40-423f-417a-9595-4e0aa0151538.png)

**Comment by ElRicki** [comment]
how to fix custom materials I don't have the unity project anymore

**Comment by DMJaxun** [comment]
This is due to Legacy Terrain being ported to the Devkit Terrain, you need GUIDs for each material now but getting it set up is a pain. Waiting on Nelson.

**Comment by ElRicki** [comment]
So there is no way to recover old materials? or any way to fix mine without having to paint all again @SDGNelson

**Comment by SDGNelson** [comment]
Sorry for the hassle! Unfortunately old maps only had the name of the material in Materials.unity3d as a point of reference for conversion, so if Materials.unity3d did not match one of the official (or Greece) maps and the name did not match any vanilla materials it used primary colors as a fallback.

Fortunately this is an easy fix in the editor! If you open the "Tiles" menu and click "Fallback_Red" you can choose a replacement material from the list on the right. Once you are happy with the materials you can click "Copy Layers to All Tiles" to all those settings to the entire level.
