### ISSUE TITLE
[Bug] Loading Screen Shifting

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3181]
When loading a map, the loading screen picture shifts offscreen as the progress bar goes up.
![image](https://user-images.githubusercontent.com/66274985/168378711-62b9e1a4-33a6-4eb5-b775-156b9f44bcdd.png)

**Comment by GazziFX** [comment]
Its new feature

**Comment by SDGNelson** [comment]
Hmm it does look like it is moving further left than it should 😕 thanks for the report!

**Comment by SDGNelson** [comment]
For the meantime I disabled moving the loading screen because it does not work well enough until loading is better time-sliced and/or made asynchronous.
