### ISSUE TITLE
Disable GeForce Experience and amd / similar filters

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#3182]
Example on Pei:
![image](https://user-images.githubusercontent.com/80723434/168380311-971f0c62-224a-40e9-a65d-1ddd457b8f82.png)
![image](https://user-images.githubusercontent.com/80723434/168380355-f9529180-0b4d-4e5a-851b-e536ffd8c41b.png)

Lots of games dont allow filters, to nerf the day in night third person im puting midnight on complete darkness, on South America the filters are 99% used for seeing on the night without first person nightvision, busted if we consider the zoomed in 0 recoil third person that i despise
Not entirely viable since the darkness is annoying and anticlimactic, i need to spam lights everywhere

![image](https://user-images.githubusercontent.com/80723434/168379169-650f99ad-fd85-4493-bef4-ba96f1edb582.png)
![image](https://user-images.githubusercontent.com/80723434/168379537-7dedc9ef-19f9-46e2-b9d2-d731a47908fa.png)

**Comment by SDGNelson** [comment]
Even if we are able to get in contact with Nvidia and Amd to disable this for Unturned it would unfortunately still be possible by increasing monitor gamma. The only non-bypassable method would be completely black pixels as you found with your map. I think the best compromise might be for nights to be a bit brighter, but to have more end-game areas on maps that are fully dark.
