### ISSUE TITLE
Materials - Cut

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3183]
Where put?

How to fill it
![image](https://user-images.githubusercontent.com/65422793/168383897-c9fac477-389d-40de-8fbf-53210980ef13.png)

**Comment by SDGNelson** [comment]
You can hold Left Shift and click to fill the hole.

**Comment by FANYPLAYRU** [comment]
Oh thanks

**Comment by FANYPLAYRU** [comment]
This usable or devkit LandscapeHoleVolume?

**Comment by SDGNelson** [comment]
This is the replacement for LandscapeHoleVolume, yes.
