### ISSUE TITLE
[Bug] Disconnecting time

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3184]
![image](https://user-images.githubusercontent.com/65422793/168394102-36ad1e92-ac27-4fc2-ac39-fa91f757d515.png)

Map Loading

**Comment by SDGNelson** [comment]
Is your server on the .1 patch? It released earlier this afternoon and fixed a bug with dedicated server not loading out-of-bounds terrain.

**Comment by FANYPLAYRU** [comment]
Client and Server on .1 version

**Comment by SDGNelson** [comment]
In that case: could you send me the Client.log file from Unturned/Logs and the Server_ (id) .log file from U3DS/Logs please?

**Comment by FANYPLAYRU** [comment]
i lost logs file

**Comment by SDGNelson** [comment]
Are players still losing connection to the server like that still? If not, then I guess it was fixed with that bug fix in the .1 patch. If you are still losing connection then you can send me the log file after it happens again.

**Comment by aman7** [comment]
> Idk. Game crashed in this momnet

is it still happening for you?
