### ISSUE TITLE
Material problems

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3187]
Hello, after the last update all materials are broken. Any easy way to fix it?
![unknown](https://user-images.githubusercontent.com/43903270/168429722-568b62de-350b-4648-8567-c2b4047b148f.png)

**Comment by SDGNelson** [comment]
Sorry for the hassle! Unfortunately old maps only had the name of the material in Materials.unity3d as a point of reference for conversion, so if Materials.unity3d did not match one of the official (or Greece) maps and the name did not match any vanilla materials it used primary colors as a fallback.

Fortunately this is an easy fix in the editor! If you open the "Tiles" menu and click "Fallback_Red" you can choose a replacement material from the list on the right. Once you are happy with the materials you can click "Copy Layers to All Tiles" to all those settings to the entire level.
