### ISSUE TITLE
Rich Chat glitch

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#319]
![image](https://user-images.githubusercontent.com/1809172/40976266-4530e29c-68d6-11e8-83df-1b5783d49321.png)

I think its related to rich text which is too long.
Not sure on how to reproduce this exactly, but its obviously something not meant to happen.

**Comment by Trojaner25** [comment]
I suggest that max chat length should not include rich text formatting tags, like <color> etc. It should only count the rendered visible characters.

**Comment by SDGNelson** [comment]
Classic edge case kind of thing 😋 
You're probably right that the tags are getting cut off. I'll adjust the chat to be able to send longer text, and only limit the client->server message length.

**Comment by SDGNelson** [comment]
After investigating a bit I think the actual issue is that the C in <Color is capitalized. I'll get that fixed up.
