### ISSUE TITLE
[Bug] Weird spacing between categories in the game's control screen.

### ISSUE THREAD

**Issue by XanderCodes** [SmartlyDressedGames/Unturned-3.x-Community#3191]
Hiya. Just discovered this weird issue with the game's controls menu where the spacing of the control categories titles, and the actual buttons is a little wacky, making it look like the titles are buttons: 

![image](https://user-images.githubusercontent.com/19631080/168477398-1a855876-435e-4347-ac35-b2855e53377a.png)

**Comment by SDGNelson** [comment]
Oops! Thanks for the report, I will get that fixed for the next update. Sooner or later I want to improve the organization of this menu as well.

**Comment by XanderCodes** [comment]
No worries at all!

**Comment by SDGNelson** [comment]
My bad: I forgot to take care of this for today's update. Still on the to-do.

**Comment by SDGNelson** [comment]
Should be fixed in the .1 patch shortly!
