### ISSUE TITLE
Return to Map editor comfortable software

### ISSUE THREAD

**Issue by Raptor-UA** [SmartlyDressedGames/Unturned-3.x-Community#3192]
Return to Map editor comfortable software , because I don't understand how to use it . And where are the trees ? I hope next update fix all problems and do map editor more comfortable . Good luck !

**Comment by SDGNelson** [comment]
Sorry for the trouble! I have now published an FAQ to hopefully clear up any issues, but feel free to ask specific questions as well: https://gist.github.com/SDGNelson/dcd967e7ca1a0db7e15cce258ed7e401
