### ISSUE TITLE
Scopes and Gunplay

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#3193]
Figured I'd make this since the current trend seems to be making scope quality off unusable and forcing scope qual on, not something I'm completely against since it is an undeniable advantage but mainly caused by scope quality on feeling absolutely terrible to play with coming from any fps game.

Setting Additions
ADS Sens Multiplier - New options are fine but a lot more universal with a general ads sens scale. Separate option for 1 zoom and 1> zoom sights. 1 zoom sights are way too fast being 1:1 with hip and anything above feels way too slow with the current options.

Changes
Scope Qual Off - Change to work all sights as holographic sight and zoom the entire screen in rather than blackout and zoom making it work like other fps games such as Warzone and Apex. ADS fov preference changes viewmodel alone without touching effective zoom. Effectively makes it scope quality on without the dual render fps decrease.
Scope Qual On - Same dual rendered scopes with the additional full screen zoom in, possibly to a lesser extent.
General Changes -
- Arm and gun sway while moving heavily reduced
- Reduce visual recoil and gun shake

Jumping - Few ways to go being either forced unscope while airborne, gun pointing to ground or just having it not move.

**Comment by SDGNelson** [comment]
Out of curiosity why do you want "Scope Qual On - Same dual rendered scopes with the additional full screen zoom in, possibly to a lesser extent." - the primary benefit of dual-render scopes is that only the optic itself is zoomed in, whereas without dual-render the entire view has to be zoomed in.

**Comment by Kentoraketti** [comment]
That's how Tarkov does it but yeah it's eh probably fine to leave it alone. Still feels extremely weird playing qual on without setting independent ads sens sliders
