### ISSUE TITLE
[Bug?] NPC not being able to sell more than 35-50 vehicles.

### ISSUE THREAD

**Issue by JuicyNuts** [SmartlyDressedGames/Unturned-3.x-Community#3194]
Hey, so when I put more than 35-50 vehicles in vendor, the dialogue doesn't work. What I mean is that if I exceed the limit, the dialogue won't work, it'll just leave the NPC. Any idea on what to do? And is it possible to just make it so it can sell more vehicles?

**Comment by JuicyNuts** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8701693/Client.log)

Not sure if this really shows anything. And yes, basically when I click it, instead of opening the vendor menu it just closes dialogue.

**Comment by SDGNelson** [comment]
Today's update adds a more helpful error message, and will use the player's location as a spawn position (same way as /vehicle command) if invalid.
