### ISSUE TITLE
[Feature Request] Clothing Degrade Timer

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#3195]
Hello!

I am hard at work on creating a large scale update to my Fallout Power Armor sets, and something that I am constantly running into the issue of is that the armors carry the constant struggle of being extremely overpowered and extremely underpowered, and not being very accurate to the material at the source.

To combat this, I was wondering if a few toggleable features could be added to make the power armor function more as one would expect.

Timed_Wear : This would essentially make the clothing operate like a battery meter, having the armor drop by 1 percent every X amount of time, whatever the value for that would be, to make armor have a drain to it similar to how armor within Fallout 4 needs to be kept up to power using fusion cores.

Disable_Damage_Wear : This would make it so that forms of taking damage do not decrease the armor value of the clothing, similar to how easy mode treats clothing but per item and working across all difficulties.

Always_Max_Armor : This would make the armor protect for the maximum value, whatever is normally designated in the dat file, regardless of the percent of the armor, this would be great for preventing the issue of people using low damage, high firerate weapons to melt the armor into being useless within seconds due to the low damage players take while within the armor. 

Speed_At_Zero : This would function identically to the speed method already within the game, but only activate at 0 percent armor, functioning as an "Out of Power" state for the armor.

These features are critical to me in getting the tactile feel of power the armor gives and making them harder to simply cheese around with rapid fire weaponry and give the armor the true protection that it deserves to have while still functioning as a normal piece of Unturned clothing. Please consider adding any of these that you would be able as I am very passionate about this project and I would love for it to be the best that it could be.

**Comment by surv0013** [comment]
It seems to me that instead of a thousand of these features that complicate the network code on vanilla servers where they are not used, it is better to finally add scripts that allow modders to do whatever comes to their mind.

**Comment by Dumfoozler** [comment]
Until that happens, I have no choice but to request what I need to make my creations work directly

**Comment by GazziFX** [comment]
> It seems to me that instead of a thousand of these features that complicate the network code on vanilla servers where they are not used, it is better to finally add scripts that allow modders to do whatever comes to their mind.

I want some interpreted lang like lua or python on clientside but it will never happen

**Comment by Gamingtoday093** [comment]
This is very possible with Plugins! Essentially just do it yourself.

**Comment by Dumfoozler** [comment]
> 

No functionality in singleplayer/non-plugin servers is sad

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
