### ISSUE TITLE
Kick after giving kit

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3197]
![image](https://user-images.githubusercontent.com/43498426/169576361-0612bf15-f6a5-4413-b7f3-6b62cb16fce3.png)

**Comment by Bradler26** [comment]
Can confirm I get the same. I could move the rate limit up but I would like to avoid that because its clearly there to improve performance. Any suggestions?

**Comment by SDGNelson** [comment]
Copying text from patch notes:

This highlighted a flaw in the equipment system from back when integrity checks were first added to equipped items. For the meantime I have increased the equipment rate limits significantly as a temporary workaround, but for the next major update I will properly resolve this flaw. If you experience other incorrect rate limit kicks please let me know and I will get them fixed, and as a temporary measure it is also possible to raise the Rate_Limit_Kick_Threshold in Config.json.
