### ISSUE TITLE
Weird game version

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3198]
![image](https://user-images.githubusercontent.com/43498426/169576794-f973f50b-32a3-48e7-b0c4-3f56d4dc398e.png)

**Comment by SDGNelson** [comment]
Sorry, as mentioned in #3196 it looks like somehow the wrong branch got set as released! This has now been corrected, and I am going to check into what happened causing this and make sure the release tools are improved to ensure it does not happen again.
