### ISSUE TITLE
Shark-Tooth Sword Animation Bug 

### ISSUE THREAD

**Issue by xdlewisdx** [SmartlyDressedGames/Unturned-3.x-Community#32]
Does not hold item properly and doesn't make swing animation 

Found by: BLACC 10Penny

**Comment by V1CeNtE** [comment]
is this? https://imgur.com/a/ww9hu

**Comment by xdlewisdx** [comment]
yes, also doesn't swing

**Comment by SDGNelson** [comment]
Forwarding to Hawaii team.
