### ISSUE TITLE
WorkshopDownloadIDs.json doesn't work for maps?

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#320]
Inserted map workshop id to WorkshopDownloadIDs.json, map downloaded to Workshop/Steam/Content/304930. Then loaded server but it loads PEI map for some reason. Am I doing something wrong or its just not for maps?

**Comment by SDGNelson** [comment]
Good timing actually. EZ reported a bug with it last week which is fixed in the coming patch!
