### ISSUE TITLE
After update some peoples cant join on server with problem:

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3204]
![image](https://user-images.githubusercontent.com/39222548/169578780-5292e54d-4cd2-472e-a9ea-32dd3bbcf12c.png)

**Comment by KeriDGaming** [comment]
Same.
![20220520133845_1](https://user-images.githubusercontent.com/103531662/169588126-71cc49e3-59d4-423e-af1d-0f6e777d3bc2.jpg)
