### ISSUE TITLE
Dear, greatly respected, Nelsuck, please let us sleep in peace.

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3208]
Please dear Nelsan(sorru i am russian and can mady errors in text) i use google translutor!
Could you leave your wonderful and wonderful game without your rash and quickly made decisions, because it turns into some kind of cringe, with each update of your wonderful game, we are not preparing for something good, but on the contrary, all the community think: "What Will he break this time?" 
We perfectly understand how difficult it is to make updates in one, but please, if you break something, either roll the game back, or fix it right away, and not in a year or two, we love you very much and want to expect something good from your updates , kind, adding something new, and not breaking the fcking game!😀😀😀
Don't make us cry!!!😅😅😅😅

**Comment by negrifelipe** [comment]
Stop posting shit ;) good luck with someone understanding your translutor

**Comment by QERT2002** [comment]
Its not a "shit", nelson ruin a game after next update.
Nelson ruins the game every update, and then fixes his own bugs for 2 years, no one needed a new kickak RPC system, but instead of a normal map editor, or optimization, or fixing any bugs, instead of adding what people have been asking for many years, just breaks his own game and that's a fact

**Comment by DMJaxun** [comment]
Mald

**Comment by QERT2002** [comment]
> Mald

Where's your server maaaaaaan??? Why it sleep for 2 days?????

**Comment by SDGNelson** [comment]
¯\\\_(ツ)_/¯

Your frustrations are understandable, but you have spammed a bunch of topics and I do not want to deal with your bad attitude, so I am blocking you from the SDG repo for 30 days. In some ways it is an accomplishment considering there are a bunch of known cheat developers who post here and are not blocked 🙄
