### ISSUE TITLE
[Minor Bug] Font Color collides with Interface Foreground Color Blue Slider

### ISSUE THREAD

**Issue by KodakDolph** [SmartlyDressedGames/Unturned-3.x-Community#3209]
![githubissue](https://user-images.githubusercontent.com/105953666/169625761-5bf550e7-1677-47bd-ba7d-d71059d36189.png)

Unable to adjust blue sliding

**Comment by SDGNelson** [comment]
Thanks for the report! Sorry about that, will fix for the next update.

**Comment by KodakDolph** [comment]
👍 Thanks Nelson!
