### ISSUE TITLE
Server doesn't appear on server browser list after most restarts

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#321]
This bug appeared pretty long time ago and its still happening which is super annoying. Basically, you usually need to make like 10 restarts for server to appear on browser. And it doesn't appear only on "internet" tab. And sometimes it appear on it just fine (after first restart/launch).

OS: windows, there are definitely no bot related plugins etc. And its happening for all 4 servers I run.

**Comment by SDGNelson** [comment]
Is this an immediate thing, or even after waiting a bit? When I was first implementing the GS API I found it took a little time to show up.

One other thing that comes to mind: are there any errors in your log about your tags/desc? For example if your description is longer than 64 characters it won't register properly.

**Comment by baranmod** [comment]
if it appears on list it appears practically instantly. And if it doesn't - even 10 or more minutes later - its still not on the list. And only way to put it on list is to make like 4-5 more restarts (sometimes even more)

There are no errors related to tags/description, nor anything else.

**Comment by SDGNelson** [comment]
Are you able to connect to the server by IP:port when it doesn't register?

**Comment by baranmod** [comment]
Yeah, as I mentioned in my previous message: servers functioning as it should, all works and it appears on all other tabs (history, favorites..) and I also can connect with ip/port. It just doesn't appear on internet tab

**Comment by JustOneMoreBlock** [comment]
@baranmod Are you using different ports and not using the `bind` option? Because this feature has apparently been removed.

**Comment by baranmod** [comment]
@JustOneMoreBlock I am actually using different ports and bind option

**Comment by JustOneMoreBlock** [comment]
Remove the `bind` option providing it's the same IP address and your issue should be resolved.

Unturned no longer supports dedicated IPs anymore.

**Comment by baranmod** [comment]
Sadly, it didn't solve the issue..

**Comment by SDGNelson** [comment]
Are your servers 3 ports apart? The first port should be 27015, second should be 27018, etc

**Comment by baranmod** [comment]
yeah, all good in ports too

**Comment by SDGNelson** [comment]
I'm not sure then, other servers seem to work fine
