### ISSUE TITLE
[Bug Report/Feature Request] Skin Renders on Unused Pixels

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#3210]
![image](https://user-images.githubusercontent.com/76188059/169659247-76b6fae3-fb17-4b47-8cdd-54b84b937b4e.png)
![image](https://user-images.githubusercontent.com/76188059/169659845-e1d4fa86-0de1-41bf-9364-52c34a5204f5.png)

Image above for better explanation. Attempting to do a mesh replacement that does not use the override to allow for it to be a shirt with extra bits hanging off. However, I'm running into the issue of transparents that are intended to be cut out instead fully blocked in with the skin color. the only thing that needs to be done to fix it is for the blank parts of the unturned mesh (Those that dont have any form of texture on them, AKA the bottom right of the texture) to not be rendered with the skin color of the player, or to allow it to cutout so that transparent parts remain transparent rather than fill with player color.

Whether this be an alteration, a toggle, or some kind of feature, this working perfectly normal is so close yet unattainable without the fix for the skin showing up where it should not.

The override is a thin "skirt" hanging over the legs that uses the bottom right as a texture, the template for which shown below.
![Overhang_Template](https://user-images.githubusercontent.com/76188059/169659862-151d058e-853e-45b1-ba29-114cfb0b9ded.png)

Scaled up the skirt mesh area to better show how it interacts
![image](https://user-images.githubusercontent.com/76188059/169659933-2b1b86f3-910c-410b-91c8-58a0b1893bb8.png)

Currently, the materials for mesh replacements are either all in or all out, being that they have to use vanilla shirt and pants or use ONLY the mesh replacement material and not allow pants to show up at all. The only solution that I see would be to fill in the extra parts of the mesh in the texture void, so blocking the skin from rendering in that area will have no effect on the character and also allow mesh replacements to work with any and all types of clothing.

**Comment by SDGNelson** [comment]
Cool trick! Unfortunately the clothing shader is opaque right now, but I will bear this in mind for clothing rewrite because it should become possible to layer multiple skinned meshes.

**Comment by Dumfoozler** [comment]
Until then could would it be possible to create someway to add additional texture to a mesh replacement by any means? Maybe an option rather than to override the materials completely to overlay it on top of everything else? I want to do things like hanging threads, shoulder pads, gloves and the likes but i can't color them without making the entire character invisible or having everything be the player's skin color by default.

**Comment by SDGNelson** [comment]
Sorry, not with the current clothing

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
