### ISSUE TITLE
[Minor Bug] Car glass not see through, blacked out on mac

### ISSUE THREAD

**Issue by JR-TS** [SmartlyDressedGames/Unturned-3.x-Community#3213]
I'm on Mac (M1) macOS Monterey 12.3.1, Unturned 3.22.10.0 using a mod called UDarkRP Vehicles, the glass on the cars aren't transparent. This happens with other car mods too like Vanilla Vehicles 3, where the headlights aren't transparent. Is this an operating system specific bug?

<img width="1440" alt="Screen Shot 2022-05-21 at 4 52 05 PM" src="https://user-images.githubusercontent.com/85190042/169668725-8b44dbfe-293d-4de7-a01c-f029946f1c33.png">
<img width="1440" alt="Screen Shot 2022-05-21 at 4 52 14 PM" src="https://user-images.githubusercontent.com/85190042/169668726-1ced322b-def2-44e8-9b2b-c085d3c24232.png">
<img width="1440" alt="Screen Shot 2022-05-21 at 4 55 50 PM" src="https://user-images.githubusercontent.com/85190042/169668729-2a03b3e3-9dbb-41b2-9f46-cd03e1b541f0.png">

<img width="1440" alt="Screen Shot 2022-05-21 at 4 52 20 PM" src="https://user-images.githubusercontent.com/85190042/169668727-f02e1ba9-1bd8-4537-a008-3d130edbdbc7.png">

**Comment by SDGNelson** [comment]
Do vanilla transparent materials like glass and helicopter blades render properly for you? If so, then unfortunately it is up to the mod creator to adjust these transparent materials. My guess is that the mod is doing one of the following three things:
1. Not exporting multiplatform asset bundles (needed for Mac and Linux)
2. Not increased "Asset_Bundle_Version" to 3 in their .dat file
3. If they do not want to do either of the above, the other alternative is to use a transparent shader from the base game

**Comment by JR-TS** [comment]
Thank you for responding! The vanilla helicopter blades do render properly for me, so I think it is the mod that's messing up, I'll go to the mod creator for help. Thanks!
