### ISSUE TITLE
Centering entire map

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#3214]
![image](https://user-images.githubusercontent.com/80723434/169682992-baa0a21b-c83d-4b6c-98b2-de3ff1d1ed1c.png)

I only tried 2 times to transform a medium map to insane, both times leaving the terrain in a corner and streets, structures, barricades and others in their original position
Would it be possible to add an option to center the terrain? Not only when changing the size of the map but also choosing one of the squares, like the square of a medium map and moving it with everything

Any way to center it right now?
It would only have to redo streets, a bit of devkit and resources

**Comment by GazziFX** [comment]
It can be possible with creating custom module which will be properly convert to other size, but writing this module will take some time

**Comment by SDGNelson** [comment]
Sorry to say that there is not any good way to bulk move all of those right now. The best way to manually move the objects and devkit stuff would be to use the world-space move handle with 1024 grid snap interval. Then to move the terrain tile you could add tiles at the new location and swap the file names in YourMap/Landscape folder.
