### ISSUE TITLE
Error "prosur"

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3216]
![image](https://user-images.githubusercontent.com/65422793/169710871-a40cc1e6-b79d-4b56-9c77-2793c33c4c33.png)

How i can fix this?

**Comment by SDGNelson** [comment]
This means that the prosur asset bundle hash does not match between client and server. You might need to re-export with "multiplatform" enabled.

**Comment by danielstankw** [comment]
@SDGNelson I am having that issue as well,
Can you explain please how can it be solved? 
Other players are able to join the server, but when I join Arid it gives me that error.

I tried downloading the mod but didn't help

**Comment by SDGNelson** [comment]
@danielstankw it looks like Arid was updated yesterday, so it might just be that your client needed to get the latest update.
