### ISSUE TITLE
QoL Suggestion: Separate placement model for placeable items

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3217]
I wanted to do modified placeables with scripts in them awhile back, however they seem to always start the script so I'm assuming the preplaced & placed item uses the same prefab. So a simple fix to this would be that make it so that the preplaced item is on a separate prefab so that the script doesn't start.

From experience, I wanted to make a placeable timed charge that used a script timer, but even before placing it, the script starts. So hopefully something can be done so that placeables can properly support scripts that only start when placed.

**Comment by SDGNelson** [comment]
Agreed that this would be helpful, but probably not until barricades get revisited sorry. Structures will probably happen first hopefully soon.
