### ISSUE TITLE
Reworks of systems

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#3219]
I think it's time to rework very old systems of inventory and storaging, also clothing system is need rework too.

For example, you can see that storaging of items works trough the 2 arrays.
First array representing occupied slots and second representing items.
I guess we can do something about it.

Clothing system can be reworked with addition of enum
Why do we need RPC for each type of clothing and actions if we can use one for each action and send there enum that representating wearing type ?
```csharp
public enum WearableType
{
    Hat,
    Mask,
    Vest,
    Pants,
    Shirt,
    Glasses,
    Backpack
}
```
Why can't we replace fields like "vest", "vestAsset", "visualVest", "vestState", "vestQuality" to some type that will store this data? 
```csharp
public class ClothingData
{
    Item item;
    public Item Item
    {
        get => item;
        internal set
        {
            item = value;
            OnUpdated?.Invoke();
        }
    }
    public int Visual { get; internal set; }
    public ItemClothingAsset Asset => Assets.find(EAssetType.ITEM, Item.id) as ItemClothingAsset;
    public event System.Action OnUpdated;
}
```
Why can't we use just array to store there data about clothings ?
```csharp
public class PlayerClothing
{
    // ...
    public PlayerClothing()
    {
        var types = Enum.GetValues(typeof(WearableType));
        Clothings = new ClothingData[types.Length];
        foreach (WearableType type in types)
        {
            var data = Clothings[(int)type] = new ClothingData();
            data.OnUpdated += () => OnClothingUpdated?.Invoke(type, data);
        }
    }
    ClothingData[] Clothings;
    public delegate void ClothingUpdated(WearableType type, ClothingData clothing);
    public event ClothingUpdated OnClothingUpdated;
    public ClothingData this[WearableType type] => Clothings[(int)type];
}
```

**Comment by SDGNelson** [comment]
These are definitely on my to-do list / wishlist, and some might even happen this year. Just a byproduct of my level of (in)experience in 2014. There are a lot of related things which need cleaning up at the same time e.g. item networking using GUIDs and separating savedata from state[].
