### ISSUE TITLE
Unable to interact with server console on Linux

### ISSUE THREAD

**Issue by TomatoCo** [SmartlyDressedGames/Unturned-3.x-Community#322]
After starting the headless server I am able to connect and play. However, the server terminal itself does not respond to commands. For instance, after I connect I go to my shell and type 'shutdown', '/shutdown', and '@shutdown' and the server does not acknowledge any of them.

I am starting the via a bash script which does this:

`cp $PWD/../steamcmd/linux32/steamclient.so $PWD/Unturned_Data/Plugins/x86/steamclient.so`
`export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH`
`./Unturned_Headless.x86 -nographics -batchmode -logfile 'Servers/myserver/unturned.log' +secureserver/myserver`

so that Unturned can find the steamclient.so binary, then to actually start the server itself. After about 10 seconds the server is joinable but I am unable to issue any commands.

**Comment by Trojaner25** [comment]
This is a Unity bug and can not be fixed.
You can install RocketMod as a workaround.

**Comment by TomatoCo** [comment]
Can you be more specific about this workaround? I originally thought this
was a Rocket bug because I tried installing that first and had the same
problem.

**Comment by Trojaner25** [comment]
You need to use the Rocket Launcher instead of starting Unturned directly.

**Comment by TomatoCo** [comment]
Yes, I observed the same bug when doing that with the stock start.sh script.

**Comment by SDGNelson** [comment]
@Trojaner is right that rocket works around this. Windows is the main server platform for 3, but Linux will be the main platform for 4.

**Comment by TomatoCo** [comment]
I have been unable to get Rocket to work around this. To the best of my knowledge I followed the correct steps. Where can I find the official installation instructions?
