### ISSUE TITLE
'Player.Player.life.ServerRespawn' works strangely

### ISSUE THREAD

**Issue by ChumnoyGHOST** [SmartlyDressedGames/Unturned-3.x-Community#3220]
Why if I respawn a dead player using 'ServerRespawn()', player respawns at a random spawnpoint, but if he was in a vehicle at the time of death, the player respawns next to the vehicle in which he was sitting?

Default respawn:
![image](https://user-images.githubusercontent.com/76044557/170340418-3c31fe2a-26d1-4a6d-853d-5fdc6f6b2543.png)
![image](https://user-images.githubusercontent.com/76044557/170340588-37668408-e105-47b1-a3c8-c312df4de88d.png)

Respawn after death in vehicle:
![image](https://user-images.githubusercontent.com/76044557/170340839-253a7156-9775-41f0-89df-f6fa76aecd90.png)
![image](https://user-images.githubusercontent.com/76044557/170340921-d699ba22-b6d8-49c7-8e32-5629727c1727.png)

**Comment by SDGNelson** [comment]
Is there an exception in your server log? Internally ServerRespawn is called by the regular respawn button. Also even if spawnpoint is not assigned during death is should pick one during ServerRespawn.

**Comment by ChumnoyGHOST** [comment]
There are no exceptions in the server log.

**Comment by GazziFX** [comment]
I think respawn called before player exit vehicle by death

**Comment by ChumnoyGHOST** [comment]
At the moment of death the player is not in vehicle. I checked this by logging `Player.IsInVehicle` in the console.

**Comment by rube200** [comment]
I think it can happen if it fails to get a spawn point for some reason

**Comment by ChumnoyGHOST** [comment]
I tried it, but nothing changed.
> Ok, I think the problem is the player is not completely death yet. Try using PlayerLife.onPlayerDied

**Comment by GazziFX** [comment]
Maybe StartCouroutine wich will wait for next frame?

**Comment by ChumnoyGHOST** [comment]
I don't think that's the best solution.
> Maybe StartCouroutine wich will wait for next frame?

**Comment by ChumnoyGHOST** [comment]
Now I tried dropping the player from the car on the `PlayerLife.OnPreDeath` event, but that didn't work.

**Comment by rube200** [comment]
Player is automatically removed after OnPreDeath
![image](https://user-images.githubusercontent.com/20555316/170372341-57bdffe1-b6ca-46b7-a47b-afb79f882316.png)

**Comment by rube200** [comment]
wait a minute, are u testing with suicide?

**Comment by ChumnoyGHOST** [comment]
Not only with suicide.
> wait a minute, are u testing with suicide?

**Comment by surv0013** [comment]
This is a very old bug that has existed since the advent of transport. The player does not immediately exit the transport, so it is necessary to revive it in the next frame. Gazzi offered a working version. You just need to create a coroutine with a single frame wait.

**Comment by ChumnoyGHOST** [comment]
I was able to fix this with a coroutine, but I really don't like this solution, because after respawn I teleport the player to a certain place. Because the player doesn't teleport immediately (avoiding the bug), the player ends up in a different place for a very short period of time, and it's noticeable.
My code:
```c#
private void Events_OnPlayerDead(UnturnedPlayer Player, Vector3 Position) {
    Player.Player.life.ServerRespawn(false);
    StartCoroutine(Events_OnPlayerDead_Helper(Player));
}
private IEnumerator Events_OnPlayerDead_Helper(UnturnedPlayer Player) {
    yield return new WaitForSeconds(0.1f);
    try {
        // My code
    } catch (Exception) { }
}
```

> This is a very old bug that has existed since the advent of vehicles. The player does not immediately exit the vehicle, so it is necessary to revive it in the next frame. Gazzi offered a working variant. You just need to create a coroutine with a single frame wait.
> 
> You will have to wait a frame anyway, because otherwise the player will spawn with less than full health if they get killed with a shotgun, since not all bullets will immediately hit him. It's best to set a wait of `.1f` seconds for all the processes of the previous life to be completed and only then revive the player.

**Comment by GazziFX** [comment]
Did you try like this?
```csharp
private void Events_OnPlayerDead(UnturnedPlayer Player, Vector3 Position) {
    StartCoroutine(Events_OnPlayerDead_Helper(Player));
}
private IEnumerator Events_OnPlayerDead_Helper(UnturnedPlayer Player) {
    yield return new WaitForEndOfFrame();
    Player.Player.life.ServerRespawn(false);
}
```

**Comment by ChumnoyGHOST** [comment]
Now I tried it. It doesn't work. Most likely the bug occurs in the next frames.

> Did you try like this?
> 
> ```cs
> private void Events_OnPlayerDead(UnturnedPlayer Player, Vector3 Position) {
>     StartCoroutine(Events_OnPlayerDead_Helper(Player));
> }
> private IEnumerator Events_OnPlayerDead_Helper(UnturnedPlayer Player) {
>     yield return new WaitForEndOfFrame();
>     Player.Player.life.ServerRespawn(false);
> }
> ```

**Comment by SDGNelson** [comment]
Thanks to everyone for helping. Sorry to say this is unlikely to change anytime soon.
