### ISSUE TITLE
Russian hacker joining servers

### ISSUE THREAD

**Issue by ElRicki** [SmartlyDressedGames/Unturned-3.x-Community#3223]
This russian user joined my server to do something like this... using hacks like ESP, wallhack and noclip with a car
Here is a video of what he do:
https://www.youtube.com/watch?v=h1C-a5ojSHs
I found his youtube channel because he spammed in my server chat: 
![image](https://user-images.githubusercontent.com/75626024/170769498-99f58120-9b7c-479c-9dec-8699c922cd50.png)

The steam user is this: https://steamcommunity.com/id/765611993035727858/

**Comment by GazziFX** [comment]
Can you send his IP?

**Comment by GazziFX** [comment]
Also it was not a permalink it can be changed.
https://steamcommunity.com/profiles/76561199303727858

**Comment by SDGNelson** [comment]
Sorry, we cannot ban from the video, only from anti-cheat detection. 😞 If they reveal which cheat they are using or the cheat is leaked elsewhere then they should be banable.
