### ISSUE TITLE
Forced change of player skin color

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3227]
How to force change player color?) This would be useful for controlling players on RP servers.

**Comment by GazziFX** [comment]
Subscribe to Provider.onCheckValidWithExplanation and edit SteamPending.skin

**Comment by PARTOVIY** [comment]
The skin can only be obtained, I already tried it.

**Comment by GazziFX** [comment]
Use reflection to set "_skin" field
```
var field = typeof(SteamPending).GetField("_skin", BindingFlags.Instance | BindingFlags.NonPublic);
field.SetValue(pending, color);
```

**Comment by PARTOVIY** [comment]
> Subscribe to Provider.onCheckValidWithExplanation and edit SteamPending.skin

Is it possible to subscribe to UnturnedPermission.onJoinRequest and get the same effect?

**Comment by GazziFX** [comment]
Yes, but it is just a wrapper

**Comment by PARTOVIY** [comment]
Thanks you, very much
