### ISSUE TITLE
Russia Map console error

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#323]
after the last update, whenever i am restarting russia map i am getting this error, but it is not affecting game or any player, server is running fine with no issue, but still i thought informing you.
![image](https://user-images.githubusercontent.com/6502438/41242182-7a5619ca-6dbc-11e8-87ff-41e91c3fe7c1.png)

**Comment by Trojaner25** [comment]
Thats not the full error.
From the parts that are visible I can say that a plugin is outdated.
So this is not an Unturned bug

**Comment by aman7** [comment]
i thought about plugins, but i have like 12 servers all having same plugins. but only this map is having this error.

**Comment by Trojaner25** [comment]
Please post your full Rocket.log; otherwise its impossible to tell which plugin causes it.

**Comment by aman7** [comment]
[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2090756/Rocket.log)
here it is

**Comment by Trojaner25** [comment]
A plugin which is using "0Harmony.dll" as library causes it.
However I can not say which one exactly.

**Comment by aman7** [comment]
i dont even have 0Harmony.dll in liberary
![lib](https://user-images.githubusercontent.com/6502438/41243686-682a3836-6dc0-11e8-9dc8-77dae1c2289b.png)

**Comment by Trojaner25** [comment]
Check the AviRockets in your Modules.

**Comment by Trojaner25** [comment]
I'm almost sure that an Avi plugin causes it.

**Comment by aman7** [comment]
yes it is there in modules folder, but that is being used by 6 more maps than russia. but errors are in russia only. sounds strange

**Comment by Trojaner25** [comment]
You can have the the exact same set up on all servers.
Does not matter, error can still occur one some and not on some.

Anyway, its likely that its not AviRockets itself but rather a plugin which uses it.

**Comment by aman7** [comment]
well i am using only aviAdmin and its updated

**Comment by SDGNelson** [comment]
@Trojaner25 is likely right, the signatures of the damage methods changed recently so some plugins needed to be recompiled
