### ISSUE TITLE
Problem with map materials

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3230]
Hello Nelson!

After the update, my main materials disappeared on my map and were replaced by others. I don't know what is causing this and how to fix it. **Help me please.**

My materials file was in the root folder of the map.

I am attaching a file with my materials and screenshots.

Materials: https://drive.google.com/file/d/14uQhnsJwDkk0SLfD43hCMvBwIBN1JjWL/view?usp=sharing

Sincerely,
Svyatoslav
![20220213152846_1](https://user-images.githubusercontent.com/75787898/171844113-b17decb9-4ca1-4a1d-a790-9af3b768f2ca.jpg)
![20220603141832_1](https://user-images.githubusercontent.com/75787898/171844140-8f284461-939d-4c41-b5bd-44361e74e3af.jpg)
v

**Comment by SDGNelson** [comment]
Sorry for the trouble! Here is the FAQ about fixing these materials: https://gist.github.com/SDGNelson/dcd967e7ca1a0db7e15cce258ed7e401#q-how-to-fix-red-checkerboard-or-other-incorrect-materials

**Comment by FireRain4** [comment]
> Sorry for the trouble! Here is the FAQ about fixing these materials: https://gist.github.com/SDGNelson/dcd967e7ca1a0db7e15cce258ed7e401#q-how-to-fix-red-checkerboard-or-other-incorrect-materials

Thanks Nelson! However, there was about the same problem with custom resources - they are simply not in the list for installation in the map editor. What to do in this case?

**Comment by SDGNelson** [comment]
Here is a separate doc explaining the changes to trees and why: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Foliage.md

**Comment by FireRain4** [comment]
Thanks!
