### ISSUE TITLE
Bans are working weird

### ISSUE THREAD

**Issue by ElRicki** [SmartlyDressedGames/Unturned-3.x-Community#3232]
Some players are not being banned, and some people are banned with other people's reasons from quite some time ago

**Comment by ElRicki** [comment]
Example: ![image](https://user-images.githubusercontent.com/75626024/171972186-6179dfee-d0dc-4e2d-ab72-ae5f54709ea6.png)
A normal user from my server was banned, while no one banned him, that was a ban to another player with the reason "Spanish server" without that symbols.

**Comment by GazziFX** [comment]
Maybe related to #3231

**Comment by SDGNelson** [comment]
Sorry about these, it should be fixed in a patch this afternoon though I still need to investigate the reported BattlEye issues on Mac.

**Comment by MoltonMontro** [comment]
I believe this was fixed following the 3.22.11.1 patch. Can this issue be closed?
