### ISSUE TITLE
(NPC Feature) Condition appears defined Message_#_Page_# in Translation

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3234]
Hello Nelson!

There is an idea to add the ability for NPCs that certain Message_#_Page_# appear under a certain condition, for example:

Message_0_Page_0 You have to complete a difficult task related to Carlos.

Message_0_Page_1 It's good that you managed to get a map in time, which will allow you to find him much faster.
Message_0_Page_1_Conditions 1
Message_0_Page_1_Condition_0_Type Flag_Bool
Message_0_Page_1_Condition_0_Logic Equal
Message_0_Page_1_Condition_0_ID 10255
Message_0_Page_1_Condition_0_Value True

Message_0_Page_2 Thanks to the fact that you saved Anna, now we know how he motivates his actions. Use it when talking to him.
Message_0_Page_2_Conditions 1
Message_0_Page_2_Condition_0_Type Flag_Bool
Message_0_Page_2_Condition_0_Logic Equal
Message_0_Page_2_Condition_0_ID 10256
Message_0_Page_2_Condition_0_Value True

Message_0_Page_2 Find Carlos before he kills us all.

**Comment by SDGNelson** [comment]
Different responses according to what you did during the quest? Interesting idea - for the meantime albeit more work it should be possible to do this with different separate messages visible.

**Comment by FireRain4** [comment]
If this is implemented through various dialogs (for example, if the dialog has a huge number of options), then you get a lot of code, and if you do it this way, you can make very interesting storylines for NPCs. And spend less time doing it.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
