### ISSUE TITLE
One Way Glass Glitch

### ISSUE THREAD

**Issue by JackOfHearts914** [SmartlyDressedGames/Unturned-3.x-Community#3235]
I figured out that when you have scope quality off, you get a weird effect. You are able to zoom in and peek through one way windows. As you can see in the video, it also affects the windows when I run. This effect is not happening when you have your scope quality low-ultra. The glitch works on glass plates as well.

Video: https://www.youtube.com/watch?v=ihDXvOTquqs

**Comment by SDGNelson** [comment]
This seems reminiscent of a bug in old versions of Unity where the transparent field of view would not get updated when using TAA. Did you enable and disable TAA as part of finding this? Will investigate.

**Comment by JackOfHearts914** [comment]
I have retried it and when you enable FXAA, it does it as long as you have scope quality off.

**Comment by JackOfHearts914** [comment]
It works with Anti-Aliasing Off or on FXAA

**Comment by JackOfHearts914** [comment]
When you run around with Anti-Aliasing off/FXAA, it shifts the glass even when you have scope quality up.

**Comment by DanielWillett** [comment]
Happens for me with Anti-aliasing off, settings file attached

(gh doesn't support json)
[Preferences.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8885212/Preferences.txt)

**Comment by SDGNelson** [comment]
Should be fixed in tomorrow's update which reverts the post-processing version used by the game!
