### ISSUE TITLE
objects having ghost duplicates

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#3236]
doors and sentries turn into uninteractable clones for no reason
![image](https://user-images.githubusercontent.com/81492602/172017693-d33b19d5-ab79-493f-8a95-1a3bef9f14d8.png)

**Comment by SDGNelson** [comment]
Is there any exception in the server or client log?

**Comment by ddxn78096** [comment]
no idea, i dont run the server

**Comment by SDGNelson** [comment]
In that case sorry, the server owner would need to contact us for help debugging.
