### ISSUE TITLE
NPC Quest UI text

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3238]
More items you add to a quest, bigger the UI is. However this doesn't apply to text and it creates mess like this.
![image](https://user-images.githubusercontent.com/81763752/172042677-ced5b11d-ecaa-4af3-954e-342a82743cd1.png)

**Comment by SDGNelson** [comment]
Is this from a tall quest description? Sorry, the game does not currently have a way to measure text size for both IMGUI and uGUI. My hope is that once UIElements is used everywhere we can add auto resizing to most menus.

**Comment by surv0013** [comment]
> My hope is that once UIElements is used everywhere

When?
