### ISSUE TITLE
Steam username cannot be just numbers

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3241]
Players with just numbers for usernames cannot join servers. I cannot remember when this was added, but I think the intent may have had to do with preventing weird usernames that could be difficult to ban. For most people, the solution is to just change their public Steam username to include something other than just numbers.

Unfortunately, this also affects players who **_cannot_** change their public username. Steam Support can ban accounts from being able to change their public username, usually in response to reported Steam profiles that have problematic public usernames. When this happens, the account's public username becomes a series of numbers—their SteamID. The account is then unable to change their public username, for some variable amount of time.

This only affects a small handful of players, but perhaps we could revisit this server feature?

**Comment by SDGNelson** [comment]
I think this has been like this from the first 2014 releases because as you mention otherwise certain names are hard to ban. Interesting point about players who are unable to change their names. Prerequisite might be improving the ban/moderation tools and then reconsidering name limitations.
