### ISSUE TITLE
Is there anyway to request access to the source code?

### ISSUE THREAD

**Issue by WFPhantom** [SmartlyDressedGames/Unturned-3.x-Community#3245]
I see that the source is on GitHub but it's private, any way to get access for modding and stuff? if not is decompiling it legal under unturned's license?

**Comment by GazziFX** [comment]
Upload decompiled code only to private repo

**Comment by SDGNelson** [comment]
For a long time I have wanted to make the source code publicly available, but there is no ETA yet sorry.

In the meantime yes decompiling for modding is fine.
