### ISSUE TITLE
failed to load battleye client library

### ISSUE THREAD

**Issue by Destroyerm19** [SmartlyDressedGames/Unturned-3.x-Community#3250]
Ijust like this man said i have also recently loaded up unturned on my mac and when joining a server I received a message saying that i've been kicked from the server as "failed to load battleye client library". I tried verifying files on unturned, uninstalling and restarting my computer. Even when reinstalling I still get the same error message. A game I love so much has become broken and it seems theres no way to fix it: wierdly enough though this only happened when the new updated for unturned on the 4th of june did this happen and im so sad

**Comment by jatapa** [comment]
This is same as #3233

**Comment by jatapa** [comment]
Should close this
