### ISSUE TITLE
Players use a bug to get through walls

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#3251]
Hello!  On my RP life server, I made people grow plants and get exp for it.  However, quite a long time ago there was a problem that the plants that players put in their homes inexplicably disappear, although all the windows and doors in the building are barricaded.  Recently, I managed to find out what is really going on.  The player removes the asset of the building to be infiltrated and logs into the server.  Through a transparent wall, you can interact with any barricade and plant.  You can't go through the wall, but you can drive through.  I'll attach a video below for you to see.  Please fix this, it's a big problem:
https://youtu.be/ELmyjiiermI

**Comment by SDGNelson** [comment]
In good news: this should have been fixed with some of the asset integrity checks improved earlier this year!
