### ISSUE TITLE
Server crashing randomly without any error

### ISSUE THREAD

**Issue by TheFrieber** [SmartlyDressedGames/Unturned-3.x-Community#3256]
Sup, my Server is crashing randomly by itself. It does not save and turn off, it just crashes, while the crash happens, on the left upside corner, it says that the Server is not responing anymore and then kicking us out. After that the Server is closed and needs to get restarted. I already looked into the logs. But there was nothing, it's not saving the error anywhere either. i can see my command actions(im saving manually rn, my Server is not Rocket and has no plugins/mods) that i used before the crash, but the crash itself is not listed in the logs, not even a shutdown.

Server:
1 Core(Around 70% usage while playing with friend)
6 GB Ram(using around 50%-70%)

No mods, the Server is already updated to the latest, it was setup with the guide in Unturned "host"(The git).

Map: Kuwait
Custom options: Yes
Diff: Normal(A litte Customized too)

![image](https://user-images.githubusercontent.com/77841885/173610597-f262c23a-3467-4dca-9549-5efc62308cb0.png)
Horizontal red line is the moment of the crashing, Vertical is the startup of the Server(Pic is in Hour view, the server runned acually longer)

**Comment by GazziFX** [comment]
Do you have RocketMod and any plugins installed?

**Comment by hehseomeone** [comment]
> Do you have RocketMod and any plugins installed?

How i mentioned above, no i don't, it's only vanilla with kuwait on it.
Here the logs:
[Server_UnturnedServerS_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8902886/Server_UnturnedServerS_Prev.log)

**Comment by hehseomeone** [comment]
> What Linux distribution do you have?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by SDGNelson** [comment]
Sorry for the trouble! The engine (Unity) also writes its own log file which might have some information about the crash. Could you check for this file please? `~/.config/unity3d/Smartly Dressed Games/Unturned/Player.log`
If it does not exist we might need to specify a location for it to write to.

**Comment by hehseomeone** [comment]
> ~/.config/unity3d/Smartly Dressed Games/Unturned/Player.log

The path exist, but there is nowhere a log file.

**Comment by SDGNelson** [comment]
Okay, in that case if you add `-logfile yourpathhere` *before* +InternetServer in your server launch script it should write the Unity log file. For example `-logfile /var/log/unity.log`
