### ISSUE TITLE
[Feature Request] InteractableVehicle.vehicle.findPlayerSeat(byte seat)

### ISSUE THREAD

**Issue by wsmajt** [SmartlyDressedGames/Unturned-3.x-Community#3259]
I think this would be great for checking if someone is on that seat in the vehicle, if its not returning null.

**Comment by GazziFX** [comment]
`vehicle.passengers[seat].player`
Isnt that what you need?

**Comment by wsmajt** [comment]
yeeess, I knew i saw this before..
closing now.
