### ISSUE TITLE
Unturned Ladder Bug

### ISSUE THREAD

**Issue by HelgeoX** [SmartlyDressedGames/Unturned-3.x-Community#3266]
So i found this ladder bug in Unturned, it's nothing big but it can be a bit annoying. Basically, this bug occurs when you use a melee while jumping on a ladder. Example: https://medal.tv/games/unturned/clips/oZzjU3ypoN4Zf/d1337qu6pFUY?invite=cr-MSxsQVQsNTY0NjgzMzIs I decided to make it a bit funny cuz why not. Anyway, I hope this bug will be fixed soon, thanks for your time!

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time. This is intentional: ladders are ignored while performing non-interuptable actions.
