### ISSUE TITLE
Vehicle information

### ISSUE THREAD

**Issue by ChumnoyGHOST** [SmartlyDressedGames/Unturned-3.x-Community#3268]
I'm trying to get the vehicle speed in km/h, but values are too inaccurate.
I take the vehicle speed from `Vehicle.speed` (InteractabeVehicle) and multiply by 3.6 (to convert it to km/h). The problem is that `Vehicle.speed` is of float type, but always takes an integer value.
How can i get the exact speed of the vehicle?
```c#
public static void CodeExample(UnturnedPlayer Player) {
    Rocket.Core.Logging.Logger.Log("Speed: " + (Math.Abs(Player.CurrentVehicle.speed) * 3.6f)); // float but int * 3.6
    Rocket.Core.Logging.Logger.Log("PhysicsSpeed: " + (Math.Abs(Player.CurrentVehicle.physicsSpeed) * 3.6f)); // float but int * 3.6
    Rocket.Core.Logging.Logger.Log("spedometer: " + Player.CurrentVehicle.spedometer); // Always 0
}
```
I also don't understabd why there is a `spedometer`. It always equals 0.

**Comment by GazziFX** [comment]
`spedometer` is only client-side, `speed` and `physicsSpeed` is also client-side values, but they sent via `DrivingPlayerInputPacket` and coded just in one `byte`.
The best solution is calculate speed by tracking position, but it need to add some smoothness because of it discrete nature

**Comment by ChumnoyGHOST** [comment]
But why speed and physics speed is integer?

**Comment by GazziFX** [comment]
> But why speed and physics speed is integer?

Its transfered within one byte
