### ISSUE TITLE
[Bug] Using ladders to get under the map

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3273]
Just a very easy and repeatable method to get under any map.
![ladderbug](https://user-images.githubusercontent.com/71527679/175093354-8d600e55-8a82-46bc-86cc-9c9274d292f0.gif)

**Comment by SDGNelson** [comment]
Thanks for the report! Spent a while investigating this morning, and it seems for some reason `PlayerStance.hasHeightClearanceAtPosition` detects the ground in singleplayer, but not in multiplayer. Doing a sphere cast or line cast detects the ground in multiplayer, but not the capsule overlap or check. I have not figured out why yet, but will add a line cast that *only* hits the ground as a temporary workaround. Fortunately for the meantime any non-admins doing this would get teleported back up to the surface (only admins can go below terrain on maps with underground allow zones).
