### ISSUE TITLE
No sun, moon, or clouds with linux version.

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#3274]
Just noticed today. that they're missing.

Running with Proton:
![Screenshot_20220624_103858](https://user-images.githubusercontent.com/103531662/175559854-4b006acf-7906-483b-a60d-67194cd93701.png)

Linux:
![Screenshot_20220624_104300](https://user-images.githubusercontent.com/103531662/175559571-a40d8d2f-b9de-4e84-ba5d-ba2760a85d41.png)

**Comment by SDGNelson** [comment]
That is particularly odd considering that the white-blue background gradient is handled by the same shader as the clouds and sun. Perhaps specific to Linux distro and drivers? On my Steam Deck running native the clouds and sun appear normally.

**Comment by KeriDGaming** [comment]
Since every pc in the house has Kubuntu,  I downloaded and used SteamOS, same issue.
![download (1)](https://user-images.githubusercontent.com/103531662/175824959-112bac38-d8c1-4daf-be4e-29bc082d323d.jpeg)

**Comment by GazziFX** [comment]
Can confirm on Ubuntu 21.04 GPU GeForce GTX 1660 Ti, not work on default settings, but work with `-force-vulkan`
![Снимок экрана от 2022-06-26 21-49-46](https://user-images.githubusercontent.com/43498426/175829580-d721944f-ce22-46f3-9fd1-b02d6e4fa36c.png)

**Comment by GazziFX** [comment]
After manual install GPU drivers, I got even greater increase in FPS

**Comment by GazziFX** [comment]
Can we get Vulkan on Windows? I think it can be useful with some cards
In `Player` settings:
![image](https://user-images.githubusercontent.com/43498426/175831462-b409c11e-2828-401f-9f1f-67f04c0ba167.png)

**Comment by KeriDGaming** [comment]
Thank you Gazzi.

**Comment by SDGNelson** [comment]
Hmm I wonder why it is not working on OpenGL. Also I would think Vulkan would be the default on Linux nowadays. Will investigate.

**Comment by KeriDGaming** [comment]
I'm now trying to decide which is better:  The sun and moon, with blocky and missing vulkan particles and textures.  Or, better particle effects, with no sun & moon...
![imgs](https://user-images.githubusercontent.com/103531662/175849095-bb23bacc-d5f9-4dac-9c9b-cb34df692185.png)

**Comment by GazziFX** [comment]
I dont have such bug, can you try to update your drivers?
![Снимок экрана от 2022-06-27 10-42-06](https://user-images.githubusercontent.com/43498426/175886886-dc74465c-b552-4d16-9f39-facd9a5ad21d.png)

**Comment by KeriDGaming** [comment]
Apparently, it's the Kuwait map, pei is fine.

**Comment by GazziFX** [comment]
I have bugs on Kuwait too, but Arid works fine. I think Kuwait is too old for Vulkan and it doesnt even contain `Asset_Bundle_Version` so game cant define how to upgrade it. Also not all mods provide linux bundles so I think it will be really hard to fix, or maybe Nelson will create more advanced shader upgrade tool. And maybe if Unturned will support Vulkan for Windows all future mods will support it without creating separate bundles for each platform (idk if it work that way)

**Comment by GazziFX** [comment]
I setup my Unity project like this https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3274#issuecomment-1166628593 and now its working properly on linux with Vulkan even without multiplatform setting checked
![Снимок экрана от 2022-06-27 18-05-41](https://user-images.githubusercontent.com/43498426/175972970-d85247b5-8c89-4b47-8056-7a96344f3fd1.png)
![Снимок экрана от 2022-06-27 18-06-19](https://user-images.githubusercontent.com/43498426/175972979-6e0ff864-897c-405b-aed9-3fe5dd8283bd.png)

**Comment by Johnanater** [comment]
Weird, I remember seeing the new clouds when they were first added, but now they don't seem to appear on my game as well.

They still appear in the main menu
![image](https://user-images.githubusercontent.com/10360610/176333167-2a5047b8-22c8-4629-b968-68e858898326.png)

I'm on Manjaro, using Nvidia Driver 465.31, which is sadly the last version that works on my card.

I tried the `-force-vulkan` parameter and the game would get stuck loading on skin asset 464/489

![image](https://user-images.githubusercontent.com/10360610/176334096-413e1fa9-b59b-426b-b218-2d78eb683c37.png)

**Comment by SDGNelson** [comment]
Vulkan was enabled for Linux in the most recent update. (IIRC before it was disabled because it was marked experimental?) After this update have things become more consistent for you?

**Comment by KeriDGaming** [comment]
Removed -force-vulkan and back to no clouds, sun/moon.
![Screenshot_20220711_230228](https://user-images.githubusercontent.com/103531662/178400179-0ec8c24f-8565-4a03-af94-74b7f9a15407.png)

**Comment by SDGNelson** [comment]
If you do use Vulkan are there no more visual issues?

**Comment by KeriDGaming** [comment]
If vulkan is used, the map/mod may have visual issues, such as the tinted windows, now opaque, on the heli, or the rotors on both.
![Screenshot_20220714_094526-1](https://user-images.githubusercontent.com/103531662/178997345-a441dc84-2922-44fb-981b-d0cefd631a00.png)

**Comment by HereticHazel** [comment]
I'm still having this issue, though `-force-vulkan` fixed it with no side effects
