### ISSUE TITLE
[Feature Request] Unofficial Skins in Workshop Mods

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3276]
This has probably been asked before but I couldn't find an issue on it so I'll make a new one; Is there any chance of getting features for adding custom skin assets to mods and applying them in multiplayer? Steam inventory could still take priority so people can't fake owning official skins, but this would allow modders to create their own cosmetics for their guns/vehicles since modded content doesn't really have cosmetics (as far as I know). Even if they're only usable through plugins it would be neat to be able to give players a list of skin assets they have access to on join (similar to how it works now with the econ int ids but a separate array with ushorts/guids, also the ability to update it without requiring a relog would be nice).

I know this probably wouldn't be a high-priority feature but it would expand modding a lot and from what I can tell wouldn't be terribly difficult to implement.

 Thanks

**Comment by surv0013** [comment]
It seems to me that it is better to give the opportunity to create your own types of attachments (grip, tactical and etc.) for weapons, then it would be possible to make the skin as new attachment type, what would allow you to change it through the weapon modification menu.

**Comment by MoltonMontro** [comment]
> Even if they're only usable through plugins

For the record, I am fairly certain that I have seen some server networks do stuff similar to what you're asking, via custom plugins. (That is—custom/modded skins, for use on custom/modded items.)

**Comment by DanielWillett** [comment]
@SDGNelson Curious to know your opinion on all this when you have a chance.
