### ISSUE TITLE
[Feature] Make the player's line in chat longer than 128 characters

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3277]
**Hello Nelson!**

With the deepest respect, the administrator of one text RP in the dark Middle Ages addresses you. We have been waiting for a chat improvement in our favorite game for a long time. However, we have been waiting for certain changes for a very long time....

Please make the player's line in chat longer than 128 characters. Players, unfortunately, cannot fit their entire line into 128 characters, and splitting it into several messages is a big inconvenience.

You might also be interested in ideas like the text that appears above the player when they send a message. Or when a character types, three dots appear above them.

![20220625202533_1](https://user-images.githubusercontent.com/75787898/175786780-861541aa-35ea-4966-939b-cf095d9c4b33.jpg)

https://user-images.githubusercontent.com/75787898/175786783-bddbad3f-3557-427b-8562-c3db074ec796.mp4

**Sincerely,
Creator migliorerp.ru**

**Comment by surv0013** [comment]
I support the idea of reworking the chat, the chat is uncomfortable.

The text above the head is better implemented using mods and plugins, but for this it is necessary to rework the EffectManager, allow to attach effects to the Transform, and send the text not only to the TextUI, but also to the TextMesh.

**Comment by SDGNelson** [comment]
It is definitely on my wishlist. It depends on measuring the text size, as do several other similar UI improvements. Will probably happen after the UIElements update which I started experimenting with again after the Unity 2020 update.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
