### ISSUE TITLE
Arid Map not Installing Unturned server

### ISSUE THREAD

**Issue by SirWumbus** [SmartlyDressedGames/Unturned-3.x-Community#3278]
I have had a look at a few other posted issues and tried their solutions. 
I tried deleting the U3DS/Server/Default/Workshop/Steam folder but upon running the server it would attempt to download get caught on:
Downloading workshop item: 2683620106
and then nothing more would come up
Checking the workshop folder again there is a new Steam folder there with the map in .../downloads/304930
Do I have to move this into the Maps and Content folders manually?

**Comment by SDGNelson** [comment]
How long did it stay "downloading workshop item"? After it finishes it should say "downloaded [...]". Were other workshop files working normally?

**Comment by SirWumbus** [comment]
Sorry for not replying sooner.
I can't exactly remember but I actually got it to work. I removed the ID from the workshop download and copied the Arid files from my workshop into the server manually.
Sorry for the late reply but I have managed to fix it.
Thank you.

**Comment by SDGNelson** [comment]
Glad to hear you got it working! Though manually installing is definitely not ideal
