### ISSUE TITLE
Starting game leads to no graphics with MacOS 10.13

### ISSUE THREAD

**Issue by RenProto** [SmartlyDressedGames/Unturned-3.x-Community#3281]
When launching the game via steam or app package in MacOS 10.13.6, it will launch the application in full screen and will refuse to draw any assets, even a loading screen. After ~5-7 minutes, it would start the main menu's theme, but would still not draw anything. Attached is the log file when I decided to wait the time.
[log file](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9002413/Client_Prev.log)
upd: another log file
[log file 2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9005872/Client.log)
Appending graphics device details to thread start:
iMac (21.5-inch, Mid 2011)
```
AMD Radeon HD 6750M:

  Chipset Model:	AMD Radeon HD 6750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Dynamic, Max):	512 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x6741
  Revision ID:	0x0000
  ROM Revision:	113-C2950H-175
  VBIOS Version:	113-C29505-102
  EFI Driver Version:	01.00.560
  Displays:
iMac:
  Display Type:	LCD
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort
  ```

**Comment by SDGNelson** [comment]
Sorry for the trouble! It looks like it is probably *mostly* working, but that somewhere along the line it is having trouble copying to the screen:

> Invalid pass number (1) for Graphics.Blit (Material "(Unknown material)" with 0 passes)

Could you attach this engine log file as well please? The game log file captures some of the engine logging, but not all of it, so there might be an explanation in here:
1. Hold Alt and click Go > Library in the Finder toolbar
2. Open the Logs folder > Smartly Dressed Games > Unturned
3. Attach the Player.log file to your email

**Comment by RenProto** [comment]
Attached is the log file from the directory you asked.
[Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9022599/Player.log)

**Comment by SDGNelson** [comment]
Thanks for the log file! It looks like it is having trouble initializing the graphics device / GPU (integrated GPU in the case of Macs). Do you have any special graphics configuration for example trying to use an external GPU or having changed some settings on the command-line?

**Comment by RenProto** [comment]
This is a fresh install of macOS after wiping all data, I don't believe there is anything I've changed that would affect graphics.

**Comment by SDGNelson** [comment]
It might be worth trying running the game as OpenGL:
1. Right-click Unturned in your Steam Library
2. Select Properties... > General
3. Find the Launch Options field
4. Type "-force-glcore" without quotes

**Comment by RenProto** [comment]
Using `-force-glcore` as an appcommand doesn't want to launch the game.
Here's information on my graphics device.
```AMD Radeon HD 6750M:

  Chipset Model:	AMD Radeon HD 6750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Dynamic, Max):	512 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x6741
  Revision ID:	0x0000
  ROM Revision:	113-C2950H-175
  VBIOS Version:	113-C29505-102
  EFI Driver Version:	01.00.560
  Displays:
iMac:
  Display Type:	LCD
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort```

**Comment by SDGNelson** [comment]
Have you been able to play Unturned before? (to clarify whether it only stopped working recently)

When you say "as an appcommand" did you use the Steam launch options feature, or something else? I wanted to double-check because I am unfamiliar with "appcommand" on macos.

Thinking about it more the OpenGL shaders might not actually be included in the current game version, but they will be in the next update - I only recently enabled all graphics API support on all platforms.

If the game **has** worked for you before then it might also be worth try forcing the Metal API in case it is failing to initialize for some reason choosing not to use Metal:

1. Right-click Unturned in your Steam Library
2. Select Properties... > General
3. Find the Launch Options field
4. Type "-force-metal" without quotes

**Comment by RenProto** [comment]
> Have you been able to play Unturned before? (to clarify whether it only stopped working recently)

Yeah, I did play before about 1 year to 18 months ago.

> When you say "as an appcommand" did you use the Steam launch options feature, or something else? I wanted to double-check because I am unfamiliar with "appcommand" on macos.

Yeah, I did mean launch options, sorry for the malapropism.
---

Launching the game with `-force-metal` leads to also the inability to run, like attempting to force OpenGL. I do not think this device even supports metal. I don't have an Intel Mac, newer or older, to test this against. However, I checked with my friends if they could run it w/ Apple Silicon, and they could.

I've also tried Vulcan, but I would most likely assume that is just the render tech that is the default with Unturned since it did run. Currently looking into seeing if it is a firmware issue, but this is an untouched iMac in terms of modification of its internals.

**Comment by SDGNelson** [comment]
In that case maybe it just is that the OpenGL shaders have been excluded after you last played. They will be included in Thursday's update, or if you would like you can try the preview branch which has them already:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Betas
3. From the dropdown select "preview"

**Comment by RenProto** [comment]
Yes, it does render assets in the preview beta, so the shaders being excluded was the issue! Strange how it would consider the device as null w/o the shaders being present, but I would assume that's down to unity.


Attached is the working session's [Player.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9041568/Player.log) file.

**Comment by SDGNelson** [comment]
Glad to hear it is working in the next update! :)
