### ISSUE TITLE
Is There an Event When the Inventory Is Opened?

### ISSUE THREAD

**Issue by CinarBenli** [SmartlyDressedGames/Unturned-3.x-Community#3282]
Is There an Event When the Inventory Is Opened?

**Comment by DevInc0** [comment]
Hey there!
I guess, you can use `Rocket.Unturned.Events.UnturnedPlayerEvents.OnPlayerUpdateGesture`



Something like this:
```cs
using Rocket.Unturned.Events.UnturnedPlayerEvents;
using Gesture = Rocket.Unturned.Events.UnturnedPlayerEvents.PlayerGesture;

/* there's should be Plugin initialization and so on */

protected override void Load()
{
    UnturnedPlayerEvents.OnPlayerUpdateGesture += OnPlayerUpdateGesture;
}

private void OnPlayerUpdateGesture(UnturnedPlayer unturnedPlayer, Gesture gesture)
{
    if (gesture == Gesture.InventoryOpen)
    {
        // player opened the inventory
	return;
    }

    if (gesture == Gesture.InventoryClose)
    {
        // player closed the inventory
	return;
    }
}
```

**Comment by DMJaxun** [comment]
@DevInc0 Don't suppose you could help me as well, but would you happen to have a script that allows a buildable only to be placed in water? Cheers.

**Comment by GazziFX** [comment]
> @DevInc0 Don't suppose you could help me as well, but would you happen to have a script that allows a buildable only to be placed in water? Cheers.

BarricadeManager.onDeployBarricadeRequested
and
WaterUtility.isPointUnderwater
