### ISSUE TITLE
Weird bug with menu

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3284]
![2](https://user-images.githubusercontent.com/65300126/176875045-a14249e7-ae6b-4afc-a60e-c0334c5de1dc.png)
![1](https://user-images.githubusercontent.com/65300126/176875050-121055d1-9ff1-43b1-9acf-72c464de9235.png)

**Comment by SDGNelson** [comment]
Sorry for the trouble! Was this a one-off, or does it happen when you open those menus again?

**Comment by sunnamed434** [comment]
i dont know, it appers randomly when i dead, then I cant interact with ui normally anymore, I had to leave from server and this problem disappear
