### ISSUE TITLE
[Minor bug] Circular table LOD's

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3286]
All of the circular tables (1288, 1289, 1290, 1291) use the same renders at LOD 1.
![tables](https://user-images.githubusercontent.com/71527679/176985830-99728373-324a-4836-8bf2-cef67a63c6ad.gif)

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix.

**Comment by SDGNelson** [comment]
Should be fixed in tomorrow's update!
