### ISSUE TITLE
Modified or corrupted asset despite Bypass_Hash_Verification

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#3289]
So I am a server dev and I also make some minor guns/etc. that come with. Sometimes the gun bugs out and then I have to reupload it with Bypass_Hash_Verification. However, sometimes I don't have access to unturned to upload, but I do have access to the server (on my potato laptop) and about 1 or 2 years ago, I would temporarily put a Bypass_Hash_Verification on the gun's file on the server until I was able to reupload, and this would work as a stopgap until I updated my workshop mod. Now, it doesn not seem to work like that anymore, and giving all my guns bypass hash is a bad idea but also finding broken guns one by one and reuploading is pretty tiresome too. I've tried setting Validate_masterbundle_hashes to false but it still does not change this error.

**Comment by SDGNelson** [comment]
Perhaps there is a duplicate asset on the server? The client does not get that kick if the asset has Bypass_Hash_Verification enabled on the server side.

**Comment by tankirules** [comment]
> Perhaps there is a duplicate asset on the server? The client does not get that kick if the asset has Bypass_Hash_Verification enabled on the server side.

I don't think so, but for some reason the hosting website installs workshop content into the "base" directory (where the executable is normally located) and not into the server's "server's" folder

**Comment by GazziFX** [comment]
> I don't think so, but for some reason the hosting website installs workshop content into the "base" directory (where the executable is normally located) and not into the server's "server's" folder. Could this be the reason?

Have you used other workshop installation except `WorkshopDownloadConfig.json`?

**Comment by SDGNelson** [comment]
If they are installed in the same directory as the server executable that does sound like something weird is going on - mods should be auto downloaded by the WorkshopDownloadConfig.json file's WorkshopeFileIDs list.

**Comment by tankirules** [comment]
> If they are installed in the same directory as the server executable that does sound like something weird is going on - mods should be auto downloaded by the WorkshopDownloadConfig.json file's WorkshopeFileIDs list.

I tried moving it to servers/servername/workshop/content and it still does not work. Is this because it is a masterbundle?

**Comment by tankirules** [comment]
Yeah turns out the workshop assets were installed twice by the hosting website
