### ISSUE TITLE
Character Mesh Replacement collapsed

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3290]
I've checked a similar issue that has been closed by now, and the solution there was wrong bone axis. However, I've set up the bone axes export settings as mentioned in the Animation.md, but still the player model is collapsed (and it's not a custom model, its the example model we have in Sources)

Model applied to preview character in Unity
![изображение](https://user-images.githubusercontent.com/59206749/177327363-cbf2cc66-3695-4678-addc-20a74b54452e.png)

Export settings
![изображение](https://user-images.githubusercontent.com/59206749/177327571-0c4eec9a-7c39-433d-b95b-84da2713344a.png)

**Comment by SDGNelson** [comment]
Looks mostly default except I think it might be the Export Settings Transform is not default - if you change Forward to -Z Forward and Up to Y Up does it work?

**Comment by DerpyHoowes** [comment]
Sadly, this didnt help. The model is still collapsed.

**Comment by SDGNelson** [comment]
I just double-checked by re-exporting the vanilla character and while the body was not collapsed there was something weird with the hips. Will investigate what is going on there.

**Comment by SDGNelson** [comment]
It looks like the roll on the character .blend file's legs was reset at some point, here is a version with correct roll:
[Model_Src.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9162664/Model_Src.zip)

Here are the Unity import settings used by the game:
https://i.imgur.com/WRFQnRT.png
https://i.imgur.com/sUjy5gy.png

**Comment by DiFFoZ** [comment]
Thanks it is now fixed

**Comment by SDGNelson** [comment]
Phew! Sorry about that.

**Comment by V1nDeer** [comment]
Да ничего страшного. Спасбо что не оставил без внимания

**Comment by V1nDeer** [comment]
It's okay. Thanks for fixing
