### ISSUE TITLE
Placing Structures after the Update

### ISSUE THREAD

**Issue by progressPH** [SmartlyDressedGames/Unturned-3.x-Community#3293]
After the update 3.22.12.0 Players can't place simple items (I would guess that something is not aligned properly)

https://imgur.com/a/59uDIQn

**Comment by SDGNelson** [comment]
Sorry for the trouble! Is this on your server? If I can come check that spot in debug mode I will see what might be the issue. Or if you can send me the Structures.dat file from the Level savedata folder I can load it up locally.

**Comment by progressPH** [comment]
Well it's a server I am Moderator for so I don't really know about stuff like that

**Comment by PandahutMushy** [comment]
Hi Nelson, thank you for your reply. This is an issue happening on only one of our servers and does not appear to be a plugin issue. I will follow up with you on this via email, where I'll attach the server's structures.dat file.

**Comment by liebesleid-eth** [comment]
Its also happening on one of my servers (arid) 
![image](https://user-images.githubusercontent.com/99780369/178202252-af63c351-08c7-4b45-93a6-ae0f48aad008.png)
![image](https://user-images.githubusercontent.com/99780369/178202287-5f7013cc-1f8d-4e6c-b417-51c196b55a01.png)
![image](https://user-images.githubusercontent.com/99780369/178202299-7e699591-b6c8-4c60-a335-72611eb94642.png)

as well as in a washington server (Fullplomo #2)  that isn't mine

**Comment by SDGNelson** [comment]
Hm I am not sure what is blocking it in those examples, but for the next update I am going to improve the "Blocked" message and also handle more structure overlap cases.
