### ISSUE TITLE
New Structure Update and some questions... -_-

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3294]
Why all new updates with structures are internal?
You ruin a no need pillars system on my server, becouse you delete Clip.prefab.
It's ok, im think so, and i go to find another way to create this system, but ALL new system in game code are internal.
And now i have to fuck with reflection to get the desired result.

P.S: Why did you ignore 3 of my threads with pretty cool stuff and fix hardcoded claim flag radius.

**Comment by GazziFX** [comment]
I think would be nice to have built-in solution to place special walls without pillars

**Comment by SDGNelson** [comment]
Closing as duplicate.

**Comment by GazziFX** [comment]
What is about add this feature officially?

**Comment by GazziFX** [comment]
@SDGNelson https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3294#issuecomment-1178413029
