### ISSUE TITLE
[Minor Bugs] UI Scaling

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3295]
Could we get some adjustments made to how the UI scales, and how the setting is saved?
This is particularly annoying on 4k displays. 

This is the screen that I have regularly been met with when I open Unturned over the last few days.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71527679/177879854-cb94068d-816c-4a88-80da-43a2d2676e41.png">

It is running in 1280x720p with a UI Scale of 2.0, on a 4k display.
This is caused by the UI Scale setting not saving correctly between game restarts after switching from 4k with a 2.0 scale, to 720p with a 0.6 scale. 
If anyone else is unfortunate enough to have these settings appear when launching the game (or worse), the Configuration menu can't be reached on the menu - and the solution is to click Singleplayer and where you can _just about_ click on the Play Offline button in the bottom left. If the scale was any higher you would be soft-locked from playing the game without altering launch options or config files.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71527679/177879973-92c73983-efc2-4790-a9f3-62fd0c3fd703.png">

Once the map has loaded you're able to pause and go to Display, where you can change the UI Scale, but at this point you're editing the Scale in-game which will not save on next restart from what I can tell. 

On a slightly separate topic.

A 3840 x 2160 resolution with a default UI Scale of 1 (although it doesn't really come across well in a screenshot) is almost unreadable: 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71527679/177884109-a1372bcd-945f-415c-856a-145935c26be1.png">

And changing the UI Scale to 2.0, while much more appropriate and close to the default (1080p, UI Scale 1), leads to some awkward overlapping on the main menu: 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71527679/177884579-131728d3-6217-46ec-ba70-458159a764e7.png">

**Comment by SDGNelson** [comment]
Are you switching between playing the game on a 1280x720 and a 4K display, or are you saying they are getting reset to those values? Currently all settings are saved to Steam cloud, but some settings like graphics and display should really be per-machine. Anyway for the meantime if you would like you can override the launch options per-machine:
`-ui_scale #`
`-width # -height #`

As for the news feed: it still uses uGUI separately from the rest of the entire game, so I am planning to update it to the same UI as part of the UIElements update.

**Comment by AdamDN** [comment]
> Are you switching between playing the game on a 1280x720 and a 4K display

This is all on the same 4k display - I'm just referring to changing resolutions in the display settings. 

> or are you saying they are getting reset to those values?

I regularly switch between a 4k resolution with a 2.0 scale, a 720p resolution with a 0.6 scale, and a 1080p resolution with a 1.0 scale. These resolution and scale combinations are all usable and ideal for my display, and all useful in difference scenarios.
The issue is that from what I can tell, they are both really unreliable at saving across game restarts.
Sometimes the resolution will save, sometimes the scale will save. 
So despite _only_ ever using those combinations of resolutions with scales, the game will often launch with a mismatched resolution and scale combination that can make it impossible to navigate the menus. 

Using the launch options would guarantee that the menu is _usable_ on launch, but it will also guarantee the inconvenience of having to manually set the resolution and scale each time.

**Comment by SDGNelson** [comment]
The resolution and UI scale are actually even saved to the same file. I just tried closing and restarting the game with a variety of resolution+scale combos and it seemed to restore properly.

Is perhaps one of the resolution or UI overrides set in the Preferences.json file?

One thing I wonder: if you note which resolution and UI scale you were using and expect, perhaps the UI scale always saves but the resolution gets reset? I wonder if something else is causing the resolution to get reset. For example if the loaded resolution is larger than the "highest recommended resolution" then it clamps to the max.

**Comment by AdamDN** [comment]
> Is perhaps one of the resolution or UI overrides set in the Preferences.json file?

It doesn't appear to be this, they are all set to -1. 
```
    "Override_Resolution_Width": -1,
    "Override_Resolution_Height": -1,
    "Override_UI_Scale": -1.0,
    "Override_Fullscreen_Mode": -1,
```

> I just tried closing and restarting the game with a variety of resolution+scale combos and it seemed to restore properly.

I believe the issue is something to do with changing settings from in-game, not from the main menu. Or perhaps making changes on the menu, then more changes in-game? I'm struggling to find the exact combination to replicate the same results every time, despite this happening almost every time I launch the game.

I've also just clipped this. 
https://imgur.com/RyLmoAa
It's slightly unrelated as the main bug I'm reporting is the settings not saving between game restarts, but in this clip it decided to change while loading into a server. You can see the scale of the loading bar change mid-load.
At the start of the clip the resolution is 1280x720 with a scale of 0.6. By the end of the clip the resolution is 3840x2160 and the UI Scale was set to 0.
It's also worth noting that immediately after this clip I set the resolution back to 1280x720, the UI Scale to 0.6 using the in-game display menu, and used the Quit to desktop button from in-game. 
Re-launched the game to be faced with this screen again: 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71527679/178072411-7770d56e-aca3-4b8d-9eda-15a2ca1f6aa7.png">
With 1280x720 res and a scale of 2.0.

And then to top it all off, while messing around and switching between resolutions to try and find you a more sure-fire way to replicate it yourself, I got a blast from the past with the old-school alien text bug haha. 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71527679/178072190-3ce77802-c4e0-40fc-ba30-165411736ece.png">

**Comment by SDGNelson** [comment]
That's bizarre... thanks for the clip! I will also see what could possibly be changing the UI scale during the loading screen :confused:

**Comment by AdamDN** [comment]
> I have not found any reason why these things would be happening unfortunately, but for the next update I have added more logging for UI scale and resolution changes to maybe catch something.

Has the additional logging been added? I'd be happy to send over the logs of a play session where it has happened - but a quick scroll through them myself and I can't seem to find any new logs regarding scale/resolution.

**Comment by SDGNelson** [comment]
Yes, they should be in the most recent update. It should be logging anything related to those :confused:

**Comment by AdamDN** [comment]
I've just checked again - it does indeed have some logs of the changes.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9162085/Client.log)

**Comment by SDGNelson** [comment]
Was there any issue after starting up with that log? It does not look like the UI scale got reset or clamped in that log.

**Comment by AdamDN** [comment]
The log attached above was during a session where the game launched in 1280 x 720, with a Scale of 2.0, and then the resolution was changed to 3840 x 2160 with a Scale of 0.6 when a server was connected to. 

I've recreated it while recording - here is a video including two full launches. 
https://youtu.be/nM2fgfq5P4s

Launch 1 
The game launches in 1280 x 720 with a Scale of 0.6. 
Connecting to a server forces it into 3840 x 2160 with a Scale of 0.6. 
In-game the resolution and scale were manually set to 1280 x 720 and 0.6 again, and the game was closed and reopened.

Launch 2
Launched as you would expect, opening with the last used resolution and scale, and connecting to a server did not change it.
 
[Launch1.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9162910/Launch1.log)
[Launch2.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9162911/Launch2.log)

This is just focusing on the issue of the resolution changing when connecting to servers, and it is pretty easily repeatable. The issue with the game launching with a different resolution/scale than it was closed with is less repeatable but I can get a clip/logs of that too next time it happens.

**Comment by SDGNelson** [comment]
I have no idea why it is changing. I tried reproducing even with the same settings, but could not replicate when joining server. Not sure what it would be but perhaps an external application is changing the resolution, or something built-in to Unity?
