### ISSUE TITLE
Do anything with internal classes and methods faster

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3296]
I love you so much, dear Nelson, please do public, NO INTERNAL all you new stuff associated with structures FASTER THAN 2 months or one year😀😀😀😀.

No pillars system hardcoded in my server, and I'm forced to close it before you fix it.

When you publish new super cool mega duper updates, make sure that you can at least fix them without your help.

**Comment by SDGNelson** [comment]
Code that is not intended to be used (at least not yet) by plugins is not marked public.
