### ISSUE TITLE
Very important questions about structures

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3297]
You have already updated the game and while the plugins do not need to use the new code, I have 2 questions:
1) NOW How i can get a pillars position?
2) I have been developing a structure stability system for 2 months now, when I should be busy rewriting it so that nothing breaks and the code is public?

**Comment by SDGNelson** [comment]
1. Pillar position should be the same as before (none of the sizes have changed)

2. Sorry to interfere with your stability system. This is a tricky problem if I am also working on housing improvements, but in general all public APIs will be kept backwards compatible *EXCEPT* for the RPCs which are only public for calling by the generated code.
