### ISSUE TITLE
[AssetParametRequest] Recent Update Structure

### ISSUE THREAD

**Issue by 0x646F317068696E3732** [SmartlyDressedGames/Unturned-3.x-Community#3299]
Hi all!

At the moment, when installing the wall or ceiling, there is a static check for the presence of pillars and this is not good, because it broke several implementations of ideas from **RUST** , but it made me think about the parameter in the structure asset.

1. I would like to get a simple parameter **as soon as possible** that allows / disables checking for the presence of pillars.
2. It might be convenient to create blueprint parameters that check for the presence of other structures nearby to set structures. For example, it would be possible to build a ramp only if there were 2/3/4 pillars (possibly with an ID check).
Thank you.
https://i.imgur.com/ZnTELQ8.png

**Comment by Foks132** [comment]
Yes, that would be really great

**Comment by GazziFX** [comment]
Said that in another issue https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3294#issuecomment-1178413029

**Comment by SDGNelson** [comment]
Officially supporting building without pillars is on my to-do list 👍
