### ISSUE TITLE
Killing/Destroying Quests

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3300]
Hello,
as you may know, every single quest condition (Kill Animals, Zombies, Trees, Players | Destroy Objects) that somehow increment a flag value by 1 by doing some action, counts it for every single player that have the same quest active. Would it be possible to move on from this system and make it so it counts it specificaly only for the player that made the action? (Ex. I kill ingame someone, my quest increments by 1 and it increments it only for me, not for everyone else.)

I would also like to ask about specific locations these quest conditions can be made in. Currently only Kill zombies and destroy objects can be in a specific location; why wouldn't we have it as well for kill animals, trees and players? 

This could definitely make quests a little more challenging (And I could play around more with quests) as now with a (ex.) 100 kill player condition, some players are just AFKing inside of safezone waiting for people outside to kill eachother and thus completing the quest without doing anything.

**Comment by SDGNelson** [comment]
The reason for crediting nearby players was that if players are working together it would suck to not make progress on the quest. In the future it would be nice to track who has dealt damage to the target recently and credit those players specifically.

**Comment by Darkmega18** [comment]
sounds good. where possible. for bosses etc.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
