### ISSUE TITLE
France Building Bug

### ISSUE THREAD

**Issue by realtrollman2319** [SmartlyDressedGames/Unturned-3.x-Community#3303]
title says it all, here's a detailed view
we were building a safezone tower, but the issues appeared once we built up higher, when i salvaged some stuff, it was blocked even nobody is blocking it
![image](https://user-images.githubusercontent.com/108993392/178115221-ac140fc4-bf45-4f9b-9f08-0759a551483
![image](https://user-images.githubusercontent.com/108993392/178115274-d7ca0ef4-f371-4fc6-abec-64b00e85b0b2.png)
4.png)

**Comment by KodakDolph** [comment]
I believe related to https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3293

**Comment by KodakDolph** [comment]
Players also reporting having issues placing down items where they should be allowed on my servers.

**Comment by KodakDolph** [comment]
![Uploading 09CBF22D-80C2-4105-B19B-ACAA04488EF8.jpeg…]()

**Comment by KodakDolph** [comment]
![3532816A-73CE-4BC0-A675-2AFB672765D6](https://user-images.githubusercontent.com/105953666/178119467-6762fdb5-880e-455b-bbd6-a63595adb9d9.jpeg)

**Comment by SDGNelson** [comment]
In this image it is being blocked by the floating wall to the left. Currently it does not know the wall is connected if the floor is removed. This will be improved as part of supporting building downwards.
