### ISSUE TITLE
[Suggestion] Limit to what server owners can set the "exit/quit" timer to.

### ISSUE THREAD

**Issue by XanderCodes** [SmartlyDressedGames/Unturned-3.x-Community#3305]
Hiya.

Just a quick suggestion to impose a maximum limit on what server owners can set the "exit/quit" timer to on the game's pause menu.

I recently went to leave a new server and found out I had to wait ~2 minutes to leave the server or exit the game. Not really a massive issue, but is certainly annoying.

That's all.
Thanks :D

**Comment by SDGNelson** [comment]
Fair point! Will limit to 60 seconds for the next update.

**Comment by XanderCodes** [comment]
Cheers!
