### ISSUE TITLE
Falsely banned from Discord server

### ISSUE THREAD

**Issue by AhmedQureshi-CEO** [SmartlyDressedGames/Unturned-3.x-Community#3307]
I was falsely banned for alts, yet I have no alt accounts in the discord server

**Comment by AhmedQureshi-CEO** [comment]
Ahmed Qureshi#4293

**Comment by SDGNelson** [comment]
Closing as off-topic for this repository. This would need to be resolved with the relevant Discord server moderators, sorry.
