### ISSUE TITLE
[Suggestion] in world quick collect and in GUI Hold and slide auto collect/store

### ISSUE THREAD

**Issue by Darkmega18** [SmartlyDressedGames/Unturned-3.x-Community#3308]
It can be a pain when you need to quickly pick up a large amount of drops repeatedly, such as hitting a few trees into an area, a box that you just salvaged and everything dropped out, a salvaged/exploded car, a dropped inventory of clothing taken off, a large amount of items within a box, a dead friend/foe, etc.

I'd like to suggest the ability to hold your pick up key in world, potentially with some permutation of additional button context that can allow you to rapidly collect all items you're capable of collecting in the reachable area, or atleast repeatedly collect items as you mouse over them for situations like these.

Similarly, sometimes you just want to pick up and move a whole load of items you've dumped off somewhere into a crate, or from the crate to yourself to then craft something. The ability to hold down click and then just move the mouse over the next things in the inventory to also move them would be a useful addition to prevent repetitive clicking pains.

consider it something similar to "mouse tweaks" mod in minecraft for the inventory.

Players could also turn this on and off in settings or perhaps in the inventory somewhere so that if it's actually get in the way or they keep doing it by accident when they don't want to it can be reverted.

**Comment by GazziFX** [comment]
Nelson, can you also add something like this in long term, when you rewrite the inventory

https://user-images.githubusercontent.com/43498426/178330261-43cfcc49-2fb7-4a33-9dd4-ec7ee2e37e27.mp4

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by Darkmega18** [comment]
Gotcha. sorry for the stress. :<

**Comment by SDGNelson** [comment]
No don't worry! Sorry, I didn't mean to imply it was anyone's fault. I later posted a summary here explaining the chain of events: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3641
