### ISSUE TITLE
[Bug] Non-Unturned Steam Game Servers in Server Browser

### ISSUE THREAD

**Issue by IAmSilK** [SmartlyDressedGames/Unturned-3.x-Community#3309]
A LAN ARK Survival Evolved server is showing up in the LAN section of the Unturned server browser. Might occur elsewhere, but this is where I saw it.

![image](https://user-images.githubusercontent.com/16708907/178329115-9e5e5d08-1458-4781-bb4a-3c8a9ca49515.png)

**Comment by IAmSilK** [comment]
More interesting info - crazy how well it actually shows in the Unturned browser.
![image](https://user-images.githubusercontent.com/16708907/178329295-e403340f-cb63-4f40-b65f-0fceccdd207f.png)

**Comment by SDGNelson** [comment]
That's... weird. I am surprised Steam does not automatically filter out servers for different games. Fixed for the next update, thanks!
