### ISSUE TITLE
[Minor Bugs] Inconsistent Mannequins

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3311]
Just some very minor issues with mannequins. 

1) The arrow when placing mannequins doesn't point the way the mannequin will be facing, the way it does with signs and other barricades. 
![mannequins1](https://user-images.githubusercontent.com/71527679/178586625-0242fc59-d31c-4719-aa87-9e8af93faabe.gif)
Personally I think it would make sense for _all_ barricades to be facing towards the player by default, (with only a few rare exceptions e.g. the claymore) - but the mannequin being the only object to place opposite of the arrow leads to it constantly being placed the wrong way. 

2) Clicking the pose button too quickly will change the text but not the pose.
![mannequins2](https://user-images.githubusercontent.com/71527679/178586311-d5566588-7e6d-4ac7-8f22-abc724925b79.gif)

**Comment by GazziFX** [comment]
2. RPC Limit

**Comment by SDGNelson** [comment]
Thanks for the report! Yeah I suspect #2 is from the set pose RPC rate limit.
