### ISSUE TITLE
Auto Updater Going Crazy Lol

### ISSUE THREAD

**Issue by KodakDolph** [SmartlyDressedGames/Unturned-3.x-Community#3316]
Hey, set the auto updates up in config.json. My servers have restarted like 3 times now but haven’t seemed to actually apply the update. Don’t know if anyone else is having the same.

**Comment by KodakDolph** [comment]
I had just set the config.json option to true for the new auto updates. 

Was there another step I was supposed to have taken?

**Comment by SDGNelson** [comment]
It does not install the update automatically - only restarts if an update is detected

**Comment by MoltonMontro** [comment]
> Was there another step I was supposed to have taken?

You should refer to the [patch notes](https://store.steampowered.com/news/app/304930/view/3319730991365422626) that introduced this feature. Specifically, this quote:

> ## Practical Application:
> 
> These options are most useful in conjunction with a script that updates and restarts the server in a loop. For example this Windows .bat script can be placed in the steamcmd folder to infinitely update and restart the server:
> 
> ```@echo off
> rem @ suppresses echo command from being echoed, and then disables echoing in this script.
> 
> rem This is a label for use with "goto". The script will return to this label to update and restart the server.
> :loop
> 
> rem %~dp0 expands to the path to this script's directory, allowing it to be called from a different working directory.
> rem The "/wait" option pauses our script until steamcmd is finished.
> rem Start steamcmd, download latest version of Unturned Dedicated Server, then close cleanly.
> echo Updating...
> start "" /wait "%~dp0steamcmd.exe" +login anonymous +app_update 1110390 +quit
> 
> echo Finished update! Launching server...
> start "" /wait "%~dp0steamapps\common\U3DS\Unturned.exe" -batchmode -nographics +InternetServer/MyServer
> 
> echo Server has exited. Restarting after timeout...
> echo:
> echo Press CTRL+C and then Y during this timeout to cancel restart.
> timeout 10
> 
> rem Return to the "loop" label to update and restart the server.
> goto loop```
