### ISSUE TITLE
Blood decals hidden when "Blood Splatters" disabled

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3318]
**Context:** Manually-placed blood decal objects cannot be disabled, although "Blood Splatters" from damaging entities can. Often, the reasoning for disabling blood splatters is that the player is younger (or is playing with a younger family member), and blood is either too scary or not quite family-friendly enough.

**Issue:** Manually-placed blood decals (**Graffiti_7**) are not as graphic as blood splatters, but I feel like it's a similar idea. Perhaps there should be a way to disable these as well?

**Suggestion:** There could be a property for _Type Decal_ objects, syntax being something like _Is_Blood true_. And then either the current "Blood Splatters" setting could disable it, or there could be a new setting specifically for disabling other types of blood/gore that aren't caused due to hit effects.

**Comment by SDGNelson** [comment]
Very good point! Thanks for bringing this up. I will change this for the next update.
