### ISSUE TITLE
"Requires_Pillars" - for the walls, and the roof?

### ISSUE THREAD

**Issue by ArtemD7265** [SmartlyDressedGames/Unturned-3.x-Community#3319]
Added a parameter for walls that allows you to place walls without pillars. But then how to install the roof? 
Shouldn't a wall with disconnected pillars completely replace them? Including for the installation of the roof. 
If there is 1 wall, it should be possible to install a roof!?

*sorry if it's unclear... I use a translator*

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time. In the same update it was changed to snap roofs to walls.
