### ISSUE TITLE
[Feature Request] Safezone Volumes in Devkit

### ISSUE THREAD

**Issue by Gorge420** [SmartlyDressedGames/Unturned-3.x-Community#3321]
Please add Safezone Volumes to the Devkit so you dont have to use 50 circles to make a square. Thanks

**Comment by surv0013** [comment]
Devkit will be removed, Nelson is now migrating functions from it to the default map editor.

**Comment by Gorge420** [comment]
> Devkit will be removed, Nelson is now migrating functions from it to the default map editor.

Yeah I know but you still cant have box shaped safezones without using a ton of nodes based zones.

**Comment by DrDallas1** [comment]
Were they removed? I remember safezone volumes (with square shapes) being a thing on devkit, I even have a video of me using it... about christmas? Try reverting your game to an earlier version (back everything up of course) and then place that volume on your map.

**Comment by DrDallas1** [comment]
+ You could probably just get the actual unity script for it and attach it to an object, easier to manipulate + it would be in normal editor!

**Comment by Spebby** [comment]
> Or, you could probably just get the actual unity script for it and attach it to an object, easier to manipulate + it would be in normal editor!

While this would theoretically work it's not ideal and an in-built solution would be prefered.

**Comment by Spebby** [comment]
Also
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1292
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2008

**Comment by Spebby** [comment]
this has now been resolved, please close!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
