### ISSUE TITLE
Server log spammed with "shader unsupported"

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#3322]
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
Is there anyway to turn these off? It absolutely clogs the console

**Comment by SDGNelson** [comment]
Unfortunately no way to turn it off - Unity writes these to standard output.

**Comment by Brittank88** [comment]
Despite being closed this is still a present issue with the latest version of U3DS.

**Comment by Mysterious-Wrangler** [comment]
Still an issue. This makes the server start very very slowly, it doesnt always happen at startup. It has a mind of its own and does this at random, like wth. Also i get "Boxcollider does not support negative scale or size". When it starts doing this i just close the program and start the server again.

**Comment by DanielWillett** [comment]
Sometimes you just have to hit enter for it to catch up and show the normal logs.

**Comment by Mysterious-Wrangler** [comment]
> Sometimes you just have to hit enter for it to catch up and show the normal logs.

Thank you, that worked. Never was this bad before but hitting enter worked. Server console behaving weird today.
