### ISSUE TITLE
Game mode is working?

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#3323]
I've been looking at the "Default_Game_Mode" parameter for a long time and I can't figure out how to add my custom game mode to the map?

**Comment by Spebby** [comment]
I'm unsure what your question is exactly. I poked around for the "Default_Game_Mode" parameter and came up short. I assume you're trying to add a custom label to the map on the map selection screen that states a custom mode. (Ex. "Survival", "Arena", "Deathmatch", "Parkour") I will include the relevant info from Dango's config and language files.

If all you want to do is change the label, just add `GameModeLabel MODE` to your English.dat and how many other localisations you have. I recommend setting your map to a survival map under the hood, so you have more flexibility with any other parameters you may be attempting to add.

While not required, I recommend adding the following to your map's Config.json
`"PlayerUI_FoodVisible": false,
"PlayerUI_WaterVisible": false,
"Mode_Config_Overrides":
{
	"Players.Virus_Infect": 0,
	"Players.Food_Use_Ticks": 0,
	"Players.Water_Use_Ticks": 65000,
	"Players.Food_Damage_Ticks": 65000,
	"Players.Water_Damage_Ticks": 65000,
	"Players.Lose_Skills_PvP": 1,
	"Players.Lose_Skills_PvE": 1,
	"Gameplay.Timer_Respawn": 0,
	"Gameplay.Timer_Home": 0
},`
These config lines allows you to effectively ignore those pesky food and water stats.

**Comment by surv0013** [comment]
> I'm unsure what your question is exactly. I poked around for the "Default_Game_Mode" parameter and came up short. I assume you're trying to add a custom label to the map on the map selection screen that states a custom mode. (Ex. "Survival", "Arena", "Deathmatch", "Parkour") I will include the relevant info from Dango's config and language files.

I want to replace the character's GameObject.

LevelAsset.cs
```CS
[Inspectable("#SDG::Asset.Level.Default_Game_Mode.Name", null)]
public TypeReference<GameMode> defaultGameMode;
```

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time. That feature was started but never finished unfortunately. (sigh)
