### ISSUE TITLE
[Feature Request] More context (and solutions) to error messages

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3324]
**The issue:**
Error messages (in particular, ones that require the user to _do something_ to fix them) can seem vague, especially for the younger players. 
A quick search on the official Discord shows that many others are struggling with errors such as the Missing Asset error. 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/71527679/179429499-af4c879c-fab0-4342-9c66-5c4ab0fe5079.png">
and on my own Discord we receive so many help requests (almost daily) from players that we had to set up an automatic response explaining what the error means and how to fix it.

**The request:** 
The error messages should reworded to explain the issue in more child-friendly, and user-friendly terms, along with suggesting a potential fix. 
E.g:
> You were kicked from this server because: missing asset: "example" File: "example" Id: 123

could be replaced with:
> The server you are attempting to connect to uses an asset which you are missing. 
> Missing asset: "example" File: "example" Id: 123
> This asset is from the "Example" Workshop Mod.
> **Try unsubscribing from the effected Workshop Mod, and then restart Unturned.**

and 
> Modified or corrupted asset: "Metal Door" File: "Door_Metal" Id: 8d0b21995b084db3a91bb7a75d777f75 Client: A88B84C49E421A4CB473F57AD11AB02A68FA5042 Server: 9820E0243C65846D2D0A50B1F89331D4AF65EC1A

this error contains a ton of information that is useless and confusing to the average user. 
It should still contain the vital information for troubleshooting, but the main message should be more user-focused.
Example: 
> The server you are attempting to connect to uses a modified version of an asset you have downloaded.
> The asset: "Metal Door" does not match the server's asset. 
> This asset is from the "Example" Workshop Mod.
> **Try unsubscribing from the effected workshop mod, and then restart Unturned.**
>
> File: "Door_Metal" Id: 8d0b21995b084db3a91bb7a75d777f75 
> Client: A88B84C49E421A4CB473F57AD11AB02A68FA5042 
> Server: 9820E0243C65846D2D0A50B1F89331D4AF65EC1A

Similarly, the error about Asset bundle version mismatch could also suggest unsubscribing from workshop mods, and this one: 
> "Server missing unknown asset? (should never happen) Id: 72623cb33e4695e27273697a3e4f7665"

(which happens very often, by the way)
(from my experience it's usually caused by a corrupted sign placed somewhere on the map) 
Could suggest contacting the server owner to report the issue.

For bonus points, how possible (and ethical) would it be to include an optional button which deletes the files of the affected mod, allowing it to re-download next time Unturned is opened? 

Whatever the solution/change may be, I think something needs to be done as I have seen first hand that many users have seen these errors and assume it's an issue with the server, completely unaware that it could be something that they're capable of solving themselves.

**Comment by Spebby** [comment]
Excellent! I can see this benefitting not only server creators, but also map makers that include custom content. A lot of comments modders get are in regards to errors like this, it would be extremely helpful if the game provided more information regarding the errors, and how to fix them!

**Comment by ZanyISP** [comment]
This is Amazing! I wish this was more accessible. Took me Hours and Finally checking the Issues in the repository to find this!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
