### ISSUE TITLE
random disconnects

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#3325]
i have been watching my servers since starting of june, and i can see there are random disconnects, where all players suddenly disconnect. this happens multiple times during the day.
the error message player gets is "this server lost your connection"
what could be the possible reason?
anyone else having similar problem?

**Comment by aman7** [comment]
i checked, i think they are fine. some of players from my server reported these error message after getting kicked.
`You were kicked from this server because: significantly exceeded SDG.Unturned.ObjectManager.ReceiveToggleObjectBinaryStateRequest rate limit (10 times in 0.5 seconds)`

`You were kicked from this server because: significantly exceeded SDG.Unturned.PlayerEquipment.ReceiveEquipRequest rate limit (10 times in 0.2 seconds)`

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time!

TH3AL3X was probably right about it being stuck in the main thread. The kick message there suggests the server froze while the client repeatedly tried to use the object, so when the server resumed and processed all those requests it hit the rate limit.

For anyone who runs into it in the future, here is the support article: https://support.smartlydressedgames.com/hc/en-us/articles/12236562526228
