### ISSUE TITLE
I don't understand the error

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#3329]
Often seen in the background of the server
Curl error 28: Failed to connect to smartlydressedgames.com port 443 after 26250 ms: Timed out

**Comment by jatapa** [comment]
I am not 100% sure why it tries to connect the the SDG website.
but basically the error means that it failed to connect to the SDG website using the HTTPS port.
I think that should not cause any issues not 100% sure tho.

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time. cURL was probably writing to standard output when unable to retrieve the latest game version or something.
