### ISSUE TITLE
put items in unturned chest rocketmod

### ISSUE THREAD

**Issue by L0rdL0ther** [SmartlyDressedGames/Unturned-3.x-Community#3330]
hello, I've been trying to add and remove things to the cabinets thanks to the unturned plugin, I've been looking for a long time, but I couldn't find anything, I'm writing here as a last resort, please tell me.

**Comment by GazziFX** [comment]
InteractableStorage storage = ...
storage.items.tryAddItem(new Item(id));

**Comment by L0rdL0ther** [comment]
thx bro thx

**Comment by jatapa** [comment]
you could ask for help in LDM community discord https://discord.gg/w8SJUWrx or in a discord like imperil plugins
also should close the post now that you got your owner
