### ISSUE TITLE
Recent event and concerns with Unity engine.

### ISSUE THREAD

**Issue by Glass47** [SmartlyDressedGames/Unturned-3.x-Community#3331]
Hey Nelson, i recently come across [this ](https://www.youtube.com/watch?v=R6xUVQKCsAk )video, i would advise you to watch it and tell me what do you think regarding it. I am a bit concerned. Best regards.

**Comment by GazziFX** [comment]
InstallCore is just SDK, it not include unwanted apps or malware as default, and its also deprecated.
https://youtu.be/HobK9kug-Lo?t=493

**Comment by SDGNelson** [comment]
Unity's disappointing leadership aside, if they did put something bad into the core engine we would lock into an LTS version until they reversed their decision.
