### ISSUE TITLE
(Kind of a Feature request) Increase Wall/Pillar/Roof/Side Hook's modability after the 3.22.12.0 + 3.22.13.0 update

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#3333]
I haven't tried to fully manipulate the side and positioning of the wall hooks in structures prior to the two updates, only recently just tried to do so.

One difference between the examples assets given after the update and prior to the updates is that there are no more hooks to the structure prefab.

I thought to add the wall hook to the structure prefab anyway to give the cube prefab a go.
No matter what I changed of the wall hooks, it doesn't take hold now. It will always default to the vanilla wall size and vanilla wall hook's position (Which, to the custom floor cube structure, looks like the next cube wall I am supposed to place is in the mid air).

Since we can previously adjust the position and size of the other structural hooks, would it still be good to have that ability sometime after the structure rework is finish? (So we can mod custom structures again without conforming to the exact vanilla sizes + allow more flexibility, less collision compared to being snapped automatically)

Erm thanks :)

**Comment by SDGNelson** [comment]
Sorry, they were never meant to be different sizes before. Different sizes might be supported further down the road, but will need to be supported in vanilla first.

**Comment by Ongjming** [comment]
Hmm even for the same sizes, I realised for some of the custom structures (like custom pillar hook placement position for structures), prior to the update they are fine, now they default to whatever their structure type is regardless of pillar hook positions. (Floor type structure defaults to 2 pillar hooks near the center of the structure origin. Other structure types lost the pillar hook altogether, haven't tested with roof types)

Was hoping the hooks could still be modable instead of being reverted to hardcoded.

**Comment by Ongjming** [comment]
After fiddling around a bit more, realised that after the update, structures like the floor would default its 4 pillar hooks + Roof hook +wall hooks + side hooks to the center origin of the Structure gameobject. This makes vanilla default sized hooks but custom location hooks for custom structures difficult to snap on each other due to the forced positioning of the mentioned hooks instead of being moddable like before the update. Even with "Has_Clip_Prefab true", it will still disregard the Clip's hook information and still set it at the center origin of the Structure gameobject.

Sorry if my prior message made it seemed like I was looking for custom dimension sized hooks, I just wanted the ability for the vanilla sized hooks with different placement locations to be available as before the update.

Erm if I can't phrase it well enough I can elaborate more, brain is tired after the fiddling at this time :)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
