### ISSUE TITLE
[BUG REPORT] Interactable buttons freakout in map editor

### ISSUE THREAD

**Issue by LiamDoubleU** [SmartlyDressedGames/Unturned-3.x-Community#3334]
Quickly any buttons in the map editor such as the ones in the settings tabs or the ones at the top allowing you to switch between terrain, environment etc causes them to wildly click by themself. I have tested my mouse to see if it was my hardware but it does not appear to be.
Video attached below

https://user-images.githubusercontent.com/109856071/180603298-407c67d6-b17a-40de-b004-0323a2cf64bc.mp4

Edit 1:
Okay, this is happening with basically ALL clickable buttons, still testing my mouse and im not getting the same issue while clicking on a CPS tester etc. My mouse does not have to stay on the button for the clicking to continue either.

**Comment by LiamDoubleU** [comment]
Okay, this is happening with basically ALL clickable buttons , still testing my mouse and im not getting the same issue while clicking on a CPS tester etc.

**Comment by SDGNelson** [comment]
Maybe it is being treated as a repeated keystroke? Similar to how when you hold a letter key it gets faster.

**Comment by yeeterPan** [comment]
> Maybe it is being treated as a repeated keystroke? Similar to how when you hold a letter key it gets faster.

Im having an issue similar to this but in game and in the menus and its a little more severe

**Comment by SDGNelson** [comment]
Sorry that I didn't reply at the time. This was the only report I got of it so hopefully it was a one-off. If still happening feel free to comment and I will re-open. I would guess it is something in uGUI / not directly fixable unfortunately.
