### ISSUE TITLE
Request to join Rocket Get All Permissions Group

### ISSUE THREAD

**Issue by hksz** [SmartlyDressedGames/Unturned-3.x-Community#3339]
RocketPermissionsHelper
Add
public List GetAllGroup()
{
return this.permissions.Instance.Groups;
}

RocketPermissionsManager
Add
public List GetAllGroup()
{
return helper.GetAllGroup();
}

IRocketPermissionsProvider
Add
List<RocketPermissionsGroup> GetAllGroup();

**Comment by QERT2002** [comment]
Rocket is open source project, you can edit source code and bundle you own rocketmod:/

**Comment by rube200** [comment]
First, this repository is for Unturned and not LDM so you should ask it in the correct repository.
Second you can obtain it using reflection.

**Comment by hksz** [comment]
> First, this repository is for Unturned and not LDM so you should ask it in the correct repository. Second you can obtain it using reflection.

I've already asked a question on Legally Distinct Missile, but no one is paying attention to me
I don't know much about reflexes, but I do now, thanks for your help!

**Comment by hksz** [comment]
Solutions

XMLFileAsset<RocketPermissions> permissions = new XMLFileAsset<RocketPermissions>(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "Permissions.config.xml"));
List<RocketPermissionsGroup> groups = permissions.Instance.Groups;

**Comment by GazziFX** [comment]
> Solutions
> 
> XMLFileAsset permissions = new XMLFileAsset(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "Permissions.config.xml")); List groups = permissions.Instance.Groups;

Might not be good idea as it wont update on `permissions reload`

**Comment by hksz** [comment]
> Correction, replace Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "Permissions.config.xml") with System.IO.Directory.GetCurrentDirectory() + "\Permissions.config.xml"

Missing a symbol "\"

**Comment by hksz** [comment]
Correction, replace
Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "Permissions.config.xml")
with
System.IO.Directory.GetCurrentDirectory() + "\\Permissions.config.xml"

**Comment by hksz** [comment]
![屏幕截图 2022-10-18 232435](https://user-images.githubusercontent.com/51861438/196474033-ef386523-115f-4ff0-9cdb-5c09ffcdfc26.png)

**Comment by rube200** [comment]
Why would u do that instead of using reflection

**Comment by hksz** [comment]
> reflection

Because I still haven't figured out how to use

**Comment by GazziFX** [comment]
```csharp
var helperField = typeof(RocketPermissionsManager).GetField("helper", BindingFlags.Instance | BindingFlags.NonPublic);
var helper = fieldInfo.GetValue(R.Permissions);
var permissionsField = helper.GetType().GetField("permissions", BindingFlags.Instance | BindingFlags.NonPublic);
var permissions = (Asset<RocketPermissions>)permissionsField.GetValue(helper);
```

**Comment by hksz** [comment]
> ```cs
> var helperField = typeof(RocketPermissionsManager).GetField("helper", BindingFlags.Instance | BindingFlags.NonPublic);
> var helper = fieldInfo.GetValue(R.Permissions);
> var permissionsField = helper.GetType().GetField("permissions", BindingFlags.Instance | BindingFlags.NonPublic);
> var permissions = (Asset<RocketPermissions>)permissionsField.GetValue(helper);
> ```

This is very useful, thank you very much!
