### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3340]
Hi, 
I got a question about vanish.
From what I understand when player goes into vanish the model is teleported to (0,0,0) position in the map.
Is there any way to change that loaction? I have looked into the source code and wasnt able to find where the zero location is defined.
Would appreciate some hints on how to change it.

**Comment by QERT2002** [comment]
You need to edit rocketmod, or use harmony to patch vanish method.

**Comment by fahrettinenes** [comment]
You can try harmony, that will help you.

**Comment by SmallBerry** [comment]
In order to use harmony I need to know which method to patch,
After using the decompiler and checking the files I was unable to find where exactly the (0,0,0) vector is defined.

**Comment by QERT2002** [comment]
![image](https://user-images.githubusercontent.com/39222548/181080852-8f03d439-73dc-4938-aee7-a0590430e47f.png)
Man you are very bad coder if you cant find vanish position:/

**Comment by SDGNelson** [comment]
Before closing this:

@SmallBerry I know it was a while ago, but don't let what QERT2002 said get to you. We all gradually get better at these things and everyone is at a different point in their journey. Best wishes and good luck to you in your projects!
