### ISSUE TITLE
[Bug Report] Object/Resource bug outside world border on large maps

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3343]
https://user-images.githubusercontent.com/47935791/181679741-e8a82130-fcad-4a89-9d12-56f5eab279b3.mp4

video shows off the bug. This was recorded north of the border on an insane sized map, outside the chart's bounds.

problematic because it severely prohibits detailing outside the map, leaving terrain looking very bare.

**Comment by SDGNelson** [comment]
Currently most of the systems are designed with "insane" as the absolute maximum size. Are you at this border on California?

**Comment by Spebby** [comment]
> Currently most of the systems are designed with "insane" as the absolute maximum size. Are you at this border on California?

Yep
