### ISSUE TITLE
Interactability_Conditions with Flag_Short

### ISSUE THREAD

**Issue by felipedual** [SmartlyDressedGames/Unturned-3.x-Community#3344]
Hello. I would like to know if it is possible to put a flag_short condition on interactable objects? If yes, I would like to know how to do it.

**Comment by Ongjming** [comment]
Erm felipedual, so is it possible to put flag_short condition on interactable objects? I am assuming it is possible but haven't tried it, hence asking out of curiosity. Thanks!

**Comment by felipedual** [comment]
> Erm felipedual, so is it possible to put flag_short condition on interactable objects? I am assuming it is possible but haven't tried it, hence asking out of curiosity. Thanks!

Yeah, its possible.
