### ISSUE TITLE
[Bug Report] Collision box issue in Editor

### ISSUE THREAD

**Issue by wybiral** [SmartlyDressedGames/Unturned-3.x-Community#3346]
## What's happening
There's a glitch in the map I've been editing where a large region is completely blocked off by an invisible barrier when I test play it. There are no objects there as far as I can find and the terrain is normal but the player can't walk into a certain rectangular zone. It's nowhere near the boundary of the map either.

## What I think caused it
I placed "Lobby 2" in my map not knowing what it was and deleted it after I saw how huge it is. That area seems about the size of this collision glitch, so maybe the collision boundary for that wasn't deleted when the object was? Tat could just be a coincidence and a simply test of doing the same thing didn't reproduce it.

## Details
I'm using Windows with Unturned 3.22.13.0

I can supply the level files if it helps to debug. I'm not sure how the game stores collision boundaries or objects so I can't dig into those files but if there are any docs for those formats I can see if anything looks wrong.

**Comment by SDGNelson** [comment]
Sure, if you can email me the map zip I can load it up and take a look.

**Comment by wybiral** [comment]
Thanks for your help Nelson. I'm closing this issue because it was user error on my part.

For anyone who has the same issue, here's what I did wrong and how I fixed it: I used the building Lobby # 1 on a map, not realizing it was designed for arenas to keep players inside, and that was causing invisible walls. Deleting that building solved the problem!
