### ISSUE TITLE
Theft in Workshop

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3347]
One person downloaded my mod, and uploaded it under his own name for use on his server, how do I file a complaint against him?

**Comment by GazziFX** [comment]
![image](https://user-images.githubusercontent.com/43498426/182043611-d7b78549-a26b-4730-b494-2a21303543bc.png)
![image](https://user-images.githubusercontent.com/43498426/182043615-eda02db8-7c75-4450-b063-af8e6495cfe0.png)
![image](https://user-images.githubusercontent.com/43498426/182043622-42c9fd4b-e07a-4306-9448-07954566769f.png)

**Comment by MoltonMontro** [comment]
> One person downloaded my mod, and uploaded it under his own name for use on his server, how do I file a complaint against him?

Users can file copyright complaints here:  https://steamcommunity.com/dmca/create/  and Steam's DMCA team receives the complaints directly.
