### ISSUE TITLE
[Bug]The map editor cannot edit the newly created map.

### ISSUE THREAD

**Issue by prank0011** [SmartlyDressedGames/Unturned-3.x-Community#3348]
After editing, the progress bar will stop somewhere.
After deleting the Terrain folder, the progress bar can be loaded, but the game will crash when finished.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9242620/Client.log)

**Comment by GazziFX** [comment]
I think this is reason `The AssetBundle 'Materials.unity3d' can't be loaded because another AssetBundle with the same files is already loaded.`
Try to remove other custom maps from folder and unsubscribe from workshop maps

**Comment by prank0011** [comment]
I found that the crash was caused by other reasons, but I still don't know what the reason is.

**Comment by prank0011** [comment]
> I think this is reason `The AssetBundle 'Materials.unity3d' can't be loaded because another AssetBundle with the same files is already loaded.` Try to remove other custom maps from folder and unsubscribe from workshop maps

I tried to delete the Terrain folder in mid-July, and then I can enter the editor, but after entering, I have to paste the Terrain folder back again and save it, otherwise I won't save the terrain.

**Comment by prank0011** [comment]
When I try to edit other maps, the game crashes after the progress bar runs. This is the crash log
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9248700/Client.log)
.

**Comment by SDGNelson** [comment]
I will fix the exception for the next update. As for unable to load the map could you send me a zip of the map and I will try loading it please?

**Comment by prank0011** [comment]
> I will fix the exception for the next update. As for unable to load the map could you send me a zip of the map and I will try loading it please?

I send it to others for editing, and they can open it, but I will pop up this window. I tried to verify the integrity, but it still didn't recover.
![aa](https://user-images.githubusercontent.com/68633558/182773057-8a5d5db1-614b-4e85-8f2a-2770acf7e974.jpg)
[Map.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9256963/Map.zip)

**Comment by prank0011** [comment]
This is a damaged map file, which seems to be caused by the mod.
[Map.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9256984/Map.zip)

**Comment by SDGNelson** [comment]
I was able to load up the map in the editor as-normal. When you mention caused by a mod: which mod? If you disable the mod does it work? Also, did you say it happens with all other maps too?

**Comment by prank0011** [comment]
> I was able to load up the map in the editor as-normal. When you mention caused by a mod: which mod? If you disable the mod does it work? Also, did you say it happens with all other maps too?

I'm not sure. I deleted all the Bundles folders in all the maps and it went back to normal.

**Comment by merlepx** [comment]
had a similar issue several days ago, deleting all the mods in the workshop content folder fixed it for me
