### ISSUE TITLE
Collision Event Hook not working when a barricade is on vehicle

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#3349]
I have a vehicle with a trigger collider and a collision hook and a barricade with a gameobject which layer is "Player" and the collision event hook detects that barricade only if i place it on the ground but not on a vehicle itself.
![изображение](https://user-images.githubusercontent.com/110701629/183224701-91eac4cc-a4b7-4a36-b6fe-9c58b015525b.png)
![изображение](https://user-images.githubusercontent.com/110701629/183224724-4c0f1f65-15ed-4142-a22c-975f0a0cf0be.png)

**Comment by GazziFX** [comment]
It would be hard to fix because Vehicle ignore barricades placed on it
```csharp
if (region.parent != null)
{
	BarricadeManager.barricadeColliders.Clear();
	transform.GetComponentsInChildren<Collider>(BarricadeManager.barricadeColliders);
	foreach (Collider collider in BarricadeManager.barricadeColliders)
	{
		bool flag = collider is MeshCollider;
		if (flag)
		{
			collider.enabled = false;
		}
		if (collider.GetComponent<Rigidbody>() == null)
		{
			Rigidbody rigidbody = collider.gameObject.AddComponent<Rigidbody>();
			rigidbody.useGravity = false;
			rigidbody.isKinematic = true;
		}
		if (flag)
		{
			collider.enabled = true;
		}
		if (collider.gameObject.layer == 27)
		{
			collider.gameObject.layer = 14;
		}
	}
	transform.gameObject.SetActive(false);
	transform.gameObject.SetActive(true);
	InteractableVehicle component = region.parent.GetComponent<InteractableVehicle>();
	if (component != null)
	{
		component.ignoreCollisionWith(BarricadeManager.barricadeColliders, true);
	}
}
```

**Comment by TheMew0** [comment]
thanks for the info, i've figured out how to make it so it detects so closing the issue

**Comment by Ongjming** [comment]
> thanks for the info, i've figured out how to make it so it detects so closing the issue

Erm just curious here, how did you solve it then?
