### ISSUE TITLE
Passive Tactical Mode

### ISSUE THREAD

**Issue by Vilespring** [SmartlyDressedGames/Unturned-3.x-Community#335]
Currently, the only stat on a gun that tacticals can passively change is firerate (eg: Adaptive Chambering). Active tacticals (eg: Tactical Laser) are capable of changing shake, recoil, and accuracy.

Adding a "Passive" mode to tacticals should allow more creativity to what can be done with them.

**Comment by SDGNelson** [comment]
True, all tacticals should be able to influence those stats
