### ISSUE TITLE
Weather preview field has character limit

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3350]
The level editor's **weather preview** field has a character limit of 16. I believe this field is meant to read GUIDs, which have more than 16 characters. Additionally, it doesn't seem to read hardcoded weather names either, such as **storm** or **blizzard**.

Am I misunderstanding the purpose of the field, or is it indeed broken?

**Comment by GazziFX** [comment]
Yes, it takes only GUID, seemed Nelson is confused that GUID is 16 bytes and made 16 characters limit but 16 bytes in hex require 32 characters

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like this and the terrain layer guid field must have been broken when text field max length (default 16) was fixed with uGUI in a relatively recent update. Fixed for the next update.
