### ISSUE TITLE
Requesting a small change to Attachments.updateAttachments

### ISSUE THREAD

**Issue by Endey132** [SmartlyDressedGames/Unturned-3.x-Community#3352]
I'm making a plugin which has to increase the length of gun states, but a check at the beginning of the client-side method Attachments.updateAttachments prevents me from doing this.

If the code:
```csharp
if (state == null || state.Length != 18)
  return;
```

Could be changed to something like:
```csharp
if (state == null || state.Length < 18)
  return;
```

That would help me a lot. Thanks in advance!

**Comment by SDGNelson** [comment]
Sorry, this is very much unintended / unsupported. When I get the opportunity to do some rewrites to the inventory / items I plan to add the ability for plugins to add custom data to items.
