### ISSUE TITLE
Missing 'item'GameObject 

### ISSUE THREAD

**Issue by DkFall** [SmartlyDressedGames/Unturned-3.x-Community#3355]
I'm trying to install a mod from the workshop on my linux server, the developer says she's testing it on the server itself and it's working, but on my server the mod only works in part

Accessories, sights, ammunition, magazines and that stuff, spawns perfectly, but the weapons don't spawn, when you're installing the mod on the server, there are some errors on my server like the ones below

"missing 'item' GameObject"
"Exception has been thrown by the target of an invocation"
"missing blueprint type"
"missing effect GameObject"

If anyone knows what could be the cause I would appreciate it.

**Comment by Ongjming** [comment]
For "missing blueprint type" it is probably one of the .dat files missing this line:
![image](https://user-images.githubusercontent.com/28900564/184381645-d86a6f6d-bd6f-4518-989a-c2cf83d17159.png)
(Check out what types are there via https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ItemAsset/Blueprints.md under Blueprint_#_Type)
This one determines which tab in the crafting menu the craft recipe shows up in.

For "missing 'item' GameObject" and "missing effect GameObject"
It could be due to
1. The MasterBundle.dat not being named as such
2. The masterbundle didn't have a linux support export (Since your server is running on Linux)
3. The folder path of the masterbundled mod and the folder path within unity is different.
4. Asset_Prefix (Asset location path) line within the MasterBundle.dat is referring to a place where it cannot detect the same folder structure as found in unity for the mod.
5. Unity Tag and Layer for the Item and Effect might be not assigned or on the wrong layer/tag for the particular item.

For "Exception has been thrown by the target of an invocation" I have totally no idea.

That's all I know so far through fiddling around :D

**Comment by DkFall** [comment]
> Para "tipo de blueprint ausente", provavelmente é um dos arquivos .dat sem esta linha: (Confira quais tipos existem em https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ItemAsset/Blueprints.md em Blueprint_#_Type) Este determina em qual guia no menu de criação a receita de artesanato aparece. ![imagem](https://user-images.githubusercontent.com/28900564/184381645-d86a6f6d-bd6f-4518-989a-c2cf83d17159.png)[](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ItemAsset/Blueprints.md)
> 
> Para "GameObject de 'item' ausente" e "GameObject de efeito ausente" Pode ser devido a
> 
> 1. O MasterBundle.dat não está sendo nomeado como tal (A esquerda é a forma correta)
>    ![imagem](https://user-images.githubusercontent.com/28900564/184383969-3aa90808-1b76-46e7-91b6-8a61918f3f0a.png)
> 2. O masterbundle não tinha uma exportação de suporte ao linux (já que seu servidor está rodando no Linux)
>    ![imagem](https://user-images.githubusercontent.com/28900564/184383332-2f065e7a-586f-41e8-9e0b-f3a6d3fd5e92.png)
> 3. O caminho da pasta do mod masterbundled e o caminho da pasta na unidade são diferentes.
> 4. A linha Asset_Prefix (caminho do local do ativo) dentro do MasterBundle.dat está se referindo a um local onde ele não pode detectar a mesma estrutura de pastas encontrada na unidade para o mod.
> 5. Unity Tag e Layer para o Item e Effect podem não estar atribuídos ou na layer/tag errada para o item específico.
>    ![imagem](https://user-images.githubusercontent.com/28900564/184384208-d522bcbf-acbb-4b3a-a5b4-4a48f3715541.png)
> 
> Para "A exceção foi lançada pelo destino de uma invocação", não faço ideia.
> 
> Isso é tudo que eu sei até agora brincando :D



> For "missing blueprint type" it is probably one of the .dat files missing this line: ![image](https://user-images.githubusercontent.com/28900564/184381645-d86a6f6d-bd6f-4518-989a-c2cf83d17159.png) (Check out what types are there via https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ItemAsset/Blueprints.md under Blueprint_#_Type) This one determines which tab in the crafting menu the craft recipe shows up in.
> 
> For "missing 'item' GameObject" and "missing effect GameObject" It could be due to
> 
> 1. The MasterBundle.dat not being named as such (The left is the correct form)
>    ![image](https://user-images.githubusercontent.com/28900564/184383969-3aa90808-1b76-46e7-91b6-8a61918f3f0a.png)
> 2. The masterbundle didn't have a linux support export (Since your server is running on Linux)
>    ![image](https://user-images.githubusercontent.com/28900564/184383332-2f065e7a-586f-41e8-9e0b-f3a6d3fd5e92.png)
> 3. The folder path of the masterbundled mod and the folder path within unity is different.
> 4. Asset_Prefix (Asset location path) line within the MasterBundle.dat is referring to a place where it cannot detect the same folder structure as found in unity for the mod.
> 5. Unity Tag and Layer for the Item and Effect might be not assigned or on the wrong layer/tag for the particular item.
>    ![image](https://user-images.githubusercontent.com/28900564/184384208-d522bcbf-acbb-4b3a-a5b4-4a48f3715541.png)
> 
> For "Exception has been thrown by the target of an invocation" I have totally no idea.
> 
> That's all I know so far through fiddling around :D

for option 2 of the "missing item" error, is there any way to fix it?

**Comment by SDGNelson** [comment]
Thanks @Ongjming!

If you attach the server's log file from U3DS/Logs/Server_ (id) .log there may be more details as well.

**Comment by DkFall** [comment]
> Thanks @Ongjming!
> 
> If you attach the server's log file from U3DS/Logs/Server_ (id) .log there may be more details as well.

Okay, I will leave the two files that exist in my logs folder uploaded

**Comment by SDGNelson** [comment]
It looks like the only error on the server is the missing blueprint type. The missing item/effect prefab errors must be happening on the client which should be easier for the developer to reproduce.

**Comment by DkFall** [comment]
> It looks like the only error on the server is the missing blueprint type. The missing item/effect prefab errors must be happening on the client which should be easier for the developer to reproduce.

the errors that disappeared, it was because what @Ongjming said about the masterbundle file with the wrong name, I managed to solve it and most of the errors disappeared, now it's just these errors

**Comment by SDGNelson** [comment]
Glad to hear you fixed it!
