### ISSUE TITLE
v3.22.14.0 update upward roof placement

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#3356]
Bug:
Roof's hook is missing, I cannot build upwards even with 2 vanilla pillars placed on the vanilla floor.
![image](https://user-images.githubusercontent.com/28900564/184429910-36c4d2bd-df76-4769-98b7-b62174624fc0.png)

Edit: will go sleep now.

**Comment by KodakDolph** [comment]
Can confirm happening to me too

**Comment by SDGNelson** [comment]
Sorry, this is intentional: it was simplified so that roofs are attached to wall edges. (wall must be placed first)

**Comment by KodakDolph** [comment]
Ah, okay, ill pass the word on then. thanks
