### ISSUE TITLE
Not able to see foliage on the foliage tab of other maps or even custom ones

### ISSUE THREAD

**Issue by Crist4n** [SmartlyDressedGames/Unturned-3.x-Community#3358]
Is there a way to see foliage that i don't see but i installed in the new Foliage Tab on the editor? Because **Nelson whenever i try to use the foliage tab and search the foliage that i installed via workshop they don't appear**, is there a way to fix it?

**Comment by SDGNelson** [comment]
Most likely they do not have a newer "FoliageAsset" unfortunately, but you can create one: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Foliage.md

**Comment by Crist4n** [comment]
How can i create that? i doesn't say how to in the link Nelson
I'm actually not so much experienced is there a detailed way?

**Comment by SDGNelson** [comment]
Sorry, not a complete start to finish guide. A good starting point would be the asset documentation and copying one of the vanilla foliage assets from Unturned/Bundles/Assets/Landscapes/Foliage/Resources to base yours off of.
