### ISSUE TITLE
Fix negative scaling sometimes mirroring along the wrong axis

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#3359]
This seems to be an unfortunate side effect of using `Matrix4x4.lossyScale`, will investigate a better replacement.

**Comment by lockboy** [comment]
Hi.SDGNelson I m lockboy can i ask u something related to Unturned glazier mod?Cause now there is a new steam menu and i don't under stand what u are talking on the ugui refactor pls ans me on discord lockboy#2833

**Comment by educatalan02** [comment]
> Hi.SDGNelson I m lockboy can i ask u something related to Unturned glazier mod?Cause now there is a new steam menu and i don't under stand what u are talking on the ugui refactor pls ans me on discord lockboy#2833

What a random one guy
