### ISSUE TITLE
Can't manually type . in number fields for brushes

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3360]
The fields accept decimal values, but typing a **.** in the field does not actually do anything. Instead, mappers have to hit the **[Right Arrow →]** key, or manually click past the decimal point.

Minor nuisance. Would be great QoL if pressing **.** actually did something though.

Presumably, this issue stems somewhere along the field automatically always including a decimal point. (Trying to delete the decimal point just results in all of decimal values being shifted to the integer, and then a decimal and three 0's automatically being appended.)

**Comment by SDGNelson** [comment]
It is probably getting reset when TryParse fails. Will see if there is a better option in the uGUI text field!

**Comment by SDGNelson** [comment]
Should be fixed in the .2 patch this morning!
