### ISSUE TITLE
UseableGun rewrite

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3361]
Current implementation contain a lot of bugs/mistakes.

## 1. Spread calculations are incorrect
This is actual code of the game
```csharp
Vector3 vector = base.player.look.aim.forward;
vector += base.player.look.aim.right * UnityEngine.Random.Range(-spread, spread);
vector += base.player.look.aim.up * UnityEngine.Random.Range(-spread, spread);
vector.Normalize();
```
You can represent this algorithm with following image
![image](https://user-images.githubusercontent.com/43498426/184493642-5c275ede-171b-4ebf-8efa-1f761dcf86e3.png)
So currently spread is not an angle, but tangent of it. And this is non-linear function.

I think it should be replaced with something like this
```csharp
Quaternion quaternion = Quaternion.LookRotation(dir);
Vector2 vector = Random.insideUnitCircle;
Vector3 direction = quaternion * Quaternion.Euler(vector.x * spread, vector.y * spread, 0f) * Vector3.forward;
```
## 2. Tracers of other players not affected by the spread
You can make shared random seed per gun between client and server, so server can predict which direction will be.

## 3. Firerate lower than 11 on semi guns doesn't make sense
Semi gun is waiting when you release the button, but PlayerInput listen to keys every 4 FixedUpdate and it also give additional delay between mouse click and first shot

**Comment by QERT2002** [comment]
The best coder ever, i love you gazzi, thanks for fixing game bugs!🧡🧡🧡

**Comment by SDGNelson** [comment]
There is definitely a lot of room for improvement in the older UseableGun code.

Also in retrospect makes sense that QERT2002 is a troll. 🙄

**Comment by GazziFX** [comment]
Will it happen after item metadata rewrite?
