### ISSUE TITLE
Admin edit bug

### ISSUE THREAD

**Issue by Che3syPotato** [SmartlyDressedGames/Unturned-3.x-Community#3364]
So whenever i use my admin edit the arrows dont show up im on mac btw
<img width="1440" alt="Screen Shot 2022-08-15 at 10 22 20 PM" src="https://user-images.githubusercontent.com/106875490/184784910-144b25c2-cdea-4824-bc28-1d4253983952.png">

**Comment by Che3syPotato** [comment]
so i guess i fixed it i restarted my unturned but idk

**Comment by SDGNelson** [comment]
Glad to hear it started working! 🤷‍♂️
