### ISSUE TITLE
Custom physical material

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3365]
![image](https://user-images.githubusercontent.com/83378019/184976836-3b70cd5f-7da7-451d-bec2-b193af37f306.png)
I want to create my own custom material, but I can't figure out where these sounds are

**Comment by GazziFX** [comment]
In masterbundle

**Comment by JorelDecker** [comment]
![image](https://user-images.githubusercontent.com/83378019/184990301-2175526b-e62c-4071-b63d-e6b1e4ca9951.png)
Like this?

**Comment by Spebby** [comment]
> ![image](https://user-images.githubusercontent.com/83378019/184990301-2175526b-e62c-4071-b63d-e6b1e4ca9951.png) Like this?

Very late reply, my apologies. Make sure to add at least 1 audio clip to the scriptable object. To attach a sound, increase the "size" of the clips section and then drag and drop your audio clips in.
<img width="171" alt="image" src="https://user-images.githubusercontent.com/47935791/189466532-51139dd9-0739-429f-9899-68efbeee53cc.png">
