### ISSUE TITLE
Question about terrain height limits

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3366]
I'm not sure whether to class this as a Bug Report, a Feature Request, or just a genuine question. 

**Context:**
This might have just been an editor limitation in the past which was changed with the devkit merge, or maybe I missed some patch notes - but originally terrain height limitations were 0 to 256, and at some point in the last few months it was increased to -1024 to 1024. 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/71527679/185012909-3dad83a4-5c15-45fa-939b-37a666011c8b.png">
Despite the height limit changes, players still aren't able to travel below 0. Making all the additional space in the negative coordinates unusable.

**Question/request:**
Is there a technical reason for this boundary, and would it be possible to remove this restriction?
It would allow for deeper oceans/rivers, or deep canyons to be added into both new and existing maps. 
Currently to create anything with any sort of depth like this you have to plan for it right from the very beginning, and you lose out on vertical space by doing so.

**Comment by SDGNelson** [comment]
It should currently be possible - do you have `Use_Legacy_Clip_Borders` in your level's Config.json file?

**Comment by AdamDN** [comment]
It's not currently in there, no. 
Should I add it set to true/false?

**Comment by GazziFX** [comment]
Set to false

**Comment by AdamDN** [comment]
Perfect, thank you!
