### ISSUE TITLE
[Feature Request] Make copied objects have the same material palette in Map Editor

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3368]
Right now, when you copy and paste an object with randomized material palette, it spawns with a new random material palette, and it is very uncomfortable when you try to use randomized material palettes for objects like fences: there are too many of them and they all must have the same material palette, so all you can do is keep copying them until you get the right color.

So copying and pasting an object should copy the material palette too. If the user wants to get a new material.

Actually it would be great to have a way to manually select the palette you want to use, but still at least tweaking copying and pasting process would make it a lot more comfortable to work with such objects.

**Comment by SDGNelson** [comment]
Currently it is manually specifiable in the devkit, and that will be brought over to the regular editor in one of the next few updates! Objects with manually specified material palette get the value copied when they are copy/pasted.
