### ISSUE TITLE
Disable vehicle gameobject if its far from player

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3370]
If server has a lot of vehicle it cause huge FPS drops

**Comment by surv0013** [comment]
Animals and players too

**Comment by DerpyHoowes** [comment]
Thats what LODs are for...

**Comment by GazziFX** [comment]
> Thats what LODs are for...

How you supposed to disable MonoBehaviour with LOD?

**Comment by SDGNelson** [comment]
More likely only loading vehicles/animals/players near the client same as barricades, but no ETA.
