### ISSUE TITLE
Client-side is destroying sign barricade

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3372]
Hello! I'm invoking BarricadeManager's ServerSetSignTextInternal method from the server-side. It works until the client reconnects to the server. But client-side (yes, client-side. It still appears on the server-side) is destroying the barricade (sign) after the reconnect.
![unknown](https://user-images.githubusercontent.com/43903270/185661709-6e448916-3fdf-4445-be40-167d0df5bf86.png)
![unknown](https://user-images.githubusercontent.com/43903270/185661719-7de509c6-fb09-4679-b14a-9fae9e766c67.png)

EDIT 1: Code;
```cs
  public void UpdateSign(InteractableSign sign, string text)
  {
      if (!BarricadeManager.tryGetRegion(sign.transform, out var x, out var y, out var plant, out var region))
      {
          return; 
      }
              
      typeof(BarricadeManager)
          .GetMethod("ServerSetSignTextInternal", BindingFlags.NonPublic | BindingFlags.Static | 
          BindingFlags.InvokeMethod).Invoke(null, new object[] { sign, region, x, y, plant, text });
  
      System.Console.WriteLine("Done!");
  }
```

```cs
    [HarmonyPatch(typeof(InteractableSign))]
    [HarmonyPatch(nameof(InteractableSign.isTextValid))]
    public class Patch_TextValidation
    {
        [HarmonyPrefix]
        public static bool Prefix(string text, ref bool __result)
        {
            __result = true;
            return false;
        }
    }
```

**Comment by SDGNelson** [comment]
What do you mean by the client destroying it? Also why are you patching that method rather than using `ServerSetSignText`?

**Comment by GazziFX** [comment]
Why do u append color tags to all square symbols instead of grouping them?

**Comment by fahrettinenes** [comment]
> What do you mean by the client destroying it? Also why are you patching that method rather than using `ServerSetSignText`?

It's being disappeared after reconnect. Also ServerSetSignText has some validations. Because of that I'm Invoking Internal one.

**Comment by fahrettinenes** [comment]
> Why do u append color tags to all square symbols instead of grouping them?

You're right, my bad. But main issue not about this i think.

**Comment by fahrettinenes** [comment]
Server is kicking me when i reconnected:
Server missing unknown asset? (should never happen) Id: 726f6c6f0a3e633c6e3ee2963d637961

**Comment by GazziFX** [comment]
Disable all patches and reset world

**Comment by fahrettinenes** [comment]
> Disable all patches and reset world

Doesn't work :<

**Comment by GazziFX** [comment]
Did you used public method this time, I think you reached chars limit and trying to bypass it cause bugs

**Comment by fahrettinenes** [comment]
> Did you used public method this time? I think you reached chars limit and trying to bypass it cause bugs

If I use public method I can't bypass char limit, do you have any idea about bypass char limit?

**Comment by GazziFX** [comment]
I think its definitely the reason because old barricades medata doesn't support that amount of bytes, but the SendText RPC can handle it so it doesn't crash on the first time, but appears on the reconnect, and exceed bytes cause unknown asset error to appear

**Comment by GazziFX** [comment]
> If I use public method I can't bypass char limit, do you have any idea about bypass char limit? 

Maybe use only RPC and not write to metadata

**Comment by GazziFX** [comment]
If you want to automatically send this text to new or freshly entered region players you can create text registry and add postfix to barricade region load and call that RPC with text from registry

**Comment by fahrettinenes** [comment]
Thanks for replies Gazzi, like you said it's about metadata.

**Comment by fahrettinenes** [comment]
It's work when I called RPC

**Comment by GazziFX** [comment]
Nelson, I think you should hire me to do Unturned features instead of cheats 🐱

**Comment by fahrettinenes** [comment]
I agree that ^^

**Comment by SDGNelson** [comment]
Yeah your `state[]` length is longer than supported.
