### ISSUE TITLE
Resources.dat hash zero on client

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#3373]
Hello,

There is issue with level hash computation for workshop item 2850531174.
The server said:
`[2022-08-20 11:01:13] [92] Including "Resources.dat" in level hash: 3EF5FEA3248FE85700FBCA464C15F4DB8FA69AE2`

The windows client said:
`[2022-08-20 11:04:20] [92] Including "Resources.dat" in level hash: 0000000000000000000000000000000000000000`

File Resources.dat exists both on server and on client and has the same contents.

That leads to invalid level hash error

**Comment by SDGNelson** [comment]
There is probably a "Tree with no asset" error above those lines in the Client's log file. It should have the ID of the missing tree.

**Comment by D-AIRY** [comment]
Yes, there are some. Do that cause zero hash?

**Comment by SDGNelson** [comment]
Yes, if the asset is missing it resets hash to zero to cause a kick.
