### ISSUE TITLE
Syncing ChatHook

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3374]
If I make a door that will open from the text in the chat (like the Anastasia door). Will it work fine on the server as a normal door?

**Comment by DevInc0** [comment]
What do you mean by a _**"normal door"**_?

Basically, **_every ModHook_** should work fine both in _**multiplayer**_ and in _**single player**_.

So, if you place your door _**on server**_, then it will open _**via chat message**_ same as in single player.

**Comment by GazziFX** [comment]
> Basically, **_every ModHook_** should work fine both in _**multiplayer**_ and in _**single player**_.

Not really, for example, if you add Collision Event Hook which will activate gameobject and some of the player activate it, it wont be visible for players joined after event.

Anastasia door is `InteractableObjectBinaryState` which replicates state for new players. So I think `InteractableObjectBinaryStateEventHook` is preffered to use with "modhook doors"

**Comment by SDGNelson** [comment]
The Anastasia door works because it uses the IOBS Event Hook which has replication support in multiplayer. If you use that it should work, but if you directly set properties like whether a component is enabled it will not be synchronized.
