### ISSUE TITLE
Other text fields using default 16-char max length

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3375]
1. Server name filter, when filtering through the server list. Makes it hard to filter for certain server names.
2. Item name filter, when filtering through Steam Economy inventory. Makes it hard to filter for certain item descriptions (when that's toggled on).
3. Object name filter, when filtering through objects list in the editor. Many workshop/curated mods will prefix their names, so they can get pretty long. E.g., **California Mall Shelf #**__12__.
4. Materials name filter, when filtering through materials list in the editor. Similar idea as above, with some pretty long names.

**Comment by SDGNelson** [comment]
Thanks for pointing these out! Alternatively I wonder should the default max length be increased? 16 seems rather short, but on the other hand these fields are visually small.

**Comment by MoltonMontro** [comment]
Tabbing left/right through a text field to see all that was typed is always annoying, but at least the field lets one type all they want to type. With the exception of the **object field**, I think the fields are actually fairly big compared to their max length anyways:
![image](https://user-images.githubusercontent.com/7608445/186072858-762f40fd-b33a-44bc-8386-f7e91487730a.png)
![image](https://user-images.githubusercontent.com/7608445/186072883-efc68cc0-08bc-4958-a8f5-9c87166938f9.png)
![image](https://user-images.githubusercontent.com/7608445/186072992-1a00fa1b-5d5a-4160-9a5b-998724cfaecb.png)
![image](https://user-images.githubusercontent.com/7608445/186073078-7341cc09-b22f-4474-80d1-ddf1313a4850.png)

**Comment by SDGNelson** [comment]
What I meant was: do you think there would be any downside to increasing the max length from 16 to maybe 100?

**Comment by MoltonMontro** [comment]
Oh, for _all/most_ text fields, not just these—My bad. I don't foresee any notable downsides. I think it's better to overcompensate than undercompensate anyways. Personally, I'd at least want the fields doubled to 32 as default – the length of a GUID.

Text can always be deleted quickly with Ctrl+A → Backspace. Tabbing left/right through text that's longer than the visual field is annoying but not always necessary (e.g., some fields will likely never hit whatever the new cap is anyways, so the disparity between the visual size of the field versus the max length isn't always relevant).

Technically someone could fill the field with whitespace characters, and then start typing with leading/trailing spaces and get confused. But I think most fields don't actually care about excess whitespace. Fields seem to automatically select/highlight all when you first click on it anyways (at least, on Windows?), so excess whitespace should be somewhat obvious. You can technically have excess whitespace with the current character limits anyways, so it's not a unique/new issue.

**Comment by SDGNelson** [comment]
Will go the route of increasing the max limit then 👍

**Comment by SDGNelson** [comment]
Oops I should have marked this next update so that I remembered!
