### ISSUE TITLE
Make upgraded fishing rod blueprint reacquirable on Russia map

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3377]
You get upgraded fishing rod blueprint only once, so if you get killed and loose it, you can only hope someone else gives you one or log in with a different character (also impossible if multi-character saves are disabled). I guess there could be some vendor allowing you to buy it for experience, or maybe for fish.

PS:
These changes might be a little too much but:
You can only get one scoped ace. I guess it was intended to be unique this way like the fighter jet, but its not something very important so maybe being able to buy it or get a new one for some Scientist's quest that you can repeat.
Armory shop feels completely useless, since the only useful item you can buy there is the rangefinder, and you can only sell ammo for ridiculously low price. Adding new items for sale to this shop like guns might break the balance, but at least increasing the ammo sell prices and adding more items to sell to this vendor might make it useful as XP souce for buying uniforms and food from other Coalition members.

I know that Russia's questline has been out there for years now without changes, but replaying it still feels great even after all these years and completing it for multiple times, so I think these changes might make it even better and more enjoyable.

**Comment by SDGNelson** [comment]
Happy to hear you still enjoyed playing the Russia quests! :)

It would be nice to make these re-acquirable. No ETA but I do want to do it.

**Comment by Sgtlog123** [comment]
very soon:tm:
