### ISSUE TITLE
Loading music doesn't work on queue

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#3379]
Am I missing something or is it intentional that loading screen music stops when player is in queue? I think it would be worth making so song plays on queue as well, since loading itself takes only 1-2 seconds.

**Comment by SDGNelson** [comment]
Hmm it should be playing in the queue! Will investigate.

**Comment by SDGNelson** [comment]
Should be fixed in the next update!
