### ISSUE TITLE
Occasional disconnect after vehicle blow up on multiplayer

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#338]
No errors in console or anything, the server just seems to time people out when their vehicle blows up with them still in it. I'm not sure if this is vanilla or not but I have no Rocket plugins that do anything with vehicle explosions, and this has been happening for I think over a year now.

**Comment by SDGNelson** [comment]
I think this happened to me before on a public server, but I haven't been able to replicate it on a test server with artificial 1000ms latency either by driving in a 0 health vehicle as it explodes or crashing helicopters.
