### ISSUE TITLE
Small disconnect on the model on Rainbridge on Washington.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#3380]
There is a very small gap and model overlap on Rainbridge on the Washington map,

Pictured here;
https://cdn.axodouble.tech/v3/img/UwJLdkmzYD.png
https://cdn.axodouble.tech/v3/img/QmD2N0QOro.png

This bug makes the game literally unplayable and ruins all immersion!
Please fix soon, with all love :heart:

**Comment by SDGNelson** [comment]
Sorry, this is because the bridge is a bunch of straight models connected together. Would need to add a shallower bridge turn model but no plans unless working on a new map.
