### ISSUE TITLE
Custom UserInterface elements periodically disappear.

### ISSUE THREAD

**Issue by ChumnoyGHOST** [SmartlyDressedGames/Unturned-3.x-Community#3381]
I have an user interface with a plugin. The interface has a field for text and an image.
![image](https://user-images.githubusercontent.com/76044557/186040797-e182947b-022d-47d8-b8c1-3def595bd567.png)
When a player connects, the plugin sends him an interface.
```c#
EffectManager.sendUIEffect(19999, 19999, SteamPlayer.transportConnection, true);
EffectManager.sendUIEffectText(19999, SteamPlayer.transportConnection, true, "UserInterface_HUD_Information_Experience_Field", string.Format(CultureInfo.InvariantCulture, "{0:#,##0}", UnturnedPlayer.Experience));
EffectManager.sendUIEffectImageURL(19999, SteamPlayer.transportConnection, true, "UserInterface_HUD_Information_Icon", "https://something.png");
```
After a while the fields may become empty, and the pictures disappear. The plugin does not affect them in any way.
This can happen if someone connects to the server, but it usually happens after a while (I'm not sure if connecting another player affects it).
![image](https://user-images.githubusercontent.com/76044557/186041097-a765e72c-5158-4416-880f-11df44f61d2c.png)
Could this be due to the length of the field? Or what is it related to?

**Comment by SDGNelson** [comment]
By default there would not be anything in the base game resetting it. Perhaps someone else in your code is resetting it accidentally?

**Comment by ChumnoyGHOST** [comment]
Unlikely. At least the balance field cannot be empty. It changes only when experience changes. It can be 0, but 0 is displayed as 0.

**Comment by SDGNelson** [comment]
Sorry, cannot think of any reason in the base game why it would be getting reset.
