### ISSUE TITLE
Foliage not being placed outside of map despite foliage volume.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3382]
Hello, I'm here to report a possible bug with foliage. I made multiple tiles on a large map out past where the default water volume ends, and it seems like foliage (specifically types that can be interacted with by the player, like harvesting and destroying for items) cannot be placed that far outside of the map despite me having a foliage volume covering the tiles. This happens with baking, painting, and using the exact tool.

**Comment by SDGNelson** [comment]
Sorry, if it is not allowing them to be placed then it is probably outside the "insane" map size limits. Everything starts to hit old edge cases past that point, so best to have playable area inside 8x8 landscape tiles.

**Comment by Jdance-Media** [comment]
Closing this as it has been almost a month. Thank you for the response, I believe these titles were within the 8x8 tiles, but I'll just stay away from doing stuff that is too far outside the legacy borders.
