### ISSUE TITLE
Can't Join in the server

### ISSUE THREAD

**Issue by moemeow233** [SmartlyDressedGames/Unturned-3.x-Community#3383]
I Just started a server on my PC. At first,Players can join in, But after a update, Some of Players met the following error message:
**Asset bundle error: 1 of 2 installed** 
Screenshot:`https://img1.imgtp.com/2022/08/23/MZ4qure1.jpg`
while other players can normally play.
I have confirmed the players who have this problem didn't install any new workshop mods except mine

**Comment by SDGNelson** [comment]
If they can send you their Client.log file to attach after the error it should list which asset bundle is missing and (hopefully) why.

**Comment by moemeow233** [comment]
> If they can send you their Client.log file to attach after the error it should list which asset bundle is missing and (hopefully) why.
`https://zerobin.net/?38604bbc6324a618#6iY6p8B/K0CBdkbVeQPEi8wznUZv6Qq1BNyd/p0thTo=`

**Comment by SDGNelson** [comment]
It looks like the missing asset bundle is Elver. Do you have Elver listed in the server's required workshop files?

**Comment by moemeow233** [comment]
> It looks like the missing asset bundle is Elver. Do you have Elver listed in the server's required workshop files?

No,But I Have a server based on Elver

**Comment by moemeow233** [comment]
Hi I managed to solve the problem, I asked players to delete all their workshop contents and retry. It finally playable now! Thank you for your help and Have a nice day!
