### ISSUE TITLE
[Feature request] Effect infinite lifetime

### ISSUE THREAD

**Issue by ChumnoyGHOST** [SmartlyDressedGames/Unturned-3.x-Community#3384]
The effects in the game have a problem. I had the need to put the same effects as marks, but found a problem. When I'm cleaning an effect with the plugin, the "scheduled cleanup" (Lifetime of the effect) stays, but the next effect with the same ID is cleaned because of the previous one.
I fixed this with the `Lifetime 65535` property in the `.dat` file of the effect. In fact, the bug remained, but now you have to play for a very long time to get it.
Can I ask to add a property that allows to make `Lifetime` infinite?

**Comment by iBowie** [comment]
Lifetime property is float, you CAN set it to infinity, or a very, very big number.

**Comment by ChumnoyGHOST** [comment]
How can I set infinity in `.dat` file?

**Comment by GazziFX** [comment]
> How can I set infinity in `.dat` file? Just `Lifetime Infinity`?

604800 seconds is enough, I think you wont play Unturned 7 days without disconnecting from the server

**Comment by ChumnoyGHOST** [comment]
But how make Lifetime infinity?

**Comment by GazziFX** [comment]
Why?

**Comment by SDGNelson** [comment]
Out of curiosity what effect do you have with an infinite lifetime? Currently a negative lifetime defaults to the graphics settings lifetime, so I would recommend a high value as others have mentioned.

**Comment by ChumnoyGHOST** [comment]
In my case, the effect is caused by the plugin and is also removed, and it is desirable that the lifetime was infinite.

**Comment by DevInc0** [comment]
> How can I set infinity in `.dat` file? Just `Lifetime Infinity`?
> 
> Also, the problem of cleaning up the effect is still there, unless I make Lifetime infinite.

Actually, yes

```cs
// EffectAsset cctor
public EffectAsset(Bundle bundle, Data data, Local localization, ushort id) : base(bundle, data, localization, id)
{
    ...
    this._lifetime = data.readSingle("Lifetime", 0f);
    ...
}

---

// Inside of class Data
public float readSingle(string key, float defaultValue = 0f)
{
    if (!float.TryParse(this.readString(key, null), NumberStyles.Any, CultureInfo.InvariantCulture, out result))
    {
	result = defaultValue;
    }
    return result;
}
```

And, according to:
https://stackoverflow.com/questions/18398690/how-should-i-parse-infinity-with-double
https://answers.unity.com/questions/978278/destroysome-object-mathfinfinity-what-happens.html

Your effect's lifetime will be infinite<br><br>

Worked fine for my TestEffect.dat
```dat
Type Effect
ID 55676

Lifetime Infinity

Exclude_From_Master_Bundle
```
