### ISSUE TITLE
Boost doesnt appears on client side in UI

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3387]
I changed client boost with this code below.

*Without reflection it wont work (marked ">").*
```cs
private static readonly ClientInstanceMethod<EPlayerBoost> sendBoost = (ClientInstanceMethod<EPlayerBoost>)typeof(PlayerSkills).GetField("SendBoost", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null);

> typeof(PlayerSkills).GetField("_boost", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(source.Player.skills, EPlayerBoost.OLYMPIC);

sendBoost.InvokeAndLoopback(source.Player.GetNetId(), ENetReliability.Reliable, Provider.EnumerateClients_Remote(), EPlayerBoost.OLYMPIC);
```

Boost is working fine (I tried Olympic also Flight) but on the client side it wont show in UI
![image](https://user-images.githubusercontent.com/65300126/186443738-3c087788-34f0-4858-8be4-938be0d0a786.png)

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time. For anyone who comes across this: please don't patch/reflect to call RPCs!
