### ISSUE TITLE
BattlEye: Query Timeout at Turkish IP Blocks

### ISSUE THREAD

**Issue by aerodak2** [SmartlyDressedGames/Unturned-3.x-Community#3388]
In some Turkish IP address blocks, we get "BattlEye : Query Timeout" Error on our servers.
I tried contact with BE but they ignored me lol.

**Comment by treeminder** [comment]
good, maybe it's because your cheat is pasted + garbage

**Comment by aerodak2** [comment]
> good, maybe it's because your cheat is pasted + garbage

Nah not about cheats. my own server lmao

**Comment by aerodak2** [comment]
+ everyone got kicked in server without cheats
