### ISSUE TITLE
Plugin or map option to disable grass off

### ISSUE THREAD

**Issue by Jerico97** [SmartlyDressedGames/Unturned-3.x-Community#3389]
Hello Nelson.
I would like to request an option so that grass on the map cannot turned off.
It would be great for hide and seek game-mode or something like that.
I was able to implement this through module, but unfortunately in this case batleye has to be disabled.
Thanks for reading.

**Comment by SDGNelson** [comment]
Sorry, this is not likely to be an option, but at some point Low grass setting will become the minimum. (no Off setting)

**Comment by surv0013** [comment]
> Sorry, this is not likely to be an option, but at some point Low grass setting will become the minimum. (no Off setting)

I'm sorry to interfere, but maybe it's worth disable turning off the quality of the sight? Because the turned off scope gives an advantage in terms of greater zoom and the absence of camera swaying when moving.

P.S. https://www.youtube.com/watch?v=9g2VqJvWnQI
