### ISSUE TITLE
Steam can not be initialized

### ISSUE THREAD

**Issue by San3l** [SmartlyDressedGames/Unturned-3.x-Community#3394]
Hello i was getting this error and i found something like change steamclient.so other game into unturned folder so i did and still same on off discord i was trying ask and i get reply with change steamclient.so this problem is same on pterodactyl servers or hostings can someone help me with this ? 

Sanel.
![image](https://user-images.githubusercontent.com/92259733/186992738-9bb0b024-842c-4325-bb44-57b13b42cb7f.png)
![image](https://user-images.githubusercontent.com/92259733/186992786-b6714e9c-d130-4cd1-87c5-48f51bff697e.png)

**Comment by SDGNelson** [comment]
There were some reports before that Pterodactyl does not install the game through steamcmd so some important files are missing. Are you able to install the game through steamcmd instead?

**Comment by San3l** [comment]
yes i install it with steam cmd with ID -validate

**Comment by San3l** [comment]
but i have still same problem 
can you help me ?

**Comment by SDGNelson** [comment]
Could you attach the Server_ (id) .log file from the Logs folder please?

**Comment by San3l** [comment]
![image](https://user-images.githubusercontent.com/92259733/187050000-b48680a4-6933-4eb4-9521-570c632c452c.png)
 this logs ?

**Comment by surv0013** [comment]
> ![image](https://user-images.githubusercontent.com/92259733/187050000-b48680a4-6933-4eb4-9521-570c632c452c.png) this logs ?

Yes. Send all this files.

**Comment by San3l** [comment]
i cant

**Comment by San3l** [comment]
if i instal ftp server i cant log in

and i got banned for nothing :I i didnt hack or smh and i dont know even if any exist 
![image](https://user-images.githubusercontent.com/92259733/187519304-6ea4dffe-41e0-4894-b6f6-6f8aad097fef.png)

for nothing not gets email from battleye i get banned
https://steamcommunity.com/id/Sanelmore/ my steam i send it into battleye and last time i was playing on cloud boosteroid now i cant play anymore with my beta t shirt
