### ISSUE TITLE
Interactable object working in single, not in multi

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3395]
Hello,
I've made a quest where you need to pick up 5 bones and 1 skull. Here's a video of how it should look like:

https://user-images.githubusercontent.com/81763752/187019823-2c720c57-9e98-42b0-b558-2648141e9699.mp4

However on a public server all it did was play the sound effect of taking the item. None of the rewards went through and I don't know what to do. The clip is at time 0:55 
https://medal.tv/games/unturned/clips/x8bcwOBAIp_XH/d1337QtCIWt9?invite=cr-MSxsajgsNTAxNzk5ODgs

What could be the cause?

**Comment by SDGNelson** [comment]
Hmm hopefully there might be a relevant warning/error in the Client.log file from your Unturned/Logs folder or the Server_ (id) .log file in U3DS/Logs.
