### ISSUE TITLE
Maximum value of effect code?

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#3397]
Currently, I am using Effect to make UI, and I would like to know how many Effect numbers are supported. (Currently, I am using the 4200 series.)

Also, in order not to overlap the code of the built-in Effect used by Unturned, how many times should I use the code first?...

**Comment by Gamingtoday093** [comment]
Effects like any other asset type have a maximum value of **65356** `2^16` *(ushort max value)*.
As for IDs reserved for vanilla use, your minimum ID is **200**.
So any ID between **200** and **65356** is perfectly fine to use!

**Comment by Blackwolf7704** [comment]
Thanks!

**Comment by GazziFX** [comment]
> Effects like any other asset type have a maximum value of **65356** `2^16` _(ushort max value)_. 

65535 2^16-1 because it starting from 0 not 1
