### ISSUE TITLE
New Volume Implementation

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3398]
Let me start by saying that I love the new Volume editor you added a few updates ago. I really love the fact that you are moving the devkit tools into the regular editor. Just makes them way more accessible and easier to work with for everyone!

To give some pretext, us Unturned Modders have been using **Scripts** to add previously unobtainable functionality to anything. Like making anything Buoyant using the `Buoyancy.cs` script, or making anything a Grenade using the `Grenade.cs` script etc. **Scripts** in this context is refering to referencing already existing scripts in the Unturned framework as they will run perfectly fine unless modified. And up until recently, adding Kill Volumes or any other Volume to our items, effects and more worked too! But with the new Volume changes it doesnt seem so possible anymore.

I have been looking at a decompiled version of the game for some time now trying to understand how the new volumes work. They are for sure a lot more abstract than *derive from a `MonoBehaviour`* like the old ones did. I do know that they do somehow still derive from a MonoBehaviour as `OnTriggerEnter` is a Unity function. Which I've seen one of them using. Although the new Manager is what looks like to be the barrier that prevents entry. As It looks like a Volume that doesnt reference the Manager is possible.

My Question simply is; Could one independently add a Volume like a Kill Volume to an Object through the Unity Editor or is it something youd have to add functionality for? Any hacky way is of course allowed, just as long as it works

**Comment by SDGNelson** [comment]
Hmm interesting question. Do you have an example .dat+assetbundle using the kill volume this way that I could try loading up to see what is happening when the game tries to spawn it please?

**Comment by prank0011** [comment]
> Hmm interesting question. Do you have an example .dat+assetbundle using the kill volume this way that I could try loading up to see what is happening when the game tries to spawn it please?

This is a sample about DeadzoneVolume. It seems that it still works, but I can't make the size I want.
[DeadzoneVolume.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9470263/DeadzoneVolume.zip)

**Comment by prank0011** [comment]
> > > Hmm interesting question. Do you have an example .dat+assetbundle using the kill volume this way that I could try loading up to see what is happening when the game tries to spawn it please?
> > 
> > 
> > This is a sample about DeadzoneVolume. It seems that it still works, but I can't make the size I want. [DeadzoneVolume.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9470263/DeadzoneVolume.zip)
> 
> To be precise, I can't precisely control the zoom in the Z direction. . . X and y are fine. . . ![image](https://user-images.githubusercontent.com/68633558/187934467-142b806a-2c7f-4280-a1aa-39f349f540c6.png)

If you can, I hope you can increase the volume that increases/deducts player damage per second. I will try to make unofficial mod hooks.

**Comment by Gamingtoday093** [comment]
Oh snap. Youre right. That looks like itd work. The Size should be influenced by a trigger collider im pretty sure which you are missing. So youve tested this and deriving from a Monobehaviour just works? Idk it seems a bit weird. I guess its just down to how Unturned Loads the Scripts.

**Comment by Gamingtoday093** [comment]
Honestly, this looks to just be the solution. I am just silly. I'll close this issue here unless I find something else.

**Comment by SDGNelson** [comment]
Glad to hear it is working for you guys!
To clarify: a collider is not necessary, I think the issue there is that the mesh used by the game is 1x1x1 rather than 2x2x2. So for example a box volume with scale 3x3x3 only covers 1.5m in each direction.
