### ISSUE TITLE
[Feature Request] Hide Object's that couldn't be loaded in the Editor and make Logs easier to Access

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3399]
Exactly as the Title says. If an Object's Model is not loaded and is set to null the ObjectAsset will **Still** be loaded but you will not be able to place the Object in the Editor as it will throw `(ObjectAsset) *ObjectName* [*ObjectID*]: missing "Object" GameObject`.
*Every other asset checks this so I presume it's an oversight/bug.*

**Comment by SDGNelson** [comment]
It should show an error in the Errors menu with -ValidateAssets, but otherwise the Object.prefab does not actually get loaded until needed for the map. When it does eventually get loaded it should also log that error.

**Comment by Gamingtoday093** [comment]
Oh I had no idea that Objects were only loaded when the level was loaded. I guess that makes sense for performance. Its just that I've been getting a lot of reports from new Modders not being able to figure out why their Object doesn't get loaded when they for example haven't named their Object `Object` or their File Hierarchy is wrong.
They look at the Error log for help without any errors and get really confused when the object appears in the editor but placing it is not possible. I guess it is actually reported in the Error log after the object gets fully loaded. But It would appear that people don't check it again after not seeing it the first time. *I mean it's also obviously reported in the Client Logs in the Game Files, But thats not the easiest to check.*

Well anyways thanks for explaining that to me. I really dont have a brilliant solution to this issue. But maybe hiding objects that couldn't be loaded in the editor *(Unsure how realistic that is)* as well as perhaps making Logs way easier to access would help somewhat. Specially the last thing.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
