### ISSUE TITLE
The Train Does Not Receive Damage by Zombies and Bullets

### ISSUE THREAD

**Issue by V1CeNtE** [SmartlyDressedGames/Unturned-3.x-Community#34]
Zombies dont hit the train

**Comment by xdlewisdx** [comment]
You sure it's because it hasn't been damaged enough yet?

**Comment by V1CeNtE** [comment]
i lie, the train does not receive damage by zombies

**Comment by V1CeNtE** [comment]
and bullet either

**Comment by xdlewisdx** [comment]
close issue.

**Comment by xdlewisdx** [comment]
Wait what... i though you said they do receive damage? if so leave closed but if they do not probs should reopen?

**Comment by V1CeNtE** [comment]
all right, for a moment i felt bad

**Comment by SDGNelson** [comment]
The train not taking damage is intentional.
