### ISSUE TITLE
Make lasers show for other people

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#340]
Hey Nelson, I think it would be really awesome if you made it so you see all laser sights rather than just your own. Just a suggestion and it's probably a more advanced thing, but I think everyone would be happy to see it, especially RP and PVP servers.

**Comment by Trojaner25** [comment]
As a side note, Nelson only uses GitHub for tracking bugs, not suggestions.
For the  suggestions you can use the forum, reddit or the official discord.

**Comment by N1GHTPATROL** [comment]
Yeah sry I just know he checks this the most but I'll use reddit from now on

**Comment by SDGNelson** [comment]
Not going to be added to 3 sadly, but probably in 4.
