### ISSUE TITLE
Sometime When a new player join the server, all other players in the server will be kicked out of the server, the log shows "Disconnecting: PlayerID: XXX Name: XXX Character: XX BattleEye Print Player: # tHe w0rld disconnected"

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3400]
When a player enters the server, **all other players** in the server will be kicked out of the server **AT THE SAME TIME**, the log shows "Disconnecting: PlayerID: XXX Name: XXX Character: XX BattleEye Print Player: # tHe w0rld disconnected",So I lost a lot of server players :-1: 

I checked the logs, including but not limited to: Server_Germany.log, stats_log.txt, connection_log_27017, client_log, connection_log, service_log, systemmanger, configstore_log and workshop_log, and found that only **stats_log.txt** reported an error:
` [AppID 304930] CAPIJobStoreUserStats::BInit( ) - no stats found, aborting`
print how many logs to show how many players are offline.

I'd like to know what might cause players to drop at the same time, and a quick fix. thanks

**Comment by makeloffve** [comment]
Here is the logs:

**2022-08-29 12:13:42 and 2022-08-29 13:14:15** A collective disconnection occurred, 2022-08-29 13:14:15 After seeing a new player entering the server in the log, all other Online player disconnected from server

[connection_log_27017.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442109/connection_log_27017.txt)
[content_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442110/content_log.txt)
[Server_Germany.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442111/Server_Germany.log)
[service_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442117/service_log.txt)
[stats_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442118/stats_log.txt)
[systemmanager.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442119/systemmanager.txt)
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442120/workshop_log.txt)
[configstore_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9442121/configstore_log.txt)

**Comment by SDGNelson** [comment]
It looks like the server froze for about a minute which caused everyone to lose connection. Maybe a plugin trying to load something when that player connected?
