### ISSUE TITLE
Terrain editing error

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3402]
Greetings! 
When I create terrain on my map using the standard tools, occasionally holes appear that cannot be interacted with in any way. They cannot be removed and the only way to remove them is to remove a whole square of the area. Help solve this.

![20220829173049_1](https://user-images.githubusercontent.com/75787898/187225801-90e2c919-decc-4f00-b8f9-66bf3f280a19.jpg)

![20220829173053_1](https://user-images.githubusercontent.com/75787898/187225804-b3c6f6e1-5b6f-4bf9-8d0c-c9b13b46d3b4.jpg)

**Comment by SDGNelson** [comment]
Could you send me a map file which has this issue please?

**Comment by FireRain4** [comment]
I apologize for the delay. It turned out that this bug was solved by itself after restarting the game. And it never happened again...

**Comment by SDGNelson** [comment]
No worries. Glad it fixed itself for the meantime, but if you notice it happening again or any idea why please feel free to comment or email!
