### ISSUE TITLE
[Very minor feature request] ThisIsAComment Script

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#3405]
This is incredibly niche but doesn't seem like it would take any time to add, but a "Comment" script would be very handy for people dealing with many event hooks, as unity has no built in comment system. This would take very little time to add and would help people organize and understand, especially when passed between different people.

**Comment by prank0011** [comment]
If you don't need it to run in the game, you can make your own.

**Comment by DevInc0** [comment]
I agree with [prank0011](https://github.com/prank0011)
I'd say that you won't need a "Comment" script in game.
So, you can simply make your own script, which won't be loaded at run-time

```cs
using UnityEngine;

public class Comment : MonoBehaviour
{
    [TextArea]
    [SerializeField]
    private string _comment;
}
```

![image](https://user-images.githubusercontent.com/63493877/188118164-7607d7f5-8cb0-4772-adb0-d0705b33cecb.png)

**Comment by DrDallas1** [comment]
Huh. When I used a common script, my entire object broke, and I assumed it’s a preventative measure against scripts. Sorry.

**Comment by SDGNelson** [comment]
It should be fine to add arbitrary scripts because they will just be skipped by the engine while loading in-game. It would be nice if there was a way to document these setups in Unity built-in, but it is also not exactly an intended way of doing things. I will add a comment component in the next update.

**Comment by SDGNelson** [comment]
Added in the next update
