### ISSUE TITLE
steamnetworkingsockets spam

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3406]
This one printed 4 times every second `src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1781) : r >= 0`

**Comment by GazziFX** [comment]
Also players report kicks
![image](https://user-images.githubusercontent.com/43498426/188198782-7b947641-506a-4207-a2b3-9824694ac749.png)

**Comment by KodakDolph** [comment]
Confirmed the spam but haven’t heard about any kicks on my end

**Comment by y1meng** [comment]
> It looks like this means there was an unknown error while sending a packet. To disable the spam you can add `-LogSteamNetworkingSockets=0`

After today's update, my server also started to output "src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1781) : r >= 0" frantically, and players could not enter the server.

**Comment by y1meng** [comment]
> > It looks like this means there was an unknown error while sending a packet. To disable the spam you can add `-LogSteamNetworkingSockets=0`
> 
> After today's update, my server also started to output "src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1781) : r >= 0" frantically, and players could not enter the server.

I tried rebooting twice and everything is back to normal, weird issue...

**Comment by rube200** [comment]
It seems alot of people are reporting this bug, will be there any patch to fix it? or is a steamworks bug?
