### ISSUE TITLE
"Missing Floor"

### ISSUE THREAD

**Issue by Silverr12** [SmartlyDressedGames/Unturned-3.x-Community#3407]
After the newest update, in both singleplayer and multiplayer I have been unable to build structures such as roofs and stairs despite there being a floor and the required pillars, see below.
![ezgif-2-533838759e](https://user-images.githubusercontent.com/48173453/188255658-bba7592c-9993-479a-ac4f-c898f545e52f.gif)
I suspect this has something to do with the new adjustable floor height.

**Comment by DiFFoZ** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3356#issuecomment-1213537066

**Comment by Silverr12** [comment]
Thanks

> [#3356 (comment)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3356#issuecomment-1213537066)
