### ISSUE TITLE
Mod Hook Request: Instantiate Hook

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3408]
I've made a simple script that instantiates gameobjects, but unfortunately it's not a copy of the game's scripts, making it not work in-game. It'll be great to see this as a new mod hook for purposes that require duplication of gameobjects. Additionally it would be nice to have an option for the mod hook to activate the selected gameobject.

For anyone's curiosity on my script, this is how it went:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using Steamworks;


namespace SDG.Unturned
{
    public class Instantiate_Component : MonoBehaviour
    {
        public GameObject Clone_Target;
        public bool Clone_SetActive;

        public void Clone_Function()
        {

            GameObject Cloned_Target = Instantiate(Clone_Target, transform.position, transform.rotation);
            Cloned_Target.SetActive(Clone_SetActive);
        }

    }

}
```

**Comment by GazziFX** [comment]
How you want to control lifecycle of instantiated objects?

**Comment by OneManOperative** [comment]
However the creator wants them to be. My current use of them is basically indefinite, but I think they can already be controlled via timer event + destroy hooks.

**Comment by SDGNelson** [comment]
What do you have in mind to use it for?

**Comment by GazziFX** [comment]
> What do you have in mind to use it for?

Custom grenade launchers I think

**Comment by OneManOperative** [comment]
My current use for the mod hook is to clone gameobjects stored in prefabs without destroying them, in this case, vehicle-mounted rockets. But same can be applied to Gazzi's idea.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
