### ISSUE TITLE
[Unity Question] MasterBundle building takes very long time

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3409]
For some reason whenever I build a masterbundle, even one with very little data in it, it takes about 10-15 minutes. Is it normal, or is there a way to fix/improve it?
Also I think it used to be a lot shorter but then became this way at some point (but I didnt pay attention since I was bundling big mods so I thought that its okay).

**Comment by SDGNelson** [comment]
10-15 minutes without much in it seems odd. Even core.masterbundle is faster than that. Is that with multi-platform selected? Switching the build target to Linux, Mac, and back to Windows usually has a painful amount of overhead so I only do Windows while testing. If you look in Unity's log file there might be some timing info about what is taking so long.

**Comment by Spebby** [comment]
What's your hardware? On my old pc bundling times would take ~20 minutes at least, regardless of content being bundled. Are you using a Hard drive?

**Comment by DerpyHoowes** [comment]
Im not bundling multi-platform, windows only.
Yes, I am using hard drive and I have Core i3 cpu and 8 gb RAM. I know its kinda weak, but as I said, it used to bundle way faster, at least I think so.

**Comment by GazziFX** [comment]
> Im not bundling multi-platform, windows only. Yes, I am using hard drive and I have Core i3 cpu and 8 gb RAM. I know its kinda weak, but as I said, it used to bundle way faster, at least I think so. And even with bad pc specs, how it can bundle 3 items for 20 minutes straight?

It also depends how many data you have in project not only what you bundling I think

**Comment by Spebby** [comment]
> Im not bundling multi-platform, windows only. Yes, I am using hard drive and I have Core i3 cpu and 8 gb RAM. I know its kinda weak, but as I said, it used to bundle way faster, at least I think so. And even with bad pc specs, how it can bundle 3 items for 20 minutes straight?

Harddrive is the culprit. Check your read and write speeds and that should explain everything. Unfortunately there's not much you can do besides just getting better hardware. An SSD improves these kind of tasks radically. Ram may also be a bottleneck depending on if it's DDR3/4/5. 8gb isn't much and can be filled up pretty quick, but I don't think it's the biggest contributor here.
