### ISSUE TITLE
Ireland weapons

### ISSUE THREAD

**Issue by thereis** [SmartlyDressedGames/Unturned-3.x-Community#341]
There is a reason to remove the weapons from Ireland update?

For example, I was using a Dagger in a normal server, after this update I can't even spawn it, there is a reason the remove the weapons too?

**Comment by SurvivorCDG** [comment]
It seems to me that weapons from Ireland had non-vanilla style.

**Comment by thereis** [comment]
For me there is alot of similarity with the vanilla weapons.

There is no reason to remove it since it made part of the weapon arsenal.

**Comment by MoltonMontro** [comment]
> There is no reason to remove it since it made part of the weapon arsenal.

This isn't true. The Dagger was timed curated content. Its timed curation ends. If you wanted to still use the Dagger you should've downloaded the content from the Workshop.
