### ISSUE TITLE
Consumables are classified as weapons.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3411]
Pretty self-explanatory, makes it annoying for people using `is ItemWeaponAsset`. Someone seemed to have an issue with this on Imperial Plugins yesterday.

**Comment by MoltonMontro** [comment]
Consumeables use this because of vanilla items like the Explosive Chewing Gum, and nowadays some workshop/curated items likely do too.

**Comment by Jdance-Media** [comment]
No reason at all why they cannot be used instead. I did not even take the chewing gum into consideration, but that makes sense. Thank you for the context 👍.
I suppose the main reason why one would use `is ItemWeaponAsset` at first is because it can theoretically allow people to blacklist, whitelist, or ban all weapons.

**Comment by surv0013** [comment]
> making the statement `if (asset is ItemGunAsset && asset is ItemMeleeAsset && asset is ItemThrowableAsset)` would also do the job just fine.

`if (asset is ItemGunAsset || asset is ItemMeleeAsset || asset is ItemThrowableAsset)`

**Comment by GazziFX** [comment]
> `if (asset is ItemGunAsset || asset is ItemMeleeAsset || asset is ItemThrowableAsset)`

`if (asset is ItemWeaponAsset && !(asset is ItemConsumeableAsset))`
