### ISSUE TITLE
FoliageStorage improvements

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3412]
Current implementation produces huge file size https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3188
My implementation produces up to 3x smaller file size (502MB -> 163MB) https://github.com/GazziFX/FoliageStorageX
it saves foliage matrices in shorter and less precise form, but in practice didnt saw any visual differences

**Comment by GazziFX** [comment]
@SDGNelson

**Comment by GazziFX** [comment]
@SDGNelson

**Comment by GazziFX** [comment]
If you dont want to check whole repo, this is code to save matrix
```csharp
Matrix4x4 matrix = matrices[j];

// use "local" space to reduce effect of half precision
Vector3 localPos = matrix.GetPosition() - tilePos;

binaryWriter.WriteHalf(localPos.x);
binaryWriter.WriteHalf(localPos.z);
binaryWriter.Write(localPos.y); // keep y precision because it can be far away

Vector3 eulerAngles = matrix.GetRotation().eulerAngles;
binaryWriter.WriteHalfVector3(eulerAngles);

Vector3 scale = matrix.lossyScale;
binaryWriter.WriteHalfVector3(scale);

binaryWriter.Write(clearWhenBaked[j]);
```

**Comment by GazziFX** [comment]
Ну и где моя фича? 🤔
![image](https://user-images.githubusercontent.com/43498426/197245551-e779f132-137e-41a3-b28b-b4cfc8f45117.png)

**Comment by SDGNelson** [comment]
Foliage file size should probably be revisited at some point, but I'm not sure that this is the route I would take.
