### ISSUE TITLE
Clouds not visible on some %s of Max Draw Distance

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3413]
[Originally reported by Pelks on the SDG Forum.](https://forum.smartlydressedgames.com/t/clouds-disappearing-randomly-on-max-draw-distance/19433)

The supplementary gif provided showcases the issue fairly well. On some percentages, clouds are no longer visible. On others, they're perfectly visible. I'm able to recreate this issue.

![d9c33c2677ec880f8d5b4ff0259ba5655f75a476](https://user-images.githubusercontent.com/7608445/188518119-35273de1-c08b-4754-8781-0f6e59f91c5d.gif)

**Comment by SDGNelson** [comment]
Unfortunately this is related to the clouds change for OpenGL. For the meantime it was reverted for the next update. 😞

**Comment by MoltonMontro** [comment]
Ah, I knew there were earlier issues reported with OpenGL. I hadn't realized that this is part of the same problem. Thanks!
