### ISSUE TITLE
Charts are no longer rendered pixel perfect

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3414]
When rendering charts I've noticed that pixels are no longer sharp, they're being blurred. Looks fine when completely zoomed out, but looks bad when zooming in. Same for the GPS but may be intentional behaviour there.

Edit: this behaviour exists regardless of if a cartography volume is present or not

**Comment by SDGNelson** [comment]
This was actually intentional: the chart capture now uses 4 samples per pixel, essentially 200% supersampling. It makes thin lines like fences look nicer.
