### ISSUE TITLE
[Feature Request] Toggle + Dropdown support

### ISSUE THREAD

**Issue by DevInc0** [SmartlyDressedGames/Unturned-3.x-Community#3415]
Dear Nelson,
It would be extremely cool, if plugin developers would have an event `OnToggleChanged` (or so) at `EffectManager` class.

---

`UnityEngine.UI.Toggle` has `UnityEvent<bool> onValueChanged`.
I believe, it's the same song as `EffectManager.hookButtonsInUIEffect(Transform)`.
So, it must be really easy to add this feature.

---

Moreover, this feature will allow us to work not only with Toggle, but also with Dropdown, because the Dropdown list consists of Toggles.

**Comment by DevInc0** [comment]
`Important edit`

My bad. It won't work for `Dropdown`, because `Dropdown list` is created at the time `Dropdown button` is pressed, so Toggles won't hook when creating an UI.

---

But `UnityEngine.UI.Dropdown` has `UnityEvent<int> onValueChanged`, which still makes it same song as `EffectManager.hookButtonsInUIEffect(Transform)`. _**Second para of upper message**_

---

Hope, you'll add these features, because every Plugin+UI developer is in `extremely need of` it.

**Comment by DevInc0** [comment]
@SDGNelson just in case. 

At least say "no, I won't add it...".

There's no need to ignore us. We only want to _**help you**_ to make the game a better version of itself.

Best wishes,
DevInc0 with plugin developers community

**Comment by SDGNelson** [comment]
My position has been for a long time that I do not want to deepen the dependence on uGUI, and will improve plugin UI support once we can use UIElements. It sucks that it has been a long time.

**Comment by surv0013** [comment]
> My position has been for a long time that I do not want to deepen the dependence on uGUI, and will improve plugin UI support once we can use UIElements. It sucks that it has been a long time.

Of course, I understand everything, but the functionality is needed now, because I strongly doubt that I will make plugins in 2049.
![image](https://user-images.githubusercontent.com/17459138/191627868-948f8782-fae6-4332-a76d-7df642aee9e9.png)

**Comment by DevInc0** [comment]
@SDGNelson 
I strongly agree with surv0013

So, is there any chance to add these features in next updates? Please, we need it.

Many servers need it, but unforunately developers can't do anything about it.
