### ISSUE TITLE
How do I start the vehicle while the player is inside the vehicle?

### ISSUE THREAD

**Issue by aloshai** [SmartlyDressedGames/Unturned-3.x-Community#3416]
I somehow stop engine the player's vehicle on the plugin I made (by removing the battery). And after a while I add it back to the vehicle, but the vehicle does not start even though the battery is fully charged. How can I start the vehicle's to engine?

**Comment by aloshai** [comment]
more precisely, how do I toggle the vehicle's engine?

**Comment by SDGNelson** [comment]
Sorry, there is not currently a supported way to do this because in vanilla the battery can only be added without a driver.
