### ISSUE TITLE
Decay time is set to half by its own [elver]

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#3418]
look at the image of my config file. decay_time is set to 7 days (604800)
![config](https://user-images.githubusercontent.com/6502438/189496952-e53a8e4e-53d1-4c3b-b17f-958f88087d1a.png)

and now look at the image of sever configuration before joining the server. its actually half = 3.5 days(302400)
![server](https://user-images.githubusercontent.com/6502438/189497048-f8d1fe21-b177-4e5e-af5d-c9a9e0251f71.png)

can you tell me what could be reason?

**Comment by GazziFX** [comment]
Config file has three settings tiers Easy, Normal and Hard make sure it matches with gamemode on server

**Comment by aman7** [comment]
i know that, all the game mode have same settings, if you guys want, i can send whole config file

**Comment by DevInc0** [comment]
Well, I think the reason of your problem is map configuration, which "overrides" server configuration.

In `Elver's` configuration file (`Config.json`) both barricades and structures decay time are set to `302400`.

![image](https://user-images.githubusercontent.com/63493877/189675566-599f4f55-975c-4504-80ae-85873d11b291.png)

**Comment by GazziFX** [comment]
Harmony patch that will disable all overrides, you can insert it in plugin
```csharp
[HarmonyPrefix]
[HarmonyPatch(typeof(Provider), "applyLevelModeConfigOverrides")]
public static void applyLevelModeConfigOverridesPrefix()
{
    return false;
}
```

**Comment by SDGNelson** [comment]
Level settings can override the server config only if the server config value is equal to the default value. In the log it will say "Level overrides config" vs "Skipping level config override". If you would like to keep the decay time higher the easiest way would be to increase +1 it to e.g. 604801.
