### ISSUE TITLE
Rotating UI Effect

### ISSUE THREAD

**Issue by aloshai** [SmartlyDressedGames/Unturned-3.x-Community#3421]
I'm trying to make UI spedometer. I'm trying to rotate speed hand in the UI effect. I have a tried to use script but it didn't work I have came across with this comment;

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/435#issuecomment-434008325

This comment was in 2018. Is this supported yet?

**Comment by GazziFX** [comment]
I think radial fill is better than rotating

**Comment by aloshai** [comment]
I need a rotating because I want to make a moving speed pointer. Like this;
https://youtu.be/WKF_3BLD4-8?t=350

**Comment by aloshai** [comment]
Something nice can be done with radial too, but the rotating feature seems to better with things like roulette, wheel, clock or speed pointer.

**Comment by GazziFX** [comment]
I think there is should be universal component which would forward argument from server to UnityEvent, I can write some sample, but Nelson wont add it anyways

**Comment by aloshai** [comment]
Adding such content makes a difference for the servers. Attracts the attention of the players. I think Nelson doesn't break us developers and I hope add it. 🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺

**Comment by fahrettinenes** [comment]
![unknown](https://user-images.githubusercontent.com/43903270/189698553-81ae0709-9182-4f80-8c2e-0ec21cc44a86.png)

**Comment by GazziFX** [comment]
By UnityEvents arguments I mean this
<details>
<summary>Code</summary>

```csharp
using UnityEngine;
using UnityEngine.Events;

namespace SDG.Unturned
{
    public class ServerArgumentEventModHook : MonoBehaviour
    {
        public UnityEvent<string> StringEvent;
        public UnityEvent<float> FloatEvent;
        public UnityEvent<int> IntEvent;
        public UnityEvent<Vector3> Vector3Event;
        public UnityEvent<Quaternion> QuaternionEvent;
    }
}
```
</details>
<details>
<summary>Examples</summary>

![image](https://user-images.githubusercontent.com/43498426/189701861-97799424-cc66-4ab6-bc3a-a08af92d370b.png)
![image](https://user-images.githubusercontent.com/43498426/189702001-3af814fd-ee71-4d70-bb2d-fd13395c1c45.png)
</details>

**Comment by aloshai** [comment]
we may need a key to ServerEventsModHooks, in order for the Server to find the field of the event triggered

**Comment by GazziFX** [comment]
You mean RPC?

**Comment by DanielWillett** [comment]
I would love to see this as well. Would open up a lot of opportunities for triggering UI animations, vehicle features, etc.

**Comment by aloshai** [comment]
@SDGNelson Are you considering adding such a feature?

**Comment by fahrettinenes** [comment]
@SDGNelson, please dont ignore us :/

**Comment by SDGNelson** [comment]
I have considered something like that - this is part of the reason NetId can reference arbitrary child gameobjects by name. Converting effects to use guids and netids is on my to-do list. Ideally UI will not rely on uGUI however.

**Comment by aloshai** [comment]
> I have considered something like that - this is part of the reason NetId can reference arbitrary child gameobjects by name. Converting effects to use guids and netids is on my to-do list. Ideally UI will not rely on uGUI however.

I did not fully understand. You won't do it just for UIs, do I understand right?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
