### ISSUE TITLE
Mesh Replacement and Hitbox 

### ISSUE THREAD

**Issue by Orpham-Guestino** [SmartlyDressedGames/Unturned-3.x-Community#3422]
Hi, so this isn't really an issue, just a cool change that would allow modders a little more freedom, and it'd be cool to see. Mesh replacements are limited when it comes to how big they can be along with their hitboxes. I do a lot of things for a medieval server and a few months ago we were experimenting with making a mesh replacement of a giant (pics of our failed attempt), the only issue is setting up the skeleton correctly, so it doesn't slide along the ground when moving, and also making a hitbox because, well, it can't be grown or shrunk. Not a major thing, but I know a lot of people would like to see it, especially the hitbox part, allows for a lot more freedom when it comes to clothing and other things. 
![image](https://user-images.githubusercontent.com/113400165/189785420-ee91c015-bac0-4c6d-a3a9-ebccac6c85d7.png)
![image](https://user-images.githubusercontent.com/113400165/189785451-41fbda02-6d59-4c79-a003-2f018dcc33fd.png)

**Comment by surv0013** [comment]
I would like to add. We (server developers) don't just need a mesh replacement, we need a replacement for the prefab. Also, it was great to be able to add and/or replace character animations.

By the way, in the settings it is possible to change the number of bones, which leads to the breakage of the mesh. I believe that the number of character bones should be fixed.

**Comment by SDGNelson** [comment]
Sorry, this is unlikely to happen soon because lots of the related settings are hardcoded (for now).
