### ISSUE TITLE
[VERY IMPORTANT FEATURE REQUEST] ServerArgumentEventModHook

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3423]
Hello, we really need that. We can make better plugins and mods with this event hook.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3421#issuecomment-1243964752

Just check that and PLEASE DON'T IGNORE ME

**Comment by DrDallas1** [comment]
This isn't very important.
