### ISSUE TITLE
Fall Damage Detection/Ignoring

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3424]
Could you add something to make easier detection when player getting fall damage and prevention of it?

**Comment by SDGNelson** [comment]
What kind of usage do you have in mind?

**Comment by sunnamed434** [comment]
Event when player landed and bool (eg ref shouldAllow) for preventing getting the fall damage

**Comment by aloshai** [comment]
You can check `EDeathCause.BONES`

**Comment by GazziFX** [comment]
askDamage not fire damage event

**Comment by sunnamed434** [comment]
> You can check `EDeathCause.BONES`
> 
> ![image](https://user-images.githubusercontent.com/39468199/190857114-23b39a8e-6294-400e-9d8e-9946b7037e6f.png)
> 
> I guess it has not been used anywhere else. You can probably set `shouldAllow` to false when player takes damage by checking `EDeathCause.BONES`.

Probably it may done like that, this is bad practice I think, other plugins still be able to accidentally do damage with EDeathCause.BONES. This is also could be patched with harmony but there is a lot of code which can change with new updates, its harder to support in future

**Comment by SDGNelson** [comment]
Will add for the next update!

**Comment by sunnamed434** [comment]
similarly would be useful if in this event can be modified income damage which player will receive in result on fall
