### ISSUE TITLE
[Bug Report]The player can take choking damage in the safe zone.

### ISSUE THREAD

**Issue by prank0011** [SmartlyDressedGames/Unturned-3.x-Community#3425]
If this is intentional, can you make a safe zone where the player won't take choking damage?

**Comment by prank0011** [comment]
I want to make an underwater safe zone.
I didn't want to have lots of water volume just to make an underwater space, so I wanted to use a safe zone.

**Comment by GazziFX** [comment]
Theres one old bug, you can build in safezone when you on the edge of it

**Comment by prank0011** [comment]
> Theres one old bug, you can build in safezone when you on the edge of it

It doesn't matter. I just want the player to be able to fuel the generator before taking damage.
