### ISSUE TITLE
Client and server have different assets with the same ID 

### ISSUE THREAD

**Issue by YesItsZyax** [SmartlyDressedGames/Unturned-3.x-Community#3428]
Im having this issues in my server
"Client and server have different assets with the same ID ", I looked for every fix and all of it didn't work
![unknown](https://user-images.githubusercontent.com/113866809/190934769-f8df027b-80d6-406d-a664-188749139231.png)

**Comment by GazziFX** [comment]
Maybe GUID collision

**Comment by sunnamed434** [comment]
Seems to be you have the same item id well as server (mod from workshop or other servers), try to clear your all downloaded things from "Steam\steamapps\workshop\content\304930"

**Comment by SDGNelson** [comment]
Most likely the creator of the VKS_Scope mod copied the vanilla scope without changing the GUID. Ordinarily the downloaded mod would override the vanilla one, so my guess is that the mod is missing from the downloads as well.

**Comment by YesItsZyax** [comment]
I un-subscribed the mod with VKS scope and it fixed the errors, thanks!
