### ISSUE TITLE
Unturned Merged Maps Issue

### ISSUE THREAD

**Issue by RestoreMonarchy** [SmartlyDressedGames/Unturned-3.x-Community#3429]
Hello,

I'm working on an open-source tool that allows to merge multiple maps into a single one. The project is available [here](https://github.com/RestoreMonarchy/UnturnedMapMergeTool) on GitHub.

For example make a Large map from 4 existing Medium maps or Insane map from 1 Large and 3 Medium maps like on the picture below.  

<img src="https://user-images.githubusercontent.com/35507241/190928075-dc47b8db-4128-4ee7-81c6-db1097e6a705.png" height="400" />

I managed to merge data from the `Spawns`, `Environment` (except Navigation), `Level` (except `Visibility.dat`) and `Terrain/Trees.dat`. 
The landscape files I merged by copying and renaming tile file names from the original maps.

I'm not trying to completely eliminate the manual work of combining the maps. Actually I only meant to do the most time-wasting (impossible) job for the map maker which is copying data like spawns, objects, roads, trees and landscapes. 

Now I have a problem with describing the steps the user must take after running a tool.  
I tried to generate an empty map and make a tool save the combined files in that just created map directory, but the landscape and terrain wasn't visible and everything else was flying. 
I played around with editor tools and `config.json`. I have a problem with selecting the existing navigation flags and moving stuff in the editor. In the end all my playing came to nothing.

I recorded a 3 minutes video to demonstrate how I prepare the files for running my MergeTool and then showing the issue.  
I uploaded the video on Youtube: https://youtu.be/5mvsGzlMpr4

What can be causing the problem with moving the flags and objects in editor?  What can I try to fix this?

**Comment by SDGNelson** [comment]
Did you email me about this before? Otherwise I think there might be two similar projects working on this. Either way it looks like it is coming along nicely!

Could you send me an example merged map please and I will see what is preventing the navigation flags from being selected?

**Comment by RestoreMonarchy** [comment]
It wasn't me, I just started working on it last week. I was inspired by the AMIO map that showed up on workshop and then was taken down. 
This is the zip file of the exact copy I showed on the video. 
[MergedMaps.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9601060/MergedMaps.zip)

Thanks!

**Comment by SDGNelson** [comment]
Unfortunately I have no idea why it is not working. Some of them can only be clicked from one direction. Even within Unity's physics debugger tool the raycast only hits from one side of the box collider. Maybe a collider or physics limit being reached. :confused:

**Comment by RestoreMonarchy** [comment]
Ok, thanks for checking it anyways. 
I tried combining Washington and Yukon that in total have less objects, spawns, nodes and navigations than Russia, but the problem was still present (although it was much less frequent, I mean I was able to select most of the flags on this map).
Then I tried to eliminate the merged files one by one and I found out it works when I don't migrate the `nodes.dat`. I don't know why, but I'll work on it.
I got another issue with the zombies are not spawning on the map when I baked the navigation (and the spawns are present in the bounds), but I will try to fix it on my own too.

**Comment by RestoreMonarchy** [comment]
😐
Everything was because I used the incorrect save data version for `nodes.dat` (2 instead of 8).
I'm ashamed by making this mistake. I will be more careful next time.
Sorry for making this an issue here and thanks again for your quick reply.
