### ISSUE TITLE
[HELP] How to know wheather  two voicePlayers belong to the same group or not in Rocket plugin development

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3431]
Hello there!
I am developing my voice plugin. I want my server players to be able to voice with players in their group, so I overwrite `onHandleVoice(PlayerVoice speaker, PlayerVoice listener)`, but How to know wheather two voicePlayers belong to the same group or not?

anyone provide an API ? or code snippets would be better

**Comment by makeloffve** [comment]
Does this code work fine?

```C#
private bool onHandleVoice(PlayerVoice speaker, PlayerVoice listener)
{
    return UnturnedPlayer.FromPlayer(speaker.player).CSteamID.Equals(UnturnedPlayer.FromPlayer(listener.player));
}
```

**Comment by sunnamed434** [comment]
First of all you in your code what you send you checking not for a having the 'group', you checking for a having the same SteamId for both targets (speaker and listener), which group do you mean (Steam group/in-game group) ?

To check if players are have the same Steam Group ->
```cs
private bool onHandleVoice(PlayerVoice speaker, PlayerVoice listener)
{
    var unturunedPlayerSpeaker = UnturnedPlayer.FromPlayer(speaker.player);
    var unturunedPlayerListener = UnturnedPlayer.FromPlayer(listener.player);

    return unturunedPlayerSpeaker.SteamGroupID.m_SteamID == unturunedPlayerListener.CSteamID.m_SteamID;
}
```

To check if players are have the same in-game Group ->
```cs
private bool onHandleVoice(PlayerVoice speaker, PlayerVoice listener)
{
    // or by just calling method 'isMemberOfGroup'
    return speaker.player.quests.isMemberOfSameGroupAs(listener.player);
}
```

**Comment by makeloffve** [comment]
> First of all you in your code what you send you checking not for a having the 'group', you checking for a having the same SteamId for both targets (speaker and listener), which group do you mean (Steam group/in-game group) ?
> 
> To check if players are have the same Steam Group ->
> 
> ```cs
> private bool onHandleVoice(PlayerVoice speaker, PlayerVoice listener)
> {
>     var unturunedPlayerSpeaker = UnturnedPlayer.FromPlayer(speaker.player);
>     var unturunedPlayerListener = UnturnedPlayer.FromPlayer(listener.player);
> 
>     return unturunedPlayerSpeaker.SteamGroupID.m_SteamID == unturunedPlayerListener.CSteamID.m_SteamID;
> }
> ```
> 
> To check if players are have the same in-game Group ->
> 
> ```cs
> private bool onHandleVoice(PlayerVoice speaker, PlayerVoice listener)
> {
>     // or by just calling method 'isMemberOfGroup'
>     return speaker.player.quests.isMemberOfSameGroupAs(listener.player);
> }
> ```

thank you for your reply, Another problem needs help, I use 0Harmony.dll patch `public static bool handleRelayVoiceCulling_Proximity(PlayerVoice speaker, PlayerVoice listener);` to change default Proximity Voice behave to broadcast broadcast to everyone on the server, here is my code, but does not work at all.

VoicePatch.cs
```C#
namespace MakeloveVoiceChat
{
    [HarmonyPatch(typeof(PlayerVoice), "handleRelayVoiceCulling_Proximity")]
    internal class VoicePatch
    {
        internal static Handle onHandle;

        [HarmonyPrefix]
        private static bool handler(PlayerVoice speaker, PlayerVoice listener) => {return true;}

        internal delegate bool Handle(PlayerVoice speaker, PlayerVoice listener);
    }
}
```
Main.cs

```C#
harmony = new Harmony("broadcastechat");
harmony.PatchAll();
```

Is handleRelayVoiceCulling_Proximity() deprecated? any other way to boardcast voice to everyone? 
I am a newbee developer，Many thanks!

**Comment by makeloffve** [comment]
After debugging, I determined that the code segment 
```C#
        [HarmonyPrefix]
        private static bool handler(PlayerVoice speaker, PlayerVoice listener) => {return true;}
```
has been executed and returned true.

But I still can't hear the voice when I'm out of range.

**Comment by makeloffve** [comment]
> First of all, you should better learn about Harmony prefixes. - https://harmony.pardeike.net/articles/patching-prefix.html
> 
> "To stop executing prefixes and skip the original, let the prefix return a bool that returns false. To let the original run after all prefixes, return a bool that returns true."
> 
> So, in your case the original code of handleRelayVoiceCulling_Proximity() will be executed anyways.
> 
> Secondly, there's no need in Harmony at all. Because you can change sound distance through `ref PlayerVoice.RelayVoiceCullingHandler cullingHandler` parameter at `onRelayVoice`.
> 
> So, code in your plugin class should look like this:
> 
> ```cs
> protected override void Load()
> {
>     PlayerVoice.onRelayVoice += OnRelayVoice;
> }
> 
> protected override void Unload()
> {
>     PlayerVoice.onRelayVoice -= OnRelayVoice;
> }
> 
> private void OnRelayVoice(PlayerVoice speaker, bool wantsToUseWalkieTalkie, ref bool shouldAllow, ref bool shouldBroadcastOverRadio, ref PlayerVoice.RelayVoiceCullingHandler cullingHandler)
> {
>    cullingHandler = handleRelayVoiceCulling_Infinite;
> }
> 
> private bool handleRelayVoiceCulling_Infinite(PlayerVoice speaker, PlayerVoice listener)
> {
>    // Here you should return a bool value. Which will be a "condition" of hearing speaker`s voice by listener.
>    
>     return listener.player.equipment.itemID == 81; // Listener must hold a MRE in hand
>     return true; // Listener will hear speaker`s voice no matter what.
> }
> ```

I removed all Harmony code, add `handleRelayVoiceCulling_Infinite()`, **but still not work**, should I need to set `shouldAllow` & `shouldBroadcastOverRadio` to true?  know nothing about `shouldAllow`  :(

```C#
private void OnRelayVoice(PlayerVoice speaker, bool wantsToUseWalkieTalkie, ref bool shouldAllow, ref bool shouldBroadcastOverRadio, ref PlayerVoice.RelayVoiceCullingHandler cullingHandler)
{
       shouldAllow = true;
       shouldBroadcastOverRadio = true;
       cullingHandler = handleRelayVoiceCulling_Switch;
}
```

**Comment by DevInc0** [comment]
But what do you have inside of `handleRelayVoiceCulling_Infinite`?

**Comment by makeloffve** [comment]
> But what do you have inside of `handleRelayVoiceCulling_Infinite`?

just 

```cs
private bool handleRelayVoiceCulling_Infinite(PlayerVoice speaker, PlayerVoice listener)
{
    return true; 
}
```

**Comment by sunnamed434** [comment]
> @SDGNelson @DevInc0 @sunnamed434 any suggestion ? I'm stuck in this :(

What the problem is?

**Comment by GazziFX** [comment]
Should be something like this I think

```csharp
private void OnRelayVoice(PlayerVoice speaker, bool wantsToUseWalkieTalkie, ref bool shouldAllow, ref bool shouldBroadcastOverRadio, ref PlayerVoice.RelayVoiceCullingHandler cullingHandler)
{
   if (speaker.player.quests.isMemberOfAGroup) // if player not in group it wont override behavior
   {
      shouldBroadcastOverRadio = true;
      cullingHandler = handleRelayVoiceCulling_Group;
   }
}

private bool handleRelayVoiceCulling_Group(PlayerVoice speaker, PlayerVoice listener)
{
    return speaker.player.quests.isMemberOfSameGroupAs(listener.player);
}
```

**Comment by makeloffve** [comment]
> > @SDGNelson @DevInc0 @sunnamed434 any suggestion ? I'm stuck in this :(
> 
> What the problem is?

I want everyone else in the server to be able to hear the sound when someone is holding alt and talking. what do i need to do in my rocket plugin.

**Comment by makeloffve** [comment]
thanks for erverone，i will close

**Comment by makeloffve** [comment]
Close it
