### ISSUE TITLE
Bumper damage detection

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3432]
Could you add something to add detection when vehicle getting damage that caused by bumper?

**Comment by Orpham-Guestino** [comment]
Something like it records it in logs or what?

**Comment by DevInc0** [comment]
> Something like it records it in logs or what?

I'd say something like an event.

But is it possible at the moment?

**Comment by GazziFX** [comment]
> But is it possible at the moment?

Isnt it just `EDeathCause.ROADKILL`?

**Comment by DevInc0** [comment]
> Isnt it just `EDeathCause.ROADKILL`?

`EDeathCause.ROADKILL` is for on player getting damage.

But sunnamed434 asked for "`when vehicle getting damage`"

**Comment by sunnamed434** [comment]
I mean firing the event when vehicle bumper getting damaged (eg ref for damage, vehicle), at the moment there is no such thing. `EDeathCause.ROADKILL` as I understand this is not what is need

**Comment by Gamingtoday093** [comment]
I made a plugin that does this! You really dont need to ask Nelson to implement something like this when you can do it yourself

**Comment by sunnamed434** [comment]
> I made a plugin that does this! You really dont need to ask Nelson to implement something like this when you can do it yourself

Thats as great thou made plugin that does it. If you want you can post code here, to understand what are you talking about
