### ISSUE TITLE
Issue with note at Washington military base

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3433]
![image](https://user-images.githubusercontent.com/67397422/192113158-b54d22f3-3795-4e18-b599-b512b9686577.png)
In the image, you can see that Intractability_Text_Line_7 is visible for some reason.

**Comment by SDGNelson** [comment]
Thanks for the report. Whoops! I suspect this broke when I tidied up some of the translation code to always load English as a fallback. Something probably changed to treat an empty value as missing.

**Comment by Jdance-Media** [comment]
👍
