### ISSUE TITLE
[BUG] Impact grenade not disappear after explosion

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#3434]
Impact grenade (Clientside) is not removed after explosion. I think it is necessary to create a client component "ImpactGrenadeClient" to solve this problem.
```CSharp
//Class "UseableThrowable"
if (Provider.isServer)
{
    //Serverside grenade component
else
{
    //Clientside grenade
    Object.Destroy(transform.gameObject, equippedThrowableAsset.fuseLength);
}
```

**Comment by SDGNelson** [comment]
Replacing the projectile physics is on my to-do list for the very near future, so this might be taken care of as part of that.
