### ISSUE TITLE
Vehicles on client are out of sync with the server

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#3435]
Please see the video: https://youtu.be/DSaeyaTA6fo?t=30

Sometimes when player exits the vehicle he and the vehicle get teleported back. 

The server is not overloaded, all other stuff working perfectly.

**Comment by SDGNelson** [comment]
Vehicle physics are simulated by the driver's client - eventually I would like to convert vehicles to be fully server authoritative.

**Comment by D-AIRY** [comment]
![playermovement fixedupdate](https://user-images.githubusercontent.com/20150321/192723818-4eda7ba2-6d8b-4a9a-a6d4-217322581d01.PNG)
Shouldn't there be just `PlayerInputPacket` instead of `WalkingPlayerInputPacket` in PlayerInput::FixedUpdate() on the first spot?
