### ISSUE TITLE
Currency Localization

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3438]
Currently {0} doesn't work for Currency Condition. If it's used in a quest, it won't even open the quest. It doesn't work on objects as well.
Are there any plans to change that and actually make Currency Localization editable to show how much $ the player has on them exactly?

**Comment by SDGNelson** [comment]
It looks like currently only the target value is formatted into the currency condition. My guess is that you have both {0} and {1} which is throwing an exception when used in those places. For the next update I will change this to also format in the current value.
