### ISSUE TITLE
800x600 not able to click check box in singleplayer

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3439]
![image](https://user-images.githubusercontent.com/65300126/193318679-042a7a2f-9d97-411e-bd97-305debeb71cb.png)
![image](https://user-images.githubusercontent.com/65300126/193318787-cbe8bc84-adfa-4324-b4b1-68ba658eae5d.png)

**Comment by SDGNelson** [comment]
Pretty wild that some players are still using 800x600 in 2022. Will fix that menu's alignment.

**Comment by aviadmini** [comment]
I use that resolution when I have a single monitor (laptop) , game + server both fit on screen pretty easily then
