### ISSUE TITLE
Now zombies might make vehicles fly

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3441]
Tested in single player with random cars
![image](https://user-images.githubusercontent.com/65300126/193320046-95762ece-eeca-4094-b478-0038dae5faf6.png)
![image](https://user-images.githubusercontent.com/65300126/193320269-54dfb326-0411-4e75-a9fb-776afd1725dc.png)
![image](https://user-images.githubusercontent.com/65300126/193320368-68ba56c1-42bc-42e4-89eb-3ae55bd3d609.png)

**Comment by GazziFX** [comment]
This problem exist for years

**Comment by SDGNelson** [comment]
It has been like this for a long time, sorry.

**Comment by sunnamed434** [comment]
> It has been like this for a long time, sorry.

Are you sure? I dont think so,
here is a small vid about that https://vimeo.com/755989189

**Comment by GazziFX** [comment]
> Are you sure? 

Yes, this is on 3.22.10.1 https://youtu.be/OyheBg6CCvQ
![image](https://user-images.githubusercontent.com/43498426/193428838-ec1bc56c-903e-4a49-ac28-4ef4312214a3.png)

**Comment by sunnamed434** [comment]
> > Are you sure?
> 
> Yes, this is on 3.22.10.1 https://youtu.be/OyheBg6CCvQ ![image](https://user-images.githubusercontent.com/43498426/193428838-ec1bc56c-903e-4a49-ac28-4ef4312214a3.png)

Interesting feature
