### ISSUE TITLE
[Feature request] Option to disable camera shake on player hit

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#3445]
Would it be possible to add an option to disable the shaking of camera (flinch) when player gets damage? Its a nice addition to the game overall, but its definitely not the best for all type of servers. Or maybe even better option would be to add multiplier on how hard camera shakes when you get shot instead of disabling it completely.

**Comment by GazziFX** [comment]
Temp solution patch `PlayerLife.doDamage`
