### ISSUE TITLE
Sound settings not saving on Linux

### ISSUE THREAD

**Issue by Romelete** [SmartlyDressedGames/Unturned-3.x-Community#3446]
When the sound settings are changed (set to zero) and the game is closed and reopened, the sound settings return to default at 100%.  Not sure if something I'm doing wrong.  Issue wasn't present on Windows 10.

OS: Pop!_OS 22.04
Version: 3.22.16.0

**Comment by Romelete** [comment]
After doing some messing around with proton the issue does not occur on proton experimental, not sure why

**Comment by SDGNelson** [comment]
Glad to hear you got it working!
Proton might be more performance than native if native is using OpenGL by default whereas proton is using Vulkan through D3D layer.
Are other settings not saving? Volume settings are in the same file as all of the other options in the Options menu.

**Comment by Romelete** [comment]
On further inspection if the options are changed in the main menu, the settings stay as I set them, but if the options are changed in the editor, the game changes them to what they were set to before.

**Comment by SDGNelson** [comment]
Thanks for the report! Options must not be getting saved properly, will investigate.
