### ISSUE TITLE
Game issues screen resolution and frequency to fall.

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#3447]
When I start the game, it changes my resolution to 1024x768 and frequency to 60 Hz.
Defaults for my monitor is 1920x1080 and 144 Hz. (It does even if game is console)

When I change it back to defaults, it's just falls to the same settings, even if game closed.
Nvidia driver is newest 517.48

**Comment by GazziFX** [comment]
Never heard about it, but faced in opposite way if I set 800x600 after map loading it defaults to 1920x1080

**Comment by Sl4vP0weR** [comment]
> Did you tried to change with command line arguments?

I didn't, I think it wouldn't fix the issue.

**Comment by SDGNelson** [comment]
If you can attach the Client.log file there might be an explanation. Otherwise the command-line arguments may be a good way to force the engine to use the proper settings.

**Comment by Sl4vP0weR** [comment]
Driver reinstallation fixed issue.
