### ISSUE TITLE
Animation of an animal.

### ISSUE THREAD

**Issue by SaneKCLOFF** [SmartlyDressedGames/Unturned-3.x-Community#3451]
I made an animal as a drone and there is a problem with the attack animation, its attack animation works very strangely. During the attack, other animations may start playing, or the attack animation may work through time (i.e. 1st attack with animation, 2nd attack without animation, animation stops, 3rd attack again with animation.) I don’t know what could be problem (what happens somehow can be connected with a long animation, since with a length of 30 frames the animation works every other time, and with a length of 24 frames the animation starts to mix with other animations.). I would also like to know if it is possible to increase the attack distance for an animal?

https://drive.google.com/file/d/1h2SrvWZX8jMmUoUynx0wVayfmlhLnIbA/view?usp=sharing
https://drive.google.com/file/d/1hz5G4Mvvr-KSrk0NmEjmnudDUUhOsBcG/view?usp=sharing
https://user-images.githubusercontent.com/91375266/194111092-a5eb8eba-1962-46e5-bcad-801326897386.mp4

**Comment by SDGNelson** [comment]
It might be short enough that the blending duration is too long. Unfortunately the animal stuff is not very customizable for clever uses like this. I do want to rewrite a bunch of the enemy/zombie/AI features at some point.

**Comment by SaneKCLOFF** [comment]
So I need to increase or decrease the duration of the attack animation?

ср, 5 окт. 2022 г. в 21:09, Nelson Sexton ***@***.***>:

**Comment by SaneKCLOFF** [comment]
In the examples of the unity, animals with an attack use 24 frames, I
thought that exactly 24 was needed.

ср, 5 окт. 2022 г. в 21:17, SaneKCL ***@***.***>:
