### ISSUE TITLE
Player settings don't save when quitting directly from the pause menu

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#3452]
I noticed this a while back, but wasn't sure if it was just paranoia or not, and I thought someone would've mentioned it already. [Romelete has pointed it out with sounds on Linux though](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3446)

Whenever I change any settings i.e. turning off V-Sync or disabling shadows, and then pressing the "Quit" button to close the game, the settings will not save and opening the game again V-Sync and shadows will be enabled again. Only way to have them save is to exit to the main menu first, then quit.

I noticed this inside the editor specially, though I believe it happens on singleplayer/multiplayer as well.

I'm on Windows 10, and on the latest Unturned version.

**Comment by SDGNelson** [comment]
Sorry about this, it will be fixed soon as mentioned in the issue you linked.
