### ISSUE TITLE
[Bugs] A list of (very minor) Editor related bugs

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3454]
Hi there, just wanted to make a list of all the (very minor) editor bugs that have been bothering me over the last few months. 
Most of these are so minor that they don't even need fixing, but I thought it would be good to have them documented somewhere to make sure you're aware of them. 

1) Some objects randomly flip while being rotated.
(Potential cause; rotating objects that have previously been flipped prior to 3.22.15.0 "Negative scaling not rotating objects when necessary.")
![editorBug1](https://user-images.githubusercontent.com/71527679/194715667-da82f457-6fac-4d62-8de8-6c8f8dfdc1f8.gif)
![editorBug4](https://user-images.githubusercontent.com/71527679/194715737-e4bcc5fa-42b8-4247-8a69-8e748f6ee38d.gif)

2) Terrain materials don't line up correctly on tile edges (very frustrating). 
![editorBug2](https://user-images.githubusercontent.com/71527679/194715759-4a3adc68-71eb-420a-bccc-0770f054b5f9.gif)

3) Not necessarily a bug, but the hotkeys for brush tools (e.g. B for brush size) seem to be based on the mouse's position on the terrain within a 3D plane. This makes it difficult to accurately use the hotkeys while under the map, or while the camera is horizontal to the terrain (note how the Brush Strength quickly jumps from 20 to 800+ with very little mouse movement when the mouse reaches the horizon line). It might be better to track the mouse's distance from the starting point within screenspace, on a 2D plane. 
![editorBug3](https://user-images.githubusercontent.com/71527679/194715848-09e7277c-4bf1-48da-bc48-f0feb11a33e1.gif)

4) Minor object bug; the "Hanger 1" object has strange shadows on the side that change with the object's rotation<img width="649" alt="image" src="https://user-images.githubusercontent.com/71527679/194716062-1311409a-995e-49e4-9332-f2957641693d.png"><img width="649" alt="image" src="https://user-images.githubusercontent.com/71527679/194716071-8d8c238e-0f74-4d54-b40f-db092bff8056.png">

5) The weight dots on the Material and Heights brush disappear when there is X number of dots within the circle, presumably intentionally, but the number of dots which can be visible before they are hidden is different between the tools, equating to brush size 26 for the materials tools, and only 18.3 for the heights tool. Also, any sizes close to these number (e.g. 25.9 or 18.2 respectfully) cause the weight dots to flicker. Besides the flickering, it would be nice if these numbers were increased. 18 is quite a small brush size where working with large areas of terrain, and the dots really help with precision.
![editorBug6](https://user-images.githubusercontent.com/71527679/194716293-103b1668-9276-4c28-9704-c28fa97b7c12.gif)

6) Minor object bug; you can't use the alternative transform tools with "Prison Slide Door" or "Prison Swing Door". <img width="389" alt="image" src="https://user-images.githubusercontent.com/71527679/194727311-7314268f-73f2-460f-915c-30178fb90c79.png">

7) Again a very minor bug that doesn't necessarily need fixing, but each input box seems to react differently to being set to a ridiculously high number, some cap out to 2048, some reset to 1000000000, some have no cap, and some reset back to zero. 
Also when you reset a value back to zero after typing a large number, the text is out of alignment. 
![editorBug7](https://user-images.githubusercontent.com/71527679/194728138-19b977a4-1f1d-4a98-a9ac-3bca69c8911b.gif)

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time!

Will do:

4. It looks like the normals on the sides of the hangar are messed up. Will fix!

Other:

1. I think something like this was fixed. If you have been making maps recently did you run into this again?

2. It has been annoying like this ever since the terrain tiles were added. I should really re-investigate the terrain shaders at some point.

3. It uses a 2D plane on the up axis, so editing from the side like that doesn't work very well.

5. This is the Max Preview Samples option.

6. Not sure if this was changed eventually but it's probably because they have skinned mesh renderers.
