### ISSUE TITLE
Change admin color in Unturned 

### ISSUE THREAD

**Issue by Nervy1** [SmartlyDressedGames/Unturned-3.x-Community#3455]
how can l change admin blue color ( not in chat) but on a player list in game 
or who can make a plugin for it l will pay

**Comment by GazziFX** [comment]
Hide Admins only can affect it

**Comment by Nervy1** [comment]
l dont want to hide it buy just change the color

**Comment by GazziFX** [comment]
You can try to insert color tag

**Comment by Nervy1** [comment]
l have tried it with a premission command bubt l chanched only chat color not  nickname

**Comment by GazziFX** [comment]
Rich tags also not work in players tab
![image](https://user-images.githubusercontent.com/43498426/194852427-3011fee0-1d8b-429f-9967-b71fadff0836.png)

**Comment by Nervy1** [comment]
but can l change color for other players ?
not in chat

**Comment by GazziFX** [comment]
> but can l change color for other players ?
> not in chat

You can't

**Comment by Nervy1** [comment]
but l saw it on a different server there players had it

**Comment by GazziFX** [comment]
I dont think this possible
![image](https://user-images.githubusercontent.com/43498426/194949919-95b1649d-7f7d-40d1-9293-6dea81357769.png)

**Comment by Nervy1** [comment]
where players color setup there ?

**Comment by Nervy1** [comment]
and l cant rewrite it where it says Palette ADMIN ?

**Comment by Nervy1** [comment]
and what does palette means? can l write a different color there ?

**Comment by Nervy1** [comment]
hmmm l dont hav that folder on a host server in files

**Comment by GazziFX** [comment]
> and l cant rewrite it where it says Palette ADMIN ?
> 

Just a predefined value, you cant change it from server

**Comment by DanielWillett** [comment]
The best you can do is change the color of their name in chat but it won't reflect in the menu or in the hint when you look at them.
