### ISSUE TITLE
Unable to enter lan server

### ISSUE THREAD

**Issue by negrifelipe** [SmartlyDressedGames/Unturned-3.x-Community#3463]
Hi, after serveral attempts to enter a local server i keep getting this error: `Rejected because your calculated ping (913ms) exceeded the server maximum of 750ms.`. Entering a server that it is not on my machine works fine.

- I tried removing both openmod and rocketmod
- Setting Timeout to 10000
- Making sure i have both client and server updated
- Restarted my pc
- Deleting the hole server

**Comment by negrifelipe** [comment]
Instead of connecting using the Play -> Server -> Lan section using   Play -> Connect -> 127.0.0.1, 27015 works

**Comment by GazziFX** [comment]
> - Deleting the hole server

😆

**Comment by SDGNelson** [comment]
Weird that your LAN ping is so high. Glad to hear you got it working though!
