### ISSUE TITLE
Optimization for laptop

### ISSUE THREAD

**Issue by FoxDevUnt** [SmartlyDressedGames/Unturned-3.x-Community#3466]
Hi Nelson, I have 1 problem. My PC is giving out pretty low fps in the game and I don't know what to do. 
My laptop configuration is:
Processor: Intel Core i7-11800H 
Video card: Nvidia RTX 3050ti 4 gb DDR6
Memory: DDR4 16 gb 
Disc: NVME 512gb.
FPS in Unturned 50-60 on any settings, frame lock is on 140 frames because I have a 144 hertz monitor. In other games, more demanding games, the fps is much higher than here.

**Comment by FoxDevUnt** [comment]
I am also the developer of one of the largest servers for rust fashion in unturned.
And I need to understand how to explain to players who have similar systems that it's not about optimizing my project, but about optimizing the game.

**Comment by SDGNelson** [comment]
60 fps with those specs seems pretty good. Unturned is CPU-bottlenecked, mostly by culling and rendering. Hopefully that will change someday.

**Comment by FoxDevUnt** [comment]
> 60 fps with those specs seems pretty good. Unturned is CPU-bottlenecked, mostly by culling and rendering. Hopefully that will change someday.

but let's say there are about 35 arids on the map
