### ISSUE TITLE
Increasing the amount of things stored in storage

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3468]
Currently, the maximum number of items in storage is 255.
This is very disturbing if the storage contains things 1 by 1 in size.

Nelson, please increase this number. Many global servers where more community plays the game need this increase.

**Comment by SDGNelson** [comment]
Thanks DiFFoZ, unfortunately that is still the most up-to-date answer.

**Comment by GazziFX** [comment]
Sample module to expand limit from 200 to 255
https://github.com/GazziFX/ItemCountExpander
![image](https://user-images.githubusercontent.com/43498426/196294615-f9f4fc0e-0a22-40f8-9e49-7638047d08ca.png)

**Comment by PARTOVIY** [comment]
@GazziFX this does not work with storage and is it possible to make the increase larger than 255?

**Comment by GazziFX** [comment]
How did you tested storages? You cant increase it more because many methods use byte indexes, also storages save items count as byte.
