### ISSUE TITLE
Workshop Editor Not Baking Trees

### ISSUE THREAD

**Issue by AthenaDev** [SmartlyDressedGames/Unturned-3.x-Community#347]
I've been doing some workshop editing and I've found myself unable to Bake trees.

All of the settings are fine and they should be baking, but they simply don't. The closest I've come to fixing this is changing the Tree rendering from Legacy, but that makes my game crash every time I play on a normal map, and for some reason that isn't working anymore.

The only error I get in logs is this:
`Desired shader compiler platform 15 is not available in shader blob`

Also, if you haven't seen this issue, would you please look at it?
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/307#issuecomment-399416611
I have 16GB RAM and decent graphics..Not sure why this is happening.

**Comment by SDGNelson** [comment]
Double-checked and it seems to be working. Are you trying to use the older resource tools on a map using landscape v2? Otherwise when this comes up it's typically due to the editor's poor communication of what the options do.

**Comment by AthenaDev** [comment]
I don't think I'm using older resource tools - I've just created the map recently, within the past week or two. Is there any way specific to check for those settings? I've never specified for anything to be Landscape v2.

**Comment by AthenaDev** [comment]
Managed to get this working. I'm thinking the issue might've been "the editor's poor communication of what the options do," but for future reference the new tree rendering system in settings is usually a safe solution.
