### ISSUE TITLE
Deleting and transforming Selections in Devkit bugged

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3470]
The Selection tool in the Devkit seem bugged. Things can be selected, but the tool is generally unresponsive (e.g., tool handles don't work, so the Inspector tool has to be used to transform stuff). Additionally, the [Delete] function doesn't seem to work.

**Original report:** https://forum.smartlydressedgames.com/t/broken-devkit/19576/

**Comment by MoltonMontro** [comment]
Looked into this a bit further, and renamed issue accordingly.

**Comment by SDGNelson** [comment]
Sorry for my delay was thinking about this. Will probably move the remaining misc stuff into the Nodes editor, and put the devkit selection tool in there as part of fixing it.

**Comment by MoltonMontro** [comment]
This should be fixed as of 3.22.19.x
