### ISSUE TITLE
[HELP] Where to get param key in API ‘public static void sendUIEffect(ushort id, short key, bool reliable) ’

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3471]
I have completed an effect mod, bundled and uploaded it. When programming using rocket, I called `EffectManager.sendUIEffect(ushort id, short key, bool reliable);` to show effect, but I could not get the the param **short key**.I got **ushort id** in .dat, Where to get param **key**?

**Comment by DevInc0** [comment]
This is a parameter for binding the effect to some value, so that later it can be conveniently accessed through `sendUIEffectText` and `sendUIEffectVisibility`

You can set any value that is convenient for you in the range `from -32.768 to 32.767`

**Comment by rube200** [comment]
Are u sure?
It is a ushort

**Comment by GazziFX** [comment]
> Are u sure?
> It is a ushort 

key is short

**Comment by makeloffve** [comment]
> > Are u sure?
> > It is a ushort
> 
> key is short

thanks a lot，worked!

another question.
I want to send effect UI every time the player is born(connected or death respawn). I didn't find a suitable api for my sendEffectUI method. what should I do?

**Comment by rube200** [comment]
There is a event for when player respawn and connect

**Comment by SDGNelson** [comment]
Originally the intention was that some helper for assigning those key IDs to plugins would be included. Once effects are converted to NetIds then those will be available instead.

**Comment by makeloffve** [comment]
> ntention was that some helper for assigning those key IDs to plugins would be included.

have learned event `OnPlayerConnected` for connect, but not work when player respawn.

**Comment by makeloffve** [comment]
> I want to send effect UI every time the player is born(connected or death respawn). I didn't find a suitable api for my sendEffectUI method. what should I do?

@SDGNelson hello Nelson, I want to send effect UI every time the player is born(connected and death respawn). but I didn't find a suitable event api for my sendEffectUI method. what should I do?

**Comment by DevInc0** [comment]
Use either `SDG.Unturned.PlayerLife.OnRevived_Global` or `Rocket.Unturned.Events.UnturnedPlayerEvents.OnRevive`
