### ISSUE TITLE
[Bug] Map Editor: Coordinate Limit

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#3472]
When creating a map, we encountered a limitation in the map editor that prevents us from placing an object beyond coordinates 4096. At the same time, it is possible to place a landscape.

**Comment by GazziFX** [comment]
4096 is the regions bounds and its not configurable

**Comment by surv0013** [comment]
> 4096 is the regions bounds and its not configurable

The point is not what it is, but why it is so. You can put new landscape tiles, but you can’t build on them, it seems to me that it shouldn't be like that.

**Comment by GazziFX** [comment]
Current system is hardcoded to insane map size
```csharp
private static void getUnsafeCoordinates(Vector3 point, out int x, out int y)
{
   x = Mathf.FloorToInt((point.x + 4096f) / (float)Regions.REGION_SIZE);
   y = Mathf.FloorToInt((point.z + 4096f) / (float)Regions.REGION_SIZE);
}

internal const byte CONST_WORLD_SIZE = 64;
public static readonly byte WORLD_SIZE = 64;
internal const byte CONST_REGION_SIZE = 128;
public static readonly byte REGION_SIZE = 128;
```

**Comment by Spebby** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3343
previously reported here
