### ISSUE TITLE
"Grass set to low" bypass.

### ISSUE THREAD

**Issue by Azura-GH** [SmartlyDressedGames/Unturned-3.x-Community#3475]
Hello, Nelson. I wanted to report that people can bypass the new grass option by just using the preferences.json.

I hope this will be fixed soon. Since it gives people a unfair advantage over those who don‘t know how to do it / people who actually care about some decent graphics in the game. If you know what I mean.

Thanks!
-Azura

**Comment by SDGNelson** [comment]
The game should override the "off" setting to "low" for old config files, and Preferences.json does not have any foliage-related settings. One potential issue (foliage visibility group) comes to mind I should sort out but I wonder if they are using something else?

**Comment by GazziFX** [comment]
Foliage.blob hash not included in level

**Comment by SDGNelson** [comment]
A variety of workarounds to disable grass - including the per-level Foliage file hash - are fixed in the next update.
