### ISSUE TITLE
Converting Germany to Legacy

### ISSUE THREAD

**Issue by squidland** [SmartlyDressedGames/Unturned-3.x-Community#3477]
Hello! I am attempting to edit Germany in the editor but running into trouble. Since it was made in the devkit is there any possible way to convert it over to the editor? For example saving the objects to Objects.dat instead of the Level.hierarchy file.

**Comment by SDGNelson** [comment]
Eventually this should be sorted out as part of merging the devkit and regular editor together. For the meantime there is no way to do this however, sorry.
