### ISSUE TITLE
Quest Reward option to give item as full instead of empty. #196

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3478]
It'd be great if there was an option for quest rewards to have a modifier that can specify if the rewarded item is full, such as a gas can/canteen which currently can only be given as empty, unlike vendors which give the item as full.

**Comment by Gamingtoday093** [comment]
More Specifically Vendors give Items with the `EItemOrigin` of `Admin` while NPC Item Reward gives Items with the `EItemOrigin` of `Craft`.

**Comment by DMJaxun** [comment]
@SDGNelson

**Comment by SDGNelson** [comment]
Okay I will see about an option for this soonish
