### ISSUE TITLE
[Bug] Can't set the isBreathable Property for OxygenVolume (Script)

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3479]
This is **NOT** related to the Unturned Map Editor but rather using the OxygenVolume as a Script on a GameObject for a Mod.

After studying the code behind the OxygenVolume I created this Script to reference it in a modded item but there is an issue with the `isBreathable` property. Both `Shape` and `falloffDistance` both work flawlessly but for some reason `isBreathable` cannot be set. It just defaults to `true`. I've tried turning on the OxygenVolume during runtime with no avail. Looked at the Code for hours trying to understand if there is anything wrong. Just wondering if you could give me some more insight on what I may have messed up or if there is a limitation with initilizating the OxygenVolume this way?
```
using System;
using UnityEngine;

namespace SDG.Unturned
{
    // The New Volumes use the Scale of the GameObject as the Size for the Volume, No Colliders Required
    // This Volume Script should be attached to an Empty GameObject with Tag and Layer :: Trap
    // To Visualize the Size of the Volume Temporarily Attach either a BoxCollider or a SphereCollider. Making sure that the Collider Component uses the default Radius ( 0.5 ) or Size ( 1 1 1 )
    public class OxygenVolume : MonoBehaviour
    {
        public bool isBreathable = true;

        public ELevelVolumeShape Shape;

        public float falloffDistance;
    }
    
    public enum ELevelVolumeShape
    {
        Box,
        Sphere
    }
}
```

**Comment by GazziFX** [comment]
You cant just copy inherited fields `_shape` and `falloffDistance` to that script, you need to extent it from `LevelVolume<TVolume, TManager>` and you can extent `LevelVolume` from `MonoBehaviour` unless you need to change `VolumeBase` or its underlying properties.
For breathable you should keep original field name
```csharp
public bool _isBreathable = true;
```
or (not sure if this would work properly)
```csharp
[SerializeField]
protected bool _isBreathable = true;

public bool isBreathable
{
	get
	{
		return _isBreathable;
	}
	set
	{
		_isBreathable = value;
	}
}
```

**Comment by SDGNelson** [comment]
Yes it should be `_isBreathable`, but it is missing the `[SerializeField]` attribute which I will fix for the next update.

This is not exactly an intended use but funnily enough I do have a comment in the code:
```
// This pre-existing collider check is because modders have been adding the
// volume components in Unity without the _shape property necessarily matching.
```
