### ISSUE TITLE
New cheats allow for cheaters to take other clients directly off the server

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#348]
Recent hacked clients are able to crash the clients of other people on servers. I've been sent (anonymously) the hacks which I dm'd you on discord with. I didn't want to post the link where anyone can download them.

The hackers knocked my server from 48 people down to 14 in minutes. Please try to fix this ASAP. People have reported their game stop responding, a DC from the server, and in some instances they have to verify their game.

After further testing I see that these cheats are in fact working (on some random server w/o causing problems of course) and they don't ban me, but they do not seem to include the crashing feature.

**Comment by khakers** [comment]
I would say leaving those here publicly may not be the best idea

**Comment by SDGNelson** [comment]
(following up on Discord)
