### ISSUE TITLE
Map modification question

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3480]
Hi,
I have edited one of the curated maps, as I wanted to add some features to it. I re uploaded it to workshop. 
The problem is that when players who subscribed to official version try to join the server it tells them that server is running different version of the map. The solution to that problem is to unsubscribe from the original version and subscribe to my version of the map.

I wonder if there is another way to deal with that issue? Can I upload the edited version of the map in a way that wont cause that issue? 

Thank you

**Comment by GazziFX** [comment]
Rename map
