### ISSUE TITLE
[BUG REPORT] Water Reflection Bug

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3481]
If water quality is set to Ultra and any other graphics setting is adjusted, then Unturned tries to enable Skybox Reflections on _all_ water volumes present on a map, regardless of if Skybox Reflections is toggled and the water volume's settings.

Only one volume actually gets the reflections, while other volumes get this milky-white tint that I assume the game uses as a base for planer reflections. I suspect the volume that gets the reflections is chosen chronologically. Below is an example of that.
<img width="738" alt="image" src="https://user-images.githubusercontent.com/47935791/197898387-d4c2093e-0372-4d57-b725-d74399cc1453.png">

Video shows glitch in action.
https://www.youtube.com/watch?v=zzI57bcdMzY

This is unlikely to occur for most players, since I'd wager most players don't play with water quality on Ultra with skybox reflections off. Only encountered this due to testing a shader with skybox reflections enabled/disabled.

**Comment by SDGNelson** [comment]
Thanks for the report. To clarify: the skybox reflection setting is only for the global reflection cubemap, it looks like this issue is with Planar Reflections.
