### ISSUE TITLE
Cannot Connect to my server

### ISSUE THREAD

**Issue by HollaYalla** [SmartlyDressedGames/Unturned-3.x-Community#3484]
Hello, I am wanting to host a few unturned servers and when I direct connect to it, I can connect to the main page of the server but as soon as I hit join I am instantly hit with the **Failed connection to host or steam servers** or something like that and it has been days since I have found this issue and trouble shooting could I get some help please.

**Comment by GazziFX** [comment]
Where you hosting server on your PC, or on dedicated server? Did you add to firewall server port and port + 1. If you hosting on your PC, does your IP allow to handle incoming requests and if you have router you need to forward ports on it too.

**Comment by SDGNelson** [comment]
Sorry I didn't reply at the time! If you still happen to be hosting a server and running into this, (which seems unlikely if you ran into an issue and it was unaddressed for 3 months my bad...), then please feel free to comment and I will re-open.
