### ISSUE TITLE
[Rocket] Command changes?

### ISSUE THREAD

**Issue by Blackwolf7704** [SmartlyDressedGames/Unturned-3.x-Community#3487]
I used the most recent version of the rocket, why was it changed so that admin can only be used with a unique number?

/admin TEST => Invalid parameter
/admin 765611***** => success

**Comment by SmallBerry** [comment]
/admin <name> still works
If player is not on the server you can only admin them by steam64id and not by their name

**Comment by GazziFX** [comment]
> /admin still works If player is not on the server you can only admin them by steam64id and not by their name

LDM cannot admin/unadmin by steamid if player is offline
```csharp
public void Execute(IRocketPlayer caller, string[] command)
{
    if (!R.Settings.Instance.WebPermissions.Enabled)
    {
        UnturnedPlayer player = command.GetUnturnedPlayerParameter(0);
        if (player == null)
        {
            UnturnedChat.Say(caller, U.Translate("command_generic_invalid_parameter"));
            throw new WrongUsageOfCommandException(caller,this);
        }

        if (!player.IsAdmin)
        {
            UnturnedChat.Say(caller, "Successfully admined "+player.CharacterName);
            player.Admin(true);
        }
    }   
}
```
