### ISSUE TITLE
[Modding] Mod works on Singleplayer but doesnt on multi

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3488]
Hi,
I have taken another mod for lockers, edited the IDs, HP and slots and re uploaded it (with creators permission)
When I spawn in the lockers or craft them in single player everything works as it supposed to.
When I upload the mod on the server, I am able to craft the locker and view it in my inventory but I can't equip it. 

**What I tried**
- [x] Delete my mods folder and download the mods upon joining the server 
- [x] Delete servers mods folder and re-download all of them
- [x] Restarted server and my own game multiple times

**Comment by GazziFX** [comment]
Can you send your mod URL or something?

**Comment by educatalan02** [comment]
There are 50% chances that you have 2 mods with the same GUID. Try restarting the GUID and reupload them.
