### ISSUE TITLE
Bake Satellite/Chart Improvements in the Workshop Editor  

### ISSUE THREAD

**Issue by AthenaDev** [SmartlyDressedGames/Unturned-3.x-Community#349]
So, right now Bake Satellite/Chart takes about 6+ hours for everyone. Regardless of RAM, as mentioned in #307. 

A previous, low-priority solution was proposed by Nelson:
"It could be improved if it were rendered across multiple frames in smaller tiles and then stitched together, but that's low priority since it works as-is."

I would argue that it doesn't necessarily work as-is, but perhaps a temporary solution would be at least to not freeze the whole game? A progress bar would be nice; i.e you're still able to work on the map while the Satellite or Chart bakes, and see the progress.

I hope this isn't too much to ask for, as a low priority feature might not be in Unturned for a long time.

**Comment by baranmod** [comment]
"6+ hours for everyone" - really? As it takes less than 10min for me, no matter how detailed and big map is. It doesn't really depends much on RAM. Your CPU probably dying.

**Comment by SDGNelson** [comment]
A progress bar would require implementing the change described, as currently the rendertexture is captured in one frame. Making these changes is unlikely to happen.

**Comment by AthenaDev** [comment]
Surprisingly enough, I tried Bake Satellite once more and it worked within seconds -- chart works too but takes a bit longer. I believe it worked this time because either my tree rendering was on Legacy or (more likely) I filled up the map more. Maybe neither; but it works!
