### ISSUE TITLE
UI is blocking selection in Shift + F6

### ISSUE THREAD

**Issue by MrKanYT** [SmartlyDressedGames/Unturned-3.x-Community#3490]
I have a plugin with UI that can be always displayed. 

Default (closed) state:
![image](https://user-images.githubusercontent.com/45901873/199024823-b268b3f1-f18b-4f87-8bd8-28c8232bdf26.png)

Active (opened) state:
![image](https://user-images.githubusercontent.com/45901873/199025152-6dad4b26-5e23-448b-8f20-b8700b93c6de.png)

When the UI is enabled, i can't select anything with Shift + F6. Yellow rectangle doesn't appear. With hidden UI everything works fine. Is it possible to fix that somehow?

**Comment by SDGNelson** [comment]
If it has mouse focus then the game will give the UI input priority. Clicking outside that UI should release mouse focus.
