### ISSUE TITLE
Bug Report: Trap-type barricades with Damage Tires setting use GameObject's box collider instead of trap box collider

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3491]
Found this when testing a trap that has separate box colliders for the main Prefab & the Trap GameObject. However, a tire won't be damaged if it hits the Trap's box collider, only when it hits the main Prefab's box collider.

**Comment by SDGNelson** [comment]
Currently the wheel only checks for the tire damage component on the hit collider, and that component is added to the root prefab. I am not sure why off the top of my head. Sooner or later I do want to do all the vehicle physics simulation on the server, so it might be possible to move the damage to OnTriggerEnter same as the regular trap damage.
