### ISSUE TITLE
Glitched Vehicle causes ladder bug

### ISSUE THREAD

**Issue by dzonyloker** [SmartlyDressedGames/Unturned-3.x-Community#3493]
I wasted several hours to find this
https://medal.tv/games/unturned/clips/GVCmrYJo8yAx3/d1337zmfkBLU?invite=cr-MSxjd0UsMzM2NDM1MDYs

**Comment by SDGNelson** [comment]
It might be that modded vehicle has a giant collider covering the entire level. (I have seen some modders doing that unfortunately.) How did it end up far away from the level there and how did you know it was there? If you spawn that vehicle back in the same ladder issue happens?

**Comment by dzonyloker** [comment]
I use this car on my roleplay server and the whole PD group has been using it every day for 3 months. 

I found this vehicle because first I was destroying vehicles in a small area in each city separately because I didn't know which car was the problem.

This broken vehicle did not provoke a prolblem only with ladders but also with other things. All vehicles on the map had a problem with boxcollider. I was using a plugin that allows you to hide vehicles in a virtual storage garage, and because of this problem players couldn't use it, because when player looked at a vehicle and wanted to hide it with command /gadd, character didn't detect anything in sight.

**Comment by dzonyloker** [comment]
This time the error occurred when player "grab" car by skycrane heli
https://medal.tv/games/unturned/clips/IWvfigQ_ztgs3/pGTOzE88AjUQ?theater=true
