### ISSUE TITLE
Bug Report: All bullet casings disappear when weapon is unequipped

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3496]
A small issue, but noticeable when done. My guess is that the effect is within the gun, not too sure if that's the case though.

**Comment by SDGNelson** [comment]
Sort of - currently the game returns the effect to the pool when the gun is dequipped. Maybe a timer could be added that waits until all particles have despawned before returning to the pool.
