### ISSUE TITLE
Feature Request: Give The Binary script server-sided options

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3499]
A bummer that it hasn't gotten those options. The script is ideal for setting up random chances what I was going for involving box colliders, but the script currently works client-sided only. If possible, please do add that next update.

**Comment by SDGNelson** [comment]
For the Binary Random component? If AuthorityOnly is enabled then it will only trigger on the server or singleplayer, but if AuthorityOnly is disabled it triggers on clients as well.

**Comment by OneManOperative** [comment]
Ah ok. Apologies for the complaint. It was an abrupt report when I found my issue. Mb
