### ISSUE TITLE
Bug Report: object heights change slightly upon restarting editor

### ISSUE THREAD

**Issue by JD550** [SmartlyDressedGames/Unturned-3.x-Community#3501]
when placing roads down and using CTRL+B/CTRL+N and lining everything up perfectly. after restarting the editor, all of the road's heights change (including sidewalks).

**Comment by SDGNelson** [comment]
Sorry about this! I think there may be some unnecessary jitter introduced because all transforms were using a world to pivot space then pivot to world space matrix transformation. The next update will only use this matrix transformation for scaling.

**Comment by iXpertgaming** [comment]
im having this problem aswell may I have some help fixing it please!
