### ISSUE TITLE
Server missing unknown asset? (should never happen)

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3502]
Players on my server have randomly been getting kicked with the following message.
It started after the 3.22.17.0 update (after which no updates were made to the mods/plugin)

`Server missing unknown asset? (should never happen) Id: 07006401000295d60164000a0300d695`

Logs claim it's a barricade, we don't use any assets with that GUID.
Looking at the code for when this message is sent I really can't see any reason for it to send but it happens a lot to players.

As a temporary fix I just tried transpiling ServerMessageHandler_ValidateAssets.ReadMessage to remove the kick, waiting to see if it works now, but I was curious as to your thoughts on what could cause this message and how I could properly fix it. The server uses one plugin I co-wrote so I'd be open to suggestions.

My first thought was my BarricadeManager.SendRegion patch but I've triple checked it uses the right structure so not too sure what could be causing it.

I included a client log from someone, the kick is at line 2281.

Side note, it's not always the same ID, usually one of 3 but they seem to follow a similar pattern and don't look like normal randomly generated GUIDs (they all include the data 640100), almost seems like data isn't being sent in the right order or is reading a different message or something:
03006401000865a6016400060800c095
07006401000295d60164000a0300d695
d1b2d7308e34303064010010e2876d00
[Client_2.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9945219/Client_2.log)

**Comment by SDGNelson** [comment]
If you are patching SendRegion that is almost definitely why. This error is intended to catch cases of GUID corrupted between client<->server. What are you patching in SendRegion?

**Comment by DanielWillett** [comment]
It's to adjust how clients see signs per player, I've made sure the structure is correct so that it's read correctly, it's mostly copy-pasted from decompiled code then I just added a check to change the state of signs based on the player.

Patch:
https://github.com/UncreatedStaff/UncreatedWarfare/blob/45d11d8eaf9f4a66ffd3f51dac98153e8841198c/UncreatedWarfare/Patches/RegionsPatches.cs#L143

**Comment by SDGNelson** [comment]
I would recommend disabling the plugin to double-check that it is causing the missing asset kick.
