### ISSUE TITLE
Map Editor failing to save assets correctly.

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3505]
I didn't really know how to format this well. Recently my editor (and from more people too I assume) has been wonky & annoying in saving assets that NEED to be alligned. 
![image](https://user-images.githubusercontent.com/101991669/200582932-e2243ecf-03e7-46f2-befd-b654e0baa942.png)
I have placed this road on the EXACT same height using Ctrl B & Ctrl N. After saving & going into singleplayer. It got missalligned. This happend to **all** my road pieces. Including my bridges... 

As a person with OCD its quite annoying that this keeps on happening. I can't fix it cuz it'll just miss-alling itself after saving & quitting the map editor...

**Comment by UsernameIsUnavailible** [comment]
![image](https://user-images.githubusercontent.com/101991669/200621980-c093d3af-3136-4897-85af-f47a7242a761.png)
After booting up this beta, Weird "red boxes" appeared in my map. Is this an "error"?

**Comment by SDGNelson** [comment]
It is only compatible with servers running the preview version, so my suggestion would be to try on the preview branch and then go back to the default branch.

Clarifying the map compatibility: there are some changes to map savedata on the preview branch with objects and nodes. These have a higher version number on the preview branch. If you save the map on the preview branch with this higher version number then the default branch does not know how to load the map with a future higher version number. For this reason you should save a copy of the map so that when you go back to the default branch you can continue editing the original map and delete the copy.

**Comment by UsernameIsUnavailible** [comment]
![image](https://user-images.githubusercontent.com/101991669/200623014-9572a4c7-b723-4f15-bfa3-72ec3edb0871.png)
Seems like the gaps are still occuring, Way less & violent then before though

**Comment by UsernameIsUnavailible** [comment]
Yeah even after replacing the entire bridge + ramp it still gets missaligned. I'll try to make it completely new in a couple of hours

**Comment by UsernameIsUnavailible** [comment]
@SDGNelson 
![image](https://user-images.githubusercontent.com/101991669/200835677-e4a5fef9-397a-4981-bd9b-3bc9233c0921.png)
Inside the map editor

![image](https://user-images.githubusercontent.com/101991669/200835726-c80bc124-d37f-47a1-818e-b789d4ddd867.png)
Loading the map up in SP & Re-opening the map in editor. Bridge gets missaligned.

**Comment by UsernameIsUnavailible** [comment]
^^ Does not happen with the other "Modular Bridge Exit #2" From DE steam mod.

**Comment by UsernameIsUnavailible** [comment]
![image](https://user-images.githubusercontent.com/101991669/200839644-088456aa-de12-4c0e-b7b1-efe597bc2b55.png)
Seems like its still happening, Less violent though.

**Comment by SDGNelson** [comment]
Can you think of anything that would be unusual about your map's object setup or size?
Alternatively, I wonder if you could send your map to me at nelson@smartlydressedgames.com and maybe I can replicate it when I use your map? If I can replicate/reproduce it in the editor that would make it a lot easier to fix.

**Comment by UsernameIsUnavailible** [comment]
There shouldn't be anything unusual. I'm editing Washington & revamping all mayor locations for an RP server. I can send you my map but it requires steam mods. I'll make a quick collection so you can easier subscribe to the mods.

**Comment by UsernameIsUnavailible** [comment]
Also seems like the offset isn't only vertical, I just noticed that my bridges are also offset horizonatlly
![image](https://user-images.githubusercontent.com/101991669/201181212-fe6bdcd0-33a2-4351-a9e1-ea644b4cc960.png)

**Comment by SDGNelson** [comment]
Following up: it seemed that most of the objects in the city had some amount of error in their rotation or scale. For example rotated 89.99 degrees or a scale of (1.001, 1, 1). The vanilla maps do not have this, so it must have been an earlier problem with some of the tools - perhaps with the error accumulation while dragging.

In order to eliminate this noise I made some changes so automatically snap scales and rotations that are very near to axis-aligned. For example 1.001 scale is corrected to 1, (and -1.001 to -1), and 89.99 degrees is corrected to 90. Testing on your map I found the gaps in the bridge, fixed them by repositioning the objects with Ctrl+B/N, and after saving/reloading it seems to be back to normal.

Sorry for all the hassle! If you have a moment I would be curious to know whether it seems to be fixed for you in version 3.22.19.103 on the preview branch. My hope is that this scale/rotation fixup will make it easier to snap other objects in the future as well.

**Comment by UsernameIsUnavailible** [comment]
Following up: it seemed that most of the objects in the city had some amount of error in their rotation or scale. For example rotated 89.99 degrees or a scale of (1.001, 1, 1). The vanilla maps do not have this, so it must have been an earlier problem with some of the tools - perhaps with the error accumulation while dragging.
A: Impossible, I made the bridge using Ctrl B, Ctrl V & copy pasting the parts so they were all alligned

I found the gaps in the bridge, fixed them by repositioning the objects with Ctrl+B/N, and after saving/reloading it seems to be back to normal.

A: Alright that sounds cool & a relief my bridges won’t have tiny gaps anymore xd

Sorry for all the hassle! If you have a moment I would be curious to know whether it seems to be fixed for you in   version 3.22.19.103 on the preview branch. My hope is that this scale/rotation fixup will make it easier to snap other objects in the future as well.
A: I’ll try the preview branch tommorow, Its currently around an hour past midnight & I can’t really boot up my Unturned without waking my parents from my cooling fan noices xD
Van: Nelson Sexton
Verzonden: vrijdag 11 november 2022 0:52
Aan: SmartlyDressedGames/Unturned-3.x-Community
CC: Michael; Author
Onderwerp: Re: [SmartlyDressedGames/Unturned-3.x-Community] Map Editor failingto save assets correctly. (Issue #3505)

Following up: it seemed that most of the objects in the city had some amount of error in their rotation or scale. For example rotated 89.99 degrees or a scale of (1.001, 1, 1). The vanilla maps do not have this, so it must have been an earlier problem with some of the tools - perhaps with the error accumulation while dragging.
In order to eliminate this noise I made some changes so automatically snap scales and rotations that are very near to axis-aligned. For example 1.001 scale is corrected to 1, (and -1.001 to -1), and 89.99 degrees is corrected to 90. Testing on your map I found the gaps in the bridge, fixed them by repositioning the objects with Ctrl+B/N, and after saving/reloading it seems to be back to normal.
Sorry for all the hassle! If you have a moment I would be curious to know whether it seems to be fixed for you in version 3.22.19.103 on the preview branch. My hope is that this scale/rotation fixup will make it easier to snap other objects in the future as well.

**Comment by UsernameIsUnavailible** [comment]
Oh crap I didn't know you send the message here & not via my mail lmao

**Comment by UsernameIsUnavailible** [comment]
**Following up: it seemed that most of the objects in the city had some amount of error in their rotation or scale. For example rotated 89.99 degrees or a scale of (1.001, 1, 1). The vanilla maps do not have this, so it must have been an earlier problem with some of the tools - perhaps with the error accumulation while dragging.**
A: Impossible, I remade the bridge multiple times & expanding the parts copy pasting, So they should have been 100% alligned.

Sorry for all the hassle! If you have a moment I would be curious to know whether it seems to be fixed for you in version 3.22.19.103 on the preview branch. My hope is that this scale/rotation fixup will make it easier to snap other objects in the future as well.
A: I'll be checking it out right now

**Comment by UsernameIsUnavailible** [comment]
(also sorry for my "useless" mail I send around 5-ish mins ago xd)

**Comment by UsernameIsUnavailible** [comment]
Seems like everyting stays in its original position after saving & reloading the map editor multiple times!

**Comment by SDGNelson** [comment]
Phew, glad to hear it!
