### ISSUE TITLE
How to submit the data in UI Effect to the server

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3506]
I want the player to click the UI button, and the properties of the gameobject in the UI will be sent to the server, but how to use these methods to get the data stored from client‘s gameobjects.

```C#
        public delegate void EffectButtonClickedHandler(Player player, string buttonName);
        public delegate void EffectTextCommittedHandler(Player player, string buttonName, string text);
```

**Comment by GazziFX** [comment]
```csharp
protected override void Load()
{
    EffectManager.onEffectButtonClicked += OnEffectButtonClicked;
}

protected override void Unload()
{
    EffectManager.onEffectButtonClicked -= OnEffectButtonClicked;
}

private void OnEffectButtonClicked(Player player, string buttonName)
{
    if (buttonName == "MyButton")
    {
        // Do something
    }
}
```

**Comment by makeloffve** [comment]
> ```cs
> protected override void Load()
> {
>     EffectManager.onEffectButtonClicked += OnEffectButtonClicked;
> }
> 
> protected override void Unload()
> {
>     EffectManager.onEffectButtonClicked -= OnEffectButtonClicked;
> }
> 
> private void OnEffectButtonClicked(Player player, string buttonName)
> {
>     if (buttonName == "MyButton")
>     {
>         // Do something
>     }
> }
> ```

> ```cs
> protected override void Load()
> {
>     EffectManager.onEffectButtonClicked += OnEffectButtonClicked;
> }
> 
> protected override void Unload()
> {
>     EffectManager.onEffectButtonClicked -= OnEffectButtonClicked;
> }
> 
> private void OnEffectButtonClicked(Player player, string buttonName)
> {
>     if (buttonName == "MyButton")
>     {
>         // Do something
>     }
> }
> ```
Thanks for your reply! I'm sorry to have failed to make myself clear.
My UI is a form.  I want to pass the client's input (include props of gameobjects) in the UI form to the server? It seems that the ` (Player player, string buttonName)` 2 parameters can't do it .

**Comment by makeloffve** [comment]
> ```cs
> protected override void Load()
> {
>     EffectManager.onEffectButtonClicked += OnEffectButtonClicked;
> }
> 
> protected override void Unload()
> {
>     EffectManager.onEffectButtonClicked -= OnEffectButtonClicked;
> }
> 
> private void OnEffectButtonClicked(Player player, string buttonName)
> {
>     if (buttonName == "MyButton")
>     {
>         // Do something
>     }
> }
> ```

Thanks for your reply! I'm sorry to have failed to make myself clear.
My UI is a form.  I want to pass the client's input (include props of gameobjects) in the UI form to the server.It seems that the ` (Player player, string buttonName)` 2 parameters can't do it .

**Comment by makeloffve** [comment]
`public static Transform createUIEffect(ushort id, short key)`
`public static void hookButtonsInUIEffect(Transform effect);`
`public static void hookInputFieldsInUIEffect(Transform effect);`
`public delegate void EffectTextCommittedHandler(Player player, string buttonName, string text);`

Are there any **relations** between these methods?
