### ISSUE TITLE
Unturned fails to load/crashes when trying to launch in [preview] "beta" mode.

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3507]
![image](https://user-images.githubusercontent.com/101991669/201094378-a0e50ddb-6999-40f7-a9ac-cd961effda23.png)
Translated ->
![image](https://user-images.githubusercontent.com/101991669/201094531-bc4e948b-90ea-48ad-a2d4-d74e2eadafc3.png)

**Comment by SDGNelson** [comment]
Sorry about this - I was experimenting with something.
