### ISSUE TITLE
How to protect yourself from DDoS attacks?

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3509]
One not very good person for our project got wound up, who can drop the server with his ddos. How to protect yourself from this?

```
[2022-11-10 20:57:58] Disconnecting: PlayerID: 76561198404592957 Name: Noname Character: Noname
[2022-11-10 20:57:58] BattlEye Print: Player Noname disconnected
[2022-11-10 20:57:58] Removing player steamid:76561198393621204 due to transport failure (ClosedByPeer Reason: 1000 Message: "Application closed connection")
```

And so threw out all the players of the server.

**Comment by GazziFX** [comment]
Mostly DDoS protection comes from provider, but in cases when application specific methods come, you should add protection in app. Whats actually happened when players got disconnected, was it network or CPU overload?

**Comment by SDGNelson** [comment]
That message (ClosedByPeer Reason 1000) fortunately just means the connection was closed before the Steam authentication ticket closed event was received by the server. It has been clarified a bit in the next update with a separate message for when the client intentionally disconnects. Do you have other reason to believe the server is being attacked?
