### ISSUE TITLE
Console Freeze randomly

### ISSUE THREAD

**Issue by Kast2** [SmartlyDressedGames/Unturned-3.x-Community#351]
Good morning, for some days my server suffers from a serious enough problem that my developers and I can not solve: the console of the server freeze without any apparent reason, I leave a link to a video to make you understand:
https://www.youtube.com/watch?v=c2DsaxHlxKU
We tried to do everything, changing vps, look into all the log files and more but we can not understand the cause. If anyone knows something, let me know 

(Forgive my English)

**Comment by 2KastOnBag2** [comment]
https://www.youtube.com/watch?v=tFA3pQFTGn4
This is the second video I recorded yesterday while we were in-game during the "freeze" moment.
The server was fixed for 20-40ms, VoIP worked perfectly, while an action (like getting out of a car, opening doors or pulling out weapons was impossible).

Please don't look at the sockets written in the console, that's a problem that we solved a moment later with our hosting. However, this is what happens during the "freeze" in-game moment.

**Comment by N1GHTPATROL** [comment]
Put your Windows power plan on high performance.

**Comment by 2KastOnBag2** [comment]
@N1GHTPATROL Thank you for your advice, I have just made this change now.
Anyway today we did other tests, for 4 hours in a row went smoothly and still is going without problems. So the last option we have is that someone is using hacks to crash the client server. I've read around that there is this "problem" in the BE system and we suspect two of our users can do this.

Is this possible?

**Comment by N1GHTPATROL** [comment]
Before the last update people could crash other players' games on a server, but he may have fixed that in the last update. It was also possible a few months ago to directly crash a server using askVehicle packets. Since then he did fix that but I wouldn't be suprised if there were a few other hidden issues. I would be suprised if people did that on your server since people usually let you know and threaten you if they were doing that. There'd be no return for them if it was a hacker.

**Comment by 2KastOnBag2** [comment]
I attach the following problem to these two people for the simple fact that whenever one of them is connected to our server for strange reasons we always go offline. Knowing them and having already received other threats from them, I know that they would be able to do so.
However, I'll wait for an answer from Nelson, you never know, every tip is accepted.

**Comment by SDGNelson** [comment]
Sorry for the delay while I was away. I've received some information about one potential cause of this, and should be increasing security in that area for tomorrow's update.
