### ISSUE TITLE
Devkit Editor Kill Barrier Volume

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#3511]
Hey Nelson, 
Since the devkit editor was removed, is there currently not a way to add a kill barrier volume to custom maps? As that's what we use to stop players from glitching under the map since some of our buildables are out of bounds.

**Comment by SDGNelson** [comment]
It is possible! These were moved to the Editor > Level > Volumes tab.
