### ISSUE TITLE
lost connection

### ISSUE THREAD

**Issue by ShamHyper** [SmartlyDressedGames/Unturned-3.x-Community#3512]
Why Nelson killed my airdrop plugin? Anyone can't connect to the server

```
NullReferenceException: Object reference not set to an instance of an object
at US.AirDrop.Plugin.OnLevelLoaded (System.Int32 level) [0x0002c] in <f0c3b0704d80453db43d2b423264da98>:0
at (wrapper delegate-invoke) <Module>.invoke_void_int(int)
at SDG.Unturned.Level+<init>d__133.MoveNext () [0x005b7] in <022d55f7e31340c0a0c1910cb2f4009a>:0
at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <b29daebb1e374c1a899ae688ce447840>:0
```

**Comment by GazziFX** [comment]
Just fix it? If you can't send plugin

**Comment by ShamHyper** [comment]
> Just fix it? If you can't send plugin
[ArumAirdrop.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9994370/ArumAirdrop.zip)

**Comment by ShamHyper** [comment]
> Just fix it? If you can't send plugin

I tried to fix it, but I only got more errors

**Comment by GazziFX** [comment]
Seems this plugin use old assets system
```csharp
spawn.GetType().GetProperty("areTablesDirty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).SetValue(spawn, true);
Assets.add(spawn, true);
```

**Comment by GazziFX** [comment]
Error occured because AirdropNode type changed to AirdropDevkitNode which also requires GameObject.
[ArumAirdrop.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9994492/ArumAirdrop.zip)

**Comment by ShamHyper** [comment]
> Error occured because AirdropNode type changed to AirdropDevkitNode which also requires GameObject. [ArumAirdrop.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/9994492/ArumAirdrop.zip)

Thx man
