### ISSUE TITLE
"Server did not reply to workshop details request" after Update

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3514]
I'm getting this error in the client.log after the latest update. 
This is happening on 4 different servers, 3 of which don't have any workshop mods - 1 of which has many mods, and there's also a 5th server which has mods which isn't having this issue. 

```
[2022-11-12 17:16:18] Rusty Moose RP〖 Casual Roleplay 〗 host ban flags: None
[2022-11-12 17:16:19] Initializing ClientTransport_SteamNetworkingSockets
[2022-11-12 17:16:19] Client Steam Networking available
[2022-11-12 17:16:19] Client connecting to 66.23.205.214:27016
[2022-11-12 17:16:19] Client connection with 1069786527 ready
[2022-11-12 17:16:49] Disconnecting: Server did not reply to workshop details request (30.00094s elapsed)
[2022-11-12 17:16:49] Client disconnect from 1069786527 result: True
[2022-11-12 17:16:49] Returning to main menu
[2022-11-12 17:16:49] Disconnected
```

Any ideas what's causing this, and how to fix?

**Comment by SDGNelson** [comment]
Based on some other reports it sounds like a potential cause is a plugin throwing an exception during startup. Could you attach the Server_ (id) .log file from U3DS/Logs please? I will take a look.

**Comment by AdamDN** [comment]
Yep you're right. The workshop error in client.log had me looking in the complete wrong place.

> [2022-11-12 11:11:20] ArgumentException: Object of type 'System.Collections.Generic.List`1[SDG.Unturned.AirdropNode]' cannot be converted to type 'System.Collections.Generic.List`1[SDG.Unturned.AirdropDevkitNode]'.
> [2022-11-12 11:11:20] System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> RestoreMonarchy.AirdropManager.AirdropManagerPlugin.OnLevelLoaded (System.Int32 level) (at <033522da75ad49cd8094c0e4a7f0edad>:0)
> SDG.Unturned.Level+<init>d__133.MoveNext () (at <107dc1e50f9d49fc9f83b64098eed852>:0)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <966ecbc21bec4138a5192b5e1b2dd41f>:0)
> [2022-11-12 11:11:21] Long delay between Updates: 2.226154s

Looks like it's this plugin causing the issue: https://github.com/RestoreMonarchyPlugins/AirdropManager .
It's already been patched and seems good now.

Thanks again for the help :) Now it's just the issue in #3510 keeping 1 server offline.
