### ISSUE TITLE
[Request] ProjectWorldPositionToMap / DeprojectMapToWorld

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3515]
Would you be able to make `PlayerDashboardInformationUI.ProjectWorldPositionToMap` and `PlayerDashboardInformationUI.DeprojectMapToWorld` public if possible? Would like to use them for a map grid. Thanks

**Comment by SDGNelson** [comment]
Could you elaborate on what you mean by map grid? Those methods might not be particularly useful because they are specific to the user interface. i.e., you would want something different for pixel projection or world space projection.

**Comment by DanielWillett** [comment]
For example to lay a grid over the map image then be able to calculate which grid space they're in (like chess grids). Currently have a method to do it with square maps but I'm not sure how that will translate to the new map system with non-square maps.

**Comment by SDGNelson** [comment]
You can use InverseTransformPoint to get the world position relative to the box:

`Vector3 localPosition = cartographyVolume.transform.InverseTransformPoint(worldPosition);`

This would be -0.5 to +0.5, so then you can multiply by `cartographyVolume.GetBoxSize()` for the world-space distance relative to the box.
