### ISSUE TITLE
Bug report: Location map names disappeared

### ISSUE THREAD

**Issue by GeeJotaa** [SmartlyDressedGames/Unturned-3.x-Community#3517]
With the new update the place names on my map (created on 2016) disappeared. Although the respective editor button does work, the old nodes do not appear in the map editor, but still working for teleport command.

**Comment by SDGNelson** [comment]
There should be a red wireframe box representing the named locations. You can click named location in the upper right and box select to help find them. Are they not visible?

**Comment by GeeJotaa** [comment]
I tried putting new named locations in the editor. At the time of entering the server with the map, only with the command "/tp" it takes you to the legacy locations, and only with "/teleport" to the new ones. But in the editor only the new ones are visible and selectable. I'll stop using /tp, maybe it's rocket failure or something.
illustrative video:
[https://youtu.be/SjgJrqrXsgE](url)

**Comment by SDGNelson** [comment]
Ah: the reason probably is the plugin TP command looking for the old node type which was kept for backwards compatibility, but the existing and newer location nodes use a different type. There was a helper method for finding location by name but TP was probably not using that.
