### ISSUE TITLE
AirDrop on a offical map

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3518]
I need to replace the airdrop on my server, but I use an official map(pci). To install my Airdrop, I need to change the configuration of the map. Is there a way to install your airdrop on the server without editing the official map?

**Comment by SDGNelson** [comment]
There are a few options:
- Custom variant of the map
- Overriding the airdrop spawn table with custom ones
- Making a plugin to completely replace the map's airdrops

**Comment by JorelDecker** [comment]
> 



> There are a few options:
> 
> * Custom variant of the map
> * Overriding the airdrop spawn table with custom ones
> * Making a plugin to completely replace the map's airdrops

That is, it is possible to change the Airdrop model without editing the map, only through the plugin?

**Comment by GazziFX** [comment]
There's no way to change airdrop model with plugins and you can't have several airdrop models on the same map
