### ISSUE TITLE
UI tokens bug

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#3519]
I've created UI effect with TMP Text object that contains {0} token and a button. In plugin I'm using EffectManager.sendUIEffect method with arg0 parameter to display some text right away but it's not working. With button removed it starts to work again. Setting text by object name with sendUIEffectText method is working fine too. Is this intended or am I doing something wrong?

Oh and a regular UI Text is doing fine with any buttons

**Comment by SDGNelson** [comment]
Does the button have a regular Text component? The game only looks for TextMeshPro components if the Unity built-in Text component is not used.

**Comment by Ankumo** [comment]
I've tried both TMP and a regular one. No luck :(

p.s. Reading my first sentence again got me a thought that it may be misleading. Just to clarify: the button is **_not_** inside the Text object. It's just an effect with 2 objects on canvas: TMP Text and a button.

**Comment by Ankumo** [comment]
Oh no, wait. Tested it again and it definitely works if there's no regular Text objects. Seems that I've just took built-in button from legacy effect on my scene in previous testings. TYVM for clarifying and sorry for bothering
