### ISSUE TITLE
Doorways still broken

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#352]
Hi Nelson, please consider fixing the doorways that can be shot right through the side. In particular, I know this applies to a vault door on a metal doorway, you can shoot people and zombies right through the end. It is causing lots of drama and it's hard to enforce a rule against it on my server. Thanks!

**Comment by SDGNelson** [comment]
This should have been fixed a while ago, but I'll see if there's something different about the vault doors.

**Comment by SDGNelson** [comment]
Might be fixed now? We'll see...
