### ISSUE TITLE
Spawnpoints after update bug

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3520]
NPCs do not teleport you anymore to the spawnpoint after the update. Response simply doesn't do anything, doesn't teleport you.
```
Response_4_Rewards 1
Response_4_Reward_0_Type Player_Spawnpoint
Response_4_Reward_0_ID Parkour5
```

**Comment by SDGNelson** [comment]
I think you want Type Teleport, the Player_Spawnpoint reward sets your spawnpoint for respawn.

**Comment by LocoCZ** [comment]
Yes, well, my fault, however it seems like I have been using Player_Spawnpoint for the whole entire time and worked as a teleporter for some reason (I've got it inside of majority of my old files).
