### ISSUE TITLE
3.22.19.0 - Some players are not able to join server (Stuck in Queue Position 1)

### ISSUE THREAD

**Issue by NathanKarnezis** [SmartlyDressedGames/Unturned-3.x-Community#3522]
The players are stuck in queue position one and cannot connect to the server. Console does not receive a request that the player or player's ID is being registered connecting to the server. I have tried everything from updating mods, limiting Plugins, and changing hosting region, even increasing the allowed packets. I am open to troubleshooting techniques but I used this link as reference and have found nothing.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3442

**Comment by GazziFX** [comment]
Did you checked client logs?

**Comment by NathanKarnezis** [comment]
[Server_unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10026889/Server_unturned.log)
![76561198112978507Aus](https://user-images.githubusercontent.com/21159520/202330690-4992b4ca-6823-47c8-a4ac-bf87f4afe955.png)

Player SteamID: 76561198112978507

**Comment by SDGNelson** [comment]
Sorry that I didn't reply at the time. That error is from the old Steam Networking. If you have -NetTransport= in your server's launch arguments it should probably be removed.
