### ISSUE TITLE
Client and server are both missing unknown asset!

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#3524]
Me and the players of my server are kicked in certain places on the map for the reason:
Client and server are both missing unknown asset! ID: b6f4f2130b0640caa24602752c870ded
This probably means either an invalid ID was sent by the server,
the ID got corrupted for example by plugins modifying network traffic,
or a required level asset like materials/foliage is missing.

At this moment in the console it says: Kicking steamid: 76561198195756979 for invalid file integrity request guid: b6f4f2130b0640caa24602752c870ded

When I try to connect again, it kicks and writes the same error.
Noticed after update 3.22.19.0
[Server_survivalhost.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10024069/Server_survivalhost.log)
Look at the log line 27993 and 28027

What to do? A large number of plugins are installed on the server and I am not a programmer

**Comment by SDGNelson** [comment]
Sorry about this! It is probably related to this change which will get easier to fix after the .3 patch today: https://gist.github.com/SDGNelson/41cfd0f4b7bbf217593ce220e92ef654

**Comment by MrGoBi** [comment]
Yes, I managed to fix the problem. Thank you!
