### ISSUE TITLE
All servers unjoinable ;-;

### ISSUE THREAD

**Issue by KodakDolph** [SmartlyDressedGames/Unturned-3.x-Community#3525]
Players able to join for a sec or two before getting kicked for: 

Server asset bundle hash out of date for "Metal Doorway"! (File: "Doorway_Metal" ID: c1db19365f03442088c67a20226b272d)
This probably means the mod creator should re-export the "core" asset bundle.
Client and server agree this asset is from Vanilla Built-in Assets.

or perhaps the asset is different map-to-map. but that is what happened when someone tried to join Russia. 

Looks like it's affecting all Unturned servers.

**Comment by KodakDolph** [comment]
![image](https://user-images.githubusercontent.com/105953666/202284872-5e70fdf5-7a18-4f66-b8eb-f438afc90a96.png)

![image](https://user-images.githubusercontent.com/105953666/202284894-b81c241d-9794-41da-8ce6-d8be01e492ad.png)

**Comment by joeymisfit** [comment]
Having the same issues on another server not linked to Kodak's, throws the error for nearly everything vanilla i.e. (tanktraps, pine floors, metal triangular roof's, etc). Literally nobody can join the server.

**Comment by GazziFX** [comment]
```
Server asset bundle hash out of date for "PEI Grass 00"! (File: "PEI_Grass_00_Material" ID: 3d7717c2bc074401853b2fdacd9db1ba)
This probably means the mod creator should re-export the "core" asset bundle.
Client and server agree this asset is from Vanilla Built-in Assets.
```

**Comment by gegtor** [comment]
Can confirm all of my 24 servers are dead too

**Comment by gegtor** [comment]
@SDGNelson

**Comment by gegtor** [comment]
apparently the update also specifically broke Linux servers

I can join from macOS but my players with Windows PCs can't

**Comment by gegtor** [comment]
<img width="964" alt="Screenshot 2022-11-16 at 22 24 16" src="https://user-images.githubusercontent.com/10978723/202297536-e41410bf-b88b-43f5-a46f-c581df144830.png">

**Comment by surv0013** [comment]
> <img alt="Screenshot 2022-11-16 at 22 24 16" width="964" src="https://user-images.githubusercontent.com/10978723/202297536-e41410bf-b88b-43f5-a46f-c581df144830.png">

Yes it is.

**Comment by KodakDolph** [comment]
> <img alt="Screenshot 2022-11-16 at 22 24 16" width="964" src="https://user-images.githubusercontent.com/10978723/202297536-e41410bf-b88b-43f5-a46f-c581df144830.png">

Confirmed to have worked.

**Comment by SDGNelson** [comment]
Sorry about this and for the delay on the fix. It should have been quick, but something is going wrong when trying to update the dedicated server - according to steamcmd logs http 404 error for some dedicated server manifest. Tried a few things and still trying a few things but will roll back if the .4 patch is refusing to upload.

As for the actual issue: when I was fixing something else I thoughtlessly changed `getHashFilePath`.

Sigh. What a mess this update has been. No update for at least a few weeks after all this.

**Comment by SDGNelson** [comment]
Actually just going to revert now 😩

**Comment by GazziFX** [comment]
`Enable_Update_Shutdown` doesnt work in opposite direction 😐

**Comment by SDGNelson** [comment]
The patch has been re-released now. Hopefully stable for the next several weeks.
