### ISSUE TITLE
k_EResultFail

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3526]
If I start a fresh server and add mods to the WorkshopDownloadConfig.Json then everything works. If I go to 
Workshop > Steam > Content > 304930 and delete all the mods, then start up the server so it will re-download them, it wont work and instead I will get this error.
```
Download workshop item 2888080297 failed, result: k_EResultFail
Downloading workshop item: 1268199545
Download workshop item 1268199545 failed, result: k_EResultFail
```

I have tried suggestion from https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2052
But it didnt work. Any suggestions ?

**Comment by SmallBerry** [comment]
@SDGNelson 
**FIXED**
I run servers on linux and it turns out that to solve that issue instead of deleting the `304930` folder, one needs to delete a whole `Workshop` folder, else the error will persist.

I will keep it open till Nelson will check it out. I assume its a result of some bug introduced with recent update

**Comment by SDGNelson** [comment]
That failure error is within Steam, this is not a bug with the game - it sounds like you got it figured out though.

**Comment by r9Void** [comment]
kakapop
