### ISSUE TITLE
Crashing players bug still exists

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#353]
Hello Nelson, the bug involving players crashing other players is out of control, and has been for the past two weeks. Players are able to join my server and crash whoever they like, and I am disappointed to see this bug is still existent this late into the game's development. Please contact me if you would like more information. Thanks

**Comment by Trojaner25** [comment]
Please attach output_log.txt of a player who has crashed

**Comment by 2KastOnBag2** [comment]
Rather I think there is a problem in the port 27015 in general. In fact, attacking it with a heavy stresser you are able to crash the client server.

**Comment by N1GHTPATROL** [comment]
Already checked many times, but I'll get back to you @Trojaner25 . I don't think it's a DDOS because they're taking down each player with ease, making their game not respond. A booter generally cannot make programs not respond.

**Comment by Kast2** [comment]
@N1GHTPATROL I still know two people who can do this. So the bug is there.

**Comment by N1GHTPATROL** [comment]
I can now confirm that absolutely nothing happens in the logs when a cheater crashes another client. My logs attached:
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2164457/Client.log)

**Comment by Trojaner25** [comment]
Is this really the output_log.txt in /Unturned/Unturned_Data?

**Comment by silentshotghost** [comment]
ya this player crashed me dude

**Comment by niggaman42069** [comment]
just change your port to 27016 problem solved

**Comment by Kast2** [comment]
The problem would continue to exist, even if the port were changed.

**Comment by niggaman42069** [comment]
wrong because only port 27015 is affected lol idiot

**Comment by silentshotghost** [comment]
thanks niggaman42069 you fixed it for me

**Comment by Trojaner25** [comment]
Fun fact:
@silentshotghost is a guy distributing Unturned hacks:
https://www.youtube.com/watch?v=aIGyZAvRQAQ
https://www.youtube.com/watch?v=9-jEUxIM5Aw
https://www.youtube.com/watch?v=QcTMTBEcWvc

@niggaman42069 Is obviously a troll and will be reported to GitHub.

**Comment by Coopyy** [comment]
hackersworth

**Comment by silentshotghost** [comment]
https://www.youtube.com/watch?v=neAEOdp8igU

**Comment by zoomy500** [comment]
i miss manoman why did he have to go :(

**Comment by absolutenothing** [comment]
lol, I've never fucking played that mape before @N1GHTPATROL  LOLOLOLOL

**Comment by Kast2** [comment]
@SDGNelson This type of problem is getting worse. In the Italian community it is impossible to open a server that through some "glitches" closes the access to the server making it blocked/freezing.

**Comment by zoomy500** [comment]
buddy i cut you a share of my profits if you get the italian mob to help me with an issue i am having

**Comment by zoomy500** [comment]
i know you have close ties to to the family business

**Comment by Kast2** [comment]
@zoomy500 I have no contact with these people.

**Comment by zoomy500** [comment]
lies, your business is a front for their operations

**Comment by SDGNelson** [comment]
Sorry for the delay while I was away. I've received some information about one potential cause of this, and should be increasing security in that area for tomorrow's update.
