### ISSUE TITLE
This server is running a map you don’t have

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3532]
I am managing an Unturned server with a few friends, and we are trying to prepare it for launch. I recently maked a custom map and uploading to the Steam Workshop for the server, and my friends can join it perfectly fine. We all have the same mods, but for some reason I keep getting this error: **“This server is running a map you don’t have.”** I’m very confused. I have deleted all of my mods, uninstalled Unturned, redownloaded the mods, still doesn’t work. I originally downloaded my map through the Steam Workshop and I got the error, so I deleted it and downloaded it through connecting to the server…to no avail it doesn’t work. 

[my map mod workshop url on steamcommunity ](https://steamcommunity.com/sharedfiles/filedetails/?id=2891514820)

Can someone help me out?

**Comment by MoltonMontro** [comment]
You've probably downloaded multiple versions of your map. You likely subscribed to your map on the Steam Workshop, while also having a local version of your map (i.e., the version you've been editing) as well. Try moving the local version out of your game folders, and then playing on the map (while subscribed to your map on the Steam Workshop)?

**Comment by makeloffve** [comment]
> 

Hi, here is my process of making and uploading maps:

1. After editing the map, I will copy the map folder under 'unturned/Maps' to the empty folder named map on the desktop.
2. The copied folder is renamed as war3.
3. Put my Level.png in the war3 folder.
4. On the submit page of the workshop, use the path of the map folder to submit mod.
5. I didn't subscribe to my mod.

What does the map version check? Map folder name or a file in the map folder? need more detail
If only check the folder name, I have modified the folder name of the map. The folder name of the map edited under the game maps file is different from the folder name of the workshop
