### ISSUE TITLE
Asset V2 Vehicles

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#3534]
This is a random thought I had today:

As of right now vehicles require different prefabs and multiple .dats for each different, minor variation of itself, and setting them up is a bit annoying.

In theory, creating a Vehicle Asset V2 system could save up space by making it use a similar system to object's material palettes, by making it randomly choose between a list instead of having multiple different prefabs/dats. I'm not sure if that would mean a lower file size (I hope so!) but it would definitely be convenient.

I hope this can count as a "sketch" of what I imagined;

![image](https://user-images.githubusercontent.com/59755846/203228565-9b0c798a-696f-4de7-9326-c162d57a911a.png)

and then the vehicle's V1 could just have a line like `VehicleAsset  6fe40e04e45f4428a43325427d760a44` to reference it.

**Pros:**

- Will be more convenient to edit one .asset instead of multiple .dats
- Can be shared by multiple different cars with the same materials 
- Only one Asset V1 .dat and folder needed.

**Cons:**

- Doesn't use old IDs, which isn't convenient when setting spawn tables or using the /vehicle command
- Will probably cause problems with Localization.dats, as names such as "Red Hatchback" will probably need to be written in-game through code, alternatively it would just be called "Hatchback".

I'm not a programmer so I don't know if I'm missing any potential problems with this system, so apologies if I missed something.

**Comment by Jdance-Media** [comment]
In my opinion, it would be better to just allow vehicles to use material palettes and then add an additional line allowing the modder to pick the material index. Would still require multiple .dat files, but would still make things easier in the long run without having to redo so much code.
