### ISSUE TITLE
Feature Request: Remove Water from Vehicle

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#3535]
Hey Nelson,  is it possible to make an air-pocket for the vehicle so the player is able to traverse in the vehicle properly as well as stay alive when the vehicle is underwater?

**Comment by GazziFX** [comment]
If its not patched yet you can attach OxygenGenerator script and often call updatedWired iirc

**Comment by SMDIndomitable** [comment]
Thank you for the reply. Is that going to fix the water in the vehicle or just the player oxygen? Ultimately, player should be able to walk in the vehicle when the vehicle is fully submerge in the water.

**Comment by SMDIndomitable** [comment]
Thanks man really appreciate that answer, but I am asking for water to be remove from vehicle when is submerged in water

**Comment by Gamingtoday093** [comment]
You can add a DepthMask gameobject to prevent water from being rendered. Isnt perfect tho since youll still experience the audio difference from being underwater

**Comment by Gamingtoday093** [comment]
For Oxygen you can use the new Oxygen Volumes, simply attach a OxygenVolume script. Here I use this one and it works perfectly!
```cs
using UnityEngine;

namespace SDG.Unturned
{
    // The New Volumes use the Scale of the GameObject as the Size for the Volume, No Colliders Required
    // This Volume Script should be attached to an Empty GameObject with Tag and Layer :: Trap
    // To Visualize the Size of the Volume Temporarily Attach either a BoxCollider or a SphereCollider. Making sure that the Collider Component uses the default Radius ( 0.5 ) or Size ( 1 1 1 )
    public class OxygenVolume : MonoBehaviour
    {
        public bool isBreathable
        {
            get
            {
                return this._isBreathable;
            }
            set
            {
                if (!base.enabled)
                {
                    this._isBreathable = value;
                    return;
                }
                this._isBreathable = value;
            }
        }

        [SerializeField]
        private bool _isBreathable = true;

        public ELevelVolumeShape Shape;

        public float falloffDistance;
    }
}
```
Save this as a new script file in unity and name it `OxygenVolume`

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
