### ISSUE TITLE
can't spawn volume on map editor 

### ISSUE THREAD

**Issue by ChouroBoros** [SmartlyDressedGames/Unturned-3.x-Community#3536]
hello, i can't spawn volume on map editor but i can do all other thing like copy paste wen they already existe on the map, make them smaleur or biger change the Shape ect...

**Comment by SDGNelson** [comment]
Do you have IMGUI enabled? This would be the -Glazier=IMGUI option in your launch options. There was a bug with spawning volumes/nodes with IMGUI that should be fixed in the next update.
