### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3539]
I made a set of custom animations for my gun, and there's a problem with it: Sometimes when you aim, the sight shifts off the screen center for some reason. Usually re-equipping the gun helps, and this whole issue appears randomly. What could be causing it? Could it be something with my animation or is it some in-game glitch? Also one weird thing to point out is that deviation angle is always different.
![изображение](https://user-images.githubusercontent.com/59206749/204114061-d42e1d0f-fbda-4b99-95c7-9b028fd2d808.png)
![изображение](https://user-images.githubusercontent.com/59206749/204114066-9474f8ee-402a-400d-9326-cfc18954eabf.png)
![изображение](https://user-images.githubusercontent.com/59206749/204114071-68ad4159-4141-4dcd-a2ee-dfe841f1649f.png)

**Comment by prank0011** [comment]
After the right action, you must adjust the "right _ hook" so that the gun is directly in front, because aiming only transfers the position of the lens to the sight, not including the angle.
![image](https://user-images.githubusercontent.com/68633558/204144651-789b55f9-3384-43d3-aaab-86bd44db7bad.png)

**Comment by DerpyHoowes** [comment]
Well the Right_Hook is angled properly, I even used rotation constraint copying rotation of an empty object in the scene to generate keyframes. So this shouldn't be the case. Also if it was angled wrong, why would this problem appear randomly? Because sometimes its angled properly, and sometimes its not.

**Comment by SDGNelson** [comment]
Maybe the end of the aim animation is off by one frame? The final frame of the aim animation should have the gun parallel with the camera direction.

**Comment by DerpyHoowes** [comment]
Well, I dont know, it seems to be in order to me. The Aim_Start animation is the first in NLA export timeline and lasts from frame 1 to 15. And in the unity it is set accordingly.
![изображение](https://user-images.githubusercontent.com/59206749/204518115-54919563-3609-4b8d-9446-c28408d17bd0.png)
![изображение](https://user-images.githubusercontent.com/59206749/204518562-167f96c6-f544-4ffd-90c3-f7d1a2bac99e.png)
Also for the experiment I applied Aim_Start rotation to preview, put the gun in Right_Hook's children just like it is in the game, skipped to the last frame of animation and dragged it out of the preview hierarchy, and as you can see in its coordinates, and its completely parallel (well maybe there are some numbers after the comma, but I dont think they're big enough to affect it)
![изображение](https://user-images.githubusercontent.com/59206749/204518887-fa371fd6-dfb0-490b-b0c3-a07d6a543c52.png)
And still, if the animation was just wrong, why would it be random in its deviation? People are sending me screenshots where their scopes slide left, right, over and under the screen center. It seems to be completely random.
I first thought that inertia could be causing it, so I turned it off, but the issue is still present.

**Comment by DerpyHoowes** [comment]
My friends also tested out the mod today, and noticed several details about this glitch: The model seems to slide towards the direction you're moving in. So when your character walks around, his arms slide left and right, and if you aim while the arms move to the left, the aim also seems to shift to the left and so for the right side. If you aim while prone hands with gun slide towards the top of the screen. Also movement caused by Shake parameter seems to affect the direction in which the viewmodel shifts.
So it all seems somehow connected to the scripted movements of viewmodel. What mistake could I make to cause such problem? Im actually clueless, since I dont know much of how camera and viewmodel work, but maybe I have some unwanted keyframes or something?

**Comment by DerpyHoowes** [comment]
https://user-images.githubusercontent.com/59206749/204676864-c1cf4758-4103-4071-9922-55bd8f2c9f88.mp4

**Comment by DerpyHoowes** [comment]
https://user-images.githubusercontent.com/59206749/204678336-6f4a0364-8215-4bde-974e-6ce62f6057de.mp4

**Comment by SDGNelson** [comment]
The automatic sight alignment could benefit from some improvement anyway. I will put it on my to-do list.

**Comment by DerpyHoowes** [comment]
prank0011, instead of trying your suggestion I first decided to try make a gun with the same animations but no animated parts, so essentially a vanilla type static gun mode with mesh filter and mesh render, and the aiming problem still occurs. So its not about the moving parts, something is wrong with animation itself. Could the fact that I dont export keyframes for Skull, spine and legs cause they arent being moved by gun animations the reason? Like, maybe the skull moves in a wrong way or something, cause I cant find a proper explaination of why this happens.

**Comment by prank0011** [comment]
I tried it, but it didn't trigger the Bug.Can you share the 'Equip' animation file?
![QQ截图20221204000539](https://user-images.githubusercontent.com/68633558/205450278-5664ff31-40c2-42d4-bbf7-d9f27edb1874.jpg)

**Comment by DerpyHoowes** [comment]
Turns out its not the Equip animation causing. First I tried to replace equip animation with vanilla one, but the issue was still present. Then I did the same with aiming animations and it fixed. So the problem is caused by something in aiming animations.
Can you give me your discord nickname or maybe some other contact, so I can send you the animation file privately?

**Comment by prank0011** [comment]
My discord username is prank#0079, or you can send it to my email: 1010124811@qq.com, thank you very much!

**Comment by DerpyHoowes** [comment]
Actually I've found a way to fix it! Turns out this was happening because I didnt export all bones keyframes, only the ones I moved. I dont know what does that have to do with camera snapping to the wrong position, but at least it fixed it.
