### ISSUE TITLE
UI Effect Lifetime set to 3 Always exists without closing

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3540]
Here is my effect mod: [https://steamcommunity.com/sharedfiles/filedetails/?id=2893102173](url)

Here is the configuration file of one of the prefabs, `Lostingpoint.dat `:

```dat
Type Effect
ID 3002

Lifetime 3
```

I played with single player mode, and found 2 problems:

**Problem 1:** Lifetime doesn't work  =>even if I set `Lifetime 3`. when using `/effctUI 3002`，effect always appears without closing.

**Problem 2:** effect cannot appear together, even if they have different IDs
step1: using `/effctUI 3001`
![1](https://user-images.githubusercontent.com/12797737/204128757-f5aee14a-435b-47eb-aa3f-4fe5f238c24b.jpg)
    step2: using `/effctUI 3002`
![1](https://user-images.githubusercontent.com/12797737/204128794-0b6cbdc2-f5a9-448d-b6c1-e07c5f9d850d.jpg)

I want 3001 and 3002 appear together, not 3002  appear and 3001 disappear

These problems also occur in the server mode, using `sendUIEffect` method.

**Comment by GazziFX** [comment]
`/effectui` always use key `1`, effects with same keys replace each other, and for `sendUIEffect` if you pass key `-1` effects wont replace each other and will use lifetime

**Comment by makeloffve** [comment]
> `/effectui` always use key `1`, effects with same keys replace each other, and for `sendUIEffect` if you pass key `-1` effects wont replace each other and will use lifetime

Sir, you did me a big favor, thanks a million!!!
