### ISSUE TITLE
GPS & Volumes bug

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3541]
If you have a volume set on "Solid" & bake GPS, The GPS Will bake the visible black/grey box with it. 
![image](https://user-images.githubusercontent.com/101991669/204263509-e273b903-fbd8-4b30-9ba8-01af40289474.png)

**Comment by UsernameIsUnavailible** [comment]
![image](https://user-images.githubusercontent.com/101991669/204263693-38783e3c-b7cd-4a2b-9f2e-eebde80cea9e.png)
This is the dam visible from in-game. No black box seen (cuz its a playerclip volume set on solid)

**Comment by SDGNelson** [comment]
Haha whoops! Will see about an alternative layer for those.
