### ISSUE TITLE
player look check not working (Raycast i was told its called)

### ISSUE THREAD

**Issue by Akulation** [SmartlyDressedGames/Unturned-3.x-Community#3542]
In my server any command/event/whatever that uses the function of a player looking at a barricade/player/vehicle stopped working. This is for a couple of rocketmod plugins aswell as uscripts.

The main one that is happening is for a plugin that allows players to revive another player by using surrender and looking at the knocked down player.

**Comment by GazziFX** [comment]
All of my plugins with raycast works fine

**Comment by Akulation** [comment]
okay, to update on this, the barricades/structures are working for raycast.
the vehicles and players are not working though.

**Comment by GazziFX** [comment]
What exactly code fails?

**Comment by Akulation** [comment]
im not sure, i dont make my own plugins for rocketmod.
the plugins are used by many people and seem to work for everyone, i was told by the plugin developer to ask here for help.
