### ISSUE TITLE
I cant create UI

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3544]
Have this error from log
![image](https://user-images.githubusercontent.com/65422793/205119636-7001b50c-0a8c-494a-8e6d-8ad8409ac646.png)
Have this path
![image](https://user-images.githubusercontent.com/65422793/205119726-48ea61c0-c8d4-48d0-a91c-eb18b57d3623.png)
Path in Unity
![image](https://user-images.githubusercontent.com/65422793/205119789-6170eb09-cded-4698-aca3-a54c1f367f22.png)
MasterBundle.dat
![image](https://user-images.githubusercontent.com/65422793/205119911-30659f11-4125-467c-ab1c-c56f0ef7066a.png)

**Comment by FANYPLAYRU** [comment]
AssetBundle on ChoosePerm folder 
![image](https://user-images.githubusercontent.com/65422793/205120110-efbca215-1fb9-4935-9feb-4f80f88460cc.png)

**Comment by FANYPLAYRU** [comment]
2020.3.42f1
![image](https://user-images.githubusercontent.com/65422793/205140388-991ba019-bcbe-4255-b968-9d595066f2ee.png)

**Comment by FANYPLAYRU** [comment]
Game
![image](https://user-images.githubusercontent.com/65422793/205140483-9e88facb-8e41-4872-af69-3de96dcaab4e.png)

**Comment by GazziFX** [comment]
You should install unity version 2020.3.38f1 or older

**Comment by FANYPLAYRU** [comment]
Seriously? On the 19 version of the engine I used the latest version and everything worked 
Thank you very much!
