### ISSUE TITLE
Misaligned Editor UI elements

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3545]
"Misaligned" isn't the perfect word to describe these issues. Technically has more to do with size and position?

### Volumes button misalignment

![Volumes tab diagram](https://user-images.githubusercontent.com/7608445/205172968-d718d861-7011-42e9-9758-afd091a0033a.png)

The Volumes tab is too short, and doesn't line up with both ends of the Level tab. It looks like the **X Size Offset** for the **Volumes button** is off by 5 pixels (should be **-5** instead of -10?).

### Objects UI very low

![Objects UI diagram](https://user-images.githubusercontent.com/7608445/205176494-22f5717d-9d28-462e-b0c0-df7fe99b1842.png)

The Objects UI starts much lower than it should. It's ~80 pixels lower than other, similar UIs with that have their tools in the top-right area.

**Comment by SDGNelson** [comment]
Thanks! Fixed these now for the next update.
