### ISSUE TITLE
[Bug] "Pro" items in vendors do not show Name/Description!

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#3546]
Hello,

"Pro" items are designed to be cosmetics, and so cannot be given into your inventory. They are a great method for creating an "empty" output, especially in spawn tables, quests, etc. However, there is one issue. 

"Pro" items do not properly work in Vendors. The name and description do not appear, even if you have the proper localization file for it. I do not know if this is an oversight or intentional, but this small change could allow for custom vendor icons, with little change to the structure of how vendors work.

Combined with the introduction of Vendor conditions and rewards, you can dispense quests, flags, vehicles, etc while providing an icon that does not affect gameplay nor give you an item. Would be incredible for customization.

Thank you.

![image](https://user-images.githubusercontent.com/66083394/205235043-92bc96ce-deb0-44cf-8aff-56720cc59fae.png)

![image](https://user-images.githubusercontent.com/66083394/205235068-6dcb565d-e7fb-4703-af6b-ebf3580364d0.png)

![image](https://user-images.githubusercontent.com/66083394/205235443-49fe6390-13f3-4014-b8cc-51cea6772757.png)

![image](https://user-images.githubusercontent.com/66083394/205236533-1d99ad69-058d-4f54-8e06-5b6d8ae2754c.png)

**Comment by SDGNelson** [comment]
This is not a bug because localization was intentionally not read for these items, but using them as an icon is a pretty clever hack so I will change that for the next update.
