### ISSUE TITLE
Workshop download failed lag

### ISSUE THREAD

**Issue by Dudewithoutname** [SmartlyDressedGames/Unturned-3.x-Community#3548]
Recently i was joining to a random server and got kicked out because i didn't have the map which couldn't download since  workshop's failing and retrying so i joined another server and freezing started

https://user-images.githubusercontent.com/54103088/205420822-a1a92a35-258a-4dcf-8854-1e7296eb7560.mp4

**Comment by SDGNelson** [comment]
It might be related to the download start/stop in the background I guess. If it was one-off there is not much to be done, or is it happening after restarting the game?

**Comment by Dudewithoutname** [comment]
I had to clean workshop download cache to stop it.
