### ISSUE TITLE
Dear Nelson, please remove one line from game code[Bug/Feature]

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3549]
Please remove typeof(PreUpdate.UpdateVideo) from DISABLED_SYSTEMS
This system need for correct video player work, you can check it yourself.
I really need a video player on my server.

**Comment by Jdance-Media** [comment]
There were past requests to remove that.

**Comment by educatalan02** [comment]
It's not a bug I guess

**Comment by SDGNelson** [comment]
It is not a bug because the game tries to disable any extra features not being used. Though I should review what features are disabled there. This request keeps coming up so how about if a bunch of developers comment on this I will enable video player.

**Comment by blazethrower320** [comment]
I would personally love being able to play a video on a UI. Would make alot of new, unique UIs.

**Comment by Senior-S** [comment]
It can be a cool addition

**Comment by DanielWillett** [comment]
Could see it being great for showing tutorial/intro videos to new players.

**Comment by fahrettinenes** [comment]
That would be really good

**Comment by negrifelipe** [comment]
Would be cool to have it :)

**Comment by liebesleid-eth** [comment]
I'm not even a developer but I'd absolutely love to have that featurefor the same reason Daniel said!
I've noticed some newer players cannot use steam browser ingame, which renders links to youtube or guides useless for them

**Comment by QERT2002** [comment]
Thanks for answer, i have been waiting for this system for a very long time and I hope you add it)

**Comment by XanderCodes** [comment]
Would appreciate it! No more attempts at scripting to make a sprite animation that is 300 frames long 😆

**Comment by Edbtvplays** [comment]
Please Enable! Would be awesome to finally implement some tutorials for servers etc...

**Comment by blazethrower320** [comment]
Developers shall unite!

**Comment by DerSpeedMann** [comment]
Pls let us use videos

**Comment by sunnamed434** [comment]
You shall not pass bugs, nice to be added

**Comment by Dudewithoutname** [comment]
Expands possibilities so why not (+1)

**Comment by Akulation** [comment]
im just starting to make UIs and this would be a really good addition to the possibilities for making plugins.

**Comment by Paradox304** [comment]
Would be nice not having to create a sprite animation of 900 frames long, please add

**Comment by Nonanti** [comment]
I think that will be unbelievable

**Comment by SDGNelson** [comment]
Today's update removed the video player from list of disabled player loop subsystems
