### ISSUE TITLE
Game Crashing Randomly With No Errors

### ISSUE THREAD

**Issue by silentshotghost** [SmartlyDressedGames/Unturned-3.x-Community#355]
My frames starts to drop rapidly and my game freezes but when i go to check error log there are no error.

It's not my pc i have a i7 6700k and a gtx 1080ti

**Comment by Trojaner25** [comment]
![image](https://user-images.githubusercontent.com/1809172/42590372-4ced9e20-854c-11e8-806b-d230558afb5f.png)

[silentshotghost, the cheat guy, is totally not trying to troll]

**Comment by silentshotghost** [comment]
no troll this is real talk

**Comment by silentshotghost** [comment]
i was 1v1 puppy and game crashed even ask puppy
