### ISSUE TITLE
[Bug] Game client don't check workshop update.

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3550]
When i am update my mods and restart server, peoples can't join without restarting your client.
Can you add workshop check when client connect to the server?
Because before restart i need to type in broadcast something like: "Guys, i am update server mods, please reboot your game application".

**Comment by SDGNelson** [comment]
Off the top of my head the last time I checked into this I could not force the client to detect new workshop version. The plan is to add direct download of files over HTTP at some point.

**Comment by QERT2002** [comment]
Thanks for answer, you can use steam api.
And before test see what your modification checked by steam system.
Maybe this will help.
