### ISSUE TITLE
[Feature Request] Adding magnet for vehicles via asset

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3551]
The ability to add magnet hook function to vehicles without editing them in unity and adding Hook prefab. This would allow players to add magnet hooks for vanilla vehicles or vehicles from old mods using asset pointers.

Example
Magnet_Hook
Magnet_Hook_X (float)
Magnet_Hook_Y (float)
Magnet_Hook_Z (float)
If any coordinate isnt specified in the asset, its set to zero by default.

**Comment by SDGNelson** [comment]
In general the magnet feature needs some work. My plan is if/when I can make vehicles server authoritative the magnets will use physics rather than parenting them to the vehicle.

**Comment by DerpyHoowes** [comment]
Well, until then this little feature would still make life a bit easier ;)
