### ISSUE TITLE
[Feature Request] Clear all spawns button.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3552]
It would be helpful to have a button to clear all placed spawns of a certain type on a map. Many people require this feature because they copy spawn files from other maps in order to use their premade tables.

**Comment by SDGNelson** [comment]
Rather niche, but in the meantime one option would be to copy just the Items.dat file because that has the spawn tables without the placed item spawn points.

**Comment by Jdance-Media** [comment]
The inconvenience comes about when the placed spawns from another map (in this case Russia) pop up on the custom map. When I transferred the Vehicles.dat, they showed up.
![2022-12-03_17-49-00](https://user-images.githubusercontent.com/67397422/205465479-38f1f564-31aa-49a4-98d4-e8ab9ef07990.png)

**Comment by prank0011** [comment]
You can create a new map of the same size, copy the Vehicles.dat of the new map and put the map you need to modify.

**Comment by SDGNelson** [comment]
True, vehicles do not have the same separation of files unfortunately. I guess the easiest option for those would be to make note of which "spawn table IDs" you want to use since that has most of the vehicle spawn settings.

**Comment by Jdance-Media** [comment]
How did I not think of that.
