### ISSUE TITLE
[Bug] Server only shows up in LAN, but showed up in WAN hours earlier

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#3554]
Simple.

The server showed up on WAN for everyone including me earlier today.

But now it only appears on LAN, despite having made no changes to anything.

I have tried the following
💠 Generating a new steam login token and using that
💠 Removing all Rocketmod plugins
💠 No need to check ports, it was already configured correctly months ago

My servers have been running for months and this has never happened until today. Could it be because a local steam server is down? If so, shouldn't console tell me it failed to connect? In which case this would become a suggestion for such a feature to be added.

**Comment by RainOfPain125** [comment]
When I try to directly connect it works fine.
IP - 70.160.21.187
Port - 27015

**Comment by SDGNelson** [comment]
This server was de-listed for intentionally mimicking the details of another server. I will re-list it this afternoon, but please do not fake other servers again or it will be blocked.

**Comment by RainOfPain125** [comment]
> This server was de-listed for intentionally mimicking the details of another server. I will re-list it this afternoon, but please do not fake other servers again or it will be blocked.

I sometimes rent out servers from my own home network, it would be nice if there was a way to provide a warning in the event that one of the renters were to do such a thing, as they have unlimited access to their configs and setup via FTP & a server panel. Maybe having some code on the server-end that writes to console a warning that the IP has been blacklisted, and to contact SDG support email to resolve the conflict? That sounds like it could work, so this is a feature request.

Although in this particular case, it was indeed not a renter. This "mimick" server (wont bother saying the name) wasn't meant to be on +InternetServer, it was meant to be on +LanServer for testing purposes while I tried to remedy a similar server, based off of an existing one (make an identical "fake" server with the same Config.json Commands.dat WorkshopDownloadConfig.json and other misc setup, and then proceed from there as a baseline to work with).

Though I can understand the concern, I must clarify that I had no bad intentions. Thank you for understanding, and thank you for taking it off the blacklist (when you get around to it).
