### ISSUE TITLE
[Bug] Items work in singleplayer, but dont work on a server

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3556]
Some of items of my mod dont work on my friend's server. They work in singleplayer, but on my friend's server you cant spawn them. There are no errors in the error logs, no conflicting IDs (/i plugin just says "Invalid Parameter"), all other items of the mod work fine on server. My friend checked the server logs and said there was nothing about these items.
Whats the weirdest thing about all of this, is that all three items that dont work contain the same word in their names:
(ID)      (Asset Name)  (Localization Name)
31902 Soviet_C_JSgt "Red Army Junior Sergeant Uniform"
31903 Soviet_C_Sgt "Red Army Sergeant Uniform"
31904 Soviet_C_SSgt "Red Army Senior Sergeant Uniform"
https://steamcommunity.com/sharedfiles/filedetails/?id=2896649362
It all seems very weird: The fact that they work in SP but dont work on the server (I havent tested them out on any other servers though), the fact that everything else in the mod works and the fact that they all contain the same word Sergeant in their Localization names and Sgt in their asset names. In theory what could be causing this?

PS: These three items have similar files to other shirt items of the mod, there is nothing special neither about their assets nor about their folders in unity. So yeah, I have absolutely no idea why its these items that dont work on server.

**Comment by DerpyHoowes** [comment]
Tested it on my PC with unturned dedicated server and it works for me. So something is wrong with my friend's server but we just dont know what exactly.

**Comment by SDGNelson** [comment]
Is your friend's server on Linux? Is there a capitalization difference between the item folder and file names? Linux has case sensitive file names whereas Windows is case insensitive.

**Comment by DerpyHoowes** [comment]
Yeah, and turns out that capitalization indeed doesnt match.
