### ISSUE TITLE
[Bug] Items not spawning

### ISSUE THREAD

**Issue by Rampardge** [SmartlyDressedGames/Unturned-3.x-Community#3558]
Sometimes when playing either alone on singleplayer or with a friend on a server I bought, loot just dont spawn in when we go somewhere. They take between 1-5 minutes to actually spawn but its extremely irritating and caused us to stop playing until we get a fix for it.
Only thing that fixes it is restarting the server, which takes too long and cannot be bothered with it whenever we go loot something.
Its not anything to do with server settings as weve tried item despawn and respawn times multiple times.
The bug happens on both single and multiplayer aswell and happens randomly, sometimes there is loot sometimes not.
Is this a known bug and is there any fix for it?

**Comment by SDGNelson** [comment]
Item respawning can end up being a little slow especially if it is a giant map. What did set Respawn_Time and Spawn_Chance to? Did you modify the section corresponding to the difficulty? e.g. If your server difficulty is set to Normal then you need to edit the "Normal" section of the config file.

**Comment by Rampardge** [comment]
I modified the correct files and respawn time was 10-15 minutes and spawn chance was something like 0.4

we were playing on the maps germany and france

**Comment by SDGNelson** [comment]
10-15 minutes is very high. The default on Normal mode is 100 seconds. You probably want something much lower.

**Comment by Rampardge** [comment]
that would mean that after looting an entire city, the area u looted first would have long respawned when u get there which feels a bit cheaty
