### ISSUE TITLE
[Bug]&[Feature Request] Two maps with the same name will make the editor bug out

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#3559]
Well you would assume it would, but instead of letting the player into the editor maybe you could instead prevent the player from editing the map by kicking them out of the editor with a message (much like a server would) that explains that there are two maps with the same name.

Also, for convenience you could make it so that if you have a local development map, and the workshop version of the map, then the editor inherently prefers the local map and will choose to load only that, neglecting the workshop map even if it has a .unlocker

**Comment by SDGNelson** [comment]
Something like this is on my to-do list
