### ISSUE TITLE
[BUG] Placing locker wardrobe claim flag inside each other

### ISSUE THREAD

**Issue by Commando53** [SmartlyDressedGames/Unturned-3.x-Community#3562]
#1520
this bug was in the game for a long time but after going back and checking nelson said that it will be fixed, and it was fixed, you cant hide claim flags inside of structures, but you can hide it inside a locker or wardrobe just like in the screenshot
![image](https://user-images.githubusercontent.com/105989119/206457738-dad17736-c62f-4362-9e3d-6704ab6a1847.png)
![image](https://user-images.githubusercontent.com/105989119/206457832-e0036718-f871-4bb1-854a-bb4ca00cdc9c.png)
![image](https://user-images.githubusercontent.com/105989119/206457888-54709cc6-5ceb-4033-bb77-0819be803299.png)

it gets really annoying when trying to get to the claim flag you just waste your ammo on a wardrobe

now personally i love this one as a feature you can cram 2 wardrobes into each other for using the corners of a base efficiently
![image](https://user-images.githubusercontent.com/105989119/206458409-10622299-f392-4ebe-866a-d025bd13d325.png)

i created this issue cause i couldnt find any other issue mentioning this issue
now i dont know if this is meant to be like this or not i need someone to enlighten me

**Comment by DerSpeedMann** [comment]
You might also consider using a second person and placing them both at the same time to bug the flag inside a wardrobe

**Comment by SDGNelson** [comment]
Rewriting some of the barricade placement stuff is on my to-do list. Sorry about this!
