### ISSUE TITLE
How do you get the impact EffectAsset of a PhysicsMaterialAsset from it's name?

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3564]
Looking at ingame implementations they seem to all use `PhysicMaterialCustomData` which is an internal class. Meaning its not really accessible. Whats the correct way to get the Impact EffectAsset or just the `PhysicsMaterialAsset` from a PhysicMaterials name?

**Comment by GazziFX** [comment]
Personally I prefer to patch reference assemblies to make all types public, but you must set AllowUnsafeBlocks in project

**Comment by SDGNelson** [comment]
Old code was all public, newer code is internal to be more intentional with what is exposed for plugin use. What are you trying to do with physics materials? Which type of impact? What is your intention?

**Comment by Gamingtoday093** [comment]
> Personally I prefer to patch reference assemblies to make all types public, but you must set AllowUnsafeBlocks in project

While yes, I could do something like this. I was wondering if there was an actual proper existing way to convert from a PhysicsMaterial `Name` to the actual asset or impact effect. This is also why using a lookup table for Effect ids isnt ideal either (Even if I've used them in the past) since the best solution would have the same support as regular unturned. (Custom PhysicsMaterials and all)

> What are you trying to do with physics materials? Which type of impact? What is your intention?

I am simply trying to show an *impact* effect on a player or anything with collision. Essentially as two examples I just want to trigger Effect ID: 5 (Flesh Impact) when a player gets hit by for example a custom colleteral bullet or another effect when a vehicle does damage to another vehicle by a custom bumper implementation.

What is *if it exists* the current supported way for plugins to get the PhysicsMaterial Data?

**Comment by sunnamed434** [comment]
> Looking at ingame implementations they seem to all use `PhysicMaterialCustomData` which is an internal class. Meaning its not really accessible. Whats the correct way to get the Impact EffectAsset or just the `PhysicsMaterialAsset` from a PhysicMaterials name?

Why not just use reflection to get access to the internal class?

**Comment by GazziFX** [comment]
> Why not just use reflection to get access to the internal class?

Overhead probably

**Comment by sunnamed434** [comment]
> Personally I prefer to patch reference assemblies to make all types public, but you must set AllowUnsafeBlocks in project

Do you have an example of patching reference assemblies? I guess this is unsafe

**Comment by Gamingtoday093** [comment]
> It sounds like in your case you would like to add some extra custom effects to the material asset?
No I do not wish to add custom effects just *get* them thats all. So for example "Flesh_Dynamic" => EffectAsset with Id 5

**Comment by SDGNelson** [comment]
@Gamingtoday093 right now the closest thing is an internal method `WipDoNotUseTemp_GetBulletImpactEffect`. This method could be made usable for plugins (or something more like "GetGenericImpactEffect"), but it would change in the future when the decal and particles are separated out. :/ :(
