### ISSUE TITLE
Zero-alloc NetworkSnapshotBuffer

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3565]
Problem comes here when you casting struct to interface it becomes reference(boxed) type and allocates additional memory, it can be an issue with high numbers of entities.

I modified it a bit
```csharp
public interface ISnapshotInfo<T> 
{
    void lerp(in T target, out T result, float delta); // Avoid copy of large structs
}

public struct NetworkSnapshot<T>
{
    public T info;

    public float timestamp;
}

public class NetworkSnapshotBuffer<T> where T : ISnapshotInfo<T>
{
    public NetworkSnapshot<T>[] snapshots { get; private set; }

    public void getCurrentSnapshot(out T);

    public void updateLastSnapshot(T info);

    public void addNewSnapshot(T info);
}

```

**Comment by GazziFX** [comment]
Also `PhysicMaterialCustomData.GetAudioDef` has some unwanted `IEnumerator` allocations
![image](https://user-images.githubusercontent.com/43498426/206758119-f0ff6ce8-253e-481f-adee-6040a4e46f76.png)

**Comment by SDGNelson** [comment]
To some degree I want to ignore this out of spite (GazziFX is the developer of an Unturned cheat client), but I should sort both of these out. Sigh.
