### ISSUE TITLE
Animator will be re-enabled

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#3567]
Animator depends on Director which was disabled as part of revisiting the disabled PlayerLoop subsystems. This did not get caught because nothing in the base game or curated content uses Animator. I will enable the Director subsystems in a patch and make a note that mods/plugins are using it. Waiting a little bit in case any other issues are reported in the update.

**Comment by Commando53** [comment]
related to the update, crosshair hides itself a bit delayed after opening the menu like on the screenshot, which i find kind of annoying
![image](https://user-images.githubusercontent.com/105989119/206771111-64d6ec97-657e-4181-9b11-52503f5cb478.png)

**Comment by SDGNelson** [comment]
@Commando53 thanks for the report! That's weird, I will investigate...

**Comment by surv0013** [comment]
I don't want to rush you, but how long do we have to wait?
