### ISSUE TITLE
Comments about the new update.

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3570]
@SDGNelson, I'm interested in the following questions.

1. If the server uses GSLT, but is blocked for using other people's modifications, then the person will still not be able to connect to the server?
2. What exactly is the permission of the author of the modification to use his mod? His message? If the author revokes permission to use his modification, then it can no longer be used?
3. Now many different servers use modifications without the permission of the authors. Don't you think that by introducing the rules on the ban on connecting to servers without GSLT, you are losing part of your community?

**Comment by SDGNelson** [comment]
1. If a server is intentionally stealing workshop mods then there is usually a warning before an actual block.

2/3. The problem is only if re-uploading workshop files without permission. Using the original workshop file is fine unless the creator blocks a server from using it.
