### ISSUE TITLE
[Feature Request] Config Option for Aurora only during Holiday Season

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3572]
title :)

something like
"Is_Aurora_Borealis_Holiday_Only": true,

EDIT: Spyjack's suggestion would be much preferred!

**Comment by spyjack** [comment]
There are a lot of little config things people want changed for holidays, and limiting it to specifically just Christmas or Halloween creates this self repeating cycle of 'Can this one overwrite be added for X holiday', so **I have a counter suggestion**:

Give either level configs or level assets, or both, a 'Holiday override' table where it defines a holiday, and anything designated in the table/array/whatever it is gets overridden on said holiday, so you could have different weather like thunderstorms on Halloween and blizzards on Christmas, Auroras on Christmas, maybe even a special _totally not the_ polar express durring christmas or something bizarre. Point being, it would take longer to add but would provide a LOT more utility.

**Comment by Spebby** [comment]
100% agree with you. I would have suggested that, but a simpler request is more likely to be added so I threw it up. But ideally yours would be ideal. I've in the past requested overriding lighting for the holiday season, so having more flexible weather and spawntable tools even would be ideal.
