### ISSUE TITLE
Error plugin

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3575]
Before starting the Rocket server, it sends me this message
`Invalid or outdated plugin assembly: ALTPlugins`
What to do with it?

**Comment by GazziFX** [comment]
I think you have corrupted ALTPlugins.dll or something in your Plugins folder

**Comment by PARTOVIY** [comment]
No, the plugin was compiled without any errors. This was not the case before the new update.

**Comment by sunnamed434** [comment]
> Before starting the Rocket server, it sends me this message `Invalid or outdated plugin assembly: ALTPlugins` What to do with it?

Perhaps ALTPlugins doesn't has RocketPlugin/RocketPlugin<> base type

**Comment by PARTOVIY** [comment]
@Gamingtoday093 thank you <3
