### ISSUE TITLE
[Feature Request] Action Type Quest

### ISSUE THREAD

**Issue by spyjack** [SmartlyDressedGames/Unturned-3.x-Community#3577]
The ability to right click on an item to craft a blueprint with a custom defined text and tooltip is awesome, especially since blueprints can activate quest rewards, but what happens if you aren't trying to craft something, what if the item is just there for utility or quests?

### [Suggestion]
I propose a new type of `Action_#_Type` to go alongside `Blueprint` called `Quest` that would allow for triggering quest rewards via the context menu. These actions would be able to define quest conditions that change if the context option appears or not, and rewards to perform if the defined conditions are met.

### [Community Usage Examples]
- Either quest specific items, or normal items, that can be 'inspected' or 'examined' during some sort of detective quest to provide clues.
- Sending items to the shadow realm for experience
- Unlocking a new area in the map

### [Personal Usage Examples]
- Crafting recipes that can be permanently unlocked via examining a scroll
- Puzzle items
- Turn gold coin items straight into quest flag stored currency

Thank you for your time and consideration.

**Comment by SDGNelson** [comment]
That is a pretty cool way to extend the item Actions feature.
