### ISSUE TITLE
Wrong server token account ban

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#3578]
My steam account server token function is restricted, he pointed out that I have a server token banned, but I don't think I have any violating servers
I suspect someone may have stolen my server token!
My Steam64: 76561198190678453
@SDGNelson

**Comment by CatzMR** [comment]
https://smartlydressedgames.com/UnturnedHostBans/index.html
There is no server about me on the banned server list!

**Comment by CatzMR** [comment]
@SDGNelson Urgently hope you can deal with it as soon as possible, he has seriously affected me

**Comment by CatzMR** [comment]
https://smartlydressedgames.com/UnturnedHostBans/index.html
The only Chinese server owner on this list is https://steamcommunity.com/profiles/76561198316853346
Not affiliated with me, but his server is hosted on the same ISP as mine
I think this ban is wrong for me

**Comment by 1436269916** [comment]
Sound like someone stole your GLST and then made a malicious copy of the server's name on the banned list,To frame you for it.
Then,the actual offending serversuccessful to evade the ban.

**Comment by CatzMR** [comment]
@IronManMK47 So how should I do it, this has a great impact on me, I feel so innocent

**Comment by IronManMK47** [comment]
I think u should report the real offending server ip to Nelson,Good luck for u~

**Comment by SDGNelson** [comment]
I see you also sent an email about this so I followed up by email.
