### ISSUE TITLE
[Feature Request] Weak/Strong Melee Animation Variants

### ISSUE THREAD

**Issue by spyjack** [SmartlyDressedGames/Unturned-3.x-Community#3579]
The current Melee system works well but doesn't have a whole lot of depth to it, and one of the bigger issues is that attacking with the weapons looks and feels really repetitive, you constantly attack in the exact same manner with the exact same movements. I am suggesting something similar to how animals have animation variants.

### [Suggestion]
If melee weapons could have a definable amount of animation variants for weak and strong attacks, exactly like how animals can have multiple attack/startle/idle animations, that would be chosen at random when the player swings their melee weapon. This could open up a nice extra layer of depth and strategy. Since the `Strong` and `Weak` .dat lines tell where in the animation to deal damage, this would also allow for the animations to have varying length so you have to time your swings and track your target more so than the repetitive way of clicking currently. This could potentially be defined with a .dat line such as `Weak_Animation_Variants X` and `Strong_Animation_Variants X` where X is the amount of variants. 

An add-on to this suggestion to counter the 'Randomness in combat is not fun or balanced' argument is to have one other .dat flag like `Attack_In_Order` to cause the animations to play in the listed order opposed to randomly chosen. This way the attacks will feel fluid while also providing quality variations and extra skill. The order could be reset after not swinging for a bit, using the other attack method, or unequipping.

### [Community Usage Examples]
- Visual variations to melee weapons to make fights look and feel more dynamic.
- Melee fights could be more fluid with different outcomes than who has the better weapon and who clicked first.
- Weapon attack 'combos' where the first attacks are slow and the last is fast

### [Personal Usage Examples]
Melee weapons are the staple and majority weaponry in Tales of Terror, and with only having 2 possible animations, it feels very repetitive and boring to fight larger amounts of enemies.
- Quick weapons, like Daggers, would have varying length to balance the DPS while still keeping the attacks fast.
- Heavy weapons, like Battleaxes and Warhammers, would have rare special 'quick' strong attacks.
- Swords would have better combat feel and attack performance by having quicker and slower attack variations.

Thanks for your time and consideration.

**Comment by prank0079** [comment]
I think if we change the melee attack system, it is more practical to use the stored power mode.

**Comment by SDGNelson** [comment]
I agree this makes a lot of sense. Revamping melee is on my wishlist.

Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
