### ISSUE TITLE
Problem with deleting a separate resource

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3580]
Previously, in the map editor, I could delete one separate resource from the map using rendering. At the moment, I need to completely remove the vanilla resources "BUSH" from the map, but the new editor now has an active tool that creates a render of all resources together. How do I delete a separate resource from the map?

**Comment by SDGNelson** [comment]
You want to remove a specific bush asset from the map? Best option would be to use the "remove selected" hotkey with the paint brush, select the bush asset, and paint the map with a large brush.
