### ISSUE TITLE
Hi I want to spawn object on vehicle

### ISSUE THREAD

**Issue by adaekin** [SmartlyDressedGames/Unturned-3.x-Community#3584]
Hi, I am doing a TOW(Guided Missile) I did it tracking system and other thing but the problem is reloading.
I've been trying for 4 day but I still can't do reloading system.
The gameobject have a rocket modhook, when the gameobject hit somewhere it gonna blow up and deleting the gameobject.

(Triggering the object its so easy with turret modhooks so dont think that)

My problem is I can't return that object, that means I have only one rocket or how money rocket clone I added.

I used magazine gameobject
every modders knows magazine have object(mesh), I added a rocket to mesh then I tried to detach from the magazine
yeah it not worked too

I really have a no idea
I am waiting your suggestion especially Nelson...
![image](https://user-images.githubusercontent.com/76937703/207946696-036c98c7-d514-43da-b7e0-de4c62420e4f.png)
![image](https://user-images.githubusercontent.com/76937703/207946726-053d17fd-fa0d-49a0-a9e6-b659b2d9b261.png)
![image](https://user-images.githubusercontent.com/76937703/207946799-004280b0-a36c-41e5-95e9-01937be9a9ce.png)

**Comment by adaekin** [comment]
I looked lots of scripts from Assemblycharp on dotpeak

**Comment by SDGNelson** [comment]
Sorry, I am not sure I understand how it is setup, but this is not really supported as-is. Ideally a vanilla feature for laser-guided missiles would be added.
