### ISSUE TITLE
[Bug Report] Menu icons don't also change color tint.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3586]
Explains itself.
![image](https://user-images.githubusercontent.com/67397422/208194318-755b93f9-d16f-4477-bf46-6175cadeb18a.png)

**Comment by SDGNelson** [comment]
Those two are unaffected by tint because their branding guidelines require they are displayed in white.

**Comment by Jdance-Media** [comment]
> Those two are unaffected by tint because their branding guidelines require they are displayed in white.

Ah, my apologizes then.
