### ISSUE TITLE
Issues downloading mods sometimes

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3589]
Recently it seems like getting steam to download mods is difficult most of the time. I attached a video that will show what I mean better but basically, the game says it's downloading, finishes quicker than it should, then a `k_EResultFail` Steamworks error is logged for each mod. (Yes my internet is working in the video and Steam is not blocked or restricted by the firewall or anything like that). The server has the mod ids in the workshop config file, not in the folder. Some players can join, but I think others sometimes get this issue.

[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10253122/Client.log)

https://youtu.be/yOWBFLiEjVc

I don't know if this is a steam issue, Unturned, or somehow how the server is set up but any advice would be appreciated. Thank you.

**Comment by SDGNelson** [comment]
Since the client download is failing then there might be more details in Steam's workshop log if you can attach that. It should be something like: "C:\Program Files (x86)\Steam\logs\workshop_log.txt"

**Comment by DanielWillett** [comment]
[workshop_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10254972/workshop_log.txt)
(around `2022-12-17 21:00:00` to `2022-12-17 21:45:00`)

It says it's missing game files but those files are in mods, I'm running an integrity verification now I'll let you know how it goes in a few minutes.

**Comment by DanielWillett** [comment]
So the verification did sort of fix it until I wiped my `workshop/content/304930` folder to join my dev server (because we have a separate dev version of a mod and I need to take out the main one to prevent bundle and asset verification issues). I used to do this all the time to switch servers but all of a sudden it doesn't redownload them.

**Comment by SDGNelson** [comment]
It looks like it is not happy the file is being deleted unexpectedly. Is the dev mod a separate workshop file id? If so, as of a recent update it will only load the files used by the server so they should not conflict.
