### ISSUE TITLE
Black screen on lauch fix not working

### ISSUE THREAD

**Issue by MrWool** [SmartlyDressedGames/Unturned-3.x-Community#359]
So after doing all the fixes I can find, including the intalling of C++ Visual studio (2017 and 2015).Nothing worked i couldn't launch Unturned with the Steam overlay, but without it the game works ... but rarely, a lot of times i couldn't load any singleplayer world/server ,it says that it's loading, but then it's stays like that and crashes.Please, any help would be welcome! :D

**Comment by SDGNelson** [comment]
Could you post output_log.txt from the Unturned/Unturned_Data folder please? What're your hardware specs?

**Comment by MrWool** [comment]
[output_log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2192859/output_log.txt) Ok, so here are the logs,and here are my specs:
Windows 8.1 64bit
Processor: i3-3220 3.30 GHz(4cpus)
RAM: 4GB
GPU: Geforce 650GTX (i have the latest drivers)
and here is some more details if you want:
[DxDiag.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2192950/DxDiag.txt)

**Comment by Trojaner25** [comment]
NullReferenceException: Object reference not set to an instance of an object
  at SDG.Unturned.MenuDashboardUI.onWebRequestReady (IWebRequestHandle webRequestHandle) [0x00000] in <filename unknown>:0 
  at SDG.SteamworksProvider.Services.Web.SteamworksWebRequestHandle.triggerWebRequestReadyCallback () [0x00000] in <filename unknown>:0 
  at SDG.SteamworksProvider.Services.Web.SteamworksWebService.onHTTPRequestCompleted (HTTPRequestCompleted_t callback, Boolean ioFailure) [0x00000] in <filename unknown>:0 
  at Steamworks.CallResult`1[Steamworks.HTTPRequestCompleted_t].OnRunCallResult (IntPtr thisptr, IntPtr pvParam, Boolean bFailed, UInt64 hSteamAPICall_) [0x00000] in <filename unknown>:0 

Seems like it is a bug in Unturneds code, and it seems like its indeed related to the overlay.

**Comment by MrWool** [comment]
Well, on my side im soon gonna do a hard reset of my computer and uprgrade to windows 10.Cuz apparently no bugs are on there in terms of Unturned but for the time being im still win 8, and I think a part of the problem comes from my windows because i had a lot problems with other software /games not running because of missing windows files that did not install apparently.

**Comment by Trojaner25** [comment]
The issue is not related to Windows 8 or Windows 10.

**Comment by MrWool** [comment]
oh thanks for the info

**Comment by SDGNelson** [comment]
Trojaner's right that you've found a bug in Unturned's implementation of news/announcements retrieval! I'll see about bulletproofing that and what it might have been blocking.

As for loading into maps issues, my guess is that unfortunately some maps may require more memory than your computer has available (4 GB). Is it mainly the Large maps that have problems loading?

**Comment by Josukeboi** [comment]
Even worse for me, MY OUTPUT LOG IS MISSING and im having a black screen issue in unturned also...

**Comment by Josukeboi** [comment]
It started a few days ago and wasn't like this not after installing some outdated mods and at the afternoon this started to happen, I tried all sorts of methods not a single one of them worked...
