### ISSUE TITLE
Questions about Ping

### ISSUE THREAD

**Issue by chenyicheng311** [SmartlyDressedGames/Unturned-3.x-Community#3591]
@SDGNelson My server will get hundreds of delays when the players reach 5 and above, but below 5 is only stable at 20~40.The following is the performance occupation of my server and debug and some error messages, I hope you can help me solve them, thank you very much!
Debug![debug (2)](https://user-images.githubusercontent.com/98081801/208326009-22ea1d02-9cad-4622-80b4-13cba9351b3e.png)

![image](https://user-images.githubusercontent.com/98081801/208326030-787fb8ba-d3be-47b0-b0ee-9781f0cd9a2a.png)

sever error:
srceamnetworkingsockets/clientlibeamnetworkingsockets_lowlevel.cpp (1873) : Assertion Failed: SDR service thread gave up on lock after waiting 65ms. This directly adds to delay of processing of network packets!

**Comment by SDGNelson** [comment]
Does the server CPU usage significantly increase past 5 players? The 65ms warning suggests the server is running around ~15 FPS at that point.
