### ISSUE TITLE
Polaris [server crash] - server owners

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3593]
Hi @SDGNelson ,
After talking with other server owners it seem to me that the issue I am experiencing is also experienced by other networks.
Servers tend to crash when hosting Polaris map, it doesn't matter whether servers are using Linux or Windows. 
The error is not seen in Rocket nor Server Logs but in case of Linux in docker logs.

Server simply crashes and restarts, and players lose their most recent progress. 
I attached docker log snippet with the error:
```
Caught fatal signal - signo:11 code:1 errno:0 addr:0x7ffc16d593b4
/entrypoint.sh: line 42:    61 Segmentation fault      (core dumped) ${MODIFIED_STARTUP}
server@lyhme~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
```

and here

```
Caught fatal signal - signo:11 code:1 errno:0 addr:0xb8
/entrypoint.sh: line 33:    40 Segmentation fault      (core dumped) ${MODIFIED_STARTUP}
container@ModernHosting~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@ModernHosting~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
```

I invite other server owners to post here errors they have, so that hopefully this issue can be resolved asap.

**Comment by KodakDolph** [comment]
Cannot find any errors but can confirm my Kodak SemiVanilla #7 running on Polaris has been crashing about every 30 mins to 2 hours.

**Comment by gegtor** [comment]
RAID-CITY Also has this issue we were first to report it

@SDGNelson Is aware and working on a fix 

Unity LTS update could be a shotgun attempt at fix

**Comment by P9ndx** [comment]
"P9nda's Polaris" servers are also experiencing it

**Comment by gegtor** [comment]
Here is 2 day graph of my A6 Polaris servers and the frequency of crashes (sudden drops)
As you can see S7 server was wiped to test my theory and the frequency of crashes dropped significantly but not fixed the issue

This could be cause by a change in player behaviour because of the wipe or something got fixed by wiping
After S7 was wiped S17 started to have much more frequent crashes 

I'm out of ideas so I'm giving everything I have

@SDGNelson 

<img width="1613" alt="Screenshot 2022-12-19 at 16 31 22" src="https://user-images.githubusercontent.com/10978723/208466251-142989ba-f00f-4fc7-bb67-ef2c10304666.png">

**Comment by SDGNelson** [comment]
Thanks to a crash.dmp from SOD yesterday it seemed the crash callstack was happening in the engine during a collider/trigger Enter/Exit event when attaching a collider or rigidbody.

Yesterday morning I spent a while trying every combination of trigger/collider/attachment I could think of without luck. (airdrops, explosives, kill volumes, sewer teleporters, etc)

We also double-checked any custom use of those events in the A6 Polaris files. (e.g. PlayerCollisionEventHook)

Yesterday evening I tested on the latest Unity LTS patch (updated from 38f1 to 43f1) and the bugs I ran into on earlier versions seem to be fixed, so just in case this has now been upgraded in the .2 patch.

This morning danaby2 realized the grenade launcher projectile has a giant collider for an "airburst" effect which seems like a very possible cause, so he is going to try removing that in an update to the map.

**Comment by SmallBerry** [comment]
> Thanks to a crash.dmp from SOD yesterday it seemed the crash callstack was happening in the engine during a collider/trigger Enter/Exit event when attaching a collider or rigidbody.
> 
> Yesterday morning I spent a while trying every combination of trigger/collider/attachment I could think of without luck. (airdrops, explosives, kill volumes, sewer teleporters, etc)
> 
> We also double-checked any custom use of those events in the A6 Polaris files. (e.g. PlayerCollisionEventHook)
> 
> Yesterday evening I tested on the latest Unity LTS patch (updated from 38f1 to 43f1) and the bugs I ran into on earlier versions seem to be fixed, so just in case this has now been upgraded in the .2 patch.
> 
> This morning danaby2 realized the grenade launcher projectile has a giant collider for an "airburst" effect which seems like a very possible cause, so he is going to try removing that in an update to the map.

Lets hope that will fix it, thank you for looking into the issue.

**Comment by gegtor** [comment]
.2 Update still has crashes 

I know this was not intended as a 100% certain fix but just reporting

**Comment by SDGNelson** [comment]
It seems the new Unity version also has some other new crashes, so I am going to roll back to 38f1. 😢 

danaby2 is putting together some other fixes to the map as well but plans to release his patch today.

**Comment by SDGNelson** [comment]
For anyone whose servers have been running A6 Polaris v1.0.0.2 today has it crashed after danaby2's fix?

**Comment by gegtor** [comment]
I haven't seen crashes yesterday after v1.0.0.2

**Comment by SmallBerry** [comment]
No crashes so far

**Comment by xes66** [comment]
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
