### ISSUE TITLE
[BUG] ID Conflict with Polaris Cosmetics and Hawaii Gliders

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3594]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/47935791/208364966-3de3fdf1-1579-4276-8c04-4255a8a176a2.png">

**Comment by MoltonMontro** [comment]
Just posting a reference table for Hawaii's item IDs:

Item | ID | Item | ID | Item | ID
-- | -- | -- | -- | -- | --
Yellow Glider | 786 | Red Glider | 1800 | Blue Glider | 1801
Green Glider | 1802 | Orange Glider | 1803 | White Glider | 1804
Purple Glider | 1805 | Black Glider | 1806 | Plain Mushroom | 2010
Roasted Mushroom | 2011 | N/A | 2012 | Spotted Mushroom | 2013
Obsidian Axe | 2014 | Obsidian Club | 2015 | Aegis Security Top | 2016
Aegis Security Bottom | 2017 | Aegis Lab Top | 2018 | Aegis Lab Bottoms | 2019
Shark-Tooth Sword | 2020 | Raft Makeshift Vehicle | 2021 | Gyro Makeshift Vehicle | 2022
Platinum Ring | 4000

**Comment by Spebby** [comment]
I did not add anything, I checked the files for both a _fresh install_ of Hawaii and Unturned's internal ids for pro cosmetics and they do overlap

**Comment by MoltonMontro** [comment]
> I did not add anything, I checked the files for both a _fresh install_ of Hawaii and Unturned's internal ids for pro cosmetics and they do overlap

I'm referring to @SDGNelson

**Comment by SDGNelson** [comment]
Thanks for the report, and thanks for the clarification Molt. Sigh. I will adjust the IDs of the cosmetics and make a note about Hawaii's items in that range.

**Comment by MoltonMontro** [comment]
Since this has been fixed in x.x.x.4, **close topic?**
