### ISSUE TITLE
Players on Mac reportedly unable to join servers

### ISSUE THREAD

**Issue by KodakDolph** [SmartlyDressedGames/Unturned-3.x-Community#3595]
Getting reports from players on Mac, (and also some non-mac users) that they cannot join servers after .3 patch.  They have reinstalled and verified game files.

Errors:

![image](https://user-images.githubusercontent.com/105953666/208516895-bb6b2bdd-05f2-40f4-b7a5-6126766a50d3.png)

A player got this error when attempting to join my PEI Server, and another got the same one when joining Russia:

You were kicked from this server because: missing asset: "Pine Doorway" File: "Doorway_Pine" Id: 2718e79756684574a8223f055c70470f

Both of those are from mac uers^

**Comment by Altf4pew** [comment]
I had the same problem but it said "Asset bundle error: 0 of 1 installed" I'm on mac not sure if its the same thing or not

**Comment by SDGNelson** [comment]
Chiming in to add that I think it might be from reverting the Unity version so I deleted the Library folder this afternoon and it has just slowly been re-building it for a while now. Will check whether that seems to have fixed it and follow-up.

**Comment by SDGNelson** [comment]
It *seems* to be working fine again on Mac after re-importing/exporting the project, so fingers crossed 🤞 that .4 is the final patch of the year.

Also took the opportunity to fix #3594 in this patch.

**Comment by MoltonMontro** [comment]
A couple users have told me that this patch resolved the issue. **Close topic?**
