### ISSUE TITLE
Zombie_Difficulty

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3597]
Where i can find tutorial all setting Zombie_Difficulty?

**Comment by Spebby** [comment]
> Where i can find tutorial all setting Zombie_Difficulty?

There's unfortunately not a page on the U3 docs at the moment. Here is one that I wrote recently.

"Metadata"
{
	"GUID" "8bd15bb899a84b739081131d66c6df44"
	"Type" "SDG.Unturned.ZombieDifficultyAsset, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
}
"Asset"
{
	"ID" "0"
	"Crawler_Chance" "0.15"
	"Sprinter_Chance" "0.2"
	"Flanker_Chance" "0.05"
	"Burner_Chance" "0.05"
	"Acid_Chance" "0.1"
	"Spirit_Chance" "0.075"
	"Boss_Wind_Chance" "0.06"
}

**Comment by JorelDecker** [comment]
Nelson?

**Comment by MoltonMontro** [comment]
Planning to make a PR for ZombieDifficultyAsset documentation soon (this month?), but in the meanwhile:

- **Overrides_Spawn_Chance** *bool*: Defaults to true. You wouldn't set this to false unless you were _only_ changing the last three properties listed.
- **Crawler_Chance** *float*
- **Sprinter_Chance** *float*
- **Flanker_Chance** *float*
- **Burner_Chance** *float*
- **Acid_Chance** *float*
- **Boss_Electric_Chance** *float*
- **Boss_Wind_Chance** *float*
- **Boss_Fire_Chance** *float*
- **Spirit_Chance** *float*
- **DL_Red_Volatile_Chance** *float*
- **DL_Blue_Volatile_Chance** *float*
- **Boss_Elver_Stomper_Chance** *float*
- **Boss_Kuwait_Chance** *float*
- **Mega_Stun_Threshold** *int*
- **Normal_Stun_Threshold** *int*
- **Allow_Horde_Beacon** *bool*

**Comment by MoltonMontro** [comment]
Here's a link to the file that'd be added with the pending PR: https://github.com/SmartlyDressedGames/U3-Docs/blob/b08c7e25730528a60d3f66899c0ecb832b1e8792/ZombieDifficultyAsset.md

**Comment by MoltonMontro** [comment]
U3-Docs has since been updated with documentation for this. Feel free to close this issue yourself, assuming this resolves your question. https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ZombieDifficultyAsset.md

In the future, documentation requests would probably be better off on the U3-Docs repo. Or if you're looking to just discuss/collaborate with other modders, I'd suggest using one of our community hubs instead.

**Comment by JorelDecker** [comment]
> З тих пір U3-Docs був оновлений документацією для цього. Не соромтеся закривати це питання самостійно, припускаючи, що це вирішить ваше питання. https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ZombieDifficultyAsset.md
> 
> У майбутньому запити на документацію, ймовірно, будуть кращими щодо репо U3-Docs. Або якщо ви хочете просто обговорити/співпрацювати з іншими моддерами, я пропоную замість цього використовувати один із наших центрів спільноти.

Thank you very much.
