### ISSUE TITLE
How i can get icon img from asset

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3598]
I want to use it in the UI. Will I be able to do that?

**Comment by sunnamed434** [comment]
Copy all images from Unturned upload them on some hosting such as GitHub and make public repo, do some naming like (id and file format) 15.png (first aid kit), 363.png (maplestrike), etc, or just stay as it should be, Gazzi have a good example of that on his GitHub repo with all images of Unturned.

**Comment by GazziFX** [comment]
`ItemTool.getIcon` but it may not work on headless server, because it has disabled rendering

**Comment by FANYPLAYRU** [comment]
> Copy all images from Unturned upload them on some hosting such as GitHub and make public repo, do some naming like (id and file format) 15.png (first aid kit), 363.png (maplestrike), etc, or just stay as it should be, Gazzi have a good example of that on his GitHub repo with all images of Unturned.

This don't work for workshop

**Comment by FANYPLAYRU** [comment]
> `ItemTool.getIcon` but it may not work on headless server, because of disabled rendering

Can I use this method to output to the UI?
