### ISSUE TITLE
Level Editor Graphics Menu

### ISSUE THREAD

**Issue by V1CeNtE** [SmartlyDressedGames/Unturned-3.x-Community#36]

**Comment by xdlewisdx** [comment]
Does it not go by ingame settings?

**Comment by V1CeNtE** [comment]
I make changes constantly and sometimes I forget to change them, this implement would save me sometimes. 

If your pc is a potato and you want to use the level editor with 50 fps and you want to make a capture with ultra graphics ... this implement would serve and and you would not waste time.

**Comment by MoltonMontro** [comment]
I feel like Nelson may as well just add full-on graphical presets to the options menu instead then.
