### ISSUE TITLE
Huge RAM problem from 3.25.0.0

### ISSUE THREAD

**Issue by Kast2** [SmartlyDressedGames/Unturned-3.x-Community#360]
Since the 3.25.0.0 update I have noticed a big RAM usage on my Windows 10 laptop.
The game switched to using MAXIMUM 2.5GB RAM on 8GB and 5GB without any reason (see screen). This results in very frequent random freeze and large loss of frame rates.

Screen: https://prnt.sc/k6duid

**Comment by Trojaner25** [comment]
Do you have the same issue if you delete all workshop content and play singleplayer?

This might be caused by servers which are using too much workshop content.

**Comment by N1GHTPATROL** [comment]
• Unsub from all/unneeded workshop content on Steam
• Delete the file "C:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_304930.acf" 
• Delete the folder "C:\Program Files (x86)\Steam\steamapps\workshop\content\304930"

**Comment by Kast2** [comment]
@Trojaner25 I apologise for the late response.
However, the only contents I downloaded are 1 map (of my roleplay server) and a modpack (always of my roleplay that weighs about 1 GB).

We're talking about a laptop with a GTX 1050 and an Intel Core i7-7700HQ. A 3GB increase in RAM seems too much for me to blame the modpack, since before the update the game did not occupy more than 3GB.

**Comment by Kast2** [comment]
@N1GHTPATROL Thank you, I will try the last 2 tips.

**Comment by SDGNelson** [comment]
Did those tips affect the RAM usage? I believe the only memory focused change in that update was making quite a few meshes non-read/writable CPU side which should have reduced usage if anything.

**Comment by Kast2** [comment]
@SDGNelson I tried with the tips, and no one solved the problem.
I would like to point out that I only installed a custom map with a weight of 30MB and a Modpack with a total weight of almost 900MB. These two mods are used by several players and out of about 50 only 2-3 have noticed a disproportionate increase in the use of RAM.

As a result it seems that the problem comes from the game...
