### ISSUE TITLE
Map Updating - Server uses modified version of the map

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3604]
Hi @SDGNelson 
Since recent update whenever a map gets updated and player tries to rejoin the server, with updated map, instead of automatically downloading the updated version an error is displayed
**Server is using modified version of the map**.
The solution to that is deleting map from workshop mods and rejoining. 

It it quite a pain to do, as most players do not know how to deal with that issue.
What has been changed that suddenly that error is caused? 
And most importantly, is it possible to change something Unturned side to avoid having to go through those steps?

**Comment by sunnamed434** [comment]
Unlikely this is my worst issue to describe players how to delete maps from their disks and join the server again. So, also there's one more solution is to re-upload the map to the workshop with a different page. (Do not update the current but create a new one)

**Comment by SDGNelson** [comment]
Is this a custom map? The map version should be changed so that it shows an "this server has version X, you have version Y" message.

**Comment by SmallBerry** [comment]
@SDGNelson 
Apologies for late reply,
It is a France map fix called France 22 (https://steamcommunity.com/sharedfiles/filedetails/?id=2888080297&searchtext=france22) 
I do change the version number in the config.json of the map after each update, however despite that whenever player attempts to join server which runs other version of the map, instead of automatically downloading the updated version players are forced to unsubscribe > re-subscribe in order to join server.
From what I am aware same issue happens (used to happen) on Polaris A6

**Comment by SDGNelson** [comment]
For anyone who comes across it in the future there is now a support article for this error: https://support.smartlydressedgames.com/hc/en-us/articles/12230991951124--This-server-is-using-a-modified-version-of-the-map-

I intend to make this a bit easier in the future.
