### ISSUE TITLE
It is impossible to know what player in the inventory from the server.

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3605]
Please add delegate like:
![image](https://user-images.githubusercontent.com/39222548/209258596-42992afd-22ec-4e0d-a92e-16374e43f8be.png)
So that from the server side you can know if a person has an inventory open.

**Comment by GazziFX** [comment]
Maybe it not work in 100% cases but have you tried `PlayerAnimator.OnGestureChanged_Global` with values `INVENTORY_START`, `INVENTORY_STOP`?

**Comment by surv0013** [comment]
It was also great to have an event that fires when the pause menu [Esc] opens.

**Comment by QERT2002** [comment]
And for ("Open Gestures Menu")button too

**Comment by QERT2002** [comment]
> Maybe it not work in 100% cases but have you tried `PlayerAnimator.OnGestureChanged_Global` with values `INVENTORY_START`, `INVENTORY_STOP`?

I tried, but if player has equipped item it not work.
