### ISSUE TITLE
 Server Lags since the Latest Update

### ISSUE THREAD

**Issue by FiRoX24** [SmartlyDressedGames/Unturned-3.x-Community#3606]
Hello,

Since latest update, my server is having an issue. When someone sells or buys somethings from an NPC's, the server experiences huge ping (ms) spikes. I've seen this happening other servers as well and wanted to know if you know why it's only happening since the latest update.
I've about 30/40 players connected on my server and it becomes unplayable...(big rollbacks)
Here is a video.

Have a good day.

https://user-images.githubusercontent.com/121272775/209262882-d7e3f9c0-6675-47a3-812d-f917e661e1e9.mp4

**Comment by SDGNelson** [comment]
Closing because this was discussed (resolved?) over email.
