### ISSUE TITLE
How to keep the player's experience unchanged after death?

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3607]
I set ` Lose_ Skill_ PvP ` to 1.0 in my config.json. but  the player's experience remains unchanged after the first death,  and the player's experience drops to 50 after the second death, no matter how much experience remains before death. 

I want the player to not lose his experience after he dies, so how to configure the server?

**Comment by GazziFX** [comment]
Did you set `Lose_ Skill_PvE` to 1.0?

**Comment by makeloffve** [comment]
> Did you set `Lose_Skills_PvE` to 1.0?

Yes, `Lose_Skills_PvE: 1.0` in my config.json. does this configuration cause the problem?

**Comment by GazziFX** [comment]
no, maybe some of your plugins doing that?

**Comment by SmallBerry** [comment]
@makeloffve 
It is important to remember the following
If you launched server with settings different than what you mention, player joined and after you changed it to keep skills, then you will need to wipe Players folder for that to apply.
The Lose_Skills is saved per each player in player folder, so if you didnt have it from start changing it wont do a thing.
Gotta wipe players folder
