### ISSUE TITLE
F6 admin editor broken

### ISSUE THREAD

**Issue by kocsisakos** [SmartlyDressedGames/Unturned-3.x-Community#3608]
Due to danaby making some areas a no build zones, i wanted to move some bases out of there. I selected a base 
![image](https://user-images.githubusercontent.com/112898588/209438253-253ef2a2-35d7-47cd-a26b-179fd4613316.png)
but it also selected many bases far from the original base.
![image](https://user-images.githubusercontent.com/112898588/209438305-f274859f-5e84-44a2-931c-37656c641925.png)

**Comment by SDGNelson** [comment]
Hmm that's weird, thanks for the report! Will investigate.

**Comment by SDGNelson** [comment]
My apologies for the long delay between my comment and checking into it.

I tried reproducing this but unfortunately no luck. My first guess was that maybe a test that the selection is in front of the camera was missed, but selecting while looking away from an object seems fine. I tried a few variants of selecting objects in the sky with objects on the ground in surrounding regions, and cancelling the selection in different ways.

Did it happen multiple times? Do you know any trick to reproduce it?

**Comment by kocsisakos** [comment]
I don't moderate for that network anymore so its hard for me to replicate it. I will try to get an older save and make a video of this happening.

**Comment by SDGNelson** [comment]
It happened specific to a save? In that case would it be possible to share the save file? If it can be reproduced on a specific save file then it should be easy to fix! :)

**Comment by kocsisakos** [comment]
It happened multiple times but I know for a fact that I could replicate the bug on the same save.
I've contacted the owner a couple of days ago, but I haven't gotten a response yet.

**Comment by SDGNelson** [comment]
Closing for now, but if there is an update please feel free to comment and I will re-open.
