### ISSUE TITLE
When starting Unturned Via View > Servers > [servername] > Connect, you cannot connect to servers.

### ISSUE THREAD

**Issue by Lolsyoff** [SmartlyDressedGames/Unturned-3.x-Community#3609]
When starting unturned via the "Server Connect" feature, you are not able to connect to servers or view any at all.

1. _Location of Server List_
![image](https://user-images.githubusercontent.com/121456352/209576711-7b34ba42-405a-4ead-995f-1356969d41a8.png)
2. _Server list, and connect button_
![image](https://user-images.githubusercontent.com/121456352/209576767-a131f14d-0ce6-40f3-8952-148d4a79c0cd.png)
3. Result. No server shows on any list
[](url)
![image](https://user-images.githubusercontent.com/121456352/209576878-58f4632c-82f8-4e2d-ae02-bd6404a9e09a.png)

**Comment by Lolsyoff** [comment]
If you have questions, or need a video, message me on discord! --- Luke!#0001
**I recorded a video of exactly what happens, but the file it to large for git to post.

**Comment by sunnamed434** [comment]
Due to your complex search settings, it could affect on it, try to set everything as `ANY` if this is possible, then try to check if this works.

You could upload your video on Google Drive or Youtube or even somewhere else.

**Comment by SDGNelson** [comment]
The way I tested this was:

1. Refresh Steam's old built-in server browser favorites list
2. Connect to an Unturned server
3. Game opened to the server's lobby screen (as expected)
4. Refreshed in-game server browser favorites list
5. Able to join servers normally

Has it still been happening for you? Was something I did different?

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
