### ISSUE TITLE
Creation of a new SteamCall

### ISSUE THREAD

**Issue by AnomolyLove** [SmartlyDressedGames/Unturned-3.x-Community#361]
Currently PlayerLife.askView is client-sided.

I'm requesting you to create a SteamCall for PlayerLife.askView to allow us, developers, to alter the player's vision and hallucination status for creating more unique, gameplay-enhancing plugins.

```c#
[SteamCall]
public void askView(CSteamID steamID, byte amount, ... )

**Comment by ConorJ18** [comment]
I feel like this would be good developers to code new plugins, for example an addition plugin: Getting addicted to things and then have hallucination effect.

This would not only give the game a better chance of being more fun attracting new players to different servers but it also brings out the survival  (RP, PvE) out in the game.

Thanks for Readin👋
Conor

**Comment by SDGNelson** [comment]
Cool ideas! For the next update I've added a public method called sendHallucination in PlayerLife for this purpose.
