### ISSUE TITLE
Server missing asset. Great Hsi-Ku Arsenal mod

### ISSUE THREAD

**Issue by WarmMillk** [SmartlyDressedGames/Unturned-3.x-Community#3610]
I've been at this for like 3 days please help me. I have no idea what the issue is. It only seems to effect items in the file path of Attachments > Sights > Pre attached sights > Generic Sights
I'm out of places to ask about fixing this issue, there are no helpful videos or guides out there to fix it. This is the first mod i've ever run into this issue with, and it only seems to be that one folder from my small testing
Full Error: Server missing asset: "JS 9mm Iron Sight" File: "Iron Sight For Carrying Handle" Id: 85e6333a677a4982a982c4c069192223
I have no mismatches between me and the server i made that is running the mod, disabling VAC and BE did nothing, unsubbing from all the mods and restarting steam still didnt fix the issue either.
framerate sucked in the video for some reason, but it kicks you from the server when you equip the weapon.
https://user-images.githubusercontent.com/96452455/209586599-9872f256-11b0-4c65-9f16-09d759160215.mp4

**Comment by MoltonMontro** [comment]
Are there any errors in the in-game error log available from the main menu?

**Comment by WarmMillk** [comment]
> Are there any errors in the in-game error log available from the main menu?

I'm not sure where you would find this. I've never seen a log available in game anywhere. I just created this log file from the server though.
[Server_HelpMe.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10310850/Server_HelpMe.log)

**Comment by MoltonMontro** [comment]
![image](https://user-images.githubusercontent.com/7608445/209736926-1a030189-df53-4c31-9353-ea83e120a444.png)

**Comment by WarmMillk** [comment]
There are quite a lot of errors in here. Clicking "browse logs" in the top-right corner brings me to this file.
![image](https://user-images.githubusercontent.com/96452455/209737673-b6f9bb93-1504-4537-be78-c1ddcefd4b29.png)

[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10311210/Client.log)

**Comment by MoltonMontro** [comment]
Off the top of my head, this error is meant to catch corrupted GUIDs being sent between the client and server. This kind of error should only be happening due to plugins. Consider disabling your plugins and seeing if you're able to join the server.

**Comment by WarmMillk** [comment]
I had completely removed rocket and its plugins and it didnt fix anything at all, the same issue persisted. i can try setting up a test server with just the mod to see if the same issue persists.

**Comment by WarmMillk** [comment]
the bug still persists even in a test server with 0 plugins but only rocket running, and with only Hsi-Ku Arsenal installed. it only seems to happen for select guns that have sights in that folder, because the other sights work fine.

**Comment by WarmMillk** [comment]
Temporary fix until the mod developer fixes it, i just deleted the folder for both client and server, and every other client has to delete it as well
