### ISSUE TITLE
[Request] Official Config.json Explanation page

### ISSUE THREAD

**Issue by SmallBerry** [SmartlyDressedGames/Unturned-3.x-Community#3613]
@SDGNelson 
Have an official site, page where every part of `config.json` is explained, and it is updated with patches, updates.
I have added my version https://unturned.fandom.com/wiki/User_blog:SmallBerry/Unturned_Server_Config_-_Explained in here, but:
1. Its not official so most people do not find it.
2. I stopped updating it.
3. Would be great to have official updated version, with clear explanations and which is maintained, so that there is no need to create a few blog posts about it, but one clear one, easily findable.

If needed I can volunteer some time to help with it.

**Comment by MoltonMontro** [comment]
Similar information will available from the official U3-Docs repo at some point as part of the server documentation.
