### ISSUE TITLE
Stockpile cosmetic previews are Cyan-colored

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3615]
As far as I could tell, it's just the Arrowhead and Goggly Cap (from [Arid bundles](https://store.steampowered.com/itemstore/304930/detail/1205/)) that have preview images like this, and generating new ones manually from in-game (using my machine) doesn't replicate this issue.

**It looks like the player's body/hair color just hasn't been set before it starts to generate preview images.**

![Arrowhead](https://user-images.githubusercontent.com/7608445/209767667-10285eb4-cf5e-408d-903c-aac58de88b42.png) ![Goggly Cap](https://user-images.githubusercontent.com/7608445/209767696-3a442cc0-bb8f-4856-b8f8-769c9f0a4ab4.png)

_(Minor note: the Goggly Cap intentionally uses the player's hair color.)_

What seems to have happened was that: first cosmetic (Arrowhead) has preview generated, body color is set, second cosmetic (Goggly Cap) has preview image generated, hair color is set, and then the rest of the cosmetics have preview images generated. Maybe a check should be added here, to ensure that these have been set before preview images start being generated.

**Comment by SDGNelson** [comment]
Whoops! Thanks, will fix!

**Comment by SDGNelson** [comment]
As an easy workaround the game renders the character with hair and skin once first so that those materials are good-to-go.
