### ISSUE TITLE
[Bug] LAN Servers Still Require GLST

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3617]
I and some other fellow players have been having issues with connecting to LAN servers if there is no GLST set. At first I figured this was normal, but then I read the 3.22.20.0 Update Notes that mention LAN servers should be unaffected.

Image from another person having this issue:
![image](https://user-images.githubusercontent.com/67397422/209887636-cc791a58-1f50-43b6-9ac1-24a45fb6fda4.png)

**Comment by GazziFX** [comment]
Only these subnets treated as LAN: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16

**Comment by SDGNelson** [comment]
It depends on the address used to connect to the server. If you use the machine's LAN address it does not require GSLT, but if you use your public WAN address it will require GSLT.

**Comment by Kotyarendj** [comment]
My friend tried every IP, WAN and LAN. Nothing works and it just tells about GSLT.

**Comment by Jdance-Media** [comment]
I tested it earlier with attempting to connect to my LAN server via the LAN tab in the server browser. Perhaps this is only an issue there?

**Comment by SDGNelson** [comment]
Interesting, I guess the LAN list is returning your public IP address in that case? I will get this fixed so that joining through the LAN list is always treated as LAN regardless of the IP address. Sorry for the trouble!
