### ISSUE TITLE
[Bug] Mechanic #2 Has Miscolored Wall

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3618]
As shown in the image below, I have reason to believe that this interior wall is miscolored compared to the other interior walls of `Mechanic #2`.

![2022-12-28_14-21-19](https://user-images.githubusercontent.com/67397422/209887908-01fa6612-2121-4e6b-9c66-4de8e4a127cc.png)

**Comment by SDGNelson** [comment]
Literally unplayable!
