### ISSUE TITLE
New player crashing bug

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#362]
Hi Nelson, hack developers have caught on to yet another bug hours after your patch, and have it loaded into hacks they are selling. Further info in DMs.

**Comment by zoomy500** [comment]
we're been compromised, abort mission

**Comment by N1GHTPATROL** [comment]
You have another three weeks before you should expect any changes @zoomy500 so no worries

**Comment by DefCon42** [comment]
execute zulu protocol

**Comment by SDGNelson** [comment]
Curious if any more specific information is available. I'll have to more thoroughly bulletproof some of this packet receiving code, and begin rejecting connections rather than just ignoring packets from spamming senders.
