### ISSUE TITLE
Friends can't connect to my internet server.

### ISSUE THREAD

**Issue by WarmMillk** [SmartlyDressedGames/Unturned-3.x-Community#3620]
It used to work just fine with the router we have, never had to port forward or anything. Once i switched to a repeater so i could actually get better connection, it sarted having issues with unturned. I have it set up for DMZ Host, and port forwarded 27015-16, and it still doesnt work at all. I've yet to be able to figure it out. Its a tenda router.
![image](https://user-images.githubusercontent.com/96452455/209984102-e2d50d9c-7126-4284-8df8-01be19fd8cf0.png)

**Comment by sunnamed434** [comment]
As I understand these friends in IRL have different PCs and are locally connected to your router, so, try to use Hamachi or Radmin VPN to fix it, might look weird to use Hamachi to play locally while everyone is already locally, try :D

You could also try to install Torrent/BitTorrent/QBitTorrent, I suggest QBitTorrent cuz this is open source, and open there your port

**Comment by WarmMillk** [comment]
I've used hamachi before, just heard about radmin vpn last night as well. radmin works fine so we will probably just have to stick to that, although the ping with it seems to be high.

**Comment by sunnamed434** [comment]
Are your friends connected with Wifi or with LAN cable?

**Comment by WarmMillk** [comment]
wifi. nobody is connected to my server from lan besides me

**Comment by GazziFX** [comment]
Why your lan port is 53?

**Comment by SDGNelson** [comment]
IIRC ports under 1000 are reserved - your server's configured LAN port should probably be 27015. Port 53 is for DNS.

**Comment by WarmMillk** [comment]
it just gave me a list of LAN ports with no guide on anything, no guide for looking at what ports to open up tells you what LAN port to use. What would be the recommended one to open the port under then?

**Comment by GazziFX** [comment]
LAN port is what you set in Commands.dat port

**Comment by SDGNelson** [comment]
You should select Manual and enter the same port as your server (27015 and 27016) UDP.
