### ISSUE TITLE
[Feature Request] We need some animation RPCs

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3625]
Hellow Nelson! What do you think about adding a ClientStaticMethod for custom barricade and structure animations? So it will be like this:

```cs
public static readonly ClientInstanceMethod<string> SendPlayAnimation = 
ClientInstanceMethod<string>.Get(typeof(Interactable2), "ReceivePlayAnimation");
```

```cs
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER, deferMode = ENetInvocationDeferMode.Queue)]
public void ReceivePlayAnimation(string clipName)
{
    var animation = GetComponent<Animation>();

    if (animation == null || animation.GetClip(clipName) == null)
    {
        return;
    }

    animation.Play(clipName);
}
```

**Why did I write this code for Interactable2?**
Because "Interactable2SalvageStructure" and "Interactable2SalvageBarricade" implement "Interactable2," it can work for structures and barricades in this way. not just for barricades.

**Are you sure about the code?**
No. I just checked the InteractableDoor class and did the same thing.

**Possible problems**
I'm not really sure, but theoretically it should work with this code.

**Did you test it before posting the code?**
No.

**Comment by fahrettinenes** [comment]
And yeah, we could store the `animation.GetClip(clipName)` as a local variable. I know. I know. I know. I really know.

**Comment by fahrettinenes** [comment]
![image](https://user-images.githubusercontent.com/43903270/210335744-c9b73aa3-f52e-4b26-918a-1c33d0c7ae43.png)
I got a really genius question from Diffoz. He is totally right, can you also add it for objects?

**Comment by GazziFX** [comment]
Why animation clips and not UnityEvent which would be more flexible? You can start animations from events

**Comment by fahrettinenes** [comment]
> Why animation clips and not UnityEvent which would be more flexible? You can start animations from events

ServerArgumentEventModHook would be really cool, but he won't make this event hook until next millennium. RPC will be easier for Nelson.

**Comment by GazziFX** [comment]
Its almost the same work

**Comment by fahrettinenes** [comment]
> Its almost the same work

shrug

**Comment by fahrettinenes** [comment]
@SDGNelson ?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests, and the feature requests are making it less useful in my opinion. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
