### ISSUE TITLE
[Feature Request] Fishing Rod functions

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3626]
Fishing is a great game mechanic, that allows you to relax after all the other activities in Unturned, just like in many other games, and it seems to be acknowledged by curated map teams, as they add custom fishing rods and fishes. But sadly there arent many possibilities for diversity in fishing, as the only thing we can really make is custom fishing rods, each with its own spawntable of fishes. So some changes could be made to make it a bit more interesting:

Unique fish spawn tables for each time and weather and possibly moon stage.
Just like the modhooks that allow us to toggle events if its day or night, or if there's a specific type of weather going on, there could be unique spawn tables for these conditions, allowing creators to add fish, that can be only caught at night, or during rain and e.t.c.

Fishing volumes/Unique fish spawn tables for Water Volumes.
Either a fishing volume, which is an area, when fishing in which, you can catch a special fish, or a setting for water volumes, so that when fishing in a specific water volume, you can catch a special fish.

Fishing Rod Durability
The ability to make fishing rods loose durability and break over time, just like the melee weapons and guns.

Bait?
This suggestion is probably a lot harder to make than the other ones, but I think it still might be possible. The ability to choose bait for your fishing rod in a circular menu, just like the gun attachments menu or housing planner, would be very nice, although that might be too much.
But the first three suggestions are pretty possible to make, in my opinion.

**Comment by olberturned** [comment]
best feature request ever

**Comment by Jdance-Media** [comment]
Would be nice to have a `FishingAsset` which uses the Assets v2 setup. This asset could have those time, weather, and full moon properties alongside with the unique spawn table values. Fisher item assets could have a `FishingAsset` line to specify the FishingAsset and water volumes could have an input to specify the FishingAsset. You could then add a `Should_Override_Water_Volumes <bool>` line to the Fisher item so modders can still make their rods override those properties.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
