### ISSUE TITLE
Fences de-render too fast. But some do not

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3629]
This also happens with vanilla fences
https://www.youtube.com/watch?v=3tcTfdlYj10
![image](https://user-images.githubusercontent.com/101991669/210786325-d2c5a98d-8401-408f-9cb3-7d2ec9a6faae.png)
it can't be a model LOD issue as the backside fences do not dissapear.

**Comment by GazziFX** [comment]
Video not available

**Comment by UsernameIsUnavailible** [comment]
Does this new URL Work?
https://www.youtube.com/watch?v=3tcTfdlYj10
(edited it my original post too)

**Comment by UsernameIsUnavailible** [comment]
How can it be a LOD Issue though? Fences at the back do not dissapear whilst the ones near the warehouses do

**Comment by SDGNelson** [comment]
It's confusingly named. The .dat "LOD" option is for disabling objects "inside", not related to the LODGroup component.
