### ISSUE TITLE
Adding bots to the server

### ISSUE THREAD

**Issue by LUTIY-KIBER** [SmartlyDressedGames/Unturned-3.x-Community#3630]
I am a coder in Rocket, I noticed that after some kind of update, artificially created plugin players log on to the server, but they do not spawn. Can you tell me what to do? We know about the policy that online cheating is prohibited. But we do this for personal testing purposes, in order to write intelligence to them. So that they run, shoot

**Comment by fahrettinenes** [comment]
Are you talking about this plugin? or is it custom one?
*http://imperialplugins.com/Unturned/Products/AI-Bots*
