### ISSUE TITLE
Attaching a different caliber to a different location

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3632]
I need to make a laser sight with a different caliber, attached to a different place on the weapon. How do I do this?

**Comment by GazziFX** [comment]
You need to move tactical slot on that weapons

**Comment by JorelDecker** [comment]
> You need to move tactical slot on that weapons

You don't understand what I need. I need a laser sight with a caliber of "1" to be attached to point 1. and a laser sight with a caliber of "2" to point 2.

**Comment by GazziFX** [comment]
Its not possible

**Comment by DerpyHoowes** [comment]
It is possible with magazines, so perhaps its possible with other attachments too.
