### ISSUE TITLE
[Bug Report] Selecting a button in objects tab doesn't register always.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3633]
https://user-images.githubusercontent.com/67397422/211210409-86abd971-6e83-42e3-b8f1-26b9ad9400a0.mp4

In the provided video clip, selecting a different object to place (in this case "Bulldozer") doesn't always register.

**Comment by SDGNelson** [comment]
It looks like you are releasing the mouse press after exiting the button? The buttons are "down and up" so the mouse release needs to happen while over the button.

**Comment by Jdance-Media** [comment]
I might have done that once in the recording. After further testing, this issue still occurs when pressing the mouse, dragging it while staying within the button, and releasing it.

**Comment by SDGNelson** [comment]
Ah: it looks like the scrollview handles the click and drag so you can move the list without the scrollbar. If you click the button without moving your mouse it selects the object.
