### ISSUE TITLE
NET Standard API compatibility level

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3637]
Unity planning upgrade to NET 6, switching to NET Standard will ensure a smooth migration of plugins, and fix some issues with external packages. Old plugins should still work https://docs.unity3d.com/Manual/dotnetProfileSupport.html. Its a bit tricky way to reference assemblies in Visual Studio if you targeting NET Standard but I think its acceptable

**Comment by GazziFX** [comment]
New plugins can be compiled using NET Standard 2.0 and NET Framework 4.7.2+ targets

**Comment by SDGNelson** [comment]
Maybe, will see after eventual update to a Unity version that supports it.
