### ISSUE TITLE
Big disconnect of players

### ISSUE THREAD

**Issue by blackdatet** [SmartlyDressedGames/Unturned-3.x-Community#3646]
Suddenly all the server players were disconnected, in the game errors I found only
 [2023-01-14 15:19:58] BattlEye Print: Failed to receive from BE Master (0)
 [2023-01-14 15:19:58] BattlEye Print: Disconnected from BE Master
 
 
![image](https://user-images.githubusercontent.com/74265225/212472105-d5433e68-c625-4be6-a12e-d27b0f37cffc.png)

**Comment by GazziFX** [comment]
It means your server lost connection not only to players

**Comment by SDGNelson** [comment]
Can you attach the U3DS/Logs Server_ (id) .log file please? There may be more context.
https://support.smartlydressedgames.com/hc/en-us/articles/12298951221908-Where-are-the-dedicated-server-log-files-

**Comment by blackdatet** [comment]
Unfortunately, no more than 2 logs are stored in "U3DS/Logs Server_ (id) .log". Logs have already been deleted

But, there was nothing in them except these two sentences
![image](https://user-images.githubusercontent.com/74265225/212559740-78c863a6-4ab0-41f4-b433-d667bbf753d2.png)

**Comment by SDGNelson** [comment]
The second log screenshot message "after graceful disconnect message" suggests all of the clients requested disconnect (i.e., they did not timeout / lose connection), so after BattlEye lost connection it probably told them to disconnect.
