### ISSUE TITLE
Homing Missile

### ISSUE THREAD

**Issue by L0rdL0ther** [SmartlyDressedGames/Unturned-3.x-Community#3647]
hello, I've been trying to make a rocket following the camera for almost 1 month. I tried every method, I created and tried more than 200 dlls, but I couldn't reach a result, can you help me please?

**Comment by GazziFX** [comment]
https://github.com/UncreatedStaff/UncreatedWarfare/blob/be1bc2e594acbaef8928011a94c47d7e99128b22/UncreatedWarfare/Components/GuidedMissileComponent.cs

**Comment by L0rdL0ther** [comment]
ty

**Comment by GazziFX** [comment]
Close issue?
