### ISSUE TITLE
Error while editing map

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3649]
Hello!

I'm having a problem with a map I'm editing. I saved the progress, but when I tried to go to the map again, I could not do it. Interrupts the eternal loading of the map.

Please, help.

Sent a copy of the map and logs to your mail.
Email subject: Error while editing the map (Svyatoslav)

Sincerely,
Svyatoslav

**Comment by SDGNelson** [comment]
Replying to the email momentarily.
