### ISSUE TITLE
Generator Example

### ISSUE THREAD

**Issue by ImIveooo** [SmartlyDressedGames/Unturned-3.x-Community#365]

**Comment by MoltonMontro** [comment]
Not that it wouldn't hurt to have one, but I don't believe there's anything unique about generators that'd warrant it (when you can use one of the other barricade examples instead already).

**Comment by SDGNelson** [comment]
For the next update I've included the small generator files.

They are very similar to others, but it looks like the radius effect is actually part of the generator right now (should be instantiated elsewhere) so for the moment those shaders have to be included when creating custom ones.
