### ISSUE TITLE
Allow creation of new items using its guid

### ISSUE THREAD

**Issue by negrifelipe** [SmartlyDressedGames/Unturned-3.x-Community#3655]
Hi, currently if you want to create an item you have to use it's ushort id so it would be cool to be able to create them using the guid and also to get the guid from an existing item without having to fetch the asset using the ushort id

**Comment by GazziFX** [comment]
I think it wont be until inventory rewrite https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2990#issuecomment-1013532588

**Comment by SDGNelson** [comment]
GazziFX is correct

**Comment by GazziFX** [comment]
Any ETA or roadmap on rewrite? You can create issue with checkboxes

**Comment by MoltonMontro** [comment]
Nelson discussed the inventory rewrite a couple times last month, in a video. Mostly offhandedly, but this is the most relevant clip: https://youtu.be/Dxj4Z5ha9Eo?t=5040 (**1:24:00** – **1:25:59**)
