### ISSUE TITLE
Preview branch changelogs

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#3656]
Going forward the changes in current preview branch versions will be published here:

https://support.smartlydressedgames.com/hc/en-us/articles/12462494977172

There is also a link on the main menu to that page. :)

**Comment by MoltonMontro** [comment]
A similar news post has been made in our other communities. Notably: this Twitter thread already has some [feedback/reports](https://twitter.com/MoltonMontro/status/1615917346144526337), and a [forum post](https://forum.smartlydressedgames.com/t/preview-branch-changelogs/22012/2) is scheduled to go live a little bit later today.
