### ISSUE TITLE
Using an empty method in the game code?

### ISSUE THREAD

**Issue by 0x646F317068696E3732** [SmartlyDressedGames/Unturned-3.x-Community#3657]
![image](https://user-images.githubusercontent.com/108773646/213868251-28dfa66d-0446-4f6c-b1ad-457c0d8e21b2.png)
![image](https://user-images.githubusercontent.com/108773646/213868316-c49de9c4-c526-4ae4-b5e0-7efc21b099b4.png)
![image](https://user-images.githubusercontent.com/108773646/213868343-8ec4aace-24bf-4a48-9f56-dadb9fc71893.png)

**Comment by GazziFX** [comment]
Are you inspecting dedicated server dlls?
![image](https://user-images.githubusercontent.com/43498426/213868573-526ff61b-f45e-4fa6-b11c-4a2517ce289b.png)

**Comment by sunnamed434** [comment]
Perhaps you're trying to use dedicated server DLLs, as @GazziFX mentioned, and use files from the installed game if you want. Sometimes I'm using dedicated server files because I don't need to see the client code and just server-side
