### ISSUE TITLE
InternetServer doesn't work

### ISSUE THREAD

**Issue by chinxddd** [SmartlyDressedGames/Unturned-3.x-Community#3658]
Every time I try to use +InternetServer/Server it doesn't work and set everything as default, but when I try to do +LANServer/Server it does work pretty well, please fix this bug.

**Comment by SDGNelson** [comment]
Could you attach the log file after trying to use +InternetServer please? https://support.smartlydressedgames.com/hc/en-us/articles/12298951221908-Where-are-the-dedicated-server-log-files-

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I will re-open.
