### ISSUE TITLE
add new new function

### ISSUE THREAD

**Issue by TNTNUBERONE** [SmartlyDressedGames/Unturned-3.x-Community#3659]
Hello dear Nelson, please add the ability to call the user interface panel and change the text through the plugin code.

This is:
public void sendMessage(EPlayerMessage message)

On 
public void sendMessage(EPlayerMessage message, string text)

**Comment by GazziFX** [comment]
Duplicate of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions/3651
Also for ideas use discussions

**Comment by MoltonMontro** [comment]
GazziFX is correct – this repository is intended for reporting issues. Things like feature requests / ideas shouldn't be posted here. You could use the Discussions area instead, or post them onto our [official forums](https://forum.smartlydressedgames.com/).
