### ISSUE TITLE
Internet issues on launch!

### ISSUE THREAD

**Issue by TurtleTull** [SmartlyDressedGames/Unturned-3.x-Community#3661]
Whenever I run Unturned and get into the main menu, my internet slows to such an extreme point I can't do anything! It was running fine yesterday, any ideas on what is it or that I could do?

**Comment by SDGNelson** [comment]
What do you mean by your internet slows? Are you doing something in the background that requires internet traffic? By default the main menu shouldn't be making many network requests after startup.

**Comment by TurtleTull** [comment]
I was running Opera Gaming in the background, which seems to be causing the
issue, sorry for worrying you and thank you for responding! Keep up the
good work!

**Comment by SDGNelson** [comment]
Thanks, glad to hear you got it sorted out!
