### ISSUE TITLE
[Possible bug] Engineer Skills

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#3663]
Engineer skills says "Makeshift items, basic items, complex items" but no makeshift item requires the skill.
![image](https://user-images.githubusercontent.com/34221626/214466680-bdbd8813-95a9-4106-a5a0-a07717bad1b9.png)
![image](https://user-images.githubusercontent.com/34221626/214466727-00ecca7c-808c-46c6-9f25-9cb94040139d.png)
![image](https://user-images.githubusercontent.com/34221626/214466781-98ac8d8a-a0b2-4395-b178-09631a5bfa32.png)

**Comment by Jarshoowas** [comment]
Surprising, also why isnt there an option to require different skills for blueprints? The current list of skills that you can require for a blueprint is too limited 

Current list of skills you can require for a blueprint: 
Cook , Craft , None and Repair

**Comment by SDGNelson** [comment]
I'm not sure I understand what you mean. In the screenshot it shows those items require the skill?

**Comment by Jarshoowas** [comment]
It says it requires crafting but engineer, isnt the engineer skill supposed to reveal new blueprints?

**Comment by SDGNelson** [comment]
Ah, thanks Jarshoowas, to clarify: Engineering is required for repairing certain items. I double-checked and the vanilla items requiring the skill are:
```
Repairing Makeshift Muffler requires Engineering level 1
Repairing Military Muzzle requires Engineering level 2
Repairing Military Suppressor requires Engineering level 2
Repairing Ranger Muzzle requires Engineering level 1
Repairing Ranger Suppressor requires Engineering level 1
Repairing Augewehr requires Engineering level 1
Repairing Devil's Bane requires Engineering level 1
Repairing Calling Card requires Engineering level 1
Repairing Desert Falcon requires Engineering level 2
Repairing Dragonfang requires Engineering level 2
Repairing Eaglefire requires Engineering level 2
Repairing Ekho requires Engineering level 1
Repairing Empire requires Engineering level 1
Repairing Hell's Fury requires Engineering level 3
Repairing Fusilaut requires Engineering level 1
Repairing Grizzly requires Engineering level 2
Repairing Heartbreaker requires Engineering level 2
Repairing PDW requires Engineering level 2
Repairing Rocket Launcher requires Engineering level 3
Repairing Maplestrike requires Engineering level 2
Repairing Matamorez requires Engineering level 1
Repairing Maschinengewehr requires Engineering level 1
Repairing Nightraider requires Engineering level 1
Repairing Nykorev requires Engineering level 1
Repairing Peacemaker requires Engineering level 2
Repairing Sabertooth requires Engineering level 1
Repairing Shadowstalker requires Engineering level 3
Repairing Snayperskya requires Engineering level 1
Repairing Swissgewehr requires Engineering level 2
Repairing Timberwolf requires Engineering level 2
Repairing Viper requires Engineering level 2
Repairing Vonya requires Engineering level 1
Repairing Yuri requires Engineering level 2
Repairing Zubeknakov requires Engineering level 1
```
Skills/crafting are definitely some of the underdeveloped areas of the game that deserve fleshing out someday.
