### ISSUE TITLE
[NPC bug] Full moon

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#3664]
NPC's condition "fullmoon" is not working when a plugin set the full moon.

**Comment by educatalan02** [comment]
Yes, the plugin just set LightingManager.isFullMoon to true

**Comment by SDGNelson** [comment]
In that case the plugin should be setting the time of day directly. I should probably add some helper methods for setting time to certain presets.

**Comment by educatalan02** [comment]
Alright, thanks you for the quick response.
