### ISSUE TITLE
Invisible barricades and some objects

### ISSUE THREAD

**Issue by nikiternak5269** [SmartlyDressedGames/Unturned-3.x-Community#3666]
Who has lost doors on the server after the update and some buildings have become invisible? How to solve it. After all, if you put the same barricades again, they will be visible.
P.s it is impossible to pass through invisible objects

**Comment by Pioneerkin1337** [comment]
https://youtu.be/LP9C3NaHbTg

**Comment by SDGNelson** [comment]
Is your issue the same as in the video? It looks like the barricade loaded on the server but not on the client. If you can attach the client and server logs maybe there is an error?

**Comment by Pioneerkin1337** [comment]
[Server_zSandBoxGrand.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10522934/Server_zSandBoxGrand.log)

**Comment by Pioneerkin1337** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10522937/Client.log)

**Comment by Pioneerkin1337** [comment]
The problem is as in the video, the client and the server have these barricades, in some houses the objects were preserved after the update, and in some they turned into transparent ones.

**Comment by Pioneerkin1337** [comment]
> Is your issue the same as in the video? It looks like the barricade loaded on the server but not on the client. If you can attach the client and server logs maybe there is an error?

The server and client logs are attached above

**Comment by Pioneerkin1337** [comment]
> Is your issue the same as in the video? It looks like the barricade loaded on the server but not on the client. If you can attach the client and server logs maybe there is an error?

Reinstalling modifications for clients and servers does not help. Trying to publish a new modification didn't help either

**Comment by SDGNelson** [comment]
It looks like the problem might be the "HorseManager" plugin. There is an exception thrown related to barricades with a HorseManager callstack during movement.

**Comment by Pioneerkin1337** [comment]
> It looks like the problem might be the "HorseManager" plugin. There is an exception thrown related to barricades with a HorseManager callstack during movement.
[Server_zSandBoxGrand.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10523372/Server_zSandBoxGrand.log)

**Comment by Pioneerkin1337** [comment]
> It looks like the problem might be the "HorseManager" plugin. There is an exception thrown related to barricades with a HorseManager callstack during movement.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10523379/Client.log)

**Comment by Pioneerkin1337** [comment]
> It looks like the problem might be the "HorseManager" plugin. There is an exception thrown related to barricades with a HorseManager callstack during movement.

The server was started without plugins, a game error is issued

**Comment by Pioneerkin1337** [comment]
> It looks like the problem might be the "HorseManager" plugin. There is an exception thrown related to barricades with a HorseManager callstack during movement.

Fix game issue plz

**Comment by SDGNelson** [comment]
Unfortunately it looks like the barricade state[] array might be corrupted. Do you have a backup of the server's savedata (in particular Barricades.dat) from before this error?

**Comment by Pioneerkin1337** [comment]
> 

There is no backup

> Unfortunately it looks like the barricade state[] array might be corrupted. Do you have a backup of the server's savedata (in particular Barricades.dat) from before this error?

**Comment by SDGNelson** [comment]
In that case the only option would be deleting Barricades.dat, sorry. :(
