### ISSUE TITLE
After the update, the keychains started to fall down.

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3667]
We had keyfobs on the server that were made as a tactical element. It was made using Hinge Joint. The physics worked fine, but after the update, the part of the keychain that had the Hinge Join component just started to fall down. Commands Destroy_Attachment_Colliders 
and Destroy_Item_Colliders don't help
![image](https://user-images.githubusercontent.com/83378019/215182135-9da21dc5-30fa-4007-a0d5-92b1e86285fb.png)

**Comment by SDGNelson** [comment]
Is the hinge joint in Item.prefab or in the Tactical.prefab?

If in the Item.prefab:
Destroy_Item_Colliders false

If in the Tactical.prefab:
Destroy_Attachment_Colliders false

When you tried did it have the false value?

**Comment by JorelDecker** [comment]
> 



> Is the hinge joint in Item.prefab or in the Tactical.prefab?
> 
> If in the Item.prefab: Destroy_Item_Colliders false
> 
> If in the Tactical.prefab: Destroy_Attachment_Colliders false
> 
> When you tried did it have the false value?

I used both the value on both item and tactical. The keychain it self is made as tactical. 
Below I attach a screenshot of all settings
![image](https://user-images.githubusercontent.com/83378019/215216052-32b27851-a060-4e2f-83bb-b63d76664c30.png)
![image](https://user-images.githubusercontent.com/83378019/215216432-3b802759-24a5-4b29-84ed-585ed153c3f1.png)
![image](https://user-images.githubusercontent.com/83378019/215216448-828fb77a-2b97-48cc-b9e3-7579c7a97011.png)
![image](https://user-images.githubusercontent.com/83378019/215216472-90057c81-abef-4ce6-a140-b23090d9e076.png)

**Comment by JorelDecker** [comment]
If you switch to third-person mode, the keychain appears in random places
![image](https://user-images.githubusercontent.com/83378019/215218108-fd43ec80-2947-44b2-9e00-6ef7415a08d2.png)
![image](https://user-images.githubusercontent.com/83378019/215218151-0f766f52-313c-46fd-8d49-6d085cd022f0.png)

**Comment by SDGNelson** [comment]
Could you send the example mod please? I can give it a try

**Comment by JorelDecker** [comment]
When I put Hinge Joint on Tactical and set its kinematics, it fixed the situation. But I believe that this should not be the case, and it should have worked as before.
![image](https://user-images.githubusercontent.com/83378019/215220197-21c2131f-43ab-40a3-b4e1-f79c3e6bd13b.png)

**Comment by JorelDecker** [comment]
> Could you send the example mod please? I can give it a try

I'm sending you an example by gmail

**Comment by SDGNelson** [comment]
Sorry, to clarify: could you send me the previously working version please? i.e., the .dat and .unity3d files. I will try loading up the old version with the same config as you to figure out why it didn't behave the same as before.

**Comment by JorelDecker** [comment]
[TestBrel.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10523865/TestBrel.zip)
This is the version of the keychain that worked before the update, but doesn't work now.

> Sorry, to clarify: could you send me the previously working version please? i.e., the .dat and .unity3d files. I will try loading up the old version with the same config as you to figure out why it didn't behave the same as before.

**Comment by SDGNelson** [comment]
Thanks for the example file!
Did one of the joints depend on the Rigidbody on the attachment's Tactical prefab? There were some inconsistencies in which prefabs had their Rigidbody cleaned up and this update fixed those and removed them from all vanilla prefabs. Another alternative might be to put the Rigidbody as a child of the attachment's Tactical prefab.

**Comment by JorelDecker** [comment]
> Thanks for the example file! Did one of the joints depend on the Rigidbody on the attachment's Tactical prefab? There were some inconsistencies in which prefabs had their Rigidbody cleaned up and this update fixed those and removed them from all vanilla prefabs. Another alternative might be to put the Rigidbody as a child of the attachment's Tactical prefab.

Thank you for your clarification, in any case, the option above repairs everything, so the question is exhausted. Thank you for your time.
