### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by IWSProject** [SmartlyDressedGames/Unturned-3.x-Community#3668]
When Unturned were updated - all players have this problem:
![image](https://user-images.githubusercontent.com/123774921/215192383-6a0e4695-d5ec-419b-b728-12e1313ca2b5.png)

**Comment by SDGNelson** [comment]
I have now posted an article explaining the most likely reason: https://support.smartlydressedgames.com/hc/en-us/articles/12733613923092

**Comment by SDGNelson** [comment]
The .1 patch has changed it to only validate objects prior to the legacy ID fallback so it shouldn't be kicking, but fixing the underlying problem is highly recommended because otherwise players can modify those objects.
