### ISSUE TITLE
Large list of first person view issues

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3677]
(bad english notice, hehe) Has been a long time since I noticed all this visual problems and seems that nobody has talked about how annoying they are. All of this issues happens on first person view and also affects how other ones see you. I'm pretty sure this is why first person view is still not used as much as third view person, and maybe fixing/improving it will make more people create servers with only first person view

### 1. Jumping while aiming
While aiming, you can notice the center/dot and where shots will go

![2023-01-31_13-49-47](https://user-images.githubusercontent.com/57012631/215849554-f0191c96-f82c-4a8f-bdd3-ba8a2de7526f.png)

But if you jump while aiming, you can see how the center/dot stays on center, but the view model of the gun also jump, making it not visible the center/dot

![2023-01-31_13-49-51](https://user-images.githubusercontent.com/57012631/215849779-1fc800df-4698-4c4d-874d-f6d0fecdaef7.png)

### 2. Leaning to sides while prone
When leaning while prone you can notice how your head moves/rotates like 45 degrees in first person

![2023-01-31_13-51-17](https://user-images.githubusercontent.com/57012631/215850138-f10d1d1e-8a5b-4b2d-8765-6271507b071b.png)

![2023-01-31_13-51-20](https://user-images.githubusercontent.com/57012631/215850165-00a5e923-19f2-4f7a-83b9-93ec3d48ba6e.png)

But on third persons your character actually is stretched to left or right, making it way lot visible for enemies, where actually you can barely see because you're not stretching on first person view, you're just rotating

![2023-01-31_13-51-49](https://user-images.githubusercontent.com/57012631/215850271-d3d75564-efc7-4b2e-b94a-4c0171ecd65d.png)

![2023-01-31_13-51-57](https://user-images.githubusercontent.com/57012631/215850304-6d719713-166b-41bb-ae5c-ab0817114e0c.png)

![2023-01-31_13-52-41](https://user-images.githubusercontent.com/57012631/215850329-34c9fb10-cc29-4286-ba40-32e7fa4abae4.png)

### 3. Viewing while prone
While you're prone, you can barely see something (for not saying that you can see nothing)

![2023-01-31_13-54-07](https://user-images.githubusercontent.com/57012631/215850921-08d78685-dc75-4237-b9be-c1724ae735cd.png)

But others actually can even see your eyes and your whole head, making you way lot visible rather than the actual way you can see others

![2023-01-31_13-54-25](https://user-images.githubusercontent.com/57012631/215850997-d903ef63-a8d3-46ee-a1a4-6e4e0ca76963.png)

### 4. Wrong views when stand up, crouch and prone
The pictures speaks by themselves, but blue is your first person view vs red is how your character model is actually showed. The first person view should actually move along with the character model (Y pos/front/back) and not just in Y pos

![2023-01-31_13-59-19](https://user-images.githubusercontent.com/57012631/215852519-d912583d-9a7c-4eb1-a2d6-43fdc8d5b715.png)

![2023-01-31_13-59-23](https://user-images.githubusercontent.com/57012631/215852534-40a2d6b5-b6c8-43bc-9245-0ee7d1d10d08.png)

![2023-01-31_13-59-33](https://user-images.githubusercontent.com/57012631/215852557-bc2ec09d-233a-45ae-9c7f-2b5fb70e31af.png)

### 5. Disparity between aims on first/third person views
Something that happens when aiming constantly on first/third person, you can notice how bullets aren't actually shot where you want, and here you have some examples of this issue. On this picture I'm shooting on first person while leaning right and those bullets goes to the fences

![2023-01-31_13-56-52](https://user-images.githubusercontent.com/57012631/215853198-9d1da600-bf9b-4b41-994e-3c1a34423242.png)

But if I change to third person view, those bullets will go to the wall. This issue is actually very annoying and happens constantly when fighting zombies 

![2023-01-31_13-57-04](https://user-images.githubusercontent.com/57012631/215853454-248f3bb5-c04e-4e78-ac6b-eb46d197603f.png)

Here you have another example from a friend

![image](https://user-images.githubusercontent.com/57012631/215859755-0f1c4d2a-326b-4eb0-8c24-7d06392195e8.png)

![image](https://user-images.githubusercontent.com/57012631/215859775-ebc666f3-e73c-4c51-9652-5cb681c319aa.png)

**Comment by diddlyono** [comment]
these are mostly animation issues, and not view issues.
besides, any attempt to fix these could go catastrophically wrong, example: how are you supposed to fix 4? center the characters head and make the torso slide back in the animation?

its just unturned things tbh, really just about getting used to it if you havent already.

**Comment by SDGNelson** [comment]
Thanks for the report, however these are all intentional-ish, but to clarify a couple points:
- The third-person aiming different is because it shoots towards your where your 2D crosshair intersects the world, otherwise it would be impossible to shoot in third-person. (all third-person games do this)
- Some of the desyncs between first and third person head placement would ideally be ironed out in a future character animation remaster / revamp.
