### ISSUE TITLE
Belgian Poacher Bundle description is incorrect

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3678]
The [Belgian Poacher Bundle](https://store.steampowered.com/itemstore/304930/detail/997/)'s description is incorrect. It seems to have been copy-pasted from the [Belgian Infantry Bundle](https://store.steampowered.com/itemstore/304930/detail/984/) and accidentally left unchanged.

Currently, it's: `Kit for mid-1800s historical re-enactment.`

Based on the Belgian Poacher Bundle's contents, it was most likely intended to be: `Blackmarket utilities for blackmarket work.` instead. This is the description shared by all of its contents.

**Comment by SDGNelson** [comment]
Whoops, thanks! You're right that it must have been copy-pasted without changing. Will fix!

**Comment by SDGNelson** [comment]
Thanks! The item description was updated, but the Steam item definitions weren't. I've now re-exported and uploaded those but it won't take effect until Steam's cache refreshes.
