### ISSUE TITLE
Corrosive Eaglefire has incorrect Emission Intensity on Attachment Material

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#3680]
_(or vice versa, main body may have incorrect emission intensity, but judging from the pic on the inventory, its the attachment)_

i noticed while playing on my steamdeck that the **Corrosive Eaglefire** skin that my alt equipped was using two different shades of green for the skin. all of the attachments put on the gun were visually brighter than the gun itself. if i had to guess, this is simply that the attachment material has its intensity incorrectly set, or, the skin was brightened in an update but only one material was changed, _imo i think the brighter green looks better but thats because i like bright flashy skins :)_

![Screenshot_122](https://user-images.githubusercontent.com/67235885/215901886-c82ce6cd-21d3-42c5-8b7d-21aeda0b6ab0.png)
heres the skin in first person with a zoom in on the scope and base, very clearly contrasting shades

![Screenshot_119](https://user-images.githubusercontent.com/67235885/215901934-a2f3da36-56cc-407a-93b0-db570026e9f1.png)
once again, but showing it in third person, with a direct comparison between the shades of green

![Screenshot_120](https://user-images.githubusercontent.com/67235885/215901982-a4bff114-82d3-480d-b558-93d7eae2c3ed.png)
and the clearest look, on a rifle rack. notice how this also affects the iron sights, despite not affecting them in the economy icon.

![Screenshot_123](https://user-images.githubusercontent.com/67235885/215902100-fbc3adcd-8bda-4e5c-901c-6a505e8d75a0.png)
once again in first person, however with a direct comparison of the greens

![Screenshot_124](https://user-images.githubusercontent.com/67235885/215902154-50e41e3b-b88e-4530-bde3-95fb9f4ddf3e.png)
and one more, on a rifle rack, where it is very visible that the irons, vertical grip and military magazine are brighter than the gun itself.

_i spent £0.14 on this skin to report this lmao_

**Comment by SDGNelson** [comment]
Thanks for the report! Looks like this affects a variety of skins. Will fix for the next update.
