### ISSUE TITLE
How can i use VideoPlayer

### ISSUE THREAD

**Issue by Efemd** [SmartlyDressedGames/Unturned-3.x-Community#3682]
i tried but it didn't work

![asd](https://user-images.githubusercontent.com/95052851/216717021-98b80b6e-6573-4ca1-86b7-9c2d63bf87a8.png)

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3549#issuecomment-1344604545

**Comment by GazziFX** [comment]
Try to set loop or disable gameobject by default and then enable it in plugin

**Comment by Efemd** [comment]
> Try to set loop or disable gameobject by default and then enable it in plugin

I think I failed can you give an example of this?
Are you sure the Video Player is working? Have you tried this?

**Comment by GazziFX** [comment]
Tried when videoplayer was fixed and it worked for me

**Comment by GazziFX** [comment]
[UnityPackage](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10609397/video.zip)
![video](https://user-images.githubusercontent.com/43498426/216784196-58acec1d-6340-4a38-8b55-eef69ae1602b.jpg)

**Comment by Efemd** [comment]
The effect file you sent did not work, can you tell me what to do with the plugin?

**Comment by Efemd** [comment]
> [UnityPackage](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10609397/video.zip) ![video](https://user-images.githubusercontent.com/43498426/216784196-58acec1d-6340-4a38-8b55-eef69ae1602b.jpg)

the video is so funny asdlşkasşldkasşldkşasödşlasökdşlaskdasşas

**Comment by sunnamed434** [comment]
> [UnityPackage](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/10609397/video.zip) ![video](https://user-images.githubusercontent.com/43498426/216784196-58acec1d-6340-4a38-8b55-eef69ae1602b.jpg)

Halo is the best👍

**Comment by Efemd** [comment]
Thank you GazziFX for helping me <3
