### ISSUE TITLE
Too many Unturned Cheats on the GitHub

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3684]
Hello, I want to tell you something that harasses me too much. When I search for something related to Unturned on GitHub, I see too many cheats, etc.. and most of them are working codes and new. (here is a live example: https://github.com/NurdAlert/unburned/ , they even have a bypass). Are you planning to do something about these cheats? Maybe you can try to take down these repositories because I don't think people are publishing these repositories for educational purposes :D

**Comment by fahrettinenes** [comment]
Hey, also I suggest fixing this repository quickly because the repository owner is publishing his cheat as built to players. https://github.com/https://github.com/NurdAlert/unburned/

**Comment by realtrollman2319** [comment]
These probably don't work and just free ways to get banned

**Comment by SDGNelson** [comment]
Compiling/using them should result in a BattlEye ban. I will forward the report of this one just in case, thanks for the report! I haven't tried taking down repos on GitHub before though. Closing the issue to remove the link from the list.
