### ISSUE TITLE
Shield clip bad working

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3685]
![image](https://user-images.githubusercontent.com/83378019/216778646-29d9c75f-38d3-4b74-bb2d-933e867dd88b.png)
I created the shield as a generator. In a single player game, the shield reacts to blows, but on the server, the shield does not react to shots. He slows down the player, does not let him pass, but it is impossible to damage him

**Comment by Gamingtoday093** [comment]
Something is wrong with your Clip gameobject

**Comment by SDGNelson** [comment]
Do you have Has_Clip_Prefab false? If not, it may be worth adding so that the server uses the same prefab as the client. (same suggestion as Gamingtoday093)

**Comment by GazziFX** [comment]
If you have colliders inside "Engine" GameObject it might not work on server because it was created only for clientside visuals

**Comment by JorelDecker** [comment]
OK, thank you all, I solved the problem using a different configuration.
