### ISSUE TITLE
Perhaps some performance optimization is needed.

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#3690]
When will U3DS support CPU multi-core processing?
At present, I see that dedicated servers have very high requirements for CPU single-core performance, so that we have to use expensive Intel 13900K as servers.

**Comment by GazziFX** [comment]
I think you doing something wrong, we have AMD Ryzen 9 5900X it easily handles 5 unturned servers (a lot of mods and plugins, 90-110 players + 20 AI bots), 1 minecraft server, several databases, web server, and have only 20-30% CPU utilization

**Comment by GazziFX** [comment]
I have one idea for optimization, but didnt tested yet. Organize animals, zombies and players into systems, to reduce P/Invoke calls overhead per entity

**Comment by SDGNelson** [comment]
The next multi-threading related improvement I have on the to-do is .dat reading + parsing on a separate thread.

GazziFX I did actually try that (e.g., updating all vehicles directly rather than InteractableVehicle.Update) but the performance difference was minuscule.
