### ISSUE TITLE
Make semi-automatic mode faster/more responsive

### ISSUE THREAD

**Issue by benvalkin** [SmartlyDressedGames/Unturned-3.x-Community#3691]
I haven't checked the code that causes this myself, but I believe it may have been mentioned here - #3361

Firing on semi-automatic has always felt extremely sluggish because of the unexpectedly long and inconsistent time between shots (which feels like somewhere between 0.2 and 0.5 seconds). Many players in multiplayer don't even use semi-auto/semi-only weapons, because no matter the gun asset's configured fire rate, semi-auto is just too slow and can't compete with full-auto weapons. It would be great if semi-auto was faster and more responsive to mouse clicks like in other FPS games.

If this is intentional, it would be nice to know why it was implemented, however to me it looks like a small issue with how PlayerInput is handled.

**Comment by SDGNelson** [comment]
It's because if mouse button is clicked fast enough it will be considered pressed on both server frames. Adding a third state to represent that the client did release and press again is actually on my to-do list.
