### ISSUE TITLE
Server finder bad working

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3692]
After several game updates, the search system began to search for servers for a very long time (30sec-minute), please fix this, before servers were searched for 1-3 seconds.

**Comment by GazziFX** [comment]
I think its more depend on Steam master-server rather than Unturned

**Comment by SDGNelson** [comment]
Depends how specific your filters are. Some filters are handled on the master server which speeds up the search significantly.

**Comment by QERT2002** [comment]
All my filters are "ANY" and "No Password", if it is steam problem, can you make a cache system idk, because many peoples say me, like that: "Man i don't see your server in server list, all my filters are any".
I try to find another servers in server list, and I know that earlier they were searched very quickly, but now it took a lot of time and at the moment I thought that these servers were turned off, in fact, I just had to wait more than a minute.
