### ISSUE TITLE
[Bug] Aiming with a bow in third person and switching to first causes the crosshair to disappear.

### ISSUE THREAD

**Issue by KarmaWSYD** [SmartlyDressedGames/Unturned-3.x-Community#3693]
When aiming in with a bow (tested with different bows) while in third person the crosshairs disappear when switching to first person. Tested on both singleplayer and a Linux-based server in the current version and in singleplayer on the unity 2019 beta. Couldn't replicate the behavior on non-bow items, hence I assume it's specifically related to bows.
![Unturned Screenshot 2023 02 06 - 20 42 51 60](https://user-images.githubusercontent.com/92757174/217059470-da424366-a933-4ff0-86c0-f413031cc02d.png)
![Unturned Screenshot 2023 02 06 - 20 43 01 13](https://user-images.githubusercontent.com/92757174/217059475-e2b6d603-c1db-44d6-b2dc-fdcd1f6dada6.png)

**Comment by SDGNelson** [comment]
Thanks for the report!

**Comment by SDGNelson** [comment]
This led to finding some particularly ugly code I must have missed when making the crosshair changes. The fix doesn't fully tidy it up, but should be working properly at least!
