### ISSUE TITLE
sendUpdateState() not working

### ISSUE THREAD

**Issue by realtrollman2319** [SmartlyDressedGames/Unturned-3.x-Community#3694]
I really know this is the method to update the player's viewmodel, but it dosen't seem to work. I've tried updateState() yet it still dosen't work.

Yes the code works, it updates the inventory icon but not viewmodel.

```
ulong parsedPlayerID = ulong.Parse(playerIdGiven); // A string

Player playerGiven = PlayerTool.getPlayer(new CSteamID(parsedPlayerID));
itemGiven.Item.item.metadata = bList.ToArray();

playerGiven.equipment.sendUpdateState();
playerGiven.inventory.sendUpdateInvState(itemPage, itemGiven.Item.x, itemGiven.Item.y, bList.ToArray());
```

![image](https://user-images.githubusercontent.com/108993392/217263025-f36ee126-0acc-40ea-8099-2a38192a681e.png)

**Comment by SDGNelson** [comment]
It looks like the easier option would be to set the state prior to adding the item to the player's inventory.

**Comment by realtrollman2319** [comment]
That works, but I want it to actually apply the state edits without re equipping.

**Comment by SDGNelson** [comment]
For the equipped item you can use: PlayerEquipment.state

**Comment by GazziFX** [comment]
I don't know what you trying to do, but I can share my code for infinite ammo
