### ISSUE TITLE
Invalid ResourceSpawnpoint.id

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3699]
My friend had a problem with this, it doesn't happen on the old map, perhaps because now resources are saved by GUID. Replacing `ResourceSpawnpoint.id` with `ResourceSpawnpoint.asset.id` fixed the problem. It should be marked obsolete or fixed

**Comment by SDGNelson** [comment]
I suppose yes it should be marked obsolete. It is now marked obsolete on the preview branch.
