### ISSUE TITLE
Power system enhancements

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#370]
Currently client will only work with powered items with quite a restriction:
There must be a working generator (on client) within range of 64

Which means effectively increasing range of custom generators over 64 won't work (and doesn't, confirmed)

I'd really like to control `InteractablePower`s from server without touching generators

Easiest example would be a global power plugin - everything is always powered. 
Then I'd want to turn power on/off for exact objects (binary state)

imho a viable solution would be adding some sort of `PowerType` enum value to InteractablePower and a way to change that on clients from server.
I guess `PowerType` could have values like
 `UseGenerator` (default) - make check from generators around the powered object/barricade
`Unpowered` - would force unpower it (server managed) 
`Powered`  - third - force power

Any suggestions welcome, I don't claim this to be the best solution

**Comment by aviadmini** [comment]
Again, **on client** max wire is hardcoded to 64 which makes it impossible for people in larger range to use any electrically powered devices because they just show up red

**Comment by SDGNelson** [comment]
Hmm if that's the case it sounds like a bug. I'll look into it.

**Comment by SDGNelson** [comment]
Looks like you're right. I've changed that number to 256, and moved it to PowerTool.MAX_POWER_RANGE. Generator assets with a further range will cause a warning message about the max supported range.

**Comment by aviadmini** [comment]
Guess that means no to any kind of serverside powering options 😣

Welp, 256 is 4 times better than 64
