### ISSUE TITLE
Dedicated servers need optimization

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#3701]
Due to some personal reasons, I can only use a server equipped with two E5 2690V4 processors.
After I set up the server, I found that its Updates per second: 14%.
Compared with the server Updates per second using AMD 5900X, it is much lower.
I noticed that this may have something to do with the game map used, but I don't quite understand why, as a dedicated game server, a large number of Objects are loaded, which makes the server lag seriously.
And I found that the CPU usage rate of Unturned is only 6.1%, obviously there are more CPU resources, the program does not continue to use more CPU.
When there are 22 players in my server, the CPU usage is still around 6%, and there is no obvious increase in usage!
![NJS$}OG@0HUK$0~J(ADP6X8](https://user-images.githubusercontent.com/62692767/218317699-0093930a-d084-4735-a1ea-233d4aafd1d1.png)
I really have no way to use a better server, I want to know if there is any other solution to this.

**Comment by SDGNelson** [comment]
It looks like the percentage is out of the total number of cores available. The game is maxing out 1 or 2 cores, but the rest are unused by the single server. The game loop runs on a single thread and will usually be the bottleneck for anything that is run on other threads like web requests or database connections.

**Comment by GazziFX** [comment]
@CatzMR I don't really understand what you trying to say, you mean low CPU usage is bad?

Do players have jagged movement or other issues?

Did you tested without plugins?
