### ISSUE TITLE
Unable to upload edits to a map I'm contributor on?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#3705]
Hey @SDGNelson, 
Since the latest Unturned Update I've been unable to upload edits to a map I'm contributor on. When uploading the map it states failed to upload inside of the game and when I go into the unturned logs the error states, "Failed to submit update because: k_EResultInvalidParam" and I've also tried re-accepting the Steam Subscriber Agreement and it literally won't let me, the button is clickable but the page doesn't reload nor does the date change in which I last re-accepted the agreement. Is this by chance a known reported issue or something new that hasn't been reported as of yet? As k_EResultInvalidParam isn't really an error unless it goes in depth as to what the error relates to. If you could possibly assist I'd be greatful.
Thank you!

Attachments: 
![01](https://user-images.githubusercontent.com/20868143/219228786-64d46a40-70b9-46a3-b139-0b4b76d1c76d.png)
![02](https://user-images.githubusercontent.com/20868143/219228781-0cd5c10d-c363-4af4-a611-03d88742d73c.png)

**Comment by MoltonMontro** [comment]
**To clarify:** k_EResultInvalidParam is a Steam error, not an Unturned error. There's a couple reasons as to why it can appear.

For your mod, are you trying to use a preview image that's less than 16 bytes? If so, try using a larger image file.

**Comment by SDGNelson** [comment]
Adding to what Molt said: if you can attach the `workshop_log.txt` file from `C:\Program Files (x86)\Steam\logs` there should hopefully be more details about the underlying error.

**Comment by joeymisfit** [comment]
I ended up giving it a try without the thumbnail as you suggested and it worked. I always assumed the thumbnail was required even for updates due to the ! right before the path.

**Comment by MoltonMontro** [comment]
I'm glad you were able to resolve the issue. :)

@SDGNelson Maybe something about the upload menu should be changed here for clarity? I doubt that the current upload menu had the slightly-limited permissions of co-authors in mind.

**Comment by SDGNelson** [comment]
Revamping the workshop submission menu is definitely on my to-do!
