### ISSUE TITLE
Dear Mr. Nelson or other friends, Why can't my Unturned upload creative workshop items, any items can't

### ISSUE THREAD

**Issue by gp23385** [SmartlyDressedGames/Unturned-3.x-Community#3706]
Upload failure will be displayed as soon as it is uploaded. I am online, and a black box will appear on the creative workshop page in my published items after failure，but，some people can upload.I don't know what's going on. It has become so strange before.Can you tell me what happened, thanks

**Comment by SDGNelson** [comment]
Could you attach the `workshop_log.txt` file from `C:\Program Files (x86)\Steam\logs` please?

**Comment by gp23385** [comment]
---Original---
From: "Nelson ***@***.***&gt;
Date: Sat, Feb 18, 2023 00:48 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SmartlyDressedGames/Unturned-3.x-Community] Dear Mr. Nelson orother friends, Why can't my Unturned upload creative workshop items, any itemscan't (Issue #3706)




 
Could you attach the workshop_log.txt file from C:\Program Files (x86)\Steam\logs please?

**Comment by SDGNelson** [comment]
It looks like you tried sending a reply by email but the message was empty.

**Comment by gp23385** [comment]
023-02-17 18:48:14] Loading workshop items for 27 installed apps for user [U:1:1070335853]:[2023-02-17 18:48:14] [AppID 1583720] Loaded workshop items in "G:\SteamLibrary\steamapps\workshop" (1 installed, 1 needed)[2023-02-17 18:48:14] [AppID 1483870] Loaded workshop items in "F:\SteamLibrary\steamapps\workshop" (3 installed, 3 needed)[2023-02-17 18:48:14] [AppID 1279610] Loaded workshop items in "E:\SteamLibrary\steamapps\workshop" (0 installed, 0 needed)[2023-02-17 18:48:14] [AppID 1088790] Loaded workshop items in "C:\Program Files (x86)\Steam\steamapps\workshop" (0 installed, 0 needed)[2023-02-17 18:48:14] [AppID 1012880] Loaded workshop items in "E:\SteamLibrary\steamapps\workshop" (0 installed, 0 needed)[2023-02-17 18:48:14] [AppID 602960] Loaded workshop items in "G:\SteamLibrary\steamapps\workshop" (0 installed, 0 needed)[2023-02-17 18:48:14] [AppID 431960] Loaded workshop items in "F:\SteamLibrary\steamapps\workshop" (61 installed, 61 needed)[2023-02-17 18:48:14] [AppID 362890] Loaded workshop items in "E:\SteamLibrary\steamapps\workshop" (18 installed, 18 needed)[2023-02-17 18:48:14] [AppID 304930] Loaded workshop items in "F:\SteamLibrary\steamapps\workshop" (14 installed, 14 needed)[2023-02-17 18:48:14] [AppID 246620] Loaded workshop items in "D:\SteamLibrary\steamapps\workshop" (0 installed, 0 needed)[2023-02-17 18:50:30] [AppID 304930] Detected workshop change : changed cached item 2617687827, new manifest 7999792257158768210[2023-02-17 18:50:30] [AppID 304930] Starting Workshop download job ( updating )[2023-02-17 18:54:14] [AppID 304930] Finished Workshop download job : No Error[2023-02-17 22:59:28] [AppID 12210] Loaded workshop items in "C:\Program Files (x86)\Steam\steamapps\workshop" (0 installed, 0 needed)[2023-02-17 23:06:15] [AppID 304930] GetDetails request 0x3 - batch (0-14 of 14) =&gt; not in cache, requesting from Steam[2023-02-17 23:16:11] [AppID 304930] GetDetails request 0x7 - batch (0-1 of 1) =&gt; not in cache, requesting from Steam[2023-02-17 23:52:33] [AppID 304930] GetDetails request 0x9 - batch (0-1 of 1) =&gt; not in cache, requesting from Steam[2023-02-18 06:43:25] [AppID 304930] GetDetails request 0xa - batch (0-14 of 14) =&gt; not in cache, requesting from Steam[2023-02-18 06:52:25] [AppID 304930] GetDetails request 0xe - batch (0-1 of 1) =&gt; not in cache, requesting from Steam[2023-02-18 07:35:29] [AppID 304930] Updating workshop item details failed with No Connection[2023-02-18 07:48:12] [AppID 304930] GetDetails request 0x10 - batch (0-1 of 1) =&gt; not in cache, requesting from Steam[2023-02-18 07:59:15] [AppID 304930] Upload starting for workshop item 2923734302 by AppID 304930[2023-02-18 07:59:15] [AppID 304930] Upload workshop item 2923734302 failed (Build for workshop item has no content)[2023-02-18 08:00:48] [AppID 304930] Upload starting for workshop item 2923734302 by AppID 304930[2023-02-18 08:00:49] [AppID 304930] Upload workshop item 2923734302 failed (Build for workshop item has no content)

**Comment by SDGNelson** [comment]
It looks like the error is that the content folder is empty. (the folder trying to be uploaded)

Judging by: Upload workshop item 2923734302 failed (Build for workshop item has no content)

**Comment by gp23385** [comment]
I put it in clearly. Why is it empty? How to solve it

---Original---
From: "Nelson ***@***.***&gt;
Date: Sat, Feb 18, 2023 14:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SmartlyDressedGames/Unturned-3.x-Community] Dear Mr. Nelson orother friends, Why can't my Unturned upload creative workshop items, any itemscan't (Issue #3706)




 
It looks like the error is that the content folder is empty. (the folder trying to be uploaded)
 
Judging by: Upload workshop item 2923734302 failed (Build for workshop item has no content)

**Comment by SDGNelson** [comment]
I don't know why it is empty, but it might be worth trying moving the upload folder elsewhere in case it is a permissions issue.
