### ISSUE TITLE
LevelObject's Transform's new Name

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3707]
In the most recent update (Version; 3.23.2.0) LevelObject's Transform's name was changed from their ushort Object ID to the Object asset name. Which is fine. But `ObjectManager.getObjectsInRadius()` still uses a list of Transforms as the result. This makes it extremely inconvenient to get the Asset or ID of an Object. GetComponent is not super fast and copying the `getObjectsInRadius` method to replace the Transform list with a LevelObject list feels like it shouldnt be necessary.

**Comment by SDGNelson** [comment]
It is unfortunate that so much older code uses the transform as a handle. For the meantime the best option would be a custom helper method to get `LevelObject`s instead as you mention.
