### ISSUE TITLE
Material Index isn't kept when copy-pasting object

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3708]
_Originally reported on the Forum: [Map Editor material indexes](https://forum.smartlydressedgames.com/t/map-editor-material-indexes/22101?u=moltonmontro)._

When copy-pasting an object that has been manually assigned a material index, this value is not kept on the new object. Instead, the copy-pasted object uses the default `-1` value, and the intended value must be reassigned.

This seems like an oversight, as other properties for assets/objects are kept when copy-pasting. E.g., a spherical deadzone doesn't get pasted as a cube deadzone.

**Comment by SDGNelson** [comment]
True should probably be copied!

**Comment by SDGNelson** [comment]
Ah, unfortunately I forgot how much older the object editor code is. I shouldn't have marked it "will do soonish". Unlike the other copy/paste stuff the objects have code specifically for copy/paste that should get cleaned up first.

**Comment by SDGNelson** [comment]
(closed as not planned, but *should* happen in the future whenever objects editor gets overhauled)
