### ISSUE TITLE
Seasonal Objects still have collisions on multiplayer

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3709]
![1](https://user-images.githubusercontent.com/71527679/219828286-e4eab86e-752f-462f-b3a4-b2d65f9d2ec9.gif)
<img width="710" alt="image" src="https://user-images.githubusercontent.com/71527679/219828178-d4f748f0-26de-43bd-94fb-653c2e907c99.png">

**Comment by SDGNelson** [comment]
Yikes, thanks for the report! I will fix this in a patch probably tomorrow, will wait and see if there are other bug reports.

**Comment by SDGNelson** [comment]
Should be fixed now, fortunately the only bug reported in this update. 😄
