### ISSUE TITLE
Plane Issue Bug

### ISSUE THREAD

**Issue by aliq1100** [SmartlyDressedGames/Unturned-3.x-Community#3710]
Was playing Unturned then this random bug/glitch happened, have a look. It's letting me drive the plane while I'm stuck in one position.
![image](https://user-images.githubusercontent.com/125736221/219856577-ce6ef968-13ff-4e75-89f4-b712c369b4fc.png)
![image](https://user-images.githubusercontent.com/125736221/219856581-54735a27-c10f-4683-b5fb-887d6a3a33de.png)

**Comment by MoltonMontro** [comment]
This is a known issue: https://support.smartlydressedgames.com/hc/en-us/articles/12298639522452-Floating-outside-vehicle-bug

If you're able to reliably and consistently reproduce this issue, and can provide the steps to do so (as either text, or a video), that'd be useful. Thank you!

**Comment by aliq1100** [comment]
Yes, I have a video but the file size is too large.

**Comment by sunnamed434** [comment]
> Yes, I have a video but the file size is too large.

Try uploading to the google disk or even on youtube

**Comment by MoltonMontro** [comment]
> Yes, I have a video but the file size is too large.

Like the helpful user above said, you could upload it somewhere else and then provide a link. E.g., upload it to YouTube and then post a link to the video. Alternatively: you can email the video file to us/me.
