### ISSUE TITLE
Object Culling volumes can't be selected if placed via .dat

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3714]
Unsure if this is intended behaviour. Volumes auto placed by LOD Area and LOD Mesh cannot be adjusted in editor. Fine tuning the cull values would be very useful for some cases. 
EDIT: Being able to delete them as well may also be helpful, but this may just cause headaches.

**Comment by SDGNelson** [comment]
This is intentional: culling volumes owned by objects aren't saved into the level.
