### ISSUE TITLE
Game will crash anytime it tries to load the map or tutorial

### ISSUE THREAD

**Issue by Spade8012** [SmartlyDressedGames/Unturned-3.x-Community#3716]
My first issue happened when the game would load up the loading screen and then when it was done, it would crash.
After I went through steam, went through local files to update/validate the game so it would work, the game would load up the menu screen and everything. but when I tried to load up the tutorial or main maps it would crash. I also tried to turn down all of the graphic settings down. I have some crash logs in my temp folder, but I dont know what to do with them.

**Comment by SDGNelson** [comment]
Sorry for the trouble! Could you submit a crash report following this article please? https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash
