### ISSUE TITLE
Objects Issue

### ISSUE THREAD

**Issue by Pioneerkin1337** [SmartlyDressedGames/Unturned-3.x-Community#3717]
https://www.youtube.com/watch?v=Mp6HmFg7Thg&ab_channel=Pioneerkin1337

How fix it?

**Comment by sunnamed434** [comment]
Seems like new update break the lods system

**Comment by SDGNelson** [comment]
It appears to be related to this feature: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ManualObjectCulling.md

**Comment by MoltonMontro** [comment]
Bumping this to note that there was a similar troubleshooting question posed on the forum. https://forum.smartlydressedgames.com/t/vanilla-objects-invisible-on-workshop-map/22170
