### ISSUE TITLE
Need account to download server

### ISSUE THREAD

**Issue by tenten8401** [SmartlyDressedGames/Unturned-3.x-Community#372]
Any chance you could make it so that we don't need to login to a steam account that's played unturned in order to download it for server use? it's a free game so I'm not sure there's really even a point to have it like that, unless the anticheat needs it or something

**Comment by SDGNelson** [comment]
I've asked the Steam team to add it to the anonymous package a few times in the past, but never heard back from them unfortunately. This is taken care of for 4 though - the dedicated server is a separate app which can be downloaded anonymously.
