### ISSUE TITLE
*Very important* Unturned loading system failing abuse

### ISSUE THREAD

**Issue by JTDyt** [SmartlyDressedGames/Unturned-3.x-Community#3721]
So recently ive seen multiple people getting this glitch where the unturned loading system bassicaly fails mid way while trying to load about like 30k elements in seattle (this is on the Pandahut #10 server just for some info) now with this video being provided it basicaly shows that vehicles cannot colide into seemingly said "ghost blocks" which is where things would appear invisible but you cannot walkk inside them, you would just simply get pushed back, now with vehicles, they seem to not follow the same rule as players being pushed back they can simply drive into drive thrus or garages or we could say door, and all they simply need is basicaly something i call jump starting the loading system which is where they would tp out to unload the 30k elements and tp back in, about 80% of the time it will work. 

here is a streamable attachment
https://streamable.com/v7qtld 

here is a discord attachment of the same video incase streamable dosent work
https://cdn.discordapp.com/attachments/1077928834046906429/1078277415190659155/Veryeasilyabusable.mp4

**Comment by SDGNelson** [comment]
The reason the vehicles can drive through is their physics are *mostly* client authoritative, whereas walking player movement is server authoritative.

Is it reproducible? For example is there a specific area it often happens? Are there any errors in the server console?

It comes to mind that the cause could be similar to #3100, but if that were the case I'd expect the existing barricades to get unloaded.

**Comment by SDGNelson** [comment]
Actually it's probably more likely to be: #3725
Feel free to comment and I will re-open.
