### ISSUE TITLE
.masterbundle won't update if only change is folder name

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3722]
If the only change for a masterbundle is a renamed folder, as far as I can tell it won't actually update. Instead, you'd have to delete all of the current masterbundle files first—or make a more tangible change to the Unity project—so that the tool is required to generate new ones.

It's unlikely for someone to run into this issue that often, but if they do it can be confusing to troubleshoot and is a minor annoyance to have to make a random change (or delete the masterbundle files) to workaround this.

_I originally mentioned this peculiarity on the SDG Forum: https://forum.smartlydressedgames.com/t/weapon-mod-not-working-mod-name-is-red-in-manager-list/21824/8_

## Example

A modder has a masterbundle with a main folder named "ExampleBundle", and their MasterBundle.dat points to `Asset_Prefix Assets/ExampleBundle`. They're about to release their mod, but want to rename the main folder to something more fitting. They rename the mod's main folder to "MyMod", and change the asset prefix to `Asset_Prefix Assets/MyMod`.

They boot up the game to test their mod, but it's broken. The error log lists every item as "missing 'Item' gameobject". This error is technically correct—because the asset prefix is now wrong.

Even more likely, this could happen if a modder is renaming individual item folders for better organization/consistency. For example: renaming "Barricade_Test" and "MetalBarricade", to "Barricade_Metal_0" and "Barricade_Metal_1".

**Comment by SDGNelson** [comment]
If the folder is renamed in Unity? I guess this is a bug or issue with Unity's asset bundle export not considering it a change, and outside of our control aside from maybe an option in the export tool to force a rebuild.

**Comment by MoltonMontro** [comment]
Yeah, if the folder is renamed in Unity.
