### ISSUE TITLE
Question: What triggers Vehicle Decay?

### ISSUE THREAD

**Issue by bytemage** [SmartlyDressedGames/Unturned-3.x-Community#3724]
This is not an issue, but I don't know where else to post this.

I'm running Polaris and there have been several vehicles that trigger the VehicleDecay event but with 0 damage. I guess the damage is set to 0 by the map config, as the server config is all default.

What I don't understand is how VehicleDecay triggers. Some vehicles were locked by active players, so it's not the owner like with structures/barricades. Is it the last time the vehicle was used?

**Comment by GazziFX** [comment]
When vehicle is not driven long time (Decay_Time in config) it gets damaged by Decay_Damage_Per_Second
```csharp
if (interactableVehicle.isDriven && (interactableVehicle.transform.position - interactableVehicle.decayLastUpdatePosition).sqrMagnitude > 1f)
{
   interactableVehicle.ResetDecayTimer();
   return;
}
```

**Comment by bytemage** [comment]
Thanks
