### ISSUE TITLE
[Bug] Game doesn't support changing/checking barricade types.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3725]
Hello, recently the More Farming Mod updated on February 24th and changed several barricade types: 

> Changed the item type of non-interactive wall-mounted furniture such as Wall Shelves, Wall Vines, Wall Planter and Towel/Paper Holder from Charge to Torch and Wall Storage.

This update caused this error on servers that previously had barricades placed for that mod:

```2023-02-24 16:54:57] ArgumentException: length
[2023-02-24 16:54:57] System.Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length) (at <695d1cc93cca45069c528c15c9fdd749>:0)
SDG.Unturned.BarricadeManager+<>c__DisplayClass174_1.<SendRegion>b__1 (SDG.NetPak.NetPakWriter writer) (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
SDG.Unturned.ClientStaticMethod.Invoke (SDG.NetTransport.ENetReliability reliability, SDG.NetTransport.ITransportConnection transportConnection, System.Action`1[T] callback) (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
SDG.Unturned.BarricadeManager.SendRegion (SDG.Unturned.SteamPlayer client, SDG.Unturned.BarricadeRegion region, System.Byte x, System.Byte y, SDG.Unturned.NetId parentNetId, System.Single sortOrder) (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
SDG.Unturned.BarricadeManager.onRegionUpdated (SDG.Unturned.Player player, System.Byte old_x, System.Byte old_y, System.Byte new_x, System.Byte new_y, System.Byte step, System.Boolean& canIncrementIndex) (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
SDG.Unturned.PlayerMovement.updateRegionAndBound () (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
SDG.Unturned.PlayerMovement.simulate () (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
SDG.Unturned.PlayerInput.FixedUpdate () (at <0a05cbc6ac0845e7ad7d3b38701ae80d>:0)
[2023-02-24 16:54:57] ArgumentException: length
```

I believe this error was caused by the fact that different types of barricades have different array lengths. This error then causes barricades to not show up on client-side yet players will still collide with them. It also effects other mods too, barricades from mods such as Furniture Expansion start to disappear as well. Could there be an implementation of checks to make sure that problems like this don't happen again? or better yet, the ability to freely change barricade types.

**Comment by rube200** [comment]
That error came from barricade.state, from the error it seems the item that is causing is a Storage.
If it is a Storage without displaying item the state should be at least 16 of size

**Comment by SDGNelson** [comment]
Unfortunately yes this isn't properly handled at the moment. In the future I need to separate savedata from the replicated state, and will probably change the per-barricade savedata to something plugins can extend as well.

For the meantime I will probably change the barricade loading to discard any that changed type between save/load. :(

I suspect this is a continuation of: https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/issues/59

**Comment by Jdance-Media** [comment]
Thanks, much appreciated.

**Comment by SDGNelson** [comment]
I should elaborate on a few workarounds for anyone who reads this in the meantime:

1. Easiest, but most destructive: deleting the server's Barricades.dat file would reset everything.

2. Less destructive: temporarily disabling More Farming, start the server to wipe all the barricades which are now missing assets, then re-enable More Farming.

3. Most labour intensive: copy the server's Barricades.dat file to a singleplayer world. Manually pick up the relevant barricade(s). Save and copy edited Barricades.dat back to the server. [Thanks Adam!]

**Comment by SDGNelson** [comment]
Technically the change is on the preview branch, but not saving with it yet otherwise switching back to default branch would not be forwards compatible.
