### ISSUE TITLE
Player loses connection when a nearby vehicle has just been destroyed

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#3726]
When a player tries to walk into an area where a vehicle has just been destroyed (`VehicleManager.askVehicleDestroy`), the server will throw exception:
```
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at UnityEngine.ControllerColliderHit.get_gameObject () [0x00001] in <db18c9c73121425ebf2b91729ce270d3>:0
  at SDG.Unturned.PlayerMovement.simulate (System.UInt32 simulation, System.Int32 recov, System.Int32 input_x, System.Int32 input_y, System.Single look_x, System.Single look_y, System.Boolean inputJump, System.Boolean inputSprint, System.Single deltaTime) [0x00648] in <0a05cbc6ac0845e7ad7d3b38701ae80d>:0
  at SDG.Unturned.PlayerInput.FixedUpdate () [0x008c1] in <0a05cbc6ac0845e7ad7d3b38701ae80d>:0
```
Then the player can no longer move around, and after about 20 seconds, the player loses connection to the server.

https://user-images.githubusercontent.com/64722485/221365395-d078079a-b4a9-40c1-bc34-aacf1f98168c.mp4

Server version:
```
Game version: 3.23.2.1 Engine version: 2020.3.38f1
Rocket Unturned v4.9.3.10 for Unturned v3.23.2.1
```

Has anyone run into this issue?

**Comment by warren39** [comment]
This issue only appeared after the recent update. I didn’t pay attention to which version.

**Comment by sunnamed434** [comment]
iirc this is a deprecated method, isn't it? I can be wrong, try to use other methods to destroy the vehicle

**Comment by Jdance-Media** [comment]
> iirc this is a deprecated method, isn't it? I can be wrong, try to use other methods to destroy the vehicle

`askVehicleDestroy` is the proper method to destroy a single vehicle. It would be `tellVehicleDestroy` that is obsolete.

**Comment by rube200** [comment]
The method seems to be good, when are you asking to destrói the vehicle?

**Comment by DiFFoZ** [comment]
The reason of NRE is that `ControllerColliderHit` gets gameobject from collider:
```cs
public GameObject gameObject => this.m_Collider.gameObject;
```

Changing `gameObject` to `collider` should fix it: https://github.com/Unturned-Datamining/Unturned-Datamining/blob/linux-client-preview/Assembly-CSharp/SDG.Unturned/PlayerMovement.cs#L894

```diff
- if (!flag3 && mostRecentControllerColliderHit != null && mostRecentControllerColliderHit.gameObject != null && mostRecentControllerColliderHit.normal.y > 0f && mostRecentControllerColliderHit.gameObject.CompareTag("Agent"))
+ if (!flag3 && mostRecentControllerColliderHit != null && mostRecentControllerColliderHit.collider != null && mostRecentControllerColliderHit.normal.y > 0f && mostRecentControllerColliderHit.gameObject.CompareTag("Agent"))
```

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix for the next update.
