### ISSUE TITLE
Typo for workshop upload success message.

### ISSUE THREAD

**Issue by RoyalMilkTea** [SmartlyDressedGames/Unturned-3.x-Community#3727]
![image](https://user-images.githubusercontent.com/126480436/221571881-f2156c91-8973-439c-90ae-1ac3418ba839.png)

Minor typo.

**Comment by sunnamed434** [comment]
You mean, there should be that instead? Succe`s`sfully submitted

**Comment by SDGNelson** [comment]
Thanks, will fix.
