### ISSUE TITLE
Child Explosion Armor Multiplier doesn't work

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3728]
**Child Explosion Armor Multipliers** no longer work. This applies to both the gameplay config setting, and the setting available per vehicle.

What's intended to happen is that buildables placed on a vehicle will reduce the damage taken from explosions, when they obstruct the explosion. What actually happens is that the vehicle takes full damage anyways.

I verified that this featured used to work, by testing it again on the Unity 2017 branch (version 3.19.15.2). I'm not sure which specific update broke it, but I know explosions have changed a couple times over the years.

**Comment by SDGNelson** [comment]
I just checked and those multipliers do work, but not as expected:

In older versions the explosion line of sight test was to the center of the vehicle, whereas nowadays it is to the closest point on the vehicle. When the barricade is within 50cm of closest point the line of sight test is not long enough to hit it. If the barricade is further from the surface then it does get hit and the armor multiplier is used.

I think this 50cm threshold must have been in part to help compensate for *not* using the closest point, so I will adjust it down to maybe 1cm for the next update which should register barricades on the surface.

**Comment by MoltonMontro** [comment]
> I think this 50cm threshold must have been in part to help compensate for _not_ using the closest point, so I will adjust it down to maybe 1cm for the next update which should register barricades on the surface.

Tangential, but I wonder if this is part of the reason why the Precision Charge has issues with damaging some vehicles (e.g., Tanks when placed anywhere but inside the driver's seat window)? It's something I recently noticed as well. Maybe it's due to a different issue
