### ISSUE TITLE
Issue related to starting Unturned after 3.25.2.0 Update

### ISSUE THREAD

**Issue by themisfitgames** [SmartlyDressedGames/Unturned-3.x-Community#373]
Hello Nelson,

After the latest update was pushed out I am no longer able to run Unturned, it states that Unturned has crashed and client.log has spammed the following exception;

_NullReferenceException: Object reference not set to an instance of an object
SDG.SteamworksProvider.SteamworksProvider.updateServices ()
SDG.SteamworksProvider.SteamworksProvider.update ()
SDG.Unturned.Provider.Update ()_

Lets hope we can get this update fixed so that past issues don't keep on reoccuring. :)

![clientlog](https://user-images.githubusercontent.com/20868143/43179906-1253e07e-8f8a-11e8-84a2-721db30b9c8b.PNG)

Thanks!

**Comment by baranmod** [comment]
Just wanted to add that same stuff is happening for masses. Running game as administrator or running in win8 compatibility mode helps for some reason.

**Comment by SDGNelson** [comment]
I looked through a bunch of log files with that same error, but haven't been able to replicate it. Do you have any code mods e.g. RocketMod or cheats/hacks installed on the client? Nevertheless I've bulletproofed that code a bit more.

For the crash my hunch is that it's related to the mesh RAM changes, so I've rolled those back and we'll see what happens.

**Comment by khakers** [comment]
Still happening for me after the update. error log is filled with the same message.

**Comment by SDGNelson** [comment]
Tracked it down now to some sort of change in the Discord integration. Since the patch didn't address that I've rolled back to 3.25.1.0 for now.

**Comment by SDGNelson** [comment]
After investigating more, both that log spam and the crash only happen if Discord is running. I suspect this is then related to updating to the most recent version of the Discord API.

I'm still not sure how it could be causing that specific error, as these two systems have no knowledge of eachother.

For the moment I'm going to roll out a patch which disables the Discord integration temporarily. I've also added a command-line option "-NoDiscord" which overrides the "-Discord" option.
