### ISSUE TITLE
Z-Fighting on a couple of objects

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3731]
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/71527679/222329378-246561d1-ebe6-45b7-a7c8-18eb645f20b7.png">

"Wrecked Space Shuttle #1" - by default
and 
"Wheel #6" - but only while using material palette GUID "5e91aafd7cce4217a7e32d63122604a5" Index: 1

**Comment by AdamDN** [comment]
I feel like this might be a wider issue that affects more objects that I haven't listed, but these are the only 2 I've noticed so far. 
This issue is only recent - it did not exist in previous versions. It also only happens in-game, not in the Editor.

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like some meshes have UVs exactly at 0.0 or 1.0, so when atlassed they are at the intersection of 2-4 pixels. Tested padding very slightly by 0.00001 texels and it seems fine for the update.
