### ISSUE TITLE
Bridge Line #2 Europe / Bridge_Line_7 uses the wrong ID

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3734]
The **Europe** variant of any Vanilla Bridge object always uses the same ID as the original, with the exception of `Bridge Line #2 Europe` which surely must be by mistake.
![BridgeWrongID](https://user-images.githubusercontent.com/70017362/222724124-a344e84d-2cb5-41ef-bde3-b0237f79ca9a.png)
*This is again related to the Plugin I am developing. I got some issues on Germany because of this which forced me to combine both objects from `Bridge #1` and `Bridge #2` into one **BridgeReference** in my Plugin. Which absolutely isn't ideal since those Bridge objects will never be used in combination as one single Bridge.*

On a sidenote, I didn't know objects allowed for IDs colliding. I guess they all use GUIDs now, which I think is a very welcome change, hoping that makes it way to all other assets. That got me curious though. Is there anything that actually uses the Object ID or is it just an unused legacy property?

**Comment by SDGNelson** [comment]
AFAIK nothing in vanilla uses the legacy object IDs anymore. Do you need them for something? What is your plugin doing?

**Comment by Gamingtoday093** [comment]
> AFAIK nothing in vanilla uses the legacy object IDs anymore.

Alright just curious.
> Do you need them for something? What is your plugin doing?

No, not *really*, I just think IDs are a lot more user friendly than GUIDs since they are shorter and you dont have to explicitly copy paste them everywhere. In my plugin I represent bridges like this;
```cs
<Bridge>
    <BridgeLines>
        <ObjectId>290</ObjectId>
    </BridgeLines>
    <BridgeCaps>
         <ObjectId>291</ObjectId>
    </BridgeCaps>
    <BridgeBlocked />
</Bridge>
```
Having objects belonging to `Bridge #1` seperate from objects of `Bridge #2` works perfectly fine for literally every other object except `Bridge Line #2`, I just find it annoying that it's clearly using the wrong Id and it would work perfectly fine in my plugin if it instead used the correct one.

**Comment by SDGNelson** [comment]
I'd highly recommend that you switch them over to guids, otherwise you will also run into conflicts with mods and the curated objects.
