### ISSUE TITLE
F6 again works crooked (Rotation)

### ISSUE THREAD

**Issue by OldUntLover** [SmartlyDressedGames/Unturned-3.x-Community#3735]
I decided once again to work with the F6 camera on the server / map editor and found that when I try to evenly rotate the object, releasing the mouse button, it turns a little to the side, because of this it is not possible to make everything even and beautiful, please fix it

**Comment by SDGNelson** [comment]
Unfortunately a bit of precision is lost with barricade rotation because they use degrees rounded to the nearest multiple of 2 rather than quaternions. In the future they will use quaternions instead which should resolve problems like this.
