### ISSUE TITLE
AttackAudioClip & EquipAudioClip don't work with OneShotAudio assets

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3736]
Currently OneShotAudio assets work with only `ImpactAudioDef` & `InventoryAudio`. I've tried copying a path of inventory audio to EquipAudioClip, `Sounds\inventory\Seeds.asset` did not work. When I pasted there `Sounds\inventory\Seeds\shaker_sprinkle_seeds_cook_garden_01.ogg`, it started working. Would it be possible to use OneShotAudio assets on Equip and Attack audio clips as well? It would be nice to have for example different sounds for swinging your melee weapon. 
![image](https://user-images.githubusercontent.com/81763752/222771018-c0437a32-ca90-4623-a512-126c57fefe8e.png)

**Comment by SDGNelson** [comment]
Ideally they should, but that code is a bit older than the "audio references" that support clips+audiodef. Closing as a feature request, but I do want/intend to do this at some point in the future.
