### ISSUE TITLE
Roof Structure Debris

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3738]
Is there a reason the Roof structure type (ramps/stairs/holes included) doesn't have debris when destroyed? 
Floors are understandable given their size/shape, but I can't think of a reason for Roof's to have it disable, other than perhaps it just looks bad? 

If it's purely down to design choice feel free to close this, but I just thought I'd mention it incase there's a technical reason that can be added to the to-do list.

**Comment by SDGNelson** [comment]
Off the top of my head I think you're right that it didn't look as nice or something along those lines. Perhaps in the future an option to override the model when the structure is destroyed can be added.
