### ISSUE TITLE
//FIXME tellHallucinate

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#374]
Using `PlayerLife.sendHallucination` results into "Failed to find a method named: tellHallucinate"
Reason: `tellHallucinate` is private while `SteamChannel.build` calls `Type.GetMembers` which only `Returns all the public members of the current Type.`

**Comment by SDGNelson** [comment]
Whoops! Should be test cases for the plugin RPCs. Would be nice to refactor to invoke by delegate / method pointer rather than by name, too.

**Comment by aviadmini** [comment]
I actually made my own strongly typed steam call framework. Because there has been too many times when I ducked up by using wrong type, i.e. int instead of byte)
