### ISSUE TITLE
Objects with Unity3d files still use legacy IDs

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3741]
If there's an object inside of a masterbundle, it doesn't require IDs. NPC Objects don't require IDs either. However if you have a unity3d file, it shows you this error and object doesn't work ingame.
![image](https://user-images.githubusercontent.com/81763752/222905846-8eda97ca-e4be-4b2f-90f0-99849bbbb32a.png)

The dat file looks like this 
![image](https://user-images.githubusercontent.com/81763752/222905914-58a0812a-b5a2-4e49-8b87-5d2fb0525fa8.png)
![image](https://user-images.githubusercontent.com/81763752/222905974-bfb8c296-0c2a-4bd6-9403-71e844110ffd.png)

**Comment by iBowie** [comment]
Solving this will allow us to completely abandon IDs for objects. This is important for me as a developer of Asset Editor as well. If this is resolved - I will be able to just hide IDs for objects completely.

**Comment by educatalan02** [comment]
Side note: this will be a breaking change

**Comment by SDGNelson** [comment]
Yes I suppose that error can/should be disabled for objects. It shouldn't break anything though - object IDs are unused.
