### ISSUE TITLE
[Feature Request] Distant gun sounds

### ISSUE THREAD

**Issue by benvalkin** [SmartlyDressedGames/Unturned-3.x-Community#3746]
It would be great to able to have a second sound clip that plays when a weapon shoots that is only heard by players who are much further away. Such a clip would also need to be overridable with certain barrel attachments (like suppressors, since it doesn't make sense for them to have a long-range audible sound).

I am requesting this feature because I tried implementing it with the UseableGunEventHook, which works well except for the fact that it does not support different barrel attachment sounds - meaning that I'd probably need official game support to make this requirement possible.

https://user-images.githubusercontent.com/69928007/222953299-e1462e17-33a4-468f-b9f9-175dee1eb45d.mp4

**Comment by SDGNelson** [comment]
That does sound impressive. Closing because the issues list is not intended for feature requests, but feel free to post as an idea.

**Comment by MoltonMontro** [comment]
To add onto what Nelson said, ideas can be posted in the discussions section or onto our [official forums](https://forum.smartlydressedgames.com/).
