### ISSUE TITLE
(Bug Report) Zombies ignoring the player while proning.

### ISSUE THREAD

**Issue by JimmyDeluxe0** [SmartlyDressedGames/Unturned-3.x-Community#3747]
Greetings,

Recently I have come across an issue (I don't know if this was intentional or not but it seemed weird to me) where if you prone near any kind of zombie (even if you are right next to them and touching them), they will completely ignore you.

**Comment by SDGNelson** [comment]
Just double-checked and the zombies do detect prone players, but note it is affected by the sneakybeaky skill so with the highest skill value the prone detection radius is only 50cm.

**Comment by SDGNelson** [comment]
Sorry, it seems I misunderstood, I was linked [this video](https://www.youtube.com/watch?v=oOPDruBoOBw) which shows that with the zombie collision although the player can be detected the zombie can't actually get close enough. I'll re-open and fix for the next update.
