### ISSUE TITLE
BattlEye doesn't work on Linux dists

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3748]
No need for extra comments I guess. Please fix as soon as possible, that's a public bypass anymore.

**Comment by sunnamed434** [comment]
I think it's not a problem it's part of the bug i.e feature 😉

**Comment by GazziFX** [comment]
You use the wrong words, it works, but it doesnt have any detection checks, memory protection and etc

**Comment by SDGNelson** [comment]
Unfortunately this is as-expected currently.

**Comment by TH3AL3X** [comment]
> Unfortunately this is as-expected currently.



> This problem has been known for 2 years. Can someone fix this shit please? There is no Service about battleye in linux subsystems like ubuntu etc. And Modules can be Loaded from Unturned/Modules using IModuleNexus. Modules should be disabled in Client.

Everything about kernel, just switch to EasyAntiCheat, BattlEye is actually trash.
