### ISSUE TITLE
Steam prevents you from launching Unturned, if U3DS is active

### ISSUE THREAD

**Issue by realtrollman2319** [SmartlyDressedGames/Unturned-3.x-Community#3749]
Basically, if you have U3DS running and you want to launch Unturned, it will show this.
![image](https://user-images.githubusercontent.com/108993392/223763058-b55fb3fd-bead-48cf-8991-e6c3e7042f15.png)

**Comment by rube200** [comment]
Sometimes for some reason Unturned battleeye dont close properly. Try close it by yourself and yes it is annoying

**Comment by SDGNelson** [comment]
It's because the server executable has the same name as the client. Ideally it would be renamed, but hosts would be mad at me for breaking scripts. Using steamcmd rather than through the Steam library is recommended to reduce problems with this.
