### ISSUE TITLE
Request - Grenade.cs to have miscellaneous option to not detect player killer

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3750]
The script has great utility until tested on a server. In the server, the player dies but cannot respawn & the server doesn't detect the death. It can only be fixed via exiting the server.

Make it so that the CSteamID killer is not necessary & can be replaced by death cause from KillVolume.cs. The reason is to make use of the entity damage the script can deal around it. It's just right now, the issue arises if the player dies to the script.

**Comment by SDGNelson** [comment]
It's not meant to be used that way, but it also sounds like there is a different bug here. Unset "killer" should work fine. Could you elaborate on what you mean by dies but cannot respawn please? I will give it a try as well.

**Comment by prank0079** [comment]
Probably Grenade.cs only runs on the client, but not on the server.
This phenomenon often occurs when using unofficial mod hooks.
For example, put "KillVolume.cs that will kill players" on vest, and then put it on zombies.

**Comment by OneManOperative** [comment]
> It's not meant to be used that way, but it also sounds like there is a different bug here. Unset "killer" should work fine. Could you elaborate on what you mean by dies but cannot respawn please? I will give it a try as well.

In the case of using Grenade.cs in foreign assets like Effects & Barricades, it may work. But in multiplayer, it will cause players that die to it to not respawn because the killer line-of-code does not detect who caused the death.

A friend explained to me as well. He said projectiles created by the game code get a CSteamID assigned to them and the networking code tracks it so it can display who shot (created) the projectile and then register kills correctly. So only a plugin can assign the CSteamID to fix it, which is inconvenient if you do not have one for the purpose.

**Comment by SDGNelson** [comment]
I think prank0079 is right that perhaps you are added it to something on the client. By default this component is only added on the server. I will add a check to only explode on the server to prevent problems like that.
