### ISSUE TITLE
too quick of inputs will be dropped on certain actions

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#3758]
## if youre too quick with tapping certain actions, then those inputs will be dropped entirely.

https://streamable.com/6i56k7
(streamable link as this video is too large to upload directly to github)

this most notably happens with:
movement(regular WASD, leaning or jumping)
using items (will probably explain why sometimes semi autos wont fire as fast as youre clicking IF they are supposed to)
changing stance (crouching or going prone)
selecting buildables in the housing planner
interacting (pressing F by default)

this does not happen with:
opening menus (ESC menu or gesture menu)
crafting (refilling ammo included)
placing markers on the map

there appears to be certain times where the game will register inputs for some actions, and some times where they dont. if you try to make inputs inbetween these "windows" then it is common for them to get "dropped" (not registered), especially when trying to slightly inch in a direction by lightly tapping the movement key.
this realistically doesnt have _much_ of a difference on gameplay, but i like to mess with TASing (Tool Assisted Speedrunning) a bit with unturned and this change would help me greatly, but thats a minor thing. this fix would make unturned more responsive in general.

**Comment by SDGNelson** [comment]
One that will change sooner than later is on my near-term to-do list adding pressed-and-released state for the attack inputs that will fix the semi auto problems. (if input is pressed in subsequent ticks currently the server doesn't know it was released)
