### ISSUE TITLE
Steam call to send effect and scale it

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#376]
Currently effects are shown as is at certain position with rotation option

Would be great to be able to change it's size (scale it)

Example usage:
We have a zone with no pvp for example, would be great to make a visual representation of it - similar to what generators and claim flags do but using a plugin

Steam call be like:
```csharp
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void tellEffectPointNormalScale(CSteamID steamID, ushort id, Vector3 point, Vector3 normal, Vector3 scale) {
    if (!channel.checkServer(steamID)) { return; }// TODO should remove this because validation is already performed in SteamChannel, right?
    Transform fx = effect(id, point, normal);
    fx.localScale = Vector3.Scale(fx.localScale, scale); // Little trick to avoid changing EffectManager.effect(...) method. I'm not sure this works but it should
}
```

**Comment by SDGNelson** [comment]
Added! Two new overloads for sendEffectReliable have been added which take uniform scale as an argument.

**Comment by aviadmini** [comment]
@SDGNelson any chance to get non-uniform scale (vector) - cuz that was the whole point

**Comment by SDGNelson** [comment]
What sort of effect is it?

**Comment by aviadmini** [comment]
Semi-transparent mesh (cube or sphere) to show at certain zones

**Comment by aviadmini** [comment]
Bump @SDGNelson 👯

**Comment by aviadmini** [comment]
Bubump

**Comment by aviadmini** [comment]
@SDGNelson could we get non-uniform scaled effects too?
