### ISSUE TITLE
Sentries on vehicle not rotating when the vehicle turns

### ISSUE THREAD

**Issue by Dawicjusz098** [SmartlyDressedGames/Unturned-3.x-Community#3762]
When playing On single player Germany, i place a sentry on an APC facing North. After i rotated the the vechicle by driving, the sentry was still aiming North, which rendered placing sentries on the vehicle useless.

**Comment by SDGNelson** [comment]
There are a few wonky aspects of turrets on vehicles, however it should still shoot targets properly and turrets are not placeable on vehicles in multiplayer by default.
