### ISSUE TITLE
my vision is stuck in 3.00.00.0

### ISSUE THREAD

**Issue by XbombX** [SmartlyDressedGames/Unturned-3.x-Community#3764]
please help me some one

**Comment by GazziFX** [comment]
Please provide more info, screenshots, logs, steps to reproduce etc

**Comment by SDGNelson** [comment]
Are you getting kicked with a version number message? Or does the main menu say the game version is 3.0.0.0?

**Comment by SDGNelson** [comment]
Closing but will re-open if OP comments.
