### ISSUE TITLE
Items.onItemAdded bug

### ISSUE THREAD

**Issue by kaposzta99** [SmartlyDressedGames/Unturned-3.x-Community#3766]
onItemAdded event doesn't fire when item is added from Nearby

**Comment by SDGNelson** [comment]
Are you using it on the client? 😕

**Comment by kaposzta99** [comment]
I don't get the question, but here is the code:
`
public void Execute(IRocketPlayer caller, string[] command)
{
            var uplayer = (UnturnedPlayer)caller;
            var inventory = new Items(7);

            inventory.resize(8, 8);

            inventory.onItemAdded = (byte page, byte index, ItemJar jar) => {
                // this does not fire when item is picked up from nearby
            };

            uplayer.Player.inventory.updateItems(7, inventory);
            uplayer.Player.inventory.sendStorage();
}
`

**Comment by SDGNelson** [comment]
Mmm I'm not sure, the inventory code is a mess currently sorry ¯\\\_(ツ)_/¯
