### ISSUE TITLE
Stuck at queue #1 ... helppp

### ISSUE THREAD

**Issue by MonsterClown1** [SmartlyDressedGames/Unturned-3.x-Community#377]
every once in a while, the loading screen will be stuck on queue position 1 on some servers, my mouse still work fine and i can press cancel and to move it but it doesn't enter the server no metter how many tries i try to rejoin, i didn't subscribe to any addon on the workshop and I have verified game cache and even tried to reinstall the game, restarted steam, unturned and my PC countless times. I have reduced the resolution and requirements to low and it still does not work... 
pls help meeeeeeee :)

**Comment by MonsterClown1** [comment]
bump

**Comment by SDGNelson** [comment]
Unfortunately I have nothing helpful to say right now, but I had one idea of what the issue might be which will start getting logged in the next update so we can see if it's the problem.
