### ISSUE TITLE
I got Perma-banned for nothing

### ISSUE THREAD

**Issue by ToastyerToast** [SmartlyDressedGames/Unturned-3.x-Community#3771]
I play on a relatively empty server and when I got on, it says I was permanently banned for "BE." When I checked the ID of the player it was banned for, its not my name. It says the ban was for a different guy, so I don't know why I'm also affected in the ban. A helper told me that my IP was the same as the guy that got banned (I don't know if that's possible), so appealing to the ban wouldn't work. Is there any way to unban my IP or change it so that I don't share a random guys ban.

**Comment by sunnamed434** [comment]
Might you need to contact with BE directly? (email, or smth like that)

**Comment by GazziFX** [comment]
I think you see Global ban ID, its not the same as SteamID

**Comment by ToastyerToast** [comment]
So what should I do? I have already emailed them so should I just wait or is there a faster way?

**Comment by sunnamed434** [comment]
> So what should I do? I have already emailed them so should I just wait or is there a faster way?

As a temp solution (while you're waiting), you could just create a new account on steam and continue playing

**Comment by ToastyerToast** [comment]
The Problem is I don't have any access to my base and I'm afraid it will decay if I can't refuel the Generator inside.

**Comment by sunnamed434** [comment]
> access

Tbh, forget about your base, it is gone already, 100% sure that you would be unbanned in a month...

**Comment by MoltonMontro** [comment]
> I play on a relatively empty server and when I got on, it says I was permanently banned for "BE." When I checked the ID of the player it was banned for, its not my name. It says the ban was for a different guy, so I don't know why I'm also affected in the ban. A helper told me that my IP was the same as the guy that got banned (I don't know if that's possible), so appealing to the ban wouldn't work. Is there any way to unban my IP or change it so that I don't share a random guys ban.

Is there a game ban visible on your Steam profile? Are you able to play on other multiplayer servers? Currently, it just sounds like the server banned you, and gave you a misleading ban message that was meant to look like you were banned by the BattlEye anti-cheat.

Here are some relevant support articles:

- https://support.smartlydressedgames.com/hc/en-us/articles/12082986788884-Multiplayer-bans
- https://support.smartlydressedgames.com/hc/en-us/articles/12233962470548--You-are-banned-from-playing-multiplayer-
- https://support.smartlydressedgames.com/hc/en-us/articles/12237672383892--You-are-banned-from-playing-on-VAC-secure-servers-

**Comment by ToastyerToast** [comment]
I can still play on other servers, but I specifically can't play on this one. There aren't any visible game bans on my steam profile either.

**Comment by GazziFX** [comment]
Contact to owner of this server

**Comment by SDGNelson** [comment]
Yes, it sounds like the owner banned you from their server. (not BattlEye / VAC ban) Unturned support cannot override server bans, so your best option for support is contacting the server's moderation team.
