### ISSUE TITLE
Why blocking Asia server? 

### ISSUE THREAD

**Issue by IronManMK47** [SmartlyDressedGames/Unturned-3.x-Community#3772]
If I hadn't checked the blocked pages, I might never have known why my server was not searchable.
I can't understand the server being banned (including Vanilla server copyright infringement?).
We are a Chinese server operating for 6 years (this year is the 7th year).
This ban is unacceptable.We use a wide variety of mods that we've created through unity3d, and we've published amazing projects on Creative Workshop back in 2018 (and got 4 and 5 stars).
Using a mod that our created but was banned for copyright infringement.
I can provide all evidence that the banned servers are using mods that we made ourselves.
We have 10-20 servers,Close to 15 servers that are 100%Vanilla, absolutely fair and charging nothing.
We've been working hard on anti-cheating, we've been working on better anti-cheating plugins, we've been building our own plugins and all kinds of UI to make it a better experience for new players at unturned, and now we've been hit with a lot of abuse.
We are not the best server, we just want to spread this happiness to more players, and let new players in Asia quickly learn about this game, and experience the fun of fair competition in all our servers!
Please reply to me as soon as possible, it is very important~
![Uploading CCGK)7~81D$%OWS%{}C}})L.png…]()

**Comment by IronManMK47** [comment]
Of course, there may be some misunderstandings in this, we did not use the module to earn any money, of course, there may be some negligence of our management staff to use a small number of Creative Workshop files, if there are infringing files, we can immediately delete, we need an accurate reply of infringement

**Comment by GazziFX** [comment]
What server are you talking about?

**Comment by IronManMK47** [comment]
asia&nbsp;server&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月21日(星期二) 凌晨0:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SmartlyDressedGames/Unturned-3.x-Community] Why blocking Asia server?  (Issue #3772)





 
What server are you talking about?

**Comment by IronManMK47** [comment]
asia&nbsp;server&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmartlyDressedGames/Unturned-3.x-Community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 凌晨0:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmartlyDressedGames/Unturned-3.x-Community] Why blocking Asia server?  (Issue #3772)





 
What server are you talking about?

**Comment by GazziFX** [comment]
At first, I did not understand that Asia is the name of the server, then deleted comment

**Comment by SDGNelson** [comment]
The concern here was your server is selling/promoting the sale of 3D-printed models from the vanilla game. If you remove the listing I will remove the warning.

**Comment by IronManMK47** [comment]
i m server owner  my discord id is Asia Studio#3788

**Comment by IronManMK47** [comment]
As for the 3D printing model, our initial intention is to provide Chinese players with an opportunity to love, because Chinese players cannot normally buy your official peripheral products, but there are problems in the post-production process of the factory, and the quality is not up to our standards. We have already refunds all the orders, and I will remove all relevant push-ups from the server later I am very sorry for this

**Comment by SDGNelson** [comment]
Thanks, I have now removed the warning and restored them to the public server list.
