### ISSUE TITLE
Bug (?) with barricades

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3773]
Since barricades are pooled, OnDestroy doesn't get called on custom components.

(BarricadeDrop.CustomDestroy)
![image](https://user-images.githubusercontent.com/12886600/226627064-64672da8-ec84-4392-9536-21452f790723.png)
I see IManualOnDestroy but since it just uses GetComponent it will only call on one component, meaning if more than one plugin or the base game uses it, it could cause bugs... if this was replaced with GetComponents and a loop then it would be a lot more reliable.

Also i know this isnt the place for feature requests but if you could, there is no event for a post-barricade destroyed event like BarricadeManager.OnBarricadeDestroyed or something.

**Comment by SDGNelson** [comment]
Not a bug because the base game only has one component using this interface at a time.

I take it you have a custom component implementing IManualOnDestroy? Out of curiosity what are you using it for?

**Comment by SDGNelson** [comment]
Sorry I'm not sure I understand what you mean. To double-check: you do have a custom component attached to barricades, and you are patching the destroy barricade method to remove the custom component before it is returned to the pool?

**Comment by DanielWillett** [comment]
Yes
________________________________
