### ISSUE TITLE
Explosion damage applying to gameobject center, not to closest point

### ISSUE THREAD

**Issue by Wyvernaed** [SmartlyDressedGames/Unturned-3.x-Community#3775]
Looks like in 3.20.9.0 update explosion starts using closest point rather than gameobject origin but either i didn’t even notice it, or it was always buggy, but the exlposion damage still applying to the center.

https://youtu.be/dnE-xgrQ_1s

**Comment by SDGNelson** [comment]
Unfortunately it still depends whether the pivot of the vehicle/object/character/etc is within radius of the explosion center. 😞  Perhaps it should just use a sphere overlap in the future.
