### ISSUE TITLE
Move vehicles to server-side

### ISSUE THREAD

**Issue by kaposzta99** [SmartlyDressedGames/Unturned-3.x-Community#3776]
In https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1968 it's stated that moving vehicles to server-side is possible.
Can anyone provide me some example code?

**Comment by SDGNelson** [comment]
If you set the vehicle's transform.position without a driver it will move, however off the top of my head moving while driven is not currently supported.
