### ISSUE TITLE
Editor Asset Redirectors for Resources

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#3777]
Currently Asset Redirectors support object GUIDs. You can replace objects fine, but you can't do the same with trees. I'm currently in a situation where I need to replace a lot of custom placed trees however this Redirector only works for objects. It would be awesome if it would work for resources as well. Thank you

**Comment by SDGNelson** [comment]
Yes, I'd like to add support for them to other asset types. Closing since this is more-so a feature request but feel free to post in the suggestions/ideas discussion.
