### ISSUE TITLE
Helipads dont having spawns for vehicles?

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3778]
I'm sorry if this is not a bug and is just intentional, but are some helipads just placed in there to be decorative? I mean the next ones:

At Belfast Airport tank fuels, PEI
At Seattle highest tower, Washington
At Scorpion-7 tank fuels, Washington

None of those have actual spawns for vehicles, maybe would be cool to have vehicles in there spawning? so PEI could have another heli to spawn rather than just the mili heli, and Washington could have the Skycrane on the Scorpion spawn? if it's just intentional its fine, just having the doubt!

**Comment by SDGNelson** [comment]
They were originally intended just as decorations yes. A nice place to land a helicopter if you happen to have one. I don't currently plan to add more vehicle spawns to those maps but perhaps in the future when improving vehicles.
