### ISSUE TITLE
Fallback font not working for tracked quest name

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3779]
Japanese, Chinese, and Korean text doesn't appear in the tracked quest name. Every other location (e.g., the quest list... quest pop-up menu...) seems fine. My assumption is that it's just an issue with that UI element and Noto Sans CJK.

![image](https://user-images.githubusercontent.com/7608445/228013693-603e1120-8fbe-4f1d-a774-616b350814f6.png)

_Originally reported on the forums: https://forum.smartlydressedgames.com/t/translation-file-is-not-reflecting-properly/22402_

**Comment by SDGNelson** [comment]
Thanks, it seems the title text doesn't have enough vertical space for Japanese, fixed and will credit nemukopic in the changelog.
