### ISSUE TITLE
Queue position 1 errors, in depth..

### ISSUE THREAD

**Issue by themisfitgames** [SmartlyDressedGames/Unturned-3.x-Community#378]
Hello Nelson, 

As of late I've had several players of a community I somewhat co-own reach out to me and inform me that they aren't able to connect to any of my servers or other servers on Unturned due to a threading error which a log will be posted in attachments from one of them, could you please help me so that I can assist them with resolving this issue at hand?

Thanks!

[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2261147/Client.log)

**Comment by SDGNelson** [comment]
Those errors are unrelated unfortunately. Occasionally this version of A* pathfinding project has trouble ending those threads when exiting the map.

I had one idea of what the issue might be which will start getting logged in the next update so we can see if it's the problem.
