### ISSUE TITLE
Bug with admin camera

### ISSUE THREAD

**Issue by ymo-4** [SmartlyDressedGames/Unturned-3.x-Community#3780]
When player is in admin camera (and/or using admin wh) and not admined, camera can only be disabled by changing perspective, wall-hack cannot be disabled in any way. But I think camera and wh should automatically disable when unadmin.

https://www.youtube.com/watch?v=_2sPuwSxgzs

**Comment by SDGNelson** [comment]
This should probably be changed, but there are a variety of admin and admin-tool related improvements I'd like to make. For example currently the isAdmin flag doesn't use RPCs, and the server doesn't know whether admin cam is being used. No ETA, sorry.
