### ISSUE TITLE
[Editor] Problem with Foliage

### ISSUE THREAD

**Issue by OboemaUnt** [SmartlyDressedGames/Unturned-3.x-Community#3781]
After reinstalling Windows and updating the game itself, when using Foliage, my vegetation cursor is only in the middle of the map, it cannot be moved, no matter how much I press the mouse and keyboard. This works on all cards, even on PEI, I don’t know what to do and changed to an older version of the game, and nothing works for the latest one, Steam closed and opened, rebooted the PC, did file verification, reinstalled the game, nothing helps at all from above listed. If anyone knows what's wrong, please tell me!
![image](https://user-images.githubusercontent.com/129435659/228938182-a8b2d9d0-f01d-4a49-86e8-9c98aa84a9c8.png)

**Comment by SDGNelson** [comment]
Closing because this was also submitted as a support ticket. For anyone who runs into the same issue: setting Surface Mask to 1802240 should fix it. I need to make that field properly configurable.
