### ISSUE TITLE
Barricades like Rifle Racks not using skins when directly interacting with them

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3782]
Normally when opening an storage like sentries and rifle racks, you do open the storage and put items in there, and if you have a skin for a gun it will be shown there. Now, if you directly take an item inside of it by pressing CTRL + F, items inside won't show your skins

https://streamable.com/w8l30j

**Comment by SDGNelson** [comment]
Thanks for the report, but will not plan to change this currently. The item inside the storage doesn't track who placed it there, rather when the displayed item is added the storage itself tracks the skin used by the owner.
