### ISSUE TITLE
PEI map looking like Sonic levels

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3784]
Very self descriptive
https://streamable.com/cbhj7a

![2023-03-31_21-58-08](https://user-images.githubusercontent.com/57012631/229260594-48c36116-82e1-401b-aa24-7ceae791d6b7.png)

![image](https://user-images.githubusercontent.com/57012631/229260567-3dd8ab56-5217-4226-a167-c0a62447738a.png)

**Comment by ItsRodrigoAl** [comment]
wait, no way this is an april fools joke...

**Comment by MoltonMontro** [comment]
PEI is configured to use these materials during April Fools'.
