### ISSUE TITLE
Reset button get stuck between servers after quitting servers with "Can Suicide" config disabled

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3785]
If you join a server with "Can Suicide" config option set to False, you can press the Restart buttons but they won't do anything. Also if you quit the server and go to another one where "Can Suicide" config option is set to True, then the button will be blocked as it had to be on the previous non-suicidable server. This seems like is not affecting single player worlds

https://streamable.com/onw888

**Comment by SDGNelson** [comment]
Thanks for the report! It sounds like the UI is created before the setting is received from the server. I'll see about getting this fixed.
