### ISSUE TITLE
Game requires to drop/unequip the items to refresh "Item Icon Anti-Aliasing" graphics setting per item

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3786]
Items on your inventory aren't updated with the "Item Icon Anti-Aliasing" option, however items on ground are updated or they need to be moved from your hands to your inventory to be updated. Is this a bug or is intentional? The UI scale was increased to notice better the anti-aliasing

https://streamable.com/opnhis

**Comment by SDGNelson** [comment]
Unfortunately yes this is low priority to fix - currently the existing icons are not refreshed when the setting changes. For the meantime restarting the game is required.
