### ISSUE TITLE
Wrong connect callback order for first player connecting to server

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#379]
It's supposed to be
`Provider.onCheckValid` then ` Provider.onServerConnected`
However it's vice versa for _the very first_ player connecting to server

**Comment by SDGNelson** [comment]
onCheckValid is called once Steam Authentication data is received by the server, which is one of three prerequisites before accepting a connection (after which onServerConnected is called). onServerConnected could be called if a plugin is using Provider.accept directly, or by the test "ad" CommandQueue option. Is your plugin directly accepting players?

**Comment by aviadmini** [comment]
Nay, my plugin is applying some changes to steamPending in onCheckValid callback
I noticed that it totally doesn't work for first player connections to server and figured out that callback order is wrong

**Comment by SDGNelson** [comment]
Double-checked on a test server, and can verify that onCheckValid is fired before onServerConnected for first and subsequent players in the vanilla game.

**Comment by aviadmini** [comment]
Confirmed: I was wrong about `onCheckValid`

However it turned out that I used something different that has weird behaviour
