### ISSUE TITLE
Can't get player's camera

### ISSUE THREAD

**Issue by kaposzta99** [SmartlyDressedGames/Unturned-3.x-Community#3790]
```
UPlayer.GetComponent<Camera>();
Player.look.characterCamera;
Player.gameObject.GetComponent<Camera>();
```

I need it for the WorldToScreenPoint function, but seems like all of these return null.

**Comment by GazziFX** [comment]
Not sure if this function works because server has no graphics, and also it will be misaligned with client side because of different fov and aspect ratio

**Comment by GazziFX** [comment]
To check if player facing specified direction you can try Vector3.Angle or Vector3.Dot
