### ISSUE TITLE
Loading screen tip outdated

### ISSUE THREAD

**Issue by NickSkunk** [SmartlyDressedGames/Unturned-3.x-Community#3792]
The Tip says:
Tip: Your crafting materials impacts stats from best to worst are: Metal -> Brick -> Pine -> Maple -> Birch

When it should be:
Tip: Your crafting materials impacts stats from best to worst are: Brick -> Metal -> Pine -> Maple -> Birch

**Comment by SDGNelson** [comment]
Fair point, thanks for the report. I will flip that order and then probably forget when the balance is adjusted again in the future!
