### ISSUE TITLE
Hacks allow to destroy/kill/loot stuff through walls

### ISSUE THREAD

**Issue by P9ndx** [SmartlyDressedGames/Unturned-3.x-Community#3793]
I am pretty sure its known but it has increasingly become a problem where hacks allow users to shoot beds, crates or even players through base walls. They can also access storage through walls or pick up loot that is dropped on the floor there and it has been ruining people's experience. There needs to be something done about this. Even when identifying and banning the hacker, they will just spoof their HWID and join with a new account to cause enough damage again.

**Comment by QERT2002** [comment]
It's fixed long time ago, use your own anti-cheat if you want idk :/

**Comment by P9ndx** [comment]
It is still happening, so it has obviously not been fixed.

**Comment by GazziFX** [comment]
Try on my server

**Comment by GazziFX** [comment]
Server authoritative shooting will require rewriting a bunch of stuff
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2697#issuecomment-878451156

**Comment by SDGNelson** [comment]
The server does a line-of-sight test for bullet impacts, but it relies on the initial hit information reported by the client. The server does some basic validation of the hit submitted by the client, for example that the point of impact was within 16 meters of the hit player's current position if not inside a vehicle. Servers that claim to have "custom anti-cheat" are typically tightening these built-in limits beyond my recommendations. For example a player sent flying by a bounce charge wouldn't be shootable by someone with high ping. My linked comment still applies here: at some point increasing the input rate and/or basic rollback on the server will allow the vanilla limits to be clamped down.

Meanwhile cheat developers like GazziFX are happy to play both sides. 🤡
