### ISSUE TITLE
Server Private Anti-Cheat

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#3794]
Hello again, how are you? 😃

I started to develop an anti cheat for my server (it won't be mandatory for players to have it), but I'm on the back foot, I'm afraid it could cause a ban on steam. Should I be concerned?

What the software does (in the initial version):
-Prints of the Unturned screen.
-List of processes.
It is a portable EXE file, for Windows only.
It is not necessary to install much less put it in the unturned folder, anywhere on the computer for the "Telemetry of the cited data"

About GDPL (General Data Protection Law):
Yes, everything is within the terms I do not take personal data or files, nor do I search the computer, I only analyze the unturned screen by prints, and the list of processes.

**Comment by GazziFX** [comment]
It wouldnt cause a ban until you replacing game files, accessing memory or loading unsigned drivers

**Comment by GabrielMaestre** [comment]
> Não causaria uma proibição até que você substituísse os arquivos do jogo, acessasse a memória ou carregasse drivers não assinados

Thanks for the explanation, is there anything else that could cause problems, or just that?
(Anti-Cheat) will not mess with any of those parts you mentioned

**Comment by sunnamed434** [comment]
> About GDPL (General Data Protection Law):
> Yes, everything is within the terms I do not take personal data or files, nor do I search the computer, I only analyze the unturned screen by prints, and the list of processes.

I don't think it's such a big problem, e.g Battleye doesn't care about it, they could do whatever they want until unturned is running with Battleye

One of the problems you may run into is that your anticheat is installed locally, and you need to protect it, for example, obfuscation

On the other hand, you may run into issues if your anticheat is a client Module, battleye won't pass it 

Good luck with it 👍

**Comment by GabrielMaestre** [comment]
> > About GDPL (General Data Protection Law):
> > Yes, everything is within the terms I do not take personal data or files, nor do I search the computer, I only analyze the unturned screen by prints, and the list of processes.
> 
> I don't think it's such a big problem, e.g Battleye doesn't care about it, they could do whatever they want until unturned is running with Battleye
> 
> One of the problems you may run into is that your anticheat is installed locally, and you need to protect it, for example, obfuscation
> 
> On the other hand, you may run into issues if your anticheat is a client Module, battleye won't pass it
> 
> Good luck with it 👍

Thanks for the answer!

The intention is that players still use Battle Eye, but along with mine
Anti-Cheat.

Yes, it will be obfuscation, and I'm developing in C#
The biggest concern I'm having is when taking a screenshot of Unturned, I don't know if this could be a problem, that's why I asked here, but thank you very much for your answer!

**Comment by sunnamed434** [comment]
> The biggest concern I'm having is when taking a screenshot of Unturned, I don't know if this could be a problem, that's why I asked here, but thank you very much for your answer!

I think it depends on what kind of users will use your anticheat, anyway I'm sure you don't need to care about it, just less speak about screenshotting something, because it could be a big problem, people could start to resent, your goal is protect - how it works they doesn't need to know

**Comment by GabrielMaestre** [comment]
> > A maior preocupação que estou tendo é na hora de tirar screenshot do Unturned, não sei se isso pode ser um problema, por isso perguntei aqui, mas muito obrigado pela resposta!
> 
> Acho que depende de que tipo de usuário usará seu anticheat, de qualquer forma, tenho certeza que você não precisa se preocupar com isso, muito menos falar sobre fazer screenshots de algo, porque pode ser um grande problema, as pessoas podem começar a se ressentir, seu objetivo é proteger - como funciona, eles não precisam saber

Alright, thanks again for the answer, I'm less worried about it. Thank you friend

**Comment by SDGNelson** [comment]
If it doesn't tamper with Unturned or BattlEye then it's probably fine. Once it's ready it may be worth contacting BattlEye support so that they are aware what it is.
