### ISSUE TITLE
Unturned workshop problem

### ISSUE THREAD

**Issue by Alex998878** [SmartlyDressedGames/Unturned-3.x-Community#3795]
So whenever i try to upload my npcs to workshop for my server it says failed to submit

**Comment by sunnamed434** [comment]
Any screenshots of what you're trying to do? Sometimes it happens when path is incorrect

**Comment by Alex998878** [comment]
i chcked the path serval times it was correct

**Comment by SDGNelson** [comment]
Could you attach Steam's workshop_log.txt file described in this article please? https://support.smartlydressedgames.com/hc/en-us/articles/14696825041684

**Comment by Alex998878** [comment]
this is the latest [2023-04-08 15:29:07] [AppID 304930] GetDetails request 0xab - batch (0-5 of 5) => not in cache, requesting from Steam
[2023-04-08 15:37:34] [AppID 304930] GetDetails request 0xaf - batch (0-1 of 1) => not in cache, requesting from Steam
[2023-04-08 15:53:11] [AppID 304930] Create new workshop item of type Community for AppID 304930 : 2959367401 (OK)

**Comment by Alex998878** [comment]
After this it also says Failed to submit

**Comment by MoltonMontro** [comment]
According to this message, your Workshop item was successfully created:

> [2023-04-08 15:53:11] [AppID 304930] Create new workshop item of type Community for AppID 304930 : 2959367401 (OK)

It looks like you haven't accepted the latest Steam Workshop Agreement. You can do so from here: https://steamcommunity.com/workshop/workshoplegalagreement/

**Comment by Alex998878** [comment]
Worked thanks so much
