### ISSUE TITLE
Outdoors skill wrong description

### ISSUE THREAD

**Issue by P9ndx** [SmartlyDressedGames/Unturned-3.x-Community#3796]
The outdoor skills which is supposedly just increasing the resource damage, will also grant you more drops when destroying any resource such as tree or metal. When having the skill maxed it seems to drop ~1.5x of what it usually would. If you set the Reward Min and Max to "1" it will already drop 2 items if you have Outdoors on Level 1. Either the description of the skill is wrong, or it has a (pretty useful) side feature.

**Comment by MoltonMontro** [comment]
(Verified this with P9nda earlier. Outdoors skill gives a hidden, guaranteed **+50% resource drops** in addition to the mentioned +50% resource damage.)

**Comment by SDGNelson** [comment]
Thanks for the report! Will fix.
