### ISSUE TITLE
Bug-Fixing Suggestion - Checker for placeables if they are despawned or not

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3797]
Hopefully this issue is relevant on GitHub, as it correlates to a bug I encountered. This issue is also a small follow-up on a previous issue. Link is here if interested:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3750

Using non-plugin methods to recreate Unturned 2.0 MOAB placeables, it is successful to an extend. Throughout testing, the placeable is thought to be despawned when detonated. When re-entering its render distance, the placeable respawns, although it does not detonate again. My guess is that it doesn't update through the server properly, but I'm not entirely sure.

A good fix, or fallback depending on how this is viewed, is to give placeables a checker to see if they are alive or not. ATM, it seems that the alive or dead states of placeables are only updated if destroyed by players or zombies.

**Comment by SDGNelson** [comment]
Are you using that Grenade component for an explosion on a barricade? It sounds like the prefab is getting destroyed which will not update the code responsible for instantiating/destroying barricades.

**Comment by SDGNelson** [comment]
In that case for a placeable time bomb the best option at the moment would be a plugin to keep track of the timer and trigger an explosion.
