### ISSUE TITLE
Named locations, and nodes file doesnt save

### ISSUE THREAD

**Issue by MeedicBear** [SmartlyDressedGames/Unturned-3.x-Community#3798]
Whilst i am making a map im adding location nodes to my towns, they show up on the map but when i upload my map the my server, i cant teleport to the nodes.

I have found that the Nodes.dat file doesnt save with any data other than [this](https://i.imgur.com/OdWyVlY.png) , from my understanding this means my server cant interact with the nodes?

I understand the names show up because they are located in the Level.hierachy file.

What am i missing or is this a bug?

**Comment by GazziFX** [comment]
IIRC they have been moved to other file, for plugins you can access them by `LocationDevkitNodeSystem.Get().GetAllNodes()`

**Comment by GazziFX** [comment]
Created pull request https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/pull/61 to fix it in Rocket

**Comment by SDGNelson** [comment]
GazziFX is correct that it depends whether the teleport command you are using handles the rewrite that got rid of all the old node types. If you use the vanilla "/teleport" command it should work properly.
