### ISSUE TITLE
Sights on Maschinengewehr hides the kill counter attachment

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3801]
It doesn't happens with zoomed sights, just for those that doesn't have zoom like the Dot, Kobra and Halo ones, this means the kill counter on the gun should be moved to do not be hidden

![2023-04-11_00-51-52](https://user-images.githubusercontent.com/57012631/231077275-e77916fe-68dc-49b5-b2a9-53428db92da0.png)

![2023-04-11_00-51-44](https://user-images.githubusercontent.com/57012631/231077280-46438402-02f0-4e35-a77f-9f96e6ea4517.png)

**Comment by SDGNelson** [comment]
Thanks for the report! This should be moved.
