### ISSUE TITLE
Not enough space on UI for translations

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3802]
There's so much free and useless space on some parts of the current UI's, making it the translation to another language a bit difficult. For example, I've been translating literally the whole game to Spanish (hopefully this translation could be even the official one for the game) but I've noticed this issues with the UI where some important buttons seems to be REALLY small compared with the rest of free space from other buttons

On this example, I had to cut the words "Sintonizar" to "Sinton." and "Reiniciar" to "Reinic.", but as you can see on the main radio frequency button there's like a mega free space, just to put 6 numbers
![image](https://user-images.githubusercontent.com/57012631/231079308-19eb5f65-2d58-4ff2-a107-5841a362b41b.png)

On this one I've had to cut the word "Expulsar" to "Expul." and this also happens with the others Spy and Slay buttons which are shown when you're admin, and **again** there's a lot of useless space for the nicknames
![image](https://user-images.githubusercontent.com/57012631/231079766-8109d4fb-1a5e-41fa-a97c-fff1a523aac3.png)

And on this one I've had to cut the words "Jugadores" to "Jugad." and "Latencia" to "Laten.", but then the space for the server names and description (which are capped to only 50 letters both) have that giga and useless free space to put... nothing (?
![image](https://user-images.githubusercontent.com/57012631/231080233-cfd70fea-f67f-4558-9c92-61acc8ec45ad.png)

I saw this same issue happened with another translations for Korean/Japan language (I don't remember) where the Quest text space had to be reworked to fix it, well this issue is basically the same

**Comment by SDGNelson** [comment]
Sorry about this. Currently the UI has no automatic layout, so everything is designed around allocating as much space as possible to whichever element might need to expand, especially considering players with low resolutions. In the future when/if automatic layout is added (probably with UIElements update) some UIs will start being redesigned to take advantage. The Japanese/Korean text fixes were specifically about a lack of vertical space preventing any text from displaying.
