### ISSUE TITLE
Leaving vehicle sometimes spawns you on default spawn.

### ISSUE THREAD

**Issue by HarryBGamer2570** [SmartlyDressedGames/Unturned-3.x-Community#3804]
When you have parked the vehicle in your base and exit it and there's nowhere where to place the player it chooses a random spawn as if you died and just puts you there.

This has happened to me twice for now and I don't know if this is intentional or not, but sometimes is can be very annoying when it spawns you on the other side of the map and you have to walk all the way to your base if you don't find a vehicle on the way. And if it is indeed intentional, I think it would be better if it just didn't let you leave until you can safely exit the vehicle. Of course, then there's a chance that you cannot move the vehicle, then I'd suggest that it puts you in "crowched" or "laying down" position somewhere around the vehicle.

**Comment by SDGNelson** [comment]
Yes, this is intentional. The game tries to find a valid exit position, but if none is available it would suck to be permanently stuck in a vehicle.

**Comment by CyberAndrii** [comment]
What about `Hold F to teleport to a spawn` instead of instant teleportation?

**Comment by rube200** [comment]
That would be good, something like 'there is no spa e to peace the vehicle long press f to be teleport to spawn

**Comment by SDGNelson** [comment]
Making it optional is a nice idea. Currently it only does the exit placement checks when trying to exit because it would be expensive to run every frame. No ETA but it might happen in the future.

**Comment by educatalan02** [comment]
It would be better to just not let you exit the vehicle when no there is no space

**Comment by rube200** [comment]
> It would be better to just not let you exit the vehicle when no there is no space

That is very bad, imagine for some reason tires broke or u empty your gas, this cases can be este but we need to always prevent it stuck players
