### ISSUE TITLE
issues with Shared_Skin_Lookup_ID

### ISSUE THREAD

**Issue by NickSkunk** [SmartlyDressedGames/Unturned-3.x-Community#3806]
Sorry if this is as intended but I did some testing with my "Steampunk 0 Kelvin Arctic Luger w/ Killcounter" skin.

On the vanilla luger everything works as expected

On a mod gun with Shared_Skin_Lookup_ID 1476 in the dat file:
The kill counter is invisible (being inside of display storage the kill counter can be seen)
The 0 Kelvin effect does not work
everything else works as expected

I know this issue happens with other guns as well

it would be nice if this was fixed so I and others could make modified vanilla gun mods that still have the cool effects

**Comment by SDGNelson** [comment]
Thanks for the report. Interesting point. There must be a few places that use the item's ID rather than the shared skin ID. I'll see about getting that fixed.
