### ISSUE TITLE
GSLT tokens for favorites 

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#3807]
I believe this was a planned feature before but I have just tested it and it doesn't appear to work. Is this something that can be added?

Could servers Favorited by users be bound to the server Login token rather than IP and port. Would make it a lot easier for server owners to move machines/upgrade hardware without needing to worry about an IP change.

**Comment by ItsRodrigoAl** [comment]
YES, PLEASE

**Comment by SDGNelson** [comment]
Favourites transferring with GSLT seems to be a rumour/myth around them, I'm not sure whether it is true or not. I've heard some hosts have it work for them and others not - it might be a matter of time.

Unturned uses the Steam server list Favourites for tracking these. It only saves the IP+Port, but supposedly Steam might internally adjust the saved IP+Port to match the new server at some point.

The game could track the server's Steam ID which persists with GSLT, but until the requirement for joining by IP+Port is removed it would have no way to query the server without refreshing the entire server list.
