### ISSUE TITLE
Legacy parse color ignores blue flag

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#3808]
For example, `Laser_Color_B` is ignored and using the default value.

Problem is here, `key` was not added, so it's only checking `_B`
https://github.com/Unturned-Datamining/Unturned-Datamining/blob/9224d215d2ab4ea4265e32a3ef8eec5043d45021/UnturnedDat/SDG.Unturned/UnityDatColorEx.cs#L185

**Comment by DiFFoZ** [comment]
Is also not working for legacy vector parse
https://github.com/Unturned-Datamining/Unturned-Datamining/blob/9224d215d2ab4ea4265e32a3ef8eec5043d45021/UnturnedDat/SDG.Unturned/UnityDatEx.cs#L109

**Comment by DanielWillett** [comment]
beat me by a minute lol, yeah same issue here.

Examples:
 Cyan laser
![image](https://user-images.githubusercontent.com/12886600/232122954-ac96a57c-d925-42a3-a925-1c1948cda9c9.png)
![image](https://user-images.githubusercontent.com/12886600/232123020-120d5d62-5cb7-4ed9-a0c0-1dfd79a956c0.png)
Older image of the same laser:
![image](https://user-images.githubusercontent.com/12886600/232123948-57df0aba-bbfa-44d4-92be-492d8a6e251b.png)

 Magenta laser 
![image](https://user-images.githubusercontent.com/12886600/232123113-5faa12ed-b700-4a89-9e9b-ce31e47dd6ca.png)
![image](https://user-images.githubusercontent.com/12886600/232123171-e391ba91-e287-4147-9724-d95cfc496cb8.png)

Night vision scope (should be blue)
![image](https://user-images.githubusercontent.com/12886600/232123334-ffe4d6c1-e905-45fa-b013-12f1b168a61b.png)
![image](https://user-images.githubusercontent.com/12886600/232123363-ea797916-5d2f-44fd-83a4-b9657cfd7d2c.png)

**Comment by SDGNelson** [comment]
Uh oh! Sorry about this. Thanks for the report! I will fix in a patch, or in the meantime another option is to set the colors in this style:
`Laser_Color #00ffff`
or
```
Laser_Color
{
    R 0
    G 255
    B 255
}
```

Of course those are the two methods that ended up without unit tests :|
![image](https://user-images.githubusercontent.com/12567645/232127219-9fa0e6bc-dbc1-496c-a11a-52bdae18e28b.png)

**Comment by sunnamed434** [comment]
> Uh oh! Sorry about this. Thanks for the report! I will fix in a patch, or in the meantime another option is to set the colors in this style: `Laser_Color #00ffff` or
> 
> ```
> Laser_Color
> {
>     R 0
>     G 255
>     B 255
> }
> ```
> 
> Of course those are the two methods that ended up without unit tests :| ![image](https://user-images.githubusercontent.com/12567645/232127219-9fa0e6bc-dbc1-496c-a11a-52bdae18e28b.png)

Unturned now unit tested? How long?

**Comment by SDGNelson** [comment]
@sunnamed434 Unturned has been using some form of automated testing for a long time now with some small amount of unit testing, and gradually any rewritten features over the past few years have more automatic testing. In particular the networking code and now asset parsing have a lot of tests.

**Comment by sunnamed434** [comment]
> @sunnamed434 Unturned has been using some form of automated testing for a long time now with some small amount of unit testing, and gradually any rewritten features over the past few years have more automatic testing. In particular the networking code and now asset parsing have a lot of tests.

Cool to hear that

**Comment by SDGNelson** [comment]
By the way regarding the issue: I am just waiting a bit to see if any other problems are reported. So far nothing else. Avoiding a .2 patch if possible.

**Comment by DanielWillett** [comment]
all good, thanks for the quick response.

**Comment by SDGNelson** [comment]
Released the fix now 👍
