### ISSUE TITLE
Changing range of generators

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#381]
When I change the range of generators directly in the files, some physical or visual bugs like the new range or even I have to stop the generator and start working again.

not being able to change a range like this:

typeof(ItemGeneratorAsset).GetField("_wirerange", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(ItemGeneratorAsset Gen, (Single)99);

**Comment by SDGNelson** [comment]
Not sure what the actual question is. If you're trying to override _wirerange serverside that won't work because what's currently powered is locally determined as well. (Server authoritative for things like doors though)
