### ISSUE TITLE
Update link in Unturned/Bundles/Sources/README.txt

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3811]
README link goes to old-markdown-docs branch.

`https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GettingStarted.md#Getting-Started` should probably be something like **`https://docs.smartlydressedgames.com/en/stable/about/getting-started.html`** instead.

**Comment by SDGNelson** [comment]
Good catch on this and the server scripts, thanks! I'll get these fixed for the next update.
