### ISSUE TITLE
Grass Shader not affected by wind direction

### ISSUE THREAD

**Issue by DerSpeedMann** [SmartlyDressedGames/Unturned-3.x-Community#3812]
Wind direction used to check weather effects does not affect grass.
The wind direction used in the grass shader does not seem to change at all.
The video shows wind coming from infront of me, whilst the grass is still swaying left to right.

https://user-images.githubusercontent.com/38493853/232178133-4aadde51-72f5-45b6-ad06-e22a214c0f40.mp4

**Comment by DerSpeedMann** [comment]
Or i guess if you know any way that could be fixed for custom objects, that would already help a ton

**Comment by SDGNelson** [comment]
Unfortunately the grass predates the wind and has not been updated yet, but doing so is on the roadmap: https://trello.com/c/cSOvYqDJ/20-unify-wind
