### ISSUE TITLE
Manually restarts doesn't search for patches updates

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3813]
I have a server where I have to manually update it since leaving it automatically will make it crash. However, I noticed that no matter how much times I did restarted it, it was just updated to the v3.23.6.0 and not to the latest patch v3.23.6.1, so nobody was able to join. After +14 hours trying over and over again and waiting for it, I decided to enable the auto-updates from the server config `"Enable_Update_Shutdown": true`, and finally the server got the patch update, this means that manually restarts only search for main updates and not for patches

**Comment by SDGNelson** [comment]
Running "app_update" in steamcmd is what actually downloads the update/patch. If your server is crashing please submit a crash report here: https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash
