### ISSUE TITLE
Show Blood Splatters should be moved to Graphics instead of Options

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3814]
I'm pretty sure most of Unturned players always had this confusion, not only because I always had it but also my friends still have it today like "hey man where can i disable the blood thing? i just do not find it - its on Options, not on Graphics - oh okay". Also this should be on Graphics since enabling the Blood Splatters adds a LOT of lag when you're playing on PvP servers, so if disabling it will prevent you having lag, then the Graphics is the most appropriate page for it

_I know this is not a bug at all, but it may be considered a common issue maybe? If no, then I have no problem in moving it to Discussions-Ideas in order to add it only if Nelson actually likes the idea :D_

Concept
![image](https://user-images.githubusercontent.com/57012631/232200563-c84c89f8-e1ba-463b-b968-bd5b098f10bb.png)

**Comment by SDGNelson** [comment]
Subjective. Would like to reorganize the options menus with a search bar someday.
