### ISSUE TITLE
Adding "{0}" for Rarity lines for PlayerDashboardInventory.dat translation

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3815]
So I had this little problem when translating the game to Spanish, and It's basically the order of the types of items along with their rarity that can not be changed in order to be correctly translated to Spanish. On the default translation files it is showed like this:

![image](https://user-images.githubusercontent.com/57012631/232201411-e8d639fc-57a8-42cc-ac20-55647293653b.png)

This makes show the items in this way: "Rare Food", which is completely fine on English:

![image](https://user-images.githubusercontent.com/57012631/232201549-77a0c929-74af-43ec-9ea6-ad558a066a5c.png)

But what happens in Spanish is that you need to set first the type of item and then the rarity (_like "Food Rare"_), and a way to fix it is adding a {0} to the item rarity, like this:

![image](https://user-images.githubusercontent.com/57012631/232201998-25b7995c-18d8-4338-856c-369e67a50291.png)

Adding this {0} to identify the Rarity and then the Type adds the possibility to order it in another way, so in Spanish It could be translate on It's correct way like this:

![image](https://user-images.githubusercontent.com/57012631/232202408-c61ea459-3618-4397-bf66-79a75ee1a8c1.png)

So in this way it could be correctly translated "Comida Rara" (Rare Food, fine) instead of "Rara Comida" (Food Rare, wrong). I have seen this on multiple lines of the translations files, so adding it to these lines would be appreciated!

**Comment by SDGNelson** [comment]
The order of these is controlled by  the `Rarity_Type_Label` key
