### ISSUE TITLE
Car going through walls

### ISSUE THREAD

**Issue by Chenennn** [SmartlyDressedGames/Unturned-3.x-Community#3816]
Me and my friend found a glitched where the car is able to no clip through any walls and structures. There is a glitch where I sit out of the car but I am still able to control it. When I drove it away from my render distance, the car then started to go through the structures. 

![image](https://user-images.githubusercontent.com/130845868/232227695-3dadc968-949b-4751-a923-432c94f1fc69.png)

Video of it: https://www.youtube.com/watch?v=XVTR2gdKRYE

**Comment by SDGNelson** [comment]
Sorry to say floating outside the vehicle like this is a known issue, but I haven't been able to narrow down a cause or recreate it. (https://support.smartlydressedgames.com/hc/en-us/articles/12298639522452-Floating-outside-vehicle-bug) After that article was posted I bullet-proofed what I thought were possible causes and tried artificially recreating some situations for example rollback when entering vehicle, but no luck. If you know any way to recreate it that would be greatly appreciated. 😞
