### ISSUE TITLE
Shared_Skin_Lookup_ID skins counter kills do not count

### ISSUE THREAD

**Issue by NickSkunk** [SmartlyDressedGames/Unturned-3.x-Community#3817]
sorry about this again SDG, and extra apologizes if this is intentional to work this way!

using a modified gun with Shared_Skin_Lookup_ID 140 (butterfly knife) and Shared_Skin_Lookup_ID 1476 (luger)
and testing by spawning and killing animals 1-7 and dozens of different naturally spawned zombies, the counter never ticked up.

The same situation was also tested with the vanilla butterfly knife & luger and they worked as expected.

I am unable to test the player kill counter, though I suspect it has the same issue, the issue may also apply to other items as well i suspect such as the beans and detonator

**Comment by SDGNelson** [comment]
Sorry about that! I must have missed a spot when fixing Shared_Skin_Lookup_ID for kill counters and ragdoll effects, will investigate.
