### ISSUE TITLE
Problem with Phantox Timberwolf skin and a small comment about Makeshift Scope and Muffler

### ISSUE THREAD

**Issue by Semidvista** [SmartlyDressedGames/Unturned-3.x-Community#3818]
Hello
There is a problem with the Phantox Timberwolf skin, instead of turning black, this skin turns gray
Looking at how all the other skins of the Phantox series look like this looks like a problem
![Screenshot_233](https://user-images.githubusercontent.com/130897671/232288843-6ca172a8-f29e-4bec-ad38-baa92d5d2d12.png)
![Screenshot_234](https://user-images.githubusercontent.com/130897671/232288848-27e5964e-47f1-4c65-9cc1-a35cba211c31.png)
![Screenshot_235](https://user-images.githubusercontent.com/130897671/232288850-5d73c6fc-6890-4235-aba1-32dcad34258b.png)
![Screenshot_236](https://user-images.githubusercontent.com/130897671/232288851-f1edc19c-630e-402c-80c7-9798859f1c03.png)
![Screenshot_237](https://user-images.githubusercontent.com/130897671/232288855-01bdee10-a856-49a0-8e9e-c8f3d4ecc14c.png)
![Screenshot_238](https://user-images.githubusercontent.com/130897671/232288858-45e4d752-b33c-439d-b7f5-62bd9c1cef37.png)
I also want to add a few words about Makeshift Scope and Muffler
Adding just one line "Paintable" to their .dat config file would allow these items to look incredibly beautiful on skins in the game.
![Screenshot_239](https://user-images.githubusercontent.com/130897671/232289217-68593de8-6dcc-4f03-a2fd-616303a33f25.png)
![Screenshot_240](https://user-images.githubusercontent.com/130897671/232289221-8dc18240-564a-4804-85b9-c85cd183b15c.png)
![Screenshot_241](https://user-images.githubusercontent.com/130897671/232289223-0361ae1b-3286-4a81-ad77-0951fa4df5c0.png)
Especially on those where they are used most often (Sportshot, Schofield and Hawkhound)
![Screenshot_242](https://user-images.githubusercontent.com/130897671/232289250-5d491913-c255-488b-aee9-3c7e5a3db646.png)
![Screenshot_243](https://user-images.githubusercontent.com/130897671/232289253-6e528c40-db83-40ef-b263-266be6e6b833.png)
![Screenshot_244](https://user-images.githubusercontent.com/130897671/232289256-b6f4973e-51fe-4547-8e65-41ce069d8e9a.png)
These items can be crafted on any of the vanilla maps in the game (even the Yukon), so there will never be a moment when you won't be able to access them.
I think this change will allow these items not to stand out from the general appearance of the skin, since it is very ugly when the entire skin is completely painted and full of colors, and the item worn on it is not painted in any way
Also, it will motivate people to buy skins in general, as they will generally look better, plus they will buy skins on Sportshot, Schofield and Hawkhound much more often, because, as I said, they are used most often on these weapons
Let me remind you how these items look now
![Screenshot_245](https://user-images.githubusercontent.com/130897671/232289591-3b4edb79-59a2-41e3-b18f-3a8e13bd8e38.png)
![Screenshot_246](https://user-images.githubusercontent.com/130897671/232289595-7b9f504e-e55b-49cb-936c-8c1e6005d036.png)
![Screenshot_247](https://user-images.githubusercontent.com/130897671/232289596-4e7dfa62-45ee-4f11-964b-e6be2f66d149.png)
![Screenshot_248](https://user-images.githubusercontent.com/130897671/232289601-3621b1b4-c1f7-4032-980c-0a47a811b7e3.png)
![Screenshot_249](https://user-images.githubusercontent.com/130897671/232289603-ccc6537a-a75b-479c-ac33-58a9bcc73f34.png)
![Screenshot_250](https://user-images.githubusercontent.com/130897671/232289605-a1469aa2-96de-4003-bc8a-ef5fb912d339.png)
By adding just one line to the .dat file, you can achieve a qualitative improvement in the appearance of weapons with skins

**Comment by SDGNelson** [comment]
Thanks for the report! Sorry about that, I'll see about getting that skin fixed up. I'm unsure about the makeshift attachments though because they are intended to look less perfect than their factory-made counterparts.

**Comment by Semidvista** [comment]
Even when painted in different colors, they look like homemade ones, because of the shape of the object model.
Just because they're painted some color won't make them look like their factory counterparts.

**Comment by Semidvista** [comment]
> Thanks for the report! Sorry about that, I'll see about getting that skin fixed up. I'm unsure about the makeshift attachments though because they are intended to look less perfect than their factory-made counterparts.

Even when painted in different colors, they look like homemade ones, because of the shape of the object model.
Just because they're painted some color won't make them look like their factory counterparts.
