### ISSUE TITLE
16x Scope Not Centered

### ISSUE THREAD

**Issue by JimmyDeluxe0** [SmartlyDressedGames/Unturned-3.x-Community#3819]
![Screenshot 2023-04-17 005529](https://user-images.githubusercontent.com/125661718/232347654-27f50062-554d-4ca4-a919-03a732341f29.png)

The 16x scope is a little off centered from the center of the screen. Nothing big just thought I’d put it up there.

**Comment by SDGNelson** [comment]
This is because the scope texture's lines are 1 pixel wide. At some point in the future I'd like to improve the scope visuals. (https://trello.com/c/OuHSjotG/44-scope-range-markers-zeroing)
