### ISSUE TITLE
Fire delay resets when pressing the shoot button

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#3820]
Fire delay can be reset when pressing the shoot button repeatedly.

**Comment by SDGNelson** [comment]
I'm not sure whether this is problematic. Does it have a negative side effect for your weapon? Off the top of my head I'm thinking of the R8 in CS:GO where you can prepare to fire. On the other hand there's Mei's icicle gun in Overwatch which has no cancel.

**Comment by DerEnte** [comment]
The R8 has to have the shoot button to be held down instead of being
pressed once

Dne po 17. 4. 2023 17:50 uživatel Nelson Sexton ***@***.***>
napsal:

**Comment by SDGNelson** [comment]
Ah right. Is there a problem in Unturned with this though?

**Comment by DerEnte** [comment]
Well not really for me, but for some people it may be problematic.

Dne út 18. 4. 2023 2:51 uživatel Nelson Sexton ***@***.***>
napsal:

**Comment by DerEnte** [comment]
For some weapons it could take away the skill required to shoot the weapon
or if the the gun has a prefire sound it could be spammed indefinetely
(theoretically, will test later)

Dne út 18. 4. 2023 13:07 uživatel Egor Fedotov ***@***.***>
napsal:

**Comment by Wyvernaed** [comment]
> Ah right. Is there a problem in Unturned with this though?

I think main problem that you can delay shot more and more just pressing use button and also spamming fire delay sound
