### ISSUE TITLE
Haunted particle interferes with 3rd person aiming

### ISSUE THREAD

**Issue by Semidvista** [SmartlyDressedGames/Unturned-3.x-Community#3821]
I think it's worth slightly reducing the distance that a given particle can move away from an object
![20230402005355_1](https://user-images.githubusercontent.com/130897671/232691672-c044343f-79d5-4575-9034-2f9f1b88df35.jpg)
![20230402005350_1](https://user-images.githubusercontent.com/130897671/232691677-d358b637-3fcc-414a-a823-c5a2521a786e.jpg)
![20230402005333_1](https://user-images.githubusercontent.com/130897671/232691679-84e5132e-04f4-4f3f-b01b-9b29ce66ca55.jpg)
![20230402005332_1](https://user-images.githubusercontent.com/130897671/232691682-038bfcc9-61bf-49c7-980e-7298861e1c52.jpg)
I use this item
![Screenshot_254](https://user-images.githubusercontent.com/130897671/232691900-d0c2086a-75f6-4c93-9dc4-7a29489739f9.png)

**Comment by SDGNelson** [comment]
That is annoying, but I don't think there is a good way to change this currently without making the effect worse. One potential option in the future would be to use a different shader for mythical particles that fades them out near the center of the screen.

**Comment by sunnamed434** [comment]
What do you think to don't show the effects on the client side if they are in 3rd person aiming or smth like that? Or

**Comment by iBowie** [comment]
Maybe it would be a good idea to make effect more transparent as it approaches game camera or crosshair? If it's even possible.

**Comment by Semidvista** [comment]
> Возможно, но я думаю, что было бы неприятно, если бы все ваши мифические эффекты исчезали каждый раз, когда вы начинаете прицеливаться.

Maybe it's worth reducing the particle flight radius?
So that he would fly in the same way near a piece of clothing, but the distance at which he could move away from this object would be less than it is now?
