### ISSUE TITLE
Mesh Collider doesn't work on the vehicle

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#3822]
When the Clip of the vehicle uses the Mesh Collider, the vehicle will cross the ground.The object will also be crossed, but the collision between the player and the vehicle is normal.

https://user-images.githubusercontent.com/68633558/233116484-78998301-ce6c-4883-b7cc-23486e0cffa0.mp4

**Comment by Wyvernaed** [comment]
Unity dont support non-convex mesh collider with non-kinematic rigidbody. Use convex mesh collider, box or capsule colliders.

**Comment by SDGNelson** [comment]
Wyvernaed is correct that for vehicles you would need to enable the "Convex" setting on the Mesh Collider.
