### ISSUE TITLE
Effects spawning their old copy

### ISSUE THREAD

**Issue by Wyvernaed** [SmartlyDressedGames/Unturned-3.x-Community#3823]
Effect spawning their old copy and when you use animations or something like rocket scripts that destroying yourself after first effect ends, following effects becomes buggy, like animations are already played, rockets destroyed and etc.

I fix it with grenade script that destroying effect after fuse(equal lifetime of effect) ends but it looks like bug and maybe old effects copies affect on performance?

**Comment by SDGNelson** [comment]
Currently all effects are pooled/recycled. Using scripts to destroy game objects is going to cause problems. Maybe it can be done without destroyed, for example hiding something using the animation?

**Comment by Wyvernaed** [comment]
I use rockets to simulate artillery barrage, dont think it can be done with animation. And the main problem it if i dont destroy effect with grenade, after first spawned effect ends, all new effects becomes without rockets. So i think may be keeping effect copies maybe buggy for some effects and bad for performance(if you have a lot of effects).

**Comment by SDGNelson** [comment]
Sorry, I don't think what you are trying to do is currently supported. In the future I would like to separate projectiles into their own system so the server can spawn arbitrary rockets/grenades/etc which will work better for that. (https://trello.com/c/Rx3KI6md/45-projectiles-rewrite)

**Comment by Wyvernaed** [comment]
It is fully supported, except that killer cannot be tracked and that trick with grenade script) But hope after projectiles rework it will be possible to shoot projectile from the selected prefab, not from players screen if you shooting from vehicle turret and also be nice to have projectile per magazine.

**Comment by Wyvernaed** [comment]
And maybe solution for that trick with grenade would be Delete_After_Lifetime line for .dat file or something like that because now its looks like effects doesnt deleting from scene and they replaying after new effect spawned.
