### ISSUE TITLE
GeForce users unable to play Unturned.

### ISSUE THREAD

**Issue by KodakDolph** [SmartlyDressedGames/Unturned-3.x-Community#3828]
Copied from a staff member of my server who uses GeForce to play:

"Okay, so I load Unturned using the GeForce Now website. It loads Unturned fine, but when I try to join a server with an official map like Germany, Washington, PEI, and others, it won't work. Only modded maps seem to work. I've made many tickets over the past week, but GeForce Now keeps saying their concern team will look into it, and I never hear anything back. I know it's not just me because I've found many other posts about the same issue."

Other posts he mentioned: https://www.reddit.com/r/GeForceNOW/comments/12s5les/unturned_stuck_at_loading_map/
https://www.nvidia.com/en-us/geforce/forums/gfn-tech-support/46/517457/unturned-stuck-loading-map-when-trying-to-play/

**Comment by SDGNelson** [comment]
Sorry, this is outside of my control. (GeForce Now runs the regular version of the game) Considering it has been reported to them they are probably looking into it, and of course if they do contact me about it I will assist.
