### ISSUE TITLE
Decouple freecam from admin

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#383]
Currently the only way to use freecam is to have admin which is not wonderful - people who capture footage might not need that much rights.

Would be great to have that separated and changeable via steam calls

Before *too clever* people start telling "there's a plugin bla bla bla" - I know at least 3 problems with faking admin on client, one of which is major and leads to unrepairable desync between client and server

**Comment by SDGNelson** [comment]
Added! Use this method:
https://i.imgur.com/iV6G1d3.png
