### ISSUE TITLE
Door Interactability_Reset Time is affected by the map

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#3831]
I've tested the same door on 3 different maps. In the .dat file of the door, I have the following line `Interactability_Reset 2`.
On the first map, 2 seconds after the door opened it closed itself.
On the second map, it took 5 seconds before the door closed.
On the third map, it took 30 seconds before the door closed.

All three maps were tested with the same settings being the default Easy parameters, with GPS enabled and item spawn chance to the max. None of the maps have a Config.json that could modify parameters. The door files are located in the Bundles folder of the third map. 
Here's a link to a video showcasing the issue: https://youtu.be/pihUnEUozfI

Here's the full .dat of the door object:
![image](https://user-images.githubusercontent.com/48290038/234940721-078f93d6-a0d4-400c-8ef5-7fed890e20b5.png)

Here's the logs, don't know if that will help. GUID of the door if needed `130e71a86aaa46219259077ea78a4ad0`
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11346447/Client.log)

**Comment by SDGNelson** [comment]
Thanks for the report, but unfortunately this is a side effect of how those timers work for now. (e.g. applies to item despawn, tree respawn as well) They check one item per grid cell per frame. It's on my wishlist to rewrite with a proper ordered timer system.
