### ISSUE TITLE
Audio source on item does not loop in first person even if looping is checked

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#3832]
it will loop only when the audio source is 2d

**Comment by SDGNelson** [comment]
On the viewmodel? The audio listener is at the main camera whereas the viewmodel is at the world origin, so it must be outside range. What did you have in mind?

**Comment by DerEnte** [comment]
Yeah on the viewmodel

**Comment by SDGNelson** [comment]
* What did you have in mind? -> What kind of audio are you trying to do?

**Comment by DerEnte** [comment]
I am trying to do 3d audio on an item which will loop in third person and
first person and will be audible in third person and first person.
