### ISSUE TITLE
Workshop UI bug

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3835]
As you can see `DailyRewardsUI` mod is leaving outside of the actual size of the UI

Windowed 1024x768, UI Scale 1.000

![image](https://user-images.githubusercontent.com/65300126/235430032-9440b061-fb12-46b7-bcf0-c0a4e08fdbe5.png)

**Comment by SDGNelson** [comment]
It depends whether the scroll bar there is visible. The workshop submission menu is pretty bad and needs a redesign someday.
