### ISSUE TITLE
Server was listed without workshop items, but requested workshop downloads

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3836]
Trying to test the UI on my local machine, is there's a way to ignore this message and let me join the server? 

Would be great to make it configurable in `Config.json` or `WorkshopDownloadConfig.json`, e.g. `AllowUnlistedWorkshopItems`, and check if the player has the same mod already installed and server the same way, so, that means there's no need to install the workshop item installed locally by the player and server.

I already downloaded the workshop item locally, and the problem is I can't upload mods in Steam because the account is new and I need to invest in steam about ~$5 to let me upload public mods not only for friends.

![image](https://user-images.githubusercontent.com/65300126/235430610-8ac4ed74-8cc7-4bdb-acb3-61cee130f4eb.png)

## Workaround
Install the mod locally and server-side in `U3DS\Servers\Server_Name\Workshop\Content\` and the id of the mod in `WorkshopDownloadConfig.json`

**Comment by SDGNelson** [comment]
This is to prevent servers from advertising as not requiring any downloads and then installing dozens of mods when connecting.

**Comment by sunnamed434** [comment]
> This is to prevent servers from advertising as not requiring any downloads and then installing dozens of mods when connecting.

Yeah, you probably got my issue wrong, but what to do then If I just need the mod on the local server? How do I install the mod without installing it in the workshop?

**Comment by SDGNelson** [comment]
Currently the easiest/intended way to test custom content without uploading to Steam is to include in the loaded map's Bundles folder. For example MyTestLevel/Bundles will be loaded on both client and server in the Maps folder.
