### ISSUE TITLE
FPS and TPS models do not match up

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#3837]
FPS
![image](https://user-images.githubusercontent.com/80266096/235439455-e4df9dfc-c031-4e3d-9952-a6f1db7e8bd5.png)
TPS
![image](https://user-images.githubusercontent.com/80266096/235439480-c337d61e-3566-4e2c-b23c-c79844bac7fb.png)

**Comment by SDGNelson** [comment]
Hmm the 3rd-person mesh weights might have been adjusted without updating the 1st-person mesh. I'll check.

**Comment by SDGNelson** [comment]
Updating the first-person arms to match third-person makes a lot of animations look worse, but it's probably better for improving the animations in the long run. Updated it for the meantime but might revert, unsure.
