### ISSUE TITLE
[Bug?] SelectionTool uses hardcoded KeyCodes instead of ControlSettings

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3840]
The abstract SelectionTool responsible for the NodesEditor and VolumesEditor tools uses hardcoded KeyCodes such as `KeyCode.E` instead of `ControlSettings.tool_2` unlike EditorObjects. Which means that they can't be rebond.

Big thanks to 𝓢𝓣𝓡𝓮𝓶𝓸𝓷𝓽𝓪𝓽𝓪𝓾𝓻#3793 on the official Unturned discord server for discovering this issue.

Marked as [Bug?] because I am unsure if this is a known issue.

**Comment by SDGNelson** [comment]
Unfortunately yes: most of the ported "devkit" stuff wasn't using the player's control settings for whatever reason. My plan is to revisit input at some point with the new input manager and revamp the controls menu e.g. search for binding by name.
