### ISSUE TITLE
Tracer not appearing at low FPS. (Normal bullet tracer)

### ISSUE THREAD

**Issue by Sgtlog123** [SmartlyDressedGames/Unturned-3.x-Community#3843]
Here video : https://youtu.be/7x9TG63gP6w
Youtube compression make it look quite bad

**Comment by SDGNelson** [comment]
It looks like this is because the tracer effect is triggered once per physics update at the bullet position, but below a certain FPS the lifetime is less than the frame time. In the future I intend to update the bullet trails effects to work a bit differently.
