### ISSUE TITLE
ObjectAsset still have ID restrictions

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3847]
ObjectAsset still restricts ID usage even if they arent used by the game anymore. This means that you still have to specify an ID for both Objects and NPCs above 2000 which is annoying.

https://github.com/Unturned-Datamining/Unturned-Datamining/blob/linux-preview/Assembly-CSharp/SDG.Unturned/ObjectAsset.cs#L492-L495
> AFAIK nothing in vanilla uses the legacy object IDs anymore
_Originally posted by @SDGNelson in https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3734#issuecomment-1453763782_

**Comment by iBowie** [comment]
This code is outdated, the issue was solved a few updates ago.
#3741

**Comment by Gamingtoday093** [comment]
Oh resolved on preview Branch, nvm then
