### ISSUE TITLE
Bug? "Engine" gameobject for Oxygenators isnt replicated on the server.

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#3849]
Hello,

Not sure if this is a bug, I am pretty sure it is. The "Engine" gameobject on oxygenators is not invoked on the "Clip" prefab when the barricade switches states. Causes unpredictable behaviour between the client and server.

**Comment by SDGNelson** [comment]
Not a bug, previously all of the "Engine" gameobjects were client-only but were changed because some mods were using them for collision. What do you have in mind?

**Comment by DrDallas1** [comment]
I am currently using the "Engine" gameobject to start animimations and changes in collision on the server, but no matter how I change the structure, it works in single player, but fails to start in multiplayer. (Yes, I do have Has_Clip_Prefab false)

**Comment by SDGNelson** [comment]
I suppose maybe all of the barricades with "Engine" objects should be made consistent. (only the generator was changed from client-only previously by mod request)
