### ISSUE TITLE
Splatmap smooth tool (pixel average mode) has no effect, glitches splatmap on high strength.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3850]
When using the splatmap smooth tool in the editor on pixel average mode, it doesn't really do anything. If you turn the strength up too high it can glitch the splatmap in the brush radius. If I had to guess I think it's either setting one of the layers weight to NaN/infinity or setting all layers to 0 weight.
Brush average mode seems to work fine.

Video: https://youtu.be/4qF5KyqTvyo

Nothing in client log.
I asked someone else to try it on their game and they had similar results.

**Comment by DanielWillett** [comment]
After looking at it a bit more I think it's because currentWeights is being averaged instead of the neighboring coordinates so it always averages to the same number.

`TerrainEditor.handleSplatmapWriteSmooth`
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/7f8ac33b-1b02-4270-8e04-46d2021b4f15)

**Comment by SDGNelson** [comment]
Thanks for the report! I think you're right that the wrong value is being averaged. 🤦‍♂️
