### ISSUE TITLE
Any tool like NBTEplorer for minecraft .dat files but for Unturned Level/MapName/*.dat and Players/PlayerID/MapName/Player/*.dat files?

### ISSUE THREAD

**Issue by creeloper27** [SmartlyDressedGames/Unturned-3.x-Community#3851]
I was wondering if there is a tool to read and idealy edit Unturned Level/MapName/*.dat files (`Barricades.dat`, `Groups.dat`, `Lighting.dat`, `Objects.dat`, `Structures.dat`, `Vehicles.dat`) and Players/PlayerID/MapName/Player/*.dat file (`Anim.dat`,  `Clothing.dat`, `Inventory.dat`, `Life.dat`, `Player.dat`, `Quests.dat`, `Skills.dat`) just like you can do for minecraft .dat files with NBTEplorer.

If not how is data encoded in those files? I would like to make a tool similar to NBTEplorer but for Unturned.

**Comment by iBowie** [comment]
Each file uses it's own structure. Your best bet would be to reverse-engineer it.

**Comment by creeloper27** [comment]
> Your best bet is to look at the implementation of the corresponding save/load method.

I am quite new to Unturned development and Unity in general, do you mind pointing me to the resource you mentioned? Where can I find that source file?

**Comment by SDGNelson** [comment]
Sorry, it's only available from de-compiling currently. In the meantime this project is interesting: https://github.com/Unturned-Datamining/Unturned-Datamining
