### ISSUE TITLE
Walls are blocked by doors above

### ISSUE THREAD

**Issue by DerSpeedMann** [SmartlyDressedGames/Unturned-3.x-Community#3852]
There might be other barricades that block them but doors are the most obvious / annoying

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/38493853/388dd6b7-484d-4b56-82f9-d74de808c967

**Comment by ItsRodrigoAl** [comment]
YES PLEASE, is so annoying when you get raided and you want to put again walls but you can't because you have doors in the upper floor, so you need to go upstairs and salvage all the doors, go down again build the walls and go upstairs again to put the salvaged doors.

**Comment by SDGNelson** [comment]
This is on my radar to fix, but as part of rewriting the barricade placement similar to structures. Right now the game doesn't track which door is in the doorway so it can't ignore collisions yet.
