### ISSUE TITLE
Add PlayerLife instance in delegates

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3853]
Would be great to add a PlayerLife instance into delegates that I specified in the screenshot below:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/43f5cee5-0ee5-4c94-b418-39a64f7bfd76)

Cuz in future this will make those troubles:
1. Unable to normally unsubscribe from the event (which would cause issues in the future, at least in Unity - it's very important to unsubscribe from the subscribed events)
2. Need to recreate a lambda to call a method
```cs
private void OnUnturnedPlayerConnected(UnturnedPlayer unturnedPlayer)
{
    unturnedPlayer.Player.life.onStaminaUpdated += newStamina => OnStaminaUpdated(unturnedPlayer, newStamina);
}
private void OnUnturnedPlayerDisconnected(UnturnedPlayer unturnedPlayer)
{
// Could not work, bad
    unturnedPlayer.Player.life.onStaminaUpdated -= newStamina => OnStaminaUpdated(unturnedPlayer, newStamina);
}
private void OnStaminaUpdated(UnturnedPlayer unturnedPlayer, byte newStamina)
{
}
```

**Comment by SDGNelson** [comment]
For new code usually yes, but no ETA on updating this older code.

**Comment by rube200** [comment]
Its a bit annoying but u can add UnturnedPlayerComponent if you use rocketmod

**Comment by sunnamed434** [comment]
> Its a bit annoying but u can add UnturnedPlayerComponent if you use rocketmod

Hm.. Yeah, good idea
