### ISSUE TITLE
The HMD has no Rarity

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#3855]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/137ecb56-c518-4551-b06f-4ffa197b1d88)
The HMD cosmetic is marked as "Glasses", thats it. no rarity, unlike other glasses items which are marked as "Common Glasses" etc etc.
personally i think this should be either a Gold yellow or Achievement orange item.

**Comment by SDGNelson** [comment]
Fair point that some items looked weird, quite a few items had "name color overrides" which I ended up just removing.
