### ISSUE TITLE
PTB - Makeshift scope range not visible with scope quality on

### ISSUE THREAD

**Issue by Sgtlog123** [SmartlyDressedGames/Unturned-3.x-Community#3859]
PTB - Build ID 11267013 / 3.23.7.103
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/111060879/38723a5e-5197-4276-88c8-d89099047985)
Scope quality off
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/111060879/28c19408-98fb-42cb-bd5a-13cbc7caded8)

**Comment by Sgtlog123** [comment]
Also at some resolution range line doesn't appear or missing completely.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/111060879/45b02522-b8da-4da4-99c9-4af7fd23bde7)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/111060879/e3b90e04-6174-4fde-9c10-281b25ecc8f8)

**Comment by SDGNelson** [comment]
Thanks for the report! The incorrectly enabled labels for the 2D scope have been fixed in the most recent preview version now. I'm undecided on what to do about the lines at low res / low UI scale though.

**Comment by Sgtlog123** [comment]
Please add option to change hitmarker style
