### ISSUE TITLE
New issues after update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#386]
Apparently some of the players are stuck on loading screen while joining servers now. Sometimes it connects, sometimes doesn't. Stuck on:

![image](https://user-images.githubusercontent.com/14231707/44621250-5db7ca00-a8ab-11e8-9922-35be5678ad1c.png)

Also, you can press ESC and quit server, but after doing that - getting "time out" when trying to connect to server again (server is online, and other players are playing though). After relaunching game, it lets to connect again, but there is still a chance (pretty big) to get stuck on loading screen.

**Comment by SDGNelson** [comment]
If you get the chance could you check the server's log files for any lines containing "refusing" please? That would indicate their connection getting blocked, but that seems unlikely since the previous update was the soft implementation to help catch false positives.

One other potential cause could be if the workshop query is getting ignored (now rate-limited per-connection), but that would be if they're trying to connect within ~30s of their original connection...

**Comment by baranmod** [comment]
Can't find any lines containing "refusing"

**Comment by SDGNelson** [comment]
That's reassuring. I expect it's the workshop query then. Right now the client doesn't cache the workshop info in-case the server reboots with different workshop configuration (relatively common), but to help with this I might adjust the client to cache that info for a short period like 1 minute.

**Comment by baranmod** [comment]
Well, I am not really into these backend things, so can't give any ideas on what might be wrong in this case. Anyways, I believe this is happening for vanilla server too. Might be wrong though.

**Comment by SDGNelson** [comment]
Ah sorry, I worded that confusingly - it queries what workshop content the using which may be none, or may be some items.

**Comment by Coopyy** [comment]
im getting an error in my server that shows Refusing connections from <my steam id> and then i cant see the map, whats going on? my friends and i cant join my server

**Comment by SDGNelson** [comment]
Hi Coopyy, if your server is logging refused connections could you post the full output_log.txt from the server's Unturned_Data folder please?

**Comment by SDGNelson** [comment]
Unfortunately (or fortunately?) none of the logs from hosts I looked through were refusing connections, however I put together a few fixes in a .1 patch which I'm fairly confident in.

**Comment by baranmod** [comment]
Apparently, didn't help. Same thing is happening

**Comment by jatapa2** [comment]
atleast 1 of my servers says refusing connection

**Comment by SDGNelson** [comment]
Additional logging in .1 helped track down another issue which was patched in .2, and now after playing around for a bit on a few servers everything seems to be going smoothly again. Ultimately all these changes have been security focused, so hopefully that's the last of this for a while. In the mean time off to bed zzz...

**Comment by jatapa** [comment]
everything is working just fine with my servers

**Comment by baranmod** [comment]
It seems its working well now for me too. Will drop an update if same issue appears again for someone.

**Comment by Coopyy** [comment]
still dc'ing trying to join servers
