### ISSUE TITLE
[PREVIEW] Masterbundles without assets do not load in preview branch.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3864]
For a project I'm working on I have a masterbundle that is just treated as a kind of 'Resources' bundle and doesn't actually contain any assets.
I've been trying to fix it for a while now and finally figured out why. If there are no assets queued by the reader thread, then the worker's `IsWorking` property is set to false in `AssetWorker.Update` while the asset bundle request is still not done, which ends the `LoadAssetsFromWorkerThread` coroutine before the bundle finishes loading. The bundle never gets removed from pending or loaded into the master bundle list.

I believe an easy fix would just be to make this `while (worker.IsWorking || pendingMasterBundles.Count > 0)`
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/356614cd-a10e-4d21-a19a-0143ee610196)

With a test asset:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/dd23f1cd-7a63-4d4b-b2c8-7a61f74b5637)

With no assets:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/d9c1533a-f37c-4d2d-bf91-be312839d635)

Note how the load start message (which is triggered from a prefix to `MasterBundleConfig.StartLoad`) gets displayed but the 'load end' message doesn't (triggered from a prefix to `MasterBundleConfig.FinishLoad`).

Edit: This is the coroutine I'm using to load the bundle
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/a775d39e-0190-4d19-98ab-3a295c1150e0)

**Comment by DiFFoZ** [comment]
Just use the unity API to load asset bundle, https://docs.unity3d.com/ScriptReference/AssetBundle.LoadFromFileAsync.html

**Comment by SDGNelson** [comment]
While DiFFoZ is correct that Unity asset bundles can be directly loaded, I agree this would be good to fix in case there is any existing content in the same situation. Thanks for the report!

**Comment by DanielWillett** [comment]
Works now, thank you.
