### ISSUE TITLE
Bypass the group restriction when the "Allow_Static_Groups" option is disabled

### ISSUE THREAD

**Issue by Semidvista** [SmartlyDressedGames/Unturned-3.x-Community#3865]
Hello
These players bypassed the restrictions on the number of players in the group (maximum 5 players, on my servers), while the option in config.json "Allow_Static_Groups" (disables grouping on the server when entering through one steam group) was disabled
I don't know exactly how they did it, but I have a hunch that it happened when using the "Lobby" item in matchmaking
In this way, you can bypass any restriction on the group on any server and make a group of 10 people, with a maximum allowed of 2, 4 or 5 people, which has a very negative effect on the balance of power on the server
I have a suggestion how this can be fixed, you just need to add the "Allow_Lobby_Groups" item to config.json and give it the ability to set it to true / false, if the value is false, when connecting to the server, the lobby group will disintegrate and all people will be alone and without groups
![Screenshot_301](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/2e2e379a-00e3-4a23-a1bc-049f1a0a3e5f)
![Screenshot_302](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/c94a3960-c9a9-41ae-9df3-ff999e3831b7)
![Screenshot_304](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/f327f489-291a-4626-84e8-6528538ac5b7)

**Comment by SDGNelson** [comment]
Thanks for the report! You're probably right that the lobby group was used. I'll check into this.
