### ISSUE TITLE
The sound of water that drives you crazy

### ISSUE THREAD

**Issue by Semidvista** [SmartlyDressedGames/Unturned-3.x-Community#3869]
When you want to build a house on the beach or under water, you are faced with the fact that now the sound of water will constantly sound in your ears, it is very annoying and makes it difficult to concentrate when you are busy doing something that takes a lot of time in your house
It seems to me that a great way out of this problem would be the ability to add an item to the settings that would allow you to disable and enable beach ambient and underwater ambient (both parameters in one item, or two for different ones), just like we have now ability to turn off day/night ambient
At the same time, all other sounds, such as walking on water or the sounds of swimming, will also be heard as before, this option should turn off only the ambient
These items will be enabled by default for everyone, as well as day / night ambient, but at the same time people will have the opportunity to turn them off if these ambients really interfere with them

**Comment by SDGNelson** [comment]
Closing as feature request. (feel free to post requests in discussions though) Adding a new audio settings menu is on my to-do when I revamp some of the menus.
