### ISSUE TITLE
Melee weapons do not make a sound to other players

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#3871]
Swinging any melee weapon, including fists (but excluding Auto Melees, such as the chainsaw) will make a sound for _you,_ but not anyone else. 

https://streamable.com/bws4mc

as you can see, when i punch, you can hear the "whoosh" of the punch, but when stas (right) punches, you cannot hear the "whoosh" of _his_ punches. impact sounds work as usual.

(video is cropped weirdly because i forgot i wanted to report this a while back and so i just threw together a video during the buak playtest, cropped so as little of the map is seen as possible)

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like this has probably been broken a long time: it relies on the "simulation frame" being updated on other clients but I'm not sure when that changed. I will probably change this to just use regular time.

**Comment by ItsRodrigoAl** [comment]
@SDGNelson I want to report something similar to this, but I don't know if this is related to the same issue or if I should create another issue post

Basically if you're jumping + running, only you will hear your step sounds, but others won't, so with this way if you're full skilled you could be just running and jumping being totally stealthy for others, which is ironic

**Comment by SDGNelson** [comment]
That's unrelated to this, and is probably happening because the replicated positing of the player is staying above the ground. In the future the server should probably tell clients whether the player is considered walking on the ground or not.

**Comment by SDGNelson** [comment]
Both punching and melee should be fixed in the next update (finally)! Oddly enough they were for completely different reasons.
