### ISSUE TITLE
"lost connection to host or steam network"

### ISSUE THREAD

**Issue by Baltek223** [SmartlyDressedGames/Unturned-3.x-Community#3873]
so from yesterday i have this issue that when i join any server and play on it for like 5-10 mins it just kicks me for "lost connection to host or steam network" i tried restarting my pc, steam, wifi, reinstalling unturned, unsubscribing maps from the workshop and still this thing happens my wifi is pretty good (10mb/s download and 5mb/s upload) and i have like 40-100 ping in game.

**Comment by SDGNelson** [comment]
Could you submit a support ticket with this log file please? I'll check whether there is any other error information. https://support.smartlydressedgames.com/hc/en-us/articles/12168092423700-Reporting-a-bug

**Comment by joeymisfit** [comment]
Hey @SDGNelson,
I've also noticed this issue on multiple servers where after a certain amount of time it'll throw the "Lost connection to host or steam network" that or "Battleye isn't responding" which is quite strange.

**Comment by SDGNelson** [comment]
@joeymisfit aside from network-related timeout cause, the most common reason would be if the game froze for a while or BattlEye's servers temporarily went down.
