### ISSUE TITLE
Oxygen wont change

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3874]
Trying to change the player oxygen in positive and negative directions, and for me nothing happens 

```cs
life.serverModifyHealth(-20); // works fine
life.askSuffocate(40); // not work
life.simulatedModifyOxygen(-40); // not work
life.simulatedModifyOxygen(-40f); // not work
life.tellLifeWithOxygen(CSteamID.Nil, 100, 70, 70, 70, 50, false, false); // everything changes except oxygen
life.ReceiveLifeStats(life.health, 90, 90, 90, 20, false, false);  // everything changes except oxygen
life.onOxygenUpdated?.Invoke(40); // not work
```

Extra check if the player is dead, and the same with `askBreath`
```cs
public void askSuffocate(byte amount)
{
  if (amount == (byte) 0 || this.isDead || this.isDead)
    return;
  this.lastSuffocate = this.player.input.simulation;
  if ((int) amount >= (int) this.oxygen)
    this._oxygen = (byte) 0;
  else
    this._oxygen -= amount;
  OxygenUpdated onOxygenUpdated = this.onOxygenUpdated;
  if (onOxygenUpdated == null)
    return;
  onOxygenUpdated(this.oxygen);
}
```

**Comment by SDGNelson** [comment]
Sorry, there isn't currently any way for plugins to modify the player's oxygen level.

**Comment by sunnamed434** [comment]
> > Sorry, there isn't currently any way for plugins to modify the player's oxygen level.
> 
> Although it's terribly ugly and uncomfortable, we can use something like that:
> 
> ```cs
> public void ServerModifyOxygen(Player player, byte newOxygen)
>  {
>     ClientInstanceMethod<byte, byte, byte, byte, byte, bool, bool>? SendLifeStats = 
>     typeof(PlayerLife).GetField("SendLifeStats", BindingFlags.NonPublic | BindingFlags.Static).GetValue(player.life) as 
>     ClientInstanceMethod<byte, byte, byte, byte, byte, bool, bool>;
>             
>     FieldInfo field = player.life.GetType().GetField("_oxygen", BindingFlags.NonPublic | BindingFlags.Instance);
>     if (SendLifeStats is not null && field is not null)
>     {
>         field.SetValue(player.life, newOxygen);
>         SendLifeStats.Invoke(player.life.GetNetId(), ENetReliability.Reliable, player.channel.owner.transportConnection, 
>         player.life.health, player.life.food, player.life.water, player.life.virus, player.life.oxygen, player.life.isBleeding, 
>         player.life.isBroken);
>     }
> }
> ```

Thanks, works fine

**Comment by sunnamed434** [comment]
> > > Sorry, there isn't currently any way for plugins to modify the player's oxygen level.
> > 
> > 
> > Although it's terribly ugly and uncomfortable, we can use something like that:
> > ```cs
> > public void ServerModifyOxygen(Player player, byte newOxygen)
> >  {
> >     ClientInstanceMethod<byte, byte, byte, byte, byte, bool, bool>? SendLifeStats = 
> >     typeof(PlayerLife).GetField("SendLifeStats", BindingFlags.NonPublic | BindingFlags.Static).GetValue(player.life) as 
> >     ClientInstanceMethod<byte, byte, byte, byte, byte, bool, bool>;
> >             
> >     FieldInfo field = player.life.GetType().GetField("_oxygen", BindingFlags.NonPublic | BindingFlags.Instance);
> >     if (SendLifeStats is not null && field is not null)
> >     {
> >         field.SetValue(player.life, newOxygen);
> >         SendLifeStats.Invoke(player.life.GetNetId(), ENetReliability.Reliable, player.channel.owner.transportConnection, 
> >         player.life.health, player.life.food, player.life.water, player.life.virus, player.life.oxygen, player.life.isBleeding, 
> >         player.life.isBroken);
> >     }
> > }
> > ```
> 
> Thanks, works fine

The problem is when you do that it sets stamina to 100, would be great to have control on top of it, for example, a possibility to pass the stamina inside of the method
