### ISSUE TITLE
Constant server crashing with new v3.23.7

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3878]
Since the last update my servers are constantly crashing with this error
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/136d17ac-17da-47db-a113-94fcdc4ed245)

**Comment by SDGNelson** [comment]
Sorry for the trouble, could you attach the Unity and server log files please in case there is hopefully more details?

**Comment by ItsRodrigoAl** [comment]
> Sorry for the trouble, could you attach the Unity and server log files please in case there is hopefully more details?

@SDGNelson Sadly that's everything it shows up. The server loads normally with all its plugins, then someone joins for some seconds and shows that error, it crash and restart again

[crash-2023-05-26 16_29_11.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11578219/crash-2023-05-26.16_29_11.log)
[Server_unturned.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11578220/Server_unturned.log)

**Comment by SDGNelson** [comment]
Thanks for the logs. According to the Server_unturned.log file the shutdown feature is being triggered. One thing to narrow down: if you disable OpenMod, Rocket, and uScript does it still crash? (i.e. is crash vanilla)

**Comment by ItsRodrigoAl** [comment]
> Thanks for the logs. According to the Server_unturned.log file the shutdown feature is being triggered. One thing to narrow down: if you disable OpenMod, Rocket, and uScript does it still crash? (i.e. is crash vanilla)

I'm trying different ways to get this error. One of them is trying to use /vault (to open a secure storage, this is a common plugin) and also even the /i (to get items) from RocketMod, both when are executed makes the server crash

**Comment by ItsRodrigoAl** [comment]
Found "the issue", its related to Openmod. With rocket and uscript it doesn't crash, but when Openmod is installed again it crash

**Comment by Jiraxd** [comment]
The issue seems to be related to RocketMod aswell. I don't use Openmod and the server still crashes after executing /kit, with the same error message shown above.

**Comment by SDGNelson** [comment]
Guessing this isn't my bug then since lots of servers are working with Rocket/OpenMod, but I may be able to help depending what the underlying issue is. Lots of asset code was reworked but still backwards compatible, though that doesn't seem related to these cases like /kit.

**Comment by JustOneMoreBlock** [comment]
Very strange. I'm running the latest version with RocketMod only and I don't get any crashes at all.

Part of my start script:

```
#!/bin/sh

unturned() {
export STEAM_GAMESERVER_A2S_INFO_REQUIRE_CHALLENGE=0
/usr/games/steamcmd +force_install_dir /home/Games/unturned +login anonymous +app_update 1110390 validate +exit
chmod +x /home/Games/unturned/ServerHelper2.sh
yes | cp -rf /home/Games/steamcmd/linux64/steamclient.so /home/Games/unturned/Unturned_Headless_Data/Plugins/x86_64/
yes | cp -rf /home/Games/steamcmd/linux64/steamclient.so /home/Games/unturned/
}

rocket_update() {
        cd /home/Games/unturned/Extras/
        yes | cp -rf Rocket.Unturned /home/Games/unturned/Modules/ 
}
```
- 45903ed6862aacdb05ba2f7309533950  /home/Games/steamcmd/linux64/steamclient.so

Running:

```
root@ut:/home/Games/scripts# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
```
- No Docker — Just using `screen`.

**Comment by Jiraxd** [comment]
[World] mam ban za nic [jestem biedny]: "/give 50010"
Caught fatal signal - signo:11 code:1 errno:0 addr:0x55861c603af8
/entrypoint.sh: line 42:    57 Segmentation fault      (core dumped) ${MODIFIED_STARTUP}

Seems to be an issue with vanilla commands aswell, certain modded items trigger this error.

**Comment by SDGNelson** [comment]
That's weird, which mod is the crashing item from? I'll install on a server and see if I can reproduce the crash.

**Comment by Jiraxd** [comment]
It's a custom mod, i can send you a link, but it seems to be related to https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3885

**Comment by SDGNelson** [comment]
Out of curiosity what was the cause?

**Comment by ItsRodrigoAl** [comment]
Was due to a plugin. Seems like some code was changed and it was causing the plugin to crash all the servers. Then the game was updated + Openmod was also updated + he updated his plugin and now everything seems to be working fine again :)

**Comment by Vanilla-Mix** [comment]
> Was due to a plugin. Seems like some code was changed and it was causing the plugin to crash all the servers. Then the game was updated + Openmod was also updated + he updated his plugin and now everything seems to be working fine again :)

I'm actually getting this exact same issue, I haven't even added a new plugin in the last 3 weeks and yet no issues til yesterday what plugin was causing this error?

**Comment by GazziFX** [comment]
Does it happen if you disable plugins or Openmod/Rocketmod
