### ISSUE TITLE
[Plugins] Clickable effects

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#389]
The idea: 
Add OnClick to effects with buttons (Needs to be done from player side as well) and then send back notification to the server when one of the buttons is pressed (could be done with an event),
Should be easy to implement.
Thank you, Roy.

**Comment by cheesynuggets** [comment]
@SDGNelson Get your ass up boy.

**Comment by SDGNelson** [comment]
Was one of the original considerations when adding those UI RPCs. Will probably add one for buttons, and one for text fields.

**Comment by SDGNelson** [comment]
The next update has an event for onEffectButtonClicked, as well as Player.serversideSetPluginModal to show the cursor while in a plugin menu.
