### ISSUE TITLE
Building Roof Issue 

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3893]
See [video](https://youtu.be/sZZ9zUfG1pc)
[![Watch the video](https://img.youtube.com/vi/sZZ9zUfG1pc/default.jpg)](https://youtu.be/sZZ9zUfG1pc)

**Comment by ItsRodrigoAl** [comment]
Not a bug, those pillars need a wall

**Comment by sunnamed434** [comment]
> Not a bug, those pillars need a wall

Interesting. Would be great to notify the player that this requires a Wall (not a floor)

**Comment by SDGNelson** [comment]
ItsRodrigoAl is correct that it needs a wall or floor to snap to. A new message should probably be added for that.
