### ISSUE TITLE
Cannot upload mods using Mac.

### ISSUE THREAD

**Issue by HathHub** [SmartlyDressedGames/Unturned-3.x-Community#3894]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/66932866/f93f9a39-7633-42d2-85f2-a90c61b815f9)
Acess permission denied when inputting the directory.
People have asked in the discord yet no one had an answer, everyone that has a mac is changing to their pc constantly to upload.
Thanks for reading.

**Comment by SDGNelson** [comment]
Unfortunately if the game can't get permission to use that path it's outside of the game's control. The Mac equivalent of running as administrator (?) might work, or there might be a different folder with different permissions. ☹️
