### ISSUE TITLE
There is no scope distance markers

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#3896]
There is no distance markers on some guns 

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/134800978/5a0b588e-5a18-4fde-980d-07b423caa666)
There is no distance markers on the bluntforce, shadowstalker and shadowstalker mk2, rocket launcher, paintball gun, devils bane and QuadBarrel.
I was using makeshift scope, 8x scope and 16x scope.
(I used default fov)
Devils bane, QuadBarrel and crossbow has distance markers but it looks like this 
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/134800978/e7b40da2-33e1-4e4b-8f95-b82bd26f3707)
This is not a big problem but the game looks unfinished and I want to play the finished game

**Comment by SDGNelson** [comment]
They aren't visible on certain guns depending whether it has bullet drop or the bullet drop is so extreme that the lowest marker would be off-screen.
