### ISSUE TITLE
Sabertooth hit sound bug

### ISSUE THREAD

**Issue by JetFire69420** [SmartlyDressedGames/Unturned-3.x-Community#3897]
When you hit someone with sabertooth from a long distance you hear hit sound like he is in front of you. Doesn't happen with other sniper rifles like  Grizzly, Matamorez, Ekho and etc.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/73253839/50306d43-b14b-46c8-b0ff-7fc5ed6a068c

**Comment by ItsRodrigoAl** [comment]
This is a feature added on the latest game version to provide more feedback when shooting. However it should be enabled for all guns and not only with Sabertooth, are you sure this is not happening with the other guns as well?

**Comment by JetFire69420** [comment]
> This is a feature added on the latest game version to provide more feedback when shooting. However it should be enabled for all guns and not only with Sabertooth, are you sure this is not happening with the other guns as well?

Tried with all assault rifles and smgs, sniper rifles too, happens only with Sabertooth I'm pretty sure

**Comment by diddlyono** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/27a0a902-56d3-4bca-852d-079228e1f843)
this was part of the latest update
however youre saying its not happening with everything else, _that_ seems like a bug.

**Comment by SDGNelson** [comment]
Watching your video I think it's probably just that it's more noticeable because your Sabertooth is silenced. It's harder to notice / more subtle when using an unsuppressed gun.

**Comment by JetFire69420** [comment]
Yes that might be a reason, I was looking for that change in "Added" section and thought it was a bug as it is kinda strange implementation, I will check that out and sorry for my mistake.

**Comment by JetFire69420** [comment]
> Watching your video I think it's probably just that it's more noticeable because your Sabertooth is silenced. It's harder to notice / more subtle when using an unsuppressed gun.

But I can surely say I didn't hear it on "Hecate", Does it work only on vanilla guns or any?

**Comment by SDGNelson** [comment]
It applies to all guns yes
