### ISSUE TITLE
Has anyone gotten "Assertion Failed: packet number not properly initialized!" in standard output recently?

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#3900]
Not an issue or a PSA, but I figure this is a great place to post for the server hosts and plugin devs who would be most likely to run into it.

**Comment by ItsRodrigoAl** [comment]
What does PSA mean?

**Comment by SDGNelson** [comment]
Public Service Announcement
I added that label a while ago for some notices prior to API changes.
