### ISSUE TITLE
Access permission denied when uploading a mod

### ISSUE THREAD

**Issue by CyberAndrii** [SmartlyDressedGames/Unturned-3.x-Community#3901]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/37713088/4ae290af-826e-4da3-93a6-252e18b99797)

As it turns out, it's not a permission issue, but rather that `Directory.GetAccessControl(string path)` throws `PlatformNotSupportedException` on macOS and Linux.

[code](https://github.com/Unturned-Datamining/Unturned-Datamining/blob/d5830525c3dfe391468c0483b76937b96300aca5/Assembly-CSharp/SDG.Unturned/ReadWrite.cs#L599...L625)

**Comment by SDGNelson** [comment]
Thanks for the report! Well that explains the issue post the other day about uploading on Mac.

I wonder if I should just remove that check considering Steam's permissions may be different as well. According to [Directory.GetAccessControl](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getaccesscontrol) docs it throws `UnauthorizedAccessException` if "This operation is not supported on the current platform." which seems unhelpful for separation. (It sounds like in your testing it throws a more useful exception, but at least that means the documented explanation is inconsistent?)

**Comment by CyberAndrii** [comment]
Oh, I'm not surprised that Mono doesn't follow the behavior of Microsoft's .NET Framework again.

After googling for some alternatives, I agree that removing that check may be the best option.

**Comment by SDGNelson** [comment]
Well, on the bright side some players incorrectly getting that message will be happy! For the next update I'll make that check Windows-only.
