### ISSUE TITLE
Checking for map files in wrong order?

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3902]
#2749 - I came to the realization that my weird issue post might actually be a sign of a bigger issue. The map editor was acting up when I had a version of my map in the editor and subbed on the workshop. I assume the game is supposed to **only** load data from the folder that takes priority, which is the editor version (`Root Unturned Dir/Maps`). Perhaps the order is inconsistent throughout the game code?

**Comment by SDGNelson** [comment]
Currently it might put a separate listing for one in the Maps folder and one on the workshop. When it actually selects the level to use it should use the one in the Maps folder. At some point I'd like to tidy this code up though because it's pretty bad.

**Comment by SDGNelson** [comment]
Taking a peek at issues with the "should probably do eventually" label and I believe it was fixed later in 2023 without updating this particular issue! (there was a similar separate one) Now the editor level list can show multiple versions of the same map and the tooltip indicates where it was loaded from.
