### ISSUE TITLE
Model Bug

### ISSUE THREAD

**Issue by Ditmas1** [SmartlyDressedGames/Unturned-3.x-Community#3903]
Dufflebag from official game looks like its partly in the character (Edit also some other vanilla backpacks)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/107338452/bb8ab9d9-dad4-4bbd-8662-ff2febc802c6)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/107338452/10abed6b-97a4-42c9-8a74-81882d77e43d)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/107338452/dcf7a0c4-490f-4e32-a494-d1a34e28bfdc)

**Comment by SDGNelson** [comment]
Thanks for the report, but this is very minor and unlikely to change anytime soon, sorry.
