### ISSUE TITLE
Spawntable editor acting funky?

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3906]
Trying to create a spawntable using `33140` ends up with this result.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/31b3f2e7-0afa-4925-9eb3-d865e9e2a326)

Trying to create a spawntable using `43140` ends up with this result.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/7e028119-6895-4c7e-8f20-1287d5333df5)
This is confusing because Food_Organic (which I was viewing earlier) was shown.

I think the new asset rewrite broke some portions of the spawntable menu. It seems that it wasn't updated for two weeks (even then, a small method naming change).

**Comment by Jdance-Media** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/a9224e74-0067-44bc-9195-fc266a498791)
Also, not fit for another issue, but these two buttons have the same tooltip. I personally get confused between Asset and Spawn. Also, those buttons aren't doing anything, even with a ushort ID inputted.

**Comment by SDGNelson** [comment]
Hmm it seems likely something broke related to it during the multi-threaded assets rewrite considering that menu is the only in-game one that creates assets. Updating them to support guids is on my to-do list so maybe I can do both at the same time.

**Comment by SDGNelson** [comment]
Resolved for the next update! A few nice changes:

1. (bug is fixed)
2. GUID support in the roots and tables properties
3. Support for the newer dat list format `[ ]`
