### ISSUE TITLE
Transparent texture

### ISSUE THREAD

**Issue by SurvivorCDG** [SmartlyDressedGames/Unturned-3.x-Community#391]
Nelson, how to make transparent texture for glass?
![Try #666](https://user-images.githubusercontent.com/17459138/44677085-22053780-aa46-11e8-8fe7-32090bf73fff.png)

**Comment by baranmod** [comment]
set rendering mode to transparent? Might be wrong though, but it surely does the thing 
![image](https://user-images.githubusercontent.com/14231707/44689936-cf397900-aa61-11e8-947d-2d69f982d72a.png)

**Comment by ImIveooo** [comment]
In the .dat of your object puts "asset_bundle_version 2".

**Comment by SDGNelson** [comment]
Imlveooo's right, otherwise the game overrides materials.
