### ISSUE TITLE
Showing titles as tooltips instead of titles on Options

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3910]
So, looking on the Configuration > Options i noticed this thing where I'm not totally sure if it is intentional or not, but as you can see the first and last button show its title of it at the right, so you may directly know what it is and just click on the button. However with the other buttons its title is not showed up and you have to keep the mouse above the button to show its title (tooltip) to know what it is.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/283cef0a-a64e-4a68-858e-a266ab465498)

Shouldn't all those show directly the title instead of being a clear text and needing to keep the mouse above to show its title? As you can see on the Graphics settings, you have their titles at right, the text at left but also their tooltips above to explain what it does

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/15c48d6b-9331-47bc-b823-ff68506b63ae)

**Comment by SDGNelson** [comment]
You're right that's rather inconsistent, will fix.
