### ISSUE TITLE
Effects sometimes work and sometimes don't

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3911]
I've been developing a plugin that uses Effects as kill tips but I've been encountering a weird issue with effects.

My code is simple:
```C#
       public void ShowPointUpdate(UnturnedPlayer player, int point, string eventName, ushort effectId)
        {
            short key = -1;
            EffectManager.sendUIEffect(effectId, key, player.Player.channel.GetOwnerTransportConnection(), true, getPointUpdateDesc(point), eventName);
            Logger.Log("ShowPointUpdate----------------------");
        }

       private void onPlayerPointUpdate(UnturnedPlayer player, int oldPoint, int currentPoint, string reason)
        {
            Logger.Log("onPlayerPointUpdate----------------------");
            UIManager.GetInstance().ShowPointUpdate(player, (currentPoint - oldPoint), reason, Configuration.Instance.EffectConfig.PointUpdateId);
        } 
```

I'm sure both `Logger.Log("ShowPointUpdate----------------------")` and `Logger.Log("onPlayerPointUpdate----------------------");` were executed. But ` EffectManager.sendUIEffect(effectId, key, player.Player.channel.GetOwnerTransportConnection(), true, getPointUpdateDesc(point), eventName);` sometimes shows effect, sometimes does not.

Is there a limiting mechanism for `sendUIEffect`? or I called the `sendUIEffect` incorrectly?

**Comment by makeloffve** [comment]
my workshop file: [https://steamcommunity.com/sharedfiles/filedetails/?id=2983136129](https://steamcommunity.com/sharedfiles/filedetails/?id=2983136129)

Effect.dat
```
GUID 7363b28a5dd248d2bebc000ff4a41803
Type Effect
ID 2901

Lifetime 1
```

**Comment by sunnamed434** [comment]
> my workshop file: https://steamcommunity.com/sharedfiles/filedetails/?id=2983136129
> 
> Effect.dat
> 
> ```
> GUID 7363b28a5dd248d2bebc000ff4a41803
> Type Effect
> ID 2901
> 
> Lifetime 1
> ```

`Lifetime` is set to 1, try to set a bigger value (e.g `10000`)

My `.dat` UI file:
```dat
Type Effect
ID 6970

Lifetime 99999
```

**Comment by DanielWillett** [comment]
To expand on what sunnamed said, try adding `Lifetime_Spread 0` to your dat file, as it defaults to 4 seconds, meaning your lifetime can vary by a random value from -4 to 4 seconds.

**Comment by makeloffve** [comment]
> > my workshop file: https://steamcommunity.com/sharedfiles/filedetails/?id=2983136129
> > Effect.dat
> > ```
> > GUID 7363b28a5dd248d2bebc000ff4a41803
> > Type Effect
> > ID 2901
> > 
> > Lifetime 1
> > ```
> 
> `Lifetime` is set to 1 it appears and disappears, try to set a bigger value (e.g `10000`)
> 
> My `.dat` UI file:
> 
> ```
> Type Effect
> ID 6970
> 
> Lifetime 99999
> ```

I want effect to disappear after 1s, so set Lifetime to 1 and key to -1.

**Comment by makeloffve** [comment]
> sir, I want effect to disappear after 1s, so I set Lifetime to 1 and key to -1.

and following your answer, Am I making the correct changes?

dat
```
GUID 7363b28a5dd248d2bebc000ff4a41803
Type Effect
ID 2901

Lifetime 1
Lifetime_Spread 0
```

code
```C#
EffectManager.sendUIEffect(effectId, -1, player.Player.channel.GetOwnerTransportConnection(), true, getPointUpdateDesc(point), eventName);
```

**Comment by makeloffve** [comment]
> To expand on what sunnamed said, try adding `Lifetime_Spread 0` to your dat file, as it defaults to 4 seconds, meaning your lifetime can vary by a random value from -4 to 4 seconds. Edit: this spread doesn't apply unless your key is -1, so sunnamed is right, change it to something else.

> sir, I want effect to disappear after 1s, so I set Lifetime to 1 and key to -1.

and following your answer, Am I making the correct changes?

dat
```
GUID 7363b28a5dd248d2bebc000ff4a41803
Type Effect
ID 2901

Lifetime 1
Lifetime_Spread 0
```

code
```C#
EffectManager.sendUIEffect(effectId, -1, player.Player.channel.GetOwnerTransportConnection(), true, getPointUpdateDesc(point), eventName);
```

**Comment by sunnamed434** [comment]
> > To expand on what sunnamed said, try adding `Lifetime_Spread 0` to your dat file, as it defaults to 4 seconds, meaning your lifetime can vary by a random value from -4 to 4 seconds. Edit: this spread doesn't apply unless your key is -1, so sunnamed is right, change it to something else.
> 
> sir, I want effect to disappear after 1s, so I set Lifetime to 1 and key to -1.
> 
> and following your answer, Am I making the correct changes?
> 
> dat
> ```
> GUID 7363b28a5dd248d2bebc000ff4a41803
> Type Effect
> ID 2901
> 
> Lifetime 1
> Lifetime_Spread 0
> ```
> 
> code
> ```C#
> EffectManager.sendUIEffect(effectId, -1, player.Player.channel.GetOwnerTransportConnection(), true, getPointUpdateDesc(point), eventName);
> ```
> 
> 

Remove guid and set the non -1 key
