### ISSUE TITLE
The Server I'm using through a Hosting service using Pterodactyl Panel won't let me connect to my server

### ISSUE THREAD

**Issue by KylanMonkeyMan** [SmartlyDressedGames/Unturned-3.x-Community#3913]
The Server I'm using through a Hosting service using Pterodactyl Panel won't let me connect to my server, I've tried Changing Ports in Commands.dat and Reinstalling the Server but still no luck. What happens is I try to join the Server but it says that the server didnt respond (This is after I hit Join on the Server) and then kicks me back to the lobby and says "Lost connection to host or Steam network." I've tried looking it up and nothing Helps. and Yes I have Good Wi-Fi

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/135281789/36789877-bb61-4b86-beae-e7a6a2ea6ce2

**Comment by SDGNelson** [comment]
Are both the server port and port + 1 open? e.g. 27015 and 27016

**Comment by Qwoost** [comment]
Hi. The new update has a problem with loading mods and plugins.
Players complain and don’t understand what’s going on.

**Comment by Jdance-Media** [comment]
> Hi. The new update has a problem with loading mods and plugins. Players complain and don’t understand what’s going on.

The update did have some issues with mods. Primarily the backslash issue (see #3886) and legacy methods of installing mods on the server not working (see #3877). Most of my plugins work fine with the new update, thanks to the somewhat decent backwards compatibility.

If your plugins are not functioning properly after the update, I'd recommend contacting the plugin developer and asking them to revise their plugins. Especially after a major change like the multi-thread asset loading, I highly doubt there is much that can be changed in the base game to make certain plugins work again, especially if they are using things like harmony patching. Most active developers will get back to you within a few days.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.

**Comment by KylanMonkeyMan** [comment]
> Are both the server port and port + 1 open? e.g. 27015 and 27016

I Believe so, also if I put one of the ports (I've tried 27015 - 27027) into 'commands.dat' it won't even let Me 'Connect" to the server so I can hit Join...

**Comment by SDGNelson** [comment]
Looking back on your original video it appears the port is set to 30463. In that case: 30463 and 30464 should be open for your server.

You mention using a hosting service, do they specifically offer Unturned server hosting? If so, I'd recommend contacting them as well because they'd have more experience with their setup. (I'm personally unfamiliar with using Pterodactyl)

**Comment by KylanMonkeyMan** [comment]
> Looking back on your original video it appears the port is set to 30463. In that case: 30463 and 30464 should be open for your server.
> 
> You mention using a hosting service, do they specifically offer Unturned server hosting? If so, I'd recommend contacting them as well because they'd have more experience with their setup. (I'm personally unfamiliar with using Pterodactyl)

No, They do mostly other Games. Also, How much would it Change to open those ports cause if I can get to the page for the server (Where its shows the name and Join Button) doesn't that mean that its already open?

**Comment by SDGNelson** [comment]
GazziFX is correct that the second port is important because it's the one for actual game traffic.
