### ISSUE TITLE
Color codes

### ISSUE THREAD

**Issue by zevordex** [SmartlyDressedGames/Unturned-3.x-Community#3914]
I think it's a client error with color codes on my side.
Normal descriptions turns to xml layout, how can i fix it?
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/60899690/db11ea44-356c-4fec-8471-5dd159911134)
(yep this is Arid item, but my friend have normal descriptions and some of chat messages on my side broken too)

**Comment by surv0013** [comment]
It could be the lack of a closing tag.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/17459138/f5ac94e0-fd13-4afb-b320-59d0d3727c1e)

**Comment by SDGNelson** [comment]
surv0013 is probably correct that the </color> tags are missing, however this might be a difference in behavior between IMGUI and uGUI mode: it looks like you are using IMGUI whereas your friends are probably using uGUI.
