### ISSUE TITLE
Missing effect gameobject

### ISSUE THREAD

**Issue by EternalFG** [SmartlyDressedGames/Unturned-3.x-Community#3915]
After the latest unturned updates I started receiving errors in the console when loading new workshop items in Unturned and then installing them to the server

Error in console:
Missing effect gameobject
  at SDG.Unturned.EffectAsset.PopulateAsset (SDG.Unturned.Bundle bundle, SDG.Unturned.DatDictionary data, SDG.Unturned.Local localization) [0x00055] in <c3db911e19194800a909cc385159f650>:0
  at SDG.Unturned.Assets.LoadFile (SDG.Unturned.AssetsWorker+AssetDefinition file) [0x00511] in <c3db911e19194800a909cc385159f650>:0

**Comment by EternalFG** [comment]
Note: even my old saved UIs cannot be reuploaded and used again on my Unturned Server (throws the same exception), which actually worked fine before Unturned update

**Comment by SDGNelson** [comment]
This suggests there is a problem loading the asset bundle for those effects. Can you attach the full log file please?

**Comment by EternalFG** [comment]
> This suggests there is a problem loading the asset bundle for those effects. Can you attach the full log file please?
[Server_Example.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11645445/Server_Example.log)

**Comment by SDGNelson** [comment]
It looks like the underlying error is:

`Unable to read header from archive file: C:/Users/Tesa_/Downloads/steamcmd/steamapps/common/U3DS/Servers/Example/Workshop/Steam/content/304930/2983897444/Ranks/Ranks.unity3d`

Was it exported with a future version of Unity? The current version used by the game is 2020.3.38f1

**Comment by EternalFG** [comment]
> Was it exported with a future version of Unity? The current version used by the game is 2020.3.38f1

I used editor version 2020.3.48f1

**Comment by GazziFX** [comment]
You can't use newer version of Unity

**Comment by SDGNelson** [comment]
Thanks, yes: if you downgrade to 2020.3.38f1 it should work.
