### ISSUE TITLE
Cosmetic/Skin Crafting text uses old rarity colors

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#3916]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/77992bb4-b741-4176-90d0-26a2a16611fd)

Minor visual inconsistency. The crafting recipes for some items (stat counters, ragdoll modifiers...) that have since had their rarity color changed (to no-rarity/gold-color), still use their old, unique colors in the crafting list.

Also – can the High Tier skin/cosmetic crafting yield anything besides Uncommon rarity items? If not, maybe the text should be green instead of white.

**Comment by SDGNelson** [comment]
Good points, thanks! I'll fix those up.
