### ISSUE TITLE
Problems with draw distance 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#3917]
I think u already know about this but still 
https://youtu.be/4Hrlc7xZlfc
In this video I show the problem
In short some objects just not visible untill u will come to a сlose range.

**Comment by Jdance-Media** [comment]
Odd, I can normally be on the other side of Volk and still manage to see most of the hescos, I think all of them actually. Have you trying changing some of your draw distance settings?

**Comment by Happy12222** [comment]
> Odd, I can normally be on the other side of Volk and still manage to see most of the hescos, I think all of them actually. Have you tried changing some of your draw distance settings?

I tried everything and its still the same
