### ISSUE TITLE
Embedded Chromium Support

### ISSUE THREAD

**Issue by aloshai** [SmartlyDressedGames/Unturned-3.x-Community#3920]
Chromium support may be added to Unturned. This will allow us to create more interfaces and animations and develop different content like FiveM and many other games. For example, a roleplay could be like building a second-hand market system for a game or putting your house up for sale. This feature can be offered as an option, even if it costs a little. After some research I realize this is tedious but if such a feature comes along it will be perfect for RolePlay or Minigame servers especially. We can do just about anything you can think of.

**Comment by fahrettinenes** [comment]
I totally agree aloshai at this point, we all need this!

**Comment by SDGNelson** [comment]
Closing because the Issues list is only intended for bug reports, not feature requests. Feel free to post in discussions though.
