### ISSUE TITLE
About the Unturned Module system

### ISSUE THREAD

**Issue by aloshai** [SmartlyDressedGames/Unturned-3.x-Community#3921]
We are aware that the modules we develop in the Unturned Module system affect the game. We also know that if we give it to the Client to be automatically installed, we will experience keylogger and many other problems. However, this can be prevented by making a script compiler in Unturned so that modules can be loaded automatically on the client side.

By scripting LUA or C# Client and Server side, usable methods, namespaces and other things that Nelson offers can be determined. In this way, we will not have a chance to abuse ourselves. This allows us to enable certain features that can be added and modified to the game.

**Comment by sunnamed434** [comment]
If the point is security then why not just make the module open source or smth like that, to let the users know that its ok. Btw, if the server is make sense and trust I'm sure everyone will install whatever they need and required to join their lovely server.

The idea is really cool, but the thing is more and more we see how Nelson makes his game more and more "secure" with minimal access to the client from the server

**Comment by fahrettinenes** [comment]
> If the point is security then why not just make the module open source or smth like that, to let the users know that its ok. Btw, if the server is make sense and trust I'm sure everyone will install whatever they need and required to join their lovely server.
>
> The idea is really cool, but the thing is more and more we see how Nelson makes his game more and more "secure" with minimal access to the client from the server

I agree aloshai at this point, Minecraft is also downloading texture-packs automatically once you join to a server but it ASKS to do that.

**Comment by DanielWillett** [comment]
> If the point is security then why not just make the module open source or smth like that, to let the users know that its ok. Btw, if the server is make sense and trust I'm sure everyone will install whatever they need and required to join their lovely server.
> 
> The idea is really cool, but the thing is more and more we see how Nelson makes his game more and more "secure" with minimal access to the client from the server

There's no guarantee that the code in the DLL is the same as the linked repository, and the majority of players won't know how to read it. It'd be very easy to sneak in one malicious line of code with no one noticing. It would have to be an interpreted script. 

Perhaps uScript could be modified to work client-side, then the worst you could do is a while (true) loop.
Some stuff would have to be removed obviously like database access, file IO if that's even in it, etc.

The scripts could be downloaded on join or put in mods. Only problem with this is stealing scripts would be easy, but I guess that's not a huge deal in the grand scheme of things.
If this is actually considered, the ability to call methods from the server would be needed. Some kind of invoke method like the legacy networking system could work.

`void Invoke(string script, string method);`

**Comment by SDGNelson** [comment]
Closing because the Issues list is only intended for bug reports, not feature requests. Feel free to post in discussions though.
