### ISSUE TITLE
Taking damage while the hud is disabled turns the hud back on for a brief second.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#3922]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/8f56011a-abd9-444a-9cc4-39d8e7c5c2cf

**Comment by MoltonMontro** [comment]
I believe this comment is relevant: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3860#issuecomment-1555961980

**Comment by sunnamed434** [comment]
The same issue

**Comment by SDGNelson** [comment]
Thanks for the report, however this is intended as a fix for #3827 - as Molt mentioned this is a limitation of how the UI works currently.
