### ISSUE TITLE
Playermodel Issues after latest minor update, and how to fix some other issues with the previous playermodel.

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#3926]
everyones mentioned something about the playermodel after this update in one way or another, so im just gonna try and report this in the best way possible

personal suggestion: revert the playermodel changes from this update, future changes should be ran through the preview branch so the community can comment. 👍
_also i have to update my vrchat model to match this and i dont wanna /lh_

ok, starting off:
the weight painting for the arms appear to have been changed, causing this weird uneven kinda "hourglass" look on the torso as the arms clip into it.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/7f546c5a-beb2-4224-89b0-f8bb66f49647)
_and i thought we said no to a feminine bodytype, haha /j_
from my experience with working with the model for vrchat, i learned this effect is caused when the torso does not have the correct weight painting, as the beginnings of the limbs should have a 50% weight to them, on the Spine bone.
Comparison:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/e99139f5-9cea-4b2f-8677-525f5f86aec0)
same weird hourglass on the left, normal, non-clipping arms on the right.
Another look, but T-Pose:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/bc1d3805-e3b4-4fce-a099-c8d59769f1b4)

next section is about the PREVIOUS model, before the update, an issue it has, and how to fix it.

another thing is that (pre update, this is if you revert) the left hand had a rounded edge, also as a result of a weight painting error.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/7ab2d10f-d7a9-453a-9b19-64ad64a46a4b)
this was visible ingame with certain viewmodel adjustments (which i normally play at):
![Screenshot_251](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/1f60819e-9d68-4d4b-8fe1-c1706e2e5515)
a very visible rounded corner.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/cbde70e4-df94-4258-8d65-dab79ce150bc)

**luckily, i found the solution 🥳:**

the pixel in the corner has weight painting on the **Spine,** at 0.033 weight.
eyedropping this pixel:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/9f6d276d-6c08-40e3-adca-7bb66eaebe58)
with the spine selected will show the issue.
simply clear the weight on that pixel, and boom.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/054e73df-eeee-4cfd-ab4c-46bc10014fee)
👍

**Comment by SDGNelson** [comment]
There were actually a surprisingly high number of vertices with incorrect weights in the older version if you selected a Vertex Group and click Select in Edit Mode (not just the left hand). This update removed some Vertex Groups that didn't have a corresponding bone, normalized the weights (previously they didn't add up to 1), and removed the incorrect weights. As you pointed out though I missed the non-0/1 weights on the arms ☹️ - which I will fix in the next patch or update. In the meantime closing in favor of #3918

**Comment by diddlyono** [comment]
ah, i see.
will the Model_Src in the example files be updated with these changes?

**Comment by SDGNelson** [comment]
Yes: I'll get that updated as well. 🙂
