### ISSUE TITLE
Explode_On_Impact only checks for BoxCollider

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3931]
had an explosive that used a sphere collider on the throwable prefab. Was confused why it wasn't exploding. Eventually tried making it a box collider and it started working. Evidently the game only checks for a boxcollider on this prefab when explosion_on_impact is set true.

**Comment by Spebby** [comment]
I'm unsure of what the code actually looks like, but iirc Unity has a generic "Collider" class that the other colliders inherit from, so whatever check is being done could perhaps use that instead?

**Comment by SDGNelson** [comment]
Looks like TriggerGrenadeBase.Awake assumes it has a box collider for the purposes of enabling isTrigger and expanding its size - not ideal either. Will change for the next update.
