### ISSUE TITLE
[Feature Request] Discord RPC for ALL Maps

### ISSUE THREAD

**Issue by aerodak2** [SmartlyDressedGames/Unturned-3.x-Community#3932]
Discord Rich Presence can be added to all maps as default and should can be disabled from map configuration or game settings.
If this feature needs to be easier to use modders/map makers should can add their own Application ID from [Discord Developer Portal](https://discord.com/developers/applications) 

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/56191556/95d8fc26-7542-4335-94d5-ad063dafba73)

There is a option named `Has_Discord_Rich_Presence` but a mapmaking info website says: 
`Has_Discord_Rich_Presence bool: Only valid for official maps. If discord integration is enabled and this flag is true discord will check for a map icon configured in their partner page.`

It's a bit strange that this setting only applies to official maps. Workshop Map makers will appreciate having an extra setting for all maps!

Or you can allow mapmakers made their custom RPC from Discord Developers RPC Visualizer at Discord Developer Application Settings

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/56191556/a01fb501-81d6-49d8-b5f7-d8989694d4b3)

_if it is added i will be waiting to use it_

_-aerodak2_

**Comment by SDGNelson** [comment]
Closing because the issues tracker is not intended for feature requests, and Discord integration was disabled a while ago.
