### ISSUE TITLE
Sending messages ("enter") doesnt work

### ISSUE THREAD

**Issue by Strilyx** [SmartlyDressedGames/Unturned-3.x-Community#3933]
when i go onto any server in unturned and when i type something anything js anything as a refrence lets just say i wanna type "hello" and i click my keyboards enter key it selects the text instead of sending the message into the chat. ive seen 2 topics abt this one on reddit and one on steam but both of the js stop with no explanation and no specific fix for it. is there anyone here that can help me?

https://streamable.com/5qdppb

**Comment by DanielWillett** [comment]
do you have a normal keyboard layout (qwerty)?

**Comment by Strilyx** [comment]
yes i indeed do

**Comment by Strilyx** [comment]
i fixed it

**Comment by MoltonMontro** [comment]
From Discord, where I and a couple other users attempted to help them as well:

> my keybaord was using numpad enter
> instead of the normal enter
> so i had to remap the key in my sofware
> wich i did
> and now it works

**Comment by SDGNelson** [comment]
Interesting, thanks Molt! I'm not 100% sure about uGUI but for the next preview version it should maybe worth with either Return or Numpad Enter.
