### ISSUE TITLE
Chat data not passed to ChatManager.onChatted even if it contained a hardcoded banned word. Problem for custom filters.

### ISSUE THREAD

**Issue by M10327** [SmartlyDressedGames/Unturned-3.x-Community#3934]
Hi, I run custom filters on my server using some detailed regex to automatically hand out punishments for people that say slurs, but due to how you implemented the new hardcoded filtered words, if the vanilla game's filters block a message then my filters never get to see it, and thus cannot punish the player.

From the decompiled source: 
```
if (ProfanityFilter.NaiveContainsHardcodedBannedWord(text))
  return;
Color chatted = Color.white;
if (callingPlayer.isAdmin && !Provider.hideAdmins)
  chatted = Palette.ADMIN;
else if (callingPlayer.isPro)
  chatted = Palette.PRO;
bool isRich = false;
bool isVisible = true;
Chatted onChatted = ChatManager.onChatted;
``` 
The profanity filter here does a `return` before the event is triggered, so plugins listening in on that event will never see that a player sent a message. It would be great if we could have the event fire before the hardcoded filters, then you can still block the message and our plugins will also continue to do their jobs as intended.

**Comment by GazziFX** [comment]
Quick solution: add Harmony prefix or postfix to `ProfanityFilter.NaiveContainsHardcodedBannedWord` which will change result to `false`

**Comment by M10327** [comment]
> Quick solution: add Harmony prefix or postfix to `ProfanityFilter.NaiveContainsHardcodedBannedWord` which will change result to `false`

Oh, why didnt I think of that. I used a transpiler patch to set the lines that checks the filter and the return statement to no op. Either way, it'd be ideal to not have to do any of this.

**Comment by SDGNelson** [comment]
Okay, I'll change when the event is invoked.
