### ISSUE TITLE
Search for a method to check for voice hour and get metadata

### ISSUE THREAD

**Issue by source014** [SmartlyDressedGames/Unturned-3.x-Community#3935]
Good day to everyone. Could you tell me how to check for the use of voice chat by a player and get metadata about weapons in the hands of a person? Thank you for any answer <3

**Comment by GazziFX** [comment]
You can also check `PlayerVoice.onRelayVoice` event for more advanced features

**Comment by source014** [comment]
> You can also check `PlayerVoice.onRelayVoice` event for more advanced features

Thank you for your help. I've seen plugins like "Tespy plugins" hidden on some servers in some way, but at the same time they use a plugin from the gamestores platform, how did they do it?

**Comment by sunnamed434** [comment]
> > You can also check `PlayerVoice.onRelayVoice` event for more advanced features
> 
> Thank you for your help. I've seen plugins like "Tespy plugins" hidden on some servers in some way, but at the same time they use a plugin from the gamestores platform, how did they do it?

More known name for this plugin is "LobbyManager", it hides plugins configuration and other info.

Simply subscribe to this event: `Level.onPostLevelLoaded` (don't forget to unsubscribe) and then invoke this method:
```cs
SteamGameServer.SetKeyValue("rocketplugins", null);
// Plugins are hidden
```

**Comment by source014** [comment]
Thank you all so much for your help <
