### ISSUE TITLE
Hits dont register

### ISSUE THREAD

**Issue by P9ndx** [SmartlyDressedGames/Unturned-3.x-Community#3937]
This has been a bug for as long as I can think of, but I am not entirely sure if you are aware of it yet. 
Often if you equip a melee and try to hit something really quick, so right after equipping, you often have these ghost hits where you see the hitmaker but it doesn't do any thing. You can often fix it by stopping to hit for a bit, look away or re-quipping that melee. It might only be an issue on servers as that's is the only time I have experienced this

**Comment by Wyvernaed** [comment]
The problem is that hits do not register until "action queue" is over after equip action.
For example, if after equipping you hold in turn weak and strong attack button or release and hold weak button before animation ends, then damage will still not register until queue started with equiping ends.

**Comment by SDGNelson** [comment]
Hmm I'll check into this.

**Comment by sunnamed434** [comment]
I had the same issue #3767

**Comment by QERT2002** [comment]
It's a long time issue, very common on "Rusturned" servers

**Comment by Kopfstroh** [comment]
Been having this issue for years

**Comment by SDGNelson** [comment]
Man this code is OLD. I don't think it's been updated since it was first written in 2014. I think the problem is that the animation length is used directly rather than converting it to a number of "simulation frames" like attacks. Fingers crossed 🤞
