### ISSUE TITLE
First person Emitter doesnt copy original light rotation

### ISSUE THREAD

**Issue by Wyvernaed** [SmartlyDressedGames/Unturned-3.x-Community#3940]
Im trying to made lights with shadows using spot light instead of small point light on selected gameobject:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/113861259/0109b141-71a6-4eb3-aa5e-1e658ddd2457)

But there is problem that gameobject named Emitter that simulate light in first person doesnt copy rotation of original light source:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/113861259/317729bd-e541-4396-9372-d29939afe0fe)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/113861259/64d0c3b9-6256-46bf-943f-580650d74519)

On headlamp that Emitter is not supported at all.

Can you copy rotation for that Emitter at least? At most, made it for headlamps too. Also you can check #3941 for one of solutions.

**Comment by SDGNelson** [comment]
The reason the world position is not used for the viewmodel is otherwise there is noticeable jitter even on 4x4km maps. The .dat spotlight is intentional rather than attaching lights like this because it allows graphics settings to potentially control spotlight shadows.
