### ISSUE TITLE
vanish not so vanish

### ISSUE THREAD

**Issue by P9ndx** [SmartlyDressedGames/Unturned-3.x-Community#3945]
When you are in /vanish you are only in vanish for the people that are in your render distance. When a player enters that area whilst you are in vanish already they can see you. It takes any sort of movement to go into vanish again for all users in that render area.

**Comment by GazziFX** [comment]
When player connecting he gets your real position instead of vanished

**Comment by SDGNelson** [comment]
Ideally something would/will get built-in to vanilla for this someday. (/vanish is not a vanilla feature)
