### ISSUE TITLE
Raycasting Players

### ISSUE THREAD

**Issue by StilauGamer** [SmartlyDressedGames/Unturned-3.x-Community#3947]
So after testing around with raycasting players with both the use of `Physics.Raycast` and `DamageTool.raycast(new Ray())`, I've figured out that the legs doesn't work to raycast onto.
It looks like the client model and the server model is not the same and making it hard for the server to actually know that they are legs.

Here's a link to what I am experiencing: https://imgur.com/5qRFw2g
As you can see the legs are not registering as the player meaning it returns null and it doesn't work.

**Comment by SDGNelson** [comment]
In Unity it looks like they're the same, so I'm not sure what the issue is here, sorry. Off the top of my head it's not used in the vanilla game so it's not necessarily supported.
