### ISSUE TITLE
Question : Does unturned have IPV6 support?

### ISSUE THREAD

**Issue by Sgtlog123** [SmartlyDressedGames/Unturned-3.x-Community#3949]
Like connecting to server etc.
Just a question.

**Comment by Jdance-Media** [comment]
No, not yet. It seems to be a regular topic though. Once in a while someone mentions that they want IPV6 support. Perhaps Unturned might get it at some point? dunno.

**Comment by SDGNelson** [comment]
Realistically, no. The network features do support it but matchmaking / server list APIs in Steam still use IPv4 only. Unturned's bans and helper methods also only work with IPv4, but should support both someday.
