### ISSUE TITLE
Game does not support constant keyframes for player animations

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#3951]
in unity, constant keyframes from blender work in unity on the preview character, but not on the character ingame, they somewhat interpolate weirdly.

**Comment by SDGNelson** [comment]
Constant keyframe mode doesn't interpolate between frames, so I wonder if what you are noticing is that the in-game framerate is higher than your animation. For example if your animation is 30 FPS and nothing else is moving in Unity it will look fine, but in-game if you're running at 60 FPS you'll only see an update to the animation every 2nd frame. I imagine you're using constant framerate to avoid space-switching interpolation problems which Unturned/Unity doesn't have a good solution for at the moment AFAIK. Unreal's solution for this is Virtual Bones: https://docs.unrealengine.com/5.2/en-US/virtual-bones-in-unreal-engine/

**Comment by DerEnte** [comment]
Yes, I animate at 60 fps.

**Comment by SDGNelson** [comment]
Closing if Yes means that was the issue, but feel free to comment and I'll re-open if you think there is a separate issue.
