### ISSUE TITLE
Stuck in zombies near the vehicle on exit 

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3954]
[See](https://imgur.com/zERC5Es) a gif with repro

<img src="https://imgur.com/zERC5Es.gif" width="600" height="400" />

**Comment by surv0013** [comment]
**Life Hack:**
Swap to another seat and get out of the vehicle.

**Comment by sunnamed434** [comment]
> **Life Hack:** Swap to another seat and get out of the vehicle.

but my vehicle get more damage then

**Comment by sunnamed434** [comment]
> Owch but ordinarily without god mode you should die in that situation.

I had no god mode an I could survive with such count of zombies, I turn on god mode to make a normal repro guide
