### ISSUE TITLE
Item_Dropped_On_Destroy property doesn't work

### ISSUE THREAD

**Issue by nkliev** [SmartlyDressedGames/Unturned-3.x-Community#3956]
Any modders that tried to use Item_Dropped_On_Destroy property for their barricades? It doesn't work for me. I tried singleplayer, multiplayer, even just trying to use it in vanilla assets. Nothing works

**Comment by MoltonMontro** [comment]
You probably didn't set any values for `Min_Items_Dropped_On_Destroy` and `Max_Items_Dropped_On_Destroy`.

**Comment by SDGNelson** [comment]
Thanks, Molt has now updated the next version of the docs to reflect that.

**Comment by nkliev** [comment]
thank you! my problem was that i was using the uint16 as a spawn table id, not GUID, everything works now!
