### ISSUE TITLE
Unity 2020.3 EOL

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3957]
Unity download page says

> Please note that the 2020.3 LTS stream has reached End-of-Support and 2020.3.48 is the final patch version. Please consider upgrading to a more recent LTS. The 2020.3 LTS stream will remain available for installation on the Unity Hub until August 2023.

**Comment by SDGNelson** [comment]
Yes: time for an engine update sooner than later!
