### ISSUE TITLE
Negative box colliders do not properly work in multiplayer.

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#3959]
Hello, sometime recently (I presume?) negative box colliders broke for objects. Buildings that were inverted in the negative direction for looks had their collisions broken server side. However, they still perfectly work in single player, and on client-side collisions in multiplayer (causing you to fall through but jitter upwards continuously). 

Could issue be resolved for single player and multiplayer consistency? 

Thank you, DrDallas.

Likely error message:
"BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Fridge_0/Root/Skeleton/Hinge""

**Comment by SDGNelson** [comment]
I just double-checked and it seems to work fine. Are they modded objects? My guess is that either those assets are missing (though there should be a kick for this) or that the server collision doesn't match.

**Comment by DrDallas1** [comment]
They are modded objects. Those assets are not missing, actually found this out by comparing two of the same asset, side by side, in a server environment. The one of normal scale works just fine, with correct collision, but the one on negative scale of one axis has a broken collision.

https://www.youtube.com/watch?v=NsVcRv8IOdo

Here is a demonstration.

**Comment by SDGNelson** [comment]
Thanks for the demo. Could I get a copy of that map please? I'll see if I can find anything useful for debugging the problem. It *might* be outside of our control however, though I can't imagine why it would be different between client and server.

**Comment by DrDallas1** [comment]
I have looked and tested further - turns out this issue seems only to occur with my own objects. I will investigate further.
