### ISSUE TITLE
Rich text doesn't fade away in chat

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#396]
This is because setting alpha of Text with rich text doesn't work just like that in Unity. You need a different way of doing that ;)

**Comment by Trojaner** [comment]
I can confirm this, got multiple reports about this.

**Comment by SurvivorCDG** [comment]
It's true.

**Comment by SDGNelson** [comment]
Investigated this a bit, but there doesn't seem to be any straightforward way of fading out the alpha of IMGUI rich text color tags. One option would be to modify the string every frame (color=rrggbb**AA**), but that would be insane.

**Comment by aviadmini** [comment]
I believe you could try to apply the workaround that works for Unity 5 GUI - make text a child if canvas group and set group alpha

**Comment by SDGNelson** [comment]
All of the game UI uses Unity 4 IMGUI which wouldn't be compatible with that fix.

**Comment by aviadmini** [comment]
And switching [at least chat part] to Unity UI is not an option? 
Makes much more sense than legacy system
