### ISSUE TITLE
You can see through walls

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#3960]
you can look through the walls at the military
![Unturned_A5lL4CdBGn](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/134800978/b18d53ff-4359-4bcc-adde-8ad5ae5a2b48)

**Comment by SDGNelson** [comment]
It currently depends whether the object is "medium" or "large". Closing as existing issue #3917 involves replacing these with their large equivalent. Unfortunately Unity's physics don't allow different collision masks per object but if/when they do it will be replaced with a per-object camera-blocking setting.

**Comment by GazziFX** [comment]
Why you cant tweak camera blocking mask or change this object to large and maybe combine more blocks into a single mesh?
