### ISSUE TITLE
Server Open but can't Connect

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-3.x-Community#3962]
Yeah, i know the title is very generic but I have a server that until dawn was working normally, and today it entered its automatic restart, now the server opens but no one can connect.
LOG has a strange error, I will fix it and send a print.

Ubuntu 22.04

1) The required ports are open.
2) I have already restarted the machine and validated and forced to update the server.

https://i.imgur.com/0cYkezl.png (Game Message)
https://i.imgur.com/hM9JNEA.png (Error in Log)

[log-error.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11803986/log-error.log)

**Comment by GazziFX** [comment]
Not sure which error you talking about, I noticed several of them:
- NRE on uScript load
- dlopen failed because it opens 32 bit steamclient
- failed to load vehicles because save is corrupted

**Comment by GabrielMaestre** [comment]
I was not very specific, I'm sorry, but it's the last print I left there, which has to do with "VehicleManager"

- The uScript issue can be ignored, it's just a test plugin that didn't work

- and SteamCliente is a standard problem always appears, obs and use 64x bits

**Comment by GabrielMaestre** [comment]
Yaaah that was it thanks buddy, I deleted the Vehicles.dat and it was fixed, thanks!
