### ISSUE TITLE
Reloading (Pg up) while in main menu breaks the main menu

### ISSUE THREAD

**Issue by riku8405** [SmartlyDressedGames/Unturned-3.x-Community#3963]

**Comment by SDGNelson** [comment]
I tested by reloading assets on the main menu and it seemed to work. What happened in your case? (What broke?)

**Comment by riku8405** [comment]
The buttons on the side and the counter at the top were hidden, and only the news and featured workshop showed

**Comment by MoltonMontro** [comment]
> The buttons on the side and the counter at the top were hidden, and only the news and featured workshop showed

It sounds like you disabled the HUD with the [Home] button.

**Comment by SDGNelson** [comment]
Yes, I think Molt's correct that either you accidentally pressed the Home key, or disable HUD is also bound to Page Up.
