### ISSUE TITLE
lost connection to host or steam network with pterodactyl panel

### ISSUE THREAD

**Issue by Samuuel18** [SmartlyDressedGames/Unturned-3.x-Community#3964]
Hi there! 

Before I start, I'd like to point out that I'm French, so I had to use a translator ^^'.

I've installed a Pterodactyl debian 11 panel on my Linux VPS. I installed an unturned server thanks to an "egg" found on github, but when I connect to the server, I'm returned to the main menu with the error message: "lost connection to host or steam network".

Does anyone have a solution for me ?

Thanks

**Comment by GazziFX** [comment]
Did you add additional port? (+1 to main port)
![IMG_20230621_190139.jpg](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/43498426/ea69de80-cabe-4546-9e37-c4a9109559f3)

**Comment by Samuuel18** [comment]
> Did you add additional port? (+1 to main port) ![IMG_20230621_190139.jpg](https://user-images.githubusercontent.com/43498426/247615613-ea69de80-cabe-4546-9e37-c4a9109559f3.jpg)

Which ports should I add?

**Comment by GazziFX** [comment]
Whatever you like, default is 27015-27016

**Comment by Samuuel18** [comment]
> Whatever you like, default is 27015-27016

If I've already assigned 27015 to another game?

**Comment by GazziFX** [comment]
Choose another one and make sure it displays in startuo section of the server

**Comment by SDGNelson** [comment]
Thanks GazziFX, it does sound like the issue was the overlapping ports. Were you able to get it resolved?

**Comment by Samuuel18** [comment]
Well, I wasn't expecting it, but it works! I used ports 25445 and 25446 instead of 27015 and 27016. 
By the way, excuse my absence, I was in exam period.

Thank you very much for taking the time to help me GazziFx.

By the way, I know you don't have time for this, but I really admire your work Nelson, Unturned is still so fantastic after all this time, and it makes me super happy to see that you're active to help your community. 

Thank you <3

**Comment by SDGNelson** [comment]
Thanks for your kind words, and glad to hear you got it working!
