### ISSUE TITLE
ingame vc not working

### ISSUE THREAD

**Issue by cuteycute143** [SmartlyDressedGames/Unturned-3.x-Community#3969]
My ingame vc not working, it works with steam and every other app but just not unturned all the vc settings like inbound and outbound are on and i dont know why its not working.

**Comment by SDGNelson** [comment]
Sorry for the trouble. I'd first recommend trying the steps from this article on the support site: https://support.smartlydressedgames.com/hc/en-us/articles/12112087800724-Troubleshooting-voice-chat
