### ISSUE TITLE
The ability to change the player's perspective

### ISSUE THREAD

**Issue by SurvivorCDG** [SmartlyDressedGames/Unturned-3.x-Community#397]
The matter is that I have a TDM server where there is no third-person view, but recently it became possible to give the right to use the camera for individual players without the administrator's privilege, but in order to switch to free camera mode, you must first go to the view from third person, which is impossible on my server. I see 2 ways of solving the problem. Either allow me to switch to free camera mode from the first person, or add "sendChangePerspective" to "PlayerLook".

```C#
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void tellChangePerspective(CSteamID senderId, EPlayerPerspective perspective)
{
      this.setPerspective(perspective);
}

public void sendChangePerspective(EPlayerPerspective perspective)
{
      this.channel.send("tellChangePerspective", ESteamCall.OWNER, ESteamPacket.UPDATE_RELIABLE_BUFFER, perspective);
}
```

**Comment by aviadmini** [comment]
Alternatively add option to use Freecam from 1st person
Maybe some HUD instead of shortcuts

**Comment by SDGNelson** [comment]
Now you can enter freecam from 1p which temporarily enables 3p, and once freecam is disabled it will force you back into 1p on 1p/v3p servers.
