### ISSUE TITLE
Weapons in inventory that are not "slot any" show hotkey bindings text

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3973]
Might be a leftover from when this hotkey text was added. The game doesn't check if a weapon's slot is set to "any" and will display the hotkey bindings regardless. This is also an issue on guns. Should be changed because it creates confusion for new players on what is and isn't allowed to be set as a now primary/secondary hotkey in the inventory. 
<img width="392" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/47935791/75099e9a-ae2d-49d9-bcb7-24f1663b0a3d">

**Comment by SDGNelson** [comment]
Thanks for the report, will investigate.

**Comment by Spebby** [comment]
changed title to be more accurate
