### ISSUE TITLE
Request: Option to disable asset disagreement kicking

### ISSUE THREAD

**Issue by staridiot** [SmartlyDressedGames/Unturned-3.x-Community#3974]
In game I've always liked having ample space for looting. Even an alicepack is kind of small. So I used to be able to modify the clothing items in the Bundles folder to increase the space. But now there's a check in place to make sure the server & client's files match. I've tried adding the `Validate_MasterBundle_Hashes` setting to Config.json but that gets removed suggesting its no longer a valid option. Not sure it would have allowed what I'm trying anyway. All I'm asking for is an option on the server that toggles whether or not it will kick players for having matching asset files.

The kick message in question:
```
Client and server disagree on asset "Police Vest" configuration. (File: "Vest_Police" ID: fe9c024b96504144952c055aea57c5fc)
Usually this means the files are different versions in which case updating the client and server might fix it.
Alternatively the file may have been corrupted, locally modified, or modified on the server.
Client hash is B2BACF32B7B1CCF671ABACCC2B8F38BE6C9A272F, whereas server hash is F1837ED89F48B5BD4624B2FF299EBB65E81968AB.
Client and server agree this asset is from Vanilla Built-in Assets.
```

Thanks for considering my request.

**Comment by SDGNelson** [comment]
For items on the server you can add this line to the item's .dat file:
`Bypass_Hash_Verification`

Only for items and vehicles though.

**Comment by 315923876** [comment]
> For items on the server you can add this line to the item's .dat file: `Bypass_Hash_Verification`
> 
> Only for items and vehicles though.

Hello, is this command available now? My server said “Unable to match "Bypass_Hash_Verification" with any built-in commands”
Or”Unknown entry in Commands.dat: 'Bypass_Hash_Verification'”


Game version: 3.23.12.1 Engine version: 2021.3.29f1
