### ISSUE TITLE
Main menu on preview is kinda empty

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#3975]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48765566/1c4ee2b6-8621-465e-b785-b6f9b7eb4179)

**Comment by SDGNelson** [comment]
Thanks for the report, however funnily enough this is expected/intentional: the regular menu was moved in preparation for the Buak menu event, and the reason it's hidden at the moment is because the Pride Month event is active. (it should reappear on the preview branch on July 1st)
