### ISSUE TITLE
Problem with maps that are not officially added to unturned (maps for modded servers)

### ISSUE THREAD

**Issue by Kryhaaako** [SmartlyDressedGames/Unturned-3.x-Community#3976]
Add Should_Verify_Objects_Hash to the maps or do the same as you did with curated maps so that you can't access any on-line server with changed map. In its current state, you can freely edit the map (delete, add items, etc.), thanks to which items, e.g. items lying on a higher floor, fall to the very bottom of the player's building floor and can be picked up, or trees and all other visual obstacles can be legally removed.

**Comment by Kryhaaako** [comment]
> Map creaters can add it by themselves

it cannot be changed now

**Comment by GazziFX** [comment]
Unfortunately, we don't have set this parameter, I thought we have. Will set later

**Comment by GazziFX** [comment]
This parameter was removed in version 23.1.0

**Comment by Kryhaaako** [comment]
> This parameter was removed in version 23.1.0

that's what I was talking about earlier

**Comment by GazziFX** [comment]
It should be fine. This check is now always enabled in the code
![Screenshot_2023-06-29-09-00-06-046_com.android.chrome.jpg](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/43498426/89b955fc-f777-4e52-aa68-2b6a9044c5ab)

**Comment by Kryhaaako** [comment]
> It should be fine. This check is now always enabled in the code ![Screenshot_2023-06-29-09-00-06-046_com.android.chrome.jpg](https://user-images.githubusercontent.com/43498426/249686051-89b955fc-f777-4e52-aa68-2b6a9044c5ab.jpg)

if it still works then secure your map and see if i can join the server

**Comment by GazziFX** [comment]
There's no "secure" options, try on any server and upload video, I can't play game right now

**Comment by Kryhaaako** [comment]
> There's no "secure" options, try on any server and upload video, I can't play game right now

I tried on pandahut 3 serwers and some others this works all the time

**Comment by Kryhaaako** [comment]
> There's no "secure" options, try on any server and upload video, I can't play game right now

I can make a video about it but also in 8 hours because I'm not at home

**Comment by SDGNelson** [comment]
GazziFX is correct that it's no longer optional. I just double-checked by modifying the level's trees, joined a Pandahut server, and was immediately kicked. Is this something you tested recently?

**Comment by Kryhaaako** [comment]
> > There's no "secure" options, try on any server and upload video, I can't play game right now
> 
> I tried on pandahut 2 serwers and some others this works all the time

**Comment by Kryhaaako** [comment]
https://youtu.be/UZIxKVBzeCU - one evidence

**Comment by Kryhaaako** [comment]
> GazziFX is correct that it's no longer optional. I just double-checked by modifying the level's trees, joined a Pandahut server, and was immediately kicked. Is this something you tested recently?

https://youtu.be/UZIxKVBzeCU - one evidence

**Comment by SDGNelson** [comment]
Thanks for the example! I was able to replicate that. I wonder if pandahut has a plugin that disables the level hash check. I'll email them to ask.

**Comment by SDGNelson** [comment]
Pandahut confirmed that yes, they do use a plugin to intentionally disable this on some of their servers.
