### ISSUE TITLE
Dedicated servers not accessible

### ISSUE THREAD

**Issue by maciejisnotavailable** [SmartlyDressedGames/Unturned-3.x-Community#3978]
Having an issue with dedicated servers. Installed with steamcmd on linux and configured a server with a valid GSLT, but nobody could join the server through direct connection. Nobody could join through the "Friends" tab but I could join through LAN. The server is hosted on another device in my network, so if I could join through LAN that meant that the ports were configured correctly on the computer. The port configuration should be correct on the router, then, as well. Still, nobody can connect. So I got my friend to try on their computer, on Windows, which resulted in the same issue. When trying to use ZeroTier, the same issue occurred, so I tried to bind with Commands.dat. This resulted in the issue: "Failed to connect to Steam servers because k_EResultNoConnection, still retrying" The same issues also occurred when using Hamachi. These issues were not specific to my device either, they both also occurred on my friend's machine (Windows)

It seems there were a few people reporting the same error in 2021. These issues have since been closed. I'll reference them here.

#2506 #2090 #2360

I really hope we can get to the bottom of this since I've spent the past few days trying to figure this out and I don't want to turn back now. I really love Unturned and it'd be a shame if this was how it died for me. Thank you for reading.

**Comment by maciejisnotavailable** [comment]
I accidentally mentioned a few irrelevant but similar issues. I've removed them from this comment.

**Comment by GazziFX** [comment]
Probably your provider using NAT. If you want to host server for friends you can try RadminVPN, if you need public server, I recommend using VDS or other hosting options

**Comment by maciejisnotavailable** [comment]
My provider does use NAT. I'll check out RadminVPN and thank you for the unexpectedly quick reply. What's the problem with NAT, if you don't mind explaining?

**Comment by maciejisnotavailable** [comment]
Update:

Went to my port-forwarding. Instead of adding a port range, added each port individually, and each port I added an individual rule for both TCP and UDP. Now the server can be directly connected to over IPv4 to my public IP (as expected)

I should have tried that long ago. Leaving this issue open, but leaving this information in case anybody finds it useful.

**Comment by GazziFX** [comment]
> What's the problem with NAT, if you don't mind explaining?

In NAT several clients may share same IP and router will dynamically allocate ports for each connection, port can't be allocated for incoming request (because it doesn't know which client running on that port) and your local port will be changed to that allocated port

**Comment by maciejisnotavailable** [comment]
I can confirm this is not the case for my network, though I haven't specifically checked, I remember setting a unique internal IP address specifically for this reason, and it is static.

**Comment by DanielWillett** [comment]
Just want to make sure, your friends are connecting via your public IP, correct? Not the one that shows in `ipconfig`? If not you can find this by just googling 'whats my IP'.

**Comment by maciejisnotavailable** [comment]
Yeah, public IP and not internal IP. (192.168.0.x)
The issue only affects VLAN (Hamachi, ZeroTier) connections.

**Comment by SDGNelson** [comment]
Thanks for others trying to help, however this is outside the scope of the game issues.

GazziFX's explanation is correct. You've assigned a unique local IP within your house, but your WAN address is not unique: it's shared with other houses/clients by your ISP.

The problem would be related somehow to the configuration of the tunnel/VPN regardless of which tool is used.
