### ISSUE TITLE
Boulders from Russia/Hawaii are baked as purple on Chart

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#398]
Something like this: https://www.reddit.com/r/unturned/comments/6077vf/what_are_these_purple_spots_on_my_chart_are_those/

They suggest to use hawaii charts asset bundle but I'd rather hear some sort of official advice/tutorial of making it.

Ideally any objects should render well

**Comment by aviadmini** [comment]
Only reference here: https://steamcommunity.com/sharedfiles/filedetails/?id=470770384
However the information is kind of not too helpful

**Comment by SDGNelson** [comment]
Guide has now been updated with more specific information.
