### ISSUE TITLE
GSLT issue

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#3980]
Hey @SDGNelson,

I hope you are doing well on this 4th of July weekend, I was just wondering if you have received any reports about **Steam GSLT** not working properly? To further explain on one of my client nodes we changed the port to possibly fix the Steam connection errors issue from _27015:27016_ to _25445:25446_ and it doesn't show under favorites or recently played. If you have any fixes or suggestions for this issue I'd greatly appreciate it!

Thank you!

**Comment by CyberAndrii** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3807

**Comment by SDGNelson** [comment]
Thanks @CyberAndrii, interesting to see that thread! Out of curiosity did you find it redirected after ~24 hours?

**Comment by joeymisfit** [comment]
Hey @SDGNelson,
It showed up a bit more than 24hrs after changing the port and starting up the pterodactyl instance. Due to having it restart every 12hrs of being live. Thank you @CyberAndrii for your assistance in this thread!

**Comment by SDGNelson** [comment]
Thanks! I've now noted this in the Unturned GSLT documentation with credit to both of you.
