### ISSUE TITLE
Welcome To Germany's Achievement Icon is out of date

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3982]
<img width="236" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/47935791/b8a2f409-38a5-4d05-801c-10016736f7c7">

Super minor, but it reflects the old version pre-terrain colour change.

**Comment by Spebby** [comment]
Tangentially related, the 14th and 15th screenshot on the store page is also of old Germany.
<img width="667" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/47935791/9b588043-fb1e-4934-b1d2-a7feeae10a80">
<img width="681" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/47935791/334aec88-72c5-4ec8-a4bd-81ce5147802e">

**Comment by SDGNelson** [comment]
The achievement icon is now up-to-date. At some point I will update the store page with action-oriented screenshots rather than environments.
