### ISSUE TITLE
Server is running on the different version

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3989]
The title message I started receiving after once being on the server for 2-3 hours, the server was with some count of the players, and the server is updated to the latest version

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/c9e4c62b-5000-4dc2-b659-182ceccc668d)

**Comment by SDGNelson** [comment]
Perhaps a plugin is kicking you with the wrong rejection reason? The reason I wonder this is the server version is missing from the kick message. The vanilla server provides server version as the kick reason, and then the client formats that into the message.

**Comment by sunnamed434** [comment]
I'm sure that this is not a part of the plugin, this is something else

**Comment by SDGNelson** [comment]
Is it your server? If you disable Rocket/OpenMod/plugins does it still happen?

**Comment by sunnamed434** [comment]
> Is it your server? If you disable Rocket/OpenMod/plugins does it still happen?

Yes, the server is mine,this happened only once, and it hasn't happened anymore yet. I guess it was really random behaviour

**Comment by SDGNelson** [comment]
Weird but glad to hear it fixed itself!
