### ISSUE TITLE
Snowstorm (blizzard) in certain region of map only

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#399]
What I want to achieve: snowstorm in a certain region of map only.
Afaik it's possible if that region is elevated high enough compared to rest of map but I can't seem to find a good way to calculate that in editor

Would appreciate any help

**Comment by SDGNelson** [comment]
Rain/Snow regions are used in the France map which will be a good example, or in the mean time Destruction has them as well from testing when they were first added.

**Comment by aviadmini** [comment]
@SDGNelson could you please give some more info on how to set this up?
