### ISSUE TITLE
Some unturned server issues

### ISSUE THREAD

**Issue by skMayi** [SmartlyDressedGames/Unturned-3.x-Community#3995]
I found that it seemed that the Unturned server was not working properly for commands with Chinese characters, such as: say 你好 Maybe it's a code page problem?

Another problem with the server side is that the command line window doesn't work very well, because if you want to enter a command, let's say there are a lot of people on the server, they're chatting or something, it's possible that the command line window will be overwritten by the new log content. But if you press Enter, you can still run the command.

On my server, the unturned server window seems to sometimes cause content tears (like the last log and the new log are partially overwritten), I don't know if this is a problem with the Unturned server or my server

**Comment by SDGNelson** [comment]
Sorry about these, unfortunately it's a longer-term issue: #3648
