### ISSUE TITLE
Disable the tags <style> and <align> for Desc_Server_List

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#3997]
Very self explanatory why this should be made. With `<style>` you can set bigger sizes for text than `<size>`, and with `<align>` those giant texts can be placed on the center of the screen, so while the rest of servers have their server description with a decent small text at left, this servers have this giant colored texts on the center of the screen, breaking the server list style

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/11e717fd-f325-456e-bed3-38efedaec3fb)

**Comment by SDGNelson** [comment]
Thanks for the report! I will prevent those from being used there.

**Comment by MoltonMontro** [comment]
If **\<align>** is being disabled, you may also consider disabling **\<space>**. I don't think these stand out as much given the font size being restricted, but as an example:

![Example](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/1aa22d46-459b-4c3a-946f-b9549e833403)

The above is using **\<space=30em>** to pad the description out. Note: I wouldn't be surprised if some servers are currently using \<space> for separating individual descriptive tags. E.g.,
- `[PvP][10x][Kits][Vault][TPA]` using [ ]  _vs._
- `PvP | 10x | Kits | Vault | TPA` using |  _vs._
- `PvP    10x    Kits    Vault    TPA` using \<space>

**Comment by SDGNelson** [comment]
In the next update this is hardcoded on the client. After my earlier comment I used the server moderation filters to prevent servers with these tags from being visible.
