### ISSUE TITLE
Send help for sendHallucination

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#400]
Just tried it out and it happens to have a few limitations:
1) It's uncancelable unless you send `tellLife` packet that resets it along with doing tons of redundant stuff. Sending lower value is negated by Max(current, new)
2) There is no control over actual hallucination in PlayerLook, PlayerMovement, PlayerEquipment and PlayerUI. Those are totally random with certain chance 

This can be also be an interesting feature for workshop - control exact effects that consumable applies

**Comment by SDGNelson** [comment]
Moved max(current, new) into consumeables, so you should be able to cancel hallucinations now.

**Comment by aviadmini** [comment]
What about 2?

**Comment by SDGNelson** [comment]
Server control over the specific hallucination effects likely won't be added
