### ISSUE TITLE
Buak Bug

### ISSUE THREAD

**Issue by agfshgafadgadfadfadnhgf** [SmartlyDressedGames/Unturned-3.x-Community#4000]
After finishing the last wedding quest, the members of the safe zone do not move and the key does not appear anywhere
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/78652687/74e9f7da-d534-460f-b51f-862a80e35932)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/78652687/869cfa97-a0f1-44e4-b741-33db9399acde)

**Comment by SDGNelson** [comment]
Did you give the the ring already?

**Comment by agfshgafadgadfadfadnhgf** [comment]
Yes, I did.

**Comment by diddlyono** [comment]
you need to speak to amber
(this one)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/0c44b073-f090-48da-b81f-558491b9ca88)

and ask how shes doing. she says "i hope this day never ends" or somethin then it _comically_ ends right after.
then ask them (forgot which one) about the key, then it appears in the tent behind them.

**Comment by agfshgafadgadfadfadnhgf** [comment]
> you need to speak to amber (this one) ![image](https://user-images.githubusercontent.com/67235885/252883780-0c44b073-f090-48da-b81f-558491b9ca88.png)
> 
> and ask how shes doing. she says "i hope this day never ends" or somethin then it _comically_ ends right after. then ask them (forgot which one) about the key, then it appears in the tent behind them.

lemme check because i think i have to press that dialogue option after she says that

**Comment by agfshgafadgadfadfadnhgf** [comment]
that was it, sorry for the inconvenience

**Comment by SDGNelson** [comment]
Glad to hear it was resolved, thanks @diddlyono!
