### ISSUE TITLE
White Buak

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4004]
One player from my servers is reporting that there's an issue with the map, that nothing happens and the map is full white.

Player tried to:
1. Exit the game
2. Cleanup all workshop
3. Verify the game via steam
4. Run again and join the server

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/3e0ae5e0-dffd-46eb-97c8-16023626afb1)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/6f605028-fc59-432b-a177-3925a390b07f)

**Comment by CyberAndrii** [comment]
This can happen either when using `-SkipAssets` or when the map's Bundles folder is missing. In UO discord he said he's copying map files around instead of using WorkshopDownloadConfig.json so the second option is more likely. Not really an issue with the game tho.

**Comment by SDGNelson** [comment]
Sorry about this! It should hopefully be fixed with the .1 patch this morning. Does it work properly when they join now?

**Comment by sunnamed434** [comment]
> Sorry about this! It should hopefully be fixed with the .1 patch this morning. Does it work properly when they join now?

Will check if it work fine now

**Comment by sunnamed434** [comment]
Just got a new report by the same player
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/fb4690e3-6b60-4241-98cc-742cc09007ae)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/c4070844-ad91-4bdb-9ca7-e8a4ba5ec538)

**Comment by sunnamed434** [comment]
Breaking: he just reinstalled the unturned, and it worked!
