### ISSUE TITLE
Add player equip event

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#401]
There should be an event for players equipping weapons or tools.

I've seen plugins that try restricting what a player can equip with a timer to check if the player is equipping an item, then dequipping it. That's a pretty terrible way to do it.

Thanks! :)

**Comment by SDGNelson** [comment]
Similar to barricade manager I've now added equip/dequip request handlers so that you can cancel attempts to equip/dequip

**Comment by Johnanater** [comment]
Thanks for adding it, but shouldn't onEquipRequested be static so we can use it?

**Comment by Johnanater** [comment]
@SDGNelson Sorry for the tag, but is it supposed to not be static? If so, then how do you use it?

Thanks!

**Comment by Johnanater** [comment]
Ah, I didn't know you could hook into events with OnPlayerConnected, thanks!
