### ISSUE TITLE
"Flanker_Chance" not applying changes on vanilla Germany map

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4012]
Basically I was trying to disable the flankers zombies on Germany. While I was able to disable it on PEI and Washington with       `"Flanker_Chance": 0.0`, this didn't worked on Germany and those zombies are still spawning

**Comment by SDGNelson** [comment]
It's probably the zombie difficulty assets on Germany, sorry, they override the gameplay config currently.
