### ISSUE TITLE
OnPlayerUpdateStance doesn't work as intended.

### ISSUE THREAD

**Issue by XShine555** [SmartlyDressedGames/Unturned-3.x-Community#4014]
When you use the OnPlayerUpdateStance event and the player changes his state, it doesn't work as intended and only works if you change it manually (Player.stance.stance = EPlayerStance. PRONE). Also, there isn't any way to prevent the player to change his state like OnEquipRequested do (shouldAllow).
```
protected override void Load()
{
            UnturnedPlayerEvents.OnPlayerUpdateStance += OnPlayerUpdateStance;
}

private void OnPlayerUpdateStance(UnturnedPlayer player, byte stance)
{
           Console.WriteLine(stance);
}
```

**Comment by GazziFX** [comment]
If you disallow prone it will cause sync errors as it will be received on client later than on server and client won't be able to determine from which tick start resimulation. Its better if we have per player allowed stances, which would be also client-sided

**Comment by GazziFX** [comment]
If you really understand what you trying to do then you need to make patch in `PlayerInput.FixedUpdate` around `SendSimulateMispredictedInputs.Invoke(...)`

**Comment by SDGNelson** [comment]
To double-check: are you saying that you are overriding the player's stance when that event is invoked?

**Comment by XShine555** [comment]
Yes, the idea was that if the player is bleeding he cannot get up and has to be in a prone position, but as I said before the event isn't triggering when the player changes his stance and only triggers when you change his stance manually per example.
```
protected override void Load()
[
    UnturnedPlayerEvents.OnPlayerUpdateBleeding += OnPlayerUpdateBleeding;
}

private void OnPlayerUpdateBleeding(UnturnedPlayer Player, bool Bleeding)
{
    // For some reason this will trigger the OnPlayerUpdateStance event, but when the player changes his stance normally it doesn't.
    Player.Player.stance.stance = EPlayerStance.PRONE;
}
```

**Comment by SDGNelson** [comment]
The game is probably setting the stance after the event is called so overriding it is ignored for now. Currently the server overriding stances isn't well supported. One less-optimal way of doing it would be to check periodically whether the player is standing and override the stance.
