### ISSUE TITLE
Negative values for item stats

### ISSUE THREAD

**Issue by biedakxyz** [SmartlyDressedGames/Unturned-3.x-Community#4017]
It's a pitty we can't make player lose some hp, hunger, water etc with consumable items. Only thing that we can take from player is immunity. Same goes for weapon attachments. You can't make weapon shot slower. It isn't anything complicated to do and it would honsetly make modding more unique.

**Comment by SDGNelson** [comment]
It would make sense to support negative values for those properties, but closing this issue for now because the issues list isn't intended for feature requests, sorry.
