### ISSUE TITLE
Stuck on Loading screen

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#402]
![unknown](https://user-images.githubusercontent.com/37576886/45238385-f1dd5480-b2e1-11e8-9556-8d02a6f971e2.png)

I've got report from more players having this "bug". This happens since the last update (which was supposed to fix the server crashes by hackers)
The bug is, they can NOT join a server, if they restart their router, game, pc, doesn't matter, won't fix their problem.

These guys are not banned, and trying to join server which they played a half hour ago or so.

I think it isn't server sided problem, since other players can calmly play the server while the "victim" can't even start load into it. So as i noticed, it happens to random players and on random servers & maps, not only one.
(The server(s) i talk about aren't using any workshop items and i never got reports about that trouble before the last updates) (Reports were taken from different people, trying to join different servers on different days.)

**Comment by baranmod** [comment]
I can approve this. I also got reports from some players getting time-out on loading screen (only a few tho). Its fixing randomly for them. Like one day they can't join whatever they try and other day they can join without a single problem

**Comment by lvlbgn** [comment]
Same here, while it's been already fixed for the owner of the picture i sent as starting of issue, on next so (to)day i've got a report again from an other player.

**Comment by SDGNelson** [comment]
I got an interesting log file the other day which I think has narrowed this down, but one thing I'm curious is if you get any exceptions from plugins hooking onTriggerReceive.

**Comment by lvlbgn** [comment]
[errorscollected.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2365675/errorscollected.txt)
I've checked logs for any exceptions, but could not find (probably) anything with "onTriggerReceive"
Possibly i didn't understand you well.
I've also contacted the plugin creator if he uses anything like that just to make sure every way. (He answered, the plugin doesn't use anything like that.)

Till that, i've collected a few exception which is probably related to Unturned and not a plugin.
In the errorscollected.txt file you can find them, i also noted which map i see the errors on.
PEI map has an error which i think caused by the Jail Doors on Prison, since similar error happens on sandbox server while they are trying to spawm the jail door (/i jail)


Sadly i have no idea for the other errors, but on Germany map i saw a "onTriggerEnter" one (this map was one which a player could not join to) I sent all the errors i found, it isn't too much but still.

However, most of the errors surely has nothing to do with our current issue, so if needed, i can open an other one just for them.

To short my answer: No i didn't get any exceptions with that.

**Comment by SDGNelson** [comment]
Thanks for the comprehensive error log lvlbgn! I've introduced additional checks to several of those now, and exceptions will now be caught when invoking RPCs so that the rest of the network update continues properly.

**Comment by SDGNelson** [comment]
Do things seem more stable after the release of the patch yesterday?

**Comment by lvlbgn** [comment]
Depends what you ask about.
I still see errors …… okey well, it seems this became worse. (by the reason it happens more frequently)
Now i started to see an error (https://hastebin.com/quzavudeqo.css) on PEI and Washington map which literally spams the server (happens a lot of times in 8 hours)

I also see (but i saw Null error before aswell) this: (https://hastebin.com/amawibobor.css) (RUSISA MAP)

However, the Germany one, which was a short error shown in my comment above, so since the release of patch yesterday, i didn't see it.

I also found an error on a sandbox server with washington map which i probably didnt see yet. (https://hastebin.com/godazucoqo.css)


Plus i can tell, the Loading stuck, which is the start of this issue, still isn't proved to be fixed.
I got only one report since the release, uhm.. exactly after the release of patch, an US player got the same bug. He said, he tried reinstalling the game, verifying, pc restart, nothing worked, and then 2 hours later he could join again.
Maybe this could be only for him.. or this can be a proof that the loading bug isn't fixed yet.

That's all i could say for now but i Will keep watching, plus going to record a few other ingame bugs which you would see proof for (probably)

**Comment by SDGNelson** [comment]
The contents of those links appear to be gone now, but if I recall correctly it was an item-specific Useable exception. For the next update I've improved that to log which item caused the problem so that it's easy to track down.

**Comment by lvlbgn** [comment]
""""Looking through the code I found this comment from back when claim flags were added lol "// No vehicle claims (yet?) depends if that's balanced", for the next update claim flags on vehicles will prevent others from building on that vehicle.""""

These are your words, saying you Will turn on CLaim Flag's effect on vehicles.
This is an really bad decision. My report was about to turning off players able to placing claim flags on vehicles. So what i wanted to say to DO NOT let claim flags be placed on vehicles since they have no effect.
But if you turn it back on, did u realize, they Will be able to move under houses to troll / claim them? In my opinion it Will be hardly glitchy and buggy!
I say that here cuz u closed my isssue.



About the errors, the links were sent days ago and hastebin prob deletes it, didn't know that Will happen so i collect you the errors in a txt.
I also commented each error again in the txt file.
[errorpack.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2386359/errorpack.txt)

**Comment by SDGNelson** [comment]
You can still comment on closed issues. Claim flags on vehicles only impact that vehicle, so you won't be able to claim bases just by driving near them.

**Comment by SDGNelson** [comment]
As for the jail door: you're right that the serverside version was misconfigured, and will be fixed in the next update along with asset errors for that problem in the future.

**Comment by lvlbgn** [comment]
I would like to ask, is there anything new about that stuck on loading screen?
I've got only one report since your last released small update. (After 1 day) This could be a problem only for him, or the players just didn't report it anymore..

Maybe it's fixed already as i believe.

**Comment by SDGNelson** [comment]
If it's only one report across the past five days it's probably resolved then! Hooray!

**Comment by lvlbgn** [comment]
https://cdn.discordapp.com/attachments/359365952980385813/491620923498037248/Zrzut_ekranu_31.png

Sadly, the reason why we didn't get report, it's because happened only for non-talking players.
Today i've got 2 different reports playing 2 different servers
They had the bug again. While others are playing on the servers without any problem.

**Comment by SDGNelson** [comment]
Does the server log file (Unturned_Data/output_log.txt) mention any refused connections?

**Comment by lvlbgn** [comment]
I can send you my whole output log and you can check it but i ask you to add me on discord then cuz i wouldn't share it since i don't rly know what it contains

**Comment by SDGNelson** [comment]
Ah thanks for the log, interesting... I believe what's happening is that the client is invoking a different RPC, but the indexes are rebuilt before that RPC arrives causing a mismatch. Should be fixed in a patch within the next day or two alongside some other changes.
