### ISSUE TITLE
Hotbar keys while player is in modal state

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#4024]
If you press hotbar keys in almost any mode that activates cursor (Release Cursor hotkey, emote wheel, object interaction, plugin modal) it'll be resetted. This should work only in inventory menu, isn't it? It's pretty frustrating as you can press them occasionally :(

**Comment by SDGNelson** [comment]
Thanks for the report! It was checking whether the inventory menu was the active tab, but not whether that dashboard was open.
