### ISSUE TITLE
Bug Report - Train Cars 

### ISSUE THREAD

**Issue by FillipoPL** [SmartlyDressedGames/Unturned-3.x-Community#4028]
# Bug Report

## Description
Destroying a train vehicle (with _VehicleManager_) does not remove the cars. Train cars left behind are blocking the railroad tracks and are not synchronized for new players

## Current behavior
- train cars are not destroyed when destroying a train vehicle (_InteractableVehicle_)

## Expected behavior
- train cars are destroyed when the train is destroyed

## Cause
- train cars parent is set to null during vehicle initialization
- train cars are not destroyed manually in the methods responsible for destroying vehicles

## Solution
Change _VehicleManager.ReceiveDestroySingleVehicle_ and _VehicleManager.ReceiveDestroyAllVehicles_ implementation.
1. Setting train cars parent to train vehicle (used on the video) **OR**
2. Deleting each train car "manually"

## Video
https://youtu.be/ZyVAkjgpwkE

I can provide the code that was used in the video or demonstrate it on a live server.

**Comment by SDGNelson** [comment]
These two posts are very thorough, nice work, including making your own implementation! Sorry to disappoint however both that the issues list is only for bugs (not proposals), and destroying trains / changing tracks is currently unsupported. Perhaps it might happen if steering for trains is added. (e.g. hold left to take the left track)

**Comment by FillipoPL** [comment]
> These two posts are very thorough, nice work, including making your own implementation! Sorry to disappoint however both that the issues list is only for bugs (not proposals), and destroying trains / changing tracks is currently unsupported. Perhaps it might happen if steering for trains is added. (e.g. hold left to take the left track)

I'd like you to at least take a look at the cars destruction, because this error is directly caused by using the public methods `askVehicleDestroy`, `askVehicleDestroyAll`.
I didn't mention this in the original post, but cars from destroyed trains are blocking new players but not rendering for them (collision comes from the server).

Fix for this takes no more than 10 lines of code and solve a problem that has been present since the introduction of trains.

**Comment by nikiternak5269** [comment]
I really like this idea. Many systems are available on the Internet, but they do not improve from update to update. It would be nice to see their improvement, the same possibility of turning trains on the tracks. But to do this, you need to make a good fork in the road to the trains. It would also be cool to have an object that would move around the map as an object, but you could also walk on it. The Unturned roadmap is also very far behind what is currently available. Electrics - eh, it would be nice to have one, some ideas are really good. But it will be a very very long time yet
