### ISSUE TITLE
Proposal - Changing train road and roadPosition

### ISSUE THREAD

**Issue by FillipoPL** [SmartlyDressedGames/Unturned-3.x-Community#4029]
# Proposal
## Description
Add two network methods *ServerSendRoadIndex* and *ServerSendRoadPosition* that allow to send the roadIndex and roadPosition of a specified vehicle from the server to clients.

## Reasons
- trains are now assigned to a road (specified in map configuration file) during vehicle initialization, which cannot be changed during the game.
- changing train road is a complex process that requires restarting the server, editing the map and uploading it to the workshop. 
- current implementation also limits spawning new trains on many railways, limiting it to spawning new trains on the first matching road.
- changing roadPosition is not possible, when the player is in the vehicle
Both methods can solve listed limitations.

## Example solution/use
https://youtu.be/Eyj7byaqdmY

I can provide the code that was used in the video or demonstrate it on a live server.

**Comment by SDGNelson** [comment]
Closing as part of reply to #4028, sorry.
