### ISSUE TITLE
Missing tellBarricade in SteamChannel.onTriggerSend

### ISSUE THREAD

**Issue by Alekaei** [SmartlyDressedGames/Unturned-3.x-Community#403]
the tellBarricade packet is missing from SteamChannel.onTriggerSend event. It is only invoked when placing barricades on vehicles but not when placing barricades on the ground, this is because the SteamChannel.send method that is being used (the one with the region data being passed) doesnt invoke SteamChannel.onTriggerSend at any point, it should be a easy fix and would help a lot.

**Comment by SDGNelson** [comment]
The onSend/onReceive events exist for compatibility so that Rocket didn't have to inject into the game's assemblies anymore. What purpose do you need? Parsing packet traffic isn't the cleanest option.

**Comment by Alekaei** [comment]
well i was gonna turn the packet data into the following events, onBarricadePlace, onStructurePlace, onBarricadeSalvage and onStructureSalvage. It was all going so well until i tried to get tellBarricade since it didnt work while tellStructure, askSalvageBarricade and askSalvageStructure worked fine

**Comment by SDGNelson** [comment]
In the next update you can listen for onServerWritingPacket and onServerReadingPacket events, as well as onBarricadeSpawned and onStructureSpawned!
