### ISSUE TITLE
Gun disappears while shooting

### ISSUE THREAD

**Issue by Noamm0** [SmartlyDressedGames/Unturned-3.x-Community#4031]
Gun just disappears while I'm trying to shoot, hit or something else. When I try to shoot or hit I'm starting to punching air.

I will say that it happens on all server and all maps. I didn't change any of game files. I reinstalled game and nothing changed.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/140642717/70870d79-3036-420f-b1a9-125e63c6b7ea

**Comment by Noamm0** [comment]
> clearly you changed some stuff in your game files. your arms looks like spaghettis when punching

I don't think so viewmodel can do something like this.

**Comment by SDGNelson** [comment]
It looks like you're dequipping your item when you attack. My guess is that Dequip accidentally got bound to Left Mouse in the Controls menu, or that a macro is accidentally pressing the Dequip key.
