### ISSUE TITLE
Incorrect ban

### ISSUE THREAD

**Issue by chenyicheng311** [SmartlyDressedGames/Unturned-3.x-Community#4035]
Hello dear Nelson, I know this is not being discussed here, but I hope Nelson will be taken seriously, because my account has a lot of trinkets and is very expensive! At that time I just reinstalled my computer system, and I installed Chinese patch, because my English is not very good, and Chinese patch does not have anything to disrupt the game balance, I changed the hard drive label and serial number, which may affect Wareye? But none of this upset the balance of the game, why was I banned? Please explain to me reasonably! Thank you!

**Comment by Jdance-Media** [comment]
https://support.smartlydressedgames.com/hc/en-us/articles/12082986788884-Multiplayer-bans

**Comment by SDGNelson** [comment]
Sorry, but Jdance-Media is correct that article has the applicable information (thanks Jdance)
