### ISSUE TITLE
Vanilla Map Asset Bug BSOD

### ISSUE THREAD

**Issue by MacKinnon7** [SmartlyDressedGames/Unturned-3.x-Community#4037]
**I get a BSOD when baking a satellite image when the ObjectAsset (Infinite Stairs Example) is placed on the map.
while making a map i placed it to see it try it and did all of that everything was fine then i decided to bake Satelite then as per usual it takes a few seconds but this time im met with a BSOD after the BSOD the map loses its set materials in the TILES bar so you have to set them again hope this helps making the game less bugged.
Thanks for the lovely game nelson i played for about 5000 hours and i still cant get enough.**
if u need to contact me
Discord: mackinnon
Steam: https://steamcommunity.com/profiles/76561198297062740/
Email: 7thsteel.n17@gmail.com

**Comment by GazziFX** [comment]
It may be caused by RAM or VRAM overflow, Satellite capture resolution was increased year ago. You can try increase page file.
Also please attach logs [https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash](instruction) and specs of your PC

**Comment by MacKinnon7** [comment]
after removing the infinite stairs the Satelite Bake was fine
but before i got BSOD

**Comment by SDGNelson** [comment]
Thanks for your longtime support, 5,000 hours wow!
GazziFX is correct that yes if you can submit a support ticket about the crash through that article please I can better investigate further. (thanks GazziFX)
