### ISSUE TITLE
Error Ban

### ISSUE THREAD

**Issue by MaoMao520twit** [SmartlyDressedGames/Unturned-3.x-Community#4038]
Hello, dear Nelson, I read the https://support.smartlydressedgames.com/hc/en-us/articles/12082986788884-Multiplayer-bans carefully, I first got the ban of BattlEye, Today I logged in and it became a "ban imposed by the game developer" and I sent a complaint message to BattlEye (https://www.battleye.com/contact/
I waited 48 hours and I didn't get any response! I need an explanation! My account is worth 500+ RMB names, I want to know why I was banned? Why? I will not end this without a reasonable explanation! Why didn't BattlEye reply? Why am I banned? The reason?
My steam https://steamcommunity.com/profiles/76561199260758255/

**Comment by MaoMao520twit** [comment]
I'll get to the bottom of it until it's dealt with properly!

**Comment by CatzMR** [comment]
He is an excellent server plug-in developer and creative workshop mod maker in China. I don't quite believe he will be punished by Battleye. As far as I know Battleye has wrongly banned plugin developers.

**Comment by CatzMR** [comment]
#1618

**Comment by MaoMao520twit** [comment]
@SDGNelson

**Comment by MaoMao520twit** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/98081801/36386748-077c-4509-912b-3995a4336ff6)

**Comment by MaoMao520twit** [comment]
![{)6 AJTBPIKS)1}9DAMWX_Y](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/98081801/09d25f90-0ffd-405a-beaa-a916b64124dd)
From MCrow (https://unturnedstore.com/products/1535)

**Comment by MaoMao520twit** [comment]
@SDGNelson sad

**Comment by SDGNelson** [comment]
No need to spam. Considering the circumstances I've now submitted a ticket to BattlEye to double-check.

**Comment by MaoMao520twit** [comment]
@SDGNelson Any results?

**Comment by SDGNelson** [comment]
It sounds like they are confident it is a valid ban, and some of your alt accounts were detected with the same cheats shortly afterwards.
