### ISSUE TITLE
Server in ban but on site no information :/

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4041]
Server in ban, but on site with bans no info:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/e1dd48c6-6ffb-4088-914e-6e9a96d0efee)

Very important issue, because idk what what should I do.

**Comment by SDGNelson** [comment]
You know that your server "FUNNYPLAY" is UNITYPLAY, and you know why it is banned.
