### ISSUE TITLE
Hostile animals dont play Startle animation

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4043]
Whenever hostile animals encounter player, no matter if the player shoots them first, or just gets spotted, they instantly start chasing him, playing Run animation, without startling. If startling upon seeing/being shot at by player isnt supposed to be a thing, then I dont understand why vanilla Wolf and Bear have these animations in their animation sets.
So if its a bug, it should get fixed, and if it wasnt intended in the first place, well, then I think it would be a good addition, because the way they start chasing you instantly right now looks silly.

Also while testing this, I noticed that if player, chased by a hostile animal stops, the animal starts running in circles around the player, making it impossible to hit it with a melee weapon or fists, at least if its a wolf or something as small. I guess its because of the Capsule colliders bumping into each other, while the is animal trying to get closer to the player's origin point. Should be addressed too, in my opinion.

**Comment by SDGNelson** [comment]
Thanks for the report, in the next update it will play when the animal detects a player.
