### ISSUE TITLE
Scope missing atributes under low resolution 1024x768

### ISSUE THREAD

**Issue by Kubusiek3** [SmartlyDressedGames/Unturned-3.x-Community#4044]
![scope5](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/e5afcd6a-e01a-4fc2-95a5-cb5c5ac19281)
![scope1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/c6e6e7a4-08b9-49d8-83f7-2822fc872728)
![scope2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/3861426d-e1d0-484b-8133-d90a621dffed)
![scope3](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/bddb62b8-0f23-476e-bae5-57c86af51325)
![scope4](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/5b3f8b46-83ae-4962-bdd3-a165d9d80787)

**Comment by SDGNelson** [comment]
Sorry, there isn't currently a plan to fix this because the scope texture which has 1 px wide lines is getting scaled smaller than its resolution. If scopes are updated to draw without using textures (similar to the distance markers) then it would be fixed.

**Comment by GazziFX** [comment]
Wouldn't mipmaps help with that?
