### ISSUE TITLE
Animals child models renderers not getting turned off

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4046]
The game turns off mesh renderer of Model_0 of an animal when it dies, but it doesnt turn off renderers of any other models that are in animal's hierarchy. This leaves these models still visible, hanging in the air after animal's death.
I guess some code, that would search animal's hierarchy for mesh renderers and turning all of them off, instead of a specific one would solve this.

PS: No, I couldn't make all the meshes for animal as one model for material animation reasons

**Comment by GazziFX** [comment]
Maybe disable whole GameObject?

**Comment by SDGNelson** [comment]
As a workaround for the meantime if your reason for multiple meshes is material animation can you use multiple material slots with a single skinnedmeeshrenderer?

**Comment by SDGNelson** [comment]
Closing for now but feel free to comment and I will re-open.

**Comment by DerpyHoowes** [comment]
The problem is that when animating properties of one material, properties of all the materials attached to the same mesh are affected. Mainly I was working with the texture offset for the facial animations of human-looking hostile animals using the texture offset to change the face displayed. But animating offset of the face materials also affects the offset of body material too, so I had to make it as a separate model, hence encountering this problem.

**Comment by SDGNelson** [comment]
Interesting. I would have thought animation tracks could refer to the specific material's parameters. I'll what the implications of enabling/disabling the gameobject would be.

**Comment by SDGNelson** [comment]
I should have revisited this much sooner. My apologies for the long delay.

When I wrote that comment I think I was considering activating/deactivating the animal game object. A simpler option might be to activate/deactivate the model_0 and model_1 objects so something else can be nested underneath. I believe I need to be very careful when making changes like that, however, as a lot of mods nowadays are attaching scripts to game objects to extend behavior, and these kind of changes could easily break that. For newer features we've been exposing more settings in the asset .dat files as to exactly which game objects should be modified and in what ways, but I don't have current plans to do bigger updates to animals, so I'm going to close this as not planned for the meantime.
