### ISSUE TITLE
Target decalable shader causing issues

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4047]
Vanilla target's ragdoll acts weird because of it's decalable shader. Probably should switch it to Standard. Not sure if this was intended, because I cant think of any use to having decals being displayed on ragdolls.

Also could it be possible that some other breakable objects' ragdolls use this shader?
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/3d9de506-96ff-45ef-bdfe-2c2a6e1b54cf)

**Comment by Jdance-Media** [comment]
If I'm not mistaken, I believe it has the decalable shader so that bullet holes would be shown.

**Comment by iBowie** [comment]
Bullet holes cannot be seen anyway since target is one hit. But the initial suggestion is to change material to a non-decalable one when ragdolling.

**Comment by SDGNelson** [comment]
Jdance-Media is likely correct that this changed when effects like bullet holes became attachable in multiplayer. At some point I do intend to transfer network attachments from the live model to the dead model (e.g. trees) so I don't think this is worth changing in the meantime, sorry.
