### ISSUE TITLE
Error Ban 2

### ISSUE THREAD

**Issue by MaoMao520twit** [SmartlyDressedGames/Unturned-3.x-Community#4048]
The same cheat? Are you serious? XD, I just reinstalled the system, I changed the mechanical code, disk serial number, because this is changed automatically, why is it cheating?? What are you talking about? Is this your attitude towards banned players in China? I also had an account banned before, but it was not very expensive, but this account is very expensive, you have to give me an explanation, for example: which program is a cheating program, tell me.

**Comment by MaoMao520twit** [comment]
@SDGNelson I also banned multiple cheaters on my own server, and it was impossible for me to use cheats.

**Comment by MaoMao520twit** [comment]
I don't know why my reinstallation caused all my unturned games on this computer to be banned, why? Just because I reinstalled the system?

**Comment by SDGNelson** [comment]
I'm sorry but I can't help any further. BattlEye is confident your ban is legitimate, and based on your earlier post (#2997) you were patching the game client which isn't allowed on BattlEye-protected servers.

**Comment by MaoMao520twit** [comment]
I didn't patch the game client! Chinese patches are not allowed? So why aren't players who install Japanese patches and patches in other languages banned? Why?

**Comment by MaoMao520twit** [comment]
@SDGNelson I didn't patch the game client! Chinese patches are not allowed? So why aren't players who install Japanese patches and patches in other languages banned? Why?
