### ISSUE TITLE
Error ban 3

### ISSUE THREAD

**Issue by MaoMao520twit** [SmartlyDressedGames/Unturned-3.x-Community#4049]
I didn't patch the game client! Chinese patches are not allowed? So why aren't players who install Japanese patches and patches in other languages banned? Why?If Chinese patches are banned, then you should ban 80% of players in China, why not?

**Comment by MoltonMontro** [comment]
Please don't spam the GitHub repository – if it's disruptive, it can result in being blocked from the GitHub repository. This is not the appropriate place for ban appeals/inquiries, and spamming makes it more difficult for others to use the repository for its intended purpose.

I understand your frustration with having received a multiplayer ban. Your original inquiry has already been answered to the best of our capabilities at this time, which included directly reaching out to BattlEye Support on your behalf. BattlEye was confident that your ban is legitimate. Please refer to this message again: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4048#issuecomment-1664776569.

Thank you.

**Comment by MaoMao520twit** [comment]
Because I'm now prompting a ban from the developer, I tried to complain to BattlEye, they didn't get any response, I won't stop, it's not spam, it's a protest from a security player

**Comment by MaoMao520twit** [comment]
Why are other developers like me lifted? I can't? Just because I'm Chinese?

**Comment by TH3AL3X** [comment]
Don't worry, I also received a ban for the use of "cheats" when I was doing debugging and I'm still banned, in addition to Nelson banning my unturned servers for creating a spoofer thats allow me to play his game....

> Why are other developers like me lifted? I can't? Just because I'm Chinese?

**Comment by TH3AL3X** [comment]
In addition to having appealed millions of times and that users of my server appeal for me and that they want my servers to return lol...

**Comment by MaoMao520twit** [comment]
It's disgusting, disappointing...
