### ISSUE TITLE
Events "onItemDropAdded" and "onItemDropRemoved" do not work

### ISSUE THREAD

**Issue by SurvivorCDG** [SmartlyDressedGames/Unturned-3.x-Community#405]
And if not difficult, you can add new variables.

```C#
public delegate void ItemDropAdded(CSteamID steamID, byte x, byte y, ushort index, ushort id, Vector3 point);

public delegate void ItemDropRemoved(CSteamID steamID, Transform transform, InteractableItem item, ref bool shouldAllow);
```

P.S. If the item was spawned by the server, then the CSteamID is 0.

**Comment by RoyIL** [comment]
Why do you want to get the CSteamID lol?? 
However the changes you offered for ItemDropAdded is just for lazy devs and you can check the changes you offered with like 3 lines. 
The only thing that might be useful here is shouldAllow...

**Comment by SurvivorCDG** [comment]
@RoyIL I really only need "ItemDropAdded" to delete certain items as soon as they appear, and not check every second who threw it out.

**Comment by RoyIL** [comment]
@SurvivorCDG I don't understand how any of the changes you offered are going to help. 
The only thing useful in this ticket is that the event is broken? (I don't really know because I never used it)

**Comment by SurvivorCDG** [comment]
@RoyIL Yes, it's broken.

**Comment by SDGNelson** [comment]
Those events are only used clientside, and operate on the physics-simulated dropped items (which the server doesn't spawn) which is why your serverside plugin isn't receiving them.

I'll add an event to allow preventing items from being dropped serverside.

**Comment by SDGNelson** [comment]
In the next update you can listen for all item spawns (including level startup) and allow/disallow with onServerSpawningItemDrop, or per-player drops with onDropItemRequested.
