### ISSUE TITLE
Turret_#_Aim_Offset is unimplemented

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4050]
It looks like vehicle turrets have a property called ``Turret_#_Aim_Offset``, but this doesn't seem to do anything / doesn't look like it's been fully implemented.

Maybe this property was removed at some point, or perhaps it's always been unimplemented? Presumably, it would have offset the camera from the ``Aim`` GameObject by a chosen distance. – perhaps as a workaround to avoid needing to rebundle the asset.

Just looking for clarification as to whether this is bugged, removed, etc.

**Comment by SDGNelson** [comment]
Thanks for pointing this out! You're probably right about it being for camera offset, but in that case I'm not sure why it was a float rather than a Vector3. Since it's unused I will remove it for the next update.

**Comment by iBowie** [comment]
Same goes for NPCs. They have "Head_Offset" property, which is a float instead of a Vector3.

**Comment by surv0013** [comment]
> Thanks for pointing this out! You're probably right about it being for camera offset, but in that case I'm not sure why it was a float rather than a Vector3. Since it's unused I will remove it for the next update.

I think it's a good opportunity to remember this [suggestion here](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions/3946), which will greatly simplify vehicle modding by not using a `RenderTexture` and a `Camera` to shift the camera view.
