### ISSUE TITLE
ZombieTables with isMega enabled completely ignore ZombieDifficultyAsset

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4055]
ZombieTables with isMega set to true completely ignore its ZombieDifficultyAsset as shown [Here](https://github.com/Unturned-Datamining/Unturned-Datamining/blob/b05516d0b7da1a7f3ad21556c48a4137c5f7c777/Assembly-CSharp/SDG.Unturned/ZombieManager.cs#L865-L874).

I believe it is understandable that someone would make the mistake of turning on Mega if they were to be, for example, creating a Boss ZombieDifficultyAsset ( Like Me :( ). So, either keep it as it is by adding a UI Warning when isMega is enabled and there is a present ZombieDifficultyAsset or simply ignore isMega if a ZombieDifficultyAsset exists.

**Comment by SDGNelson** [comment]
Sorry about that, it's a reasonable complaint, but I'm hesitant to mess with those unless going back to rework zombie spawns because it will probably break something else.
