### ISSUE TITLE
Issues with over scaling objects

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4056]
## Issue: 
1. Over scaling an object or volume causes precision errors.
2. A world that has a kill volume bugged in this way, instantly kills players that join the map in Singleplayer - even if the volume isn't covering the area they logged in. (It doesn't seem to have an effect on Multiplayer).

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/f360d6ec-e4c4-4d55-8aa8-c5e0196f8067

## Cause:
This video is obviously a recreation, but this can occasionally happened unintentionally if you have multiple monitors > borderless fullscreen mode, and click off screen while resizing. It can also be a lot less obvious, with the object going fully invisible and not jittering at all.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/d8ab4d4e-0b9c-499f-9a81-0c9848ebbaf8

## Solution:
It's not an issue that's unique to Unturned - it's the same in Unity and Unreal. But it might be preventable in the editor by adding a restriction to maximum scale? Preventing accidental over scaling.
I don't think anyone would have an issue with a maximum scale being say 10,000x, but you could safely go up to even 500,000x - it doesn't seem to be an issue in Unity until around 1million x scale.

## Real world scenario:
I know this issue is pretty edge-case, and not necessarily a bug that need fixing so feel free to close the issue if you want to.
But it did cause me a couple days of troubleshooting, so I thought it was worth documenting in case anyone else has related issues in the future.

The volume I was having issues with myself is in the video below. It was not only scaled up, but had also move miles from 0,0,0 leading to some weird behaviour with the box select.
It wasn't jittering, I wasn't aware that I had scaled it up at all, and at a glance the wiremesh appeared to be right shape/size in the right position. It wasn't obvious that it was there until I went looking for it, after many players reporting they were dying when loading up the map in singleplayer.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/5d7d7d6d-e9a8-46dc-afc0-6f9f115bd1e1

side note
- saving the map after pressing F on this volume would have required manually deleting the camera.dat, as there's no way to reset the camera in-game.

**Comment by SDGNelson** [comment]
Good points thanks, for the next update I'll clamp the scale and pressing F without a selection will return near origin.
