### ISSUE TITLE
onDamageVehicleRequested

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#406]
i have this event:
`void OnDamVehicle(CSteamID instigatorSteamID, InteractableVehicle vehicle, ref ushort pendingTotalDamage, ref bool canRepair, ref bool shouldAllow, EDamageOrigin damageOrigin)`

from this:

`public delegate void DamageVehicleRequestHandler(CSteamID instigatorSteamID, InteractableVehicle vehicle, ref ushort pendingTotalDamage, ref bool canRepair, ref bool shouldAllow, EDamageOrigin damageOrigin);
`

but the code is wrong:

```
if (VehicleManager.onDamageVehicleRequested != null)
        VehicleManager.onDamageVehicleRequested(instigatorSteamID, vehicle, ref pendingTotalDamage, ref canRepair1, ref canRepair, damageOrigin);
        if (!canRepair1 || pendingTotalDamage < (ushort) 1)
                return;
vehicle.askDamage(pendingTotalDamage, canRepair);
```

this should be:

```
if (VehicleManager.onDamageVehicleRequested != null)
        VehicleManager.onDamageVehicleRequested(instigatorSteamID, vehicle, ref pendingTotalDamage, ref canRepair, ref shouldAllow, damageOrigin);
        if (!shouldAllow || pendingTotalDamage < (ushort) 1)
                return;
vehicle.askDamage(pendingTotalDamage, canRepair);
```

**Comment by SDGNelson** [comment]
Not sure why it's showing as canRepair1 for you, but you're right that canRepair and shouldAllow were getting passed in the wrong order to that event. Thanks for the report! Fixed in the next update.
