### ISSUE TITLE
game lock

### ISSUE THREAD

**Issue by medvet331** [SmartlyDressedGames/Unturned-3.x-Community#4062]
Hello. I was given a game lock in the game unturned for nothing. I understand that a lot of time has passed since the lock, but I still wanted to remove it. I could have provided proof, but this information was lost, unfortunately. I can only tell you how it happened, I've been playing on the X100 server for 4 months, everyone already knew me there. and suddenly they wrote to me that you can't play on online servers, I was shocked and the friends with whom I played and sat in the discord were also shocked. so could you please take it off me. here is my steam account https://steamcommunity.com/profiles/76561198844570933/

**Comment by SDGNelson** [comment]
Sorry but this is not the right place for this. For more information: https://support.smartlydressedgames.com/hc/en-us/articles/12082986788884
