### ISSUE TITLE
Max_Group_Member not working

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#4065]
Here is my gameplay config:
```json
      "Allow_Static_Groups": true,
      "Allow_Dynamic_Groups": true,
      "Allow_Shoulder_Camera": true,
      "Can_Suicide": true,
      "Timer_Exit": 10,
      "Timer_Respawn": 10,
      "Timer_Home": 30,
      "Timer_Leave_Group": 30,
      "Max_Group_Members": 5
```
A group of 7 members appeared, this group may be a static group, is this a BUG or I misconfigured the config.json?

![2692bd636b17ff3a96ca783d49be94ca](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12797737/409e74da-cddb-4cc9-89dd-71baa5715a90)

**Comment by Jdance-Media** [comment]
Perhaps the group joined as a lobby. Perhaps mess with:
```
      "Allow_Static_Groups": true,
      "Allow_Dynamic_Groups": true,
      "Allow_Lobby_Groups": true,
```
