### ISSUE TITLE
Entering Main Menu Disregards FPS Cap/Vsync

### ISSUE THREAD

**Issue by Romelete** [SmartlyDressedGames/Unturned-3.x-Community#4066]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/33403276/46251551-37a7-49f3-86da-1353d0b63ea0)

Occasionally entering into the main menu from the editor (haven't tested singleplayer) will cause the main menu to not follow the set fps limit.  In this image my frame cap is set at 100hz (vsync is also on for my 100hz monitor) but clearly the game is quite eager to take use of my graphics card causing crazy coil whine.  Switching the fps cap on and off fixes the problem.

**Comment by SDGNelson** [comment]
Sorry about this. I remember investigating something similar a while back without any luck. Looking at the code I can't imagine why it is happening. Could you attach your Client.log file after it happens again please?

**Comment by Romelete** [comment]
will send through email on account of private error messages

**Comment by SDGNelson** [comment]
Thanks for the log file. It doesn't *look* like anything weird is happening. It applies graphics settings the one time, i.e., it's not applying multiple times or being reset by the UI or something. I'll add some logging specifically for the frame rate limit, and between that and the engine update to 2021 LTS (next preview version) maybe hopefully there will be some progress? 🤞
