### ISSUE TITLE
10-20 people disconnecting at a time (Battleye timeout)

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4068]
Similar to #3646. I can upload logs if needed, but seemingly random groups of people keep getting disconnected from my server and temporarily banned for a Battleye timeout. It doesn't affect the entire server, only large groups at a time.

**Comment by asineth0** [comment]
I'll post some snippets here, and I'll send you the full log file via email (I mainly don't want to accidentally leak IPs/etc).

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72173894/8228761f-1c9f-4333-842d-3526b462f81d)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72173894/6ff2f26a-917d-44dc-86a5-a844705ad3b1)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72173894/1d8fe043-fcd0-40dd-a312-74bd48065e41)

**Comment by SDGNelson** [comment]
Thanks for the log. Sorry to say I don't have much to add here. There don't seem to be any hitches or significant errors nearby, so it's likely that BattlEye temporarily lost connection to those players. For example, maybe they were applying an update to one of their master servers in a particular region.

**Comment by asineth0** [comment]
Do you know what ports/etc that Battleye uses to connect to the master server? This is happening constantly and makes the server borderline unplayable sometimes. Like I said, it seems to affect groups of players and not always the entire server.

**Comment by mycpphurts** [comment]
The battleye query timeout also causes the kicked user to get banned for 1 minute after being kicked, an example from such is shown below:

![image2132131](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57727007/6b61e7f4-5d7b-4d10-b88a-617c9ea03d0b)

**Comment by SDGNelson** [comment]
My guess is that the players themselves are losing connection to BattlEye, and then BattlEye tells your server to kick them. If a player can share their log there might be confirmation or denial of this in there.

There is this line in the BattlEye config file suggesting the port, but I don't know for sure.
`MasterPort 27035`

**Comment by mycpphurts** [comment]
I could try sharing mine, just need to hop on Asineth's server and get kicked out because of battleye. I'll send a log here when I have one
