### ISSUE TITLE
OnTellVirus_Global possible bug

### ISSUE THREAD

**Issue by DevInc0** [SmartlyDressedGames/Unturned-3.x-Community#4069]
While I was developing custom HUD plugin I bumped into a bug, which causes a strange behavior of `PlayerLife.OnTellVirus_Global`

https://www.youtube.com/watch?v=mA7-fzYeIss

Somehow, the event is being called only with `48` (probably because server config Virus_Infect parameter) and `100` (because /heal is implemented trough askDisinfect(100)) values and rarely with `18`.

Possible solution of bug is to replace `askRadiate(1)` to `askInfect(1)` in `PlayerLife.simulate(uint)`

```cs
// at PlayerLife.simulate(uint simulation)

else if (this.virus > 0)
{
    if (simulation - this.lastRadiate > 1U)
    {
        lastRadiate = simulation;
        askRadiate(1); // replace with askInfect(1);
    }
}
```

```cs
public void askRadiate(byte amount)
{
	if (amount == 0 || this.isDead)
	{
		return;
	}
	if (this.IsAlive)
	{
		if (amount >= this.virus)
		{
			this._virus = 0;
		}
		else
		{
			this._virus -= amount;
		}
		
		// Only instance event is being called
		
		VirusUpdated virusUpdated = this.onVirusUpdated;
		if (virusUpdated == null)
		{
			return;
		}
		virusUpdated(this.virus);
	}
}
```

```cs
public void askInfect(byte amount)
{
	if (amount == 0 || this.isDead)
	{
		return;
	}
	if (this.IsAlive)
	{
		if (amount >= this.virus)
		{
			this._virus = 0;
		}
		else
		{
			this._virus -= amount;
		}

		// Both static and instance events are being called due to SendVirus.Invoke()
		
		PlayerLife.SendVirus.Invoke(base.GetNetId(), ENetReliability.Reliable, base.channel.GetOwnerTransportConnection(), this.virus);
		Action<PlayerLife> onTellVirus_Global = PlayerLife.OnTellVirus_Global;
		if (onTellVirus_Global == null)
		{
			return;
		}
		onTellVirus_Global(this);
	}
}
```

**Comment by SDGNelson** [comment]
I just checked and it looks like this is the intended behavior. That event was added for backwards compatibility when plugins were patching the RPC code to listen for certain methods. In this case, tellVirus, now called SendVirus/ReceiveVirus. For a custom HUD I would recommend polling the life stats anyway so that multiple stat changes in a short period don't result in sending multiple redundant UI update RPCs.
