### ISSUE TITLE
Option to send cursor to player from server side 

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#407]
So my question basically is: 
Can you add an option to send showCursor from server side to player? 
RN if you wanna click a button you need to open chat and most of the players don't know that. 
Thanks!

**Comment by aviadmini** [comment]
*facepalm*

**Comment by SDGNelson** [comment]
This should currently be possible with Player.serversideSetPluginModal, but let me know if there are issues with it.

I'm actually really curious about what sort of menus you guys create using these new features! :)
