### ISSUE TITLE
Matamorez magazine doesn't have the same rarity as Matamorez gun

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4070]
Matamorez = Legendary
Matamorez Box = Legendary
Matamorez Magazine = Epic

**Comment by SDGNelson** [comment]
Thanks for the report. I think I checked into this as part of the Scalar magazine rarity fix, but decided to keep the Matamorez magazine labeling as is because it's less rare than the box.
