### ISSUE TITLE
Visible items on Rifle Racks having disparities

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4072]
If a weapon is placed on a Rifle Rack, Plaques, Sentries and similar, they're show correctly. When another item like knifes, foods and more are placed on Plaques and Sentries they're also ok, but on Rifle Racks they're show somehow incorrect/not the same rotation as weapons

![2023-08-16_16-11-52_NoUI](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/946153b7-cf8d-4781-be31-05e82b4569a4)
![2023-08-15_20-04-16_NoUI](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/88cb6dc6-8575-4533-bb27-7ef04ddc631f)

With any storage all weapons, items and more are being show at 0, 90, 180 and 270°, however only on Rifle Racks items are being rotated like at 45, 135, 225 and 315°, having this weirds results

![2023-08-16_16-13-11_NoUI](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/137c526e-a77c-4568-b258-37be78088a6c)

what about adding extra rotations for the visible items on storages, so instead of 4 different directions, there would be 8, so every item could be shown at 0°, 45°, 90°,135°, 180°, 225°, 270° and 315° on any storage? if not, then just fixing the Rifle Rack would be nice too!

**Comment by SDGNelson** [comment]
There are separate transforms for large guns, small guns, melee weapons, and other items. It looks like rifle racks have the melee weapon rotated by 45 degrees. There are a lot of weird item placements possible. It could maybe use enhancements someday, but low priority for the meantime, sorry.
