### ISSUE TITLE
Server freezing for 40-60s attempting to load Steam profile

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4079]
I keep having an issue where my server freezes up for 40-60 seconds, and the CPU drops to a very low percentage (5-10%) as it seemingly dose nothing but wait for an HTTP request to finish (loading a Steam profile). It logs this to console after the server unfreezes. 

Everyone gets disconnected from the server due to the freeze, so this is a pretty critical bug.

I'm not sure if this is caused by a plugin or Rocket itself, since I don't see a plugin in the stack trace. Any pointer in the right direction would be appreciated, as I don't mind attempting to debug this myself. 

```
Rocket.Core >> Error reading Steam Profile, Field: unknown -> Exception in .ctor: System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <39d8670c8f6e487fb992d3c14d754584>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x00072] in <39d8670c8f6e487fb992d3c14d754584>:0 
  at System.Net.WebClient.DownloadString (System.Uri address) [0x00020] in <39d8670c8f6e487fb992d3c14d754584>:0 
  at System.Net.WebClient.DownloadString (System.String address) [0x00016] in <39d8670c8f6e487fb992d3c14d754584>:0 
  at Rocket.Core.Steam.Profile.Reload () [0x0002f] in <59a13feb721848c8b0cd173f6d0e820b>:0 
  ```

**Comment by DanielWillett** [comment]
This is a problem with the SteamProfile (player.Profile) class. Because it's implemented synchronously, if steam lags or something it can cause lag like this. No plugins should be using this at all and I don't think there's a way for him to fix it, except maybe lowering the timeout to like a second or two.

**Comment by surv0013** [comment]
Move the task of obtaining a profile to an another thread.

P.S. There is a method for obtaining a profile in Rocket itself, but as far as I remember, it is not used anywhere, so it is most likely one of the plugins using it.

**Comment by SDGNelson** [comment]
Thanks @DanielWillett. It may be worth trying disabling a few plugins at a time until figuring out what's using that code, but this is outside of the vanilla game.
