### ISSUE TITLE
My game doenst show up in internet list

### ISSUE THREAD

**Issue by Teusck** [SmartlyDressedGames/Unturned-3.x-Community#4080]
I made everthing, open the ports, config the server, but for some reason, the server doenst look up in the server list, what i need to do? i see somewhere that i need to run the server for atleast 8 hours, it is true?
i need some help :D

**Comment by ItsRodrigoAl** [comment]
Mostly not a bug, did you set your GSLT?

**Comment by Teusck** [comment]
yes, i set the GSLT in commands, and in configs
the game not appears in lan, but appears in favorite, my friends can connect into it

**Comment by DanielWillett** [comment]
This is normal behavior I think, I've never been able to see local servers in the internet list. As long as other people can see it, it shouldn't be a problem.

**Comment by Teusck** [comment]
and how i can make the server be in the internet list? how i make an WAN server?

**Comment by GazziFX** [comment]
Can you write IP of the server

**Comment by Teusck** [comment]
Of course size-religions.gl.at.ply.gg:32927

**Comment by GazziFX** [comment]
I can ping IP, but cannot connect to the server. It seems you haven't forwarded ports, DDNS won't help in this case

**Comment by GazziFX** [comment]
If you want to play only with friends this shouldn't be a problem, for public servers I recommend using dedicated servers

**Comment by Teusck** [comment]
the server was closed, i need to shutdown the pc, the strange think is, i fowarded ports, in my firewall and my router, but for some reason i cannot see the server in the list, i fowarded the port of the playit, the general port of the documentation, with is 27015 to 27019. i can show u
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/62607661/b9f86ef2-ee86-468f-8d8c-12ba680242a9)

**Comment by Teusck** [comment]
I will do the forwarded port again, and i come with results

**Comment by GazziFX** [comment]
Tunneling might not work as expected if it expose only specific ports, because Steam will probably add your public IP to server list and not IP of tunnel

**Comment by Teusck** [comment]
Im trying now without the tunneling, maybe it works

**Comment by Teusck** [comment]
Ok, so, i remove the tunneling, open the port with 27015-27016, put the GSLT in the commands and in config (a new one) put the port  27015 in commands, everthing seeing fine, but for some reason just shows on in LAN tab, my firewall is enable in the port, i tried without the firewall port foward, but its seems nothing change, and now im without hope LOL, maybe i need to pay for an IPV4

**Comment by JadenSWang** [comment]
I'm actually having the same issue but the server shows up a few seconds after coming online and then disappears

**Comment by SDGNelson** [comment]
Thanks to everyone who helped out here. If connecting is working, there isn't much we can suggest, sorry. As mentioned in [this article](https://support.smartlydressedgames.com/hc/en-us/articles/16050989363732) the Steam master server is a "black box" so the exact implementation is a mystery, but it may depend on whether the server has been online for a certain amount of time and/or has active players. In particular when there are a large number of active servers with players on them it seems empty servers might not be returned unless specifically filtering for empty servers.
