### ISSUE TITLE
Seeds able to plant on a forage box collider

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#4081]
For some reason, I can plant seeds on top of the gameobject 'Forage' ingame. Here's a test on vanilla map on washington:

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81763752/dbfd1a66-3bb0-443e-a947-772ca0f9bc97

As soon as I harvest the bush, I'm not able to place any more seeds. The box collider inside of Unity is in fact 'is Trigger', but I don't understand why would someone be able to place seeds there.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81763752/34fb5fd1-a9ed-4319-825b-ff4c2df65409)

**Comment by iBowie** [comment]
My best guess is that it's because of a physics material.

**Comment by LocoCZ** [comment]
Bowie is correct. I have now removed the physics material from the berry bush, bundled it, made my own asset file for it and I cannot put seeds on top of it anymore.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81763752/4c12437a-675e-48fc-8d6d-9059974940a3)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81763752/72c1a2c9-c8fa-4b94-b844-93675f71d1d4)

**Comment by SDGNelson** [comment]
Funny point, thanks. Maybe I should add a separate physics material for those.
