### ISSUE TITLE
Server periodically shows up on the server list. 

### ISSUE THREAD

**Issue by JadenSWang** [SmartlyDressedGames/Unturned-3.x-Community#4082]
I have an extremely strange issue. My unturned server is able to be connected to via ip and port, shows up in favorites and history, and shows up in the "internet" list briefly after launching the server (10 seconds ish) and then disappears. Any ideas here?

**Comment by SDGNelson** [comment]
If connecting is working, there isn't much we can suggest, sorry. As mentioned in [this article](https://support.smartlydressedgames.com/hc/en-us/articles/16050989363732) the Steam master server is a "black box" so the exact implementation is a mystery, but it may depend on whether the server has been online for a certain amount of time and/or has active players. In particular when there are a large number of active servers with players on them it seems empty servers might not be returned unless specifically filtering for empty servers.
