### ISSUE TITLE
i play unturned and cs go my server(unturned) open i join cs go its kick from the server Kicking for inactivity: PlayerID: 76561199539458289 Name: arrow1475 Character

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4084]
help?

**Comment by DanielWillett** [comment]
Not sure if i even understand this correctly but I don't think you can be in two steam servers at once.

**Comment by arrow12312** [comment]
no bro its not this i play cs go and unturned

**Comment by arrow12312** [comment]
i join cs go its kick mybe bug

**Comment by DanielWillett** [comment]
CSGO and Unturned both use steam servers, you can't join two at the same time. It's not really a bug, nor something he can fix.

**Comment by arrow12312** [comment]
I used to do it like this in 2014 I had a server until 2017

**Comment by SDGNelson** [comment]
Thanks @DanielWillett, yes this is not supported.
