### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Barinnf** [SmartlyDressedGames/Unturned-3.x-Community#4086]
People log into the server, play with no problems, but some people can't log into the server. They log in, however they hang in the queue and see the loading screen. However, they are on the server. They are not the problem as 50% have this error. 
Here is the error itself
[Rocket.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12455750/Rocket.log)

**Comment by GazziFX** [comment]
It seems the glasses has corrupted state, and can't be toggled, and other errors is uninitialized player maybe due previous exception

**Comment by Barinnf** [comment]
> It seems the glasses has corrupted state, and can't be toggled, and other errors is uninitialized player maybe due previous exception

And how do I fix it so everyone can log in?

**Comment by GazziFX** [comment]
It may be caused by mods, you need to test them. If its not a cause, you can try wipe your server, if won't help try to remove all plugins and add them back by one

**Comment by DanielWillett** [comment]
I've had this issue in the past after making a mistake with my kits plugin, had to add in a patch for it. It would be good to get a length check in that method (`PlayerEquipment.updateVision`). Easy mistake to make since I think it's the only clothing with any metadata.

Gazzi is correct that it's an issue with saves, a temporary solution would be to get someone to make you a prefix patch for `PlayerEquipment.InitializePlayer` with something like this:
```cs
    [HarmonyPatch(typeof(PlayerEquipment), nameof(InitializePlayer)]
    [HarmonyPrefix]
    private static void GlassesStateFix(PlayerEquipment __instance)
    {
        ItemGlassesAsset? glasses = __instance.player.clothing.glassesAsset;
        if (glasses != null && glasses.vision != ELightingVision.NONE &&
            (__instance.player.clothing.glassesState == null || __instance.player.clothing.glassesState.Length < 1))
        {
            __instance.player.clothing.glassesState = new byte[1];
            __instance.ReceiveToggleVision();
        }
    }
```

Or less ideal, delete the Clothing.dat saves of all the players that can't join, which will wipe their clothing and probably mess up their inventory since the page sizes will change.

**Comment by Barinnf** [comment]
So you have to constantly purge people's clothing inventory to get them in, and the problem is the clothing?


> I've had this issue in the past after making a mistake with my kits plugin, had to add in a patch for it. It would be good to get a length check in that method (`PlayerEquipment.updateVision`). Easy mistake to make since I think it's the only clothing with any metadata.
> 
> Gazzi is correct that it's an issue with saves, a temporary solution would be to get someone to make you a prefix patch for `PlayerEquipment.InitializePlayer` with something like this:
> 
> ```cs
>     [HarmonyPatch(typeof(PlayerEquipment), "InitializePlayer")]
>     [HarmonyPrefix]
>     private static void GlassesStateFix(PlayerEquipment __instance)
>     {
>         ItemGlassesAsset? glasses = __instance.player.clothing.glassesAsset;
>         if (glasses != null && glasses.vision != ELightingVision.NONE &&
>             (__instance.player.clothing.glassesState == null || __instance.player.clothing.glassesState.Length < 1))
>         {
>             __instance.player.clothing.glassesState = new byte[1];
>             __instance.ReceiveToggleVision();
>         }
>     }
> ```
> 
> Or less ideal, delete the Clothing.dat saves of all the players that can't join, which will wipe their clothing and probably mess up their inventory since the page sizes will change.

**Comment by Barinnf** [comment]
So you have to constantly purge people's clothing inventory to get them in, and the problem is the clothing?
For me it is very difficult to understand honestly what you write about, because I do not understand in such peculiarities of errors at all, and I do not know what to do either.

**Comment by DanielWillett** [comment]
Any plugins that mess with the inventory could cause the issue you have, most likely a kits plugin.

**Comment by SDGNelson** [comment]
Thanks DanielWillett and GazziFX.

Another possible cause on the vanilla side is if the item type in a mod changed. For example, if a regular pair of glasses received the nightvision function.

For the next update I'll add that length check to updateVision.

The item state/metadata is definitely one of the top priorities for an inventory rewrite. My plan would be to revamp both how vanilla item dynamic properties are stored, and to allow plugins to persist custom item properties.

**Comment by DanielWillett** [comment]
> allow plugins to persist custom item properties.

that would be very nice.

**Comment by Barinnf** [comment]
I removed the plugin for whales, restarted the server, people still can’t log in, they stand in an endless queue.

**Comment by Barinnf** [comment]
but why did the error remain even after I removed the plugin?

**Comment by GazziFX** [comment]
Because it doesn't produce it and you not wiped clothes
