### ISSUE TITLE
Why can we put claim flag on vehicles

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#409]
https://cdn.discordapp.com/attachments/379200952147771393/489855357502619669/unknown.png
https://cdn.discordapp.com/attachments/379200952147771393/489856142235926558/unknown.png
On both pictures you can see 2-2 claim flags placed by different people whos not in Group

So what i realized, claim flags have no effect on vehicles, but still shows area while placing it.
So it's literally useless in my opinion to let players able to place claim flags on it.

Basicly i wanted to suggest to avoid glitches cuz thought it has effect, but now i just report it as an useless thing which should be blocked just like beds to place on vehicle.

SHORT: I'm suggesting to block claim flags to be able to place on vehicles by players. (So not let them place it there since it has no effect plus it's pointless to place then.)

**Comment by SDGNelson** [comment]
Looking through the code I found this comment from back when claim flags were added lol "// No vehicle claims (yet?) depends if that's balanced", for the next update claim flags on vehicles will prevent others from building on that vehicle.

**Comment by lvlbgn** [comment]
Uhh, you just said,  you Will turn on CLaim Flag's effect on vehicles?
This is a really bad decision in my opinion. My report was about to turning off players able to placing claim flags on vehicles. So what i wanted to say to DO NOT let claim flags be placed on vehicles since they have no effect.
But if you turn it back on, did u realize, they Will be able to move under houses to troll / claim them? In my opinion it Will be hardly glitchy and buggy!
