### ISSUE TITLE
Unable to determine UGC type for downloaded item: 3026913260

### ISSUE THREAD

**Issue by bjorn29922** [SmartlyDressedGames/Unturned-3.x-Community#4090]
Anyone knows how to fix this 
Unable to determine UGC type for downloaded item: 3026913260

**Comment by bjorn29922** [comment]
Yes

**Comment by DanielWillett** [comment]
It's defined by that .meta file in the base directory. If you don't have that try reuploading.
If for some reason that doesn't work just make it yourself.

Should either be `Map.meta`, `Object.meta`, `Vehicle.meta`, `Item.meta`, or `Localization.meta`.
File contents don't matter afaik.
