### ISSUE TITLE
Vehicles and Players Collision bug. 

### ISSUE THREAD

**Issue by DepxGarage** [SmartlyDressedGames/Unturned-3.x-Community#4093]
I will post 2 ytb videos of the problem i have, but shortly:

1. Players cant climb ladders. If they press F to climb, nothing happens. If they try to climb by themself, they will get glitched and drop on the ground.
2. Admins can /tp (player) that are inside cars, feature withch its impossible on unturned.
3. Can`t delete vehicles with commands. Simply it doesnt detect the cars (example destroy tool from ShimmysAdmin tools plugin
4. PlayerRob -> command /rob  doesnt detect players.

My server was working fine 2 days ago. Didnt install something new.

https://www.youtube.com/watch?v=xmuAAWTAYFw
https://youtu.be/mbsfQvUyIHw

**Comment by DepxGarage** [comment]
Some people told me that the problem its: Level.dat its corrupt

**Comment by SDGNelson** [comment]
It looks like this was submitted both here and as a support ticket with more details, so I will respond to the support ticket.

**Comment by DepxGarage** [comment]
@SDGNelson i didnt open one

**Comment by SDGNelson** [comment]
Oh, that's weird, they linked to the same videos as your post. If you turn off your plugins do these issues still happen?

**Comment by educatalan02** [comment]
Its fixed by deleting Vehicles.dat

**Comment by SDGNelson** [comment]
@educatalan02 were you running into the same issue recently?

**Comment by educatalan02** [comment]
Not recently, but yes like 1 year ago. Somehow the vehicles.dat gets corrupted and no collision works & raycast doesnt too.

**Comment by SDGNelson** [comment]
If that is the case with Vehicles.dat, could you upload the file please @DepxGarage? I'll see if I can reproduce it on a test server.

**Comment by DepxGarage** [comment]
Hi @SDGNelson , solved the problem with the help of educatalan. I deleted the level folders one by one, and found that vehicle.dat was the problem. Too bad i no longer have the corrupt file so i cant provide it

All my respect and thanks for responding to my ticket.
