### ISSUE TITLE
Does -maxmem do anything?

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4095]
My server has 40GB of RAM and I've seen people mention that you can pass the `-maxmem` argument to Unturned. Does that do anything? Would I see a performance benefit over the default RAM allocation?

**Comment by SDGNelson** [comment]
No, I don't believe so. The game will use as much RAM as it needs. i.e., the amount in use by the server is the amount it needs.
