### ISSUE TITLE
Alive/dead system break the game

### ISSUE THREAD

**Issue by TheReal-Kaze** [SmartlyDressedGames/Unturned-3.x-Community#4096]
Hi there, i’ve been working on a system with the alive/dead system and the bug is the following:
When i use 9 sections (from 0 to 8) and put the object in a map, the map simply do not load and stay in the loading indefinitely, (8 sections works well (0->7) ,

i mean first of all if its not supported i guess that it should be just ignored and load the map and secondly i wanna ask for more sections if it is possible because that system is the more complete thing i could ever saw for lot of systems in unturned if you could fix the limit to 15 or 20 or even more it could be very very cool.

Thanks ^^

**Comment by GazziFX** [comment]
Can't found any limits except byte range 255

**Comment by SDGNelson** [comment]
Sorry but the limit is 8 currently, and no current plans to revise destructible objects.

**Comment by TheReal-Kaze** [comment]
> Sorry but the limit is 8 currently, and no current plans to revise destructible objects.

Lot of things can appear in unturned with that, its more easy than making 25 npc mod hooks and you can have multiples objects with the same system in the map since its not an event like with interactability_Reward + npc mod hook, please really think about it because lot of cool stuff can happen in Unturned.
Thank you Nelson ^^
