### ISSUE TITLE
Unturned cant join

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4097]
I bought a server built by unturned, I can see it but can't log in. Does anyone have any help?

**Comment by arrow12312** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/28991078/9c5a0fb7-4489-4fb9-bedd-95c019a52f2c)

**Comment by arrow12312** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/28991078/7da16e8a-3da2-4d4b-ab70-716363965156)

**Comment by SDGNelson** [comment]
I'm certainly very late replying, sorry! Did you end up getting it working with GazziFX's suggestion?

**Comment by SDGNelson** [comment]
Closing, but if you follow-up I will re-open.
