### ISSUE TITLE
Crafting stats not working

### ISSUE THREAD

**Issue by Astrepio** [SmartlyDressedGames/Unturned-3.x-Community#4099]
My crafting stats stopped at 100.000 crafts. After that I did like 1000+ crafts and this number didnt change. What to do to fix it?
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/144468384/5dd963bc-b5b7-4528-bcde-14e4933444c3)

**Comment by SDGNelson** [comment]
Currently 100,000 is the per-player maximum. Were you intentionally crafting lots of items to try and increase it? (when you mention 1k+ afterwards)

**Comment by ItsRodrigoAl** [comment]
> Currently 100,000 is the per-player maximum. Were you intentionally crafting lots of items to try and increase it? (when you mention 1k+ afterwards)

What Astrepio tried to say is that, after 100.000 crafted items that number was not increasing anymore, after those 100.000 he crafted about +1.000 items but they didn't count, but you just said it is limited. The other stats like kills and more are always updated but this one is limited, why?

**Comment by Astrepio** [comment]
Yea, why this one is limited? Can you make this stats not limited :)? I just want to see my whole history of crafting in one number

**Comment by SDGNelson** [comment]
All of the stats have upper limits. From time to time the upper limits have been raised when hit by longtime players IF they weren't just trying to raise the stat as much as possible. Have you hit this limit as well @ItsRodrigoAl?

**Comment by ItsRodrigoAl** [comment]
> All of the stats have upper limits. From time to time the upper limits have been raised when hit by longtime players IF they weren't just trying to raise the stat as much as possible. Have you hit this limit as well @ItsRodrigoAl?

Yup, actually like 1-2 years ago :( I don't even imagine how much crafted items would I had if this limit were higher since then

**Comment by SDGNelson** [comment]
Okay: I've now raised the limit!
