### ISSUE TITLE
Unturned Debug? A very bad bug

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#410]
https://www.youtube.com/watch?v=4hWiJSNxGk4&feature=youtu.be
This video shows what i mean, but lemme give a description aswell:

Since Germany map is in Unturned, we found a very annoying bug which is probably meant to be a "debug".
The thing is, we kept reports from players, they log off in their base and they get teleported to some other location, so on the video we finally tested it and get the proof for their words.

Description:
If you log off on a "free" space, you Will stay on the position where you logged off.
BUT, if you log off crouching or laying under a plate, or something that blocks you to spawn, you Will be teleported out to somewhere, probably just simply get respawned cuz they spawn while standing so they could get into the plate.

It is very annoying for players because you know most of them log on while hiding under plates, standing on lockers or so.
Then they just respawn on somewhere and can get killed with their full loot cuz u prob know they log off with their loot to don't lose it while sleeping.

(I assume it supposed to be a debug, but instead it just annoys every single player who can't get the idea to log off in some "free room"

(PS.: Do not worry, this is my last bug report for now :D )

--- Seems the video cant be Accessed, re-recording it.
----- Video fixed.

**Comment by FCheat** [comment]
Obvious reasons, could save if the user is crouched/laying down when they sign off & use that base to rework the whole trace system. Wasn't it like 0.75 crouched and 1.45 standing? Something like that.

**Comment by SDGNelson** [comment]
This should be fixed for the next update. Previously the stance was saved when logging out, but that was broken at some point.
