### ISSUE TITLE
Animals still Alert Damaged from Point even if the damage was cancelled

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4100]
Animals still run away/investigate their damage origin even if the damage was cancelled. Simply because `Animal.alertDamagedFromPoint()` is not apart of `DamageTool.damageAnimal()` and will therefore always execute regardless of if damageAnimal returned early. This is true for all instances of `Animal.alertDamagedFromPoint()` being used. Such as in [UseableGun](https://github.com/Unturned-Datamining/Unturned-Datamining/blob/linux-client-preview/Assembly-CSharp/SDG.Unturned/UseableGun.cs#L1168-L1169).

**Comment by Gamingtoday093** [comment]
Oh it seems to be the same case for Zombies? Is this intentional?

**Comment by SDGNelson** [comment]
The events were added much later than the AI notification, so this was an oversight. It might make sense to move into the damage animal code with an option in DamageAnimalParameters.
