### ISSUE TITLE
Kicking player <steamid> for unknown session response 10

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4101]
After the latest updates I started being kicked from my local server, I have disabled VAC + BE on the server, and disabled BE on my launched Unturned.

Sometimes if I restart my server twice the problem disappears

**Comment by SDGNelson** [comment]
It looks like this new response was added a couple months ago:

`k_EAuthSessionResponseAuthTicketNetworkIdentityFailure = 10,	// The network identity in the ticket does not match the server authenticating the ticket`

Are you using a modded client?

**Comment by sunnamed434** [comment]
No, I don't have a modded client, a fresh new installed Unturned on days

**Comment by GazziFX** [comment]
Its possible that its Steam relatee error not Unturned

**Comment by SDGNelson** [comment]
Odd coincidence that the first/only person to run into this so far is a cheat developer. :eyes:

I'll add a message for this the next time we update Steamworks.

**Comment by DiFFoZ** [comment]
Actually, I'm and @negrifelipe also getting this error.
> negrifelipe: Has any of you experienced issues with the server while developing? For some reason every time  i shutdown the server (localhost) and open it again i am not able to join again if i dont restart the game. I get unknown session response 10 error

The workaround that helped me is to use `Connect` or just refresh the servers list by clicking `LAN` button.

**Comment by negrifelipe** [comment]
> Actually, I'm and @negrifelipe also getting this error.
> > negrifelipe: Has any of you experienced issues with the server while developing? For some reason every time  i shutdown the server (localhost) and open it again i am not able to join again if i dont restart the game. I get unknown session response 10 error
> 
> The workaround that helped me is to use `Connect` or just refresh the servers list by clicking `LAN` button.

Works fine for me now

**Comment by GazziFX** [comment]
Got same error when accidentally removed token, probably players trying to connect to server with previous server identity

**Comment by SDGNelson** [comment]
Thanks for the additional reports. In that case, I will make sure the message is added for the next update. If you the server was rebooted between refreshing the server list and joining that would make sense because the client would be joining the old steam ID.
