### ISSUE TITLE
Finding location of specific objects placements in map level

### ISSUE THREAD

**Issue by WagonRexy** [SmartlyDressedGames/Unturned-3.x-Community#4103]
Is there any way of finding a specific object that was placed on a map in the editor. I have the asset ID but I need the coordinates of any occurrences of this asset in the level. Could this be done through a dat file maybe to find coordinates? 

I have little experience with map editing or coding so help would be much appreciated.

**Comment by DanielWillett** [comment]
Loop through LevelObjects.objects

**Comment by SDGNelson** [comment]
Sorry to confirm that without a custom plugin there isn't a good way to do this currently.

**Comment by GazziFX** [comment]
Maybe something like devkit hierarchy window with search and double click will move you to the object like in Unity editor?
