### ISSUE TITLE
Conditions not updating on large objects.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4104]
```
GUID 53775e564f33489f8ff840255efa0df0
Type Large
ID 0

Conditions 1
Condition_0_Type ITEM
Condition_0_Logic EQUAL
Condition_0_ID 19227
Condition_0_Amount 1

Has_Clip_Prefab true

Asset_Bundle_Version 4
```

The condition itself like this works, but only when leaving and rejoining the game, however I want this to appear / disappear when a user is holding an item or has it in their inventory. But it does not update when these changes do happen.

**Comment by SDGNelson** [comment]
Sorry to say that item conditions aren't supported for object visibility because it would currently need to refresh every time your inventory changes.
