### ISSUE TITLE
Blueprint conditions and rewards do not apply on Repair and Ammo

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#4105]
Correct me if I'm wrong, but currently blueprint conditions and rewards work only in types other than ``AMMO`` and ``REPAIR``.

I don't think it's an intended behavior, since conditions are checked on all types. However, they do not apply (reset) in ``AMMO`` and ``REPAIR``.

**Comment by SDGNelson** [comment]
You're right that this looks like a bug. Thanks for the report!
