### ISSUE TITLE
LOD_Bias on Factory #1 object is too low

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4107]
This is a low-priority 'bug' obviously but object culling happens very close for the factory object (`Objects\Large\Buildings\Factory_0`), which is a lot more noticeable because of the large open doors all around it.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/6e34d037-b5df-45a0-aed7-514ecddb122c)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/f163ae8f-286d-4faf-93fe-b454cad76784)

\- thank you

**Comment by SDGNelson** [comment]
Sorry for my delay. I just now adjusted the Factory #1 culling volume distance, but even something like +50% is still rather obvious, unfortunately. FWIW I'll increase the factory and the hangar objects as well since they are all similarly open.
