### ISSUE TITLE
Add the ability to find out on the server side if a player has opened an inventory

### ISSUE THREAD

**Issue by 0x59R11** [SmartlyDressedGames/Unturned-3.x-Community#4108]
Hey, Nelson!

These are all the necessary requirements, nothing needs to be changed on the server side, we will do everything ourselves using some kind of harmony ;)
![2023-09-24_17-11](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/41921371/ee0122d3-169b-49cf-a1f8-66ecd608135f)

**Comment by SDGNelson** [comment]
Is it for UI extension?

**Comment by surv0013** [comment]
> Is it for UI extension?

I think yes. This will hide the HUD when opening the inventory.

**Comment by SDGNelson** [comment]
The official plan for this is to provide an API for the server to extend the UI through extension points. For example, attach UI to the main HUD and only visible when the HUD is visible. The next update will finally have UIElements fully or mostly integrated depending on some straggling inconsistencies I need to sort out.
