### ISSUE TITLE
"Problem" with the option "Collision_Important"

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#4109]
Objects have a "Collision_Important" parameter, which prevents the game from disabling collision, and everything would be fine, but the problem is that the renderers are disabled, which is why the object becomes invisible. Can I ask you to make parameter for renderers, for example “Visibility_Important”.

**Comment by SDGNelson** [comment]
What do you have in mind to use it for?

**Comment by surv0013** [comment]
> What do you have in mind to use it for?

I want to use an object as a landscape. This option will allow me to make a map in Blender.

**Comment by SDGNelson** [comment]
Sorry, but that isn't currently intended/supported.
