### ISSUE TITLE
cars can swim under water 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4110]
exemple on the buak map
https://youtu.be/8QF2r1YAZRc?si=QeKTpvj9zB20jCDW

**Comment by MoltonMontro** [comment]
I double-checked this, and this doesn't appear to be a bug. Vehicles decelerate when they enter water -- which is what happened in the video & in-game. If you stayed in the water longer, the car would've came to a full stop.

Normally they'd decelerate faster than that, but my assumption is that Buak's custom vehicle profile is what's causing it to take longer to fully stop.

**Comment by SDGNelson** [comment]
Thanks @MoltonMontro, yes, this is a side effect of the lack of drag in water. Not realistic but right now underwater only turns off the engine rather than also slowing down the drag.
