### ISSUE TITLE
"Unable to find spawn table for resolve with id [***]" Error on server console running custom map

### ISSUE THREAD

**Issue by Curly0-brackets0** [SmartlyDressedGames/Unturned-3.x-Community#4111]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/dd714cfe-6e6c-47c8-a4fe-dba74e8df418)
Do you have any idea what is causing this error? I'm guessing it has something to do with an obsolete or unfindable spawn table, but I can't find that ID anywhere in any workshop file the server is running. Is there any way I can search for legacy ID's like this in my folders without having to go through every .dat or .asset individually? 
Thanks in advance :)

**Comment by SDGNelson** [comment]
The next update actually has a big improvement in this regard! It will log what's trying to use that spawn table ID to make it easier to narrow down.

**Comment by SDGNelson** [comment]
There should be a much better error message after today's update. Let me know how it goes!
