### ISSUE TITLE
Navigation bounds count {0} does not match graph count {0} during server load

### ISSUE THREAD

**Issue by Curly0-brackets0** [SmartlyDressedGames/Unturned-3.x-Community#4112]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/cda9efaa-9623-412d-aa8c-398654929bfb)
This error is popping up on my server running a custom map, are you aware of a fix for this? what is the graph count and why is it not updating to match the amount of navigation zones on the map (which is what I assume "navigation bounds count" is?)
thanks in advance :)

**Comment by GazziFX** [comment]
Probably you deleted several of them in map folder

**Comment by SDGNelson** [comment]
Some of the navmeshes might not be baked. Even re-saving the map should try to fix it automatically.
