### ISSUE TITLE
Some type of items are still showing the hotkey text

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4118]
Items types like Ammo, Craft Supply, Optics and more are still showing the hotkey text when they should not

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/79b57f4a-773e-4a62-9ff2-00d89e168224)

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like the change in the update was for primary/secondary weapons, but I've now changed this to match the actual hotkey code.
