### ISSUE TITLE
Almost empty ammunitions doesn't show how many bullets remains + small inconsistency

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4119]
## 1
As you can see, this 1911 ammo have a quantity of 2/7 and it does show how many bullets are on it
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/483a146c-9654-4468-90d0-c9c18ec36968)

But then this Ace ammo have 1/6 and it doesn't show it on the item description. This happens with 1 and 0 of ammo
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/c2a04c24-e0bb-4c4d-9c3b-5dd95bac74e5)

## 2
Also I want to remark an small inconsistency on this. With the new preview branch you can see how much ammo the guns have currently/total
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/76197a65-794c-4115-b469-d52726cfefb3)

But with their ammo as an individual item it doesn't show the current/total, just the current one
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/1c2c3494-6921-4973-9fa8-893ff19dd028)

**Comment by SDGNelson** [comment]
These amount labels predate the update (i.e., in the current public version these amounts are shown), but it's a fair point that the capacity should be shown similar to the gun description.
