### ISSUE TITLE
FPS freezing on any server

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#412]
Did you ever heard about that "bug"?
After a while if a server is not wiped, like 1-2 weeks (if enough popular) even the admins are clearing maps, they Will be "laggy"
But it's about FPS, rendering a few kind of bases, which are not bigger than 8x8 either.
Mostly it happens on ALL the maps at military locations, i can get Records for you if you want.
But the short description of this
You move, your game freeze for 1-2 second, then unfreeze and you can continue moving
But these locations are staying there, you move back, freeze again.. etc etc

It's really annoying when we are talking about people die in pvp, clicking on respawn and they get disconnect after a huge freeze. It must has something to do with rendering bases, just tell if need to record. (The maps are being cleared from time to time, staff of each server is taking care to remove raided bases, etc.. so it can't be "full of trash")

Is there anything you can do about it?

**Comment by SDGNelson** [comment]
There is some stutter on really dense servers while instantiating the bases when moving between regions. It could be improved by queuing that across multiple frames, but there are a lot of side effects which would need addressing as well e.g. receiving updates to items which haven't been created yet. May happen, but after all the recent 3.x updates I've promised to get back to work on 4 so not soon.
