### ISSUE TITLE
Some medical items showing "low quality" warnings

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4120]
Some medical items like Vitamins and Suturekits are showing this warning about the low quality risk, but actually they don't even have quality levels. Some other items like Medkits or Purification tablets aren't showing it

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/30846c31-be7f-49f1-b570-c1c35951dfb2)

**Comment by GazziFX** [comment]
Isn't it inside your localization? I can't remember any quality warnings

**Comment by GazziFX** [comment]
![IMG_20231010_131357.jpg](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/43498426/f9004f10-4d84-42b0-b929-623002f583db)

**Comment by ItsRodrigoAl** [comment]
> Isn't it inside your localization? I can't remember any quality warnings

Def not related with location, how would I even add that? xD I just translated the new values

The low quality warning is showed when a consumable item is at 50% or lower of it's quality, however I found some medical items are showing this message too even if they don't have this quality level, no idea if it's something related with metadata stuff. Try going to a medic with the default game durability settings and check medkits, suturekits, tablets antibiotics and more

**Comment by SDGNelson** [comment]
Thanks for the report! I'll get this fixed for the next preview version.
