### ISSUE TITLE
Some suggestions + inconsistencies with the new stats values on items

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4122]
## Values as 'tips' and 'stats'
First of all, I will divide all the stats values in 2 types: stats and tips. We can identify the 'tips' as those values that only have a `Description text`, and 'stats' as those which have `Text: {value}`

Now we've identified them, I want to talk about how are they shown on the item descriptions. On some 'tips' their color may be gray, red or white, and this may be a little confusing since most of values have just a gray text and that's all. For example, the value `ItemDescription_Buildable_Lockable` applies a white color since is like a 'buff' and `ItemDescription_ConsumeableMoldy` uses a red color since its like a 'debuff'. With this said, personally I think both colors should be applied to all 'tips' and not only to these ones, since having a large gray text wall is not intuitive and fast readable at all, and here's an example of what I'm talking about

Both 'tips' and 'stats' are combined in just a plain large gray text wall and actually you couldn't identify them really fast:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/f88953e3-a50d-43e1-9e26-453f3dd93ddf)

However, applying a color to the 'tips' as if they were 'buffs' and 'debuffs' would help, looking like this:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/cd149d6c-8a70-4871-bfd3-3fe5bfbe4db2)

I made a list for all the 'tips' and which I consider are buffs and debuffs so they should show their color depending of what they do, and not only using gray color for all of them:

BUFFS (white):
ItemDescription_Buildable_Lockable Locked for players outside your group. (Already implemented)
ItemDescription_Clothing_FireProof Protects against fire.
ItemDescription_Clothing_RadiationProof Protects against radiation.
ItemDescription_ExplosiveBullet Explodes on impact.
ItemDescription_Throwable_Sticky Sticks to surface on impact.
ItemDescription_Throwable_ExplodeOnImpact Explodes on impact.
ItemDescription_Farmable_CanFertilize Growth can be expedited with fertilizer.
ItemDescription_Farmable_AffectedByRain Growth can be expedited by rainy weather.
ItemDescription_Buildable_ExplosionProof Cannot be damaged by explosions.
ItemDescription_WeaponBleeding_Heal Impact stops bleeding.
ItemDescription_WeaponBones_Heal Impact fixes bones.
ItemDescription_ConsumeableBleeding_Heal Stops bleeding.
ItemDescription_ConsumeableBones_Heal Fixes bones.

DEBUFFS (red):
ItemDescription_ConsumeableMoldy Low quality indicates spoiling/mold and will hurt immunity. (Already implemented)
ItemDescription_Throwable_Flash Blinds nearby players looking into the explosion.
ItemDescription_Trap_BreaksBones Trap breaks bones.
ItemDescription_Trap_DamagesTires Trap pierces tires.
ItemDescription_Farmable_RequiresSoil Must be planted in arable terrain.
ItemDescription_Farmable_AffectedByAgricultureSkill Yield is affected by your Agriculture skill level.
ItemDescription_Buildable_CannotPickup Cannot be picked up after placement.
ItemDescription_Buildable_CannotSalvage Cannot be salvaged when damaged.
ItemDescription_Buildable_CannotRepair Cannot be repaired when damaged.
ItemDescription_WeaponBleeding_Always Damage always causes bleeding.
ItemDescription_WeaponBones_Always Damage breaks bones.
ItemDescription_ConsumeableBleeding_Cut Causes bleeding.
ItemDescription_ConsumeableBones_Break Breaks bones.
ItemDescription_Consumeable_Explosive Explodes when consumed.

## Small space between them
Now I've mentioned all the first topic, I would like to suggest that those both tips and stats shouldn't be in the same text group. For example, when looking to a seed description, it shows the tips at top, then leaves an small space and then shows the stats, making it better readable:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/c20290f7-30f2-45c8-8fe6-62b671e1dee0)

However, this doesn't always happens with all items and it may put them togheter, like this:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/d65f7a3e-0134-4d2d-9666-623fdfb2d2cf)

Of course this is not a big problem with items with just few stats or tips, however with other ones like the Demolition Charge example above, I think it explains better what I'm talking about, and It's even worse if they don't even have a different color

## Adding the plus and minus to all the stats + some text inconsistencies 

As you can see with the Hell's Fury values, some of them shows the '+' and '-' symbols indicating they're positive or negative, also they're colored with white or red to identify them better if they're buffs or debuffs:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/16ff0a83-9478-4297-ae97-e48ed495e8c5)

However, this rule is not applied to all the stats, and there are items like the examples above like Morphine, having buffs and debuffs but without their symbols and just a colored number. This is in some way inconsistent because those items will still apply a one-time positive or negative effect on you, and is not like they will reduce your final stats

Another thing I noticed are the stats from the Skills page and more parts of the game, where it shows '+0%', having the '%' without the space that is showed on the new stat values like '+0 %'.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/c6d4460a-9985-4db5-8d2d-c4c5e2197bdd)

From what I saw on the official wiki, I guess this should be fixed for the percentage values deleting the space. Also I noticed that rpm was wrote 'rpm' instead of 'RPM', which may be consider a discrepancy between what is shown on the official wiki and what is shown on the game. Another values like '100 m' are fine between what are shown on the website and the game

## Making the item values be enabled/disabled by the user, and not by map
I have no idea if someone else think this should be good or no, but personally I think that what is shown or not on the items should be decided by the player and not by the map. I mean, there should be an option to disable or enable the values you want on the config, with just a check mark. With this way, modders shouldn't worry about what or which things to show on the items description values (I'm pretty sure almost nobody will care about the animal stats XD). The options would be just some marks like this one:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/4e157da9-dbd0-4f45-b963-21e19b4220a2)

And well, those marks could go to the Options page (maybe at the bottom?), and be shown like this (the Bold text are their titles and the text under it is what it enables/disables):

**Show Tips Values**
(All the values I showed before above)

**Show Equipped Attachments Stats Values**
ItemDescription_SightAttachment Sight: {0}
ItemDescription_TacticalAttachment Tactical: {0}
ItemDescription_GripAttachment Grip: {0}
ItemDescription_BarrelAttachment Barrel: {0}

**Show Equipped Clothing Stats Values**
ItemDescription_Clothing_Armor Armor: {0}
ItemDescription_Clothing_ExplosionArmor Explosion Armor: {0}

**Show Movement Modifiers Stats Values**
ItemDescription_ClothingMovementSpeedModifier Wearing Movement Speed: {0}
ItemDescription_EquipableMovementSpeedModifier Equipped Movement Speed: {0}

**Show Attachments Stats Values**
ItemDescription_PelletCount Pellets: {0}
ItemDescription_BulletDamageModifier Bullet Damage: {0}
ItemDescription_RecoilModifier_X Horizontal Recoil Control: {0}
ItemDescription_RecoilModifier_Y Vertical Recoil Control: {0}
ItemDescription_RecoilModifier_Aiming Aiming Recoil Control: {0}
ItemDescription_AimDurationModifier Aiming Speed: {0}
ItemDescription_AimingMovementSpeedModifier Aiming Movement Speed: {0}
ItemDescription_SpreadModifier Accuracy: {0}
ItemDescription_SwayModifier Scope Sway: {0}
ItemDescription_AimingSpreadModifier Aiming Accuracy: {0}
ItemDescription_ZoomFactor Zoom: {0}x
ItemDescription_ThirdPersonZoomFactor Zoom (3rd-Person): {0}x
ItemDescription_BulletGravityModifier Bullet Gravity: {0}

**Show Consumable Effects Stats Values**
ItemDescription_Consumeable_HealthPositive Restores Health: {0}
ItemDescription_Consumeable_HealthNegative Damages Health: {0}
ItemDescription_Consumeable_FoodPositive Restores Food: {0}
ItemDescription_Consumeable_FoodNegative Depletes Food: {0}
ItemDescription_Consumeable_WaterPositive Restores Water: {0}
ItemDescription_Consumeable_WaterNegative Depletes Water: {0}
ItemDescription_Consumeable_VirusPositive Restores Immunity: {0}
ItemDescription_Consumeable_VirusNegative Infection Damage: {0}
ItemDescription_Consumeable_StaminaPositive Restores Stamina: {0}
ItemDescription_Consumeable_StaminaNegative Depletes Stamina: {0}
ItemDescription_Consumeable_OxygenPositive Restores Oxygen: {0}
ItemDescription_Consumeable_OxygenNegative Depletes Oxygen: {0}
ItemDescription_Consumeable_WarmthPositive Provides Warmth: {0}

**Show Gun Effects Stats Values**
ItemDescription_WeaponDamage_Player_FoodPositive Impact Restores Food: {0}
ItemDescription_WeaponDamage_Player_FoodNegative Hunger Damage: {0}
ItemDescription_WeaponDamage_Player_WaterPositive Impact Restores Water: {0}
ItemDescription_WeaponDamage_Player_WaterNegative Thirst Damage: {0}
ItemDescription_WeaponDamage_Player_VirusPositive Impact Restores Immunity: {0}
ItemDescription_WeaponDamage_Player_VirusNegative Infection Damage: {0}
ItemDescription_WeaponDamage_Player_HallucinationPositive Damage Causes Hallucinations: {0}
ItemDescription_WeaponDamage_Player_HallucinationNegative Impact Heals Hallucinations: {0}

**Show Player Damages Stats Values**
ItemDescription_WeaponDamage_Player_Head Player Headshot Damage: {0}
ItemDescription_WeaponDamage_Player_Body Player Body Damage: {0}
ItemDescription_WeaponDamage_Player_Arm Player Arm Damage: {0}
ItemDescription_WeaponDamage_Player_Leg Player Leg Damage: {0}

**Show Zombie Damages Stats Values**
ItemDescription_WeaponDamage_Zombie_Head Zombie Headshot Damage: {0}
ItemDescription_WeaponDamage_Zombie_Body Zombie Body Damage: {0}
ItemDescription_WeaponDamage_Zombie_Arm Zombie Arm Damage: {0}
ItemDescription_WeaponDamage_Zombie_Leg Zombie Leg Damage: {0}

**Show Animal Damages Stats Values**
ItemDescription_WeaponDamage_Animal_Head Animal Headshot Damage: {0}
ItemDescription_WeaponDamage_Animal_Body Animal Body Damage: {0}
ItemDescription_WeaponDamage_Animal_Limb Animal Limb Damage: {0}

**Show Level Damages Stats Values**
ItemDescription_WeaponDamage_Barricade Barricade Damage: {0}
ItemDescription_WeaponDamage_Structure Structure Damage: {0}
ItemDescription_WeaponDamage_Vehicle Vehicle Damage: {0}
ItemDescription_WeaponDamage_Resource Resource Damage: {0}
ItemDescription_WeaponDamage_Object Object Damage: {0}

**Show Explosive Damages Stats Values**
ItemDescription_WeaponDamage_Invulnerable Heavy Weapon: Can damage Tough entities.
ItemDescription_ExplosionBlastRadius Explosion Radius: {0}
ItemDescription_ExplosionPlayerDamage Player Damage (Explosion): {0}
ItemDescription_ExplosionZombieDamage Zombie Damage (Explosion): {0}
ItemDescription_ExplosionAnimalDamage Animal Damage (Explosion): {0}
ItemDescription_ExplosionBarricadeDamage Barricade Damage (Explosion): {0}
ItemDescription_ExplosionStructureDamage Structure Damage (Explosion): {0}
ItemDescription_ExplosionVehicleDamage Vehicle Damage (Explosion): {0}
ItemDescription_ExplosionResourceDamage Resource Damage (Explosion): {0}
ItemDescription_ExplosionObjectDamage Object Damage (Explosion): {0}

**Show Trap Damages Stats Values**
ItemDescription_Trap_PlayerDamage Player Damage: {0}
ItemDescription_Trap_ZombieDamage Zombie Damage: {0}
ItemDescription_Trap_AnimalDamage Animal Damage: {0}

**Show Gun Stats Values**
ItemDescription_Firerate Rate of Fire: {0} rpm
ItemDescription_Spread Inaccuracy: {0} °
ItemDescription_DamageFalloff Damage falloff begins at {0} down to {2} at {1}.
ItemDescription_WeaponRange Range: {0}

**Show Buildable Stats Values**
ItemDescription_Buildable_ArmorTier_Low Armor Tier: Low
ItemDescription_Buildable_ArmorTier_High Armor Tier: High
ItemDescription_Buildable_Health Health: {0}
ItemDescription_Buildable_Invulnerable Tough: Can only be damaged by Heavy Weapons.

**Show Farmable Stats Values**
ItemDescription_Farmable_GrowSpecificItem Produces: {0}

**Show Storage Stats Values**
ItemDescription_StorageDimensions Storage: {0} x {1}

**Show Throwable Stats Values**
ItemDescription_Throwable_FuseLength Fuse Length: {0}

**Show Melee Stats Values**
ItemDescription_Melee_StrongAttackModifier Strong Attack Damage: {0}
ItemDescription_Melee_StrongAttackStamina Strong Attack Stamina Cost: {0}

**Show Arrest Stats Values**
ItemDescription_ArrestEnd_UnlocksItem Unlocks: {0}

**Comment by SDGNelson** [comment]
Thanks for the feedback!

Some of these have been adjusted in the next preview version.

For percentages without a separate positive/negative description the +/- is used, but for stats with a negative description there shouldn't have been a negative symbol.

The beneficial vs negative coloring was initially intended to be from the perspective of the player owning the item. Some stats aren't necessarily positive/negative from that point of view, instead they are neutral. For example, whether a weapon heals bleeding is positive depends whether the weapon is intended for healing or not. Decreasing thirst is positive if the weapon is offensive, but negative if it's otherwise a healing weapon.

Knowing that mods use these properties in lots of different ways informed some of the descriptions. For example, the farmable description doesn't have equivalent descriptions if those plant-specific properties are removed because mods use them for money printers. The long sentences there are merged into a paragraph now btw.

I'm not sure what route we'll end up going with the option to turn individual descriptions on/off. I think it depends what kind of requests there are after the update.
