### ISSUE TITLE
Schofield have bad texture

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4123]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/a58d2f19-6467-46cf-86bf-33dfd1447eba)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/9263a66e-1e28-4330-8b5c-24b3e2a00825)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/4d4b48ea-90af-4c38-8fd2-52edf8f84080)

**Comment by QERT2002** [comment]
Hawkhound too
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/c82533c2-32eb-4d90-86ca-341e65a970b4)

**Comment by SDGNelson** [comment]
Thanks for the report! Before the preview release Molt ran into this with the Mercenary top as well. I tried updating to the latest LTS version, no dice. Slightly modifying the image and resaving seemed to resolve it both times. :confused:

**Comment by ItsRodrigoAl** [comment]
@SDGNelson PDW also need this fix
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/1136d863-035e-48a0-ae9e-517b7a1f311d)
