### ISSUE TITLE
Rocket.cs not destroying moving parent barricade on multiplayer servers

### ISSUE THREAD

**Issue by ucynik** [SmartlyDressedGames/Unturned-3.x-Community#4125]
I have made a barricade that moves via a constant force. It has a function to enable a box collider on it, which would allow an attached `Rocket.cs` to explode and destroy the barricade. Image shown below.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/129130028/a3355a26-b668-4f45-b124-42340679e331)

This barricade is also tagged/layered as so to enable collision with the ground and other objects:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/129130028/9561698e-3ecd-4816-aaf8-a6d0c87ad7ca)

On Singleplayer, this works as intended, the barricade is destroyed without any issues. 

However on Multiplayer, the barricade has a strange interaction; after exploding the barricade appears to be destroyed, but upon the player relogging, the barricade appears at its original position. This ghost barricade cannot be interacted with or destroyed until the server reboots, during which it reverts to a normal version of this barricade. **This only happens if the barricade has traveled more than roughly 20-30 meters, otherwise it is destroyed without any issues.**

As for the reason this is happening, I asked on Unturned Official for a possible explanation on why `Rocket.cs` might not be destroying barricades correctly on servers, and this was the answer I recieved. Hopefully this will make the issue clearer: 

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/129130028/570e4336-979c-4f0a-b735-386da2798e61)

This is the `.dat` of the barricade:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/129130028/21210b6f-b090-4aa9-b6e7-8ce46fcefd0e)

**Comment by GazziFX** [comment]
This barricade is not fully destroyed, you destroy only GameObject but data still presented in memory. Full GameObjects state replication will never be supported

**Comment by GazziFX** [comment]
This barricade is not fully destroyed, you destroy only GameObject but data still presented in memory. Full GameObjects state replication will never be supported.

You can also try to move rocket script to child object and see if only child or whole barricade was destroyed

**Comment by SDGNelson** [comment]
Sorry but this would not be properly supported as mentioned by GazziFX. In part, for example, that barricades won't move properly unless the system is notified.
