### ISSUE TITLE
(PREVIEW BRANCH) Left_Handed_Characters_Mirror_Equipable keeps the Killcounter Flipped

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4126]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/5f7346a9-b037-45be-850a-bb6e0873306b)

shouldnt be too big of an issue, but when an item has "Left_Handed_Characters_Mirror_Equipable false", the item gets flipped as expected, but the killcounter is not un-flipped.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/e6ce443a-2557-453f-b8bb-5fce1584701a)
the killcounter is flipped when set to true, as expected.

shouldnt be that big of an issue as any item that supports killcounters dont have this on by default.

**Comment by SDGNelson** [comment]
Thanks for the pointing it out. Fortunately, I don't think this is a concern because as you mentioned no items with kill counters use it.
