### ISSUE TITLE
The dll dependencies not load correct.

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4128]
The modules after update load dependencies from the main Unturned folder, not from /Modules/TestModule folder.

**Comment by SDGNelson** [comment]
Are you using OpenMod? (issue #4127)?

**Comment by QERT2002** [comment]
> Are you using OpenMod? (issue #4127)?

No vanilla game Modules system
Load module dependencies from main Unturned folder

**Comment by QERT2002** [comment]
I use rocket and rocket don't have dependecies like 0Harmony.dll
But my module what fix rocket color use this dll, and before update it load it from /Modules/QertColorFixer/0Harmony.dll
After update it loads only from U3DS/0Harmony.dll

**Comment by SDGNelson** [comment]
My test server has Rocket installed, and it loads several assemblies from the per-module folder. If Rocket is working for you and loading dependencies why are the dependencies for your module loaded differently?

**Comment by QERT2002** [comment]
[QertRocketLogColorFix.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12898174/QertRocketLogColorFix.zip)

Just put this in the modules folder

**Comment by QERT2002** [comment]
When the game server open it says: I can load dependencie 0Harmony.dll
And you need to copy and paste 0Harmony.dll to U3DS main folder

**Comment by SDGNelson** [comment]
It looks like 0Harmondy.dll isn't in the Assemblies list. If you add it does it work?

**Comment by QERT2002** [comment]
But this is dependency to main dll, i never wrote it down on that list, because it's not need to direct load

**Comment by QERT2002** [comment]
Yes, if i add it to assemblies list it work's but it shouldn't work like that.
I have heavier modules that use 5-6 dependencies and adding each of them to a file would be stupid.
Before the update, they simply loaded from their folders automatically without any problems.

In the .module file I always wrote only the module itself, which should be loaded into the game and which implements the INexusModule interface.

**Comment by DanielWillett** [comment]
Assemblies have never loaded if they weren't in the list. Likely it was being loaded by another module like OpenMod.

**Comment by QERT2002** [comment]
> Assemblies have never loaded if they weren't in the list. Likely it was being loaded by another module like OpenMod.


Yes, this is called a dependency system, the main dll checked whether the folder contains the dlls it needed and load them

**Comment by QERT2002** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/0fdce2c8-25f8-4c1b-b3c1-8edf6a45c8fc)

Main dll and its dependency

**Comment by SDGNelson** [comment]
Perhaps the way .NET automatically resolves assemblies changed? Nevertheless, including it in the .module file's assemblies list should work.

**Comment by QERT2002** [comment]
> Perhaps the way .NET automatically resolves assemblies changed? Nevertheless, including it in the .module file's assemblies list should work.

Adding to the list solves the problem, but this is a crutch, if you changed something in the operation of the modules, please check and fix this, it's very annoying problem.

**Comment by DanielWillett** [comment]
He didn't change anything with the modules. It's just a side effect of changing Unity versions. I don't think that was intended behavior in the first place.

**Comment by QERT2002** [comment]
> He didn't change anything with the modules. It's just a side effect of changing Unity versions. I don't think that was intended behavior in the first place.


I see, thanks for the answer, it’s a shame that this is happening.

**Comment by SDGNelson** [comment]
It looks like Rocket also binds AssemblyResolve, and does a search for all *.dll files in plugin directories to handle requests. Nothing related to Unturned's module loading was changed in this update, but my guess is that somehow either the order is different after the engine update or the way return values from events with multiple subscribers changed.

Unturned could do an equivalent search, but I'm hesitant about that for a few reasons. That might also mess with OpenMod.

Another option would be to add an event to ModuleHook invoked before Unturned's AssemblyResolve, allowing Rocket to override the result.

Unturned's list could also be smarter using AssemblyName rather than string name.

It looks like the .NET version for Rocket would need to be increased to 4.8 if updating, so I'm wondering also if that might cause more headache.

Thoughts?

**Comment by SDGNelson** [comment]
In 3.23.12.2 on the preview version I added three events:
- `PreVanillaAssemblyResolve` invoked before any of Unturned's `AssemblyResolve` code
- `PreVanillaAssemblyResolvePostRedirects` invoked after the Steamworks.NET redirect
- `PostVanillaAssemblyResolve` invoked after Unturned's built-in `AssemblyResolve` code

Rocket 4.9.3.16 on the preview branch now uses `PreVanillaAssemblyResolvePostRedirects` as well as `AssemblyResolve`.

That being said, I'm not sure if it's actually made a difference. Based on the logging it seems like Rocket was maybe already still handling AssemblyResolve. If you're running into issues with assembly loading, did this actually fix it for you?
