### ISSUE TITLE
Gun audio not playing for other players, most recent update. 3.23.12.0

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4129]
All audio made by guns by other players cannot be heard, making guns completely silent.
Guns do have audio for the person shooting them, but not for the opponent.

**Comment by Axodouble** [comment]
Attached below a video link (mp4) of gun audio not working.
https://xdbl.dev/i?i=d14123312.mp4

**Comment by SDGNelson** [comment]
Thanks for the report! Sorry, when I checked before the update the only issue I saw posted was #4126, maybe there was some GitHub service downtime. D:

**Comment by SDGNelson** [comment]
Oh actually my system clock was out of sync by 6 hours. ???

**Comment by Axodouble** [comment]
> Oh actually my system clock was out of sync by 6 hours. ???

Incredibly unfortunate, I assume you have gotten reports of the issues with OpenMod now too?

**Comment by SDGNelson** [comment]
Should be fixed with the .1 patch now!
