### ISSUE TITLE
Any idea on what happened?

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#413]
https://pastebin.com/gKCReGiU

This server is running on a Linux machine. Something weird that I noted is that when we tried to type things into console it would not prompt / give anything back (such as typing 'players' didn't give me a report of players, which I thought was incredibly weird)

`Loading level: 50%
Loading level: 58%
Loading level: 66%
Loading level: 75%
Loading level: 83%
Loading level: 91%
Loading level: 100%
players
/players
players
players
list
players
admin rain
s`

After that the error occurred. The server was up for quite a while before it had the error.

Extra sidenote: This error pops up everytime the server starts. The other servers are fine and I browsed online and found that it's just some error that means nothing - https://pastebin.com/6G9B4CUM not entirely sure though.

**Comment by RainOfPain125** [comment]
oh, uh. Ok. Assuming this will never be fixed / cant be fixed or what not the server is working fine after a restart. so uh.. idk. Thanks I suppose

**Comment by RainOfPain125** [comment]
Not sure if relevant, but

https://pastebin.com/YbVxEVdn this error crashed one server

https://pastebin.com/wX9YgFMV this error occured when trying to shutdown another server. same machine / using linux.

**Comment by Jonnyfencing1** [comment]
it is a mono error
