### ISSUE TITLE
Inventory icons and skins not loading correctly. 3.23.12.0

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4130]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/73b46eb0-1276-434c-9be8-422d67045322)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/b06c4139-edc9-4650-af6c-3e31e16cd1c9)

As pictured above, item skins are not loading correctly on to guns.

**Comment by SDGNelson** [comment]
Thanks for the report! There seem to be a handful of metallic textures that got messed up presumably from the engine upgrade. (#4123) I've now resaved the Augewehr metallic map for the patch.

**Comment by SDGNelson** [comment]
This gun and the Bounty Hunter Maplestrike should be fixed in the .1 patch now!
