### ISSUE TITLE
NPCs do not teleport the player

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#4132]
After the update, NPCs stopped teleporting the player.

```
Response_0_Rewards 1
Response_0_Reward_0_Type Teleport
Response_0_Reward_0_Spawnpoint 1
```
Also, NPCs do not give flags in dialogues.

**Comment by SDGNelson** [comment]
This should be fixed in the patch now! (https://twitter.com/SDGNelson/status/1712918538997178825)
