### ISSUE TITLE
Screenshot functionality not working with high resolution/supersampling

### ISSUE THREAD

**Issue by KarmaWSYD** [SmartlyDressedGames/Unturned-3.x-Community#4133]
While testing out the update, I noticed a crash + error while trying to take a 10240x5760 screenshot (1440p with 4x supersampling), tested out in the current update as well as the Unity 2020 branch. Notably, issues only happen with high resolutions, 3x supersampling at 1440p (7680x4320 or 8k) or below worked fine.

Crash log (Screenshot attempt, instant crash, no screenshot created):

> [2023-10-13 18:57:19] Steam overlay screenshot requested
[2023-10-13 18:57:19] Capturing 10240x5760 screenshot (Size Multiplier: 4 Use Supersampling: True HUD Visible: False)
[2023-10-13 18:57:20] Texture has out of range width / height
[2023-10-13 18:57:20] 0x00007ffaa09b0c4d (UnityPlayer) UnityMain
0x00007ffaa09b5cb3 (UnityPlayer) UnityMain
0x00007ffaa099fcd5 (UnityPlayer) UnityMain
0x00007ffaa0f6707e (UnityPlayer) UnityMain
0x00007ffaa0557698 (UnityPlayer) 
0x00007ffaa0d17493 (UnityPlayer) UnityMain
0x00007ffaa03640a9 (UnityPlayer) 
0x00000261e441f6e5 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.ScreenCapture:CaptureScreenshotAsTexture (int,UnityEngine.ScreenCapture/StereoScreenCaptureMode)
0x00000261e441f603 (Mono JIT Code) UnityEngine.ScreenCapture:CaptureScreenshotAsTexture (int)
0x00000261e441dab3 (Mono JIT Code) SDG.Unturned.Provider/<CaptureScreenshot>d__18:MoveNext ()
0x0000025fe9698270 (Mono JIT Code) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
0x0000025fe969839f (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr (object,intptr,intptr,intptr)
0x00007ffaa59ffb54 (mono-2.0-bdwgc) mono_jit_set_domain
0x00007ffaa593e794 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007ffaa593e92c (mono-2.0-bdwgc) mono_runtime_invoke
0x00007ffaa07c17dd (UnityPlayer) 
0x00007ffaa07ae7c2 (UnityPlayer) 
0x00007ffaa07a0d95 (UnityPlayer) 
0x00007ffaa04ca2b4 (UnityPlayer) 
0x00007ffaa0627b44 (UnityPlayer) 
0x00007ffaa061aaba (UnityPlayer) 
0x00007ffaa061ab60 (UnityPlayer) 
0x00007ffaa061d838 (UnityPlayer) 
0x00007ffaa081a67a (UnityPlayer) 
0x00007ffaa08193ab (UnityPlayer) 
0x00007ffaa081db87 (UnityPlayer) 
0x00007ffaa081f6eb (UnityPlayer) UnityMain
0x00007ff7eb6211f2 (Unturned) 
0x00007ffb75527344 (KERNEL32) BaseThreadInitThunk
0x00007ffb774a26b1 (ntdll) RtlUserThreadStart
[2023-10-13 18:57:21] Texture '' has no data.
[2023-10-13 18:57:21] 0x00007ffaa09b0c4d (UnityPlayer) UnityMain
0x00007ffaa09b5cb3 (UnityPlayer) UnityMain
0x00007ffaa099fcd5 (UnityPlayer) UnityMain
0x00007ffaa0f6707e (UnityPlayer) UnityMain
0x00007ffaa05518a2 (UnityPlayer) 
0x00007ffaa055b35c (UnityPlayer) 
0x00007ffaa0d174aa (UnityPlayer) UnityMain
0x00007ffaa03640a9 (UnityPlayer) 
0x00000261e441f6e5 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.ScreenCapture:CaptureScreenshotAsTexture (int,UnityEngine.ScreenCapture/StereoScreenCaptureMode)
0x00000261e441f603 (Mono JIT Code) UnityEngine.ScreenCapture:CaptureScreenshotAsTexture (int)
0x00000261e441dab3 (Mono JIT Code) SDG.Unturned.Provider/<CaptureScreenshot>d__18:MoveNext ()
0x0000025fe9698270 (Mono JIT Code) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
0x0000025fe969839f (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr (object,intptr,intptr,intptr)
0x00007ffaa59ffb54 (mono-2.0-bdwgc) mono_jit_set_domain
0x00007ffaa593e794 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007ffaa593e92c (mono-2.0-bdwgc) mono_runtime_invoke
0x00007ffaa07c17dd (UnityPlayer) 
0x00007ffaa07ae7c2 (UnityPlayer) 
0x00007ffaa07a0d95 (UnityPlayer) 
0x00007ffaa04ca2b4 (UnityPlayer) 
0x00007ffaa0627b44 (UnityPlayer) 
0x00007ffaa061aaba (UnityPlayer) 
0x00007ffaa061ab60 (UnityPlayer) 
0x00007ffaa061d838 (UnityPlayer) 
0x00007ffaa081a67a (UnityPlayer) 
0x00007ffaa08193ab (UnityPlayer) 
0x00007ffaa081db87 (UnityPlayer) 
0x00007ffaa081f6eb (UnityPlayer) UnityMain
0x00007ff7eb6211f2 (Unturned) 
0x00007ffb75527344 (KERNEL32) BaseThreadInitThunk
0x00007ffb774a26b1 (ntdll) RtlUserThreadStart
[2023-10-13 18:57:21] No texture data is available to upload.
[2023-10-13 18:57:21] 0x00007ffaa09b0c4d (UnityPlayer) UnityMain
0x00007ffaa09b5cb3 (UnityPlayer) UnityMain
0x00007ffaa099fcd5 (UnityPlayer) UnityMain
0x00007ffaa0f6707e (UnityPlayer) UnityMain
0x00007ffaa055d517 (UnityPlayer) 
0x00007ffaa0d174b7 (UnityPlayer) UnityMain
0x00007ffaa03640a9 (UnityPlayer) 
0x00000261e441f6e5 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.ScreenCapture:CaptureScreenshotAsTexture (int,UnityEngine.ScreenCapture/StereoScreenCaptureMode)
0x00000261e441f603 (Mono JIT Code) UnityEngine.ScreenCapture:CaptureScreenshotAsTexture (int)
0x00000261e441dab3 (Mono JIT Code) SDG.Unturned.Provider/<CaptureScreenshot>d__18:MoveNext ()
0x0000025fe9698270 (Mono JIT Code) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
0x0000025fe969839f (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr (object,intptr,intptr,intptr)
0x00007ffaa59ffb54 (mono-2.0-bdwgc) mono_jit_set_domain
0x00007ffaa593e794 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007ffaa593e92c (mono-2.0-bdwgc) mono_runtime_invoke
0x00007ffaa07c17dd (UnityPlayer) 
0x00007ffaa07ae7c2 (UnityPlayer) 
0x00007ffaa07a0d95 (UnityPlayer) 
0x00007ffaa04ca2b4 (UnityPlayer) 
0x00007ffaa0627b44 (UnityPlayer) 
0x00007ffaa061aaba (UnityPlayer) 
0x00007ffaa061ab60 (UnityPlayer) 
0x00007ffaa061d838 (UnityPlayer) 
0x00007ffaa081a67a (UnityPlayer) 
0x00007ffaa08193ab (UnityPlayer) 
0x00007ffaa081db87 (UnityPlayer) 
0x00007ffaa081f6eb (UnityPlayer) UnityMain
0x00007ff7eb6211f2 (Unturned) 
0x00007ffb75527344 (KERNEL32) BaseThreadInitThunk
0x00007ffb774a26b1 (ntdll) RtlUserThreadStart

I proceeded to test it a couple of times and crashed each time with the same crash log. I then proceeded to test in the unity 2020 archival branch, which gave the following error (no crash, however no screenshot was created):

> [2023-10-13 20:21:21] Steam overlay screenshot requested
[2023-10-13 20:21:21] Capturing 10240x5760 screenshot (Size Multiplier: 4 Use Supersampling: True HUD Visible: True)
[2023-10-13 20:21:22] Texture has out of range width / height
[2023-10-13 20:21:22] SetPixels32 can only be called on a RGBA32 or BGRA32 texture but is being called on GraphicsFormat None (0)
[2023-10-13 20:21:22] No texture data is available to upload.
[2023-10-13 20:21:22] ArgumentException: RenderTextureDesc graphicsFormat must be a supported GraphicsFormat. None is not supported.
Parameter name: desc.graphicsFormat
[2023-10-13 20:21:22] UnityEngine.RenderTexture.ValidateRenderTextureDesc (UnityEngine.RenderTextureDescriptor desc) (at <966ecbc21bec4138a5192b5e1b2dd41f>:0)
UnityEngine.RenderTexture.GetTemporary (UnityEngine.RenderTextureDescriptor desc) (at <966ecbc21bec4138a5192b5e1b2dd41f>:0)
UnityEngine.RenderTexture.GetTemporaryImpl (System.Int32 width, System.Int32 height, System.Int32 depthBuffer, UnityEngine.Experimental.Rendering.GraphicsFormat format, System.Int32 antiAliasing, UnityEngine.RenderTextureMemoryless memorylessMode, UnityEngine.VRTextureUsage vrUsage, System.Boolean useDynamicScale) (at <966ecbc21bec4138a5192b5e1b2dd41f>:0)
UnityEngine.RenderTexture.GetTemporary (System.Int32 width, System.Int32 height, System.Int32 depthBuffer, UnityEngine.Experimental.Rendering.GraphicsFormat format) (at <966ecbc21bec4138a5192b5e1b2dd41f>:0)
SDG.Unturned.Provider+<CaptureScreenshot>d__18.MoveNext () (at <45050d842cd8471a8f6dd493c1a66add>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <966ecbc21bec4138a5192b5e1b2dd41f>:0)

Finally, I proceeded to retry the error in the current version, and though it still gave the initial error the game didn't crash (potentially indicating that the issue wasn't the only reason for the crash?), and created the following blank screenshot:
![2023-10-13_23-26-45](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/92757174/ee9b3c3d-5b07-40e6-9ff1-4941a219ec06)

**Comment by SDGNelson** [comment]
Thanks for the report. It looks like Unity perhaps unintentionally introduced a crash for their "Texture has out of range width / height" error. Unity's highest texture size is 16384, but perhaps lower on your PC. I'll change the game to not request a screenshot if size is higher than `SystemInfo.maxTextureSize`. Nevertheless, it won't be able to handle this size.
