### ISSUE TITLE
Guns / items not restricted in animation anymore.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4135]
Not sure if bug, however guns are no longer stuck in an animation if you want to swap out an item while the animation is still playing, this lets you spam swap different items without needing to wait for the animation to finish playing.

**Comment by Axodouble** [comment]
Edit: You can cancel any animations, this includes swapping items while running, swapping items instantly, this also includes barricades and structures.

**Comment by SDGNelson** [comment]
Oof 🤦‍♂️

**Comment by Axodouble** [comment]
> Oof 🤦‍♂️

Yup, sorry about that. lol
