### ISSUE TITLE
Issue with reward value Reward_#_Auto_Equip.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4136]
Minor issue being, reward value `Reward_#_Auto_Equip` does not auto equip if the bool is set to true.

Example:
```
Type Food
Useable Consumeable
ID ITEMID

Size_X 1
Size_Y 1

Quest_Rewards 1
Quest_Reward_0_Type Item
Quest_Reward_0_ID ITEMID
Quest_Reward_0_Amount 1
Quest_Reward_0_Auto_Equip True
```

Expected behaviour is not replicated in-game and doesn't auto equip the item once rewarded.

**Comment by SDGNelson** [comment]
In that example I think it's because you're using it with the consumable item. It can't auto equip while the consumable item is still equipped. Were you only using it in this context, or is it not working elsewhere for you?

**Comment by Axodouble** [comment]
That makes sense- though might be nice to have in the future. As for example Arid as multi-use water bottles but the newly received less-filled water bottles aren't automatically equipped, with or without this tag.
