### ISSUE TITLE
Bugs with HUD.

### ISSUE THREAD

**Issue by m00nchance** [SmartlyDressedGames/Unturned-3.x-Community#4139]
And a wierd bug?
And no  i did not hide HUD , i tried pressing every key and nothing appears , when i press inventory keybinds the background just get's blurred
I was just gonna join a server w friend and this happend :
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146444863/f490dffa-e173-4136-863a-67d09bf86d37)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146444863/7482b496-53d7-4fc3-8781-01a63d007b25)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146444863/75dccd50-c5e3-4237-aad1-8916f04722d2)

**Comment by SDGNelson** [comment]
Does it happen again after re-opening the game? If so, could you attach this log file please? https://support.smartlydressedgames.com/hc/en-us/articles/12299037547284

**Comment by m00nchance** [comment]
> Does it happen again after re-opening the game? If so, could you attach this log file please? https://support.smartlydressedgames.com/hc/en-us/articles/12299037547284

Here it is ,  it happend when i joined the rusturned server
here " [2023-10-14 14:22:51] US Modded Rusturned 3x #3 | RUST MOD [US] host ban flags: None "
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12906674/Client_Prev.log)

**Comment by SDGNelson** [comment]
Ah! Thanks for the log. I suspect this error is the same cause of #4134 🤔
