### ISSUE TITLE
Animated color

### ISSUE THREAD

**Issue by ImIveooo** [SmartlyDressedGames/Unturned-3.x-Community#414]
I don't know if this is possible but is it possible to have an example to have animated color like a gif, like a  raimbow car ? 🤔

**Comment by FCheat** [comment]
I mean yea, you can do it for your own client, the fields are markup.

**Comment by SDGNelson** [comment]
Playing a gif in-game, or in dynamic surfaces in general? Most likely you want to look into writing surface shaders or vertex+fragment shaders for Unity, and then set Asset_Bundle_Version 2 to enable loading them in-game.
