### ISSUE TITLE
Suggestions for game updates For SDGNelson 

### ISSUE THREAD

**Issue by IronManMK47** [SmartlyDressedGames/Unturned-3.x-Community#4141]
I've been running the server on this game for 7 years, and since 2016, I've noticed that you often choose to update the game every Friday in your local time (which is Saturday morning in our local time), and most developers in the world choose Wednesday or Thursday to release updates to their games
   because when you find that There is a problem in the update that has been released, you can have enough time to fix it, and Wednesday, Thursday and Friday are weekdays, the flow of players will be much less than the weekend, even if the spread of vicious vulnerabilities will be greatly reduced, and the affected players will be much lower.
   In fact, the most hurt in this is our thousands of server owners, not all of them will find the update notice you posted on the blog in advance, and even if they see it, they will not test it, because we are not sure that you will release the update on that day, at least as most ordinary server owners, there is no opportunity to communicate with your team immediately.
When you release some big update, you choose to update on your local Friday, you are not sure if there will be some bugs, maybe you know there will be some problems, but you also need us players to find your bugs, so all of us players will have a bad weekend gaming experience.
   I only suggest on behalf of myself: we hope you can choose to release the update every Wednesday or every Thursday, even if there is a problem, we will have enough time to adjust and repair, so as to avoid damaging the players' beautiful game mood, and you will also have enough time to adjust and repair, so that you can have a good weekend (no players will disturb you because of game problems).
   Hopefully, avoiding weekend updates will be the smartest thing you can do!
   All of the above is just a few opinions, just a small suggestion.
    Everyone can express your opinion

**Comment by ItsRodrigoAl** [comment]
Well, this is not a game issue so should be good is you move it to the Discussions page

Big updates like this one are very weird (is not like updating the unity version were every month), keeping it on Fridays help to have this "hype" factor for players. However, I support the idea of moving big updates like this one to Wednesdays because they have bigger chances to ruin a lot of things like yesterday, but for small updates it's fine to keep it on Fridays

**Comment by SDGNelson** [comment]
Thanks for your support all the way back to 2016!
Friday updates are kind of a "tradition" for Unturned, but nowadays I would tend to agree that mid-week would be wiser. Releasing the preview version several days ahead with the update notes available was in part intended to help cases like this. (3.23.12.0 was on the preview branch this past Monday) It seems like a shame to break the tradition, but maybe it's the right thing to do.
