### ISSUE TITLE
[Suggestion] EPluginWidgetFlags.ShowChat

### ISSUE THREAD

**Issue by wristcry** [SmartlyDressedGames/Unturned-3.x-Community#4142]
Or any other way to disable chat

As chat box is now fully clickable, it breaks some modded fullscreen UIs
[It looks like this](https://youtu.be/7STEo_gO4OU)

**Comment by SDGNelson** [comment]
For the sake of compatibility with plugins like that, I've now changing the chat scroll view to enable/disable raycast target on the content rect when chatting or not.

**Comment by SDGNelson** [comment]
Should be resolved!
