### ISSUE TITLE
I think you forgot to turn off full stacktraces for unity errors

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4143]
All of unity engine errors have full stacktrace that at the moment of recording the log, FPS drops.

**Comment by QERT2002** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/d1802ab4-5948-4d06-8cd5-7da22e1e1666)

**Comment by SDGNelson** [comment]
Thanks! You're right: there was an error related to web requests I was trying to track down so I enabled full stack trace for a couple weeks and forgot to turn it off.

**Comment by nikiternak5269** [comment]
When should I expect a fix?

**Comment by SDGNelson** [comment]
Should be resolved now!

**Comment by rube200** [comment]
@SDGNelson is it related to async calls?
On OpenMod we spotted a bug in Mono itself related to socket ReceiveAsync

**Comment by SDGNelson** [comment]
@rube200 The reason was that Unturned wasn't properly disposing of UnityWebRequest. I'm not personally very familiar with c# async. It's used in a couple places. For example, ResourceHash uses CopyToAsync, and that seems to be working fine.
