### ISSUE TITLE
i found a issue with typing in public chat some words go to *** but in group chat it dont do it

### ISSUE THREAD

**Issue by Aimbot12345678** [SmartlyDressedGames/Unturned-3.x-Community#4146]
i found a issue with typing in public chat some words go to *** but in group chat it dont do it 

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/89653178/c6535286-0da1-453f-ae68-9c1903bd6caf)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/89653178/31d22441-d982-4b0f-849f-316d2655d262)

**Comment by SDGNelson** [comment]
What was the original message? I don't think anything in the game replaces with * except the Steam profanity filter?

**Comment by DanielWillett** [comment]
> i found a issue with typing in public chat some words go to *** but in group chat it dont do it

think it was this

**Comment by SDGNelson** [comment]
Haha, thanks @DanielWillett! Yes, that makes sense. I'll check into it.

**Comment by SDGNelson** [comment]
I tested that message but it went through normally. I wonder if:
- Is it a particular server? Maybe they have their own profanity filter.
- Do you have any custom phrases added to Steam profanity filter?

**Comment by Aimbot12345678** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/89653178/c9b1c071-1090-44a8-963b-b9940eed4c44)

**Comment by SDGNelson** [comment]
I notice you closed the issue - did you find the cause? If you don't mind me asking, what was it? (no judgement)
