### ISSUE TITLE
With IMGUI Interface buttons in inventory not work

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4147]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/c7cde83a-7e67-488a-8dad-eaa74f62c93e

I like use old interface, because it have normal font and "Craft All" / "Craft" buttons and it have lower lags and freezes than new interfaces, but after update buttons in inventory(item desc) not work.

**Comment by SDGNelson** [comment]
Thanks for the report! I'll get this fixed for the next patch/update.

**Comment by SDGNelson** [comment]
Visually the UITK option is quite similar to IMGUI and supports the newer features except for wonky scrollviews everywhere.

**Comment by QERT2002** [comment]
> Visually the UITK option is quite similar to IMGUI and supports the newer features except for wonky scrollviews everywhere.

I think if you can add the options to enable "Craft All" / "Craft" buttons and option to change font from bold to normal in game settings, many peoples who using old interface can normally play on new interfaces.

**Comment by DanielWillett** [comment]
You can sort of change that in your preferences file.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/7b38833d-5b6c-44de-b1b3-7b39c929cd2b)

Which correspond to the following values (starting at zero), so setting them all to zero should achieve what you're looking for (although imo the shadows look good).
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/757ed07a-508f-4651-88aa-3dcbdb295004)

What they look like (not sure if you can use Tooltip)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/10e77946-544d-46f2-8ab0-041ccb624dc3)

**Comment by QERT2002** [comment]
> You can sort of change that in your `preferences.json` file.
> 
> ![image](https://user-images.githubusercontent.com/12886600/276027720-7b38833d-5b6c-44de-b1b3-7b39c929cd2b.png)
> 
> Which correspond to the following values (starting at zero), so setting them all to zero should achieve what you're looking for (although imo the shadows look good). ![image](https://user-images.githubusercontent.com/12886600/276027811-757ed07a-508f-4651-88aa-3dcbdb295004.png)
> 
> What they look like (not sure if you can use Tooltip) ![image](https://user-images.githubusercontent.com/12886600/276028991-10e77946-544d-46f2-8ab0-041ccb624dc3.png)

Oh, it's cool +rep idk about this. If Nelson Add a "Craft All" / "Craft" buttons option i must use new interfaces

**Comment by QERT2002** [comment]
I have all values are zero by default, and despite this I think that the new interfaces use a different font/boldness
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/70c491ad-3d60-45a4-af4f-595eb642f0b1)

**Comment by QERT2002** [comment]
New font: 
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/e1f6e3db-2c21-4ab8-babc-11a9a7f926f3)

Old font:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/92d57b70-025d-4e1c-8095-179424140467)

**Comment by DanielWillett** [comment]
It's supposed to work I think, could be a bug.

**Comment by DanielWillett** [comment]
@QERT2002  Sorry I was mistaken, the correct values are below. Try setting them to 3.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/f58b7824-7c48-4b53-ab83-0291cc212593)
