### ISSUE TITLE
"sv channel receive failed"

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#415]
Hey Nelson,

My server is experiencing issues where many people disconnect from my server at once. Looking at logs when this happens reveals this line being outputted at the time of the disconnect:

`[20:43:13 - 21/09/2018] General: Refusing connections from 76561198111393416 (sv channel receive failed)`

for many players on the server. This doesn't happen for some people (out of 18 people on the server, 5 did not get kicked)

IN ADDITION players are not able to re-connect until the server is restarted (Disconnects when on queue screen)

Attached is the full log for my server. Please help! Thanks.

[Server_US1_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2407396/Server_US1_Prev.log)

**Comment by SDGNelson** [comment]
Sorry for the delay, a patch should have been released earlier today but there's been some crazyness which I hope I can talk about soon. I'll try to get it up tonight!

**Comment by SDGNelson** [comment]
Most recent build is up on the preview branch now, but won't be released until tomorrow morning when I can properly keep an eye out for issues.

**Comment by N1GHTPATROL** [comment]
Fixed :)
