### ISSUE TITLE
Player Shadow not appearing when on Bike (or vehicles in general?)

### ISSUE THREAD

**Issue by Kopfstroh** [SmartlyDressedGames/Unturned-3.x-Community#4156]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/83455977/63bca610-d79c-48e2-ab1b-d9a0defebeca)
As you can see in this screenshot I took on PEI, player shadows dont get shown when you're on a bike

**Comment by SDGNelson** [comment]
I don't think the player shadow has ever been visible in first-person - the third-person model is disabled while in first-person. This was an improvement in 4.0 but is unlikely to happen in 3.x, unfortunately.
