### ISSUE TITLE
Local Server: Built-in resources mismatch. Verifying game files should repair this.

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4158]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/f3edb649-5c77-4f72-b8f9-7242aefe0d33)

My attempts to solve this problem:
- Verify files in Unturned via steam
- Reinstall local server
- Run empty server without openmod or rocketmod
- Reinstall Unturned

**Comment by SDGNelson** [comment]
Are you able to join other servers? i.e., is it only your local server?

Have you tried the `validate` steamcmd `app_update` flag?

**Comment by sunnamed434** [comment]
Its the same if I join other servers (even Vanilla without mods or plugins)

**Comment by sunnamed434** [comment]
Fixed after reinstalling unturned again

**Comment by parys0** [comment]
hey i have same problem you just reinstaled unturned ?

**Comment by sunnamed434** [comment]
> hey i have same problem you just reinstaled unturned ?

Hey, I also deleted the whole Unturned directory: `Steam\steamapps\common\Unturned`, and after that I deleted the Unturned via steam

**Comment by parys0** [comment]
thanks it actually worked

**Comment by sunnamed434** [comment]
np :wink:
