### ISSUE TITLE
Menu message for workshop legal agreement

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4159]
https://steamcommunity.com/workshop/workshoplegalagreement/

Seems like there's some new (?) requirement to accept this to upload to the workshop. In-game when you haven't accepted it just says Failed to Submit but in log it says 'Failed to create item because you need to accept the workshop legal agreement'. Would probably be best to add a new message as I've seen quite a few people ask about it recently.

**Comment by MoltonMontro** [comment]
> Seems like there's some new (?) requirement to accept this to upload to the workshop.

This isn't a new requirement – you just have to re-accept it every time Steam updates the agreement.

**Comment by DanielWillett** [comment]
Ah that makes sense.

**Comment by Gamingtoday093** [comment]
Indeed it has always been the case, although I do agree with improving the error to be a more descriptive if thats possible

**Comment by SDGNelson** [comment]
Relatively recently (last few years I think) they added `m_bUserNeedsToAcceptWorkshopLegalAgreement` to the create/update item callbacks which I should update the game to check. Oddly their documentation still says that if you create an item without signing the agreement it should just be hidden.

**Comment by SDGNelson** [comment]
For the next update I've added an error message specifically for the legal agreement case as well as an error message with the Steam error code.

I'm not sure what I was thinking about `m_bUserNeedsToAcceptWorkshopLegalAgreement` - that's been around for many years. Maybe I thought they added something to the SDK to check whether the agreement needs to be accepted *before* submitting but that doesn't seem to be the case either (though that would be nice).
