### ISSUE TITLE
Workshop Items fail to install sometimes

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#416]
> NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Provider.onDedicatedUGCInstalled ()
SDG.Unturned.DedicatedUGC.triggerInstalled ()
SDG.Unturned.DedicatedUGC.installNextItem ()
SDG.Unturned.DedicatedUGC.onItemDownloaded (DownloadItemResult_t callback)
Steamworks.Callback1[Steamworks.DownloadItemResult_t].OnRunCallback (IntPtr thisptr, IntPtr pvParam)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback1:OnRunCallback(IntPtr, IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.SteamworksProvider.SteamworksProvider:update()
SDG.Unturned.Provider:Update()
NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.LevelSavedata.fileExists (System.String path)
SDG.Unturned.GroupManager.load ()
SDG.Unturned.GroupManager.onLevelLoaded (Int32 level)
SDG.Unturned.Level.onSceneLoaded (Scene scene, LoadSceneMode mode)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (Scene scene, LoadSceneMode mode)

Maybe it should include more information about the item that fails

**Comment by SDGNelson** [comment]
Looks like two exceptions, one when starting up the server after installing UGC and another when loading groups without a level loaded. Fixed the second one, but unfortunately the cause of the first one is unclear and I'm unable to replicate. If you have any repro steps it should be fixable of course.

**Comment by Trojaner** [comment]
Is it possible to do try-catch and at least show the item ID?

**Comment by SDGNelson** [comment]
It's not caused by any specific item (failed item installs do log which item and why). While not well named, onDedicatedUGCInstalled is when the server begins starting up after all UGC prerequisites are ready.
