### ISSUE TITLE
DOS end of line character causing chat overlap.

### ISSUE THREAD

**Issue by Gorge823** [SmartlyDressedGames/Unturned-3.x-Community#4161]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109441902/46ac8a17-533a-4f9e-834e-bb2b84f77eb0

Not a problem in most text editors due the hiding in the DOS end of line characters, but in an editor like VIM I am able to copy them. They cause the error shown in the video above. They're hidden in my VIM, but you can see the text space after the line i'm copying.

**Comment by SDGNelson** [comment]
Interesting find, but this would be an issue with the underlying text field (IMGUI, uGUI, or UITK) since they are set to single line. If you submit it to the server it should be discarded because it contains a linebreak.
