### ISSUE TITLE
Texture errors - Multiple Workshop skins

### ISSUE THREAD

**Issue by OyamatCH** [SmartlyDressedGames/Unturned-3.x-Community#4163]
I've noticed that some skins have texture errors, parts of the skins either go full black or get darker.

- Supercharged Shadowstalker
- Air Raider Augewehr
- Bodycount Nightraider
- Bounty-Hunter Ace

The Accelerated Force Determinator also had the same issue when I was looking around but it seems to have stopped by itself.

(In the case of the Air Raider, Bodycount and Bounty-Hunter, the spots went from full black to simply darker but still different from the image used for the Steam inventory.)

![supercharged_shadowstalker_error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/148770499/73f69a55-8000-4736-943a-31cc033c6165)
![bodycount_nightraider_error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/148770499/22cb4615-d849-41d7-91cc-32ea5ec2de16)
![bounty_hunter_ace_error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/148770499/98fcdb43-3ad5-4c2a-b8eb-1eb315372c99)
![air_raider_augewehr_error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/148770499/2defc083-8383-4fb8-ad56-3b3eee58c4ec)

**Comment by OyamatCH** [comment]
![augwehr_error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/148770499/8e296bad-7075-44b1-b831-7fa2d7a90230)
![determinator_error](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/148770499/45a3f10d-93e5-40c1-9487-4243d8843102)

**Comment by SDGNelson** [comment]
Thanks for these reports! I'll get them fixed for the patch.
