### ISSUE TITLE
Some servers aren't showing their lobby description

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4166]
I've been searching all morning on the server list and most of servers aren't showing their lobby descriptions, including mines

Is not a plugin related issue because I disabled Rocketmod, Openmod and uScript at same time and it was not showing neither. I tried to change some things on the texts on the server config and still nothing

For example these servers are the only ones on that list that are showing their lobby descriptions, doesn't matter if I restart the game or something like that:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/80c1810e-4b77-46dd-ba41-accb1aa9f032)

Their lobby looks like this:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/5fbdc904-2603-4973-a8fe-48f741115960)

I did also asked to my friend and he has the same issue, so there we go :P

**Comment by SDGNelson** [comment]
For me it looks like that server's description is:
```

<b><size=13><color=white>Te presentamos <color=#FFB73D>FullPlomo Semi-vanilla</color></color></size></b>

<align=left><margin=1em>Contamos con un PvP más entretenido y duradero, junto a un survival mejorado para reducir los raideos offline, incluyendo todos los siguientes cambios:

<line-height=125%><margin=2em>- Loot del mapa personalizado
- Multiplicador de loot aumentado a x1
- Clima nocturno deshabilitado
- Daño de armas nerfeadas y balanceadas
- Centinelas con munición infinita
- Horario anti-raideo nocturno de 10h
- Resistencia de las construcciones aumentado<line-height=100%><margin=0em>

<align=center><alpha=#66>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _<alpha=#FF>


<line-height=125%><b><color=#FF5D4F>Wipes: primer Viernes de cada mes</color>
Por: Rodrigo Al. y Zacho
```
Sometimes the game server "rules" data seems to fail to go through. For some players it's fine with or without a VPN. There was a report a while ago where it turned out to be related to the MTU. Maybe the server's description is larger than the MTU, or client MTU or something? A couple weeks ago I enabled jumbo packets on my network - maybe that's why I can see it?

**Comment by ItsRodrigoAl** [comment]
> For me it looks like that server's description is:
> 
> ```
> 
> <b><size=13><color=white>Te presentamos <color=#FFB73D>FullPlomo Semi-vanilla</color></color></size></b>
> 
> <align=left><margin=1em>Contamos con un PvP más entretenido y duradero, junto a un survival mejorado para reducir los raideos offline, incluyendo todos los siguientes cambios:
> 
> <line-height=125%><margin=2em>- Loot del mapa personalizado
> - Multiplicador de loot aumentado a x1
> - Clima nocturno deshabilitado
> - Daño de armas nerfeadas y balanceadas
> - Centinelas con munición infinita
> - Horario anti-raideo nocturno de 10h
> - Resistencia de las construcciones aumentado<line-height=100%><margin=0em>
> 
> <align=center><alpha=#66>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _<alpha=#FF>
> 
> 
> <line-height=125%><b><color=#FF5D4F>Wipes: primer Viernes de cada mes</color>
> Por: Rodrigo Al. y Zacho
> ```
> 
> Sometimes the game server "rules" data seems to fail to go through. For some players it's fine with or without a VPN. There was a report a while ago where it turned out to be related to the MTU. Maybe the server's description is larger than the MTU, or client MTU or something? A couple weeks ago I enabled jumbo packets on my network - maybe that's why I can see it?

Nope is not related for how long the descriptions are because I even deleted all that descriptions and I changed them to only an "A" and still it was not showing up. Any way how can I enable those jumbo packets too for testing? Or you have something else in mind?

**Comment by SDGNelson** [comment]
To clarify: jumbo packets is just an MTU of ~9000. Also, are you playing on Linux? There have generally been more reports of issues with the "rules" data with the Linux Steam client as well.

**Comment by ItsRodrigoAl** [comment]
I play on Windows but my servers are hosted on Linux machines, yep!

**Comment by Yzuuu123** [comment]
I also have the same problem with my server, when will you fix it Nelson?
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/101071673/6a21f0f8-9f8d-4f84-a4e1-1779b2fefe4e)

**Comment by SDGNelson** [comment]
Unfortunately, this is outside of our control as far as I'm aware. There was the one time this came up a few months ago where it turned out to be the discrepancy in MTU. That one's even straightforward to replicate - the Steam rules response fails with a VPN active.

**Comment by ItsRodrigoAl** [comment]
Wanted to clarify this eventually got fixed somehow. No idea what happened but now all servers seems to be showing their lobby again!

**Comment by SDGNelson** [comment]
Weird but glad to hear it fixed itself!

**Comment by sarshane** [comment]
Same problem happened, seen some servers have it too
