### ISSUE TITLE
Direct connect to LAN server shows server running on asn older version:

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4167]
As the title would suggest, running a server currently locally for some testing purposes.

Expected behaviour would suggest that connecting to it using direct connect should also work as well as just going to the LAN tab on the server, however that is not the case.

Going to the server via the LAN tab lets me connect to the server fine without any issues, this also let's me join as expected.

However using my **external** IP Address to connect after having port-forwarded seems to instead state that the server is running an outdated version, that being: `3.21.7.0`, and as expected does not let me connect to the server itself.

Checking my port forwarding settings I do not see any issues as these are the following settings I am using:
```
[game-unturned-tcp]
type = tcp
local_ip = 192.168.68.114
local_port = 27015
remote_port = 27015

[steam-unturned-tcp]
type = tcp
local_ip = 192.168.68.114
local_port = 27016
remote_port = 27016

[game-unturned-udp]
type = udp
local_ip = 192.168.68.114
local_port = 27015
remote_port = 27015

[steam-unturned-udp]
type = udp
local_ip = 192.168.68.114
local_port = 27016
remote_port = 27016
```

Help would be greatly appreciated.

**Comment by Axodouble** [comment]
Screenshot of the server in direct connect:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/62dac027-c66a-403a-82b5-79a1a4c8c2b8)

**Comment by Axodouble** [comment]
Screenshot of the server in the LAN tab:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/7a1372c9-8e67-4bf7-a9e9-3c2cb17dfadb)

**Comment by DanielWillett** [comment]
Can other people connect?

**Comment by SDGNelson** [comment]
Considering that this comes up from time to time and there seem to be issues with the server "rules" data for some players, I've now removed the default 3.21.7.0 value in the today's patch. When that feature was first added 3.21.7.0 was the currently released version.

**Comment by SDGNelson** [comment]
If none of the details were going through I might think it was a NAT Reflection issue, but the Axo's Test Server description is visible. There's also the reports of issues with it on Linux, and the reports that adjusting MTU resolved it. 😕

**Comment by Axodouble** [comment]
> If none of the details were going through I might think it was a NAT Reflection issue, but the Axo's Test Server description is visible. There's also the reports of issues with it on Linux, and the reports that adjusting MTU resolved it. 😕

I am hosting my server on a linux server, could that be the issue?
