### ISSUE TITLE
Queue Exit Group

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#4168]
I didn't test this but after looking to player leave group code, if `Timer_Leave_Group` is set players can create duplicated entries on queueExit
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/20555316/d6435931-1985-4cca-9f76-6a5a39e652bd)
I think this should have a check to see if player already requested the exit.
Player still be limited to request at every 5s but if Timer_Leave_Group is longer it will have duplicated entries for sure.

**Comment by SDGNelson** [comment]
Whoops! It looks like it was intended to check `isPlayerInGroupExitQueue`. Perhaps I will just update `requestGroupExit` to ignore the request if the player is already in the list.
