### ISSUE TITLE
Ideas for items

### ISSUE THREAD

**Issue by SurvivorCDG** [SmartlyDressedGames/Unturned-3.x-Community#417]
**Add:**
```C#
public delegate void TakeItemRequestHandler(PlayerInventory inventory, ItemDrop item, ref bool shouldAllow);

public delegate void UseItemRequestHandler(PlayerInventory inventory, Item item, ref bool shouldAllow);
```

**Fix:**
The muffler breaks when shot, when "Provider.modeConfigData.Items.Has_Durability" is "false"

**Comment by SDGNelson** [comment]
Added an event for onTakeItemRequested to the next update. Unfortunately item use and barrel durability are both locally predicted right now, so the server can't override those without having to rollback the client yet.
