### ISSUE TITLE
Gameobjects with the layer tag "Viewmodel" appear in 3rd person

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#4172]
Gameobjects with the layer tag "Viewmodel" appear in 3rd person

**Comment by GazziFX** [comment]
I don't understand what you trying to achieve but normally all gameobjects under the first person character is disabled

**Comment by SDGNelson** [comment]
The game is probably automatically changing the layer for you - trying to be helpful. What do you have in mind?

**Comment by DerEnte** [comment]
Putting a shader that's animatable so I can have a screen shake and a screen zoom effect when firing.

**Comment by SDGNelson** [comment]
I remember Dug posting that had done something like that. He might be able to share more details on how it was done.
