### ISSUE TITLE
[Linux] Mouse cursor showing in game

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#418]
Whenever I play Unturned, the cursor dooesn't get hidden/replaced by the Unturned cursor.

OS: Manjaro 17.1.12 (XFCE)

Main menu:
![screenshot_2018-09-29_17-19-09](https://user-images.githubusercontent.com/10360610/46251728-22f80300-c410-11e8-8dc4-806e324d0c2a.png)

In game:
![screenshot_2018-09-29_17-21-16](https://user-images.githubusercontent.com/10360610/46251729-22f80300-c410-11e8-8c3b-ed663d9f7cfd.png)

**Comment by SDGNelson** [comment]
Unlikely to be fixed since it's distro specific, sorry. Might be resolved if the game updates Unity versions.
