### ISSUE TITLE
In IMGUI when you click on empty place item description not close

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4181]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/74f592aa-228a-4105-9f08-eed814891a87

**Comment by SDGNelson** [comment]
Sorry but this was an intentional tradeoff to fix #4147. Clicking outside to close the selection is only supported with uGUI and UIToolkit currently. You can also press Esc to close the popup.
