### ISSUE TITLE
Lavaflow texture possibly bugged

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4182]
**REPORT:** Flodo reported that the lava at Mauna Kea, Hawaii looked darker/different.

I compared it to some older footage and it looks fairly similar, except older footage lacks these **squarish white splotches** on the texture. Maybe this is just a difference in lighting compared to years ago, or maybe these textures were messed up with the 2021 Unity upgrade as well?

I've included photos of how Lava objects and Lavaflow skins currently look.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/5fa37b3c-73b9-4cf6-a021-51a4bf965138)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/20b27a34-5773-403b-ba0f-41fb9df44d24)

**Comment by SDGNelson** [comment]
Thanks for the report! This is probably the same issue as the other metallic textures. :(

**Comment by SDGNelson** [comment]
At first I thought this was an issue with the imported textures alpha channel, but it actually seems to be something different with the way the colors were blended in the shader. 😕
