### ISSUE TITLE
Unable to join unturned online servers. (Built-in resources mismatch. Verifying game files should repair this.)

### ISSUE THREAD

**Issue by MellohiMC7** [SmartlyDressedGames/Unturned-3.x-Community#4183]
all it says when i try to load is "Built-in resources mismatch. Verifying game files should repair this." i have tried many times to fix it and watched many tutorials but none of them work so i am stuck to single player. Can anybody help me with this?

**Comment by Kubusiek3** [comment]
delete all your workshop mods and unsubscribe mods

**Comment by MellohiMC7** [comment]
that did not help at all, just made me get rid of all my wallpapers

**Comment by sunnamed434** [comment]
I also had the same problem, check similar [issue and the solution here](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4158#issuecomment-1779461283)

**Comment by MellohiMC7** [comment]
After me trying everything 3 times it finally worked. Thank You!
