### ISSUE TITLE
Render Glitch , Door Glitch

### ISSUE THREAD

**Issue by Kubusiek3** [SmartlyDressedGames/Unturned-3.x-Community#4184]
Hello you can abuse render to see through map it works in alot of places specially in tunnels underground, you can sit in bugged doors and suprise your enemy without opening the door. 

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/462f1a87-025a-4438-ab72-587172bb49c1

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/dd857345-c741-4c1a-bd52-f92874caff03

**Comment by Jdance-Media** [comment]
This appears to be on a curated map. The issue regarding the gate is a problem with the object itself and should be fixed by the curated map developer. As for the berets that you have been asking for, from what I'm aware Nelson doesn't hand those out anymore.
