### ISSUE TITLE
Water height transparent sort flag for barricades/items

### ISSUE THREAD

**Issue by Letgalian** [SmartlyDressedGames/Unturned-3.x-Community#419]
There is an issue with transparent materials being rendered throug the "depth fog" when below water. It can be fixed by using `Use_Water_Height_Transparent_Sort` flag for objects but it doesn't seem to work for items, such as barricades. As far as I can tell, the in game glass barricades have the fix hard-coded in them, so modders cannot apply it to their content. Is this something that could get fixed or am I just missing something?

**Comment by SDGNelson** [comment]
You're right! Sorry about that - for the next update I've added support for that flag to barricades, and the vanilla glass won't be hard-coded anymore.

**Comment by aviadmini** [comment]
What about vehicles?

**Comment by SDGNelson** [comment]
@aviadmini transparent vehicle?

**Comment by aviadmini** [comment]
no, the vehicle is ok but when it's rainy the vehicle looks like there's no rain, even from distance (I assume it doesn't render fog or some sort of that)
https://cdn.discordapp.com/attachments/358307882480959488/498533954106949632/5C38832A5F806EDED38D61CCD8ED06B98F359031.png
https://cdn.discordapp.com/attachments/358307882480959488/498535497401106458/unknown.png

**Comment by SDGNelson** [comment]
Looks like it's using a shader that doesn't apply fog.

**Comment by aviadmini** [comment]
What do you have to use to apply fog when importing from Blender

**Comment by SDGNelson** [comment]
Ah, if you're using the unity 5 standard shader on your imported material you should be fine then. I'd suggest looking at the Graphics Settings -> Shader Stripping fog modes, it should be manual checked.
