### ISSUE TITLE
Russia Mili Tunnel Glitch. Deadzone silo exit wallhack door

### ISSUE THREAD

**Issue by Kubusiek3** [SmartlyDressedGames/Unturned-3.x-Community#4192]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/dca5a6eb-4283-4497-8721-752243a65a74

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/45b90f12-7ab4-4bed-88bb-9d10361ae4cd

Tunnel glitch very hard to recreate but possible

**Comment by MoltonMontro** [comment]
To clarify, did you do this on single-player?

**Comment by Kubusiek3** [comment]
tunnel yes, checking this wh doors no
