### ISSUE TITLE
Equippable prefab replacement not affecting inventory viewmodel

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4197]
As it seems, the viewmodel rendered when you open the inventory still only uses the Item prefab, ignoring any EquipablePrefab specified. Here you can see it with my item: While equippable prefab is kept unchanged from the animation file, model is moved and rotated in the Item prefab, for better placement on the character's back when unequipped. This causes the inventory viewmodel to hold it the wrong way.
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/d08482d8-2136-4881-a049-454ff8098efd)
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/0ac2f2a6-6600-4128-bf2f-8ea2b59441cc)

**Comment by DerpyHoowes** [comment]
Update: I've reequipped it, and it became normal. Im not sure what could be the cause of the issue, but most likely it sometimes does replace the equippable model, and sometimes doesnt, for some bizzare reason.

**Comment by SDGNelson** [comment]
I double-checked and in the code it does use the same prefab for the inventory preview, 3rd-person, and 1st-person views. Are you able to get it to happen again? If so, is there an exception or something in the Client.log file?

**Comment by DerpyHoowes** [comment]
It did happen several times in different game sessions to me, but now I've been unable to replicate it on purpose to check the logs.

**Comment by SDGNelson** [comment]
Will leave open in the meantime in case it pops up again in the next couple weeks. 🤷‍♂️

**Comment by DerpyHoowes** [comment]
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/d83f0b22-a5ff-4137-8d5f-2aa525bb5e30)
It reoccured again while I was playing on a server, but Im not sure if you will be able to find the line with so many errors relating to mods installed on the server.
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13299918/Client.log)

**Comment by SDGNelson** [comment]
Ah, looking back at the code again I think the problem might be when the gun's "state" updates like changing attachments. Messy related code 😦 but easy fix!
