### ISSUE TITLE
Can_Be_Locked false vehicles getting locked when rewarded by NPCs

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4198]
Apparently when you get a vehicle as a reward, it gets locked even if by default you're unable to lock it. It may be up for discussion whether it should be fixed our kept for the safety from other players stealing your vehicles, but I guess if the mod developer thought that the vehicle shouldn't be lockable, it shouldn't be locked on spawn either.

And a little suggestion while we're on the topic of locking spawned vehicles: Perhaps vehicles spawned by barricade spawners should also be locked.

**Comment by SDGNelson** [comment]
Thanks for the report. Will fix for the next update!
