### ISSUE TITLE
I thinks it's little bug in your code (NPCItemCondition)

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4200]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/bac2d0ce-6e71-46ef-a366-114c48f28992)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/1c6c291a-fc11-4c0a-87f0-8a2e08ba7629)

formatCondition method shows the number of items, not their amount.
But isConditionMet check amount normally than count.
Just for example: I want to receive from the player item with 132/250 amount, but quest show me what i have just 1 item not the 132.
Or i have quest with 750 amount of item with 14234 id (Mod item "bricks" with amount more than 1), and if i have 2 items with this id:
first item 140/250, second item 245/250, ui show me what i have 2/750, but the expected behavior is 140 + 245 =  385/750.
Please fix this problem. ❤️

**Comment by SDGNelson** [comment]
Thanks for the report. You're right: IsConditionMet and ApplyCondition are counting the amount but the UI is not. Will fix for the next update.
