### ISSUE TITLE
I think it's bug too NPCItemReward

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4201]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/ab2581d2-18d0-46c2-81fe-e9c337cb1331)
Replace "amount" to "count"
Add Amount
Add Quality

Just like that:

Reward_0_Type Item
Reward_0_ID 19055
Reward_0_Amount 55
Reward_0_Count 2
Reward_0_Quality 100

It's be so cool

**Comment by SDGNelson** [comment]
For the meantime this is working as intended. In vanilla Amount is only really used for ammo. If/when I rewrite some of the item code then Amount would be more widely supported e.g., for stacking.
