### ISSUE TITLE
SERVER problems, no clue what is going wrong.

### ISSUE THREAD

**Issue by cosmickitteh** [SmartlyDressedGames/Unturned-3.x-Community#4204]
my dedicated server is up and going, i can execute commands and everything, but i cannot connect to it through the server list or the direct connect, i tried both ports and both the external and internal ip, nothing.
i have no idea what has gone wrong, if you need my cfg file or anything, ask and i will provide.
i am running the server on windows 10, not using steamCMD.
the server is an internet server and not a lan server.
the port forwarding is fine, i have reset my router whenever i changed the port forwarding rules.
the ports im using are 27015 and 27017.
any help would be greatly appreciated.
thank you!

**Comment by DanielWillett** [comment]
Make sure you have a Login_Token set up in the config. https://steamcommunity.com/dev/managegameservers go here to make one.

**Comment by DanielWillett** [comment]
Usually the two ports are sequential... have you tried using two next to each other?

Also post your log from U3DS/Logs/Server_\<Server id\>.log.

**Comment by SDGNelson** [comment]
Closing, but if you follow-up I will re-open.
