### ISSUE TITLE
Issues at town on Yukon

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4206]
This one is ok
![2023-11-14_07-53-47](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/d4b66f81-ed75-486a-a16e-567d5f4ff188)

But this one is floating, if I'm not wrong for 0,25 or 0,50px
![2023-11-14_07-54-17](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/af2e048a-7620-48d2-8f56-eadc5f60fc09)

Also seems like dirt below those is really off-side? is moved way more to left than right
![2023-11-14_07-55-53](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/9b1e43a8-5eb3-4ed1-938e-d8b63d30fb89)

pd: pls nelson give some love to yukon 😭 is a waste that an official medium snow map is forgotten like this because it have almost nothing interesting to do/is really empty

**Comment by ItsRodrigoAl** [comment]
something is missing...

![2023-11-16_04-11-48_NoUI](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/fd56ca6a-c1cc-4ee3-b3b7-7faa24faace6)

**Comment by MoltonMontro** [comment]
> something is missing...

These have never had any sort of robes/cables between them, if that's what the image is trying to show.

**Comment by ItsRodrigoAl** [comment]
> > something is missing...
> 
> These have never had any sort of robes/cables between them, if that's what the image is trying to show.

still something is missing...

ok out of jokes, even if these never had cables, it shouldn't be good if they get ones? c'mon, floating seats? there could be even just a stretched 2D .PNG file to simule a cable

**Comment by Jdance-Media** [comment]
> ok out of jokes, even if these never had cables, it shouldn't be good if they get ones? c'mon, floating seats? there could be even just a stretched 2D .PNG file to simule a cable

Would have to agree with this one. If not mistaken there was some interest in making structures collapse if they have no supports. Having the ski-lift cars floating goes against this ideal. I also think that some people don't know what ski-lifts are, so having the cables would better show off their purpose (since they mostly exist in snowy regions that have ski-resorts). May be a poor assumption tho.

**Comment by MoltonMontro** [comment]
> If not mistaken there was some interest in making structures collapse if they have no supports

This might be referencing a comment made about skybases, or maybe it's referencing an old comment about destructible objects? I'm not super sure.

Personally, I agree that ropes/cables between ski lifts, telephone/electrical poles, etc. would make sense graphically. Reminds me of this very old blog post, https://blog.smartlydressedgames.com/rainwind-experiments-01/.

**Comment by SDGNelson** [comment]
Really minor but I've adjusted the dirt and vertical positioning for the next update.
