### ISSUE TITLE
 Very annoying problem on my server (Loading barricades and structures)

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4207]
I have tried to fix it by load structures and barricades save on vanilla map.
I have tried test it on server without plugins.
And nothing was successful.
I no longer know how to solve this problem, so i ask you for help.
In the video (turn the sound on) i tried to talk about this problem. (Sorry for my bad english)🤪
IMPORTANT: (Maybe this info help you) I tried to move part of the base to another region with Shift + F6, and wood structures when i back to this place appeared after 1 minute.
[Save of level with this base](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13359907/Hehe.zip)
[Video of this bug](https://youtu.be/jZG31XH5B74)
https://steamcommunity.com/sharedfiles/filedetails/?id=2933845672 Workshop mod with these structures and barricades.
Map Config.json: ![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/76855ce9-519f-4453-8872-4e99c9943d9b)
Map type: large
Map workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2989920124
Place with this fully bugged base:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/4ac62ff9-be5f-4f2c-8178-8b755ed805ac)

**Comment by ItsRodrigoAl** [comment]
But you're not saying what's going on. You tried to fix **what?** what's happening? what's the issue?

**Comment by QERT2002** [comment]
> But you're not saying what's going on. You tried to fix **what?** what's happening? what's the issue?

Some of structures and barricades not load at all, some structures loaded so slow, in the video you can see it.

**Comment by DanielWillett** [comment]
What I suspect is happening here is the steamworks buffer is filling up. With my map editor server module ive been working on I attempted to send the level through a steam server on join, but I ended up having to space the data out into packets of around 55000 or so bytes to stay under the minimum which appears to be 65535 bytes, otherwise only a little bit of it actually gets sent as it doesn't seem like steamworks can handle packets that big. Even spacing out the messages the way you did doesn't seem to change much because they're still being queued by steam networking at the same time.

Perhaps you could try a few things to lower the byte count of region messages:
1. Store guids in a index at the beginning of each packet and only use their indexes so repeated GUIDs only take up one or two bytes instead of 16. (You may have to investigate the performance of a static dictionary here as your index but I think it would be fine)
2. Only send the 32 bit ID (AccountID_t) of owners and groups and reconstruct it client-side. More details here: https://developer.valvesoftware.com/wiki/SteamID
3. You'd have definately have to do some trial and error with this to see if it's viable but try lowering the bit count of the positions after first subtracting the coordinates of the region's lower corner so the precision loss doesn't affect it as much.

### Shameless api request while im at it

If you do end up messing with this it would be very nice to have an event to modify barricade and structure properties and visibilities as they're being sent.

I know this sounds useless from your perspective but it makes it so much easier and more future-proof to do stuff like changing text on signs per player, making virtual rooms that only specific players can see, and many more neat effects.


Example:
```cs
delegate void BarricadeSending(SteamPlayer client, RegionCoord region, BarricadeDrop drop, ref Vector3 position, ref Vector3 rotation, ref bool isVisible, ref byte health, ref ulong owner, ref ulong group, ref byte[] state);

// please dont pass ITransportConnection to this as we'd have to loop through each player for each barricade.
delegate void StructureSending(SteamPlayer client, RegionCoord region, StructureDrop drop, ref Vector3 position, ref Vector3 rotation, ref bool isVisible, ref byte health, ref ulong owner, ref ulong group);

void SendRegion(...)
{
// ...
SendMultipleBarricades(writer =>
{
   RegionCoord region = new RegionCoord(x, y);
   // write region data
   foreach (barricadeDrop /* etc */)
   {
      BarricadeData barricadeData = barricadeDrop.serverSideData;
      Barricade barricade = barricadeDrop.barricade.state;

      byte health = (byte)Mathf.RoundToInt(barricade.health / (float)barricade.asset.health * 100f));

      Vector3 position = barricadeData.point;
      Vector3 rotation = barricadeDrop.model.rotation.eulerAngles;

      ulong owner = barricadeData.owner, group = barricadeData.group;

      byte[] state = barricade.state;

      if (barricade.interactable is IClientSideStateInteractable interactable)
      {
          // adding an interface here would really clean this up (if you do plz dont make it internal)
          state = interactable.GetClientsideState();
      }
      bool isVisible = true;
      OnBarricadeSending?.Invoke(client, region, barricadeDrop, ref position, ref rotation, ref isVisible, ref health, ref owner, ref group, ref state);

      float angleX = (byte) (Mathf.RoundToInt(rotation.x / 2f) * 2f),
            angleY = (byte) (Mathf.RoundToInt(rotation.y / 2f) * 2f),
            angleZ = (byte) (Mathf.RoundToInt(rotation.z / 2f) * 2f);

      // write barricade data
   }
   // ...
}
```

**Comment by DanielWillett** [comment]
@QERT2002 This will destroy your ping but try putting `-NetTransport SystemSockets` in your server's launch options and see if anything changes.

**Comment by QERT2002** [comment]
> @QERT2002 This will destroy your ping but try putting `-NetTransport SystemSockets` in your server's launch options and see if anything changes.

Спасибо, сейчас попробую

**Comment by QERT2002** [comment]
> @QERT2002 This will destroy your ping but try putting `-NetTransport SystemSockets` in your server's launch options and see if anything changes.

Doesn't connect to the server.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/fd81cfb8-11bd-47fe-a691-9b82def4d126)

**Comment by DanielWillett** [comment]
Works for me on a local server with these launch options
`-batchmode -nographics -NetTransport SystemSockets +insecureserver/TestServer`

**Comment by QERT2002** [comment]
> Works for me on a local server with these launch options `-batchmode -nographics -NetTransport SystemSockets +insecureserver/TestServer`
> 
> Edit: secureserver works as well

One sec, try on local server.

**Comment by DanielWillett** [comment]
I tested it on system sockets and steam networking (the default), steam networking looks exactly like your video (even on a local server) and system sockets appears to fully replicate.

### After structures fully loaded

SNS:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/5e7ae1ca-5430-4e0a-8492-5e26ff84f990)

System sockets: (I know this looks like some are missing but I believe they're supposed to be since there are no collision issues)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/657440cb-c533-46e7-8110-7790f370d00c)

**Comment by QERT2002** [comment]
> @QERT2002 This will destroy your ping but try putting `-NetTransport SystemSockets` in your server's launch options and see if anything changes.

Very slowly, but ALL barricades and structures were fully loaded.
It took about 20 seconds.

**Comment by DanielWillett** [comment]
Also seems to be unrelated but I believe one of your modded sentry's is missing an `Aim` object in unity, probably this one
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/fa09070c-6af4-408e-8ec6-497782987f6d)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/3a8c42cf-11fc-4da2-8c68-0ead9b4e2b9c)

InteractableSentry.Update:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/09768065-0b22-4fab-93e8-23a536f017cb)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/e4a346f5-c3b0-4225-8aa6-691d252d9924)

**Comment by QERT2002** [comment]
> Also seems to be unrelated but I believe one of your modded sentry's is missing an `Aim` object in unity, probably this one ![image](https://user-images.githubusercontent.com/12886600/283018979-fa09070c-6af4-408e-8ec6-497782987f6d.png)
> 
> ![image](https://user-images.githubusercontent.com/12886600/283018881-3a8c42cf-11fc-4da2-8c68-0ead9b4e2b9c.png)
> 
> InteractableSentry.Update: ![image](https://user-images.githubusercontent.com/12886600/283019130-09768065-0b22-4fab-93e8-23a536f017cb.png)
> 
> ![image](https://user-images.githubusercontent.com/12886600/283019106-e4a346f5-c3b0-4225-8aa6-691d252d9924.png)

This is by design, it is disabled on the server side in the Update -> InteractableSentry patch

**Comment by DanielWillett** [comment]
> What I suspect is happening here is the steamworks buffer is filling up. With my map editor server module ive been working on I attempted to send the level through a steam server on join, but I ended up having to space the data out into packets every 0.05 or 0.1 seconds (depends on ping i think) of around 55000 or so bytes to stay under the minimum which appears to be 65535 bytes, otherwise only a little bit of it actually gets sent as it doesn't seem like steamworks can handle packets that big. Even spacing out the messages the way you did doesn't seem to change much because they're still being queued by steam networking at the same time.

Since its working on system sockets, this is very likely whats happening.

**Comment by QERT2002** [comment]
> > What I suspect is happening here is the steamworks buffer is filling up. With my map editor server module ive been working on I attempted to send the level through a steam server on join, but I ended up having to space the data out into packets every 0.05 or 0.1 seconds (depends on ping i think) of around 55000 or so bytes to stay under the minimum which appears to be 65535 bytes, otherwise only a little bit of it actually gets sent as it doesn't seem like steamworks can handle packets that big. Even spacing out the messages the way you did doesn't seem to change much because they're still being queued by steam networking at the same time.
> 
> Since its working on system sockets, this is very likely whats happening.

It’s very cool that you realized what the problem was so quickly, respect.
Now we are waiting for a solution to this problem in the normal operation of the server from Mr. Nelson.

**Comment by SDGNelson** [comment]
Thanks @DanielWillett for helping troubleshoot!

How many structures are in that region? From Daniel's analysis if it's filling up Steam's internal buffer I'm curious how many it reached.

Rewriting structure/barricade replication is on the to-do, but considering this data is already in reliable mode it seems like the most straightforward option would be to raise the sending buffer size for the meantime.

**Comment by QERT2002** [comment]
> Thanks @DanielWillett for helping troubleshoot!
> 
> How many structures are in that region? From Daniel's analysis if it's filling up Steam's internal buffer I'm curious how many it reached.
> 
> Rewriting structure/barricade replication is on the to-do, but considering this data is already in reliable mode it seems like the most straightforward option would be to raise the sending buffer size for the meantime.

I think you can download save of this map, and check, because idk how to check count of structures in single region.

**Comment by Jdance-Media** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/55394007-c4ec-4fda-b582-c75f8a28776a)
This is what I got for drop counts. Grabbed the region I was in by passing my player transform position into the Region.tryGetCoordinate method.

**Comment by DanielWillett** [comment]
> ![image](https://user-images.githubusercontent.com/67397422/283326435-55394007-c4ec-4fda-b582-c75f8a28776a.png) This is what I got for drop counts. Grabbed the region I was in by passing my player transform position into the Region.tryGetCoordinate method.

While you have that set up can you count all regions in the radius of BarricadeManager.BARRICADE_REGIONS, which is what would get sent.
Check BarricadeManager.onRegionUpdated

**Comment by Jdance-Media** [comment]
> While you have that set up can you count all regions in the radius of BarricadeManager.BARRICADE_REGIONS, which is what would get sent. Check BarricadeManager.onRegionUpdated

I'll get a permanent implementation done for it either later today or tomorrow to fully debug all of the placables.

**Comment by DanielWillett** [comment]
13k structures is... a lot

**Comment by SDGNelson** [comment]
For the next update I've added a command-line option `-SNS_SendBufferSize=#` measured in bytes. If set, it overrides `k_ESteamNetworkingConfig_SendBufferSize`. The default is `524288`.

**Comment by SDGNelson** [comment]
If you raise the send buffer size now does it synchronize all of the items?

**Comment by SDGNelson** [comment]
Closing but feel free to comment and I'll re-open.
