### ISSUE TITLE
Issue with modded weapons damage

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#421]
There is some bug with modded weapons. If I set weapon damage to 150~ + skull multiplier (1.2) it then sometimes won't kill undressed players with one hit. It looks like there is some damage cap and if you go above that cap - weapon will stop working properly.

Also, one suggestion: is it possible to add clothing config option for explosive damage resistance? (bomb suit :D)

**Comment by aviadmini** [comment]
Does it do any damage to them? 
P.S. better open another issue for explosive damage resistance

**Comment by SDGNelson** [comment]
It's an integer overflow problem, stupid on young Nelson's part. I hadn't gone through to fix it before but I will for the next update.

Bomb suit is a cool idea. Depending how many changes it requires I might get it in for the update. :)
