### ISSUE TITLE
Character Outline/Blur can be seen through objects and buildings. 

### ISSUE THREAD

**Issue by Lickkx** [SmartlyDressedGames/Unturned-3.x-Community#4211]
I was in an Unturned server pvping when I discovered this issue. 

You are able to see a players outline through tents, walls, etc. It is harder to see the outline however if the wall you're looking at them through is one solid color. You are able to see Zombies, Players, and even Animals through walls. The blur is slightly better when up close and far away from the player. You can sort of compare it to an ESP however it isn't. My guess is Anti-Aliasing may have something to do with the issue or it can be a Draw Distance issue.

I attached a video showing more about the issue and how Player-Blur works. 
If anymore help is needed I can provide. 

Video: https://drive.google.com/file/d/1jKZj-X0oSfAK7lvWhce63KYWV2sPYCq4/view?usp=sharing

**Comment by DanielWillett** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3674

**Comment by SDGNelson** [comment]
Unfortunately yes as DanielWillet mentioned. We had to revert the post-processing package after the most recent engine update because of a different, worse bug with AA where the transparent fov gets stuck.
