### ISSUE TITLE
trees under frozen ocean in yukon

### ISSUE THREAD

**Issue by Prosperity182** [SmartlyDressedGames/Unturned-3.x-Community#4216]
there is a large quantity of trees under the map located below the ice in yukon

**Comment by Prosperity182** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/151689551/9571010f-a0e5-4b6a-89e3-d1074be07a94)

**Comment by sunnamed434** [comment]
What about adding a button in edtior to remove all trees under ground?

**Comment by Jdance-Media** [comment]
> What about adding a button in edtior to remove all trees under ground?

There could be unintended consequences. There are probably times when people want trees/foliage underground. The trees underground issue doesn't affect anyone too much and doesn't happen insanely often either.

**Comment by GazziFX** [comment]
> Those trees are accessible in Summer when the snow melts and the water level falls. 😄 

I can't wait for it to happen
