### ISSUE TITLE
[preview] Allow admins to place freeform buildables.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4217]
Title pretty much says it all

**Comment by SDGNelson** [comment]
Maybe placeable but not craftable?

**Comment by DanielWillett** [comment]
Yeah sounds good ig. Just kind of inconvenient to have to rely on plugins to place those as admins.

**Comment by SDGNelson** [comment]
As in, inconvenient to spawn them in? The point is that freeform buildables are no longer available by default.

**Comment by DanielWillett** [comment]
Like just to be able to place them like for a safezone or something, unless I missed something it looked like there wasn't any logic to let admins place them.

**Comment by SDGNelson** [comment]
Added for the update! :)
