### ISSUE TITLE
(Preview branch) New night vision brightness not applying with Use_Skybox_Ambience turned on

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4218]
Use_Skybox_Ambience = false
![2023-11-21_21-11-24](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/6cee267e-a6d9-41c9-88c4-543e6d8c1d54)

Use_Skybox_Ambience = true
![2023-11-21_21-05-19](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/3eb2c118-b0f3-4cb2-a81a-d2777225dafa)

**Comment by SDGNelson** [comment]
Thanks for the report, but this is because the sky wasn't brightened, only the ambient lighting. I think keeping the sky dark helps retain the nighttime feel, and Use_Skybox_Ambience is only accessible through manually editing a file.

**Comment by GazziFX** [comment]
Nelson, can you remove it completely?
https://forum.smartlydressedgames.com/t/use-skybox-ambience-unfair-advantage/23513

**Comment by ItsRodrigoAl** [comment]
I really like how does the sky box ambience give a different look to the vanilla game because it makes it be more blue-ish instead of yellow, so maps like Yukon looks **really** good, however yes, what Gazzi posted is true, it should be disabled (even P9 agreed on that forum post, and all his videos are with this option turned on)

**Comment by SDGNelson** [comment]
Yes maybe it should be removed. I probably won't do it for this update, however.
