### ISSUE TITLE
Blade ID 0  being forced upon any Melee weapon

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4219]
Probably not a bug, but rather a way to avoid adding Blade_ID_0 0 to every melee weapon back when they were added, but it causes potential problems to modded tools.

If it's getting forced on melee weapons by default, it's weird that vanilla Pickaxe and Jackhammer have BladeID 0 specifically mentioned in their asset.

Would be nice to have some tag to disable it, if the tool is only meant to damage the kind of resources that you specified, and not the vanilla trees.

Example: I made a resource and a tool for it. The resource has lots of HP and is invulnerable to explosions, to insure that it won't be destroyed by occasional or purposeful explosions/gunfire. It is vital for me that this resource can only be destroyed by the tool I made. Since I can only block damage from low caliber weapons and explosions, but not high caliber weapons with Invulnerable tag, I made it have lots of HP, and the tool I made has very high resource damage accordingly. As a side effect, this tool chops trees in 1-2 strokes, and I dont want that.

**Comment by SDGNelson** [comment]
Trees and weapons both default to BladeID 0, but if you specify any BladeID(s) the default zero is not added. Trees also have `Vulnerable_To_All_Melee_Weapons` which defaults to false. If you give your custom melee weapon a blade ID it won't be able to damage default trees - I'm not sure I understand your issue?

**Comment by DerpyHoowes** [comment]
Well, see for yourself: no BladeID 0 specified, yet in the game it still damages trees.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/25edd457-298e-4ecd-91dd-94446ba9e945)

**Comment by DanielWillett** [comment]
Blade ID max is 255

**Comment by SDGNelson** [comment]
Thanks @DanielWillett, it looks like that is the issue here.
