### ISSUE TITLE
[Linux] Can't change attachments on weapons

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#422]
When holding C (or the "customize weapon button") it only lets you change your face.

I doubt this one is distro-specific. :)

![bug](https://user-images.githubusercontent.com/10360610/46567678-935cc380-c8eb-11e8-9f52-d045ec91420f.png)

![bug1](https://user-images.githubusercontent.com/10360610/46567679-98217780-c8eb-11e8-9861-f34e635bf16c.png)

These work fine though.

**Comment by aviadmini** [comment]
Isn't T for attachments?

**Comment by SDGNelson** [comment]
I believe @aviadmini is right that you're opening the emotes menu instead, and when you don't have an item equipped you can perform gestures.

**Comment by Johnanater** [comment]
I must have it binded to the same button on Windows... oops
