### ISSUE TITLE
Odd Mannequin Behaviours on Vehicles

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4229]
Mannequins seem to work differently based on where the mannequin is placed on the vehicle? 
Confirmed on singleplayer, multiplayer, vanilla and modded vehicles. 

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/76009497-c0b1-4de6-964c-510c31f03836

**Comment by SDGNelson** [comment]
Thanks for the report! That's weird to say the least. I wonder if it thinks the pose change is blocked by another player.

**Comment by SDGNelson** [comment]
Doors have a similar check for overlaps, but ignore vehicles when placed on one. Mannequins weren't ignoring vehicles when placed on one, so it was getting blocked by the vehicle colliders. :P
