### ISSUE TITLE
Huge FPS drop when player equips modded gun with left-handed character

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#423]
I am not sure if its because something I forget to do while modding gun (probably it has something to do with exporting model from blender) or thats unturned problem itself but when some player with left-handed character takes a gun FPS drops for all players on server (from 300+ to 5~ when equiped and 40~ while holding it on back) or may even crash whole server.

If character is right-handed - there is absolutely no FPS drop at all

Unity version: 5.5.6

**Comment by SDGNelson** [comment]
Could you post the output_log.txt file from Unturned/Unturned_Data after experiencing the FPS drop please? I'll take a look and see if it says anything suspicious.

**Comment by baranmod** [comment]
Ok, I believe I found a problem. Mesh colliders somehow were added for each model, deleted them - everything seems to be solved. 

BTW, is there any way to make so weapon wouldn't be mirrored while holding in left hand? thanks

**Comment by SDGNelson** [comment]
Whoops! What sort of weapon is it? Originally they were mirrored into the left hand so that everything would work consistently.

**Comment by baranmod** [comment]
Well, mirroring ruins appearance of guns which have some text on textures. I think letting content creators disable it via config would help to deal with it. Anyways, these are pretty specific cases and I am not sure if its really necessary thing, just some thoughts. Maybe even better option would be ability to disable left-handed characters on server itself

**Comment by SDGNelson** [comment]
I experimented with this a bit today, but it has a lot of far-reaching implications e.g. the dual-render scope mirroring so I don't want to risk breaking it while my main dev focus recently has been 4. Still may get changed, but not for the next update.
