### ISSUE TITLE
Tags in nicknames

### ISSUE THREAD

**Issue by RodriiTepatzi** [SmartlyDressedGames/Unturned-3.x-Community#4233]
There is an issue relating to using tags on nicknames.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72983645/1b391d05-593a-4e6c-861e-b896c20d0bc1)

As you can see here by using the h1 tag

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72983645/60a92371-ec6b-4d42-a3f8-e4c559a1b31e)

i am getting this as result when using the chat. It can result on something very annoying.

**Comment by SDGNelson** [comment]
This is because chat supports rich text but the ordinary places names are shown do not. Changing players' names is not officially supported, sorry.
