### ISSUE TITLE
Muzzle device benefits not stopping after the device is at 0% durability

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4234]
Not sure if it was even intended, but it would sure make more sense, if when the muzzle devices such as suppressors and flash hiders stopped adding their bonuses, such as additional hip accuracy or reduced recoil once they reach 0% durability.

**Comment by SDGNelson** [comment]
You're right that it doesn't look like quality currently affects those stats. I'm not sure whether it should be considered a bug or not though. I might just leave it as-is for now. :P
