### ISSUE TITLE
Vehicle stops on server after passing 79 kph speed limit

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4236]
We have two vehicles with identical stats on our servers that use same Physics Profile and basically they freeze in place after accelerating to speed higher than 79 kph (basically reaching its speed limit, as it seems by the speed bar) and starts teleporting back and forth for a second on two, and then starts going again from 0 speed. This issue started appearing after I assigned the mentioned Physics Profile to them. In singleplayer everything is okay. What could be causing this problem? In the server logs it doesnt say anything. These vehicles are the only ones that cause problems. There are several other vehicles that go faster than these, and dont cause any problems, so most likely there is something wrong with the physics profile.

Physics profile contents:
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/df6ca8e4-1b69-42e0-8386-38285f8c9afd)

Vehicle asset:
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/2b0fe0e5-d9b9-4657-8d23-d52494b521f9)

**Comment by SDGNelson** [comment]
GazziFX's answer is correct that with the different physics settings the game's not-very-good guess of max speed is too low.
