### ISSUE TITLE
Russian Gas Station Pathfinding Issue

### ISSUE THREAD

**Issue by FluffyWabbitz** [SmartlyDressedGames/Unturned-3.x-Community#4239]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/152986234/b9da04ef-5df7-488d-aab7-181b6a9bfd3b

Zombies can't seem to path find over the windows in the gas station object.

**Comment by SDGNelson** [comment]
Thanks for the report, but unfortunately it looks like the video upload failed. Could you share a screenshot of the location please?
