### ISSUE TITLE
(In editor) Hiding nodes causes decal boxes to flicker 

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4242]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/d687f48c-8499-44c3-b8f7-5401ffaa89d1

**Comment by SDGNelson** [comment]
Thanks for the report! I'm not sure why the Nodes visibility affected it (no link between those) but updating the decals to render gizmos the same way as everything else seemed to resolve it.
