### ISSUE TITLE
Wrong wiki info about Portable Generator + suggestion for generator stats

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4243]
Portable generator
2.000 * 20 / 3.600 = 11h
2.000 * 20 / 3.600 / 60 * 100 = 18min

However, wiki says 
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/e80de99e-479a-4f8d-b5f4-71c52e2621c6)

Industrial generator:
20.000 * 5 / 3.600 = 27h
20.000 * 5 / 3.600 / 60 * 100 = 46min

Wiki says this, meaning its ok
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/57012631/49fcf302-219a-4e97-9018-f450083cd4f1)

Would be cool to have like 1 or 2 new stats for Generators so you can know: how much fuel it can have OR all the time it can be turned on with all their fuel refilled

**Comment by SDGNelson** [comment]
Yeah those should definitely be added! I'll add some lines for generators and fuel+water storage related items.
