### ISSUE TITLE
"Order by" player list button hides after quitting servers with game groups disabled 

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4244]
I've noticed this same issue https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3785 happens when leaving servers with in game groups disabled. For example, if you join to a server with groups disabled, on the player list it wont show the "Order by" button after changing to another server since there are no groups and it will order the player list by player name by default

The expected behaviour would be having the "Order by" button again after joining to a another server with groups enabled

**Comment by SDGNelson** [comment]
Thanks for the report! You're exactly right that it's the same cause as #3785. I've now applied the same fix here.
