### ISSUE TITLE
Can't render barricade on all map

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4246]
I have several barricades that I want to be visible from anywhere on the map, but from the server (even using patches), this is not possible, since the client has a lot of checks for the disabled region, please add 1 line of code to asset .dat file it was possible to specify Infinity_Render and the barricade did not turn off the gameobject when changing the region.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/813460e9-1a3d-4361-8f5a-f1f4dd84da52)

**Comment by SDGNelson** [comment]
This isn't planned or supported, sorry.
