### ISSUE TITLE
Players don't take damage from weapons while falling..

### ISSUE THREAD

**Issue by themisfitgames** [SmartlyDressedGames/Unturned-3.x-Community#425]
Hello Nelson,

A friend of mine; Enigma, wanted me to go ahead and get in contact with you as he doesn't have time to get on GitHub to post a thread about this issue, anyways to reiterate about the subject matter when falling from planes or skybases, in the midst of PVP or base raids players aren't able to take damage from other players unless they have a glider or umbrella out, and with that being noticed, Many server owners and players will find this as a disadvantage once it is noticeable and I'd like to see a fix implemented for this. As players alike we are merely trying to kill our opponents in PVP matches or as I stated in the midst of base raids. If you could please assist with this issue it would be much appreciated.

Thank you.

**Comment by SDGNelson** [comment]
Should be reverted in the next patch, it was due to over-aggressive serverside maximum player position change.
