### ISSUE TITLE
Underground post is not letting me build 

### ISSUE THREAD

**Issue by BeEmpathic** [SmartlyDressedGames/Unturned-3.x-Community#4250]
I made an underground post, and you can't remove it, because it's underground I tried to use explosives, but it's invulnerable, because it's underground.
I made it by putting floor then aiming down and putting a post on the corner.
Screen how it's looks like:
![obraz](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/62871950/355e22b6-477d-424d-a1c6-995be250959a)
Video on YouTube how I made it:
https://youtu.be/P64x-tjFyq4

**Comment by SDGNelson** [comment]
Sorry about this. There's been a few reports and I thought I had meant to add checks that a placed structure isn't slightly below ground, but it looks like it was only added to floors. I think it should be fine to test that pillars and posts are at least slightly above ground. 🤔
