### ISSUE TITLE
PSA: Changes to client/server connection messages on preview branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#4251]
Of the changes in the update, this is the one most likely to affect plugins. That being said, it should only be if the plugin was patching/injecting this code which isn't officially supported. Other changes should be backwards compatible.

The changes were to support "server codes" and "fake IP":
https://docs.smartlydressedgames.com/en/latest/servers/server-codes.html
https://docs.smartlydressedgames.com/en/latest/servers/fake-ip.html

Unturned really should have supported those sooner, but several systems relied on information from the server listing advertisement e.g. the map and camera mode. These are now retrieved from the connection messages instead, so the advertisement is no longer critical. This also means IPv6 and non-Steam network transport could become better supported in the future (not in this update yet).

**Comment by realchameleon** [comment]
I do have a question though with this option how will favoriting a server would work because the ip will change after every restart alot of servers restart very 24h for stabillity

**Comment by GazziFX** [comment]
> I do have a question though with this option how will favoriting a server would work because the ip will change after every restart alot of servers restart very 24h for stabillity

I think it would be saved by Steamid which is unique for each login token (GSLT)

**Comment by SDGNelson** [comment]
> I do have a question though with this option how will favoriting a server would work because the ip will change after every restart alot of servers restart very 24h for stabillity

I haven't personally tested this, but my guess is that GazziFX is correct that if a GSLT is set the favorite should transfer. For the meantime I'd recommend that big servers continue using public IPs just to be safe.

**Comment by KarmaWSYD** [comment]
There are seemingly some issues with transferring favorites with Fake IPs set. Earlier DiFFoZ tested whether they worked and came up with the answer of no, which I also verified. I just tested again (I'm pretty sure the preview was updated in between(?)) they seem to now at least sometimes work. There are some issues with using both a Fake IP and a real one at the same time, namely, there's seemingly a chance for the server to disappear from at least favorites if not the whole list if you first connect normally and then with a Fake IP. Sometimes, at least when using Fake IP/Server codes, (possibly as a result of mixing connection methods in the same session?) the server will just not connect you, causing a 30s timeout.

Currently, I'd stick with just public IPs for any server that can do so, as arguably using Fake IPs creates more problems than it solves for many servers, mixing use seems to come with mixed results. I haven't tested only using Fake IPs though so experiences for that might vary.

**Comment by SDGNelson** [comment]
@KarmaWSYD That's unfortunate. One of the changes in the preview patch was renaming `Experimental_Use_FakeIP` to `Use_FakeIP`, so it's possible that's why it seemed to start working if it got turned off by default again.

The ideal solution would be to have our own custom favorites list. Currently it wouldn't provide much benefit over Steam's, however, as we would need to refresh the Internet list and filter by Steam ID.

**Comment by KarmaWSYD** [comment]
I did actually notice it resetting and re-enabled Fake IP before the newer testing, so I doubt it was that.

**Comment by Paradox304** [comment]
> > I do have a question though with this option how will favoriting a server would work because the ip will change after every restart alot of servers restart very 24h for stabillity
> 
> I haven't personally tested this, but my guess is that GazziFX is correct that if a GSLT is set the favorite should transfer. For the meantime I'd recommend that big servers continue using public IPs just to be safe.

Does this also work with using real ips, sometimes machines or hosts need to be changed. Causing a change in the IP which makes the server disappear of the favourites list for everyone.

**Comment by SDGNelson** [comment]
> Edit: Given that the system does work over changing regular IPs I think there's a chance that it just takes a while for it to update to the new IP or something, at least given that it should function much in the same way... I'll certainly be doing some more testing over the weekend in an attempt to figure it out.

In that case maybe it was just a matter of time before it transferred? 🤔 

> Does this also work with using real ips, sometimes machines or hosts need to be changed. Causing a change in the IP which makes the server disappear of the favourites list for everyone. Or is this only applicable for people using fake ips for their server.

With a GSLT it can automatically transfer them if the server details change. This should happen within approximately 24 hours. (Verified in [issue #3980](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3980) thanks to CyberAndrii and joeymisfit, and on [AlliedModders](https://forums.alliedmods.net/showthread.php?p=2529549#post2529549).)
