### ISSUE TITLE
Make Flag Values Setable from Server

### ISSUE THREAD

**Issue by DerSpeedMann** [SmartlyDressedGames/Unturned-3.x-Community#4252]
Having the option to change flag values from server to client would allow for so many new options to interact with quests and npcs from plugins.

It would be a minimal addition but would have near limitless potential

This would help out our Unturnov project to use more vanilla features and extend upon them like:

- Add custom quests with advanced requirements
- Allow interactions between npcs and plugins
- Sync flag values between group members
- Change object states from server
- And much more

**Comment by GazziFX** [comment]
It already exists for a long time
