### ISSUE TITLE
Diner_0 is missing a door slot

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4254]
The inner door on Diner_0 is missing a door slot.
<img width="692" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/505c7ceb-690a-45f8-ab24-890e13c62aaf">

**Comment by SDGNelson** [comment]
Thanks for the report! I will fix this today.
