### ISSUE TITLE
Moon buggy, bugged lighting in normal conditions.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4256]
The moon buggy appears to have bugged lighting, probably happened during the last Unity upgrade.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/fccab977-831e-4fb8-a511-29fe128ce997)

**Comment by SDGNelson** [comment]
Thanks for the report! I'll get this fixed before the update.
