### ISSUE TITLE
Nightvision goggles + nightvision scope issue

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4257]
Only with Scope Quality > Off. 
With Nightvision goggles enabled, scoping in with a Nightvision scope and then toggling to third person will disable the goggles, requires two toggles to re-enable. 
Any credit should go to "10fireking" for this one 👍 

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/a815893f-b241-4281-94f5-f69dc5f9ee9e

**Comment by SDGNelson** [comment]
Thanks for the report! I'll see about getting this fixed for the next update and will credit 10fireking.
