### ISSUE TITLE
Flag Updates do not get synced to clients in some cases 

### ISSUE THREAD

**Issue by DerSpeedMann** [SmartlyDressedGames/Unturned-3.x-Community#4258]
I use the `PlayerQuests.onAnyFlagChanged` event to listen to flag changes. 

When interacting with an npc i change the value.
In the event i change the flag value in the same server tick using `player.quests.sendSetFlag(flagId, value);` it does change on the server but the client still holds the previous value (set by the npc).

It requires a one tick delay to apply properly:

```
private static IEnumerator ChangeFlagDelayedRoutine(Player player, ushort flagId, short value)
{
    yield return null;
    Logger.Log($"change flag delayed {flagId} value {value}");
    player.quests.sendSetFlag(flagId, value);
}
```

**Comment by SDGNelson** [comment]
Why are you changing it in the event? Off the top of my head what's happening here is you send your new value in the middle of the event before execution of the original flag value changed occurs and gets sent to the client.

**Comment by DerSpeedMann** [comment]
I use the flag updates as a client request to do x
When I get this request I set the flag to its cooldown value and start doing my stuff
When I am done with that I set it back to its ready state
All those changes will be reflected in npc dialogue to inform the player

Yes exactly, the problem is there is no reference passed from the `sendSetFlag ` to `setFlag` / the event called inside
I know that searching for the current flag value, before sending it would be excessive but is 100% save alternative would be to
Create a new `setFlag` function that uses a PlayerQuestFlag object which is passed from `sendSetFlag` all the way to the event
Or a ref value in `setFlag` that is updated with the PlayerQuestFlag value after the event.

Alternatively I would need to patch the `sendSetFlag` and hope this resolves my issue, but if you could give us a proper way to achieve this or know an alternative way please let me know

**Comment by SDGNelson** [comment]
For a client request to do something I would suggest using the NPC Event reward type instead. It's intended for plugins to listen for dialogue-related interactions. (There are also components for listening and broadcasting these for non-plugin uses.)
