### ISSUE TITLE
Server finder bugs/shortcomings

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4259]
1) onServerListResponded does not stop working after starting to connect to the server.
2) After each re-opening of the "Multiplayer" tab, the results of the previous search are removed and a new search for servers begins.(It's annoying to wait for the server to appear every time).
3) After you enter server name and press "enter key", nothing happens.(Expected behavior: start searching for a server by name with filters installed).

**Comment by SDGNelson** [comment]
True the server list refreshing after returning from a lobby screen is annoying. I'll change it to not refresh in that case.
