### ISSUE TITLE
Extremely minor: workshop image in menu needs some padding

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4261]
![2023-12-16_21-50-29](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/f76aeefa-6bfc-489c-aed6-4b299cf8039a)
If you zoom in close enough you can tell that the workshop image is a tad outside of the box. Perhaps it could receive the same setup as the images below it? (the update notes).

**Comment by SDGNelson** [comment]
Thanks! IIRC I didn't abstract the container padding yet so there might be some annoying reason for this. I'll see whether we can workaround it easily or not.

**Comment by SDGNelson** [comment]
As a workaround for the meantime I've implemented this specifically for uGUI.
