### ISSUE TITLE
Craft interface: Some blueprints are too long to show completely

### ISSUE THREAD

**Issue by LolinDawson** [SmartlyDressedGames/Unturned-3.x-Community#4262]
As the picture show, when some recipes require too many items or take up too much space, Blueprint's required item images and the words above each recipe don't appear completely, which can be a major reading obstacle for players.

Suggestion: Adding wheel swipes might solve this problem, so you can see all of Blueprint.
This is really important to me, other mod developers and gamers :)
![20231217162433_1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/154049881/6cbc9892-1ffe-47a0-8381-9a1636b658d3)

**Comment by DanielWillett** [comment]
maybe a hotfix could be just to remove the + signs if its too long

**Comment by SDGNelson** [comment]
Those are very wide! Crafting has been getting a lot of discussion recently so it is a good candidate for one of the next reworks. Unfortunately, we don't have a good way to fix this case (expanding width) as-is - only a few automatic layout containers are partially supported so far.

**Comment by LolinDawson** [comment]
> Those are very wide! Crafting has been getting a lot of discussion recently so it is a good candidate for one of the next reworks. Unfortunately, we don't have a good way to fix this case (expanding width) as-is - only a few automatic layout containers are partially supported so far.

I'm not sure how you can make the craft interface display items and fields, but if each recipe is an interface rather than a collection of images, I think a scrollbar is a good idea, but not all recipes need a scrollbar, you can set conditions such as more than 8 recipes to have a scrollbar.
