### ISSUE TITLE
/CopyServerCode missing from "/Help" list [Preview branch]

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4264]
Server console's /help command does not output the new **/copyservercode** command available on the preview branch.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/56936b29-987b-4939-b92d-e728336363db)

**Comment by SDGNelson** [comment]
Thanks! I was lazy with some of the recent commands because I've been meaning to rework how they are setup. Considering this is a command players will use I ought to add the appropriate help text.
