### ISSUE TITLE
NPC Interactibility on Objects.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4265]
As there seems to be the ability to add interactibilities on objects, I attempted to add NPC interactibilities to add custom dialogue on different objects to act as a narrator, however this seems to be not natively supported or seems to not work entirely, can't find anything about this on the documentation either.

**Comment by SDGNelson** [comment]
There is the `InteractableObjectQuest` but no support for dialogue on interactable objects (yet). It was on my mind during the NPC RPC rewrite earlier this year so it will likely be added at some point.
