### ISSUE TITLE
(very minor) Map issues with PEI 

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4266]
I posted a similar thread to this for Washington earlier this year.
I think most of these are terrain related that were probably caused by the terrain conversion a long time ago. 

Fences are floating near Fernwood Farm:
<img width="1074" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/d1991ca9-7631-403a-9df8-8fbf9f3dd68a">

Road is floating near Fernwood Farm: 
<img width="913" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/08b07322-ba47-4cfb-b43b-72af34955c9c">

Fences floating near Wellington Farm:
<img width="996" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/f601181d-ea85-41d5-9af0-65cdc854e407">

Terrain overlapping Lodge at Kensington Campground:
<img width="761" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/4dc71d81-d73f-4115-99ab-3c816e4b0a47">

This bench is floating at Kensington Campground:
<img width="516" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/c8a838ed-8da3-44ce-b811-aff4d37eaa3c">

Road is wonky/floating where it connect to Liberation Bridge:
<img width="695" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/8645f3c8-c8b7-45c9-9ee4-423d1e16d025">

All the exterior benches at O'Leary Prison are floating: 
<img width="1510" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/7c1ee8df-da56-498f-a92f-0e6ec85120b7">

Floating dumpster at Cafe in Alberton:
<img width="772" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/61beefe8-4d72-4a87-8d5d-63a60ac32798">

Floating fences at Wiltshire Farm:
<img width="629" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/fc1bdf7d-7958-46ab-9694-4728dbc109ef">

Pallet is floating inside Wiltshire Farm: 
<img width="780" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/27d60ef3-4d98-4962-bc2a-1da0876b3c55">

This table in the Holman shipwreck is at an odd angle + table leg is poking through the floor below: 
<img width="1003" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/ab132520-64fe-4f10-9c07-45fd7b2bdd4b">

Targets are floating Summerside Military Base: 
<img width="558" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/6b36dbaf-9101-4985-bcb6-8f33b24c1f8a">

**Comment by SDGNelson** [comment]
That is indeed a lot of minor issues. 😱 Thanks for the reports. I'll fix them probably the update _after_ this one.
