### ISSUE TITLE
Objects included with a map aren't loaded when downloaded from a server

### ISSUE THREAD

**Issue by khakers** [SmartlyDressedGames/Unturned-3.x-Community#427]
Checked by joining a server with a custom map and objects. The objects weren't visible until I left the server, reloaded assets with insert, and rejoined, where I could then see them.

**Comment by SDGNelson** [comment]
Do you have the server details I could join to check? If the assets are included with the map workshop item they should be in a Bundles folder to be found while loading the files from the server.

**Comment by khakers** [comment]
They are in the bundles folder in the map.
Server is 24.150.134.79 port: 27015

**Comment by khakers** [comment]
Here’s the workshop link incase it’s needed.
https://steamcommunity.com/sharedfiles/filedetails/?id=1536502001
The only custom object is the billboard shown in the thumbnail

**Comment by khakers** [comment]
Unfortunately it appears the server host decided to stop hosting locally so they no longer have an empty test server

**Comment by SDGNelson** [comment]
Hmm I'll close this for now then. I'm fairly confident the feature works, as when doing the recent improvements there were several server hosts providing feedback on any issues they ran into.
