### ISSUE TITLE
Sudden server problems

### ISSUE THREAD

**Issue by DoomBoi113** [SmartlyDressedGames/Unturned-3.x-Community#4270]
I hosted a server for a couple of my friends, and it was all going smoothly for a while, then suddenly my fps dropped while on the server, and i noticed that unturned is taking up 100% of my CPU ??? I play on fairly decent pc (i5 9th Gen, NVIDIA GTX 1650) and i've never had issues like this before. I tried playing other much more requiring games and they worked fine, taking up only 30% of my CPU. What the hell happened, one second everything was fine, the next my fps is down to 40 and the game and dedicated server are taking up 100% of my cpu ? Please help. When i say all was going smoothly for a while i mean i hosted many servers over the years and i've never experienced such issues till now.

**Comment by sunnamed434** [comment]
Do you have any plugins on your server?

**Comment by DoomBoi113** [comment]
> Do you have any plugins on your server?

I do not, i have however couple of workshop mods, but nothing insane, like i said i had no issues with that particular server for a while.

**Comment by GazziFX** [comment]
Can you upload logs, it can show related issues

**Comment by DoomBoi113** [comment]
> Can you upload logs, it can show related issues

What file do you need uploaded? This one?
[Server_The_Trilogy.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13744088/Server_The_Trilogy.log)

**Comment by SDGNelson** [comment]
Sorry for the trouble. I believe they were suggesting you attach your Client.log file from your Unturned/Logs folder in case there was an error getting spammed while playing on your server. If you've launched the game since then it might still be in the Client_Prev.log file.

**Comment by DoomBoi113** [comment]
> Sorry for the trouble. I believe they were suggesting you attach your Client.log file from your Unturned/Logs folder in case there was an error getting spammed while playing on your server. If you've launched the game since then it might still be in the Client_Prev.log file.
Here it is, thank you for your help!

**Comment by DoomBoi113** [comment]
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13745505/Client_Prev.log)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13745506/Client.log)

**Comment by SDGNelson** [comment]
Unfortunately (or perhaps fortunately depending on your point of view) there aren't any unusual errors.

Two types of modded content that are notorious for performance issues:
- Custom vehicles with Animator components and/or visual suspension. This is one reason I need to make visual suspension a vanilla feature sooner or later.
- Extra cameras rendering to texture. e.g., GPS overlay from above, fancy custom scope types.

Considering you mentioned the performance is usually fine, I think it would be worth trying with some of the modded content off (e.g., half off to start) and see how the performance compares. That will narrow down if it is any particular mod causing the drop.

**Comment by DoomBoi113** [comment]
You were absolutely right, i removed one mod with vehicles with animated parts and it got back to normal! Strange though, because that mod was downloaded from the start, maybe too many of those vehicles got bundled together ... Thank you so much for your help ! You made me and my buddies 
really happy!

**Comment by SDGNelson** [comment]
Glad to hear the performance was resolved! Sorry about not having those vehicles though. Hopefully some vehicle rewrites happen sooner than later. 😄

**Comment by DoomBoi113** [comment]
> Glad to hear the performance was resolved! Sorry about not having those vehicles though. Hopefully some vehicle rewrites happen sooner than later. 😄

**Comment by DoomBoi113** [comment]
I'll get over it ... i'm just glad i can host server again!
