### ISSUE TITLE
LevelInfo.resolveAsset bug

### ISSUE THREAD

**Issue by Alniroza** [SmartlyDressedGames/Unturned-3.x-Community#4273]
When you host a server using a workshop map that doesnt get found, the map will be set to the default 'PEI', if a player connects to this map and then you restart the server so its set to the one you really wanted (ex. Arid), the players will still see the recipes from PEI, even if the property to hide core is set correctly on the Bundle.

I tried deleting all map related info from Levels and Players, but this didnt work.

**Comment by SDGNelson** [comment]
To double-check: you have a custom version of the level with a Crafting Blacklist Asset and `Allow_Core_Blueprints` set to false?

**Comment by Alniroza** [comment]
I had one who used Arid Bundle, with it activated. I added the Allow_Core to this new Bundle (Arid 3.0) to test it, and didnt fix nothing.

This has happened me before with the Curated Arid too.
