### ISSUE TITLE
The map's holiday mode doesn't match the weather.

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#4276]
Recently, maps such as Washington and Russia have turned on the Christmas holiday mode. They are all covered with snow, but why is it still raining in summer?
I think this is a bit unreasonable, he should have snowed.

**Comment by SDGNelson** [comment]
Fair point. Currently the holiday overrides don't yet support changing the weather. Maybe gentle snowfall in the future. Closing because I'm not sure when/if I will get to that, however.
