### ISSUE TITLE
Server crashing after last update

### ISSUE THREAD

**Issue by TeemoCell** [SmartlyDressedGames/Unturned-3.x-Community#4277]
Removed RocketMod already once and restarted the server. Same with uScript and i also removed all Workshop mods.

Error from rocket.log: https://paste.teemocell.dev/pizedajufu
Full rocket.log: https://paste.teemocell.dev/oyedeqedex
Server_unturned.log: https://paste.teemocell.dev/yasetukuce
Server_unturned_Prev.log: https://paste.teemocell.dev/inijuvirus
Console Log View: https://paste.teemocell.dev/guneceyege

**Comment by SDGNelson** [comment]
It looks like SteamGameServer.Init is failing. Earlier in the log it mentions `steamservice.so` was not found. I also see you are using Pterodactyl. I know there were some posts in the past about issues with using Pterodactyl and not using steamcmd. I'm not personally familiar with how Pterodactyl works. Does the container have steamcmd inside?

**Comment by GazziFX** [comment]
> I'm not personally familiar with how Pterodactyl works. Does the container have steamcmd inside?

Yes, you can look at https://github.com/Trillion-Servers/unturned-egg-pterodactyl/blob/main/entrypoint.sh

**Comment by TeemoCell** [comment]
I have no idea what exactly caused the problem but i fixed it by reinstalling the server. I thought it is a problem with the latest update bec i had that problem already a few times when a update came out. The servers are running again, even with the error

``Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory``

I feel like something is being deleted when the server updates. No idea if there is a problem with Pterodactyl, Steam or the Unturned updates.

**Comment by RBMKBlaze** [comment]
> It looks like SteamGameServer.Init is failing. Earlier in the log it mentions `steamservice.so` was not found. I also see you are using Pterodactyl. I know there were some posts in the past about issues with using Pterodactyl and not using steamcmd. I'm not personally familiar with how Pterodactyl works. Does the container have steamcmd inside?

Had this happening last night, i was also using Sparked's Appollo panel (Ptero), the support team (by the logs) seems to re-ran the build in panel installer.

**Comment by SDGNelson** [comment]
Glad to hear it seems to have resolved itself! 🙂
