### ISSUE TITLE
Set the duration of the model disappearance after the vehicle explosion (modified in .dat file)

### ISSUE THREAD

**Issue by LolinDawson** [SmartlyDressedGames/Unturned-3.x-Community#4278]
I am building vehicles such as heavy machine guns (they can only be implemented with vehicles), and I have noticed that Drop_ID can be set to get the effect of heavy machine guns, but in some servers, damaged vehicles will be there for a long time.
Can you do a Properties, such as: Explosion_Time, to set the duration of the destroyed vehicle?

**Comment by SDGNelson** [comment]
It depends on the server's vehicle respawn timer currently, sorry.
