### ISSUE TITLE
Crashes unturned with unity error. Half of the players have it.

### ISSUE THREAD

**Issue by addemals** [SmartlyDressedGames/Unturned-3.x-Community#4280]
Hello developers of unturned. I'm playing on the GSRP server and starting with a recent update, it starts crashing with a unity error. Please fix it

**Comment by addemals** [comment]
Crashes unturned and not the server

**Comment by sunnamed434** [comment]
I have a similar problem on my vanilla server, once someone shutdown the server unturned crashes on my side (client-side), and the same happens for some other players

**Comment by SDGNelson** [comment]
Sorry for the trouble! If you can submit a crash report according to this article it instructs how to include some files that are helpful for determining the cause: https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash
