### ISSUE TITLE
Certain clothing articles not appearing in character inventory-

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4282]
Certain clothing articles are not appearing in the character inventory if their storage is set to 0 Width & 0 Height.

This seems to affect all pieces of clothing that by default have the ability to have storage, being;
- Shirts.
- Pants.
- Vests.
- Backpacks.

If they have their storage set to 0 Width & 0 Height, they no longer appear in the inventory ui as an equipped article of clothing, whereas their counterparts such as the hats or glasses will still appear as an equipped article of clothing, this doesn't seem to make much sense for consistency reasons, and instead if this is intended behaviour, adding in a tag to keep them invisible in the inventory ui would much be appreciated.

**Comment by SDGNelson** [comment]
This is rather hardcoded at the moment that certain clothing slots are always for storage, and others are always for non-storage. I'd like to address it as part of inventory and clothing changes to allow custom clothing slots and separate those two features from one another.

**Comment by Axodouble** [comment]
> This is rather hardcoded at the moment that certain clothing slots are always for storage, and others are always for non-storage. I'd like to address it as part of inventory and clothing changes to allow custom clothing slots and separate those two features from one another.

Either I am misunderstanding you, or you misunderstand me, but if a shirt itself has no storage assigned to it, it does not show anywhere as it being equipped, other than the physical player model.

**Comment by surv0013** [comment]
> I am misunderstanding you, or you misunderstand me

Yes, you just didn’t understand each other. This bug is at least 4 years old. In general, the essence is this: set the height and width of the shirt to 0 and put it on. There is no button in the inventory on the right to remove it, you have to click on the character on the left to do it.

**Comment by GazziFX** [comment]
> Certain clothing articles are not appearing in the character inventory if their storage is set to 0 Width & 0 Height.

Just set Width 0 and Height 1
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/43498426/ce494fd3-19b0-4f43-8da4-99e030cc9d86)

**Comment by Axodouble** [comment]
> > Certain clothing articles are not appearing in the character inventory if their storage is set to 0 Width & 0 Height.
> 
> Just set Width 0 and Height 1 ![image](https://private-user-images.githubusercontent.com/43498426/292655863-ce494fd3-19b0-4f43-8da4-99e030cc9d86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjM4MjEsIm5iZiI6MTcwMzQyMzUyMSwicGF0aCI6Ii80MzQ5ODQyNi8yOTI2NTU4NjMtY2U0OTRmZDMtMTliMC00ZjQzLThkYTQtOTllMDMwY2M5ZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEzMTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxM2Q1ZmZhMDFlNzEwMjUwNzcxMTM1ZjU0MWY2M2EyMzdjYjJmNmE5YjM0MjMzYmJhMGE0MDYyMzJkNGQ0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-zcmz19Zux7UgqWe8w5MDNH-7v7R6XwLawGiPcNEkU)

Workarounds are nice, but a fix is better.
