### ISSUE TITLE
Death and transfer cannot trigger the "OnPlayerExit" event for "CollisionEventHook".

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#4285]

**Comment by SDGNelson** [comment]
True. I used to tend not to trust the physics system. It would be useful to notify the event components of these events.

**Comment by prank0079** [comment]
If you can, it is recommended to recreate a mod hook.
The fix may break the mod I made earlier.

**Comment by SDGNelson** [comment]
So to clarify: Changing the behavior of CollisionEventHook to take into account player death and teleport would break your existing content?

**Comment by prank0079** [comment]
If you change the trigger mode that depends on the Tag, it will break the mod I did before.
Most of the time when I use Collision Event hooks, I don't need the actual player to enter.
