### ISSUE TITLE
Crash issue for specific users on the game server

### ISSUE THREAD

**Issue by Blackwolf0726** [SmartlyDressedGames/Unturned-3.x-Community#4287]
```
[2023-12-25 15:20:51] SDG.Unturned.PlayerMovement.updateRegionAndBound () (at <4536c5529add4d67816deff02f8b9c51>:0)
SDG.Unturned.PlayerMovement.simulate (System.UInt32 simulation, System.Int32 recov, System.Int32 input_x, System.Int32 input_y, System.Single look_x, System.Single look_y, System.Boolean inputJump, System.Boolean inputSprint, System.Single deltaTime) (at <4536c5529add4d67816deff02f8b9c51>:0)
SDG.Unturned.PlayerInput.FixedUpdate () (at <4536c5529add4d67816deff02f8b9c51>:0)
[2023-12-25 15:20:51] NullReferenceException: Object reference not set to an instance of an object
[2023-12-25 15:20:51] SDG.Unturned.PlayerMovement.updateRegionAndBound () (at <4536c5529add4d67816deff02f8b9c51>:0)
```
While operating a game server, certain users repeatedly experience the above error and the game crashes.

**Comment by DanielWillett** [comment]
He'll probably want the full log under Unturned/Logs. likely one error at the top is causing the remaining errors.

**Comment by GazziFX** [comment]
IL offset is not displayed in Client.log, attaching UnityAppData/Player.log will be appreciated

**Comment by Blackwolf0726** [comment]
[Player-prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13778059/Player-prev.log)

**Comment by GazziFX** [comment]
After looking at your log it seems crash related to #4281

**Comment by SDGNelson** [comment]
Thanks, yes, it's probably the same issue. If you turn off the Keep Microphone Ready option in the Options menu does it stop crashing?

**Comment by SDGNelson** [comment]
Hopefully this should be resolved in the .3 patch out now!
