### ISSUE TITLE
Game crashing on changing scenes

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4288]
Could be related to other crashes, but ive figured out that it ussualy crashes when the scene gets changed (Assets loading -> Main menu). 
_A factor to this could be that doing somethimg like tabbing nto the game when the scenes switch could cause it also (for me i have to tab back in n out to replicate this)_

**Comment by SDGNelson** [comment]
If you turn off the Keep Microphone Ready option in the Options menu does it stop crashing?

**Comment by RBMKBlaze** [comment]
> If you turn off the Keep Microphone Ready option in the Options menu does it stop crashing?

Will check tommorow.

**Comment by sunnamed434** [comment]
I have the same problem, but it appears once I click quit button, sometimes happens when server got shutdown (auto update) due to new unturned update

**Comment by RBMKBlaze** [comment]
> If you turn off the Keep Microphone Ready option in the Options menu does it stop crashing?

Played with it for about 4 hours, it seems the crashes arent happening anymore.

**Comment by SDGNelson** [comment]
Hopefully this should be resolved in the .3 patch out now!
