### ISSUE TITLE
Game keeps crashing for no reason

### ISSUE THREAD

**Issue by DustyOwO** [SmartlyDressedGames/Unturned-3.x-Community#4289]
Game keeps crashing when entering inputs (Walking or clicking or tabbing back into the game) Computer is not low end.

**Comment by SDGNelson** [comment]
If you turn off the Keep Microphone Ready option in the Options menu does it stop crashing?

I intend to release a patch in the next couple days for some of these misc bugs. :S

**Comment by SDGNelson** [comment]
Hopefully this should be resolved in the .3 patch out now!
