### ISSUE TITLE
Update door state

### ISSUE THREAD

**Issue by Enrique-go** [SmartlyDressedGames/Unturned-3.x-Community#4296]
For some reason, when I change the state of my door (owner and group), it doesnt lock. I tried the birch, metal and maple door and only the metal door is blocked, the other 2 cannot be picked up but can be opened.
![Unturned Issue](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/61326104/34f692d4-58a3-4756-9fc2-7aa708a58985)

**Comment by SDGNelson** [comment]
Unfortunately, there is some currently messiness required for what you're trying to do. Looking for door state in Issues brings up a few posts with more details explaining how to work around it, e.g.: #701
