### ISSUE TITLE
Add "Listen Server Host Mode" option to IOBS Event Hook

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#4298]
Hia,

the IOBS event hook does not sync correctly in single player. All IOBS triggers in unity are dependent on the player.

Let me give an example: 
- A specific IOBS object has an Interactibility condition where you can only press F if you x flag
- In multiplayer, this door works as intended: it can be manipulated, toggled remotely by unity, and only players with x flag can interact with it
- In singleplayer, this door does not work as intended. If you trigger the IOBS toggle in unity, if you don’t have x flag, it won’t move. (It treats all interactions with doors as being done by the one, currently active player)
- Same with rewards. Applies Interactibility rewards even if you trigger it remotely in unity.
Please fix this unintended behavior! Make it so single player behavior is exactly the same as multiplayer!

Thank you, DrDallas

**Comment by SDGNelson** [comment]
Can you elaborate on your setup please? Pressing F on the interactable uses the same RPC as if the singleplayer host or a multiplayer client calls the IOBS event hook methods. The difference is only if the dedicated server requests a change of state, in which case there is no player to associate with the request. My guess from your description is that in multiplayer it's being called by the server rather than by a client.

**Comment by DrDallas1** [comment]
Yes exactly! In single player, all IOBS interactions are affected by the player. This means that in cases where a unity trigger triggers a door, the reward and condition is applied to the one, single, player. There is a heavy disconnect between the single player interpretation (where all IOBS doors changing state on the map are the fault and result of the player no matter what), compared to multiplayer (where unity events don’t associate a player, unless you are pressing F on the object)

**Comment by DrDallas1** [comment]
To clarify, I think the multiplayer interpretation is the correct version, that should be carried into single player (it makes the most sense)

Example:

Let’s say there is an IOBS door that rewards you with flag “X” when clicked. This door is normally sunk into the ground, but when you trigger a specific NPC event, it rises out of the ground for a one time trigger.

Multiplayer
- Speak with NPC -> trigger NPC event -> trigger NPC event hook in unity -> toggle door state -> Door raises out of the ground -> any player can click F on it once to get the flag, in which case it goes down in the floor
(Correct)
Singleplayer:
- Speak with NPC -> trigger NPC event -> trigger event hook -> toggle state -> door raises out of the ground, and instantly gives the player the flag (just because it was raised by the NPC event)
(incorrect)

**Comment by SDGNelson** [comment]
I don't think there's really a "correct" case, rather it would be useful to have an option for whether it's run as client or as server when run on the listen server host.

**Comment by DrDallas1** [comment]
That’s wonderful! Thank you so much!
