### ISSUE TITLE
Raiding Door Glitch

### ISSUE THREAD

**Issue by YtubBearFX** [SmartlyDressedGames/Unturned-3.x-Community#43]
By placing down two plates in a specific way you can glitch through doors and walls into bases, I know this can be countered through a claim flag, but I think that this is really GAME BREAKING, especially for new players who might be hiding away in a little shack for the night and then the next morning everything has been taken away by a griefer/glitcher, a little off topic but it is important to fix this please Nelson, you can also use this glitch similarly to break the map and build glitch bases another HUGE GAME BREAKING BUG, I hope the caps helps give light as to how frustrating this is to me, I know there are always going to be Bugs, Glitches and Hacks for Unturned but having nearly 2K hours I know that this has been lurking in the game for a very long time, and I don’t think you can push onto 4.0 without giving the base game.

**Comment by V1CeNtE** [comment]
read before post

**Comment by YtubBearFX** [comment]
What?

**Comment by V1CeNtE** [comment]
this is posted :/
