### ISSUE TITLE
`MasterBundle:AssetPath` format not supported in `MasterBundleReference<T>.TryParse`

### ISSUE THREAD

**Issue by Curly0-brackets0** [SmartlyDressedGames/Unturned-3.x-Community#4300]
A weather .asset file I'm making is not showing the default rain particle system no matter what I change.
Puddles show up as expected; I assume because of the Legacyraincomponent component_type, but there are no raindrops visible in-game at all.
Everything else works fine.
Syntax is correct as I have understood it.
Is this a masterbundle issue?

File path:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/8a5f501f-9e48-49ab-a8f5-b4e677515c79)

Component_Type:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/b6321ed4-f1ed-4104-9411-cdf5eb0b6920)

Prefab:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/2f62dd64-c063-4c57-b4f7-8e958f380b4c)

What could be the issue here, and is there a way I can diagnose it?

Thanks in advance, Curly.

**Comment by GazziFX** [comment]
I think it try to load asset from your masterbundle because its not in built-in assets

**Comment by Curly0-brackets0** [comment]
@GazziFX Yeah I though so too, nelson mentions in the documentation for masterbundleptrs this:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/2db853c6-c32a-4f22-b3ed-c91c7077ed17)
but based on the syntax he uses it seem like that is for .dat files not .asset files, do you know how to point to the core masterbundle for a .asset file?

**Comment by SDGNelson** [comment]
The default masterbundle is the one found in the file hierarchy, so in your case you will need to explicitly specify the core masterbundle with "core.masterbundle:path/to/file.extension"

**Comment by Curly0-brackets0** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/146196839/36d37131-2eff-4dd6-ab44-95c443037d68)
Assuming this is how, it still doesn't get the particles.
Do I also need to add exclude_from_master_bundle in the .asset file when I use an override like this for it to work?

**Comment by SDGNelson** [comment]
Off the top of my head that looks right. Can you attach your asset file please and I'll try loading it up?

**Comment by Curly0-brackets0** [comment]
Github seemingly doesn't support attaching .asset files, I have attached a .zip file which contains the .asset file instead :/
[Urals Storm.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/13877627/Urals.Storm.zip)

**Comment by SDGNelson** [comment]
Thanks for the example asset! My bad: It looks like the `mb:path` format was supported in the old .dat parser but not the new .dat parser, and somehow wasn't caught until now. I will add support for that in the next update.

In the meantime I double-checked and this is parsed correctly:

Replace:

`"Prefab" "core.masterbundle:Effects/Weather/DefaultRainParticles.prefab"`

With:
```
Prefab
{
	MasterBundle core.masterbundle
	AssetPath Effects/Weather/DefaultRainParticles.prefab
}
```

**Comment by Curly0-brackets0** [comment]
Ah thanks a lot!
