### ISSUE TITLE
Keep experience on death.

### ISSUE THREAD

**Issue by northstar3703** [SmartlyDressedGames/Unturned-3.x-Community#4306]
I am wondering if there is a way for players to keep their **experience** on death. I have noticed that in my server when a player dies there experience is set to zero, or at least reduced in some capacity. I was wondering if there is a way around this, as my server utilizes UconomyXP (uconomy based off XP) and it is kind of an issue for players money to wipe every time they die. 

to answer a few questions, 
- Yes, loose skills is set to 0 in the config.
- No, I have not tried using the regular Uconomy as I don't want to set up MySQL (I believe that Uconomy requires MySQL).
- Yes, I am new to Unturned server development.
- No, no other plugins are interfering with experience.

**Comment by QERT2002** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/7be170a0-46a5-492e-9a7b-ed1063717d8b)
Set this in all modes: normal, easy, hard.
If after that experience still loose you must check your plugins

**Comment by GazziFX** [comment]
It works in opposite way
```
newExp = oldExp * Lose_Skills_PvP
```
so you need to set it to 1

**Comment by northstar3703** [comment]
> ![image](https://private-user-images.githubusercontent.com/39222548/295818952-7be170a0-46a5-492e-9a7b-ed1063717d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTEwNjIsIm5iZiI6MTcwNTAxMDc2MiwicGF0aCI6Ii8zOTIyMjU0OC8yOTU4MTg5NTItN2JlMTcwYTAtNDZhNS00OTJlLTlhN2ItZWQxMDYzNzE3ZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIyMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTcxODhhZWE1M2Y0NDVlMGEyOGI1YTAyMzAxN2E1YjJjOTcyZmFiMDA1Zjg2MDNmNTlkMmU2ZTVkODJlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYDJF5NKG3pXeXFJejFCr9y2X6zPDPLjAH55XefvEcI) Set this in all modes: normal, easy, hard. If after that experience still loose you must check your plugins

![Screenshot 2024-01-11 170644](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/110694408/13edc235-8a7e-4fcd-b3b4-535cced8eb07)

**Comment by northstar3703** [comment]
its not the skills I am concerned about, those already stay, what im concerned about is players XP count.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/110694408/fcc3a87a-bf32-4b52-8f10-10e6ced3f238)

**Comment by northstar3703** [comment]
> ![image](https://private-user-images.githubusercontent.com/39222548/295818952-7be170a0-46a5-492e-9a7b-ed1063717d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTEwNjIsIm5iZiI6MTcwNTAxMDc2MiwicGF0aCI6Ii8zOTIyMjU0OC8yOTU4MTg5NTItN2JlMTcwYTAtNDZhNS00OTJlLTlhN2ItZWQxMDYzNzE3ZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIyMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTcxODhhZWE1M2Y0NDVlMGEyOGI1YTAyMzAxN2E1YjJjOTcyZmFiMDA1Zjg2MDNmNTlkMmU2ZTVkODJlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYDJF5NKG3pXeXFJejFCr9y2X6zPDPLjAH55XefvEcI) Set this in all modes: normal, easy, hard. If after that experience still loose you must check your plugins

also if you would have read the bottom part of my post, you would have seen that I already said that I had set loose_skills_pvp/pve to 0 (like i said before the problem is not the skills, its the experience.

**Comment by DanielWillett** [comment]
They use the same config value, like he said in the bottom of his post, it needs to be 1 not 0.

https://github.com/Unturned-Datamining/Unturned-Datamining/blob/linux-client-preview/Assembly-CSharp/SDG.Unturned/PlayerSkills.cs#L665

**Comment by SDGNelson** [comment]
Thanks GazziFX and DanielWillett, their answers are correct that you want this set to 1 not 0.

**Comment by northstar3703** [comment]
> Thanks GazziFX and DanielWillett, their answers are correct that you want this set to 1 not 0.

yea I had my developer explain it to me in a VC. thats confusing asf but thanks
