### ISSUE TITLE
I want to get unloaded in the game unturned 

### ISSUE THREAD

**Issue by Ramzes2323** [SmartlyDressedGames/Unturned-3.x-Community#4307]
I want to get banned from the unturned game because I was mistakenly banned for always. Is it possible? I really like this game and I don't want to stop playing it!

**Comment by SDGNelson** [comment]
Sorry but for multiplayer bans please refer to this support article: https://support.smartlydressedgames.com/hc/en-us/articles/12082986788884-Multiplayer-bans
