### ISSUE TITLE
Wrongly placed shelf on Vanilla Russia map

### ISSUE THREAD

**Issue by Erdbeersahnetorte** [SmartlyDressedGames/Unturned-3.x-Community#4309]
![Screenshot (2823)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156500434/e956e22a-7c12-4eb5-8bf2-a2d903c89028)

**Comment by SDGNelson** [comment]
Thanks for the report. Where is this on the map?

**Comment by Erdbeersahnetorte** [comment]
The tan house in St. Peterburgs on the left of the Mechanic (House marked with the blue X)
![Realpeter](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156500434/4680bf17-4d5b-4847-89f3-a3cc3518b986)

**Comment by SDGNelson** [comment]
Thanks for the indicator!

**Comment by Erdbeersahnetorte** [comment]
Will the reporting of this issue in me  receiving one of those fancy berets?

**Comment by ItsRodrigoAl** [comment]
> Will the reporting of this issue in me receiving one of those fancy berets?

No
