### ISSUE TITLE
Problems with steam workshop servers?

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#431]
I am curious if there are any problems with steam workshop server at the moment? I got reports from players that they can't connect to server "missing this", "missing that" (mods). Checked that myself and only like half of mods were downloaded, checked again - a bit more than a half then, still not all of them.

**Comment by khakers** [comment]
There’s been a lot of issues regarding “missing barticade assets” for a long while.

**Comment by baranmod** [comment]
It seems like its skipping most of mods for some reason while connecting. It downloads like 30-40% packs only. And its happening for small amount of players but its increasing pretty fast.

**Comment by Daniil1288** [comment]
Can confirm.
Had a server download folders but 0 bytes of files from workshop using WorkshopDownloadIDs.json

**Comment by baranmod** [comment]
All good now. Seems it was just a temporary issue.
