### ISSUE TITLE
Better handle clusters of player labels in HUD and map

### ISSUE THREAD

**Issue by 0x59R11** [SmartlyDressedGames/Unturned-3.x-Community#4310]
## On servers where a large number of players accumulate, the map is not possible to use normally.
**I'd offer a simple solution to the problem, in my opinion it will be very useful, as it will allow to realize more pleasant servers on special topics.**

  Server settings:
  - `Provider.modeConfigData.Gameplay.Map_HidePlayersName : bool`
  If true - hides the display of player names on the map. Or alternatively, the name is displayed only when the mouse is over the player icon itself.
  
  - `Provider.modeConfigData.Gameplay.Map_HidePlayersIcon : bool`
  If true - Display a pointer of a certain color instead of the player icon.

**Comment by SDGNelson** [comment]
Are you using something to show the labels for all players? I would think by default for group members it wouldn't be *too* many.

**Comment by DanielWillett** [comment]
I think he means having a lot of people in the same group. My server has a similar issue with the map being hard to see at high-pop since the server is split into two groups.


> Or alternatively, the name is displayed only when the mouse is over the player icon itself.

This is a cool idea.

**Comment by 0x59R11** [comment]
> Are you using something to show the labels for all players? I would think by default for group members it wouldn't be _too_ many.

I think a simple colored circle texture with some shadows or outlines would be enough.

As for me it would bring new opportunities for server developers. As an example, here is a screenshot from one server, the theme of which is built on a large number of players in one team, the map is really hard to use.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/41921371/ad966840-001e-4617-8793-86a4e9aad494)

Another problem is the nicknames in the HUD. Yes they can be disabled, but then there is another problem, to distinguish the enemy from the partner becomes much harder.

The problem is that if the player in front of a large number of partners, it is not possible among all these nicknames something to see. 
As a solution I propose to make a label (with transparency) instead of nicknames.
*(as well simple colored texture)*

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/41921371/7f25baf1-4bfd-4780-94d5-1e9540407f82)

**Comment by SDGNelson** [comment]
That's the kind of thing that would definitely bug me in other games and think "man I wish I could make this one update." I'm not sure whether I'll do it for the next update but I'll mark as "should do".

**Comment by SDGNelson** [comment]
The next update has two related changes:
1. Names above players' heads are at 50% opacity and fade out to 5% when closer to the middle of the screen. They stay at 100% opacity with the "spectator" setting enabled.
2. The map screen has toggles underneath for markers, player names, and avatars. (players can choose to enable/disable as-needed)
