### ISSUE TITLE
Twitter and blog icons do not get colored by Interface Foreground Color setting

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#4311]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/a28ff5a6-e1fa-41c7-b9c4-cd2c7cc57d71)

**Comment by CyberAndrii** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3586

**Comment by DerEnte** [comment]
mb
