### ISSUE TITLE
See about updating quest list to support automatic vertical layout

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4313]
Yes, this is a legitimate problem I've run into, not just bounds checking.
It's ugly but maybe a scroll bar can be added if the list gets too long for the conditions. And track/abandon/return buttons are always on screen.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/47935791/0015dc67-8ac0-4aff-b2e3-706d931cd390)

**Comment by SDGNelson** [comment]
Yikes. What kind of quest is it? Why does it have so many conditions? Should some of them not be visible?

**Comment by Spebby** [comment]
Visiting all the named locations on a map.

**Comment by SDGNelson** [comment]
Fair enough. Off the top of my head I'm not sure how well everything will support the newer auto layout like for chat, but I'll look into it for the quest menu.

**Comment by Spebby** [comment]
> Fair enough. Off the top of my head I'm not sure how well everything will support the newer auto layout like for chat, but I'll look into it for the quest menu.

it should be noted that this may be an issue unique to my system as I run a 3:2 ratio. A friend could still access some buttons so be sure you account for unusual monitor ratios.

**Comment by prank0079** [comment]
Oh...  I usually break it down into a few quests.

**Comment by Spebby** [comment]
TO NOTE: i just checked and I had UI scale set to 1.5 due to my display size. This is 100% the cause on my end, but obviously the game should be able to support all UI scales fine.

**Comment by SDGNelson** [comment]
The quest screen actually already supported a scrollbar when the content was too tall, but your note highlighted the underlying issue: It wasn't taking the UI scale into consideration when deciding whether to use the scrollbar in that menu. This should be fixed for the next update.
