### ISSUE TITLE
Aurora Skier Helmet clips with biohazard hood

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4316]
unplayable
<img width="239" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/47935791/a18a5dac-1933-4ff7-997d-9786bf67e216">

**Comment by SDGNelson** [comment]
Unfortunate inevitability of the large number of item combinations. I checked and there isn't enough room to move the helmet up slightly enough to prevent that. Another option would be to make the biohazard mask slightly smaller, but that would surely introduce a different clipping issue.

**Comment by Augusha** [comment]
You can fix it easily by moving this vertices on 0.013m by Y axis
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/93490929/e40e38a1-54c7-4abf-8feb-3d9d7c89d5c5)

Before:
![Screenshot (350)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/93490929/e4967be7-588b-42bd-85f5-1c754ce658e4)
After:
![Screenshot (349)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/93490929/5d3eaa46-87b3-4963-bb43-2ca9ebbce389)

**Comment by SDGNelson** [comment]
@Augusha Thanks, I take it you are August? Would you be willing to email the unitypackage with the revised mesh to nelson@smartlydressedgames.com please? If so, I will include it as a fix in the next update.

**Comment by Augusha** [comment]
Okay I'll send it a little bit later, just woke up

пт, 19 січ. 2024 р., 23:05 користувач Nelson Sexton <
***@***.***> пише:

**Comment by SDGNelson** [comment]
Thanks!
