### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Blackwolf0726** [SmartlyDressedGames/Unturned-3.x-Community#4317]
1. When working in Unity, is it possible to only use the Mod Hook that comes standard with Unturned?
2. The monobehaviour script added by an individual does not work. Can you tell me how to solve this?
  And I don't know much about this, but the extension in the link below worked in the past, but doesn't seem to work now.
  https://github.com/olie304/UnturnedScripts
3. I uploaded a modpack by adding AssetCustomData, and as an experiment, I uploaded another modpack with the same content (with a different workshop ID), and the other modpack worked. (Not unloaded.)
4. If the master bundle is changed, can the contents be reloaded without restarting the game?

**Comment by GazziFX** [comment]
Only existed scripts can be loaded, because it can't be bundled into mod

**Comment by Blackwolf0726** [comment]
As an answer to question 1, can I understand that only basic Mod Hooks can be used, and monobehaviour scripts cannot be used?

AssetCustomData seems to be a feature provided by default in Unturned, but it does not work properly.

**Comment by GazziFX** [comment]
Not only ModHooks can be used, but every existing script in the game

**Comment by DrDallas1** [comment]
Mono behavior scripts can be used. What script are you trying to use?

**Comment by MoltonMontro** [comment]
> AssetCustomData seems to be a feature provided by default in Unturned, but it does not work properly.

If you're talking about [`AssetBundleCustomData`](https://docs.smartlydressedgames.com/en/stable/assets/asset-bundle-custom-data.html), this can be used to make it more difficult for people to re-upload your mod.

**Comment by SDGNelson** [comment]
Thanks guys for answering their questions. Re the 4th: pressing the reload all assets key (in controls menu) will reload everything. Unfortunately, there isn't a way to directly replace all of the content with the reloaded master bundle without reloading everything.

Also note: the Issues tracker is intended for problems/bugs in the game. For modding questions the intended place would be discussions, the SDG forum, the official Discord, etc.

**Comment by Blackwolf0726** [comment]
> Mono behavior scripts can be used. What script are you trying to use?

I wanted to implement a unique item.

**Comment by Blackwolf0726** [comment]
> Thanks guys for answering their questions. Re the 4th: pressing the reload all assets key (in controls menu) will reload everything. Unfortunately, there isn't a way to directly replace all of the content with the reloaded master bundle without reloading everything.
> 
> Also note: the Issues tracker is intended for problems/bugs in the game. For modding questions the intended place would be discussions, the SDG forum, the official Discord, etc.

Okay. I will be careful.
