### ISSUE TITLE
spawning a crashed helicopter via plugin

### ISSUE THREAD

**Issue by Maximjetfs1305** [SmartlyDressedGames/Unturned-3.x-Community#4318]
Hello, maybe someone can tell me if it’s possible to plug in a crashed helicopter on a map. 
That sort of thing.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/147804958/c7e70b7b-73b5-4c05-b8f5-16abc5cdc414)

Or where you can find object data id, maybe someone already has.

I know you can make a model of a crashed helicopter and blow it up like a barricade through BarricadeManager. But this varrian doesn’t really suit me.

**Comment by GazziFX** [comment]
Objects can be placed or moved only in designer time

**Comment by DrDallas1** [comment]
You should just do it via a barricade. The plugin spawns the barricade, and it looks just like the object.

**Comment by SDGNelson** [comment]
Thanks DrDallas1 - I'd tend to agree that's the best way to do it at the moment.
