### ISSUE TITLE
Horde Beacon - Glitched zombies?

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#432]
Hello! There was an old bug, but nowadays i started to hear about it many times, Daily 3-4 times aswell.
Players are doing Horde Beacon, and from time to time (Not always) the last zombies Will not spawn OR spawn but on unreachable location.
The reporters are all playing Russia map, however they got this trouble on locations like Novobirsk, Vladimir Farm aswell which have no "underground" place.
I don't know if it's a real bug, if it's even fixable, but i preferred to report it.

**Comment by SDGNelson** [comment]
Hmm easier to track down if it happened always / reproducible steps. I know that on Hawaii there were some spots that the map devs had to adjust spawns underneath the ground in caves, but as you say those are aboveground on Russia. Looking through the code I don't immediately see anything suspicious, but if you see a report of a trick to reproduce it that would be very helpful.

**Comment by lvlbgn** [comment]
Hey, so i partially tracked it down for you. We could keep replicating this bug any day, any time..
The horde beacon can't be finished on PEI, Holman Isle. (This might be the same bug on all the other maps/locations, which i started this issue with) >> Falling zombie
So yea, we recorded this for you and catched a falling zombie at 1:42, which keeps falling but can NOT be killed causes the horde can not be finished.https://youtu.be/WtX-VEmjOjY

A clear view for the falling zombie:  https://youtu.be/WXnSi2F7wv4

**Comment by SDGNelson** [comment]
Thanks for the videos! My guess is that the zombie somehow managed to fall through both the bunker and the landscape underneath (spawned underneath the world maybe?), is at some huge negative location which is then remapped into the multiplayer replication range. For the next update I'll adjust the damage restrictions to fix shooting falling zombies, and teleport out-of-map zombies back in.
