### ISSUE TITLE
Seeds placed by the map editor will not grow.

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#4320]
And the seeds produced by replacing the airdrop model did not grow.
I don't know if this is a bug or if it's not allowed.
PS：Yes, I want to use Carepackage.cs to generate seeds that can grow.

**Comment by SDGNelson** [comment]
Currently, the "planted" time isn't set for farmable items not placed by players. It might be a straightforward change depending whether time is set before the barricades are loaded, I'll check.
