### ISSUE TITLE
[MEDIUM BUG] Direct Connect wont attempt to connect

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4321]
Hello, when I enter the IP & Port into the fields in the "Direct Connect" menu, sometimes nothing happends; it doesn't even display"Connection Attempt: 1", the button doesn't do anything. I've had this happening with the IP being a normal IP and it being a domain. I haven't found the exact cause or environment that this would happen in. 

NOTE: Each time there was a server on the end. Some members fixed this by using a VPN; pinging the IP/Domain would result in it not resolving the host.

If this issue isnt related to the game it would be nice to atleast return some feedback.

**Comment by SDGNelson** [comment]
If it doesn't show the attempting to connect menu it probably thinks the IP isn't valid. Can you post a screenshot of the screen please?

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I will re-open.
