### ISSUE TITLE
Unturned Player cannot join server if Glasses are given Nightvision.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4323]
As the title describes, if glasses get their nightvision property added or removed, it soft-locks the player into the queue and they are unable to join the server.

**Comment by GazziFX** [comment]
Glasses without vision has state length 0 and nightvision has state length 1, its not updated until item recreated and gives out of range exception

**Comment by Axodouble** [comment]
> Glasses without vision has state length 0 and nightvision has state length 1, its not updated until item recreated and gives out of range exception

Still should not soft lock players from joining the server, that is why I made this.

**Comment by DanielWillett** [comment]
Thought that was fixed in #4086.

Can you post the Client.log?

**Comment by SDGNelson** [comment]
Thanks @DanielWillett, that issue was my first thought, too. I'll try reproducing just in case, but otherwise what's the exception in client or server log?

**Comment by SDGNelson** [comment]
Tested this in the most recent version two ways, firstly:
1. Equip NVGs in multiplayer
2. Remove NVG property from item asset and restart server
3. Client is able to join without issue
4. Add NVG property back to item asset and restart server
5. Client is able to join without issue

Secondly:
1. Equip snorkel in multiplayer
2. Add NVG property to item asset and restart server
3. Client is able to join without issue

Did you run into this recently? Or was it a while ago before the fix?

**Comment by Axodouble** [comment]
Ah yeah I ran into it a while ago but only recently remembered, but in that case it's good.
