### ISSUE TITLE
I am getting this Error there are about 38 mods 

### ISSUE THREAD

**Issue by RubbleTV** [SmartlyDressedGames/Unturned-3.x-Community#4324]
![sel5m-20240123-0002](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/83584625/73d865bd-2f06-495b-904d-1104d56e068c)

**Comment by SDGNelson** [comment]
Maybe the server doesn't have permissions to read those files? I'm unfamiliar with this hosting dashboard.

**Comment by SDGNelson** [comment]
Closing as this seems to be part of issue #4328.
