### ISSUE TITLE
I'm getting this error from the map I made myself. 

### ISSUE THREAD

**Issue by RubbleTV** [SmartlyDressedGames/Unturned-3.x-Community#4326]
I would appreciate if you don't close it
![Ekran_goruntusu_2024-01-25_150728.png](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/83584625/47d9f8e1-f144-4c9f-ac0b-0128d1e36b68)

**Comment by SDGNelson** [comment]
If you can attach `workshop_log.txt` from your `steamcmd/logs` folder there *might* be some additional information.

It may also be worth trying the quick option of forcing a reset of the workshop install: https://smartlydressedgames.zendesk.com/hc/en-us/articles/18254340552212

That being said, my answer in #4325 still applies.

**Comment by RubbleTV** [comment]
It didn't work, I reset it but the workshop

**Comment by RubbleTV** [comment]
.

**Comment by RubbleTV** [comment]
_**Workshop Log**_

[2022-05-03 16:33:57] Loading workshop items for 0 installed apps for user [a:1:3801673830]:
[2022-05-03 16:34:10] [AppID 1110390] Loaded workshop items in "C:\steamcmd\steamapps\workshop" (0 installed, 0 needed)


[2023-02-06 13:11:54] Loading workshop items for 1 installed apps for user [a:1:3819286949]:


[2023-02-06 13:18:46] Loading workshop items for 1 installed apps for user [a:1:3364135259]:


[2024-01-26 20:00:55] Client version: 1705108307
[2024-01-26 20:00:55] Loading workshop items for 1 installed apps for user [a:1:2828676421]:




By the way my new map id is **3146526712**

**Comment by SDGNelson** [comment]
Sorry, I was mistaken: the relevant `workshop_log.txt` file should actually be in `U3DS/logs` - I just double-checked by installing Kuwait. Our support article about where `workshop_log.txt` is located was out-of-date so I've corrected that.

**Comment by RubbleTV** [comment]
> Sorry, I was mistaken: the relevant `workshop_log.txt` file should actually be in `U3DS/logs` - I just double-checked by installing Kuwait. Our support article about where `workshop_log.txt` is located was out-of-date so I've corrected that.



[Workshop Log](https://s2.dosya.tc/server28/apbc8r/workshop_log.txt.html)

**Comment by SDGNelson** [comment]
Thanks for the log. It looks like most of the workshop files are downloading fine, and only your workshop uploads are timing out. I tried downloading yours as well and also timed out on my end.

It might be worth contacting Steam Support and reporting that your workshop file times out when downloading. They might be able to get more error information.

It could also be something related to what you uploaded. For example, does it contain a huge number of tiny files?

**Comment by RubbleTV** [comment]
> Thanks for the log. It looks like most of the workshop files are downloading fine, and only your workshop uploads are timing out. I tried downloading yours as well and also timed out on my end.
> 
> It might be worth contacting Steam Support and reporting that your workshop file times out when downloading. They might be able to get more error information.
> 
> It could also be something related to what you uploaded. For example, does it contain a huge number of tiny files?

Have 37 mods

**Comment by SDGNelson** [comment]
Those are the dependencies, downloaded separately (seem to be working okay).

Since this is an issue in steamcmd as well (i.e., using `workshop_download_item 304930 3146526712`) I don't think there is anything we can do on our end aside from recommend contacting Steam support, sorry.
