### ISSUE TITLE
Sandbox server bugs? ?[?]

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#433]
There seem to be a bug with servers which wipe Daily, some players Will not be "see-able" for some other players until the invisible player relog.
They are not cheaters, plugins like DeathMessage can get their name, while on Unturned's bottom when you die and you see a message who killed you, it shows ?[?]
I don't know if it's caused by server wipes, but on normal servers which wipe monthly i never heard about this bug. But it must be related to Unturned since plugins can get these players' name.
If you don't get what i mean i can try to get proof for it.

I see this error in server logs:

[10/24/2018 6:21:15 PM] [Error] NullReferenceException - SDG.Unturned.Provider.accept (SDG.Unturned.SteamPlayerID playerID, Boolean isPro, Boolean isAdmin, Byte face, Byte hair, Byte beard, Color skin, Color color, Color markerColor, Boolean hand, Int32 shirtItem, Int32 pantsItem, Int32 hatItem, Int32 backpackItem, Int32 vestItem, Int32 maskItem, Int32 glassesItem, System.Int32[] skinItems, System.String[] skinTags, System.String[] skinDynamicProps, EPlayerSkillset skillset, System.String language, CSteamID lobbyID)
SDG.Unturned.Provider.accept (SDG.Unturned.SteamPending player)
SDG.Unturned.Provider.sendGUIDTable (SDG.Unturned.SteamPending player)
SDG.Unturned.Provider.handleClientGroupStatus (GSClientGroupStatus_t callback)
SDG.Unturned.Provider.onClientGroupStatus (GSClientGroupStatus_t callback)
Steamworks.Callback`1[Steamworks.GSClientGroupStatus_t].OnRunCallback (IntPtr thisptr, IntPtr pvParam)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback`1:OnRunCallback(IntPtr, IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.SteamworksProvider.SteamworksProvider:update()
SDG.Unturned.Provider:Update()

-- This error seems to happen when someone connect to the server but not always. When i dont see a player connect i guess they just try to connect that time.

**Comment by SDGNelson** [comment]
Your though process is likely right, and yep the ? means the client doesn't know about that player. That method was last changed for a login stance adjustment, so I've made a small fix related to that which I think is the most likely cause.

**Comment by SDGNelson** [comment]
Any news after the 3.26.4.0 update from the other day?

**Comment by lvlbgn** [comment]
Didn't get reports anymore, but it could be because players just accepted this bug. Hoping for the best, i close this ticket & Will reopen in a few days if i meet this again (i Will ask my staff team to check sandbox more frequently to see if its still persisting.)
