### ISSUE TITLE
Balaclava has 0.95 Armor in the .dat but no armor displayed in game.

### ISSUE THREAD

**Issue by FluffyWabbitz** [SmartlyDressedGames/Unturned-3.x-Community#4331]
![2024-02-02_11-07-07](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/152986234/48d374a6-9ad0-41fb-aa46-37d69b6439e7)
![Capture](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/152986234/5e39ebed-089f-418e-a684-202961adde12)

**Comment by MoltonMontro** [comment]
Although balaclavas have an armor value with a ×0.95 modifier, players cannot benefit from armor provided by masks. However, zombies can benefit from this armor multiplier, because masks can be worn in their hat slot.

**Comment by SDGNelson** [comment]
Thanks Molt. This comes up often enough that maybe I should just remove that line from them.
