### ISSUE TITLE
Update on Semi-auto firemode having slow firerate. (regardless of Firerate value)

### ISSUE THREAD

**Issue by Sgtlog123** [SmartlyDressedGames/Unturned-3.x-Community#4333]
Currently, this makes weapon that's supposed to have fast firing semi-auto feel very unresponsive.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/111060879/cc459a25-0b48-4f8a-bb9c-bfa09a754651

Any plan to fix this in the future?
If yes, how?

Similar issue.
(Open) Incorrect RPM for Semi guns #4275
(Closed) Make semi-automatic mode faster/more responsive #3691

**Comment by SDGNelson** [comment]
In the 2024 Survey the accompanying option would be part of "input responsiveness", currently one of the top selections.

#3691 was actually already fixed (mention in #4275).
