### ISSUE TITLE
main menu banners still redirect when pressing "dismiss"

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4335]
i dont really have like "proof" of this because i clicked dismiss already and it went away and i dont know the file that controls it but

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/51b8776e-3dd4-41dc-b97d-d00bad4fe2d0)
pressing the "Dismiss" text on the banner in the main menu will still open the banner, in this case, pressing dismiss will still open the google form. 
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/19cca0a9-e92a-4736-8f06-f50b0f8bfa7c)
not really that big of an issue but still a bug nonetheless.

**Comment by SDGNelson** [comment]
You're right - thanks! IIRC that label was added because non-link banners can still be clicked to dismiss them. I'll fix this so that it only shows if there isn't a link configured.
