### ISSUE TITLE
(Very Minor) Workshop map icons on server browser

### ISSUE THREAD

**Issue by AngelAbov3** [SmartlyDressedGames/Unturned-3.x-Community#4340]
Since the server browser update servers using workshop maps have not had icons.

Since I don't think it's in the game an option for maps to use a folder called Mapicons like how curated maps use CuratedMapIcons

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123339655/c9c99f1b-d590-41b8-801c-bdfcd91d8a93)

**Comment by SDGNelson** [comment]
It depends whether you have that map installed. If you subscribe to the workshop map it should show the icon.
