### ISSUE TITLE
Issue with Scopes and Zoom_Using_Eyes True

### ISSUE THREAD

**Issue by AngelAbov3** [SmartlyDressedGames/Unturned-3.x-Community#4341]
Scopes with scope quality disabled break when using Zoom_Using_Eyes True.
However scopes with scope quality  enabled work when using Zoom_Using_Eyes True.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123339655/70a2c3f2-3188-407c-94d8-d39fe951ac97

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123339655/232b07d8-5bfb-4b31-a210-600699676a9c

**Comment by SDGNelson** [comment]
After looking at your video I had a hunch but double-checked by enabling Zoom_Using_Eyes with a factor of 1.5x on the Eaglefire iron sights and red dot sight. The reason it's weird here is that it's set up with the dual-render scope, whereas the eye zoom was intended for model-based and holographic sights. Was this just a test item experimenting with the eye zoom option?

**Comment by AngelAbov3** [comment]
This was a just test item experimenting with the eye zoom option.

I wanted to apply it on scopes below 2.0x zoom because I'd had complaints of the scopes zooming you out instead of inwards and this seemed to be a fix apart from scope quality of not working with the option enabled.

**Comment by SDGNelson** [comment]
It sounds like what you're running into is this issue: #4237 
Sorry to say I don't have any ETA of working on that at the moment. I'd recommend making the scope larger on-screen similar to the vanilla scopes for the meantime.
