### ISSUE TITLE
Barrel devices unable to change muzzle flash

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4342]
Specifying a muzzle flash effect in the barrel attachment's asset doesn't affect it. If we already can hide the muzzle flash/tracer, why can't we make it so that muzzle device adds it/changes it?

**Comment by SDGNelson** [comment]
Sounds like a useful suggestion, but this is not really an issue/bug - more so for the Discussions section.
