### ISSUE TITLE
Redirect player using server code

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4343]
Right now it's only possible to do redirect player using IP:PORT, but not the server code

**Comment by SDGNelson** [comment]
That does seem like a useful and straightforward improvement.

**Comment by realchameleon** [comment]
This would be very useful, for example if you change hosts the server code is just tied to the gslt token so it will never change and it will make some of the infrastructure way easier to manage.

**Comment by SDGNelson** [comment]
I've added an overload for the next update to relay by server code (steam ID). I did a basic test but there might be some edge case that comes up with immediately joining the next server when the menu loads - fingers crossed 🤞
