### ISSUE TITLE
Hitmarker Positioning not applying to shotguns

### ISSUE THREAD

**Issue by kulkaGM** [SmartlyDressedGames/Unturned-3.x-Community#4344]
Hitmarker Positioning is always Dynamic meaning the option is not applying to weapons like.. Bluntforce, Vonya, Devil's Bane ...

**Comment by SDGNelson** [comment]
I believe it's been like this for quite a while - any weapon that shoots more than one pellet shows multiple hitmarkers for clarity.

**Comment by kulkaGM** [comment]
If this is a feature..
Disclaimer should be present on the Hitmarker Positioning option -> "Does not apply to Weapons shooting pellets"
