### ISSUE TITLE
I was mistakenly banned by Unturned

### ISSUE THREAD

**Issue by q81362406** [SmartlyDressedGames/Unturned-3.x-Community#4346]
I have been playing Unturned for 7 years, and the first time I did nothing, I was banned by Unturned. I spent a lot of money on buying accessories, and I played on a PVE server. After playing for several days, I have cleared the game and it is impossible to use any cheats. I want to know the reason why I was mistakenly banned. Please help me solve it. Thank you ，I hope to receive compensation.  STEAM  ID:76561198292310060   MY steam: https://steamcommunity.com/profiles/76561198292310060/

**Comment by q81362406** [comment]
And I have already tried to find BE support，I haven't received a response yet

**Comment by MoltonMontro** [comment]
It looks like you probably sent an appeal today or yesterday. If you filed an appeal recently, it can take some time before you'd receive a response if your ban is revoked by BattlEye.

BattlEye Support rarely responds to appeals that have been denied (e.g., if someone appeals a ban for cheating, and they conclude that they were rightfully banned for cheating). If it's been a couple weeks and BattlEye Support has not responded to your appeal/inquiry, your appeal has most likely been denied.

It can take several business days before an appeal is reviewed; please give BattlEye Support time to review your appeal. For more information about appealing a BattlEye ban, please refer to their [FAQ](https://www.battleye.com/support/).

**Comment by SDGNelson** [comment]
Thanks Molt
