### ISSUE TITLE
System events for modding.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#435]
You probably know that you can add scripts to a file with a mod (.unity3d).
Of course, if these scripts are in the game.
I have an idea.
Simple example:
![image](https://user-images.githubusercontent.com/32962870/47644193-d50e2080-dbb0-11e8-8968-343fee34006f.png)

**Comment by Adamv21** [comment]
Don't wanna be that guy but there is a reason to why scripts are banned after all. If there was a way around that I would love to see that though.

**Comment by VitaxaRusModding** [comment]
I have already added component  Landscape this way to the game, and not any problems.

**Comment by Adamv21** [comment]
Oh, wait I think it's limited on workshop only? Maybe it's changed, not sure.

**Comment by aviadmini** [comment]
OnEnterVehicle -> Add KilLVolume -> OnVehicleExploded -> OnPlayerDied -> Profit

**Comment by VitaxaRusModding** [comment]
there may be many. OnDay OnNight etc.

**Comment by Trojaner** [comment]
1) You can not export scripts with asset bundles.
2) This would be very dangerous

**Comment by VitaxaRusModding** [comment]
You can use a copy of the script from the game by adding it asset bundles!

**Comment by Trojaner** [comment]
No, you can not export scripts.

**Comment by VitaxaRusModding** [comment]
I personally attached the script component Landscape and added it from the objects to the game, your inexperience.

**Comment by khakers** [comment]
You cannot have any custom script in assetbundles but you can reference scripts in game through a bug

**Comment by aviadmini** [comment]
You can attach scripts that already exist in game. But there's not many useful ones

**Comment by VitaxaRusModding** [comment]
Thus, if a developer adds a script and throws us an example, we will be able to use it.

**Comment by VitaxaRusModding** [comment]
And I'm talking about events that will be useful for modding.

**Comment by SDGNelson** [comment]
The other comments are correct that you unfortunately cannot export scripts inside asset bundles. If you open the asset bundle file you can see that they're serialized as numeric IDs of components included with vanilla Unity so that you can bundle components like meshes, landscapes, lights, etc.

I believe I saw a blog post (maybe from Facepunch?) recently about how they extended this list of IDs to include their own code, however that would still be limited to components from the game's dlls.

For the most part these sorts of events are currently possible by hooking events in the base game using Rocket or the modules feature.

**Comment by SDGNelson** [comment]
As an example here's the header for 4's headlights component (picked random recent bit of code), much better documentation coverage and designed for modded components to hook events or inherit from.

https://gist.github.com/SDGNelson/0e6057ec280b0eb302879d459b5814ff

**Comment by VitaxaRusModding** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1086881979&searchtext=script
Read, here is what I mean, UnityEvent with game events.
Add separate scenarios with events and call these events, and we attach scripts to objects and listen to events.
And send the scripts to us so that we add them to the gameobject.
Sorry for my english please.

**Comment by VitaxaRusModding** [comment]
You are talking about modules, but if I'm not mistaken, players will not be able to load them (for example, as mods).
I use some tricks to fundamentally change the logic of the game on the server (and these are not modules or plugins), but this is not enough for me.

**Comment by SDGNelson** [comment]
Interesting, I wonder if Unity hashes the attached script and then the game recognizes the hash is the same as one in the assembly. (I imagine that's why the script has to be identical.)

From your original example it looks like you want delegates for existing scripts, in which case do they even need to be attached? Rocket plugins already hook delegates from the vanilla scripts for many things.

**Comment by aviadmini** [comment]
It doesn't have to be identical. It just needs to have same entry points. Moreover, only those you need

**Comment by VitaxaRusModding** [comment]
In general, I can make events myself, send scripts to the developer, and the developer simply adds them to the game and initiates the events?

**Comment by VitaxaRusModding** [comment]
**Hi, I created an example.**
1. I created the VehicleEvent script in Assembly-CSharp.dll
![image](https://user-images.githubusercontent.com/32962870/47961514-e1322c00-e04f-11e8-84a9-6b6419fe825d.png)
2. I changed the method in VehicleManager.enterVehicle
![image](https://user-images.githubusercontent.com/32962870/47961541-5271df00-e050-11e8-82a9-aa28e99e89aa.png)
Got the component "VehicleEvent" with the gameobject "Vehicle" and raised the OnEnter event...
In the same way, I changed the VehicleManager.exitVehicle method and added an OnExit event call.
3.I added a copy of the “VehicleEvent” component to the “Vehicle” gameobject and added lighting to the train when the player returns to the train the light turns on, and when he leaves the train the light turns off.
![image](https://user-images.githubusercontent.com/32962870/47961617-daa4b400-e051-11e8-9a42-eb2433a6291f.png)
Here's what happened:
![20181104161023_1](https://user-images.githubusercontent.com/32962870/47962003-50f8e480-e059-11e8-8d61-cfb2ccebcc6b.jpg)
![20181104161043_1](https://user-images.githubusercontent.com/32962870/47962009-74239400-e059-11e8-983e-215ce9a27ae0.jpg)
![20181104161058_1](https://user-images.githubusercontent.com/32962870/47962012-7a197500-e059-11e8-9771-c4593f4e6676.jpg)
![20181104161130_1](https://user-images.githubusercontent.com/32962870/47962014-7dacfc00-e059-11e8-8c7c-b3ce3401febe.jpg)
There is an idea with keystrokes, there is an idea with triggers ...

**Comment by VitaxaRusModding** [comment]
I can implement various event systems and provide samples to the developer, can I do it or not? =\

**Comment by SDGNelson** [comment]
Interesting, thank you for the example. I wasn't aware unity events let you control properties like that. (they're not used in the game anywhere) Not sure when the next update will be, but as an experiment I'll add a bunch of events for vehicles similarly to what you requested + more, and we'll see how it goes.

**Comment by VitaxaRusModding** [comment]
Always happy to help ... =)

**Comment by SDGNelson** [comment]
"+ more" was an overstatement, for the next update here's the hook:
https://gist.github.com/SDGNelson/61b5f598cbe3553ba53c04b074577d7f
These scripts will be kept in the Bundles/Sources/ModHooks/ folder.

Once the update is out let me know if it works correctly for you, and from there you can let me know other events needed!
