### ISSUE TITLE
Animator component objects glitch with the Nightvision scope

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4352]
I made a generator type barricade, which has animations for it's idle state, on and off actions. When you look at it with a Nightvision scope, somehow the entire barricade seems to rotate same as one of the bones, or something like that. The issue isn't showing up on normal scopes, or with Nightvision goggles, and I didn't encounter a similar issue with any other animated barricade I made, or with vanilla barricades (like Pump Jack).

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/568b0018-ca3e-42b9-a4e9-6fbd58c2d7bf

To be honest, it doesn't bother me at all, and I find it quite funny, but a bug is a bug. Also it's rather curious, that it only works with nightvision scopes, but not with normal ones.

PS: Since when military nightvision looks so weird? It's as if there is just a slight tint added to the picture. Its not monochromatic as it used to be, and is supposed to.

**Comment by SDGNelson** [comment]
That is odd to say the least. I think not something to fix on my end though considering - as you mentioned - it doesn't happen with vanilla animated barricades.

Does it have any extra components on it? For example, something that might change with the lighting state?

**Comment by DerpyHoowes** [comment]
No, only the Activation Event Hook and Animator Component. Other than that, it's identical to vanilla generator.

**Comment by SDGNelson** [comment]
Sorry, I have no idea why it's happening then. 😕 🤯
