### ISSUE TITLE
Militia_Russia_Magazines spawns gun instead of magazine

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4354]
**ISSUE:** Militia_Russia_Magazines spawn table is unable to spawn a Viper Magazine. Instead, it contains the ID for spawning a Viper. The Viper is already part of the equivalent spawn table for guns.

----

Looks like it was originally reported here: https://forum.smartlydressedgames.com/t/bug-militia-russia-magazines-contains-viper-should-probably-be-viper-25-instead/7206

And mentioned more recently here: https://forum.smartlydressedgames.com/t/please-fix-the-russia-militia-spawn-tables/24141/2

**Comment by SDGNelson** [comment]
Thanks for crossposting as an issue. Unfortunate that the original thread was missed. I'll get this fixed for the next update and will credit both posters.
