### ISSUE TITLE
Can't change LOD distance by using Character_Mesh_3P_Override_LODs

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4355]
I can't change this distance, can you add something like this Character_Mesh_3P_Override_LOD_Distance in dat file.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/21d6fa02-fb37-4daf-956f-fe4fc53e2035

**Comment by SDGNelson** [comment]
They don't have a distance, rather the meshes in that array replace the meshes in the renderers assigned to the character LOD group - currently just 2.
