### ISSUE TITLE
Armored lockers cant turn in to display lockers (workshop map A6 Polaris)

### ISSUE THREAD

**Issue by Valpffs** [SmartlyDressedGames/Unturned-3.x-Community#4358]
So in polaris u can make armored lockers and display lockers. The problem is that you should be able to turn armored lockers into display lockers and wise versa. But u cant turn armored lockers in to display lockers you can only turn display lockers in to armored lockers

**Comment by SDGNelson** [comment]
Thank you for the report. For a curated map like this, however, could you repost it to the A6 Polaris discussions please? https://steamcommunity.com/workshop/filedetails/discussion/2898548949/5822622429924596746/
