### ISSUE TITLE
Russia map quest related issues

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4359]
Several issues I ran into, while re-doing all Russia quests with my friend:
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/df550cbe-704d-40ba-a88d-a01d1ecb55fc)
Sould crystal decal no longer attached to the stone properly, hangs in the air instead
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/fab747fe-537f-43e6-a765-8c058e9592e6)

Sould crystal sacrifice effect started playing while we were clearing out the horde beacon on Oil Rig for some unknown reason.
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/f74c9c93-81ae-4af3-9cc2-9756403ae9ee)

Shereyavo International Nav borders need readjustment. While doing the Horde Beacon there, it broke when we went to the edge of airstrip. as if we left the location. Doesnt make sense that the Navigation doesn't cover the whole airfield, at least within it's fence (and we didn't go outside the fence).

And also one thing that bugs me for several years already, but isn't a bug really. I'ld write it in the discussion but it seems that nobody really reads those, as I almost never get a reply there. Why on Russia map all locations' names are some kind of gibberish? Yekativurg instead of Yekaterinburg, Novobirsk instead of Novosibirsk, and so on. At first I thought it's an in-game decision to make up locations, but then again: Why on Germany, PEI, Washington, Yukon and curated maps all of the towns and locations are named properly? Ok, PEI, Yukon and Washington are parts of english speaking countries, and Russia isn't, and maybe when it came out, there was some kind of decision behind that. But then again, we got Germany with all the proper names in german. Whats so hard about making actual and proper location names for a map instead of messing up somebody else's language?

**Comment by SDGNelson** [comment]
Thanks for the reports. Weirdly enough I got a report of the soul crystal door symbol just a few days ago and fixed it recently - the issue was the symbol got included in static batching.

It is odd the soul crystal effect would happen at the oil rig. Were you playing on a server that might have different kill effects? I know a lot of servers play those kind of effects, for example, when a player dies.

Sorry about the bad experience at the airfield. Looking at the navmesh it is a bit close to the edge, but it's also not too different from most locations.

I don't remember who placed the location names on Russia (it could have been me or anyone collaborating on Russia), but my guess is whoever did it misread the names - not out of malicious intent.

**Comment by DerpyHoowes** [comment]
We were indeed playing on a public server, but its total vanilla, and has no plugins except for some chat text messages. If they did that thing with death effects, we would have noticed by now. Attached a video of this moment, perhaps it will give you some useful context.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/b44d0ea8-7f36-4fdd-9e6b-e77319e1087a

As for the airfield navmesh, it might be not too different from most locations, but it is really frustrating to waste a horde beacon (now that it requires a detonator, and not just easily accessible supply items to craft) and big ammo supply used to clear up the horde beacon. Even when everything goes right, all these horde beacon quests feel like a total waste of resources because how bad rewards are, and with these accidents it gets even more frustrating.

As for the names, never saw it as having some malicious intent behind it, but it's just weird that after all these years its not been fixed yet. For russian-speaking community it has always been very weird and confusing to read these names

Corrections:

Actual city/landmark names misspelled:
Novobirsk - Novosibirsk
Yekativurg - Yekaterinburg
Shereyavo International - Sheremetyevo International
Keryev - Kirov

If these changes ever get done, the sign on airport's building object needs to be altered as well.

Camp Oleksandr seems to be completely made up, derived from a male person name, yet misspelled. In russian this name is spelled Aleksandr (Oleksandr is valid spelling in some other languages of eastern Europe, but not in russian).

Jhavesk is just some gibberish that tries to sound russian, but to any native speaker sounds extremely weird.

Mount Nivek is something made up, but at least it doesn't sound all that weird, so it's debatable, whether to rename it or keep it as imaginary location.
Nordvik Farm sounds totally alien, but I suppose its some kind of reference, just like the Mawby's Farm on Germany map?

**Comment by MoltonMontro** [comment]
I wasn't involved with the Russia map's development in any capacity, but IIRC all of the location names were a reference to, or inspired by, the region the map was based on. E.g., Nordvik Bay or Izhevsk.

**Comment by DerpyHoowes** [comment]
Still doesn't explain misspelling the names, while on all other maps the names are accurate. We didn't get Tohoma instead Tacoma in Washington, or Greymule instead of Whitehorse in Yukon. This is just weird, out of place, and sounds goofy to all native speakers.
Also naming a farm after a bay is weird imo, lol.

**Comment by Jdance-Media** [comment]
Naming a farm after a bay is not weird. Typically most establishments and local companies are named after the region they are in. So while the bay may not be wholely visible, the naming of the farm I'd argue is okay-ish.

**Comment by DerpyHoowes** [comment]
And what farm exactly would be around the bay in desolate arctic area, to be named after it? Its literally in one of the coldest regions of Russia, and one with the least population density in country because of these harsh conditions.
![изображение](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/3c4505be-7ff9-464f-8d07-996e9e6aad75)

If Russia map was at least trying to show the climate variety of the region, and actually added a small arctic part somewhere, it would probably be okay to name some camp in this area like that, but the way it is now doesnt fit your explanation.

Even the entire thing with Nordvik bay seems weird, cause its an absolutely no-name geographical feature, one of hundreds. On all other maps all names are either real and well-known locations, or references like the mentioned Mawby's Farm. But with half of the locations on this map, it seems that things were named with whatever words somebody stumbled upon or came up with. Instead of trying to come up with some logic behind it, it would be just easier and make more sense to just replace gibberish or obscure names with the most notorious real life landmark names, and fix the misspelled names.

I dont see it having any kind of sophisticated idea behind it. Its simply a mistake, without any malicious intent (which probably just comes from the lack of knowledge about the region), as Nelson said. So what stops us from simply fixing it, instead of coming up with the justifications for it?

**Comment by MoltonMontro** [comment]
Sorry, my original comment seems to have derailed this GitHub issue a bit more than I expected; other players have given feedback/suggestions regarding map location names (e.g. Rainbridge Island) or felt that map layouts should be more 1:1 to real-life.

Regarding your bug report: I haven't been able to recreate the issue you had with the Horde Beacon on the Oil Rig. Have you been able to recreate this again, or is this the only time it's happened?

**Comment by DerpyHoowes** [comment]
No, I was unable to recreate it. I tried it in singleplayer, with the quest active (thought maybe its somehow related to that), but was unable to replicate it.

**Comment by Jdance-Media** [comment]
> And what farm exactly would be around the bay in desolate arctic area, to be named after it?

Fair, honestly did not think of that. I do agree with you on that then, alongside the other place names. I do think that location names are important considering that basically all of the vanilla maps only include the major locations of each region and none of the places in between.

**Comment by SDGNelson** [comment]
For the next update I have applied a few of the renames:

Novobirsk -> Novosibirsk
Yekativurg -> Yekaterinburg
Shereyavo International -> Sheremetyevo International
