### ISSUE TITLE
Equipment Exception

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#436]
Hi Nelson, I have a system to prevent the players from equipping some items (I am not using the equipementRequest), but when a player starts to make a quick spam of the equipment to try to equip this excetpion happens. Any ideas?

```
[Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.PlayerEquipment.tellEquip (CSteamID steamID, Byte page, Byte x, Byte y, UInt16 id, Byte newQuality, System.Byte[] newState)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.PlayerEquipment:tellEquip(CSteamID, Byte, Byte, Byte, UInt16, Byte, Byte[])
System.Reflection.MethodBase:Invoke(Object, Object[])
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.SteamChannel:send(ESteamCall, ESteamPacket, Int32, Byte[])
SDG.Unturned.SteamChannel:send(String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.PlayerEquipment:tryEquip(Byte, Byte, Byte, Byte[])
SDG.Unturned.PlayerEquipment:askEquip(CSteamID, Byte, Byte, Byte, Byte[])
System.Reflection.MethodBase:Invoke(Object, Object[])
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.Provider:receiveServer(CSteamID, Byte[], Int32, Int32, Int32)
SDG.Unturned.Provider:listenServer(Int32)
SDG.Unturned.Provider:listen()
SDG.Unturned.Provider:Update()
```

**Comment by SDGNelson** [comment]
It might be some specific item, but I wonder why you're not using the onEquipRequested event? It should handle what you're trying to do, or if not I should adjust it to support that.

**Comment by rube200** [comment]
I have already got support for onEquipRequested but in a "non-direct" way, but now this exception continues to appear much less frequently, and it is not a specific item

**Comment by SDGNelson** [comment]
Non-direct?

**Comment by rube200** [comment]
yes I needed "usablestructure" and I only got it through the equip, so I expected him to equip the item to check if he had to unequip or not

**Comment by SDGNelson** [comment]
You can do that with the onEquipRequested event in a few ways, for example:

if(asset is ItemStructureAsset)

**Comment by rube200** [comment]
hmm, I still think it's strange and I think you should take a look later.
