### ISSUE TITLE
Feature request: Artificial horizon

### ISSUE THREAD

**Issue by ksdsksd** [SmartlyDressedGames/Unturned-3.x-Community#4360]
A client side only(so as no additional data needs to be transmitted) artificial horizon would be nice to have in vehicles for flying in storms.  Just so you have some idea of orientation, to prevent swimming or crashing.
Simple like:
![Artificial](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/17296616/426df322-59d0-4f48-9f56-e422a8702daa)
Gimp:
[Artificial.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/14422874/Artificial.zip)

**Comment by SDGNelson** [comment]
That would be a cool addition. Closing your issue post however, sorry, as the issue tracker is only intended for bug reports.
