### ISSUE TITLE
Can open InteractableVault and door when group changed to 0 on deploy

### ISSUE THREAD

**Issue by MrRousek** [SmartlyDressedGames/Unturned-3.x-Community#4363]
```
using System;
using Rocket.API;
using Rocket.Core;
using Rocket.Core.Plugins;
using Rocket.Unturned.Player;
using SDG.Unturned;
using Steamworks;
using UnityEngine;

namespace TheObjectToUse
{
    protected override void Load()
    {
        SDG.Unturned.BarricadeManager.onDeployBarricadeRequested += OnDeployBarricade;
    }


    private void OnDeployBarricade(Barricade barricade, ItemBarricadeAsset asset, Transform hit, ref Vector3 point, ref float angle_x, ref float angle_y, ref float angle_z, ref ulong owner, ref ulong group, ref bool shouldAllow)
    {
        group = 0;
    }
}
```
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/105581272/ecc4f166-d349-4f0e-8359-be80516d0dcd)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/105581272/11194aad-be48-4789-bfdf-0dc945a1cf61)

**Comment by MrRousek** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/105581272/aa7a2068-0bac-4966-8141-451c2f067112)

**Comment by MrRousek** [comment]
You can't salvage darricade, but you can interact.

**Comment by SDGNelson** [comment]
Perhaps I'm misunderstanding, but if the owner still matches the player then they can still interact with it intentionally. If you set both owner and group to zero they won't be able to.

**Comment by MrRousek** [comment]
> Perhaps I'm misunderstanding, but if the owner still matches the player then they can still interact with it intentionally. If you set both owner and group to zero they won't be able to.

it is clear that I am the owner, but other players from the group can still interact even if group = 0

**Comment by MrRousek** [comment]
> Interactable Storage still have old group

Гази, прикол в том, что можно открыть сейф/дверь, а вот забрать нельзя. Ну по логике так не должно работать

**Comment by MrRousek** [comment]
I'll record the video and send it

**Comment by GazziFX** [comment]
`InteractableStorage` and `BarricadeDrop` have their own owner and group you should change `_owner` or `_group` field of `InteractableStorage` and call `rebuildState()` to keep them in sync

**Comment by MrRousek** [comment]
> `InteractableStorage` and `BarricadeDrop` have their own owner and group you should change `_owner` or `_group` field of `InteractableStorage` and call `rebuildState()` to keep them in sync

Thank you, I understand that. But still, it probably needs to be synchronized at the level of the game code.

**Comment by SDGNelson** [comment]
Ah, I understand now, sorry - yes: GazziFX's answer is correct that the interactables have their own owner/group properties whereas the general barricade owner/group are used for things like salvaging and whether players can see the HP.

**Comment by MrRousek** [comment]
> Ah, I understand now, sorry - yes: GazziFX's answer is correct that the interactables have their own owner/group properties whereas the general barricade owner/group are used for things like salvaging and whether players can see the HP.

Do you synchronize this at the game code level?

**Comment by MrRousek** [comment]
I think it's worth synchronizing it.

**Comment by MrRousek** [comment]
Or at least add a synchronization method

**Comment by DanielWillett** [comment]
(#3498)
