### ISSUE TITLE
No difficulty filter for servers in serverslist

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4366]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/a3a2b07e-b8f8-46ff-9510-b671285f9a93)

[From](https://www.reddit.com/r/unturned/comments/1arbmvu/where_is_the_dificulty_filter_for_servers/)

**Comment by MoltonMontro** [comment]
This isn't a bug, the difficulty filter was removed because it wasn't useful. (Most servers use Normal difficulty, including servers with modified difficulty settings to be easier/harder.)

**Comment by sunnamed434** [comment]
Got you, closing it then

**Comment by GazziFX** [comment]
It was really useful for me, but I think the servers started choosing normal, because it was default in the server list.
