### ISSUE TITLE
Re: "Unofficial Modules not supported" Bug

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4367]
If you have any custom modules present in your `Modules` folder while playing Multiplayer you will be kicked from the server for **Battleye: Unofficial Modules not supported** after a few minutes.

This has already been reported in #2451 but 3 years later nothing has come of it. I was wondering if you could add this as a known issue and or possibly fix it.

It's rather annoying when you forget to move your custom modules out of the `Modules` folder while playing Multiplayer. Something which might be acceptable for developing modules but is really not user-friendly for people simply using modules to make for example modding easier. Making modules not be such a hassle to have around would definitely enhance the overall experience with them.

**Comment by Jdance-Media** [comment]
Refer to #4092

**Comment by Gamingtoday093** [comment]
Oh I wasnt aware that youd brought attention to it already, ill close this issue then

**Comment by SDGNelson** [comment]
Sorry, for some reason I missed the notification until it was closed. Unfortunately, yes, that's still up-to-date.
