### ISSUE TITLE
SleekSkill on client renders constant values instead of server-side info

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4371]
The problem is client uses info about the max level that the player can get while clicking, however, in UI it renders constant values, i.e the default `PlayerSkills.SKILLSETS`, when actually must render the info that the server provided, in this case: skill.GetClampedMaxUnlockableLevel() or skill.max.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/10173914-5a59-4115-b6e1-9e94c0dc6e10

Repro:
```cs

PlayerSkills.onApplyingDefaultSkills += OnApplyingDefaultSkills;

private void OnApplyingDefaultSkills(Player player, Skill[][] newSkills)
{
     // iterate through the skills and get skill and set it to player max skill level (in my case from rocket plugin configuration)
     var skill = player.skills.skills[restrictedSkill.SpecialitySection][restrictedSkill.SpecialityIndex];
     var maxLevel = restrictedSkill.MaxLevel;
     skill.max = maxLevel;
}
```

So this is what it must look like:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/66537c21-196b-41e6-886b-aaac008fb139)

Currently, the only solutions are edit map or patch Upgrade methods to notify the player that this skill is no longer upgradable, and to give a least any feedback to the player

**Comment by SDGNelson** [comment]
`maxUnlockableLevel` is set by the level config which the client would ordinarily be able to show in the UI. The game doesn't currently support setting it by plugin, sorry.
