### ISSUE TITLE
Sentry example asset missing from ExampleAssets.unitypackage

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4372]
Sentry example asset is missing from ExampleAssets.unitypackage, even though previously it was stated to be added.

**Comment by SDGNelson** [comment]
I don't think it's ever been included because it pulls in the rest of the game's scripts as dependencies. It has been shared in a few places as an individual asset, however. Where did I say it was added to the example assets package?

**Comment by SDGNelson** [comment]
Here's the vanilla sentry without dependencies: 
[Sentry.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/14540087/Sentry.zip)

**Comment by MoltonMontro** [comment]
Following up on this, the next game update will include the Sentry gun as part of the ExampleAssets.unitypackage. :)
