### ISSUE TITLE
Inconsistency of barricades and structures' position (and rotation) when moved via build mode

### ISSUE THREAD

**Issue by realtrollman2319** [SmartlyDressedGames/Unturned-3.x-Community#4375]
This is very irritating, because you can't even build on it anymore once you move it around like 5 times, and will just cause "Blocked"
I think this has to do somewhere on `ReceiveTransformRequest` inside `BarricadeManager`.
Picture shows a building being moved around 2 times with build mode:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/108993392/e8c3cf11-3baa-4cda-a8d2-9d1f7fb35891)

**Comment by SDGNelson** [comment]
This is an unfortunate side effect of the way barricade and structure rotations are saved and replicated. Newer features directly replicate rotation as a relatively high-precision quaternion, whereas buildables use rounded euler angles. If/when reworking more aspects of how buildables work I'd like to revamp this, but no ETA at the moment based on the priorities for 2024, sorry.
