### ISSUE TITLE
Have player names align with player location on map when avatar is disabled.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4381]
Self explanatory. The player avatar normally represents the player position, but since there is no avatar you kind of just got to remember that their position is to the left of their name. Would make more sense to center the text on the player position when avatars are turned off.

**Comment by SDGNelson** [comment]
Hmm... It's a fair point, but I think it might be harder to pinpoint the center of the text than the left of the text. Maybe a 4x4 dot instead of the avatar when disabled?

**Comment by Jdance-Media** [comment]
Yeah, that is probably a better solution, but it would be wise to use a dot that is distinctly different from the waypoint/marker dot that way they don't get confused.
