### ISSUE TITLE
"Scope" animation is documented but does not work

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#4382]
I tried to experiment with what it does since it is an optional feature, but in-game, it does not work. I looked into the `UseableGun.cs` to find the line that plays the function, but the only line I found is `base.player.animator.setAnimationSpeed("Scope", speed);`. Basically, there's no way I can play the "Scope" animation.

**Comment by SDGNelson** [comment]
Sorry - Molt actually updated the docs for this recently (https://github.com/SmartlyDressedGames/Unturned-Docs/pull/316) but it wasn't merged into stable yet. I may as well merge the docs now because it doesn't have anything from the next update yet.
