### ISSUE TITLE
[Extremely Minor] Computers in St. Petersburg bank are floating

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4383]
Was playing with a friend on Russia when I noticed some of the computers were floating in the bank. Extremely minor but mind as well report it.

![2024-03-14_20-50-52](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/69433047-3df7-4318-be63-3da3272f4d4b)

**Comment by SDGNelson** [comment]
Heh, will fix.
