### ISSUE TITLE
Long pause 30-40 seconds after joining a map in linux

### ISSUE THREAD

**Issue by Zombs-R-Cute** [SmartlyDressedGames/Unturned-3.x-Community#4385]
Playing on a linux machine, within 30-40 seconds of joining a map, the game completely freezes for 5 seconds, then a few seconds later, it freezes for another 0.6 second. 

[untitled.webm](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/161528800/fcf27307-1a10-48d4-8736-110fb68f1ea8)

**Comment by SDGNelson** [comment]
Thanks for the report. Sorry about the freeze. If in singleplayer this might actually be straightforward to reproduce and investigate, but if in multiplayer that'd be much more challenging. Is that default Arid? I could try loading in at the same spot facing the same direction.

**Comment by Zombs-R-Cute** [comment]
It happens in all multiplayer maps, started last year sometime after an update.   Just got around to making a report.  
I noticed if using proton it doesn't happen, but that causes it's own issues, like randomly releasing the mouse, and end up losing focus.

**Comment by SDGNelson** [comment]
Disappointing answer, sorry, but closing as "can't/won't fix" (https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4457#issuecomment-2161320359 for more details).
