### ISSUE TITLE
Item model desynced from point

### ISSUE THREAD

**Issue by ai-kana** [SmartlyDressedGames/Unturned-3.x-Community#4386]
As seen in the video the distance is based on the item's drop point and not the model location. 

I don't believe this is a bug, so call it a feature request. 

But a fix of it would allow for a nice anti-cheat measure to be build into the game as far as item  range cheats. That being my original plan for this item distance stuffs.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109441902/3b077d85-b042-4e8c-a0fd-5a86b1b2a3a4

**Comment by SDGNelson** [comment]
This is working as intended, sorry. Currently item physics are only simulated on the client, not the server, and if they pass a certain distance they will disable physics and snap to the server's drop position. (e.g., rolling down a hill)
