### ISSUE TITLE
Vanilla commad queue_size ad don't work

### ISSUE THREAD

**Issue by 0x646F317068696E3732** [SmartlyDressedGames/Unturned-3.x-Community#4387]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/108773646/143e208a-c0f1-4fb8-be48-90f7fad63f7e)

**Comment by SDGNelson** [comment]
I expect it broke around the network transport updates, sorry. It was some temporary test thing when I was adding the server queue and hasn't been used since then.
