### ISSUE TITLE
No localization for flag reward in NPC rewards

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#4388]
When a quest has only flags as a reward, it's not really straightforward to the player. We, NPC creators, need to use experience reward (or item reward with 0x items) of 0 XP and use the localization in there in order to say what player receives. Yes, I could type it in the description, but a lot of players don't read those.

I was speaking with @iBowie about this and he wanted to create this issue for some time. He confirmed there's no override for flag reward in the npc rewards

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81763752/bd81c489-8c5a-4954-8971-763360fc992a)

**Comment by SDGNelson** [comment]
Fair point - it looks like NPC conditions will show text by default if specified, but not NPC rewards. I've now changed this for the next update.
