### ISSUE TITLE
Please add the event OnPlayerUpdateOxygen

### ISSUE THREAD

**Issue by MrRousek** [SmartlyDressedGames/Unturned-3.x-Community#4389]
Similar events exist in UnturnedPlayerEvents, but there is no Oxygen

**Comment by MrRousek** [comment]
I understand that this is from the RocketMod code. But there was already practice when you updated RocketMod command

**Comment by Jdance-Media** [comment]
But...
Isn't that just PlayerLife.onOxygenUpdated?

I feel like this is a issue/request more fitting for the actual LDM repository. You could make a PR to both LDM and RMF and see if they get accepted.

**Comment by SDGNelson** [comment]
Thanks Jdance. Also, it was probably somewhat related to the differences between the mostly-predicted-only vs always-have-been-replicated life properties.

**Comment by rube200** [comment]
There is onOxygenUpdated but could we get a global version of it?

**Comment by Jdance-Media** [comment]
Well, the global version is technically the life updated event, which is triggered for all the stats I think.
