### ISSUE TITLE
Move entire map to the center

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#4390]
Hello i asked this about 2 years ago, im asking again in the case there is a easy fix now
I changed the level dat of an insane map into a medium one and needed to redo all the trees, roads and other things on the new place of the terrain that is the lower left corner
Is there any way to change everything under the bottom left square so it moves to the center square of insane size? 

I changed the size so i can add isles but the world borders and openning the map and needing to zoom to the left square is a problem

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80723434/02770dfb-b173-4e03-950f-26a5ac7f0aac)

Also any commands for the server for better physics on cars, cars colisions, rubber band and other gameplay elements?
-ForceTrustClient helps right? What does it do and where do i add it?

**Comment by DanielWillett** [comment]
It would probably be easier for you to turn off legacy clip and water and add your own player clip and water volumes.

Include any/all of the following for that, mainly the top 3, then add all the volumes yourself.
```json
{
	"Use_Legacy_Ground": false,
	"Use_Legacy_Water": false,
	"Use_Legacy_Clip_Borders": false,

	"Use_Legacy_Snow_Height": false,
	"Use_Legacy_Oxygen_Height": false
}
```

you can then go and add/delete any tiles you want and the center of the map doesn't really matter that much, although keep in mind you still won't be able to go past the insane border because most things break after that limit is reached, so you will only be able to expand upwards (from this image) left and right.

**Comment by Lancer-TG** [comment]
So you are saying i can extend the barrier of the map until the very edge of the water? If thats the case it works for me, only need a little space so planes dont crash all the time

**Comment by Lancer-TG** [comment]
Any other experimental server commands like -ForceTrustClient or its the only one left?

**Comment by GazziFX** [comment]
> Any other experimental server commands like -ForceTrustClient or its the only one left?

Increase allowed sqrDelta is better solution than completely removing checks

**Comment by DanielWillett** [comment]
> So you are saying i can extend the barrier of the map until the very edge of the water? If thats the case it works for me, only need a little space so planes dont crash all the time

You can put the clip barriers wherever you want, even rotated, or not at all.
Example:

Here is an example of clip volumes, a water volume, and a cartography and foliage volume (hidden, covers the same area as the clip volumes).
Note this is 6 clip volumes forming a cube, not one.

The setup in this picture mimics the ones created when you use legacy settings for a small map.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/cc6c94b1-7c81-471f-851e-66d8ec78eef6)

**Comment by SDGNelson** [comment]
Thanks DanielWillett!

Also, past some point `-ForceTrustClient` only applies to vehicle movement (no longer player movement). Enabling it will allow vehicles to noclip without any speed limit.
