### ISSUE TITLE
How to add a snow to my custom map?

### ISSUE THREAD

**Issue by Devilanc762** [SmartlyDressedGames/Unturned-3.x-Community#4391]
Hi there! I trying to add a snow to mountains in my map.
And i want the weather to always be snowy in a certain place, and it could be raining in another place, for example
I tried to add snow with snow levels, but it doesn't always snow, and it can't rain at the same time elsewhere.

**Comment by MoltonMontro** [comment]
Hey @Devilanc762,

This GitHub repo is for tracking _bug reports_. For other types of posts – such as questions about the game, modding, mapping, etc. – please use a more appropriate platform. E.g., [our forums](https://forum.smartlydressedgames.com/) or [Discord server](https://discord.com/invite/unturned).

That aside, it sounds like you're trying to add multiple weather types to your map. I recommend visiting our modding documentation site: https://docs.smartlydressedgames.com/en/stable/.

Specifically, you'll probably want to read about: [Level.config](https://docs.smartlydressedgames.com/en/stable/mapping/level-config.html) → [Level.asset](https://docs.smartlydressedgames.com/en/stable/assets/level-asset.html) → [Weather.asset](https://docs.smartlydressedgames.com/en/stable/assets/weather-asset.html).
