### ISSUE TITLE
IOBS Event Hook gets triggered on object loaded

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4393]
I guess its not something that was considered during the creation of IOBS hook, so technically its not a bug, but it does cause some issues.

What I mean is: When player is far away from an object, on client it gets unloaded, and when the player re-enters the loading radius of it, the object gets loaded back, and that also triggers the events corresponding to the binary state in which object is in. This might not be an issue for objects that use it for simply playing some animation or doing some other visual change, but in case of the thing that I made, it does cause problems.

Basically I use the IOBS hook on a binary state interactable object to send certain commands from player's client via ClientTextChatMessenger to trigger a plugin function. This issue I described causes player's clients to send the command to chat everytime they re-enter the loading radius of this object, and I bet it can potentially cause problems for other people when they find some kind of creative use for this hook.

If the game could avoid unwarranted event triggers due to object culling, it would be great.

P.S. For all the people who are going to say that a plugin can do that way better than this hook: I'm not into coding, so I use the tools and pre-existing plugins that are available to me.

**Comment by prank0079** [comment]
You can add "Exclude_From_Level_Batching" to object.dat to keep the Object loaded at all times.

**Comment by SDGNelson** [comment]
Do you have `InvokeWhenInitialized` enabled?
```
/// <summary>
/// Should the OnStateEnabled and OnStateDisabled events be invoked when the object is loaded, becomes relevant
/// in multiplayer, and is reset? True is useful when visuals need to be kept in sync with the state, whereas
/// false is useful for transient interactions.
/// </summary>
public bool InvokeWhenInitialized = true;
```

**Comment by DerpyHoowes** [comment]
Alright, my bad. Thought this thing only affects objects being first loaded into the game on server join.
