### ISSUE TITLE
Invisible transform arrows in building camera (F6) on linux

### ISSUE THREAD

**Issue by ymo-4** [SmartlyDressedGames/Unturned-3.x-Community#4396]
There's not much to say: have used two distros: fedora linux and kubuntu, experienced the same issue on both. client.log says nothing about that.

[Screencast.webm](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/41833771/7e2b42e5-1a34-4763-9f98-e5821c7fe4ef)

Edit: the same happens with rotate (W) circles

**Comment by ymo-4** [comment]
Just found that this issue was previously posted in #3444. I'll try adding -FallbackGizmos as described there when i have time

**Comment by ymo-4** [comment]
Adding -FallbackGizmos fixed the problem. But why then not just make this argument used by default (use this fallback gizmos by default or something)? Or at least write something about it into client.log

**Comment by SDGNelson** [comment]
Glad to hear you found the fallback option! It might become the default someday because it's implemented in a more future-proof manner. I would like to restore some kind of debug menu to the `~` key someday and revisiting these debug features would likely happen then.
