### ISSUE TITLE
Explosion_Min_Force vector3 requires legacy _Y key

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4399]
For example, this is the legacy parsing currently used by the Bicycle:

```scala
Explosion_Min_Force_X -16
Explosion_Min_Force_Y 128
Explosion_Min_Force_Z -16
Explosion_Max_Force_X 16
Explosion_Max_Force_Y 128
Explosion_Max_Force_Z 16
```

This property should support vector3 parsing, which could look like this:

```scala
Explosion_Min_Force (-16, 128, -16)
Explosion_Max_Force_X (16, 128, 16)
```

That does not work. Instead, you have to first specify the legacy _Y key. This looks like:

```scala
Explosion_Min_Force_Y 128
Explosion_Min_Force (-16, 128, -16)
Explosion_Max_Force_Y 128
Explosion_Max_Force (16, 128, 16)
```

This applies to `Explosion_Max_Force` as well. LOD_Center, LOD_Size, and Override_Center_Of_Mass are fine.

**Comment by SDGNelson** [comment]
You're right - it's checking for the _Y key to decide whether to assign the default value or not (very old). I'll fix this on the vehicles branch.

**Comment by SDGNelson** [comment]
Thanks by the way! This should be fixed in the next private branch version.

**Comment by SDGNelson** [comment]
Note to anyone who comes across this: It's not marked as "resolved on the preview branch" yet because this fix was made in a separate branch with the WIP vehicle changes.
