### ISSUE TITLE
Removing item from WorkshopDownloadIDs.json doesn't delete item files

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#440]
I think it should do

**Comment by SDGNelson** [comment]
SteamUGC caches the downloaded items until they haven't been requested by the game for a while, so they will eventually be uninstalled.

**Comment by D-AIRY** [comment]
Do you know how long to wait? Steam docs doesn't state how long "temporarily" is. Item was removed 4 days ago and files still here. Can you manually remove item folder if it not listed in WorkshopDownloadIDs.json at server startup?

**Comment by SDGNelson** [comment]
You can remove it if you really want to, but it's not like it's loaded if it's not in the download IDs file.
