### ISSUE TITLE
a lamp through the window or wall on the map	

### ISSUE THREAD

**Issue by WilliamB0rum** [SmartlyDressedGames/Unturned-3.x-Community#4400]
Hello everyone
I found 1 mistake on structure of map oficial
it's a map Russia, in the town Yekatiburg, I found a lamp through the window or wall	, That could be a mistake through the wall of a lamp	

here I am going to present you a video	

https://youtu.be/rUBRFSTe4uU

**Comment by SDGNelson** [comment]
Thanks for the report. I'll move the lamp for the next update.

**Comment by WilliamB0rum** [comment]
You're welcome
