### ISSUE TITLE
Server advertised a different map than the one it requested to load.

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4401]
Started having this issue with my server after I updated it's map.
"Server advertised a different map than the one it requested to load."
 Tried restarting server, specifying a different map in Commands.dat (did work with PEI, still not with the original map), clearing map save folder of the server, rewriting the WorkshopDownloadID file. Nothing worked so far. I know it's maybe not the best place to post, (although I do find the fact that this issue appeared after my absolutely normal map update procedure), but it's just that I never faced this exact issue, and was unable to find any kind documentation for this exact case either.

**Comment by SDGNelson** [comment]
Can you attach the client and server log files please?

**Comment by GazziFX** [comment]
Do you have any plugin hider or something changing server info?

**Comment by DerpyHoowes** [comment]
[Uploading Rocket.log…]()
[Uploading Server_SRVGame.log…]()
Here.
And no, I dont think we have any plugins like that, or well at least I think so.

**Comment by SDGNelson** [comment]
It looks like these are both server log files. (missing client log file) That said, it looks like you were able to connect successfully - the "advertised different map" disconnect happens before the player tries to join the queue. Is it working fine now?

**Comment by DerpyHoowes** [comment]
Apparently it does, because we removed all of the new plugins we added. Dont even know which one was causing it, but there were no plugins specifically dedicated to hiding the workshop used by server or messing with the lobby/server browser page in general. Still don't know what is the issue with it.

**Comment by SDGNelson** [comment]
Glad to hear it started working!

**Comment by sunnamed434** [comment]
Sometimes it happens to me, I actually gave the server advertise updater, map, name, max online etc, but server appears in the server list and anyone can join it, however everyone who will try will be disconnected, but if you will wait about 10-15 more seconds and all things will be applied (such as new max online etc) and you can join it, maybe it make sense to don't show server in the server list until the steam game server is not initialised (of course it won't be applied to the servers without token more known as GSLT) ?
