### ISSUE TITLE
The mod hook cannot run on the server

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4402]
Recently, I have discovered that many mod hooks cannot run properly on the server. I believe that currently there are NPC global event messengers, client text messengers, and server text messengers that cannot run on the server, but can run in single player mode.

Rocket Hook cannot cause damage to any object (player vehicles, buildings, obstacles, zombies, animals) on the server, and Kill Hook cannot kill on the server
![Uploading RU2BC13MN_55XD5H5(DFVLT.png…]()

As a MOD creator and server owner with two years of experience, I believe these are very important for technological changes and plugins can be omitted. I am a hyj who often sends you emails.

**Comment by hyjhkt** [comment]
![Uploading `62A1HBJ`C8{IA10YS[CR~A.png…]()

**Comment by ai-kana** [comment]
https://unturned.info/Modding/ModHooks/
The chat hooks as stated above require special server settings, make sure those are applied. I've had these hooks work in past server side.

As for the other hooks wait for someone else!

**Comment by hyjhkt** [comment]
> https://unturned.info/Modding/ModHooks/ 如上所述的聊天挂钩需要特殊的服务器设置，请确保应用这些设置。我已经让这些钩子在过去的服务器端工作了。
> 
> 至于其他的钩子等别人吧！

Thank you very much. I did not find this answer on. cs or elsewhere. Thank you for your reminder

**Comment by hyjhkt** [comment]
> https://unturned.info/Modding/ModHooks/ The chat hooks as stated above require special server settings, make sure those are applied. I've had these hooks work in past server side.
> 
> As for the other hooks wait for someone else!

  "UnityEvents": {
    "Allow_Server_Messages": true,
    "Allow_Server_Commands": true,
    "Allow_Client_Messages": true,
    "Allow_Client_Commands": true
  },
This still doesn't work on the server, I don't understand...

**Comment by hyjhkt** [comment]
"UnityEvents": {
"Allow_Server_Messages": true,
"Allow_Server_Commands": true,
"Allow_Client_Messages": true,
"Allow_Client_Commands": true
},
This still doesn't work on the server, I don't understand...

**Comment by SDGNelson** [comment]
Thanks ai-kana, that's correct.

@hyjhkt How do you have your components configured? For example, what object are they attached to?

**Comment by hyjhkt** [comment]
@SDGNelson 
![{Q(AMQ$Y8JE A{WR5U(BD0](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/0e8e0c2a-af3d-4b0f-b25e-243aa8fda7e7)
![Q_84 EM037(X5BX({{_9~ Q](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/9a9569b4-bcb2-47de-98d6-95535cf143df)
This is when I ask the cube to send an event to GameObject within five seconds. GameObject will generate an effect, which is valid in single player mode but not on the server

**Comment by SDGNelson** [comment]
Thanks for the example. The reason is that by default the NPC Global Event Messenger only emits the event on the server. If you enable `Should Replicate` it will be emitted on the client as well.

With that change, is it now working how you expect?

Note: `SendEvent` only works *from* the server. i.e., clients cannot call `SendEvent`.

**Comment by hyjhkt** [comment]
@SDGNelson 
Does NpcGlobalEventMessenger work on animals? The layer is Entity and the label is Animal

**Comment by SDGNelson** [comment]
There's no reason it shouldn't, however the `_Dedicated` prefab is spawned on the dedicated server and the `_Server` prefab is spawned in singleplayer.

**Comment by SDGNelson** [comment]
Closing but feel free to comment and I will re-open.
