### ISSUE TITLE
The loop of TimerEventHook cannot be stopped

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4407]
If TimerEventHook is checked and 'should replicate' is selected when other hooks call 'canceltimer', and if an object with TimerEventHook is deactivated and cannot stop timing

**Comment by SDGNelson** [comment]
Can you elaborate, please? TimerEventHook doesn't have an option to replicate.

**Comment by hyjhkt** [comment]
@SDGNelson If a component with TimerEventHook is disabled after selecting a loop, the timing of TimerEventHook will not be stopped. The canceltimer method cannot end the loop

**Comment by SDGNelson** [comment]
Are you sure? It only starts the next coroutine if gameObject.activeInHierarchy is true, so disabling should also stop it. I also double-checked by connecting TimerEventHook to ActivationEventHook.OnEnabled, and when disabling the gameObject the looping timer stopped.

**Comment by SDGNelson** [comment]
Closing but feel free to comment and I will re-open.
