### ISSUE TITLE
Players cannot hear the sound of shooting when attacking animals from a distance with their backs turned.

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4408]
When the player turns their back to the long-range attacking animal, they cannot hear the sound of the long-range attacking animal firing
![1(8L3YBJBKUN2NYYIWNOWRM](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/b15eb342-456e-4c0b-bf12-b6d5840252a9)

**Comment by SDGNelson** [comment]
This doesn't sound like a problem with the game itself, but if you're triggering the audioclip from an animation the reason might be due to animation culling.
