### ISSUE TITLE
Object doesn't disable Collider when no conditions

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4412]
I have an object that must be shown only when `50006` flag is set to `true` via NPCs or somewhere else, however, when `50006` flag is set as false object is "invisible" (and it is just fine) and the player can't go through this place where this object supposed to be, it means collider stops the player, my idea if there are no conditions completed object collider must be hidden (component disabled).

Note: Once an object picked-up NPC quest is completed i.e `50007` is set to true to mark that quest is completed, and `50006` to false to hide the object

.dat file of the object:
```dat
GUID ..

Type Medium

ID ..

Has_Clip_Prefab False

Conditions 1
Condition_0_Type Flag_Bool
Condition_0_ID 50006
Condition_0_Value True
Condition_0_Logic Equal

Interactability Quest
Interactability_Effect 7
Interactability_Rewards 2
Interactability_Reward_0_Type Flag_Bool
Interactability_Reward_0_ID 50007
Interactability_Reward_0_Value True
Interactability_Reward_1_Type Flag_Bool
Interactability_Reward_1_ID 50006
Interactability_Reward_1_Value False
```

**Comment by SDGNelson** [comment]
Unfortunately, this is a limitation - conditions are only for the visibility of objects. i.e., there is no per-player collision. All vanilla and curated objects with visibility conditions do not have collision.
