### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4417]
How update server? If anyone have video

**Comment by sunnamed434** [comment]
There are a lot of ways to do that, for example, this is my `Auto-Update.bat` placed in the folder where my `steamcmd.exe` located, you can also use a dedicated unturned server from the steam, so updates are going to be automatic

```bat
@echo off
steamcmd +login anonymous +app_update 1110390 validate +quit
echo Update completed.
```

**Comment by SDGNelson** [comment]
Thanks sunnamed434. Yes, if you are using steamcmd you can update it using the same command you used to install the server. (app_update 1110390)
