### ISSUE TITLE
In game shows Workshop error logs buggy

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4420]
Probably it happened after I pressed the Page up button (to reload assets)

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/0cc2149c-3cc9-4bc4-b2f9-ef65d40f6b4d

**Comment by SDGNelson** [comment]
Thanks for the report. You're probably right about the cause. If that's the case though I'm not sure it's worth investigating further - clicking Reload on the lower-right would refresh it
