### ISSUE TITLE
How to modify workshop on the server side?

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#4422]
I remember a command to change id of workshops items so you can fix conflicts yourself
Works for other things like player dmg or vehicle speed?
Any weird problems for players like they cant use/see the modified items?

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80723434/10ed86a3-c868-4562-8cbc-19f8de1edd0a)

**Comment by SDGNelson** [comment]
Items and vehicles do have an older option `Bypass_Hash_Verification` which disables kicks if they mismatch - I suspect this is what you're thinking of.

**Comment by ItsRodrigoAl** [comment]
> Items and vehicles do have an older option `Bypass_Hash_Verification` which disables kicks if they mismatch - I suspect this is what you're thinking of.

@SDGNelson This does work for vanilla items as well? and if not, you could make it possible? With this we could change some vanilla items stats without workshop but also showing its real stats when right clicking on it (lets say, changing the Maplestrike damage to 32 and adding the `Bypass_Hash_Verification` will work well without changing to default stats after starting the server or kicking the players of the server?)

**Comment by GazziFX** [comment]
> @SDGNelson This does work for vanilla items as well on servers? and if not, you could make it possible? With this we could change some vanilla items stats without workshop but also showing its real stats when right clicking on it (lets say, changing the Maplestrike damage to 32 and adding the `Bypass_Hash_Verification` will work well without changing to default stats after starting the server or kicking the players of the server?)

Nah, it wont show real stats unless you configure it the same way on client, for damage change you can use plugins, they wont affect hash

**Comment by SDGNelson** [comment]
Yes, GazziFX's answer is correct.
