### ISSUE TITLE
shovel in rifle rack on a sedan turning into a weird bull cobra skin after a relog

### ISSUE THREAD

**Issue by gruggerfrfr** [SmartlyDressedGames/Unturned-3.x-Community#4423]
https://medal.tv/games/unturned/clips/26nTsFFlMXl8Hp/d1337ipuJSJR?invite=cr-MSw3a3gsMTk1NDUzMjgyLA

**Comment by SDGNelson** [comment]
Unfortunately, I don't think this is something I can re-create, sorry. I put a shovel on a rifle rack on the car just in case and reconnected and restarted the server without luck. It might've been that the savedata for that storage got messed up (the way item savedata works would really benefit from a rewrite), or maybe a plugin on the server modifies storage, or something else entirely.
