### ISSUE TITLE
The signal to close the inventory.

### ISSUE THREAD

**Issue by Syetag** [SmartlyDressedGames/Unturned-3.x-Community#4424]
1. **In my script, I create a new storage and send it to the player:**

>             UnturnedPlayer player = (UnturnedPlayer)caller;
>             var inventory = new Items(7);
>             inventory.resize(10, 15);
>             player.Player.inventory.updateItems(7, inventory);
>             player.Player.inventory.sendStorage();

2. **Then in the main script, I connect to the gesture change signal:**

`            UnturnedPlayerEvents.OnPlayerUpdateGesture += OnPlayerUpdateGesture;`

3. **And then when the signal is triggered with the condition gesture == PlayerGesture.InventoryClose. I'm calling the logic for my Storage when I close it:**
```
        private void OnPlayerUpdateGesture(UnturnedPlayer player, PlayerGesture gesture)
        {
            if (gesture == PlayerGesture.InventoryClose)
            {
                sellCommand.SellItems(player);
            }
        }
```
### The problem is that the inventory closing signal is triggered only if there is nothing in your hands. How else can I check if the player has closed the inventory and (if possible) the created storage.

**Comment by GazziFX** [comment]
check if he moves

**Comment by sunnamed434** [comment]
Here I described solution : https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions/4263#discussioncomment-8659990

**Comment by SDGNelson** [comment]
Thanks sunnamed434 and GazziFX for suggesting workarounds!
