### ISSUE TITLE
Another way to limit construction like claim flags?

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#4425]
Do we have any option to limit placing objets that is not a claim flag?
What would cause more lag, an ambience option for no placing objects inside it or a lot of claim flags?
I tried a zones plugin a couple years ago with restrictions zones but it was buggy
Also a no crafting zone like an ambience option would be great

**Comment by ai-kana** [comment]
A clip volume that doesn't block players can be added, its an option in the bottom right when placing it in the editor. If you're looking to not edit a map flags or a plugin are your only options.

**Comment by SDGNelson** [comment]
Thanks ai-kana! That's what I would suggest as well.

**Comment by ItsRodrigoAl** [comment]
I can help you with that, it would require RocketMod and uScript
