### ISSUE TITLE
Ambiance volumes not working

### ISSUE THREAD

**Issue by Marky2701** [SmartlyDressedGames/Unturned-3.x-Community#4427]
I have been trying to use the ambiance node to make frost effect and darkness effect and both don't work, any idea why?

**Comment by SDGNelson** [comment]
The issue tracker is more-so intended for bugs/crashes/issues than troubleshooting, sorry. We would also need more details about your setup. I'd suggest posting in one of the modding-related discussion boards like on the forum or Steam discussions and someone with experience setting up custom effects for ambiance volumes might be willing to help. I recalled seeing this video recently which may be a good point of reference for asking for help with your mod: https://www.youtube.com/watch?v=HBJg1v53QVA
