### ISSUE TITLE
NPC Text Animation "animated talking" doesn't parse some rich text

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4428]
Crosspost of the "[[Bug] NPC Rich Text Modifiers Half Working](https://forum.smartlydressedgames.com/t/bug-npc-rich-text-modifiers-half-working/24278)" forum topic.

The "animated talking" setting doesn't work with dialogue using rich text as expected. Some properties seem to be parsed (e.g., `<color>` and `<size>`) but aren't always removed from the text. Other properties like `<align>` aren't parsed at all.

**Example:** `<align=center><size=150%><color=blue>Ah, welcome, welcome</color></size></align=center>` (closing tags optional).

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/b4371ad9-badc-412b-a7ec-68b755d02faf)

**Comment by SDGNelson** [comment]
Oops I saw that post and meant to double-check, thanks. I think we currently have a few hardcoded tags supported. :S

**Comment by SDGNelson** [comment]
Thankfully this turned out to be a relatively straightforward issue! It didn't properly remove the opening tags if the first character of the message was '<'.
