### ISSUE TITLE
Vanish - packet sending

### ISSUE THREAD

**Issue by Harry5656** [SmartlyDressedGames/Unturned-3.x-Community#4430]
Hello! I'm going to make a player creator plugin which will let the player create their own character on rp server. To achieve this i wanna spawn a player in an empty room infront of bot which will have selected assets. Player could choose their hair, skin etc. Bot will be updated per every click on options.

What i need? I know how to summon a bot, but if more players join, they will see each other etc in the creator room.... So i wanna make a specific Vanish which will make them see only specific players (only their bot). To achieve this I wanna overwrite method which send level, especially player info to the others. I know that Provider class in its accept method does but there should be something like that in some update too. If I overwrite only accept it will be still sending these messages in update.

QUESTION. Dear Nelson, where can I find an update method which uses the netmessages things and sends these packets in which class?

**Comment by GazziFX** [comment]
look at PlayerManager.sendPlayerStates

**Comment by Harry5656** [comment]
> look at PlayerManager.sendPlayerStates
Yup, I'll check it. I think i've done it already but didn't check yet. It was a long time ago and I dont remember clearly what was there exactly. I made a file txt with tons of methods to check. That's why I created this thread, just wanted to be sure what should check, i wanted to spend less time.

**Comment by SDGNelson** [comment]
Thanks GazziFX. Sorry to say, however, this isn't something that's officially supported because it will involve a lot of patching of vanilla code.

**Comment by Harry5656** [comment]
But it's still possible
