### ISSUE TITLE
uconomy&shop

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4431]
How do I kill a zombie and get paid for it?

**Comment by rube200** [comment]
Why are you asking this on game repo? When that is related to modules/plugins?

**Comment by arrow12312** [comment]
This is the only help I know to delete?

**Comment by SDGNelson** [comment]
As rube200 mentioned (thanks!), this repository is for bugs, crashes, issues, etc with the base game, sorry. There may be more information in the documentation for your plugin.
