### ISSUE TITLE
The script cannot be run on the prefabricated body "Projectile".

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4434]
The following events take effect in single player mode, but not on the server. The server has enabled "UnityEvents": {"Allow-Server-Messages": true, "Allow-Server-Commands": true, "Allow-Client-Messages": true, "Allow-Client-Commands": true
In the first image, the object under 'Projectile' has an ActivationEventHook. However, when the 'Grenade Launcher' hits' Projectile ', the ActivationEventHook does not take effect.
After the grenade launcher fired a Projectile, other prefabricated items used NpcGlobalEventMessenger to send events, but the NpcGlobalEventHook on the Projectile did not receive any events

**Comment by hyjhkt** [comment]
![R@5 1S7L%}}~5HVNGPU6M8L](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/b08df8f3-f5d6-457b-965d-c933652765ff)

**Comment by hyjhkt** [comment]
![7A{@)MC505KS$EZZA4LOM 6](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/ec03693a-262e-4f1e-b940-638850bfa011)
![03E(D}))3I9NVV5}5KTVUAY](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/932b2b5b-7e68-4c11-b9ac-f509304141e4)
The script on the item prefabricated body takes effect on the server

**Comment by SDGNelson** [comment]
It sounds/appears this is more-so about the particular setup, whereas this repository is intended for bugs/crashes/issues/etc in the game rather than modding assistance, sorry.
