### ISSUE TITLE
Package Using Unity 2019.4 LTS Version Content Is Larger In Size Compared To The 2018 version

### ISSUE THREAD

**Issue by AnthonyZX2** [SmartlyDressedGames/Unturned-3.x-Community#4439]
Before Using 2018.4 LTS Version to package my bundle, it has about 50M. But After I Try in 2019.4 LTS to package my project, it seems has more than 70M. Is anyone can help me to find out how to fixed it?Thanks

**Comment by SDGNelson** [comment]
It's commendable of you to want to optimize the asset bundle size, but if it only changed after the engine update it's likely outside of your control. In the big picture a 20 MB increase is very small nowadays - I wouldn't worry about it if I were you. :)

**Comment by GazziFX** [comment]
Probably default compression method has changed, I can help with it if you send a sample
