### ISSUE TITLE
Request for FPS Cap in In-Lobby Environment

### ISSUE THREAD

**Issue by KingRami** [SmartlyDressedGames/Unturned-3.x-Community#4441]
Hi,
Could you please consider adding an option to limit the FPS in the lobby environment, maybe at 60 or 30 FPS or customizable? This would optimize performance and reduce the load on the hardware.

Thank you for considering my suggestion.

**Comment by SDGNelson** [comment]
In the arena lobby? Have you used the "framerate limit" option in the Display menu?

**Comment by KingRami** [comment]
Yes, there is an FPS limit, but this is global

I meant an FPS limit for the lobby only and a separate one for ingame

as an example:
I have 240fps ingame and I don't want to have that in the lobby if I don't join a server for 30min, that's unnecessary load for my PC.

**Comment by GazziFX** [comment]
I think fps cap when unfocused is better

**Comment by SDGNelson** [comment]
I'm inclined to agree with GazziFX that an unfocused FPS cap might be a more general solution. I've seen it in quite a few games though haven't used it personally. Do you tab out from the game while in the lobby?

**Comment by KingRami** [comment]
I must honestly say that it is sometimes like this and sometimes like that.
Sometimes I'm tabbed out and sometimes I'm just chilling in the lobby on my phone.
The best solution would be that the "Lobby Cap" is also the unfocused cap with the example of 30fps it would be good in both scenarios.
Thanks again

**Comment by SDGNelson** [comment]
I wouldn't apply the unfocused FPS while in the arena lobby because some players wouldn't want that, but in your case you could get into the habit of tabbing out while in the lobby. Is the reason just to maybe conserve electricity?

**Comment by KingRami** [comment]
The main reason is to save GPU usage, while also saving power. Because the game uses 40% usage regardless of whether it is in-game, in the lobby or tabbed out.

**Comment by SDGNelson** [comment]
I'll plan to add the unfocused FPS limit for one of the next couple updates. There will likely be a relatively small (vanilla-wise) update in the next few weeks and it probably won't be in that, but the update after that.
