### ISSUE TITLE
A very serious problem!

### ISSUE THREAD

**Issue by LolinDawson** [SmartlyDressedGames/Unturned-3.x-Community#4443]
![GOZZ}@ BIP VTF5`%P7(V](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/154049881/2b05c545-5d0c-4e90-a60c-46538329c8b1)
I got the server to subscribe to my mod, but I noticed a problem with most of the models.
![EV9H8WA1IZZW_1ALI4}SMEK](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/154049881/b1447c0c-bcdd-4f45-ae8a-306946fb9f76)
Many .dat files of mods downloaded from the server are empty.

**Comment by SDGNelson** [comment]
If I understand correctly, are they empty on your dedicated server install? It might be worth forcing a reinstall from Steam: https://support.smartlydressedgames.com/hc/en-us/articles/18254340552212-Repairing-server-workshop-install

**Comment by SDGNelson** [comment]
Closing for the meantime but feel free to comment and I'll re-open.
