### ISSUE TITLE
Flying Tanks Through Collision

### ISSUE THREAD

**Issue by SuchFlaree** [SmartlyDressedGames/Unturned-3.x-Community#4444]
We can fly tanks into air infinitely just by getting someone into driver's set in prone mode
here is a video with me(slr) and my friend(tr274) https://streamable.com/gm23t4 , sorry if its a repost.

**Comment by SDGNelson** [comment]
Unfortunately, yes, this is a known longstanding issue. If I recall correctly it's the lesser of two evils with some of the compromises related to vehicle-player physics interactions. In particular using vehicles to push players through walls and floor. It's one thing I check when we do engine updates to see whether we can fix some related issues.
