### ISSUE TITLE
InteractableDoor.updateState does not Reset Disabled Colliders

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4446]
When an `InteractableDoor` is destroyed into the pool while playing it's opening or closing animations the doors Animated Colliders will remain **Disabled** as `disableAnimatedColliders` finishes early making it permanently uninteractable. This is because the Colliders are not reset in `updateState` when the `InteractableDoor` is instantiated from the pool again.

Perhaps it could be helpful to also check other areas where you're using Coroutines that might get cancelled early, just to ensure they're being handled correctly.

**Comment by SDGNelson** [comment]
Thank you for the report - good catch! I'll ensure this is fixed for the next update.

**Comment by SDGNelson** [comment]
This will be fixed on the preview branch soon. 😉 
I put the fix in `OnDisable` so it should happen when returning to the pool. I tested by standing inside the door while the colliders were off, destroying the door, and then placing down another one.
