### ISSUE TITLE
vehicle outlines carry over to dismounted players as long as you keep the vehicle highlighted

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4447]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/27f774c8-58da-4941-bda6-e965b565b9c7

works with any vehicle of any rarity.
the outline that vehicles get when looking at them carries over to players, which is intended, but it isnt detached from them when they get off the vehicle, as long as you keep looking at them.

not too high priority honestly as its kinda obscure and doesnt do anything big like wallhack.

**Comment by SDGNelson** [comment]
Hi stas! 😄 
Thanks for the report, but unfortunately you're right that it's been like this for a long time. Outline highlights are one of the remaining third-party plugins (along with A*PFP, Json.NET, Steamworks.NET) and I don't really want to get into the weeds of sorting this out considering it seems to be fine after changing focus from the vehicle. My hope is that if/when we change to one of the newer Unity render pipelines I'll replace the outline highlights and sort this out.
