### ISSUE TITLE
Equipment weapon icon

### ISSUE THREAD

**Issue by Maximjetfs1305** [SmartlyDressedGames/Unturned-3.x-Community#4449]
Hello everyone, maybe someone knows or can tell me where to dig.
I need to receive an icon of a weapon in my hands, I know that there are icons for all items in the game files, but I already need to receive it with attachments that are installed on the weapon. that's how it is in vanilla.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/147804958/60b227ec-61c3-4073-9c9e-6e54d6beadf8)

**Comment by SDGNelson** [comment]
Unfortunately, if you want to generate icons like that you'll need to write a fair bit of client-side code, but the relevant method is `ItemTool.getIcon` which has a parameter for the "item state" specifying which weapon attachments are on the gun.
