### ISSUE TITLE
Headlamps & non vanilla NVG no longer covered by cosmetics.

### ISSUE THREAD

**Issue by Zombs-R-Cute** [SmartlyDressedGames/Unturned-3.x-Community#4456]
Vanilla NVG:
![nvg](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/161528800/0196b02f-13ab-4101-8752-2d61cda8261a)

Headlamp:
![headlamp](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/161528800/6f4045b9-f8f9-4caa-8306-6551b199d059)

**Comment by Zombs-R-Cute** [comment]
And, turns out arid nvg is no longer covered.
![Screenshot_20240509_205923-1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/161528800/874c9786-0dea-4c18-bf7d-5a59bf33a10e)

**Comment by GazziFX** [comment]
Probably a balance change as it hide nvgs lightning which reveals you at night

**Comment by SDGNelson** [comment]
Ah right, whoops! I added `Priority_Over_Cosmetic false` explicitly to a few items but not the headlamp. I'll change this for the next patch.

**Comment by Zombs-R-Cute** [comment]
Nelson, you fixed the headlamp, but the nvg of Arid, and Escalation still show.  They were hidden before.

**Comment by SDGNelson** [comment]
Currently, the default is the old behavior of hiding when wearing the cosmetic. I didn't originally intend to override the Arid, Escalation, Buak, etc balance, so it's up to their devs whether to add `Priority_Over_Cosmetic false` to those items.
