### ISSUE TITLE
Possible cause of Linux freezes when joining servers

### ISSUE THREAD

**Issue by ai-kana** [SmartlyDressedGames/Unturned-3.x-Community#4457]
When joining a server on Linux there is two freezes on normally ~5 seconds as logged by the game. A second shorter one after which is not 1.5 seconds long so is not logged.

Logs from `Provider.Update()`
```
[2024-05-10 00:19:17] Long delay between Updates: 5.101098s
```

The following is the output from `strace` during the freezes between the first log and the second log there is a 5 second time difference that is the initial freeze followed by an enumeration of all active processes that seems to only happen on a server in which both battleye and VAC is enabled.

Unturned's process ID was `10914` during this session

Watching strace in real time you can see the enumeration begin the game freeze then when its finished the game resumes, that being the small freeze after the 5 second one.

I believe at minimum the second freeze to be caused by this enumeration I can provide more logs of this happening for the 5 second freeze if needed.

What is weird to me is that this only occurs when both anti cheats are active on the server I cannot reproduce it with only one or none active. Makes it hard to tell what is making this enumeration

```
[pid 10914] 17:21:31 openat(AT_FDCWD, "/sys/kernel/tracing/trace_marker", O_WRONLY) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 access("/sys/kernel/debug/tracing/trace_marker", F_OK) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 access("/sys/kernel/debug/tracing/trace_marker", F_OK) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 access("/sys", F_OK) = 0
[pid 10968] 17:21:36 access("/sys/kernel", F_OK) = 0
[pid 10968] 17:21:36 access("/sys/kernel/debug", F_OK) = 0
[pid 10968] 17:21:36 access("/sys/kernel/debug/tracing", F_OK) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 openat(AT_FDCWD, "/sys/kernel/debug", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 openat(AT_FDCWD, "/sys/kernel", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 96
[pid 10968] 17:21:36 openat(AT_FDCWD, "/sys", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 96
[pid 10968] 17:21:36 openat(AT_FDCWD, "/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 96
[pid 10968] 17:21:36 openat(AT_FDCWD, "/sys/kernel/debug/tracing/trace_marker", O_WRONLY) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 access("/sys/kernel/tracing/trace_marker", F_OK) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 access("/sys/kernel/tracing/trace_marker", F_OK) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 access("/sys", F_OK) = 0
[pid 10968] 17:21:36 access("/sys/kernel", F_OK) = 0
[pid 10968] 17:21:36 access("/sys/kernel/tracing", F_OK) = 0
[pid 10968] 17:21:36 access("/sys/kernel/tracing/trace_marker", F_OK) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 faccessat2(0, "/sys/kernel/tracing/trace_marker", F_OK, AT_SYMLINK_NOFOLLOW) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 openat(AT_FDCWD, "/sys/kernel/tracing", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
[pid 10968] 17:21:36 openat(AT_FDCWD, "/sys/kernel/tracing/trace_marker", O_WRONLY) = -1 EACCES (Permission denied)
[pid 10914] 17:21:36 openat(AT_FDCWD, "/dev/urandom", O_RDONLY) = 96
[pid 10914] 17:21:36 openat(AT_FDCWD, "/dev/urandom", O_RDONLY) = 96
[pid 10957] 17:21:36 openat(AT_FDCWD, "/sys/kernel/debug/tracing/trace_marker", O_WRONLY) = -1 EACCES (Permission denied)
[pid 10957] 17:21:36 openat(AT_FDCWD, "/sys/kernel/tracing/trace_marker", O_WRONLY) = -1 EACCES (Permission denied)
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/version", O_RDONLY) = 96
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/cmdline", O_RDONLY) = 96
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 96
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/1/cmdline", O_RDONLY) = 125
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/2/cmdline", O_RDONLY) = 125
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/3/cmdline", O_RDONLY) = 125
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/4/cmdline", O_RDONLY) = 125
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/5/cmdline", O_RDONLY) = 125
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/6/cmdline", O_RDONLY) = 125
[pid 10914] 17:21:40 openat(AT_FDCWD, "/proc/7/cmdline", O_RDONLY) = 125
```

**Comment by ai-kana** [comment]
Seems to be the same as the issue Zombs described in https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4385

Probably should've posted there.

**Comment by SDGNelson** [comment]
Interesting, thanks for the report and analysis! If it's from the anti-cheat it might not be something we can do anything about, but I'll ask BattlEye about it on Monday in case it's something fixable from the BE Linux client.

**Comment by SDGNelson** [comment]
Wanted to reproduce locally before pestering anyone, but on my end there wasn't a hitch (fortunately or unfortunately). Ubuntu 22 LTS, updated all packages first, no proton, and joined a few servers with VAC + BE. At least as far as I'm aware it shouldn't be Proton - I double-checked the installed copy isn't the Windows version, and there's no compatibility override in the Steam > Unturned > Properties > Compatibility window.

One thing that comes to mind is my Linux partition is on an SSD. Do you have Linux on a hard drive?

**Comment by ai-kana** [comment]
My install is on an SSD.

I am also using an Arch system. Could be differences there.

**Comment by CyberAndrii** [comment]
Reproduces for me on Ubuntu.

```
[S_API FAIL] Standard callback dispatch cannot be used; manual dispatch has already been selected.
```
Writes this line exactly 500 times to `~/.config/unity3d/Smartly Dressed Games/Unturned/Player.log` on the first freeze. Nothing on the second one.

**Comment by ai-kana** [comment]
I can confirm the same thing that is logged exactly 500 times.

Here is a little more context to that logging.
```
There can be only one active Event System.
[S_API FAIL] SteamAPI_RegisterCallResult cannot be used; manual dispatch has already been selected.
[S_API FAIL] Standard callback dispatch cannot be used; manual dispatch has already been selected.
```

**Comment by ai-kana** [comment]
After attaching tail to the Player.log file the second it begins writing to it the game freezes till all 500 lines are written. 

Very similar to the process enumeration.

**Comment by Zombs-R-Cute** [comment]
Ubuntu 24.04, 23.10 my first report, installed on SSD
[S_API FAIL] SteamAPI_RegisterCallResult cannot be used; manual dispatch has already been selected.
500x [S_API FAIL] Standard callback dispatch cannot be used; manual dispatch has already been selected.

**Comment by SDGNelson** [comment]
Checked again on Ubuntu and Steam Deck but unfortunately (or fortunately) no freeze here. Was a good opportunity to use the deck client tools but weirdly enough couldn't get the Unity log file even with -logfile override on command-line, will need to revisit that.

Reproduced the [S_API FAIL] spam on my end, too. Based on when it happens and that the game / steamworks.net don't call `SteamAPI_RegisterCallResult`, I think it's likely BattlEye attempting to get the Steam "encrypted app ticket". Since mine didn't freeze when it happened I'm unsure whether it's the cause of the freeze in your case.

I'm afraid this is "above my pay grade" and unlikely to be fixed anytime soon, sorry. I'm not very familiar with Linux yet, but longer term some related projects are:
- I want to rely on Windows less. It's my main desktop OS at the moment. I've heard good things about Mint being beginner-friendly. I aim to set up a small server rack under my desk with a dedicated Linux machine for development, and then get one of level1techs' fancy KVMs to quickly switch between systems.
- Optimistic about Godot's future. If I understand correctly, many of the core developers use Linux as their main OS, so hopefully it works quite well there.
- Gradually self-hosting more services locally and gaining experience in that area. Albeit rather turnkey we've been using local pfSense and TrueNAS for a while now.
