### ISSUE TITLE
Hawaii broken :(

### ISSUE THREAD

**Issue by Darkmega18** [SmartlyDressedGames/Unturned-3.x-Community#4459]
After some recent desires to come back to continue playing unturned I asked a friend if they wanted to go back to our lovely hawaii map and continue the quests.

Unfortunately for us, it appears that a recent "editor update" i saw in a comment or two has rendered the map broken. People reporting the map is all white and the buildings are gone. 

The map itself hasn't been updated since 2022 on the workshop, but it is uploaded in your name I'm fairly certain (since I remember it was a curated or atleast featured map at one point?) 

Is there any chance at all that you might do a pass of atleast your old curated maps and make sure they're functional for the latest versions of unturned? Especially given that those maps did have loot crates and such associated with them, and so should be kept in a functional state for people to revisit as past content.
Or if that would put too much on your plate, perhaps commission or implore their original credited creators to come and give them a pass to touch them up then send them back in for a future update to put them back into a functioning state if they're still at all interested in the game?

I'd like to see our old base again and finish the map at some point  :<.
_(and then explore some of the other vanilla functioning curated maps which might have also met the same fate)_ .

**Comment by SDGNelson** [comment]
Welcome back to Unturned!

Sorry to hear of the trouble on Hawaii. I just loaded it up in 3.24.2.0 and it seemed fine to me - buildings present and non-white ground.  Which platform (Windows, macOS, Linux) are you on? After trying to load the map could you send me this log file please? https://support.smartlydressedgames.com/hc/en-us/articles/12299037547284-Where-are-the-log-files

**Comment by Darkmega18** [comment]
thats the thing. it literally doesn't appear in my game. nor does it appear in my server. it's downloaded in my steam workshop and also installed into the server's workshop map folder where the other maps are, but attempting to load it just sticks me on PEI.

So I'm just going off what others have reportedly gotten in the comments, as it's utterly nonfunctional or invisible for me. :< I did notice some people said to verify cache but all my files were verified just fine...

Maybe I'll try redownloading hawaii since it'd been sitting in there for some time.

My platform is windows 10. the log when searching hawaii seems to load it and pick it up.

*[a few minutes later]*
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/8104689/06abb891-4847-46f0-ba99-54811a50ebbc)
??? well bugger me. still doing things the old way before I had the server tool and some stuff must've changed on me? :V

**Comment by SDGNelson** [comment]
No worries - I'm glad to hear you were able to get it all working after all! And I hope you and your friend have fun returning to your old save together.
