### ISSUE TITLE
The volume box of the map editor cannot be placed using the "E" on the keyboard

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4460]
![1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/84921450-68ed-4f07-82a5-bba66bb49dc4)
The volume box of the map editor cannot be placed using the "E" on the keyboard

**Comment by Jdance-Media** [comment]
Hi, I suspect this probably has something to do with the surface mask option. Sometimes people accidently change the value, or perhaps change it without knowing what they are doing. Make sure your surface mask field is set to `1077641216` as suggested on the [SDG Support Site](https://support.smartlydressedgames.com/hc/en-us/articles/18346795651604) and remember to select what volume you want prior to pressing **` E `**.

**Comment by SDGNelson** [comment]
Thanks @Jdance-Media! That's almost certainly the reason.

**Comment by hyjhkt** [comment]
> 你好，我怀疑这可能与表面掩模选项有关。有时人们会意外地更改该值，或者可能在不知道自己在做什么的情况下更改它。确保您的表面掩模字段设置为[SDG 支持网站](https://support.smartlydressedgames.com/hc/en-us/articles/18346795651604)`1077641216`上的建议，并记住在按 之前选择您想要的体积。[](https://support.smartlydressedgames.com/hc/en-us/articles/18346795651604)**`E`**

Can you tell me which file needs to be modified? I don't know
