### ISSUE TITLE
Crop growth model not updating

### ISSUE THREAD

**Issue by ai-kana** [SmartlyDressedGames/Unturned-3.x-Community#4462]
When using `BarricadeManager.updateFarm()` to change when a planted was placed it does not updated the model in `InteractableFarm.Update()` if the plant is going from a fully grown state to non-fully grown state.

`InteractableFarm.updateState()` does update the state but doesn't replicate it to clients as `BarricadeManager.updateFarm()` does.

**Comment by SDGNelson** [comment]
This isn't something the game supports / expects to happen. Are you making a plugin which resets farms?

**Comment by ai-kana** [comment]
Yes, I am making a plugin that resets farms

**Comment by SDGNelson** [comment]
Would it work to damage the existing farm and immediately spawn a new one replacing it? Or is there some state that would be lost?

**Comment by ai-kana** [comment]
Possibly, but then I'd have to remove one of the two items. My goal is to give the harvest one of two and keep the plant so they don't have to craft seeds and replant.

While possible I don't see this as a very good fix.
