### ISSUE TITLE
The volume box of the map editor cannot be placed using the "E" on the keyboard 

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4463]
The volume box of the map editor cannot be placed using the "E" on the keyboard
I don't know which file to modify, where to modify the file, and I haven't found any explanation or guidance in the document
![329535894-84921450-68ed-4f07-82a5-bba66bb49dc4](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/064d6732-01e5-401b-ac52-456454122db9)
![3TNQ5ZTL70893RCQC)RBS)K](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/ae603edc-2232-439d-a9bd-f8f76e0d21a7)

**Comment by MoltonMontro** [comment]
The **Surface Mask** field is located in the bottom-left corner of the screen. If you're using a localization mod (it looks like you are), the field may be translated as something slightly different. But it's the bottommost field.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/05c808f9-6d01-4c37-a8ad-55b935e94c13)

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4460

**Comment by SDGNelson** [comment]
Thanks Molt!
