### ISSUE TITLE
Known old vehicles/raycasts bug

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#4465]
Hi. 

Some time ago we've discovered a new trouble with our server and tried to reproduce and debug it. So it appears that if any vehicle for any reason will stay too low on Y axis - raycasts will stop working. Due to rare latency peaks combined with any collisions it can lead to vehicle falling under ground and killing all of our plugins raycast interactions. Players will not be able to use ladders and so on... 

I tested it on PEI and Polaris and it appears that it'll teleport vehicle back right after it reaches some weird values on Y. But on freshly created map in Editor stuff will break :( Unfortunately this is also true for our server map. Here's steps to reproduce:

1. Create any new map in Editor menu
2. Simply add some terrain and player spawn
3. Create plugin with some basic command to teleport vehicle via raycast under the map (death value starts approx. after -1000000000, but you can use `float.MinValue` just for a good measure)
4. Try to use raycast with same command again on other vehicle

Optionally add some tool (another command) to return vehicle back where it was before. You'll see that raycasts returned back to normal behavior. Possibly it can be also true if vehicle is too high and its rigidbody constraints are set to freeze Y serverside. But unfortunately I don't have much spare time to inspect that. (if I recall correctly troubled cars that we fixed and that were too high also for some reason appeared outside of the map on X and Z)
Here's the method I'm using to get vehicle from raycast:

```csharp
private InteractableVehicle GetVehicleRaycast(Player player, float distance = 5f)
{
    if (Physics.Raycast(player.look.aim.position, player.look.aim.forward, out var hitInfo, distance, RayMasks.VEHICLE))
    {
        return DamageTool.getVehicle(hitInfo.transform);
    }

    return null;
} 
```

Is there any chance it'll be fixed or this should be fixed map-wise? If yes, how so? What makes vanilla map to act like that when vehicles falling under the map?

**Comment by Ankumo** [comment]
Some related issues: (just a few I've found, maybe there's more)
#4093
#4314
#3542

**Comment by SDGNelson** [comment]
Since you mention it's a custom level, do you have Use_Underground_Whitelist set to true in your level's Config.json file? That will prevent players and vehicles from going out of bounds below the terrain - it sounds like the underlying issue is that they are falling out of the level?

**Comment by Ankumo** [comment]
Hmm, well the first thing I tried obviously is to just copy config.json from PEI on a new map and it didn't work. Now I tested it again and it worked. Maybe I just accidentally scooped this variable off when I was clearing "Asset" region of config, eh? In our map config.json it is set to `false` so I guess that wraps it up. But as I'm not the one who created it I'm still not really sure this will not affect badly some fancy-hacky places. Is there any chance setting it to `true` might break something?

**Comment by SDGNelson** [comment]
Glad to hear that did the trick!

It would break any underground locations without "underground allow volumes" placed in the editor. This option relies on the mapper indicating where players are *supposed* to be able to go underground, and anywhere else is considered falling out of bounds. They should be relatively straightforward to add to the map, however.

**Comment by Ankumo** [comment]
We're now in a process of remaking some areas on the map with our huge underground tunnels system. But what if someone decides to not turn that setting on? One would face this problem too sooner or later... Shouldn't this just be enabled by default for everyone? At least for vehicles

**Comment by SDGNelson** [comment]
Ideally, yes, we recommend every map enabled this setting, especially curated maps. It defaults to false because there were something like 7+ years of maps before it was added. The defaults for old maps are currently the same as for new maps, but if we update the level config file to be writable by the game it could enable by  default for new maps.

**Comment by Jdance-Media** [comment]
Could we perhaps get a Config.json option that enables the game checking to see if vehicles are out of bounds? Perhaps have it check every time the server starts and corrects the vehicles (either by deleting them or somehow teleporting them back).

**Comment by SDGNelson** [comment]
@Jdance-Media How far out of bounds? Currently, during save it will reset vehicles with NaN or infinite positions, as well as vehicles above the max height. I think one concern was that some maps do allow vehicles to travel outside the ordinary bounds.

**Comment by Jdance-Media** [comment]
Around 100000000+ is when the problem seems to be consistently happening. Perhaps do a check on the y-axis for vehicles at a ridiculous elevation. For x and y, perhaps either have the limit be the insane bounds or a tad bit outside of it. My assumption is that this would be an optional feature/fix.

**Comment by SDGNelson** [comment]
@Jdance-Media Mixed feelings on the optional setting. Safest option is to default to off because I've seen plugins which store vehicles far off in the sky. But, if it defaults to off, servers will continue occasionally running into this issue. Will annoy some people but maybe it has to default to on.

**Comment by Jdance-Media** [comment]
Well, my assumption that the plugins that store vehicles far out are more niche and harder to come by on servers in comparison to the number of plugins that utilize raycasts. I have doubts that there will be genuine backlash to the setting being on by default, as it seems to be a greater good scenario.

If you want to go another route and have it check more often, you could have an event so a plugin could optionally decide what happens to the vehicle, but that seems really overkill in comparison to the check on load.
