### ISSUE TITLE
When in first person items in the world does not rotate to align with the viewmodel

### ISSUE THREAD

**Issue by Wittummm** [SmartlyDressedGames/Unturned-3.x-Community#4466]
In first person the item in the world(not viewmodel) does not align with the look direction. The item seems to only take account position and not rotation.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/95731023/40554b8f-c428-43e8-b937-ad6d5b1c8326

The flashlight is always facing down only moving up and down while in first person.

(I know the correct way to do flashlights with PlayerSpotLightConfig. I just wanted to mess around :> )

**Comment by SDGNelson** [comment]
Unfortunately (as you mentioned) this isn't supported, sorry.
