### ISSUE TITLE
VERY BIG MULTIPLAYER FPS PROBLEM 

### ISSUE THREAD

**Issue by xomakhamster** [SmartlyDressedGames/Unturned-3.x-Community#4467]
I was trying to understand the reason for low fps on my server.
-Numerous modification corrections did not produce any result.
-I tried using a special module to turn off the rendering of the player’s clothes and weapons.
But this did not give any result and FPS remained at the same level.
Combined with these factors, I realized that it’s not about mods and the load on the video card, but about the processor load.
I tested play on my server on another computer with a more powerful single-threaded processor (AMD Ryzen 5600) and same video card and this gave a fabulous boost of +120 fps.
From this I concluded that with a large number of players the processor is heavily loaded and FPS drops.

Next, on my main computer, I tried using the module to turn off the main transform for each player except me (steamPlayer.Player.transform)
And this gave an excellent result +(80-100) fps on my main computer.

I think you should do something about this because most Unturned players have weak hardware and experience difficulty in fps when playing on servers with 30+ online.

**Comment by SDGNelson** [comment]
Repost of #4395 on a different account? :confused:
