### ISSUE TITLE
battlaye

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4468]
Hello to you I want to ask with I can do batllaye I will not kick people with afk

**Comment by Jdance-Media** [comment]
I'm having trouble understanding where you are getting at with this. Are you asking how to prevent BattlEye from kicking players for a particular reason? Or are you asking what you can do with BattlEye?

**Comment by arrow12312** [comment]
I want battleaye to stop kicking people who are afk

**Comment by SDGNelson** [comment]
It looks like you tried to upload an image but it didn't finish uploading before you clicked "Comment."

**Comment by arrow12312** [comment]
![6345ca4d-651a-4c0b-ba2d-4a3263b48456](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/28991078/f236c876-608b-4e5c-92b0-98e5cdab458d)

**Comment by DanielWillett** [comment]
Delete everything in your Unturned/Modules folder. its not related to being AFK, just happens after a minute or so of being in the server.

**Comment by SDGNelson** [comment]
Thanks @DanielWillett! Yes, the Unturned/Modules folder needs to be empty to place on BattlEye-protected servers.
