### ISSUE TITLE
Images from mods.

### ISSUE THREAD

**Issue by Syetag** [SmartlyDressedGames/Unturned-3.x-Community#4469]
### Is it possible to use images from mods for EffectManager.sendUIEffectImageURL?

****Is it possible to store these images directly in the mod, and in the plugin determine the path to them and use local files (get them from the bundle).**
Or is it possible to get an image only via the Internet?**

**Comment by DanielWillett** [comment]
No, although would be a nice addition (along with item icons).

**Comment by Jdance-Media** [comment]
Actually yeah. If we can specify paths to certain elements then why not allow us to specify paths to images. Could just use the 'bundle.masterbundle:path/to/file' formatting.

**Comment by SDGNelson** [comment]
As DanielWillett and Jdance-Media answered (thanks!) it isn't currently supported, sorry. I agree it would be a useful potential improvement though.
