### ISSUE TITLE
I’ve noticed something on wiki, and have some questions about crafting

### ISSUE THREAD

**Issue by Nalanlinxue** [SmartlyDressedGames/Unturned-3.x-Community#4470]
It was told in wiki that spectral gems cannot be gained by crafting, and I truly didn't craft a spectral gems skin for a long time, is that true? Or it’s just that it can’t be crafted on a runic canned bean and still can be crafted on other skins 
![IMG_4847](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/170659850/d9dbb352-3ddd-4f77-91d9-b323c6effff6)
![IMG_4848](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/170659850/de0c9aac-68ed-4e5f-9381-ba8987b90dd1)

**Comment by Nalanlinxue** [comment]
@SDGNelson

**Comment by MoltonMontro** [comment]
Somewhat relevant: Holiday Spirit and Spectral Gems should've both been checkmarked as particle effects on the wiki table (just like they are in the Steam inventory filters). I've fixed this on the wiki now.
