### ISSUE TITLE
uEssentials kit

### ISSUE THREAD

**Issue by RubbleTV** [SmartlyDressedGames/Unturned-3.x-Community#4471]
I deleted uessentials to renew it, but I took a backup of the kit.json file to create the kits.I delete the kit.json file and upload a backup, but the kits do not arrive, it creates default kits.

**Comment by DanielWillett** [comment]
this repo isn't for plugins, also uEssentials is very old and newer plugins should be used instead. It's probably bad formatting in the JSON file or something, check for errors in the log.

**Comment by TH3AL3X** [comment]
> I deleted uessentials to renew it, but I took a backup of the kit.json file to create the kits.I delete the kit.json file and upload a backup, but the kits do not arrive, it creates default kits.

Hello, what version are you using?, try this one, it's full fixed [uEssentials maintained](https://github.com/TH3AL3X/uEssentials)

**Comment by SDGNelson** [comment]
Thanks DanielWillet and TH3AL3X for your helpful suggestions! As they mentioned, however, this repo isn't for plugin troubleshooting, sorry. I +1 DanielWillet's suggestion to check the formatting with a json linter and to look for errors in the log.
