### ISSUE TITLE
vacban

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4474]
![90369fdb-b604-4429-b457-89e1837a3a75](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/28991078/ae0c1716-8ac5-4cf6-b2d8-23df2a7e0aaa)
After trying to talk to steam and it didn't help, trying my luck here
I wanted to delete the ban but I couldn't.
I gave up I want to delete where it says ban 2580 days what do you think I can do something with someone who understands and can help I will be happy after 3600 hours on the game
That was 7 years ago

**Comment by rube200** [comment]
Stop bothering people with it
Don't cheat next time.
Vacban is almost always permanent and only steam can help.

**Comment by arrow12312** [comment]
With you don't know why, so it's better for you to keep quiet people with cheats destroyed my servers until I said I had to do something and I did what I did and it worked and it paid off I just asked you don't have to help or attack

**Comment by arrow12312** [comment]
I just want to delete it from my profile

**Comment by SDGNelson** [comment]
There isn't an option to hide it from your profile, sorry. Relatively recently I've learned that VAC bans are hidden from your profile after a certain period of time, so I think it's possible Valve will decide to hide old game bans at some point.

**Comment by arrow12312** [comment]
thank you
