### ISSUE TITLE
Animal movement on the server is "lagging"

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4475]
If we set "Should-Play Anims-On Edited_Server" to true and add objects to "Animal-Dedicated. prefab" in Unity, can we solve this problem: due to the large number of players placing objects on the server (the server has been running for a year and a half), the number of online players on the server, and the number of objects on the map, the animals on the server move and attack, causing them to "lag".
Today's issue is to solve the problem of animal motion lag on the server
![3E@ H@X6OBIT 25~UH$18IO](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/f519bed3-3114-4a58-bc11-3e4598f8a19f)

**Comment by SDGNelson** [comment]
How many animals do you have at a time? The game doesn't properly support more than maybe the Large or "Insane" default value. Also, the character controller move operation is one of the slowest tasks, so more animals is unlikely. This is part of why zombies don't roam around towns while idle - high CPU physics cost.
