### ISSUE TITLE
Unpainted tiles appear as black in editor.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4476]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/e40c26e9-a880-40ee-ba31-20baecddb448)

Shown in the image above, the terrain turns black when you move the camera far away from it. Once you zoom closer, it appears fine.
When you first create a map, it does this until you actually paint a material at full strength on the black parts. However, having to remember to paint the entire map using the material brush prior to doing anything is annoying. 

Credit to bruhmoment6844 on the Discord for the screenshot. I've personally experienced this issue and it is quite annoying to say the least. I'd rather not have black terrain when I zoom out to get a better view of the map.

**Comment by SDGNelson** [comment]
To properly fix this I think we'd need a custom "basemap" shader which generates the low resolution texture shown at a distance. The easiest workaround would be to use a huge brush and quickly paint the entire map. No current plan to work on this, sorry.

**Comment by Jdance-Media** [comment]
Is there any way to just replicate what the brush is doing when the map is first created? I don't see any harm in there being an actual default material applied.

**Comment by SDGNelson** [comment]
Hmm that sounds like a good workaround. Okay, I'll adjust this for one of the next few updates!
