### ISSUE TITLE
Effects and memory allocation

### ISSUE THREAD

**Issue by ZoliWorks** [SmartlyDressedGames/Unturned-3.x-Community#4477]
So long story short, effects stop working after spawning them a few times. The longer the effect is, the less you can spawn before it stops spawning completely. The effects have their lifetime configured in the .dat file.

I didn't use **-AggressiveGC** for this test as I'm sure most players don't.

For a few years now I've been using a grenade script on the effect prefabs with a fuse that's just 1 second shorter than the effect lifetime  for cleanup as it deletes the prefab and all its children. This makes it so I can keep spawning the effect time after time without issues. 

Don't know if anyone else reported this so far or not but I thought I'd make a note of this just in case. Attached a video showing a test without and with the grenade script.

[https://youtu.be/RrALZfIr5WE](url)

**Comment by GazziFX** [comment]
Probably you Destroy GameObject without proper notification to GameObjectPool and pool trying to return destroyed effect

**Comment by SDGNelson** [comment]
Do you have Lifetime_Spread set to zero? If not, the default 4 would be below the minus one lifetime occasionally.

After some similar issues with Escalation I think I'll add an Eligible_For_Pooling option to effects, similar to barricades.

That said, if the effect can be made compatible with pooling that's certainly ideal.

**Comment by ZoliWorks** [comment]
I forgot about **Lifetime_Spread**. I'll certainly add it to all current and future effects as it would solve those 1% cases where the effect breaks.

As far as making it pooling-compatible, it certainly can be done. However, that would mean I'd have to create extra effects which would increase file size. Certain servers are very adamant on the mod being as light as possible.

**Comment by SDGNelson** [comment]
Fingers crossed that resolves the issues! 🤞 
I think the pooling option will be in the patch this week, too.

**Comment by SDGNelson** [comment]
When I wrote about the Eligible_For_Pooling option I was underestimating the degree to which effects currently assume they work with the pool. I implemented the option but it was really hacked-in, so I pivoted to better handle null entries in the pool, and to do some cleanup in PoolReference.OnDestroy removing from attachments list and pool active list.

**Comment by DanielWillett** [comment]
Does that mean #4414 is possible now :) ?

**Comment by SDGNelson** [comment]
@DanielWillett Not yet, unfortunately. The issue there (IIRC) is that the *parent* needs to call ClearAttachments before destroy, but only entities that can attach bullet hits support that ATM.
