### ISSUE TITLE
I got into the texture on the Escalation map

### ISSUE THREAD

**Issue by brrt127** [SmartlyDressedGames/Unturned-3.x-Community#4479]
Video where a got into the texture: https://www.youtube.com/watch?v=NCY7XYbHqSk
My steam: https://steamcommunity.com/id/Boss12233aa/

**Comment by GazziFX** [comment]
Probably should be posted here https://steamcommunity.com/workshop/filedetails/discussion/3251926587/4326348922703778470/

**Comment by SDGNelson** [comment]
Thanks GazziFX. Also, the underlying problem looks to be this known issue, unfortunately: https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds
