### ISSUE TITLE
Map Level Config Credits Issue

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#4480]
In the single-player menu, it appears in some cases that names are missing. 

In this scenario for example.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48290038/f9f7fc94-1978-46eb-b387-699dbda54469)
Since the 2 other sections are empty, the last name of the list will be missing from the credits, only from the join menu, it will show just fine from the actual map loading screen. Here are the in-game pictures.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48290038/32a8ac3f-dcda-46b7-804e-4b1cd4390011)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48290038/2836760b-5b7a-47da-a3d0-4d684c96c45a)

Now let's do it again but, let's add an extra name in one of the 2 empty sections.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48290038/5f30d1e9-6471-4302-9615-a27185b7a138)
Here is the in-game result.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48290038/37a857e1-8c9a-4bf7-8d15-15a3ba89e1a9)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48290038/41306d14-64af-4f46-bc5e-0cbedd37d073)
this time there is no issues

**Comment by WW-TC** [comment]
To simplify it all, if the credits names are all in the same sections, and the 2 other sections remain unused, the last line of the names will be ignored in the main menu credits.

**Comment by SDGNelson** [comment]
Sorry about that. I think most likely it's getting cut off without enough vertical space in the singleplayer menu.
