### ISSUE TITLE
bug skills

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4481]
i have bug in my server after i die i not lose skills
and config its 1 lose

**Comment by GazziFX** [comment]
it works as keep multipler

**Comment by MoltonMontro** [comment]
Thanks, @GazziFX.

Yes – it's a multiplier. When set to "1", 100% of the player's skills will be kept on death. When set to "0", 0% of the player's skills are kept.

https://unturned.wiki.gg/wiki/Gameplay_config#Players

**Comment by arrow12312** [comment]
"Lose_Skills_PvP": 1.0,
      "Lose_Skills_PvE": 1.0, its not work

**Comment by Jdance-Media** [comment]
> "Lose_Skills_PvP": 1.0,
> 
>       "Lose_Skills_PvE": 1.0, its not work
> 
> 

As said just above, it is a multiplier. If you want players to lose skills you need to set the values to '0.0'.

Some of the options in the Config.json are confusingly named (some values behave differently), so it is understandable as to why you'd be confused about those two.

**Comment by arrow12312** [comment]
"VAC_Secure": true,
    "BattlEye_Secure": false,
    "Max_Ping_Milliseconds": 1500,
    "Timeout_Queue_Seconds": 15.0,
    "Timeout_Game_Seconds": 30.0,
    "Max_Packets_Per_Second": 50.0,
    "Rate_Limit_Kick_Threshold": 10,
    "Fake_Lag_Threshold_Seconds": 3.0,
    "Fake_Lag_Log_Warnings": false,
    "Fake_Lag_Damage_Penalty_Multiplier": 0.1,
    "Enable_Kick_Input_Spam": false,
    "Enable_Kick_Input_Timeout": false,
    "Enable_Scheduled_Shutdown": false,
    "Scheduled_Shutdown_Time": "1:30 am",
    "Scheduled_Shutdown_Warnings": [
      "00:30:00",
      "00:15:00",
      "00:05:00",
      "00:01:00",
      "00:00:30",
      "00:00:15",
      "00:00:03",
      "00:00:02",
      "00:00:01"
    ],
    "Enable_Update_Shutdown": false,
    "Update_Steam_Beta_Name": "public",
    "Update_Shutdown_Warnings": [
      "00:03:00",
      "00:01:00",
      "00:00:30",
      "00:00:15",
      "00:00:03",
      "00:00:02",
      "00:00:01"
    ],
    "Validate_EconInfo_Hash": true,
    "Use_FakeIP": false
  },
  "UnityEvents": {
    "Allow_Server_Messages": false,
    "Allow_Server_Commands": false,
    "Allow_Client_Messages": false,
    "Allow_Client_Commands": false
  },
  "Easy": {
    "Items": {
      "Spawn_Chance": 0.15,
      "Despawn_Dropped_Time": 600.0,
      "Despawn_Natural_Time": 900.0,
      "Respawn_Time": 50.0,
      "Quality_Full_Chance": 0.1,
      "Quality_Multiplier": 1.0,
      "Gun_Bullets_Full_Chance": 0.1,
      "Gun_Bullets_Multiplier": 1.0,
      "Magazine_Bullets_Full_Chance": 0.1,
      "Magazine_Bullets_Multiplier": 1.0,
      "Crate_Bullets_Full_Chance": 0.1,
      "Crate_Bullets_Multiplier": 1.0,
      "Has_Durability": false
    },
    "Vehicles": {
      "Decay_Time": 604800.0,
      "Decay_Damage_Per_Second": 0.1,
      "Has_Battery_Chance": 1.0,
      "Min_Battery_Charge": 0.8,
      "Max_Battery_Charge": 1.0,
      "Has_Tire_Chance": 1.0,
      "Respawn_Time": 300.0,
      "Unlocked_After_Seconds_In_Safezone": 3600.0,
      "Armor_Multiplier": 1.0,
      "Child_Explosion_Armor_Multiplier": 1.0,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Melee_Repair_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64
    },
    "Zombies": {
      "Spawn_Chance": 0.3,
      "Loot_Chance": 0.15,
      "Crawler_Chance": 0.01,
      "Sprinter_Chance": 0.01,
      "Flanker_Chance": 0.01,
      "Burner_Chance": 0.01,
      "Acid_Chance": 0.01,
      "Boss_Electric_Chance": 0.001,
      "Boss_Wind_Chance": 0.001,
      "Boss_Fire_Chance": 0.0,
      "Spirit_Chance": 0.0,
      "DL_Red_Volatile_Chance": 0.01,
      "DL_Blue_Volatile_Chance": 0.01,
      "Boss_Elver_Stomper_Chance": 0.0,
      "Boss_Kuwait_Chance": 0.0,
      "Respawn_Day_Time": 360.0,
      "Respawn_Night_Time": 30.0,
      "Respawn_Beacon_Time": 0.0,
      "Quest_Boss_Respawn_Interval": 600.0,
      "Damage_Multiplier": 0.75,
      "Armor_Multiplier": 1.25,
      "Backstab_Multiplier": 1.25,
      "NonHeadshot_Armor_Multiplier": 1.0,
      "Beacon_Experience_Multiplier": 1.0,
      "Full_Moon_Experience_Multiplier": 2.0,
      "Min_Drops": 1,
      "Max_Drops": 1,
      "Min_Mega_Drops": 5,
      "Max_Mega_Drops": 5,
      "Min_Boss_Drops": 8,
      "Max_Boss_Drops": 10,
      "Slow_Movement": true,
      "Can_Stun": true,
      "Only_Critical_Stuns": false,
      "Weapons_Use_Player_Damage": false,
      "Can_Target_Barricades": true,
      "Can_Target_Structures": true,
      "Can_Target_Vehicles": true,
      "Beacon_Max_Rewards": 0,
      "Beacon_Max_Participants": 0,
      "Beacon_Rewards_Multiplier": 1.0
    },
    "Animals": {
      "Respawn_Time": 180.0,
      "Damage_Multiplier": 0.75,
      "Armor_Multiplier": 1.25,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64,
      "Weapons_Use_Player_Damage": false
    },
    "Barricades": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Melee_Repair_Multiplier": 1.0,
      "Allow_Item_Placement_On_Vehicle": true,
      "Allow_Trap_Placement_On_Vehicle": true,
      "Max_Item_Distance_From_Hull": 64.0,
      "Max_Trap_Distance_From_Hull": 16.0
    },
    "Structures": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Melee_Repair_Multiplier": 1.0
    },
    "Players": {
      "Health_Default": 100,
      "Health_Regen_Min_Food": 90,
      "Health_Regen_Min_Water": 90,
      "Health_Regen_Ticks": 60,
      "Food_Default": 100,
      "Food_Use_Ticks": 350,
      "Food_Damage_Ticks": 15,
      "Water_Default": 100,
      "Water_Use_Ticks": 320,
      "Water_Damage_Ticks": 20,
      "Virus_Default": 100,
      "Virus_Infect": 50,
      "Virus_Use_Ticks": 125,
      "Virus_Damage_Ticks": 25,
      "Leg_Regen_Ticks": 750,
      "Bleed_Damage_Ticks": 10,
      "Bleed_Regen_Ticks": 750,
      "Armor_Multiplier": 1.0,
      "Experience_Multiplier": 1.5,
      "Detect_Radius_Multiplier": 0.5,
      "Ray_Aggressor_Distance": 8.0,
      "Lose_Skills_PvP": 1.0,
      "Lose_Skills_PvE": 1.0,
      "Lose_Experience_PvP": 0.5,
      "Lose_Experience_PvE": 0.5,
      "Lose_Items_PvP": 1.0,
      "Lose_Items_PvE": 1.0,
      "Lose_Clothes_PvP": true,
      "Lose_Clothes_PvE": true,
      "Lose_Weapons_PvP": true,
      "Lose_Weapons_PvE": true,
      "Can_Hurt_Legs": true,
      "Can_Break_Legs": false,
      "Can_Fix_Legs": true,
      "Can_Start_Bleeding": false,
      "Can_Stop_Bleeding": true,
      "Spawn_With_Max_Skills": false,
      "Spawn_With_Stamina_Skills": false,
      "Allow_Instakill_Headshots": false,
      "Allow_Per_Character_Saves": false
    },
    "Objects": {
      "Binary_State_Reset_Multiplier": 1.0,
      "Fuel_Reset_Multiplier": 1.0,
      "Water_Reset_Multiplier": 1.0,
      "Resource_Reset_Multiplier": 1.0,
      "Resource_Drops_Multiplier": 1.0,
      "Rubble_Reset_Multiplier": 1.0,
      "Allow_Holiday_Drops": true,
      "Items_Obstruct_Tree_Respawns": true
    },
    "Events": {
      "Rain_Frequency_Min": 1.3,
      "Rain_Frequency_Max": 2.6,
      "Rain_Duration_Min": 0.05,
      "Rain_Duration_Max": 0.15,
      "Snow_Frequency_Min": 1.3,
      "Snow_Frequency_Max": 4.6,
      "Snow_Duration_Min": 0.2,
      "Snow_Duration_Max": 0.5,
      "Weather_Frequency_Multiplier": 1.0,
      "Weather_Duration_Multiplier": 1.0,
      "Airdrop_Frequency_Min": 0.8,
      "Airdrop_Frequency_Max": 6.5,
      "Airdrop_Speed": 128.0,
      "Airdrop_Force": 9.5,
      "Arena_Min_Players": 2,
      "Arena_Compactor_Damage": 9,
      "Arena_Compactor_Extra_Damage_Per_Second": 1.0,
      "Arena_Clear_Timer": 5,
      "Arena_Finale_Timer": 10,
      "Arena_Restart_Timer": 15,
      "Arena_Compactor_Delay_Timer": 1,
      "Arena_Compactor_Pause_Timer": 5,
      "Use_Airdrops": true,
      "Arena_Use_Compactor_Pause": true,
      "Arena_Compactor_Speed_Tiny": 0.5,
      "Arena_Compactor_Speed_Small": 1.5,
      "Arena_Compactor_Speed_Medium": 3.0,
      "Arena_Compactor_Speed_Large": 4.5,
      "Arena_Compactor_Speed_Insane": 6.0,
      "Arena_Compactor_Shrink_Factor": 0.5
    },
    "Gameplay": {
      "Repair_Level_Max": 3,
      "Hitmarkers": true,
      "Crosshair": true,
      "Ballistics": false,
      "Chart": true,
      "Satellite": false,
      "Compass": false,
      "Group_Map": true,
      "Group_HUD": true,
      "Group_Player_List": true,
      "Allow_Static_Groups": true,
      "Allow_Dynamic_Groups": true,
      "Allow_Lobby_Groups": true,
      "Allow_Shoulder_Camera": true,
      "Can_Suicide": true,
      "Friendly_Fire": false,
      "Bypass_Buildable_Mobility": false,
      "Allow_Holidays": true,
      "Allow_Freeform_Buildables": true,
      "Allow_Freeform_Buildables_On_Vehicles": true,
      "Timer_Exit": 10,
      "Timer_Respawn": 10,
      "Timer_Home": 30,
      "Timer_Leave_Group": 30,
      "Max_Group_Members": 0,
      "Explosion_Launch_Speed_Multiplier": 1.0,
      "AirStrafing_Acceleration_Multiplier": 1.0,
      "AirStrafing_Deceleration_Multiplier": 1.0,
      "ThirdPerson_RecoilMultiplier": 2.0,
      "ThirdPerson_SpreadMultiplier": 2.0
    }
  },
  "Normal": {
    "Items": {
      "Spawn_Chance": 0.35,
      "Despawn_Dropped_Time": 600.0,
      "Despawn_Natural_Time": 900.0,
      "Respawn_Time": 100.0,
      "Quality_Full_Chance": 0.1,
      "Quality_Multiplier": 1.0,
      "Gun_Bullets_Full_Chance": 0.05,
      "Gun_Bullets_Multiplier": 0.25,
      "Magazine_Bullets_Full_Chance": 0.05,
      "Magazine_Bullets_Multiplier": 0.5,
      "Crate_Bullets_Full_Chance": 0.05,
      "Crate_Bullets_Multiplier": 1.0,
      "Has_Durability": true
    },
    "Vehicles": {
      "Decay_Time": 604800.0,
      "Decay_Damage_Per_Second": 0.1,
      "Has_Battery_Chance": 0.8,
      "Min_Battery_Charge": 0.5,
      "Max_Battery_Charge": 0.75,
      "Has_Tire_Chance": 0.85,
      "Respawn_Time": 300.0,
      "Unlocked_After_Seconds_In_Safezone": 3600.0,
      "Armor_Multiplier": 1.0,
      "Child_Explosion_Armor_Multiplier": 1.0,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Melee_Repair_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64
    },
    "Zombies": {
      "Spawn_Chance": 0.25,
      "Loot_Chance": 0.5,
      "Crawler_Chance": 0.15,
      "Sprinter_Chance": 0.15,
      "Flanker_Chance": 0.025,
      "Burner_Chance": 0.025,
      "Acid_Chance": 0.025,
      "Boss_Electric_Chance": 0.0,
      "Boss_Wind_Chance": 0.0,
      "Boss_Fire_Chance": 0.0,
      "Spirit_Chance": 0.0,
      "DL_Red_Volatile_Chance": 0.0,
      "DL_Blue_Volatile_Chance": 0.0,
      "Boss_Elver_Stomper_Chance": 0.0,
      "Boss_Kuwait_Chance": 0.0,
      "Respawn_Day_Time": 360.0,
      "Respawn_Night_Time": 30.0,
      "Respawn_Beacon_Time": 0.0,
      "Quest_Boss_Respawn_Interval": 600.0,
      "Damage_Multiplier": 1.0,
      "Armor_Multiplier": 1.0,
      "Backstab_Multiplier": 1.25,
      "NonHeadshot_Armor_Multiplier": 1.0,
      "Beacon_Experience_Multiplier": 1.0,
      "Full_Moon_Experience_Multiplier": 2.0,
      "Min_Drops": 1,
      "Max_Drops": 1,
      "Min_Mega_Drops": 5,
      "Max_Mega_Drops": 5,
      "Min_Boss_Drops": 8,
      "Max_Boss_Drops": 10,
      "Slow_Movement": false,
      "Can_Stun": true,
      "Only_Critical_Stuns": false,
      "Weapons_Use_Player_Damage": false,
      "Can_Target_Barricades": true,
      "Can_Target_Structures": true,
      "Can_Target_Vehicles": true,
      "Beacon_Max_Rewards": 0,
      "Beacon_Max_Participants": 0,
      "Beacon_Rewards_Multiplier": 1.0
    },
    "Animals": {
      "Respawn_Time": 180.0,
      "Damage_Multiplier": 1.0,
      "Armor_Multiplier": 1.0,
      "Max_Instances_Tiny": 4,
      "Max_Instances_Small": 8,
      "Max_Instances_Medium": 16,
      "Max_Instances_Large": 32,
      "Max_Instances_Insane": 64,
      "Weapons_Use_Player_Damage": false
    },
    "Barricades": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Melee_Repair_Multiplier": 1.0,
      "Allow_Item_Placement_On_Vehicle": true,
      "Allow_Trap_Placement_On_Vehicle": true,
      "Max_Item_Distance_From_Hull": 64.0,
      "Max_Trap_Distance_From_Hull": 16.0
    },
    "Structures": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      "Melee_Repair_Multiplier": 1.0
    },
    "Players": {
      "Health_Default": 100,
      "Health_Regen_Min_Food": 90,
      "Health_Regen_Min_Water": 90,
      "Health_Regen_Ticks": 60,
      "Food_Default": 100,
      "Food_Use_Ticks": 300,
      "Food_Damage_Ticks": 15,
      "Water_Default": 100,
      "Water_Use_Ticks": 270,
      "Water_Damage_Ticks": 20,
      "Virus_Default": 100,
      "Virus_Infect": 50,
      "Virus_Use_Ticks": 125,
      "Virus_Damage_Ticks": 25,
      "Leg_Regen_Ticks": 750,
      "Bleed_Damage_Ticks": 10,
      "Bleed_Regen_Ticks": 750,
      "Armor_Multiplier": 1.0,
      "Experience_Multiplier": 1.0,
      "Detect_Radius_Multiplier": 1.0,
      "Ray_Aggressor_Distance": 8.0,
      "Lose_Skills_PvP": 1.0,
      "Lose_Skills_PvE": 1.0,
      "Lose_Experience_PvP": 0.5,
      "Lose_Experience_PvE": 0.5,
      "Lose_Items_PvP": 1.0,
      "Lose_Items_PvE": 1.0,
      "Lose_Clothes_PvP": true,
      "Lose_Clothes_PvE": true,
      "Lose_Weapons_PvP": true,
      "Lose_Weapons_PvE": true,
      "Can_Hurt_Legs": true,
      "Can_Break_Legs": true,
      "Can_Fix_Legs": true,
      "Can_Start_Bleeding": true,
      "Can_Stop_Bleeding": true,
      "Spawn_With_Max_Skills": false,
      "Spawn_With_Stamina_Skills": false,
      "Allow_Instakill_Headshots": false,
      "Allow_Per_Character_Saves": false
    },
    "Objects": {
      "Binary_State_Reset_Multiplier": 1.0,
      "Fuel_Reset_Multiplier": 1.0,
      "Water_Reset_Multiplier": 1.0,
      "Resource_Reset_Multiplier": 1.0,
      "Resource_Drops_Multiplier": 1.0,
      "Rubble_Reset_Multiplier": 1.0,
      "Allow_Holiday_Drops": true,
      "Items_Obstruct_Tree_Respawns": true

**Comment by SDGNelson** [comment]
Thanks everyone for helping explain the setting!
