### ISSUE TITLE
cutscene mode does not hide player model in third person?

### ISSUE THREAD

**Issue by wristcry** [SmartlyDressedGames/Unturned-3.x-Community#4485]
not sure if its supposed to work like that
[0___o](https://www.youtube.com/watch?v=BGN-6CWS3DE)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/32246563/6085c81c-0e1e-4728-8b7f-aa584b345d24)

most useless thing in my opinion btw
it does not:
1. prevents player from moving
2. prevents player from punching
3. prevents player from rotating
4. prevents player from using barricades, from using items like detonator... shortly: from doing anything except shooting, eating and using melee weapons/throwables
5. hides any ui

why is it even called "cutscene" mode? 0_o

**Comment by SDGNelson** [comment]
Yes, it works as-intended. It was added to help with a couple specific spots in Escalation.
