### ISSUE TITLE
EVehicle Battery Bugs

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4486]
If a vehicle reaches 0 battery, as long as the driver doesn't exit, the vehicle is still drivable, only the sounds stop.

If BatteryMode_Empty is set to Charge, and the battery is completely empty, the vehicle will not charge.

Here are the .dat settings I'm using on my test vehicle.

```

Battery_Powered true
BatteryMode_Empty Charge
Battery_Charge_Rate 10
BatteryMode_Driving Burn
Battery_Burn_Rate 100

```

**Comment by SDGNelson** [comment]
Thanks for the report. Will need to fix the driving with zero battery on the vehicles branch.

Note BatteryMode_Empty is for when the vehicle doesn't have a driver, not when the battery is at zero.

**Comment by Spebby** [comment]
> Note BatteryMode_Empty is for when the vehicle doesn't have a driver, not when the battery is at zero.

I probably should have said this more clearly; this does work as expected when the battery is at 1% and the driver is not in the vehicle. However if the battery is at 0% and the driver isn't in the vehicle, it will not charge. I'm assuming the vehicle maybe "consumes" the battery and thus there's nothing to charge when battery hits 0%? This behaviour exists regardless of if the player can steal the battery.

**Comment by rube200** [comment]
I think some Devs don't want for batteries at 0% to vanish, so they can make a system to charge or something

**Comment by CyberAndrii** [comment]
Related issue: helicopter's rotors are spinning when there's 0% fuel
