### ISSUE TITLE
"Focusing" camera type slowly moves away from player when spinning around

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4487]
https://streamable.com/kf5mzl streamable because 78mb lol

holding D slowly moves the camera away from yourself while in the shift + F6 camera focusing mode
this makes simple videos of rotating difficult to seamlessly loop, as a full rotation will be slightly closer/farther than before.

**Comment by SDGNelson** [comment]
Can see how seamless loop would be useful. This should be a relatively straightforward fix (just keeping the magnitude of orbit offset the same after horizontal movement in focusing mode).
