### ISSUE TITLE
Spirit Zombie Boss doesn't have bullet resistance

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4489]
Bullet resistance was initially added for spirit zombies. Could be intentional, but the only zombies with bullet resistance are Spirit Zombies and the Stomper Zombie Boss (Elver).

Spirit Zombie Boss was added later (for Ireland) – maybe that's why it doesn't have bullet resistance?

**Comment by SDGNelson** [comment]
Weird oversight 🤔

**Comment by SDGNelson** [comment]
Thanks for the report by the way. The reason I wrote "will investigate" was that hopefully I'd have a note as to *why* it was like that, but unfortunately not. I think it's reasonable to assume it was supposed to have bullet resistance though.
