### ISSUE TITLE
Bug If you are in the technique behind the turret and they kill you, that's what happens

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#449]
![screenshot](https://user-images.githubusercontent.com/32962870/48304587-347c1100-e55f-11e8-89da-552a3f727ac1.png)

Another mistake: if you throw a grenade under a tank, then the player’s damage goes away, please correct it.

**Comment by SDGNelson** [comment]
Was this with a custom vehicle? Just experimented around in multiplayer with the vanilla tanks and wasn't able to replicate it. May be something mis-configured with the custom vehicle, and in that case I should correct the game to properly handle it.

As for grenades, armored vehicles reduce explosive damage.

**Comment by VitaxaRusModding** [comment]
Well, it's probably a matter of modification, but what do you say to that: If you throw a grenade under a tank, then everyone who sits in the tanks will be wounded or completely killed.

**Comment by VitaxaRusModding** [comment]
In the screenshot I was kill by an explosion when I was sitting behind the turret.

**Comment by SDGNelson** [comment]
Was it a modified vehicle though? Alternatively, if you know which custom vehicle it was you could send it over and I could try replicating the bug with it.

**Comment by SDGNelson** [comment]
Okay, will close the issue then.
