### ISSUE TITLE
A couple of bugs that I found at the "Zavod"

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4492]
1.how to get permamently stuck inside of a tank 
https://youtu.be/yEcMzMdQUjM
2.how to get in the tank tower (applies to all towers that lie on the ground)
https://youtu.be/_dSP8P6FbfY

**Comment by SDGNelson** [comment]
Thanks for the report. The inside of the tank is essentially the same answer as your bookshelf report, but I will add collision to that part of the tank turret.
