### ISSUE TITLE
How to hide loot inside of a plane om Russia Volk Militay Base

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4493]
https://youtu.be/_Qy0hqlXxok
I belive it is posiible to place a bed there but i didnt maneged yet

**Comment by SDGNelson** [comment]
Thanks for the report. Unfortunately, there are a lot of issues like this with older models (e.g., house roofs), so I'm not sure it's worth fixing one if not going through all of the old content.
