### ISSUE TITLE
Modules displayed as "Name" on costom weapons from liberator 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4494]
![Unturned_WmvWUvGL89](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/134800978/5f5f5597-e85e-4cb6-924d-f59b47623388)
same with ace with 8x scope

**Comment by SDGNelson** [comment]
Thanks for the report. Currently, when a gun doesn't support an attachment in that slot, it will show it in the description if it doesn't match the default attachment for that slot. Perhaps what I'll change is to not show the name if one isn't set.
