### ISSUE TITLE
The paint in the parking lot turns everything it touches yellow 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4496]
https://youtu.be/pT9aoMMo0Cs

btw Im finding a lot of small bugs and idk how to send them all in one issue or separately

**Comment by Jdance-Media** [comment]
Not sure if that can be considered a true bug, as that is how those decals are supposed to act when in Deferred. Perhaps lowering them into the ground more might work? The problem is that the forward version of the decals might be hidden then.

**Comment by SDGNelson** [comment]
Thanks Jdance! Buildable items can receive decals so that bullet holes are visible on them. Thanks for the report, but I don't think this is a big concern.
