### ISSUE TITLE
Can't upload workshop if you are banned

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#4498]
I don't know if you are checking that obviously or you can disable that, but i'm getting this, cause i'm banned from the game, and i want to upload some stuff to the workshop, I understand that it doesn't let you play and that it only allows you to play on servers without battleye or without vac, but why should it restrict uploading things to the workshop?

`Failed to create or update item. Steam error code: k_EResultBanned`

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/13141042/9d08f5a4-a986-4fe3-b59d-825af4461863)

**Comment by Jdance-Media** [comment]
From what I'm aware, if you are VAC banned some community features are limited by Steam. Higher probability that this is Steam and not Unturned.

**Comment by SDGNelson** [comment]
Thanks Jdance, yes, I believe this is just how it is. I think it's a reasonable precaution.
