### ISSUE TITLE
Loot is respawning too fast

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#450]
Hello again! So i reported to you the "loot respawn when relog" bug.
You fixed it but since that "update" there is a new bug. I mean i only get report about it since you fixed the above mentioned one.
So the bug is as the issue name say,the loot is respawning so fast. On a default configured server, you can get a lot of raiding ammo in a very short time.
https://cdn.discordapp.com/attachments/330031205003165698/510889371218739211/unknown.png
https://cdn.discordapp.com/attachments/330031205003165698/510889411257434139/unknown.png
This, and a lot more was looted in like a half hour on a server where the loot chance & respawning is default. One player did this loot, on ONE location. (Washington, Military base)

So we tried to replicate this bug on a fresh wiped PEI, with fresh config, etc. No plugins, no modifications.
Here is the result: https://youtu.be/YbN-c8Zz1ug
0:24 > 3:54 or 2:30 > 3:10
He goes back to exact same location where all loot is respawned in a short time. (40second at 2:30 to 3:10) This "bug" is there on all the map (at least i got reports from russia, pei and washington maps)
I believe it has something to do with the last change you made due to my report.

**Comment by SDGNelson** [comment]
I believe it's using the values from the config as-intended, but who knows how long that bug was there. It will try to keep each map grid cell Spawn_Chance of total spawns full, re-spawning each Respawn_Time, but the values may need some tuning.

**Comment by SDGNelson** [comment]
It's not a bug, just that the default value is too low now that the original issue was fixed. In the next update the default values are about 3x+ higher, but that won't override existing config.
