### ISSUE TITLE
Lagging ground texture on Krovi 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4500]
https://youtu.be/TCVGX7Jy_Go

**Comment by MoltonMontro** [comment]
To clarify, it looks like this is just z-fighting between the two roads placed here (not lagging).

**Comment by Happy12222** [comment]
> To clarify, it looks like this is just z-fighting between where the two roads meet at the Krovi Estate entrance (rather than lagging).

You sound like you know more then me so I will just agree with you
