### ISSUE TITLE
drop

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4501]
why not get drop i have 100h in game and i not get drop (skin free or box)

**Comment by Jdance-Media** [comment]
Item drops were disabled a long time ago as a measure to prevent botting. This is not a bug.[SDG Support Article](https://support.smartlydressedgames.com/hc/en-us/articles/12110874710164-Playtime-item-drops)

**Comment by arrow12312** [comment]
sucks thank you very much

**Comment by SDGNelson** [comment]
Thanks Jdance!
