### ISSUE TITLE
How to make the magazine appear earlier when performing a reload animation

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4502]
![Y_D4$FI(FJJ7GLWQJVO$YSD](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/21e5662a-d487-4773-a603-0e608abcfaba)
![`PKOM(X7YXAO%36E{P$90JN](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/021130a3-f789-4d03-91c5-6cc953275f81)

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/af0ba323-d7d8-463a-b5fb-6b0a3dd6a118

**Comment by hyjhkt** [comment]
Based on the video above, I would like to know how to make the magazine model appear earlier so that I can scale the multi bone model to 0

**Comment by SDGNelson** [comment]
Nice work, that looks quite impressive! Note, however, that the tracker here on GitHub is for bugs/crashes/issues, not modding support.

Since Unity's Animation component references bones and transforms by name, you can animate children of the Item prefab which might do what you need in this case.
