### ISSUE TITLE
Dusk Skins

### ISSUE THREAD

**Issue by DustyOwO** [SmartlyDressedGames/Unturned-3.x-Community#4504]
The dusk skins in the inventory ingame are broken, they come out as a horrible brown instead of their pretty red colour that they normally have, both my maplestrike and nightraider are like this, i dont have the dawn skins so i cant check those
![20240616105456_1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/97802758/a90ecff2-8074-450a-a2bb-ceb6f7eac946)

**Comment by SDGNelson** [comment]
Personally, I think that looks kind of cool. The reason it doesn't appear the same in that preview as it does in-game is that it uses colors from the per-map day/night cycle.
