### ISSUE TITLE
Unturned (3.24.3.3) Mansion roof glitch

### ISSUE THREAD

**Issue by Williriano** [SmartlyDressedGames/Unturned-3.x-Community#4508]
I found a glitch mansion roof in Krovi Estate

https://youtu.be/1U5yJKvmrNA?si=wkim6340MVB0if71

**Comment by Happy12222** [comment]
I have already reported that bug and nelson said that this is known issue

**Comment by SDGNelson** [comment]
Yes, I'm afraid it's the same underlying issue as, sorry: https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds
