### ISSUE TITLE
Beta Branch Pre-3.22.4.0

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4509]
I'm unsure if this page is the right place to post this since this is technically a request, not a bug report, but it's technical enough and generally "community focused" enough that it could belong here.

3.22.4.0 removed support of Content files completely. There will be maps on the workshop which used these files but never got updated to masterbundle only. The most recent archive which supports Content files is Unity 2018: 3.20.13.2, which will be missing a lot of features that some of these maps may have used. I feel this was a major enough change to warrant its own branch for preservation purposes, just as most major Unity upgrades received a branch.

**Comment by SDGNelson** [comment]
Is this purely theoretical, or do you know of a workshop map where it's an issue? Outside of a few curated maps, most levels back then opted to use the older Details.unity3d file until support for that was replaced. Ideally this would be something we did back then.

**Comment by Spebby** [comment]
> Is this purely theoretical, or do you know of a workshop map where it's an issue? Outside of a few curated maps, most levels back then opted to use the older Details.unity3d file until support for that was replaced. Ideally this would be something we did back then.

This is mostly theoretical. I do have some personal projects that I've lost the sources to that depend on .content but I don't think it's out of the question that there probably is something on the workshop that uses .content. Understandable if a lack of a proper example makes this not a planned addition.

**Comment by SDGNelson** [comment]
Closing for the meantime then. 👍
