### ISSUE TITLE
Game update causes abnormal material display

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4510]
![X3CV0$ENS4GD(J@)ZOQ669J](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/3dd075fa-bb37-41ef-b2c2-40a201f31b05)
If the shader used by the shader is not "standard" but other, such as Image 1, then when imported into the game, it will display "white paper"，Second picture

![c310075d533d16ceb16bcd6165e020df](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/04ceb3ce-7468-4ded-9bfc-b12b24bc4793)

It will also turn purple

![EA)OKM%R}$VR07GCBBB8H`Y](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/9e96259c-78fa-4558-99d0-31057f06be70)

Nowadays, some creative workshop items, such as items with changed skin and special effects, use shaders other than "standard". We hope this issue can be fixed as soon as possible

**Comment by SDGNelson** [comment]
One reason for this could be if `Asset_Bundle_Version` is missing or a lower version that required the game to replace missing shaders.

That said, custom shaders are not something we officially support.
