### ISSUE TITLE
Request for placement tags on objects / barricades.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4514]
Hello, this request sounds pretty simple but outlines something that would be of invaluable modding usage;
Tags, or modifiers to determine on what a barricade could be placed, EG:

A sentry with the following tags:
```
Allow_Placement_On Walls
Allow_Placement_On Ceiling
Disallow_Placement_On Floor
```
Would not allow the sentry to be placed on the floor, but would allow it on the walls and ceiling.
Pretty self explanatory realistically, however it would allow for more creative freedom with certain barricades.

**Comment by SDGNelson** [comment]
I would like to do something along these lines as part of rewriting barricade placement, but there's no current ETA and the issues list tracker isn't for feature requests, sorry.
