### ISSUE TITLE
Cannot undo volumes position change with e with [ CTRL + Z ].

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4515]
The behaviour appears to be super buggy with the Underground Whitelist volume.

Placing an underground whitelist, scaling it and moving it and then changing a different volume and pressing CTRL + Z on it's adjustments will still apply the CTRL + Z to the initial volumes adjustment undoing what was done on the other volume even though other changes have been made in the meantime.

**Comment by SDGNelson** [comment]
I tried reproducing your instructions and it worked as-expected for me at least. Can you elaborate on an example of what's not working, please?

**Comment by Axodouble** [comment]
It appears I cannot recreate it either, must have been a more obscure issue than I thought, I will make a new report once I find it.
