### ISSUE TITLE
Outdated InteractableObjectQuestEventHook.cs

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4517]
The current version of `InteractableObjectQuestEventHook.cs` in Project.unitypackage is outdated and doesnt support the new replication to clients added about a Month ago

**Comment by SDGNelson** [comment]
Sorry about that! IIRC it was added to resolve an Escalation issue so I must have sent it specifically to NSTM. It should be up-to-date in the next update as I exported it recently, but here's a copy in the  meantime: 
[Download Project.zip (28 KB)](https://github.com/user-attachments/files/15959969/Project.zip)
