### ISSUE TITLE
How to modify the damage value of a destroyed vehicle's explosion

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4518]
I would like to know how to modify the explosion damage of a destroyed vehicle. I need to solve the problem of accidental vehicle explosion and obstacle damage caused by the release of the cloud garage plugin

**Comment by SDGNelson** [comment]
Sorry to say this isn't configurable per-vehicle at the moment aside from `ShouldExplosionCauseDamage false`, but a server plugin can filter the damage from `EDamageOrigin.Vehicle_Explosion`.
