### ISSUE TITLE
Huge problem with magazines for most skins

### ISSUE THREAD

**Issue by Semidvista** [SmartlyDressedGames/Unturned-3.x-Community#4519]
In the dusk and dawn skin lines, as well as in all common and uncommon rarity skins, the skin color that applies to any other modules is not applied to magazines
If we take muzzle and military drum as an example, then both of them have the Paintable tag in their config, which means that they should be painted in the color of the skin

![notepad++_nejERYZbkp](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/8ced2a42-a905-493b-af82-300f70500c56)
![notepad++_zTBFs9gR7z](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/24bad0ef-8986-431e-a308-888555e9f2ce)

Dusk, dawn, common and uncommon skins have the following tags in their description:
Layered Attachments
Fallback Attachments

![chrome_89GM0xhvct](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/4c41452d-6758-40ac-a1f1-99da141ac16e)
![chrome_YhTeXHar5k](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/138da6bc-3030-4d59-bb71-f47de3d12819)

![chrome_gTWVQFHsrB](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/5509eefa-7890-4c99-8024-82d8ccf126f5)
![chrome_gdkzVPBU3U](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/7eb0ae90-25fd-4bd9-9830-006eaab8edfb)

Which means that they should paint all the modules that are installed on the weapon, but this does not happen

![Unturned_XkNR1jYZWv](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/77673ebe-2584-4c09-9f77-bc3ff3d4f181)

But at the same time, any other unique skin, colors the magazines as it should, even without having in its description a line with a unique skin for a particular weapon module
(an example of such a skin was Phantox Zubeknakov with ranger drum, which is not in the skin description, but it is still painted)
Following the logic, magazines and drums should be painted on the Dusk, dawn, common and uncommon skins too

**Comment by SDGNelson** [comment]
Thanks for the report, but I believe the reasoning was that it looks more interesting for the magazine to retain its material if the skin doesn't have a magazine-specific skin. 🤷‍♂️
