### ISSUE TITLE
Going through a ladder?

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#452]
We just accidentally found this "bug".
It isn't too important, not even useful for abusers, but i thought i should report it aswell.
You can just go through the ladder at the Tower in Heritage Valley (Washington map)
https://youtu.be/P3rIm2Pz7sY

**Comment by SDGNelson** [comment]
It's intentional, you can't climb ladders when an item has marked itself as busy.
