### ISSUE TITLE
[Preview Branch] Vehicle Engine sound stops after getting submerged and leaving water

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4522]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/dd8d3326-e5b3-4fff-92ae-5e983714b3fd

Vehicle Engine sound stops after getting submerged in water and leaving water.

**Comment by SDGNelson** [comment]
Thanks for the report!
