### ISSUE TITLE
Decal scale gets influenced on scaled objects by the parent object's scale

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4523]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/1d2f7cf8-90c5-41dc-a99c-0f330f8b6d9d)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/dbd571da-91d2-449f-ad3f-b28c0cc4b0ed)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/b9e51ff5-d935-4ef2-b2b5-311235fba072)

The decals appear stretched on scaled objects.

**Comment by SDGNelson** [comment]
Thanks for the report. I'll see about taking the parent scale into account when attaching them but off the top of my head it might not be possible to fully eliminate especially with a "skew" transform.

**Comment by SDGNelson** [comment]
After checking into this I'm sorry to say it's already preserving the world position+rotation+scale when attaching, so I don't think this is something the game can mitigate. This is one reason to prefer scaling objects uniformly where possible, i.e., same scale value on each axis.
