### ISSUE TITLE
Scope Quality - Off overlay prevents pause menu from appearing

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4524]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/bef0bf00-49e8-4ff5-bbe3-cdc049157b5c

The playercamera gets blurred as expected, but the pause menu does not appear.

**Comment by SDGNelson** [comment]
Thanks for the report, but this is not a big deal IMO and messy to fix with the way the menu system works as-is. Ideally would be improved as part of rewriting how the menus work.
