### ISSUE TITLE
[Preview Branch] Custom Vehicle shader lacks metallic maps

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4525]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/87e2b4b7-5844-4800-8518-28d828cff7f4)

Currently the custom vehicle shader provided in the examples, does not support metallic maps nor emission.
Expanding the shader with metallic maps and emission maps could be really useful for certain vehicles.

**Example solution**
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/7148e41f-2182-483f-8234-faf5a49ce205)

**Comment by SDGNelson** [comment]
I agree it could be a useful improvement, but I didn't want to focus too much on making a more complicated shader + shader inspector. In the meantime if you need metallic maps one option would be to have a separate material for the metallic parts of your car, as the paintable sections can specify a material index.

**Comment by elsultaan** [comment]
Iirc, if the vehicle has more than one material, those will not get tinted black if the vehicle explodes. But I guess the OnExploded event will provide a solution to that issue.

I quickly threw a prototype together which seems to work well, so if anyone sees this issue and would like to still use the custom Vehicle shader, I will leave my edited version here, with proper credits included as comments.

**The shader ingame:**
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/d6b95157-abf2-4b7b-99e2-ad7a812eae2b)

**Shadercode:**

`// Created by Nelson Sexton - Smartly Dressed Games
// Modified to have the option of metallic and emission maps.
// Lacks a CustomEditor (StandardShaderGUI for example) to improve inspector usage.

Shader "Unturned/VehicleMetallic"
{
    Properties
    {
        [Header(Color Settings)][Space]
        _Color ("Tint Color", Color) = (1,1,1,1)
        _PaintColor ("Paint Color", Color) = (1,1,1,1)
        _MainTex ("Albedo (RGB)", 2D) = "white" {}

        [Header(Metallic Settings)][Space]
        _Glossiness ("Smoothness", Range(0,1)) = 0.5
        _Metallic("Metallic", Range(0.0, 1.0)) = 0.0
        _MetallicGlossMap("Metallic Map (R) and Smoothness (A)", 2D) = "white" {}

        [Header(Emission Settings)][Space]
        _EmissionMap("Emission Map", 2D) = "white" {}
        _EmissionColor("Emission Color", Color) = (0,0,0)
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Opaque"
        }

        LOD 200

        Stencil
        {
            Ref 1
            WriteMask 1
            Pass Replace
        }

        CGPROGRAM

        // Physically based Standard lighting model, and enable shadows on all light types
        #pragma surface surf Standard fullforwardshadows

        // Use shader model 3.0 target, to get nicer looking lighting
        #pragma target 3.0

        sampler2D _MainTex;
        sampler2D _MetallicGlossMap;
        sampler2D _EmissionMap;

        struct Input
        {
            float2 uv_MainTex;
            float2 uv_MetallicGlossMap;
            float2 uv_EmissionMap;
        };

        half _Glossiness;
        half _Metallic;
        float4 _Color;
        float4 _PaintColor;
        float4 _EmissionColor;

        void surf (Input IN, inout SurfaceOutputStandard o)
        {
            // Albedo comes from a texture tinted by color
            float4 textureColor = tex2D(_MainTex, IN.uv_MainTex);
            float4 baseColor = lerp(_PaintColor, textureColor, textureColor.a);
            float4 c = baseColor * _Color;
            o.Albedo = c.rgb;
            
            // Metallic and smoothness from maps and sliders
            half4 metallicGloss = tex2D(_MetallicGlossMap, IN.uv_MetallicGlossMap);
            o.Metallic = metallicGloss.r * _Metallic;
            o.Smoothness = metallicGloss.a * _Glossiness;
            
            // Emission
            half3 emission = tex2D(_EmissionMap, IN.uv_EmissionMap).rgb * _EmissionColor.rgb;
            o.Emission = emission;

            o.Alpha = c.a;
        }

        ENDCG
    }

    FallBack "Diffuse"
}
`
