### ISSUE TITLE
vehicles that enter water get their sound cut off, but when they exit, they dont regain their sound

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4528]
https://imgur.com/a/RDtPFZK imgur link as its more than 10mb

replication:
get a vehicle
drive into water
drive out of water
vehicle no longer has sound

**Comment by SDGNelson** [comment]
Thanks for the report! I'm closing this as the same as #4522 and crediting both of you in the patch 103 changelog.
