### ISSUE TITLE
feet are weight painted to the world center when changing to certain pants

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4529]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/d4bbed87-6d06-4175-b59e-c8a5eaf45b72)
i dont know how to describe this, 
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/14c2bf32-c7b5-4143-b38f-a3e542d3bac4)
i dont know how i did this but switching from "Mythical Musical Tracksuit Bottoms" (for some reason only these pants) to other pants will parent them to the center of the world.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/d9a55bb2-3a4d-474d-865d-cb059685b408)
i think somethings messing up with parenting the musical effect, but i have no idea.

**Comment by SDGNelson** [comment]
That's... bizarre. I can't imagine what part of this update would've affected that. I don't suppose you have a character mesh override equipped?

After it happens again could you attach the Client.log file in case there's a related exception please?

**Comment by diddlyono** [comment]
it should be replicatable, it seems to be any mythical pants, but sure ill attach a log in a minute

**Comment by diddlyono** [comment]
[Client.log](https://github.com/user-attachments/files/15996581/Client.log)
opened the game, equipped the pants, unequipped them, legs broke, closed the game.

**Comment by SDGNelson** [comment]
Ohhh with mythical clothes I bet I accidentally deleted the legs when you change pants! 😱

**Comment by SDGNelson** [comment]
So uh. Yep. On the current preview version it deletes your legs when you change mythical pants. I managed to mess this up specifically for pants but not shirts or vehicle mythics. :P
