### ISSUE TITLE
Stuck to map border

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#453]
So this report is about a few weird spots in the maps.
As you might know, if you get to the invisible wall on the map's border, you can just go "with it" without getting stuck.
But we found randomly 1-2 spot on Washington(-959.5 84.7 -636.7) & Russia(1983.5 164.7 702.5) where you just get to stuck if you go to it and sometimes you can't even get out without dying.
https://youtu.be/yvlzfAu2UbU
Very minor bug but still, a bug.

**Comment by SDGNelson** [comment]
Looks like it might be the intersection point of two landscapes or something. May be resolved as part of updating to 2017.4 soon
