### ISSUE TITLE
[Preview branch] Dirtbikes are kinda unuseable.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4533]
The cars I've tried feel really nice but the dirtbikes and police motorcycles are a little too unstable. Even just driving on the road is almost impossible without falling over. They also have trouble picking themselves back up. If they're knocked over so that the top of the bike is towards a downhill slope, they kind of crawl down the hill trying to flip themselves over.

**Comment by SDGNelson** [comment]
Happy to hear the cars have felt better so far! Sorry to say, however, that the bikes and motorcycles haven't received any adjustment yet. (It should be just as bad on the main branch - I double-checked and it seems about the same to me.)

**Comment by DanielWillett** [comment]
Ah alright, havent really tried them in a while on the main so makes sense. Thanks
