### ISSUE TITLE
[PTB] Remove space between % and audio values

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4535]
There shouldn't be a space between the values & the unit symbol / make consistent with other menus where there isn't a space.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/7608445/03aae727-0552-4157-8381-893a90379525)

**Comment by SDGNelson** [comment]
The reason for the difference is that older UIs included the percent symbol in the translation file without a space, whereas newer UIs use the `"P"` float format specifier. I believe this is the more correct way to do it as it will use the per-culture format preference. For example, some countries put the % symbol before the number. It's annoying that the en-US or whatever culture has the space though as without space certainly seems more common. (It is an option in number formatting https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.percentpositivepattern?view=net-8.0#system-globalization-numberformatinfo-percentpositivepattern)

**Comment by MoltonMontro** [comment]
Ah, it does appear that a space is intentional with en-US. Adhering to ISO instead of English style guides. :X

I tried switching the Steam client language to Turkish (**%beforeNum**) and Chinese (**noSpace%**), which I believe should use different formatting than en-US, but it didn't appear to change in-game.

**Comment by SDGNelson** [comment]
I wonder if the reasoning behind it is documented publicly anywhere.

Sorry, to clarify, the cultureinfo formatting uses your operating system settings. On Windows 10 it might be the Settings -> Time & Language > Region settings but I'm not 100 % (😄) sure.
