### ISSUE TITLE
Magazine Prefab animation hierarchy issues

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4537]
Animating the Magazine Prefab **directly** through setting up the same hierarchy is really useful if we want to have special double-magazine reload animations, with the benefit of having multiple different looking magazine types (Polymer magazine with faster reload speed, etc.).

_The Instantiated_Attachment_Name_Override .dat argument makes this possible._
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/2c24d64f-65ac-4648-88d6-2b4bddb547b1)

However, after removing the magazine completely, and putting it back, the Player's Animator refuses to see the Magazine prefab's rig, and the magazine stays static until the Gun is re-equipped.
(Note: Unplace and Replace were both set to 0 for animation fluidity)

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/fb9ccc9a-e1d9-4ae4-9b5b-7b3fd2bfc9e7

**Comment by SDGNelson** [comment]
That looks nice! From your description I think this is outside of the game's control, however. Though I think Buak used a similar approach so maybe worth checking whether the Buak guns run into the same problem?
