### ISSUE TITLE
Umbrellas / Gliders are more effective than they supposed to be

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#454]
Umbrellas / Gliders are more effective than they supposed to be.
You can spam getting it to your hand & stay a lot of longer in the air, much easier to raid skybases, very glitchy.
https://youtu.be/VBjsewSB8Nc

**Comment by SDGNelson** [comment]
While not solving the prediction difference, a slight tweak for the next update is umbrellas will not take effect until the equip animation is complete.
