### ISSUE TITLE
[Preview Branch?] Orca and Hind bullet-hit issues?

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4540]
I have no idea

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/874bf541-9caf-4b8a-9eb0-fce04c8c1699

This happens when damaged by any invulnerable gun.

**Comment by SDGNelson** [comment]
Uh oh, thank you! Will get this patched on the preview branch shortly.
