### ISSUE TITLE
Unable to spawn vehicles by GUID

### ISSUE THREAD

**Issue by bananasov** [SmartlyDressedGames/Unturned-3.x-Community#4541]
Unlike items, you can not spawn in a vehicle using a GUID. For example `/vehicle 4df21927a16e4ff89ab7314afd7ed83a` for a White Pickup Truck on Escalation will not work but `/vehicle 51021` will.

**Comment by SDGNelson** [comment]
Maybe you had the wrong guid? I just tested with `/vehicle e0f8b4b23249483a9cd5c1402e2170fb` to spawn the vanilla offroader.

**Comment by bananasov** [comment]
I just tried `/vehicle e0f8b4b23249483a9cd5c1402e2170fb` and i got nothing, i tested on PEI and Escalation.

**Comment by SDGNelson** [comment]
Are you on the preview branch?

**Comment by bananasov** [comment]
I am not

**Comment by elsultaan** [comment]
This feature only exists on the preview branch.

**Comment by SDGNelson** [comment]
Thanks elsultaan, yes, it's only on the preview branch at the moment, sorry.
