### ISSUE TITLE
[Preview Branch] Tire Item still uses old Tire model

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#4545]
The title says everything.

**Comment by SDGNelson** [comment]
The reason I kept it with the old model - at least for the meantime - is to hopefully reduce confusion over whether it can be used on all vehicles. All of the new tire models keep the profile and similar colors to the old tire model, but I thought if the tire item looked like any specific one of the new tire models it might seem like it's only compatible with that vehicle.

That said, it's always worked on tires that look nothing like the default ones, so maybe it's a non-issue and should use the new model. Or different tire items for different tires. Might need to revisit after updating traction in case, for example, there were different tires for different conditions (snow).

**Comment by SDGNelson** [comment]
Closing for the meantime because I think I will hold off on changing the level editor and item tire models, sorry.
