### ISSUE TITLE
Animals moving abnormally on the server

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4547]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/e009f87d-894b-4c64-8669-8312b6721a60

**Comment by hyjhkt** [comment]
Question 1: Why do remotely attacking animals switch back and forth between attacking and moving actions when moving on the server?
Question 2: Why do some animals clearly unable to wander around

**Comment by SDGNelson** [comment]
Unturned's animals in general aren't very fleshed out. In this case, it's suffering from the way the client infers whether the animal is "running" based on the distance between position updates. At the moment its speed needs to be high enough to exceed that threshold, sorry.
