### ISSUE TITLE
[Preview Branch] Crawler, Num_Steering_Tires, IsModelSteered issues

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4548]
The Crawler and Num_Steering_Tires arguments refuse to work with the new WheelConfigurations system.
I'd like to add visual suspension (ModelUseColliderPose true) to my tank, but I don't want to first wheels to turn. Adding IsModelSteered false to any of the front wheels or Crawler/Num_Steering_Tires 0 to the .dat file doesn't change anything either.

**Comment by SDGNelson** [comment]
Those options are made obsolete by WheelConfiguration. You can't use ModelUseColliderPose at the same time as IsModelSteered, sorry. Tanks haven't been addressed in vanilla yet so it's probably best not to use the new properties in a hacky way for them.
