### ISSUE TITLE
[Preview Branch] Spine Parent breaks

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4549]
When parenting items to the spine, animating becomes a hassle because in-game the Item prefab will always be rotated 90 degrees on the z? axis. Ideally a Spine_Hook bone should exist that moves independently from the Spine, like the Right_Hook and Left_Hook bones for both hands. So people can move that around instead of having to animate the Item prefab's transforms, or adding an armature to the Item Prefab and vertex grouping parts of the item. The latter will cause even more problems for items like guns, because it will be necessary to add constraints to every attachment to make sure they follow the moving bone.

**Comment by DerEnte** [comment]
Yeah, same issue over here.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/086ef8b9-509b-4e2e-9974-f6c1ac8079bd

**Comment by DerEnte** [comment]
Same issue over here

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/394f3926-545f-4a19-ae66-1a09584362e4

**Comment by SDGNelson** [comment]
It will default to (0, 0, 90), but I'd think the animation would override the item transform's rotation. For the gun animation attached to the spine are you animating a child of the item transform?

**Comment by elsultaan** [comment]
We were both animating the Item's transforms/rotations because it seemed easier than having to animate the root bone of the item's armature itself. That would complicate things further because the attachments on the gun follow the item prefab and not the root bone of the armature.

**Comment by elsultaan** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/a56135ab-f0a5-4e80-b62f-8a7140ea6c4e)

This was happening to Der Ente's gun and my Brass Knuckles (as seen in the pic) earlier.

**Comment by SDGNelson** [comment]
Sorry, I'm not sure I understand. When you say animating the root bone of the item's armature, is that a child of the equipable prefab / item prefab? If you're animating the Item's transform does it have the 90 degree rotation offset in Blender as well?

**Comment by elsultaan** [comment]
When it comes to animating guns with moving parts, we always set up the item prefab in this way. The Blender hiearchy corresponds to the unity hierarchy.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/c3d90e7a-6b5c-49a9-a8b2-e300a74b9d52)

Item_SMG2 is the same as Instantiated_Item_Name_Override Item_SMG2.

When using the Spine Parent argument, Ente used a new bone with the same name as the Unity Item Prefab.
That's the source of 90 degree rotation issue.

I managed to fix my brass knuckles with keeping the Item stationary at the location of the Spine bone. And animating the Equipped item's child armature, which will let me move each brass knuckle separately from the item's actual position.
But this solution won't work for guns because every attachmenthook(grip, barrel, etc) will have to be parented to the root bone of the gun that we animate so it moves along with the gun.

This is why a Spine_Hook bone, would solve everything because it would work independently from the parent just like Right_Hook or Left_Hook without the need of treating the Item Prefab as a bone.

**Comment by DerEnte** [comment]
Personally, I copied one of the hook bones and rotated it and parented it to the spine and renamed it to "Item", afterwards I parent my entire weapon armature on it treating it as if it was an item prefab in unity.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/eee6931c-e0b1-42e4-b6ed-fa8f1e2b4c38)
In blender, the animation works normally as opposed to in unity, where the item prefab gets rotated 90 degrees, as seen in my previous comment.
We tried various workarounds such as parenting an empty to the spine and having it copy transforms from the original hook bone, which resulted in Sultaan's example.

**Comment by SDGNelson** [comment]
It's been a while but I suppose those hook bones must have been added for a similar reason in the first place!

I'm not 100% sure how far-reaching the implications of modifying the base skeleton might be, so I'm hesitant to mess with this shortly before the update. I do think, however, that it should be possible to work around this using the EquipablePrefab option. Since it sounds like your gun contains a skinned mesh, this is already right up the alley of having a separate higher-detail prefab for the gun and a static mesh for the Item prefab.

If I'm understanding correctly, I think it might work for the EquipablePrefab gun to be aligned with however the animation is being imported into Unity, and in Blender to rotate the constrained model so that you can work on it normally. Does that make sense?

**Comment by DerEnte** [comment]
I honestly don't see how the EquipablePrefab can help with this, and also we have various bone constraints on the gun itself, so if we rotate the constrainted model, the constraints will react to those changes, thus we cannot export the animation normally while it is rotated.

**Comment by SDGNelson** [comment]
Could you email me one of your example cases, please? I'll see if I can find a workaround, and if not I'll have to add the new bone.

**Comment by DerEnte** [comment]
Bet

**Comment by SDGNelson** [comment]
Thanks for sending it! I wasn't quite sure about how the sub-item transforms were being exported, but for the root I wonder if this Forward: X, Up: Z, Apply Transform: Yes option works on your end? This was exporting the gun as a separate fbx with different settings than the character and putting the mesh directly on the "Item" bone.
![FBX Settings](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12567645/3acfb006-8e38-4c5b-aa2e-68081c3ece0f)
![Animation](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12567645/25c18e10-a509-40c9-b5b2-1db972110d94)

**Comment by DerEnte** [comment]
This does work on my end, but as soon as I add in the armature of the gun just turns 90 degrees, I had to double check 10 times that this does infact happen.

I think I could probably somehow connect the entire weapon armature to the player skeleton, this could work.

**Comment by SDGNelson** [comment]
Maybe the most feasible option is indeed an intermediary bone. I'll add it as a fourth option for attachment parent. :S

**Comment by SDGNelson** [comment]
Okay: There's a `SpineHook` option for `EquipableModelParent` on the preview branch now, but the bone is optional. You can add a bone named `Spine_Hook` to the `Spine` bone and it should work to have your item underneath that. 🤞

**Comment by DerEnte** [comment]
Ok, I will check it out tommorow

**Comment by DerEnte** [comment]
thank you

**Comment by elsultaan** [comment]
Thank you!

**Comment by SDGNelson** [comment]
You're welcome, no problem! Thanks for raising the issue before the update released. Hopefully it works OK - I will double-check in multiplayer this evening.

**Comment by DerEnte** [comment]
Works almost fine.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/ae18c6e3-f0d7-4a51-a0a4-6928c3ab9a30

**Comment by DerEnte** [comment]
also in 3rd person, it seems that the weapon doesn't follow the spine.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/6daaba12-2735-488c-953a-afdf4e6e4a07)

**Comment by DerEnte** [comment]
although this seems to be a problem in blender as well

**Comment by DerEnte** [comment]
fixed it in blender by clearing the parents, the issue persists in unturned though.

**Comment by SDGNelson** [comment]
🤞 The version of the gun you made using the Spine_Hook bone *should* work in the new preview branch version without any additional changes.

**Comment by DerEnte** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/7ce57611-68af-4b8c-9f6c-c233a257f272)
What else can I say. Works like a charm.

**Comment by DerEnte** [comment]
the one frame of the gun being in it's idle pose still persists though, please do fix that

> Works almost fine. https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/80266096/ae18c6e3-f0d7-4a51-a0a4-6928c3ab9a30

**Comment by SDGNelson** [comment]
Yay! 🎉 

Oh, I didn't even notice it in the video! Could you attach or send me the latest version of the test gun please? I'll see whether I can narrow down what's going on there.
