### ISSUE TITLE
Can build at (possibly) any map's corner

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#455]
This bug was reported from Washington map, but we could replicate it at any corner of Russia map aswell.

On each corner, you can place bedroll or anything else in around a 2x2 base's size and it is an easy way to get an "unraidable" glitched base for any server's solo player.
https://youtu.be/t1Y_0nvhoXA

**Comment by SDGNelson** [comment]
Looks like I didn't take into account the rounded corners for that check! Also adjusted those out-of-bounds checks to check for player clip volumes.
