### ISSUE TITLE
Negative steering bug

### ISSUE THREAD

**Issue by Big-Raider** [SmartlyDressedGames/Unturned-3.x-Community#4551]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174275952/95f4b0e7-3323-43ec-bdec-e9ffda540e0a

Setting the wheel's steering angle to a negative number causes this to happen
also i as a suggestion since i don't know where to put it, maybe a option to invert a specific wheel steering angle so vehicles with front and rear wheels steering can be made

**Comment by SDGNelson** [comment]
Haha that's weird! I could force that value positive, but I think it's sufficient to say "don't set it to a negative value." Per-wheel configuration for rear steering is an interesting idea but no ETA.
