### ISSUE TITLE
Glass Plates Inconsistence 

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#4552]
Making the **Bulletproof** or the **One-way** glass into plates will make them lose their bulletproof property.

**Comment by SDGNelson** [comment]
Haha fair point. This must have been a casualty in the plate changes. Perhaps the small form factor reduces its ability to flex and withstand bullet impacts! I'll rename the **Bulletproof** small plate to **Bullet Resistant** for the update.
