### ISSUE TITLE
Dirtbikes even more unusuable now after the update

### ISSUE THREAD

**Issue by 0x5BC2** [SmartlyDressedGames/Unturned-3.x-Community#4554]
After a bit of testing, I've came to the conclusion that dirt bikes that are supposed to be offroad, are even more unusable even in city conditions. Driving on a terrain, the bike tends to do 'bunny-hops' from place to place and seems to be way more unstable in turns.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82274007/d7c87daf-3edc-4341-88ad-3b31c272b4da

**Comment by SDGNelson** [comment]
Yes, sorry, two-wheeler vehicles like bikes and snowmobiles are still rather questionable (to say the least) and haven't been addressed by this update yet.
