### ISSUE TITLE
New Car update bugs 

### ISSUE THREAD

**Issue by NELSONKISSESP9NDANDRETU** [SmartlyDressedGames/Unturned-3.x-Community#4557]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174636339/1ba6444a-8188-4ac0-94b7-88c29a6cb7f7

idk how this works
APC is much slower in water i dont think in last update apc max in water was max 14kph 
JET has too much movement on thirdperson 

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174636339/45dc09f7-19d5-4d7f-b84c-2b160e3a9231

shooting out bicycle with carjack  experience ability

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174636339/66a34e13-8c11-44b6-87e4-1381796ae988

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174636339/6c1ff95d-75ed-4646-bd2f-c078e1c2fe83
you can drive any wall 
![dg](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174636339/c7d0b7a9-afe1-4301-b7cd-00d9101c3a31)

Quad has too fast start? 0-50 1 sec
some cars give you WH through walls
I have question can i get faster updates to help with catching bugs?
i have debugger beret.
https://steamcommunity.com/profiles/76561198222086980/

**Comment by SDGNelson** [comment]
I'm guessing your were banned from this repo on a different account?

The offroader driving on the ceiling of the tunnel is pretty funny. I'll open a separate issue to see if something broke related to the car lifts but otherwise I think these are pre-existing issues.
