### ISSUE TITLE
Animal movements on the server twitching

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4558]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/2a287522-f622-48e3-b54f-dcfa11e596ea

![T($XZ$D0$C@VKDWTFMNE_0](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/8611e52d-8984-499f-9423-4da7c1436ad7)
The video shows my animal switching back and forth between attacking and moving actions while moving on the server. The picture shows
"Speed_Run 8"
"Speed_Walk 7.5"
How can I solve the problem of animals switching back and forth between slow walking and attacking actions when moving on the server

**Comment by SDGNelson** [comment]
Sorry to say this appears to be the same issue as #4547. We can't help troubleshoot modded content.
