### ISSUE TITLE
After entering "save" in the server backend, Structures. dat reported an error

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4559]
![0551627beaace36ac7dd230ee0c83e0f](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/b579601a-e58e-4df6-8ee4-371c8bb66d9b)
[Server_aekn.txt](https://github.com/user-attachments/files/16088546/Server_aekn.txt)
I hope to know why the game will report this red letter after the update

**Comment by SDGNelson** [comment]
Sorry for the trouble. It looks like the problem is with "Yut.AdvancedRegionModule". They appear to be patching barricade and structure save/load, in which case the plugin developer will need to update for the change to quaternion rotations.

**Comment by hyjhkt** [comment]
> 抱歉,麻烦了。看起来问题在于"YUT.先进区域模块"。他们似乎正在修补路障和结构保存/负载,在这种情况下,插件开发人员将需要更新以实现四元数旋转。

If Yut is not changed AdvancedRegionModule， Can the functions related to this plugin in the server be used normally, and can Save be saved properly? Will archiving be affected

**Comment by hyjhkt** [comment]
> 抱歉,麻烦了。看起来问题在于"YUT.先进区域模块"。他们似乎正在修补路障和结构保存/负载,在这种情况下,插件开发人员将需要更新以实现四元数旋转。

@SDGNelson 
If "Yut. AdvancedRegionModule" is not changed, will the functions related to this plugin in the server be able to be used normally, and can "Save" be saved properly? Will archiving be affected
