### ISSUE TITLE
Error preventing client connection to server

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#456]
Hello, many of my players are reporting this error when they try to connect to my server, running Washington:

ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
System.String.Substring (Int32 startIndex, Int32 length)
SDG.Unturned.MenuDashboardUI.insertContent (UnityEngine.GameObject news, System.String contents)
SDG.Unturned.MenuDashboardUI.onSteamUGCQueryCompleted (SteamUGCQueryCompleted_t callback, Boolean io)
Steamworks.CallResult`1[Steamworks.SteamUGCQueryCompleted_t].OnRunCallResult (IntPtr thisptr, IntPtr pvParam, Boolean bFailed, UInt64 hSteamAPICall_)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.CallResult`1:OnRunCallResult(IntPtr, IntPtr, Boolean, UInt64)
Steamworks.NativeMethods:SteamAPI_RunCallbacks()
Steamworks.SteamAPI:RunCallbacks()
SDG.SteamworksProvider.SteamworksProvider:update()
SDG.Unturned.Provider:Update()

They are stuck on the loading screen and eventually disconnected. Please help, thanks!

**Comment by Trojaner** [comment]
Definitly some Workshop content causing this.

**Comment by SDGNelson** [comment]
Not your server or content's fault, it looks like when they returned to the menu it was unable to parse the featured workshop item's description in an unexpected way. (e.g. maybe they had 5 opening [h1] but only 3 closing [/h1] or something) The game should handle those, but for the next update I'll catch and log exceptions from there just to be safe.
