### ISSUE TITLE
The save file cannot be loaded normally

### ISSUE THREAD

**Issue by Aikkes-xk** [SmartlyDressedGames/Unturned-3.x-Community#4563]
After updating the server, the archive is read normally when it is loaded for the first time. However, it cannot be read normally when the server is shut down and restarted.
![20240704042602](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/68454687/14cd7a5d-7d3d-493e-be14-2196b91dc6f9)

**Comment by SDGNelson** [comment]
Is this the server mentioned in #4561? If so, I'm afraid you may need to backup your Barricades.dat file for that server and reset it until the plugin is updated.

If not, there's an older Barricades.dat corruption issue that pops up occasionally but we haven't been able to reproduce it. 😞 (e.g., #4293) In that case the only option is to delete Barricades.dat to reset it.
