### ISSUE TITLE
Holiday overrides dont load the base main menu

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4566]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/94f7c7f0-bcfa-4199-9a09-3723a78ccf1e)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/5c5ffd46-363a-42c8-8737-9fa31517c4ec)

i think the main menu scene isnt loading alongside the decoration scene, this was an issue with PrideMonth but it appears to be every holiday override, but ive only tested with PrideMonth and Halloween.

**Comment by SDGNelson** [comment]
Sorry about that! It's because there's a different menu override scheduled but I should get it reverted before Halloween. 😉
