### ISSUE TITLE
Main Menu wheel models should be updated to match new wheels

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4569]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/a5a0ca5e-9731-475e-bb65-f76c83fe9c04)
i feel like this is different enough from the tire item to involve an update, as these are supposed to reflect the ingame wheels.
also, maybe these ones too?
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/7da5410e-53bf-469e-aafd-755afa1c61d0)
this might count as the tire items however, but they have been here since before those were a thing soo idk about this one.
i remember mention of a new menu soon so i wouldnt call for action asap on this one but good to have in notes probably

**Comment by SDGNelson** [comment]
Good point, thanks! I'll swap those out for the next update.
