### ISSUE TITLE
Vehicles wont never be on "neutral" gear

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4570]
No matter if you hold space, if you don't move, if you press W+S, vehicles will be always on gear 1 but never on Neutral

Reverse and other gears works as expected 👍

**Comment by SDGNelson** [comment]
True - When simplifying everything I never landed on when it should actually use the neutral gear. This isn't a bug at the moment since it's not necessary, but maybe it will have a use in the future. :)
