### ISSUE TITLE
Non-Vanilla Vehicles with no ID do not work

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#4571]
`[2024-07-06 04:02:52] Caught exception while populating "C:\Program Files (x86)\Steam\steamapps\common\Unturned\Maps\Jogristan\Bundles\Vehicles\IT_Tractor_0\IT_Tractor_0.dat": ID < 200`

This happened after removing the ID line from the `.dat` file. The vehicle was gone and couldn't be spawned in (even with GUID)
After re-adding the line it worked again just fine.

*btw this was bundled as a Masterbundle*

**Comment by iBowie** [comment]
The reason for this is ID check still being present in ``VehicleAsset.cs``

```csharp
if (id < 200 && !base.OriginAllowsVanillaLegacyId && !data.ContainsKey("Bypass_ID_Limit"))
{
	throw new NotSupportedException("ID < 200");
}
```

If vehicles are really non-dependent on IDs anymore, it would make sense to remove this check.

**Comment by SDGNelson** [comment]
Oops! Thanks guys, I'll remove that check. In the meantime as a workaround I suppose adding the Bypass_ID_Limit flag should turn off the exception.
