### ISSUE TITLE
The server backend continuously displays this

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4572]
![420829fe8c6f9a74e2cd7dca007bdb80](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/467280fa-f24a-483a-9b87-9105cfaf3527)
![da9eb0e92dd17a10ef08bf52c73cda1f](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/f49d637c-7678-4f95-990d-fb292c491cdd)

**Comment by SDGNelson** [comment]
Thanks for the report! Looking at the related code nothing immediately jumps out at me as potentially causing the null reference exception. Is it with a custom magazine or a vanilla explosive magazine?

**Comment by SDGNelson** [comment]
Tested with vanilla explosive magazine and explosive arrow without issue, but feel free to comment and I'll re-open.
