### ISSUE TITLE
Gameobjects with joints on vehicles don't move for other players

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#4573]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/110701629/bbf6635f-b69f-4517-b194-ab958cb3f1b3

Tested with configurable joint and hinge joint

While they work as intended from the driver's perspective, for everyone else they just don't move, and it breaks a lot of mechanics that modders made for their cars. (For example, I have a configurable joint flying around and activating collision event hooks, that is used for when the car is in drift mode, the smoke could appear when the car is sliding, that doesn't work anymore)

**Comment by SDGNelson** [comment]
Sorry about this! Curious setup. It looks like the reason is because the client calls `SetPositionAndRotation` on the vehicle transform rather than rigidbody's `MovePosition` and `MoveRotation`. I'll revert those and make a note in the code as to why.
