### ISSUE TITLE
Wheels on cars don't turn for other players while the car is standing still

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#4574]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/110701629/2e3a58c4-ecf0-4050-bc9c-7efcdd89c301

Here you can see the driver's perspective (on the left) and my perspective (on the right), he turns the steering wheel but the wheels don't turn for other players, they only start turning when the car starts moving.

**Comment by SDGNelson** [comment]
Turns out there was a reason for this: When no updates have been received from the server remote clients reset the steering to forward. I *think* it would probably be fine to get rid of that as long as the steering is then reset when the vehicle is empty.
