### ISSUE TITLE
Interior of the Santa's Sleigh APC preview model is missing a material

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4576]
![Screenshot_92](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67235885/749388c7-c0b7-45ce-974a-b74e9d802777)
most likely because the S.S APC doesnt override the interior material, unlike how the rally car skins *do* causing this bug to not happen to those but happen to this APC

**Comment by SDGNelson** [comment]
Thanks for the report. This is actually the invisible plane that hides water when you drive in it! I should hide it when the APC is inspected in the menu like that.

**Comment by diddlyono** [comment]
ah, so it is. i didnt notice the sides of the apc were textured correctly.
