### ISSUE TITLE
Text autosizing for unboxing screen.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4579]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/192fbcd6-5ed5-4afb-b60f-0e3c4184fc6f)
Somewhat self explanatory, I think it would be good because cosmetic names seem to only be getting longer these days because of mythicals.

**Comment by SDGNelson** [comment]
I agree it would be good. Some of the item names *are* crazy long now. Unfortunately, we don't have a good option for this at the moment. The only part of the UI system that supports automatic layout are scroll views like the chat, item description, news feed, etc. Need to implement in all 3 glaziers, but I don't think anyone wants me focusing on that again for a while. ;)

**Comment by Jdance-Media** [comment]
Fair enough, but I wasn't really suggesting that the entire box, etc gets auto sized. Just that the text box is set to auto size so that the font decreases in size to fit.

**Comment by SDGNelson** [comment]
Oh yes, even adjusting the font size automatically isn't something the game has support for at the moment. xD

**Comment by Jdance-Media** [comment]
Oh okay. 👍
Good to know.
