### ISSUE TITLE
Can move/chat after dying to spikes on login

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#458]
We found a bug (i believe its old) IF you die to spikes(or maybe anything that kills instantly) on login, you will be able to move, chat, and by that accept teleports or so, and can not respawn until relog.

We tested, if you just simply die to spikes, nothing happens, this bug happens only if u log into these spikes.

I report this as a "real problem" because it can cause abuse for servers, as they can kill eachother and like a ghost, just tell informations to their friends about the enemies in pvp (while they are invisible).
OR it can be very bad to see, when you log off, and they just put spikes under you to die if you get back.

This video shows it: https://youtu.be/bQQ58uqPE1Q
The start isn't a thing, we just wanted to show that there are spikes for real. SAME bug happens if spikes aren't there at logging out.

**Comment by SDGNelson** [comment]
This may be fixed in the next update. I was able to replicate it when logging in/out on spikes. I believe the problem were some bits of code that waited for onLifeUpdated which didn't check the current state, and after correcting them I wasn't able to get it to happen again.
