### ISSUE TITLE
Unaccessible fields after the Gear & RPM Update

### ISSUE THREAD

**Issue by 0x5BC2** [SmartlyDressedGames/Unturned-3.x-Community#4580]
After the recent 3.24.4.0 update, the classes InteractableVehicle and VehicleAsset have gained new fields regarding the new RPM, Gear and etc:

In InteractableVehicle:
- gearNumber
- replicatedEngineRpm
- animatedEngineRpm

In VehicleAsset:
- reverseGearRatio
- forwardGearRatios
- gearShiftDownThresholdRpm
- gearShiftUpThresholdRpm
- engineIdleRpm
- engineMaxRpm
- engineRpmIncreaseRate
- engineRpmDecreaseRate
- engineMaxTorque

Those fields are currently marked as internal, preventing their use in plugins and modules. 

Was this intentional, or could it be an oversight? Making these fields public would allow to make unique/interesting systems with vehicles, without the need of reflection or patching during runtime.

**Comment by surv0013** [comment]
I also wanted to create a discussion, but relying on previous experience, I decided to just use reflection. To be honest, I don’t fully understand the point of making fields private, because the only people who use them are plugin/module developers, and if we do something, we do it with awareness of what the consequences may be. But okay, let's say it's fool proof, then why not make the fields accessible but not overwriteable?

```CS
public float Value
{
	get;

	internal set;
}
```

**Comment by Jdance-Media** [comment]
I'm more on the side of keeping the fields inaccessible but making properties to so that plugin and module developers can access them. This is better on the off chance that these fields are made obsolete for whatever reason.

**Comment by 0x5BC2** [comment]
Reflections can be one of many workarounds, but in my current case, I need to get values from the currently active InteractableVehicle from the Player class. Which also would be running for every player as every player could be in a different vehicle. This method, running every few frames, on multiple players can and will become heavy on server performance. Using Harmony to patch just for a few digits seems overkill, especially when this could be avoided with a simple change for the fields' access.

**Comment by DanielWillett** [comment]
You can use dynamic methods for fields and/or `typeof(..).GetProperty(..).GetGetMethod(true).CreateDelegate` for properties to significantly speed up running the getters, but I do agree sometimes it seems like a lot of newer features are marked as internal that maybe don't need to be.

I get it's to allow you to make changes later but now that there's XML documentation maybe you could just mark them as subject to change in the comments so people know not to rely on the member staying the same.

**Comment by SDGNelson** [comment]
I think making some public properties with internal setters as proposed by Jdance and surv is a good way to go.

Although all of you are experienced enough to use reflection to access these regardless, I have been defaulting to internal for most code to help protect any new plugin developers from shooting themselves in the foot.

e.g. Gear Ratios were originally going to be a struct but simplified for now, so might need to add a method for plugins to get the gear ratio given the gear number.

In this case, I probably intended to have public getters but didn't get around to it and was in a rush to get everything wrapped up before the anniversary.

For the meantime, what were you guys hoping to do/add/implement?

**Comment by 0x5BC2** [comment]
I'm currently developing an RM plugin that includes several HUD variants. To implement some of those variants, I'm trying to access fields like the current Gear and RPM, and other relevant data from the player's active vehicle and the vehicle's asset to show that information on the HUD seamlessly, and just deemed that reflecting those values could be removed and directly access the fields to improve performance as the HUD updates about vehicles are executed on every LateUpdate.

**Comment by GazziFX** [comment]
I don't use reflection in my projects for several years, I just make all fields and methods public for reference assemblies, and it work with original assembly in runtime if you enable Allow Unsafe Code

**Comment by sunnamed434** [comment]
> I don't use reflection in my projects for several years, I just make all fields and methods public for reference assemblies, and it work with original assembly in runtime if you enable Allow Unsafe Code

Just in case you can also use this [tool](https://github.com/krafs/Publicizer) which makes target assembly/everything fully public, it works on MSBuild level
