### ISSUE TITLE
Inexplicable server lag

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4581]
I have an attached server. If I "give" a piece of clothing (both original and mod, and as long as it is worn on the body, including backpack, eyes, and pants), when the clothing is worn on a person, the server is normal. When the clothing is removed, the server starts to get stuck, the clothing does not turn into an item and enters the backpack. At this time, I am not kicked out of the server, and the character cannot take any effective actions. The server backend does not report an error, and there is no further display of any text on the server backend. The delayed section in the upper right corner displays green text for a period of time, and red text for a period of time

**Comment by DanielWillett** [comment]
Most likely there's a plugin making a remote request (such as accessing a database or website/webserver) on the main thread. In that case try removing any plugins that have to do with clothes.

**Comment by SDGNelson** [comment]
Thanks @DanielWillett, yes it sounds like it's a plugin or mod issue rather than a vanilla bug.
