### ISSUE TITLE
Menu button misalignment (Minor)

### ISSUE THREAD

**Issue by ai-kana** [SmartlyDressedGames/Unturned-3.x-Community#4583]
When viewing an item in the inventory menu the Scrap/Delete button go past the edge of the info box above

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109441902/5de4b60a-5904-4f98-be33-158dd9b785f0)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109441902/38cb3b5e-55b9-4376-8c7b-ac47bc15c6b2)

**Comment by SDGNelson** [comment]
Whoops, thanks!
