### ISSUE TITLE
Sort level Problem (Found a solution!)

### ISSUE THREAD

**Issue by Alexondeer** [SmartlyDressedGames/Unturned-3.x-Community#4585]
As you know, the game has a problem with the sort level of transparent materials under water. I found a solution to this problem quite a long time ago and it has already been solved for transparent barricades.
We are talking about the **WaterHeightTransparentSort** script. This script can be added to any object with a transparent material and call the **updateRenderQueue** method via the **Unity Event Hook**.

The only problem is that due to restrictions, I can't add this script to the player's prefab.

Since this is a potentially simple and useful tool I suggest adding **WaterHeightTransparentSort** to the other **Mod Hooks**.
(To work correctly in **Unity**, you need to comment out some lines of code and make the methods **public**.)

Add **WaterHeightTransparentSort** to the player's standard prefab.
(It is possible to add an enabled **Parameter** to the **item clothing config** for optimization.)

![0](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/99840216/3fc260ef-9ddc-44ce-83e0-3f0dc8d0798c)
![1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/99840216/f460854a-3529-46bd-b2e0-a1ee6a68377b)
![2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/99840216/580af83c-509d-473e-965d-d34ae7b2ac14)

**Comment by SDGNelson** [comment]
The game has a couple of features related to this, but they're not *great*. Certain vehicle parts are registered with `DynamicWaterTransparentSort` which updates one transparent material per frame, and as you mentioned the `WaterHeightTransparentSort` script is added to barricades with a flag enabled, but is only intended for static objects.

It might be expanded in the future but transparent players aren't officially supported at the moment, sorry.
