### ISSUE TITLE
Warnings on ">200" Vehicle ID when no ID

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4586]
Since the Carr update, Vanilla has ditched vehicle ids on official content. While updating Easter Island, I noticed that the game throws errors when I try to remove IDs from the vehicles. For now, this can be fixed by including Bypass_ID_Limit in the dat.

**Comment by CyberAndrii** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4571
