### ISSUE TITLE
Gasmask & Compass Widget Flags

### ISSUE THREAD

**Issue by 0x5BC2** [SmartlyDressedGames/Unturned-3.x-Community#4588]
Currently, Unturned has bunch of Widget Flags responsible for various UI elements, such as the statistics bars, status icons, gun status, and vehicle status. However, there are no Widget Flags for removing the Compass UI or Gasmask Status UI. Were they just overlooked after implementation, or is there another way to disable those without the use of Widget Flags?

**Comment by SDGNelson** [comment]
No, there isn't currently a way to disable those, sorry. More options for disabling vanilla UI might be added in the future - there's a suggestion in the discussions tab for gasmask (#4009), but no ETA at the moment.
