### ISSUE TITLE
Stamina Boost seemingly broken on non Stamina Powered vehicles

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4589]
Ran into this while updating vehicles on Easter Island. Tested with various values, no effect. Bike still works, so I assume this is functionality that was not ported to the new vehicle physics.

**Comment by SDGNelson** [comment]
Like a gas-powered car that has a stamina boost? 😕

**Comment by Spebby** [comment]
> Like a gas-powered car that has a stamina boost? 😕

Yep. Easter used it to emulate a turbo functionality, and iirc there was a blog post at one point shouting out a mod that used it.

**Comment by SDGNelson** [comment]
When boosting with the older wheel physics it multiplies the wheel torque applied. I've changed it to do the same for the new wheel physics as well, but I wouldn't necessarily recommend this approach with the gearbox because it will change gears every time the stamina runs out.
