### ISSUE TITLE
?[?] bug is back

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#459]
Hey there! The bug i reported earlier is back again.
Didnt get reports until today so we closed the report, but yeah. sadly.

https://cdn.discordapp.com/attachments/501831950831714332/513412865563033615/unknown.png

**Comment by SDGNelson** [comment]
Hard to know what exactly the issue is without a reproducible case, but in the current version there are 3 places responsible for telling clients about players, so for the next update I've unified them into 1. Most likely there was some subtle difference between them, e.g. it looks like clients weren't getting which language other clients are using properly... not that that's really used anywhere in vanilla.

**Comment by evermoreservers** [comment]
Sadly i can't tell you how to reproduce it, but i can tell a few important details, sorry for not telling it before.

1. It is known bug only on Sandbox servers which are wiping Daily and the Players & Level folders both being deleted. (So i'm guessing sometime it isnt generating well)
2. The bug causes the player to shown ?[?] and invisible for everyone who joined before him.
3. The unknown player can be seen, and wont be ?[?] for players who joined after him.

(To make sure you understand: If you are on server, and i get this bug, you wont see me, but an other player joins later, he Will see me.)
(So this bug fixes "itself" for player who relog, or for everyone if the bugged player relog. But sadly, happens Daily and they wont relog, just start saying "hacker".)

**Comment by SDGNelson** [comment]
Looking through this code thoroughly nothing is popping out at me as suspect. I've now added several try/catch blocks to help track down if this is an exception on the client, so client logs will help after the update. If we can narrow it down after tomorrow's update I'll put out a patch asap... Fingers crossed.

**Comment by SDGNelson** [comment]
Any luck after the update?

**Comment by evermoreservers** [comment]
I didn't get reports about it anymore. Seems to be fixed. : )
