### ISSUE TITLE
Weird gearbox behaviour (and kickup particles)

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#4590]
When braking with S key (spacebar works fine), the car shifts into reverse gear and then if you press on the gas again it shifts firstly into first, then in the gear it needs to be in at that speed. That would blow the motor in a real car, and it just looks and sounds weird.

The particles from under the wheels are also being kinda weird, you can see that in the video. That only occurs on sufficient speeds (I'd say at 55+ kph) after the ground material has been updated.

https://github.com/user-attachments/assets/4b96c702-c087-4521-9b8b-2bf228165a71

**Comment by DanielWillett** [comment]
The issue with the tire motion effects is caused by the maximum number of particles allowed at once set on the system, I noticed that in unity when i was messing around with the example assets. There's a setting in the particle system where you can tell it to delete the oldest particles when it hits the maximum that would probably help with that (or just raising the maximum i guess).

**Comment by TheMew0** [comment]
Yes, that can be the reason, but the thing is, there is no particle system that I can configure in unity, even in example assets, so I can't do anything about it. By the way, it also happens with vanilla vehicles.

**Comment by SDGNelson** [comment]
Good point that it should use the appropriate gear while moving quickly forward and switching between reverse and forward.

Regarding the issue of blowing up the motor, I suppose the correct behavior would be to brake without changing gears to reverse? i.e., only change gears once the car has reached a standstill? Or should it change to neutral?

Thanks I think you're right @DanielWillett about the particle limit. When implementing kickup I didn't run into it with vanilla vehicles, but makes sense it could be hit with faster modded vehicles. I'll see about raising the limit for the vanilla effects in the next version.

**Comment by TheMew0** [comment]
> I suppose the correct behavior would be to brake without changing gears to reverse?

Yeah, in real life you just downshift when braking, and put it in neutral when reaching a standstill. On cars with automatic gearboxes you are not even able to put it in reverse while moving forward, because the car just won't let you.

**Comment by SDGNelson** [comment]
Ring Buffer mode on the tire motion particles would be _perfect_ except that `ParticleSystem.IsAlive` returns true while they are "dead", meaning that the old particle systems aren't cleaned up properly. For the meantime I'll increase the Max Particles from 64 to 256.

Also fixed the gear change. 👍
