### ISSUE TITLE
Wheel's state is not being saved if its index is 8 or more

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#4591]
Wheels are a great way of storing information on vehicles, they synchronise nicely and their state is actually stored on server. I've used that feature to make stable systems for my cars (I basically made a plugin to break or repair certain wheels to activate some things on the car), and that limitation is really painful, as I can implement only four additional things on a car, and I really want to add more.

**Comment by SDGNelson** [comment]
Sorry, but this is very much an unintended way to extend the car state. Support for more wheels might be implemented in the future but ideally for something like this there'd be an intended way to extend custom state. No ETA, however, sorry.
