### ISSUE TITLE
Tweak to the Desert Military Top texture

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4592]
The discussion in this player's suggestion is generally accurate. https://forum.smartlydressedgames.com/t/usa-shoulder-flag-reversal-correction/24672/1

It'd be a small tweak to the texture, but would make it more accurate to U.S. flag etiquette. (On the right shoulder, having the union closer to the front of the player.)

**Comment by SDGNelson** [comment]
Thanks for cross-posting here. I made the adjustment to the Arctic top and US jersey as well!
