### ISSUE TITLE
The shield cannot block bullets and instead increases the area of injury

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4593]
The shield cannot block bullets and instead increases the area of injury
I added a shield grid and collision box to a gun preform, and added Destroy_ITEM_Clliders false to dat. However, on the server, when player 2 used a gun to shoot and hit player 1's gun and shield, player 1 suffered damage. This is equivalent to the collision box of this item increasing the area of player 1's injury
![K`W3JMF}LW$%ED 3ZUX6 N8](https://github.com/user-attachments/assets/e2659386-33fa-433b-bc07-21792006b686)
![H`E91KNMJ$(N8)KN6UX V1P](https://github.com/user-attachments/assets/8e3ac36d-a35e-405f-8f62-2ff48f5d3778)
![FDCUAS~W}~R$T$ 06(@67S](https://github.com/user-attachments/assets/c72da7e2-c27b-4666-a655-a1fe856a73e0)
[防爆盾牌玻璃军用洛洛克18c - 副本.txt](https://github.com/user-attachments/files/16246701/18c.-.txt)

**Comment by hyjhkt** [comment]
![T~}3LX@}6E$@_N$9G`E}BB5](https://github.com/user-attachments/assets/97926606-b14e-41ca-9463-c560e1726326)

**Comment by SDGNelson** [comment]
This isn't something that's officially supported, so I don't recall how mods have used item colliders to block damage like that in the past, sorry. It *might* be something related to making the colliders children of the item and putting them on a different collision layer like, e.g., vehicle.
