### ISSUE TITLE
Vehicle turret pitch is unaffected by pitch rotation if contrainted

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#4595]
When making a vehicle turret that can lock its rotation in place, the yaw is successfully locked in place but fails for pitch rotation. In simpler words, the turret can have a feature to stop its gun rotation horizontally but its vertical rotation cannot support this.

I found this issue when using parent constraints in the turret to make 2 systems that emulate saving its rotation when the player leaves and enters the turret, and making it a platform to support multiple turrets with different weapons that follow the main turret when inactive.

**Comment by SDGNelson** [comment]
It sounds like a cool setup you've got going, but this isn't officially supported at the moment, sorry. Rotation speeds and general turret improvements are on my radar as candidates for future vehicle improvements, however!
