### ISSUE TITLE
Battery Powered Boats don't get Saved

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4597]
Battery Powered Vehicles don't need to have Fuel defined, which sets it to a default value of 0. Boats get Auto Cleared during saving if they do not have any Fuel, [Seen Here](https://github.com/Unturned-Datamining/Unturned-Datamining/blob/linux-client-preview/Assembly-CSharp%2FSDG.Unturned%2FInteractableVehicle.cs#L612). Since Battery Powered Vehicles with no Fuel defined has no Fuel that means that they don't get Saved.

I know this can easily be fixed by simply adding some Fuel to the Boat that doesn't burn but it doesn't make sense to be forced to add that.

Big Thanks goes to sensucha on Unturned Official for encountering this Bug.

**Comment by SDGNelson** [comment]
Interesting catch, thanks! Will credit both of you in the patch notes.
