### ISSUE TITLE
About variables in server-side and client-side

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#4598]
Hello, I am developing an Anti-Cheat Server-Side to combat hackers, and testing with some cheats with "Freecam" I have seen that isOrbiting is activated on the client, but when I try to check the variable on the side from the server, it tells me that it is not "isOrbiting", is there any way to find out what the current player is doing? What I am trying to detect is this specific feature.

Variable that not getting from Client-Side to Server-Side: unturnedPlayer.Player.look.isOrbiting

` if (!unturnedPlayer.IsAdmin && !rocketPlayer.HasPermission("*") && !rocketPlayer.HasPermission("dac_bypass"))
 {
     // Player without permissions it's using freecam?
     unturnedPlayer.Player.look.sendFreecamAllowed(false);
     if (unturnedPlayer.Player.look.isOrbiting || unturnedPlayer.Player.look.isTracking)
     {
         // ban, kick
     }
 }`

https://github.com/Darkness-Anti-Cheat/Darkness-AntiCheat

**Comment by TH3AL3X** [comment]
If you can see, when i enable that cheat "feature" and you have admin in the server, it saying that you're orbiting, but when i try to get that variable in server-side, it's saying "false"
![image](https://github.com/user-attachments/assets/32fb96b8-2e15-41cf-a5dc-e7624f1ea4b3)

**Comment by SDGNelson** [comment]
Those aren't replicated to the server. You're probably thinking of `EPlayerAdminUsageFlags.Freecam`.

**Comment by TH3AL3X** [comment]
But is is possible to get if client is using FreeCam with cheats?, i mean if you get the variable `unturnedPlayer.Player.look.isOrbiting`, if the "cheater" is using FreeCam, it says "false" always

**Comment by DanielWillett** [comment]
For what it's worth, a cheat could easily just tell the server it's not orbiting even when it is.
