### ISSUE TITLE
Hello, I hope to improve the animal refresh mechanism

### ISSUE THREAD

**Issue by roujiamo123456** [SmartlyDressedGames/Unturned-3.x-Community#4599]
Because the NPCs on the map can no longer be refreshed, I asked the server administrator and they said that the NPCs cannot be refreshed because the animal refresh mechanism is not done well

**Comment by GazziFX** [comment]
Do you mean animal state replication or whatever?

**Comment by roujiamo123456** [comment]
> Do you mean animal state replication or whatever?

I don't know, the administrator has already fallen asleep. Here are the chat records I had with him before
![Screenshot_2024-07-22-03-54-33-76](https://github.com/user-attachments/assets/3ca800a2-8c02-4a43-8770-1c4b24af1b0d)

**Comment by roujiamo123456** [comment]
The game map I am playing is Huubske_内布拉斯加州_3, which is not the original map

**Comment by roujiamo123456** [comment]
> Do you mean animal state replication or whatever?

Hello, are you there

**Comment by roujiamo123456** [comment]
> Do you mean animal state replication or whatever?

Hello, the administrator has answered me
![Uploading Screenshot_2024-07-22-17-00-44-21.png…]()

**Comment by roujiamo123456** [comment]
> Do you mean animal state replication or whatever?

Hello, the administrator has answered me
![Screenshot_2024-07-22-17-00-44-21](https://github.com/user-attachments/assets/059bdd9c-0cd1-40f1-b9f2-83ee29b9fd80)

**Comment by roujiamo123456** [comment]
This is the answer from the server administrator I am playing with
![Screenshot_2024-07-22-17-00-44-21](https://github.com/user-attachments/assets/464d9490-d8d7-4658-867f-b01a5e59e497)

**Comment by roujiamo123456** [comment]
This is the answer from the server administrator that I am playing. The map running on this server is not an official map
![Screenshot_2024-07-22-17-00-44-21](https://github.com/user-attachments/assets/3fa58cb6-d2fa-4817-b5ab-cc2973d4b811)
