### ISSUE TITLE
Is it possibly to control console via FIFO(pipe) on linux?

### ISSUE THREAD

**Issue by 7cmb** [SmartlyDressedGames/Unturned-3.x-Community#4600]
I have dedicated a server in docker and i have wrote an entrypoint for it to run automatically.

I want to save once every 60s without rocket and put these commands in entrypoint.

This is what i tried:
```bash
mkfifo un_pipe
cat > ./un_pipe &
./ServerHelper.sh < ./un_pipe 2>&1 > ./running.log +InternetServer/MyServer
while true;do
echo 'save' > ./un_pipe
sleep 60
done
```

I also try writing to process's fd 0 and add an option "-logfile 2>&1 ./un_pipe" but all fail. So is it possibly to control console via FIFO on linux?

**Comment by SDGNelson** [comment]
It's an interesting idea! I'm afraid I don't have an official answer but will leave this open for a few days in case anyone who checks on this repo knows something and is willing to share.
