### ISSUE TITLE
Soul Crystal Ragdolls dont apply the material properly to cosmetics with transparency

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4602]
randomly noticed in pvp

"tested" with a Magenta Soul Crystal Ragdoll Modifier, shot a guy with Blue Ski Goggles i think.

![20240721224947_1](https://github.com/user-attachments/assets/24a65130-a1ac-4f0a-b892-b3ef3d8a58a6)

i would test with more ragdoll modifiers but uhh haha those are expensiveee

may happen with zero kelvin/jaded modifiers too, may happen with other transparent cosmetics.

**Comment by SDGNelson** [comment]
Thanks for the report! I suspect the issue is with multiple materials on one renderer (second material for the transparent bit).  Should be a straightforward fix thankfully since IIRC clothing on ragdolls isn't pooled.
