### ISSUE TITLE
Landmines and Claymores radius detection is too small for vehicles 

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4603]
While I was re balancing the Landmines and Claymores for my servers, I noticed most of vehicles won't toggle them. You can notice how none of the vehicles activated it, but only the bicycle. It was also only activated on a deformed land so I guess there the vehicle hitbox would meet the minimum detection distance for the landmine
https://github.com/user-attachments/assets/cd3abb60-bb3b-41a4-9d28-2b0efb02c9f4

By the way, please consider increasing the Claymore and Landmine damages:
- Claymores on real life will totally destroy you and kill you if you're on their front, from at least 0m-100m. In game you need to touch them, but they wont kill you even if you're naked

For my servers, I increased the player damage from 91 to 120 so it will kill any player touching them (just as reference)

- Landmines in real life are for persons or vehicles, however on the game the model seems to be more for vehicles. Again, in real life it would totally destroy a vehicle, but in game it does almost nothing to them, even with civil weak vehicles

For my servers, I increased the vehicle damage from 75 to 800 (just as reference)

**Comment by HathHub** [comment]
skibidi

**Comment by SDGNelson** [comment]
Thanks for the report! They might not actually be configured to collide with the tires themselves, only the vehicle body. I'll have to see whether this is something we can change without too many side-effects.

**Comment by SDGNelson** [comment]
It looks like `WheelColliders` don't generate `OnTriggerEnter` events. I think this must've been part of why wheels do their own check for the `InteractableTrapDamageTires` component. The way that works at the moment would benefit from changing to `GetGroundHit` and some other cleanup - though isn't ideal performance-wise. Unsure when/if that will be adjusted.

**Comment by ItsRodrigoAl** [comment]
@SDGNelson I was talking with Renaxon about this issue, just asking "but why on maps like Arid landmines works just fine?"

Then he said this:

![image](https://github.com/user-attachments/assets/9397a225-3127-46fa-82c4-38db2bfc2191)

![image](https://github.com/user-attachments/assets/dd9821d0-8989-4abc-80e0-2b58693a27be)

So, can not be the **collider box** of the landmines and claymores be just resized a bit to work fine? **I even tested the caltrop and it works just fine with wheels!**, so is not something related with wheels at all

Probably **maybe** you want to make the landmines and claymores work with the wheels too (just like the caltrop) instead of the whole vehicle itself in the future... but for the meanwhile, doesn't sounds good to you just resizing the box collider of them for the meanwhile?

**Comment by SDGNelson** [comment]
The reason the Caltrop works differently is it has the `Damage_Tires` flag which adds the `InteractableTrapDamageTires` component I mentioned.

While increasing the height of the landmine collider does allow them to touch the vehicle body rather than the wheels, it also increases the likelihood of detonating when the player is jumping over it. You're free to make that adjustment for your server though of course!

**Comment by ItsRodrigoAl** [comment]
For anyone wanting this bug to be fixed for your vanilla servers, if you're using uScript you can easily paste this script into your server. It will remove the landmine placed by the player and put a new one only 0.22m above, keeping all the owner data of the previous one. With this, vehicles can actually explode with them (only landmines, not claymores)

```cs
event onBarricadeBuild(player, id, position, cancel)
{
    if(!player) return;
    if(id != 1101) return;
    playerGroup = "0";
    if(player.isInGameGroup) playerGroup = player.gameGroup.id;
    if(player.isInMainGroup) playerGroup = player.steamGroup;
    cancel = true;
    player.inventory.removeItem(1101);
    spawner.spawnBarricade(1101, vector3(position.x, position.y+0.22, position.z), 270, 0, 0, player.id, playerGroup);
}
```


Or if you're more skilled you can recreate it easily with a plugin based on this (send it to me tho XD)
