### ISSUE TITLE
Modal flag bug.

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#4605]
If you set a flag `EPluginWidgetFlags.Modal` for a player when he uses a item `UseableConsumeable`, he will be able to walk and rotate the camera.

### To check you need:
0) Pick up a bottle of water and start using it.
1) Set modal flag.

**Comment by SDGNelson** [comment]
I'm not sure I understand what you're trying to achieve. Can you elaborate, please?

**Comment by surv0013** [comment]
I want it so that when the player opens the custom interface, he can't walk and rotate the camera. It usually works like that, but if the player uses an useable item, the modal window is not works. That is, the interface appears, but the cursor does not, so he can continue to walk and rotate the camera.

**Comment by SDGNelson** [comment]
Are you sure the Modal flag is actually getting enabled?

**Comment by SDGNelson** [comment]
Closing but feel free to comment and I'll re-open.
