### ISSUE TITLE
Animal refresh issue

### ISSUE THREAD

**Issue by roujiamo123456** [SmartlyDressedGames/Unturned-3.x-Community#4606]
At an animal refresh point,
Whether creating two groups, add one animal to each group. Create a group and add two animals to it. This refresh point can only select one animal to refresh after each server restart, and cannot randomly select "animal B" to refresh after "animal A" dies

**Comment by SDGNelson** [comment]
This is one of the limitations of animals at the moment, sorry. They are very half-baked. 😞
