### ISSUE TITLE
UseableGunEventHook.cs missing Inspect related UnityEvent

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4607]
The lack of this event breaks items with inspect animations that manipulate the item's armature. For example, guns with inspect animations where the player pulls back the charging handle to check the chamber.

For Hammer animations, this is fixed with using the 'On Chambering Started' event:

![image](https://github.com/user-attachments/assets/b5f17fe5-8c48-4ad4-961a-1bd7faca3afd)

However, there is no such event for Inspect animations, which complicates the fix. The only solution is to copy the Blender animation clip, turn it into a Unity animation clip, and manually disable the animation component in the animation clip. This process is a hassle because it must be repeated every time a change is made to the inspect animation.

Solution would be to add these:

![image](https://github.com/user-attachments/assets/aa7e3e3b-a127-4695-9ce0-6b043e7d0d02)

**Comment by SDGNelson** [comment]
This has actually been brought up a couple of times recently so I'll see about adding a separate component for the base item events since any item can be inspected!
