### ISSUE TITLE
Incorrectly named Slot in Diner #1

### ISSUE THREAD

**Issue by HathHub** [SmartlyDressedGames/Unturned-3.x-Community#4608]
![image](https://github.com/user-attachments/assets/bbfaeaef-ef2c-470c-ad6b-4b71b48312e7)
One of the door slots of diner #1 is named "Door (1)", assuming you ctrl c and ctrl v it and forgot to rename. not huge issue, just a heads up.

**Comment by surv0013** [comment]
#4254

Emmm...

**Comment by SDGNelson** [comment]
Oof thanks for the report!
