### ISSUE TITLE
Don't add physics materials from other maps to PhysicsMaterialNetTable.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4609]
I'm running into the limit for physics materials, and since you need a physics material now to set up a tire motion effect you kind of need one for each landscape material, and because of #4087, all maps' assets must be loaded at startup to use the maps in multiplayer.

Not entirely sure if this makes sense, but I'm proposing not adding any physics material assets from any other map mods that aren't the current map to `PhysicsMaterialNetTable`, except when the physics material is referenced by the current map's landscape materials.

If this doesn't make sense maybe the limit could just be raised to 255.

**Comment by DanielWillett** [comment]
On second thought it would probably make a lot more sense to just remove the limit for singleplayer.

**Comment by SDGNelson** [comment]
Darn I hoped nobody would hit the limit anytime soon. Since the table is different per-server I think we can infer the number of bits needed for the index and remove the hardcoded limit. 🤔
