### ISSUE TITLE
Spraypaint texture bug with the bike - Tiny issue

### ISSUE THREAD

**Issue by CircleTrigonist** [SmartlyDressedGames/Unturned-3.x-Community#4610]
There's a small issue with the bike where the body of the bike is painted but a few areas retain their default color.
https://github.com/user-attachments/assets/c1e41c43-47ce-4624-8fad-ec6beb7ba574

**Comment by ItsRodrigoAl** [comment]
I dont think is a issue. Look for example the Otter, some areas aren't painted neither and its intentional

**Comment by SDGNelson** [comment]
I think this was intentional but I don't recall why. Maybe the light grey areas should be a shade darker but the same color as the paint.

**Comment by CircleTrigonist** [comment]
My bad thought it was a bug just by the way that my mind was bothered by it.
