### ISSUE TITLE
tank bug

### ISSUE THREAD

**Issue by Lo7us** [SmartlyDressedGames/Unturned-3.x-Community#4612]
**you press z in front of the drivers part of the tank, you wait, they drive the tank and you can go up to the limit with the tank, there is a video recording

https://github.com/user-attachments/assets/156311d5-7855-44c5-8d71-aab4e091210b

1 the location is inside the tank , it has no location on the map , it is made inside the tank

2 If someone entered by pressing z while in the car, the driver should be prohibited from getting into the car, he should give a warning, or the automatic killing of the person who pressed z in the car may be a solution, sorry for my English

3 
With this bug, players can quickly go to skybase, easily raid, and spoil the pleasure of the game**

**Comment by ItsRodrigoAl** [comment]
It's a well known issue, actually, and sadly this has existed for years :/

**Comment by ItsRodrigoAl** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4444

**Comment by Lo7us** [comment]
> #4444
