### ISSUE TITLE
Washington bridge issue.

### ISSUE THREAD

**Issue by tarzandomates** [SmartlyDressedGames/Unturned-3.x-Community#4613]
1.Location and map.
washington-You can enter the bridge next to the police station near Seattle mili.

2.How to replicate the issue.
When we enter the bug, we can throw it to the spawn or kill it, but if we enter it by mistake, we will lose our loot and the players will complain, it would be more useful to throw it to the spawn.

3.How it effects gameplay.
First of all, it affects the game negatively, everyone builds houses inside the bridges or enters the houses from the roofs of the houses and raids them easily.
 
https://github.com/user-attachments/assets/51c5a932-d0f1-4fdf-9048-615e0ea20f9e

**Comment by Jdance-Media** [comment]
Side note: Is this vanilla Washington? I'm seeing the European bridge instead of the typical yellow line.

**Comment by tarzandomates** [comment]
Sorry, I tried another SW, I'll post the Washington one right away.

**Comment by SDGNelson** [comment]
Unfortunately, it appears to be this issue: https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds

It *might* be slightly better in the next update, however, thanks to some changes to movement. 🤞

**Comment by tarzandomates** [comment]
I had this problem before, but I didn't worry about it much, then I contacted you because it would negatively affect the game.
