### ISSUE TITLE
unturned failed to respawn an item with ID 0 error help me pls

### ISSUE THREAD

**Issue by qJaiL** [SmartlyDressedGames/Unturned-3.x-Community#4614]
![image](https://github.com/user-attachments/assets/e8ac0d87-48e9-4040-afff-d56411806b87)

**Comment by SDGNelson** [comment]
An older unhelpful error message! This means the level has an item spawn placed using the table "Elma" which contained an item with ID 0 (invalid). Is this your level?

**Comment by qJaiL** [comment]
I added this mode from morefarming mode and typed the apple id in more farming from spawn in the map editor section and spawned it.

**Comment by SDGNelson** [comment]
It might've been accidentally entered in the "table ID" field, or you might have a spawn tier without any items in it.
