### ISSUE TITLE
How to change the exit position of the vehicle?

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4615]
[远程四轴飞行器.zip](https://github.com/user-attachments/files/16434899/default.zip)
I made a vehicle and added a rigid body to its seat to separate the seat from the vehicle, achieving unmanned driving. However, when getting off the vehicle, the person will get off from the side of the vehicle. How can I change the exit position?
![8P1{EJ_HWLGA)05V{3$ 4PS](https://github.com/user-attachments/assets/c3108f62-2913-4917-b23a-d65835d01ea8)

**Comment by SDGNelson** [comment]
It uses the position of the child transform named Center, but you could probably use a position constraint to lock it to your external seat. Note that this isn't officially supported, however.
