### ISSUE TITLE
Where can I find more mod hooks

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4616]
I am a server owner with 2 years of experience, and I really enjoy adding mod hooks to mods because I don't know how to write plugins. Where can I find more of the latest mod hooks?

**Comment by GazziFX** [comment]
Unturned/Extras/Sources/Project.unitypackage

**Comment by SDGNelson** [comment]
Thanks GazziFX - yes, that's the only source of scripts/components that are officially supported.
