### ISSUE TITLE
Placing glass on a non-structural surface will skew

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#4621]
1. Appears only on the server.
2. This bug occurs when a "slot" obstacle appears in the shadow and moves the position and then puts it down.

https://github.com/user-attachments/assets/80a76930-3403-4c60-b658-edf2fe75a111

**Comment by SDGNelson** [comment]
Thanks for the report! I'm not sure I understand, however: Are both barricades a window? And the problem happens when attaching the window to another window?

**Comment by prank0079** [comment]
The first was "Pump Jack" and the second was "Glass."

**Comment by SDGNelson** [comment]
Could you attach or email the masterbundle/unity3d and dat file for those items please? Then I'll try loading them up to reproduce the issue.

**Comment by prank0079** [comment]
[Bundles.zip](https://github.com/user-attachments/files/16485305/Bundles.zip)

**Comment by SDGNelson** [comment]
Thank you! I'll check it out soon.

**Comment by SDGNelson** [comment]
When I tested with your example the second item aligns with the scaffhold on both client and server:

![image](https://github.com/user-attachments/assets/00bda56f-b2a8-4998-81e6-a698532005e0)

In case it is related to the slot as you speculated in your first post, I wonder if it would be worth trying with the PlacementPreviewPrefab override? This way your orange/blue preview item could exclude the extra slots.

**Comment by prank0079** [comment]
I added, and did not fix.
I found that this bug was triggered when players were facing east and west, and remained even after exiting and re-entering the server.


https://github.com/user-attachments/assets/1aad3e6f-33c5-40c1-b8b0-05becc6bb456

**Comment by SDGNelson** [comment]
Ohhh I think this may actually be as simple as an oversight on my part with the change to quaternions for barricades! I'll put a potential fix on the preview branch shortly. 🤞

**Comment by SDGNelson** [comment]
I think this should be fixed in the preview version if you get the chance to give it a try, though it's understandably a bit of a hassle to set up the preview branch server and everything - it should be released next week in any case.
