### ISSUE TITLE
Plugin hotkeys cause the game to crash.

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#4622]
The TPA plugin I use is this: https://github.com/F-Plugins/Teleporting
This plugin supports hotkeys Q (reject request) E (accept request), and the game crashes when I press E
Tested it twice and the game crashed both times.
[Unturned.zip](https://github.com/user-attachments/files/16487679/Unturned.zip)
This is the game log.
[Crashes.zip](https://github.com/user-attachments/files/16487682/Crashes.zip)

**Comment by SDGNelson** [comment]
It looks like the crash happens in a microsoft library "textinputframework" accessing an invalid address. I doubt this is within our control, sorry.
