### ISSUE TITLE
UI Overlap

### ISSUE THREAD

**Issue by 0x5BC2** [SmartlyDressedGames/Unturned-3.x-Community#4623]
On smaller/weirder resolutions, if you open a map editor panel that has a bit more features, windows on the side etc, it may cause those to overlap the escape menu rendering some, if not all of the buttons useless due to the sort layer setting of the escape menu being below the map editor layer, I would assume.

https://github.com/user-attachments/assets/3b9da724-6f49-4b0f-b161-db629adf2c17

https://github.com/user-attachments/assets/27f8934b-91f1-45cb-8e1c-496524e56da0

**Comment by SDGNelson** [comment]
There's a lot of ugly stuff in the editor UI. 😞  Unfortunately, I don't think otherwise functional editor UI stuff like this will be addressed soon, sorry.
