### ISSUE TITLE
assets not loading for some people?

### ISSUE THREAD

**Issue by GatoAgus** [SmartlyDressedGames/Unturned-3.x-Community#4625]
could you check this pls nelson rn i think is a game bug because there is 2 people, not only 1.
It could be a bug of some update you did that affects some devices, you could try talking to them.
https://discord.com/channels/324229387295653889/1270562576627138641
https://discord.com/channels/324229387295653889/1270010140124516503
![imagen_2024-08-07_193040253](https://github.com/user-attachments/assets/751ee450-6e38-4454-acea-cd41e15dae40)
![imagen_2024-08-07_193137905](https://github.com/user-attachments/assets/99ed1b92-272e-44a2-a0c1-ca7e9e60c837)

**Comment by MoltonMontro** [comment]
It sounds/looks like they have a bunch of mods installed. Their hardware might not be strong enough for whatever they're trying to do. If they haven't already, those users should try uninstalling all of their mods and seeing if the game loads.

**Comment by GazziFX** [comment]
There are probably some errors in the logs, without looking at them we cant determine your problem

**Comment by SDGNelson** [comment]
I would guess the crash is from running out of RAM, but otherwise yes if you can attach the [log file](https://support.smartlydressedgames.com/hc/en-us/articles/12299037547284-Where-are-the-log-files) we can take a look.

**Comment by SDGNelson** [comment]
Closing for the meantime but feel free to comment or submit a support ticket.
