### ISSUE TITLE
Possible exception message mistake due to copy paste.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4626]
![image](https://github.com/user-attachments/assets/707c7066-cc94-46c6-bcdf-af8a42b467df)
For `GuidBuffer`, the `Read` method refers to the 'destination buffer' in the exception message, but it is checking the source buffer. The `Write` method has the same exact message, so it seems like the message wasn't modified when copied.

**Comment by Jdance-Media** [comment]
Someone ran into the exception for the source array being too short, it is confusing to refer to the destination array.

**Comment by CyberAndrii** [comment]
It was fine back in the day when `GuidBuffer` was written, but now that it is possible to do "reinterpret cast", it can be rewritten as follows:

```cs
using Unity.Collections.LowLevel.Unsafe; // defined in UnityEngine.CoreModule.dll

internal static unsafe class GuidHelper
{
    public static Guid Read(byte[] source, int offset)
    {
        if (offset + sizeof(Guid) > source.Length)
        {
            throw new ArgumentException("Source buffer is too small!");
        }

        return UnsafeUtility.As<byte, Guid>(ref source[offset]);
    }

    public static void Write(Guid source, byte[] destination, int offset)
    {
        if (offset + sizeof(Guid) > destination.Length)
        {
            throw new ArgumentException("Destination buffer is too small!");
        }

        UnsafeUtility.As<byte, Guid>(ref destination[offset]) = source;
    }
}
```

This not only reduces the amount of code but also improves performance by avoiding memory pinning.

PS: `UnsafeUtility` is an alternative to `System.Runtime.CompilerServices.Unsafe`, which is internal in Unity.

**Comment by DanielWillett** [comment]
There's also a new constructor that takes a read only span and a Guid.TryWriteBytes available in the new unity version unturned is using now.

**Comment by CyberAndrii** [comment]
Hm, I always thought it wasn't possible to use spans in Unity, like the Unsafe class. Idk why Nelson doesn't use them everywhere already.

**Comment by SDGNelson** [comment]
Whoops, thanks!

AFAIK System.Span only became available to us after the most recent engine update. Relatively recently `getRagdollEffect` was updated to use it and I think that's the only place in the entire project so far.

Thanks for the tips about guid span constructor and `Guid.TryWriteBytes` as well! I'm not going to change for this update to avoid breaking anything more on preview, but I will keep it in mind for the next time we are working on those!
