### ISSUE TITLE
[CRITICAL - PREVIEW BRANCH] Objects.dat writing bug

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4627]
![image](https://github.com/user-attachments/assets/ca29a7e5-d044-44c9-a7a7-754aa73a4543)
If an object isn't found, the new boolean value won't be written to the river, causing any v12 files to be corrupted if there's an object missing an asset.

**Comment by DanielWillett** [comment]
I created a small program to fix this here if anyone's files are corrupted.

https://github.com/DanielWillett/UnturnedPreviewObjectDatFix/releases/tag/v1.0.0

**Comment by SDGNelson** [comment]
Yikes, sorry about this! I'll get a patch up on the preview branch shortly to help prevent it from affecting anyone else.
