### ISSUE TITLE
Game refuese to launch after reverting from preview branch

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4628]
I have switched to preview branch to see whats new, after I've reverted from the preview branch the game refuses to launch `Client.log`'s last messages are command line argument parsing messages. The game's window is transparent untill you minimize, open it again and then its black and then stops responding and crashes in the end (UnityCrashHandler does not kick in). 

Temporary Fix: Disable steam could sync (`Steam Settings -> Cloud`), go into your `Steam\userdata\<steamid>\304930` folder and delete it, then launch the game and close it after it opens, then re-enable steam cloud, launch the game again and when it asks you which save would you like to choose, select `Local Save`.
 -> WARNING: This will erase your character data (Equipped skins, characters) and saves.

**Comment by SDGNelson** [comment]
Sorry about this! To test I changed from the preview to public branch, but in my case I didn't run into this. There were a variety of new settings added, perhaps the server filter settings in particular caused this.

Typically the public branch isn't forwards-compatible with the preview branch, that is, it can't load **newer** save formats, however the new version should always be able to load **older** save formats. That said, I try to keep new data at the end of the files to avoid breaking after changing.

I'll make a note to write a warning message to always include in the preview branch notes in the meantime.
