### ISSUE TITLE
BattleEye Error

### ISSUE THREAD

**Issue by FreakSp** [SmartlyDressedGames/Unturned-3.x-Community#4629]
I keep getting banned for a few seconds by the battle eye, and idk why
![image_2024-08-08_200915009](https://github.com/user-attachments/assets/8eecd34e-59c8-48ec-a7bb-c945b83be2bd)

**Comment by SDGNelson** [comment]
Sorry for the trouble, here's the relevant support article: [BattlEye Unofficial Modules not supported](https://support.smartlydressedgames.com/hc/en-us/articles/12856410339604-BattlEye-Unofficial-Modules-not-supported)
