### ISSUE TITLE
Horses.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#463]
Yes, I understand that a horse is not only a horse, but also a seat and a cart.
I understand that you are working on 4.0, and you do not have time.
But still, I will try to tell you how inadequate horses are.
For example: In Unturned we have a lot of diversity from the past to the future.
But the past without horses is boring.
I wanted you to add a horse.
I can also help you in both the models and the animation.

Here it is the same wild west...
![20180410211354_1](https://user-images.githubusercontent.com/32962870/48751215-7545f980-ecc6-11e8-8f30-341d69d7915c.jpg)

**Comment by VitaxaRusModding** [comment]
There is another option:
Add a play (or event) to the animation (forward, back, etc.).
Well, it would be nice to add hunger instead of horse fuel.

**Comment by aviadmini** [comment]
For The Horse!
Feed horses with fuel, that is how true slavs do (they use vodka tho)

**Comment by SDGNelson** [comment]
Planned for 4+, but you're right that it won't be added in 3.
