### ISSUE TITLE
Airdrop plane sound bug

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4631]
Sometimes when an airdrop its called, it sound an small "bump" before the sound of the current plane starts playing near you. This happens as well with vanilla and curated maps, and happens **sometimes**, not always, however it can be easily reproduced by just calling a lot of airdrops with /airdrop

Sorry if this is a know issue, but this has existed since I ever started to play again Unturned back on 2021

**Comment by SDGNelson** [comment]
Does it sound like you hear the airdrop near you for a very short time? I haven't personally run into this before but will try listening for it. 😕

**Comment by Jdance-Media** [comment]
I can confirm that I've experienced this issue on two different systems before.

**Comment by SDGNelson** [comment]
I'm not at all confident that it'll resolve it, but I've changed spawning these to use the Instantiate override that takes the initial transform in case for some reason it was audible from the map center. 🤞

**Comment by ItsRodrigoAl** [comment]
I guess it was fixed with the latest preview branch

I joined to PEI and Washington on singleplayer, called a lot of airdrops and none of them did that weird sound. However when I reverted the version to the latest public one, literally the first airdrop I called made that sound, so I think it was finally fixed

**Comment by SDGNelson** [comment]
Glad to hear it seems to be fixed! That's so weird - no difference on my end when tested - I wonder why it's different. I'll add this to the changelog.

**Comment by Jdance-Media** [comment]
I can also vouch for it being seemingly fixed.
