### ISSUE TITLE
(Preview branch) Bicycle drives faster going backward than forward

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4633]
And also if you're going backward and you try to rotate to left and then to right, you won't be able to until the bicycle stops. it works weird

**Comment by ItsRodrigoAl** [comment]
Forget to mention, it was while shifting

**Comment by SDGNelson** [comment]
Thanks for the report! Fixed for the next preview version.
