### ISSUE TITLE
(Preview branch) Inconsistency on Audio menu background box

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4634]
As you can see on the "subtitle" options like Movimiento and Postura, those background boxes are with a good size since these are the same size around all the UIs on the game

![2024-08-10_04-49-30](https://github.com/user-attachments/assets/80996d87-79a3-4b29-bd0e-29f589651ad8)

However for the new "Music" subtitle one on the Audio menu, its looks pretty oversized compared to the ones above
![2024-08-10_04-49-35](https://github.com/user-attachments/assets/39b63eb6-6d27-4a66-8c6b-854a93e73b1c)

**Comment by SDGNelson** [comment]
Fair point, I'll make those consistent, thanks!
