### ISSUE TITLE
Volatiles dont have their material properly replaced by ragdoll modifers

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4635]
![Screenshot_17](https://github.com/user-attachments/assets/45a4744d-4223-46c8-b044-151cc9ca407a)

this *MIGHT* be fixed on preview branch but i have no idea as i found this on latest build
tested with soul crystals and ice

**Comment by SDGNelson** [comment]
Thanks for the report! I'll check whether this is fixed on the preview branch.

**Comment by SDGNelson** [comment]
Indeed a separate issue, should be fixed in the next preview version!
