### ISSUE TITLE
(Plugin issue) Teleporting a car is basically impossible

### ISSUE THREAD

**Issue by TheMew0** [SmartlyDressedGames/Unturned-3.x-Community#4638]
When trying to teleport a car by using standard methods or by just changing the "position" vector3, the server "interpolates" the car's movement for some reason, and because of that the car appears to smoothly move towards its destination instead of teleporting instantly. The only solution to teleport cars at the moment is to despawn the car and spawn the identical one at the destination. A new method would me much appreciated by the developers.

**Comment by SDGNelson** [comment]
Unfortunately, you're right that there isn't a way to disable interpolation at the moment. This isn't a bug so I'm closing this issue for the meantime, but as a workaround you might be able to "slowly" teleport it by moving it underground, moving horizontally, then moving back up? This would prevent the interpolation from flying through the air at least.
