### ISSUE TITLE
Server does not show on Internet List with Fake IP active

### ISSUE THREAD

**Issue by stan9564** [SmartlyDressedGames/Unturned-3.x-Community#4639]
My server does not show up on the internet list with the Fake IP function active, however, when I turn it off, it shows as usual

server ip: 104.234.224.240:26913

**Comment by SDGNelson** [comment]
No idea comes to mind as to why this would be happening, sorry. If it has no players online it might not be prioritized by the master server, but that's just a theory - it's a black box.

**Comment by stan9564** [comment]
Figured it out, I was using a shared pterodactyl host, FakeIP was trying to
use a port my server didnt have access to, fixed by using a dedicated server

Em ter., 13 de ago. de 2024 22:20, Nelson Sexton ***@***.***>
escreveu:
