### ISSUE TITLE
(Preview branch) Online Safety screen won't show again if you go back on it

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4640]
There's a `Dont show this again` label at bottom on the Online Safety screen but, when is your first time seeing that screen, if you go back, it won't show again that screen on that player session, no matter if you didn't clicked on the label. It should always show that screen until you click the label to confirm you actually don't want to see it again

**Comment by SDGNelson** [comment]
Good point: Currently it shows it once per session. So if you restart the game it will show again. I'll change this so that it only shows once per session if you click the "proceed" button.
