### ISSUE TITLE
(Preview branch) Online Safety screen description text is too short for translations

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4641]
Can be the lines for the description text increased a bit? Maybe only 1 or 2 lines just in case

Translating the original english text:

`Please be careful online! Never share personal information - such as your password, address, phone number, age, or full name - with other people. Multiplayer servers are hosted by other players, so your experience may vary significantly.`

Into spanish:

`¡Por favor ten cuidado estando en línea! Nunca compartas información personal - como tu contraseña, dirección, número de teléfono, edad, o nombre completo - con otras personas. Los servidores multijugador están alojados por otros jugadores, así que tu experiencia puede variar significativamente`

makes the text only be visible until "experiencia".

![2024-08-14_02-45-27](https://github.com/user-attachments/assets/1a485aa9-b93f-4d42-bb06-8da54bcdf1f1)

**Comment by SDGNelson** [comment]
Thanks for including it in your translation! Sure, I'll increase the height of that label. This is a good example of why we need more auto-layout features for the UI. :[
