### ISSUE TITLE
The problem I am currently facing

### ISSUE THREAD

**Issue by roujiamo123456** [SmartlyDressedGames/Unturned-3.x-Community#4642]
1 I put a box in the safe zone, but it didn't get attacked but lost blood. I asked the server administrator, and the server administrator said it might be a game design issue
2 I am playing with a mod server, and my backpack shows as available but unable to retrieve items, indicating that it is full. I asked the server administrator, and they told me that the game is designed with a container that can only hold 225 items

So, I hope to address the issues of blood loss in safe zones and backpack capacity. For example, if the backpack has a capacity of 500, it can hold items with a capacity of 500 instead of 225

**Comment by SDGNelson** [comment]
Ideally, yes, the item limit per storage would be unlimited. This is unlikely to change until when/if we can do a rewrite of some of the inventory features, however.

Can you elaborate on what you mean by point 1 please?

**Comment by roujiamo123456** [comment]
> Ideally, yes, the item limit per storage would be unlimited. This is unlikely to change until when/if we can do a rewrite of some of the inventory features, however.
> 
> Can you elaborate on what you mean by point 1 please?

The box loses its health without any attack

**Comment by roujiamo123456** [comment]
> > Ideally, yes, the item limit per storage would be unlimited. This is unlikely to change until when/if we can do a rewrite of some of the inventory features, however.
> > Can you elaborate on what you mean by point 1 please?
> 
> The box loses its health without any attack

This server plugin is not related

I remember putting the box on July 11th, and on July 29th, I reported to the server administrator that the box had lost blood. During this period, I went online every day

**Comment by roujiamo123456** [comment]
> Ideally, yes, the item limit per storage would be unlimited. This is unlikely to change until when/if we can do a rewrite of some of the inventory features, however.
> 
> Can you elaborate on what you mean by point 1 please?

The box loses its health without any attack

This server plugin is not related

I remember putting the box on July 11th, and on July 29th, I reported to the server administrator that the box had lost blood. During this period, I went online every day

**Comment by roujiamo123456** [comment]
> > Ideally, yes, the item limit per storage would be unlimited. This is unlikely to change until when/if we can do a rewrite of some of the inventory features, however.
> > Can you elaborate on what you mean by point 1 please?
> 
> The box loses its health without any attack
> 
> This server plugin is not related
> 
> I remember putting the box on July 11th, and on July 29th, I reported to the server administrator that the box had lost blood. During this period, I went online every day

This period refers to July 11th to July 29th

**Comment by roujiamo123456** [comment]
> Ideally, yes, the item limit per storage would be unlimited. This is unlikely to change until when/if we can do a rewrite of some of the inventory features, however.
> 
> Can you elaborate on what you mean by point 1 please?

The box loses its health without any attack

This server plugin is not related

I remember putting the box on July 11th, and on July 29th, I reported to the server administrator that the box had lost blood. I logged into the game every day from July 11th to July 29th

**Comment by SDGNelson** [comment]
Someone standing outside of the safezone may have damaged it (safezone prevents players inside from taking damage but not barricades). It does sound like it might be a plugin otherwise, as the vanilla game doesn't damage barricades over time.
