### ISSUE TITLE
Add note to online safety menu that settings can be changed later from options menu

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#4645]

**Comment by MoltonMontro** [comment]
*By extension, maybe warning should be something players could re-enable if they _do_ want to continue seeing it? E.g., a toggle in the Options menu. Defaults to **On**, but the "Don't show this again" toggles it to **Off**.

Alternatively, having it tied to something like resetting the Options menu back to defaults. (But no dedicated button for toggling on/off.)

**Comment by SDGNelson** [comment]
Sure, that sounds like a good addition as well.

**Comment by SDGNelson** [comment]
+Adjust wording of options in safety menu to make it clearer the "OFF" is the *current* state
