### ISSUE TITLE
Jump height reduced?

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4648]
Now the character is jumping at a lower height than before and I don't know if this was intentional or not

For example, before the update, if you had your jump skills at max, you were able to jump the fences at Summerside Military Base completely normal. Now, it is way more difficult, but still not impossible, and that's a problem 

Was this intentional? If it was, it should still be retouched to reduce the height a little more so at least you know you won't actually be able to jump higher than these kind of fences (which are very common), otherwise is really annoying now trying to jump like 15 times above the fences until you finally get it, when before you were always able to do it

If it was not intentional, well, there you go, something to investigate :]

**Comment by SDGNelson** [comment]
Thanks for the report! Not intentional. 😕

**Comment by ItsRodrigoAl** [comment]
@SDGNelson After the patch, now there's another problem with the player movement:

you can climb trees again, just like in 2016 lol

**Comment by SDGNelson** [comment]
At first I thought it was entirely caused by the floor snapping, but during testing even with the slope limit it seems easier. I think it's because you can get closer to the tree itself now, which has also made the annoying falling-through-outward-sloping-surfaces worse. Bah.

**Comment by SDGNelson** [comment]
For the next update I ended up reverting part of the recent changes that allowed you to get closer to surfaces than before.
