### ISSUE TITLE
In crafting table,  Item's Model overrided skill requirement

### ISSUE THREAD

**Issue by Gloa233** [SmartlyDressedGames/Unturned-3.x-Community#4649]
I had to make my model horizonally
![d6dc79cd6fb960077a8f0fb9074c46643187c84e](https://github.com/user-attachments/assets/00b3c584-a76e-45f4-b118-e146e546e2f2)

**Comment by SDGNelson** [comment]
Sorry about that! Unfortunately, the crafting menu UI is not well laid out to say the least. Ideally, it will be revised as part of a future crafting update.
