### ISSUE TITLE
Regarding online safety link changes

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4652]
This is less of an issue, and more of a question and suggestion about the change.
Keeping in mind the patch notes listed the goal as "These changes are intended both to increase safety for younger players, and to improve the first-time player experience."

1)
What is the purpose of disabling direct Discord links if they can still be linked through external sites?
Surely seeing a direct "https://discord.gg/" link is safer for players to click on than a custom URL that _claims_ to be a link to the network's Discord.
You can also still link to a manually created Steam linkfilter to bypass the Discord link filter - which is effectively identical to using a direct Discord link since all links should be put through the filter anyway?
<img width="432" alt="image" src="https://github.com/user-attachments/assets/830b9371-fd7a-494e-bff2-594f6b5babc9">

2) 
If the goal is both safety and improving player experience for the younger players, I suggest the the Browser Request should still display the final destination link, rather than the steam link filter. Younger players especially are going to have a hard time reading a linkfilter link and understanding what website they're actually being sent to.

**Comment by SDGNelson** [comment]
Thanks for starting a discussion about this!

1. In part we wanted to increase friction to joining Discord servers. Previously, for example, you could click the link in the lobby screen and it would immediately open the Discord app to join. As you pointed out there are a few workarounds that require more effort. Maybe we should direct it to the Steam link filter instead of blocking.

2. I agree we should change it to display the original link rather than the directed link in the patch.

**Comment by AdamDN** [comment]
I understand the intention behind it, but realistically it's going to be impossible to block masked URL's that server owners are going to be forced to resort to. I think unblocking it and just filtering it with the rest of the links would be the best option.
At least a direct discord.gg/ link will always be safer to click on than a masked link. 

Perhaps you could add this notice from the patch notes as a pop-up when clicking on a Discord link: 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/0fe1d7ec-9dcc-472f-8903-7e1f66b8d491">
But even then, I think if you added _any_ form of friction people will still choose to use a masked URL to avoid it. 

I would also propose that if you want to tackle players getting linked to unsafe Discords, then server owners adding Discord links to the lobby page and browser requests is a lot less of an issue than regular players putting Discord links in chat and on signs.

**Comment by SDGNelson** [comment]
Okay: Today we've updated the link filter to show Discord links via Steam's link filter rather than blocking them!
