### ISSUE TITLE
Add new filter and gasmask properties

### ISSUE THREAD

**Issue by Gloa233** [SmartlyDressedGames/Unturned-3.x-Community#4653]
Some maps have multiple types of gasmasks and filters, 

but in reality, their properties are the same within the same dead zone.
That‘s monotonous.

I think adding filter and gasmask codes to Unturned,which can adjust the filter to recover the durability value of the gas mask,and gasmask‘s maximum using time.

**Comment by SDGNelson** [comment]
Closing as the issue tracker is intended for bug reports. To clarify, however, the gasmask can affect the settings after a relatively recent update. Ideally, filters would be able to, but it would require additional per-item data that we don't have a good way to add retroactively at the moment.
