### ISSUE TITLE
The problem of climbing pine trees upwards

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4654]

**Comment by hyjhkt** [comment]
[Unturned 2024-08-17 09-54-23.zip](https://github.com/user-attachments/files/16643041/Unturned.2024-08-17.09-54-23.zip)

**Comment by SDGNelson** [comment]
Thanks for the report and sorry about this! There have been a few reports of unintentional side effects from the change to floor snapping, and I believe this is one of them. I ought to get it sorted out for the patch this coming week.

**Comment by MoltonMontro** [comment]
@SDGNelson It looks like this is still an issue as of the latest patch. https://forum.smartlydressedgames.com/t/easy-climb-is-canon/24976

**Comment by SDGNelson** [comment]
At first I thought it was entirely caused by the floor snapping, but during testing even with the slope limit it seems easier. I think it's because you can get closer to the tree itself now, which has also made the annoying falling-through-outward-sloping-surfaces worse. Bah.

**Comment by SDGNelson** [comment]
For the next update I ended up reverting part of the recent changes that allowed you to get closer to surfaces than before.
