### ISSUE TITLE
Feature Request: Ingame dumpable universal ID viewer (modding/testing/informational tool)

### ISSUE THREAD

**Issue by Darkmega18** [SmartlyDressedGames/Unturned-3.x-Community#4655]
Basically, I'd like to request a feature where as the game loads the items from various mods and assets it should note down the id of the items and collate them into a sortable ingame list of various ids somewhere within maybe the developer's window _(same area where you can check for mod errors, upload mods etc)_ .

While online unturned item id lists exist and can sort of be searched this becomes a whole lot more dicey when you install mods and and you want run cross compatibility through recipes or just want to get the ids of item for servers/testing and such reasons.
It likely also puts a bit of stress on modmakers to always list their item ids on their pages, but it is a task and a half to micromanage a lot of tabs and guides from said developers to know your item ids you're putting into your own game.

Instead with this suggested feature the game itself would note these ids as it loads and list them somewhere nicely. Then if someone wants to they could then sort the list, whether by straight numerical order _(1 2 3 4 5 etc down the line)_ or sort by sectioned numerical alphabetical source _(mod source of the item as a category and then numerical in those sections)_.
Also the list could catch the ingame name of the item it corresponds to and people could sort by alphabetical on that list.

Think of it like a details view in your file explorer but the files are items (and vehicles and other features that use ids also) which also list their name, source and type. _(having it know the type and being able to hide or show what kinds of ids you're looking for would be huge also.)_

The main point would be that this searchable ingame list should then be able to be dumped into a text file as just a simple list which you can throw into a post for people to have ids at a glance _(but still be able to fetch them in game themselves)_ or for a jaded quality of life recipemaker like myself can quickly find and search for specific ids and things and not have to spend hours bouncing back and forth between tabs memorizing the ids of several mods I'd like to do recipes for. :(

If done right this could also check and warn players about overlapping item ids when they make their mod which users can very easily warn their modmakers about to get the ids fixed and you could see exactly where they are _(cause two or more items with the same id would be present.)_

**Comment by Jdance-Media** [comment]
Hi, feature requests are not within the scope of the issue tracker currently. It would be best if this was posted in 'Discussions', which was suggested in the past by Nelson has the alternative.

**Comment by SDGNelson** [comment]
Thanks Jdance, yes closing this post for the meantime for that reason.

I agree this would be a very useful QoL feature. Every time I open a spreadsheet to check IDs it's like, yep, really need to get to adding that. :X

**Comment by Darkmega18** [comment]
crap, I forgot. >_< been another long period between thoughts of unturned.
