### ISSUE TITLE
The ability to add Lobby Server

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#466]
The Ability to add Custom Lobby to servers like waiting lobby for queue with custom music wich owners of the servers can change it. 
That can be good for roleplay servers, to show the rules and that things in the screen.
It can be too an option to enable or not

**Comment by JustOneMoreBlock** [comment]
I'd like the idea of a proxy-based server to where you can have just one hostname, and add a bunch of servers.

A custom map could be created and as you suggested would be a "Lobby" or "Hub" server.

Then a GUI could be created to show all connected servers from within the server.

**Comment by educatalan02** [comment]
Yeah like a hub full customized by owners, with the option to enable it or disable it

**Comment by Trojaner** [comment]
Regarding "custom Lobby": Plugins can do that as well...

I guess Proxy-based servers (like bungee) are a bit hard to realize since Unturned uses Steamworks for networking and this would require some customization to it.

I think the features suggested here should be considered for Unturned 4 instead, as it looks like Unturned 3 only gets minor updates and fixes.

**Comment by JustOneMoreBlock** [comment]
We do this currently with Minecraft using "BungeeCord". Although all connected servers in Minecraft required to be in offline mode.

I suppose in Unturned something similar may need to be required to be disabled as the "proxy" would handle:
- Authentication
- MOTD
- Server Icons
- List of servers

**Comment by educatalan02** [comment]
I'm not saying like BungeeCord. I mean like FiveM or something like that. Waiting screen with customizable options.

**Comment by Trojaner** [comment]
You can not let the proxy server handle authentication as Steamworks is being used, which must handle the authentication instead.

**Comment by Johnanater** [comment]
So a loading screen, like on Garry's Mod and FiveM? That'd be pretty cool. It'd be nice to force users to read rules and other information. (Although loading into Unturned doesn't take nearly as long)

It'd probably be best not to let servers play audio though.

**Comment by SDGNelson** [comment]
This would be cool, however all of the game code assumes the map does not change during the server load (dumb old assumption). Closest in the current game would likely be sending an RPC redirecting the client back through the menu and into a new server, or something as part of the pre-server screen which wouldn't be as customizable. I think your best option for the moment is to include as much information in the server info screen which allows images, descriptions, etc. Most recently I've been working on some dogfooding mods for 4, and I'll keep that in mind for them actually - hub world between game modes.

**Comment by VOODOXD** [comment]
how do i create a lobby for my eaglercraft server
