### ISSUE TITLE
Something happened to the door/gate/glass slots

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#4661]
After the latest update (3.24.5.0), doors/gates/glass began to be placed crookedly in the openings of some mod buildings. Everything is fine in the Unity project. How to solve this problem?

![2024-08-18_11-10-43](https://github.com/user-attachments/assets/7f1fb1c4-e990-4d70-abfd-a17dd58732f1)
![image](https://github.com/user-attachments/assets/5d688848-e6e5-4aeb-b3dd-9880874dec3f)
![image](https://github.com/user-attachments/assets/b4773855-58f6-4d9e-bdaf-0808b42a48fa)

**Comment by MrGoBi** [comment]
![image](https://github.com/user-attachments/assets/a2533ce6-e17e-4fc9-ab7d-2b9078656c0a)

**Comment by SDGNelson** [comment]
Sorry about this! I think it must be the same as #4651. It seems like there might have been two ways of configuring the slot alignment with most of the vanilla content still working, but the other alignment causing this issue. I ought to get it sorted out in a patch this week.

**Comment by MrGoBi** [comment]
The windows and garage doors are now fine, but the problem continues with the doors.
![image](https://github.com/user-attachments/assets/df16d1b5-525e-4b33-99d0-de3be4048009)

**Comment by SDGNelson** [comment]
Glad to hear the windows and garage doors are fixed! In those cases the vanilla default was Z+ forward for slots, and some older code to also support Y+ forward (oof). I didn't see something similar for doors, however. Does your door slot have Y+ forward? Did you create it recently, or is it older and it used to work? (If it's older and it used to work I'm confused. 🤔 )

**Comment by SDGNelson** [comment]
Sorry about that! I'm genuinely confused and surprised that it worked before. 😕 

I can "add" support for Y+ forward in the next patch, but, unfortunately, in the meantime your best option would be to adjust any important doors to Z+ forward. Definitely not a convenient workaround, though. 😞
