### ISSUE TITLE
Discord links getting hidden from server links?

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4662]
Just randomly the button to join to the Discord server of my servers got hidden, however this is working for any other server after searching a bit. What happened? I've tried restarting tho

![image](https://github.com/user-attachments/assets/8fd28d01-b92e-4395-ae66-a3f6d3887167)
![image](https://github.com/user-attachments/assets/6c2dd413-08d4-44e7-846e-0178c5546942)

**Comment by SDGNelson** [comment]
The underlying reason is #4652, we might change the Discord link to go through the Steam link filter instead of hiding. :S
