### ISSUE TITLE
Material Palette Override issue

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4663]
If an object's material palette is overridden with a different one and then changed back to 0, the material won't change back to the original one until the map is re-entered in the editor.

https://github.com/user-attachments/assets/92bb6cbd-9dba-4648-be12-9ff4b2482a45

**Comment by SDGNelson** [comment]
Interesting point, thanks for the reports! Unfortunately, the game doesn't currently track the materials originally applied to the object's renderers, so there isn't a straightforward way to restore them if the material override is removed. Considering the straightforward workaround I think this is a "won't fix", sorry.
