### ISSUE TITLE
Incorrect screenshot shortcut key

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4668]
When I double-click the left mouse button in the Unturned game window, Steam displays a screenshot of the game window. The last time I pressed the '0' button on the keyboard, I took a screenshot of the window. I restored the default settings for the game buttons, but it didn't resolve the issue. There is no such problem in other games

**Comment by SDGNelson** [comment]
Do you have your Steam screenshot key bound to something non-default? The game handles the Steam screenshot request as well so that it can use the supersampling feature.

**Comment by SDGNelson** [comment]
Here's where the setting is:
![image](https://github.com/user-attachments/assets/c54d0a33-6c2f-44d3-814d-cd3e083de955)

**Comment by hyjhkt** [comment]
![`2RRE)ZSI56WF_N(XGSA AX](https://github.com/user-attachments/assets/8a991343-049a-4ff0-8791-b31462c5663b)
My screenshot settings shortcut key has always been 'F12', now whether it's' F12 'or double clicking with the mouse, you can take screenshots

**Comment by SDGNelson** [comment]
Do you have any macro-related software that might be affecting it? For example, software for your mouse or keyboard? (Many RGB keyboards and mice have these programs.) 

Is the in-game keybinding set to the default?
![image](https://github.com/user-attachments/assets/73e34a71-611a-4d34-a580-af6b07c0b7e5)

**Comment by hyjhkt** [comment]
![L~QRPWO0)O%`7ZZU3JPA`GN](https://github.com/user-attachments/assets/766ab5ef-ee41-4189-9a60-f5778bcbed2e)
I have been trying to restore the default button for a long time

**Comment by hyjhkt** [comment]
@SDGNelson Sorry, there's no need to solve it

**Comment by SDGNelson** [comment]
Glad to hear you found a solution! If you don't mind sharing, how did you fix it? It may come in useful for other players who run into something similar in the future.

**Comment by hyjhkt** [comment]
@SDGNelson I uninstalled Quark Browser

**Comment by SDGNelson** [comment]
Thanks for sharing how you fixed it! Odd that a browser would cause an issue like this.
