### ISSUE TITLE
Fertilizer wrongly shown on Barricades craft menu

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4669]
I guess it should be on the Utilities one since there are the seeds and more, also nor the rope or the fertilizer are something related with barricades

![2024-08-22_00-00-11](https://github.com/user-attachments/assets/3bb6c05a-11e5-491e-b7fa-426510090fea)

**Comment by SDGNelson** [comment]
Good point. Maybe it originally happened because the crops are "barricades"? I have mixed feelings whether we should change this or not since everyone's used to it. :x

**Comment by ItsRodrigoAl** [comment]
> Good point. Maybe it originally happened because the crops are "barricades"? I have mixed feelings whether we should change this or not since everyone's used to it. :x

Well, if you think about it, the Barricades tab include mostly barricades like for base building, defense and like these. However the Utilities one include some more decorative/survival barricades, like plants, furniture, etc, but all they are still barricades.

With that said, fertilizer shouldn't be included on the Utilities one since is not a barricade like the seeds, so what about moving it to the Supplies or Gear tabs?

**Comment by MoltonMontro** [comment]
Gear is mostly crafting materials and Supplies is medicine/food/drink stuff. I think Tools is most consistent right now (composed of weapons, traps, and other useables).

The 3 makeshift vehicles could probably be moved as well (e.g. to Tools or Utilities), and so could the explosive arrow & nailgun magazines (to Tools, with the other magazines).

**Comment by SDGNelson** [comment]
The distinction of all items is kind of arbitrary. Maybe it should just be automatic based on the item type. Since a crafting update was high priority I think it's more likely we'll remove those manually-assigned categories and add better filters as part of a new UI.
