### ISSUE TITLE
PEI Bug. Cave.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#467]
![image](https://user-images.githubusercontent.com/32962870/48904740-aed35c00-eea2-11e8-961a-deff564d855c.png)
![image](https://user-images.githubusercontent.com/32962870/48904787-dfb39100-eea2-11e8-8c79-617b1aed1508.png)

 Transparent cave texture.

**Comment by SDGNelson** [comment]
This dang cave... Now gone and removed the 1-sided cliffs from there.
