### ISSUE TITLE
Unturned HUGE problems with server

### ISSUE THREAD

**Issue by xdxdyesyes** [SmartlyDressedGames/Unturned-3.x-Community#4672]
hello i was just ready to play with my friend on our own dedicated server. im hosting it on the same machine i play unturned. i booted it joined and these things started happening...
https://www.youtube.com/watch?v=ueTZsBIzbHA
https://www.youtube.com/watch?v=QKiewOjQnF4
these videos shows my , and friend perspective of these unnatural events xd
its first time when i see things like this happen . i have this server for like 2 years played a lot of maps and yesterday it all just broke. i have 16 gb ram and intel core i5 4440 but its probably not the case. i also have like 7 mods installed. i dont know what to do :( its making the game unplayable without invicibility :(((((((
(edit) i searched discord, official forum, reddit and i couldn't find a fix for this or why is this happening i just dont know

**Comment by SDGNelson** [comment]
Sorry for the trouble! I'm surprised it's teleporting the vehicle so far backward. This server is hosted on the same PC that you're playing on? Yet it looks like your ping is 200 to 300 ms? If that's the case, it sounds like you might need to host the server on a different machine because it's really struggling.

**Comment by xdxdyesyes** [comment]
hey thanks for responding its really stange. because yes im hosting this server on the same pc but i think thats not the issue . i have router connected with cable to my pc so i have literally the best internet in the house . i will try to boot up the server today and see if its the same

**Comment by xdxdyesyes** [comment]
hey thanks for respodning . its really strange because even with that huge ping it was playable like i dont know how to describe it i have router connected with cable to pc ,

**Comment by SDGNelson** [comment]
For anyone who comes across this, I believe it was concluded in this forum post:
https://forum.smartlydressedgames.com/t/huge-problems-with-server-ping-unplayable/25020

OP uncovered it themselves after noticing the number of vehicles was 999,999! 😄
