### ISSUE TITLE
Hotkeying inventory problem?

### ISSUE THREAD

**Issue by analizin** [SmartlyDressedGames/Unturned-3.x-Community#4674]
Greetings! 
I have discovered a "feature" related to hotkeying items in your inventory, and I'm not sure whether it is intentional or not. If you hotkey something and make the mistake of clicking the key you hotkeyed while your inventory is open (without having selected another item), you will lose the hotkey to that item. This is really annoying if, for example, you hotkey something like a dressing on the "3" key, and you unknowingly click "3" on your keyboard while your inventory is open, and next time you intend to click "3" to get a dressing after getting bit by a zombie or after a heated firefight, the dressing will not want to equip itself, and you'll realise the dressing is not even in your hotbar. I've tested this, and it seems to only happen when you have your inventory screen open (doesn't happen when you are on the skills, crafting or information screen).
I'm opening this ticket to get confirmation on whether or not this is intentional. If not, I hope it gets fixed. If it was intentional, I hope it gets reconsidered, because it can really mess with your gameplay in its current state.

Thanks for reading,
analizin

**Comment by analizin** [comment]
If it is an issue and it gets fixed, I suggest if you want to unequip an item from a hotkey, without putting another one in, I recommend making it so that you have to first right-click on the item in question you want to unequip from your hotkey and click the already assigned hotkey to remove it from its designated spot.

**Comment by SDGNelson** [comment]
Yes: This is intentional. I believe it's worked this way since it was first introduced. I'd imagine accidentally pressing the number keys in the inventory is relatively uncommon. We could adjust if it's a popular request, but I don't recall it coming up before, sorry.

**Comment by analizin** [comment]
Fair enough, thanks for the confirmation!
