### ISSUE TITLE
Barricade generated Vehicle teammates cannot drive

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#4676]
I think it is because the vehicle does not record the owner's team id.

**Comment by GazziFX** [comment]
Unlock and lock again doesn't help?

**Comment by prank0079** [comment]
New players won't handle it.
And on servers with team-to-team plugins, not many people answer questions.

**Comment by SDGNelson** [comment]
Currently it spawns unlocked only for the person who placed it. The assumption IIRC is that we don't want someone else to immediately steal it. What's your use case? The server has two teams?

**Comment by prank0079** [comment]
I used it to place some immovable vehicles and use its turret weapons, but many new players used it immediately after placing it, and other players could not use it again after the new player died.

**Comment by SDGNelson** [comment]
I'll change this to allow group members into placed vehicles for the next patch - no reason not to comes to mind.

**Comment by prank0079** [comment]
Thanks！！
