### ISSUE TITLE
Blueprint type Ammo and Repair issue

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4677]
Making a crafting blueprint, composed of only one supply, or having outputs/products different than the item in which's asset file the blueprint is written in Ammo or Repair tab causes them to not appear in the crafting menu.

Obviously it comes from the fact that these tabs are intended for ammo refill or item repair type crafts, and they're not specified in any way other than being put in this tab, but it would be nice if at least if the game can't compose a working refill/repair craft out of listed supplies/outputs, it would still show them in this tab, and let these crafts work as usual type.

**Comment by SDGNelson** [comment]
I agree the way it works now isn't great. Closing for the meantime, however, as this is along the same lines as #4669 - that it'd make sense to do as part of a crafting update.
