### ISSUE TITLE
k_EResultFail when uploading WS items

### ISSUE THREAD

**Issue by padre-pete** [SmartlyDressedGames/Unturned-3.x-Community#4679]
k_EResultFail when uploading maps.

Game reinstalled,
Config.json Linted
Map directory changed
Game files verified
PC Restarted
Steam Restarted (via task manager)
Game Restarted plenty of times

**Comment by padre-pete** [comment]
when clicking ingame, it does not load. gives me the "-101" error code (unable to connect to server)
could you provide the link to where i can check the steam one?
- Pete

**Comment by MoltonMontro** [comment]
https://steamcommunity.com/workshop/workshoplegalagreement/
