### ISSUE TITLE
Server libmonobdwgc-2.0.so crash

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4681]
I've been getting this crash constantly, multiple times a day and it all started since the last major update. As far as I know, some other servers that I know the owners of have been having similar crashes.

I emailed you about this in case you need the coredump or any log files.

Here's the log:
```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x7f44765151f2 - /home/asineth/u3ds/Unturned_Headless_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so :
        0x7f44764bdecd - /home/asineth/u3ds/Unturned_Headless_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so :
        0x7f4476443210 - /home/asineth/u3ds/Unturned_Headless_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so :
        0x7f447db7c050 - /lib/x86_64-linux-gnu/libc.so.6 :
        0x7f441296e71e - ./linux64/steamclient.so :
        0x7f441292b5c8 - ./linux64/steamclient.so :
        0x7f4412970bc3 - ./linux64/steamclient.so :
        0x7f4412963f53 - ./linux64/steamclient.so :
        0x7f4412964b35 - ./linux64/steamclient.so :
        0x7f441296cbfd - ./linux64/steamclient.so :
        0x7f441296cffc - ./linux64/steamclient.so :
        0x7f4412943dce - ./linux64/steamclient.so :
        0x7f44129a2912 - ./linux64/steamclient.so :
        0x7f44129a33e4 - ./linux64/steamclient.so :
        0x7f44129a3a4b - ./linux64/steamclient.so :
        0x7f44132c6010 - ./linux64/steamclient.so :
        0x7f447dbc9134 - /lib/x86_64-linux-gnu/libc.so.6 :
        0x7f447dc497dc - /lib/x86_64-linux-gnu/libc.so.6 :

=================================================================
        Telemetry Dumper:
=================================================================
Thread 0x7f4410e006c0 may have been prematurely finalized* Assertion at mono-threads.c:702, condition `info' not met, function:mono_thread_info_current,
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
./ServerHelper.sh: line 18: 1767629 Aborted                 ./Unturned_Headless.x86_64 -batchmode -nographics "$@"
```

Any ideas here?

**Comment by asineth0** [comment]
I also tried switching to different physical hardware and running both in and outside of Docker just to make sure. I tried on a E3-1270 v6 and a Ryzen 5600G and both have the same issue, so it's not a system stability issue as far as I can tell. Both are on Debian 12.

**Comment by tonislcs** [comment]
Been having this since the unity version update too I asked nelson about it he said it's most likely because of that

**Comment by asineth0** [comment]
> Been having this since the unity version update too I asked nelson about it he said it's most likely because of that

As far as I know, Unturned has been on Unity 2021.3.29f1 for some time now, at least according to the log and UnityPlayer.dll file version. For me at least, it started happening after 3.24.5.0 (the vehicle improvements and online safety update).

**Comment by tonislcs** [comment]
> > Been having this since the unity version update too I asked nelson about it he said it's most likely because of that
> 
> As far as I know, Unturned has been on Unity 2021.3.29f1 for some time now, at least according to the log and UnityPlayer.dll file version. For me at least, it started happening after 3.24.5.0 (the vehicle improvements and online safety update).

Yeah not sure this has been happening to us for months hopefully nelson can figure it out I think it also dumps a core memory file in Rocket folder

**Comment by asineth0** [comment]
By sheer chance I managed to get the crash while debugging in VS2022, maybe this helps? @SDGNelson

![image](https://github.com/user-attachments/assets/669910b6-b4b9-49aa-b5ed-a11a887537f9)

**Comment by SDGNelson** [comment]
Unfortunately, I'm unfamiliar with how to find any useful details from these Linux crash reports. 😞 
The stack trace appears to only be in Steam and Mono, not game code. It might not be something within our control? 😕 If anyone with more low-level knowledge has any ideas I'd greatly appreciate your input!

**Comment by Jdance-Media** [comment]
Hi, I see you got yourself what appears to be a segmentation fault. My best guess is that a plugin is causing it. Remove each plugin and test until you find the culprit, then report the issue to the plugin developer. In my case this was MoreHomes.

**Comment by sunnamed434** [comment]
Jdance might be right. Btw, maybe you guys who have this crash can share plugin names, maybe one of them is the problem just in case

**Comment by asineth0** [comment]
> Hi, I see you got yourself what appears to be a segmentation fault (I think?). My best guess is that a plugin is causing it. Remove each plugin and test until you find the culprit, then report the issue to the plugin developer. In my case this was MoreHomes.

Ever since I dropped ImperialPlugins and removed their loader, I haven't had a single crash.

**Comment by Trojaner** [comment]
> > Hi, I see you got yourself what appears to be a segmentation fault (I think?). My best guess is that a plugin is causing it. Remove each plugin and test until you find the culprit, then report the issue to the plugin developer. In my case this was MoreHomes.
> 
> Ever since I dropped ImperialPlugins and removed their loader, I haven't had a single crash.

*Ever since all your license keys were banned because of your EULA violation. You didn't need  it anymore.

**Comment by tonislcs** [comment]
😂😂  It does not happen cause of Imperial plugins I get it without it pretty sure it's to do with rocketmod since it drops a memory dump in there

**Comment by asineth0** [comment]
> 😂😂 It does not happen cause of Imperial plugins I get it without it pretty sure it's to do with rocketmod since it drops a memory dump in there

All I'm saying is that ever since I removed their crappy low-quality plugins I have not had a single crash.

**Comment by mycpphurts** [comment]
> Unfortunately, I'm unfamiliar with how to find any useful details from these Linux crash reports. 😞 The stack trace appears to only be in Steam and Mono, not game code. It might not be something within our control? 😕 If anyone with more low-level knowledge has any ideas I'd greatly appreciate your input!

This is a segfault, no doubt. Reading the crash log, from what I can understand (and please correct me if I am wrong), it was caused from an interaction between the Mono runtime and steamclient.so

I believe it's a concurrency issue since a resource deadlock was avoided as shown in

```log
Thread 0x7f4410e006c0 may have been prematurely finalized* Assertion at mono-threads.c:702, condition `info' not met, function:mono_thread_info_current, terminate called after throwing an instance of 'std::system_error'
```

I don't believe it's caused by any of Unturned Server's dependencies since I did run some tests. However, I'd keep an eye out and check the Libraries and such in case I am wrong, @SDGNelson.

> > > Hi, I see you got yourself what appears to be a segmentation fault (I think?). My best guess is that a plugin is causing it. Remove each plugin and test until you find the culprit, then report the issue to the plugin developer. In my case this was MoreHomes.
> > 
> > 
> > Ever since I dropped ImperialPlugins and removed their loader, I haven't had a single crash.
> 
> *Ever since all your license keys were banned because of your EULA violation. You didn't need the loader anymore.

I ran some tests with your loader, @Trojaner, and ran into the same issues Asineth was facing, which kinda tells me it's one of your service's plugins, or your loader that is causing this issue.
