### ISSUE TITLE
Feature Request: In-Transit Vehicle Management

### ISSUE THREAD

**Issue by cgnranger** [SmartlyDressedGames/Unturned-3.x-Community#4682]
I would like to suggest a feature for the current vehicle updates: the ability to move around vehicles, such as ships, while they are in motion.

**Comment by SDGNelson** [comment]
This is an improvement I would like to make. Specifically, it would happen as part of future input improvement updates. Closing, however, because the issue tracker isn't intended for feature requests, sorry.
