### ISSUE TITLE
Config condition Only_Critical_Stuns not working properly

### ISSUE THREAD

**Issue by kulkaGM** [SmartlyDressedGames/Unturned-3.x-Community#4684]
Config condition `Only_Critical_Stuns` does not seem to apply.
While this option is set to `true` zombies should get stunned only on critical hit (headshot for example), but they are not getting stunned nor with headshot nor with any hit.

Steps to reproduce:
set `Can_Stun` to `true`
set `Only_Critical_Stuns` to `true`
Max your skills, and try.

**Comment by MoltonMontro** [comment]
Ah, the wiki had incorrect information about what Only_Critical_Stuns does. It's fixed here: https://unturned.wiki.gg/wiki/Gameplay_config#Zombies

A "critical stun" isn't necessarily a headshot. Rather, only backstabbing and melee power attacks can stun zombies.

**Comment by kulkaGM** [comment]
Makes sense, I only tested with guns and punching
