### ISSUE TITLE
Any option to disable water like terrain?

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#4685]
Im trying to make an underwater subway tunnel, do we have any option to remove water in squares?

If not i could try to lower sea levels and put water on all the map via volumes, and leave certain parts without water in the undergound of the sea but the map its insane size and 70% water so i dont know if its safe to try, any lag or crash to manually added volumes across a very big map?

![Captura de pantalla 2024-08-31 164038](https://github.com/user-attachments/assets/6f13c956-036d-4c7e-abfe-f325a6aabba8)

**Comment by Jdance-Media** [comment]
There is no volume for that, sorry.

**Comment by MoltonMontro** [comment]
> If not i could try to lower sea levels and put water on all the map via volumes, and leave certain parts without water in the undergound of the sea but the map its insane size and 70% water so i dont know if its safe to try, any lag or crash to manually added volumes across a very big map?

I wouldn't expect this to cause issues. But rather than "lower sea levels", you should just disable legacy water. https://docs.smartlydressedgames.com/en/stable/mapping/level-config.html

**Comment by SDGNelson** [comment]
Thanks Jdance and Molt! Unfortunately, yes, water is purely additive as-is. Constructive solid geometry (CSG) water would be really cool for sure!
