### ISSUE TITLE
Turret as barricades 

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#469]
I did not watch the system code of the tower.
But I think you can add turret to the barricades as a machine gun. (Always lacked.)
In mods, they are made like cars, but this is not beautiful, the tower will fall like a car, and it does not have fuel, and two places (driver and gunner)

**Comment by VitaxaRusModding** [comment]
And, please add the script OpenURL.cs
with open URL method.
Useful for Effect UI.

**Comment by aviadmini** [comment]
"system code of the tower" lol
"OpenURL.cs" LOL and facepalm - create separate issue for a completely different topic

I believe what you want is a manned stationary fortification = barricade that has turret slots (e.g. [this](https://www.flamesofwar.com/Portals/0/all_images/Historical/BloodyOmaha/Normandy-Fortifications-03.jpg)) 

The thing is that it would require too much of code changes for Unturned 3. So I guess it's a *no*

**Comment by VitaxaRusModding** [comment]
@aviadmini  I find it difficult to convey thoughts in another language. But you do not understand this and pretend that you are the smartest here. I understand that a lot of code changes. I wrote that I did not see how the tower works, and I did not think whether it could be done or not. I just suggested.
And I do not think that such a small discussion as OpenURL.cs is worthy of a new  issue.

**Comment by SDGNelson** [comment]
Unfortunately yes that would be a lot of code changes, and right now I'm not planning to make big gameplay feature changes to 3 (gameplay development time is going toward the 4 beta).

Currently the intended way to open urls would be to handle the button click request serverside by calling the player request open url rpc, which shows the player which url they would be opening. Does this work for you?
