### ISSUE TITLE
FOV won't change when on Spectator mode

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4691]
I used to take pictures entering on spectator mode and lowering the FOV so you can get better pictures overall, but now it wont work, it just changes when you get back to first person

not related picture, I just liked so much kuwait i wanted to leave a picture here c:
![image](https://github.com/user-attachments/assets/28a9324d-d3ae-49fe-b881-94a09aae2514)

**Comment by Jdance-Media** [comment]
To be fair, I believe you can dynamically change the field-of-view using the scroll wheel now while in spectator mode.

**Comment by ItsRodrigoAl** [comment]
> To be fair, I believe you can dynamically change the field-of-view using the scroll wheel now while in spectator mode.

Remember that, when you're on spectator mode and you do scroll wheel, you just change the speed of the camera view

**Comment by ItsRodrigoAl** [comment]
> To be fair, I believe you can dynamically change the field-of-view using the scroll wheel now while in spectator mode.

Actually, you were right, you can CTRL + scroll wheel to change the FOV, thanks you
