### ISSUE TITLE
Carepackage causes troubles if barricade spawned isn't storage

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4693]
I've been experimenting with the Carepackage script, which references the code used by vanilla airdrops, and it seems that if the barricade spawned by such script isn't storage, several issues occur: there is no carepackage drop effect (red smoke, wood particles and sound) and the physical carepackage prefab doesn't get destroyed.
Since this happens with the carepackage script, it will also most likely happen to a vanilla type airdrop if barricade spawned isn't of storage type.

**Comment by Jdance-Media** [comment]
Well, the code is likely expecting the InteractableStorage and ItemStorageAsset types. I'm not sure what use you have for airdropping other barricade types, but it might be more difficult to implement than you think.

If what I am saying is correct, this post would be more fitting as a discussion, as it probably isn't a bug that you cannot use other barricade types. However, maybe a check in place would be nice to prevent any unnecessary exceptions in console or logs.

**Comment by SDGNelson** [comment]
Thanks @Jdance-Media! Yes, currently this is only designed for use with storage.
