### ISSUE TITLE
Bad UV mapping on vanilla Shirt item model

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4694]
Now I'm not sure if this bug wasn't fixed earlier, since I'm judging it based on shirts I made myself, using the vanilla shirt model from example files, but it seems that the top faces of sleeves are inverted. Its hard to notice with vanilla clothing, since its mostly symmetrical, but if one makes a shirt with an armband/special cuff on one of the sleeves, it will appear inverted, while the inner faces appear to be mapped correctly
![изображение](https://github.com/user-attachments/assets/e510914d-a4db-48a1-81fd-bf2c20fb6a48)
The armband is supposed to be on the left sleeve, indicating that the front faces of sleeves are indeed inverted and need to be swapped.
![изображение](https://github.com/user-attachments/assets/2885caf8-21d8-483d-9ccd-970c320658d9)
The back and side faces seem to be fine, although the inner and outer side faces of sleeves have different texture length compared to back and front faces, but I guess we all got used to it already.
![изображение](https://github.com/user-attachments/assets/05a81fc5-0038-4e1c-b744-af3f3e49766d)

**Comment by SDGNelson** [comment]
Sorry for my delay on this! The shirt item model is... not exactly a great representation of how it'll look on the character, to say the least. I've now flipped those arm fronts for the next update, however, and updated the copy in example assets, too.
