### ISSUE TITLE
Animals emit effects with "rocket scripts" that cannot trigger the explosion of rocket scripts

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4697]
![EE50PZP~68IQC {DT83KZUA](https://github.com/user-attachments/assets/39a26cca-3892-4c90-a0f0-42aaa13e6631)
![~8ITR95N@4DVYTPYOKFZ5AM](https://github.com/user-attachments/assets/d2737763-ab59-4a89-ac60-350170d35e95)
![6RPG68}(KR M5)JSO0YYW0C](https://github.com/user-attachments/assets/c6fccc22-2ece-4c1d-bd31-ec87d7a6fbde)
![MG QWS%PIHCO @BB_M`HK V](https://github.com/user-attachments/assets/f104b06e-8917-4772-a9c1-c48b75a2b649)

**Comment by hyjhkt** [comment]
When the summoned effect touches other objects, it disappears directly without exploding

**Comment by Alexondeer** [comment]
1. For correct work on the server, you need to enable "Authority Only".
2. Check the specified "ID" and "GUID".
3. Why do you need to use "Grenade Scrip"? "Rocket Script" is quite enough for your purpose.
4. Also, most likely, you can face the problem of spawning effects from the pool. When you have an effect with destructible components, you expect that it will be new every time. But in fact, the game does not spawn a new effect, but simply disables the existing one. Accordingly, when you call it again, the effect will already be "used".

**Comment by SDGNelson** [comment]
Sorry for my delay and thank you for your patience! (I was away the 3rd through the 10th)

Thanks for helping them @Alexondeer!
