### ISSUE TITLE
How can guns cause treatment?

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4698]
If I want my firearm to heal other players after hitting them, do I need to change the damage to negative or add a reward?

**Comment by ItsRodrigoAl** [comment]
Please use the Discussions tab instead, since this is for bugs, not questions for features

**Comment by SDGNelson** [comment]
Sorry for my delay and thank you for your patience! (I was away the 3rd through the 10th)

Thanks @ItsRodrigoAl. Weapons can heal broken bones and bleeding, but not heal HP currently.
