### ISSUE TITLE
Blood decals are being parented to the wheels of vehicles.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4699]
Because of this, the blood decals seemingly move when going offroading.

**Comment by BUTTER-FlNGERS** [comment]
https://github.com/user-attachments/assets/4e085602-74cf-4bb3-8cb4-5bb96bc063a4
Video of decals moving

**Comment by BUTTER-FlNGERS** [comment]
https://youtu.be/P8QSTQXih4Y
better quality youtube

**Comment by SDGNelson** [comment]
Thanks for the report and the video. Hmm... I'm not sure whether we should change this or not. If it were attached to a larger moving part of the vehicle, for example, then it would look strange if it didn't move.

That said, I'm surprised it's attaching to the wheel. The wheel colliders aren't in a layer hit by blood splatters, and the vanilla vehicle wheel models don't have collision enabled until they detach from the vehicle. Do your wheel models have enabled colliders?

**Comment by SDGNelson** [comment]
Closing for the meantime but feel free to comment and I'll re-open.

**Comment by Jdance-Media** [comment]
The blood decals on the vehicle body would probably be good enough for the most part in terms of visuals (in Corbyn's words, this is a "lego block game"). The blood spatter issue with the wheels is probably more noticeable and annoying compared to just not having blood parented to the wheels.

I'll have to go check if it happens with vanilla vehicles, and if it doesn't, I'll add enabled colliders to the wheel models and see if that changes things.
