### ISSUE TITLE
Refusing Connections ( sv channel receive failed)

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#470]
Hello, Nelson here is the full log with the error printed.
I hope you fix it, my players only tell me about kicking at inesperate moment.

Here is my log with the errors.

```
RPC askAirdropState from 76561198802804203 has already been called once on channel 0, so we're refusing them

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

General: Refusing connections from 76561198802804203 (sv channel receive failed)
Refusing connections from 76561198802804203 (sv channel receive failed)
```

[WashingtonX5_Ru-aMGaming.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2611691/WashingtonX5_Ru-aMGaming.log)

**Comment by SDGNelson** [comment]
Following up to see if you have run into this after the Friday update? Should have been one of the resolved issues.

**Comment by educatalan02** [comment]
This has happened when trying to close the server to update to the new version Friday.

**Comment by SDGNelson** [comment]
It happened prior to closing the server on Friday, but not after the update?

**Comment by educatalan02** [comment]
Yeah, It happenned before the update.

**Comment by SDGNelson** [comment]
In that case presumably it's been resolved then!
