### ISSUE TITLE
Crash when playing with BattlEye

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#4701]
Recently, some people have reported that their game has been randomly crashing when playing on Multiplayer. I looked into this and after a lot of testing we narrowed it down to an issue with BattlEye (Comparing if they would crash on a server not using BattlEye which they didn't). From my understanding BattlEye only starts after a few minutes into the Multiplayer session which lines up with how long they could last on the Server before crashing.

**Ideas that didn't work:**
Verifying the Integrity of the Game files
Updating Drivers
Updating Windows

Attached Crashes .dmp and Player.log files from someone affected:
[Crashes.zip](https://github.com/user-attachments/files/16923709/Crashes.zip)

Update:
DiFFoZ was kind enough to analyze the crash files and discovered that the crashes were due to problems with Rendering. It is possible that all affected are getting kicked by BattlEye for some *maybe valid* reason which somehow breaks the rendering. Strange thing is that kicking works normally and doesn't crash the game when BattlEye isn't enabled.

Update:
One of the people affected actually managed to fix it for them by removing some possibly faulty RAM sticks. Not really sure what this means and if it will work for the other people affected.

**Comment by Macboys** [comment]
Hey Nelson, big fan! Just letting you know that I too (and a lot of others) have been struggling with this issue for a bit. Tried everything from cache verification and resetting my PC entirely. No luck there. I just tried your suggestion. Unfortunately, it didn't work out either. Please resolve this critical issue. Thank you again for your work.

**Comment by Gamingtoday093** [comment]
Yup that fixed it as well! Still seems like the root cause is faulty RAM sticks. Interesting that its only affecting the game when playing with BattlEye, who knows why thatd be the case. Anyways, thanks so much for your help! Everyone affected is super grateful

**Comment by GazziFX** [comment]
Also if you out of ram instead of game crash battleye driver cause BSOD
