### ISSUE TITLE
Can't move on linux

### ISSUE THREAD

**Issue by ymo-4** [SmartlyDressedGames/Unturned-3.x-Community#4702]
Sometimes there is a bug that after joining the server you can't move with a keyboard, even hotkeys don't work. Only jump, chat (only by pressing Enter) and admin (Shift + F) hotkeys work. Neither rejoining nor restarting the game helps. It's probably a problem with multiple keyboard layouts. The workaround is to disable or remove layouts (2 on the screen). But sometimes you can just change the switching policy (1 on the screen. Since gnome doesn't have such a setting, I always had to remove all layouts and add them back after playing). Nothing about that in Client.log.

![image](https://github.com/user-attachments/assets/ef6c82bd-0762-4ed7-bf27-1de942e89634)

Tested on: fedora gnome, kubuntu, nixos with kde.

**Comment by SDGNelson** [comment]
It sounds like you tested quite extensively! Unfortunately, this may be outside our control and unlikely to be fixed soon - maybe when/if updating the game to Unity's newer input system (currently legacy input system). I'm glad you found a sort of workaround for the meantime though. On a complete tangent, interestingly (IMO) Godot's input system uses "physical" key binds by default so they work out of the box with non-English keyboard layouts. 🙂 

Sorry for my delay and thank you for your patience! (I was away the 3rd through the 10th)
