### ISSUE TITLE
Reload on Workshop error logs doesn't reload the errors

### ISSUE THREAD

**Issue by JustcallmeALLAN** [SmartlyDressedGames/Unturned-3.x-Community#4703]
Hello,

On the main menu, the workshop tab then error logs, the reload button on the bottom right of the screen doesn't actually reload the errors when they are fixed. A temporary work-around is to restart the game which takes much longer than reloading the error messages.

**Comment by SDGNelson** [comment]
It's perhaps not implemented in the most intuitive way. That button refreshes the list of errors, but not the assets themselves. If you press the reload assets key (default Page Up) the errors list is modified, then clicking this refresh button will update the display.
