### ISSUE TITLE
Alert Radius doesn't work correctly.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#4705]
Set the alert radius of a gun to 400 meters, distant zombies just do a 360 when alerted and disengage immediately

https://github.com/user-attachments/assets/1e19f3f8-82aa-4bcf-b476-c69fdeaba926

**Comment by SDGNelson** [comment]
The game should probably handle this case better, but at the moment zombies will stop following their target if the horizontal distance between them is more than 64 m, sorry.
