### ISSUE TITLE
Skipping TerrainColour error log does not specify which entry

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4707]
![image](https://github.com/user-attachments/assets/80b970cc-0554-4bc9-85e7-0d623973d12e)
I have around 5 different entries, and figuring out which one is triggering the error log (or even which file the entry is in) is not currently possible without reloading the game multiple times.

**Comment by SDGNelson** [comment]
Whoops! It should've included the asset, will fix, thanks for the report.
