### ISSUE TITLE
Unturned keeps installing mods that I am not subscribed to.

### ISSUE THREAD

**Issue by average0belgian** [SmartlyDressedGames/Unturned-3.x-Community#4708]
I don't have a free sitting 50 GBs for mods I'm not using...

**Comment by GazziFX** [comment]
Quit from steam and clear workshop folder with manifests

**Comment by average0belgian** [comment]
I can remember Steam not doing this years ago. Either Nelson did a woopsie or Steam updated... (I'm not experiencing this with other games though...)

**Comment by Jdance-Media** [comment]
Try removing the .xcf for Unturned's app id.

**Comment by SDGNelson** [comment]
Here's our support article about this: [Why is Steam installing workshop files I'm not subscribed to?](https://support.smartlydressedgames.com/hc/en-us/articles/16184460051988-Why-is-Steam-installing-workshop-files-I-m-not-subscribed-to)

Although the article suggests against deleting the folders manually, technically yes if you delete `appworkshop_304930.acf` as well then Steam doesn't _*currently*_ know to re-install them. Relatively recently the Steam team added a new Workshop tab to the game's Properties panel, so hopefully they might add buttons to fully delete workshop files officially someday.
