### ISSUE TITLE
Animation Cancel on Burst Weapons

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4712]
Sprinting can cancel burst with all burst weapons. Can be recreated with eaglefire, but easier on guns that have more of a shooting delay.

**Comment by SDGNelson** [comment]
Is your suggestion to prevent sprinting until all of the burst shots are fired?

**Comment by Spebby** [comment]
That would probably be the easiest and would be inline with past animation cancel fixes.

**Comment by SDGNelson** [comment]
Looked into this a bit, but I'm hesitant to mess with it, sorry. Nowadays I'd probably implement the gun states as a state machine, whereas the current spaghetti checks a variety of flags for aiming, swimming, whether it can shoot while sprinting, etc. In this case it'd be easy to break something unintentionally, not to mention some guns (e.g., the 30+ round burst gun on Escalation?) may be balanced with canceling by sprinting in mind.

**Comment by Spebby** [comment]
That's fair enough. Thanks for taking a look :)
