### ISSUE TITLE
The rendering pipeline of the game

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4717]
Is the default rendering pipeline used for the game?, Alternatively, it could be using 'urp'

**Comment by GazziFX** [comment]
Unturned using built-in rendering pipeline, it would require a lot of work to migrate to URP and broke all mods

**Comment by GazziFX** [comment]
Unity recently uploaded video about future Unified RP which should solve a lot of pain of work with BRP, URP, HDRP https://youtu.be/pq3QokizOTQ

**Comment by SDGNelson** [comment]
As GazziFX mentions, Unity has announced they are going to replace the render pipeline split with a single unified render pipeline in the future, so in the long term URP might be obsolete anyway. We can keep our fingers crossed 🤞 that hopefully they'll support a migration path from the built-in render pipeline to whatever they replace it with.
