### ISSUE TITLE
Integer overflow on Spawntables with single tier

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4720]
When a spawntable has a single tier, players can still try changing the spawn table weight. This results in a value of -2,147,483,648% which takes the slider off-screen if the player interacts with a different menu. Creating new tiers just results in these overflowing as well.

https://forum.smartlydressedgames.com/t/editor-slider-is-disappearing-for-me/25102

**Comment by SDGNelson** [comment]
Thanks for cross-posting here! This should be an easy fix.
