### ISSUE TITLE
Unexpected behavior with String type gun + Magazine with capacity above 1

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4723]
I made a gun with Action type String, Auto firing mode and a 100 round magazine, yet when it fires, it destroys the magazine item after each shot, making having magazines with capacity above one impossible.

The reason I resorted to trying out this action type (which obviously wasn't intended to handle magazines, to say the least) for my gun is that I need it to only fire in aiming mode, but also snap the Player's camera to the Sight, as it does with all other gun types, while Minigun action type ignores Sight and View prefabs. Please, either allow String type guns to use magazines, or add an option to have normal aiming for minigun type guns.

**Comment by MoltonMontro** [comment]
To clarify - what are you trying to do? Only allow shooting while ADS? Force the player to re-aim after every shot?

**Comment by DerpyHoowes** [comment]
Yes, just a usual gun which can only be fired when ADS. This could be achieved by using Minigun action type, but it changes the way player aims the gun: Instead of snapping the camera to Sight/View prefab, it doesnt do anything, and player's camera stays in the same position, while I need to have iron sights on my gun. Thought I could achieve that by using String type action, and then encountered this bug.
Please either make some tag that adds ADS-only-fire restriction to other action type guns (Trigger, Pump, Bolt, etc) or at least fix this bug with String type action so we can have guns with both ADS enforcement AND proper iron sights.

**Comment by SDGNelson** [comment]
The `Action` property does leave a lot to be desired. If recreating from scratch *now* it would definitely be a variety of properties rather than lumped in like that. Closing for the meantime because I think this is more-so a feature request than a bug. Sorry to say I don't know when/if it'll be fully separated out.
