### ISSUE TITLE
FOV in spectator cam does not change

### ISSUE THREAD

**Issue by WitnessProt** [SmartlyDressedGames/Unturned-3.x-Community#4725]
For some reason the FOV of the spectator cam does not change along with the player cam if you adjust the slider in the settings.

**Comment by ItsRodrigoAl** [comment]
I reported this previously, now you need to CTRL + scroll to change the Fov. Would be good to show like a hint or something this has been made tho

**Comment by SDGNelson** [comment]
Thanks ItsRodrigoAl! Yes, the freecam FOV is set to your preferred FOV when first using it, but after that it uses its own separately controlled FOV.
