### ISSUE TITLE
Cannot use 'post process volume' component

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4726]
![}GF$M72F5GJ6QB1D5`ZP_QD](https://github.com/user-attachments/assets/76186d10-5a90-4a1c-8f48-ef14d57bbb3b)
![@FYQ6FOGNY608}T1V5S_ FF](https://github.com/user-attachments/assets/f12046a5-9d4c-485f-8dff-454a3c492e87)
![NZC`JQZR7ZCLI@)3C33SHVR](https://github.com/user-attachments/assets/b62604d8-6f8b-4b78-bc55-49e310f407b0)
![NPN@(TIZFZPQR6N MTF%O93](https://github.com/user-attachments/assets/bb5f9644-22da-4b5e-980c-cdf99d0313e5)
![QTOL5 FGBZ)5T$I}SL(A2 T](https://github.com/user-attachments/assets/1b6db8bd-1166-4592-b4fb-f78309b7aa5a)
![W TCER_(6GNU`1VGU9A$@RS](https://github.com/user-attachments/assets/7b3b2cc7-4201-4179-81d3-d42e345327a6)

**Comment by SDGNelson** [comment]
I'm not familiar with this feature of the post processing package, sorry. It might rely on the camera being in a specific Layer or having a collider component which the vanilla camera doesn't.
