### ISSUE TITLE
Regarding the sound disappearance vulnerability

### ISSUE THREAD

**Issue by roujiamo123456** [SmartlyDressedGames/Unturned-3.x-Community#4727]
I didn't hear the sound of doors opening or bonfires in the safe zone. I asked the server administrator if it was a map bug, and he told me, 'There are too many things around, and this can only be a game bug.'

https://github.com/user-attachments/assets/4760d746-3ddb-45db-af6f-160e9d3c1cea

**Comment by roujiamo123456** [comment]
> > 'There are too many things around, and this can only be a game bug.'
> 
> To clarify, are they/you saying that there's **a lot** of _noise-making things_ nearby? Only 64 sounds can be heard at the same time. So if you've placed down a lot of stuff that makes noise, then you're not going to be able to hear other stuff at all.
> 
> relevant support article: https://support.smartlydressedgames.com/hc/en-us/articles/12804404167188-Why-can-I-only-hear-gunshots

The location I am in the game belongs to a player building area, where there are over 100 items placed, which makes it impossible for me to hear any sound

**Comment by roujiamo123456** [comment]
https://github.com/user-attachments/assets/a922ca18-9985-4e09-b204-193bd8025f42

This is the second half of my video. There is no sound from the campfire, but there is a sound when picking up and putting down items

**Comment by SDGNelson** [comment]
Sorry to say the article Molt linked (thanks!) is likely the underlying cause. The audio engine likely prioritizes non-spatial sounds like item selection over 3D attenuated sounds.

**Comment by Jdance-Media** [comment]
> Sorry to say the article Molt linked (thanks!) is likely the underlying cause. The audio engine likely prioritizes non-spatial sounds like item selection over 3D attenuated sounds.

Maybe it would be worth adding toggles for inventory sounds and minor audio details like that.
