### ISSUE TITLE
More checks before passing in Vector3 into Quaternion.LookRotation

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4730]
Recently I was doing work on a server and noticed that the 'Look rotation viewing vector is zero' error was being spammed in the console. Making it impossible for us to actually view anything else in the console. I patched `Quaternion.LookRotation` to log the calling assembly, that logged the game assembly.

<img width="694" alt="image" src="https://github.com/user-attachments/assets/b83e8316-41ad-49b4-84c3-9c494121d7a0">

I also patched the EffectManager method that used LookRotation and checked if it had something being passed in as zero, but no.

My proposal is to have checks for most usages of Quaternion.LookRotation. Most important classes are `EffectManager` and `TriggerEffectParameters`, which are the most susceptible to the mistakes of plugin developers. In the case of the 'Set' methods in `TriggerEffectParameters`, ignore if it is Vector3.zero.

**Comment by Jdance-Media** [comment]
```
[2024-10-06 01:51:58] QueueTouch >>   at System.Environment.get_StackTrace () [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
  at QueueTouch.Main.LookRotation () [0x00000] in <5822bba20327474e9d58a2b243ff4f9b>:0 
  at UnityEngine.Quaternion.UnityEngine.Quaternion.LookRotation_Patch1 (UnityEngine.Vector3 ) [0x00000] in <8aebd7627ade4efeae84aca54d1d32ad>:0 
  at SDG.Unturned.Animal.move (System.Single delta) [0x00000] in <d3a5196764504621bdcbe304e20ebde8>:0 
  at SDG.Unturned.Animal.tick () [0x00000] in <d3a5196764504621bdcbe304e20ebde8>:0 
  at SDG.Unturned.AnimalManager.Update () [0x00000] in <d3a5196764504621bdcbe304e20ebde8>:0
  ```
  
  It was animals. This definitely needs a check I guess, not sure what caused it. We have a lot of animal spawns.

**Comment by Jdance-Media** [comment]
To follow up: I eventually figured out the issue, but it was a vanilla method that got around to executing LookRotation. So I'd still support checks. However, with that being said, since the problem that led to this request is resolved, I'll be closing this. 👍

**Comment by SDGNelson** [comment]
Clever patching to track down the calling code!

One issue I'm aware of in vanilla code is it can happen with trains spawned without a track. Was that the underlying issue here?

**Comment by Jdance-Media** [comment]
Yep, that was the underlying issue. There is a train system plugin to automatically drive the train. It relied on the vanilla code that called LookRotation. This isn't that common of an occurrence, so I'll go ahead and close this as I opened it after making no progress finding a solution.
