### ISSUE TITLE
Police clothing texture bug

### ISSUE THREAD

**Issue by FohnJallout** [SmartlyDressedGames/Unturned-3.x-Community#4733]
I'm not sure what happened but all of a sudden the police clothing texture seems to look very weird in the inventory, this issue can only be seen when the clothing is inside of your inventory. When put on there is no visible difference. I added a picture down below.
![Unturned triangle bug](https://github.com/user-attachments/assets/58fb9470-0dbf-414d-9990-4728a5d37d12)

**Comment by SDGNelson** [comment]
That is weird! Thanks for the report. After some testing I think it happens with Skybox Reflections on if the icon is captured while the skybox cubemap is still building. This would explain why it happens in a 90 degree direction like that - the skybox hasn't been updated there yet.
