### ISSUE TITLE
Servers showing 0 players in server list

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4735]
This has been happening often where the server list will display 0/80 players for example when a server has plenty of players in-game. It doesn't happen consistently or all the time, and it seems to come and go. But it's weird enough where I figured I'd open an issue.

Image of it affecting Horizon RP and Pandahut (two of the largest servers):
![image](https://github.com/user-attachments/assets/f3ad67e0-3812-4cde-84b9-92131b4576f3)

**Comment by SDGNelson** [comment]
It looks like both networks are using the Fake IP feature, and both dip down to zero players at the same time. Shortly thereafter the player count shows up as normal again. I'm afraid it's outside of our control - the game shows the player count reported by the Steam server list.
