### ISSUE TITLE
PEI Glitch base/ mili base rocks

### ISSUE THREAD

**Issue by thraxsh255** [SmartlyDressedGames/Unturned-3.x-Community#4738]
Hey Nelson, i'm a staff for an unturned network called Syntale, and i recently found a glitch base inside the rocks above the tunnel next to military base on pei, and after i banned the owners i was wondering how they built it so i can prevent people from doing it in the future. I was looking up unturned glitches on google when i found an interesting glitch using ramps to kind of glitch inside of things when running into a ramp. Ill be providing you a clip below to see what im talking about. Is there a fix for this?

https://github.com/user-attachments/assets/c51f9b0c-c24f-44e4-9016-c45014d12bf7

**Comment by MoltonMontro** [comment]
This doesn't look like an out-of-bounds glitch related to https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds, but rather an issue that should already fixed on our preview branch. https://support.smartlydressedgames.com/hc/en-us/articles/12462494977172-Preview-branch

We're aiming to release the current PTB onto the game's main branch this Thursday (Oct. 18th).

**Comment by thraxsh255** [comment]
> This doesn't look like an out-of-bounds glitch related to [Known issue: wiggling out of bounds](https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds), but rather an issue that should already fixed on our preview branch ([Fixed issue: reverted "skin width" portion of floor snapping changes due to all the side effects.](https://support.smartlydressedgames.com/hc/en-us/articles/12462494977172-Preview-branch)).
> 
> We're aiming to release the current PTB onto the game's main branch this Thursday (Oct. 18th).

Alright good. Also one more question regarding the new upcoming update, why was the skybox ambience removed? It made the game look so much better.

**Comment by GazziFX** [comment]
> why was the skybox ambience removed?

Probably one of the reasons, but still dont know why it isnt map/server configurable
https://forum.smartlydressedgames.com/t/use-skybox-ambience-unfair-advantage/23513

**Comment by SDGNelson** [comment]
Good point - Since the update adds a bunch of death barriers to the bunker I'll do the same here for the update.

**Comment by thraxsh255** [comment]
> Good point - Since the update adds a bunch of death barriers to the bunker I'll do the same here for the update.

Thanks, although the thing is people will always find a way of doing it.
