### ISSUE TITLE
2017.4 LTS Update News

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#474]
https://steamcommunity.com/app/304930/discussions/0/1741101364289143798/

Posting here because I know there's interest in the newer C#/.NET compatibility. If you update comment here with issues!

**Comment by NeedlessMemeing** [comment]
![screen shot 2018-12-01 at 10 44 11 am](https://user-images.githubusercontent.com/37240761/49320631-cd96ba00-f556-11e8-8668-34bd3e433181.png)
On Mac, the road object and some of the rocks have a solid black texture. Trees also got bad.

**Comment by SDGNelson** [comment]
Thanks, I'll load it up on the ol' macbook air. Off the top of my head I don't think the rocks and roads have anything in common, bizarre. Looks like the HUD gamma is wrong, too.

**Comment by aviadmini** [comment]
Just tried on MBA. Can confirm the issues: trees & bushes meshed are messed up, resources are pure black and probably more of those I missed.

Nothing weird in logs except new type of message spam:
`Could not terminate pathfinding thread[7] in 50ms, trying Thread.Abort`

**Comment by baranmod** [comment]
Might be a dumb question but I wonder how bad the mods will be broken after update? Servers will be able to launch with old (5.5 version) mods but materials will be f**** up (pink) or servers won't be able to launch at all using non-updated mods?

**Comment by Trojaner** [comment]
Non-updated workshop mods will not work.
Rocketmod and plugins will likely still work.

**Comment by khakers** [comment]
+1 on having a tag for 2017 compatible workshop items. It would also be great to have decent notice before the update so we can get older mods updated before they stop working.

**Comment by aviadmini** [comment]
I believe that workshop might work, I'm not sure whether that was 2017.2 or 2018.2 that broke compatibility

**Comment by khakers** [comment]
2017 will break bundles made in 5

**Comment by SDGNelson** [comment]
Yeah, that makes a lot of sense. I'll update the existing client and the 2017.4 client with compatibility features.

Re asset bundle compatibility: I believe it's mostly a change in how shaders are loaded. Some bundles e.g. road textures and ambiance audio can have been built ages ago and still load fine, but materials unfortunately not.

**Comment by ChubbyQuokka** [comment]
Will the 2017.4 build see a change to Unity's .NET 4.6 runtime, or will it remain on the .NET 3.5 runtime?

**Comment by Trojaner** [comment]
@ChubbyQuokka 

![image](https://user-images.githubusercontent.com/1809172/49401492-529cf180-f758-11e8-9a2d-2217921d9468.png)
Nelson told me earlier that he would use "recent versions" of .NET, so I assume the .NET 4.6 runtime.

**Comment by aviadmini** [comment]
New runtime will break binary compatibility for plugins and a lot of game code too.
It might be a difficult transition for everyone, but that would be real cool if done

**Comment by baranmod** [comment]
just checked couple workshop mod packs on test branch, most of the items (mostly guns) works well. Mostly broken things are scopes. Also tried to load it on server but getting "modified code" error (might be battleye issues?).

**Comment by Trojaner** [comment]
> New runtime will break binary compatibility for plugins and a lot of game code too.

Not really, backwards compatibility one of the great strengths of .NET. You can always run older assemblies (eg net35) in newer runtimes (like net461). As long as Nelson doesn't change any additional code, plugins will work fine.

See https://msdn.microsoft.com/en-us/magazine/ee819091.aspx?f=255&MSPPError=-2147217396

**Comment by Johnanater** [comment]
Testing on Linux here, There are tons of texture bugs, but it runs great performance-wise.

![20181212180853_1](https://user-images.githubusercontent.com/10360610/49910946-7091e280-fe39-11e8-841c-3aacfa233f0f.jpg)

The new trees look like transparent cotton candy, but hey, they don't crash the game!

![20181212181431_1](https://user-images.githubusercontent.com/10360610/49911117-04fc4500-fe3a-11e8-8143-3a18da08d3c9.jpg)

One bug I found was that mouse scrolling seems to be inverted in the settings, another was that server icons look a lot darker.

Also, ambient occlusion gives you wallhacks, which is also a bug on the current branch...

![20181212181735_1](https://user-images.githubusercontent.com/10360610/49911167-35dc7a00-fe3a-11e8-8ffb-ec4828a4e55b.jpg)

**Comment by SDGNelson** [comment]
Updated on preview today! Note the UI gamma hasn't been addressed yet.

.NET version was increased to 3.5, however at least in 2017.4 they have 4.6 tagged as experimental so I'm hesitant to use it.

**Comment by Trojaner** [comment]
Could you please enable 4.6 while on preview? This feature is really important for some of us plugin developers.

**Comment by aviadmini** [comment]
4.6 would allow to use modern libraries

Currently we're limited to 10 year old versions of some, and others don't support older runtime

It might be experimental but some games are successfully using it, for example Rust

**Comment by SDGNelson** [comment]
Current version on the preview branch is using .NET 4.6. This beta is fairly close to what will be released I think.

**Comment by Johnanater** [comment]
Will the preview branch still be compatible with the plugins compiled with the old .NET version, or will they need to be redone?

**Comment by Trojaner** [comment]
As mentioned...
![image](https://user-images.githubusercontent.com/1809172/50248835-5c2b8800-03ed-11e9-83e8-d8913725a6c7.png)

**Comment by SDGNelson** [comment]
How has it been going with 4.6? Have you tried running servers with your plugins?

**Comment by Trojaner** [comment]
I have tested it with RocketMod 4 and some plugins; and it seems to be working without any issues.

**Comment by VitaxaRusModding** [comment]
When will the transition to the new engine? I want to get ready.

**Comment by Trojaner** [comment]
![image](https://user-images.githubusercontent.com/1809172/51075109-5fd2c780-1698-11e9-8466-10c57efd9a32.png)

**Comment by khakers** [comment]
He said probably next week on the devblog

**Comment by SDGNelson** [comment]
Posting here as well, upgrade guide for the 3.28.0.0 update: https://steamcommunity.com/sharedfiles/filedetails/?id=1624005178

Aiming for end of this week! Assuming nobody is running into issues I will leave .NET 4.6 enabled. Will likely be another patch to the preview version in the next few days.

**Comment by Trojaner** [comment]
Sounds great 👍

**Comment by TheCubicNoobik** [comment]
Items don't have icons

![20190117203709_1](https://user-images.githubusercontent.com/37713088/51340658-2d5e0b80-1a98-11e9-820b-500b2b7a3ccc.jpg)

**Comment by TheCubicNoobik** [comment]
In this version my map is filled with water
![20190117202500_1](https://user-images.githubusercontent.com/37713088/51341063-25eb3200-1a99-11e9-9f5c-9df40143760c.jpg)
![20190117202617_1](https://user-images.githubusercontent.com/37713088/51340836-ae1d0780-1a98-11e9-8ab1-090c8fbc7c7f.jpg)

**Comment by TheCubicNoobik** [comment]
Dont falling when use the umbrella
Video: https://youtu.be/PxmuMey1Jdk

**Comment by SDGNelson** [comment]
@TheCubicNoobik which OS are you using?

**Comment by TheCubicNoobik** [comment]
@SDGNelson Windows 10 Home

**Comment by TheCubicNoobik** [comment]
@SDGNelson I find fix. Now float numbers use commas instead of decimal points.

**Comment by SDGNelson** [comment]
Oh, was it modified versions of the items that had commas rather than decimal points? Or you modified the item files to fix them?

**Comment by TheCubicNoobik** [comment]
@SDGNelson I modified the .dat file of medkit and icon now looks good

**Comment by SDGNelson** [comment]
Thanks again @TheCubicNoobik! (Resolved in 3.28.0.1)
Closing this for the meantime, but everyone feel free to report issues!
