### ISSUE TITLE
(Preview branch) Equipping some clothes makes the screen blink

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4741]
https://streamable.com/992zzq

**Comment by SDGNelson** [comment]
Thanks for the report! I'll try tracking this down. 😕

**Comment by SDGNelson** [comment]
Turns out the item inspect camera has a light attached. It was using the item's colliders' bounds to determine the center point, and they were out of date for the first frame so it used the origin point. Next version will use the renderer bounds instead which don't seem to have this issue!
