### ISSUE TITLE
Honeybadger spawning issue

### ISSUE THREAD

**Issue by FohnJallout** [SmartlyDressedGames/Unturned-3.x-Community#4743]
Whenever i spawn the PDW in single or multiplayer, it spawns with an empty magazine. This is the only gun that i'm having this issue with. Video down below.

https://github.com/user-attachments/assets/820721a2-b996-4043-9b11-3b1c4772bfe5

**Comment by MoltonMontro** [comment]
I can't recreate this issue. Does this still happen if you use `give 953f584b63bb487eabafa2770be0a798`?

Given that it's spawning with 0 ammo and in the Semi firing mode, I think you're using a mod rather than the vanilla PDW.

**Comment by SDGNelson** [comment]
Closing for the meantime but feel free to comment and I'll re-open.
