### ISSUE TITLE
Footsteps completely broken

### ISSUE THREAD

**Issue by mreowami** [SmartlyDressedGames/Unturned-3.x-Community#4747]
uhh not much else ngl 
https://github.com/user-attachments/assets/63d4af1c-3f35-47d3-95dd-b39ce4d395e7

**Comment by mreowami** [comment]
when climbing ladders apparently others can hear your footsteps, haven't tested this yet though.

**Comment by SDGNelson** [comment]
This should be fixed in the .1 patch up now! You're credited in the changelog which I appended to the main update changelog. :)
