### ISSUE TITLE
Assembly-CSharp can't be found 

### ISSUE THREAD

**Issue by Luis-Tanese** [SmartlyDressedGames/Unturned-3.x-Community#4748]
While testing my plugin, I got this issue with openmod, and another platform aswell. Not sure how to fix it, but translated it says that the system wasn't able to find the file
![image](https://github.com/user-attachments/assets/861766ff-bbbd-4fef-ade8-1594c0bd40a2)

**Comment by MoltonMontro** [comment]
Hey, @Luis-Tanese!

What plugins are you using / do you know which plugin is causing this error message to appear?

**Comment by DanielWillett** [comment]
That's strange.. have you tried updating OpenMod and the nuget package for it to the latest versions?

What framework are you targeting?

**Comment by Luis-Tanese** [comment]
Hey @MoltonMontro 
The plugin is a plugin I was making for a commission, this issue was happening with OpenMod and uScript as far as I can remember. Probably didn't happen to rocket but I don't use it so I can't really tell.

**Comment by SDGNelson** [comment]
Jdance mentioned on the forum that removal of InteractableDoorHinge caused some issues (didn't think any plugin would be referencing that, my bad) - perhaps related?

**Comment by Luis-Tanese** [comment]
well, that is exactly what happened with another project I was making in uscript, happened with open mod as well so I thought it was related. Especially this error:
```
-> Line: 752
-> Column: 19
-> Info: Could not resolve type with token 010000d3 from typeref (expected class 'SDG.Unturned.InteractableDoorHinge' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
StackTrace:
        at command_@open() line 752```

**Comment by SDGNelson** [comment]
Sorry about that! Is this open command yours? If so, if you adjust it to use GetComponentInParent<InteractableDoor> that should do the trick.

**Comment by DanielWillett** [comment]
Since openmod uses a nuget package to reference unturned dlls it's not always up to date to the latest update (the last update was 3 months ago). Since that class was removed in the actual game its not able to find the type it's expecting based on your references, so you need to just not use that type (InteractableDoorHinge) and it should work okay.

**Comment by Luis-Tanese** [comment]
Thank you, now it works fine

**Comment by SDGNelson** [comment]
Glad to hear you got it working! And, thanks DanielWillett!
