### ISSUE TITLE
Barricade dont allow me to join to my server

### ISSUE THREAD

**Issue by m0r3d** [SmartlyDressedGames/Unturned-3.x-Community#4751]
After unturned update i joined my empty server and placed barricade, then reconnected and got this issue.

Client and server are both missing unknown asset! ID: 31c8ca498e004487d4175506b5a38073
This probably means either an invalid ID was sent by the server,
the ID got corrupted for example by plugins modifying network traffic,
or a required level asset like materials/foliage/trees/objects is missing.

Issue is Barricade i placed near me before disconnect
```
[2024-10-19 12:50:31] Client received 41 Unity physics material names (5 bits)
[2024-10-19 12:50:31] Received initial date counter: 204
[2024-10-19 12:50:31] Context "Barricade" missing asset 31c8ca498e004487d4175506b5a38073
```

What could be solution?

**Comment by SDGNelson** [comment]
Sorry for the trouble! Weird that it would let you place it if it's missing on both. Does the server have any plugins that modify barricades? e.g., modifying synchronization of barricades in particular?

If it really is missing the asset then closing and re-opening the server would remove it from the save.

**Comment by m0r3d** [comment]
Yea, I'm thinking its AdvancedZones (https://github.com/DerSpeedMann/AdvancedZones) issue, but I'm not sure what it could be exactly. I'm not sure when and why its happening, its randomly - sometimes its working with AdvancedZones installed, sometimes its not. 

I was also testing - i placed barricade with AdvancedZones and got this error, then i removed the plugin, restarted and issue was same. 

Maybe you can check what it could be? Thank you for answer

**Comment by SDGNelson** [comment]
If you disable all plugins and then restart the server it should definitely be removed from the vanilla save file. (If asset is missing during load it's skipped.) If it still happened after removing AdvancedZones it might be a different plugin.

**Comment by m0r3d** [comment]
Makes sense, ill test all my modules/scripts/plugins installed

**Comment by m0r3d** [comment]
Issue was in sendRegion patch(as original method was updated). Thank you for answers!

**Comment by SDGNelson** [comment]
Glad to hear you found the cause!
