### ISSUE TITLE
Missing option in graphics setting for newtrees.

### ISSUE THREAD

**Issue by RedPanda181** [SmartlyDressedGames/Unturned-3.x-Community#4753]
Dear Unturned dev,
I have a problem with trees. I am stuck with oldtrees and don't see any option in graphics setting for using newtrees like I used to. This bug showed up after restarting the game and cannot seem to find any fix for this issue.
![20241020163040_1](https://github.com/user-attachments/assets/2307944c-67eb-4bd7-8cab-57bbfe3d8ccf)
I am not subscribed to any Steam workshop mods. Only thing I did was verifying integrity of game files on Steam which didn't find anything missing.
If you could help me out with this relatively small issue I would be grateful.

**Comment by Jdance-Media** [comment]
This is not a bug. This was in the patch notes.

**Comment by SDGNelson** [comment]
Thanks Jdance, yes, sorry, this was an intentional removal in the update.
