### ISSUE TITLE
Server keeps kicking me every time i get into one.

### ISSUE THREAD

**Issue by JacobDoesFake** [SmartlyDressedGames/Unturned-3.x-Community#4754]
Every single time i join a server, not even a minute after i get kicked out and something pops up saying "You were kicked from this server because: BattlEye: Corrupted Memory #0" and i have no idea what the hell it means and i only can play singleplayer. 
![efeeffwe](https://github.com/user-attachments/assets/8e28b59a-7e6f-4571-ba95-74fedc6865db)

**Comment by MoltonMontro** [comment]
> BattlEye: Corrupted Memory #0" and i have no idea what the hell it means and i only can play singleplayer.

Hey, @JacobDoesFake. I recommend reading the section about "Corrupted Memory #0" from BattlEye's FAQ page: https://www.battleye.com/support/faq/

We have an equivalent page on our Support site, which you can find here: https://support.smartlydressedgames.com/hc/en-us/articles/12792395906324-BattlEye-Corrupted-Memory-0

**Comment by SDGNelson** [comment]
Closing for the meantime but feel free to comment and I'll re-open.
