### ISSUE TITLE
Option to use old / classic reputation and clouds

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#4755]
It would be great to have a toggable option in the game rules to use the older reputation and a config on map level to use legacy clouds

I dont like that reputation scales off the other player, +1 -1 would be better for rp servers that use npcs with reputation requirements

![image](https://github.com/user-attachments/assets/c5c02b34-4e4a-4e97-b69b-9e0bf47fab6f)

**Comment by SDGNelson** [comment]
Closing as the issue tracker isn't intended for feature requests, sorry. Some maps like Obscured 2036 have turned off the vanilla clouds in favor of custom ones, so you could create a custom cloud effect like that if you want.
