### ISSUE TITLE
Add volume option where you cant lockpick

### ISSUE THREAD

**Issue by Lancer-TG** [SmartlyDressedGames/Unturned-3.x-Community#4757]
Would be great for rp servers, if there is any workaround outside zones plugings let me know too

![image](https://github.com/user-attachments/assets/8752a6cb-8da0-4d2d-8a3a-7ae5ec849204)

**Comment by MoltonMontro** [comment]
Is there an issue that prevents you from using a Safezone?

**Comment by Lancer-TG** [comment]
my bad

**Comment by SDGNelson** [comment]
In the meantime, zone plugins like you mentioned are a good workaround, too!
