### ISSUE TITLE
vehicles driving on 90 degree surfaces + rare gpu crash when vehicles enter water

### ISSUE THREAD

**Issue by Callmenoone62** [SmartlyDressedGames/Unturned-3.x-Community#4759]
https://github.com/user-attachments/assets/72a3a3d0-abfe-45e1-9d58-c16f2e545792

the gpu crash is really rare and im more than sure that it happens sometimes to everybody
it mostly happens when a vehicle enters water which leads the game to freeze and get black outlines of moving objects. many of my friends have had this issue and it happens on vanilla maps

**Comment by SDGNelson** [comment]
Lol at driving along the sides of the dock there!

After this vehicle underwater issue happens again could you submit a support ticket, please?
https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash

Additionally, in this case if you can attach the Client.log file to your ticket as well it might include some important info:
https://support.smartlydressedgames.com/hc/en-us/articles/12299037547284-Where-are-the-log-files

**Comment by Callmenoone62** [comment]
Alright thanks

**Comment by Callmenoone62** [comment]
I'll keep searching for some bugs

**Comment by SDGNelson** [comment]
Closing for the meantime, but I'll keep an eye out for your support ticket if you run into the graphics bug again. (The offroader wheel stickiness is more funny than bug IMO, refer to [How high can you go in Unturned... on a motorcycle?](https://www.youtube.com/watch?v=DM4n47SPREU) But it may change with any potential tire friction adjustments.)
