### ISSUE TITLE
The barricades did not appear after the map update

### ISSUE THREAD

**Issue by P1gStep** [SmartlyDressedGames/Unturned-3.x-Community#4764]
I decided to add barricades to the map, then they did not appear on the server, which I did not try, only the removal of past barricades helped (Which does not really suit me, because this is the removal of player data), what should I do to make them appear on the server?

**Comment by SDGNelson** [comment]
Sorry to say the barricades placed in the level editor are only added to the map when there isn't pre-existing barricade savedata. At the moment the only workaround is the one you discovered already.
