### ISSUE TITLE
Halloween Candy Bag problem on Steam Market

### ISSUE THREAD

**Issue by Andrew-Ducimus** [SmartlyDressedGames/Unturned-3.x-Community#4765]
Maybe not an Unturned in game problem, but there is no "Halloween Candy bag" Tag in "Collection" on steam market in Unturned search filter categories, and you can't find items you get from the bag even with "Halloween Gift Present" tag, we had similar crafting event previously with 10th Unturned Anniversary, and it had and has its own tag in "Collection" category on steam. Really uncomfortable to search Items from new collection without its own tag! Plz fix.
![ussue](https://github.com/user-attachments/assets/8cadeb7e-2cc4-401a-99c5-100853f56802)
![ussue2](https://github.com/user-attachments/assets/50d9aff1-e289-4b27-94eb-008baf82ed4e)

**Comment by SDGNelson** [comment]
Thanks for the report! I'd forgotten to set the collection tag display name after submitting the items. It's updated now but may take some time to take effect in Steam.

**Comment by Andrew-Ducimus** [comment]
> Thanks for the report! I'd forgotten to set the collection tag display name after submitting the items. It's updated now but may take some time to take effect in Steam.

How strange people didn't notice that thing after a week when its released 😳
