### ISSUE TITLE
Some of the last update (I think) broke some of my weapon mods

### ISSUE THREAD

**Issue by WekufuStudios** [SmartlyDressedGames/Unturned-3.x-Community#4768]
When I equip some of my custom modded weapons the equip anim doesn't start, instead I get a generic fire sound and the weapon reproduces the run animation, and then the gun gets unable to use. Checked animations, .dat files and everything is in order, also, guns worked some weeks ago just fine. Here is part of the error log corresponding to one of the guns involved (they has all the same error)

[2024-10-30 22:25:34] 48204 - Soviet_Remington870 raised an exception during tellEquip.equip:
[2024-10-30 22:25:34] Object reference not set to an instance of an object
[2024-10-30 22:25:34] at SDG.Unturned.UseableGun.equip () [0x00609] in <09e85ba5f9544deeb2b1edf9972661da>:0 
  at SDG.Unturned.PlayerEquipment.ReceiveEquip (System.Byte page, System.Byte x, System.Byte y, System.Guid newAssetGuid, System.Byte newQuality, System.Byte[] newState, SDG.Unturned.NetId useableNetId) [0x00a00] in <09e85ba5f9544deeb2b1edf9972661da>:0

**Comment by WekufuStudios** [comment]
thanks for the quick response! No, I checked everything (animations, models, textures, sounds, custom effects, etc) but everything seems to be in order. Not all of my weapons are broken (only shotguns and a pistol) but tried everything (even to change ids) and nothing seem to fix them.

**Comment by SDGNelson** [comment]
Hmm... In that case, perhaps the difference between the shotgun/pistol and your other weapons will help identify the cause?

Or, if you can send the mod and which item it is to support@smartlydressedgames.com, then I'll try loading it up.

**Comment by WekufuStudios** [comment]
Thank you so much, mate!! I will send you a mail with the mod just right now. And, well, I checked everything to see if there is pattern, but with no success.

**Comment by SDGNelson** [comment]
Thanks for sending over the files! I loaded them up in the debug version and they worked, so I tested in the release game and they worked there, too. This makes me wonder: Do you perhaps have two copies of the mod loaded by accident? For example, the copy from the workshop, and a local copy for editing?

The reason I ask is that if Unity encounters a duplicate asset bundle it won't load the second copy. For "master bundles" the game tries to detect this and redirect to the first copy loaded, but isn't able to do this for the older ".unity3d" asset bundles.

**Comment by WekufuStudios** [comment]
Wow, that is very unexpected, but no, I only use the files for editing (I'm not suscribed to my mod), I will try to reinstall the game on another drive and see if the problem persist, I really apreciate your time on this. I will notify if there is any change on this situation.

**Comment by WekufuStudios** [comment]
Ok, idk why, but I reinstalled the game and it worked, I think it was some corrupt file that the steam archive verification could not check the corrupted files. Anyway, I really apreciate your help on this. Best regards!!

**Comment by SDGNelson** [comment]
Bizarre but glad to hear it's working again! :)
