### ISSUE TITLE
Server crashing issues

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#477]
Having this issue for a while now. It was rare at first, servers crashed only once per week++. However, now during the weekends it started crashing like 3-4 times per day. 

One server is hosted on dedicated (i7 4790k, 16GB RAM (only 1 unturned server hosted on this one)), another on managed unturned hosting. Same problem happening for both. Both servers are hosted on Windows, different networks.

I understand that it might be a problem related to some plugins I use, but logs aren't clear enough for me to identify the exact crash reason.

Attaching most of the errors I could find in crash logs and some of these crash logs. Big thanks for any help! :)
[crash errors.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2636803/crash.errors.txt)
[output_log 5.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2636802/output_log.5.txt)
[output_log 1.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2636804/output_log.1.txt)
[output_log 2.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2636805/output_log.2.txt)
[output_log 3.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2636806/output_log.3.txt)
[output_log 4.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2636807/output_log.4.txt)

**Comment by baranmod** [comment]
update: whole week without crash, friday comes - first crash. Player flow is pretty much the same whole week. So I'm starting to think that the real reason for these crashes are not plugins after all

**Comment by SDGNelson** [comment]
Aside from a variety of plugin and content related warnings, the actual stack trace in each case seems to be:

physx::shdfnd::Time::getCurrentTimeInTensOfNanoSeconds

How long is the server running? I know that some server hosts are able to run it continuously for long periods, but the game engine vendors generally recommend rebooting every 24 hours.

**Comment by baranmod** [comment]
On a work days (monday to friday) it runs without restart and without crashes. Crashes starting on weekends. And players flow is only slightly higher on weekends. I am doing restarts on friday, saturday but it sometimes crash 1-2 hours after restart

**Comment by SDGNelson** [comment]
Crash after 1-2 hours sucks then. Since it's a lower level (physx) crash and looking it up some unity users are saying it was fixed in 5.6 I'm hopeful it will be resolved in the 2017.4 update, and if not we'll delve deeper. Is auto-restarting the process working for the moment? Right now I'm expecting to put out the 2017.4 update after the holidays traffic settles down. (Early Jan)

**Comment by SDGNelson** [comment]
Considering it's the weekend I wonder if you've been seeing any crashes after 3.28?

**Comment by baranmod** [comment]
so far, so good. Whole day without crash. A week ago it was crashing 4-5 times per day on a weekend. So I have a good feeling about this :)
