### ISSUE TITLE
Third person camera clipping through medium and small objects.

### ISSUE THREAD

**Issue by PelksUnderscore** [SmartlyDressedGames/Unturned-3.x-Community#4770]
After having thought the issue being resolved almost two months ago with this post https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4647 I have been proven wrong and if not are still able to phase through medium and small objects.

![clipping issue](https://github.com/user-attachments/assets/37e5f528-d405-4723-97fd-9d687e864f9f)
Performed on a server

**Comment by SDGNelson** [comment]
The reason for this is kind of annoying: Each collider in Unity can only be in one of 32 physics layers, and the game has physics layers for "small", "medium", and "large" objects. Only "large" objects block the camera, whereas it would be annoying if a "medium" object like a flagpole blocked your camera when you walked past it.

Other engines like Unreal or Godot support masking objects into multiple layers, in which case we would likely have a "blocks camera" mask to enable/disable blocking the camera on a per-object basis. Considering that Unity's been working on replacing their physics engine for a while (e.g., now they have Havoc as an alternative option) my hope is that we'll be able to do something similar for Unturned in the future.

**Comment by PelksUnderscore** [comment]
Then wouldnt it be a good idea at the very least to change the hesco classification to large instead of medium because hescos see a different use compared to as you said a flag pole?

**Comment by SDGNelson** [comment]
Perhaps, but the "large" objects also have a further render distance. If I recall correctly, this is part of why I went through and replaced a bunch of the barricades around Volk military base - to use the larger wall piece that does block the camera. Maybe we should do the same for Washington.
