### ISSUE TITLE
Missing btn icon in inventory

### ISSUE THREAD

**Issue by LocoCZ** [SmartlyDressedGames/Unturned-3.x-Community#4772]
Every single navigation button has an icon except for "Stockpile". It is the only button which has text in the middle and looks out of place.
![image](https://github.com/user-attachments/assets/3e9eed5f-1917-4943-811d-4ca2cbdf81b5)

<details><summary>If you compare it with other buttons everywhere else</summary>

![image](https://github.com/user-attachments/assets/910c4e15-2dc6-46d6-a924-70452c42b17f)
![image](https://github.com/user-attachments/assets/ef74efc5-0e9f-4528-b641-767b1934c326)
![image](https://github.com/user-attachments/assets/73b43596-ca5a-4664-8124-bc2e294e4340)
![image](https://github.com/user-attachments/assets/439a221f-6a1f-449c-ae9a-4e8a9b06db6c)
</details>

**Comment by SDGNelson** [comment]
Fair point, thanks! I should make an icon for it. 🤔
