### ISSUE TITLE
Menu UI Bundle List broken on IMGUI

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4775]
Im not exactly sure how its called (Steam Scream Fest?) bundle view is broken on IMGUI.
![Image1](https://github.com/user-attachments/assets/8ec5f8fb-4528-42f7-874f-7b01d0a67947)

**Comment by SDGNelson** [comment]
Thanks for the report! I'll fix this to not show up when using IMGUI.
