### ISSUE TITLE
Last suggestion before exiting: Refresh the library to display the ID. The server should not automatically save. The creative workshop requires a second upload.

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4776]
I am an Unturnedmod author and server owner with 3 years of experience in China. I decided to withdraw from the Unturnedmod community in August this year.
1: I am both surprised and disappointed by the number of online players on Unturned. I never imagined that between June and July this year, the number of players would drop from 65036 to 33437. Other server owners in China are also very disappointed. The most angry server owners even feel that Unturned is' rotten 'or' there is no future for opening servers on Unturned '.
PS: Even though other server owners in China have said so before, I still love UNturned very much until the number of players drops significantly.
2: I am very disappointed with the plugin developers in my country because they have no sense of responsibility. A project relies on not signing a contract, saying they won't do it, or having no news. The MOD we worked hard on before ruined the entire project due to the laziness of the plugin author. I don't know any foreign plugin authors because it's from China and I can't use Pay.
3: I feel very heavy about the expansion of Unturned. I am a MOD author who loves scripts very much. Almost all kinds of mods of Unturned include items, vehicles, clothes, guns, animals, and animations. But we know that even if we do a dazzling array of things, it will still be a "facelift", so I am very optimistic about scripts because they can help me create a lot of fun things. I need to try day and night, constantly restarting the game and reloading, because there are no developer tools, at most I use message scripts to output messages. The lack of developer tools makes me very tired and time-consuming.
This is my final suggestion before quitting:
1: I hope the generation table editing tool in the game can display 'ID' on the right side of each line instead of only displaying item names for each line. I really don't understand why the ID is not displayed, and I can only view the ID and resource location when hovering over the item with the mouse!
2: Will it automatically save quickly when the server window is clicked on the cross and closed now? Cannot automatically save after clicking the cross!
__Because the server operator may make operational errors, if the server is automatically saved when shutting down without backing up the server archive, it will result in irreversible errors, which is very frustrating!
__Some servers have added a lot of creative workshops, and it is possible that some workshops may not be loaded when starting the server. Sometimes the server operator is not aware of the problem, and if the server window is forcibly closed at this time, it may be possible to save it!
3: Do you still want to destroy the situation of secondary uploads on the creative workshop in the future? Cannot be destroyed, because a module requires data on PVE and cannot use the same data as PVE on PVP! The same principle applies to PVP war servers and pure servers, RP servers and battlefield servers

**Comment by hyjhkt** [comment]
There needs to be an option in the server configuration file: whether to verify module conflicts
Because there are many servers used in creative workshops nowadays (even if they are pure servers, there are still many), players do not know how to solve server mod conflicts. After being reported to the server with an error, there is no solution at all, and they do not know how to delete the 304930 folder, which makes novice players very distressed. Once the 304930 folder is deleted, players will need to spend a lot of time downloading it. If the download is completed again and an error message is still reported to the server, players will lose their gaming experience.
I swear I'm not exaggerating, because this is the lesson I've learned from these bloody years!
Therefore, I hope to:
1. After being saved and brought to the server, it can guide players on how to do it, which needs to be more suitable for novice players
2. The configuration file of the server can switch whether to skip module verification

**Comment by hyjhkt** [comment]
I hope to be able to view the scaling ratio of objects on the map editor, as it prevents the scale from being scaled and makes it difficult to understand the original size

**Comment by hyjhkt** [comment]
Map editor, unreasonable switching of roads
[Unturned 2024-11-04 20-04-14.zip](https://github.com/user-attachments/files/17617791/Unturned.2024-11-04.20-04-14.zip)
I originally intended to use a different image to create the second road, but when I generated the second road, I also changed the image of the first road

**Comment by SDGNelson** [comment]
Closing for the meantime but feel free to comment and I'll re-open.
