### ISSUE TITLE
Long asset file path names (>260 characters) cause issues

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4777]
This is a somewhat low-priority issue but one that's popped up a couple times on my server so I figured I'd document it and share possible solutions to fix the problem. Before knowing what the issue was, it was pretty annoying to debug.

Some assets have file names that exceed MAX_PATH on Windows (which is 260 characters). For example:
```
C:\Program Files (x86)\Steam\steamapps\common\Unturned\Maps\57 Studios Argonic County RP - Main\Bundles\Mods\BF_Furniture\57 Studios X OGN Furniture Pack\Items\Barricades\Release\Cabinet\Door_Modern_Cabinet\Birch_Door_Modern_Cabinet\Birch_Door_Modern_Cabinet.dat
```

This causes the server (often hosted on Linux, where this path length limitation doesn't exist) to load the asset fine, but the client to not load the asset. This may not immediately cause any issues connecting to the server, but for a vehicle or barricade, the client will get kicked from the server once that asset is spawned in-game. 

There's a couple reasonable solutions here:
- Log a warning in console for assets with long file names (so the issue is easier for mod developers & server owners to debug)
- Skip loading assets with file paths that exceed a certain length (eg. 260 - the length of "C:\\Program Files (x86\\Steam\\steamapps\\whatever" on the server
- [Update Unturned to support long file paths on Windows](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#application-manifest-updates-to-declare-long-path-capability)

**Comment by SDGNelson** [comment]
At least for the meantime, I've added logging for asset paths longer than 260 characters in the next update. Thanks for raising this issue! :)
