### ISSUE TITLE
FriendlyName doesn't trim trailing spaces (or markup)

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4783]
1\. FriendlyName includes **trailing spaces**. For example, "`Tire `" and "`Socketwrench `" show up in AssetIDs spreadsheet entries, and WikiCargoData folder names (e.g., "`Tire (Tire )`").

2\. FriendlyName includes **NPC Rich Text**. For example, "`<color=#c832fa>Coalition</color> Aircraft Hangar`". Seems helpful to include, but does appear clunky when in folder names (e.g., "`Aircraft_Hangar (_color=#c832fa_Coalition__color_ Aircraft Hangar)`".

---

**Very minor bugs.** Cargo DB size/queries aren't affected by trailing spaces as they'll get trimmed when stored. Trailing spaces could also just be removed from .dat files manually. NPC Rich Text could be reparsed on-Wiki if needed (e.g., to remove the markup, or substitute with an on-Wiki template that colors text similar to in-game rarities).

**Comment by SDGNelson** [comment]
1. For these I think we should fix the corresponding item's Name in the English.dat file. I'll add a quick check for spaces before/after vanilla names to find any (hopefully few) other cases.

2. Looks like this was properly handled for NPCs in that they have a separate entry for name color, whereas the vendor assets include rich text directly in the name. It might be sufficient to automatically strip rich text from vendor assets' FriendlyName.
