### ISSUE TITLE
[Battleye] Cannot use ban/kick/say using Battleye server Rcon

### ISSUE THREAD

**Issue by Sgtlog123** [SmartlyDressedGames/Unturned-3.x-Community#4786]
Image show player in the server unaffected by command executed.
![image](https://github.com/user-attachments/assets/ad8878b2-afa6-4077-a37c-f8cbe5ffd80b)

**Comment by SDGNelson** [comment]
This isn't something I've ever tried, sorry! I think BattlEye's RCON feature is from their very early days in, e.g., Battlefield and ARMA.

The game does bind BE's `pfnKickPlayer` callback which is also called by them to kick banned players.

I'd recommend using a different remote control mechanism.
