### ISSUE TITLE
VehicleUpdated Spelling Mistake

### ISSUE THREAD

**Issue by 0x5BC2** [SmartlyDressedGames/Unturned-3.x-Community#4787]
This is like, uhh, very <b>unimportant</b> but bothers :D

![image](https://github.com/user-attachments/assets/26bb7141-6d46-4a58-b4ee-4edf8eea5639)

Thank you for your attention to this 'urgent' matter! :D

**Comment by SDGNelson** [comment]
Seems like you and RBMKBlaze must've been collaborating on this! I'll fix the typo.
