### ISSUE TITLE
Matamorez/Zubeknakov Reworks

### ISSUE THREAD

**Issue by Wubze** [SmartlyDressedGames/Unturned-3.x-Community#479]
Hi Nelson can you possibly rework the matamorez to make it a sniper rifle again. Good rework stats could be 250m of range slow fire rate that is slightly higher than the grizzly and the ability to only use the 10 round mag, you can make the matamorez box a different item. The zubeknakov should have its damage buffed up to 40 to make in line with the old assault rifles.

**Comment by SDGNelson** [comment]
Several of these stats were adjusted relatively recently based on majority viewpoint from the SDG forums, but if you want to propose some changes that get traction again I'm of course open to adjustment!
