### ISSUE TITLE
Will Unturned's BattlEye ban other Steam accounts under the same machine code?

### ISSUE THREAD

**Issue by CatzTimes** [SmartlyDressedGames/Unturned-3.x-Community#4790]
I noticed a problem, in some underdeveloped countries, they usually use GHOST to reinstall the system, in this case, due to the packaging method of GHOST, the machine code after reinstalling the system using GHOST will be modified to the machine code of the computer that packaged GHOST!
This will result in many innocent players being banned.

**Comment by TH3AL3X** [comment]
BottlEye bans ur serial numbers of ur disks, obv he will ban u if ur hwid is banned, and you can't use that computer anymore bcs you will get banned in all ur accounts that you try to play.

**Comment by SDGNelson** [comment]
Responded on the support ticket, will close the issue here.
