### ISSUE TITLE
What font?

### ISSUE THREAD

**Issue by TendoDev1** [SmartlyDressedGames/Unturned-3.x-Community#4791]
![IMG_4032](https://github.com/user-attachments/assets/8e9322c0-df41-4e20-a5cc-4ec2571e5672)
What font is used for buildings, road sign "stop"?

and settings plssss

**Comment by SDGNelson** [comment]
Relatively default I think:

![image](https://github.com/user-attachments/assets/4c5cea5e-7304-447c-b8c3-5f6f84b514cf)
