### ISSUE TITLE
Vehicle Rendering

### ISSUE THREAD

**Issue by GatoAgus** [SmartlyDressedGames/Unturned-3.x-Community#4794]
Idk if this is a bug, but vehicles render not matter where you are, in singleplayers it only lowers some fps. but in multiplayer it lowers a lot of fps. Here some screenshoots about 3 taxis that are rendering. (one vanilla, 2 from mods)
The problem? The cars are rendering in my game while I was in a corner of the map. This lags, as i have already tested it in multiplayer. I deleted all cars from the server and went from like 30 fps to 75 fps.
The cars render not matter what graphics options u have.

Where im at:
![image](https://github.com/user-attachments/assets/ba13cdcb-b3ce-4731-a786-1c602ce615d2)

Low graphics:
![image](https://github.com/user-attachments/assets/217bb30a-a525-40d0-b0dc-44a76ce477c6)

Max graphics:
![image](https://github.com/user-attachments/assets/a5d600a7-5c92-44a6-81d4-23966b5ab276)

I hope this can get fixed or if it isn´t a bug, get added.

**Comment by SDGNelson** [comment]
Ordinarily, from where your character is those cars shouldn't be *rendered*. The reason they're visible with the freecam there while the other objects aren't is that objects are deactivated per grid cell past a certain distance, whereas vehicles always are always active even if they aren't rendered. Ideally, far away vehicles wouldn't even exist on the client, but at the moment the game still creates far away vehicles. It would be a fair bit of work to sort that out - might happen, but more likely to be a future game thing.
