### ISSUE TITLE
[preview branch] new stockpile icon does not respect Interface Foreground Colour options

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4798]
![Screenshot_216](https://github.com/user-attachments/assets/c824695c-a826-4c6c-a0ed-f77c51ed743e)
icon is always white when it should be the colour chosen in the interface foreground slider options

**Comment by SDGNelson** [comment]
Whoops, thanks Diddlyono! :)
