### ISSUE TITLE
Curator labels are not visible on server page or server list

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#4802]
Looks like missed to assign labels?

https://github.com/Unturned-Datamining/Unturned-Datamining/blob/4d89439e41b4dfbe6065e26ec3867dc8cb3c941b/Assembly-CSharp/SDG.Provider/TempSteamworksMatchmaking.cs#L528-L545

```diff
string serverCurationLabels = null;
if (_currentList == ESteamServerList.INTERNET)
{
    ServerListCuration serverListCuration = ServerListCuration.Get();
    ServerListCurationInput input = new ServerListCurationInput(steamServerAdvertisement);
    ServerListCurationOutput output = default(ServerListCurationOutput);
    serverListCuration.EvaluateMergedRules(in input, ref output);
+   serverCurationLabels = output.labels;
    if (!output.allowed)
    {
        if (curationDenyMode == EServerListCurationDenyMode.Hide)
        {
            return;
        }
        steamServerAdvertisement.isDeniedByServerCurationRule = true;
        steamServerAdvertisement.deniedByRule = output.allowOrDenyRule;
    }
}
steamServerAdvertisement.serverCurationLabels = serverCurationLabels;
```

Before:
![image](https://github.com/user-attachments/assets/07dff282-f421-4559-ad4d-0b0249912703)

After:
![image](https://github.com/user-attachments/assets/3cded275-e2a7-4fa9-b176-243745222ef9)

**Comment by SDGNelson** [comment]
Oof, thanks DiFFoZ! Earlier `serverCurationLabels` was an `out` parameter of `EvaluateMergedRules` and it looks like you're completely right I missed it.
