### ISSUE TITLE
[Preview Branch] Visual wheels bug while neutral steer

### ISSUE THREAD

**Issue by Kopfstroh** [SmartlyDressedGames/Unturned-3.x-Community#4803]
Visual wheels (Ones that don't have a collider) which are rotated using ModelRadius and CopyColliderRpmIndex, turn in the opposite direction on the right side of the vehicle. The affected wheels are listed in the WheelIndices for the right track. **When you are neutral steering, the wheels are turning in the direction that the ones on the left are turning in.** The wheels with colliders all act as expected, only the visual wheels copy the rotation from the left side. On the left side all is fine, its just the right side and only the visual ones on the right side.

Video on youtube because too big to upload here
https://www.youtube.com/watch?v=c5aU4RdM6p4

I'm pretty sure this is a bug but if I did something wrong please help me

**Comment by SDGNelson** [comment]
Very impressive visuals, nice work! :)

Are the visual-only wheels on the right side perhaps accidentally set to copy RPM from a wheel on the left side?

**Comment by Kopfstroh** [comment]
How exactly does CopyColliderRpmIndex work? -1 makes them not rotate, 0 doesn't either but anything above 0 has the rotating. But also only in 1 direction, there's no difference in odd and even numbers

**Comment by SDGNelson** [comment]
It's an index into the WheelConfigurations list. 0 is the first wheel, 1 is the second wheel, 2 is the third wheel, so on and so forth. If you set it to a wheel on the right side of the vehicle I think it'll do what you want.

**Comment by SDGNelson** [comment]
Ah, that makes sense. I'll see about clarifying that documentation!

Sorry about this misleading error message as well: I think perhaps you have the visual-only wheels in the crawler track material wheel indices list? I'll adjust this to clarify the wheel exists but that it's not meant to be used with visual-only wheels.
