### ISSUE TITLE
[Preview Branch] Crawler Vehicle Self Rotation Speed

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#4804]
https://youtu.be/XnGe0OrNIG0

Usually tracked vehicles have slower speeds when it comes to rotating on themselves for stability reasons.

**Comment by SDGNelson** [comment]
Thanks for the report, but I find it really fun and don't want to change it. When starting the crawler track physics on the orange off roader the first thing I did was spinning really fast. ;)

**Comment by WW-TC** [comment]
Maybe add an option then to limit it incase modders want to have more control over it?

**Comment by SDGNelson** [comment]
If you use a lower torque it shouldn't spin as fast: https://docs.smartlydressedgames.com/en/latest/assets/vehicle-asset.html#crawlertracksteering-torque

(higher torque applies more force to the wheels, higher acceleration)

**Comment by SDGNelson** [comment]
I turned down the steering torque for the tank so it's not quite as crazy as the Explorer. ;)
