### ISSUE TITLE
Zombie AI breaks if target is in a vehicle

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4805]
happens on preview branch and the live build.
zombie AI breaks if the target player is in a vehicle, instead of pathfinding around objects and breaking structures in the way, they will continuously walk towards the center of the vehicle but will ignore any obstacle, getting stuck. if there are obstacles in the way, sometimes zombies will get significantly slower.
we tested this a bit yesterday, it seems to be true no matter the vehicle, no matter the location. also true for mega zombies and most likely other special zombies.

https://www.youtube.com/watch?v=XoU0zVgSWCs

**Comment by SDGNelson** [comment]
Thanks for this report as well! I wonder how long it's been like this. 0_o
