### ISSUE TITLE
Russia's Bug on Liberator

### ISSUE THREAD

**Issue by Astrepio** [SmartlyDressedGames/Unturned-3.x-Community#4807]
When you go to a broken Tank in the Liberator you can do a texture glitch right there, so players can’t find you.
Also thank to Bear.
https://youtu.be/qLI62SR_Ho4

**Comment by SDGNelson** [comment]
Hi Astrepio, thanks for the report! Unfortunately, it's a long-term [wiggling out of bounds](https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds) issue. That article explains why it is the way it is. 😞

**Comment by Astrepio** [comment]
So it won't be fixed?

**Comment by SDGNelson** [comment]
Not in the near term, sadly. I'll re-investigate it again next time we update Unity engine versions. Enabling the fix (`CharacterController.enableOverlapRecovery`) causes worse problems like able to walk directly through certain angled walls without trying hard (whereas currently it requires some determination), and allows vehicles to push players straight through walls.
