### ISSUE TITLE
Buak Quest Bug

### ISSUE THREAD

**Issue by Molaty123** [SmartlyDressedGames/Unturned-3.x-Community#4810]
In the Quest "Clear because we are here" I finish the Quest and when i go to turn it in and press Continue the button goes Grey. I then try and to start his next Quest and it puts me in a loop and doesn't actually give me the quest.

**Comment by SDGNelson** [comment]
Sorry for the trouble! I'll forward the report on to the map developer, but will close the issue here because it's intended for bugs in the base game.

**Comment by ToothyDeerryte** [comment]
I did a quick test just in case and I didn't manage to replicate it, seems to work fine on my end. I believe it could be a conflicting mod/map though. I know Buak quests overlap a bit with a few other curated maps. I'd say check out your mod list and test out what works and what doesn't! (One thing as well, having Buak, and the Buak Assets mod on at the same time can cause issues, so keep an eye out for that or any other potential Buak duplicates!)

**Comment by Molaty123** [comment]
> I did a quick test just in case and I didn't manage to replicate it, seems to work fine on my end. I believe it could be a conflicting mod/map though. I know Buak quests overlap a bit with a few other curated maps. I'd say check out your mod list and test out what works and what doesn't! (One thing as well, having Buak, and the Buak Assets mod on at the same time can cause issues, so keep an eye out for that or any other potential Buak duplicates!)

Thank you I disabled stuff and it worked 👌

**Comment by Molaty123** [comment]
> Sorry for the trouble! I'll forward the report on to the map developer, but will close the issue here because it's intended for bugs in the base game.

My apologies thank you for helping 🙏

**Comment by ToothyDeerryte** [comment]
> > I did a quick test just in case and I didn't manage to replicate it, seems to work fine on my end. I believe it could be a conflicting mod/map though. I know Buak quests overlap a bit with a few other curated maps. I'd say check out your mod list and test out what works and what doesn't! (One thing as well, having Buak, and the Buak Assets mod on at the same time can cause issues, so keep an eye out for that or any other potential Buak duplicates!)
> 
> Thank you I disabled stuff and it worked 👌

Glad to hear it worked!
