### ISSUE TITLE
server have a some issue

### ISSUE THREAD

**Issue by Gryfiq** [SmartlyDressedGames/Unturned-3.x-Community#4814]
So i installed a custom map (not mine) and i have tried to run it on my dedicated unturned server but one error pop up

Navigation bounds count (33) does not match graph count (32) during server load

i dont know why it pop up so can someone help?

**Comment by GazziFX** [comment]
need to rebake navigation

**Comment by SDGNelson** [comment]
Thanks GazziFX - unfortunately, yes, this is something the map creator would need to update.
