### ISSUE TITLE
Smoothing bug on Analogue Detective skins

### ISSUE THREAD

**Issue by Augusha** [SmartlyDressedGames/Unturned-3.x-Community#4818]
Seems like smoothing was not imported from Blender (don't mind missing battery belt on incorrect one).
![image](https://github.com/user-attachments/assets/7f2d78ca-47b7-4ab4-9bab-ac0b949e127f)

**Comment by SDGNelson** [comment]
For anyone who comes across this: Augusha also sent me an email reporting the issue (thanks!), copying part of my response here:

I think what happened is the version of Blender on the "build machine" that prepares the updates was different than the one on my computer, and this resulted in different smoothing. To simplify things I enabled "calculate normals" import option for the mesh and I will double-check it looks correct before releasing.
