### ISSUE TITLE
Emotes under the water

### ISSUE THREAD

**Issue by Astrepio** [SmartlyDressedGames/Unturned-3.x-Community#4819]
Well, this bug has been in the game for a very long time. I thought that sooner or later someone would report it and it would be fixed, but it hasn't been fixed yet. 
As you can see in the video, emotes work underwater. But that shouldn't be the case, at least not with surrender. You should actually start sinking, not stay afloat, after all :D. Just disable surrender as you did with rest. All other emotes are fine but also can be disabled.

Video: https://youtu.be/nOswxYIA5pE

**Comment by SDGNelson** [comment]
Thanks for the report! Although it doesn't make sense in the real world, I think it's fairly harmless, and enables some options like holding a captive in an underwater base.
