### ISSUE TITLE
NEW France map texture bug

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#482]
On a video, that a player recorded for us, he shows what he found accidentally, to get under the map without any plates or other players.
https://youtu.be/-0_Cg2sAiAI
Location: https://cdn.discordapp.com/attachments/330031205003165698/519985909110800416/unknown.png

**Comment by evermoreservers** [comment]
Well. Thanks for your suggestion and answer.
I reported it here cuz the map is officially available at this moment, and as Nelson let others play it without any workshop stuff, he can be interested in bugs with this.
Hoping to help the game always : )
Also, as you could find this, and they are map creators for the game, they might also being updated with GitHub aswell. : )

**Comment by SDGNelson** [comment]
Forwarded to France team just in case.
