### ISSUE TITLE
Zombies can push tanks

### ISSUE THREAD

**Issue by Chris700577** [SmartlyDressedGames/Unturned-3.x-Community#4824]
https://github.com/user-attachments/assets/e4a97f3e-1aaf-4b6b-aeba-d564d69b1b80

https://github.com/user-attachments/assets/002af28c-b9d5-4ac3-b697-005c2624b634

**Comment by Astrepio** [comment]
Problematic issue, here you can find Nelson's answer to the issue.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4553
