### ISSUE TITLE
Filter issue again 😭

### ISSUE THREAD

**Issue by Andrew-Ducimus** [SmartlyDressedGames/Unturned-3.x-Community#4827]
Well, when Halloween candy bags were released, there was no specific filter option in "collection" to find items belong to that collection, it was quickly fixed as well as I posted issue about that. 
Now, we have same issue - no filters options for "Business Briefcase Mystery Box" and "Artisan's makeshift Mystery Box" indeed.
![No filter](https://github.com/user-attachments/assets/3f632543-d230-4c90-958f-36238ceafbe5)
Nelson pls fix 🙏, love ya❤

**Comment by MoltonMontro** [comment]
They're currently under a shared filter. 
![image](https://github.com/user-attachments/assets/0735ec77-f643-48ac-9305-9b23c98caa2a)

**Comment by Andrew-Ducimus** [comment]
oh... I need glasses
