### ISSUE TITLE
Request: Disable fading of chat messages completely

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#485]
RE: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/396

Since rich text messages fade bug will not be fixed, is it possible to disable fading completely?
It causes rich parts of the chat to fade while other parts do not fade, resulting in half chat disappearing:

![image](https://user-images.githubusercontent.com/1809172/49702626-3511d100-fc0b-11e8-98ce-eb42a702549a.png)

**Comment by SDGNelson** [comment]
Fair enough, will be in both updates

**Comment by Trojaner** [comment]
Hey Nelson,
What I meant was actually disabling fading for non-rich text messages, to have consistent chat where not only a part of the chat fades away
