### ISSUE TITLE
Add shutdown message

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#489]
My servers automatically restart themselves every 24 hours, but when the server does shutdown, the shutdown message just says "The server has been shutdown". Everyone that didn't read chat is just left to assume that the server is gone and will never come back.

It'd be awesome if you could specify a reason, such as /shutdown 5 "The server is restarting, join back in a minute!"

**Comment by SDGNelson** [comment]
Will be a lot of changes, but would be very helpful so I'll get this in for the holiday update!
