### ISSUE TITLE
When I die, I appear in the place I died before xD

### ISSUE THREAD

**Issue by Jarshoowa** [SmartlyDressedGames/Unturned-3.x-Community#491]
Sometimes when i die, i appear in the place that i died before, it happens in any server, it happens to my friends too, i dont know what is causing it, thanks for reading this

**Comment by Johnanater** [comment]
That's an odd bug _xD_

I've had reports of people respawning where they died on my server a while ago. So this might be worth checking out.

**Comment by SDGNelson** [comment]
Was it after a suicide and/or asphyxiation death? Both of those will use your previous spawnpoint to prevent intentionally teleporting around the map.

**Comment by Jarshoowa** [comment]
Nope, those deaths were caused by a crash (jet crash)

**Comment by SDGNelson** [comment]
There was a bug with disconnection after a vehicle crash which was fixed a few updates ago. Has this actually happened to you recently?
