### ISSUE TITLE
Some issues after update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#494]
#1 Getting some error because of horde beacon. Horde stays even after server restart, Logs flooding with errors. After killing last zombie horde doesn't break.
![image](https://user-images.githubusercontent.com/14231707/50026211-c0ff7080-fff0-11e8-9efd-47d37efd6e5f.png)
![image](https://user-images.githubusercontent.com/14231707/50026225-cbba0580-fff0-11e8-92c2-e85e37e25f91.png)

#2 No damage for barricades, structures (charges, raiding rifles)
#3 Charges don't disappear after detonating (doesn't do damage tho)

**Comment by Trojaner** [comment]
These are related to plugins which got broken by the update. You should contact their respective developers.

**Comment by baranmod** [comment]
ok, found out which plugins caused it. Thanks :)

**Comment by SDGNelson** [comment]
Sorry about that! Generally avoids API compatibility changes (e.g. I add new method called by old signature), but in this case a get property was changed into a public field.
