### ISSUE TITLE
StackTrace does not show up anymore

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#501]
Hey,
I have noticed that in logs stacktraces do not show up anymore. This is problematic for plugin developers as we can not find out whats causing errors this way. Is it possible to re enable them again?

**Comment by SDGNelson** [comment]
In the 2017.4 version?

**Comment by Trojaner** [comment]
No, on normal branch.

**Comment by Trojaner** [comment]
You can see an example here: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/494

**Comment by SDGNelson** [comment]
I don't think anything changed? In that post's stack trace:

ZombieManager.Update
Zombie.tick
Tried to call get_owner, but property doesn't exist anymore

**Comment by Trojaner** [comment]
Yes, but according to StackTrace Unturned itself tries to call that. This is not possible; as it wouldnt compile this way.

**Comment by SDGNelson** [comment]
If you throw an exception from your own plugin does it generate a stack trace in the output_log.txt?

**Comment by Trojaner** [comment]
It looks like some other plugin is hooking Unturned methods which causes this weird behaviour. Sorry for wasting your time :(

**Comment by SDGNelson** [comment]
Np
