### ISSUE TITLE
Add SteamCall for overriding client-side Player gravity

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#51]
[ Follow-up for the #44 ]

The implementation could be _something like_ the following:

- Add additional property `gravityOverride` that will be managed on server
- Add Steam call `tellGravityOverride` in `PlayerMovement` that will change the `gravityOverride` value (e.g. call it with `ESteamCall.ALL` to set both clients and server gravity for specific player)
- Change `public float gravity;` field in `PlayerMovement` to the following

```csharp
        private float _gravity;
        private float _gravityOverride;

        public float gravityOverride {
            get { return _gravityOverride; }
            set {
                _gravityOverride = value;
                computedGravity = _gravityOverride * _gravity;
            }
        }

        public float gravity {
            get { return _gravity; }
            set {
                _gravity = value;
                computedGravity = _gravity * _gravityOverride;
            }
        }

        public float computedGravity { get; private set; }
        
        [SteamCall]
        public void tellGravityOverride(CSteamID steamID, float newGravityOverride) {
            if (channel.checkServer(steamID)) {
                gravityOverride = newGravityOverride;
            }
        }
```
- In `PlayerMovement.Start()` method add `gravityOverride = 1f;` right before `gravity = 1f;`
- Change read accesses to old `gravity` field (which became a property now) to `computedGravity` getter (which is the final gravity value we want to use). Those accesses are all found in `PlayerMovement.simulate()`, `PlayerLife.onLanded()` and `PlayerAnimator.onLanded()` methods
- (Optional) rename `gravity` property to `itemGravity` or similar (for the sake of naming)

I don't claim it to be the best way to implement gravity overrides but this implementation has following advantages: 
- keep item gravity (for umbrellas etc) separate from server overridden gravity thus eliminating collisions 
- adding more gravity modifiers is easy

One concern I got is moving vertically when gravity is overridden (afaik all vertical movement is gravity, jump and glitches)

**Comment by SDGNelson** [comment]
The next update adds a method sendPluginGravityMultiplier to PlayerMovement which updates a separate gravity multiplier for the server and owning player as described in your post!
