### ISSUE TITLE
Issue with unturned screen

### ISSUE THREAD

**Issue by BraianKant** [SmartlyDressedGames/Unturned-3.x-Community#512]
On my server often there are various bugs on the screen. What can be the reason? The screen can just smudge or roll over, etc.
![image](https://user-images.githubusercontent.com/41028671/50349351-5c4a9580-055d-11e9-895d-b254e3bd77ff.png)
![image](https://user-images.githubusercontent.com/41028671/50349364-62407680-055d-11e9-8f8e-316ff08f45a5.png)

**Comment by SDGNelson** [comment]
Wow that's pretty wacky! I'd guess this is the sort of thing that will be resolved after the unity LTS update. If it's happening for you in singleplayer I'd be interested to know if it works fine for you in the preview branch. (Unturned > Properties > Betas > preview)

**Comment by BraianKant** [comment]
This happens in many players on my server.

**Comment by BraianKant** [comment]
Can you tell me the reason for all this? Mods? I have only UI installed on my server

**Comment by MeedicBear** [comment]
that use to happen to me everywhere when i had deferred render mode

**Comment by BraianKant** [comment]
So when is it going to be roughly fixed?
