### ISSUE TITLE
Players can fly up Russia APC (and maybe more veh)

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#513]
So we just noticed that players started to fly up to skybases using vehicles, like APC,
Was close to ban them for hacking but then they just told us it's a glitch that can be used in single player aswell.
So here is a video how 2 player does it without any commands:
https://youtu.be/FwB07DqzJVI

Of course, with teleport, it is way faster and easier, but players have time so the slow-mode Works too.

> As on the video, get under vehicle, the second player change to passenger seat, and the player under vehicle just spamming SPACE button.

**Comment by themisfitgames** [comment]
Sounds like the hack client that allows people to fly any vehicle on Unturned at any given moment.

**Comment by Johnanater** [comment]
Yeah, players can move vehicles, but I haven't seen it this bad. I've used the plugin uFly to move some vehicles. Basically I'd just fly into them and they'd go flying.

**Comment by evermoreservers** [comment]
Well, they can just fly up to any skybase, get out the vehicle and run through the plates put on the vehicle and reach the skybase, or they can just fly close enough and simply raid it sitting in the vehicle, then jump in simply.
So literally, they dont need plates, they dont need heli, they just bug up and so on.
