### ISSUE TITLE
Broadcast messages go weird

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#514]
Hey! So I've just noticed that if 2 message, like announcement and a death message is said at exactly the same time, none Will shown but Will go to a weird character set.
This is a bug since you modified something with Rich text or added, i dont know, but it happens only since a few months. (2-3)
This is what happens:
https://cdn.discordapp.com/attachments/432909372272803860/524925965865058314/unknown.png
https://cdn.discordapp.com/attachments/488104226002567168/526089424317186079/unknown.png

Yeah i know it is being said by plugins, but the broadcast is by the game, im sorry if i didnt say right time, but you might know when did u change it.. if i say it happens since you removed the [W] [A] [G] markings at chat.

**Comment by aviadmini** [comment]
uPdAtE rOcKeT and AviRockets modules

**Comment by evermoreservers** [comment]
Yeah as i said this bug is here since months.. so of course i updated rocket long ago, and i'm not using avirockets.
I also know that the messages were messed up after an update and had something to do with rocket and avirocket, but that time all the messages were bad. Now i reported a case where this problem happen when 2 broadcast goes at same time. Please read my report before commenting.

**Comment by Trojaner** [comment]
This is a bug that occurs if you use outdated RocketMod and plugins. This is not an Unturned bug.

**Comment by evermoreservers** [comment]
I understand. Well then, thanks for answer.
