### ISSUE TITLE
Cant connect to a too long domain name

### ISSUE THREAD

**Issue by Adamv21** [SmartlyDressedGames/Unturned-3.x-Community#519]
Basiaclly. If you own a domain longer then 9 charcters (it seems like atleast) you can't connect to it. When yuo click the connect button ingame nothing happens. I can't say forsure it's because of this because I haven't looked in source code but it seems to me the client (my unturned) doesn't even try connect.

**Comment by Trojaner** [comment]
This might happen if you domain contains spaces

**Comment by Adamv21** [comment]
No spaces (there is no subdomain and the "extension" is .com

**Comment by Trojaner** [comment]
In that case the space bug should be fixed too as its sometimes frustrating when just nothing happens.

**Comment by SDGNelson** [comment]
Unturned uses System.Net.Dns.GetHostAddresses to resolve that. I may need to allow longer strings in the connect field, or it might be returning >1 address? One change I'll make is to connect to the first returned address rather than silently returning
