### ISSUE TITLE
Items exported on Unity 2017 looks very bland/ too bright

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#520]
What may be the cause of items looking way too bland in game? On editor they look almost black and in game they look light-grey.

**Comment by SDGNelson** [comment]
Happens if the color space is mis-matched. In Unity there's an option in Player Settings called Color Space which should be set to Linear. Worked through a lot of reports of this, so I will be making an upgrade guide with workarounds :)

**Comment by baranmod** [comment]
For some reason, it looks much worse with linear color space (almost white, light grey instead of black in game)

**Comment by SDGNelson** [comment]
Using the shaders from the preview AllShaders unity package?

**Comment by baranmod** [comment]
Ok, I believe I found a solution. For some reason after opening project on unity 2017 sRGB was disabled for all textures.

**Comment by SDGNelson** [comment]
Glad to hear it! Obviously you already sorted it out, but I've now got a guide on upgrading here:

https://steamcommunity.com/sharedfiles/filedetails/?id=1624005178

Let me know if you still have any issues or additions for the guide.
