### ISSUE TITLE
Server +24 slots is visible

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#521]
It would be nice if servers with more than 24 slots are visible in the search bar.

**Comment by Johnanater** [comment]
Having more than 24 players can kill the server and make it lag, there's plugins for this though.

**Comment by Trojaner** [comment]
Apparently some do not get the issue here.

If you server has more than 24 slots, it will not show up in the Servers tab. A plugin can not fix this, its a hardcoded into the client.

**Comment by Johnanater** [comment]
We're referring to faking the max player count. You can set the max player count to 48 in the server config, but have a plugin report it as 24 to the server list.

But yes, back to the topic. There should be at least an option to show 24+ slot servers.

**Comment by SDGNelson** [comment]
Been lots of discussion over this. For the LTS update I'll add a preference to show >24 by default, and maybe show >24 when searching by name

**Comment by thereis** [comment]
Yes!!!! Finally!

**Comment by SDGNelson** [comment]
Recommended player count is still 24, but 'max' is now 100. If you search for a server by name then it will show up in the server list regardless of max player count. You can also set Show_Servers_With_Greater_Than_Recommended_Players in your preferences.json file to show all servers.

**Comment by thereis** [comment]
But it will show servers more than 24 players by default, right?

**Comment by SDGNelson** [comment]
Nope, the default is still to hide servers >24 max players, but now they will be visible when explicitly searching.

**Comment by thereis** [comment]
I think that solves the problem partially. If you're saying that is not recommended, why does not show a message displaying this alert? In my concern, the option to show servers >24 should be default.

**Comment by Adamv21** [comment]
I agree, it makes it kindof useless if it can't be found natuarlly.

**Comment by thereis** [comment]
It does not make sense for newbies.

**Comment by Adamv21** [comment]
Maybe. Still don't see how 24 players would be better for that. 32-48 player pvp servers i'd imagine would be alot more popular. IF people find it too much action they'll probably leave and find another one. That's just my perspective. Either way I think it should be the default setting. Maybe it varies from user to user but let them get the chance to experience 48+ servers. Because at the moment no servers will be found if you need to search for it. It needs to be viable.

**Comment by Adamv21** [comment]
Lol, dunno if you were serious about the socialism part xd. I just think the player should have an option (by default) to search for servers > 24. 95% of the playerbase (I feel like) probably doesn't know prefrences.json even exist. Nor where and how to edit it.

**Comment by thereis** [comment]
Yes, I'm joking... but sometimes it seems it is ¯\_(ツ)_/¯. I've opened a ticket with the same purpose... and the answer? You probably know... #192
