### ISSUE TITLE
SDG.Unturned.Block.writeByteArray error spam + Crashlogs

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#528]
Rarely happens after someone joins. Doesn't happen with every server. Could be connected with mods somehow?
The spam starts getting a little out of control after a bit... (see the line count)
![image](https://user-images.githubusercontent.com/1404955/51390876-96e62480-1b41-11e9-89c5-074d3411cc26.png)
Attaching all (3) logs I could find:
[Desktop.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2773175/Desktop.zip)

...Also, I've collected all (13) crashes I've had with various servers (Client crashes + Server crashes) in a month in this archive:
[game.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2773178/game.zip)
Could help with fixing some bugs, I hope.

**Comment by Daniil1288** [comment]
Still seem to have some issues with my server:
[1/19/2019 12:15:22 PM] [Info] [SV]Belka [Bel☯ka❅] was blown up by [SV]NOICEMC [✞Святой отец✞] with a missile!
[1/19/2019 12:15:28 PM] [Info] General: Exception raised when RPC invoked tellDead:
[1/19/2019 12:15:28 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.getBytes (Int32 prefix, System.Int32& size, System.Object[] objects)
SDG.Unturned.SteamChannel.getPacket (ESteamPacket type, Int32 index, System.Int32& size, System.Byte[]& packet, System.Object[] arguments)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, Byte x, Byte y, Byte area, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.ItemManager.dropItem (SDG.Unturned.Item item, Vector3 point, Boolean playEffect, Boolean isDropped, Boolean wideSpread)
SDG.Unturned.PlayerInventory.onItemDiscarded (Byte page, Byte index, SDG.Unturned.ItemJar jar)
SDG.Unturned.Items.loadSize (Byte newWidth, Byte newHeight)
SDG.Unturned.Items.resize (Byte newWidth, Byte newHeight)
SDG.Unturned.PlayerInventory.onLifeUpdated (Boolean isDead)
SDG.Unturned.PlayerLife.tellDead (CSteamID steamID, Vector3 newRagdoll)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.SteamChannel:send(ESteamCall, ESteamPacket, Int32, Byte[])
SDG.Unturned.SteamChannel:send(String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.PlayerLife:doDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&)
SDG.Unturned.PlayerLife:askDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&)
SDG.Unturned.DamageTool:damage(Player, EDeathCause, ELimb, CSteamID, Vector3, Single, Single, EPlayerKill&, Boolean)
SDG.Unturned.DamageTool:explode(Vector3, Single, EDeathCause, CSteamID, Single, Single, Single, Single, Single, Single, Single, Single, List`1&, EExplosionDamageType, Single, Boolean, Boolean, EDamageOrigin)
SDG.Unturned.Rocket:OnTriggerEnter(Collider)
[1/19/2019 12:15:29 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ItemManager.askItems (CSteamID steamID, Byte x, Byte y)
SDG.Unturned.ItemManager.onRegionUpdated (SDG.Unturned.Player player, Byte old_x, Byte old_y, Byte new_x, Byte new_y, Byte step, System.Boolean& canIncrementIndex)
SDG.Unturned.PlayerMovement.updateRegionAndBound ()
SDG.Unturned.PlayerMovement.simulate ()
SDG.Unturned.PlayerInput.FixedUpdate ()
[1/19/2019 12:20:44 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ItemManager.askItems (CSteamID steamID, Byte x, Byte y)
SDG.Unturned.ItemManager.onRegionUpdated (SDG.Unturned.Player player, Byte old_x, Byte old_y, Byte new_x, Byte new_y, Byte step, System.Boolean& canIncrementIndex)
SDG.Unturned.PlayerMovement.updateRegionAndBound ()
SDG.Unturned.PlayerMovement.simulate ()
SDG.Unturned.PlayerInput.FixedUpdate ()

[1/19/2019 12:20:45 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ItemManager.askItems (CSteamID steamID, Byte x, Byte y)
SDG.Unturned.ItemManager.onRegionUpdated (SDG.Unturned.Player player, Byte old_x, Byte old_y, Byte new_x, Byte new_y, Byte step, System.Boolean& canIncrementIndex)
SDG.Unturned.PlayerMovement.updateRegionAndBound ()
SDG.Unturned.PlayerMovement.simulate ()
SDG.Unturned.PlayerInput.FixedUpdate ()

[1/19/2019 12:20:46 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ItemManager.askItems (CSteamID steamID, Byte x, Byte y)
SDG.Unturned.ItemManager.onRegionUpdated (SDG.Unturned.Player player, Byte old_x, Byte old_y, Byte new_x, Byte new_y, Byte step, System.Boolean& canIncrementIndex)
SDG.Unturned.PlayerMovement.updateRegionAndBound ()
SDG.Unturned.PlayerMovement.simulate ()
SDG.Unturned.PlayerInput.FixedUpdate ()

[1/19/2019 12:20:47 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ItemManager.askItems (CSteamID steamID, Byte x, Byte y)
SDG.Unturned.ItemManager.onRegionUpdated (SDG.Unturned.Player player, Byte old_x, Byte old_y, Byte new_x, Byte new_y, Byte step, System.Boolean& canIncrementIndex)
SDG.Unturned.PlayerMovement.updateRegionAndBound ()
SDG.Unturned.PlayerMovement.simulate ()
SDG.Unturned.PlayerInput.FixedUpdate ()
[1/19/2019 12:25:59 PM] [Info] [World] [SV]Belka [Bel☯ka❅]: "/kill faba"
[1/19/2019 12:26:05 PM] [Info] General: Exception raised when RPC invoked tellDead:
[1/19/2019 12:26:05 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.getBytes (Int32 prefix, System.Int32& size, System.Object[] objects)
SDG.Unturned.SteamChannel.getPacket (ESteamPacket type, Int32 index, System.Int32& size, System.Byte[]& packet, System.Object[] arguments)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, Byte x, Byte y, Byte area, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.ItemManager.dropItem (SDG.Unturned.Item item, Vector3 point, Boolean playEffect, Boolean isDropped, Boolean wideSpread)
SDG.Unturned.PlayerInventory.onItemDiscarded (Byte page, Byte index, SDG.Unturned.ItemJar jar)
SDG.Unturned.Items.loadSize (Byte newWidth, Byte newHeight)
SDG.Unturned.Items.resize (Byte newWidth, Byte newHeight)
SDG.Unturned.PlayerInventory.onLifeUpdated (Boolean isDead)
SDG.Unturned.PlayerLife.tellDead (CSteamID steamID, Vector3 newRagdoll)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.SteamChannel:send(ESteamCall, ESteamPacket, Int32, Byte[])
SDG.Unturned.SteamChannel:send(String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.PlayerLife:doDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&)
SDG.Unturned.PlayerLife:askDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&)
Essentials.Api.Unturned.UPlayer:Kill()
Essentials.Commands.CommandKill:OnExecute(ICommandSource, ICommandArgs)
Essentials.Core.Command.CommandAdapter:Execute(IRocketPlayer, String[])
Rocket.Core.Commands.RegisteredRocketCommand:Execute(IRocketPlayer, String[])
Rocket.Core.Commands.RocketCommandManager:Execute(IRocketPlayer, String)
Rocket.Unturned.<>c:<bindDelegates>b__16_3(SteamPlayer, String, Boolean&, Boolean&)
SDG.Unturned.ChatManager:process(SteamPlayer, String)
SDG.Unturned.ChatManager:askChat(CSteamID, Byte, String)
System.Reflection.MethodBase:Invoke(Object, Object[])
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.Provider:receiveServer(CSteamID, Byte[], Int32, Int32, Int32)
SDG.Unturned.Provider:listenServer(Int32)
SDG.Unturned.Provider:listen()
SDG.Unturned.Provider:Update()
[1/19/2019 12:27:01 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.writeByteArray (System.Byte[] values)
SDG.Unturned.PlayerInventory.save ()
SDG.Unturned.Player.save ()
SDG.Unturned.SaveManager.onServerDisconnected (CSteamID steamID)
SDG.Unturned.Provider.dismiss (CSteamID steamID)
SDG.Unturned.Provider.handleValidateAuthTicketResponse (ValidateAuthTicketResponse_t callback)
SDG.Unturned.Provider.onValidateAuthTicketResponse (ValidateAuthTicketResponse_t callback)
Steamworks.Callback`1[Steamworks.ValidateAuthTicketResponse_t].OnRunCallback (IntPtr thisptr, IntPtr pvParam)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback`1:OnRunCallback(IntPtr, IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.SteamworksProvider.SteamworksProvider:update()
SDG.Unturned.Provider:Update()

[1/19/2019 12:27:10 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.writeByteArray (System.Byte[] values)
SDG.Unturned.PlayerInventory.save ()
SDG.Unturned.Player.save ()
SDG.Unturned.SaveManager.onServerDisconnected (CSteamID steamID)
SDG.Unturned.Provider.dismiss (CSteamID steamID)
SDG.Unturned.PlayerInput.FixedUpdate ()

[1/19/2019 12:27:10 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.writeByteArray (System.Byte[] values)
SDG.Unturned.PlayerInventory.save ()
SDG.Unturned.Player.save ()
SDG.Unturned.SaveManager.onServerDisconnected (CSteamID steamID)
SDG.Unturned.Provider.dismiss (CSteamID steamID)
SDG.Unturned.PlayerInput.FixedUpdate ()

[1/19/2019 12:27:10 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.writeByteArray (System.Byte[] values)
SDG.Unturned.PlayerInventory.save ()
SDG.Unturned.Player.save ()
SDG.Unturned.SaveManager.onServerDisconnected (CSteamID steamID)
SDG.Unturned.Provider.dismiss (CSteamID steamID)
SDG.Unturned.PlayerInput.FixedUpdate ()

[1/19/2019 12:27:10 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.Block.writeByteArray (System.Byte[] values)
SDG.Unturned.PlayerInventory.save ()
SDG.Unturned.Player.save ()
SDG.Unturned.SaveManager.onServerDisconnected (CSteamID steamID)
SDG.Unturned.Provider.dismiss (CSteamID steamID)
SDG.Unturned.PlayerInput.FixedUpdate ()
And then the last error's being spammed at the rate of around 50errors/second:
![image](https://user-images.githubusercontent.com/1404955/51424987-1c6fe000-1be7-11e9-98d3-d78814ba8693.png)

**Comment by SDGNelson** [comment]
All of these bugs seem to have items with null state arrays in common, but the vanilla game will never create those. 😕 My guess is that a plugin is creating item instances will null state, so in the next patch I'll insert code in a few places to assign an empty state if it's null during creation.
