### ISSUE TITLE
Kick Owner Off Non-Exploding Vehicle

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#53]

**Comment by VitaxaRusModding** [comment]
Hello. Sorry that I'm writing here (most likely it's wrong). I want to ask you, below on the screen, what does it mean? Does this mean that good people have access to the source code Unturned 3.0?

![cutxv3mtluk](https://user-images.githubusercontent.com/32962870/32786575-ad34d490-c997-11e7-8e33-6638918b5ab2.jpg)
