### ISSUE TITLE
New Update's Bugs

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#531]
1. No Icons, see below.
![image](https://user-images.githubusercontent.com/1404955/51407541-38cf3680-1b6d-11e9-9acd-0ed07be2e80c.png)
2. Zombies are unkillable with all weapons except rocket launchers.
![image](https://user-images.githubusercontent.com/1404955/51407617-72a03d00-1b6d-11e9-9283-083016abf45e.png)
I will report new bugs as soon as I see them.

Edit 1: Players are also unkillable with weapons, apparently.

Edit 2: Crosshair's a dot. On every single weapon. Using Nykorev as an example:
![image](https://user-images.githubusercontent.com/1404955/51408349-703ee280-1b6f-11e9-9597-b85d5eaeff2e.png)

**Comment by LuxarPL** [comment]
![pei](https://user-images.githubusercontent.com/10651703/51407693-e259fc00-1b5c-11e9-9553-9c27adbf5bb8.png)
Windows 10, both multiplayer and singleplayer

**Comment by SDGNelson** [comment]
Could you try validating the game files please? (Steam > Unturned > Properties > Local Files > Validate Game Cache)? There was a similar issue reported earlier where it looked like some of the values were not being read properly

**Comment by Daniil1288** [comment]
@SDGNelson, 456MB was redownloaded, yet the bugs are still there:
![image](https://user-images.githubusercontent.com/1404955/51409141-ffe59080-1b71-11e9-89a4-edee9e4c2584.png)

**Comment by baranmod** [comment]
can approve, validating doesn't fix sea level, no landscape bugs

**Comment by SDGNelson** [comment]
Interesting, it looks like the data issue is related to a change in .NET 4.6's float.TryParse implementation: it won't parse the decimal point, instead expecting a comma. Might release an update which simply reverts the .NET version.

Tracking down the landscape issue will be tricky because there are so many variants (forward + deferred + gfx options), will see if anything changed in the unity default shaders.

**Comment by SDGNelson** [comment]
Comparing all built-in terrain shaders from 5.5.3f1 with 2017.4.6f1 the only difference is added 'noinstancing' pragma, so we'll try that to start with in the next patch.

**Comment by baranmod** [comment]
Apparently landscape is still here but is not visible, also there is somehow duplicated sea levels. I can lower sea level but still swim all over the map in some kind of a fog-sea :D
![image](https://user-images.githubusercontent.com/14231707/51410033-17ba1600-1b6c-11e9-8982-f67506bb6a56.png)

**Comment by Daniil1288** [comment]
The maps seem to be... hm... sunk, let's put it that way.
Flew back a bit:
![image](https://user-images.githubusercontent.com/1404955/51410039-7daa9b80-1b74-11e9-8f4a-9cba1d7dacfa.png)
Flew forward a bit:
![image](https://user-images.githubusercontent.com/1404955/51410017-74b9ca00-1b74-11e9-8dd1-b81ef278fe6e.png)

**Comment by SDGNelson** [comment]
Hmm after loading one of the maps with raised sea levels could you post the output_log.txt please? My guess is that some sort of content is throwing an exception during loading which disrupts creating the sea level.

**Comment by SDGNelson** [comment]
Ohhh wait nvm it's the water volumes because they load using float.tryparse from the devkit level file

**Comment by SDGNelson** [comment]
3.28.0.1 is now up! Fingers crossed that sorts everything out

**Comment by baranmod** [comment]
seems all good from first sight

**Comment by SDGNelson** [comment]
Even the terrain visibility? Phew

**Comment by educatalan02** [comment]
It's working perfectly for me.

If I find errors in my community I will comment here. Since they all have missed the alarms because they did not damage the weapons.

**Comment by Daniil1288** [comment]
Should I close this for now, everyone?

**Comment by SDGNelson** [comment]
Awesome! Thanks guys, I'll close it
