### ISSUE TITLE
Objects is white in night

### ISSUE THREAD

**Issue by TheCubicNoobik** [SmartlyDressedGames/Unturned-3.x-Community#533]
![image](https://user-images.githubusercontent.com/37713088/51413806-c06e7280-1b78-11e9-8a51-b09b06b18cd8.png)

Hawaii:
![image](https://user-images.githubusercontent.com/37713088/51413908-180cde00-1b79-11e9-8c09-1d0d7ba44966.png)

Greece:
![image](https://user-images.githubusercontent.com/37713088/51414172-1c85c680-1b7a-11e9-8405-d9ec45e96419.png)

France:
![image](https://user-images.githubusercontent.com/37713088/51414234-61116200-1b7a-11e9-81db-f098c15f4fd3.png)

Maybe others

**Comment by SDGNelson** [comment]
I should have followed my own guide! Looks like the color mode was reset in the curated maps unity project when I re-exported them the other day. I'll re-build them and can upload without a patch version.
