### ISSUE TITLE
There are some issues with placing barricades

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#536]
I got one barricade which can only be placed when rotated 180~ degrees for some reason. I though that I failed to re-bundle it somehow, however today I got reports that some players can't place beds too in various situations and its pretty similar issue. If I am rotating bed it won't be able to place in various angles. So I thought it might be something with unturned itself and not only my mod?

![image](https://user-images.githubusercontent.com/14231707/51426674-9491d200-1bf6-11e9-9651-0c65dce9835c.png)
![image](https://user-images.githubusercontent.com/14231707/51426677-99ef1c80-1bf6-11e9-9fbf-69dd4c7a3e6a.png)
![image](https://user-images.githubusercontent.com/14231707/51426684-b3906400-1bf6-11e9-8e7e-d101a82da53f.png)
![image](https://user-images.githubusercontent.com/14231707/51426740-90b27f80-1bf7-11e9-98d0-1fbb3e4a14c4.png)
![image](https://user-images.githubusercontent.com/14231707/51426742-9b6d1480-1bf7-11e9-9a1a-242ab82f5148.png)

**Comment by themisfitgames** [comment]
Same issue noticed for me as well, I had a few staff members approach me about bedrolls not wanting to be placed next to lockers in a pathway or simply in any hallway in a base after they built their bases on our temp vanilla pvp server. Only way I was able to place is if I ascended to the top of the base, placed the bedroll, and level edited to where the staff member wanted it.

**Comment by SDGNelson** [comment]
With the terrain in-particular I believe there was a change in unity so that it's more precise / same code path as mesh colliders, so that could explain some changes on that surface.

Experimenting myself on a server using vanilla barricades it does seem more finicky than it used to be, but it's not forcing me to rotate 180 degrees. I'll see about giving the overlap tests some wiggle room so that it doesn't have to be exactly perfect.

Is it primarly custom barricades with the issue? In which case I'd suggest tuning the offset values so that the collider isn't intersecting anything while placed.

**Comment by SDGNelson** [comment]
I was wrong about the overlap tests: they aren't used for static objects at the moment. I'll tune the bedrolls in particular however

**Comment by baranmod** [comment]
tried changing offset and also tweak colliders, rebundle on unity 4.18 - didn't solve the issue.

**Comment by SDGNelson** [comment]
If it's a bed it might be working now that the .2 patch is out, the bedrolls weren't as finicky any more

**Comment by baranmod** [comment]
nah, its simple square, big barricade.

**Comment by SDGNelson** [comment]
It's too bad the game doesn't currently better explain the exact reason it doesn't want to place. Is it only with your custom big square barricade? Wasn't happening for me with the vanilla freeform big square barricades.

Double-checking the freeform placement code I wonder how similar the radius and offset values are? Radius may have to be lowered at least 0.2 less than offset.
