### ISSUE TITLE
Charge mods doesn't detonate

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#537]
Not sure why but I can't detonate any charges I export from unity. Tried to export without any changes from example package - still the same. Demolition charge works without problems though. I can target them with detonator but when I try to detonate them - nothing happens.

**Comment by SDGNelson** [comment]
Just to be safe considering 3.28 I gave this a test with the vanilla detonator + charge in singleplayer and multiplayer, working properly as a point of reference.

It lets you select the detonator with right-click, but when you left-click nothing happens? Not even the explosion effect? Looking at the code there is one sanity check that the charge is tagged "Barricade", also would be worth double-checking that the .dat is mostly identical e.g. explosion effect is set.

**Comment by baranmod** [comment]
Just changed .dat values to exactly the same as demolition charge's and double checked tags/layers, seems all good (I bundled it from example package). Still the same issue. And yes, it does let me select charge itself but when I  left-click - nothing happens. If I select multiple charges (vanilla + modded) - vanilla will explode and modded will still be there

**Comment by baranmod** [comment]
also, didn't change anything with colliders too but for some reason I can't destroy it

**Comment by baranmod** [comment]
![image](https://user-images.githubusercontent.com/14231707/51430027-ccf8d680-1c1d-11e9-9661-10938e64c01a.png)

**Comment by SDGNelson** [comment]
The unable to destroy it must somehow be related. Do you get any exceptions in the log file when punching it? Are you able to salvage it?

**Comment by SDGNelson** [comment]
I'll rebuild the vanilla master bundle as well to ensure I'm working with the same files

**Comment by baranmod** [comment]
ahhh, false alarm. Apparently I was using the wrong version of unity 2017.4.16 instead of .18. Rebundled and it works fine :D sorry for disturbing..

**Comment by SDGNelson** [comment]
Was just about to post that I have absolutely no clue! (Worked fine for me after rebuild as well.)
Interesting that .16 to .18 made a big difference like that. I'll have to keep that in mind, in general it seems like Unity is pretty good about asset bundle compatibility even back to like 2017.2.
