### ISSUE TITLE
Receiving a SIGABRT when launching Unturned servers with map set to France and Russia

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#538]
When I launch my Unturned servers with either Russia or France as the map, I receive a SIGABRT and the server crashes. This started happening right after the Unturned update 3.28.0.1. I have already checked all of the logs and have found nothing to help me. I am also using Ubuntu 14.04. Here is the Stacktrace:

Stacktrace:

  at (wrapper managed-to-native) UnityEngine.TerrainData.Internal_SetAlphamaps (int,int,int,int,single[3]) <0x00004>
  at (wrapper managed-to-native) UnityEngine.TerrainData.Internal_SetAlphamaps (int,int,int,int,single[3]) <0x00004>
  at UnityEngine.TerrainData.SetAlphamaps (int,int,single[3]) <0x00073>
  at SDG.Unturned.LevelGround.load (uint16) <0x02088>
  at SDG.Unturned.Level/<init>c__Iterator0.MoveNext () <0x00128>
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator,intptr) <0x00046>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object_intptr (object,intptr,intptr,intptr) <0x0004b>

Native stacktrace:

        /home/steam/creativerpfrance/Unturned_Headless_Data/Mono/x86/libmono.so(+0x900c9) [0xf62600c9]
        [0xf77d6420]
        [0xf77d6440]
        /lib/i386-linux-gnu/libc.so.6(gsignal+0x47) [0xf74d2687]
        /lib/i386-linux-gnu/libc.so.6(abort+0x143) [0xf74d5ab3]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x8600819]
        /home/steam/creativerpfrance/Unturned_Headless_Data/Mono/x86/libmono.so(+0xc1b29) [0xf6291b29]
        /home/steam/creativerpfrance/Unturned_Headless_Data/Mono/x86/libmono.so(+0x245b9) [0xf61f45b9]
        [0xf77d6420]
        /lib/i386-linux-gnu/libc.so.6(+0x12ef5a) [0xf75d2f5a]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x8d33bfd]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x8f4febb]
        [0xa68c10cb]
        [0xa68c0f5c]
        [0xa68bc089]
        [0xa613d6d9]
        [0xe93c74cf]
        [0xe93c7574]
        /home/steam/creativerpfrance/Unturned_Headless_Data/Mono/x86/libmono.so(+0x284e8) [0xf61f84e8]
        /home/steam/creativerpfrance/Unturned_Headless_Data/Mono/x86/libmono.so(mono_runtime_invoke+0x66) [0xf62fdf28]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x85c0be8]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x862582d]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x85f56b8]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x82185c1]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x84425b8]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x842af38]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x807ae78]
        /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0xf74bdaf3]
        /home/steam/creativerpfrance/Unturned_Headless.x86() [0x8083909]

Debug info from gdb:

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

**Comment by SDGNelson** [comment]
Thanks! Fortunate that there's an obvious stack trace like that. My initial reaction was that should not even be called on the server side, before remembering that some old code uses it to lookup the impact physical material. Ideally for today's update I should remove the usage of terrain splatmaps on the dedicated server.

**Comment by Ascivv1** [comment]
Awesome! Should we expect this error to be fixed today?

**Comment by SDGNelson** [comment]
I expect so, but I can't be 100% certain yet. Will post back here soon after I dig a bit deeper into this code.

**Comment by Ascivv1** [comment]
Ok. Thank you!

**Comment by Ascivv1** [comment]
Thank you! I will test this in a few hours on my servers and make sure this works.

**Comment by Ascivv1** [comment]
I still seem to be getting the same error after the update. Any reason why?

**Comment by SDGNelson** [comment]
On version 3.28.0.2 - is it a different stack trace?

**Comment by Ascivv1** [comment]
It is the same stacktrace.

**Comment by SDGNelson** [comment]
I think that server must not be on version 3.28.0.2 yet then, because LevelGround.load won't be calling SetAlphamaps on the dedicated server

**Comment by SDGNelson** [comment]
Any luck forcing an update? Or hopefully a new stacktrace?

**Comment by educatalan02** [comment]
I'm using 16.04 
Stacktrace:


Native stacktrace:

        mono() [0x49ff2f]
        mono() [0x4f390e]
        mono() [0x426c19]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f58cc3d7390]
        mono() [0x5e8100]
        mono() [0x5e886f]
        mono() [0x5ea8e7]
        mono() [0x5eca95]
        mono() [0x5dfd7e]
        mono() [0x5ce716]
        mono(mono_array_new_specific+0x43) [0x5adcf3]
        mono() [0x41e042]
        mono() [0x49f103]
        mono() [0x4f2b0d]
        [0x405ae603]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

./start.sh: line 42: 14974 Aborted                 mono RocketLauncher.exe $INSTANCE_NAME

**Comment by Trojaner** [comment]
@educatalan02 
The error you posted is not related to Unturned. It is related to RocketLauncher.exe (you must downgrade your mono to use it).

**Comment by educatalan02** [comment]
Ok then I'll delete It

**Comment by SDGNelson** [comment]
Great!
