### ISSUE TITLE
Server Loading Errors

### ISSUE THREAD

**Issue by themisfitgames** [SmartlyDressedGames/Unturned-3.x-Community#542]
Hello Nelson,

Just dropping off some errors from the logs to you to take a look at in your spare time as I've noticed on multiple dedicated machines that I'm managing that are running Windows 2010 and 2016 which are experiencing the same issues.

Please keep in mind these issues are occurring on vanilla servers running no workshop content.

_NotSupportedException: Missing 'Vehicle' GameObject
SDG.Unturned.VehicleAsset..ctor (SDG.Unturned.Bundle bundle, SDG.Unturned.Data data, SDG.Unturned.Local localization, UInt16 id)
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes)
System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes)
System.Activator.CreateInstance (System.Type type, System.Object[] args)
SDG.Unturned.Assets.loadFile (ScannedFileInfo file)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.Assets:loadFile(ScannedFileInfo)
SDG.Unturned.<loadAllFilesScanned>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)_

_NotSupportedException: Missing effect gameobject
SDG.Unturned.EffectAsset..ctor (SDG.Unturned.Bundle bundle, SDG.Unturned.Data data, SDG.Unturned.Local localization, UInt16 id)
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes)
System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes)
System.Activator.CreateInstance (System.Type type, System.Object[] args)
SDG.Unturned.Assets.loadFile (ScannedFileInfo file)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.Assets:loadFile(ScannedFileInfo)
SDG.Unturned.<loadAllFilesScanned>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)_

Hopefully this helps, 

I was also hoping to speak with you privately about an issue, is there a way I can get in contact with you?

Thanks!

**Comment by SDGNelson** [comment]
I suspect there is somehow some workshop content, since my test process ensures that the vanilla servers load without missing assets. If you can post the log from: %USERPROFILE%\AppData\LocalLow\Smartly Dressed Games\Unturned it should explain which assets are missing files

For private issues you could email nelson@smartlydressedgames.com

**Comment by SDGNelson** [comment]
Looks like I was wrong: there are quite a few missing asset errors in the log, all related to France. I wonder if you could run the Validate steamcmd and see if it repairs some files?

**Comment by themisfitgames** [comment]
Perfection, thanks for the assistance!
