### ISSUE TITLE
Non-uniform effect scaling option

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#544]
I've previously requested effect scaling option (#376), but it's limited to uniform scale. My attempts to bump that thread were ignored so I'm trying again in a new one.

Please add non uniform option

**Comment by Zinidia** [comment]
I'm surprised Nelson hasn't already added this.

**Comment by SDGNelson** [comment]
Will add for the .3 patch
