### ISSUE TITLE
Unity 2017

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#55]
What are the current plans about migrating to Unity 2017? Would it be done at all? If yes, when might it happen?

(Plugin developers really need it for the much newer mono version as many features and libraries depend on >= .Net 4)

**Comment by Kr4ken-9** [comment]
+1
.NET 3.5 is nothing but pain

**Comment by TrueThat** [comment]
+1
Maybe improve API while at it ;)?

**Comment by aviadmini** [comment]
- .Net 4.6 support in Unity 2017 is still experimental 
- we all remember what *awesome performance issues* happened when Nelson migrated to 5.6 once

But yep, that migration would be extremely desirable. Having to resort to some really obscure solutions every time you could've used .Net 4 features is depressing

**Comment by SDGNelson** [comment]
Unfortunately there were still some unresolved issues last time I tried updating a couple months ago which I didn't find a workaround for. My notes say that there were linear/gamma lighting issues obvious at night on all platforms and build times were very slow.

**Comment by cartman-2000** [comment]
@aviadmini Yes, I remember when Unity 5.6 was tried, pretty much all of the players on my own server's had about a 30-60% hit to fps performance, and it broke some old legacy models used in workshop mods, one's that are still using Unity 4.x models(Causing a trace on server load, breaking the server loading process.).
