### ISSUE TITLE
Particles are visible only on landscape

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#554]
Not sure if its a bug or its supposed to be like that for some reason but particles are only visible on landscapes and water if water quality is set to lowest. Pretty sure thats because of shaders (none of in-built particle shaders works). The only shader that works well is standard (cutout rendering mode)

**Comment by SDGNelson** [comment]
Closing for the meantime, but I'm curious to hear how that worked out. It should be possible to use any shader included in the asset bundles.
