### ISSUE TITLE
Option to hide / disable buttons

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#556]
Basically i'm requesting a way to hide specific buttons from the screen,
It'll be useful when I want to make a UI with like 5 buttons for x player and one with 2 buttons for y player so instead of making 5 effects I can just hide the buttons I don't need instead.
You can just add a string array named buttonsToHide and check for each button if the array contains the button name.
Thanks, Roy.

**Comment by themisfitgames** [comment]
That would be a good idea and possibly set it permission based at some point or something. Kudos for the request.

**Comment by SDGNelson** [comment]
Added for 3.29!

The function is sendUIEffectVisibility. You pass in the name of a child of the UI effect prefab (e.g. Button1), whether its GameObject should be Active or not (visible), and the int16 key/identifier of the effect instance.
