### ISSUE TITLE
Some players have very high ping in Linux based server

### ISSUE THREAD

**Issue by TLingC** [SmartlyDressedGames/Unturned-3.x-Community#557]
Hello, I encountered a problem that some players will have some strange high-ping issues when they are connected to the server, but this is randomly and not to all players in the same server.

It's about 40ms-60ms outside of the server(using steam server browser or in-game browser), but when player join in the server, he may have 300ms-500ms, and it's only some specific players who have this problem. For example, when a server has 5-6 players, only one player has this problem, while the ping of other players are normal.

Additionally, memory, network, and CPU are ample, Unturned Windows server is also installed on the same server(Windows is base os, running Ubuntu in Hyper-V), but they don't have any problems.
I've tried to install the server as Linux(Ubuntu), but the problem remains.

I wasn't sure what the problem was, so I decided to sort it out one by one. I am using Ubuntu 16.04, with RocketLauncher.exe:
> mono RocketLauncher.exe [SERVER_NAME]

**Comment by SDGNelson** [comment]
If I understand correctly, the issue is purely the difference between out-of-game ping and in-game ping?

This is likely because the out-of-game ping is from another socket on another thread, so it should just be the network delays, whereas the in-game ping is from the game thread so it takes into account the server processing delay.

**Comment by TLingC** [comment]
@SDGNelson No, I checked this problem in the past few days. Finally I add
```
export MONO_IOMAP=all
```
to my start script and it seems that the problem has been solved.

btw, I am using docker to run Unturned server, does memory allocated to the container may affect the ping? Though the memory usage does not reach 100%.

**Comment by SDGNelson** [comment]
Interesting! I'm glad you managed to find a solution. Sorry I wasn't keeping up with the GitHub issues last week.

You're right at as long as the memory usage doesn't reach 100% the game should be fine in your container. The main factors which impact the ping would be its network accessibility (e.g. in a fast datacenter), and how many ticks per second the server can be run at.

**Comment by SDGNelson** [comment]
Externally no, but in the console you can run the vanilla Debug command for a few stats on how the server is performing.

**Comment by SDGNelson** [comment]
Both would ideally be at 100%, but probably not in practice. Targets for both are 50, update is processing all network requests, and tick is processing physics and client inputs.

**Comment by TLingC** [comment]
@SDGNelson so I should check my network if *updates per second* is lower than 50%?

**Comment by SDGNelson** [comment]
Wouldn't be issue with your network, just the speed at which the game is churning through requests. It's similar to your FPS on the client, i.e. if your target FPS was 50 and it was at 80% then you'd only be getting 40 FPS.

Linux compatibility has been kind of hit-or-miss depending on factors like the distro and how unity is feeling, but there are lots of networks hosting successfully. I would recommend auto-restarting the app once per day though. Which Linux distro are you using?

**Comment by TLingC** [comment]
I am using ubuntu 16.04, currently testing on CentOS 7.
