### ISSUE TITLE
Low Cal Ranger Ammo Box won't disappear after used

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#562]
All the crates / boxes Will be gone once they are used to refill something.
We noticed that this Low Caliber Ranger Ammunition Boksz(119) won't disappear after using it.
Proof with PIC:  https://cdn.discordapp.com/attachments/486554295970299904/541314930863898655/unknown.png
(tested on clean server without any modifications)

**Comment by SDGNelson** [comment]
Tested in multiplayer on a vanilla server in a few different scenarios e.g. multiple boxes with only a few bullets left, off-by-one box, etc but wasn't able to replicate.

What were the exact steps, what were you refilling?

**Comment by evermoreservers** [comment]
We rechecked.
This bug is only happening with Hell's Fury.
(Tested with 1-2 ranger gun + nykorev, they are ok)

**Comment by SDGNelson** [comment]
Oops! Thanks Evermore. This bug and a related bug should be fixed in this week's update.
