### ISSUE TITLE
Issue with symbol "₽"

### ISSUE THREAD

**Issue by BraianKant** [SmartlyDressedGames/Unturned-3.x-Community#565]
Hello there! After some latest updates symbol ₽ stopped showing in the chat. When I print ₽ I recieve invisible space... Please fix :P

**Comment by SDGNelson** [comment]
Tested on vanilla and it seems to show up okay: https://i.imgur.com/vdfRI7J.png
Since the UTF-8 encoding is 3 bytes it might end up wonky if your message has >85 of them?

**Comment by BraianKant** [comment]
No, just one symbol :P

**Comment by SDGNelson** [comment]
Did some additional tests on vanilla server and there weren't any issues with UTF-8 symbols including that one, so I'd suggest looking into whichever plugins are between your code and the ChatManager code that might be interfering.
