### ISSUE TITLE
Black textures on vanilla France

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#571]
After the 3.28.0.x updates there's black textures in several locations across the France map. You can see them better using a Military Nightvision.

EDIT:
I'm using Windows 7 x64

Paris:
![paris](https://user-images.githubusercontent.com/47387864/52347122-df4e7f00-2a29-11e9-9eb9-4cd35d4baaae.jpg)

Chateau de Versailles:
![chateau_de_versailles](https://user-images.githubusercontent.com/47387864/52347137-e83f5080-2a29-11e9-969a-9be6dba43d5f.jpg)

Pont Du Gard
![pont_du_gard](https://user-images.githubusercontent.com/47387864/52347148-eecdc800-2a29-11e9-8924-231cc03ea096.jpg)

Marseille:
![marseilles](https://user-images.githubusercontent.com/47387864/52347161-f68d6c80-2a29-11e9-88b8-13036a3e2e68.jpg)
**Here on the right, you can also see black textures on the railroad under the tunnel that goes to Marseille.**

Flamanville Power:
![flamanville_power](https://user-images.githubusercontent.com/47387864/52347188-05741f00-2a2a-11e9-84fb-bdd0932aa437.jpg)

(on the map) Unmarked island to the left of Contentin Arsenal:
![island_to_the_left_of_contentin_arsenal](https://user-images.githubusercontent.com/47387864/52347216-158bfe80-2a2a-11e9-8e55-4b78e32b7844.jpg)

**Comment by SDGNelson** [comment]
Thanks for the report! Useful catch with the nightvision: they weren't working properly with the nightvision fog which is why the appeared black. Will be fixed in the next update by using the proper shaders.
