### ISSUE TITLE
Locker Glitch

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#572]
(On servers with /tpa and-or cooldown on /home)

When you're looking in a Locker and you tp to somebody or /home while having a cooldown, and meanwhile you go back to the Locker, once you teleported and you didn't close locker's storage, you can manage the storage from the place you teleported to until you close it (like moving/taking/storing loot in the Locker)

**Comment by SDGNelson** [comment]
Received a report that this could be used to duplicate items, but neither them nor I could replicate it.

In the next update though it will close once you are too far away.
