### ISSUE TITLE
Players can see your gun from the other side of the wall if you go very close to it

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#574]
This is very old and common issue. I don't know how many people already reported it because I couldn't find anything about it.
Nelson, can't the player take a safety mode-like gun animation (similar to PUBG) when they're very close to a wall/structure with a gun in their hand?
This exposes the location of people especially on 3rd person servers.

**Comment by SDGNelson** [comment]
Unfortunately this is unlikely to change, but in 4+ each item has an animation when near to a wall to prevent clipping. (like PUBG as you mention)
