### ISSUE TITLE
Bug with Linux host npc

### ISSUE THREAD

**Issue by Kew1e** [SmartlyDressedGames/Unturned-3.x-Community#576]
Hi Nelson, I have a problem with npc. I keep the server in your game on the Linux operating system unthost.ru and I do not sell and do not sell npc, when, how, when 2 pumping stations work, and when 0. Ie, I want to buy something from them, but export is not removed and I don't get the item. On Windows, the server is working, I can give you a video of how it does not work, 1 video will be on Linux, and the second on the server of a friend for Windows
http://mega.dp.ua/file?source=19020615400561275075

**Comment by SDGNelson** [comment]
Most likely difference between Linux and Windows would be file capitalization. Linux file paths are case-sensitive, so if the XYZ.dat capitalization does not match the XYZ parent folder capitalization it won't find it.

**Comment by Kew1e** [comment]
I have already solved the problem, it was that many folders with the NPC were in Cyrillic, after I wrote in Latin everything worked! But somehow these NPCs worked with Cyrillic before.

**Comment by SDGNelson** [comment]
Glad that you found a solution! Thanks for letting me know about the Cyrillic issue: I'll also keep that in mind for similar reports in the future.

**Comment by Kew1e** [comment]
Thank you for your game and for answering to almost everyone))
