### ISSUE TITLE
Offbrand Hoodies

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#578]
Related: Hit with trophy for gold, silver and bronze corpse.

**Comment by GunTurned** [comment]
yes

**Comment by danaby2** [comment]
yes

**Comment by ComidaDePerro** [comment]
yes

**Comment by Th3God** [comment]
yes

**Comment by TheCubicNoobik** [comment]
yes

**Comment by ElSpyDero** [comment]
yes

**Comment by MoltonMontro** [comment]
The temptation to "yes" was weaker than the temptation to break the chain. Sorry guys, you failed me and yourselves.

**Comment by khakers** [comment]
I can’t believe you’ve done this

**Comment by Noobyfish** [comment]
yea

**Comment by danaby2** [comment]
yea

**Comment by GunTurned** [comment]
yea

**Comment by Th3God** [comment]
yea

**Comment by Johnanater** [comment]
yeah

**Comment by ComidaDePerro** [comment]
yea

**Comment by ElSpyDero** [comment]
yea

**Comment by MeedicBear** [comment]
yea

**Comment by TheCubicNoobik** [comment]
yea

**Comment by vresig** [comment]
yes

**Comment by Kenzim** [comment]
yes

**Comment by justboughtmarmalade** [comment]
would you shag me if i wore one of them @SDGNelson

**Comment by SirAdyUnleashed** [comment]
Actually, I'm really digging this idea. The point of exclusive cosmetics has always been, as I see it, to acknowledge and celebrate accomplishments of dedicated community members, as well as just resembling fun little easter eggs to enhance the player experience in an unexpected way. Thus, the implementation of these so-called "offbrand hoodies", COMMUNITY requested, may I emphasize, could definitely add a whole new layer of connection between the developer and his player base. The future looks bright for Unturned. Nelson is starting to further embrace our "meme" culture, and this would be quite a fun little addition that will certainly reward those of us who, for all these years, have been sticking around to his creation. I guess what I'm trying to say is... _yes_.

**Comment by Noobyfish** [comment]
haha yea I agree with sirady, no bias btw

**Comment by SDGNelson** [comment]
Both are good to go! Likely on the preview branch tonight. I'll put up a video to demo the TrophyAward_* skins which will be used for future contests. :)

**Comment by dragon-beast** [comment]
Yes

**Comment by MaxiorPL** [comment]
yes

**Comment by sLmpgn** [comment]
yes

**Comment by MeedicBear** [comment]
yes
