### ISSUE TITLE
Broken item textures

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#579]
The textures are broken for Binoculars and MRE.

**Comment by MeedicBear** [comment]
Can confirm
https://cdn.discordapp.com/attachments/324233420152504331/543644866857664522/unknown.png

**Comment by SDGNelson** [comment]
Thanks for the images! Kept an eye out for the past couple days to see if any similar item visuals were messed up. In the .1 patch today the Candy Bar, MRE and Binoculars should be resolved.
