### ISSUE TITLE
About the latest update

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#580]
I think you should consider this to be implemented, some plugins used the crates as virtual storages, and with this update it became impossible to be sure to create a crate in a safe area, since it can only be 20m from the player.

```public bool isStorageTrunk;
public bool CancelLongDistances = true (default);
public InteractableStorage storage;

(...)

public void closeDistantStorage()
{
    if (!this.isStoring || this.isStorageTrunk || (Object)this.storage == (Object)null || ((double)(this.transform.position - this.storage.transform.position).sqrMagnitude <= 400.0) && this.CancelLongDistances)
        return;

    this.closeStorage();
}

**Comment by SDGNelson** [comment]
Should be resolved in the .1 patch today. InteractableStorage now has a public member named "shouldCloseWhenOutsideRange" which defaults to false, and crate assets opt-in by setting "Should_Close_When_Outside_Range" to true.

**Comment by aviadmini** [comment]
Why would you create a crate for that? It's not virtual anymore, more like access a remote crate oof

**Comment by Trojaner** [comment]
I can not confirm this issue. My Vault plugin which uses virtual crates works the same as before the update. Nothing broke for me.

**Comment by rube200** [comment]
https://youtu.be/0IKmDeWpmEg This is what happened to me with this version.

**Comment by SDGNelson** [comment]
May depend if plugin is spawning one of the vanilla crates. The plugin can either set shouldCloseWhenOutsideRange to false on a vanilla crate when spawned, or create a custom crate asset with Should_Close_When_Outside_Range set to false.
