### ISSUE TITLE
One way hole in border on Washington

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#581]
I had reports that players were outside of the border on my server and there seems to be a one-way hole on Washington's border near Scorpion-7.

I uploaded a demonstration on Youtube.
https://youtu.be/OxQePAdjiGw

Also tried on pure vanilla and was able to do it.

**Comment by SDGNelson** [comment]
Thanks! Surprised, only change related to player collision is the overlap resolution, but overall that fixed more problems than it caused. Will clamp the player's position within the level bounds for the .1 patch.
