### ISSUE TITLE
what happens when vehicle disappear when you in it

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#582]
https://cdn.discordapp.com/attachments/520230067004243968/543851490691907586/unknown.png
This picture is supposed to show what happens in case the vehicle disappears when you sit in it.
Looks similar as my old report with Jet, when you crashed while having a lot of item.
But in this case, when player quit and his vehicle disappear, anyone who sit on the other seats Will get this screen and crash.

**Comment by Trojaner** [comment]
Are you using any plugins?
If yes, the plugin author should adjust it so it kicks all passengers out of the vehicle before getting deleted.

**Comment by evermoreservers** [comment]
Yeah, i use and we Will adjust it like that, i just felt like i should report it since it is similar to the Fighter Jet bug i reported a while ago.
Thanks for your tip anyway!

**Comment by SDGNelson** [comment]
Trojaner is correct that the plugin should call forceRemoveAllPlayers before destroying the vehicle.
