### ISSUE TITLE
Mannequins again...

### ISSUE THREAD

**Issue by Ankumo** [SmartlyDressedGames/Unturned-3.x-Community#583]
Hello. After last update (huge one) mannequins were broken, i've missed that issue and dunno what exactly was wrong, but since 3.28.0.0 i can't apply BarricadeManager.tryGetInfo method to mannequin transform, it just returns false, and Transform.GetComponent method returns null as well if you'll try to get InteractableMannequin object. Other barricades seems to work fine with both methods.
Here is the code i've used to find out where it breaks up in my Rocket Plugin.
`
        public void ExecuteTtt(IRocketPlayer caller, string[] command)
        {
            UnturnedPlayer player = (UnturnedPlayer)caller;

            if(!Physics.Raycast(player.Player.look.aim.position, player.Player.look.aim.forward, out RaycastHit hit, 10f, RayMasks.BARRICADE))
            {
                UnturnedChat.Say(player, "no barricade raycast", Color.red);
                return;
            }

            if(!BarricadeManager.tryGetInfo(hit.transform, out byte x, out byte y, out ushort plant, out ushort index, out BarricadeRegion r))
            {
                UnturnedChat.Say(player, "no barricade info", Color.red);
                return;
            }

            InteractableMannequin im = hit.transform.GetComponent<InteractableMannequin>();

            if(im == null)
            {
                UnturnedChat.Say(player, "no manneqiun raycast", Color.red);
                return;
            }
            //we should get here if everything is OK
            UnturnedChat.Say(player, "mannequin found", Color.magenta); 
        }
`
It was working just fine before the update.

P.S. i dunno what's wrong with github code inserting

**Comment by SDGNelson** [comment]
Related to what I believe is a fix in raycast handling (Unturned's game code had to be adjusted as well). Your hit.transform is likely one of the bone transforms, whereas tryGetInfo expects the root transform. Would suggest using helper function DamageTool.getBarricadeRootTransform. Let me know if that takes care of it!

**Comment by Ankumo** [comment]
Yep, it's working now. Thanks! But why it was working before the update? Is that related to new unity version or mannequin fixes?

**Comment by SDGNelson** [comment]
Awesome! Before the update it would return the root transform because the root transform had a rigidbody as a workaround, but that was not ideal performance-wise so I fixed all cases to remove all the extra rigidbodies from barricades.
