### ISSUE TITLE
Buildable can not be placed

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#584]
Here is a video which shows that the player can not place pillars at that position for some reason.
It is very random where it comes, we met it already a few times, but right now we talk about a fresh wiped server a day after the 3.29.0.0 (last announced) update.

https://youtu.be/UkMwztbYNcE

The reporter noted to me:
"About the bug: I thinks random and it started when Nelson made "anti doublestacking"(buildables)"

These are his words, i would mention here, he might talks about an update a month or more ago, when you fixed something about the buildables to avoid doublestacking.

**Comment by SDGNelson** [comment]
Fixed up some potential causes for the next update, and carried that logic over to barricades now as well. Will leave this open so we can see if it's fixed after the update.

**Comment by evermoreservers** [comment]
IF you have nothing more to do here, can close this Issue.
My admin checked a reported position and player could place building there after the update. (Seems fixed)

**Comment by SDGNelson** [comment]
Woohoo! Feel free to re-open or comment if it crops back up 🤞
