### ISSUE TITLE
Content Error

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#585]
Hello Nelson,
I've open a server with Windows Server 2016 and the server crash sometimes.
When the server loads game content It prints errors.

Here's the log.
[Server_pvp4_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2862345/Server_pvp4_Prev.log)

**Comment by Charterino** [comment]
You have to update your mods.

**Comment by educatalan02** [comment]
The server got 2 HUD's so is not mod problems. Because the error comes when loading Unturned Content.

**Comment by SDGNelson** [comment]
I'm inclined to agree with Charterino that it's likely to do with workshop content. Vanilla game content does not have any loading errors on client/server, so these asset loading errors are likely custom ones.
