### ISSUE TITLE
UnityPlayer.dll crash on windows2008r2 Enterprise

### ISSUE THREAD

**Issue by zch12138** [SmartlyDressedGames/Unturned-3.x-Community#588]
Here is the message from system: https://gist.github.com/zch12138/f56b908d5874e64a46c83fa3dcc7a5f8
Seems that there is no error log from unturned.

Waiting for help, thanks

**Comment by SDGNelson** [comment]
Looking online I see reports of this BEX64 message for lots of other software, and a few posts are saying it may help to run it in compatibility mode. (Especially since you're using an older windows server) I'd suggest looking around for this BEX64 issue.

**Comment by themisfitgames** [comment]
Need an updated Windows 2016 version @zch12138 ?
