### ISSUE TITLE
Option : Cam_Driver_Offset

### ISSUE THREAD

**Issue by ImIveooo** [SmartlyDressedGames/Unturned-3.x-Community#589]
Hi Nelson, I'm contacting you to find out if you could make sure that the "Cam_Driver_Offset" is not only applied to the driver of the vehicle but to all those present inside the car.

**Comment by SDGNelson** [comment]
Curious, I wonder what the use case is? Looking at the code it was added to raise the 1p view height, but I don't remember what it was originally used for either.

**Comment by ImIveooo** [comment]
We use it so that the camera is no longer in the ceiling.

**Driver**
![Avant](https://i.imgur.com/qtz2CvD.jpg)

**Passenger**
![Arrière](https://i.imgur.com/f6t9sS0.jpg)

**Comment by SDGNelson** [comment]
For the next update I've added Cam_Passenger_Offset which is applied to all passengers, including the driver. Cam_Driver_Offset still exists, and is added to Cam_Passenger_Offset.
