### ISSUE TITLE
tellVehicleDestroy - Kick players [White screen]

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#59]
for (int i = 0; i < vehicle.passengers.Length; i++)
                            {
                                if (vehicle.passengers[i].player != null)
                                {
                                    Vector3 point;
                                    byte angle;
                                    vehicle.getExit(byte.Parse(i.ToString()), out point, out angle);
                                    VehicleManager.instance.channel.send("tellExitVehicle", ESteamCall.ALL, ESteamPacket.UPDATE_RELIABLE_BUFFER, new object[]
                                        {
                                        vehicle.instanceID,
                                        byte.Parse(i.ToString()),
                                        point,
                                        angle,
                                        true
                                        });
                                }
                            }
This code should solve it, again just for making life easier (:

**Comment by SDGNelson** [comment]
askVehicleDestroy and askVehicleDestroyAll now kick all passengers in case of being called on vehicles with passengers.
