### ISSUE TITLE
Can u add this?

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#591]
OnPlaceBarricadeRequest - no need desc.
OnPlaceStructureRequest - no need desc.

Add some event to when the server sends this package (ESteamPacket.CONNECT) I can get it easier, because capturing all packages makes the game a little slower, I've had some lag experiences lately

**Comment by SDGNelson** [comment]
"no need disc" ?

**Comment by rube200** [comment]
Ups xD

**Comment by SDGNelson** [comment]
In the next update added:
onDeployBarricadeRequested
onDeployStructureRequested
