### ISSUE TITLE
Bug with OnBarricadeSpawned

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#592]
Hello! For first time i would like to report a bug with coding about barricades.
The code below Works well with structures but when its used on barricades, it has a weird bug:
When player place a barricade, it appears at him, BUT he can go through it.
Supposed to not let the player place the buildable, but he just can. It disappears from his inventory, and not only him but other players see that barricade too and can go through it.

> private void OnBarricadeSpawned(BarricadeRegion Reg, BarricadeDrop drop)
{
    try
    {
        if (!drop.model.position.CheckZone())
            return;
        BarricadeManager.tryGetInfo(drop.model.transform, out byte x, out byte y, out ushort plant, out ushort index, out var region);
        region.barricades.RemoveAt((int)index);
        if (plant == ushort.MaxValue)
            BarricadeManager.instance.channel.send("tellTakeBarricade", ESteamCall.ALL, x, y, BarricadeManager.BARRICADE_REGIONS, ESteamPacket.UPDATE_RELIABLE_BUFFER, (object)x, (object)y, (object)plant, (object)index);
        else
            BarricadeManager.instance.channel.send("tellTakeBarricade", ESteamCall.ALL, ESteamPacket.UPDATE_RELIABLE_BUFFER, new object[4]
            {
          (object) x,
          (object) y,
          (object) plant,
          (object) index
            });
    }
    catch (Exception ex) { Logger.LogException(ex); }
}

**Comment by SDGNelson** [comment]
Related to when the onSpawned delegate is used. It's meant for reacting to barricade placement, not preventing it, so you are blocking it after it's already been spawned for everyone.

Similar issue has been posted as well (#591), so I'll see about adding an event to prevent the placement!

**Comment by SDGNelson** [comment]
In the next update added:
onDeployBarricadeRequested
onDeployStructureRequested

**Comment by Johnanater** [comment]
Yay! I was needing this for a plugin as well! :D
