### ISSUE TITLE
A good chunk of objects can be abused to go inside of them

### ISSUE THREAD

**Issue by Noobyfish** [SmartlyDressedGames/Unturned-3.x-Community#593]
Me and Danaby2 were testing some objects on vanilla maps such as russia and his arena map canyon arena to find out what caused this to happen to me while we were playing, In the actual moment I was merely jumping away from gunfire and just walked out of bounds: https://i.gyazo.com/7f206c767315dad357024bc26ece71ad.mp4
Danaby and I discovered this doesnt only affect his objects but any objects that is angled or has a slanted underside.
Here is another example from his map that I found
https://i.gyazo.com/4b3c130dfcd052a14bf4a618d0a5f415.mp4
While testing this on objects of all shapes and sizes danaby and I found some pretty nasty spots that could very easily be abused in survival.
Such as this boulder on russia:
![image](https://user-images.githubusercontent.com/20568317/52992795-da9da980-33df-11e9-82bb-b850a0ddcb32.png)
https://i.gyazo.com/0245bd49ce493df14eb9a3b0c3dfc5d7.mp4
and the russian airport
https://i.gyazo.com/cbd77383d61c5f8cd364bc3079d650d1.mp4
Inside both of these spots you can still shoot outside and build inside.

We believe this to be caused by an error in the overhead collision check when you stand up from proning or crouching because after furthur testing and recreation of bug we found that it mainly happens after coming up from a crouch or prone stance. This bug can be abused on almost any angeled surface. This check doesnt even exist on playerclip volumes.

The steps of recreation differ depending on the object, For example for the airport you go as close as you can to the underside of the escalator as you can while standing then go into the prone state, go forward very slightly (barely a keypress) then you stand up, now you can walk all around the object as you please. You can even do this on the eiffel tower on france!

This bug is very easy to recreate once you can get the motions down pact and I can provide more info about how I did the ones in the gifs if needed. If you use plates even more areas can be reached and broken into, in theory.

**Comment by danaby2** [comment]
This can also be done with fridges

https://i.gyazo.com/abd926961fe8882997e20ed3b4132556.mp4

thats all i had to add thx for listening to my ted talk

**Comment by SDGNelson** [comment]
Yikes! Heart skipped a beat thinking we might need to roll back the overlap change, but it seems limited to changing stance? Looking at the code for stance space check it's pretty stupid, so it should be a straightforward fix.
