### ISSUE TITLE
Legal WH - Look through wooden walls

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#595]
It is started to be more than annoying that people instead of raiding everywhere and spending their time with the risk of finding a good room / an empty one.. they can simply just look into bases through Woodén walls.
https://youtu.be/KWYtheswsYg

**Comment by SDGNelson** [comment]
Near clip plane tuning is about as small as it's going to get, balanced that a while ago trying to increase the player capsule radius and find a good balance of near/far clip plane.

For the structure pillars and walls in particular I'll see about putting an extra plane halfway inside to prevent abusing this.
