### ISSUE TITLE
Shadowstalker MK II Easter Egg bug

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#596]
https://youtu.be/dyFqo2KbQy0?t=97
Be aware of loudness(didnt check with sound)
(at the time i put the link to start, they are getting teleported in a few seconds)

This video is supposed to explain the bug but lemme just say it:
When you are doing the easteregg on russia map, and placing a horde beacon at the red soul stone, it supposed to teleport most of you to the Pirate Boss once & to the Scorpion 7 (inside) or whatever its name.
So in this video you see, they are teleported to the interior but immediately getting out to Camp Oleksandr..
This bug has been found just now, can't be sure when i'm saying it is after the latest 2 big update.

**Comment by SDGNelson** [comment]
Whoops! Definitely caused by the change to clamp players inside the map bounds: dumb on my part I forgot that the Scorpion-7 base was outside that border. I'll do something about this for the next update.

**Comment by SDGNelson** [comment]
For the moment disabled that movement clamp
