### ISSUE TITLE
Notice: Preview branch updated with .NET 4.6

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#606]
Will likely release on Friday, let me know if you run into any issues!

**Comment by SDGNelson** [comment]
https://www.youtube.com/watch?v=3faWnacTlLI&feature=youtu.be

**Comment by TheCubicNoobik** [comment]
https://youtu.be/qeCrRl1q_jg

**Comment by SDGNelson** [comment]
@TheCubicNoobik It's a pretty wacky bug: after the 2017.4 LTS update for whatever reason toggling the stock temporal anti-aliasing seems to lock the transparent render pass field of view to whatever it was before. Fortunately that's unlikely to affect anyone.
