### ISSUE TITLE
Object upgrade tool in devkit editor creates duplicates of every object in the level, regardless of whether it's from the legacy editor or not

### ISSUE THREAD

**Issue by Hexadec1ma1** [SmartlyDressedGames/Unturned-3.x-Community#608]
![20190221221712_1](https://user-images.githubusercontent.com/32914055/53217616-a9fb8100-3626-11e9-8d30-9f67f4d142fb.jpg)

This creates problems when copying sets of objects from other levels, as it cannot be easily converted from the legacy editor into the devkit. I think a solution for this would be to implement a way similar to the legacy editor in the devkit where you can copy and paste objects from level to level, or change the way the object upgrade tool works so that it does not just duplicate every single object, legacy and devkit.

**Comment by SDGNelson** [comment]
Oversight on my part! 😜 
I only expected that tool to run on legacy maps, so it didn't check if the object was created by devkit. Will be corrected in the next patch!
