### ISSUE TITLE
Solid Colours For Object Highlights on MacOS

### ISSUE THREAD

**Issue by NeedlessMemeing** [SmartlyDressedGames/Unturned-3.x-Community#609]
Right so basically, ever since the Unity update the highlighting of objects on MacOS is completely solid. For context, here's some screenshots.
![screen shot 2019-02-22 at 11 27 23 pm](https://user-images.githubusercontent.com/37240761/53242769-e0ee9700-36f9-11e9-82fa-069ee4ba640f.png)
![screen shot 2019-02-22 at 11 27 16 pm](https://user-images.githubusercontent.com/37240761/53242774-e2b85a80-36f9-11e9-9b06-f1f50808467d.png)
![screen shot 2019-02-22 at 11 25 23 pm](https://user-images.githubusercontent.com/37240761/53242777-e4821e00-36f9-11e9-8e2d-456aa29833bb.png)
If it matters, the highlight also is put ontop of the player which from my experience isn't what normally happens.

Here are some specifications that may pertain to any debugging you could do:
MacOS Version: 10.13.6
Unturned Version: 1.29.0.1
Render Mode: Forward (deferred has no difference)
Highlight Quality: Max

If you need any files such as my config, I'm able to give them.

**Comment by gegtor** [comment]
I have the same issue since Unity LTS update 

Few other users reported this but no fix still

**Comment by SDGNelson** [comment]
Sorry for the lack of info, was looking into fixing this for a bit. Can confirm that a new dev build this morning has the outlines working properly on Mac. Will be in the next patch!
