### ISSUE TITLE
Cancellable PlayerDamage  event

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#61]
I would really appreciate it if something like this gets added.

See https://github.com/Trojaner25/RocketPlus/blob/master/Hooks/FakeDamageTool.cs#L12 for sample implementation (the patching does not work on x86 so this is not a solution)

[This code is hooked to the original method and is executed before the original code]

**Comment by SDGNelson** [comment]
DamageTool now has a delegate with this signature:

DamageToolPlayerDamagedHandler(Player player, ref EDeathCause cause, ref ELimb limb, ref CSteamID killer, ref Vector3 direction, ref float damage, ref float times, ref bool canDamage);
