### ISSUE TITLE
Tree > Cant turn off wind effect (Not important) - HAWAII map

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#613]
https://youtu.be/HT0dN7UJwUI
In this video one of my admin just found a tree which keeps "moving" even his wind effect turned off (on Hawaii)

(Blue circle as marking) https://cdn.discordapp.com/attachments/485012628926889984/548852860872425492/unknown.png

**Comment by SDGNelson** [comment]
Likely one specific tree using the wrong shader, will track it down
