### ISSUE TITLE
Crash on loading certain workshop item (something wrong with name possibly)

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#620]
Problem item is 1142425097. There is 4-byte unicode symbol in item name: `💥 BNK Clothing V2 🍀`
The log:
```
918139223 'Lax's Military Modpack' has no download IP restrictions
933868371 'Toxicity Backpacks [UNITY 2017 UPDATED]' has no download IP restrictions
1131548489 'Storm's Gunbox 3.28' has no download IP restrictions
1142425097 'Receiving unhandled NULL exception
#0  0x000000f5c28b00 in (Unknown)
#1  0x000000ffa97d14 in strerror_l
#2  0x000000ffa97d20 in operator delete(void*)
#3  0x000000ffa97e80 in operator delete(void*)
#4  0x000000ffa97ea0 in operator delete(void*)
#5  0x000000ffa97ef0 in (Unknown)
#6  0x000000ffa97f40 in (Unknown)
#7  0x000000ffa97f60 in (Unknown)
#8  0x000000ffa97f90 in (Unknown)
#9  0x000000ffa97ff0 in (Unknown)
#10 0x000000ffa98030 in (Unknown)
#11 0x000000ffa98050 in (Unknown)
#12 0x000000ffa98070 in (Unknown)
#13 0x000000ffa980a0 in (Unknown)
#14 0x000000ffa980c0 in (Unknown)
#15 0x000000ffa98220 in (Unknown)
#16 0x000000ffa98270 in (Unknown)
#17 0x000000ffa98310 in (Unknown)
#18 0x000000ffa98370 in SteamRealPath
#19 0x000000ffa983d0 in SteamRealPath
#20 0x000000ffa983f0 in SteamAPI_SetTryCatchCallbacks
#21 0x000000ffa98420 in SteamAPI_SetTryCatchCallbacks
#22 0x000000ffa98470 in SteamAPI_SetTryCatchCallbacks
#23 0x000000ffa984a0 in Steam_RunCallbacks
#24 0x000000ffa984d0 in SteamGameServer_RunCallbacks
#25 0x000000ffa984f0 in (Unknown)
#26 0x000000ffa98530 in (Unknown)
#27 0x000000ffa98540 in (Unknown)
#28 0x000000ffa98560 in (Unknown)
#29 0x000000ffa985d0 in (Unknown)
#30 0x000000ffa98610 in mono_get_jit_info_from_method
#31 0x000000ffa98670 in mono_g_hash_table_print_stats
#32 0x000000ffa986b0 in mono_runtime_invoke
#33 0x000000ffa98730 in operator delete(void*)
#34 0x000000ffa98750 in operator delete(void*)
#35 0x000000ffa98790 in operator delete(void*)
#36 0x000000ffa988c0 in operator delete(void*)
#37 0x000000ffa98900 in operator delete(void*)
#38 0x000000ffa98920 in operator delete(void*)
#39 0x000000ffa98950 in zcfree
#40 0x000000ffa98eb0 in __libc_start_main
#41 0x000000ffa98f20 in zcfree
```

**Comment by SDGNelson** [comment]
Does it always crash, or was this a one-off thing? Tried replicating with that item and it worked fine. Steam uses UTF-8 for text and the wrapper converts it accordingly, so I doubt it's related to the name.

**Comment by D-AIRY** [comment]
Yes, always in the same place (just right after the quote where the item name should begin). Tested now with only item

**Comment by D-AIRY** [comment]
[crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2898775/crash.zip)
Attached full log and gdb output

**Comment by SDGNelson** [comment]
Sorry thought I replied! I think this may actually be an exception in the steam library, inclined to think you're right that it's to do with the name. :o

**Comment by D-AIRY** [comment]
According the last stack trace, the crash happens somewhere in log writer. So it likely Unity related, not steam. Also got several crashes on player's login, seems the same reason. Can you filter strings before feeding it to System.Console.WriteLine?

**Comment by SDGNelson** [comment]
You were right, my thought process was that it was an unknown native function in the steam callstack, but from the partially formatted line it was in console writeline.

Since we didn't hear back on the other thread I assumed that it's been working for you in the legacy mono _headless version? After tonight's preview branch update both the legacy mono and latest mono versions are available on linux server.

**Comment by D-AIRY** [comment]
Yes, there is no problem with legacy mono (it just throws bad utf-16 character exception).
