### ISSUE TITLE
6 Seater makeshift vehicle isnt taken out of your inventory when placing it down

### ISSUE THREAD

**Issue by Noobyfish** [SmartlyDressedGames/Unturned-3.x-Community#621]
https://gyazo.com/b6234a693965d34448719ce3ebb9f381

The title says it all, Only tested with 6 seaters and on the map PEI.

**Comment by NeedlessMemeing** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/614

**Comment by SDGNelson** [comment]
Should be fixed in the patch!
