### ISSUE TITLE
Latest update broke a lot of servers that use RocketMod

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#622]
It might be caused by updated .NET (?)

**Comment by Daniil1288** [comment]
RocketMod 4 uses .NET 3.5. Don't think anyone will take up the task of updating it (we're supposed to use RocketMod 5 nowadays, I think?).

**Comment by gegtor** [comment]
Is this issue related to Russia map? 
Are you running Linux?

It might be my issue
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/611

My other servers run just fine Washington, PEI, etc

Only Russia causes server to crash

**Comment by Trojaner** [comment]
RocketMod 4 will not be updated and it's also not broken. Only some plugins are broken.

**Comment by aman7** [comment]
if only plugins are broken, then why all my servers hosted on linux getting crashed after few hours?

**Comment by Th3God** [comment]
gegtor, I do not own servers myself but most servers I used to play on are unplayable because of this updaye and owners can't do anything.

**Comment by Trojaner** [comment]
@aman7 sounds more like an Unturned issue. RocketMod can not crash server after some hours.

**Comment by gegtor** [comment]
I can confirm that my other server crash after some time too

On Russia it happens instantly on other maps after few hours

**Comment by Trojaner** [comment]
Please open a new issue for the crash issue as its not related to this.

**Comment by gegtor** [comment]
I did 2 days ago
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/611

**Comment by SDGNelson** [comment]
Most likely plugin(s) that depended on the DamageTool.damage signatures needed to be re-compiled. When adding new optional keyword arguments it seems that it doesn't always maintain backwards compatibility, and in those cases I can't add an overload because the compiler can't tell them apart, e.g:
method(int a = 0, int b = 0);
method(int a = 0, int b = 0, int c = 0);
