### ISSUE TITLE
/animal command glitch?

### ISSUE THREAD

**Issue by johnlemon76** [SmartlyDressedGames/Unturned-3.x-Community#623]
Basically, after spamming /animal 6, cows would respawn at random over and over. This was also happening with a bear and moose that I had spawned while testing the Animal IDs

Video:
https://www.reddit.com/r/unturned/comments/aue6nd/animal_created_an_infinite_supply_of_cows/

**Comment by Noobyfish** [comment]
When you do the animal command it makes a _spawn point_ for the animal you spawned instead of just spawning it in on its own, Its the same as if you placed a spawnpoint in the editor. I am guessing this is an intentional feature cause, from my knowledge at least, its always been like this.

**Comment by SDGNelson** [comment]
Noobyfish is correct - it works by creating a spawn point for that animal type. The animal command was sort of hacked-in later in development to test some animal features, but making it work with animal pack merging and whatnot is low priority.
