### ISSUE TITLE
When you kill a player with a 0 kelvins weapon their head doesnt fall off and just goes sideways

### ISSUE THREAD

**Issue by Noobyfish** [SmartlyDressedGames/Unturned-3.x-Community#625]
![20190224231938_1](https://user-images.githubusercontent.com/20568317/53314380-07dcd280-388c-11e9-84c3-94211a956593.jpg)
it just goes sideways
these are my settings
![image](https://user-images.githubusercontent.com/20568317/53314386-10cda400-388c-11e9-91fd-43e6f8cfae64.png)
Ive tested this three times and it went sideways all three times.
![20190224233542_1](https://user-images.githubusercontent.com/20568317/53314528-c862b600-388c-11e9-8e4a-678caeb80f8b.jpg)

**Comment by SDGNelson** [comment]
Gosh dangit I tried to be careful when making these changes (e.g. sendTeleport still exists), but turns out I made a really stupid mistake. Will have a patch out asap

**Comment by SDGNelson** [comment]
Oops that comment was on the wrong issue. Well, I will fix this too
