### ISSUE TITLE
The recent Mac OS issue now occurs on Windows, too

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#627]
Solid colour instead of textures on NPCs: https://cdn.discordapp.com/attachments/510075922116902912/549549798060195850/unknown.png
And some vehicles, objects.

**Comment by Daniil1288** [comment]
https://cdn.discordapp.com/attachments/510075922116902912/549551607898177537/unknown.png

https://cdn.discordapp.com/attachments/510075922116902912/549552164935303189/unknown.png

https://cdn.discordapp.com/attachments/510075922116902912/549552209147461642/unknown.png

**Comment by ImIveooo** [comment]
I had the bug with my mods too, but I don't see where it came from. Now I know it's not the nvidia drivers.

**Comment by ImIveooo** [comment]
Windows 10 [1809]
Nvidia 1050Ti [419.17]

**Comment by NeedlessMemeing** [comment]
inb4 the fix for windows breaks mac

**Comment by SDGNelson** [comment]
To add to this, there also seem to be issues with negative scaled objects e.g. mirror-pose mannequin.
Will investigate!

**Comment by TheCubicNoobik** [comment]
@SDGNelson Try this https://trello.com/c/nUOlKQ6S/206-negatively-scaled-objects-make-highlighting-fill-objects-with-color-instead-of-highlighted-outline

**Comment by Trojaner** [comment]
Could it be that this issue is related to the highlighter used by Unturned?

**Comment by SDGNelson** [comment]
Thanks @TheCubicNoobik! ❤️
