### ISSUE TITLE
macOS UI elements gamma/glow issue

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#628]
This issue appeared alongside  https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/609 when Unity LTS update came out for unturned

Basically, UI elements and some pictures on macOS look like their gamma was increased and they are not as sharp as on Windows 

When pixel peeping font on macOS is less sharp and looks like it has some glow around it or excessive anti-aliasing but might just be my eyes tho

macOS - Windows client graphics settings synced with steam cloud
Both running 1440 x 900

Unturned v3.29.2.1
macOS Mojave 10.14.3

macOS:
![](https://i.imgur.com/tfO4O2h.png)

Windows:
![](https://i.imgur.com/2QGCPxO.png)

macOS:
![](https://i.imgur.com/LaA9mRd.png)

Windows:
![](https://i.imgur.com/mT5wHeF.png)

macOS:
![](https://i.imgur.com/ddzkuf6.png)
Windows:
![](https://i.imgur.com/mHN6xdU.png)

macOS:
![](https://i.imgur.com/HhwOS4L.png)

Windows:
![](https://i.imgur.com/HRtWEkY.png)

**Comment by SDGNelson** [comment]
Tried to workaround this in several ways when switching to the LTS version e.g. trying to override the IMGUI shaders to gamma correct them on Mac, but no luck. Ideally this should be fixed in an LTS patch soon, but if anyone has any suggestions I'm all-ears.

**Comment by gegtor** [comment]
@SDGNelson Any progress?

**Comment by SDGNelson** [comment]
I reported it along with another developer and have been keeping an eye on the 2017.4 LTS releases, but no luck. My hope is that it will be fixed when we update to 2018.4 LTS.

**Comment by SDGNelson** [comment]
Been working on the 2018.4 LTS upgrade the past few days, and it's looking like this may finally be fixed. Fingers crossed!

**Comment by SDGNelson** [comment]
Tested on the unity-2018.4 beta branch today and unfortunately it's still broken. I had hope because on Windows there were similar gamma issues which needed updating to the new version. I'll still experiment with a few things to try and fix it. 😢 

One option I'm considering for further down the road is to generate the newer Unity UI components from the game's IMGUI code. This would fix the gamma issue and help unify the UI. That's definitely aways off though.

**Comment by SDGNelson** [comment]
Tried putting the Mac UI textures into linear mode (currently -ForceLinearUI) which just makes it worse. Sigh.

**Comment by SDGNelson** [comment]
Here's the Unity forum thread where it was brought up before: https://forum.unity.com/threads/imgui-color-space-problems-on-mac-and-xbox-one.555568/

Most likely next hope for fixing this is if we do the UI overhaul.

**Comment by gegtor** [comment]
:<

**Comment by SDGNelson** [comment]
I experimented with a few things that I can't believe I hadn't tried before, and there's a kind of dumb workaround in place now on the beta branch. It still looks bad, but it's less noticeable. I'll also follow up on that Unity forum thread.

**Comment by SDGNelson** [comment]
Closing since it seems unlikely that anything will change here soon. For the long term it makes sense to convert the IMGUI code, but I'm not sure when that will happen. #1234
