### ISSUE TITLE
Enter button.

### ISSUE THREAD

**Issue by ImIveooo** [SmartlyDressedGames/Unturned-3.x-Community#629]
The enter key on numeric keypad no longer works on Unturned.

**Comment by Trojaner** [comment]
I can confirm this issue

ImIveooo <notifications@github.com> schrieb am Di., 26. Feb. 2019, 19:01:

**Comment by SDGNelson** [comment]
I believe this is outside of my control, but it might be fixed the next time Unturned updates Unity LTS versions.
