### ISSUE TITLE
Conflicting Workshop IDs

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#631]
Not sure if this is a unturned/rocketmod issue but It would be really nice to add some form of a feature that stops servers that have 2 or more mods with conflicting Ids getting a "Missing barricade" issue or "Missing Asset" issue. I specifically have this issue with Nordic Armoury and More Farming mod as when a structure from more farming mod is placed down that conflicts with an ID from nordic the whole server crashes and gets a "Missing Barricade" Error. 

I am not sure how easy of a fix this would be but maybe instead of causing crashes it simply gives 1 item priority over the other and in order to get the specific item you want a Name should be used when spawning rather than an ID.  I have currently blacklisted the items that conflict but It still would be nice to have a way of allowing both items to work by maybe even labelling them with letters if there are 2 conflicting ids.

For example 19702a and 19702b. This way you can have 2 items that in the modpack have the same ID but on the server, they are separated by a letter.

**Comment by SDGNelson** [comment]
Interesting case! Thanks for the info about the conflicting packs. I'll do something about this for the next patch.

As for the a/b suggestion, unfortunately the 16-bit IDs are stupidly widespread hardcoded into the game. At one point I had some work done on a system that converted 128-bit IDs into 16-bit IDs over the network, but it would still be a huge undertaking to correct all the places in the code.

**Comment by SDGNelson** [comment]
Should be more in line with the original intentions for the next update:
If they don't have any item matching the ID then they get the message about missing asset because whatever pack was not loaded, but if they have an item of the wrong type then it will skip it.
