### ISSUE TITLE
See about configurable salvage speed

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#633]

**Comment by Slayix** [comment]
I like chef boyardees ravioli

**Comment by justboughtmarmalade** [comment]
@Slayix cant disagree

**Comment by justboughtmarmalade** [comment]
or nolson it might be optimisation time

**Comment by Slayix** [comment]
I took a bath last night in chef boyardees ravioli

**Comment by Kenzim** [comment]
nelson how has this taken so long lmao salvage speed is literally the bane of my life.

**Comment by SDGNelson** [comment]
Added sendSalvageTimeOverride RPC in the next update which can set the duration per-player, or -1 to disable the override.
