### ISSUE TITLE
Redirecting players via a server

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#637]
I have had this idea for a fairly long time and I have seen many people ask plugin devs for a plugin to do this.

So the idea is a way to allow a plugin to be able to redirect a player from server A to server B. The idea behind this is players could travel between a networks server base with just a command rather than searching or finding the IP and port. 

Now I am aware this can be abused by plugins in order to move all players too one server so I suggest some form of UI that is built into unturned that opens up and tells them the basic info about the server. (Map, name, ping, players)

There will then be an accept/reject button and If they do select it would simply skip the whole server browser and directly start loading them into the server that the plugin chooses.

Please excuse the fact that I have no knowledge of plugin or game development so this may be a lot harder than I am assuming. The idea for my servers would be allowing players to buy "air tickets" that allow them to "fly" to other countries (maps). The point of skipping the server browser would allow for more immersion in the RP experience.

**Comment by Adamv21** [comment]
Just want to point out: I'm not an expert in this stuff so maybe I'll just talk some bs.

I'm pretty sure when moving steam server, you do need the authentication ticket from the client. So the UI idea for you could possibly be a solution BUT, always a but, our lord and saviour nelson needs to implement it which is prob not on his priority. Tbh while writing this, it's actually kinda a good idea and maybe Nelson could make a steamcall to the client to just ask the client to disconnect and then connect to another server. Maybe there are some obstacales, like loading time.

**Comment by Edbtvplays** [comment]
Pretty much BungeCord in unturned (Bungeecord is for minecrfat and uses a proxy server to move people from one server to another)

**Comment by Johnanater** [comment]
I think it'd be more like just a client "connect" command that gets run, rather than a proxy server.

**Comment by Edbtvplays** [comment]
> I think it'd be more like just a client "connect" command that gets run, rather than a proxy server.

i think a proxy server could also be cool though.

**Comment by Johnanater** [comment]
But I lot more complicated.

**Comment by Edbtvplays** [comment]
Yes it would be but maybe something to include for unturned 4.0 just a idea that brad may be trying to portray.

**Comment by SDGNelson** [comment]
I do think it's a really cool idea... Was hesitant to reply while it ruminated in my mind.

As is, none of 3.0 was built with swapping servers from in-map, so it would require a lot of reworks, but what might be an option is sending some data to the client about another server, and then auto-disconnecting and querying that server to open/connect to the other server. Will

In 4 you can access all of the main menu features from in-game (switch to SP, lobby, MP, etc) so this will definitely be possible there without mods!

**Comment by SDGNelson** [comment]
Added the relay sort of option for the next update! Plugins can call Player.sendRelayToServer with connection info, and they'll be sent to the other server. Will leave this open until plugins have a chance to implement some use cases, though I put together a little test and it seems to work okay.

**Comment by Bradler26** [comment]
Perfect! I will try get a plugin Dev to create some sort of plugin in the next few days. I will be sure to post the results back here once I've tested it. Thanks for adding the suggestion 😉

**Comment by MrKwabs** [comment]
Thanks for the addition! However, when trying to implement this I appear to be getting this error ever time:

`[13/03/2019 19:14:22] [Error] InvalidOperationException: Steamworks GameServer is not initialized. - Steamworks.InteropHelp.TestIfAvailableGameServer () (at <64c53ca8bc964db09267151aea35058a>:0)
Steamworks.SteamGameServerNetworking.IsP2PPacketAvailable (System.UInt32& pcubMsgSize, System.Int32 nChannel) (at <64c53ca8bc964db09267151aea35058a>:0)
SDG.SteamworksProvider.Services.Multiplayer.Server.SteamworksServerMultiplayerService.read (SDG.Provider.Services.Community.ICommunityEntity& entity, System.Byte[] data, System.UInt64& length, System.Int32 channel) (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)
SDG.Unturned.Provider.listenServer (System.Int32 channel) (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)
SDG.Unturned.Provider.listen () (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)
SDG.Unturned.Provider.Update () (at <2de13a8df2bb4bd79a2f1071f29293c3>:0)
`

**Comment by RoyIL** [comment]
@SDGNelson sendRelayToServer sends you to the server menu, can you add a bool as an argument and if set to true auto "connect" to the server?
sendRelayToServer(bool autoConnect)

**Comment by Bradler26** [comment]
Okay after getting a Dev to help make a plugin we managed to get a working version. It works quite smoothly and is exactly what I needed. The plugin is free and can be found here - https://github.com/MrKwabs/ServerSwitcher

Thanks again for adding this request.

**Comment by SDGNelson** [comment]
Thought I commented on this already, sorry!
Not allowing a forced relay was intentional so that they can evaluate the new server details before committing to it. Was annoying in CS or Gmod when the server would send you off to download nine trillion mods for the next map.
Happy to hear that it's worked well! :)
