### ISSUE TITLE
Map doesn't load after adding a water volume

### ISSUE THREAD

**Issue by TheCubicNoobik** [SmartlyDressedGames/Unturned-3.x-Community#638]
Because decimal numbers is saved with comma
![screenshot_1](https://user-images.githubusercontent.com/37713088/53574752-da887100-3b78-11e9-8a13-b8fe3db60d2e.png)

**Comment by SDGNelson** [comment]
Should be fixed in the release .2 patch - just put together a change to use invariant culture when writing floats and doubles.
