### ISSUE TITLE
Vehicle Skidding Instead of Instant Stop

### ISSUE THREAD

**Issue by xdlewisdx** [SmartlyDressedGames/Unturned-3.x-Community#64]
As the title says, when pressing space vehicles instantly stop, I don't think this is very good at all because it means if you put caltrops down they can easily above them by instantly braking, instead I think if the vehicle skids it would make it be WAY better

**Comment by V1CeNtE** [comment]
this is a 4.0 feature

**Comment by SDGNelson** [comment]
Unfortunately this is unlikely to change in 3.x, but will definitely be present in 4.x.

**Comment by xdlewisdx** [comment]
Ok thanks for letting me know
