### ISSUE TITLE
Intractable Broken

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#641]
So I got this error today and I have confirmed it with a friend that co-owns NightPatrol servers. 

Pretty much what is happening is for some reason (not 100% sure) some structure or even potentially mod is causing a certain area around it to glitch out any interactable items (sentries, lockers and doors) are not allowing the placer to salvage or interact/open them. I believe this has been an issue before but it has become quite bad and is really annoying when players cant leave their base because of a door that won't open. Sometimes the items seem to go invisible and can only be seen when using /wreck.

I have noticed that if I wreck about a 100m radius around the problem area the issue is resolved. I have even attempted to pinpoint the item by wrecking items in small groups but it seems like there may be multiple.

I am going to continue my testing and see if I can pinpoint the item/mod that may be causing this. Would be nice if you could implement a fix for this if possible as I know this has been a long time issue for a while now

**Comment by lordcameron892** [comment]
TNP has a plugin that auto destroys inactive bases, someones base was wiped and when going back into that area of where it was wiped, walking around becomes rubber bandy and trying to salvage newly placed items doesn't work. Opening any kind of storage container doesn't work either.

**Comment by Bradler26** [comment]
Yes in the glitched areas on my server you cannot wreck Intractables such as lockers and sentries. There are also invisible doors and other items that can be walked into/through that cause a rubber band affect.

**Comment by Trojaner** [comment]
> TNP has a plugin that auto destroys inactive bases, someones base was wiped and when going back into that area of where it was wiped, walking around becomes rubber bandy and trying to salvage newly placed items doesn't work. Opening any kind of storage container doesn't work either.

Sounds more like an issue with the plugin which apparently does not delete them correctly to be honest.

**Comment by SDGNelson** [comment]
This must be related to the not-kicking-for-missing-buildables change, I'll fix a few things up for the patch

**Comment by joemisfit** [comment]
_Cry created the plugin._ @Trojaner 

Also, it's not a maintained plugin, it's heavily outdated, and that issue was always common on TNP Servers, in order to fix it either the structure files needed to be wiped or every individual item needed to be wiped precisely in the area of the rubberbanding for it to stop; usually i've noticed it could be due to too many items in that localised area, an item id change as he is using a custom workshop for content, or the item might just be broken/removed from the workshop.

**Comment by Bradler26** [comment]
There was over 1000 objects in a 50m radius around the area as someone was growing about 600 crops so that could be why @joemisfit. 

Nonetheless at least Nelson is going to patch it so that's good 😀

**Comment by joemisfit** [comment]
Hopefully that's the issue, but it's been around for quite some time now.

**Comment by Bradler26** [comment]
I can confirm that this does seem to be fixed with the new update. Thanks @SDGNelson 😄

**Comment by SDGNelson** [comment]
Thanks for the confirmation! Feel free to re-open if it crops up again
