### ISSUE TITLE
All the npcs are invisible

### ISSUE THREAD

**Issue by RumbLEexe** [SmartlyDressedGames/Unturned-3.x-Community#642]
This is the error

General: Exception raised when RPC invoked askUseObjectNPC:
NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ObjectManager.askUseObjectNPC (Steamworks.CSteamID steamID, System.Byte x, System.Byte y, System.UInt16 index) (at <95cc710240a3490da0f6a086ae942be5>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
SDG.Unturned.SteamChannel.receive (Steamworks.CSteamID steamID, System.Byte[] packet, System.Int32 offset, System.Int32 size) (at <95cc710240a3490da0f6a086ae942be5>:0)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.Provider:receiveServer(CSteamID, Byte[], Int32, Int32, Int32)
SDG.Unturned.Provider:listenServer(Int32)
SDG.Unturned.Provider:listen()
SDG.Unturned.Provider:Update()

**Comment by SDGNelson** [comment]
Thanks for the stack trace! This should be fixed in the next patch
