### ISSUE TITLE
Vehicle seller's NPC : vehicle not locked at the spawn.

### ISSUE THREAD

**Issue by ImIveooo** [SmartlyDressedGames/Unturned-3.x-Community#643]

**Comment by SDGNelson** [comment]
Yikes! This should be fixed in the patch.
Anecdote: not sure if you're the one who asked about this in an email the other day, but you can set Selling_#_Type Vehicle for a vendor to sell vehicles.

**Comment by ImIveooo** [comment]
Yes, it's me. 😃
