### ISSUE TITLE
Spec ops helmet

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#646]
I don't remember why I didn't add it initially, but fine I will add it 😋

**Comment by strongunturned** [comment]
What awaits us there? Let's fix linux?  😋

**Comment by Trojaner** [comment]
@strongunturned please stop spamming the Linux issue everywhere.
It has its own issue, use that and please dont push it without new information...

**Comment by BlueFire9020** [comment]
Nelson is literally me when writing code ._.
