### ISSUE TITLE
Make it possible to choose betwenn .NET 4.6 and .NET 3.5 for linux users.

### ISSUE THREAD

**Issue by Eiromplays** [SmartlyDressedGames/Unturned-3.x-Community#649]
Hi, My unturned servers that is running on Linux worked just fine with the .NET 4.6 version. But now I feel like I lost alot of my money. Because I have paid for plugins and now I kinda dont get support from there. Hope you maybe can sort this out somehow.

**Comment by khakers** [comment]
That’s something that would probably be better raised with the devs of the plugins you paid for.

**Comment by Trojaner** [comment]
We will not support multiple runtimes. The maintainability cost for continuing supporting .NET 3.5 is not worth its small user base.

**Comment by Eiromplays** [comment]
I fully understand that devs wont support downgrade back to the old version. And i fully support that. It is good to hear that you support having 2 different versions for Linux.

**Comment by aman7** [comment]
It would have been better for everyone to use .NET 4.6 and find the solution for linux users, there might be some fix exist like using latest OS and dependencies. you should find that out rather than going back.

**Comment by Bradler26** [comment]
> It would have been better for everyone to use .NET 4.6 and find the solution for linux users, there might be some fix exist like using latest OS and dependencies. you should find that out rather than going back. Or just downgrade all platform to 3.5, we linux server hosters are not getting support from plugin developers just because of 3.5 and we are few, so its upto you now to save our money

But if Nelson was to downgrade back to 3.5 most plugin devs would just quit. Us windows users will lose even more players and money compared to the amount off player and money loss the linux servers would suffer. I know it sounds harsh but you are only 20% of all the unturned servers and if I was Nelson and only had 2 choices I would rather take 80% of the servers over 20%...

**Comment by aman7** [comment]
> 
> 
> > It would have been better for everyone to use .NET 4.6 and find the solution for linux users, there might be some fix exist like using latest OS and dependencies. you should find that out rather than going back. Or just downgrade all platform to 3.5, we linux server hosters are not getting support from plugin developers just because of 3.5 and we are few, so its upto you now to save our money
> 
> But if Nelson was to downgrade back to 3.5 most plugin devs would just quit. Us windows users will lose even more players and money compared to the amount of player and money loss the linux servers would suffer. I know it sounds harsh but you are only 20% of all the unturned servers and if I was Nelson and only had 2 choices I would rather take 80% of the servers over 20%...

they will not quit, 2 weeks ago unturned was running .NET 3.5 and they were all happy and selling their plugins and making a lot of money, and its not impossible to support two .NET version of plugin they are just lazy or dont want to support because we are few. you would have understand this if you had bought the plugins like 10-20 days ago.

**Comment by Bradler26** [comment]
They simply cannot rollback. As @trojaner has stated before they are working on rocket mod 5 that is one of the most hyped released for us server owners and we can't wait. They would loose all that progress all because of a rollback. As I said before I would rather please the majority.

**Comment by aman7** [comment]
@Bradler26 just imagine you bought a game for $50 for linux, and they stopped the support next day and you not even getting the refund, and they asking you to buy windows, what would you call this? scam? or gift to the developers?

**Comment by Bradler26** [comment]
I understand that and I am not going to go into if it is a scam or not. That should be discussed with the plugin owners. I'm talking from Nelson's perspective. Let's say you are a game designer and you make a game. You can then either drop support for Linux (20% of your severbase) or pretty much ruin everyone to the point where you could loose over half of all servers. 

I think at this point we can just agree to disagree as we quite clearly have different views. I understand your frustration related to your purchases plugins but this will also happen to us if there was a revert.

**Comment by aman7** [comment]
game will be fully alive man, just remember plugin developers should depend on Unturned, not unturned should depend upon plugin developers, game will work fully on all the platforms it supports, just the plugins wont which is third party, and none of the servers will effect because of plugin because if one developers doesnt others will.

**Comment by Eiromplays** [comment]
I guess that the best for me and maybe some other Linux hosters it would have been good if we could choose between .NET 4.6 and .NET 3.5 because for some linux hosters .NET 4.6 worked just fine.

**Comment by Trojaner** [comment]
> they will not quit, 2 weeks ago unturned was running .NET 3.5 and they were all happy and selling their plugins and making a lot of money, and its not impossible to support two .NET version of plugin they are just lazy or dont want to support because we are few. you would have understand this if you had bought the plugins like 10-20 days ago.

Meanwhile about 1000 commits and one year of work went to RocketMod 5 which was exactly waiting for .NET 4.6. Plugins will not support .NET 3.5 anymore. Just because we supported it in the past, it does not mean we can easily support it again.

> @Bradler26 just imagine you bought a game for $50 for linux, and they stopped the support next day and you not even getting the refund, and they asking you to buy windows, what would you call this? scam? or gift to the developers?

No one sold these plugins for Linux. They were sold for "Unturned 3", with no promise regarding supported platform at all. Your money is not gone, you can still use the plugins, just not on that platform.

**Comment by aman7** [comment]
yes i bought this plugin for unturned 3 and there wasnt anything mentioned that it will not work for linux in future, i know you will say the same thing in future to windows server owner that now only we support MAC, not windows or linux.

**Comment by SDGNelson** [comment]
Happy to hear that .NET 4.6 worked well for you on Linux!

For the next patch I will adjust the current "32-bit linux" depot to instead be a Linux Dedicated Server depot, and will have builds for .NET 3.5 and .NET 4.6 support in there, so you will be able to use the newer plugins.

Plugin dev wise: I think it's important that those of you who are selling plugins make sure your stores state which .NET versions / platforms your plugins support.

**Comment by aman7** [comment]
thanks alot nelson.

**Comment by Trojaner** [comment]
> yes i bought this plugin for unturned 3 and there wasnt anything mentioned that it will not work for linux in future, i know you will say the same thing in future to windows server owner that now only we support MAC, not windows or linux.

Well, no one knew that this situation would happen as well.

> Plugin dev wise: I think it's important that those of you who are selling plugins make sure your stores state which .NET versions / platforms your plugins support.

This will be definitively done since now different .NET versions are around.

**Comment by Eiromplays** [comment]
Thanks you Nelson this made my day 😀

**Comment by aman7** [comment]
when the .NET 4.6 build for linux will be available?

**Comment by Ascivv1** [comment]
What .NET build is Linux using right now?

**Comment by aman7** [comment]
3.5

**Comment by Ascivv1** [comment]
Thank you. So nelson reverted it back from 4.6 to 3.5?

**Comment by aman7** [comment]
yes, soon we will have both 4.6 and 3.5 but dont know when

**Comment by SDGNelson** [comment]
Sorry it should be out in the next day or two along with the rest of the update, one option I'm looking at is setting up a separate app for the dedicated server. Previously I'd tried to have the main game set up in the anon package, but now devs can setup their own dedicated server tool app, so it might be easier for everyone if it's available there.

**Comment by SDGNelson** [comment]
3.29.3.0 is now out on preview and should release tomorrow morning

**Comment by Eiromplays** [comment]
One question Nelson. With the .NET 4.6 for Linux i can use plugins that use the older version?

**Comment by aman7** [comment]
can we get some tutorial or something to use the depot correctly, i have tried doing this download_depot 304930 304937 <manifest>, it downloads but changes doesn't reflect on the server. this is not only with me, i have asked many linux server owner, they are facing the same issue.

**Comment by Trojaner** [comment]
You must also update your start script so it uses the correct start executable.

**Comment by Eiromplays** [comment]
And the correct start executable would be?

**Comment by aman7** [comment]
no clue about the correct start executable, i think it would be nice, if .NET 4.6 build is default depot for linux.

**Comment by Trojaner** [comment]
Linux x64 .NET 4.6.1 builds seem quite stable so I agree on this.

**Comment by SDGNelson** [comment]
Closing since this seems to have gone smoothly. Will comment on the other linux64 thread
