### ISSUE TITLE
The train can still be stopped using some pipes

### ISSUE THREAD

**Issue by danaby2** [SmartlyDressedGames/Unturned-3.x-Community#65]
https://youtu.be/JqKu-Ko_2Xg

In this weeks update nelson added a thing where trains destroyed everything in front of them so they cant be blocked, but if you put a few pipes above the tracks you can still stop the train and everyone who uses the trains on that server will hate you.

**Comment by AnimaticFreak** [comment]
Engineers hate him! This man learned how to stop trains with one simple trick!

No but really that's something really weird, I bet it has something to do with the top of the train's model not having the same ability to insta-destroy things
