### ISSUE TITLE
RocketMod server crashes on startup on Linux

### ISSUE THREAD

**Issue by CH3DD4RCF** [SmartlyDressedGames/Unturned-3.x-Community#650]
When I start the server with ./start.sh, it ends with a line with "Steamworks GameServer is not initialized". However, before you call it a duplicate of [#172](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172), the workaround did nothing for me. It's also complaining about an "Error running gmcs: Cannot find the specified file"

**Comment by Trojaner** [comment]
You opened this issue in the wrong place. This is the Unturned bug tracker.

Regardless of that, support for RocketMod 4 was dropped, so your issue will not get fixed.

**Comment by CH3DD4RCF** [comment]
Then how the hell do I run an Unturned Server on Linux now? Surely Linux support hasn't been dropped. I looked for *hours* yesterday and couldn't find any linux hosting tutorial that didn't involve RocketMod

**Comment by Edbtvplays** [comment]
> Then how the hell do I run an Unturned Server on Linux now? Surely Linux support hasn't been dropped. I looked for _hours_ yesterday and couldn't find any linux hosting tutorial that didn't involve RocketMod

Unturned on Linux needs rocket mod to run i believe there is no way around this at this time.

**Comment by Coopyy** [comment]
wrong

**Comment by CH3DD4RCF** [comment]
@Coopyy 
Any chance you could at least give me an idea of how to get started without Rocket then?

**Comment by Trojaner** [comment]
Currently there is no way to get Unturned running with Wine.
