### ISSUE TITLE
Two versions of unturned on the same Windows server

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#654]
Hi, I ran into such a problem, I cannot run on one dedicated server, two versions of the game, servers on the latest version work and have a connection, but servers of version 3.27.2.1 run on a dedicated server, but in the game itself they are not visible and not connect

The server on the new version is working and has a connection - 212.109.222.142 50000. The server on version 3.27.2.1 is running, but has no connection - 212.109.222.142 27024. 

Maybe I did something wrong, the main servers are running through Steam, and I created a server on version 3.27.2.1 through SteamCmd.

<img width="1279" alt="2019-03-06 20 43 12" src="https://user-images.githubusercontent.com/48184311/53901656-871e9300-4050-11e9-9dd0-fd532c1cfefd.png">

**Comment by strongunturned** [comment]
It would be nice if the server version can be selected in the files of the server itself, edit the launch version, since in Windows it is not possible to start the server immediately for several versions

**Comment by Trojaner** [comment]
Use steamcmd not Steam...

**Comment by strongunturned** [comment]
@Trojaner, The problem remained, all servers were transferred to steamcmd, but still only see the latest version, the server is not visible on the old version
