### ISSUE TITLE
Custom placeables to craft custom items 

### ISSUE THREAD

**Issue by Swatbolt89** [SmartlyDressedGames/Unturned-3.x-Community#655]
It would be interesting if we could make custom barricades that can exclusively craft certain items. For example, a forge that could exclusively craft steel. Something like a campfire how you need to stand in a certain radius to craft said item. I asked around and I don't fully know if its a thing already or not nor have I ever seen it in a mod.

**Comment by Hexadec1ma1** [comment]
I think this might be a better addition for II

**Comment by SDGNelson** [comment]
It would make a lot of sense, but at the moment the campfires are pretty hardcoded. One feature that's on track for 4 is to allow different buildables to override the inventory and therefore setup custom crafting features, for example recently I've been working on some features for safes with codelocks that require you to input the code before accessing the items, or a bullet-crafting station could have two slots for gunpowder and casings.
