### ISSUE TITLE
Creating map objects from the server

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#656]
I don’t know for sure, but most likely it’s impossible to spawn any object on the server and on the players ...
Suppose I would like to put my NPCs on the vanilla card, or any decorations.
I would like to see this opportunity in the game.

**Comment by SDGNelson** [comment]
You're right that there isn't support for this as-is, and I guess this is a case that unfortunately guarantee will not be added. For NPCs, one option would be to place them in the map and use a flag condition for their visibility, then the server could enable/disable them as-needed. It will be possible in 4.0 to dynamically spawn objects from the server.
