### ISSUE TITLE
Russia - Volk Mili - Tent glitched

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#657]
https://youtu.be/tapA9tZsnGc

This video show you this (probably new) bug when you can go through the military tent. (Russia map, Volk)

**Comment by evermoreservers** [comment]
another similar glitch on rock. (same map)
https://youtu.be/5qTNvlj7i9A

**Comment by SDGNelson** [comment]
Sadly I guess the overlap recovery needs to be re-enabled. On the bright side it led to fixing some other related bugs like teleport overlap checks.

**Comment by evermoreservers** [comment]
But this is NOT acceptable bug.
People can actually just WIN pvp by that bug.. by getting off the tent without his enemy realizes it..

**Comment by SDGNelson** [comment]
I know, that's why I re-enabled the overlap recovery. It should not be possible anymore
