### ISSUE TITLE
The Train Shows The Blowtorch Hitmarker But Does Not Repair

### ISSUE THREAD

**Issue by V1CeNtE** [SmartlyDressedGames/Unturned-3.x-Community#66]
In this case, my train has 9% health and I can not repair it, I do not know how it came to 9% but I wanted to repair it and it did not permit me. **Even the train shows  the blowtorch hitmarker compared to the bicycle**

**Comment by xdlewisdx** [comment]
This is because trains cannot be destroyed/repaired, so not sure how it got to 9 in the first place

**Comment by SDGNelson** [comment]
Will hide them: #72
