### ISSUE TITLE
Could we get some more Unity example packages?

### ISSUE THREAD

**Issue by Hexadec1ma1** [SmartlyDressedGames/Unturned-3.x-Community#667]
Would be extremely helpful to have the light objects (Light_0, Light_1, Light_2, and Light_3), definitely would help modders a lot to be able to create more sources of light for dark maps.

**Comment by danaby2** [comment]
custom character mesh
custom character mesh

**Comment by danaby2** [comment]
"can you write finshing rod too under that github post" - renaxon

**Comment by TheCubicNoobik** [comment]
You can use this https://gist.github.com/TheCubicNoobik/4a7603a22cf89d2c846b29a622013c75 editor script to load bundles and see what you need

![Screenshot_3](https://user-images.githubusercontent.com/37713088/54084995-30aba000-4341-11e9-9cc4-1e41bbf1c141.png)

**Comment by SDGNelson** [comment]
Here's the details for the mesh replacement (shirt asset)
there are a few mod projects using it as test case which seem to be going okay so far:

	/// Mesh Replacement Details
	/// .dat Flags:
	///		Has_1P_Character_Mesh_Override True		Bool
	///		Character_Mesh_3P_Override_LODs #		Int
	///		Has_Character_Material_Override True	        Bool
	/// Asset Bundle Objects:
	///		Character_Mesh_1P_Override_#			GameObject with MeshFilter (mesh set to a skinned mesh)
	///		Character_Mesh_3P_Override_#			GameObject with MeshFilter (mesh set to a skinned mesh)
	///		Character_Material_Override		        Material
