### ISSUE TITLE
One of the problems, construction and wipe on the server survival.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#668]
I suggest to make a key object (for example, a closet) that will protect the house, and if the closet breaks, the house will be destroyed gradually.

**Comment by Trojaner** [comment]
Unturned already provides something called decay to deal with this issue.

**Comment by SDGNelson** [comment]
Sounds sort of like Rust's cabinet system, but yes Unturned has the claim flags and decay features to deal with abandoned bases.
