### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#669]
I do not know if it was me that did something wrong, but recently I have been reset for these three crashes.
[crashes.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/2949557/crashes.zip)

**Comment by SDGNelson** [comment]
Unfortunately the attached crash files only contain native data, I wonder if there's any output_log.txt file?

**Comment by rube200** [comment]
i think i already found the problem, it only occures at  the shutdown, i think it is threads stuff.

**Comment by VitaxaRusModding** [comment]
@rube200  Yes, yes...

**Comment by Johnanater** [comment]
I've also seen a crash on shutdown with my servers. It creates "Unturned.gc.log" in the server root directory. The file only has "SuspendThread Failed". I only had it happen a few times but I messed up my restarter because the exe was still running in the background.
