### ISSUE TITLE
Texture bug(minor)

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#673]
https://youtu.be/M5VI-5utugY
Volk Military Base - Tent texture bug (Russia map)

Such a small & old bug but i just got a video about it.. so maybe u can fix this, any fix is good always.
(Short desc: U can stand in the air)

**Comment by ImIveooo** [comment]
I think it's a bug the itbox and not the texture. 🤔

**Comment by Th3God** [comment]
That's hitbox not a texture - the hitbox is like an invisible shield over textures. I am pretty sure that all tents in Unturned have that hitbox issue.

**Comment by evermoreservers** [comment]
Well guys i dont know why you talk about what it is, the only matter it is a bug, and even it's a minor bug only, but good to have it fixed! : )
However i mentioned it as texture, cuz its basicly part of the texture and you can shoot through it, while hitbox supposed to stop the shooting and get "hit" by it. But doesn't matter at all, it is a bug, thats the case.

**Comment by SDGNelson** [comment]
For this case I believe it was intentional to make it harder to cheese zombies in the military bases - even with sliding down slopes it was otherwise pretty easy to quickly hop up to safety.
