### ISSUE TITLE
Item(s) in hand - Texture bugs (minor)

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#674]
Some of the item's parts are glitching or have some weird looking
Apple Juice(91) - https://youtu.be/Cph7k73t11U
Canned Beef(89) - https://cdn.discordapp.com/attachments/485012628926889984/555024207357149186/unknown.png (Other Canned stuffs are without that "line" on their top.)

We believe these minor glitches came at the same time binocular and mre was glitched too.

**Comment by ImIveooo** [comment]
I've already seen this bug in some players.

**Comment by SDGNelson** [comment]
Thanks, both should be fixed in the next update!
