### ISSUE TITLE
Вопрос чтоза ощибка

### ISSUE THREAD

**Issue by strelok228** [SmartlyDressedGames/Unturned-3.x-Community#679]
TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. - UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. - UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. - UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

MissingMethodException: Method not found: 'System.Reflection.MethodInfo.op_Inequality'. - <Module>..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for <Module>
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

MissingMethodException: Method not found: 'System.Reflection.Assembly.op_Equality'. - com.avirockets.unturned.gateway.RokkyPlugin..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for com.avirockets.unturned.gateway.RokkyPlugin
_4b.‎⁫⁫​‭‎‪‭‍‮‪‭‏‮‪‍‪‌‎‏⁬‍‪⁭​‬‫‬‎‫‮‬‍‎‮‮⁯⁪‮‪‮ (System.Object )
_4b.Awake ()
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

MissingMethodException: Method not found: 'System.Reflection.Assembly.op_Equality'. - com.avirockets.unturned.gateway.RokkyPlugin..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for com.avirockets.unturned.gateway.RokkyPlugin
_4b.‎⁫⁫​‭‎‪‭‍‮‪‭‏‮‪‍‪‌‎‏⁬‍‪⁭​‬‫‬‎‫‮‬‍‎‮‮⁯⁪‮‪‮ (System.Object )
_4b.Awake ()
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

General: Can't add script behaviour . The script class can't be abstract!

**Comment by Trojaner** [comment]
This is a problem with a plugin not with Unturned...

**Comment by RoyIL** [comment]
this error is thrown by AviRockets - RokkyPlugin

**Comment by strongunturned** [comment]
Модуль от AviRockets
