### ISSUE TITLE
NPC Conditions & Rewards for Item Blueprints

### ISSUE THREAD

**Issue by Letgalian** [SmartlyDressedGames/Unturned-3.x-Community#68]
Any chance that we could get the type of condition and reward system for item crafting as there is for NPCs (and objects)? For example, activating a quest by crafting a certain item or certain items requiring a set "Reputation", "Flag_Bool" or "Skillset" value in order to be crafted.

**Comment by SDGNelson** [comment]
Sounds useful! What case did you have in mind?

**Comment by SDGNelson** [comment]
Item crafting blueprints can now use quest conditions and rewards with Blueprint_#_Conditions and Blueprint_#_Rewards.
