### ISSUE TITLE
Workshop Download

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#680]
Hello. In the latest Unturned update, I can't seem to be able to download workshop mods. Here is an image.
![Capture](https://user-images.githubusercontent.com/42988619/54307377-8aa6a280-4599-11e9-9298-b2e72a5ce830.PNG)

**Comment by RoyIL** [comment]
works fine for me

**Comment by SDGNelson** [comment]
Server must have been unable to establish steam connection

**Comment by Trojaner** [comment]
This seems to be a bug on Steams side, as multiple people had reports this to me at the same time, however for all of them it was fixed after some time.
