### ISSUE TITLE
Perspective vehicle in Commands.dat seems to work inconsistently.

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#681]
Setting 'perspective vehicle' in Commands.dat doesn't always work. Sometimes it's changed to 'perspective both' for no apparent reason: 
![image](https://user-images.githubusercontent.com/1404955/54308900-15aa8b80-45e0-11e9-8355-447a5a40b6ed.png)
And I've received reports from players that it seems to work only on the player's first connection to a server. If he relogs, then it acts as if 'perspective both' is used.
![image](https://user-images.githubusercontent.com/1404955/54309019-5d311780-45e0-11e9-872f-9f214c1a625f.png)
I can provide a video if these screenshots aren't enough.

**Comment by SDGNelson** [comment]
Investigating this lead down a rabbit hole, unfortunately I didn't catch the rabbit yet but I did fix up a few things that I think are probably the cause of perspective not being set properly on client like you describe. Probably fixed in the next update, but if it's not feel free to re-open by commenting.

**Comment by Daniil1288** [comment]
@SDGNelson, 'perspective both' currently works in a weird way on Windows servers, one of my acquaintances (who hosts on Windows) has sent me this video: 
[Test_1.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3039793/Test_1.zip)


Perspective both is set in Commands.dat, yet when you join (and when any other player joins) it appears as if the server's first-person mode only. No reports of this issue occuring on Linux, however... hm.

**Comment by SDGNelson** [comment]
Double-checked and using both seemed to be working in vanilla on first join and subsequent join.

I notice in your video that the server join screen shows the perspective as 1P + Vehicle, so I wonder if there are other commands or plugins changing the perspective mode? In the server console it should say "successfully set perspective to both"

**Comment by Daniil1288** [comment]
Might've found the fix, will close for now and reopen if it happens again.
