### ISSUE TITLE
Bug! Video

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#684]
https://dropmefiles.com/epRVu

**Comment by Th3God** [comment]
Please re-upload the video, looks like it got deleted.

**Comment by SDGNelson** [comment]
Yeah video file appears to have expired. If you could re-post on youtube that would be ideal. I'll close for the moment, but if you comment I'll re-open.

**Comment by Th3God** [comment]
@SDGNelson It was The User standing prone on a Floor opening a vault door and trying to go through it resulting in a black screen like being teleported to nowhere.

**Comment by SDGNelson** [comment]
Ah, I got a similar video report in an email recently, maybe also from Vitaxa. Seems to be a few weird physics issues cropping up teleporting players to infinity. (other issue to reset their pos)
