### ISSUE TITLE
Bug with attachments for big weapons if 3rd person camera is disabled

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#685]
If 3rd person camera is disabled and you want to add barrel, for example, on a long weapon - hook is just isn't visible on the screen (example on a photo) 
![image](https://user-images.githubusercontent.com/14231707/54467977-6ad9cf00-4791-11e9-9790-03e65d73bb9c.png)

**Comment by SDGNelson** [comment]
Intention is that the weapon attach animation shows the entire item, most likely a custom or different animation is required.
