### ISSUE TITLE
Train Stops When Hitting Road Loop

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#69]
When a road loop is made, the train seems to stop when the road loops. A good example is on Kent Raceway on Washington. I made trains spawn on that loop but they always stop at the same place on the track. Please fix <3

**Comment by xdlewisdx** [comment]
+1 can confirm

**Comment by SDGNelson** [comment]
Loops are implemented as an extra visual section from the end to beginning of a road so train's don't support going past the end yet. I do want to support it and have opened an issue: SmartlyDressedGames/Unturned-3.x-Community#71
