### ISSUE TITLE
Disabling water using devkit

### ISSUE THREAD

**Issue by TheCubicNoobik** [SmartlyDressedGames/Unturned-3.x-Community#691]
Can be abused to find underwater bases

![20190316232939_1](https://user-images.githubusercontent.com/37713088/54482056-32e09380-4846-11e9-9a1d-50b00e719bd9.jpg)
![20190316232944_1](https://user-images.githubusercontent.com/37713088/54482058-35db8400-4846-11e9-993c-ec58bab2249c.jpg)

**Comment by Kenzim** [comment]
this is a solid yeet
nelson, please fix

**Comment by Johnanater** [comment]
Now this is a yeet indeed.

**Comment by SDGNelson** [comment]
Sneaky! In the next update devkit properties will be read-only outside the editor 😛
