### ISSUE TITLE
Loading Stuck

### ISSUE THREAD

**Issue by Creeper258** [SmartlyDressedGames/Unturned-3.x-Community#692]
When joining a server, sometime you get stuck on #loading-server forever
Because the server restart or shutdown, could you add a system that's make you disconnect server instead of doing ALT+F4 and start back the game

**Comment by SDGNelson** [comment]
If the server restarted or shutdown it should show a timeout warning and automatically return to the menu, so I wonder if something is getting interrupted during loading. I was looking into this earlier today as part of another report, added a bunch of network logging, but wasn't able to replicate.

I wonder if it happens consistently to you, and if it does happen again if you could attach the output_log.txt file from "%userprofile%/appdata/locallow/smartly dressed games/unturned"?

**Comment by Trojaner** [comment]
This also happens if during join some plugin generates exceptions

**Comment by SDGNelson** [comment]
Good point! Recently I've been wrapping plugin delegates in try/catch blocks as I come across them, so I'll do that for all the Provider callbacks.
