### ISSUE TITLE
Debug info from gdb: Could not attach to process Crash - linux depot 304937

### ISSUE THREAD

**Issue by Kenzim** [SmartlyDressedGames/Unturned-3.x-Community#696]
Using ubuntu 18.04 host os (also tried ubuntu 16 host os)
ubuntu 16.04 docker images 
installed lldb and gdb to get rid of initial errors with new depot (304937)
now getting Debug info from gdb: Could not attach to process. If your uid matches the uid of the target process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try again as the root user. For more details, see /etc/sysctl.d/10-ptrace.conf /tmp/mono-gdb-commands.QNaKzm:1: Error in sourced command file:
Changed the config to 0, so that it should be able to bind processes, still cant.
Any ideas?
full trace : https://ptero.co/catulobami.sql

**Comment by Trojaner** [comment]
This is your ordinary .NET 4.6.1-on-Linux crash.
The error message you provided is not an error message, just some information related to the debugging. 

The actual error message is `getcontext failed: Use another register retrieval method?`

This might be linked to https://github.com/ivmai/bdwgc/issues/133, which states that the issue only occurs in x86 but not in x64, so maybe try installing Unturned as 64bit on 64bit image?

**Comment by Kenzim** [comment]
will do bosserinio. i will report back soon.

**Comment by Trojaner** [comment]
Although I am not sure if @SDGNelson actually provides 64bit builds for the headless version as well.

**Comment by SDGNelson** [comment]
More details on 64bit in the other thread
