### ISSUE TITLE
Linux Headless 64bit

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#697]
Is it possible to provide a 64bit version of the headless build?

This might resolve issues with the newer .NET version that many servers faced, as another issue indicates that the recent crashes on Linux servers (when upgrading to .NET 4.6.1) might be related to using 32bit, not Linux itself.

**Comment by D-AIRY** [comment]
Russia map is working on x64 linux headless build with latest mono

**Comment by Trojaner** [comment]
There is no x64 Linux Headless Build:
https://steamdb.info/depot/304934/

There is only old mono x64. You likely installed the x64 depot over the headless depot, so you are still using Unturned_Headless_LatestMono.x86, because there is no Unturned_Headless_LatestMono.x86_64

**Comment by D-AIRY** [comment]
Right, there is no x64 headless on steam, I've made it

**Comment by D-AIRY** [comment]
![64](https://user-images.githubusercontent.com/20150321/54642388-856bbb00-4aa5-11e9-87cc-a0a1fa377888.PNG)

**Comment by Trojaner** [comment]
I don't this can not, as the latest mono runtime is not provided as x64. However there is a chance that your x64 binary loads the mono runtime as x86.

**Comment by D-AIRY** [comment]
Mono is 64 bit too.

**Comment by Trojaner** [comment]
This is hard to believe for me, can you provide proof that its really x64 with .NET 4.6.1?

**Comment by D-AIRY** [comment]
I can setup a demo server if you want to test it

**Comment by Trojaner** [comment]
Or did you download Unity yourself, build a game and replace the files?

**Comment by D-AIRY** [comment]
Yes, it was one of the steps

**Comment by Trojaner** [comment]
Sounds great if it works then 👍

**Comment by Kenzim** [comment]
Dairy please hook us up with this magic. Thanks

**Comment by SDGNelson** [comment]
Historically there hasn't been a 64-bit headless export for linux because there were problems with the 64-bit dedicated server steam API. Several other devs reported the same 64-bit steam API issues to valve several years ago and I kept tabs on the thread for a while, but haven't checked up since then. If it's working okay with steam now on 64-bit linux, then I'll include this in the next update so we can all try it out! Leaving the post open to hopefully hear back how this goes once it's up.

**Comment by Trojaner** [comment]
@D-AIRY 
Could you please explain how you fixed the steamclient.so issue?
At the moment I am getting this error on the 64bit Linux depot:

```
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init(): Sys_LoadModule failed to load: steamclient.so
[S_API FAIL] SteamAPI_Init() failed
```

**Comment by D-AIRY** [comment]
LD_LIBRARY_PATH should point to directory where steamclient.so is

**Comment by Trojaner** [comment]
I already tried this via:
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib64, however it did not manage to get it to work.

**Comment by D-AIRY** [comment]
Is error the same? Also try to put steamclient.so into plugins/x86_64 directory (where libsteam_api64.so located)

**Comment by Trojaner** [comment]
Yes, the error is the same, and yes I have put the steamclient.so there as well.
What exact command did you use for LD_LIBRARY_PATH? Did you use relative or or did you use absolute paths?

**Comment by D-AIRY** [comment]
I use absolute path to plugins/x86_64 dir. I’ll send full command today later

**Comment by Trojaner** [comment]
Thanks, got it working.
My mistake was that LD_LIBRARY_PATH was not in the same line as the executable.

Dockerized it:
https://hub.docker.com/r/imperialplugins/unturned
https://github.com/ImperialPlugins/unturned-docker

**Comment by Johnanater** [comment]
Works for me on Ubuntu 18.04.2 LTS, thanks Trojaner! :D

**Comment by SDGNelson** [comment]
Thanks for setting that up Trojaner, and thanks D-AIRY for investigating this in the first place! Closing the issue, but I will continue the headless 64 builds.
