### ISSUE TITLE
Full Controle of Bones to make better Animations

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#707]
**Hello , i'm Detox i enjoy doing animations , and play around with the character bones in blender but when i use to animate "Spine" it didnt work in game but the arms , hands , hooks work 100% , and all the animations in the game are "all _not all of them_" the same "Spine" Not animated , i don't think that if you Enable all the Bones for full controle of animations that will break the game , "Because or maybe" you didn't animate all of those bones only the "Arms & Legs for Character mouvement , Equip ..." I Would love to have Full Controle that will make other devs animations be better , and more enjoyble , But if this Full Controle of bones will break the game then just bypass it , That will take you alot of time to rework all of your animations .**

**_by the way sorry for my english :) Have a nice day_**

**Comment by Th3God** [comment]
That's going to exist in Unturned ll most likely. Please understand that Nelson is mostly fixing stuff lately, and tweaking few things.

**Comment by BREEZEXPVP** [comment]
Yes i know , I thought it was only a option to enable so if this can't be fixed or enabled , then he can just bypass it that's why i included "_if this can break the game then just bypass it_"

**Comment by SDGNelson** [comment]
Inability to rotate the spine restriction has always bugged me too, and actually in the previous 4.0 devlog post I finally sorted out the spine blending for weapons so it can be animated. Sadly won't be changing in 3, however.
