### ISSUE TITLE
Fake BattlEye ban message with plugin

### ISSUE THREAD

**Issue by glxygmng** [SmartlyDressedGames/Unturned-3.x-Community#714]
Not sure what the root cause of this issue is, so if this does not belong on this repository and I should contact the plugin author about this, let me know.

I am using this plugin to sync bans between servers with a MySQL table: https://harbor.rocketmod.net/plugins/global-ban/

The problem is, once a player is banned from the server and they attempt to reconnect, I assume the plugin kicks/prevents the user from connecting. When they reconnect, a yellow chat message appears says "(Username) was banned by BattlEye". This isn't a real ban, and once the user is unbanned from the server, they can reconnect without issue.

**Comment by Trojaner** [comment]
As you said that's related to the plugin (I assume it was done on purpose
for some reason). You should contact the plugin author or use some other
plugin.

GalaxyGaming <notifications@github.com> schrieb am So., 31. März 2019,
07:00:

**Comment by jatapa** [comment]
the plugin was made so that it sends fake message about them being banned by battleye what is the big deal about that?

**Comment by Johnanater** [comment]
Correct,
https://github.com/fr34kyn01535/GlobalBan/blob/master/GlobalBan.cs#L94

If the Config "KickInsteadReject" is set to false, it will reject their login with the "AUTH_PUB_BAN" rejection, aka a "BattlEye" reject message.

**Comment by glxygmng** [comment]
Interesting, let me test this out.

**Comment by glxygmng** [comment]
That was the solution, thank you.
