### ISSUE TITLE
Can get Transform at UI Effect?

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#717]
I can get Transform from a name GameObject at UI Effect?
I hope you understand me

**Comment by DiFFoZ** [comment]
Can I get a Transform knowing only the Gameobject name? Then change the position (for example, 0,0,0)
```
EffectManager.sendUIEffect(35278, 1235, player.CSteamID, true); 
try 
{ 
Transform UI = GameObject.Find("Name").transform;
UI.position = new Vector3(0, 0 , 0 );
} 
catch
{ 
Logger.LogError("error"); 
}
```
![image](https://user-images.githubusercontent.com/48765566/55406098-a6440e00-5585-11e9-81be-a21499fbbe89.png)

**Comment by SDGNelson** [comment]
You cannot modify those values because the changes are not replicated to clients, but you can find child transforms using Transform.Find.
