### ISSUE TITLE
Craft Mythic

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#719]
Considering allowing crafting random mythical ANY skin e.g. drop, premium, crate.
Problem with using crafting materials is it would be a huge number. Right now materials are ~100 for $3 on market and I don't want to tank mythical value.
One option would be crafting mythic using "mythical crafting materials" which are salvaged from mythical items, and can convert normal crafting materials into mythical crafting materials at a different ratio.

**Comment by JadenSWang** [comment]
I think the second option would be a little nicer, however, I feel like there is enough scrap on the market to still cause quite the depreciation. (unless we're talking 1000 scrap per mythical)
