### ISSUE TITLE
Servers are not displaying on the Internet list

### ISSUE THREAD

**Issue by JOSE007831** [SmartlyDressedGames/Unturned-3.x-Community#725]
I have been trying it and doesnt work also i have portfoward all and everything is ok but i dont know how to fix it

**Comment by RoyIL** [comment]
I'm pretty sure the SteamServers are / were down.

**Comment by JOSE007831** [comment]
That what means?

**Comment by SDGNelson** [comment]
One common issue is not opening port +1 and +2 (typically 2015, 20716 and 27017). Master server list does work, however

**Comment by JOSE007831** [comment]
Ooo thanks nelson you are the best i only open the 27015 and the 27016

**Comment by JadenSWang** [comment]
Wait you need +2 as well?

**Comment by GazziFX** [comment]
> Wait you need +2 as well?

With +1 works fine
![IMG_20230826_083829.jpg](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/43498426/f64b53e3-6bef-473b-894f-899641c78e35)
