### ISSUE TITLE
Adding a 'Mass Scrap' button?

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#728]
With today's update adding mythical crafting I bought a thousand skins of the common rarity.
Now I either have to write some sort of a script or spend a good hour scraping them manually.
Would it be possible to add a mass scraping button? For example, 'Scrap all commons'/'Scrap all uncommons'/etc.

**Comment by SDGNelson** [comment]
It would definitely be useful, but considering there are already lots of reporting of accidentally salvaging items even with the "type SALVAGE to confirm" I don't think I can add it to the vanilla game. It would actually be really straightforward to make a c# program using steamworks.net to bulk-salvage + bulk-craft, if anyone wants to start that and needs some pointers feel free to ask. Just exchange the item-to-salvage with ItemDefID+1,000,000 to create crafting materials.
