### ISSUE TITLE
Separate file .mastebundle update in Unturned(Similar to function key "Page up")

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#734]
You can make it so that when you start the game, can update the modified .masterbundle file and everything related to it.
Something like a key: Page UP
Thus, the game will allow to work faster with mods, and update those files that need to be updated.
This will allow to test and fix  mods faster.

**Comment by glxygmng** [comment]
Agreed. Especially to new modders who encounter lots of errors, it would be super helpful!

**Comment by SDGNelson** [comment]
Tested to double-check, and the reload assets function (Page Up) does seem to properly reload master bundles. Assets.unloadAllMasterBundles is called prior to the asset loading steps.
