### ISSUE TITLE
[Old Glitch] Being able to see through the floors from under them

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#735]
Crouching under high floors that reached out the max level of depth on an oblique terrain (or even air, if you build up plates on something until it reaches the floor/roof) lets you see through the floor if you're looking up, and this way it's giving you a good view inside bases (similar to the mostly-fixed wall glitch).

**Comment by SDGNelson** [comment]
Saw you closed this, I didn't test/reply yet but mostly because I'm not sure what I'll do about it yet.

**Comment by Th3God** [comment]
Oh, alright then.

**Comment by SDGNelson** [comment]
About time I did something to sort this out!

In the next update the first-person view does a sphere-cast upwards to prevent the camera from going through objects, for the most part.

There were a lot of factors affected by this which was why it slipped off the radar for so long. Unfortunately the 3rd-person animation and eye heights do not match the capsule height, but many maps are designed with the existing capsule height in mind. Many game systems also rely on the static eye heights not being affected by stuff like camera offset, e.g. even the server uses the expected aim position for hit tests. 

Doing it by simply moving the camera does then cause side effects, e.g. aim is slightly offset when crouching directly underneath a slanted surface, but I think that is a rare enough case that nobody will notice.

Thankfully in 4.0 with the stances implemented recently all of the animations, capsules and cameras are carefully tuned to match each other properly.
