### ISSUE TITLE
Possible way to patch TP glitch (?)

### ISSUE THREAD

**Issue by Th3God** [SmartlyDressedGames/Unturned-3.x-Community#736]
This glitch is old (You know, User X standing prone/crouch under a structure then User Y teleports to him gets inside/above it).

What if the game detects User X attempting to glitch while being prone/crouch under a structure and if User Y teleports he's automatically put on prone so he won't be able to glitch (User Y must be standing still in order to glitch)

**Comment by SDGNelson** [comment]
This should be patched as of a few updates ago, the teleport functions were changed to check for available space before teleporting. Has it happened recently?

**Comment by Th3God** [comment]
@SDGNelson Just today.

**Comment by JadenSWang** [comment]
just make it so teleport requires the target player to be standing

**Comment by SDGNelson** [comment]
Is it a plugin teleport command e.g. tpa? For that case, the plugin code should be calling Player.teleportToPlayer which checks for overlap space

**Comment by Th3God** [comment]
Yes it is.

**Comment by jatapa** [comment]
@Th3God then if it is plugin tell the plugin creator to fix their tpa system

**Comment by Th3God** [comment]
@jatapa even your servers are still prone to tp glitches

**Comment by jatapa** [comment]
Now ik that but most of the people who do it get banned

**Comment by Th3God** [comment]
I will close this thread for now then.
