### ISSUE TITLE
Belgium server issue

### ISSUE THREAD

**Issue by Fili7000** [SmartlyDressedGames/Unturned-3.x-Community#741]
Dunno if someone reported it yet but here it is
still blocks servers after the latest update.

KeyNotFoundException: The given key was not present in the dictionary. - System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <cfc149f8218b496788d8493c87de777a>:0)
Pathfinding.Util.TileHandler.CutPoly (Pathfinding.Int3[] verts, System.Int32[] tris, Pathfinding.Int3[]& outVertsArr, System.Int32[]& outTrisArr, System.Int32& outVCount, System.Int32& outTCount, Pathfinding.Int3[] extraShape, Pathfinding.Int3 cuttingOffset, UnityEngine.Bounds realBounds, Pathfinding.Util.TileHandler+CutMode mode, System.Int32 perturbate) (at <220f0cb8b17d419dafc6ec6e600a691e>:0)
Pathfinding.Util.TileHandler+<LoadTile>c__AnonStorey1.<>m__0 (System.Boolean force) (at <220f0cb8b17d419dafc6ec6e600a691e>:0)
AstarPath.ProcessWorkItems (System.Boolean force) (at <220f0cb8b17d419dafc6ec6e600a691e>:0)
AstarPath.PerformBlockingActions (System.Boolean force, System.Boolean unblockOnComplete) (at <220f0cb8b17d419dafc6ec6e600a691e>:0)
AstarPath.Update () (at <220f0cb8b17d419dafc6ec6e600a691e>:0)

**Comment by DiFFoZ** [comment]
#738

**Comment by SDGNelson** [comment]
There was a vehicle loading issue when missing rigidbody serverside on Belgium (as referenced in #738), but this exception doesn't seem to break anything. Since it's specific to the navmeshes / cuts setup on Belgium I don't want to dig into debugging it - hundreds of lines long internal function of 3rd party library.

**Comment by aman7** [comment]
i am having the same issue with linux, server is up with this error, but i cant join the server.
