### ISSUE TITLE
Effect Command (Feature Request)

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#742]
Add a way to test UI Effects in singleplayer.

**Comment by SDGNelson** [comment]
Good idea, sounds useful! Smarter than the way I tested them in the past. 🤦‍♂️ 
Added in today's patch EffectUI command which can take just the ID to spawn for you, or all the tokens to format into the text separated by forward slashes. For example "/effectUI 148/cat/sat/mat" spawns the test one

**Comment by XanderCodes** [comment]
A clear command may also be useful, and one to change widget flags. May as well introduce the whole toolset.

**Comment by educatalan02** [comment]
Set *lifetime 60* at your effect.dat
And your effect will stay for 60 seconds.

**Comment by XanderCodes** [comment]
> Set **lifetime 60** at your effect.dat
> And your effect will stay for 60 seconds.

Yes I understand this, but for things like custom menus, I usually just set the lifetime to 99999, so an easy clear command for quickly testing in single player would be amazing.
