### ISSUE TITLE
Unturned Master List Error

### ISSUE THREAD

**Issue by JOSE007831** [SmartlyDressedGames/Unturned-3.x-Community#744]
Hi i have try many ways but my server is not in the master list

i already do this:
- wait 8 hours with the server open
- open from the port 27015 to 27017 and the 27015 as the main port
- disable battleye

and i am using ovh hosting and they were telling me that, that was an error from the game but i dont care in that

Thanks <3

**Comment by JOSE007831** [comment]
also if someone can help me with this i will pay 5$ for the help <3

**Comment by Ascivv1** [comment]
What OVH service are you using?

**Comment by JOSE007831** [comment]
Dedicate servers in ovh us

**Comment by Ascivv1** [comment]
Which model specifically? Game? Enterprise?

**Comment by JOSE007831** [comment]
Game

**Comment by JOSE007831** [comment]
64 ram, i7

**Comment by Mithallas** [comment]
This isn't a help forum to troubleshoot problems specific to you
This is a place to report actual issues with the game.

**Comment by Ascivv1** [comment]
The Game OVH servers have an issue where they don't show up on the Internet list in Unturned. We (as in the unturned community) can't help you with this, and it is your duty to report this to the OVH support team.

**Comment by UncleLYHME** [comment]
- Try disabling the Windows Firewall (if applicant) and the Game Firewall.

For the Game Firewall on the Panel click on IP > Then Click on the 3 dots. Then you can go from there.

Then check if this solves it.

**Comment by JOSE007831** [comment]
i cant see the 3 dots

**Comment by JOSE007831** [comment]
but i already deactivate the game firewall and open the ports manually from the console

**Comment by UncleLYHME** [comment]
Alrighty, thank you for getting back to me.

**Comment by JOSE007831** [comment]
:D
