### ISSUE TITLE
Players dying (not really) and respawning in same place (with all items) a sec~ later

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#746]
I guess topic says it all. Not sure whats the problem but only started getting report about situations like this recently.
![image](https://user-images.githubusercontent.com/14231707/55840317-b898eb80-5b33-11e9-8847-3832bceb9473.png)

Also, if player stays afk on the server for some time - all other players looks freezed for that player. Relogging to server fixes it but still - pretty strange and annoying issue.

**Comment by glxygmng** [comment]
What RocketMod plugins do you have on your server? Can you include your `Config.json` as that has a setting for enabling keep-inventory.

**Comment by Johnanater** [comment]
I've also had a few reports about this, none recently though.

**Comment by SDGNelson** [comment]
Made some minor changes for the next update, but from the description I think one of the most probable causes is an exception thrown during one of the died delegates. Do you have a full log file e.g. UnityDebug_* serverside from when one of these happens?

**Comment by SDGNelson** [comment]
Will close for now, but feel free to comment to re-open.
