### ISSUE TITLE
 Visibility of servers

### ISSUE THREAD

**Issue by ZzNashzZ** [SmartlyDressedGames/Unturned-3.x-Community#747]
Some servers do not appear in the list of servers (internet, history, friends) or otherwise appears in some but not all as before, this arises from a plugin problem? or could it be from the game?

**Comment by ImIveooo** [comment]
Probably a port that is not open (27017) ?

**Comment by ZzNashzZ** [comment]
my server has port 27015 ...

**Comment by JOSE007831** [comment]
I have the same problem and i open all the needed ports from 27015 to 27017

**Comment by ZzNashzZ** [comment]
I bought host in 3 different places and by chance the same thing happens

**Comment by JOSE007831** [comment]
@SDGNelson xd now we are 2

**Comment by ZzNashzZ** [comment]
I have 3 other friends that the same thing happens :p

**Comment by JOSE007831** [comment]
ok now we are 5 xd

**Comment by arcanouie** [comment]
the same happens to me @SDGNelson

**Comment by TheMagicLord** [comment]
Some servers do not appear in the list of servers (internet, history, friends)

**Comment by laufiom** [comment]
Some servers do not appear in the list of servers (internet, history, friends) I need Help @SDGNelson

**Comment by Excars89** [comment]
the same thing happens with my server

**Comment by EliasXD321** [comment]
The same thing happen to me, pls @SDGNelson fix it!!

**Comment by Fernando173cardenas** [comment]
the same thing happens with my server

**Comment by Zgamerxd4** [comment]
there a problem about the servers do not appear in friends on the internet etc ... will it be some problem of the unturned?

**Comment by DIAZ25266** [comment]
Some servers do not appear in the list of servers (internet, history, friends) or otherwise appears in some but not all as before

**Comment by Dengario** [comment]
Its the same stuff all over and over again, I can't join to my favourite servers because of this :'c

**Comment by Ascivv1** [comment]
I currently run about 17 servers and my servers all show up on the internet. For some odd reason, certain hosts have an issue where their servers don't show up on the internet. It is most likely an issue with the way their host has their firewall setup. My recommendation would be to rent from a host that you know works, like LYHME Hosting or Venelium Hosting. (This isn't an advertisement but purely a suggestion)

**Comment by Ascivv1** [comment]
Also, please don't tag Nelson. He is likely busy with other stuff at the moment.

**Comment by Fernando173cardenas** [comment]
Some servers do not appear in the list of servers (internet, history, friends) or otherwise appears in some but not all as before

**Comment by 1Kyle1** [comment]
I have a problem with my server, and it does not appear in the list of: ° Internet, History and Favorites ° only if I enter by connection appears, I do not know if it is my or the game's problem, some plugin or port help @SDGNelson

**Comment by VitsGamer** [comment]
I have the same problem as everyone, that this server is not because it does not appear on the internet and friends, it only appears when I put the ip or in favorites

**Comment by L4falafa** [comment]
I have the same problem, my server do not appear in list of server on Internet :,c

**Comment by BabyKawaiiLatina** [comment]
Same problem as everyone here.

**Comment by SDGNelson** [comment]
Did anyone here have a server that DID show up in the past, and now no longer shows up?

I'm fairly confident that the game's implementation of the steam server browser works fine, and the steam server browser itself has gone largely unchanged for at least a decade. One indication that something is wrong with the game is if it shows in the steam client's server browser (right click steam -> servers) properly, but not the in-game list.

Otherwise, throughout the game's history on steam since 2014 there have always been reports that the server list doesn't work and then it turns out someone's ports or firewall were restricting it and it works fine.

**Comment by ZzNashzZ** [comment]
So the problem is the host that the server has? 🤔

**Comment by termsgames** [comment]
Yeah Nelson is correct.

This would be an issue with your server hoster as I personally haven't had any issues and I know a lot of other people that haven't.

**Comment by Ascivv1** [comment]
I also don't have any issues with my servers not showing on the internet. This is likely an issue with your host.

**Comment by ZzNashzZ** [comment]
already contact the support to see about the ports or the FireWall, Thank you very much to all who posted your suggestions or help

**Comment by JOSE007831** [comment]
Hi i still having this problem i have try in many ways also i disable all firawall things and open all ports in linux but still doesnt work 5$ to the one who can fix my problem <3

**Comment by JOSE007831** [comment]
![image](https://user-images.githubusercontent.com/36491401/56436820-ccb2ba80-62a2-11e9-8fbd-7044dae98fc1.png)
