### ISSUE TITLE
Simplification managers

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#748]
Hello,i work with Managers(StructureManager,VehicleManager or other)
The fact is that I want to change the server logic in the root, and I would like to have the opportunity to disable managers (VehicleManager.instance.gameobject.enabled) and create my own. eg:
![image](https://user-images.githubusercontent.com/32962870/56013829-a08cbc00-5d2d-11e9-8333-20e56099168e.png)
  If  StructureManager   disabling, then after the completion of the work VehicleManager does not work /vehicle, after the appearance of the car the player cannot sit in it ...
This method is the most convenient way...
This will radically simplify the creation of new modes.

**Comment by VitaxaRusModding** [comment]
My structure manager is like on the standard manager, but giving more functions:
![image](https://user-images.githubusercontent.com/32962870/56018902-5233e900-5d3e-11e9-890a-502912924597.png)
I do loading system houses, how in samp

**Comment by Eatric** [comment]
Harmony?

**Comment by VitaxaRusModding** [comment]
@Eatric  In my opinion it is not convenient)

**Comment by Trojaner** [comment]
I agree that you should use Harmony to patch the functions to your needs.

**Comment by SDGNelson** [comment]
Harmony is the best option, as others have said. Those classes weren't designed to be switched out, however of course in retrospect I would design these features to be more replaceable. Ce la vie.
