### ISSUE TITLE
onCheckValid  called when a player disconnects

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#75]
`Provider.onCheckValid` is fired when a player disconnects; which causes Rockets `OnJoinRequested` to fire at wrong place too and that causes plugins to malfunction (mostly NREs since the expected player does not exist) .

Related RocketMod issue:
https://github.com/RocketMod/Rocket/issues/922

**Comment by SDGNelson** [comment]
This delegate is for checking bans like RocketObserver, but I've adjusted it to be called only once an associated pending join player is found.

**Comment by Trojaner25** [comment]
It might be for a different purpose but many plugins use it to change player metadata from pending player, because this is the only event executed before the player exists
