### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by TheMagicLord** [SmartlyDressedGames/Unturned-3.x-Community#758]
Hello I came here because my server does not currently appear by Friends or the Internet, I do not know if it's an error of Unturned or some error of a plugin or host If you can solve it I appreciate it @SDGNelson

**Comment by educatalan02** [comment]
#747 
Close the issue. Becouse that's the same.

**Comment by JOSE007831** [comment]
No, dont close nothing there the people type their problem more than here

**Comment by educatalan02** [comment]
It's the same issue...

**Comment by JOSE007831** [comment]
so close this one xd

**Comment by SDGNelson** [comment]
Closing since it's a duplicate of #747 as others have said
