### ISSUE TITLE
[Feature] Event for text change on sign/book/note and who changed it.

### ISSUE THREAD

**Issue by megoesrawr** [SmartlyDressedGames/Unturned-3.x-Community#759]
An event for text change on sign/book/note and who changed it. This would be a nice to have for devs to see who changed the text.

**Comment by SDGNelson** [comment]
Makes sense, added onModifySignRequested!

**Comment by MrKwabs** [comment]
Could you add `oldText` so we can compare it to what was written before as currently you can only get the text that it is changing to

**Comment by MrKwabs** [comment]
Could you add `oldText` so you can compare to what was written before?

**Comment by SDGNelson** [comment]
It's called before changing text, so you can use the current value of text on the sign component

**Comment by MrKwabs** [comment]
I've looked at that but still appears to be the same.

**Comment by SDGNelson** [comment]
onModifySignRequested is called before tellUpdateSign, so ref text is the new value and sign.text is the old value

**Comment by MrKwabs** [comment]
That was my thoughts, but when using Sign.text it displayed the same value as what it is being updated to (ref text).
