### ISSUE TITLE
New error with each connection

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#762]
After recent update getting this error on log after player connects to a server (not sure if its harmful or not though):
```
[4/15/2019 11:26:23 PM] [Error] MissingMethodException: Method 'SDG.Unturned.Provider.reject' not found. - Rocket.Unturned.U+<>c.<bindDelegates>b__16_4 (Steamworks.ValidateAuthTicketResponse_t callback, System.Boolean& isValid) (at <d97a7b6e07e84732934032fc52b1dcfa>:0)
SDG.Unturned.Provider.handleValidateAuthTicketResponse (Steamworks.ValidateAuthTicketResponse_t callback) (at <4980f79d84974c9e8d35df850e15f4b4>:0)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.Provider:handleValidateAuthTicketResponse(ValidateAuthTicketResponse_t)
SDG.Unturned.Provider:onValidateAuthTicketResponse(ValidateAuthTicketResponse_t)
Steamworks.Callback`1:OnRunCallback(IntPtr, IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
SDG.SteamworksProvider.SteamworksProvider:update()
SDG.Unturned.Provider:Update()
```

**Comment by Ascivv1** [comment]
I also get this error too. This seems to be harmless.

**Comment by SDGNelson** [comment]
Looks like a plugin is calling reject directly (which it shouldn't be). The method gained an optional explanation string parameter, but I guess it can't load the older assemblies. Would be nice if that worked. Anyway, plugins should be listening for the onCheckValid or onCheckValidWithExplanation delegates.

**Comment by MrKwabs** [comment]
This also means plugins that reject players don't actually reject them and they can still join.

**Comment by baranmod** [comment]
ohh, I guess cheaters wave is coming then.. :D

**Comment by Trojaner** [comment]
@SDGNelson I suggest keeping the old and the new method at the same time:

I don't remember the method signature, but something like this should work and would not need code changes on your side:
```
void reject(..., string explanation)
{
}

void reject(...)
{
   Reject(..., null);
}
```

**Comment by SDGNelson** [comment]
Plugins can reject players. That's the intention of onCheckValid or onCheckValidWithExplanation. They are called at the same time as VAC check, BattlEye check, etc, so plugins can reject players. Explanation allows a reason e.g. "Custom anti-cheat doesn't like you"

In some cases I've kept the old method, but for optional parameters it would be nice if it would bind how I'd expect. Will try to remember for the future.

**Comment by Johnanater** [comment]
Although it appears to be harmless, rebuilding Rocketmod 4 fixes this.

**Comment by Trojaner** [comment]
@SDGNelson I know that there are alternative methods which should be used instead, but the point is to not break the plugins using it wrongly (including RocketMod 4), as they are often critical ban plugins which now do not work anymore.

**Comment by termsgames** [comment]
I believe you can resolve that error with GlobalBan if you enable **KickInsteadReject** inside the configuration file.

**Comment by Kenzim** [comment]
@SDGNelson @Trojaner Can you not just set a default value for the explanation, so that old plugins work, and you specifying a reason is not mandatory?

**Comment by Raxul257** [comment]
Same error appears when I'm using onCheckValid or onCheckValidWithExplanation directly.
