### ISSUE TITLE
Add storage interaction event

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#769]
There should be an event to prevent players from adding or taking items from a storage container.

Thanks :)

**Comment by SDGNelson** [comment]
For a second thought this was the 4.x issues list, I was working on this a day or two ago!
Completely irrelevant but 4's items call ReleaseItemOwnership on storage interface to ask permission for removal.

**Comment by SDGNelson** [comment]
Not really a great place to put an event for individual add/remove items, but I've added an onOpenStorageRequested event for the next update which will let you restrict storage access at least.
