### ISSUE TITLE
Cycle lock

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#770]
You could add some way to block the cycle day and night.

**Comment by SDGNelson** [comment]
Maybe I'll change it so that zero does not progress time at all

**Comment by Johnanater** [comment]
That would be nice for rp stuff.

**Comment by SDGNelson** [comment]
When I commented earlier I was thinking the day/night cycle used a timer how you might expect, but frustratingly it all relies on essentially servertime modulo duration. Chances of breaking somethere here is high so I'm going to hold off for this next update, but I may tackle rewriting it later on.
