### ISSUE TITLE
Unturned servers causing BSOD?

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#771]
https://forums.tomshardware.com/threads/bosd-after-bsod-after-bsod.3471349

People here are speculating that Unturned.exe - the servers I am running are causing frequent BSODs

**Comment by Th3God** [comment]
@RainOfPain125 For how long did you get these?

**Comment by RainOfPain125** [comment]
@Th3God I think I reinstalled windows ~2 weeks ago in an effort to fix the BSODs to no avail

I have been running these servers just fine for the past year.

**Comment by Th3God** [comment]
1) Windows 10 Pro/Home editions had horrible updates lately slowing down, freezing and eventually locking up PCs causing a lot of trouble.

2) Do you run out of memory often? Since you have 16 GBs of physical RAM installed you could increase the page file (default is +2 GBs taken from your storage drive).

3) Scan for malware.

Most common possible causes have been said in your thread on Tom's Hardware so there's not much left to say. I might be missing something, but I will eventually remember lately and come back here if so. :)

It's not Unturned doing this by the way.

**Comment by Th3God** [comment]
You shall opt for a stable Windows 10 edition like Enterprise LTSC. You can defer updates indefinitely, and even so the updates you get are much more tested & stable than regular Pro/Home editions. Telemetry can be set to even lower levels and it lacks Cortana, Edge, Microsoft Store and pretty much all of the pre-installed junk. I have never got a BSOD in my entire life with Windows until I upgraded from 7 to 10 Pro. After 1 week of 10 Pro I had to jump on Enterprise LTSC and it's a whole new world.

**Comment by Th3God** [comment]
I might need your event logs.

1) Open up Event Viewer
2) Expand Windows Logs
3) Click on System

On the right you will see logs with different types of icons. Click only on icons with Error or Critical tags and screenshot them together with the description below. Select each of them until they start repeating (they start over again from every boot-up).

System Reliability Monitor 

1) Search for View reliability history.
2) Click on each day it took records from and screenshot them.

**Comment by RainOfPain125** [comment]
@Th3God They start repeating? confused but I took screenshots of *every* critical / error, and *every* day with an error

I don't think you expected this many errors https://imgur.com/a/XuwlFrF

**Comment by RainOfPain125** [comment]
> It's not Unturned doing this by the way.

I mean.. since I halted hosting the errors have completely disappeared. This definitely seems to be something Unturned-related, or at the very least something wrong between windows-Unturned or another thing related to.

**Comment by Th3God** [comment]
Surprisingly the Reliability monitor is much more worrying than Event Viewer here. DistributedCOM, Service Account Manager and EventLog errors can be safely ignored, it's just Windows 10 panicking over small things. Such errors didn't exist in previous versions of Windows. The earliest Critical issue seems to have taken place on 3/27, the day you installed W10 probably?

**Comment by Th3God** [comment]
@TheRainOfPain125 In one of your screenshots I see a Windows crash saying *Hardware error* on 4/12/2019, can you please expand View tehnical details?

**Comment by RainOfPain125** [comment]
Source
Windows

Summary
Hardware error

Date
‎4/‎12/‎2019 3:36 PM

Status
Not reported

Description
A problem with your hardware caused Windows to stop working correctly.

Problem signature
Problem Event Name:	LiveKernelEvent
Code:	193
Parameter 1:	804
Parameter 2:	ffffffffc000009a
Parameter 3:	108
Parameter 4:	fffff802a2278860
OS version:	10_0_17763
Service Pack:	0_0
Product:	768_1
OS Version:	10.0.17763.2.0.0.768.101
Locale ID:	1033

**Comment by Th3God** [comment]
This one is pretty bad. *Shut down unexpectedly* is the result of a power loss / BSOD caused by faulty software usually, because I see that you have lots of them that prove how often you've got BSODs, but *Hardware error* is related to one of your components and you might need to replace it.

**Comment by Th3God** [comment]
@RainOfPain125 Downlowd this small benchmark:
https://www.userbenchmark.com/

Beside benchmarking your main PC components it also tells how healthy they are, if they overheat or underperform in any way. The benchmark takes 120 seconds on avg. (depends on how many components there are to benchmark e.g. multiple storage drives). At the end of the benchmark it will open your browser with the results link. Post that link here.

**Comment by Th3God** [comment]
Honestly this whole situation is sooo twisted. I don't know where to begin with exactly so I take everything as it comes in my mind, complete anarchy. There's still several other errors possibly contributing to your BSODs (like BugCheck, event 1001). Too many factors involved and I don't know *which* one is the root of all of this. Judging by your Reliability monitor logs, it is not only about Unturned but other games and the OS crashing itself too because of some hardware failure.

**Comment by Trojaner** [comment]
This issue, like almost all BSOD issues, is a hardware/driver issue, it is not related to Unturned.
A normal program like Unturned can not cause BSODs (it can only trigger them, but a driver or hardware failure causes it actually).

**Comment by RainOfPain125** [comment]
@Th3God I've used it before, and commonly use User.Benchmark for comparisons between parts

https://www.userbenchmark.com/UserRun/16365346

@Trojaner I know Unturned most probably can not make BSODs, but yes, it could trigger them through a driver. I don't see how my graphics driver has anything to do with a simply console window.

**Comment by Trojaner** [comment]
I don't know as well, but that's what I found when searching for it.

**Comment by RainOfPain125** [comment]
I have the latest and most up-to-date graphics drivers from Nvidia

**Comment by Th3God** [comment]
@RainOfPain125 BugCheck is more common for AMD CPU users like you, in this case it's most likely caused by Windows Updates who delivered a faulty update for your CPU and some Microsoft MVP said that disabling Fast Boot gets rid of it. 

Your results from UserBenchmark look fine overall, the main 1TB HDD looks a bit slower but that's because it's half full (458GB free) and Windows 10 doesn't like HDDs in general.

**Comment by Th3God** [comment]
I don't know what's causing this, but it can be Windows Update or the HDD.

**Comment by RainOfPain125** [comment]
@Th3God Disabled fast boot

My PC automatically has 21,000MB paging file. Far larger than what you asked for.

**Comment by Th3God** [comment]
@RainOfPain125 Your CPU is alright, I didn't say that it's overheating or such.

**Comment by Th3God** [comment]
Sorry but I ran out of ideas.

**Comment by Th3God** [comment]
It's clearly something on the hardware side, judging by the logs after you fresh installed Windows 10 some weeks ago it got BSODs from day one, nothing has changed from before. Multiple games kept crashing and drivers kept crashing together with the OS.

One last thing to do is update BIOS. It is not recommended to update BIOS unless you have a serious problem, which happens to be your case.

**Comment by RainOfPain125** [comment]
@Th3God BIOS is fully updated

**Comment by SDGNelson** [comment]
I don't have anything helpful to add, but popping in to say thanks to Th3God and Trojaner for helping! 🥇

**Comment by Coopyy** [comment]
people really out here reinstalling windows over a lego game

**Comment by Kenzim** [comment]
Could always try who crashed
