### ISSUE TITLE
WorkshopDownloadIDs.json is no longer functioning for people.

### ISSUE THREAD

**Issue by ForeverBluee** [SmartlyDressedGames/Unturned-3.x-Community#773]
Hey, I've had an issue where installing new mods as of late through the .json file does not work, when the server boots it'll say "Failed to install workshop mod (ID here)!" while all the previous older mods work (which is because they are cached in the Workshop folder of the server client, most likely. I know this because I deleted this folder and tried again only to see ALL my mods failing to install rather than the 5 new ones I've attempted to install ever since the problem began.) 

**Before people tell me ways to fix this, no this is not a issue on my side. Something is wrong with the game.** I know this because MANY other servers on Lyhme hosting have had this issue and all my Unturned servers were suddenly affected. 

Right now the only way to fix it is to install workshop mods the old, lame way. Manually.

Alexr03, part of the management team with Lyhme says that the issue is not on their side either, and the issue is on Unturned.

**Comment by ToucansBootlegServerDeveloper** [comment]
I am having the same issue.

**Comment by ForeverBluee** [comment]
I've looked into it more and the mods do indeed download their contents in the Workshop folder of the server directory (particularly in the Steam folder rather than "Content" or "Maps", which makes sense). Which is weird because some of the mods will download the contents while some won't. 
![image](https://user-images.githubusercontent.com/49925452/56620456-ca6f9980-65dd-11e9-8a5e-71bb1cd3844f.png)

I have 16 mods listed in WorkshopDownloadIDs.json but only 12 bothered to download and cache in Workshop > Steam > Downloads > 304930. 

For anyone having this issue, what host do you have? In case it's a game-wide issue or not.

**Comment by Ascivv1** [comment]
Is there an error you receive associated with WorkshopDownloadIDs.json?

**Comment by ForeverBluee** [comment]
> Is there an error you receive associated with WorkshopDownloadIDs.json?

Nope, nothing. Only error that comes up is in console, when downloading the mods it'll say it is downloading the mods, then end with "Failed to download workshop mod: 87777565" or whatever.

**Comment by WhiteOwll** [comment]
It may be a problem with Unturned since I'm having the same problem. My community uses a dedicated hosting machine, but it doesn't even download the mod (Like you mentioned), it just says in console "Failed to download workshop mod: {ID}!"

**Comment by SDGNelson** [comment]
Suddenly received reports of this in a few places over the past day or two. Has this only started happening for you since then? Feels like the most likely cause is a workshop serverside change.

Unturned logs that when the DownloadItem SteamUGC callback is posted and the result is not OK. While the client does log the reason, unfortunately the server does not which I'll change.

It might be helpful to inspect Steam's workshop_log.txt for details on the failures.

**Comment by ToucansBootlegServerDeveloper** [comment]
I checked the logs and it says "No connection to content servers." Is there anything I can do to fix that?

**Comment by ToucansBootlegServerDeveloper** [comment]
A quick update on the situation: The server having issues is hosted through lyhme. I decided to copy the WorkshopDownloadIDs.json file from the lyhme server and paste it in my testing server hosted on my computer. All of the workshop mods installed correctly. Any ideas why this is? I will also ask lyhme about this.

**Comment by SDGNelson** [comment]
In the next update I've adjusted the server to log the failure reason, but I think this must have been some temporary maintenance on the workshop because reports quickly stopped.

**Comment by julien040** [comment]
**Hello, I have a bug a little different.
That is to say that my map is installed, my NPC too but my mod does not want to download.
I checked, the workshopdownloadID syntax is good but the workshop does not install:**

```
[12/05/2019 07:25:52] [Info] 3 workshop items to install ...
[12/05/2019 07:25:52] [Info] Submitting workshop item query ...
[12/05/2019 07:25:52] [Info] Workshop query yielded 3 result (s)
[12/05/2019 07:25:53] [Info] This server is allowed IP for Workshop downloads: "IP server
[12/05/2019 07:25:53] [Info] "workshop 1" has no download IP restrictions
[12/05/2019 07:25:53] [Info] "workshop 2" has no download IP restrictions
[12/05/2019 07:25:53] [Info] "workshop 3" has no download IP restrictions
[12/05/2019 07:25:53] [Info] 3 workshop item (s) to download ...
[12/05/2019 07:25:53] [Info] Downloading workshop item: "workshop 1"
[12/05/2019 07:25:53] [Info] Downloading workshop item: "workshop 2"
[12/05/2019 07:25:53] [Info] Downloading workshop item: "workshop 3"
[12/05/2019 07:25:54] [Info] Successfully downloaded workshop item: "workshop 1"
```

**I am on Linux, and I had a similar bug on Windows too
I can download my workshop on my pc, it is functional but does not work on the server**

**Comment by ForeverBluee** [comment]
> In the next update I've adjusted the server to log the failure reason, but I think this must have been some temporary maintenance on the workshop because reports quickly stopped.

I'm still having this issue. I've resorted to manually downloading the mods and installing them myself but after clearing out and deleting the Workshops folder and letting it regenerate it's contents and using WorkshopdownloadIDs.json again, instead of giving errors it just give nothing.

Basically looks like this now: 

```
[12/05/2019 07:25:52] [Info] 3 workshop items to install ...
[12/05/2019 07:25:52] [Info] Submitting workshop item query ...
[12/05/2019 07:25:52] [Info] Workshop query yielded 3 result (s)
[12/05/2019 07:25:53] [Info] This server is allowed IP for Workshop downloads: "IP server
[12/05/2019 07:25:53] [Info] "workshop 1" has no download IP restrictions
[12/05/2019 07:25:53] [Info] "workshop 2" has no download IP restrictions
[12/05/2019 07:25:53] [Info] "workshop 3" has no download IP restrictions
[12/05/2019 07:25:53] [Info] 3 workshop item (s) to download ...
[12/05/2019 07:25:53] [Info] Downloading workshop item: "workshop 1"
[12/05/2019 07:25:53] [Info] Downloading workshop item: "workshop 2"
[12/05/2019 07:25:53] [Info] Downloading workshop item: "workshop 3"
```
and that's it. It doesn't say the mods successfully installed. I go to check ingame to see that indeed the mods did not download.

**Comment by SDGNelson** [comment]
Today I checked up on this on the Steam developer forums, and it looks like several other games have been having the same issues over the same time period related to specific download regions. I've chimed-in that we're having the same problem. Hopefully Valve addresses it sooner rather than later.

As a temporary workaround: it does function properly if a steam client is signed-in on the dedicated server machine. :/

**Comment by joemisfit** [comment]
Thank you @SDGNelson!

**Comment by SDGNelson** [comment]
Heard back a response this morning and have been providing more logs.

My impression is that the problem lies with retrieving which server to download the items from; sometimes the server gets a 404 from the download server.

Will keep you guys posted!

**Comment by SDGNelson** [comment]
Anonymous downloads should now be functioning properly in 3.30.3.1. Please let me know if it does or does not work for you!

**Comment by MonsterGeeks** [comment]
It works on my server

**Comment by ykpon** [comment]
Hi, have same trouble. Server long time waiting when downloading and output:
1800206054 'Nexel I PVP' queued for download
1799326422 'Nexel I PVP Content' queued for download
2 workshop item(s) to download...
Downloading workshop item: 1800206054
Download workshop item 1800206054 failed, result: k_EResultTimeout
Downloading workshop item: 1799326422
Download workshop item 1799326422 failed, result: k_EResultTimeout


Server send such request:

> http://level3.cdn.steampipe.steamcontent.com/depot/304930/manifest/3113707038229759748/**5(null)**

And getting code 404. I think 5(null) on end it something wrong.

**Comment by educatalan02** [comment]
You're running the Dedicated App?

**Comment by ykpon** [comment]
> You're running the Dedicated App?

Are u me?
Yes, i am running dedicated server 304930.

**Comment by Trojaner** [comment]
The dedicated server app is 1110390 not 304930

**Comment by ykpon** [comment]
Same problem on 1110390.

**Comment by ykpon** [comment]
No fix?

**Comment by SDGNelson** [comment]
Are you sure you switched to the standalone dedicated server ykpon?
In the meantime closing this since I'm 99.9% sure that it's resolved.
