### ISSUE TITLE
Barricades.dat corrupting every 3rd~ restart

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#774]
Getting this error every 3rd-4th server restart. Basically forces me to remove barricades.dat file to launch server again. What could be the problem? First got on Russia map, now on any other map too.

```
[Error] ArgumentException: The Object you want to instantiate is null. - UnityEngine.Object.Instantiate[T] (T original) (at <2686255ceb974cc2967520f770810585>:0)
SDG.Unturned.BarricadeTool.getBarricade (UnityEngine.Transform parent, System.Byte hp, System.UInt64 owner, System.UInt64 group, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, System.UInt16 id, System.Byte[] state, SDG.Unturned.ItemBarricadeAsset asset) (at <1c60162165a4477d9588d3bbeccaf506>:0)
SDG.Unturned.BarricadeManager.spawnBarricade (SDG.Unturned.BarricadeRegion region, System.UInt16 id, System.Byte[] state, UnityEngine.Vector3 point, System.Byte angle_x, System.Byte angle_y, System.Byte angle_z, System.Byte hp, System.UInt64 owner, System.UInt64 group, System.UInt32 instanceID) (at <1c60162165a4477d9588d3bbeccaf506>:0)
SDG.Unturned.BarricadeManager.loadRegion (System.Byte version, SDG.Unturned.River river, SDG.Unturned.BarricadeRegion region) (at <1c60162165a4477d9588d3bbeccaf506>:0)
(wrapper dynamic-method) SDG.Unturned.BarricadeManager:load_Patch1 ()
SDG.Unturned.BarricadeManager.onLevelLoaded (System.Int32 level) (at <1c60162165a4477d9588d3bbeccaf506>:0)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext () (at <1c60162165a4477d9588d3bbeccaf506>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2686255ceb974cc2967520f770810585>:0)
```

**Comment by Trojaner** [comment]
Plugins could cause this as well.

**Comment by baranmod** [comment]
well, I am using same plugins on 4 servers, only one of them is having problem though

**Comment by SDGNelson** [comment]
Looks like the savedata is valid and loading a valid barricade, however the barricade is missing the "Clip" game object. In large part the game logs these missing file type things so I'll have to look into why this one isn't and fix it up. Anyway in the meantime if you can narrow down what custom barricade this server is using that the other servers aren't that should point to the problem.

**Comment by baranmod** [comment]
it would be kinda hard to find out because I'm using same mods in two servers (one is getting error, another - not) so I believe its a matter of time when someone places that barricade in server which not getting this error yet?

**Comment by SDGNelson** [comment]
Same items in both servers, but one server the specific item gets repeatedly placed (every 3rd restart)?

**Comment by baranmod** [comment]
possible, but I believe it already would've been placed in both servers because all kits,spawn tables, airdrop tables etc. are exactly the same in both server

**Comment by strongunturned** [comment]
@baranmod как перезапускаете сервер и какой хостинг Вы используете?

**Comment by baranmod** [comment]
I don't speak russian, sorry

**Comment by strongunturned** [comment]
@baranmod Try shutting down the server through the console and use the save command before shutdown.

**Comment by baranmod** [comment]
thats what I'm always doing, doesn't help

**Comment by SDGNelson** [comment]
Looking closer the missing game objects should be logged with something along the lines of "XYZ missing 'Clip' GameObject", but I've also made the fixes in the next update to not try instantiating those null objects.
