### ISSUE TITLE
Could you add a onVehicleCarjacked event?

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#776]
I'm asking this for rp / pve servers again :D Many servers have problems with people abusing carjacks to flip every vehicle around they can find and often the vehicles get destroyed.
It would be nice if it will give you the player and the vehicle and a bool for shouldAllow so you can controll it with plugins.
Thanks.

**Comment by Johnanater** [comment]
Just imagine adding acceleration to the vehicle...

**Comment by SDGNelson** [comment]
Added onVehicleCarjacked event for the next update!
