### ISSUE TITLE
Mythical Upgrade

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#777]
Exchange to convert mythics to use the particle tag and "Vintage Mythical" tag
- [ ] Preserving custom tags on item like kill counter
- [ ] Redirecting remaining mythic unboxes
- [ ] What happens if we just change the item type?
- [ ] Ask Valve about perhaps applying to entire item database

**Comment by Coopyy** [comment]
yeah fascinating, but can you work on your better game then trying to improve a scuffed one, thanks
