### ISSUE TITLE
Load Workshop or Map will has fatal error in Linux of mono。

### ISSUE THREAD

**Issue by Cencx** [SmartlyDressedGames/Unturned-3.x-Community#781]
how to solve this problem？

**Comment by Cencx** [comment]
Log : https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/780#issuecomment-487372646

**Comment by Ascivv1** [comment]
I get that issue all of the time. Unfortunately, there is no fix that I know off.

**Comment by SDGNelson** [comment]
From the other thread it sounds like a system specific issue, but the recommendations are if you're using 32-bit linux to try Unturned_Headless_LatestMono.x86 or ideally upgrade to 64-bit linux and use Unturned_Headless.x86_64.
