### ISSUE TITLE
New ModHook

### ISSUE THREAD

**Issue by TheCubicNoobik** [SmartlyDressedGames/Unturned-3.x-Community#782]
OnDay
OnNight
OnFullMoonStart
OnFullMoonEnd
OnRainStart
OnRainEnd
OnSnowStart
OnSnowEnd

Edit: That's what I need: https://gist.github.com/TheCubicNoobik/41a289b2552ee184e5372b6a915f8223

**Comment by rube200** [comment]
You already have these events:
```
DayNightUpdated onDayNightUpdated;
TimeOfDayChanged onTimeOfDayChanged;
MoonUpdated onMoonUpdated;
RainUpdated onRainUpdated;
SnowUpdated onSnowUpdated;
```
You dont need more than those.

**Comment by TheCubicNoobik** [comment]
@rube200 I can't use it in Unity

**Comment by Bradler26** [comment]
Why are you tryna use events in unity in the first place lol?

**Comment by SDGNelson** [comment]
Sounds useful, added for the next update!
