### ISSUE TITLE
TextField input RPC

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#783]

**Comment by Dolphinchik** [comment]
Help me if you can <3

**Comment by SDGNelson** [comment]
Added onEffectTextCommitted event in the next update!

**Comment by Dolphinchik** [comment]
THANK YOU

**Comment by Dolphinchik** [comment]
😘😘😘😘😘


пн, 6 мая 2019 г., 5:47 Nelson Sexton <notifications@github.com>:
