### ISSUE TITLE
Misc map options

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#785]
- [x] Loadouts for non-arena
- [x] Specific items disappear on death

**Comment by danaby2** [comment]
nice

**Comment by joemisfit** [comment]
Hey @SDGNelson,
I'm not sure if your meaning modifying the map editor on top of the deaths and loadouts, however if at all possible could there be an implementation to transfer item spawns, zombie spawns, and all of the different nodes from map to map, as some of us have maps that we grow out of like PEI to PEI Large, etc and it would be nice to retain those same characteristics and just add on as needed.

**Comment by SDGNelson** [comment]
Added Spawn_Loadouts per-map option and Should_Drop_On_Death true/false per-item option for next update

**Comment by SDGNelson** [comment]
@joemisfit 

Should be possible by copying the Spawns folder between maps, or individal spawn file types e.g. Spawns/Zombies.dat

**Comment by joemisfit** [comment]
Thank you!
