### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#788]
![Captura de pantalla (13)](https://user-images.githubusercontent.com/34221626/57575660-f51b7800-744e-11e9-86ac-a6007c93699c.png)
![request](https://user-images.githubusercontent.com/34221626/57575662-f6e53b80-744e-11e9-8652-ebf78706b970.png)

Option to disable this HUDS with plugins.

PD: DeathEffect & Home/Respawn buttons too

**Comment by danaby2** [comment]
how will you respawn without a respawn button

**Comment by educatalan02** [comment]
With some code & EffectManager you can make custom Respawn Buttons

**Comment by Trojaner** [comment]
I am not sure but I think ESC does not work in respawn screen. If thats the case I would enable it there if these two buttons are gone.

**Comment by SPYREX03** [comment]
Cool!

**Comment by SDGNelson** [comment]
Allowing the pause menu to be used while dead has been on my to-do for a while, but quite a few places in the UI assumed otherwise. Tomorrow's update doesn't have disabling these menus (yet?), but the pause menu now works with the respawn menu

**Comment by educatalan02** [comment]
Looks good. But there's a bug with It #862

**Comment by SDGNelson** [comment]
There was some further work toward this by adding EPluginWidgetFlags in the past update. My intention is to add a VanillaDeathUI flag for use with disablePluginWidgetFlag sometime in August.

**Comment by SDGNelson** [comment]
After quite a long time, this is finally going to be supported.
Here's the EPluginWidgetFlags for the next update:

	/// <summary>
	/// 32-bit mask granting server plugins additional control over custom UIs.
	/// Only replicated to owner.
	/// </summary>
	[System.Flags]
	public enum EPluginWidgetFlags
	{
		None = 0,

		/// <summary>
		/// Enables cursor movement while not in a vanilla menu.
		/// </summary>
		Modal = 1 << 0,

		/// <summary>
		/// Disable background blur regardless of other UI state.
		/// </summary>
		NoBlur = 1 << 1,

		/// <summary>
		/// Enable background blur regardless of other UI state.
		/// Takes precedence over NoBlur.
		/// </summary>
		ForceBlur = 1 << 2,

		/// <summary>
		/// Enable title card while focusing a nearby player.
		/// </summary>
		ShowInteractWithEnemy = 1 << 3,

		/// <summary>
		/// Enable explanation and respawn buttons while dead.
		/// </summary>
		ShowDeathMenu = 1 << 4,

		/// <summary>
		/// Default flags set when player spawns.
		/// </summary>
		Default = ShowInteractWithEnemy | ShowDeathMenu,
	}

To disable it in the next update call disablePluginWidgetFlag with ShowDeathMenu.
