### ISSUE TITLE
Server crashing error

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#789]
Happened twice in a week. Server kinda crashes yet console is still up which is preventing server from restarting (during this error server is out of browser, players can't connect anymore). 

https://pastebin.com/i2LpZg9A

**Comment by SDGNelson** [comment]
Assuming that the last exception in that log is spamming the log, it looks like an auto-save plugin in FixedUpdate is having trouble saving. The save method was changed recently to add onPreSave and onPostSave, so if the plugin is using harmony to modify the method that could potentially be the issue.

**Comment by Trojaner** [comment]
The saves are done by RocketMod 4 which does not use Harmony.
All it does is calling SaveManager.save() on a periodic schedule.

**Comment by baranmod** [comment]
Can confirm. Error is spamming each 60 seconds (period I've set in rocket config to save data)
