### ISSUE TITLE
Scope glass being shown while in vanish

### ISSUE THREAD

**Issue by megoesrawr** [SmartlyDressedGames/Unturned-3.x-Community#791]
There is a weird issues with scopes that will show the glass bit, white and in the corner. this happens if the gun is on your back or equipped.
Proof: 
![304930_screenshots_20190516200134_1](https://user-images.githubusercontent.com/7830406/57894849-88b9c380-7816-11e9-814d-06aee3657510.jpg)

(That is the 10x scope from Ireland but, it also happens with modded scopes)

**Comment by Charterino** [comment]
lol how weird is that

**Comment by SDGNelson** [comment]
When working to remove Rocket's requirements on injecting into the game's assembly I added canAddSimulationResultsToUpdates which stops new movement updates from being sent to other clients, but it could be that a custom vanish command is implemented differently. By default vanilla doesn't have a vanish command.
