### ISSUE TITLE
Unturned doesn't render certain effects after the 3.28 update

### ISSUE THREAD

**Issue by Fili7000** [SmartlyDressedGames/Unturned-3.x-Community#794]
Apparentely, after the 3.28 update unturned doesn't seem to render effects that uses transparent textures, i have been experimenting with some effects for several days and they always worked bad, i checked out some effects of the same type that worked fine some months ago but now they don't anymore, since unturned changed unity version, this is all i came up with.
Any solutions?
![unknown](https://user-images.githubusercontent.com/42879002/57986028-e39a2780-7a6f-11e9-9bc8-2ef4e1d9b7e7.png)
![unknown (1)](https://user-images.githubusercontent.com/42879002/57986030-e9900880-7a6f-11e9-85a0-7526b55209a6.png)
![unknown (2)](https://user-images.githubusercontent.com/42879002/57986046-1e03c480-7a70-11e9-98bd-96d400532143.png)

**Comment by SDGNelson** [comment]
Did you find a solution? Off the top of my head it could be:
1. Asset_Bundle_Version less than two replaces all shaders with standard for Unity 4/5 content
2. Which shader was used, standard fade/transparent + emissive should be safe at least.

**Comment by Fili7000** [comment]
Yeah i solved it, i used asset bundle version 2 and different shaders, it works.
Thanks for the answer anyway!
