### ISSUE TITLE
How to use sendUIEffectVisibility and sendUIEffectText

### ISSUE THREAD

**Issue by RU-QBER** [SmartlyDressedGames/Unturned-3.x-Community#796]
`
EffectManager.sendUIEffect(17001, 13001, unturnedPlayer.CSteamID, true);
EffectManager.sendUIEffectText(13001, unturnedPlayer.CSteamID, true, "select_text_1", "Test");
                EffectManager.sendUIEffectVisibility(13001, unturnedPlayer.CSteamID, true, "bottom", false);
`

![Screenshot_5](https://user-images.githubusercontent.com/45338196/58167054-2c362880-7c9c-11e9-821f-e85020671e6c.jpg)

How to change the text and visibility of the UI element?
When you run this code, only the UI appears, but no changes are made to it.

**Comment by Adamv21** [comment]
Take a look at String.Format use {index (eg 0)} for placeholders In the effect text

**Comment by RU-QBER** [comment]
> Take a look at String.Format use {index (eg 0)} for placeholders In the effect text

You mean this function?
`sendUIEffect(ushort id, short key, CSteamID steamID, bool reliable, string arg0)`

**Comment by SDGNelson** [comment]
There's a stupid bug on my part with them in the current version, but it is patched in the next update. Sorry!
