### ISSUE TITLE
Error after masterbundle export

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#797]
Getting this error while trying to log into server. I recently re-exported all mods to master bundles. Had no problems with same mods exported as separate bundles. 
https://pastebin.com/eJsU023M

Basically can't connect to server or even open map with editor/devkit (getting stuck on loading server).

Some zombies (including mega) have some of the outfits from those masterbundles equipped.

Also, had some issues with masterbundle pants/shirt because for some reason it refuses to read texture files from sub folders (now must be in a same folder as prefab for masterbundle). However, I fixed all those pants/shirt, yet above error is still happening.

**Comment by baranmod** [comment]
Some edit: unsubscribed all packs with armors which are used on mega zombies. Then opened map in editor without a problem. Removed outfits from mega zombies. Then subscribed to all packs again and opened map in editor again without errors.

**Comment by SDGNelson** [comment]
All of the curated maps and the official content are using master bundles so clothes definitely work with them, but it does look like there's an exception there when trying to equip the clothes whose textures failed to load.

If you look earlier in the log file there should be entries listing which of the items are unable to load the Shirt / Pants textures. The texture should be in the same directory as each Item.prefab

**Comment by SDGNelson** [comment]
Almost slipped my mind to come back to this: now the zombie textures are still built properly when the shirt/pants textures are null.
