### ISSUE TITLE
Driveable Trains

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#8]
- [x] Level config trains and tracks association
- [x] Indestructible vehicle options
- [x] Show road index in editor
- [x] Train engine type
- [x] Fix jitter sampling road curves
- [x] Smooth replication
- [x] Physics blocks movement
- [x] Cargo train vehicle
- [x] Horn noise
- [x] Train noises
- [x] Move zavod train off main line
- [x] Fix upside down passenger seats

**Comment by V1CeNtE** [comment]
nice

**Comment by SDGNelson** [comment]
https://i.imgur.com/tojGvdg.png
