### ISSUE TITLE
Can you make a method?

### ISSUE THREAD

**Issue by HellGodness** [SmartlyDressedGames/Unturned-3.x-Community#800]
Hi! can you make a method for drop equipment  For example: player.Player.equipment.drop()

**Comment by Eatric** [comment]
For what?

**Comment by Game4Freak** [comment]
I think such a function is already in the game. Take a look in the CSharp-Assembly.dll or something like that

**Comment by SDGNelson** [comment]
For the moment the closest helper function would be to call askDropItem with slot 0 or 1.
