### ISSUE TITLE
Hostile animal option

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#801]
- Attracted to gunfire
- Increased detection range?

**Comment by Spebby** [comment]
Maybe also a neutral animal? Has to be attacked first.

**Comment by SDGNelson** [comment]
It turns out there was a bug with the offense behavior: in the next update those animals will properly investigate noises they hear rather than fleeing.

Re neutral: domestic animals like cows have that behavior in "ignore" mode.
