### ISSUE TITLE
nelson why did you cheat on me :(

### ISSUE THREAD

**Issue by absolutenothing** [SmartlyDressedGames/Unturned-3.x-Community#802]
[really nelson why did you cheat on me you tell me that unturned 3 is good but all you do is work on unturned 4 plz fix game noslon](https://i.imgur.com/bQIqiuV.png) :[

**Comment by RoyIL** [comment]
pull up on them nissans'
ayyy I had to say dat

**Comment by Game4Freak** [comment]
Nelson is still working on Unturned 3. Take a look in the patch-notes

**Comment by absolutenothing** [comment]
nelson :(
