### ISSUE TITLE
Request for adding a sendUIEffectSprite / sendUIEffectImage function

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#804]
It would be nice to be able to change the Sprite / Image in a UIEffect with plugins :)

**Comment by Dolphinchik** [comment]
I agree, it would be nice to add the ability to change the position of any elements.

**Comment by SDGNelson** [comment]
Added (finally) in this coming update! The function is: sendUIEffectImageURL
This is something I want to further improve with the netcode rewrite, but should service in the meantime.
