### ISSUE TITLE
Server out of memory on startup

### ISSUE THREAD

**Issue by marquikpo7** [SmartlyDressedGames/Unturned-3.x-Community#806]
![Screenshot_102](https://user-images.githubusercontent.com/16739451/58600846-95014000-825c-11e9-9c4d-f2c7d21b30df.png)
(Sorry for my english, I'm spanish) Hello, I have a rocket server, I'm using a host with 2048MB. When I start up the server it runs out of memory and get errors in the console. It was working perfectly until I uploaded a map. So I deleted the map but it still getting out of memory. Once it fails, the memory is restarted to 0 and the server starts again and fails again.
![Screenshot_100](https://user-images.githubusercontent.com/16739451/58600547-777fa680-825b-11e9-80aa-9800dcaab5e9.png)
![Screenshot_101](https://user-images.githubusercontent.com/16739451/58600561-823a3b80-825b-11e9-9a48-b5265090dfcd.png)

**Comment by SDGNelson** [comment]
If installing that specific map caused out-of-memory issues then chances are it contained a Bundles folder which may still be getting loaded depending on how it was deleted. If you placed the folder manually that's probably not the problem, but if you installed using the workshop auto-download but didn't remove it from the IDs list then the map will still be installed.
