### ISSUE TITLE
Modded claim flags?

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#807]
Is it possible to do modded claim flags? I've tried to make some simple barricade with a claim flag dat. For some reason it didn't show claim bounds. So I believe it should contain something else? Maybe could give example file for it? Thanks!

**Comment by PandahutMiku** [comment]
It would also be nice to set the default claim flag's distance in config.json

**Comment by SDGNelson** [comment]
Included for this week's update!
