### ISSUE TITLE
Make crafting materials a stackable item in steam inventories.

### ISSUE THREAD

**Issue by Kenzim** [SmartlyDressedGames/Unturned-3.x-Community#808]
Looking at pages of scrap is bloody annoying sometimes trying to get to the stuff  I want to see. Possible to make them stack like how steam's gems do?

**Comment by SDGNelson** [comment]
Ideally yes. Apparently auto-stacking _might_ be added at some point, but in the meantime the game code would need to stack after receiving the new item which is not ideal (double refresh)... but may as well add it anyway.

**Comment by SDGNelson** [comment]
Added this for the next update, and it's now a fairly smooth process. After any drop/exchange/refresh the client submits a consolidation request, so for new items it merges instantly-ish but it will take a while to merge old stacks.
