### ISSUE TITLE
Request for a onNPCVendorUIOpened and onNPCVendorUIClosed event

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#812]
Would be nice to get the player who opened / closed it so we could add a custom ui overlay or other things :D

**Comment by SDGNelson** [comment]
Off the top of my head I don't think the client tells the server when open/closing this, but I'll check it out

**Comment by SDGNelson** [comment]
Forgot to follow up on this, but the server does not know about vendor status. What sort of custom UI did you have in mind?

**Comment by Game4Freak** [comment]
Like a UI to buy item / other stuff with currency of some plugins or like to buy vehicles / houses or other stuff. But vendor UI event is not needed if there is any other way to detect when you talk to a npc.

**Comment by SDGNelson** [comment]
I think that was the original intention of NPCEventReward. So for example a dialogue option of "OpenGame4Freak Vendor" would grant an NPC event which your plugin listens for and spawns the UI accordingly. It looks like there isn't a version of that delegate with a player parameter yet though, so I'll add that for the next update. What do you think?

**Comment by Game4Freak** [comment]
Sounds nice :)

**Comment by SDGNelson** [comment]
Awesome! Closing now that it was added, feel free to reply and I'll re-open.
