### ISSUE TITLE
EffectManager | add new method to createUIEffect

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#813]
Can I add a method to createUIEffects? I need to add a component. Need to use Harmony?

**Comment by EveryWhere1337** [comment]
пошел нахуй))

**Comment by Eatric** [comment]
@EveryWhere1337 Stop this shit, это не то место, где ты можешь себе такое позволить. Зачем ты делаешь это здесь? Иди в диск или ВК и там шути свои шутки
