### ISSUE TITLE
Flying in jet causing people to get run over

### ISSUE THREAD

**Issue by Kenzim** [SmartlyDressedGames/Unturned-3.x-Community#814]
Sometimes, if i'm flying a jet over someone, they get run over for no apparent reason. I can record it and upload it if you needed.

**Comment by SDGNelson** [comment]
With the vanilla jet? Hmm if the jet is flying toward the ground and then pitches up the hitbox might sweep through a poor innocent bystander, but the server shouldn't be extrapolating its position into hitting people 🤔

**Comment by SDGNelson** [comment]
Sorry if you get a notification for this, but I will close this issue now because it might have been fixed or is otherwise really stale. Would like to update vehicles to use physics hits rather than box sweeps at some point.
