### ISSUE TITLE
Add not_break_wheels option

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#816]
Add an option (config.json) so that you can not break the wheels of vehicles with melee weapons.
Example: not_break_wheels

**Comment by SDGNelson** [comment]
This can be set per-vehicle with:
Tires_Invulnerable
Or are you thinking specifically a global config for it?

**Comment by MonsterGeeks** [comment]
It should be possible to add an option in the .dat of the vehicle or the server so that one can not break the wheels with weapons of melee but that one can destroy them with the firearms.

**Comment by SDGNelson** [comment]
Since that's a very specific case, I think the best option is to use a plugin to hook the onDamageTireRequested event and prevent tire damage with melee.
