### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by darkplatinum** [SmartlyDressedGames/Unturned-3.x-Community#817]
MacOS Mojave, Unturned fresh download (and tried reinstall), game application and freezes immediatly. No UI shown. How do I play the game?

**Comment by SDGNelson** [comment]
Quite later after your original post, but I double-checked this afternoon and was able to load in and play on a 2016 macbook air. This week's update has some improvements to the loading process to stop it from stalling as long which may be where it's not responding on your computer.
