### ISSUE TITLE
Request For Projectile

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#821]
_i'm making a Modpack based on  the univers of One piece about devil fruits Powers_
so in my way making this mod 
So  each time i'm making a Projectile , **i come across the same probleme over time 
Its About the Hitbox** , So the thing is i could'nt make this  like a simple bullte in Unturned example
Maplestrike bullets shoots & realy good at the Players character  & zombies & animals ... 
But. **When i try to make that it would'nt show my Particles that i made , Its too fast and i coud'nt slow it down like a Projectile**. _Even with in the .dat Json  **"Ballistic_Force 500"_** _its to fast to see the particles and the effects of it_ , But it hits realy good the hitbox is perfect. 

**The probleme with the Projectiles Now is the Hitbox it could only be a Trap** so in that cas that will kill the hitbox and it works Only  with touched Surface example when try to shoot a zombie or player with a  devil fruits power example fire it will only hit him if the projectiles touchs the ground or a object and the probleme with that is your own attacks & powers Hits You if u near by a objects plus the hitbox is not good not accurate like a bullet.

if there is something to change to make it better is making a **.dat Json Data** Example 

**Should_Owner_Be_Hit & Bool  = "True  / False"**
**if this put then projectile can hit Skull : Projectile_Penetrate_Skull**
**if this put then projectile can hit Spine :  Projectile_Penetrate_Spine**
**if this put then projectile can hit Arm : Projectile_Penetrate_Arm**
**if this put then projectile can hit Leg : Projectile_Penetrate_Leg**

Or

**Making the projectile Hit Detection more better can hit players & zombies & animals without touching or hiting a surface With the Tag and Layer On : Item if its Tag and layer : Trap then it should be only Surface & Ground hits only if its Item then Hitbox changes to Same Hit detection same as the Bullets**

_if there is Other ways to do it , Let's say like the bullet hit detection working on projectile then tell to me down , I would love to see my mod 100% working with better Hitbox detection Thanks_
![20190605015715_1](https://user-images.githubusercontent.com/40163506/58921949-385cc400-8739-11e9-9556-0321a87b4529.jpg)
_

**Comment by BREEZEXPVP** [comment]
i need only this for projectiles
###  **Should_Owner_Be_Hit** =   **true / false**

**Comment by SDGNelson** [comment]
If I understand correctly: you would like the option to use a different layer so that the projectile can hit zombies, animals, players, etc, but need the Should_Owner_Be_Hit option to prevent damaging yourself in that case?

**Comment by BREEZEXPVP** [comment]
yes

**Comment by BREEZEXPVP** [comment]
Yes i think that would help alot of  my work i was making this mod for like , 2 months from now but that was the only probleme with it it was the hitbox to hit zombies animals players and  should owner be hit to make it that you can't hurt yourself thanks !

**Comment by BREEZEXPVP** [comment]
and sorry for my english i'm not a expert of it :3

**Comment by SDGNelson** [comment]
For this week's update I've adjusted the projectile hits to ensure it's not a child of the player, so it should not be possible to hit yourself (aside from blast radius). Additional per-magazine options for projectiles are also on the to-do list https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/818
