### ISSUE TITLE
Jump's height

### ISSUE THREAD

**Issue by Charterino** [SmartlyDressedGames/Unturned-3.x-Community#823]
Hi, Nelson. A couple of updates ago you've added ability to change player's gravity and speed. If you edit gravity, player will just fall slower, but not jump higher. I think you should change the jump height so it depends on gravity.

**Comment by BREEZEXPVP** [comment]
Maybe it should works like this 

**Character_Movement_Speed**  "**Float**" =  _Min_ 0.1  to _Max_ 100.0 
**Character_Movement_Jump_Height** =  _Min_ 1  to _Max_ 100
_Other things_
**Character_Stats_Health** =  _Min_ 1  to _Max_ 1000

**Comment by Charterino** [comment]
Nah. The default 'Jump' value is 7. Also there is field called 'pluginGravityMultiplier'. I think that the actual just height should be calculated like '7 * 1 / pluginGravityMultiplier'. So, if you have gravity set to 0.5, you will get jump height 14. And if you have gravity set to 2, you will get jump height 3.5.

**Comment by erik7302** [comment]
> Nah. The default 'Jump' value is 7. Also there is field called 'pluginGravityMultiplier'. I think that the actual jump height should be calculated like '7 * 1 / pluginGravityMultiplier'. So, if you have gravity set to 0.5, you will get jump height 14. And if you have gravity set to 2, you will get jump height 3.5.

I think it should be separate (pluginJumpMultiplier)
1 What if I want to have the jump x2 but not fall slower?
2 What if I want 100 or 200 of jump height? and it is calculated with gravity, the fall speed will be too slow

**Comment by Charterino** [comment]
Yes. Then add separeted field as you said.

**Comment by Dolphinchik** [comment]
Also, this multiplier * pulls * player

**Comment by SDGNelson** [comment]
Added in the next update! ```sendPluginJumpMultiplier```
