### ISSUE TITLE
Gas mask despawning

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#824]
if you are wearing a gas mask and your inventory is almost full, it will disappear if you die, and if your inventory is more than half empty, it doesn't disappear. i have tested this on france and russia map. i am getting alot of complaints from players about it.

**Comment by SDGNelson** [comment]
The HUD element for the gasmask is not disappearing, or the item is not dropping? It may be the drop chance option, or a plugin modifying which items drop. I double-checked tonight and there isn't much gasmask related code.
