### ISSUE TITLE
Vehicle Gas Siphoning 

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#825]
It would be nice if we had a config.json option to disable gas siphoning for locked vehicle - Vehicles IRL can have lockable gas cap and this would be good for RP.

It would also be nice to have an event for when vehicles get siphoned from for plugin purposes.

Thanks for your time

**Comment by SDGNelson** [comment]
Will do! Been gradually adding more vehicle delegates on request

**Comment by ferrazf** [comment]
Thanks Nelson!

**Comment by SDGNelson** [comment]
Implemented for this week's updated!
