### ISSUE TITLE
Option to disable any asset loading

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#827]
This would be really helpful for plugin devs.

We have to restart the server very often and sadly it takes a lot of time for it to startup. We often do stuff that does not need us to join the server and hence do not need most of the servers features.

My request would be some startup parameter or a config variable to be added so Unturned can instantly start by skipping loading of vehicles, workshop, map and similar assets.

**Comment by SDGNelson** [comment]
Makes sense, will add

**Comment by SDGNelson** [comment]
Next update has the "-SkipAssets" command-line flag to disable loading .dat, asset bundles, workshop, etc.

**Comment by Trojaner** [comment]
Thank you very much :)
