### ISSUE TITLE
UI Text 

### ISSUE THREAD

**Issue by Dolphinchik** [SmartlyDressedGames/Unturned-3.x-Community#832]
Now the text in the UI is displayed incorrectly and is cut off; it is impossible to make it dynamic now only if you statically add text to unity. Fix it please.

**Comment by TheCubicNoobik** [comment]
Can confirm it works fine. In your text component set the text to {0} and horizontal overflow to overflow.

**Comment by Dolphinchik** [comment]
I will recover, if the text is more than ~ 89 characters, then this bug occurs

**Comment by Dolphinchik** [comment]
![image](https://user-images.githubusercontent.com/34001190/59356486-5ed6bc80-8d42-11e9-833a-7a60755baaa2.png)

Horizontal Overflow - Overflow

**Comment by Dolphinchik** [comment]
![image](https://user-images.githubusercontent.com/34001190/59359851-892b7880-8d48-11e9-9aff-c7adf6cb5b1a.png)
More can be displayed question marks.

**Comment by Trojaner** [comment]
None of the issues you mention are Unturned specific.

**Comment by Dolphinchik** [comment]
For your information, before the update it was displayed correctly.

**Comment by SDGNelson** [comment]
Maximum replicated text length is currently 255 UTF-8 encoded bytes, so if the text changed slightly it may have exceeded the limit even though it appeared a low number of codepoints. For large amounts of text sendUIEffectText might be useful.
