### ISSUE TITLE
Serverside issue with workshopids.json

### ISSUE THREAD

**Issue by joemisfit** [SmartlyDressedGames/Unturned-3.x-Community#833]
Hello @SDGNelson,

I noticed that workshopids.json is still broken since one of the updates (I forgot which update broke it.) However, I did notice that steamcmd does download unturned workshops manually, so I'm not quite sure what the issue might pertain to with it being broken since workshops are being constantly updated as of late.

As of now when you add workshopid's it adds them to the appworkshop_304930.acf file and shows them downloading in console without error or ip restrictions, yet they aren't in the folder they associate with. 

I am currently running a Windows 10 System for testing and I've also tested it on (2) Dedicated Servers running Windows 2016.

Thank you!

**Comment by SDGNelson** [comment]
Updated this on the original thread here: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/773
