### ISSUE TITLE
Option for shoot delay

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#834]
Not sure if anyone asked for this in the past or if its even possible feature to add but would be cool to have option to add delay for gun to shoot (player presses and hold left mouse button and gun only shoots after specified time). Also, option for a "delay" sound fx for bundles which would only be triggered when holding mouse until shoot.

**Comment by Dolphinchik** [comment]
Why?

**Comment by joemisfit** [comment]
@Dolphinchik He runs a heavily modded pvp server that has op items, so I think he wants to use the delay as a probability of not being able to shoot guns perhaps?

**Comment by baranmod** [comment]
For overall variety of possibilities for modding. If its possible and doesn't take tons of time to add it - I don't see a problem here then

**Comment by joemisfit** [comment]
Pretty much!

**Comment by SDGNelson** [comment]
Can see this being a lot of fun for weapons like Mei's alt-fire or the R8, so implemented for tomorrow's update! Was straightforward to add thanks to existing burst fire mode
