### ISSUE TITLE
New Events for Plugin-Makers

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#838]
Hello, dear Nelson, i want ask you to add new events - onZombieDamaged , onAnimalDamaged
with argument like: ref ushort dmg

**Comment by Trojaner** [comment]
Doesn't this already exist somehow?
I think it was exposed via an enum on the damage event, wasn't it?

**Comment by Eatric** [comment]
Yeap, it is

**Comment by SDGNelson** [comment]
Implemented for this week's update!
