### ISSUE TITLE
Toss at the moment of teleportation

### ISSUE THREAD

**Issue by Dolphinchik** [SmartlyDressedGames/Unturned-3.x-Community#839]
At the moment the teleportation method looks like this: 

- 

	public void askTeleport(CSteamID steamID, Vector3 position, byte angle)
		{
			if (this.channel.checkServer(steamID))
			{
				base.transform.position = position + new Vector3(0f, 0.5f, 0f);
				base.transform.rotation = Quaternion.Euler(0f, (float)(angle * 2), 0f);
				this.look.updateLook();
				this.movement.updateMovement();
				this.movement.isAllowed = true;
				if (this.onPlayerTeleported != null)
				{
					this.onPlayerTeleported(this, position);
				}
			}
		}

I want to offer my alternative for ease of development: 

       

-  
         public void askTeleport(CSteamID steamID, Vector3 position, byte angle, float UpTo = 0.5f)
         {
             if (this.channel.checkServer(steamID))
             {
                 base.transform.position = position + new Vector3(0f, UpTo, 0f);
                 base.transform.rotation = Quaternion.Euler(0f, (float)(angle * 2), 0f);
                 this.look.updateLook();
                 this.movement.updateMovement();
                 this.movement.isAllowed = true;
                 if (this.onPlayerTeleported != null)
                 {
                     this.onPlayerTeleported(this, position);
                }
             }
         }.
 

Thanks.

**Comment by Trojaner** [comment]
"Let's just break some random plugins"

**Comment by Dolphinchik** [comment]
> Also you could just set position y -0.5 + your own offset, I don't see why this is needed...

Probably easier to set 1 parameter, not?

**Comment by Trojaner** [comment]
> Probably easier to set 1 parameter, not?

Not really + backward compatibilty remains...

**Comment by Dolphinchik** [comment]
"I'm just stupid, forget it dude"
