### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#848]
Good day, Nelson!

I would like to ask you to consider some functions that would diversify the game)

1. New condition for NPS - to arrive in a certain zone. This zone can be set in the map editor, when a player enters this zone, he gets a certain flag for the quest.

For example, you need to explore a specific area for the construction of a survival camp.

2. Enter the official localization of the game: Russian, German, French and so on.

3. Add new faces for the character, both for people who bought a gold account, and for those who did not. Old faces are very tired and not enough new ones.

For example, the face of a dead person - crosses instead of eyes. (or hold a contest for new faces?)

4. New features for the map editor and devkit. For example, generate a random landscape for the map or change the game settings during editing (sometimes you need to make a beautiful screen, but for this you need to reloading several times).

5. New skills for the game - the skill of handling weapons, the higher you pump it, the less the weapon will break.

6. Diseases ???

Thank you for your time!

**Comment by Eatric** [comment]
NPC: 1) Can be done by plugins
Localization: Maded by community in workshop
Devkit and Map editor: 1) Useless, 
if you don’t want to spend time modifying the map, then why should Nelson do your work for you?
2, 3) Can be done by plugins
