### ISSUE TITLE
NPC: Kill Animal Condition

### ISSUE THREAD

**Issue by Vulby** [SmartlyDressedGames/Unturned-3.x-Community#85]
Would be useful for NPC creators I know a few people who would like this
It would use an animal id so modders can use their custom animals too or 'none' so you can kill any animal
```
Condition_#_Type Kills_Animals
Condition_#_Animal
Condition_#_ID
Condition_#_Value
```
*From my list on the forum
**The List https://forum.smartlydressedgames.com/t/community-npc-suggestion-list/910

**Comment by FredMods** [comment]
I'd say this isn't really what the github is for.

**Comment by aviadmini** [comment]
I'd say this is **exactly** what **this** github project is for.

Actually just wanted to post exactly the same thing :)

**Comment by SDGNelson** [comment]
The hunting condition (_Type Kills_Animals) will be in the next update!
_Animal (ID) sets the animal ID to look for.
