### ISSUE TITLE
Missing custom structure asset error after update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#850]
Not sure whats the reason behind that, but after update - players can't join server, it shows them this error (was working perfectly before update): 
![image](https://user-images.githubusercontent.com/14231707/59939571-106f9f00-9461-11e9-9014-e1ccff81af5b.png)

**Comment by SDGNelson** [comment]
One reason that comes to mind is a child item may be conflicting with a parent. Now that the server auto-collects the dependency items if one pack combines multiple but depends on another they might conflict. When you joined did it show the "Downloading XYZ" properly, or is your client already subbed?

**Comment by baranmod** [comment]
Yeah, it showed "downloading XYZ" thing if I understand correctly, and it took the same time to download mods while joining the server but it seems like none of the mod is actually loaded for players

**Comment by SDGNelson** [comment]
Hmmm could you share the address please? I'll connect and see if it's loading the downloaded mods properly.

**Comment by baranmod** [comment]
sure, us.warzonez.net:27015

**Comment by SDGNelson** [comment]
It looks like the server is using some sort of plugin to hide which workshop mods you are using which is why the client doesn't show the names of the items while connecting.

That aside, at least some of the assets aren't being instantiated because of missing master bundles. Do you have Hawaii and Greece as dependencies in the downloads list? (Those master bundles are referenced)

**Comment by baranmod** [comment]
ok, will try to turn off that plugin shortly

**Comment by baranmod** [comment]
Yeah, I've uploaded hawaii, greece bundles. Turned off plugin which was hiding workshop list - still no luck

**Comment by baranmod** [comment]
However, if I try to join server right after launching game - this error appears, yet if I reload game with "page up" after trying to connect to server - I then can join server without problems

**Comment by SDGNelson** [comment]
By uploaded, you added their workshop IDs to the collection/downloads list? (Duplicates will lead to issues)

That gives me a hunch - I'll make some changes and try connecting

**Comment by baranmod** [comment]
No, I uploaded them manually (same as all other mods) to Server/workshop/content

**Comment by SDGNelson** [comment]
Now just waiting for the patch to finish building. Includes some other changes to catch exceptions during barricade/struct/vehicle spawn and updated steam redist.

When loading in post-patch the custom files appear to have loaded correctly, but without hawaii/greece/etc those do not. Hawaii Assets and Greece should probably be added to the download list so that players get those too. (uploaded manually will only have them server-side)

**Comment by dzonyloker** [comment]
Hawaii Assets from https://steamcommunity.com/sharedfiles/filedetails/?id=1753131903

> [21.06.2019 20:05:44] [Info] Downloading workshop item: 1753131903
> [21.06.2019 20:05:44] [Info] Successfully downloaded workshop item: 1753131903
> [21.06.2019 20:05:44] [Info] Installing workshop item: 1753131903
> [21.06.2019 20:05:47] [Error] NotSupportedException: Missing effect gameobject - SDG.Unturned.EffectAsset..ctor (SDG.Unturned.Bundle bundle, SDG.Unturned.Data data, SDG.Unturned.Local localization, System.UInt16 id) (at <45b3c61f8c66464db074ee1bd0cdc3da>:0)
> System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
> System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
> System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
> System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <cfc149f8218b496788d8493c87de777a>:0)
> System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <cfc149f8218b496788d8493c87de777a>:0)
> System.Activator.CreateInstance (System.Type type, System.Object[] args) (at <cfc149f8218b496788d8493c87de777a>:0)
> SDG.Unturned.Assets.loadFile (SDG.Unturned.Assets+ScannedFileInfo file) (at <45b3c61f8c66464db074ee1bd0cdc3da>:0)
> UnityEngine.Debug:LogException(Exception)
> SDG.Unturned.Assets:loadFile(ScannedFileInfo)
> SDG.Unturned.Assets:load(String, Boolean, Boolean, Boolean, EAssetOrigin, Boolean)
> SDG.Unturned.DedicatedUGC:onItemDownloaded(DownloadItemResult_t)
> Steamworks.Callback`1:OnRunCallback(IntPtr, IntPtr)
> Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
> Steamworks.GameServer:RunCallbacks()
> SDG.SteamworksProvider.SteamworksProvider:update()
> SDG.Unturned.Provider:Update()

**Comment by baranmod** [comment]
well, I don't know why but it worked before this update (manual upload). All hawaii/greece assets were visible

**Comment by SDGNelson** [comment]
3.30.3.1 should now be available

**Comment by dzonyloker** [comment]
works fine now :D

**Comment by baranmod** [comment]
seems everything is good now

**Comment by SDGNelson** [comment]
Phew, happy to have that sorted out!
One huge benefit of this update that I'd recommend since you have so many mods installed and the anonymous download is working properly again: you can add your workshop items to a Collection, and then only need to add the collection to the WorkshopDownloadIDs.json. Your server will automatically gather all the workshop items and keep them up-to-date.
