### ISSUE TITLE
Add Option to Disable & Enable Indepth UI

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#851]
Hi @SDGNelson  
_First of all thank you for the last update that helped my project alot by fixing & adding new features to the projectiles :3_ 
  
Here so i'v seen the config of the MAP : Destruction , and there was Alot of UI Config i tried to 
Add more UI Config like ,
 **"Allow_Skills" false, 
"PlayerUI_ScoreVisible": true, 
  "PlayerUI_NearbyVisible": false,**  
and it seems not working i don't know if the config exsiste ,if it exsiste then tell me down , 

if not i would like to see more **indepth UI config**

Like this examples : 
- Nearby
- Hands
- Information
- Skills
-  Horde Mode  UI  ( Wave , Score ).

_Thanks ! for reading and sorry for my English_

**Comment by SDGNelson** [comment]
Somewhat covered by some new options in the next update, but will close for now: going forward I think we should have one issue per UI option request for discussion whether it makes sense as a per-level or server-configurable flag.
