### ISSUE TITLE
Error Barricade on update 3.30.3.0

### ISSUE THREAD

**Issue by MrSiller** [SmartlyDressedGames/Unturned-3.x-Community#852]
After I updated the server to the new version of the game I have an error with baricades what should I do? 
apper dynamic-method) SDG.Unturned.BarricadeManager:load_Patch1 ()
SDG.Unturned.BarricadeManager.onLevelLoaded (System.Int32 level) (at <c48a7d1ae7c840eb85e11d54f350f350>:0)
SDG.Unturned.Level+<init>c__Iterator0.MoveNext () (at <c48a7d1ae7c840eb85e11d54f350f350>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <8c811485138d4ef982faffe58556acf0>:0)

NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.InteractableDoor.updateState (SDG.Unturned.Asset asset, System.Byte[] state) (at <c48a7d1ae7c840eb85e11d54f350f350>:0)
SDG.Unturned.BarricadeTool.getBarricade (UnityEngine.Transform parent, System.Byte hp, System.UInt64 owner, System.UInt64 group, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, System.UInt16 id, System.Byte[] state, SDG.Unturned.ItemBarricadeAsset asset) (at <c48a7d1ae7c840eb85e11d54f350f350>:0)
SDG.Unturned.BarricadeManager.spawnBarricade (SDG.Unturned.BarricadeRegion region, System.UInt16 id, System.Byte[] state, UnityEngine.Vector3 point, System.Byte angle_x, System.Byte angle_y, System.Byte angle_z, System.Byte hp, System.UInt64 owner, System.UInt64 group, System.UInt32 instanceID) (at <c48a7d1ae7c840eb85e11d54f350f350>:0)
SDG.Unturned.BarricadeManager.loadRegion (System.Byte version, SDG.Unturned.River river, SDG.Unturned.BarricadeRegion region) (at <c48a7d1ae7c840eb85e11d54f350f350>:0)

**Comment by SDGNelson** [comment]
3.30.3.1 should now be available

**Comment by Trojaner** [comment]
Also the error was caused by a plugin as it looks like.
