### ISSUE TITLE
Players cant connect to server after Unturned update

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#853]
Good afternoon. After updating my servers to the latest version, 3.30.3.0, I have encountered an error in which players cannot connect to a Linux server running that version. I have made sure I have updated my servers to the latest version, but players can not seem to be able to connect to it. I have verified my game files and everything I can do. (If this is helpful) 304930 is my depot ID and I am using 32 bit Linux.

**Comment by SDGNelson** [comment]
Is it possible to update to the 64-bit anonymous Linux server? Going forward I'm hoping to kill the old one

**Comment by Ascivv1** [comment]
How do I update to the 64 bit server on Linux? The #697 wasn't helpful whatsoever.

**Comment by SDGNelson** [comment]
To install from steamcmd you run:
login anonymous
app_update 1110390

From there I guess we see what errors you get when trying to startup?

**Comment by Ascivv1** [comment]
How do I launch steamcmd on Linux again?

**Comment by SDGNelson** [comment]
Here's the steamcmd linux docs: https://developer.valvesoftware.com/wiki/SteamCMD#Linux

**Comment by Ascivv1** [comment]
I will test this out once I get home.

**Comment by PandahutMiku** [comment]
@Ascivv1 
Are you getting any error logged when they try to join?
I just encountered a very strange issue where players couldn't join on a map with no vehicles and that had no vehicle spawns. They would just get stuck on loading "Vehicles" and hear themselves punch and map ambiance but unable to do anything.  I fixed the issue by just blindly typing "/v vehicleid" on the loading screen which let people connect fine from that point on. I would assume it just doesn't like having zero vehicles on the map. But this issue also reoccurs every time the server is restarted until a vehicle is spawned.
The error on connect was
`[6/21/2019 3:27:16 PM] [Info] General: Exception raised when RPC invoked askVehicles:
[6/21/2019 3:27:21 PM] [Error] ArgumentException: startIndex or endIndex to askVehiclesHelper invalid - SDG.Unturned.VehicleManager.askVehiclesHelper (Steamworks.CSteamID steamID, System.Int32 startIndex, System.Int32 endIndex) (at <45b3c61f8c66464db074ee1bd0cdc3da>:0)
(wrapper dynamic-method) SDG.Unturned.VehicleManager:askVehicles_Patch1 (object,Steamworks.CSteamID)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
(wrapper dynamic-method) SDG.Unturned.SteamChannel:receive_Patch2 (object,Steamworks.CSteamID,byte[],int,int)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive_Patch2(Object, CSteamID, Byte[], Int32, Int32)
SDG.Unturned.Provider:receiveServer(CSteamID, Byte[], Int32, Int32, Int32)
SDG.Unturned.Provider:listenServer(Int32)
SDG.Unturned.Provider:listen()
SDG.Unturned.Provider:Update()`

**Comment by aman7** [comment]
if you still having problem, i can provide you update and start script for 64bit linux.

**Comment by Ascivv1** [comment]
I would like those please

**Comment by SDGNelson** [comment]
Thanks Miku, DANG I wish I'd gotten that fix in before building the .1 patch. It's finally in the midst of uploading, but if there's a .2 patch it will include the 0 vehicle fix.

**Comment by Ascivv1** [comment]
Dm then to me on discord Ascivv#4883

**Comment by Ascivv1** [comment]
Miku players can’t connect to my servers so I don’t get that error
