### ISSUE TITLE
Server errors loading official workshop assets

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#854]
https://pastebin.com/ExEbrN5w

happens when loading some workshop map assets such as
1753131903 hawaii assets
1767554683 belgium assets
1756436626 greece assets

started happening after todays update

**Comment by SDGNelson** [comment]
Tested server running Greece which auto-downloaded Hawaii too, and they started without errors. Is this using the auto download feature or manual setup?

**Comment by SDGNelson** [comment]
3.30.3.1 should now be available

**Comment by Mithallas** [comment]
I just add workshop IDs to the workshopdownloadIDs.json, heres what mine looks like
`[
  1268199545,
  1756436626,
  1753131903,
  1756455480,
  1739324658,
  1767554683
]`

**Comment by Mithallas** [comment]
fixed in 3.30.3.1

**Comment by SDGNelson** [comment]
Yay! Thanks

**Comment by Mithallas** [comment]
Belgium is still giving problems
https://steamcommunity.com/sharedfiles/filedetails/?id=1727125581
https://steamcommunity.com/sharedfiles/filedetails/?id=1767554683

**Comment by SDGNelson** [comment]
It looks like this is because they both contain the Bundles folder - if you add just the map it should be fine. I've reached out to Paladin about changing it so that there aren't duplicates

**Comment by Mithallas** [comment]
I cleared Server\Workshop\Steam\content folder this time before only putting the map in auto download and that fixed it. Thanks for the fast patch Nelson! :D
