### ISSUE TITLE
Ace pistol bug

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#856]
The ace currently has infinite ammo

**Comment by SDGNelson** [comment]
🤦‍♂

**Comment by SDGNelson** [comment]
For anyone who's curious: the reason it happened was that the Ace was the only asset which had tested a process to convert the .dat file formats ages ago, but the other format didn't have a default value for Ammo_Per_Shot. In the .2 patch tonight I've simply deleted the alternative file.
