### ISSUE TITLE
Dead + Esc Bug

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#862]
[![](http://img.youtube.com/vi/bW422uqyZSM/0.jpg)](http://www.youtube.com/watch?v=bW422uqyZSM "")

**Comment by LuisDavid1198** [comment]
Arregle, Hay Otro bug que solo Te deja Ponerle Gasolina a los Autos si estan Desbloqueados.

**Comment by SDGNelson** [comment]
Whoops! Must have only been using the Esc key while testing the UI changes. Thanks for the report; should be fixed in the .3 patch tonight.
