### ISSUE TITLE
Find player who damaged zombie/animal in new Events

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#863]
Nelson added new event in DamageTool, how can i find player(if player damage zombie/animal)

**Comment by pastet0422** [comment]
Nelson reopened new issue

**Comment by SDGNelson** [comment]
Haven't added an event for zombie killed or instigator yet, so I'll forget if the issue is closed.

**Comment by SDGNelson** [comment]
In the next update zombieDamaged and animalDamaged have been marked obsolete, replaced by damageZombieRequested and damageAnimalRequested which give access to all of the damage parameters as well as the damage instigator. In the future we will probably see a similar replacement for players/buildables/vehicles/etc.
