### ISSUE TITLE
Bouncer bug

### ISSUE THREAD

**Issue by Mithallas** [SmartlyDressedGames/Unturned-3.x-Community#864]
If I load a vanilla russia server with Hawaii Assets id in workshop json, the bouncer helicopter cannot be entered. 
Bouncer is the only consistent case although I have also gotten a couple confirmed reports from players that some other vehicles cannot be entered randomly after a period of time such as the transport helicopter

**Comment by dzonyloker** [comment]
coaster same

**Comment by SDGNelson** [comment]
Sorry I missed this for the previous patch! I double-checked in the .4 patch and was able to enter those vehicles on my test server now, so it should be fixed once that releases.
