### ISSUE TITLE
Add New Event onQuestCompleted

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#866]
/\

**Comment by pastet0422** [comment]
I found solution by patching "completeQuest" method using 0Harmony
But i think Nelson should add event.

**Comment by SDGNelson** [comment]
Will do!

**Comment by pastet0422** [comment]
Thanks you very much ♥

**Comment by pastet0422** [comment]
Why are u reopen closed issues ?

**Comment by Eatric** [comment]
will close when will do

**Comment by SDGNelson** [comment]
The event wasn't added yet, so I'll forget if the issue is closed.
