### ISSUE TITLE
Wrong map version in 3.30.3.3

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#867]
All my maps after 3.30.3.3 or 3.30.3.2 update have the 3.19.0.2 version number that prevents anyone from connecting 

Linux 16.04
32bit build
appid 304930

**Comment by educatalan02** [comment]
You should download appid  1110390

**Comment by gegtor** [comment]
I don't want to use new scripts or the new version because it doesn't provide access to a console on a linux

**Comment by SDGNelson** [comment]
Vanilla doesn't have an implementation of console input on Linux, but Rocketmod does so I assume you're using Rocket on your existing server. Did you run into issues using Rocket with the dedicated server app?

Aside from that: the only map using 3.19.2.0 version number is France, so I assume something else is amiss.

**Comment by gegtor** [comment]
I did not test it yet but i did test troyaner scripts and they don't provide a console when opened like old ones did

**Comment by educatalan02** [comment]
With the AppId 1110390 & Linux 64 bits. The console with RocketMod installed is working.

**Comment by Trojaner** [comment]
@gegtor my scripts do not provide a console output

**Comment by gegtor** [comment]
I know that @Trojaner 

I there a way to run 64bit 1110390 with console output like the old scripts had?

**Comment by Dolphinchik** [comment]
![image](https://user-images.githubusercontent.com/34001190/60090596-4b711b80-975c-11e9-9155-f0b94950ae11.png)

1 more.

AppId 1110390

**Comment by gegtor** [comment]
@SDGNelson 
<img width="852" alt="Screenshot 2019-06-25 at 13 47 33" src="https://user-images.githubusercontent.com/10978723/60098446-da2e6a00-9755-11e9-8d11-4a19a01e9085.png">
<img width="1440" alt="Screenshot 2019-06-25 at 13 47 16" src="https://user-images.githubusercontent.com/10978723/60098447-dac70080-9755-11e9-85f8-c56d2ebbaf16.png">

3.30.3.4 Update and still same thing

**Comment by SDGNelson** [comment]
Did you update to the dedicated server app yet? From the sounds of things you were using rocket on your old 32-bit server (which is why it had console input), but didn't try with rocket on the new server yet. There's also a ServerHelper.sh script which runs the vanilla linux server out of the box

**Comment by gegtor** [comment]
Okay i fixed everything with the new 64bit 1110390 unturned

Here are my scripts with a good guide if anyone would need help https://github.com/gegtor/Unturned-64Bit-Server-Scripts

They have working console and are easy to use
