### ISSUE TITLE
Vehicles in old bundles (.unity3d) have broken engine sounds

### ISSUE THREAD

**Issue by khakers** [SmartlyDressedGames/Unturned-3.x-Community#868]
Vehicles that were bundled using the old bundle tool have incredibly high pitched engine sounds. This doesn't affect vehicle bundled using masterbundle. This also doesn't affect the siren.

**Comment by educatalan02** [comment]
Also Lights too

**Comment by SDGNelson** [comment]
This should be fixed in the next patch, but in the meantime a workaround is to set "Pitch_Idle" and "Pitch_Drive" in the vehicle's asset file. The default values are 0.5 for idle and 0.05 for drive. Sorry about the horrible noises! :(

**Comment by khakers** [comment]
Can confirm this is no longer an issue. Thanks for the quick fix!
