### ISSUE TITLE
is it possible to get the source code of the game?

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#87]
Hello. Sorry that I'm writing here (most likely it's wrong). I want to ask you, below on the screen, what does it mean? Does this mean that good people have access to the source code Unturned 3.0?
![cutxv3mtluk](https://user-images.githubusercontent.com/32962870/32786869-73163c62-c998-11e7-91f1-459df7339cfa.jpg)

**Comment by xdlewisdx** [comment]
it means anyone with access to the code can find it there, for example Sven aka fr34kyn01535, RocketMod creator and other devs know where to find it

**Comment by xdlewisdx** [comment]
I'm guessing you are getting at, can someone request to view the code?, no not really.

**Comment by VitaxaRusModding** [comment]
Yes, I would like to get the source code unturned. I need it for the "Five Kingdoms" project and in general for creating modules, maps, mods.

**Comment by Trojaner25** [comment]
Officially, you wont get source code of Unturned.
There are inofficial ways to get it and many developers do so...

**Comment by VitaxaRusModding** [comment]
I use the decompiled version, for reading code and developing modules

**Comment by Trojaner25** [comment]
Well that means you do not need access to the official repo, as decompiling should be sufficient.
Keep in mind that client-side modules do not work on BattlEye servers and that they need to be downloaded manually by everyone. Mostly any client-side module fails to be successful.

**Comment by VitaxaRusModding** [comment]
Yes I know. I make launcher, for paging files and little protection for them.)

**Comment by aviadmini** [comment]
Good luck with cheaters

**Comment by SDGNelson** [comment]
Unfortunately for the moment I'm not 100% sure on the public-release licensing of 3rd party libraries, and the GitHub LFS bandwidth would be cost prohibitive to give access to everyone. It's definitely something I want to make happen, however.

**Comment by aviadmini** [comment]
Maybe other providers?

**Comment by Trojaner25** [comment]
Did someone say Gitlab?

**Comment by SDGNelson** [comment]
According to the GitLab pricing page it's $200 per user per year if you want to use LFS: https://about.gitlab.com/products/

**Comment by Trojaner25** [comment]
Afaik LFS is free on GitLab; only Amazon E3 Object Storage costs money (?)

**Comment by VitaxaRusModding** [comment]
**Nelson, we believe in you!**
