### ISSUE TITLE
Change the color of the sky on the server

### ISSUE THREAD

**Issue by Dolphinchik** [SmartlyDressedGames/Unturned-3.x-Community#871]
I think this function has greatly expanded the possibilities, for example, to change the color of the sky and possible clouds, with the emission (S.T.A.L.K.E.R.) in bright red, with the subsequent possibility to return the color of the sky depending on the time of day.

**Comment by DaemonnChumakhidze** [comment]
As far as I know, you can already do that in the map editor.

**Comment by Dolphinchik** [comment]
I need to do this plugin.

**Comment by SDGNelson** [comment]
It would be cool, but unlikely to be added sorry. In 4 you will be able to do this with replicated properties, but adding new replicated data to 3 is quite a hassle.
