### ISSUE TITLE
Sending UI effects with params keyword.

### ISSUE THREAD

**Issue by DaemonnChumakhidze** [SmartlyDressedGames/Unturned-3.x-Community#872]
Since there's only `tellUIEffect1Arg`, `tellUIEffect2Args`, `tellUIEffect3Args` and `tellUIEffect4Args`, it's pain to make something uses more than 4 placeholders.

What about this;
```csharp
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void tellUIEffectParams(CSteamID steamID, ushort id, short key, params string[] args)
{
    if (base.channel.checkServer(steamID))
    {
        EffectManager.createAndFormatUIEffect(id, key, args);
    }
}
```

**Comment by Trojaner** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/96#issuecomment-355146687

![grafik](https://user-images.githubusercontent.com/1809172/60038625-8a03c900-96bd-11e9-9a8a-c30fc663ac53.png)

Asked this back in 2018 and I think its still useful

**Comment by SDGNelson** [comment]
Assuming that it's sent in reliable mode you can use "sendUIEffectText" to set an unlimited number of child strings

**Comment by Dolphinchik** [comment]
@SDGNelson, I apologize, but I still can not make it work.

**Comment by Miha22** [comment]
Can somebody provide an example please? How exactly does this methods work? 
How game understands what effect id to use? Please give examples with child strings

**Comment by SDGNelson** [comment]
Effect ID is the id parameter, key is an optional instance identifier for modifying instances of an effect, and child name is the unity name of a GameObject with a Text component.

**Comment by Miha22** [comment]
there is no effect id parameter in sendUIEffectText

**Comment by Miha22** [comment]
```csharp
public static void sendUIEffectText(
      short key,
      CSteamID steamID,
      bool reliable,
      string childName,
      string text)
    {
      EffectManager.manager.channel.send("tellUIEffectText", steamID, (ESteamPacket) (!reliable ? 16 : 15), (object) key, (object) childName, (object) text);
    }
```

**Comment by Miha22** [comment]
> 
> 
> Effect ID is the id parameter, key is an optional instance identifier for modifying instances of an effect, and child name is the unity name of a GameObject with a Text component.

there is no effect id parameter in sendUIEffectText
```
public static void sendUIEffectText(
      short key,
      CSteamID steamID,
      bool reliable,
      string childName,
      string text)
    {
      EffectManager.manager.channel.send("tellUIEffectText", steamID, (ESteamPacket) (!reliable ? 16 : 15), (object) key, (object) childName, (object) text);
    }
```

**Comment by Eatric** [comment]
There is key parameter, use it

**Comment by Miha22** [comment]
got it thank you guys.
