### ISSUE TITLE
Hawaii glass assets not working

### ISSUE THREAD

**Issue by DollarGangstaDollar** [SmartlyDressedGames/Unturned-3.x-Community#874]
Ever since the last update, some of the assets of Hawaii weren't working. I entered into the map editor to see facility glass #3 gone. I tried spawning it back in back it wouldn't work.

**Comment by SDGNelson** [comment]
Double-checked and I was able to spawn them in: https://i.imgur.com/ryF7Bi4.png
Are you subscribed to the Hawaii Assets workshop item?

**Comment by SDGNelson** [comment]
Actually, I've been helping troubleshoot a variety of workshop items over the past few days and one problem that keeps coming up is items that contain duplicates of Hawaii content. It's possible that you're subscribed to one of those items that contains duplicates.

**Comment by DollarGangstaDollar** [comment]
Thanks for the reply, i'll see if any of those help.
