### ISSUE TITLE
Function to increase the player's skeleton

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#876]
Hello, is it possible for the creators of modifications to make a function to increase the player's skeleton? In order to make big models, in size like a mega zombie

**Comment by Dolphinchik** [comment]
If I'm not mistaken, then yes, Slavka

**Comment by SvyatoslavOrlov** [comment]
> If I'm not mistaken, then yes, Slavka

Сейчас такое сделать невозможно

**Comment by pastet0422** [comment]
Its possible,as i know,but Nelson dont added this.

**Comment by SDGNelson** [comment]
Unlikely to be added because a variety of player-related code does not expect the player size to change, so it would definitely have unintended side-effects (sorry).
