### ISSUE TITLE
"Unturned - Running" Steam-Battleye Bug

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#877]
I am running servers on a machine that I am also playing with. When I play Unturned, and close Unturned, Steam still thinks I am playing the game, and the Battleye service is still open and must be closed via Task Manager.

If you could simply adjust what Steam looks for - Unturned.exe instead of BE service

**Comment by PandahutMiku** [comment]
Just use the dedicated server steam app

**Comment by Trojaner** [comment]
Even before thee dedicated app it was a common thing to copy the whole Unturned folder for servers

**Comment by RainOfPain125** [comment]
@PandahutMiku I already use that. This issue has and still persists
