### ISSUE TITLE
Dedicated Server- SteamApi_Ini() failed 

### ISSUE THREAD

**Issue by 000001000000** [SmartlyDressedGames/Unturned-3.x-Community#879]
Hey there I've troubles with starting an Unturned Server and tried the new 1110390 Version of it. I was downloading it with my steamcmd and tried, after chmod +x ServerHelper.sh, to run this ServerHelper.sh but the return was `bash: ./ServerHelper.sh: /bin/bash^M: bad interpreter: No such file or directory` after running `sed -i -e 's/\r$//' ServerHelper.sh` this problem was fixed. So I tried to run it now properly but it returned another error, which says that he failed to locate an Instance of Steam, which is why SteamAPI_Init() failed. 
this is my hole output: 
`Set current directory to /root/unturned
Found path: /root/unturned/Unturned_Headless.x86_64
Mono path[0] = '/root/unturned/Unturned_Headless_Data/Managed'
Mono config path = '/root/unturned/Unturned_Headless_Data/MonoBleedingEdge/etc'
Preloaded 'libsteam_api.so'
Preloaded 'steamclient.so'
Logging to /root/.config/unity3d/Smartly Dressed Games/Unturned/Player.log
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
`
I tried to fix it now for days but nothing worked for me.

**Comment by educatalan02** [comment]
I already fixed something like this. Just edit your start.sh and Link STEAMCMD API to the steamcmd/linux64/steamclient.so

And then the same for UNTURNED_API to: YOURUNTURNEDFOLDER/linux64/steamclient.so

**Comment by educatalan02** [comment]
[start.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3330643/start.zip)
Here's my Start.sh you should take a look.

**Comment by Kenzim** [comment]
You've saved it with Windows line endings. You can use notepad++ or similar to convert to Unix or directly curl the script to the machine.

**Comment by 000001000000** [comment]
> You've saved it with Windows line endings. You can use notepad++ or similar to convert to Unix or directly curl the script to the machine.

That's right but as i said i fixed this and wrote it down for others having the same trouble.

**Comment by Kenzim** [comment]
Then please make your question clear and not hard and confusing to read. 
You might try this to fix your problem
```export GAME_INSTALL_DIR=(path to unturned)
export LD_LIBRARY_PATH=$GAME_INSTALL_DIR/lib64```

**Comment by 000001000000** [comment]
`Then please make your question clear and not hard and confusing to read.
You might try this to fix your problem
export GAME_INSTALL_DIR=path to unturned

export LD_LIBRARY_PATH=$GAME_INSTALL_DIR/lib64`

I'm sorry for making my question confusing!
I've done both and after that I've started the ServerHelper.sh and got the same output as mentioned at the start. 
For the dedicated Server i do not need Rocketmod is that correct? I've just downloaded with my steamcmd to my unturned folder and then tried to run the ServerHelper.sh. Have I missed something to do?

**Comment by 000001000000** [comment]
@educatalan02 Can you give me you're update.sh too maybe mine is too old (don't forget to delete your account details).
Maybe that brings me a working server ^^

**Comment by SDGNelson** [comment]
Since it's giving a "SteamAPI_Init" error that means it thinks it's trying to run as a player. Did you pass any arguments to the ServerHelper.sh script? For example running "ServerHelper.sh +InternetServer/MyServerId" will launch a server.

Regarding the other comments: you shouldn't need to worry about the steamclient.so or library path, that's what the ServerHelper.sh script does.

**Comment by Johnanater** [comment]
ServerHelper.sh has Windows line endings, like what Kenzim said, it's pretty easy to fix.

The script works perfectly for me, I just started the server using this command:
./ServerHelper.sh -logfile ./unt.log +secureserver/Test & tail -f ./unt.log

It would be awesome if we could get real stdin/stdout on Linux. :)

**Comment by SDGNelson** [comment]
Whoops! Corrected the line endings. Wrote it in vim on the linux machine, but then re-typed it in vscode on windows when adding the comments.

No immediate plans, but I'll look into doing a linux implementation - really should and it should be straightforward

**Comment by 000001000000** [comment]
That's great thank you all the solution of @SDGNelson worked fine for me! I'm gonna close it now!
