### ISSUE TITLE
Shooting through doorframes

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#88]
In the current version of Unturned, players are able to penetrate the wood directly on the outside of any door when shut.

Video: https://www.youtube.com/watch?v=RNCUeAeNvt0

**Comment by SDGNelson** [comment]
IIRC this was fixed by expanding the door's hitbox into the surrounding walls while the doors are closed. (not elegant, but does the job)
