### ISSUE TITLE
Cursor Feature

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#880]
Hello Nelson, 
It will be good if you can add to turn off the blur background when using player.Player.serversideSetPluginModal(true).

**Comment by SDGNelson** [comment]
Considering the variety of UI-related on/off requests lately I'm now planning to add a UI-features bitmask for this (amongst others) which will be controlled from the server.

**Comment by SDGNelson** [comment]
In the next update this can be controlled with EPluginWidgetFlags.NoBlur!
