### ISSUE TITLE
Interaction of plug-ins and mods

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#881]
Hey. I’ll say right away that I don’t know much about plugins, because I mainly create mods.
In general, I wanted to learn how to make a plug-in interact with a game object, turn components on and off, or change their parameters? Is it possible to do this directly by adding a command to the plugin to search for an object with the specified name, and then specifying a command like this:
public GameObject (Name);
(Name) .SetActive (true)

(Well, or something like this)

Also, as far as I know, Unity is able to compile events. Can I make my own equivalent of VehicleEventHook and activate it under a different condition using a plugin?

**Comment by SDGNelson** [comment]
Plugins could search for specific GameObjects by name, but a more reliable approach would be using the ItemManager, VehicleManager, LevelObjects, etc to access existing objects. From there you can modify components, however you'd have to keep in mind that properties do not replicate to clients without calling RPCs.
