### ISSUE TITLE
Linux server graceful shutdown

### ISSUE THREAD

**Issue by Cherry** [SmartlyDressedGames/Unturned-3.x-Community#884]
Is there any way to gracefully shutdown the server when launching from `Unturned_Headless.x86_64`? It seems like console input doesn't work, so `shutdown` is out of the question (without resorting to RocketMod), and it seems like sending a `SIGINT` or `SIGTERM` has no effect, resulting in having to send a forceful `SIGKILL`.

**Comment by SDGNelson** [comment]
Not yet, but I'm intending to implement the Linux console soon™ so I'll leave this open until then.

**Comment by Cherry** [comment]
If there’s any way to bug-bounty this to get it escalated or prioritised, let me know - we may be interested.

**Comment by SDGNelson** [comment]
Bug-bounty like a community-created implementation? There will definitely be an update early-mid July for which I'll look into this more, but right now I've been catching up on work for 4.x Update #024.

**Comment by Cherry** [comment]
A bounty like a sponsored issue essentially - https://www.bountysource.com/ is a common platform. Let us know if there's anything we can do to escalate the resolution of this. Thanks for all your hard work!

**Comment by Kenzim** [comment]
i mean the community implementation is rocketlauncher. gives you console to
do what you want.

**Comment by SDGNelson** [comment]
Kenzim is right that using Rocketmod on Linux should allow command IO from the console in the meantime.

For the next update however I have done some work on this front, more details here: #932

**Comment by Trojaner** [comment]
http://www.jprl.com/Blog/archive/development/mono/2008/Feb-08.html

Mono includes this possibility for handling signals.
https://www.nuget.org/packages/Mono.Posix/ or alternatively
https://www.nuget.org/packages/Mono.Posix.NETStandard/

For both Windows and Linux CTRL-C you could use something like this:
```cs
Console.CancelKeyPress += OnConsoleCancelKeyPress;
```

In both cases you could use the event to save & properly shut down the server.

For Windows there is also https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler.

**Comment by Kenzim** [comment]
The Linux console does work now though? You can use the log file option to user it (thanks trojaner)

**Comment by Trojaner** [comment]
Thats not exactly what I meant.
If you close the console or send a signal to the process, the server just closes and this often results in file corruptions.

**Comment by SDGNelson** [comment]
Hi Cherry! Following up to see if you were able to make use of the recent console changes and shut down cleanly in vanilla?

Going forward I expect to tidy up the -ThreadedConsole mode a bit more especially on Linux, but no ETA yet.

**Comment by Cherry** [comment]
Using `-ThreadedConsole` appears to work now, thanks @SDGNelson!

We do see the following when sending a `SIGINT` to stop the server though:
```
Could not terminate pathfinding thread[2] in 50ms, trying Thread.Abort

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
  at Pathfinding.ThreadControlQueue.Pop () [0x00158] in <9ec65a403abd40a9ab1a61c389703b09>:0
  at AstarPath.CalculatePathsThreaded (System.Object _threadInfo) [0x00071] in <9ec65a403abd40a9ab1a61c389703b09>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
AstarPath:CalculatePathsThreaded(Object)
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart(Object)

(Filename: <9ec65a403abd40a9ab1a61c389703b09> Line: 0)

Unhandled exception during pathfinding. Terminating.

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

UnloadTime: 1051.685000 ms
Current backend date: 08/01/2019 14:55:51

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Halloween: [10/27/2018 00:00:01, 11/01/2018 23:59:59]

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Christmas: [12/10/2018 00:00:01, 12/31/2018 23:59:59]

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 7f7451edf700 -> priority: 1
  Thread -> id: 7f74516de700 -> priority: 1
  Thread -> id: 7f7450edd700 -> priority: 1
  Thread -> id: 7f73f9fff700 -> priority: 1
```
It does eventually stop, but the output looks a little scary.

**Comment by SDGNelson** [comment]
Sorry I missed that response: it's a warning shutting down the pathfinding system, but should not affect anything else.
