### ISSUE TITLE
Additional workshop download config

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#885]
- [x] Number of retries in the event of a connection failure
- [x] How long to cache query results for

**Comment by Kenzim** [comment]
Some way to make this occur before the modules start loading? Plugins like
kit plugins that use the workshop can sometimes mess up when they're not
installed yet.

**Comment by Trojaner** [comment]
To be honest that sounds more like a thing the plugin should fix.
There are various events they can wait for.

**Comment by SDGNelson** [comment]
@Trojaner Replying to OP or Kenzim?

@Kenzim Curious what they rely on order wise? In current versions there is the DedicatedUGC.installed event which broadcasts once all downloads are finished (or if no downloads were requested).

**Comment by Trojaner** [comment]
@SDGNelson to Kenzim, was referring exactly to stuff like DedicatedUGC.installed

**Comment by SDGNelson** [comment]
Ah okay. :)
