### ISSUE TITLE
New EDamageOrigin and BumperDamage to delegate.

### ISSUE THREAD

**Issue by Fruten** [SmartlyDressedGames/Unturned-3.x-Community#886]
Please use the delegate from VehicleManager and add a new EDamageOrigin. Why do you change HP car directly?[https://cdn.discordapp.com/attachments/527924306924142592/594206018326757406/unknown.png](url) I made a plugin for RP servers, which allows you to control the damage on the vehicle. But there are not enough settings for collision damage ... [https://cdn.discordapp.com/attachments/527924306924142592/594209723235172392/unknown.png](url) Please add collision damage to EDamageOrigin!

**Comment by SDGNelson** [comment]
Will fix! The vehicle self-damage was added back in 2015, far before the damage overrides in 2019, so it wasn't a consideration at the time and got missed when adding them I suppose.

**Comment by Fruten** [comment]
Thanks

**Comment by SDGNelson** [comment]
Saw a link to this from elsewhere; it looks like this was missed for the most recent update because it was closed. Re-opening to fix in the future.

**Comment by SDGNelson** [comment]
Fixed for the patch, should be out today or tomorrow!
