### ISSUE TITLE
Find player who give damage zombie/animal

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#890]
Re-opened issue

**Comment by Eatric** [comment]
Why are you do this?

**Comment by pastet0422** [comment]
Do what ?

> Why are you do this?

**Comment by Eatric** [comment]
Re open the issue, you can make this by Harmony

**Comment by pastet0422** [comment]
If u said: "U can make this by Harmony", then please give me information what i should to patch by Harmony

**Comment by pastet0422** [comment]
> Re open the issue, you can make this by Harmony

I just not understand how i can found player who give damage zombie/animal, if u know answer - just say

**Comment by Eatric** [comment]
![изображение](https://user-images.githubusercontent.com/16813968/60386648-7a1b2900-9ab1-11e9-93a7-d08fd0e4ab21.png)

**Comment by Unturndster** [comment]
You so noob man, your brain is smaller than my asshole. Literally.

**Comment by pastet0422** [comment]
I still do not understand. How by patching of those methods I can get a zombie

**Comment by pastet0422** [comment]
> You so noob man, your brain is smaller than my asshole. Literally.

Special for u,my little friend - https://www.scientificamerican.com/article/does-brain-size-matter/

**Comment by pastet0422** [comment]
Nelson reopened previous issue

**Comment by SDGNelson** [comment]
In the next update zombieDamaged and animalDamaged have been marked obsolete, replaced by damageZombieRequested and damageAnimalRequested which give access to all of the damage parameters as well as the damage instigator. In the future we will probably see a similar replacement for players/buildables/vehicles/etc.
