### ISSUE TITLE
How to get the trust of Nelson?

### ISSUE THREAD

**Issue by Fruten** [SmartlyDressedGames/Unturned-3.x-Community#891]
How to get Nelson's trust and access the github code of the game?

**Comment by Trojaner** [comment]
Why do you need access to the game's source code?0

**Comment by Fruten** [comment]
To participate in the development of the game. I don't know why, but I was always interested in something like that.

**Comment by Trojaner** [comment]
Yes, let's just give full access to the random guy asking how to gain the developer's trust in a totally unsuspicious way. /s

**Comment by Fruten** [comment]
If I had bad intentions, I would try to hide the desire to gain access. Moreover, I did not ask for access, but asked how to gain trust.

**Comment by Adamv21** [comment]
How can I gain your trust so I can access  your credit card? I've always wanted to help people out spending money.

**Comment by Fruten** [comment]
Why not?:)

**Comment by Alekaei** [comment]
Send him a heart felt letter with a wax seal, make sure to use ink and quill, and your finest hand writing. After that he might consider talking to you through letters for a while as pen pals, if he really trusts you he might move onto email, and then only the luckiest get to discord convos with him. good luck traveler

**Comment by SDGNelson** [comment]
😄 

There are a few contracts in place e.g. the WeGame version who have access, which is why the description has the link to the core game repository. Decompiling the game assembly is essentially the source, and giving out access to the entire project would be problematic.

**Comment by Fruten** [comment]
> 😄
> 
> There are a few contracts in place e.g. the WeGame version who have access, which is why the description has the link to the core game repository. Decompiling the game assembly is essentially the source, and giving out access to the entire project would be problematic.

How did you meet Vitaly Vlasov? (https://github.com/VitaxaRusModding)

**Comment by SDGNelson** [comment]
He's been posting here and involved with the community for quite a while. There are a lot of regulars who are fairly active. :)
