### ISSUE TITLE
How to play video on clientside?

### ISSUE THREAD

**Issue by Unturndster** [SmartlyDressedGames/Unturned-3.x-Community#892]
I'm trying to make a plugin which can show videos on unturned client side. I sadly can't afford another monitor to jack off to porn on so I want to have it in unturned instead. I think other people will benefit from being able to watch Mia Khalifa as well as Logan Paul while role playing. Can anybody show me how+

**Comment by Eatric** [comment]
Maybe by overlay?

**Comment by Unturndster** [comment]
Steam overlay? I want to roleplay and jack off. If I have it on overlay I can't see the quality.
