### ISSUE TITLE
FPS on the map

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#895]
Yesterday I edited the map and it was stable at 80 fps, today I’m entering - 30-40. What can be the reason? How to optimize if nothing has changed on the map?

**Comment by SDGNelson** [comment]
Sorry, it looks like I'm literally a month late on this.
Was the FPS restored next time you restarted the game? My guess is that there was some error in the background.
