### ISSUE TITLE
Player healed delegate

### ISSUE THREAD

**Issue by UFI8** [SmartlyDressedGames/Unturned-3.x-Community#897]
It would be nice if we could track when players heal other players with basic information like
Player healed, who healed the player, heal amount and healed with what item ID
i.e
OnPlayerHealed(UnturnedPlayer player, UnturnedPlayer Healer, float amount, ItemJar healItem)
(or just healitemID instead of ItemJar)

Could also just make an event for ANY item used on ANY player from another player (i.e adrenaline too)

**Comment by SDGNelson** [comment]
Will do!
