### ISSUE TITLE
Cursor Setting

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#899]
Hello, please add the ability to turn off the background blur when turning on the cursor through player.Player.serversideSetPluginModal (true).

**Comment by erik7302** [comment]
#880

**Comment by SDGNelson** [comment]
Considering the variety of UI-related on/off requests lately I'm now planning to add a UI-features bitmask for this (amongst others) which will be controlled from the server in a future update.

**Comment by SDGNelson** [comment]
In the next update this can be controlled with EPluginWidgetFlags.NoBlur!
