### ISSUE TITLE
Unable to find object for GUID {GUID}, falling back to name '[NAME]'

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#901]
Everytime I start my test dedicated server with -SkipAssets, this is spammed 4023 times in the console / log. It's a vanilla Server with RocketMod installed, no Workshop.

Here are some examples:
```
General: Unable to find object for GUID 9556a896-aebc-4564-80bd-220da7efada0, falling back to name 'Bridge_Line_0'
General: Unable to find object for GUID 9556a896-aebc-4564-80bd-220da7efada0, falling back to name 'Bridge_Line_0'
General: Unable to find object for GUID c4b95fda-5cba-426a-8a20-b8f80d2427c8, falling back to name 'Inukshuk'
General: Unable to find object for GUID f94919fe-63e4-49e6-b890-98bae489dc87, falling back to name 'Boulder_12'
General: Unable to find object for GUID f94919fe-63e4-49e6-b890-98bae489dc87, falling back to name 'Boulder_12'
General: Unable to find object for GUID 94727771-cf25-4d1e-b8b2-83d36770d4f2, falling back to name 'Boulder_13'
General: Unable to find object for GUID 94727771-cf25-4d1e-b8b2-83d36770d4f2, falling back to name 'Boulder_13'
General: Unable to find object for GUID 2cb6e4e6-89dc-455b-95c6-339b47b2810c, falling back to name 'Fence_Stone_0'
```

**Comment by Eatric** [comment]
Start with parameter "-SkipAssets"

**Comment by Trojaner** [comment]
This is with SkipAssets...

**Comment by Eatric** [comment]
I understand and that was you cause

**Comment by Johnanater** [comment]
Can confirm, this happens to me as well on Ubuntu 18.04.2 LTS

**Comment by SDGNelson** [comment]
This is during map loading: what's happening here is it's trying to load the objects by GUID (default), but since none of the assets were loaded it thinks that GUID no longer exists. In-case the GUID was changed it falls back to trying to find them by the last-known object name. If you'd like to prevent these messages you could change to loading an empty map?

**Comment by Trojaner** [comment]
Does an empty map already exist? If not, could you please include one or even better disable these warnings when SkipAssets is enabled?

**Comment by Trojaner** [comment]
I can not confirm this yet, but there are hints from my customers that this also happens if SkipAssets isn't used.

**Comment by SDGNelson** [comment]
No empty map in the base game files, but I suppose it makes sense to disable these warnings with skip assets.

Each map may log a few messages like this if the assets have changed since the map was saved, e.g. when I was implementing it I saw that Hawaii updated a few references.
