### ISSUE TITLE
Airdrop Things

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#903]
I have been analyzing the code, and apparently there is no way to completely disable the airdrops.
Could you add some options for this, or something like OnAirdropRequest?

I have a system to always be in the day, I think you have not implemented something for this, so I have this code:

```
private void OnLevelLoaded(int level)
        {
            if (Config.AlwaysDay)
            {
                LevelLighting.canRain = false;
                LevelLighting.canSnow = false;
                LightingManager.cycle = uint.MaxValue / 2;
                LightingManager.onDayNightUpdated += (isDay) =>
                    {
                        if (!isDay)
                            LightingManager.time = (uint)((double)LightingManager.cycle * LevelLighting.transition);
                    };
            }
        }
```
and then this happens:
![](https://cdn.discordapp.com/attachments/485012628926889984/596738336832618497/unknown.png)

**Comment by SDGNelson** [comment]
Will do!
