### ISSUE TITLE
Npc storage

### ISSUE THREAD

**Issue by ImIveooo** [SmartlyDressedGames/Unturned-3.x-Community#905]
Hi Nelson, I’m contacting you today because me and my friends had an idea to improve Unturned.
This idea is to create NPCs with a storage system. Let me explain, a player could have access to the NPC to put things to sell in with a certain price. Then other players come and buy the things he proposes, but when there’s nothing left to sell, you can’t buy anything. Creates a locking system like the safe so that only a player and his group can sell to the NPC or also an option so that everyone can sell and buy. Also make an option so that the owner player can recover money from the NPC through sales. This system would be very useful for many servers especially for RP servers but also for PVP faction servers. I think this system would be very useful for many and would improve Unturned well.

**Comment by SDGNelson** [comment]
That does sound awesome, and can see something along those lines especially in 4, however for the moment it might be easiest to implement in a plugin. Those features should be possible with plugin systems, and it'll be a while before I would get around to a huge change like this.
