### ISSUE TITLE
Chat Message ModHook

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#912]
Hi, I propose to introduce a new ModHook into the game that will be able to intercept commands coming from players and plug-ins via chat. In it there will be two variables allowing to set the text of the command message and the radius in which ModHook will accept them. I wrote an example, but the problem is that these variables do not interact with the event, since I do not know how to record it. I hope you liked my offer and you can add something similar in the game.
I also have an idea to create my own communication channel-chat which will be available only for plug-ins and ModHook. Through it, the plugins will be able to send messages and if the message matches the variable in ModHook, the corresponding event will be activated!
[ChatMessageEventHook.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3379026/ChatMessageEventHook.txt)

**Comment by Ascivv1** [comment]
It’s called DiscordHook

**Comment by Alex-Well** [comment]
> Это называется DiscordHook

Is there now a similar ModHook in the game?

**Comment by educatalan02** [comment]
> It’s called DiscordHook

Why do you say that, Alex is just asking for a ModHook not for a plugin...

**Comment by SDGNelson** [comment]
It's an interesting idea! Sort of like the chat-activated door in the Russia metro.
What's your plan for using it? I imagine we'd need a variety of options for how the message is matched. For example whether it needs to match 1:1 vs. containing a specific piece of text.

**Comment by Alex-Well** [comment]
> It's an interesting idea! Sort of like the chat-activated door in the Russia metro.
> What's your plan for using it? I imagine we'd need a variety of options for how the message is matched. For example whether it needs to match 1:1 vs. containing a specific piece of text.

Yes, I first tried to use the script from the door in the subway on the map of Russia, but it only activates a certain class InteractableObjectBinaryState and is not universal.
I wrote my improved version of ModHook based on that script. However, Unity sees errors in it due to the fact that the project does not have the necessary parameters that are specified in the script. Perhaps you know another way to do this without error. Please take a look at the script I wrote.

```jsx
using UnityEngine;
using UnityEngine.Events;

namespace SDG.Unturned
{
	public class ChatMessageEventHook : MonoBehaviour
	{
		///The Message that must be typed in the chat
		public string phrase;
		
		///Radius in which messages are tracked
		public float sqrRadius;
		
		///Called when a message is written in the chat
		public UnityEvent OnChatMessage;

		void Start ()
		{ 
			if (OnChatMessage == null)
				OnChatMessage = new UnityEvent ();
		}
		/// The method that checks the message typed in the chat
		private void onChatted(SteamPlayer player, EChatMode mode, ref Color chatted, ref bool isRich, string text, ref bool isVisible)
		{
			///The condition is triggered if the message came from a player within a certain radius
			if (mode == EChatMode.LOCAL && !(player.player == null) && !((player.player.transform.position - base.transform.position).sqrMagnitude > sqrRadius) && text.IndexOf(phrase, StringComparison.OrdinalIgnoreCase))
			{
				OnChatMessage.Invoke ();
			}

			///The condition is triggered if the message came from the plugin on the server
			if (text.IndexOf(phrase, StringComparison.OrdinalIgnoreCase))
			{
				OnChatMessage.Invoke ();
			}
		}
	}
}
```

**Comment by SDGNelson** [comment]
Renaming this issue so that I remember what it's about on the to-do list. In the most recent update I reworked how modhook game vs exported code is split, and included them in the unity package, so it should be straightforward to do this one.

**Comment by SDGNelson** [comment]
Two new scripts have been added in the next update:
1. TextChatEventHook which triggers an event when a message passes certain filters.
2. InteractableObjectBinaryStateEventHook which can be paired with TextChatEventHook to modify objects between client and server.
