### ISSUE TITLE
Receiving player voice for "sendVoicePacket" method

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#913]
How we can get "**byte[] packet**" and "**int packetSize**" to send Player voice for other Player ?

**Comment by SDGNelson** [comment]
Sending audio data from the server is unlikely to be easily supported, as those functions use Steam's voice compression. Theoretically you could route audio data as a fake input device into Steam and send the output from the voice API, or figure out what Steam uses to compress the data.
