### ISSUE TITLE
Hashed HWID (Suggestion) 

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#914]
Basically something like Player.HWIDHash option for plugins, sets the HWIDHash to the hashed hardware id of the player when the player connects.

**Comment by Trojaner** [comment]
Hacked clients could easily spoof this (e.g. by sending a different HWID), but it might be still useful to ban normal players permanently.

**Comment by pastet0422** [comment]
HWID changer can bypass this, maybe ?

**Comment by Johnanater** [comment]
It'll just be like banning an IP, it'll work on most people, but others will know how to get around it.

**Comment by SDGNelson** [comment]
In agreement with others here, that this would be too easily bypassed to be worth implementing.

**Comment by RoyIL** [comment]
Nope, you can change your IP by just resetting your router if you don't have a static IP from your ISP.
However, changing your HWID is much harder. 
Please reopen.

**Comment by RoyIL** [comment]
We're also not talking about hacked clients only, but also people that violate the server rules and etc.

**Comment by Eatric** [comment]
I support this idea

**Comment by educatalan02** [comment]
I support too, because It's not easy to change HWID, like your IP is.

**Comment by PandahutMiku** [comment]
Yea this would help track people, nowadays it's very easy to go on a VPN but slightly more advanced to change HWID (even if hacked clients would eventually fake it), it would still be nice for tracking players using alt. accounts.

**Comment by SDGNelson** [comment]
Since there's a lot of support for this, and it's a valid point about tracking non-cheaters, I'll re-open this. Probably won't be in this week's update however.

For my future reference it looks like this will be useful, though not supported on mac or linux. Might just hash steamid for those platforms: https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html

**Comment by Trojaner** [comment]
I am not sure but it looks like deviceUniqueIdentifier is somewhat support on Linux at least.

There was a bug that returned inconsistent values on Linux but it got fixed.
https://issuetracker.unity3d.com/issues/systeminfo-dot-deviceuniqueidentifier-changes-after-pluging-in-flash-drive

**Comment by Greenorine** [comment]
I support this too, really need it.

**Comment by SDGNelson** [comment]
In the next update each player's HWID is available as a 20-byte hash via their PlayerID. onCheckBanStatus in Provider has been marked obsolete, and onCheckBanStatusWithHWID has been added which passes their PlayerID.

Client-side if HWID is not supported then a random value is generated instead. This way plugins don't need to worry about invalid HWIDs.

Leaving open in case there are any questions or issues.

**Comment by Johnanater** [comment]
So there will only be real HWIDs on Windows, or did you manage to get it to work on Linux and Mac?

**Comment by SDGNelson** [comment]
It depends whether SystemInfo.deviceUniqueIdentifier returns unsupportedIdentifier, but as Trojaner mentioned it might work on Mac/Linux and just not be documented.

**Comment by Coopyy** [comment]
neat

**Comment by Greenorine** [comment]
I can't find onCheckBanStatusWithHWID

**Comment by Greenorine** [comment]
Is it clientHash?

**Comment by Pigeon-cmd** [comment]
How would you spot the difference between a random generated HWID due to unsupported platform  and a valid HWID?

**Comment by Greenorine** [comment]
Where Provider.unban function?

**Comment by SDGNelson** [comment]
Right now there's no way to differentiate between valid HWID and unsupported, which was intentional so that plugins don't need to worry about it when banning. The chances of a random HWID matching a valid HWID are 1 in 2^160.
