### ISSUE TITLE
The problem with hacking maps on the server

### ISSUE THREAD

**Issue by karatelg** [SmartlyDressedGames/Unturned-3.x-Community#916]
Can you add a new feature to protect the maps?!
Players from the server without any problems change the location of the NPS on the map, save it and go to the server, thereby undermining the gameplay and the economy of the server. Please make some kind of protection so that you cannot log into the server with the modified card. If it will be like in the folder with the game, or in the folder workshop

**Comment by pastet0422** [comment]
Bad translation ?

**Comment by RoyIL** [comment]
He basically meant that sometimes players edit the maps and add NPCs which causes a "desync" between the server map and the player map. It also works because NPCs are managed on the client side only.

**Comment by pastet0422** [comment]
haha,not bad info,thanks you

**Comment by SDGNelson** [comment]
Are the NPCs in a locked-off / gated area? When dealing with vendors, acknowledging messages and choosing responses the server validates that they are within 20m of the NPC.

**Comment by Johnanater** [comment]
Maybe you could add a verification that they are looking at the NPC?

**Comment by SDGNelson** [comment]
Closing due to no reply, but feel free to respond and I'll re-open.
