### ISSUE TITLE
[FEATURE REQUEST] Custom tips for maps

### ISSUE THREAD

**Issue by danaby2** [SmartlyDressedGames/Unturned-3.x-Community#920]
Whenever you load into the game there's like tips at the bottom of the screen, would it be possible to add custom tips to when a player loads into a custom map? This could include info such as "sushi is healing item :D" or "items respawn every 3 min :D:DDDDD"

**Comment by SDGNelson** [comment]
Can see this being helpful for lots of maps, will do!
