### ISSUE TITLE
[FEATURE REQUEST] Option for rocket projectiles to do damage

### ISSUE THREAD

**Issue by danaby2** [SmartlyDressedGames/Unturned-3.x-Community#922]
Right now the only damage dealt from rockets is the explosion, would it be possible to add an option to make the projectile do damage to whatever it collides with instead of only the explosion?

**Comment by SDGNelson** [comment]
Projectiles (unlike bullets using the ballistics system) are not deterministic because they use the physics simulation, so I'd be hesitant to give them impact damage, but a good alternative might be to use tracer effects + bullet impact explosion.
