### ISSUE TITLE
Implement steam api appid game version number

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#929]
So I'm trying to build server auto update script using Steam API to check for any updates

When calling `UpToDateCheck` API with `appid 304930` and `version 3.30.3.5`

I get
`{"response":{"success":true,"up_to_date":true,"version_is_listable":true}}`

Which is true but it does it for any number above 1000 for example `version 6969`
`{"response":{"success":true,"up_to_date":true,"version_is_listable":true}}`

And when it fails for example with `version 69`
`{"response":{"success":true,"up_to_date":false,"version_is_listable":false,"required_version":1000,"message":"Sorry: Your client needs updating."}}`

It says `"required_version":1000` which is oddly specific 
Is it even implemented?

If not please implement it in the next update so API could work correctly 
If the version number has to be a number let's say version 3.30.3.5 would be a 33035 and so on

**Comment by Johnanater** [comment]
I currently have one in Batch that you could look at

https://github.com/Johnanater/unturned-auto-updater

**Comment by gegtor** [comment]
> I currently have one in Batch that you could look at
> 
> https://github.com/Johnanater/unturned-auto-updater

Thanks but I use Linux so this is useless for me

**Comment by Johnanater** [comment]
You could still use SteamCMD and the commands that I did. Heck, I even used wget and sed. 😉

**Comment by SDGNelson** [comment]
Thanks for sharing your script Johnanater!
Initially that version number was kept in sync with releases, and is the reason the game follows an x.y.z.w version numbering format, but has the downside that older versions are not listed in the server list. Now all servers are listed, and the client is responsible for filtering versions.
