### ISSUE TITLE
Unturned 3.0 Future

### ISSUE THREAD

**Issue by UFI8** [SmartlyDressedGames/Unturned-3.x-Community#931]
Hello Nelson,

It seems lately there is more and more requests for Unturned 3.0 and you are very focused on II,
It seems II is more then mid-way into development and it would be nice if we got an official plan,
if you were going to just finish all of the things you said you would for Unturned 3.0 and only do critical bug fixes / special requests or dedicate a day/few hours of a day a week to Unturned 3.0.

There seems to just be a lot of feature requests lately and it's unclear when you want us to stop making Feature Requests or intent to "deprecate"  3.0.

I don't mean to sound rude in any of this, apologies if it sounds that way in Translation, but it just seems at this point it would be smart to let us know what your plans are for the support of Unturned 3.0 whilst you are very focused on Unturned II, plus less context switching.

**Comment by SDGNelson** [comment]
When the development time split between the two versions is equal I typically keep the issue count around one page, but recently I've spent a lot more time on 4 pushing toward the Devlog #024 release, and there's been a higher frequency of issues/requests posted.

You mention finishing things I said I would - do you feel that I have unfulfilled promises at the moment? It's important to me that I follow through on anything I said I would do, so that the community can trust any statements I make regarding 3 or 4.

Dedicating a specific amount of time per day would be difficult, but I intend to continue somewhat regular updates for the foreseeable future that support community projects e.g. maps, plugins and adding requested features that would benefit a lot of players.

**Comment by UFI8** [comment]
> You mention finishing things I said I would - do you feel that I have unfulfilled promises at the moment? It's important to me that I follow through on anything I said I would do, so that the community can trust any statements I make regarding 3 or 4.
> 
It's not that, more just wondering when Unturned 3.0 will be "phased out" of being supported, it just feels that Unturned II will be much more superior then 3.0 in every-way and fix a lot of people's complaints already, where 3.0 is just a mess everywhere, from hackers overriding your assembly hash check by just using an unlocker tool after unturned/the dlls are loaded and replacing them with clean ones to being seemingly unable to spawn a fresh zombie and tell clients about it.

It's hard to know if my message is being misconstrued in translation, but basically I'm just asking what your plans are (if any) for fading out 3.0 support.

Thank you for your time

**Comment by Trojaner** [comment]
> It's not that, more just wondering when Unturned 3.0 will be "phased out" of being supported, it just feels that Unturned II will be much more superior then 3.0 in every-way and fix a lot of people's complaints already, where 3.0 is just a mess everywhere, from hackers overriding your assembly hash check by just using an unlocker tool after unturned/the dlls are loaded and replacing them with clean ones  

Everything you have mentioned here has been fixed ages ago

**Comment by UFI8** [comment]
> 
> 
> > It's not that, more just wondering when Unturned 3.0 will be "phased out" of being supported, it just feels that Unturned II will be much more superior then 3.0 in every-way and fix a lot of people's complaints already, where 3.0 is just a mess everywhere, from hackers overriding your assembly hash check by just using an unlocker tool after unturned/the dlls are loaded and replacing them with clean ones
> 
> Everything you have mentioned here has been fixed ages ago

Maybe the zombie thing has, but at least from Nelson's side that on join assembly hash check can still be overrided in the same way.

Regardless, kind of derailed own issue, was just curious on the plans for 3.0 in future, I'll edit to reflect.
