### ISSUE TITLE
PSA: Custom Server IO Handling

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#932]
Considering how many plugin developers frequent this issues board, I figured it makes sense to share here. In the next update the server's default IO handling can be overridden by implementing this interface:

	namespace SDG.Unturned
	{
		public delegate void CommandInputHandler(string input);

		/// <summary>
		/// Interface between the dedicated server command I/O and per-platform console.
		/// </summary>
		public interface ICommandInputOutput
		{
			/// <summary>
			/// Called when this implementation is setup by command window.
			/// </summary>
			void initialize(CommandWindow commandWindow);

			/// <summary>
			/// Called when this implementation is deleted or application quits.
			/// </summary>
			void shutdown(CommandWindow commandWindow);

			/// <summary>
			/// Called each Unity update.
			/// </summary>
			void update();

			/// <summary>
			/// Broadcasts when the enter key is pressed.
			/// </summary>
			event CommandInputHandler inputCommitted;

			/// <summary>
			/// Print white message.
			/// </summary>
			void outputInformation(string information);

			/// <summary>
			/// Print yellow message.
			/// </summary>
			void outputWarning(string warning);

			/// <summary>
			/// Print red message.
			/// </summary>
			void outputError(string error);
		}
	}

Related points from the patch notes:

Hosts can now specify -NoWin32Console on the command line to prevent the Windows server from manually allocating/freeing a console window. 

Separated Windows-specific console input/output from shared console code, and allowed plugins to override IO handling by implementing ICommandInputOutput and calling setIOHandler. When using a custom handler you can specify -NoDefaultConsole on the command line.

**Comment by SDGNelson** [comment]
By default the game has ConsoleInputOutput and WindowsConsoleInputOutput implementations which may serve as useful base classes, but they are optional. They'll probably see a few more adjustments before the update.

**Comment by Johnanater** [comment]
So Linux servers should have a real console now?

**Comment by SDGNelson** [comment]
Mmmmaybe...? We're at least headed in that direction. On Linux the dedicated server will now read commands from standard input, and write to standard output.

I suspect we'll either need a Linux-specific subclass of ConsoleInputOutput to do a bit of initialization and cleanup, or some extra shell commands from whoever starts the process. Trojaner was kind enough to link me to the Rocket implementation which I'd previously thought ran some Linux-specific code, but now that the game explicitly uses standard IO it might be easier.

**Comment by Trojaner** [comment]
Due the way how Unity handles stdin/stdout I do not think that the problem is solveable programatically.
However, one can adjust their start scripts like this: 
`./ServerHelper.sh -logfile 2>&1 | tee Servers/\<server\>/Server.log`

**Comment by QnAisbest** [comment]
@Trojaner and where in the script do you put that

**Comment by Trojaner** [comment]
You don't put it in any script...
You start the server using it.

**Comment by Trojaner** [comment]
An addition to my previous comment:
On some distributions (especially Ubuntu) `export TERM=xterm` is required before starting the server.

**Comment by SDGNelson** [comment]
Missed expanding on Trojaner's comment: the vanilla ServerHelper.so script also sets TERM=xterm as well in the .1 patch last week.

Closing this news now, however the vanilla implementation will see some more work (-ThreadedConsole), and if you make a custom implementation I'd love to hear about it!
