### ISSUE TITLE
Close Storage RPC

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#937]
Just a simple RPC to tell the client whatever storage they're in is now closed

Thanks for your time!

**Comment by SDGNelson** [comment]
It looks like calling PlayerInventory.closeStorage and then PlayerInventory.sendStorage should achieve that, though I will tidy up a bit of the related code which is directly modifying those variables.

**Comment by SDGNelson** [comment]
Let me know if that doesn't sort it. For the next update I added closeStorageAndNotifyClient which just calls those two, and is used by crate when destroyed.

**Comment by PandahutMiku** [comment]
Hi Nelson,

Sorry for the late reply, this works perfectly! Thank you for your quick response.

Have a great birthday
