### ISSUE TITLE
Say command doesn't work with colors and spaces

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#939]
The say command seems to be borked with spaces and colors.
`say Hello/255/255/255`
Will announce "Hello" in chat perfectly fine
`say "Hello there"`
Works fine
`say "Hello there"/255/255/255`
Will error with
`Failed to find parameters in format [Text]/[R]/[G]/[B].`

**Comment by Kenzim** [comment]
The first slash not needed, the speech marks act as the delimiters.
Say "hi bros"255/255/255

**Comment by Johnanater** [comment]
Well then, thanks!

Closing
