### ISSUE TITLE
Train Not Breaking Everything

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#94]
Shutters, double doors, and mannequins don't break when hit by the train. (Although, the whole double door thing is kinda cool since trains can fit through them when opened.)

(That aside, racecars and makeshift cars don't have trunk space. Was thinking this may have been intentional, but mentioning it anyways.)

**Comment by SDGNelson** [comment]
Yes: racecar and makeshift missing trunk space is intentional.

Will fix ramming those!
