### ISSUE TITLE
WrongFieldWithGroup

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#942]
Ever since today's update, I have been receiving this error, 1055:WrongFieldWithGroup , in the console and all of the players disconnect. I have tried rebooting my servers and testing all of my configs and nothing seems to be wrong. Does anyone have any knowledge on how to fix this issue?

**Comment by SDGNelson** [comment]
Nothing in the game's code has any messages like that, so it's probably a plugin.

I'm fairly confident that all code changes were kept backwards compatible in this update (e.g. marking Obsolete), so I'm curious what it could be.

**Comment by educatalan02** [comment]
That's related to PlayerInfoLib plugin. @Ascivv1

**Comment by Ascivv1** [comment]
I don’t have PlayerInfoLib on my server anymore. Also I found the issue, my MySQL stats plugin wasn’t working right.
