### ISSUE TITLE
Add static group setting 

### ISSUE THREAD

**Issue by Gsechs** [SmartlyDressedGames/Unturned-3.x-Community#945]
It would be great if there was an option that allowed owner/administrators of in-game groups to manage members that are offline.
My servers for example put a limit on how many players can be in one of these, and sometimes the owner wants to kick an inactive member, but they cannot because the player must be online to be kicked, and ditching for a new group creates issues with owner structures. 

I’m aware players can use a Steam Group to bypass this issue, but this would be a good QOL addition in my opinion for players.

**Comment by SDGNelson** [comment]
Definitely agree that it would be useful, but limited by a variety of factors in 3. For example server does not actually track the offline members of groups, so it can't even be done by plugins right now. It's unlikely that all the necessary refactoring will be done any time soon, but I plan to have much more robust grouping features in 4 off the bat.
