### ISSUE TITLE
ZombieTool GiveZombie

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#947]
Do you mind finishing this? It seems that when used in the game, nothing happens.

That would be very valuable.

Hello from Russia!

**Comment by SDGNelson** [comment]
It looks like that function and the corresponding ZombieManager.spawnZombie were disabled quite a while ago, related to zombie pooling. It should be relatively straightforward to spawn a zombie however: find one in your desired navigation bound that is dead, and then call sendRevive on the zombie.
