### ISSUE TITLE
Proper Minecraft-like Server Forwarding

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#948]
Hello,

It would be great if we had the correct redirection from the Unturned server, I understand why you may want to give players a screen to join or not, but this greatly limits our capabilities.

After all, one way or another, because people have bypassed all your limitations (at least the server browser), someone can create a forwarding server, such as Minecraft's Bungee, and defeat it. It seems silly and severely limits us. Maybe a pop-up window appears saying “Do you want {IP / server name} to redirect you?”, And save this value for the future.

**Comment by Bradler26** [comment]
I believe you are looking for #637

**Comment by Trojaner** [comment]
This is a duplicate as Brad mentioned. The required changes would be too big if possible at all.

**Comment by FlightInstructor-svg** [comment]
Hello,

I understand the concerns about bad actors abusing such a thing, but it is kind of ridicilious when such things are already bypassed. Server owners already hide workshop information on the server list, players join and the server might send them 90000 workshop items to download via that way.

It just seems that this is very limiting on creativity and options just because worry over bad actors.

Just disable workshop downloading on server forwarding or warn the player about it, or realize that such a threat already exists with the current system.

Ultimately, if need be, all of this can be bypassed by just proxying requests like Minecraft's Bungeecord, which is a complicated thing which is why I asked for a much simpler resolution first.

**Comment by Trojaner** [comment]
Something like Bungeecord (as third party software) is not possible at all since networking is handled by Steamworks.

**Comment by FlightInstructor-svg** [comment]
> Something like Bungeecord (as third party software) is not possible at all since networking is handled by Steamworks.


Despite,
I just ask for a simple chance to make plugins automatically connect players. There is no new risk - the servers can already hide information such as 9 trillion workshop mods that you can see on the screen using AviLobbyMess or CopiedLobbyMess, or the Harmony patch for the receiveServer method in Provider to change the answer to the workshop packet request to send 9 trillion workshop identifiers to the client, and none of them is displayed on the real screen.

It just seems like blocking creativity over things fear of downloading workshop things (which is already bypassed a million times over).

I understand this is a bit more work and a bit more of a threat, but it's such a small increase it seems silly to block all of the possibilities.

**Comment by Trojaner** [comment]
Again.
You are talking about something else.
Read my reply again.

**Comment by UFI8** [comment]
> 
> 
> Again.
> You are talking about something else.
> Read my reply again.
> BungeeCord doesn't redirect players, it is a proxy. The player is always connected to the same IP and never makes a new connection.
Sorry for misunderstanding,

In general, I mean simply the ability to redirect players to servers without having to accept them or anything else.

I thought the bungeecord method was a good option for an incase this is not added, just a side idea. Not important.

**Comment by SDGNelson** [comment]
I am hesitant to change this, but it is true that servers already lie on the server list.
I'll open two separate issues, one for disconnecting from servers that lie about workshop content, and another for in-game redirect to new server without menu prompt.

For future readers: currently menu workshop list query is separated from the P2P workshop connection, so they provide the real list during connection and fake list on the menu.
