### ISSUE TITLE
The position of the camera in transport from a third party

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#95]
I would like to ask that in the transport it was possible to adjust the position of the camera in the third person. The problem is that large (boats, yachts, etc.) interfere with sail, visibility. It would be great if you could adjust the camera poses from a third party.
![image](https://user-images.githubusercontent.com/32962870/32978504-b3d3a01e-cc86-11e7-897f-2b0dff3cb232.png)
Still it would be healthy, add animations for each action (forward, backward, left, right). Ie if the car moved you could connect the animation. Such opportunities will make the horse

**Comment by VitaxaRusModding** [comment]
I can completely translate the game in Russian, for official release. Completely free.

**Comment by SDGNelson** [comment]
I've added the ability to set the camera focus with a "Camera_Center" child transform in the next update.
