### ISSUE TITLE
[FEATURE REQUEST] New slot option for weapons

### ISSUE THREAD

**Issue by danaby2** [SmartlyDressedGames/Unturned-3.x-Community#955]
Right now there is "Slot Primary" that limits weapons to the primary slot and "Slot Secondary" that limits weapons to the primary or secondary slot. The new option would allow weapons/items to be equipped in the primary/secondary slot or left in the inventory and bound to [3-9] number keys. I want to add this to my secondary firearms so that multiple can be equipped at once. (Right now, removing the "Slot" line completely allows weapons to be equipped in [3-9] but not in primary/secondary which will be confuzzling for newer players)

**Comment by SDGNelson** [comment]
Interestingly there's some old old old code aroundabouts for "tertiary" weapon slots...
