### ISSUE TITLE
Thread command IO implementation

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#957]
Essentially official integration of this:
https://github.com/RocketMod/Rocket.Unturned/blob/legacy/Rocket.Unturned/UnturnedConsole.cs#L64

**Comment by Trojaner** [comment]
One problem here could be that it could conflict with what Rocket does already.
A way to ensure it won't happen is to check if the file at `Dedicator.serverID + ".console"` exists. If it does, you should maybe not handle input since RocketMod Linux is installed and will do that already. Alternatively you could add another option like -NoInputHandling or something like that.

**Comment by SDGNelson** [comment]
Maybe to start with I'll have a command-line option to opt-in to that, and then the rocketmod implementation is not needed, and then we can have a command-line option to opt-out.

**Comment by SDGNelson** [comment]
Also so I don't forget: rather than directly passing as input there should be a ConcurrentQueue between the Console.ReadLine thread and the unity update which passes to event.

**Comment by SDGNelson** [comment]
Update: In .1 the input portion can be enabled with -ThreadedConsole. It works in vanilla on linux, but not on windows.

When using the -logfile 2&>1 redirect on linux both the unity output and console output are shown, but neither input nor output are captured on windows. I think next up it's just a matter of sorting out which combination of Console SetOut / SetError are needed on each platform, but that will have to wait until the next update.

Since standard error is shown in the terminal on linux there might also be some promise in finding a console command to enable standard output display.

**Comment by Ascivv1** [comment]
What does ThreadedConsole do?

**Comment by SDGNelson** [comment]
@Ascivv1: It's the (future) replacement for the default console because it does not block the game thread.

Update: In the .2 patch I've done some more work on this, and it seems to work nicely on Windows at least. To work around a few issues I decided to only call ReadLine if KeyAvailable so output pauses while typing, but I suspect we'll need a different approach on Linux. Console output also now goes through a proxy TextWriter which writes to standard output and the default output.

Here's the current threaded console loop:

	ConsoleColor restoreColor = Console.ForegroundColor;

	PendingOutput output;
	while(pendingOutputs.TryDequeue(out output))
	{
		Console.ForegroundColor = output.color;
		Console.WriteLine(output.value);
	}

	Console.ForegroundColor = restoreColor;

	if(Console.KeyAvailable)
	{
		string input = Console.ReadLine();
		if(string.IsNullOrWhiteSpace(input) == false)
		{
			pendingInputs.Enqueue(input);
		}
	}

**Comment by AustinCZ** [comment]
Is the ThreadedConsole supposed to currently work in linux ? Without -ThreadedConsole it looks like the server is working fine, only without console. But when i enable -ThreadedConsole, the console itself seems to work, but it just eats enormously CPU. SSH starts using almost 100% cpu and 4 kworker processes (one for each core) starts using 10-20%, the server itself even after 10 minutes still uses around 150-200% cpu. Its doing something strange with stdin/out.
OS: Ubuntu 18.04

```
27047 27581     20   0 4511880 1.170g  56228 S 143.5  3.7   6:43.18 ./Unturned_Headless.x86_64 -ThreadedConsole -port 27581 -logfile test.log -batchmode -nographics +secureserver/27581
22827 root      20   0  109312   8308   6260 R  85.7  0.0   3:46.96 sshd: root@pts/7
13710 root      20   0       0      0      0 I  18.9  0.0   1:13.37 [kworker/u16:2-e]
20577 root      20   0       0      0      0 I  15.6  0.0   2:46.56 [kworker/u16:0-e]
 3879 root      20   0       0      0      0 I  10.6  0.0   3:29.15 [kworker/u16:1-e]
26205 root      20   0       0      0      0 R   6.3  0.0   0:29.60 [kworker/u16:5-e]
```

**Comment by SDGNelson** [comment]
Thanks for the report Austin! The spam of light gray must be from saving and restoring the console color repeatedly, and the ridiculous CPU usage from not sleeping the thread. I'll make a few related changes:
- Only restore color if there are outputs to write.
- Sleep on the console thread.
- Command-line option to use ReadLine rather than checking if KeyAvailable.

I'm curious what you mean by something strange with stdin/out? You're right that the game is manipulating them: during console initialization it calls OpenStandardInput and sets that as the console's input stream, and OpenStandardOutput to create a proxy text writer that writes to standard output as well as whatever the console was originally writing to.

For experimentation there are two more command-line options that affect those: -NoRedirectConsoleInput and -NoRedirectConsoleOutput. On Windows I found that both were required, but so far I couldn't find a way to write to the terminal on Linux without using the -logfile output redirection.

**Comment by AustinCZ** [comment]
Ok thanks. So much developers lately do not care about adding proper console to linux game servers, so i am really glad for your effort :)
Is there a proper way to shutdown the server without console input until the console is fixed ? kill -SIGINT or something ?
> I'm curious what you mean by something strange with stdin/out?
Forget that, i was just confused at first when i did not know why it was doing what it was doing :)

**Comment by SDGNelson** [comment]
For shutdown it should still be accepting input even if there are some issues with the output, or do you have to maintain a connection the whole time it is up? Alternatively rocketmod also redirects standard input as console commands.

**Comment by Trojaner** [comment]
It would definitly make more sense to use Console.ReadLine as it blocks the thread until input is available. If you use KeyAvailable with while true instead, it will take up the whole CPU as AustinCZ mentioned.

**Comment by SDGNelson** [comment]
The reason to only ReadLine when KeyAvailable is so that the WriteLines are processed when you're not typing. At least on Windows doing them at the same time doesn't work because the WriteLines are prefixed by the current input.

**Comment by SDGNelson** [comment]
Those issues should be fixed as of today's .1 patch, and for comparison -ConsoleAlwaysReadLine was added temporarily.

**Comment by SDGNelson** [comment]
-ThreadedConsole is the default in the next update, however the existing console will be available with the -LegacyConsole argument.
