### ISSUE TITLE
Please tell me what caused this error when loading mods?

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#958]
![Screenshot_10](https://user-images.githubusercontent.com/48184311/62004427-a74d0c80-b12d-11e9-95b8-4c85ea625306.png)

Please tell me what caused this error when loading mods?

**Comment by RoyIL** [comment]
One of your plugins, im pretty sure.

**Comment by SDGNelson** [comment]
Typically means a plugin needs to be re-complied, but that method still exists so I'm not sure why it would be failing unless there's an extension method in another plugin.
