### ISSUE TITLE
 Can you make the event for player update skills

### ISSUE THREAD

**Issue by EveryWhere1337** [SmartlyDressedGames/Unturned-3.x-Community#959]

**Comment by EveryWhere1337** [comment]
> _No description provided._

**Comment by Eatric** [comment]
PlayerSkills.onSkillsUpdated ...

**Comment by EveryWhere1337** [comment]
not static

**Comment by Eatric** [comment]
shouldn`t be static

**Comment by Charterino** [comment]
Even if you want this event to be static, you can create a new one and implement anything you want.

**Comment by Trojaner** [comment]
Step 1.
Listen for player join

Step 2.
Listen for player.skills.onSkillsUpdated

Step 3.
???

Step 4.
Profit!

**Comment by RoyIL** [comment]
@Trojaner wOw U hAcKer

**Comment by EveryWhere1337** [comment]
@Trojaner thx

**Comment by Eatric** [comment]
@EveryWhere1337 Close issue then
