### ISSUE TITLE
Config Option for Enabling Damage between Group Members

### ISSUE THREAD

**Issue by Pigeon-cmd** [SmartlyDressedGames/Unturned-3.x-Community#962]

**Comment by PandahutMiku** [comment]
This would be nice for realistic servers

**Comment by SDGNelson** [comment]
Sort of a "Friendly Fire" option. Will do, but not for the Friday update yet because this will require expanding the client-replicated config.

**Comment by SDGNelson** [comment]
Implemented in the coming update, as well as an onPlayerAllowedToDamagePlayer event for overriding the default.
