### ISSUE TITLE
[REQUEST] New events onItemUsing & onItemUsed

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#963]
In PlayerEquipment contains a method "use".
I'm asking Nelson to add onItemUsing(pre) & onItemUsed(post) events in those method.

**Comment by Eatric** [comment]
Are u seriously? Use Harmony. Allow Nelson to do Unturned 2

**Comment by SDGNelson** [comment]
Which used items do you have in mind? I think it would make most sense for Consumeable which recently got events for using on other players, but not yourself.

**Comment by SDGNelson** [comment]
> Are u seriously? Use Harmony. Allow Nelson to do Unturned 2

Thanks. 😉 Especially the past few months I've been trying to help add events to the vanilla game to reduce the usage of Harmony, as it will help reduce trouble with updates / conflict between plugins / breaking the base game.

**Comment by Eatric** [comment]
@SDGNelson Then, maybe you give access of source code for Trojaner, for example, I think he can do it and trustworthy. The fact that you jump from game to game is not very good.

**Comment by pastet0422** [comment]
Why i ALWAYS should use Harmony, for Nelson add new events isn't hard.
And I don't want of your comments.

**Comment by Eatric** [comment]
@pastet0422 I don't want yours issues. It doesn't change anything. You should do it because it is useless suggestions, you have best practices, but you want to go github and touch Nelson, when you can just write two code lines.

**Comment by pastet0422** [comment]
Its not for me,its help for all,many of Plugin-Makers dont know what is the Harmony. Harmony can't solve all our problems, just think about this. Events can be useful for many of people, not for one person

**Comment by Eatric** [comment]
But no one of them ask this. I did not say that it solves all problems, but it solves a problem with events. If you don't want to study, that only your problem, don't be so lazy

**Comment by pastet0422** [comment]
> can just write two code lines.

Creating event =
3 Lines - delegate, event, event call

**Comment by Eatric** [comment]
@pastet0422 3 lines for Nelson, which develop a new game and 2 lines for you, which instead of doing this, asks Nelson to do it for him

**Comment by pastet0422** [comment]
> If you don't want to study, that only your problem, don't be so lazy

I'm study every day, but you talking only about Harmony, in every my event request you write "Harmony blah-blah-blah".

**Comment by pastet0422** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/890#issuecomment-506945996

**Comment by Eatric** [comment]
Because you ask only events, which can easily done by Harmony. You waste  Nelson time

**Comment by pastet0422** [comment]
ok, if you thinks this don't helpful - i will close issue

**Comment by RoyIL** [comment]
Lmao, the people that don't know how to use harmony (even thought the documentation is online) are not "plugin makers" / developers.
You ask Nelson to add stuff that you're just too lazy to learn.
