### ISSUE TITLE
Workshop content dishonesty disconnect

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#965]
If connecting through the server info screen and the download list does not match advertised list, disconnect.

**Comment by Kenzim** [comment]
if you do this, can you make the default option for workshop in the browser 'any workshop'?

**Comment by ferrazf** [comment]
I support Kenzim's idea. I think there is no need to spotlight the Vanilla servers and tuck away the Workshop ones at this stage in Unturned 3's dev lifecycle. There is a vast amount of awesome and interesting modded content available for the game. People rarely get a chance to be exposed to them and the only popular modded servers are the ones that lie about their mods. I think it would be beneficial to give the Unturned community a little more freedom in this respect. A wider variety of server flavours to pick from could help to maintain a healthy level interest in the game while we wait for Unturned II.

**Comment by SDGNelson** [comment]
I double-checked because it looked like the default was changed in December 2018, however it turns out it was only changed for players who had run the game. Entirely new players still had it disabled by default. In the next update advertising mismatches will disconnect, and all players have "any workshop usage" as the default.
