### ISSUE TITLE
unable to download workshop error causing crash

### ISSUE THREAD

**Issue by Kenzim** [SmartlyDressedGames/Unturned-3.x-Community#969]
using the downloadids.json to install workshop, getting

FormatException: Input string was not in a correct format. - System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Number.ParseUInt32 (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <cfc149f8218b496788d8493c87de777a>:0)
System.UInt32.Parse (System.String s) (at <cfc149f8218b496788d8493c87de777a>:0)
SDG.Unturned.Parser.getUInt32FromIP (System.String ip) (at <9ec65a403abd40a9ab1a61c389703b09>:0)

perhaps some whitespace is getting into the ip? looking at some older decompiled versons of unturned, looks like the method is working ok, but whitespace can break that method. perhaps trim the ip first?

**Comment by SDGNelson** [comment]
I suspect this is happening when parsing download restrictions, will fix.
