### ISSUE TITLE
More events for stuff in general!

### ISSUE THREAD

**Issue by Edsparr** [SmartlyDressedGames/Unturned-3.x-Community#97]
Many of the  current events isn't that "trackebale" fif you want to find something for example when you craft something an event exist for that but it never tells what item got crafted ref bool cancel maybe? etc
Some event ideas!

Structuremanager - OnStructureDamaged(CSteamID damager, ushort previoushealth, Transform damaged, ref bool cancel)

Barricademanager - OnBarricadeDamaged(CSteamID damager, ushort previoushealth, Transform damaged, ref bool cancel)

Resourcemanager = OnResourceDamaged(CSteamID damager, ushort previoushealth, Transform damaged, ref bool cancel)

I hope you can make these events! It would be very useful for us plugin makers.

**Comment by xdlewisdx** [comment]
Any and every SteamCall can be tracked. Have a look at AdvancedLogger on my profile to see how SteamChannel.onTriggerSend works. Close

**Comment by Edsparr** [comment]
omfg really? I never realised they could thanks lewis <3
