### ISSUE TITLE
Curated Maps

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#970]
It seems the curated map system has been impaired by this update. I understand that making it workshop-based makes it easier for the map creators to update their maps, helps transition out of curated them, etc. However, it takes away from some of the core perks of curated maps. 

Servers running these maps will now only appear under the "Workshop" filter in the server browser by default, despite the map being curated and thus assumed to be a part of the game. This is a immensely detrimental, as it obscures the map into a dark corner of the server browser, putting a damper on the number of players likely to find servers running these maps, which in turn discourages servers owners from running these maps. 

Another benefit of the old curated map system was that the entire game got access to the new weapons, items, and other assets across all official maps as well. These assets could be used by servers and map creators too, even if for a limited time.

It seems the curated map system has morphed into a workshop map spotlight rather than its implied meaning and purpose.

**Comment by SDGNelson** [comment]
Fair points. After #965 I'll change "any workshop" to be the default to give servers running the maps more visibility, and I'll also change how the map filter works. 

In regards to using assets from the map my intention was that they can add Rio as a dependency on the workshop for it to be auto-downloaded, or when there are curated maps do you add them to the vanilla maps?

**Comment by Johnanater** [comment]
Same, I was considering hosting one on Rio, until I noticed that not many players will even see it.

**Comment by PandahutMiku** [comment]
It's just not worth it to add Rio as a workshop dependency on every server, it was nice to get "new content" on every vanilla server with each curated map's new guns and items, but I understand to you that's probably not worth it. Regardless, Thank you for acknowledging the issue and making these curated maps more visible.

**Comment by SDGNelson** [comment]
I double-checked because it looked like the default was changed in December 2018, however it turns out it was only changed for players who had run the game. Entirely new players still had it disabled by default, but it is fixed in the next update.
