### ISSUE TITLE
Player model rendering range is very low with landmarks off

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#971]
Not sure if its a bug or been done for some reason but if I turn off landmarks - player models renders in a very short range (I only see some moving gun)

Edit: seems that its somehow related to clothe LODs. If clothe is not rendered - player model is also not rendered. If player runs without clothes - they are visible on normal distance

**Comment by SDGNelson** [comment]
Landmark toggle only affects large props, player cull distance is fixed at 512 aside from screen size culling. Looks like player skin cull screen size was reset so it's probably related to low lod bias setting, will re-save that.
