### ISSUE TITLE
[Suggestion & ISSUE]. Add option to force delete item after drop 

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#976]
**Hi i will love to see this option in the game , To be able to remove & kill.entity after drop**

_Why It should be implemented in the game_

- Reduce lag after droping items with high poly faces & effects   'Server Side'
- Helps alot of my work and maybe others too 

**My Issue here**
**note in singleplayer if the item does not  have a hitbox or any colider with it the item will fall in the sea but the probleme in multiplayer is when item drop the item will stay even if the hitbox does not exist and will stay there for a longtime. not good for server-side and client too rendering all that effects & faces  i got some issues with it that make the ping or tps go higher then normal 50 - 60  , when the high poly item drop it goes to 160 / 200 ping and even more if there is like 10 or 5 of them in ground** 

**How ? (Fix)**
- Maybe a config in the .dat item file : Like
- _**Force_Delete_Item_After_Drop**_  _true & false_

**Thanks for reading and i'm sorry about my english :3**

**Comment by SDGNelson** [comment]
The server does not instantiate the item prefabs, so there should not be any serverside performance change.
Right now there is an option Should_Drop_On_Death which can be set to false to delete items, but not yet for intentionally dropping. Wouldn't it be confusing for players who click Drop for their item to be deleted? I could see something along the lines of "Can_Manually_Drop"?

**Comment by BREEZEXPVP** [comment]
I like the idea for the manually drop , for my case is , I don't want the players to pass there powers to others by droping the item , And if the Should_Drop_On_Death gonna works like if player is dead and the item stays then yes that will be good for my mod
