### ISSUE TITLE
Unable to connect from steam server browser

### ISSUE THREAD

**Issue by AustinCZ** [SmartlyDressedGames/Unturned-3.x-Community#978]
I am unable to connect to any server directly from steam server browser or from steam favorites.
Its the same for the steam://connect url. The game starts, but it fails to find the server after #10 tries.
According to wireshark, it is trying to query the server prior connecting to it, but it is querying it on the wrong game port instead of the +1 steam query port.

**Comment by joemisfit** [comment]
@AustinCZ Sounds to me like your firewall might be blocking Unturned from accessing the internet? If you don't have a firewall it could be the one on your router. Try adding a program exception and it should work as my firewall used to do the same thing quite awhile ago.

**Comment by Kenzim** [comment]
Happens for me on multiple hosts. If you use the game port to query, doesn't work. Use the steam port and it queries fine, but tries to use it as the game port and the connection fails. Not sure if the game should redirect steam queries on the game port to the steam port, so you can use the game port to query and then connect, or steam needs to make a change

**Comment by AustinCZ** [comment]
I dont think its firewall issue (turning off did not help).
I found out that if you already have Unturned running in menu than connecting from steam works ok and the client is querying the right query port before connecting.
But if Unturned is not running and steam has to launch unturned with the +connect ip:port parameter, than it fails and is trying co query the gameport instead of queryport.
Even if i manually run Unturned with the +connect ip:port parametr and no matter if i enter the gameport or +1 queryport, it will always tries to query on the gameport and fails. (checked via wireshark)

**Comment by educatalan02** [comment]
Kenzi is right,  you should use the query port.

**Comment by SDGNelson** [comment]
This comes up from time to time, but I am confident that it works properly. My usual test is to visit a community site e.g. https://unturned-servers.net/ and click one of the server connect links which start Unturned with the +connect command-line arguments. Just tested this and it worked properly first try.

It was implemented back in 2014 at which point the +connect Steam rich presence integration was essentially undocumented, but I based how Unturned does it on the server browser and checking what other games were sending.
