### ISSUE TITLE
Error spammed on Linux Servers

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#979]
-----------------------------------------------------------------------------------------------------------
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index - System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <cfc149f8218b496788d8493c87de777a>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <cfc149f8218b496788d8493c87de777a>:0)
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <cfc149f8218b496788d8493c87de777a>:0)
SDG.Unturned.VehicleManager.respawnVehicles () (at <4645aeff16914d29aef2ba2a37173597>:0)
SDG.Unturned.VehicleManager.Update () (at <4645aeff16914d29aef2ba2a37173597>:0)
-----------------------------------------------------------------------------------------------------------
(I added the - signs)
This error below is being spammed on my Linux servers:
Does anyone know if there a fix for this?

**Comment by Trojaner** [comment]
This is unrelated to Linux

**Comment by joemisfit** [comment]
@Ascivv1 Are you using any of Sam's plugins by chance (AviRockets)?

**Comment by SDGNelson** [comment]
Subtle change to some of the vehicle code for the snapshot logging that caused that to be called on servers with zero vehicles - if the map has vehicles spawned during startup it shouldn't happen however. Will be fixed in the next update.

**Comment by Ascivv1** [comment]
Awesome, thank you.
