### ISSUE TITLE
When Spanish mode of the machine, they are transparent. The problem is not with mods. Because I was on other hosts all the same. And plus I duputta mode of the machine! HELP TO DECIDE!

### ISSUE THREAD

**Issue by Artemfdfff** [SmartlyDressedGames/Unturned-3.x-Community#982]
When Spanish mode of the machine, they are transparent. The problem is not with mods. Because I was on other hosts all the same. And plus I duputta mode of the machine! HELP TO DECIDE!

**Comment by Gsechs** [comment]
Dilo en esp y lo traducire xddddddd

**Comment by educatalan02** [comment]
What do yo mean with that?
 @Artemfdfff

**Comment by Daniil1288** [comment]
@Gsechs he's not even spanish, just another russian kid on google translate with some conflicting outdated mods I believe.
His original message was something like this:

> When I spawn modded cars in, they're transparent. The problem is not with the mods. Because I was on different hosting providers and it's all the same. And the modded cars are being duped [translator's note: as in duplicated]! HELP ME SOLVE THIS PROBLEM!

Close this issue.

**Comment by Alex-Well** [comment]
@Artemfdfff If the model is not correctly displayed, then updating the mod to the new version of Unity is required.
