### ISSUE TITLE
ERROR DETECTED synchronization between client and server!

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#984]
I used the existing **CollisionEventHook** in my mod, but as it turned out on the server, all events that it activates occur only on the client side of a particular player. However, as practice has shown, **VehicleEventHook** works well on the server for all players. Most likely you forgot to make an **RPC** for this event! I also wanted to ask to add an **RPC** for the standard Button event: **OnClick**

**Comment by SDGNelson** [comment]
CollisionEventHook detects players the same way vehicle bumpers do. While they will detect all players serverside, only the local player is detected clientside. Since they can be added to any gameobject the most robust option would be to use a plugin to manage effects / conditions / etc.

Buttons can be bound using onEffectButtonClicked.

**Comment by Alex-Well** [comment]
@SDGNelson Could you make the **CollisionEventHook** be activated on the client side if another player entered it? I just wanted to use it to activate elements in **GameObject**, but what then is the point if elements are activated only for one player? **VehicleEventHook** fires even if another player has got into the car and activates **GameObject** elements for all players. You can fix this so that the **CollisionEventHook** works the same way, otherwise the meaning of its use is lost?

**Comment by SDGNelson** [comment]
Right now other clients don't have the necessary collision clientside, but I will see what the implications of changing it are.

**Comment by Alex-Well** [comment]
I got an example and proof of the **CollisionEventHook** malfunctioning.
https://www.youtube.com/watch?v=haatX2okrcY
In the first video clip, we see that **GameObject - Fire** is turned on and off only for a player who activates the **OnPlayerEnter** and **OnPlayerExit** events. This makes these events useful ONLY for a single player game.
In the second video fragment, we see that **GameObject - Model_0** should turn on only when the first player comes in thanks to the **OnFirstPlayerEnter** event and turn off if ALL players exit **CollisionEventHook** thanks to the **OnAllPlayersExit** event. However, **CollisionEventHook** works on the client side where only one player can exist! Therefore, the **OnFirstPlayerEnter** and **OnAllPlayersExit** events work similarly to **OnPlayerEnter** and **OnPlayerExit**, which makes them completely useless both in a single game and on the server.
I do not want you to remove CollisionEventHook since it is really a very useful tool, but it needs to be improved.
![0](https://user-images.githubusercontent.com/52251537/62737877-9d82ad80-ba39-11e9-93ab-56e2861f56b6.png)
