### ISSUE TITLE
[Sugg] Attach items each hands & hook

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#986]
Is there a way to attach items to eat hands Right & left

Some thing like this put name for the gameobject

Left_Hook_End

if the item is none duel then it should be only in Right_Hook_End

**Comment by SDGNelson** [comment]
Unlikely to be changed at this point for 3.0, but it has been planned from the start for 4.0 and used for reload / weapon interaction.
