### ISSUE TITLE
Infinite stamina option

### ISSUE THREAD

**Issue by Projoker** [SmartlyDressedGames/Unturned-3.x-Community#987]
I think Infinite stamina option will be useful in Config.json

**Comment by Eatric** [comment]
Funny, I appreciated. But stamina is entirely on the client side. Idea not bad

**Comment by SDGNelson** [comment]
Would make sense to give the server some control over this, will do, but no ETA yet.

**Comment by HanaForward** [comment]
if you want to be Infinite stamina.
you can on PlayObject opdate use tellLife.

**Comment by SDGNelson** [comment]
In the next update I've added ```PlayerLife.serverModifyStamina``` which will handle adjusting it and replicate the change. For the moment this should allow plugins to do anything, and more per-level or config options might be added in the future.
