### ISSUE TITLE
[Feature Request] NPC trade items

### ISSUE THREAD

**Issue by Alekaei** [SmartlyDressedGames/Unturned-3.x-Community#989]
Right now NPC's only trade for xp, which doesnt make much sense since xp is this "fake"/hidden value in the background that shouldnt really be a tradable, however its too late to just all together remove xp from the npc trades. It would make more sense though if NPC's would trade items for items, that way it could promote exploring more to gather certain resources to then trade them for better or rarer resources. I think this would just open up the use cases for NPC's and may even make them more useful

**Comment by SDGNelson** [comment]
Planned sometime Sept-Oct #784
