### ISSUE TITLE
Move while inventory is open

### ISSUE THREAD

**Issue by Vulby** [SmartlyDressedGames/Unturned-3.x-Community#99]
It would be useful in PvP and PvE situations 

That way you can look at your map while driving
Drop items while running
Move items in you inventory

**Comment by SnowEdwin** [comment]
that kind of removes the risk of going into your inventory, though.

**Comment by Vulby** [comment]
How about setting it as a config in the server settings

**Comment by SnowEdwin** [comment]
i'm getting iffy about server settings as some combinations become obscenely popular and it's become very difficult to find configurations that a noticeable portion of the community actually wishes to participate in that are also populated

**Comment by SDGNelson** [comment]
SnowEdwin's correct: disabling movement while in the inventory is intentional at the moment.
