### ISSUE TITLE
Advanced modding, Nelson, please help!)))

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#992]
Hello! I would like to share some of my experiences and ask just one question: How can I activate an infinite number of **GameObjects for** all players on the server?
Imagine that all **GameObjects** are in **Vehicle**. According to the standard, we can make only two activation options: **Headlights** and **Sirens**, however, two options are few. Therefore, we can make a third one - **VehicleEventHook** which will add a third option to activate **GameObjects**, but even this is not enough!
Therefore, I began to look for an alternative and found it in a UI existing in space. Due to the fact that it is possible to create as many buttons as you want with a standard **OnClick** event, I can make as many options as you like for **GameObjects** activation.

![0](https://user-images.githubusercontent.com/52251537/62613868-03c0e080-b913-11e9-9b36-541a50288b5b.png)

I thought I found a way out, but I ran into a new problem: All activations of **GameObjects** activated by clicking occurred on a third-party client and were not visible to other players on the server. Therefore, I found a solution to the problem in the new **ModHook**! They would allow creating any number of **GameObjects** activation options, but unfortunately Nelson did not answer for a long time, and then completely rejected the request, which forced me to continue searching for a solution to the problem.
More recently, it seemed to me that I had solved this problem. I created some analogue of physical data entry based on a combination of a UI button and **CollisionEventHook**.

![1](https://user-images.githubusercontent.com/52251537/62617458-9153fe80-b91a-11e9-8a7e-d1dd9bb76de7.png)

![2](https://user-images.githubusercontent.com/52251537/62617466-95801c00-b91a-11e9-9814-ae50b02c2d02.png)

In theory, it worked like this: Pressing a button triggered an **OnClick** event that occurred on the client side and launched an animation of the movement of the **GameObject** - **Sphere_Player**. This sphere had the **tag: Player** entered the **Trigger Collider** where the **CollisionEventHook** was located. Thus, the **CollisionEventHook** had to activate elements for all players on the server by pressing the UI button, which would allow creating any number of **GameObjects** activation options. (Complex system, but ingenious!)

![3](https://user-images.githubusercontent.com/52251537/62617708-1f2fe980-b91b-11e9-996d-f46a6c4aa4b6.png)

![4](https://user-images.githubusercontent.com/52251537/62617720-25be6100-b91b-11e9-80b0-2de21d8ac848.png)

![5](https://user-images.githubusercontent.com/52251537/62617728-2bb44200-b91b-11e9-875a-16a902afd2ff.png)

However, after testing this system on the server ALL my plans were destroyed, **CollisionEventHook** activated **GameObjects** only on the client side of a specific player. Although VehicleEventHook activates **GameObjects** for all players on the server.
So far I have only three options for solving the problem, and all of them require assistance from Nelson.

1. Add new ModHook (It’s important to make sure that they work for all players on the server, and not just on the client side of a particular player) I talked about them here in more detail #940  and even tried to write the code myself. At least one of them would be enough for me and the closest is **ChatMessageEventHook**, since a similar script has a door on the Russia map, it remains only to add it under ModHook.

2. Fix CollisionEventHook, make it activate **GameObjects** for all players on the server. I don’t know for sure, but for this it seems necessary to create a new **RPC**.

3. The easiest way for modding: To make the standard UI **OnClick** button event activate GameObjects for all players on the server, most likely you also need to create a new **RPC**.

Now I repeat my question: How can I activate an infinite number of GameObjects for all players on the server? Maybe you know a simpler option that would help solve my problem?
I really hope that you will understand and support me, and maybe even be able to help. Because if we have such an opportunity in **Unturned 3.0**, then we will bring modding to a new level! I will prove to you that the ability to create as many options as you want to activate GameObjects will allow you to create things that you can’t even imagine!

**Comment by Bulka148** [comment]
I think Nelson should add an inclusion function

**Comment by Bulka148** [comment]
I think Nelson should add this feature.

**Comment by SDGNelson** [comment]
Even if the CollisionEventHook is triggered clientside by other players, the animation played from clicking the button will still only be played locally and not trigger in multiplayer.

Are you aiming for it to work without any plugins? One potential feature that comes to mind is I could add the ability to invoke UnityEvents from the server, and a generic client->server event which plugins could bind.

For example rather than replicating OnClick, the OnClick UnityEvent would be assigned to a ServerRpcModHook that takes a string parameter, and then the server plugin would listen for when it's invoked. From there the server plugin could call an rpc which invokes a UnityEvent on a ClientRpcModHook to play effects / animations / object activation.

**Comment by Alex-Well** [comment]
> Even if the CollisionEventHook is triggered clientside by other players, the animation played from clicking the button will still only be played locally and not trigger in multiplayer.
> 
> Are you aiming for it to work without any plugins? One potential feature that comes to mind is I could add the ability to invoke UnityEvents from the server, and a generic client->server event which plugins could bind.
> 
> For example rather than replicating OnClick, the OnClick UnityEvent would be assigned to a ServerRpcModHook that takes a string parameter, and then the server plugin would listen for when it's invoked. From there the server plugin could call an rpc which invokes a UnityEvent on a ClientRpcModHook to play effects / animations / object activation.

It sounds very interesting, in this way we can implement the interaction of plugins and mods?

**Comment by Alex-Well** [comment]
I also had questions related to ServerRpcModHook.
1. Will it be presented as a separate ModHook or will it serve as a communication tool for old ones?
2. If plugins will activate GameObject, will this happen within the framework of one prefab? It will just be very bad if GameObject is activated in all prefabs throughout the server and will not have any restrictions.
3. Will this allow me to create many options for activating objects? By string parameter do you mean a variable that will allow you to create as many events as you like? If so, this is awesome!
U menya tak zhe poyavilis' voprosy svyazannyye s ServerRpcModHook.
1. On budet predstavlen kak otdel'nyy ModHook ili posluzhit instrumentom svyazi dlya starykh?
2. Yesli plaginy budut aktivirovat 'GameObject to budet li eto proiskhodit' v ramkakh odnogo prefaba? Prosto budet ochen 'plokho yesli GameObject budut aktivirovat'sya vo vsekh prefabakh po vsemu serveru i ne budet imet' kakogo to ogranicheniya.
3. Pozvolit li eto mozdat 'mnozhestvo variantov aktivatsii ob "yektov? Pod string parameter
I also had questions related to ServerRpcModHook.
1. Will it be presented as a separate ModHook or will it serve as a communication tool for old ones?
2. If plugins will activate GameObject, will this happen within the framework of one prefab? It will just be very bad if GameObject is activated in all prefabs throughout the server and will not have any restrictions.
3. Will this allow me to create many options for activating objects?Will the string parameter be a variable that allows you to create many events with different names? If so, that’s good!

**Comment by SDGNelson** [comment]
Thinking about what would actually be useful / doable with that is not great... but maybe worth maybe doing. Essentially SERVER plugin would listen for strings + who triggered them. Then your in-game button could have a string ID like "my_button_on_door" and server would broadcast that "my_button_on_door" was triggered by Alex-Well. For anything useful we need the object-referencing feature mentioned in #1233

**Comment by SDGNelson** [comment]
Closing for now, but feel free to comment and I'll re-open. I'm really excited to see what you make with the new options in the coming update!
