### ISSUE TITLE
Airdrop disappears from time to time.

### ISSUE THREAD

**Issue by Daniil1288** [SmartlyDressedGames/Unturned-3.x-Community#993]
As seen in this video: [https://www.youtube.com/watch?v=BKBX448rfX8](url)
No plugins modifying the airdrop behaviour were used.

**Comment by SDGNelson** [comment]
When the airdrop hits something it destroys itself on the client, but spawns the interactable version on the server. Did perhaps an airdrop crate appear nearby?

**Comment by Daniil1288** [comment]
Checked to see myself, no airdrop crate appears.

**Comment by Daniil1288** [comment]
Solved, faulty (or rather badly written) plugin was the cause.
